.github/workflows/download-pulumi-cron.yml

The "Install Pulumi via script on macOS" job keeps failing with:
```
Run echo "installed-version=$(pulumi version)" >> "${GITHUB_OUTPUT}"
echo "installed-version=$(pulumi version)" >> "${GITHUB_OUTPUT}"
echo "expected-version=v$(curl -sS https://www.pulumi.com/latest-version)" >>" ${GITHUB_OUTPUT}"
shell: /bin/bash --noprofile --norc -e -o pipefail {0}
/Users/runner/work/_temp/fc2ea067-d0b7-4c2a-8d41-a190f04de3b6.sh: line 2:  /Users/runner/work/_temp/_runner_file_commands/set_output_021331ce-28c1-4ad9-b493-f4d0f88b5042: No such file or directory
```
Looks like it's due to an incorrect placement of a space character, which this change fixes.
Fixes #12384

Fix Download Pulumi Cron workflow

---

pkg/codegen/nodejs/gen_program.go
pkg/codegen/pcl/binder_test.go
pkg/codegen/testing/test/testdata/components-pp/components.pp
pkg/codegen/testing/test/testdata/components-pp/dotnet/ExampleComponent.cs
pkg/codegen/testing/test/testdata/components-pp/dotnet/components.cs
pkg/codegen/testing/test/testdata/components-pp/exampleComponent/main.pp
pkg/codegen/testing/test/testdata/components-pp/nodejs/components.ts
pkg/codegen/testing/test/testdata/components-pp/nodejs/exampleComponent.ts

For nodejs PCL components, the config types were not entirely correct, now they are: `int` -> `number`, `bool` -> `boolean` and `{ [k: string]: Input<T> }` has now been refactored to `Record<string, Input<T>>`
Also added tests coverage for correctly binding types of `ConfigVariable` nodes in PCL components (examples of type `map` and `list`) also added more program bind tests to ensure config types are bound correctly

[pcl/program-gen] Fix nodejs component config types

---

changelog/pending/20230321--programgen-dotnet-go-nodejs-python--implement-description-as-comments-or-docstring-for-config-variables-in-program-gen.yaml
pkg/codegen/dotnet/gen_program.go
pkg/codegen/go/gen_program.go
pkg/codegen/nodejs/gen_program.go
pkg/codegen/pcl/binder.go
pkg/codegen/pcl/binder_nodes.go
pkg/codegen/pcl/config.go
pkg/codegen/pcl/diagnostics.go
pkg/codegen/python/gen_program.go
pkg/codegen/testing/test/testdata/azure-sa-pp/azure-sa.pp
pkg/codegen/testing/test/testdata/azure-sa-pp/dotnet/azure-sa.cs
pkg/codegen/testing/test/testdata/azure-sa-pp/go/azure-sa.go
pkg/codegen/testing/test/testdata/azure-sa-pp/nodejs/azure-sa.ts
pkg/codegen/testing/test/testdata/azure-sa-pp/python/azure-sa.py
pkg/codegen/testing/test/testdata/components-pp/dotnet/ExampleComponent.cs
pkg/codegen/testing/test/testdata/components-pp/exampleComponent/main.pp
pkg/codegen/testing/test/testdata/components-pp/nodejs/exampleComponent.ts

This PR adds support for the `description` field to be provided for `ConfigVariable` PCL nodes. This allows 1:1 mapping from terraform's [Input Variable Documentation](https://developer.hashicorp.com/terraform/language/values/variables#input-variable-documentation)
- For main/root program config variables (all languages): the description becomes a comment above the config declaration
- For component args (dotnet / nodejs) the description becomes a doc string 
> Also adding `nullable` field but not using it in program-gen yet!

[pcl/program-gen] Implement description as comments or docstring for config variables

---

.github/workflows/ci-lint.yml
.golangci.yml
pkg/backend/display/object_diff.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/client/client.go
pkg/cmd/pulumi/org.go
pkg/cmd/pulumi/util.go
pkg/codegen/docs/gen.go
pkg/codegen/hcl2/model/expression.go
pkg/codegen/hcl2/syntax/comments.go
pkg/codegen/nodejs/gen.go
pkg/codegen/python/gen_program_expressions.go
pkg/codegen/report/report.go
pkg/codegen/schema/docs_test.go
pkg/codegen/schema/schema.go
pkg/resource/deploy/plan.go
pkg/resource/deploy/snapshot_test.go
pkg/resource/deploy/state_builder.go
sdk/go/common/resource/plugin/context.go
sdk/go/common/resource/plugin/plugin.go
sdk/go/common/resource/properties_diff.go
sdk/go/common/util/deepcopy/copy.go
sdk/go/common/workspace/creds.go
sdk/go/pulumi-language-go/main.go
sdk/go/pulumi/run_test.go
sdk/nodejs/cmd/pulumi-language-nodejs/main.go
sdk/python/cmd/pulumi-language-python/main.go
sdk/python/python.go
tests/integration/integration_util_test.go

The new release pulls in revive 1.3 which changed its default ruleset.
With the new rule set, here are the failures we see:
```
% cat pkg/lint.txt sdk/lint.txt tests/lint.txt | cut -d: -f4 | sort | uniq -c
39  empty-block
11  if-return
67  redefines-builtin-id
5  superfluous-else
589  unused-parameter
```
This PR upgrades pu/pu to the latest release of golangci-lint,
and either fixes or excludes linters on a case-by-case basis.
Each commit is individually reviewable,
and elaborates on the rationale for disabling linter rules,
but in short:
- unused-parameter: parameter names are useful,
and the benefit we'd get from fixing 500+ instances of this
is questionable
- empty-block: revive has undesirable false positives on this
- redefines-builtin-id: we keep this rule except for 'new',
which …

ci-lint: Upgrade to golangci-lint v1.52

---

changelog/pending/20230322--auto-go-nodejs-python--fix-calling-whoami-against-pre-3-58-clis.yaml
sdk/go/auto/local_workspace.go
sdk/nodejs/automation/localWorkspace.ts
sdk/nodejs/automation/workspace.ts
sdk/python/lib/pulumi/automation/_local_workspace.py
sdk/python/lib/pulumi/automation/_workspace.py
sdk/python/lib/setup.py
sdk/python/lib/test/automation/data/testproj/Pulumi.int_test_983828.yaml
sdk/python/requirements.txt
sdk/python/stubs/semver/__init__.pyi

Fix automation `WhoAmI` calls for old versions of the CLI without "--json" support.

Support WhoAmI in automation api for old CLI versions

---

changelog/pending/20221103--ci--bumps-python-version-in-matrix-to-3-11.yaml
scripts/get-job-matrix.py
sdk/python/cmd/pulumi-language-python-exec
tests/integration/enums/python/__main__.py

chore(ci): bumps python version in matrix to 3.11

---

pkg/backend/filestate/backend.go
pkg/backend/filestate/backend_test.go
pkg/backend/filestate/meta.go
pkg/backend/filestate/meta_test.go

We want the filestate backend to support project-scoped stacks,
but we can't make the change as-is because it would break old states
with new CLIs.
To differentiate between old and new states,
we've decided to introduce the concept of state metadata.
This is a file under the path .pulumi/Pulumi.yaml
that tracks metadata necessary for the filestate backend to operate.
Initially, this contains just one field: `version`,
with the initial value of 0 representing non-project or "legacy mode".
This changes the filestate layout to track such a file,
creating it if it doesn't exist with the default value of 0.
In a future change, we'll introduce "version 1",
which adds support for project-scoped stacks.
If we ever need to make breaking changes to the layout,
the version in this file will help the …

filestate: Track a state metadata file (.pulumi/Pulumi.yaml)

---

changelog/pending/20230322--auto-go--fix-memory-leak-in-stack-up-in-automation-api.yaml
sdk/go/auto/stack.go

This PR adds a deferred close call to a PulumiCtx that previously went unclosed. Because it was unclosed, it consistently leaked a Goroutine.
Fixes https://github.com/pulumi/pulumi/issues/12463
Because memory leaks are hard to test in an automated fashion, I created a sample program to evaluate the fix. This program runs using the Go Automation API.
```golang
package main
import (
"bufio"
"context"
"fmt"
"os"
"runtime"
"github.com/pulumi/pulumi/sdk/v3/go/auto"
"github.com/pulumi/pulumi/sdk/v3/go/auto/optup"
"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)
func main() {
// Print the number of Goroutines when we start.
fmt.Printf("Goroutine Count: %d\n", runtime.NumGoroutine())
deployFunc := func(ctx *pulumi.Context) error {
return nil
}
ctx := context.Background()
projectName := "inlineTest" …
```

Closes PulumiCtx in Go AutoAPI during Up.

---

.github/workflows/on-pr-default.yml
.github/workflows/on-pr.yml

I noticed it can take some time to cut a minor version release because we have to wait for CI four times.
1. PR to bump `.version` to the intended minor version.
2. Once approved and CI is successful, wait for bors.
3. Freeze the version with another change to `.version`, waiting for CI to approve the PR.
4. Once approved, wait for bors to merge it.
This change skips status checks for PRs that only change `.version` while also side-stepping the "required status checks" rule for branch protection. I've tested this out in a personal repo to confirm it won't become a release blocker next week. 
After this PR, we will skip steps 1 and 3, reducing release time by about 52 minutes on average.
Once this is merged, we can double-check this works by making a test PR modifying the `.version` file.

Skip tests on .version changes.

---

changelog/pending/20230323--cli--improve-cli-upgrade-instructions-for-macos.yaml
pkg/cmd/pulumi/pulumi.go

On macOS, the message informing users
that a new version of Pulumi is available
takes the form:
```
warning: A new version of Pulumi is available. To upgrade from version '3.58.0' to '3.59.0', run
$ brew upgrade pulumi
```
If the user has not run `brew update` in a while,
this will not actually perform the upgrade.
Make the command more copy-paste friendly
by also suggesting a `brew update`.

[macOS] cli: Suggest brew update in upgrade message

---

changelog/pending/20230323--sdk--make-default-logger-thread-safe.yaml
sdk/go/common/diag/sink.go
sdk/go/common/diag/sink_test.go

diag.DefaultSink is not safe for concurrent use.
Whether we use it with os.File or with a bytes.Buffer,
both targets do not synchronize their writes,
so this leaves room for interleaving of messages.
Making diag.DefaultSink thread-safe is generally desirable,
but is also a requirement for #12438
so that it can run upgrades concurrently
and print warnings as tasks fail.
This makes the result of DefaultSink thread-safe
by adding a mutex around the targeted stdout and stderr.
Note:
As a special case, when stdout and stderr are the same
we want to use the same mutex for them.
This matches the behavior of [os/exec.Cmd][1]
// If Stdout and Stderr are the same writer, and have a type that can
// be compared with ==, at most one goroutine at a time will call Write.
Stdout io.Writer
Stderr …

go/common: Make DefaultSink thread-safe

---

changelog/pending/20230324--sdk--fix-extraneous-backoff-during-retries.yaml
sdk/go/common/util/retry/until.go
sdk/go/common/util/retry/until_test.go

This extracts the core logic in the retry package into a Retryer struct.
The Retryer struct supports an optional "After" field,
which allows injecting a custom time.After implementation.
With this, we're able to write tests for this package
without actually sleeping (and slowing down the test suite).
The tests exposed two surprising behaviors:
- If the context times out or expires, we correctly return `false`,
but we return a nil error instead of `ctx.Err()`.
I've chosen to not change this at this time
because we don't know what that might break downstream.
- The initial delay is never used. We start with `delay*backoff`.
This was fixed by moving the delay update down
after the first attempt.
The fix is available in its own commit.

sdk/common/retry: Add tests, fix extra backoff

---

changelog/pending/20230327--sdkgen-dotnet--respectschemaversion-now-writes-the-package-version-to-the-csproj-file.yaml
pkg/codegen/dotnet/gen.go
pkg/codegen/dotnet/templates.go
pkg/codegen/testing/test/testdata/simple-enum-schema/dotnet/Pulumi.Plant.csproj
pkg/codegen/testing/test/testdata/simple-resource-schema/dotnet/Pulumi.Example.csproj

This is more in alignment with the other languages where when respectSchemaVersion is set we write the version to the project file (pacakge.json for NodeJS, setup.py for Python) so that no version information has to be set on the build command itself.

Write <Version> to .csproj when respectSchemaVersion is set

---

changelog/pending/20230315--engine--deletedwith-resourceoption-is-now-inherited-from-its-parent-across-sdks.yaml
pkg/resource/deploy/step_generator.go
pkg/resource/deploy/step_generator_test.go

Tracking inheritance of resource options across SDKs is difficult to scale. This PR uses this information to set the `DeletedWith` when it is left unset by the user's program and there is a Parent resource to inherit the value from.
Alternate approach to https://github.com/pulumi/pulumi/pull/12420
Fixes #12158 
Needs follow up on: https://github.com/pulumi/pulumi-hugo/issues/2566

Resources now inherit the `DeletedWith` Resource Option across SDKs

---

pkg/backend/mock.go
pkg/cmd/pulumi/stack_init.go
pkg/cmd/pulumi/stack_init_test.go
pkg/cmd/pulumi/stack_ls_test.go

This refactors the `pulumi stack init` command implementation
in the same vein as #12400 and #11951.
In short, this moves
flags and global dependencies are moved to a stackInitCmd struct,
and the command implementation into a Run method on that struct.
Doing so allows direct testing of the command implementation.
As demonstration, this includes a variant of the
"--teams is not supported" test directly against the command.
This test needed a mock StackReference,
so this PR also adds one to the pkg/backend package.
This PR contains no behavior changes for the 'stack init' command.
However, this does move the default value of the --secrets-provider flag
into the Run method instead of being applied by Cobra.

refactor(cmd/stack init): Turn into a command struct

---

changelog/pending/20230325--sdk--fix-multiplied-retries-when-downloading-plugins.yaml
pkg/resource/deploy/providers/registry_test.go
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_test.go

**The commits in this PR are meant to be reviewed individually.**
---
This PR fixes two issues in the workspace.DownloadToFile retry logic:
- an off-by-one error that caused it to make 6 attempts, not 5
- a double-retry bug downstream, that caused 5 times as many requests
as intended
The net effect of this was that we made 30 attempts to download plugins
instead of the intended 5.
The fix required some amount of refactoring,
and is therefore split into N different commits.
In order, the commits are:
- Add a failing test case that verifies the total number of requests
as well as correct reporting to the `retry` callback
that is used to report progress to users.
- Refactor without changing any logic
so that we can redefine `time.After` later.
- Fix double retry bug.
This brings the number …

sdk/workspace/DownloadToFile: Fix multiplied and off-by-one retries

---

changelog/pending/20230223--auto-go--fixed-missing-path-flag-to-honor-the-cli-behavior.yaml
sdk/go/auto/local_workspace.go
sdk/go/auto/local_workspace_test.go
sdk/go/auto/stack.go
sdk/go/auto/workspace.go

Added the missing --path flag to solve the gap with the CLI and honor the same behavior. Fix #12254
This solves the gap between the CLI and the automation API.
https://github.com/pulumi/pulumi/issues/12254

Added the missing path flag to honor the CLI behavior

---

changelog/pending/20230328--backend-filestate--rename-internal-state-metadata-file-from-pulumi-yaml-to-meta-yaml-to-avoid-confusion.yaml
pkg/backend/filestate/backend.go
pkg/backend/filestate/backend_test.go
pkg/backend/filestate/meta.go
pkg/backend/filestate/meta_test.go

In #12472, we added a .pulumi/Pulumi.yaml file to filestate backends
to hold metadata about the storage layout format.
It has been brought up multiple times that this is a confusing name,
so we're renaming it to meta.yaml.
Backwards compatibility:
Although we've already shipped #12472,
and have started writing Pulumi.yaml files,
we don't currently use it for anything.
Its first use will be in #12437 when we add project-scoped stacks.
Therefore, this change is completely backwards compatible.
We'll end up leaving the extraneous .pulumi/Pulumi.yaml file behind
if the bucket was initialized with Pulumi v3.59.0 or newer,
before this change was released. This is not a high cost.
I don't think we should go back and delete these files;
I'm reluctant for the backend to perform destructive …

filestate: Rename Pulumi.yaml to meta.yaml

---

pkg/codegen/schema/schema.go

Fix inline documentation of valid schema type strings. 
- "bool" is not a valid value
- Re-order to match defined values in switch statement ~80 lines above

Fix documentation of valid schema type strings

---

tests/integration/dynamic/nodejs-error-create/Pulumi.yaml
tests/integration/dynamic/nodejs-error-create/index.ts
tests/integration/dynamic/nodejs-error-create/package.json
tests/integration/integration_nodejs_test.go

Little test to show errors work in dynamic providers, based on reports from Slack that there might be issues with this.

Add test to show errors in dynamic NodeJS providers work

---

changelog/pending/20230330--engine--fix-updating-a-resource-from-a-component-to-custom-resource.yaml
pkg/engine/lifecycletest/pulumi_test.go
pkg/resource/deploy/step_generator.go

Fixes https://github.com/pulumi/pulumi/issues/12550
If we're updating a resource from a component to custom resource (or vice versa) we always mark it as a provider diff and so trigger a replace.

Test and fix component->custom->component lifecycle

---

changelog/pending/20230330--cli-display--fixes-a-bug-in-the-interactive-update-tree-display-where-small-terminals-would-cause-pulumi-to-panic.yaml
pkg/backend/display/tree.go
pkg/backend/display/tree_test.go

This PR fixes 2 panics in the interactive update display code where a small terminal would cause panics when:
- calculation of the displayed rows to yield a negative index
- strings.Repeat() would go negative
Fixes #12545

Fixed panic in display on narrow terminals

---

sdk/go/common/resource/plugin/context.go
sdk/go/common/resource/plugin/context_test.go

This PR fixes a data race `plugin.Context` that was detected by the Go race detector.
```
==================
Read at 0x00c000630430 by goroutine 3223:
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*Context).Request()
/home/kdixler/go/src/github.com/pulumi/pulumi/sdk/go/common/resource/plugin/context.go:116 +0xf1
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*provider).requestContext()
/home/kdixler/go/src/github.com/pulumi/pulumi/sdk/go/common/resource/plugin/provider_plugin.go:300 +0x564
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*provider).Create()
/home/kdixler/go/src/github.com/pulumi/pulumi/sdk/go/common/resource/plugin/provider_plugin.go:898 +0x565
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*CreateStep).Apply() …
```

fix data race in `plugin.Context`

---

changelog/pending/20230128--backend-filestate--the-filestate-backend-now-supports-project-scoped-stacks.yaml
changelog/pending/20230328--backend-filestate--print-a-warning-if-a-project-scoped-storage-has-non-project-stacks-in-it.yaml
pkg/backend/backend.go
pkg/backend/filestate/backend.go
pkg/backend/filestate/backend_legacy_test.go
pkg/backend/filestate/backend_test.go
pkg/backend/filestate/bucket.go
pkg/backend/filestate/lock.go
pkg/backend/filestate/meta.go
pkg/backend/filestate/meta_test.go
pkg/backend/filestate/state.go
pkg/backend/filestate/state_test.go
pkg/backend/filestate/store.go
pkg/backend/filestate/store_test.go
pkg/cmd/pulumi/new_acceptance_test.go
sdk/go/common/env/env.go
tests/config_test.go
tests/integration/integration_test.go
tests/stack_test.go

This re-adds project support back to the filestate backend
by implementing a new referenceStore: projectReferenceStore.
We will use this reference store for all new filestate stores.
Existing states will continue to use the legacyReferenceStore.
To accomplish this, and to plan for the future,
we introduce a 'meta.yaml' file inside the .pulumi directory.
This file contains metadata about the storage state.
Currently, this only holds a version number:
version: 1
Version 1 is the number we've chosen for the initial release
of project support.
If we ever need to make breaking changes to the storage protocol
we can bump the format version.
Notes:
- Stack references produced by filestate will shorten to
just the stack name if the project name for the stack
matches the currently selected …

backend/filestate: Re-add project support

---

changelog/pending/20230316--cli-state--add-upgrade-subcommand-to-upgrade-a-pulumi-self-managed-state-to-use-project-layout.yaml
pkg/backend/filestate/backend.go
pkg/backend/filestate/backend_test.go
pkg/cmd/pulumi/pulumi.go
pkg/cmd/pulumi/state.go
pkg/cmd/pulumi/state_upgrade.go
pkg/cmd/pulumi/state_upgrade_test.go

Adds a new `pulumi state upgrade` command
that will upgrade the state for the current state storage
to the latest version supported by that format *concurrently*.
This is a no-op for httpstate,
but for filestate, this will migrate from unversioned storage
to the project-based versioned format.
It includes a confirmation message, informing users that
the state will be inaccessible from old CLIs after the upgrade.
They must type 'yes' to accept this.
A note on upgrade order:
We attempt to create the new meta.yaml file before moving the stack files.
This prevents us from leaving the bucket in an unreadable state
if we don't have write permission for the meta.yaml.
Extracted from #12134

{cli, filestate}: Add 'state upgrade' command

---

pkg/backend/filestate/backend.go
pkg/backend/filestate/backend_test.go
pkg/backend/filestate/meta.go
pkg/backend/filestate/meta_test.go
pkg/backend/filestate/state.go

This is an alternative take on what #12473 was for.
Specifically, the current filestate.New constructor
makes it tedious to inject optional hooks
to control external state like the environment, time, etc.
This introduces a private constructor:
func newLocalBackend(..., *localBackendOptions) (*localBackendReference, error)
The filestate.New constructor just calls newLocalBackend
with the default options.
The only available option is Getenv: an override for os.Getenv.
We replace all direct uses of os.Getenv with this function reference,
so this allows us to control environment variables in tests
without *actually* changing them with t.Setenv.
That, in turn, allows these tests to run in parallel again.
To further demonstrate the value of doing this,
this change also includes tests for …

refactor(filestate): Don't use t.Setenv in tests

---

pkg/cmd/pulumi/config.go

I think the help text to set a list value needs quotes. Without it, the indexed-accessor causes problems in a shell (macOS Terminal in my case when I ran into the problem.) One can also use double-quotes. I am hoping for this to be reflected in the [docs](https://www.pulumi.com/docs/reference/cli/pulumi_config_set/) page as well.
No user-impacting changes.

Update description of config commands

---

changelog/pending/20230405--programgen-nodejs-python--fixes-the-type-signature-of-pcl-function-entries-to-return-list-of-key-value-pair-objects.yaml
pkg/codegen/nodejs/gen_program_expressions.go
pkg/codegen/pcl/functions.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/entries-function-pp/entries-function.pp
pkg/codegen/testing/test/testdata/entries-function-pp/nodejs/entries-function.ts
pkg/codegen/testing/test/testdata/entries-function-pp/python/entries-function.py

The `entries` function in PCL had a return type of `list(tuple(keyT, valueT))` but program-gen in nodejs and python generates an expression which returns `list(object({ key = keyT, value = valueT }))` as it should. This PR fixes the type signature and adds a test case for it

[pcl] Fixes the type signature of function "entries" to return list of key-value pair objects

---

changelog/pending/20230329--programgen-python--impleneted-python-program-gen-for-pcl-components.yaml
pkg/codegen/dotnet/gen_program.go
pkg/codegen/nodejs/gen_program.go
pkg/codegen/pcl/binder.go
pkg/codegen/pcl/utilities.go
pkg/codegen/python/gen_program.go
pkg/codegen/python/gen_program_expressions.go
pkg/codegen/python/gen_program_quotes.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/components-pp/dotnet/ExampleComponent.cs
pkg/codegen/testing/test/testdata/components-pp/python/components.py
pkg/codegen/testing/test/testdata/components-pp/python/exampleComponent.py
pkg/codegen/testing/test/testdata/components-pp/python/simpleComponent.py

Implements python program-gen for components
Still todo:

[pcl/python] Implemented python program-gen for PCL components

---

changelog/pending/20230320--cli-package--fix-bug-in-package-get-schema-subcommand-caused-it-to-bail-on-certain-providers.yaml
pkg/codegen/schema/schema.go
pkg/codegen/schema/schema_test.go

This commit removes an assertion in schema JSON marshaling that function return types are mutually exclusive with Outputs. This assertion was false; in practice, packages like AWS and DigitalOcean both have functions that provide both ReturnType and Outputs (perhaps inadvisedly). This assertion broke the `package get-schema` subcommand. _e.g._, `pulumi package get-schema aws@5.24.0` or
`pulumi package get-schema digitalocean@4.19.0`. Removing this assertion restored this functionality.
Examples of functions that provide both a ReturnType and Outputs:
* `DigitalOcean.get_account()`
* `DigitalOcean.get_app()`
* `DigitalOcean.get_certificate()`
* `aws.ses.getDomainIdentity()`
Fixes https://github.com/pulumi/pulumi/issues/12457
**Question:** Any tips on how to add a regression test to prevent …

Remove mutually exclusion between ReturnType and Outputs.

---

changelog/pending/20230404--cli-state--fixes-panic-when-renaming-providers-in-pulumi-state-rename.yaml
pkg/cmd/pulumi/state_rename.go
pkg/cmd/pulumi/state_rename_test.go

This PR Propagates renames of provider resources in the `Provider` resource field in the `pulumi state rename <provider> new-name` command.
Fixes #12579

fix `pulumi state rename <provider> new-name`

---

pkg/cmd/pulumi/about.go
pkg/cmd/pulumi/convert.go
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/package.go
pkg/cmd/pulumi/plugin.go
pkg/cmd/pulumi/policy_new.go
pkg/cmd/pulumi/policy_publish.go
pkg/cmd/pulumi/up.go
pkg/engine/deployment.go
pkg/engine/query.go
sdk/go/common/resource/plugin/context.go
sdk/go/common/resource/plugin/host.go
sdk/go/common/resource/plugin/provider_plugin.go
tests/integration/dynamic/nodejs-pulumi-config/Pulumi.yaml
tests/integration/dynamic/nodejs-pulumi-config/index.ts
tests/integration/dynamic/nodejs-pulumi-config/package.json
tests/integration/integration_nodejs_test.go

Some users wish to experiment with merging stack provider config with explicit provider config. It's not clear this is something we want to fully support/expose yet, so this change forwards the stack config to provider binaries via the PULUMI_CONFIG environment variable. 
Users wishing to experiment with this in their providers can grab and JSON decode that variable and do their merging as wanted, without this affecting others users generally.
At some point we may remove this in favor of a better system that makes itself evident from these experiments.

Pass PULUMI_CONFIG through to provider plugins

---

changelog/pending/20230406--yaml--updates-pulumi-yaml-to-v1-1-0.yaml
pkg/go.mod
pkg/go.sum

This PR bumps pulumi-yaml from v1.0.4 to v1.1.0.
Fixes #12611

Bump pulumi-yaml to v1.1.0

---

changelog/pending/20230406--programgen--suppport-the-any-type-in-config-and-outputs.yaml
pkg/codegen/hcl2/model/type_scope.go
pkg/codegen/pcl/binder_test.go

Encountered while doing terraform conversions, the current binder couldn't handle types like `map(any)`.

Support map(any) in config/output types

---

changelog/pending/20230327--sdk-nodejs--fix-hang-due-to-component-children-cycles.yaml
sdk/nodejs/runtime/resource.ts
sdk/nodejs/tests/resource.spec.ts
sdk/nodejs/tests/runtime/langhost/cases/073.component_dependencies/index.js
sdk/nodejs/tests/runtime/langhost/run.spec.ts

When a resource depends on a local component resource, rather than setting the component resource itself as a dependency, each of the component's descendants is added as a dependency. This can lead to hangs when cycles are introduced.
For example, consider the following parent/child hierarchy, where `ComponentA` is the parent of `ComponentB` and `ComponentB` is the parent of `CustomC`:
```
ComponentA
|
ComponentB
|
CustomC
```
If `ComponentB` specifies it has a dependency on `ComponentA`, the following takes place as part determining the full set of transitive dependencies:
1. `ComponentA`  is a component resource so it isn't added as a dependency, its children are.
2. `ComponentA` has one child: `ComponentB`
3. `ComponentB`  is a component resource so it isn't added as a dependency, its …

[sdk/nodejs] Fix hang due to component children cycles

---

changelog/pending/20230327--sdk-go--fix-hang-due-to-component-children-cycles.yaml
sdk/go/pulumi/context.go
sdk/go/pulumi/resource.go
sdk/go/pulumi/resource_test.go
sdk/go/pulumi/rpc.go

When a resource depends on a local component resource, rather than setting the component resource itself as a dependency, each of the component's descendants is added as a dependency. This can lead to hangs when cycles are introduced.
For example, consider the following parent/child hierarchy, where `ComponentA` is the parent of `ComponentB` and `ComponentB` is the parent of `CustomC`:
```
ComponentA
|
ComponentB
|
CustomC
```
If `ComponentB` specifies it has a dependency on `ComponentA`, the following takes place as part determining the full set of transitive dependencies:
1. `ComponentA`  is a component resource so it isn't added as a dependency, its children are.
2. `ComponentA` has one child: `ComponentB`
3. `ComponentB`  is a component resource so it isn't added as a dependency, its …

[sdk/go] Fix hang due to component children cycles

---

changelog/pending/20230327--sdk-python--fix-hang-due-to-component-children-cycles.yaml
sdk/python/lib/pulumi/runtime/resource.py
sdk/python/lib/test/langhost/component_dependencies/__main__.py
sdk/python/lib/test/langhost/component_dependencies/test_component_dependencies.py
sdk/python/lib/test/test_resource.py

When a resource depends on a local component resource, rather than setting the component resource itself as a dependency, each of the component's descendants is added as a dependency. This can lead to hangs when cycles are introduced.
For example, consider the following parent/child hierarchy, where `ComponentA` is the parent of `ComponentB` and `ComponentB` is the parent of `CustomC`:
```
ComponentA
|
ComponentB
|
CustomC
```
If `ComponentB` specifies it has a dependency on `ComponentA`, the following takes place as part determining the full set of transitive dependencies:
1. `ComponentA`  is a component resource so it isn't added as a dependency, its children are.
2. `ComponentA` has one child: `ComponentB`
3. `ComponentB`  is a component resource so it isn't added as a dependency, its …

[sdk/python] Fix hang due to component children cycles

---

.github/PULL_REQUEST_TEMPLATE.md
pkg/cmd/pulumi/console.go
pkg/cmd/pulumi/login.go
pkg/cmd/pulumi/logout.go
pkg/cmd/pulumi/policy_disable.go
pkg/cmd/pulumi/policy_enable.go
pkg/cmd/pulumi/policy_publish.go
pkg/cmd/pulumi/policy_rm.go
pkg/cmd/pulumi/policy_validate.go
pkg/cmd/pulumi/pulumi.go
pkg/cmd/pulumi/stack_init.go
pkg/cmd/pulumi/stack_init_test.go
pkg/cmd/pulumi/util.go
pkg/cmd/pulumi/util_remote.go

@justinvp i went ahead and did the changes for the cli docs, since it impacts the docs on our website. feel free to close though if you would like someone else to do this changes at another time. also updated the pr template. left all other things alone.
see also
https://github.com/pulumi/registry/pull/2326
https://github.com/pulumi/examples/pull/1412
https://github.com/pulumi/pulumi-hugo/pull/2666

update cli docs service -> clouds

---

sdk/nodejs/yarn.lock

There is a security vulnerability in `json5` which we have a transitive dev dependency on via `nyc`. The change in this commit is the result of running `yarn upgrade nyc`, which transitively upgrades `json5` to v2.2.3 which contains a fix for the vulnerability.
After the change, our `yarn.lock` contains:
```
json5@^1.0.1:
version "1.0.2"
resolved "https://registry.yarnpkg.com/json5/-/json5-1.0.2.tgz#63d98d60f21b313b77c4d6da18bfa69d80e1d593"
integrity sha512-g1MWMLBiz8FKi1e4w0UyVL3w+iJceWAFBAaBnnGKOpNa5f8TLktkbre1+s6oICydWAm+HRUGTmI+//xv2hvXYA==
dependencies:
minimist "^1.2.0"
json5@^2.2.2:
version "2.2.3"
resolved "https://registry.yarnpkg.com/json5/-/json5-2.2.3.tgz#78cd6f1a19bdc12b73db5ad0c61efd66c1e29283"
integrity sha512-XmOWe7eyHYH14cLdVPoyg+GOH3rYX++KpzrylJwSW98t3Nk+U8XOl8FWKOgwtzdb8 …
```

[sdk/nodejs] Upgrade json5

---

sdk/go/pulumi/resource.go

A user expressed confusion about the existence of ResourceOptions and
ResourceOption in Community Slack, because it wasn't clear which to use.
Clarify in the documentation that these are not intended to be passed
to a resource constructor or a provider function,
and are merely snapshots of what you do pass into them.

doc(sdk/go): Clarify purpose of ResourceOptions, InvokeOptions

---

changelog/pending/20230410--backend-filestate--propagate-request-context-to-external-call-sites.yaml
pkg/backend/filestate/backend.go
pkg/backend/filestate/backend_legacy_test.go
pkg/backend/filestate/backend_test.go
pkg/backend/filestate/bucket.go
pkg/backend/filestate/bucket_test.go
pkg/backend/filestate/lock.go
pkg/backend/filestate/snapshot.go
pkg/backend/filestate/state.go
pkg/backend/filestate/store.go
pkg/backend/filestate/store_test.go

The filestate backend implementation drops context in many places
instead opting to use context.TODO.
context.TODO is a TODO--something intended to be addressed.
context.Backgruond is appropriate for process-scoped operations.
In this case, we can resolve the issues and drop all uses of
context.TODO by plumbing the received contexts appropriately.
For localSnapshotPersister, we add a new `ctx` field
because the interface doesn't yet accept a context argument.
This is tracked in #12637.
Result:
```
% rg context.TODO pkg/backend/filestate
[empty]
```
Resolves #12594

pkg/filestate: Plumb context

---

changelog/pending/20230411--cli-config--fix-config-set-all-not-saving-secret-provider-configuration.yaml
pkg/cmd/pulumi/config.go
pkg/cmd/pulumi/crypto.go
pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/logs.go
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/refresh.go
pkg/cmd/pulumi/stack_change_secrets_provider.go
pkg/cmd/pulumi/stack_history.go
pkg/cmd/pulumi/up.go
pkg/cmd/pulumi/util.go
pkg/cmd/pulumi/watch.go
tests/integration/integration_test.go

Clean up some more hidden loading of config files in `getStackEncrypter`/`getStackDecrypter` that could cause the config file to change due to secret provider initialization. Importantly this was missed in `config set-all` where we would load the config file, then later on call `getStackEncrypter` which would initialize the secrets config and save it to disk, but not return that information back up to "set-all" which then overwrote it with the config structure that it had been building. This could result in secret values written to the config file but without saving their salt meaning they could never correctly be decrypted.
Fixes https://github.com/pulumi/pulumi/issues/12632.

Fix config set-all saving secret provider configuration

---

changelog/pending/20230412--cli-display--fix-a-panic-when-diffing-empty-archives.yaml
pkg/backend/display/object_diff.go

Fixes https://github.com/pulumi/pulumi/issues/12655.

Fix panic in archive diff

---

sdk/go/common/workspace/plugins.go

Currently the "GitHub rate limit exceeded, try again in XmYs." errors look pretty bad because it's not clear that we then fallback got get.pulumi.com for our plugins when hitting this error. Adding this log line so it's a bit clearer what's going on when reading log files back.

Log that we're falling back to get.pulumi.com

---

CONTRIBUTING.md

Pulumi supports the same versions of Go as upstream.
Instead of updating the CONTRIBUTING.md with every Go releas,
specify that contributors should install "a supported version",
which will normally be one of the two most recent minor releases.
Resolves #12664

CONTRIBUTING: Require a supported version of Go

---

changelog/pending/20230412--programgen--do-not-panic-when-attribute-type-or-resource-variable-type-isnt-fully-bound.yaml
pkg/codegen/hcl2/model/attribute.go
pkg/codegen/pcl/resource.go

Sometimes during program binding, when an attribute isn't fully bound, its type would be `nil`. Later on when the attribute is used and its type needs to be type-checked, it panics. Here we resort to using `model.DynamicType` when the type isn't known. The same for the `VariableType` of resources.

[pcl] Do not panic when attribute type or resource variable type isn't fully bound

---

changelog/pending/20230405--cli-display--adds-an-indicator-for-resources-that-are-being-deleted-replaced-with-retainondelete-set-as-well-as-an-itemized-warning.yaml
pkg/backend/apply.go
pkg/backend/apply_test.go
pkg/backend/display/progress.go
pkg/backend/display/progress_test.go
pkg/backend/display/rows.go
sdk/go/common/tokens/tokens.go
sdk/go/common/tokens/tokens_test.go

This PR adds a `[retain]` suffix to Replace and Delete operations to indicate that it is leaving a resource behind. It also adds a warning message before preview to indicate how many and which URNs are leaving resources behind.
Preview:
[![asciicast](https://asciinema.org/a/VCiMwPieV5kUA8RzRLBPyiDiL.svg)](https://asciinema.org/a/VCiMwPieV5kUA8RzRLBPyiDiL)
Fixes #12030

Indicate resources being orphaned when `RetainOnDelete` is true

---

pkg/cmd/pulumi/plugin_install.go

@EvanBoyle commented that it wasn't that clear that VERSION was optional in this command.
```
Install one or more plugins.
This command is used manually install plugins required by your program. It may
be run either with a specific KIND, NAME, and optionally VERSION, or by omitting
these and letting Pulumi compute the set of plugins that may be required by the
current project. If specified VERSION cannot be a range: it must be a specific
number. If not specified pulumi will try to look up the latest version of the
plugin, this is not always possible.
If you let Pulumi compute the set to download, it is conservative and may end up
downloading more plugins than is strictly necessary.
Usage:
pulumi plugin install [KIND NAME [VERSION]] [flags]
```

Improve plugin install help text

---

changelog/pending/20230414--programgen-nodejs--linearize-component-resource-nodes.yaml
pkg/codegen/nodejs/gen_program.go

Resource declarations in components were not linear before; some resources refer to other resources declared later on in the program. This fixes the issue

[pcl] Linearize component resource nodes

---

pkg/cmd/pulumi/convert.go
pkg/util/afero/afero.go

This should help with debugging converter problems as we'll be able to easily run the converter to see what PCL its trying to write for codegen even if that's not valid PCL.
This require's double-binding of tfEject/yamlEject but that shouldn't change correctness and both of those should be changed to converter plugins that just write PCL at some point soon anyway.

Allow convert from plugin to pcl to write PCL even if binding fails

---

changelog/pending/20230407--pkg--bump-pulumi-terraform-bridge.yaml
pkg/go.mod
pkg/go.sum
tests/go.mod
tests/go.sum

Updates pulumi-terraform-bridge to pull in https://github.com/pulumi/pulumi-terraform-bridge/pull/859, which resolves an issue where we could fail to build:
```
github.com/pulumi/pulumi-terraform-bridge/v3@v3.34.1-0.20221214173921-8e65b1f9fdd5 requires
github.com/pulumi/pulumi-java/pkg@v0.6.0 requires
github.com/pulumi/pulumi/pkg/v3@v3.36.1-0.20220725155140-d69eea638451 requires
github.com/pulumi/pulumi-java/pkg@v0.5.0 requires
github.com/pulumi/pulumi/pkg/v3@v3.35.4-0.20220707201547-515cf6191cb9 requires
github.com/pulumi/pulumi/sdk/v3@v3.35.4-0.20220706194433-bf578c5d4a27: invalid version: unknown revision bf578c5d4a27
```

[pkg] Bump pulumi-terraform-bridge

---

pkg/util/afero/afero.go

Can't write a file if the parent directory isn't first created.
Annoyingly we would have probably missed this in tests using MemFs anyway because it doesn't follow that rule.

Fix convert pcl copy

---

changelog/pending/20230414--pkg-testing--deploytest-fix-custom-timeouts-smaller-than-a-minute-being-ignored.yaml
pkg/resource/deploy/deploytest/resourcemonitor.go
pkg/resource/deploy/deploytest/resourcemonitor_test.go

deploytest.ResourceMonitor currently zeroes out any custom timeout value
smaller than 60 seconds because it does integer division on it.
Further, it alawys uses a non-nil CustomTimeouts
even when the input was nil.
This causes undesirable breaks in unit tests that use this type.
This change fixes both issues in CustomTimeouts. Now:
- The RegisterResourceRequest.CustomTimeouts field is non-nil
only if the input CustomTimeouts was non-nil
- time.Duration and float divison is used to accurately format
the specified duration as a string
Encountered while writing tests for #12154

pkg/deploytest: Don't zero CustomTimeouts < 1 minute

---

.github/workflows/release.yml

Today, when we do a release, we dispatch the `trigger-cron` workflow on the pulumi/templates repo, but this workflow consistently fails on new releases because it installs the Pulumi CLI with pulumi/actions, which [relies on pulumi/docs for its list of available versions](https://github.com/pulumi/actions/blob/e50e616f7d8f4c92d3d22abdd8cfd048e6e672de/src/libs/libs/get-version.ts#L23-L45) (a list that doesn't get updated until much later as part of a different process).  As a result, every new release causes a pulumi/templates workflow failure (and alerts us in the #builds channel):
```
> Run pulumi/actions@v4
Configured range: v3.61.1
Error: Could not find a version that satisfied the version range
```
So this PR removes this step from the release workflow. 
It does seem useful to run new …

Remove the pulumi/templates `trigger-cron` step from the release

---

changelog/pending/20230331--backend-filestate-service--add-more-environment-metadata-to-updateinfo-update-cli-args-environment-variables-pulumi-version-os-architecture.yaml
pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/refresh.go
pkg/cmd/pulumi/up.go
pkg/cmd/pulumi/util.go
pkg/cmd/pulumi/util_test.go
pkg/cmd/pulumi/watch.go

After running an update, it's not necessarily clear what envvars or flags were set. This can make it unclear how an update was performed and can make reproductions of issues more difficult.
As a user, I set aliases to set flags, export PULUMI envvars in my `.zshrc`, and upgrade pulumi and when looking at an updates that ran successfully a month ago on one machine and may not run successfully on my current machine, I'd like to know this context that performed the update to enable better root cause analysis of the error.
To address this, this PR augments the existing Update Metadata to track the:
- CLI flags set (name only)
- `PULUMI_` Environment Variables set (name and truthiness `true` otherwise `set`)
- Version of Pulumi used
- Operating System and CPU Architecture (runtime.GOOS, …

Add more details to `pulumi stack history` to provide more context.

---

changelog/pending/20230414--sdk-go--fixed-newresourceoptions-dropping-mlc-dependencies-from-the-options-snapshot.yaml
sdk/go/pulumi/provider.go
sdk/go/pulumi/provider_test.go
sdk/go/pulumi/resource.go

We recently added a new API, NewResourceOptions to build a preview
of a set of resource options.
func NewResourceOptions(...ResourceOption) (*ResourceOptions, error)
This currently drops the dependencies of an MLC from the snapshot.
The reason for this is that it used a special type "urnSet"
to represent dependencies for MLCs received over the wire.
This decision was made at the time because the original Resource objects
were not available for these dependencies.
Turns out that that limitation isn't a blocker:
we can use newDependencyResource to create dummy Resource objects
that hold nothing but a URN.
This allows NewResourceOptions to work on options even inside an MLC.
Note that this currently only works for some of the options:
those that are propagated from `construct` into the Go …

sdk/go: Don't drop Dependencies in ResourceOptions snapshot for MLCs

---

changelog/pending/20230418--pkg-testing--fix-failure-in-writing-a-package-json-for-test-overrides.yaml
pkg/testing/integration/program.go

The function `writePackageJSON` used by ProgramTest
always returns a non-nil error--even when encode succeded
because it unconditionally wraps the result with an error.

testing/ProgramTest: Don't always fail write package.json

---

sdk/go/pulumi-language-go/main_test.go
sdk/go/pulumi-language-go/testdata/sample/dep/go.mod
sdk/go/pulumi-language-go/testdata/sample/dep/plug.go
sdk/go/pulumi-language-go/testdata/sample/indirect-dep/go.mod
sdk/go/pulumi-language-go/testdata/sample/indirect-dep/indirect.go
sdk/go/pulumi-language-go/testdata/sample/plugin/go.mod
sdk/go/pulumi-language-go/testdata/sample/plugin/plug.go
sdk/go/pulumi-language-go/testdata/sample/plugin/pulumi-plugin.json
sdk/go/pulumi-language-go/testdata/sample/prog/Pulumi.yaml
sdk/go/pulumi-language-go/testdata/sample/prog/go.mod
sdk/go/pulumi-language-go/testdata/sample/prog/main.go

Adds a test that sets up a Go module with a few dependencies
and queries its plugins and dependencies with the Go language host.
This test passes today because we're running in module mode.
A sibling test will be added for vendor mode
to verify the fix for #12526, where this same check would fail
if we vendor the dependencies into the Pulumi program.
NOTE:
The test does not run in parallel because we need to change the
working directory. This is resolved in a follow-up.

test(go/host): GetRequiredPlugins and GetProgramDependencies

---

sdk/go/pulumi-language-go/main.go
sdk/go/pulumi-language-go/main_test.go

Refactors the Go language host to inject CWD into it
instead of always using `os.Getwd`.
This allows the test for plugin and dependency behavior
to run in parallel.
NOTE:
Some of the RPCs methods get a Directory or Pwd in the request
but it wasn't being used before so we were running in the directory
where the host was started.
This retains that behvaior for those methods rather than changing it
because it's not clear whether that omission was intentional.

refactor(go/host): Inject current working directory

---

changelog/pending/20230418--sdk-go--support-new-options-on-packaged-components.yaml
sdk/go/pulumi/provider.go
sdk/go/pulumi/provider_test.go
tests/integration/construct_component_resource_options/go/main.go
tests/integration/integration_test.go

`provider.Construct` is used to build MLCs in Go.
It receives a pulumirpc.ConstructRequest
and turns that into a standard Go SDK ResourceOption.
In #12682, we added a few new fields to pulumirpc.ConstructRequest.
This updates the Go SDK to pick up these new options
and pass them on for the resource to pick up
(and eventually send back to the engine as a RegisterResource call).
Testing:
This change includes unit tests to verify mapping of ConstructRequests
to options, which are then interpreted with NewResourceOptions.
On top of that, it builds upon the integration test added in #12699
to verify options that are saved in snapshots.
Note that this integration test does not test for the following options:
IgnoreChanges, ReplaceOnChanges, and DeleteBeforeReplace.
These options are not stored …

sdk/go: Propagate more resource options from provider.Construct

---

changelog/pending/20230418--cli-display--pulumi-cli-can-now-display-messages-provided-by-the-service.yaml
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/client/client.go
sdk/go/common/apitype/updates.go

This PR enables a backend to supply messages for the CLI to display to the user during Pulumi updates.
Fixes #12598

display backend specific messages to the user during updates

---

sdk/go/pulumi-language-go/main_test.go

This should've been part of #12716 but was missed.
The function that actually held the test body
was still changing the current directory.

fix(go/host): Don't change working directory in test

---

sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_test.go

add rate limited url to http requests

---

changelog/pending/20230421--programgen--allow-using-option-t-in-range-expressions.yaml
pkg/codegen/hcl2/model/binder_expression.go
pkg/codegen/hcl2/model/expression.go
pkg/codegen/hcl2/model/type_collection.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/iterating-optional-range-expressions-pp/iterating-optional-range-expressions.pp

Right now when using an `option(T)` in range expressions where `T` is an iterator like maps or lists, the binder fails when it is unable to figure out the underlying iterator type. This PR fixes the issue by reducing `option(T)` to `T`

[pcl/binder] Allow using option(T) in range expressions

---

changelog/pending/20230424--auto-nodejs--add-excludeprotected-option-for-destroy.yaml
sdk/nodejs/automation/stack.ts
sdk/nodejs/tests/automation/localWorkspace.spec.ts

This change adds an `excludeProtected` option for `destroy`.
Part of #12733

[auto/nodejs] Add `excludeProtected` option for `destroy`

---

changelog/pending/20230424--cli--fix-destroy-without-project-file.yaml
pkg/backend/backend.go
pkg/backend/filestate/backend.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/stack.go
pkg/backend/mock.go
pkg/cmd/pulumi/destroy.go

Fixes https://github.com/pulumi/pulumi/issues/12714
The empty project created for destroy operations when no Pulumi.yaml is found still needs to have it's name filled in so that project name consistency checks work.
Our tests didn't pick this up because for filestate we were still searching from the working directory for consistency checks rather than checking the backends current project. I've also fixed that up as part of this change.

Fix destroy without project file

---

changelog/pending/20230425--auto-nodejs--add-refresh-option-for-preview.yaml
sdk/nodejs/automation/stack.ts
sdk/nodejs/tests/automation/localWorkspace.spec.ts

This PR adds support for `pulumi preview --refresh` in Automation API for NodeJS.
Fixes https://github.com/pulumi/pulumi/issues/12740
This is a blocker for [actions/#870](https://github.com/pulumi/actions/issues/870) and potential customer adoption.

Node AutoAPI: Support `preview --refresh`

---

changelog/pending/20230420--cli--speed-up-conversion-mapping-lookups-for-the-common-case-of-pulumi-names-matching-external-ecosystem-names.yaml
pkg/codegen/convert/plugin_mapper.go
pkg/codegen/convert/plugin_mapper_test.go

Rather than doing a linear search through all the plugins and asking each in turn for their mapping information, use the heuristic that normally the Pulumi provider name matches the mapped provider name and try that plugin first.

Speed up mapping lookup

---

changelog/pending/20230424--sdk-go--ensure-that-dependency-searches-happen-in-the-pulumi-program-directory.yaml
sdk/go/pulumi-language-go/main.go

Follow up to https://github.com/pulumi/pulumi/pull/12727#discussion_r1175433156
The GetRequiredPlugins and GetProgramDependencies methods of the Go
language host always operate in the current directory of the plugin.
This is likely unintentional because the request message includes a Pwd
field specifying the program directory.
For comparison:
- The Python host also runs in the plugin directory
- The Node host correctly uses the program directory:
via the Pwd field for GetProgramDependencies
and the Program field for GetRequiredPlugins
The existing behavior likely happens to work because the plugin happens
to run inside the program directory, but that's not guaranteed.
This switches the Go language host to run queries inside the program
directory to guard against issues in the future.

fix(go/host): Use program directory

---

sdk/go/pulumi-language-go/main.go

Use the official golang.org/x/mod/modfile package to parse go.mod files
instead of the external copy of it.
Refs https://github.com/pulumi/pulumi/pull/12727#discussion_r1178333617

fix(host/go): Use official modfile package

---

changelog/pending/20230427--backend-filestate--revert-change-causing-provided-project-name-doesnt-match-pulumi-yaml-error.yaml
pkg/backend/backend.go
pkg/backend/filestate/backend.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/stack.go
pkg/backend/mock.go
pkg/cmd/pulumi/destroy.go

Reverting the change that is causing `error: could not create stack: provided project name "" doesn't match Pulumi.yaml` errors when using the filestate backend.
Before this revert, with v3.65.0, I get the error:
```
$ pulumi login --local
$ pulumi new go -g
$ pulumi stack init dev
error: could not create stack: provided project name "" doesn't match Pulumi.yaml
```
After revert, no longer getting the error.
Fixes https://github.com/pulumi/pulumi/issues/12760

Revert "Fix destroy without project file"

---

changelog/pending/20230426--programgen-nodejs--support-range-expressions-that-are-of-type-output.yaml
pkg/codegen/nodejs/gen_program.go
pkg/codegen/nodejs/gen_program_expressions.go
pkg/codegen/pcl/rewrite_apply.go
pkg/codegen/pcl/utilities.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/iterating-optional-range-expressions-pp/iterating-optional-range-expressions.pp
pkg/codegen/testing/test/testdata/iterating-optional-range-expressions-pp/nodejs/iterating-optional-range-expressions.ts
pkg/codegen/testing/test/testdata/range-1.0.0.json
pkg/codegen/testing/utils/host.go

This PR implements nodejs program-gen support for `range` expressions that are of type `Output<T>` where `T` is a collection that should be iterated inside an `apply` call. 
<details>
<summary>Example PCL</summary>
```terraform
resource "root" "range:index:Root" {}
// creating resources by iterating a property of type array(string) of another resource
resource "fromListOfStrings" "range:index:Example" {
options {
range = root.arrayOfString
}
someString = range.value
}
// creating resources by iterating a property of type map(string) of another resource
resource "fromMapOfStrings" "range:index:Example" {
options {
range = root.mapOfString
}
someString = "${range.key} ${range.value}"
}
// computed range list expression to create instances of range:index:Example resource
resource …
```

[pcl/nodejs] Support range expressions that are of type output

---

scripts/get-job-matrix.py

This PR switches CI testing of the "Node Lastest" line from Node 19 to Node 20. This will help us catch issues for users who are on the cutting edge.
Fixes https://github.com/pulumi/pulumi/issues/12790
N/A. This is a change to CI only.

Bump NodeJS CI version.

---

changelog/pending/20230418--engine--fix-bug-where-providers-are-created-even-when-not-specified-as-a-target.yaml
pkg/engine/lifecycletest/target_test.go
pkg/engine/lifecycletest/update_plan_test.go
pkg/resource/deploy/step.go
pkg/resource/deploy/step_generator.go

Provider resources are now skipped if not targeted for creation.
Fixes #12621

Fix providers created during updates with `--target` with uncreated parents

---

changelog/pending/20230502--backend-filestate--improve-performance-of-project-existence-check.yaml
pkg/backend/filestate/backend.go
pkg/backend/filestate/store.go
pkg/backend/filestate/store_test.go

Add `projectReferenceStore.ProjectExists`.
`projectReferenceStore.ProjectExists` enables us to search for a specific project in `localBackend.DoesProjectExist`.
**Tasks**
Fixes https://github.com/pulumi/pulumi/issues/12547

Update DoesProjectExist to not list all projects

---

changelog/pending/20230503--cli--convert-now-prints-all-diagnostics-from-program-conversion.yaml
pkg/cmd/pulumi/convert.go

Convert was casting `hcl.Diagnostics` to `error` and so only ever printing the first diagnostics to the user. This prints all diagnostics to the user instead.
e.g.
```
error: main.pp:137,3-11: unsupported attribute 'timeouts'; unsupported attribute 'timeouts'
error: main.pp:163,3-11: unsupported attribute 'timeouts'; unsupported attribute 'timeouts'
error: main.pp:207,3-11: unsupported attribute 'timeouts'; unsupported attribute 'timeouts'
```

Print all pcl parse and bind diagnostics in convert

---

changelog/pending/20230502--programgen-python--support-range-expressions-that-are-of-type-output.yaml
pkg/codegen/pcl/rewrite_convert.go
pkg/codegen/python/gen_program.go
pkg/codegen/python/gen_program_quotes.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/iterating-optional-range-expressions-pp/python/iterating-optional-range-expressions.py

This PR implements python program-gen support for range expressions that are of type Output<T> where T is a collection that should be iterated inside an apply call. 
It generates intermediate helper functions that contain the loop to create the resources, then references those functions in the apply call. (see code below)
I had to change/fix `rewriteTraversal` where it type-checked a traversal expression (i.e. `value.something`) after the casing of a member has changed to snake case (i.e. `someValue` -> `some_value`) and failed the program generation. Now it no longer type checks the resulting expression, since we rely on the bind phase to do the type checking.
<details>
<summary>Example PCL</summary>
```terraform
resource "root" "range:index:Root" {}
// creating resources by iterating a …
```

[pcl/python] Support range expressions that are of type output

---

changelog/pending/20230503--programgen--allow-null-literal-as-a-default-value-for-config-variables.yaml
pkg/codegen/pcl/binder_nodes.go
pkg/codegen/pcl/binder_test.go

[pcl/binder] Allow null literal as a default value for config variables

---

changelog/pending/20230504--build--fixes-race-condition-in-building-go-sdk.yaml
sdk/go/pulumi/generate/main.go

We were building pulumi and hit an error in this function when running the makefile, but only in certain environments. I read the code, and it looks like there's a race condition here where the gofmt command finishes before the io.Copy starts, giving us this error:
```
⚠️  x86_64    | + make build
ℹ️  x86_64    | BUILD:
ℹ️  x86_64    | go generate ./pulumi/...
⚠️  x86_64    | panic: unexpected error running gofmt: read |0: file already closed
```
The go async function is unnecessary here, and the Go exec docs explain that StderrPipe should not be used with Run: https://pkg.go.dev/os/exec#Cmd.StderrPipe
CombinedOutput is a simpler way to accomplish the same thing, and fixes the race condition.

Fix race condition in go/generate function.

---

changelog/pending/20230504--cli--convert-to-pcl-will-recover-from-panics-in-program-binding.yaml
pkg/cmd/pulumi/convert.go

Workaround for issues such as https://github.com/pulumi/pulumi/issues/12826 when we just want to see the intermediate PCL.

Recover from panics in binding when writing PCL

---

changelog/pending/20230504--programgen--fix-panic-on-component-type-traversal.yaml
pkg/codegen/pcl/component.go

[pcl/binder] Fix panic on component type traversal

---

.github/workflows/ci-run-test.yml
sdk/go/pulumi-language-go/main.go
tests/smoke_test.go
tests/testdata/random_pp/main.pp
tests/testdata/simple_schema/schema.json

As discussed in ideation, some simple smoke tests to just validate that the downstream languages run against the current engine.

Add per-language smoke tests to the integration tests

---

changelog/pending/20230508--engine--fix-bug-with-targeting-and-plans-where-root-stack-resource-and-target-replaces-were-not-being-marked-targeted.yaml
pkg/engine/lifecycletest/update_plan_test.go
pkg/resource/deploy/step_executor.go
pkg/resource/deploy/step_generator.go

Fixes 2 bugs
* --target not being specified, marked all resources as targeted even though --target-replace was specified
* update plans erroring due to the root stack not being in the update plan.
Fixes #12824

[engine] engine now always targets stack resource during updates

---

pkg/backend/filestate/backend.go
pkg/backend/httpstate/backend.go
pkg/backend/watch.go

`backend.Watch` was taking a `SecretsProvider` parameter, but it already took an `UpdateOperation` parameter which already has a `SecretProvider` on it. So now we just use that.

Don't pass a second SecretsProvider to backend.Watch

---

.github/workflows/ci-build-sdks.yml
.github/workflows/ci-run-test.yml
.github/workflows/ci-test-codegen.yml
.github/workflows/release.yml
CONTRIBUTING.md
README.md
changelog/pending/20230412--sdk-nodejs--minimum-version-node16.yaml
scripts/get-job-matrix.py

This PR migrates our CI/CD to use Node 16 instead of Node 14.
Node 14 will be sunset on April 30, 2023 (less than 3 weeks from the time of writing). This PR moves CI/CD to test and build on Node 16.
Fixes https://github.com/pulumi/pulumi/issues/12646

CI: Node 14 => Node 16

---

sdk/nodejs/resource.ts
sdk/nodejs/rome.json
sdk/nodejs/runtime/closure/codePaths.ts
sdk/nodejs/runtime/closure/serializeClosure.ts
sdk/nodejs/tests/runtime/jsClosureCases_10_4.js
sdk/nodejs/tests/runtime/jsClosureCases_8.js
sdk/nodejs/tests/runtime/tsClosureCases.ts

Currently, we employ Rome as a formatter for the Node SDK. This PR enables the Rome Linter. It disables all lints by default and opts-in to a single lint: `nodelete`.
The delete operator harms performance and can cause unexpected behavior; most often, assigning `undefined` is preferred to using `delete`. [See the documentation for details.](https://docs.rome.tools/lint/rules/nodelete/)
In this PR, I had to update our closure serialization tests to satisfy the test suite.
**N/A:** This change is a refactor only.

Enable Rome Linter And Add One Lint

---

sdk/nodejs/automation/cmd.ts
sdk/nodejs/automation/localWorkspace.ts
sdk/nodejs/automation/server.ts
sdk/nodejs/rome.json
sdk/nodejs/runtime/closure/codePaths.ts
sdk/nodejs/runtime/closure/createClosure.ts
sdk/nodejs/runtime/closure/parseFunction.ts
sdk/nodejs/runtime/invoke.ts
sdk/nodejs/runtime/resource.ts
sdk/nodejs/runtime/rpc.ts

This PR removes instances of prefix-!! where the value
would already be coerced into a boolean. It also removes
instances where the "optional chaining" operator (?.)
would suffice.
This PR enables two lints using Rome to detect and eliminate these instances.
**Documentation:** 
1. https://docs.rome.tools/lint/rules/noextrabooleancast/
2. https://docs.rome.tools/lint/rules/useoptionalchain/
**N/A:** This change is purely a refactor.

Eliminate unnecessary double negations.

---

changelog/pending/20230511--engine--fix-the-engine-trying-to-install-the-pulumi-resource-pulumi-plugin-which-is-builtin.yaml
pkg/engine/plugins.go

Noticed looking at a customer log which must have been using stack references. The snapshot reports back a resource in the "pulumi" package and so ensurePluginsareInstalled tries to install "pulumi-resource-pulumi" but that's a plugin built into the CLI.

Skip trying to install the pulumi-resource-pulumi plugin

---

.github/workflows/ci-lint.yml
sdk/nodejs/Makefile

When we introduced Rome into the Node SDK, we added a Make rule
for formatting separate from our linting rule. This commit moves
format-checking into the lint rule so that the Node SDK's Make rules
will more closely match the Python SDK's Make rules.
Now, in both SDKs, `make lint` also checks formatting.
**N/A:** This is strictly a workflow refactor.

Regularlize lint workflow.

---

sdk/nodejs/rome.json
sdk/nodejs/runtime/closure/createClosure.ts

This simple lint eliminates postfix-`!!`, which has no effect over a single postfix `!`. This lint rule is enforced by Rome.
**N/A:** This change is a refactor only.

Eliminate postfix-!!

---

CONTRIBUTING.md

We mention that you need to install gofumpt,
but it's easy to miss that there's some editor setup involved.
Also, gofumpt is not mentioned in the `brew install` which, depending on editor, may be necessary. (Editors that use gopls don't need to install it globally, but editors that invoke it manually need it installed.)
Ref: https://github.com/pulumi/pulumi/pull/12854#discussion_r1190467688

CONTRIBUTING: Clarify gofumpt further

---

sdk/nodejs/rome.json
sdk/nodejs/tests/runtime/asyncIterableUtil.spec.ts

This PR enables a number of other reasonable lints. They're all quite conservative, focused on identifying bizarre engineering choices that result in unintended behavior.
The only lint that appears in the codebase is `noAsyncPromiseExecutor`. The argument to `Promise` is supposed to be a synchronous function, not an async one. There's only one instances of this in the codebase, and it's in the test suite.
**N/A.** Only one test was refactored.

[Node SDK] Enable Lints for Bizaare Behavior

---

changelog/pending/20230511--sdk-go--testing-environment-now-tolerates-errors-in-deleting-the-test-environment.yaml
sdk/go/common/testing/environment.go

CI land attempts have started failing occasionally on Windows
with the following error:
```
=== FAIL: . TestLanguageImportSmoke/go (4.00s)
environment.go:96: Created new test environment:  C:\Users\RUNNER~1\AppData\Local\Temp\test-env711178549
smoke_test.go:129: Running command pulumi login --cloud-url file://C:/Users/RUNNER~1/AppData/Local/Temp/test-env711178549
smoke_test.go:130: Running command pulumi new go --yes
smoke_test.go:131: Running command pulumi import --yes random:index/randomId:RandomId identifier p-9hUg
history_test.go:28:
Error Trace:	C:/a/pulumi/pulumi/sdk/go/common/testing/environment.go:132
C:/a/pulumi/pulumi/tests/history_test.go:28
C:/a/pulumi/pulumi/tests/smoke_test.go:132
Error:      	Received unexpected error:
remove …
```

testing/Environment: Tolerate faillures in deleting the test directory

---

changelog/pending/20230511--sdk-nodejs--replace-empty-interfaces-with-type-aliases.yaml
sdk/nodejs/automation/events.ts
sdk/nodejs/output.ts
sdk/nodejs/queryable/index.ts
sdk/nodejs/rome.json
sdk/nodejs/runtime/closure/createClosure.ts

This commit safely replaces empty interfaces with type aliases.
Empty interfaces have no effect, even when they are subtyping
other interfaces. An empty interface is always equivalent to its supertype.
They can be safely replaced with type aliases, better expressing
the semantic equivalence between the two types.
Rome is very conservative in determining what constitutes a "safe" fix. For example, import reordering is considered unsafe because imports can have side effects. However, **Rome states that this change is safe.**
See https://docs.rome.tools/lint/rules/noemptyinterface/ for more detail.
I'm going to call out this change in the CHANGELOG, even though it's nonmaterial, just to clue in community members.

[Node SDK] Replaces empty interfaces with type aliases.

---

changelog/pending/20230508--programgen-go--module-support-as-component-resources.yaml
pkg/codegen/go/gen_program.go
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/go/gen_program_test.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/components-pp/go/components.go
pkg/codegen/testing/test/testdata/components-pp/go/exampleComponent.go
pkg/codegen/testing/test/testdata/components-pp/go/simpleComponent.go

This PR implements module support in Go program-gen, following suit with nodejs, python and dotnet. 
It is not perfect though as compiled component args are not wrapped with their respective types (i.e. `"value"` should be `pulumi.String("value")` instead). Tried to fix it in multiple places but didn't work out so decided to defer fixing the issue for now.

[go/programgen] Module support

---

pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/output-literals-pp/dotnet/output-literals.cs
pkg/codegen/testing/test/testdata/output-literals-pp/go/output-literals.go
pkg/codegen/testing/test/testdata/output-literals-pp/nodejs/output-literals.ts
pkg/codegen/testing/test/testdata/output-literals-pp/output-literals.pp
pkg/codegen/testing/test/testdata/output-literals-pp/python/output-literals.py

This currently isn't generating valid Go code, so we skip the compile for that.

Test for literals in output places

---

pkg/backend/httpstate/snapshot_test.go
pkg/engine/lifecycletest/test_plan.go

- Add a utility for generating snapshots for diff testing
- Add a framework for testing and benchmarking the deployment differ
Baseline benchmark results:
httpstate ❯ go test -count=10 -run none -benchmem -bench . | tee base.txt
```
│  base.txt   │
│   sec/op    │
DiffStack/1_x_2_B-10                              46.30µ ± 1%
DiffStack/2_x_2_B-10                              82.68µ ± 1%
DiffStack/4_x_2_B-10                              191.0µ ± 1%
DiffStack/8_x_2_B-10                              499.7µ ± 0%
DiffStack/16_x_2_B-10                             1.489m ± 0%
DiffStack/32_x_2_B-10                             4.895m ± 1%
DiffStack/48_x_2_B-10                             9.651m ± 1%
DiffStack/64_x_2_B-10                             15.11m ± 0%
DiffStack/1_x_8.2_kB-10 …
```

[snapshot] Add diff benchmarks and more tests

---

pkg/backend/cancellation_scope.go
pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/policy_disable.go
pkg/cmd/pulumi/policy_enable.go
pkg/cmd/pulumi/policy_publish.go
pkg/cmd/pulumi/policy_rm.go
pkg/cmd/pulumi/policy_validate.go
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/query.go
pkg/cmd/pulumi/refresh.go
pkg/cmd/pulumi/up.go
pkg/cmd/pulumi/util.go
pkg/cmd/pulumi/watch.go

This is needed for matrix testing where we need a cancellation scope like a normal `up` but we don't want the matrix testing code to live in cmd.

Move cancellation_scope to backend

---

pkg/cmd/pulumi/package.go
pkg/cmd/pulumi/package_publish.go

This pull request adds an _experimental_ subcommand to `pulumi package` called `publish-sdk`. 
- It scaffolds the structure of this new command.
- It implements the [npm publish logic from the scripts repo](https://github.com/pulumi/scripts/blob/master/ci/publish-tfgen-package) in Go and provides it via the Pulumi CLI.
Command help text output:
```sh
Usage:
pulumi package publish-sdk <package> <language> [flags]
Flags:
-h, --help          help for publish-sdk
--path string   The path to the root of your package.
Example: ./sdk/nodejs
--tag string    The tag for your NPM package, such as "latest""
```
Fixes pulumi/home#2697
I am open to suggestions on how to test this.
n/a; this feature is developer-only

Add pulumi package publish-sdk command structure and NPM publish functionality

---

changelog/pending/20230512--engine--nontargeted-resources-are-now-added-to-internal-update-plans.yaml
pkg/engine/lifecycletest/update_plan_test.go
pkg/resource/deploy/step_generator.go

Fixes #12926
This change modifies the step_generator to include untargeted resources in plans.
This prevents the step_executor from erroring from an untargeted resource being registered.
The `step_executor` would error due to an untargeted resource being registered while not being included in the update plan.
This appeared to be applicable only to users using update plans, but update plans are enabled by default internally.
There are some rare cases where they are not such as if `--skip-preview` is set, or if using `pulumi up` with URLs or Templates without PULUMI_EXPERIMENTAL being truthy.
This error previously appeared in #12824 and was believed to be due to the root stack resource not being targeted in liue of informative error messages.
A fix was merged in: …

Untargeted resources now have update plans.

---

pkg/backend/httpstate/client/client_test.go
pkg/backend/httpstate/client/marshal.go
pkg/backend/httpstate/diffs.go
pkg/backend/httpstate/snapshot.go
pkg/backend/httpstate/snapshot_test.go

Pool the buffers used for marshaling checkpoints. The pooling works by returning the last saved checkpoint's buffer to the diff state when a new checkpoint is saved. If a pooled buffer is available, it is reused when a checkpoint is marshaled. With our current usage patterns, this will cycle through two buffers. Starting from a fresh diff state:
- The first call to `MarshalDeployment` will create a new buffer `B1`
- The first call to `Saved` will put `B1` into `lastSavedDeployment`
- The second call to `MarshalDeployment` will create a new buffer `B2`
- The second call to `Saved` will put `B1` into the pool and `B2` into `lastSavedDeployment`
- The third call to `MarshalDeployment` will get `B1` from the pool
- The third call to `Saved` will put `B2` into the pool and `B1` into …

[snapshot] Pool checkpoint buffers

---

sdk/nodejs/package.json
sdk/nodejs/rome.json
sdk/nodejs/yarn.lock

Upgrade Rome to v12.1.0
This commit upgrades the Rome CLI to 12.1.0,
which advances many new lints from the nursery to stable.
This PR disables lints we violate that are enabled by default.
We can enable those lints again individually, as needed.
**N/A:** This PR is strictly a nonfunctional change.

Upgrade Rome to v12.1.0

---

.github/workflows/ci-run-test.yml
.github/workflows/pr-test-codegen-test-on-dispatch.yml

This reference is broken and is currently breaking dependabot's ability to open PRs.

Fix reusable workflow reference

---

changelog/pending/20230516--programgen-nodejs--allow-iterating-dynamic-entries-in-typescript.yaml
pkg/codegen/nodejs/gen_program_expressions.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/dynamic-entries-pp/dynamic-entries.pp
pkg/codegen/testing/test/testdata/dynamic-entries-pp/nodejs/dynamic-entries.ts

This PR fixes an issue in TypeScript program-gen to allow iterating over a dynamic variable. Treats them the same way maps and objects are handled. 
This piece of code:
```
validationOptions = [for entry in entries(validationOption) : {
domainName       = entry.value["domain_name"]
validationDomain = entry.value["validation_domain"]
}]
```
used to compile to 
```ts
// invalid TypeScript
validationOptions:  => ({key: k, value: v})).map(entry => ({
domainName: entry.value.domain_name,
validationDomain: entry.value.validation_domain,
})),
```
but now fixed to compile to 
```ts
validationOptions: Object.entries(validationOption).map(([k, v]) => ({key: k, value: v})).map(entry => ({
domainName: entry.value.domain_name,
validationDomain: entry.value.validation_domain,
})),
```
See added test …

[typescript/program-gen] Allow iterating dynamic entries in TypeScript

---

changelog/pending/20230517--sdk-go--fix-regression-disallowing-placing-a-pulumi-program-in-a-subdirectory-of-a-module.yaml
sdk/go/pulumi-language-go/main.go
sdk/go/pulumi-language-go/main_test.go
sdk/go/pulumi-language-go/testdata/sample/prog-subdir/README
sdk/go/pulumi-language-go/testdata/sample/prog-subdir/go.mod
sdk/go/pulumi-language-go/testdata/sample/prog-subdir/infra/Pulumi.yaml
sdk/go/pulumi-language-go/testdata/sample/prog-subdir/infra/main.go

Fixes a regression in the Go language host where we started misbehaving
if the Pulumi.yaml was in a subdirectory of the Go module.
myproject/
|- go.mod
|- foo.go
'- infra/
|- Pulumi.yaml
'- main.go
This regression was introduced in #12727,
where we started parsing go.mod files to extract version information
and incorrectly assumed that the go.mod file was in the request
directory.
To fix this, we'll use the following command to get the absolute path
to the go.mod file.
go list -m -f '{{.GoMod}}'
This command works in the root or subdirectory of a module
in both vendor and module mode.
Testing:
Includes a regression test in both module and vendor mode.
Resolves #12963

fix(host/go): Allow Pulumi program in a subdir of the module

---

pkg/cmd/pulumi/gen_markdown.go

Fixes: https://github.com/pulumi/docs/issues/9087
Add redirect aliases to CLI docs gen. I was able to test this and gen the output to confirm. You can see the files this change outputs in this [test PR that I created in the docs repo](https://github.com/pulumi/docs/pull/9102). There is not much diff there content wise because susan manually fixed up the files that are committed there. This is probably a good sign the genned output is now correct.

add aliases to front matter

---

sdk/nodejs/cmd/run-policy-pack/index.ts
sdk/nodejs/cmd/run-policy-pack/run.ts
sdk/nodejs/cmd/run/index.ts
sdk/nodejs/cmd/run/run.ts
sdk/nodejs/rome.json
sdk/nodejs/runtime/settings.ts

Eliminate assignment statements used as expressions.
This change refactors assignment statements used as expressions
to prefer assignment statements instead. Assignments are often
assumed to now evaluate to a value, but instead to represent a
change to a lexical binding. By using them as expressions, we can
write confusing and buggy code. This commit eliminates those instances
and enables a lint to prevent future occurrences.
**N/A:** This PR is strictly a non-functional change.

Eliminate assignment statements used as expressions.

---

changelog/pending/20230518--engine--revert-change-in-behavior-where-providers-would-skip-running-check-on-untargeted-resources-leading-to-unexpected-diffs.yaml
pkg/engine/lifecycletest/target_test.go
pkg/resource/deploy/step_generator.go

Fixes #12964
This commit uses an untargeted resource's old inputs directly and does
not send the untargeted resource's inputs to the provider for
alterations in `provider.Check()`.
This commit fixes a bug in behavior where `provider.Check()` was
no longer be called on untargeted resources. `provider.Check()` would
alter the engine's inputs for use in resource.Goals and skipping this
would cause `__defaults` to not be configured properly in same steps by
`provider.Check()` and cause replaces in some cases.

Revert change in targeted update behavior.

---

changelog/pending/20230519--cli-plugin--fixes-pulumi_debug_grpc-to-surface-provider-errors.yaml
pkg/util/rpcdebug/interceptors.go
pkg/util/rpcdebug/interceptors_test.go

This is useful for a lot of provider debugging when a resource provider returns an error. Previously this error would
not surface in the PULUMI_DEBUG_GRPC log, and with this change it does.

Fix PULUMI_DEBUG_GPRC to intercept client errors

---

pkg/resource/stack/deployment.go
pkg/resource/stack/secrets.go
pkg/resource/stack/secrets_test.go
pkg/secrets/b64/manager.go
pkg/secrets/cloud/manager.go
pkg/secrets/manager.go
pkg/secrets/passphrase/manager.go
pkg/secrets/passphrase/manager_test.go
pkg/secrets/service/manager.go

The state from a secret manager _always_ has to be something json serialisable because we store it into the json state files. Rather than allowing any `interface{}` to be returned here and then error'ing if it happens to not be something that can be marshalled to JSON this changes the interface to return a `json.RawMessage` moving the marshalling/unmarshalling concerns into the individual implementations that can pretty much guarantee valid structures.

Change secret.Manager State to json.RawMessage

---

changelog/pending/20230419--engine--provider-plugins-are-now-loaded-as-needed-not-at-startup-based-on-old-state-information.yaml
pkg/engine/lifecycletest/provider_test.go
pkg/engine/lifecycletest/pulumi_test.go
pkg/resource/deploy/deployment.go
pkg/resource/deploy/deployment_executor.go
pkg/resource/deploy/import.go
pkg/resource/deploy/providers/registry.go
pkg/resource/deploy/providers/registry_test.go
pkg/resource/deploy/source_query.go
pkg/resource/deploy/step.go
pkg/resource/deploy/step_generator.go

This changes the provider registry to no longer load all the providers
from the old state on startup (in `NewRegistry`) instead the load logic
has been moved to the `Same` method. The step_executor and
step_generator have been fixed up to ensure that for cases where a
resource might not have had it's provider created yet (i.e. for DBR'ing
the old version of a resource, for refreshes or deletes) they ask the
`Deployment` to look up the provider in the old state and `Same` it in the
registry.
All of the above means we only load providers we're going to use (even
taking --targets into account).
One fix mot done in this change is to auto-update providers for deletes.
That is given a program state with two resources both using V1 of a
provider, if you run the program to update one of those …

Don't load providers at startup

---

changelog/pending/20230522--backend-filestate--fix-the-project-filter-when-listing-stacks-from-new-stores-that-support-per-project-stack-references.yaml
pkg/backend/filestate/backend.go
pkg/backend/filestate/backend_test.go

Fixes https://github.com/pulumi/pulumi/issues/12974

Fix filestates project filter for ListStacks

---

Makefile
sdk/go/pulumi-language-go/main.go
sdk/go/pulumi-language-go/main_test.go

The Go language host is a separate Go module
and did not have linting enabled.
This adds it to the list of packages that should be linted in CI
and fixes issues that were found:
- not gofumpted
- using ioutil

ci: Lint Go language host

---

.golangci.yml
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/preview.go
pkg/codegen/pcl/binder_component.go
sdk/go/auto/errors_test.go
tests/integration/construct_component_methods_resources/testcomponent-go/random.go

govet includes a nilness linter that detects a few nil issues.
This linter is not enabled by default in govet because the `go` tool
does not want a dependency on the libraries necessary to implement this
(golang/go#59714).
Enable the nilness linter and fix the following issues found by it
(commentary below each check mine):
pkg/cmd/pulumi/new.go:283:9: nilness: impossible condition: nil != nil (govet)
^- the error was very likely supposed to be the `os.Remove`
pkg/cmd/pulumi/new.go:633:10: nilness: impossible condition: nil != nil (govet)
^- same error checked on the previous line
pkg/cmd/pulumi/preview.go:190:11: nilness: impossible condition: nil != nil (govet)
^- same error checked a few blocks above
pkg/codegen/pcl/binder_component.go:101:64: nilness: nil dereference in dynamic method …

lint(govet): Enable nilness linter

---

.golangci.yml

Enables a few more linters that aren't part of 'go vet' by default
because of the same reason as nilness: the Go toolchain doesn't want
a dependency on the SSA analysis library.
The following checks are enabled:
- reflectvaluecompare: Checks for incorrect comparison of
`reflect.Value`s with `==` or `reflect.DeepEqual`.
Given our use of reflection APIs,
this is probably a good idea to catch.
- sortslice: `sort.Slice(interface{}, ..)` with a non-slice argument
will panic at runtime. This catches that.
- unusedwrite: Looks for writes to struct fields and the like
when they're not read again. e.g.,
```go
for _, f := range []foo{...} {
f.x = 42
// f is a struct copied by value.
// The write will be ignored.
}
```
Although we don't have any current instances of these issues,
these are possible …

lint(vet): Enable more linters

---

changelog/pending/20230523--sdkgen-go--fix-versioned-typerefs-being-marshalled-across-code-generator-rpcs.yaml
pkg/codegen/schema/schema.go
pkg/codegen/schema/schema_test.go
pkg/codegen/testing/test/testdata/remoteref-1.0.0.json
pkg/codegen/testing/utils/host.go

Fixes https://github.com/pulumi/pulumi/issues/13000

Fix version number in typerefs when marshalling schemas

---

changelog/pending/20230524--programgen--include-the-component-source-directory-in-diagnostics-when-reporting-pcl-errors.yaml
pkg/codegen/pcl/binder_component.go

Include the component source directory in diagnostics when reporting PCL errors. Usually when a PCL component reports an error, the `Subject` of the diagnostic is only a file name like `main.pp` but that is not enough information in programs with many components that have that same file name. This PR addresses the issue and replaces the `Subject` of diagnostic errors to the full path of the component directory. 
Fixes #13015
- [] I have formatted my code using `gofumpt`

[pcl/binder] Include the component source directory in diagnostics when reporting PCL errors

---

changelog/pending/20230524--cli-plugin--plugin-install-auto-fills-the-download-url-for-some-known-third-party-plugins.yaml
pkg/cmd/pulumi/plugin_install.go
pkg/codegen/schema/loader.go
pkg/util/plugin.go
pkg/util/plugin_test.go

Hardcode a list of some known third-party providers so "plugin install" works even without "--server" being set. Currently this is just the pulumiverse plugins, but we could add any other popular ones (Like lbrlabs) here as well.
Long term this would all be replaced with registry lookups.
Fixes https://github.com/pulumi/pulumi-terraform-bridge/issues/1058

Hardcode some known provider plugin locations

---

changelog/pending/20230525--cli--replace-heap-profiles-with-allocation-profiles.yaml
pkg/cmd/pulumi/pulumi.go
sdk/go/common/util/cmdutil/profile.go

The current memory profile reports the live objects and their sources at the time at which it is captured. This is almost never what we want: instead, we want a profile of _all_ allocations over the lifetime of the process. These changes replace the heap profile with an allocation profile and add a parameter, --memprofilerate, to control the rate at which allocations are profiled.

[cli] Better memory profiling

---

sdk/go/common/util/logging/log.go

`glog.Verbose(int)` returns a bool that indicates whether or not logging is enabled at the given level. Check that result prior to actually calling the logger in order to avoid extra work when verbose logging is disabled.

[logging] Guard verbose logs on glog.Verbose

---

sdk/nodejs/npm/npm_test.go

I have _no_ idea how this ever got merged to master. But this fixes the TestNPMInstallCmd on windows.
What was happening was that `Path` was being set to "false.exe", the extension for that is ".exe", `TrimRight` takes a _set_ of characters to trim (as a string) so it would trim `Path` to "fals" because "e" is in the cutset.
Changing this to `TrimSuffix` trims off the exact suffix of ".exe".

Fix TestNPMInstallCmd

---

sdk/nodejs/npm/manager_test.go

Follow up to #12983
Tests that download from NPM or Yarn will be brittle, unsafe, and slow.
We don't need to hit these servers directly.
This change alters the package installation tests to
set up a local HTTP server that implements a subset of the
[NPM Package Registry API][1] -- just enough to satisfy these tests.
[1]: https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md
In the tests, we'll set `$HOME` to a new temporary directory and write
an `~/.npmrc` or `~/.yarnrc` requesting use of the local server as the
registry.
With this, the tests are entirely local. No external requests.
Also contains minor fix-ups to the test that were pointed out in #12983:
- Use 'require' in chdir
- Use subtests for `Test*Install`
- Don't send command output to /dev/null
These fix-ups are in …

test(sdk/npm): Don't download from NPM or Yarn regstries

---

changelog/pending/20230529--auto-python--add-support-for-the-path-option-for-config-operations.yaml
sdk/python/lib/pulumi/automation/_local_workspace.py
sdk/python/lib/pulumi/automation/_stack.py
sdk/python/lib/pulumi/automation/_workspace.py
sdk/python/lib/test/automation/test_local_workspace.py

Add support for the `--path` flag for config operations in Python automation API.
Part of #5506
Related: #12265

[auto/python] Add support for the path option for config operations

---

changelog/pending/20230525--programgen-nodejs-python--implement-singleornone-intrinsic.yaml
pkg/codegen/nodejs/gen_program_expressions.go
pkg/codegen/nodejs/gen_program_utils.go
pkg/codegen/pcl/binder_test.go
pkg/codegen/pcl/functions.go
pkg/codegen/pcl/functions_test.go
pkg/codegen/pcl/utilities_test.go
pkg/codegen/python/gen_program_expressions.go
pkg/codegen/python/gen_program_utils.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/single-or-none-pp/nodejs/single-or-none.ts
pkg/codegen/testing/test/testdata/single-or-none-pp/python/single-or-none.py
pkg/codegen/testing/test/testdata/single-or-none-pp/single-or-none.pp

Implements the `singleOrNone` PCL intrinsic function and its implementation for python and typescript. This function is used when converting terraform's dynamic block that are used with resource attributes where `maxItems == 1` which means the dynamic block (compiled to a for-expression) should evaluate to a single value or none at all. 
The PR adds unit tests to assert the possible error messages produced by the binder when it doesn't type-check correctly

[pcl/program-gen] Implement singleOrNone intrinsic for python and typescript

---

changelog/pending/20230529--backend-filestate--fix-stack-rename-renaming-projects-for-the-self-managed-backend.yaml
pkg/backend/filestate/backend.go
pkg/backend/filestate/backend_test.go
tests/integration/integration_test.go

Fix renaming the project using "stack rename" for filestate.

Fix project renames for filestate

---

sdk/go.mod
sdk/go.sum
sdk/nodejs/npm/yarn.go
tests/integration/construct_component_provider_propagation/go/go.mod
tests/integration/construct_component_provider_propagation/go/go.sum
tests/integration/construct_component_resource_options/go/go.mod
tests/integration/construct_component_resource_options/go/go.sum
tests/integration/construct_nested_component/go/go.mod
tests/integration/construct_nested_component/go/go.sum

This PR uses os.Tempfile instead of creating our own with UUID. The standard library's os.Tempfile function
is race-safe, collision-proof, and uses the OS's tempdir, which allows the OS to clean up old files if Pulumi were to 
fail to do so.

Use os.tmpfile instead of creating our own.

---

.github/workflows/ci-lint.yml

When the 'go mod tidy' lint check fails,
it prints a simple error message reporting the failure.
Most will resort to running `go mod tidy` manually
to attempt to fix this, but this will not always work.
We need to run `./scripts/tidy.sh` which updates all go.mod files
and includes specific compatibility flags.

ci(lint): Helpful message on tidy failure

---

.github/workflows/ci-lint.yml

`make tidy` is a more future-proof advice than `./scripts/tidy.sh`.
Refs https://github.com/pulumi/pulumi/pull/13054#discussion_r1210794437

ci(lint): make tidy > ./scripts/tidy.sh

---

pkg/codegen/go/gen.go

If there's no alias defined and there's a root package name defined, then use that for the pkgName of the basePath instead of guessing it from the basePath.
Fixes #13038 (issue)

Fix resolution of root package name in go module init

---

changelog/pending/20230530--programgen-go--do-not-error-when-generated-go-code-cannot-be-formatted.yaml
pkg/codegen/go/gen_program.go

When generating go code in program-gen, we format the code before saving it to disk. However, if formatting fails, we don't generated anything at all and we simply error. This PR changes this behaviour such that we fall back to and generate the original, non-formatted code when formatting fails. 
Fixes part of https://github.com/pulumi/pulumi-terraform-bridge/issues/1158

[go/program-gen] Do not error when generated Go code cannot be formatted

---

pkg/resource/deploy/step_generator.go

Diff/DiffConfig is currently always called with the old outputs and new inputs, except for this one case in step_generator where we called DiffConfig with the old inputs instead of old outputs.
For providers inputs and outputs are always the same (Configure doesn't allow providers to return any properties, so the engine enforces that outputs=inputs) so using inputs or outputs here doesn't have any effect, but less confusing to not have this inconsistency.

Fix inconsistency in calling DiffConfig

---

changelog/pending/20230523--engine--add-pulumi-tags-config-option-to-set-stack-tags.yaml
pkg/backend/filestate/backend.go
pkg/backend/httpstate/backend.go
pkg/backend/stack.go
tests/integration/integration_test.go
tests/stack_test.go
tests/testdata/simple_tags/Pulumi.yaml
tests/testdata/simple_tags/index.ts
tests/testdata/simple_tags/package.json
tests/testdata/simple_tags/resource.ts

Support a "pulumi:tags" config property to set the stacks tags on operations (e.g. up, refresh, etc).
Fixes https://github.com/pulumi/pulumi/issues/5004
Note that I've gone with a slightly different approach to #5004. The suggestion in that ticket was to add a new section "tags" to the yaml, but given that we probably want to allow setting tags per-project and per-stack with some way to merge them I figured it better to reuse normal config and benefit from https://github.com/pulumi/pulumi/issues/11547 when that's done.

Support 'pulumi:tags' config to set stack tags

---

pkg/cmd/pulumi/package_publish.go

Adds more detailed output to npm publish command. 
This command has been working well when run on its own but has been consistently [failing in CI](https://github.com/pulumi/pulumi-kafka/actions/runs/5092448086/jobs/9154177739#step:3:947).
Adding these extra steps will grant more insight.
I have NOT run make tidy as it doesn't support Go 1.20

Improve publish output

---

pkg/cmd/pulumi/convert.go
pkg/cmd/pulumi/import.go

These use formatting so need to be `Message` not `RawMessage`.

Fix install failure messages

---

changelog/pending/20230602--programgen-dotnet-go--do-not-error-out-when-generaing-not-yet-implemented-forexpressions.yaml
pkg/codegen/dotnet/gen_program.go
pkg/codegen/dotnet/gen_program_expressions.go
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/entries-function-pp/dotnet/entries-function.cs
pkg/codegen/testing/test/testdata/entries-function-pp/go/entries-function.go

Partially implements `ForExpressions` in dotnet/csharp and for go program-gen, simply not erroring out when encountering not yet implemented expressions like `ForExpression`
Partially addresses #12606

[pcl/dotnet,go] Do not error out when generaing not yet implemented ForExpressions

---

changelog/pending/20230315--engine--deletedwith-resourceoption-is-now-inherited-from-its-parent-across-sdks.yaml
pkg/engine/lifecycletest/provider_test.go
pkg/resource/deploy/source_eval.go
pkg/resource/deploy/source_eval_test.go

This PR uses this information to set the `DeletedWith` when it is left unset by the user's program and there is a Parent resource to inherit the value from.
From https://github.com/pulumi/pulumi/pull/12446 which was reverted due to https://github.com/pulumi/pulumi/issues/12562 having difficulty with MLCs and Read resources.
TODO
Fixes #12158 
Needs follow up on: https://github.com/pulumi/pulumi-hugo/issues/2566

Resources now inherit the DeletedWith Resource Option across SDKs.

---

changelog/pending/20230602--cli-plugin--language-plugins-respect-pulumi_ignore_ambient_plugins.yaml
sdk/go/common/workspace/plugins.go

Fixes https://github.com/pulumi/pulumi/issues/13087
When looking up plugins that count as bundled (language plugins and the shims for dynamics and policy) they previously didn't respect `PULUMI_IGNORE_AMBIENT_PLUGINS `, this fixes that so that even for bundled plugins if `PULUMI_IGNORE_AMBIENT_PLUGINS` we don't search `$PATH`. We'll still find bundled plugins because we do a lookup in the pulumi binary folder for them.

Don't lookup bundled plugins on path if IGNORE_AMBIENT_PLUGINS is set

---

changelog/pending/20230602--programgen-go-nodejs--fix-a-panic-in-diagnostics-from-go-nodejs-project-generation.yaml
sdk/go/common/resource/plugin/langruntime_plugin.go
sdk/go/common/resource/plugin/langruntime_plugin_test.go

Fixes some nil pointer dereferences in the diagnostic marshaling code.
Fixes https://github.com/pulumi/pulumi-terraform-bridge/issues/1177

Fix hcl.Diagnostic roundtripping

---

sdk/go/common/resource/plugin/provider_plugin.go

Most of the grpc methods log their success information. GetPluginInfo didn't and it would be really nice if it did to make it easy to see in debug logs that the provider loaded reported the version we expect.

Log the version from GetPluginInfo

---

changelog/pending/20230602--programgen-nodejs--only-await-promise-returning-invokes-in-typescript-program-gen.yaml
pkg/codegen/nodejs/gen_program_lower.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/invoke-inside-conditional-range-pp/invoke-inside-conditional-range.pp
pkg/codegen/testing/test/testdata/invoke-inside-conditional-range-pp/nodejs/invoke-inside-conditional-range.ts
pkg/codegen/testing/test/testdata/std-1.0.0.json

Replaces #13051 and addresses https://github.com/pulumi/pulumi-terraform-bridge/issues/1159
The problem with program-gen panicking is that for TypeScript, when program-gen decides that the main entry program should be async, it assumed all invokes are turned into promise-returning invokes and _panics_ when it encounters an invoke that isn't promise-returning when it tries to await the invoke. 
This PR fixes this issue by only applying `await(invoke(...))` when the invoke is actually promise-returning and **not expecting** all other invokes to be promise-returning. Some _can_ be output-returning invokes inside of a program with an async entry point. 
TL;DR of this PR
```diff
- _, isPromise := call.Type().(*model.PromiseType)
- contract.Assertf(isPromise, "invoke must return a promise")
- …
```

[pcl/typescript] Only await promise-returning invokes in typescript program-gen

---

changelog/pending/20230603--programgen-dotnet--only-await-task-returning-invokes-in-dotnet-program-gen.yaml
pkg/codegen/dotnet/gen_program_expressions.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/invoke-inside-conditional-range-pp/dotnet/invoke-inside-conditional-range.cs

Similar to #13085 but for dotnet. No longer panics when encountering different types of invokes in the same program. Addresses https://github.com/pulumi/pulumi-terraform-bridge/issues/1161

[program-gen/dotnet] Only await task-returning invokes

---

pkg/codegen/convert/mapper_client.go
pkg/codegen/convert/mapper_server.go
sdk/go/common/resource/plugin/provider_plugin.go

Makes it easier to trace conversion mappings via debug logs.

Add debug logs to Mapping calls

---

pkg/codegen/convert/mapper.go
pkg/codegen/convert/mapper_client.go
pkg/codegen/convert/mapper_server.go
pkg/codegen/convert/plugin_mapper.go
pkg/codegen/convert/plugin_mapper_test.go

Now that we've removed the build link to terraform-bridge we can fix this TODO. Pass a `context.Context` to `GetMapping` because it's normally an async method.
This will require a small fix up in terraform-bridge when it updates to this version of pulumi/pkg.

Make GetMapping contextful

---

sdk/go/common/resource/plugin/converter_plugin.go
sdk/go/common/resource/plugin/converter_plugin_test.go
sdk/go/common/resource/plugin/converter_server.go
sdk/go/common/resource/plugin/converter_server_test.go

The converter diagnostics were appending to a pre-allocated but also pre-sized slice and so returning a load of `nil`s over RPC. This fixes that and adds some sanity tests for both sides of the interface.

Fix converter diagnostics

---

pkg/codegen/convert/plugin_mapper.go
pkg/codegen/convert/plugin_mapper_test.go

Fixes https://github.com/pulumi/pulumi/issues/13105
When we failed to find a mapping for a provider we wouldn't save that result, so on calling GetMapping again we'd try installing and querying that provider again.

Fix plugin mapper to not retry installs

---

pkg/cmd/pulumi/convert.go

If the language plugin returns any error diagnostics then project generation failed and we should error out of convert. This used to work because we returned the diagnostics as a grpc error, but we've just changed that to instead not be an error but just a grpc result of a full list of diagnostics but forgot to add the error case check for that.

Error in convert if any error diagnostics are returned

---

changelog/pending/20230607--programgen-nodejs--allow-output-variables-to-have-the-same-identifier-as-other-program-nodes.yaml
pkg/codegen/hcl2/model/scope.go
pkg/codegen/nodejs/gen_program.go
pkg/codegen/pcl/binder_test.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/aws-eks-pp/nodejs/aws-eks.ts
pkg/codegen/testing/test/testdata/logical-name-pp/nodejs/logical-name.ts
pkg/codegen/testing/test/testdata/output-name-conflict-pp/dotnet/output-name-conflict.cs
pkg/codegen/testing/test/testdata/output-name-conflict-pp/go/output-name-conflict.go
pkg/codegen/testing/test/testdata/output-name-conflict-pp/nodejs/output-name-conflict.ts
pkg/codegen/testing/test/testdata/output-name-conflict-pp/output-name-conflict.pp
pkg/codegen/testing/test/testdata/output-name-conflict-pp/python/output-name-conflict.py

This PR extends the PCL binder to allow declaring _output_ variables that have the same identifier as other program node types. The outputs now have their own namespace within a scope. This means that the binder now checks that outputs have unique identifier with respect to only other outputs. 
```diff
type Scope struct {
parent    *Scope
syntax    hclsyntax.Node
defs      map[string]Definition
+	outputs   map[string]Definition
functions map[string]*Function
}
```
It used to be the case that the binder would fail if it encounters an output variable with ID equal to that of another node. However, as we have seen in many terraform examples, module variables and module outputs can have the same identifier. 
All program-gens except for TypeScript can already handle this case so in this PR …

[pcl] Allow output variables to have the same identifier as other program nodes

---

changelog/pending/20230607--programgen-go--fix-panic-in-go-program-gen-when-encountering-splat-expressions.yaml
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/simple-splat-pp/dotnet/simple-splat.cs
pkg/codegen/testing/test/testdata/simple-splat-pp/go/simple-splat.go
pkg/codegen/testing/test/testdata/simple-splat-pp/nodejs/simple-splat.ts
pkg/codegen/testing/test/testdata/simple-splat-pp/python/simple-splat.py
pkg/codegen/testing/test/testdata/simple-splat-pp/simple-splat.pp
pkg/codegen/testing/test/testdata/splat-1.0.0.json
pkg/codegen/testing/utils/host.go

This PR adds a test program to show compiling splat expressions in the different languages and fixing a panic in go program-gen. I created a simple schema for this specific test which is why compiling the example is skipped in all languages. 
The problem was that rewriting splat expressions happened after rewriting conversions so I switched the order of them.  
Fixes #13108

[pcl/go] Fix panic in go program-gen when encountering splat expressions

---

changelog/pending/20230607--cli-new--escape-special-characters-in-project-description.yaml
pkg/cmd/pulumi/new_acceptance_test.go
sdk/go/common/workspace/templates.go

The `transform` method does a simple find-and-replace for all occurrences of `${PROJECT}` and `${DESCRIPTION}` we encounter when templating a new project.
The templates repo only uses `${DESCRIPTION}` in `Pulumi.yaml` files, and all use cases are identical:
```
description: ${DESCRIPTION}
```
`${PROJECT}` is validated, but `${DESCRIPTION}` is freeform text. This means the user can accidentally provide a description that generates a malformed `Pulumi.yaml`.
This PR escapes any special characters by marshaling the description to YAML before performing the find-and-replace. A test was modified to reproduce the issue and confirm the fix.

cli/new: Escape special characters in project description

---

changelog/pending/20230606--engine--fixes-a-bug-where-targeted-previews-would-error-on-deletes-of-targeted-resources.yaml
pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/refresh.go
pkg/cmd/pulumi/up.go
pkg/engine/deployment.go
pkg/engine/destroy.go
pkg/engine/lifecycletest/refresh_test.go
pkg/engine/lifecycletest/target_test.go
pkg/engine/lifecycletest/update_plan_test.go
pkg/engine/refresh.go
pkg/engine/update.go
pkg/resource/deploy/deployment.go
pkg/resource/deploy/deployment_executor.go
pkg/resource/deploy/step_generator.go

Consolidate `--target` handling internally to deduplicate `DestroyTargets` `RefreshTargets` `UpdateTargets` into a single `Targets` field.
Consequences:
-  this moves pre-update verification of `--target`s existing for destroyed resources into the Destroy command (similar to `--exclude-protected`)
- in the engine, `checkTargets()` now runs before `rebuildBaseState()` mutates the prev Snapshot it was checking
- Fixes #6422 
Fixes #13029

Consolidated Target parameters

---

changelog/pending/20230601--sdk-nodejs--add-support-for-asynchronous-mock-implementations.yaml
sdk/nodejs/runtime/index.ts
sdk/nodejs/runtime/mocks.ts
sdk/nodejs/tests_with_mocks/mocks.spec.ts

This PR implements the feature request #13049.
Pulumi's mocking feature for TypeScript is configured by calling `pulumi.runtime.setMocks(...)`. It only supports synchronous mock implementations. I.e., the functions call and `newResource`, which are provided as an object of type Mocks, must be synchronous. This prevents using any asynchronous function or APIs to generate or retrieve values to return because they cannot be awaited in a synchronous TS function.
This PR extends the `Mocks` interface with support for asynchronous mock implementations. The changes are backward compatible. In contrast to the implementation sketched in [#13049](https://github.com/pulumi/pulumi/issues/13049), this version is more elegant, requires less code, and is still type-safe.

Add support for asynchronous typescript mocks

---

pkg/codegen/pcl/binder.go
pkg/codegen/pcl/binder_resource.go
pkg/codegen/schema/bind.go
sdk/go/common/resource/plugin/converter_plugin.go
sdk/go/common/resource/plugin/converter_plugin_test.go

Fixes https://github.com/pulumi/pulumi-terraform-bridge/issues/1201
hcl.Diagnostics implements the Error interface, but this means a list of zero diagnostics still looks like a non-nil error, which throws of normal "if err == nil" checks.
This changes a few use sites of hcl.Diagnostics to ensure we return nil when there aren't any diagnostics rather than an empty slice. This ensures if they get cast to `Error` they don't trip up standard `err == nil` checks.

Don't return empty hcl.Diagnostics

---

changelog/pending/20230608--programgen--fixes-range-scoping-for-pcl-components.yaml
pkg/codegen/pcl/binder.go
pkg/codegen/pcl/binder_component.go
pkg/codegen/pcl/binder_resource.go
pkg/codegen/pcl/binder_test.go
pkg/codegen/pcl/functions.go

This PR implements proper `range` block scoping for `pcl.Component` so that when binding the component body, it understands references to the `range` expression. This fixes a couple of the PCL binder issues we have been seeing in TF converter such as  https://github.com/pulumi/pulumi-terraform-bridge/issues/1184, https://github.com/pulumi/pulumi-terraform-bridge/issues/1150, https://github.com/pulumi/pulumi-terraform-bridge/issues/1148 at least locally these errors are resolved for the linked TF example. 
Also small fix for the error we are seeing for `length(...)` because fields of object-typed config were implicitly optional and errored before. Now it flattens `option<T>` to just `T` and no longer errors. https://github.com/pulumi/pulumi-terraform-bridge/issues/1186

[pcl/components] Fixes range scoping for PCL components

---

changelog/pending/20230611--programgen-dotnet-go--add-support-for-the-singleornone-intrinsic.yaml
pkg/codegen/dotnet/gen_program_expressions.go
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/go/gen_program_utils.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/single-or-none-pp/dotnet/single-or-none.cs
pkg/codegen/testing/test/testdata/single-or-none-pp/go/single-or-none.go

This change adds support for the `singleOrNone` intrinsic to Go and C# programgen.
Fixes #13148

[programgen/dotnet,go] Implement singleOrNone intrinsic

---

changelog/pending/20230601--backend-filestate--add-an-option-to-the-upgrade-operation-allowing-injection-of-an-external-source-of-project-names-for-stacks-where-the-project-name-could-not-be-automatically-determined.yaml
pkg/backend/filestate/backend.go
pkg/backend/filestate/backend_test.go
pkg/cmd/pulumi/state_upgrade.go
pkg/cmd/pulumi/state_upgrade_test.go

Commits are individually reviewable.
---
The filestate upgrade operation is limited: it can only upgrade stacks
for which it's able to guess a project name by inspecting resources.
It cannot upgrade empty stacks, or stacks where someone recently called
`pulumi destroy` because they don't have any resources for it to inspect.
To resolve this, we need to support an external hook:
some means for the caller to fill in project names for stacks
where the names could not be guessed.
We'll use this hook in the CLI to prompt the user.
This change adds an UpgradeOptions argument to the Upgrade operation.
UpgradeOptions includes an option ProjectsForDetachedStacks.
This is a callback in the form:
func(stacks []Name) (projects []Name, err error)
It takes a list of stack names and returns a list of …

filestate/upgrade: Add hook to fill missing project names

---

changelog/pending/20230412--cli--dont-warn-about-the-cli-version-being-out-of-date-on-every-run-the-cli-will-now-only-warn-once-a-day-when-it-queries-for-the-latest-version.yaml
pkg/cmd/pulumi/pulumi.go
pkg/cmd/pulumi/pulumi_test.go

Fixes https://github.com/pulumi/pulumi/issues/12659.

Only warn about version upgrade once a day

---

changelog/pending/20230614--programgen-dotnet-go-nodejs-python--extend-skipresourcetypechecking-to-allow-generating-unknown-resources.yaml
pkg/codegen/dotnet/gen_program.go
pkg/codegen/go/gen_program.go
pkg/codegen/nodejs/gen_program.go
pkg/codegen/pcl/binder_resource.go
pkg/codegen/pcl/binder_schema.go
pkg/codegen/pcl/binder_test.go
pkg/codegen/pcl/diagnostics.go
pkg/codegen/pcl/utilities.go
pkg/codegen/python/gen_program.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/unknown-resource-pp/dotnet/unknown-resource.cs
pkg/codegen/testing/test/testdata/unknown-resource-pp/go/unknown-resource.go
pkg/codegen/testing/test/testdata/unknown-resource-pp/nodejs/unknown-resource.ts
pkg/codegen/testing/test/testdata/unknown-resource-pp/python/unknown-resource.py
pkg/codegen/testing/test/testdata/unknown-resource-pp/unknown-resource.pp

Currently when generating code from PCL and we have unknown resources (those without a schema), the binder fails and the conversion stops. This is not ideal when we try to convert terraform codebases that include resources which we haven't bridged yet. 
This PR addresses this issue by extending `pcl.SkipResourceTypechecking` to _allow_ binding unknown resources and making a best guess in program-gen of how those will look even when we their schema is `nil`. 
The option `pcl.SkipResourceTypechecking` is already enabled for `pulumi convert` and it can be disabled when running in _strict_ mode `pulumi convert --strict` 
A similar feature is still be needed for unknown _invokes_ but that can be tackled in a separate PR

[pcl/binder] Extend SkipResourceTypechecking to allow binding and generating unknown resources

---

changelog/pending/20230619--sdk-nodejs--write-port-to-stdout-as-a-string-so-node-doesnt-colorize-the-output.yaml
sdk/nodejs/cmd/dynamic-provider/index.ts
sdk/nodejs/provider/server.ts

Node's `console.log` colors numbers by default if it thinks that the output is a terminal (unless `NO_COLOR` is set). At least one user is running into a case where the port is being outputted surrounded with color codes, when using a dynamic provider on Node v20.3.0. To mitigate, we can update the places where we use `console.log(port)`, converting the number to a string first.
Fixes #13150

[sdk/nodejs] Write port as string to avoid colorized output

---

changelog/pending/20230616--programgen--allow-traversing-unknown-properties-from-resources-when-skipping-resouce-type-checking.yaml
pkg/codegen/pcl/binder_resource.go
pkg/codegen/pcl/binder_test.go
pkg/codegen/pcl/resource.go

When using the `pcl.SkipResourceTypechecking` we want to make it such that it allows traversal of unknown properties in a resource. For example, this program:
```
resource randomPet "random:index/randomPet:RandomPet" {
prefix = "doggo"
}
output "mainId" {
value = randomPet.unknownProperty
}
```
Should binds without errors when using `pcl.SkipResourceTypechecking` but fails to bind otherwise (in strict mode). This PR addresses this case and adds a couple more unit tests to document the behaviour of `pcl.SkipResourceTypechecking`

[pcl/binder] Allow traversing unknown properties from resources when skipping type checking

---

pkg/backend/httpstate/client/api.go
pkg/backend/httpstate/client/api_test.go
pkg/backend/httpstate/client/client.go

Switches the httpClient interface in httpstate
from accepting a `retryAllMethods` boolean
to an enum capable of representing another state: retry nothing.
With this, it's possible to call `httpClient.Do(..)`
and make a request without any retries.
Step towards #13166

httpstate/client: Support no retries

---

scripts/get-job-matrix.py

Temporarily bump the Windows runner size to unblock merging. I'll open an issue to root cause the actual issue and then we can move back to a lower size.

Temporarily bump Windows runner size to unblock merging

---

.github/workflows/ci-lint.yml

The golangci-lint-action comes with its own caching logic,
which includes caching Go build data.
We should not have setup-go caching enabled in that case.
ref: https://github.com/golangci/golangci-lint-action#how-to-use
Note the `cache: false`.
Note that usually setup-go doesn't take much time,
but sometimes it fails while downloading or uploading the cache.
This just drops an occasional source of flakiness in the job.

ci(lint): Disable setup-go cache for golangci-lint

---

changelog/pending/20230616--cli--pulumi-convert-will-now-cleanup-temporary-pulumi-convert-directories-when-the-command-is-finished.yaml
pkg/cmd/pulumi/convert.go

One very user visible change here is that we'll now cleanup the temporary pulumi-convert at the end of the command. Also a less obvious but helpful change is we'll shut down the converter earlier, there's no need to leave it live while we run codegen.

Couple of convert cleanups

---

changelog/pending/20230620--cli-display--fix-large-integers-displaying-in-scientific-notation.yaml
pkg/backend/display/object_diff.go
pkg/backend/display/object_diff_test.go

Fixes https://github.com/pulumi/pulumi/issues/13016

Don't print large integers in scientfic notation

---

changelog/pending/20230620--cli-config--no-longer-error-on-directory-read-permissions-when-searching-for-project-files.yaml
sdk/go/common/workspace/paths.go
sdk/go/common/workspace/paths_test.go

Fixes https://github.com/pulumi/pulumi/issues/12481
When searching directories for a Pulumi.yaml we'll return `ErrProjectNotFound` if we hit permission errors rather than the raw permission error. This helps when using pulumi under an unreadable root file system.

Translate permission errors into ProjectNotFound when searching

---

changelog/pending/20230620--sdkgen-python--python-sdk-only-prints-a-function-invoke-results-deprecation-messages-when-using-getters-rather-than-on-instantiation.yaml
pkg/codegen/python/gen.go
pkg/codegen/testing/test/testdata/external-resource-schema/python/pulumi_example/arg_function.py
pkg/codegen/testing/test/testdata/functions-secrets/python/pulumi_mypkg/func_with_secrets.py
pkg/codegen/testing/test/testdata/output-funcs-edgeorder/python/pulumi_myedgeorder/list_configurations.py
pkg/codegen/testing/test/testdata/output-funcs-edgeorder/python/pulumi_myedgeorder/list_product_families.py
pkg/codegen/testing/test/testdata/output-funcs-tfbridge20/python/pulumi_mypkg/get_ami_ids.py
pkg/codegen/testing/test/testdata/output-funcs-tfbridge20/python/pulumi_mypkg/list_storage_account_keys.py
pkg/codegen/testing/test/testdata/output-funcs/python/pulumi_mypkg/func_with_all_optional_inputs.py
pkg/codegen/testing/test/testdata/output-funcs/python/pulumi_mypkg/func_with_default_value.py
pkg/codegen/testing/test/testdata/output-funcs/python/pulumi_mypkg/func_with_dict_param.py
pkg/codegen/testing/test/testdata/output-funcs/python/pulumi_mypkg/func_with_list_param.py
pkg/codegen/testing/test/testdata/output-funcs/python/pulumi_mypkg/get_bastion_shareable_link.py
pkg/codegen/testing/test/testdata/output-funcs/python/pulumi_mypkg/get_client_config.py
pkg/codegen/testing/test/testdata/output-funcs/python/pulumi_mypkg/get_integration_runtime_object_metadatum.py
pkg/codegen/testing/test/testdata/output-funcs/python/pulumi_mypkg/list_storage_account_keys.py
pkg/codegen/testing/test/testdata/plain-object-defaults/python/pulumi_example/func_with_all_optional_inputs.py
pkg/codegen/testing/test/testdata/plain-object-disable-defaults/python/pulumi_example/func_with_all_optional_inputs.py
pkg/codegen/testing/test/testdata/provider-config-schema/python/pulumi_configstation/func_with_all_optional_inputs.py
pkg/codegen/testing/test/testdata/regress-8403/python/pulumi_mongodbatlas/get_custom_db_roles.py
pkg/codegen/testing/test/testdata/regress-py-12546/python/pulumi_plant/tree/v1/rubber_tree.py
pkg/codegen/testing/test/testdata/regress-py-tfbridge-611/python/pulumi_aws/x/iam/get_policy_document.py
pkg/codegen/testing/test/testdata/simple-resource-schema-custom-pypackage-name/python/custom_py_package/arg_function.py
pkg/codegen/testing/test/testdata/simple-resource-schema/python/pulumi_example/arg_function.py
pkg/codegen/testing/test/testdata/simple-yaml-schema/python/pulumi_example/arg_function.py

remove deprecation warning on result types unless using getters.
Fixes #11739

[sdk/python] remove deprecation warning on result types unless using getters.

---

changelog/pending/20230620--cli--make-no-retry-attempts-for-the-pulumi-new-version-query.yaml
pkg/backend/httpstate/client/client.go
pkg/cmd/pulumi/pulumi_test.go

Changes the httpstate client to not retry requests to
`GET /api/cli/version` so as not to block the CLI for 7 seconds
in airgapped environments and the like.
Testing:
Before this change, the accompanying test took 7 seconds to fail.
With this change, it succeeds nearly instantly.
Resolves #13166

{cli, httpstate}: Don't retry GetCLIVersionInfo

---

changelog/pending/20230620--cli-plugin--plugin-rm-yes-command-to-say-plugins-were-removed.yaml
pkg/cmd/pulumi/plugin_rm.go

Fixes #12719
Previously, deleting all plugins with the `--yes` flag prints this message:
```
𝛌 pulumi plugin rm -ay                    
This will remove 2 plugins from the cache:
resource cloudflare-5.0.0
resource gcp-5.0.0
```
After this change, we output the list of removed plugins explicitly:
```
𝛌 pulumi plugin rm -ay                    
resource aws-5.24.0 removed.
resource aws-5.25.0 removed.
```
The prompt still works, and we list plugins twice to confirm that deletion was successful:
```
𝛌 pulumi plugin rm -a
This will remove 2 plugins from the cache:
resource aws-5.24.0
resource aws-5.25.0
Please confirm that this is what you'd like to do by typing `yes`: yes
resource aws-5.24.0 removed.
resource aws-5.25.0 removed.
```

Split user output for plugin rm to confirmation and result log

---

changelog/pending/20230620--cli-display--update-summary-is-now-correctly-shown-when-advisory-and-disabled-policy-events-are-encountered.yaml
pkg/backend/display/diff_test.go
pkg/backend/display/progress.go

This change causes only mandatory policy violations to skip the summary display causing the resources changed and duration details to not be printed.
Policy Violations are categorized as `mandatory`, `disabled`, and `advisory`. We were treating all 3 as policy violations to skip displaying the update summary. Now we only use `mandatory`.
Fixes #13109

CLI update summary now shows after non-mandatory policy events seen.

---

changelog/pending/20230620--cli-new--pulumi-new-now-correctly-supports-numeric-stack-names.yaml
pkg/cmd/pulumi/new_acceptance_test.go
sdk/go/common/workspace/templates.go

`pulumi new` now correctly serializes a stack name of 123456 as a string in the `Pulumi.yaml` file.
Previously `123456` is interpreted as a number in YAML by default.
Fixes #12136

`pulumi new` now supports numeric stack names.

---

pkg/codegen/nodejs/gen_program.go

Fixes #10776
Examples of generated files:
tsconfig.js:
```json
{
"compilerOptions": {
"strict": true,
"outDir": "bin",
"target": "es2016",
"module": "commonjs",
"moduleResolution": "node",
"sourceMap": true,
"experimentalDecorators": true,
"pretty": true,
"noFallthroughCasesInSwitch": true,
"noImplicitReturns": true,
"forceConsistentCasingInFileNames": true
},
"files": [
"index.ts",
]
}
```
package.json
```json
{
"name": "simple-yaml",
"devDependencies": {
"@types/node": "^14"
},
"dependencies": {
"typescript": "^4.0.0",
"@pulumi/pulumi": "^3.0.0",
"@pulumi/aws-native": "*"
}
}
```

Remove extra tab that convert TS outputs in JSON file

---

changelog/pending/20230620--cli--fix-markdown-formatting-issues-in-command-usage.yaml
pkg/cmd/pulumi/logout.go
pkg/cmd/pulumi/state_delete.go
pkg/cmd/pulumi/state_rename.go

Fixes a couple of Markdown formatting issues
in the output of `gen-markdown`.
This is used as input to this section of the Pulumi website:
<https://www.pulumi.com/docs/cli/commands/>
Differences in gen-markdown output following this change:
diff -u before/pulumi_logout.md after/pulumi_logout.md
--- before/pulumi_logout.md	2023-06-20 15:20:06
+++ after/pulumi_logout.md	2023-06-20 15:20:17
@@ -19,6 +19,7 @@
If no URL is provided, you will be logged out of the current backend.
If you would like to log out of all backends simultaneously, you can pass `--all`,
+
$ pulumi logout --all
```
diff -u before/pulumi_state_delete.md after/pulumi_state_delete.md
--- before/pulumi_state_delete.md	2023-06-20 15:20:06
+++ after/pulumi_state_delete.md	2023-06-20 15:20:17
@@ -20,12 +20,15 @@
Make sure that …
```

cli: Fix Markdown reference formatting issues

---

changelog/pending/20230621--cli--fix-stack-rm-removing-config-files-for-the-wrong-project.yaml
pkg/cmd/pulumi/stack_rm.go
sdk/go/common/testing/environment.go
tests/integration/integration_test.go

Fixes https://github.com/pulumi/pulumi/issues/12246

Fix `stack rm` removing config files for the wrong project

---

changelog/pending/20230621--cli-display--fix-formatting-bugs-in-display-causing-text-like-missing-showing-in-output.yaml
pkg/backend/display/diff.go
pkg/backend/display/testdata/not-truncated/stack-output-resource-diff.json.stdout.txt
pkg/backend/display/testdata/not-truncated/template-body.json.stdout.txt
pkg/backend/display/testdata/not-truncated/up-2.json.stdout.txt
pkg/backend/display/testdata/not-truncated/up-3.json.stdout.txt
pkg/backend/display/testdata/not-truncated/up-4.json.stdout.txt
pkg/backend/display/testdata/not-truncated/up-5.json.stdout.txt
pkg/backend/display/testdata/not-truncated/up.json.stdout.txt
pkg/backend/display/testdata/not-truncated/webserver-userdata.json.stdout.txt
pkg/backend/display/testdata/truncated/up-truncate.json.stdout.txt

Fixes https://github.com/pulumi/pulumi/issues/11990
There were a few places we were passing an already formatted string in as the format argument for printf. This replaces those calls with non-formatting print calls.

Don't use printf without a fixed format string

---

changelog/pending/20230620--sdk-python--allow-tuples-as-sequence-input-values-to-resources.yaml
sdk/python/lib/pulumi/runtime/rpc.py
sdk/python/lib/test/test_next_serialize.py

Fixes https://github.com/pulumi/pulumi/issues/7029
For some reason the python RPC serializer explictly disallowed tuple, despite python codegen outputing types using `Sequence` rather than `List` suggesting that `tuple` would be acceptable.

Allow tuples as sequences in Python serialization

---

changelog/pending/20230621--cli-new--fix-empty-config-values-being-added-to-the-config-file-as-part-of-new.yaml
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/new_test.go
pkg/cmd/pulumi/up.go

Fixes https://github.com/pulumi/pulumi/issues/4081
Also plumbs the prompt function down to `promptForConfig` so this can be tested.

Don't save empty config values to the config file in new

---

changelog/pending/20230621--cli-display--on-windows-make-pulumi-state-unprotect-command-suggestion-use-double-quotes-instead-of-single-quotes.yaml
pkg/resource/deploy/step.go
pkg/resource/deploy/step_generator_test.go
sdk/go/common/resource/urn.go

Error messages would suggest the command `pulumi state unprotect 'urn'` on Windows which was not a valid quoting and now windows displays: `pulumi state unprotect "urn"`.
Fixes #13045

pulumi state unprotect command now uses OS specific quoting

---

changelog/pending/20230622--programgen-go--use-raw-string-literals-for-long-multi-line-strings.yaml
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/multiline-string-pp/dotnet/multiline-string.cs
pkg/codegen/testing/test/testdata/multiline-string-pp/go/multiline-string.go
pkg/codegen/testing/test/testdata/multiline-string-pp/multiline-string.pp
pkg/codegen/testing/test/testdata/multiline-string-pp/nodejs/multiline-string.ts
pkg/codegen/testing/test/testdata/multiline-string-pp/python/multiline-string.py

We already have logic in place to generate mutliline strings with
backticks if they meet certain conditions in genTemplateExpression.
However, the logic came into effect only if the string was complex
enough to warrant use of `Sprintf`
because the function short circuits to just printing a string literal
if the string doesn't need a `Sprintf`.
This changes genStringLiteral to be responsible for the decision
of whether the string warrants backticks or not,
retaining the prior conditions on whether the string would benefit
from being split across multiple lines.
Resolves #12358

fix(codegen/go): Use raw string literals for multiline-strings

---

pkg/cmd/pulumi/new_acceptance_test.go

`TestCreatingStackWithNumericName` is failing due to using a constant project name. A failed test run may leave a project behind so we now use a unix timestamp to try to guarantee uniqueness.

Fix failing test TestCreatingStackWithNumericName

---

changelog/pending/20230622--cli-state--disallow-renaming-resources-to-invalid-names-that-will-corrupt-the-state.yaml
pkg/cmd/pulumi/state_rename.go
pkg/cmd/pulumi/state_rename_test.go

Check that resource names are valid
before renaming a resource and possibly corrupting the stack.
Resource names are `QName`s, so we rely on tokens.IsQName for this.
Resolves #11746

cli(state/rename): Validate new name before renaming

---

changelog/pending/20230620--programgen-go--fix-aliasing-package-names-using-dashes-when-schema-doesnt-include-go-package-info-override.yaml
pkg/codegen/go/gen_program.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/using-dashes-1.0.0.json
pkg/codegen/testing/test/testdata/using-dashes-pp/dotnet/using-dashes.cs
pkg/codegen/testing/test/testdata/using-dashes-pp/go/using-dashes.go
pkg/codegen/testing/test/testdata/using-dashes-pp/nodejs/using-dashes.ts
pkg/codegen/testing/test/testdata/using-dashes-pp/python/using-dashes.py
pkg/codegen/testing/test/testdata/using-dashes-pp/using-dashes.pp
pkg/codegen/testing/utils/host.go

Fixes #13200 such that if a package doesn't have a specific go package override (like the one mentioned in the bug report) and needs an alias (because of using hypthens) then we apply aliasing for it. 
The PR adds a small synthetic schema called `using-dashes` that doesn't have any special go package info overrides and generates test programs from it.

[program-gen/go] Fix aliasing package names using dashes when schema doesn't include package info

---

changelog/pending/20230601--cli-state--the-upgrade-command-now-prompts-the-user.yaml
pkg/cmd/pulumi/state_upgrade.go
pkg/cmd/pulumi/state_upgrade_test.go
pkg/go.mod
pkg/go.sum
sdk/go/pulumi-language-go/go.sum
sdk/nodejs/cmd/pulumi-language-nodejs/go.sum
tests/go.sum

When running 'pulumi state upgrade', supply the
ProjectsForDetachedStacks option to the file state backend so that we
get asked to fill in project names for stacks where we could not guess
them automatically.
The implementation of the prompt is straightforward:
For each stack, ask a question with the survey package
and feed the result back to the filestate backend.
Testing this is a bit complicated because terminals are involved.
The test for this uses the go-expect and vt10x libraries
recommended in the documentation for survey.
It uses them to simulate a terminal emulator and acts on the output.
The pty library is used to create a compatible pseduo-terminal.
Unfortunately, these test libraries rely on Unix APIs and are not
available on Windows, so the test will not run on Windows …

cli(state upgrade): Prompt for project names for detached stacks

---

changelog/pending/20230623--engine--engine-marks-outputs-secret-if-an-output-of-the-same-name-is-marked-secret.yaml
pkg/engine/lifecycletest/step_generator_test.go
pkg/resource/deploy/step_executor.go

This makes the engine mark outputs as secret if there is an input of the same name that is marked secret.
It is an undesirable experience for a user to have an input secret leaked by an output of the same name by a misbehaving provider.
Fixes #4957

Mark outputs secret if there is a matching secret input.

---

changelog/pending/20230622--cli--stack-output-on-the-console-no-longer-escapes-html-characters-inside-json-strings.yaml
pkg/cmd/pulumi/stack.go
pkg/cmd/pulumi/stack_output_test.go
pkg/cmd/pulumi/stack_test.go
pkg/cmd/pulumi/util.go
pkg/cmd/pulumi/util_test.go

For the default `pulumi stack output` (writing to the console),
don't escape HTML characters inside JSON strings.
The only way to control this in Go is with `json.Encoder`.
However, that unconditionally places a newline at the end,
so we have to strip that for our use case.
Testing:
TestStringifyOutput was turned into a table test.
That's in an independent commit without any other changes.
Resolves #10561

fix(cli/stack output): Don't escape HTML characters

---

changelog/pending/20230624--auto-nodejs--adds-a-better-error-message-for-invalid-nodejs-autoapi-workdir.yaml
sdk/nodejs/automation/localWorkspace.ts
sdk/nodejs/tests/automation/localWorkspace.spec.ts

If you supply a workDir to a NodeJS AutoAPI LocalWorkspace, it does not validate its correctness, and proceeds to use it when trying to spawn commands. That leads to misleading and confusing "Command failed with ENOENT: pulumi version" error messages, making it look like the issue is a missing `pulumi` binary on your PATH. This changes to eagerly check and issue a more friendly error message. Fixes #13274.

Add a better error message for invalid NodeJS AutoAPI workdir

---

changelog/pending/20230623--cli-display--print-the-summary-event-for-previews-that-contain-non-error-level-diagnostic-messages.yaml
pkg/backend/display/diff.go
pkg/backend/display/progress.go
pkg/backend/display/progress_test.go

Pulumi previews now print the summary event if there are diagnostic messages. The display will not print the summary if there are error diagnostics.
Fixes #10880

Print update summary in preview even if there are diagnostics.

---

changelog/pending/20230622--programgen-nodejs-python--prefer-output-versioned-invokes-in-generated-programs-for-nodejs-and-python.yaml
pkg/cmd/pulumi/convert.go
pkg/codegen/pcl/binder.go
pkg/codegen/pcl/binder_component.go
pkg/codegen/pcl/invoke.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/aws-fargate-output-versioned-pp/aws-fargate-output-versioned.pp
pkg/codegen/testing/test/testdata/aws-fargate-output-versioned-pp/nodejs/aws-fargate-output-versioned.ts
pkg/codegen/testing/test/testdata/aws-fargate-output-versioned-pp/python/aws-fargate-output-versioned.py
sdk/go/pulumi-language-go/main.go
sdk/nodejs/cmd/pulumi-language-nodejs/main.go

This PR implements a new PCL bind option called `PreferOutputVersionedInvokes` which as the name suggests gives higher priority to using output-versioned invokes in generated programs if they exist* but only for python and nodejs. Previously we have enabled this for all languages but it breaks go and dotnet programs so here it is only applied to python and typescript. 
Binding component programs carry over this option if the main program has it too. 
This work is a continuation of #13051
<details>
<summary>PCL program example</summary>
```
vpc = invoke("aws:ec2:getVpc", {
default = true
})
subnets = invoke("aws:ec2:getSubnetIds", {
vpcId = vpc.id
})
resource webSecurityGroup "aws:ec2:SecurityGroup" {
vpcId = vpc.id
egress = [{
protocol = "-1"
fromPort = 0
toPort = 0
cidrBlocks = …
```

[convert] Prefer output-versioned invokes in generated programs for nodejs and python

---

pkg/cmd/pulumi/main.go
pkg/cmd/pulumi/main_test.go

Implement the necessary steps to avoid swallowing nil panics in out global recover statement. While we don't have any `panic(nil)` in our codebase right now, we should still handle this case correctly.

Don't discard `nil` panics

---

changelog/pending/20230626--cli-package--fixes-resolving-plugins-when-they-are-not-yet-installed-in-plugin-cache.yaml
pkg/cmd/pulumi/package.go
sdk/go/common/testing/environment.go
tests/smoke_test.go

Fixes #13279 resolving plugins with package get-schema and get-mapping when the plugins are not yet installed. 
also adds smoke tests to verify that it actually works for both `package get-schema` and `package get-mapping` which use the same codepath that was failing.

[cli] Fix resolving plugins with package get-schema and get-mapping

---

changelog/pending/20230626--cli--improve-the-cli-stack-validation-error-message.yaml
pkg/backend/httpstate/backend.go
pkg/util/validation/stack.go
pkg/util/validation/stack_test.go

Previously, the error message was:
```
error: a stack name may only contain alphanumeric, hyphens, underscores, or periods
```
This wasn't great because it lacked specificity, but was especially bad if candidate stack name was >100 characters or empty.
The new error messages are as follows:
1. If empty: "a stack name may not be empty"
2. If >100 chars: "a stack name cannot exceed 100 characters"
3. If it contains invalid characters: "a stack name may only contain alphanumeric, hyphens, underscores, or periods: invalid character %q at position %d" (with the appropriate values filled in).
In addition, this PR unifies the http backend stack name validation into a single function.

Improve the stack validation error message

---

pkg/cmd/pulumi/import.go

Fixes https://github.com/pulumi/pulumi/issues/13062

Fix import error messages

---

changelog/pending/20230628--cli-state--add-interactive-urn-selection-to-pulumi-state-rename-unprotect-delete.yaml
pkg/cmd/pulumi/state.go
pkg/cmd/pulumi/state_delete.go
pkg/cmd/pulumi/state_rename.go
pkg/cmd/pulumi/state_rename_test.go
pkg/cmd/pulumi/state_unprotect.go
pkg/cmd/pulumi/util.go

Using `pulumi state {delete,rename,unprotect}` to perform state edits requires knowing the relevant resource URN ahead of time. It's common to know part of the URN you want (say, the name) but not have the full URN memorized. 
We should allow the user to omit the URN, and then allow the user to select from the list of valid URNs in the current stack.

Support interactive state edits

---

changelog/pending/20230628--sdkgen--fix-loading-schemas-from-providers-on-path.yaml
pkg/cmd/pulumi/package.go
pkg/codegen/schema/loader.go
pkg/resource/deploy/deploytest/pluginhost.go
pkg/resource/deploy/providers/registry_test.go
pkg/workspace/plugin.go
sdk/go/common/resource/plugin/host.go

Fixes https://github.com/pulumi/pulumi-terraform-bridge/issues/1247
When running tfgen the provider plugin is generally only available on PATH, not in the plugins directory. The schema loader was only checking the plugins directory to decided if it had a resource provider already installed, and so sent off lots of github requests to lookup latest versions of plugins while running example conversion.
This changes the schema loader to use the same logic we use elsewhere where we try to use the provider (which will also look at PATH) and then if we get a missing plugin error we'll do the install and then try again.
I've also moved the `SetKnownPluginDownloadURL` call into workspace.InstallPlugin so we don't forget to call it before passing specs in.
Finally I've also removed the …

Don't try to install provider during schema loading unless missing

---

.github/workflows/ci-lint.yml
.golangci.yml

Upgrade the version of `golangci-lint` used in CI from `v1.52` to `v1.53` (latest).
This requires to a small adjustment to `nakedret` to keep our code passing `golangci-lint`. I think 60 lines is a reasonable limit, since a 60 line function still fits on a laptop screen.

Increase nakedret limit to 60

---

.github/workflows/ci-build-binaries.yml

GoReleaser 1.19.0 was released earlier today and doesn't currently work. Pin to the previous version to unblock CI until we understand what the underlying problem is.

Pin GoReleaser to previous version

---

pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/new_acceptance_test.go
pkg/cmd/pulumi/new_test.go

TestCreatingProjectWithEmptyConfig appears to be broken on master:
```
=== Failed
=== FAIL: cmd/pulumi TestCreatingProjectWithEmptyConfig (0.00s)
new_test.go:330:
Error Trace:	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/new_test.go:330
Error:      	Received unexpected error:
A project with this name already exists
Test:       	TestCreatingProjectWithEmptyConfig
=== FAIL: cmd/pulumi TestCreatingProjectWithEmptyConfig (re-run 1) (0.28s)
new_test.go:330:
Error Trace:	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/new_test.go:330
Error:      	Received unexpected error:
A project with this name already exists
Test:       	TestCreatingProjectWithEmptyConfig
```
As seen in #13323 and the attempts to land #13322.
To reduce likelihood of "name already exists" errors,
generate a random name for …

test: Attempt to fix TestCreatingProjectWithEmptyConfig

---

pkg/cmd/pulumi/new_acceptance_test.go
pkg/cmd/pulumi/new_test.go
pkg/cmd/pulumi/policy_new_acceptance_test.go
pkg/cmd/pulumi/policy_new_test.go

Using `t.TempDir()` or a hex-encoded string isn't enough
because the name may start with a number.
This switches all such temporary directories to use:
$tempDir/test-$random
Where `$tempDir` is managed by the current test.
This will address flaky errors like:
```
=== FAIL: cmd/pulumi TestCreatingStackWithArgsSpecifiedOrgName (0.69s)
new_test.go:74:
Error Trace:	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/new_test.go:74
Error:      	Received unexpected error:
'001' is not a valid project name. a project with this name already exists: 001
Test:       	TestCreatingStackWithArgsSpecifiedOrgName
```
Because the temporary directory was:
/tmp/TestCreatingStackWithArgsSpecifiedOrgName963299567/001

test(cmd/pulumi): Always use a valid project directory name

---

.github/workflows/ci.yml

The CI test matrix generator expects every module that we want to test
to be provided explicitly.
Since the Go and Node hosts became independent Go modules,
we haven't been running their unit tests in CI.
Fortunately, the tests still pass today,
but we need to include these in the build.

ci: Include Go and NodeJS hosts in unit tests

---

scripts/go-wrapper.sh

Previously, it was necessary to enable cgo
and use the system's DNS resolver on macOS.
In Go 1.20, the `net` package was rewritten
to not use cgo at all,
so CGO_ENABLED no longer has any effect there.
In fact, ever since 389860058dd6be35e1adf27b74b062ac180d819d,
this setting has been meaningless
because we've been building Darwin binaries
on Ubuntu machines (so cgo can't be enabled anyway).
This commit just deletes this now-unused block.

ci/build-binaries: Don't enable cgo for Darwin

---

.github/workflows/periodic-coverage.yml

We recently started capturing coverage data for Pull Requests again
but we omitted tracking for master.
Part of the reason for this is that the our CI setup uses the same
binaries that were used for the end-to-end tests as part of the release.
And we don't want to upload the coverage-instrumented binaries for a
release.
This is fixable, but instead of making our CI set up even more complex,
this introduces a new workflow to test master periodically.
This workflow will run every 12 hours, running all tests on master,
with acceptance tests on both Windows and macOS,
track coverage for all of this, and post that to codecov.
We'll be able to track code coverage trends on master in Codecov.

ci(new workflow): Run tests on master every 12 hours

---

sdk/python/lib/pulumi/resource.py

Looks like this was copied from the Node.js SDK. It should be `ROOT_STACK_RESOURCE` not `rootStackResource` for Python.

[sdk/python] Fix comment about `ROOT_STACK_RESOURCE`

---

.github/workflows/on-release-manual-dispatch.yml
.github/workflows/release.yml
scripts/publish_npm.sh

Publishing v3.74.0 to npm failed with `../../scripts/publish_npm.sh: line 13: my_array[2]: unbound variable`.
This commit temporarily changes the `publish_npm.sh` script to not have the unbound variable and comments out jobs in the release workflow that already succeeded, and adds a way to manually dispatch the release workflow to unblock the release. Will use that to re-run the release workflow.
Afterwords, we can revert and address the actual issue.

Temp changes to unblock the release

---

changelog/pending/20230622--cli-new--when-providing-a-stack-and-name-to-pulumi-new-the-project-names-must-match-before-creating-pulumi-yaml.yaml
pkg/backend/mock.go
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/new_test.go
pkg/go.mod

`pulumi new` `--stack` and `--name` check that the project name matches before creating a new project.
Fixes #13248

fix `pulumi new` creates new project when stack reference project name and project name don't match

---

scripts/publish_npm.sh

It looks like the intention of this script was to parse `GITHUB_REF` values in the form `refs/heads/<branch_name>` or `refs/tags/<tag_name>` per https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables, but we overwrite this envvar in the workflow:
https://github.com/pulumi/pulumi/blob/53e205f08fc08f3388e2a63d0335b8e3a8c93a71/.github/workflows/release.yml#L54
Which is passed along from here:
https://github.com/pulumi/pulumi/blob/53e205f08fc08f3388e2a63d0335b8e3a8c93a71/.github/workflows/on-release.yml#L37
Which is just the tag name.
Still unclear how this worked for previous releases, but the script errored for the latest release when `GITHUB_REF` was just `v3.74.0`.
This commit makes the script resilient to values of `GITHUB_REF` that don't have …

Fix `publish_npm.sh` script to handle `GITHUB_REF` without '/'

---

sdk/go/Makefile

`pulumi-language-go` was changed to be an independent go module, and `go install` needs to be run from the module directory. We updated the other targets, but missed updating `dist`, which this commit does.
Fixes #13335

[sdk/go] Fix the `dist` make target

---

changelog/pending/20230622--cli-new--pulumi-new-s-org-project-stack-checks-the-specified-organization-for-project-existence-rather-than-the-currentuser.yaml
pkg/backend/backend.go
pkg/backend/filestate/backend.go
pkg/backend/filestate/backend_test.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/backend_test.go
pkg/backend/mock.go
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/new_test.go
tests/stack_test.go

`pulumi new -s 'org/project/stack'` checks the proper organization for project existence rather than `backend.currentUser()`'s org.
Fixes #7423
Fixes #10748 
TODO

[cli] make `pulumi new` properly check for project name existence at org level.

---

sdk/python/lib/setup.py
sdk/python/requirements.txt

Upgrades to the latest release of grpcio for the Python SDK.
Supersedes #13421, #13425
Fixes CVE-2023-32731

deps(py): upgrade to latest grpcio

---

changelog/pending/20230629--sdk-python--python-dynamic-provider-serialized-code-is-now-saved-to-state-as-secret.yaml
sdk/python/lib/pulumi/dynamic/dynamic.py
tests/integration/integration_python_acceptance_test.go

Short term workaround for https://github.com/pulumi/pulumi/issues/8265

Always mark dynamic provider code as secret

---

changelog/pending/20230630--sdk-nodejs--node-js-dynamic-providers-mark-serialized-functions-as-secret-if-they-capture-any-secrets.yaml
sdk/nodejs/dynamic/index.ts
tests/examples/dynamic-provider/secrets/.config/Pulumi.dev.yaml
tests/examples/dynamic-provider/secrets/.gitignore
tests/examples/dynamic-provider/secrets/Pulumi.yaml
tests/examples/dynamic-provider/secrets/index.ts
tests/examples/dynamic-provider/secrets/package.json
tests/examples/examples_test.go

This allows the function serialization used by dynamic providers to capture secrets, and if so, marks the resulting input value as a secret so that the `__provider` property will be a secret in the state.
Fixes https://github.com/pulumi/pulumi/issues/8265.

Allow Node.js dynamic providers to capture secrets

---

.github/workflows/ci-build-binaries.yml
.github/workflows/ci-run-test.yml

The setup-go step in ci-run-test never has a successful cache hit.
As a result of this, it spends 5 minutes in each test runner
just filling up the cache.
Per discussion with @AaronFriel,
this is an attempt to fix this issue with two changes:
- Actually use the gocache.tmp we generate
(this is used in other such jobs)
- Share the cache key with build-binaries.
Most tests run after build-binaries,
or begin running after build-binaries has finished.
Sharing the cache key there will be useful.

ci(test): Fix setup-go caching

---

changelog/pending/20230624--sdk-nodejs--add-dependency-on-atopentelemetry-instrumentation.yaml
sdk/nodejs/package.json
sdk/nodejs/yarn.lock

The Node.js SDK makes use of `@opentelemetry/instrumentation` directly in https://github.com/pulumi/pulumi/blob/2a69c252410a2d6ffd0bf48dc2c215f51317da0c/sdk/nodejs/cmd/run/tracing.ts#L24, but it is not specified as an explicit dependency in `package.json` -- we're relying on the indirect dependency from `@opentelemetry/instrumentation-grpc`.
This can break monorepo setups using npm workspaces. If there is another version of `@opentelemtry/instrumentation`, it is not hoisted for use by the Pulumi program, resulting in pulumi crashing with `error: Error: Cannot find module '@opentelemetry/instrumentation'`.
This change fixes this by explicitly declaring the version of `@opentelemetry/instrumentation` the SDK needs in `package.json`.
Fixes #13104

[sdk/nodejs] Add explicit dependency on @opentelemetry/instrumentation

---

changelog/pending/20230710--cli-plugin--fix-interpolation-of-vesion-into-http-plugin-source-urls.yaml
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_test.go

Turns out this wasn't tested and regressed in
https://github.com/pulumi/pulumi/commit/51cc6461df930b17e23d2d1408cc6110b1ede7be when we started URL parsing the input string and so ended up with a text string with "%7B" instead of "{" to replace.
This fixes the interpolation and changes a couple of the http tests to actually use this feature so it's tested.

Fix http source URL interpolation

---

changelog/pending/20230713--sdk-python--move-some-global-state-to-context-state-for-parallel-updates.yaml
sdk/python/lib/pulumi/automation/_server.py
sdk/python/lib/pulumi/runtime/invoke.py
sdk/python/lib/pulumi/runtime/mocks.py
sdk/python/lib/pulumi/runtime/resource.py
sdk/python/lib/pulumi/runtime/rpc.py
sdk/python/lib/pulumi/runtime/rpc_manager.py
sdk/python/lib/pulumi/runtime/settings.py
sdk/python/lib/pulumi/runtime/stack.py
sdk/python/lib/test/automation/test_isolation.py
sdk/python/lib/test/provider/test_server.py
sdk/python/lib/test/runtime/test_stack.py
sdk/python/lib/test/test_next_serialize.py
sdk/python/lib/test/test_output.py

Global variables cause issues when running programs in the same process in parallel which we can do with automation api, but also in the test framework. This changes the RPCManager to be a context variable on Settings, along with other "program global" data like the resource monitor and engine logger.

Make pythons RPCManager a context variable

---

changelog/pending/20230712--programgen--allow-binding-unsupported-range-and-collection-types-in-non-strict-mode-for-pulumi-convert.yaml
pkg/cmd/pulumi/convert.go
pkg/codegen/hcl2/model/binder_expression.go
pkg/codegen/hcl2/model/expression.go
pkg/codegen/hcl2/model/type_collection.go
pkg/codegen/pcl/binder.go
pkg/codegen/pcl/binder_component.go
pkg/codegen/pcl/binder_resource.go
pkg/codegen/pcl/binder_schema.go
pkg/codegen/pcl/binder_test.go
pkg/codegen/pcl/functions.go
pkg/codegen/pcl/rewrite_apply_test.go

This PR implements a new PCL option called `SkipRangeTypechecking` and using it for `pulumi convert` in non-strict mode. It allows unsupported range types such as unions to be bound while emitting a warning instead of an error. The same applies for `ForExpression` and `IndexExpression`
Supersedes #13446 and #13450 
Fixes a whole category of bind errors where the collection being iterated is not a supported type 
-  #13318 
-  #13430 partially
-  #13191
- #13440

[pcl/binder] Allow binding unsupported range and collection types in non-strict mode for pulumi convert

---

sdk/nodejs/output.ts
sdk/python/lib/pulumi/output.py
sdk/python/lib/test/test_output.py

Fixes some broken links pointing to the Inputs & Outputs docs.
Fixes #13461.

Fix links to outputs docs

---

changelog/pending/20230713--programgen--consistently-use-non-strict-bind-options-when-applicable.yaml
pkg/cmd/pulumi/convert.go
pkg/codegen/pcl/binder.go
sdk/go/pulumi-language-go/main.go
sdk/nodejs/cmd/pulumi-language-nodejs/main.go

When using `pulumi convert` in non-strict mode, provide a single source of which bind options to use. The newly added options weren't being applied in a few places

[convert] Consistently use the same non-strict bind options when applicable

---

changelog/pending/20230713--cli-plugin--automatically-install-pulumiverse-provider-plugins-during-convert.yaml
pkg/workspace/plugin.go

This enables the automatic install of pulumiverse plugins even without a version set, as the DownloadURL is now set before we try to do a version lookup allowing the version lookup to now query github.

Fill in default plugin download URL before looking up version

---

changelog/pending/20230713--programgen-go--fix-panic-in-generateproject-when-version-is-not-set-in-schema.yaml
pkg/codegen/go/gen_program.go
pkg/codegen/go/gen_program_test.go
pkg/codegen/testing/test/testdata/auto-deploy-0.0.1.json
pkg/codegen/testing/utils/host.go

When using `GenerateProject` from go codegen against an example using a schema _without_ a version, the code hit the path:
```go
fmt.Fprintf(&gomod, "	%s v%s\n", packageName, p.Version.String())
```
Where `p.Version` is nil. 
This PR fixes this issue by defaulting to an empty string when version isn't available. 
I wasn't able to use `ProgramTest` to test the new behavior because `ProgramTest` uses `GenerateProgram` rather than `GenerateProject` in the test body. Instead I made `GenerateProject` unit testable by separating the part where we generate files into `GenerateProjectFiles` from the part where we write them out to the file system and subsequently testing that `GenerateProjectFiles` doesn't panic against the newly added test schema. Confirmed that the code in `master` fails and …

[convert/go] Fix panic in GenerateProject when version is not set in schema

---

changelog/pending/20230714--programgen--propagate-skiprangetypechecking-option-down-to-program-components.yaml
pkg/codegen/pcl/binder.go
pkg/codegen/pcl/binder_component.go

The option was added only for top level programs but it should be propagated to component programs too.

[pcl/binder] Propagate SkipRangeTypechecking option down to components' programs

---

sdk/go/common/resource/plugin/langruntime_plugin.go

Small logging fix. The method is now just "Run" not "RunPlan", but more importantly this now logs the value of `bail` not just the error result.

Include bail result in Run log

---

changelog/pending/20230714--programgen-nodejs--improve-static-typing-of-config-variables-in-main-program.yaml
pkg/codegen/nodejs/gen_program.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/invoke-inside-conditional-range-pp/nodejs/invoke-inside-conditional-range.ts
pkg/codegen/testing/test/testdata/optional-complex-config-pp/nodejs/optional-complex-config.ts
pkg/codegen/testing/test/testdata/optional-complex-config-pp/optional-complex-config.pp

Right now when generating `config.getObject(...)` calls in for typescript, we miss a lot of provided static types from the program: optional types, lists, maps and objects. This PR improves the static typing of config variables _in the main program_ 
Fixes #13498
<details>
<summary>Example PCL program</summary>
```tf
config "vpcTag" "string" {
default = null
description = "The tag of the VPC"
}
config "vpcId" "string" {
default = null
description = "The id of a VPC to use instead of creating a new one"
}
config "subnets" "list(string)" {
default = null
description = "The list of subnets to use"
}
config moreTags "map(string)" {
default = null
description = "Additional tags to add to the VPC"
}
config userdata "object({path=string, content=string})" {
default = null
description = "The …
```

[programgen/typescript] Improve static typing of config variables in main program

---

pkg/backend/stack.go
pkg/backend/updates.go
pkg/cmd/pulumi/util.go
sdk/go/common/apitype/core.go
sdk/go/common/util/gitutil/git.go

These changes add the path to the current project relative to the root of the VCS repository to update metadata. If VCS info is not available, this metadata is not added.
Part of https://github.com/pulumi/home/issues/2946.

[cli] Add project root update metadata

---

changelog/pending/20230717--programgen-nodejs--fix-interpolated-strings-used-as-keys-of-maps.yaml
pkg/codegen/nodejs/gen_program_expressions.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/interpolated-string-keys-pp/interpolated-string-keys.pp
pkg/codegen/testing/test/testdata/interpolated-string-keys-pp/nodejs/interpolated-string-keys.ts
pkg/codegen/testing/test/testdata/interpolated-string-keys-pp/python/interpolated-string-keys.py

[typescript/program-gen] Fix interpolated strings used as keys of maps

---

sdk/python/lib/test/langhost/resource_op_bad_inputs/test_resource_op_bad_inputs.py
sdk/python/lib/test/langhost/util.py

We used to test that various errors we're written out to the user in these langhost tests, but at some point those test were removed (I suspect because we stopped printing them to stderr).
This adds in the ability to check for a log message in the engine diagnostics stream, and makes use of that in one of the tests.

Add the ability to verify an expected log message was written

---

changelog/pending/20230718--sdkgen-go-nodejs--fix-replaceonchanges-being-dropped-in-go-and-nodejs-codegen.yaml
pkg/codegen/schema/schema.go

Fixes https://github.com/pulumi/pulumi/issues/13492.

Fix ReplaceOnChanges being dropped in schema marshalling

---

changelog/pending/20230718--cli-plugin--fix-lookup-of-side-by-side-binaries-when-pulumi_ignore_ambient_plugins-is-set.yaml
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_test.go

If PULUMI_IGNORE_AMBIENT_PLUGINS was set then the `filename` variable was never initialized, This regressed in https://github.com/pulumi/pulumi/pull/13086.

Fix lookup of side-by-side binaries when PULUMI_IGNORE_AMBIENT_PLUGINS is set

---

changelog/pending/20230717--cli-config--pulumi-no-longer-falls-back-on-old-config-when-config-resolution-fails-except-for-pulumi-destroy-stack-stack-name-where-the-config-may-be-unavailable.yaml
pkg/cmd/pulumi/config.go
pkg/cmd/pulumi/config_test.go
pkg/cmd/pulumi/destroy.go

Pulumi no longer falls back on prior configuration on error getting configuration except for `pulumi destroy --stack <stack-name>` where a user may run `pulumi destroy` and the configuration may not be available.
Fixes #13487

Pulumi no longer falls back on old configuration by default.

---

changelog/pending/20230718--engine--validate-urns-passed-via-resourceoptions-are-valid.yaml
pkg/engine/lifecycletest/provider_test.go
pkg/engine/lifecycletest/pulumi_test.go
pkg/resource/deploy/source_eval.go
sdk/go/common/resource/urn.go

Fixes https://github.com/pulumi/pulumi/issues/13490.

Validate resource option URNs

---

changelog/pending/20230719--engine--add-a-missing-lock-that-could-cause-a-concurrent-map-read-write-panic.yaml
pkg/resource/deploy/providers/registry.go
pkg/resource/deploy/providers/registry_test.go

Fixes https://github.com/pulumi/pulumi/issues/13491.

Add missing map lock for Registry.RegisterAlias

---

changelog/pending/20230719--cli-new--fix-the-use-of-uninitalized-backend-when-running-new-with-generate-only-when-generate-only-is-set-new-will-skip-all-checks-that-require-the-backend.yaml
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/new_test.go

Fixes https://github.com/pulumi/pulumi/issues/13527.

Fix using backend in new when --generate-only is set

---

pkg/go.mod
pkg/go.sum

There are 1 security vulnerabilities found in github.com/moby/moby v23.0.0+incompatible
- [CVE-2023-28840](https://www.oscs1024.com/hd/CVE-2023-28840)
Upgrade github.com/moby/moby from v23.0.0+incompatible to 23.0.3 for vulnerability fix
Ideally, no insecure libs should be used.
By using the [GitHub Actions](https://github.com/murphysecurity/actions) configurations provided by murphysec, we can conduct automatic code security checks in our CI pipeline.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS

fix(sec): upgrade github.com/moby/moby to 23.0.3

---

changelog/pending/20230722--engine--fix-target-dependents-from-targeting-all-resources-with-default-providers.yaml
pkg/engine/lifecycletest/target_test.go
pkg/resource/deploy/step_generator.go

Fixes https://github.com/pulumi/pulumi/issues/13557.
A while ago we changed default providers to always count as targeted. Unfortunately that resulted in every resource being manged by a default provider being targeted when --target-dependents was set, which was not expected.
This change changes --target-dependents to not treat resources as targeted just because their default provider is targeted. Explicit providers which are targeted will cause all their managed resources to become targets.

Test and fix --target-dependents

---

sdk/go/common/resource/plugin/provider_plugin.go

Mostly for internal documentation. We should never call Delete at preview time, so the provider should always be configured with known values when we do call it.

Assert that we don't call Delete with unknowns

---

pkg/engine/lifecycletest/golang_sdk_test.go
pkg/engine/lifecycletest/provider_test.go
pkg/engine/lifecycletest/pulumi_test.go
pkg/resource/deploy/deploytest/provider.go
pkg/resource/deploy/source_eval_test.go

This is so we can access the other parts of ConstructInfo inside ConstructF functions in tests, same as CallInfo and CallF.

Add ConstructInfo to deploytest

---

changelog/pending/20230724--programgen-nodejs--fixes-issue-with-javascript-program-generation-where-enums-would-incorrectly-reference-the-package-rather-than-the-import-alias.yaml
pkg/codegen/nodejs/gen_program_expressions.go
pkg/codegen/nodejs/gen_program_test.go

Fixes #12986 
Fixes issue with javascript program generation where enums would incorrectly reference the package rather than the import alias.
There are changes being made to codegen testing (adding matrix testing) which is why a more extensive test is not being added.
Context:
NodeJS package aliases are generated using the following code
https://github.com/pulumi/pulumi/blob/917b2afdfcb9d797f5d756f6e9084717d2c57da6/pkg/codegen/nodejs/gen_program.go#L333
When a provider schema supplies a language specific package name for nodejs like
```json
{
"name": "pulumiservice",
"language": {
...
"nodejs": {
"packageName": "@pulumi/bar",
...
},
...
},
...
}
```
programgen would use `@pulumi/bar` rather than `pulumiservice`. for enums
```typescript
import * as pulumi from "@pulumi/pulumi";
import * …
```

Fix node programgen enum to use package identifier.

---

changelog/pending/20230725--engine--fix-a-panic-when-trying-to-construct-a-remote-component-with-an-explicit-provider-configured-with-unknown-values-during-preview.yaml
pkg/engine/lifecycletest/pulumi_test.go
sdk/go/common/resource/plugin/provider_plugin.go

Adds a test to check that we don't try to call Construct on providers when we haven't yet configured them (because config values were unknown).
This flagged that it was possible for a user program to trigger an assert in the engine Construct code, I've changed that to an error.

Test Construct on providers configured with unknown values

---

changelog/pending/20230626--programgen-go--fix-conflicting-imports-generated-when-two-imported-packages-have-the-same-name.yaml
pkg/codegen/go/gen_program.go
pkg/codegen/go/gen_program_test.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/modpath-pp/go/modpath.go
pkg/codegen/testing/test/testdata/regress-11176-pp/go/regress-11176.go
pkg/codegen/testing/test/testdata/regress-11176-pp/regress-11176.pp
pkg/codegen/testing/test/testdata/synthetic-resource-properties-pp/go/synthetic-resource-properties.go
pkg/codegen/testing/test/testdata/third-party-package-pp/go/third-party-package.go

This fixes how programgen generates import statements
to handle conflicting imports when two imported packages
have the same name, e.g.
github.com/pulumi/pulumi-aws/sdk/v5/go/aws/ecs
github.com/pulumi/pulumi-awsx/sdk/go/awsx/ecs
To do this, we add a fileImporter type that tracks these imports.
It prefers unnamed imports for packages unless one of the following is
true:
- the name of the package has already been used by another import
- the name of the package does not match the last component
of the import path (e.g., `example.com/foo-go` with `package foo`).
If the name has already been used by another import,
it attempts the following in-order:
- Combine the last two path components of the import path
into an identifier and use that if available.
e.g., `awsxs3` from `sdk/go/awsx/s3`.
- …

programgen(go): Handle conflicting names in imported packages

---

.github/workflows/ci-run-test.yml

For tests on Windows, don't run with data race detection.
This should reduce the time and memory it takes to run these tests,
hopefully reducing the runner disconnects we've been seeing.
Relates to #13238

ci(go): Don't run with -race on Windows

---

changelog/pending/20230726--sdkgen--fix-bug-binding-provider-schema-where-type-default-int-values-could-not-take-integers.yaml
pkg/codegen/schema/bind.go
pkg/codegen/schema/schema_test.go

Fixes #6469
From the issue:
The following type definition
```json
"myprovider:index:ResourceSignal": {
"properties": {
"Count": {
"type": "integer",
"default": 1
},
"Timeout": {
"type": "string",
"default": "PT5M"
}
},
"type": "object"
}
```
causes an error during schema import
```
panic: error importing schema: binding types: failed to bind type myprovider:index:ResourceSignal:
error binding default value for property "Count": invalid default of type int for integer property
```
Apparently, we only allow floats as defaults here. Changing to `1.0` makes the error go away.

[codegen] Fix bug in provider schema where default int properties could not be int

---

changelog/pending/20230725--sdkgen-python--fixes-python-external-enum-types-missing-the-import-reference-to-the-external-package.yaml
pkg/codegen/python/gen.go
pkg/codegen/testing/test/testdata/external-enum/docs/component/_index.md
pkg/codegen/testing/test/testdata/external-enum/python/pulumi_example/component.py

Fixes #12695
Python SDKGen was not correctly referencing external enum types which needed an import alias.

[sdkgen/python] SDKgen on external enums

---

pkg/cmd/pulumi/convert.go
pkg/cmd/pulumi/import.go
proto/.checksum.txt
proto/pulumi/converter.proto
sdk/go/common/resource/plugin/converter.go
sdk/go/common/resource/plugin/converter_plugin.go
sdk/go/common/resource/plugin/converter_plugin_test.go
sdk/go/common/resource/plugin/converter_server.go
sdk/go/common/resource/plugin/converter_server_test.go
sdk/proto/go/converter.pb.go
sdk/python/lib/pulumi/runtime/proto/converter_pb2.pyi

We called this Address in one part of the code, and Target in another. This just makes it consistent by calling it Target everywhere.

Make MapperAddress consistent everywhere by calling it MapperTarget

---

changelog/pending/20230727--sdk-python--output-from_input-now-recurses-into-tuples.yaml
sdk/python/lib/pulumi/output.py
sdk/python/lib/test/test_output.py

Fixes https://github.com/pulumi/pulumi/issues/6635.

Make `Output.from_input` recurse into tuples.

---

changelog/pending/20230726--programgen-dotnet--fix-typing-for-optional-and-complex-config-variables-in-main-program.yaml
pkg/codegen/dotnet/gen_program.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/invoke-inside-conditional-range-pp/dotnet/invoke-inside-conditional-range.cs
pkg/codegen/testing/test/testdata/optional-complex-config-pp/dotnet/optional-complex-config.cs

This PR adds support in dotnet program-gen for  optional and complex config variables. For Object-typed config variables, it will generate a class with the shape of the type, then later on during `config.GetObject<T>` it will use a reference to that type `T`
Similarly to complex types in component config variables, this does not implemented _nested_ objects yet but handles the most common cases. 
Fixes #13569

[dotnet/program-gen] Fix typing for optional and complex config variables in main program

---

changelog/pending/20230727--cli--fixes-for-pulumi-import.yaml
pkg/operations/operations_aws.go
pkg/operations/operations_aws_test.go
pkg/operations/operations_cloud_aws.go
pkg/operations/operations_cloud_aws_test.go
pkg/operations/resources.go

While many of the most fundamental limitations of `pulumi logs` are still dependent on moving this code out of pulumi/pulumi and into pulumi/pulumi-aws and other resource providers (https://github.com/pulumi/pulumi/issues/608), this PR implements a few more tactical fixes which improve some common scenarios.
Unfortunately, this whole area of the code is largely untested, in part because we didn't want to add a dependency on AWS in this layer (yet another reason we really want to do https://github.com/pulumi/pulumi/issues/608).  We could choose to further violate this layering and add tests here that use `pulumi-aws` to deploy Pulumi resources and then test them against this AWS operations provider.
In the meantime, I have manually validated fixes for the following issues.
Fixes #2665. …

A few fixes for `pulumi logs`

---

scripts/tidy.sh
tests/integration/go/regress-13301/go.mod.bad
tests/integration/integration_go_test.go

The regression test for #13301 needs an intentionally bad go.mod file.
This file was excluded from `make tidy`, allowing it to remain invalid,
but this doesn't protect it from bulk commands like the following
used in #13593
```bash
find . -name go.mod -exec dirname '{}' ';' | while read R; do
(cd "$R" && ... && go mod tidy)
done
```
In fact, #13593 accidentally tidied this go.mod file
(removing the extraneous dependencies critical to the regression test)
and failed in CI.
To prevent issues like this, rename the go.mod to go.mod.bad,
and rename it back to go.mod in the test environment at test time.
This also lets us revert the `make tidy` exclusion support in tidy.sh.

test(regress-13301): Avoid accidental tidying

---

changelog/pending/20230727--programgen-dotnet-go-nodejs-python--normalize-the-declaration-name-of-generated-resource-components.yaml
pkg/codegen/dotnet/gen_program.go
pkg/codegen/go/gen_program.go
pkg/codegen/nodejs/gen_program.go
pkg/codegen/pcl/component.go
pkg/codegen/python/gen_program.go
pkg/codegen/testing/test/testdata/components-pp/another-component/main.pp
pkg/codegen/testing/test/testdata/components-pp/components.pp
pkg/codegen/testing/test/testdata/components-pp/dotnet/AnotherComponent.cs
pkg/codegen/testing/test/testdata/components-pp/dotnet/components.cs
pkg/codegen/testing/test/testdata/components-pp/go/another-component.go
pkg/codegen/testing/test/testdata/components-pp/go/components.go
pkg/codegen/testing/test/testdata/components-pp/nodejs/another-component.ts
pkg/codegen/testing/test/testdata/components-pp/nodejs/components.ts
pkg/codegen/testing/test/testdata/components-pp/python/another_component.py
pkg/codegen/testing/test/testdata/components-pp/python/components.py

This PR adds a new function `DeclarationName()` to PCL components which is then used as the name of the component inside of the code, distinguishing it from the file name where it lives. The function returns a valid and idiomatic name to be used and references in the generated code for all of the language generators. 
For example if you have a component of which its source code files live `./some-component` then the declaration name for that component would be `SomeComponent` etc. 
Fixes #13151

[program-gen] Normalize the declaration name of generated resource components

---

changelog/pending/20230727--cli-plugin--cli-will-now-warn-when-loading-ambient-plugins-from-path.yaml
pkg/cmd/pulumi/plugin.go
pkg/engine/destroy.go
pkg/engine/plugins.go
pkg/engine/refresh.go
pkg/engine/update.go
sdk/go/common/resource/plugin/analyzer_plugin.go
sdk/go/common/resource/plugin/converter_plugin.go
sdk/go/common/resource/plugin/host.go
sdk/go/common/resource/plugin/langruntime_plugin.go
sdk/go/common/resource/plugin/provider_plugin.go
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_test.go

By default Pulumi will load ambient plugins from $PATH before looking in the plugins directory or at bundled plugins.
While this is very useful for development it often causes confusion when people have forgotten that they have plugins left on $PATH.
This makes the use of these $PATH plugins a diagnostic warning to try and make that failure mode a little less silent.
Normal users shouldn't ever have plugins on $PATH and so won't see this new warning.

Warn about ambient plugins loaded from $PATH

---

changelog/pending/20230727--sdk-nodejs--nodejs-programs-will-now-warn-that-undefined-values-will-not-show-as-stack-outputs.yaml
sdk/nodejs/runtime/stack.ts
tests/integration/integration_nodejs_test.go
tests/integration/nodejs/undefined-stack-output/Pulumi.yaml
tests/integration/nodejs/undefined-stack-output/index.ts

Fixes https://github.com/pulumi/pulumi/issues/7376

Warn about undefined stack outputs

---

changelog/pending/20230802--cli-state--fix-panic-in-pulumi-state-edit-when-no-stack-is-selected.yaml
pkg/cmd/pulumi/state_edit.go

Fixes #13637
`display.Options` has a `Colors` field where the default zero value (`""`) causes a panic. This was not specified in `pulumi state edit`'s `display.Options` and a panic occurs when no stack is selected. Fixed by providing a valid value.

Fix panic if colorizer is `""`

---

changelog/pending/20230504--cli-new--support-ssh-style-git-urls-including-for-pulumi-new-private-templates.yaml
pkg/cmd/pulumi/new.go
sdk/go.mod
sdk/go/common/env/env.go
sdk/go/common/util/env/env.go
sdk/go/common/util/env/env_test.go
sdk/go/common/util/gitutil/git.go
sdk/go/common/util/gitutil/git_test.go
sdk/go/common/workspace/templates.go

This is a continuation of https://github.com/pulumi/pulumi/pull/12818. Noteworthy changes:
* This uses the `ssh_config` library to handle edge cases like `Include` directives in `~/.ssh/config`.
* Catches `ssh.PassphraseMissingError` to determine when to prompt the user. Once https://github.com/go-git/go-git/issues/490 is resolved we will be able to avoid this prompt (in some situations) and use the same default credentials as git.
* The original PR only handled scp-style SSH URLs and assumed the user was always `git`, which is often but not always the case. We now leverage `go-git` to normalize SSH URLs into the `ssh://user@host/path` format, which as an added benefit allows us to re-use the existing parsing logic for `https://` URLs.
* `PULUMI_GITSSH_PASSPHRASE` is hooked up to `pulumi …

[cli/new] Support SSH-style Git URLs

---

pkg/codegen/testing/test/program_driver.go

regress-11176 is currently broken because it imports awsx which,
without https://github.com/pulumi/pulumi-awsx/pull/1066 released
pulls in an old version of google.golang.org/genproto,
and that conflicts with the newer version.
Details in https://github.com/pulumi/pulumi/issues/13644#issuecomment-1664711242
This change disables the test so that tests on master aren't red.
Refs #13644

test(codegen): Disable regress-11176

---

pkg/codegen/testing/test/program_driver.go

Revert the test disabled in #13649 to unblock master builds
now that pulumi-awsx has been released with
https://github.com/pulumi/pulumi-awsx/pull/1066.
This reverts commit e270756ca75c2984413a0bb32cc1b3206e9661cb.
Resolves #13644

Revert "test(codegen): Disable regress-11176"

---

changelog/pending/20230728--programgen-dotnet--fixes-code-generation-of-forexpressions-both-when-creating-a-list-or-a-dictionary.yaml
pkg/codegen/dotnet/gen_program_expressions.go
pkg/codegen/pcl/utilities.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/csharp-typed-for-expressions-pp/csharp-typed-for-expressions.pp
pkg/codegen/testing/test/testdata/csharp-typed-for-expressions-pp/dotnet/csharp-typed-for-expressions.cs
pkg/codegen/testing/test/testdata/entries-function-pp/dotnet/entries-function.cs

When using ForExpressions from PCL, the resulting expression is either a list or a dictionary. Right now the generate code only emits `IEnumerable` and only works for input lists. This PR updates dotnet program-gen to fully support `ForExpressions` when creating a list, in which case the previous expression would use a suffix `.ToList()`. When creating maps/dictionaries, the generated code will use `ToDictionary(item => <keyExpr>, item => <valueExpr>)` 
<details>
<summary>Example PCL</summary>
```
config egress "list(object({FromPort=int, ToPort=int}))" {
}
config tags "map(string)" {
default = {}
}
defaultVpc = invoke("aws:ec2:getVpc", {
default = true
})
// Create a security group that permits HTTP ingress and unrestricted egress.
resource webSecurityGroup "aws:ec2:SecurityGroup" { …
```

[dotnet/program-gen] Fixes code generation of ForExpressions

---

changelog/pending/20230731--programgen-dotnet--fixes-list-initializer-for-plain-lists-in-resource-properties.yaml
pkg/codegen/dotnet/gen_program.go
pkg/codegen/dotnet/gen_program_expressions.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/csharp-plain-lists-pp/csharp-plain-lists.pp
pkg/codegen/testing/test/testdata/csharp-plain-lists-pp/dotnet/csharp-plain-lists.cs

Some resources, especially custom resources like those in `awsx` have properties which are _plain_ lists. This means that the generated dotnet SDK for them uses `List<T>` rather than `InputList<T>`. In case of the former, when initializing the list, we cannot use `new[]` (this works for `InputList<T>` because of an implicit conversion from arrays). Instead we have to use `new()` which initializes an instance of the `List<T>` class. 
This PR implements a fix such that the code generator knows when the current resource property is plain or not and subsequently emitting `new()` instead of `new[]`
Fixes https://github.com/pulumi/pulumi-dotnet/issues/21

[dotnet/program-gen] Fixes list initializer for plain lists in resource properties

---

changelog/pending/20230730--programgen-nodejs--fixes-parseproxyapply-to-handle-nested-outputs-within-index-expressions.yaml
pkg/codegen/nodejs/gen_program_lower.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/regress-node-12507-pp/nodejs/regress-node-12507.ts
pkg/codegen/testing/test/testdata/regress-node-12507-pp/regress-node-12507.pp

This PR fixes an issue with `parseProxyApply` which is supposed to simplify traversals in TypeScript but fails when the body of the apply is an index expression where the collection of that expression is another apply. 
Give this PCL (and using `pcl.PreferOutputVersionedInvokes`):
```
rts = invoke("aws:ec2/getLocalGatewayRouteTables:getLocalGatewayRouteTables", {
filters = [{
name   = "tag:kubernetes.io/kops/role"
values = ["private*"]
}]
})
```
Then `rts.ids[range.value]` generates just `rts` in TypeScript. 
This PR fixes this such that the expression compiles to `rts.apply(rts => rts.ids[range.value])` (see full test example)
Fixes #12507

[nodejs/program-gen] Fixes parseProxyApply to handle nested outputs within index expressions

---

changelog/pending/20230331--cli-plugin--improve-error-pulumi-plugin-install.yaml
pkg/cmd/pulumi/plugin_install.go
pkg/cmd/pulumi/plugin_install_test.go
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_test.go

This PR adds a check to `pulumi plugin install` to confirm that the plugin is not bundled with Pulumi before performing the download. Without this check, the CLI will produce a 404 error because the language plugins aren't distributable independently of the CLI executable.
Fixes https://github.com/pulumi/pulumi/issues/11703

Check if Plugin is bundled before installing

---

changelog/pending/20230803--sdk-nodejs--fix-finding-the-pulumi-package-when-the-runtime-wasnt-started-in-the-project-directory.yaml
sdk/nodejs/cmd/pulumi-language-nodejs/main.go
sdk/nodejs/tests/runtime/langhost/run.spec.ts

Found this while working on matrix testing which runs the language host in a totally different directory to where the projects are.

Fix a working directory issue in language-nodejs

---

changelog/pending/20230803--sdkgen-nodejs--remove-the-pluginversion-option-from-nodejs-schema-options.yaml
pkg/codegen/nodejs/gen.go
pkg/codegen/nodejs/importer.go
pkg/codegen/testing/test/testdata/enum-reference-python/schema.json
pkg/codegen/testing/test/testdata/enum-reference/nodejs/package.json
pkg/codegen/testing/test/testdata/enum-reference/schema.json
pkg/codegen/testing/test/testdata/external-enum/nodejs/package.json
pkg/codegen/testing/test/testdata/external-enum/schema.json
pkg/codegen/testing/test/testdata/simple-resource-schema/nodejs/package.json
pkg/codegen/testing/test/testdata/simple-resource-schema/schema.json

These options should be unused, and it appears the only use case we have of them is a couple of tests.
Given that these options were only exposed to NodeJS there was no sensible way for users to make use of them, as all the other SDKs would still have used the top level plugin name and version declared by the schema.

Remove 'pluginVersion' and 'pluginName' from nodejs schema options.

---

.github/workflows/release.yml

This call to the examples repo always fails for the same reason as https://github.com/pulumi/pulumi/pull/12693:
> Today, when we do a release, we dispatch the trigger-cron workflow on the pulumi/templates repo, but this workflow consistently fails on new releases because it installs the Pulumi CLI with pulumi/actions, which [relies on pulumi/docs for its list of available versions](https://github.com/pulumi/actions/blob/e50e616f7d8f4c92d3d22abdd8cfd048e6e672de/src/libs/libs/get-version.ts#L23-L45) (a list that doesn't get updated until much later as part of a different process). As a result, every new release causes a pulumi/templates workflow failure (and alerts us in the #builds channel).
So this change just removes this call from the release workflow as #12693 did.
Fixes …

 Don't dispatch the smoke-test-cli workflow to pulumi/examples on release

---

changelog/pending/20230808--programgen-go-nodejs--fix-a-bug-in-marshalling-type-refs-across-grpc.yaml
pkg/codegen/schema/schema.go
pkg/codegen/schema/schema_test.go
pkg/codegen/testing/test/testdata/localref-1.0.0.json
pkg/codegen/testing/utils/host.go

Fixes https://github.com/pulumi/pulumi/issues/13671.
The code to marshal a TokenType back to a `$ref` simple copied the token across, but that didn't correctly reconstruct the URL that `$ref`s expect.

Correctly roundtip overlay type tokens in schema marshalling

---

tests/smoke_test.go
tests/testdata/random_yaml/Pulumi.yaml

In preparation for YAML moving over to the convert interface this is just a small test to ensure that we can continue to call convert on it.

Add a simple yaml convert smoke test

---

.github/workflows/on-pr.yml
.github/workflows/pr-test-acceptance-on-dispatch.yml

We currently upload coverage artifacts to codecov every 12 hours via the periodic-coverage cron workflow, which runs the full suite of tests against master, as well as during PRs, which runs a subset of tests for the PR.
We currently see some discrepancies in the data in codecov. One theory is the difference in tests between PRs and master.
This change makes it so we no longer upload coverage artifacts during PRs, to helpfully keep the data in codecov clean for trends over time.

ci: Don't upload coverage artifacts on PRs

---

pkg/codegen/go/gen.go
pkg/codegen/nodejs/gen.go
pkg/codegen/python/gen.go
pkg/codegen/schema/schema.go
pkg/codegen/testing/test/testdata/methods-return-plain-resource/docs/configurer/_index.md
pkg/codegen/testing/test/testdata/methods-return-plain-resource/go/metaprovider/configurer.go
pkg/codegen/testing/test/testdata/methods-return-plain-resource/nodejs/configurer.ts
pkg/codegen/testing/test/testdata/methods-return-plain-resource/python/pulumi_metaprovider/configurer.py
pkg/codegen/testing/test/testdata/methods-return-plain-resource/schema.json
tests/integration/construct_component_configure_provider/go/main.go
tests/integration/construct_component_configure_provider/nodejs/index.ts
tests/integration/construct_component_configure_provider/python/__main__.py
tests/integration/construct_component_configure_provider/testcomponent-go/configurer.go
tests/integration/construct_component_configure_provider/testcomponent-go/main.go
tests/integration/integration_util_test.go

On top of https://github.com/pulumi/pulumi/pull/13592
The functionality in 13592 is extended to support returning not just plain Resource values but plain values of any type. Tests are added for returning a plain integer from a method. 
One important change is that the magic "resource" field that is renamed to "res" which can also stand for "result". This change concerns the implementation of the method, not the usage patterns for consumers.

Prompt returning methods

---

.github/workflows/ci-run-test.yml

goteststats has moved to pulumi/goteststats.
This updates the path we use to install it.
The version number is the same because we have a pre-built binary
on that release for that version.

ci/goteststats: Update repository location

---

changelog/pending/20230810--sdkgen-python--fixes-rendering-v1-2-3-alpha-8-style-of-versions-to-valid-pypi-versions-when-respectschemaversions-option-is-set-in-sdkgen.yaml
pkg/codegen/python/utilities.go
pkg/codegen/python/utilities_test.go

Fixes rendering v1.2.3-alpha.8 style of versions to valid PyPI versions.
Fixes #13706

Fixes rendering v1.2.3-alpha.8 style of versions to valid PyPI version

---

changelog/pending/20230809--engine--fixes-some-synchronization-in-plugin-shutdown-to-prevent-panics-on-ctrl-c.yaml
sdk/go/common/resource/plugin/host.go
sdk/go/common/resource/plugin/host_test.go

Fixes https://github.com/pulumi/pulumi/issues/12371.
This locks access to the plugin request channels with a RWLock. Before trying to write to the channel we try to take a Read lock (yes this sounds the wrong way round, carry on). Many loaders are free to send to the loadRequest channel at once, but we use the read lock to atomiclly track if any are currently in progress.
When we go to close the plugin host the first thing we do is take a Write lock. Firstly this can't be taken until all the read locks are released indicating that no plugins are currently loading, but secondly while the write lock is taken no more read locks can be taken blocking any further plugin loads from starting.
We never release this write lock, thus permenatly blocking plugin loads once `Close` is called. So that …

Lock access to the plugin loading channels

---

.github/workflows/on-merge.yml
.github/workflows/on-pr.yml
changelog/pending/20230809--ci--adds-support-for-githubs-native-merge-queues.yaml

See [managing a merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue).
This is a **no-op** that makes it possible to begin experimenting with GitHub's native merge queues when the team is ready to do so. It does not change anything about existing workflows -- Bors is still required.
After this lands, actually testing the merge queue (and eventually cutting over) will require some coordination. Someone with admin access on the repo will need to edit branch protections to no longer require a Bors check and instead require the merge queue. Some test PRs can be landed while these protections are flipped, but real PRs should not be until the new workflow is confirmed to be working as …

ci: Preliminary support for GitHub merge queues

---

changelog/pending/20230816--programgen-go--fixes-go-mod-version-requirement.yaml
pkg/codegen/go/gen_program.go
scripts/tidy.sh

We added program generation that assumes availability of generics as part of https://github.com/pulumi/pulumi/pull/13149, but didn't bump the version of Go required in the generated go.mod.  Currently, Pulumi is supported on the supported versions of Go, which includes Go 1.20 and 1.21, so here we bump the Go version to the minimum currently supported version, which also supports all of the code we generate today.
I was curious how this was not already failing tests, and it appears it's because we delete the `go.mod` file in our tests and recreate it with `go mod init`.  I am unclear why we do that, but it feels like we should not, exactly to avoid this sort of problem in the future and to test the actual code we generate.
https://github.com/pulumi/pulumi/blob/8696695cdba039bffdb5aaa83cae8 …

Require Go 1.20 for Go Programgen

---

CONTRIBUTING.md
scripts/get-job-matrix.py

Go 1.21 was recently released.
Switch to testing with Go 1.20 and 1.21.
Fixes #13740

ci: Test with Go 1.20, 1.21

---

.github/workflows/on-pr.yml

We're investigating odd behavior with the queue. I've disabled the "Require linear history" check and I want to test whether that affects the merge behavior.
Refs https://github.com/pulumi/pulumi/issues/13741.

ci: No-op to test merge queue

---

.github/workflows/on-merge.yml

ci: Always report a ci-ok status on merge

---

pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/azure-native-pp/go/azure-native.go

The generated go code still fails to compile. It's missing lots of type names (worse then before) and still uses `pulumi.AnyArray` (which doesn't exist). I don't see non-deterministic panics anymore
Fixes #8123

Unskip azure-native-pp generation for go

---

changelog/pending/20230823--sdk-python--update-grpc-io-from-1-56-0-to-1-56-2.yaml
sdk/python/lib/setup.py

In #13708 Snyk has updated our reference to grpc-io in the requirements.txt to 1.56.2 but didn't update `setup.py` which results in installation conflicts as reported in #13738. This PR updates `setup.py` to be in sync with `requiremments.txt` 
Fixes #13738

[sdk/python] Update grpc-io from 1.56.0 to 1.56.2

---

changelog/pending/20230824--pkg--update-pulumi-yaml-v1-2-1-v1-2-2-pulumi-java-v0-9-0-v0-9-6-pulumi-dotnet-v3-54-0-v3-56-1.yaml
pkg/go.mod
pkg/go.sum
scripts/get-language-providers.sh

Update the following preparing for the CLI release
- pulumi-yaml (v1.2.1 -> v1.2.2) 
- pulumi-java (v0.9.0 -> v0.9.6)  
- pulumi-dotnet (v3.54.0 -> v3.56.1)

[pkg] Update pulumi-yaml, pulumi-java and pulumi-dotnet

---

sdk/go/common/util/cmdutil/child_unix.go
sdk/go/common/util/cmdutil/child_windows.go

Files tagged with OS-specific build tags
should usually have a suffix in their name
indicating which OS they're narrowing to.
child_windows.go already does this,
but child.go aimed at Linux and macOS does not.
This change renames child.go to child_unix.go.
Further, it moves the go:build directives
outside the copyright block.

chore(cmdutil): Rename build-tagged files

---

changelog/pending/20230824--sdk-nodejs--when-using-closure-serializtion-lookup-package-json-up-from-current-working-directory-up-to-parent-directories-recursively.yaml
sdk/nodejs/runtime/closure/codePaths.ts

When using closure serialization, we lookup `package.json` inside of the current working directory `.`. However, if users put their `package.json` file in a parent directory and their pulumi program in a child directory, then it can't find `package.json` and fails to create inline lambdas. 
This PR addresses the issue by looking up `package.json` starting from the current working directory recursively up parent directories until it finds the closest `package.json` file and uses that as the "root" of the project from which the dependencies are inferred.
Fixes #13764 
Didn't know how to write an integration test for this since the issue is using pulumi/aws but locally testing these code changes succeed the program.

[sdk/nodejs] closure serializtion, lookup package.json from current directory up to parent directories

---

changelog/pending/20230824--engine--fix-panic-when-analyzer-plugin-is-not-found-on-path.yaml
sdk/go/common/resource/plugin/analyzer_plugin.go

Fixes #10054
Analyzer Plugins may be missing. We should error instead of panic.

Fix panic when analyzer plugin is not found.

---

.github/workflows/on-pr-default.yml

This reports `ci-ok` when CI is skipped for version bumps, otherwise PRs are blocked from merging.

ci: Report ci-ok on version bumps

---

.github/workflows/release-pr.yml

The release PR job currently fails with the error:
must provide `--title` and `--body` (or `--fill` or `fill-first`) when not running interactively
Previously, body used to be `""` or `"bors merge"`.
Now that we no longer use bors, the body needs something in it.

ci(release-pr): gh pr create needs a body

---

changelog/pending/20230825--sdk-go--add-cmdutil-terminateprocessgroup-to-terminate-processes-gracefully.yaml
sdk/go/common/util/cmdutil/child_unix.go
sdk/go/common/util/cmdutil/child_windows.go
sdk/go/common/util/cmdutil/term.go
sdk/go/common/util/cmdutil/term_test.go
sdk/go/common/util/cmdutil/term_unix.go
sdk/go/common/util/cmdutil/term_windows.go
sdk/go/common/util/cmdutil/testdata/frozen.go
sdk/go/common/util/cmdutil/testdata/frozen.js
sdk/go/common/util/cmdutil/testdata/frozen.py
sdk/go/common/util/cmdutil/testdata/frozen_with_child.go
sdk/go/common/util/cmdutil/testdata/graceful.go
sdk/go/common/util/cmdutil/testdata/graceful.js
sdk/go/common/util/cmdutil/testdata/graceful.py
sdk/go/common/util/cmdutil/testdata/graceful_with_child.go
sdk/go/common/util/cmdutil/testdata/unhandled.go
sdk/go/common/util/cmdutil/testdata/unhandled.js
sdk/go/common/util/cmdutil/testdata/unhandled.py

Adds a new **currently unused** function TerminateProcessGroup
that terminates all processes in a group gracefully.
It does so by first sending the process
a SIGINT on Unix systems, and CTRL_BREAK_EVENT on Windows,
and waiting a specified duration for the process to exit.
The choice of signals was very deliberate
and is documented in the comments for TerminateProcessGroup.
If the process does not exit in the given duration,
it and its child processes are forcibly terminated
with SIGKILL or equivalent.
Testing:
The core behaviors are tested against Python, Go, and Node.
The corner cases of signal handling are tested
against rogue Go processes.
The changes were experimented with in #13760.
Refs #9780

feat(cmdutil): TerminateProcessGroup for graceful termination

---

sdk/go/pulumix/types.go
sdk/go/pulumix/types_ext_test.go

Per discussion in Ideation today,
rename the Cast and MustCast functions
to ConvertTyped and MustConvertTyped.
This is intended to make room for
renaming SpecializeOutput to Cast
which we expect users to use more often.

sdk/go/pulumix: Rename Cast to ConvertTyped

---

pkg/cmd/pulumi/cancel.go
pkg/cmd/pulumi/convert.go
pkg/cmd/pulumi/env.go
pkg/cmd/pulumi/policy_rm.go
pkg/cmd/pulumi/stack_rm.go
sdk/go/common/util/cmdutil/exit.go
sdk/go/common/util/cmdutil/exit_test.go
sdk/go/common/util/result/result.go
sdk/go/common/util/result/result_test.go

**Background**
The result.Result type is used by our CLI implementation to communicate how we want to exit the program.
Most `result.Result` values (built from errors with `result.FromError`) cause the program to print the message to stderr and exit the program with exit code -1.
The exception is `result.Bail()`, which indicates that we've already printed the error message, and we simply need to `exit(-1)` now.
Our CLI command implementation use `cmdutil.RunResultFunc` which takes a `func(...) result.Result` to implement this logic.
`cmdutil` additionally includes a `cmdutil.RunFunc` which takes a `func(...) error` and wraps it in `RunResultFunc`, relying on `result.FromError` for the conversion:
func RunFunc(run func(...) error) func(...) {
return RunResultFunc(func(...) result.Result { …

Support bailing from RunFunc

---

changelog/pending/20230826--cli-plugin--give-plugins-a-chance-to-clean-up-before-they-exit.yaml
changelog/pending/20230826--sdk-go--deprecate-cmdutil-killchildren-please-use-cmdutil-terminateprocessgroup-instead.yaml
sdk/go/common/resource/plugin/plugin.go
sdk/go/common/resource/plugin/plugin_test.go
sdk/go/common/util/cmdutil/child_unix.go
sdk/go/common/util/cmdutil/child_windows.go

Uses the new TerminateProcessGroup functionality introduced in #13792
to shut down plugins gracefully.
Graceful shutdown takes the following form:
- Send a termination signal (SIGINT or CTRL_BREAK_EVENT)
- Wait up to 1 second for the plugin to exit
- Kill it with SIGKILL
Note that TerminateProcessGroup kills the entire group
so we don't need a separate KillChildren and cmd.Process.Kill().
This change also deprecates cmdutil.KillChildren
since we shouldn't really be using SIGKILL as a first resort anyway.
Note that this does not modify the behavior of individual plugins.
Those will exit as usual but with a SIGINT instead of SIGKILL
terminating them.
Resolves #9780

resource/plugin: Shut down plugins gracefully

---

changelog/pending/20230828--sdk-go-nodejs-python--language-plugins-clean-up-resources-and-exit-cleanly-with-status-code-zero.yaml
sdk/go/pulumi-language-go/main.go
sdk/nodejs/cmd/pulumi-language-nodejs/main.go
sdk/python/cmd/pulumi-language-python/main.go

This changes the language plugins for Go, Node, and Python
to watch for the os.Interrupt signal (SIGINT on Unix, CTRL_BREAK on Windows)
that the plugin lifetime manager sends (per #13795)
and exit cleanly on receiving the signal.
This is a no-op for users.
An immediate effect it'll have for us is that
we'll begin seeing test coverage data come out of these binaries.
A similar change is necessary in other language plugin binaries.
I did not touch uses of rpcutil.ServeWithOptions outside `main` packages
because whether a signal handler should be installed there or not
requires more knowledge of individual cases.
Note that this uses [signal.NotifyContext][1].
Calling the returned `cancel()` function removes the signal handler.
This is desirable so that if a user sends the signal again
(e.g., …

plugin(go, node, py): Exit cleanly on interrupt

---

changelog/pending/20230825--cli-new--fix-regression-where-pulumi-new-s-org-project-stack-would-fail-if-the-project-already-exists.yaml
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/new_acceptance_test.go

Fixes #13774
When `pulumi new -s org/project/stack` parses out the project name, it runs a validation of the project name which will throw an error if the project already exists and cause `pulumi new` to fail. This PR causes `pulumi new` to no longer fail. This also checks if the getStack value is nil and falls back on the projectName specified in the `-s` parameter.

Fix `pulumi new` erroring when the project already exists.

---

pkg/backend/apply.go
pkg/cmd/pulumi/refresh.go
pkg/cmd/pulumi/state.go
pkg/cmd/pulumi/state_delete.go
pkg/cmd/pulumi/state_rename.go
pkg/cmd/pulumi/state_unprotect.go
pkg/cmd/pulumi/util.go

Replaces most instances of bail results outside the core engine with BailErorr instead.
The only parts of the codebase still using `result.Bail()` are in pkg/resource/deploy.

Replace Bail result with BailError

---

pkg/backend/filestate/backend_test.go
pkg/cmd/pulumi/stack_change_secrets_provider.go
pkg/cmd/pulumi/stack_change_secrets_provider_test.go
pkg/secrets/passphrase/manager.go

This command is currently untested. This adds a couple of basic tests to ensure that state and config secrets are changed.

Add tests for stackChangeSecretsProviderCmd

---

changelog/pending/20230826--cli-plugin--give-plugins-a-chance-to-clean-up-before-they-exit.yaml
changelog/pending/20230826--sdk-go--deprecate-cmdutil-killchildren-please-use-cmdutil-terminateprocessgroup-instead.yaml
sdk/go/common/resource/plugin/plugin.go
sdk/go/common/resource/plugin/plugin_test.go
sdk/go/common/util/cmdutil/child_unix.go
sdk/go/common/util/cmdutil/child_windows.go

Fixes #13831
This reverts commit 25901d95c4b108755abaa8452e71e23b356cd384.
On linux, `pulumi up` hung during a `pulumi-command provider` panic after this change was introduced.

Revert "resource/plugin: Shut down plugins gracefully (#13795)"

---

sdk/python/Makefile

Some `make` targets broke 
when we turned pulumi-language-python into
an independent Go module.
It also has a different import path than it did before.
This updates the Makefile to match the new path
and uses `-C` to cd into that directory for relevant Go commands.

make(sdk/py): Fix install, dist, test_go, brew

---

sdk/go/Makefile

For `go` commands where we can,
prefer using the -C flag to change directories
instead of `cd` in the Makefile.
For the lint target, have golangci-lint print paths
relative to the directory containing the Makefile
by using its --path-prefix flag.

make(sdk/go): Use -C instead of cd for 'go' commands

---

changelog/pending/20230829--sdk-go--support-multi-errors-built-from-errors-join.yaml
sdk/go/common/util/cmdutil/exit.go
sdk/go/common/util/cmdutil/exit_test.go

cmdutil has some special handling for hashicorp/go-multierror
so that multi-errors are printed cleanly in the form:
%d errors occurred:
1) foo
2) bar
...
In Go 1.20, the errors package got a native `errors.Join` function.
This adds support for errors.Join-based multi-errors to this logic.
These errors implement an `Unwrap() []error` method
which can be used to access the full list of errors.
We use that and then implement the same logic for formatting as before.

cmdutil: Support errors.Join-based multi-errors

---

changelog/pending/20230809--sdk-nodejs--fix-a-possible-panic-in-running-nodejs-programs.yaml
sdk/nodejs/cmd/pulumi-language-nodejs/main.go

Hit this while testing with matrix testing. Fairly frequently the go routine waiting for `pipesDone` would try to write to the response channel and panic because it was already closed.
This rewrites the method to only use the response channel for the running program, and we just explictly wait on all three events (pipes, handle, program) and return the first one that triggers.
Also it refactors execNodejs to just be a sync method that returns the response. The management of that running in a goroutine and writing to a channel is just kept in Run.

Change nodejs waiting on pipes to not panic

---

.github/workflows/ci-lint.yml
sdk/go/pulumi/generate/templates/config-require.go.template
sdk/go/pulumi/generate/templates/types_builtins.go.template

Addresses two issues with codegen templates in the Go SDK:
1. `type_builtins.go.template` was including an import for a package that doesn't exist. (The import doesn't exist in the current generated code that is checked-in). This change removes the import line from the template.
2. Some changes had been made directly to `config/require.go`, but this is a generated file -- the changes should have been made to the template. This change moves the changes to the template.
After the changes to these templates, running `make gen` in `sdk/go` yields no diffs.
Fixes #13871

[sdk/go] Fix issues with templates

---

changelog/pending/20230906--engine--check-for-old-resources-first-by-urn-and-then-aliases.yaml
pkg/engine/lifecycletest/alias_test.go
pkg/resource/deploy/step_generator.go
pkg/resource/deploy/step_generator_test.go
tests/integration/aliases/aliases_py_test.go
tests/integration/aliases/python/alias_after_failed_update/step1/Pulumi.yaml
tests/integration/aliases/python/alias_after_failed_update/step1/__main__.py
tests/integration/aliases/python/alias_after_failed_update/step1/echo.py
tests/integration/aliases/python/alias_after_failed_update/step1/fails_on_create.py
tests/integration/aliases/python/alias_after_failed_update/step2/__main__.py
tests/integration/aliases/python/alias_after_failed_update/step3/__main__.py
tests/testprovider/fails_on_create.go
tests/testprovider/main.go

This change fixes a regression in the step generator when looking for old resources. When generating steps for a register resource event, we previously looked for old resources first by the resource's URN and then by aliases.
This regressed with #10819:
```diff
-	for _, urnOrAlias := range append([]resource.URN{urn}, goal.Aliases...) {
+	aliases[urn] = struct{}{}
+	for urnOrAlias := range aliases {
```
Previously, aliases were in a slice and we always looked for the URN first, then aliases.
With #10819, aliases changed to being stored in a map (a set). The URN was added to the map before iterating over it, but there's no guarantee it will be looked at first (iteration order for maps is unspecified), and with the current behavior when there are aliases in the map, the URN very likely won't …

[engine] Check for old resources first by URN and then aliases

---

changelog/pending/20230906--cli-config--removes-pulumi_dev-flag-for-org-search.yaml
pkg/cmd/pulumi/org.go
pkg/cmd/pulumi/org_search.go

In order to release this feature to our users, we should no longer gate it behind `PULUMI_DEV`, so it is available by default.
Fixes https://github.com/pulumi/pulumi.ai/issues/210

Removes PULUMI_DEV flag for org search features

---

changelog/pending/20230906--cli-display--displays-total-and-displayed-resource-counts-for-org-search.yaml
pkg/cmd/pulumi/org_search.go
pkg/cmd/pulumi/org_search_ai_test.go
pkg/cmd/pulumi/org_search_test.go

Currently, there is no way to know how many total resources a given query WOULD display given no account limits, nor how many of that total are being displayed. This adds a small line of text indicating each of these numbers.
Fixes https://github.com/pulumi/pulumi.ai/issues/209

[org search] Adds resource counts to results display

---

changelog/pending/20230908--cli-new--fixes-pulumi-policy-new-template-name-to-not-require-yes-when-run-non-interactively.yaml
pkg/cmd/pulumi/policy_new.go
pkg/cmd/pulumi/policy_new_acceptance_test.go
pkg/cmd/pulumi/policy_new_test.go
tests/policy_new_test.go
tests/remote_test.go

Fixes #13901
`pulumi policy new <template-name>` would fail requiring a `--yes` argument that did not exist when being run non-interactively.
This changes `pulumi policy new <template-name>` to not require `--yes` when a template-name is provided.

[policy/new] make `pulumi policy new <template-name>` runnable in non-interactive mode

---

.github/workflows/release-pr.yml

As part of the release workflow, we use the GitHub CLI to open a PR to update the changelog and go.mod files. This has been failing when running `gh pr merge` with:
```
--merge, --rebase, or --squash required when not running interactively
```
This adds the `--squash` flag to make it happy, which is the same setting for the merge queue.
The need to specify this seems like a bug in the GH CLI. When trying this out locally with `--squash` it works, but says "The merge strategy for master is set by the merge queue". Anyway, we'll specify it for now so it works.
Fixes #13858

ci: Add required `--squash` flag to `gh pr merge`

---

changelog/pending/20230906--cli-config--adheres-to-default-org-for-org-search-when-one-is-set.yaml
changelog/pending/20230906--cli-display--displays-total-and-displayed-resource-counts-for-org-search.yaml
pkg/cmd/pulumi/org_search.go
pkg/cmd/pulumi/org_search_ai.go
pkg/cmd/pulumi/org_search_ai_test.go
pkg/cmd/pulumi/org_search_test.go

Currently, `pulumi org search` will use the individual user account as the default org when none is provided via `--org`. It would be ideal if it also respected any org set by `pulumi org set-default`. This PR accomplishes that.
Fixes https://github.com/pulumi/pulumi.ai/issues/208

[org search] Supports default org configuration

---

pkg/resource/deploy/step_generator.go

Add a comment closer to where we actually lookup an old resource, noting that we should check the URN first before aliases and why.
Follow-up from postmortem discussion on https://github.com/pulumi/pulumi/issues/13848

[engine] Add extra comment on old resource lookup

---

changelog/pending/20230906--cli-config--adheres-to-default-org-for-org-search-when-one-is-set.yaml
changelog/pending/20230906--cli-display--displays-search-url-when-results-table-is-rendered.yaml
changelog/pending/20230906--cli-display--displays-total-and-displayed-resource-counts-for-org-search.yaml
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/client/client.go
pkg/cmd/pulumi/org_search.go
pkg/cmd/pulumi/org_search_ai.go
pkg/cmd/pulumi/org_search_ai_test.go
pkg/cmd/pulumi/org_search_test.go
sdk/go/common/apitype/search.go

Displays to users a copyable URL to view org search results in Pulumi Cloud as well as a `--web` flag to automatically open those results for them.
Fixes https://github.com/pulumi/pulumi.ai/issues/207

[org search] Adds both the display of and the ability to open search results URLs

---

changelog/pending/20230802--cli--adds-basic-search-and-ai-assisted-search-functionality.yaml
changelog/pending/20230831--cli--adds-csv-as-an-output-option-for-org-search.yaml
changelog/pending/20230906--cli-config--adheres-to-default-org-for-org-search-when-one-is-set.yaml
changelog/pending/20230906--cli-display--displays-search-url-when-results-table-is-rendered.yaml
changelog/pending/20230906--cli-display--displays-total-and-displayed-resource-counts-for-org-search.yaml
changelog/pending/20230910--cli--adds-basic-search-and-ai-assisted-search-functionality.yaml
changelog/pending/20230910--cli--adds-pulumi-ai-and-pulumi-ai-web-commands.yaml
changelog/pending/20230911--cli-config-display--adds-display-of-query-individual-org-validation-console-query-syntax-alignment.yaml
pkg/backend/httpstate/backend.go
pkg/cmd/pulumi/ai_web.go
pkg/cmd/pulumi/org_search.go
pkg/cmd/pulumi/org_search_ai.go
pkg/cmd/pulumi/org_search_ai_test.go
pkg/cmd/pulumi/org_search_test.go
sdk/go/common/apitype/search.go

Based on initial Org Search feedback, we were missing a few things in the original implementation. This adds the following:
- Displays the raw query which was submitted to Pulumi for both basic org search and AI assisted search
- Validates whether the org provided is the user's individual org - AI assist and search is not supported for individual orgs
- Aligns `pulumi org search` syntax with that supported in the console.

Addresses initial Org Search feedback

---

pkg/resource/deploy/deployment_executor.go
pkg/resource/deploy/source.go
pkg/resource/deploy/source_eval.go
pkg/resource/deploy/source_null.go

Continued cleanup of `result.Bail`.

Replace result.Result in SourceIterator

---

changelog/pending/20230911--cli-state--pulumi-state-edit-now-supports-multi-part-editor-env-vars-i-e-emacs-nw.yaml
pkg/cmd/pulumi/state_edit.go
pkg/cmd/pulumi/state_edit_test.go
pkg/go.mod

`pulumi state edit` now properly handles multi-part EDITOR variables (i.e. `emacs -nw`).
Fixes #13850

[`pulumi state edit`] handle multi-part EDITOR variables (i.e. `emacs -nw`)

---

changelog/pending/20230912--sdkgen-go-nodejs-python--fix-a-bug-in-marshalling-enums-across-grpc.yaml
pkg/codegen/schema/schema.go
pkg/codegen/schema/schema_test.go
pkg/codegen/testing/test/testdata/enum-1.0.0.json
pkg/codegen/testing/utils/host.go

The code to marshal an enum was not keeping the enum's comment.
Fixes #13921

Correctly roundtrip enums in schema marshalling

---

pkg/authhelpers/gcpauth_test.go

Add tests for gcpauth pkg

---

changelog/pending/20230913--cli--fixes-panic-when-default-org-is-not-set-and-no-org-is-provided-to-org-search.yaml
pkg/backend/httpstate/backend.go
pkg/cmd/pulumi/org_search.go
pkg/cmd/pulumi/org_search_test.go

Currently, if a user has no default org set, and no org is provided via --org, `GetBackendConfigDefaultOrg` returns nothing, which means no org is provided when querying the Pulumi Cloud service - this results in a 404, and a nil pointer error when attempting to retrieve query parameters from that API call. This falls back to the user name when no org is provided by the user or retrieved by `GetBackendConfigDefaultOrg`, as well as returning an error when one arises from the service call rather than returning the error later.

Safeguards org search against unset default orgs

---

changelog/pending/20230914--cli-new--use-bubbletea-to-render-pulumi-new-template-selection.yaml
cmd/pulumi-test-language/go.mod
cmd/pulumi-test-language/go.sum
pkg/backend/display/selector.go
pkg/backend/display/selector_test.go
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/up.go
pkg/go.mod
pkg/go.sum
sdk/go/pulumi-language-go/go.mod
sdk/go/pulumi-language-go/go.sum
sdk/nodejs/cmd/pulumi-language-nodejs/go.mod
sdk/nodejs/cmd/pulumi-language-nodejs/go.sum
sdk/python/cmd/pulumi-language-python/go.mod
sdk/python/cmd/pulumi-language-python/go.sum
tests/go.mod
tests/go.sum

Switches the survey-based list picker we use to pick a template
to use bubbletea with the bubbles/list widget.
Instead of using any of the default bubbles/list renderings,
this implements a custom renderer for list items (the delegate)
that provides an experience closer in look to the 'pulumi new' today.
Related to #13815 in spirit.
Fixes #11812
Fixes #8169
---
Demos
<details>
<summary>Basic usage</summary>
[![asciicast](https://asciinema.org/a/NeecyanZP2iyzlrAOKRiKckJZ.svg)](https://asciinema.org/a/NeecyanZP2iyzlrAOKRiKckJZ)
</details>
<details>
<summary>Handling of really small terminals</summary>
[![asciicast](https://asciinema.org/a/RZW3NfX5SQ8rL4mR1iRLQ6yi1.svg)](https://asciinema.org/a/RZW3NfX5SQ8rL4mR1iRLQ6yi1)
</details>

PoC: cli/new: Use bubbletea for template list

---

changelog/pending/20230913--engine--fix-aliases-of-parents-tracking-over-partial-deployments.yaml
pkg/backend/snapshot_test.go
pkg/cmd/pulumi/state_rename.go
pkg/cmd/pulumi/state_rename_test.go
pkg/engine/lifecycletest/alias_test.go
pkg/engine/lifecycletest/import_test.go
pkg/engine/lifecycletest/test_plan.go
pkg/resource/deploy/snapshot.go
pkg/resource/deploy/state_builder.go
pkg/resource/deploy/state_builder_test.go
sdk/go/common/resource/urn.go
tests/integration/aliases/python/retype_parents/step1/__main__.py
tests/integration/aliases/python/retype_parents/step2/__main__.py

Fixes https://github.com/pulumi/pulumi/issues/13903
When we change parents in a statefile we also need to fix up the URN.
This is needed so aliases can track over partial updates.

When changing parents also fix URNs

---

pkg/backend/backend.go
pkg/backend/filestate/backend.go
pkg/backend/httpstate/backend.go
pkg/backend/mock.go
pkg/cmd/pulumi/logout.go

Backends themselves don't actually need any logout logic. Logging out is mearly a function of deleting the account from the credentials file and is the same for filestate, httpstate and probably any other state we introduce.
This also simplifies the code "logout --all" which used to try and lookup the project, make up a dummy httpstate object, and then call LogoutAll to call workspace.DeleteAllAccounts. Now it goes straight to that last call.

Remove Logout logic from Backend interface

---

changelog/pending/20230914--cli-new--pulumi-new-no-longer-defaults-to-a-project-name-of-pulum-if-ran-in-a-folder-called-pulumi.yaml
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/up.go
pkg/workspace/templates.go
pkg/workspace/templates_test.go
sdk/go/common/tokens/project_test.go
sdk/go/common/workspace/templates.go
sdk/go/common/workspace/templates_test.go

Fixes https://github.com/pulumi/pulumi/issues/13946.
This also moves some of the logic from sdk/go/common to pkg/ as it's only used be `new` and `up.

Use fallback project name rather than "pulum"

---

pkg/backend/filestate/backend.go
pkg/backend/filestate/snapshot.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/snapshot.go
pkg/backend/httpstate/snapshot_test.go
pkg/backend/snapshot.go
pkg/backend/snapshot_test.go

It should never have really been the role of the persister to decide what SecretsManager to use, and they were in practice always being setup with a SnapshotManager anyway so not a lot of code to move the secrets manager around. This also gets the httpstate and filestate backends in alignment over which SecretsManager variable they're going to use.

Move SecretsManager from SnapshotPersister to SnapshotManager

---

pkg/resource/deploy/deployment_executor.go
pkg/resource/deploy/source.go
pkg/resource/deploy/source_error.go
pkg/resource/deploy/source_eval.go
pkg/resource/deploy/source_null.go

Continued chipping away at removing `result.Result`.

Change Source.Iterate to return an error

---

pkg/backend/backend.go
pkg/backend/filestate/backend.go
pkg/backend/httpstate/backend.go
pkg/backend/mock.go
pkg/backend/query.go
pkg/cmd/pulumi/query.go
pkg/engine/query.go
pkg/resource/deploy/source_query.go
pkg/resource/deploy/source_query_test.go

Continued cleanup of result.Bail with error. This cleans up the codepath using Query.

Replace result.Result in Query with error

---

changelog/pending/20230911--cli-new--pulumi-policy-new-now-injects-pulumi_access_token-when-necessary-to-support-downloading-premium-policies.yaml
pkg/backend/httpstate/policypack.go
pkg/cmd/pulumi/policy_new.go
tests/policy_new_test.go

Fixes #13881
`pulumi policy new` now injects PULUMI_ACCESS_TOKEN for Premium Policies

[policy] support premium policies

---

changelog/pending/20230922--sdkgen-dotnet--fixes-potential-conflicts-when-generating-resources-called-system.yaml
pkg/codegen/dotnet/gen.go
pkg/codegen/testing/test/testdata/provider-config-schema/dotnet/Config/Config.cs

When generating a C# package that has a resource called `System`, it fails to compile when we fully qualify `System.Diagnostics.CodeAnalysis.SuppressMessage` in the generated `Config.cs` file since it thinks that `System.Diagnostics` is referring to a static class on the `System` resource definition. 
The fix is to prefix the attribute with `global::` so that type resolution works as expected.

[dotnet/sdk-gen] Fixes potential conflicts when generating resources called System

---

changelog/pending/20230921--sdk-go--ensure-assets-of-assetarchive-are-non-nil-when-creating-serializing-and-deserializing.yaml
sdk/go/common/resource/asset.go
sdk/go/common/resource/asset_test.go

Fixes #11103
The problem in the issue the distinction between `Assets` or an archive being `nil` vs. being an empty map of assets. When creating and deserializing Archives, `nil` was allowed which leads to panics when asserting `archive.IsAssets()` because the `Assets` is `nil` even though it is a proper archive. 
This PR fixes the issue by ensuring that an instance of `Archive` will have a non-nil `Assets` field whether that is during construction or marshalling.

[sdk/go] Ensure Assets of AssetArchive are non-nil when creating and deserializing

---

changelog/pending/20230809--sdkgen-python--generate-output-versioned-invokes-for-functions-without-inputs.yaml
pkg/codegen/python/gen.go
pkg/codegen/testing/test/testdata/output-funcs/python/pulumi_mypkg/get_client_config.py
pkg/codegen/testing/test/testdata/regress-8403/python/pulumi_mongodbatlas/get_custom_db_roles.py

Partially addressing https://github.com/pulumi/pulumi/issues/12449 implements output-versioned invokes for functions without inputs for python SDKs

[python/sdk-gen] Generate output-versioned invokes for functions without inputs

---

changelog/pending/20230922--cli-engine--errors-writing-out-snapshots-now-print-error-messages-to-be-seen-by-users.yaml
pkg/backend/filestate/backend.go
pkg/backend/httpstate/backend.go

Currently if the engine encounters an error writing out snapshots it only logs that to the V11 log. 
We'd like to get to the point where the engine doesn't write out invalid snapshots in the first place, but doing this in small steps to reduce blast radius of changes to a core engine loop.
This is the first step, we'll log the error to the user error stream so it's more noticeable than just being in the developer logs at -v11.

Write out snapshot errors to the user error stream

---

sdk/python/cmd/pulumi-language-python/main.go

Python version has an extra newline at the end. This patch trims Python version so that doesn't happen.
This is visible when doing `pulumi about`:
```
This project is written in python: executable='/usr/bin/python3' version='3.11.5
'
```

Trim Python version

---

changelog/pending/20230923--cli--include-a-newline-in-pulumi-whoami-s-output.yaml
pkg/cmd/pulumi/whoami.go
pkg/cmd/pulumi/whoami_test.go

Looks like we used to output the newline, but unintentionally changed this in #12400 when refactoring to make it testable. This change fixes the command to include the newline character and updates the associated test.
Fixes #14008

fix: Include a newline in `pulumi whoami`'s output

---

pkg/resource/deploy/deployment_executor.go
pkg/resource/deploy/step.go
pkg/resource/deploy/step_generator.go

More cleanup of result.Result, this time a pass through the step generator.

Replace use of result.Result in step generator

---

pkg/backend/httpstate/token_source_test.go
pkg/cmd/pulumi/policy_new_acceptance_test.go
pkg/cmd/pulumi/policy_new_test.go
pkg/resource/deploy/source_query_test.go
sdk/go/auto/git_test.go
sdk/go/pulumi/provider_test.go
sdk/go/pulumi/resource_test.go
sdk/nodejs/cmd/pulumi-language-nodejs/main_test.go

As suggested by the [godocs](https://pkg.go.dev/context#Background).
This means a search for `context.TODO` now just shows up places we really do seem to be missing a threaded in context in real code.

Use context.Background in tests

---

changelog/pending/20230923--sdk-python--resource-property-parameters-are-now-runtime-type-checked-to-ensure-they-are-a-mapping-object.yaml
sdk/python/lib/pulumi/resource.py
sdk/python/lib/test/test_resource.py

Fixes https://github.com/pulumi/pulumi/issues/13997.
It would be a little nicer if every input type _actually_ implemented the `Mapping` interface, but that trying to do that turned into a much deeper fix than this one.

Type check props in the `Resource` initializer

---

changelog/pending/20230922--cli--add-self_manged_state_gzip-to-pulumi-env.yaml
pkg/backend/filestate/backend.go
pkg/backend/filestate/state.go
pkg/testing/integration/program.go
sdk/go/common/env/env.go
tests/main_test.go
tests/stack_test.go

Tiny fix up to env vars. This wasn't showing in `pulumi env`.

Add SelfManaged env vars

---

changelog/pending/20230925--engine--fix-creation-and-modification-timestamps-sometimes-not-setting.yaml
pkg/resource/deploy/step.go

The completion functions run _after_ the step executor has called OnResourceStepPost where we trigger the snapshot save.
So if the data was saved or not depended on it racing the snapshot goroutine.

Don't edit state in completion functions

---

changelog/pending/20230926--cli-import--import-from-plugin-will-now-try-to-auto-install-the-plugin-if-missing.yaml
pkg/cmd/pulumi/convert.go
pkg/cmd/pulumi/import.go

When using `--from` in convert it would auto install the converter, but didn't in import. This aligns them.

Auto install converter plugins in 'import' as well as 'convert'

---

changelog/pending/20230925--engine--fixes-the-engine-using-aliases-from-old-deployments-when-writing-out-statefiles.yaml
pkg/engine/lifecycletest/alias_test.go
pkg/resource/deploy/snapshot.go
pkg/resource/deploy/state_builder.go

Fixes https://github.com/pulumi/pulumi/issues/14041.
Fixes a URN normalisation error from respecting aliases from old deployments.
We no longer write out aliases to snapshot files, so will no longer pick these
aliases up on later deployments.
Longer term it would be good to refactor state and snapshot code so that
Aliases isn't on state at all, but side-channeled to snapshot code some other
way. But this is a quick fix that starts the process of removing aliases from
state now with minimal blast radius.

Fix duplicate resource error from failed delete operations 

---

pkg/backend/httpstate/backend.go
pkg/cmd/pulumi/login.go
pkg/cmd/pulumi/policy_publish.go
pkg/cmd/pulumi/util.go

Allow callers to retrieve Pulumi account information without creating a full-fledged backend.

[backend] Separate login and backend creation

---

pkg/cmd/pulumi/gen_markdown.go

Currently the pages for the CLI docs jump from H1 to H3 headings because we remove the H2s that are generated for the command name, since they are already present in the title. This gap does not align with best SEO practices. This promotes the H3 headings (### in markdown) to H2 (##) so we can get rid of the gap.
Fixes: https://github.com/pulumi/docs/issues/9537

Consecutive markdown heading levels CLI docs

---

changelog/pending/20230920--programgen--programgen-now-can-create-identifiers-for-already-used-resource-names.yaml
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/import_test.go

Fixes https://github.com/pulumi/pulumi/issues/6032
`pulumi import` no longer fails if the resource spec shares the same resource
name.

`pulumi import` now supports resources of the same name

---

changelog/pending/20230928--engine--lifecycle-tests-shouldnt-reuse-a-closed-plugin-host.yaml
pkg/backend/httpstate/snapshot_test.go
pkg/engine/lifecycletest/alias_test.go
pkg/engine/lifecycletest/analyzer_test.go
pkg/engine/lifecycletest/delete_before_replace_test.go
pkg/engine/lifecycletest/golang_sdk_test.go
pkg/engine/lifecycletest/import_test.go
pkg/engine/lifecycletest/pending_delete_test.go
pkg/engine/lifecycletest/provider_test.go
pkg/engine/lifecycletest/pulumi_test.go
pkg/engine/lifecycletest/refresh_test.go
pkg/engine/lifecycletest/resource_reference_test.go
pkg/engine/lifecycletest/step_generator_test.go
pkg/engine/lifecycletest/target_test.go
pkg/engine/lifecycletest/test_plan.go
pkg/engine/lifecycletest/update_plan_test.go
pkg/resource/deploy/deploytest/languageruntime.go
pkg/resource/deploy/deploytest/pluginhost.go

This PR fixes the inadvertent use of a closed plugin host in the lifecycle tests. The tests override the host that is provided to the engine, for good reasons, but that same host is re-used across multiple engine operations. Since the engine closes the supplied host at the end of each operation, subsequent operations are handed a closed host.
In order to detect engine bugs related to the use of a closed host (see https://github.com/pulumi/pulumi/pull/14057), the fake host should return an error if it is used after being closed (as does the real host). This PR addresses this.
The detailed change is to shift to using a host factory that produces a host in `TestOp.Run`. The `TestPlan` now takes a `TestUpdateOptions` with `HostF` and an embedded `UpdateOptions`.
Note that two tests fail due …

Lifecycle tests shouldn't use a closed host

---

changelog/pending/20230927--engine--calling-registerresourceoutputs-twice-no-longer-panics-and-returns-an-error-instead.yaml
pkg/resource/deploy/step_executor.go
pkg/resource/deploy/step_executor_test.go

Fixes #2394
Fixes https://github.com/pulumi/pulumi-dotnet/issues/39

[engine] RegisterResourceOutputs errors instead of panics when called twice

---

changelog/pending/20230927--engine--non-custom-componentresources-now-emit-resourceoutputevent-on-deletion-this-fixes-the-time-elapsed-timer-not-ending-when-the-resource-is-deleted.yaml
pkg/engine/update.go
pkg/engine/update_test.go

Fixes #13357
ComponentResources now emit resourceOutputEvent on delete
steps. This fixes the time elapsed timer not stopping when the resource
is deleted.

[display] fix ComponentResource deletion not stopping time elapsed timer

---

changelog/pending/20230929--engine--ctrl-c-should-cause-pulumi-to-send-cancellation-signal-to-providers.yaml
pkg/engine/deployment.go
pkg/engine/deployment_test.go
pkg/engine/destroy.go
pkg/engine/lifecycletest/pulumi_test.go
pkg/engine/lifecycletest/refresh_test.go
pkg/engine/query.go
pkg/engine/refresh.go
pkg/engine/update.go

Fixes #14054
This PR fixes a problem that the engine cannot forward a cancellation signal to the provider, because the plugin context is already closed. An [earlier commit](https://github.com/pulumi/pulumi/pull/9793/commits/a9ae602867834efc9821abd866ef388c1b051114) made the plugin context be closed too eagerly, with the intent of cancelling plugin installation. This PR attempts to decouple the cancellation of plugin installation from the lifecycle of the plugin context, so that plugin installation may be cancelled during the cancelation phase as opposed to the termination phase. Then, it closes the plugin context in termination phase.
There's an existing test case in the engine lifecycle tests called `TestProviderCancellation`, but it didn't catch the problem because it uses a fake plugin …

ctrl-c should cause Pulumi to call Cancel operation on providers

---

changelog/pending/20230809--sdkgen-go--generate-output-versioned-invokes-for-functions-without-inputs.yaml
pkg/codegen/go/gen.go
pkg/codegen/pcl/invoke.go
pkg/codegen/schema/schema.go
pkg/codegen/testing/test/testdata/output-funcs/docs/getclientconfig/_index.md
pkg/codegen/testing/test/testdata/output-funcs/go/mypkg/getClientConfig.go
pkg/codegen/testing/test/testdata/output-funcs/go/mypkg/x/getClientConfig.go
pkg/codegen/testing/test/testdata/regress-8403/docs/getcustomdbroles/_index.md
pkg/codegen/testing/test/testdata/regress-8403/go/mongodbatlas/getCustomDbRoles.go
pkg/codegen/testing/test/testdata/simple-yaml-schema/go/example/argFunction.go

Partially addressing #12449 implements output-versioned invokes for functions without inputs for go.

[go/sdk-gen] Generate output-versioned invokes for functions without inputs

---

changelog/pending/20230928--cli-import--import-converters-will-write-out-their-intermediate-import-file-for-manual-fixups-if-needed.yaml
pkg/cmd/pulumi/import.go

When using `import --from` it's helpful to be able to manually fix up errors. The command now writes the generated import file out to a random file in the current directory which the user can then edit and reuse with `import --file`.

Write out generated import files

---

changelog/pending/20230227--sdk-python--add-default-arg-to-config-get_secret.yaml
sdk/python/lib/pulumi/config.py
sdk/python/lib/test/test_config.py

This change adds the missing `default` arg to `Config.get_secret` method, for consistency with the other `get_secret_<type>` methods that have a `default` arg.
Fixes #12271

[sdk/python] Add `default` arg to `Config.get_secret`

---

changelog/pending/20231001--engine--fix-a-race-condition-in-the-engine-access-step-event-data.yaml
pkg/engine/events.go
pkg/resource/deploy/deployment_executor.go
pkg/resource/deploy/step_executor.go

Fixes https://github.com/pulumi/pulumi/issues/14036.
Not sure this is perfect (it's pretty hard to reason about mutation of the whole system given what Go gives us to work with), but it seems better.
We copy event payloads on construction, which should be synchronous with step execution, rather than on access which could be in parallel with the step executor or deployment executor mutating resource state.
Just copying on construction flagged up that the deployment executor and step executor both race to modify resource state when the deployment executor starts scheduling deletes. We add a synchronisation point between the two parts in this change so that the deployment executor waits for the step executor to go quite, and keeps it quite while it computes the deletes, once it starts …

Deepcopy event payloads on construction _not_ on access

---

pkg/resource/deploy/source_query.go

The continued removal of result.Result.

Clean up result.Result use in source_query.go

---

changelog/pending/20231002--cli--users-can-now-set-pulumi_disable_automatic_plugin_acquisition-to-disable-the-engine-trying-to-auto-install-missing-plugins.yaml
pkg/cmd/pulumi/convert.go
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/package.go
pkg/codegen/schema/loader.go
pkg/resource/deploy/providers/registry.go
sdk/go/common/env/env.go
tests/smoke_test.go
tests/testdata/aws_tf/main.tf

This is primarily for the providers team to enable during builds so they can have more confidence about reproducibility of builds (especially examples conversion), but I imagine some customers would enable this as well.
Fixes #14086

Add an envar to disable automatic provider installation

---

.github/workflows/ci-run-test.yml
CHANGELOG.md
pkg/backend/httpstate/policypack.go
pkg/cmd/pulumi/policy_new.go
tests/policy_new_test.go

This reverts commit b7efd1611ffd7a4873c055f1070c15aa4b2398d9 as there's no longer a need to authenticate to use these policies.
This unblocks merging into master as `TestPremiumPolicyAuth` is currently failing.
Since we're removing the capability, it's no longer necessary to advertise the functionality (even if it did ship previously), so I've stricken it from the CHANGELOG.md for `3.85.0`.
Fixes #14113

Revert "[policy] support premium policies (#13898)"

---

.github/workflows/ci-run-test.yml
changelog/pending/20231005--engine--disable_automatic_plugin_acquisition-is-respected-for-deployment-operations-now.yaml
pkg/engine/plugins.go

Missed this in the initial PR for https://github.com/pulumi/pulumi/pull/14083. This stops the deployment engine trying to install missing plugins on startup.
We're also using this for CI tests for now because deploytest tries to auto install providers that don't really exist (like pkgA). Long term we'll abstract out that code so deploytest can fake the plugin cache.
Fixes #14106

Support disable plugin acquisition in deployments, and use for tests

---

.github/workflows/ci-run-test.yml
tests/smoke_test.go

Fix the test command, in https://github.com/pulumi/pulumi/pull/14116 we forgot about a `$` sign in front of it.

fix run command for run tests

---

pkg/resource/deploy/deployment_executor.go
pkg/resource/deploy/step_generator.go

Cleanup use of result.Result in step_generator.go

---

changelog/pending/20231001--engine--restore-elided-asset-contents-from-returned-inputs-from-read-operations.yaml
sdk/go/common/resource/plugin/provider_plugin.go
sdk/go/common/resource/plugin/provider_plugin_test.go

When we send inputs to `Read` operations due to `pulumi refresh` we skip sending asset contents. However, `Read` implementation might return the asset-valued input properties unchanged (without their asset contents) and the engine will simply write out the empty assets to the state causing an invalid shape of asset in the inputs of resources.
This PR implements a function `restoreElidedAssetContents` and uses it in the `Read` implementation on the new inputs and new state returned from the provider plugins. 
Testing the CLI locally using this fix, it does correctly write out the asset contents to the state _after_ a `pulumi refresh`. ~However, when running `preview` after `refresh`, the nodejs SDK still fails with the same error in #6691 because `RegisterResource` still returns the inputs …

[cli/engine] Restore elided asset contents from returned inputs from Read operations

---

changelog/pending/20231005--cli--fix-a-panic-in-whoami-with-tokens-missing-expected-information.yaml
pkg/cmd/pulumi/whoami.go
pkg/cmd/pulumi/whoami_test.go
sdk/go/common/workspace/creds.go

Fixes https://github.com/pulumi/pulumi/issues/14109.
Fixes a panic where the service sends a token without an organization or team.

Fix panic in whoami

---

changelog/pending/20231006--auto--added-a-tracing-span-for-plugin-launch.yaml
sdk/go/common/resource/plugin/plugin.go

Adds a tracing span that covers the time spent waiting for a plugin to initialize.  This will make it easier to distinguish how much provider initialization time is contributing to overall pulumi command duration.
Fixes https://github.com/pulumi/pulumi/issues/13986 (Traces from within the provider plugins are tracked in separate issues)
It's pretty difficult to test this method independently without some refactoring. Since this change is diagnostic only, I lean toward adding without test to avoid dragging in a potentially complicated restructuring, but open to suggestions.

Add a span for plugin startup/launch time

---

changelog/pending/20231006--cli-package--fix-a-panic-in-get-mapping-when-not-passing-a-provider-name.yaml
pkg/cmd/pulumi/package_extract_mapping.go

Small bug fix in get-mapping. We added the optional arg of provider name a while ago, but didn't actually make it optional. If you didn't pass it the cli panic'd with an index out of range.

Fix index out of range in get-mapping

---

changelog/pending/20231004--programgen-python--fix-panic-in-python-program-gen-when-rewriting-index-expressions.yaml
pkg/codegen/python/gen_program_quotes.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/python-regress-14037-pp/python-regress-14037.pp
pkg/codegen/testing/test/testdata/python-regress-14037-pp/python/python-regress-14037.py

Fixes #14037 so that the program generation no longer panics

[python/program-gen] Fix panic in python program-gen when rewriting index expressions

---

changelog/pending/20231005--engine--engine-will-now-error-earlier-if-a-deployment-needs-a-bundled-plugin-that-is-missing.yaml
pkg/engine/plugins.go

As part of looking into abstracting away the plugin checks for engine tests, I noticed we have two _very_ similar methods for install plugins. The main difference was that in `installPlugin` we skipped the install if the plugin was a language plugin.
This isn't the ideal behaviour, so I've moved that check up into `installPlugins` and checked for "bundleness" not just being a language plugin and made it an error (similar error to what people get if they try and `pulumi plugin install language dotnet`).
So now if the engine wants to use a plugin that should be bundled but it's missing we'll just error out the deployment.
A follow up PR will look at merging `InstallPlugin` and `installPlugin` into one method.

Move language check from installPlugin to installPlugins

---

pkg/resource/deploy/deployment.go
pkg/resource/deploy/deployment_executor.go

The continued cleanup of result.Result, this time through the deployment_executor. 
Some tricksy changes through here so do give it a read to double check me.

Cleanup result.Result in deployment_executor

---

pkg/testing/integration/program.go

This PR changes the behavior of `ProgramTester` in `pkg/testing/integration` package, to detect test failures more eagerly and then to skip remaining steps. Specifically it checks whether the test been marked as failed by a validation function (as defined by [`t.Failed()`](https://pkg.go.dev/testing#T.Failed)).
The rationale is that, for most integration tests, each step assumes that the previous step was successful. It is simply noisy to continue with the subsequent steps. A workaround is to call `t.FailNow()` in the validation function (or use `require`).
An option is provided `ExpectTestFailure` to continue with steps after test failure (as is the current behavior).
There exists an option `ExpectFailures` to continue with steps after a pulumi deployment failure.  I took such failures …

[Test] Eager cancelation for ProgramTester

---

.github/workflows/ci-run-test.yml
.github/workflows/ci-test-docs-generation.yml

The specific SHA seems to be failing to download sometimes today.  Try to update it to the latest v3 version to see if that works better.
This seems likely an issue that's currently going on with the GitHub infrastructure, but it seems to me that we don't need to pin this version anyway, and we can get the latest fixes for the action this way.

use v3 of setup-dotnet instead of a specific SHA

---

pkg/backend/filestate/backend.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/snapshot_test.go
pkg/engine/destroy.go
pkg/engine/import.go
pkg/engine/lifecycletest/alias_test.go
pkg/engine/lifecycletest/analyzer_test.go
pkg/engine/lifecycletest/delete_before_replace_test.go
pkg/engine/lifecycletest/golang_sdk_test.go
pkg/engine/lifecycletest/import_test.go
pkg/engine/lifecycletest/pending_delete_test.go
pkg/engine/lifecycletest/provider_test.go
pkg/engine/lifecycletest/pulumi_test.go
pkg/engine/lifecycletest/refresh_test.go
pkg/engine/lifecycletest/step_generator_test.go
pkg/engine/lifecycletest/target_test.go
pkg/engine/lifecycletest/test_plan.go
pkg/engine/lifecycletest/update_plan_test.go
pkg/engine/refresh.go
pkg/engine/update.go

A big change for result.Result cleanup. This removes all references to the Result type from pkg/engine. This was mostly just search replace. Points to note, we still map to `result.Result` in pkg/backend (that will be the next big result change to deal with), and a little bit of fiddlyness with multiple error values in test_plan.go `runWithContext`.

Cleanup result.Result in pkg/engine

---

changelog/pending/20231010--cli--ignore-unexpected-types-instead-of-erroring-out.yaml
sdk/go/common/resource/config/object.go
sdk/go/common/workspace/loaders_test.go
tests/integration/integration_test.go

Before #13814, when we encountered unexpected types in a yaml file, we ignored them.  However that PR changed that, and we end up panicing, e.g. in case we have a config like the following:
```
config:
aws:region: us-east-1
aws:id:
-
```
Fix that by getting the old behaviour of ignoring this error back.
Fixes #14146

ignore unexpected types instead of erroring out

---

changelog/pending/20231010--auto-nodejs--remove-unneeded-sxs-check-for-inline-programs.yaml
sdk/nodejs/automation/server.ts
sdk/nodejs/runtime/settings.ts
sdk/nodejs/tests/automation/localWorkspace.spec.ts

This change removes the SxS check in the Node.js Automation API since it's blocking a customer scenario and isn't needed anymore now that #5449 has been addressed with #10568.
The check was originally added in #7349 to provide a helpful error message when multiple versions of `@pulumi/pulumi` were used with inline programs, which could cause clashes with global state. Since then, we've changed how state is stored to allow parallel execution of multiple inline programs with #10568. However, the SxS checks were not removed as part of that change.
A customer recently hit the error associated with the SxS check. They are creating a Next.js program that runs Pulumi operations as inline programs. Next.js ends up loading modules multiple times in a way that confuses the SxS checker, causing the …

[auto/nodejs] Remove SxS check that's no longer needed

---

changelog/pending/20231012--programgen--fixes-panic-when-binding-the-signature-of-output-versioned-invokes-without-input-arguments.yaml
pkg/codegen/pcl/invoke.go

[pcl/binder] Fixes panic when binding the signature of output-versioned invokes without arguments

---

changelog/pending/20231009--engine--engine-is-now-more-efficent-about-starting-up-provider-processes-generally-saving-at-least-one-process-startup-per-deployment.yaml
pkg/engine/lifecycletest/provider_test.go
pkg/resource/deploy/providers/reference.go
pkg/resource/deploy/providers/registry.go
pkg/resource/deploy/providers/registry_test.go
pkg/resource/deploy/source_eval.go
pkg/resource/deploy/source_eval_test.go
pkg/resource/deploy/source_query.go
tests/integration/query/step1/package.json

Fixes https://github.com/pulumi/pulumi/issues/13987.
This reworks the registry to better track provider instances such that we can reuse unconfigured instances between Creates, Updates, and Sames.
When we allocate a provider instance in the registry for a Check call we save it with the special id "unconfigured". This value should never make its way back to program SDKs, it's purely an internal value for the engine.
When we do a Create, Update or Same we look to see if there's an unconfigured provider to use and if so configures that one, else it starts up a fresh one. (N.B. Update we can assume there will always be an unconfigured one from the Check call before).
This has also fixed registry Create to use the ID `UnknownID` rather than `""`, have added some contract assertions to check …

Reuse provider instances where possible

---

changelog/pending/20231004--engine--fix-a-panic-in-the-engine-when-same-steps-failed-due-to-provider-errors.yaml
pkg/backend/snapshot.go
pkg/backend/snapshot_test.go

This should fix the panic in https://github.com/pulumi/pulumi/issues/13923, but will probably just cause a new error to be raised for that use case.

SameSteps can fail

---

.github/workflows/ci-run-test.yml
pkg/codegen/schema/docs_test.go
pkg/codegen/schema/schema_test.go
pkg/resource/deploy/providers/registry_test.go
pkg/workspace/plugin.go
tests/integration/integration_go_test.go
tests/smoke_test.go

Turns out in https://github.com/pulumi/pulumi/pull/14104 we typo'd the environment variable name, missing the "PULUMI_" prefix at the start.
This change fixes that, and the resulting fall out of tests running with automatic plugin downloads being disabled by default.
One test it made sense to actually check with and without the envvar set. All the others I've just made sure the envvar is falsy so they can fetch the plugins they want to.
I've also un-skipped the tests that had been disabled due to always hitting the rate limits. Hopefully now we should be hitting github less often to allow these to pass consistently.

Actually disable plugin acquisition

---

pkg/cmd/pulumi/state_delete.go

ericrudder 
> @dixler can we make this:
> Resources can't be deleted if other resources depend on it or are parented to it. Protected resources
will not be deleted unless specifically requested using the --force flag.
https://github.com/pulumi/home/pull/2164/files/ffdbe00b62f2fe8c0077ab83e3258eb1687fb769..1867fffa90253f58f1f57b40ad9f6780d9aa6396#r1357277045

Update help text for `pulumi state delete`

---

pkg/cmd/pulumi/refresh.go

https://www.pulumi.com/docs/cli/commands/pulumi_refresh/
Fixing : appear to be out of synch with respect to the cloud provider’s source of truth.
to: appear to be out of sync with respect to the cloud provider’s source of truth.
Fixes #14264

Fixing typo in pulumi_refresh

---

pkg/resource/deploy/deployment_executor.go
pkg/resource/deploy/import.go
pkg/resource/deploy/step_executor.go

This results in much nicer errors being bubbled up to tests. User UX is not changed by this because these errors are always wrapped into Bails and so not shown to users.
We should make a similar change for step generator errors.

Track actual error in StepExecutor

---

changelog/pending/20231016--cli--tightened-the-parser-for-property-paths-to-be-less-prone-to-typos.yaml
sdk/go/common/resource/config/map_test.go
sdk/go/common/resource/properties_path.go
tests/integration/integration_test.go

The key "my:root.[1]" used to not be accepted, because the `.` before the index is invalid.  However through https://github.com/pulumi/pulumi/pull/13814/files#r1320306140 and subsequently https://github.com/pulumi/pulumi/pull/14149, the parsing was loosened.
Presumably we were never checking this at the right level in the first place, and we only accidentally refused to parse it.  Fix this by tightening the conditions when parsing the property path.

tighten up parsing of property path to avoid accepting typos

---

changelog/pending/20231016--engine--fix-automatic-diffs-comparing-against-output-instead-of-input-properties.yaml
pkg/engine/lifecycletest/pulumi_test.go
pkg/resource/deploy/step_generator.go
sdk/go/common/resource/plugin/provider.go
sdk/go/common/resource/plugin/provider_test.go

Fixes https://github.com/pulumi/pulumi/issues/14040
When a provider returns `DiffUnknown` the step generator calculates a simple diff based on the old and new inputs.
We were not correctly marking that this is an input diff, and so when reconstructing objects from the detailed diff later in `TranslateDetailedDiff` we we're looking at the old output properties rather than the old input properties.

Mark diff as an input diff when auto-diffing in the step generator

---

pkg/resource/deploy/source_eval.go
pkg/resource/deploy/source_query.go

The LanguageRuntime in forkRun is from a plugin host, which will cache the runtimes it's asked for and close them when the host is closed.
Closing the runtime here leads to _at least_ an error in the logs when the host tries to close it later and finds the process already gone, and could potentially result in another part of the code asking for the same runtime object and having it killed unexpectedly.

Don't close LanguageRuntime in forkRun

---

sdk/go/auto/local_workspace_test.go

This test has been disabled since it was panic'ing (see https://github.com/pulumi/pulumi/issues/5301), however it is no longer doing that.  Bisecting the issue leads me to 855f1fd1cd1e40c1846916dbfdd622ec1acf4920, which seems to have fixed this.
Fixes #5301

re-enable disabled TestNestedStackFails test

---

Makefile

When testing it's sometimes useful to only build a single SDK to reduce the build time.  Change the makefile so the SDKS variable can optionally be overridden by an environment variable, to allow a developer to easily do so.

Makefile: allow SDKSs to be overridden

---

changelog/pending/20231019--sdk-nodejs--nodejs-now-supports-unknown-resource-ids.yaml
sdk/nodejs/runtime/resource.ts
sdk/nodejs/tests/runtime/langhost/cases/014.read_resource/index.js

Fixes #11719 
NodeJS now accepts unknown resource IDs for read resource.

NodeJS now accepts unknown resource IDs for read resource

---

tests/smoke_test.go

Path needs ".exe" added on Windows.

Fix TestPackageGetSchema for Windows

---

changelog/pending/20231002--cli-new--pulumi-new-now-allows-users-to-bypass-existing-project-name-checks.yaml
pkg/backend/display/options.go
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/new_test.go
pkg/cmd/pulumi/state_edit.go
pkg/cmd/pulumi/util.go

Fixes #13832
[asciinema recording](https://asciinema.org/a/zZvO66E31sMZ0t2DCAbnuMUMW)

`pulumi new` with existing project now can be bypassed

---

changelog/pending/20231020--programgen-go--fix-codegen-to-correctly-output-pulumi-array-instead-of-pulumi-anyarray.yaml
pkg/codegen/go/gen.go
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/azure-native-pp/go/azure-native.go

Currently for an array of objects, codegen for Go outputs a `pulumi.AnyArray` type.  However that does not exist.  Make sure it always outputs the correct `pulumi.Array` type.
While there give Maps the same treatment, as `pulumi.AnyMap` also doesn't exist.
Fixes #https://github.com/pulumi/pulumi/issues/8072

codegen/go: output correct array type

---

changelog/pending/20231021--auto-nodejs--add-support-for-the-path-option-for-config-operations.yaml
sdk/nodejs/automation/localWorkspace.ts
sdk/nodejs/automation/stack.ts
sdk/nodejs/automation/workspace.ts
sdk/nodejs/tests/automation/localWorkspace.spec.ts

Add support for the `--path` flag for config operations in Node.js Automation API.
Part of https://github.com/pulumi/pulumi/issues/5506
Related: https://github.com/pulumi/pulumi/pull/12265
Related: https://github.com/pulumi/pulumi/pull/13052
Related: https://github.com/pulumi/pulumi-dotnet/pull/191

[auto/nodejs] Add support for the path option for config operations

---

changelog/pending/20231023--sdkgen-python--fix-issue-calling-nonexistent-_configure-method-on-external-types.yaml
pkg/codegen/python/gen.go
pkg/codegen/testing/test/testdata/embedded-crd-types/python/pulumi_foo/component.py
pkg/codegen/testing/test/testdata/enum-reference-python/python/pulumi_example/mymodule/iam_resource.py
pkg/codegen/testing/test/testdata/enum-reference/python/pulumi_example/mymodule/iam_resource.py
pkg/codegen/testing/test/testdata/external-resource-schema/python/pulumi_example/component.py

We recently added the ability to assign default values for nested types in generated Python SDKs, when the nested types are passed as dicts. We do so by calling a new static `_configure` method on the input type, to assign default values.
The problem is that we're emitting calls to `_configure` for external types, and such types may not have been upgraded yet to the latest codegen, so they may not have a static `_configure` method yet.
This change makes it so that `_configure` is only called for external types that have a `_configure`, via a runtime `hasattr` check.
Fixes #14316

Fix issue calling nonexistent `_configure` method on external types

---

changelog/pending/20231024--cli-config--dont-crash-on-empty-config-values.yaml
sdk/go/common/resource/config/object.go
sdk/go/common/resource/config/object_test.go

In some cases we construct a nil object, which isn't handled properly when we convert it into a property value.  This is likely related to https://github.com/pulumi/pulumi/issues/14146, where we started allowing such objects as a fix for a similar, but separate issue.
Fixes #14325

fix panic when we have a nil object

---

changelog/pending/20231025--engine--fix-generation-of-property-paths-in-diff.yaml
sdk/go/common/resource/plugin/provider.go
sdk/go/common/resource/plugin/provider_test.go

Fixes https://github.com/pulumi/pulumi/issues/14335.
This was incorrectly building property keys by just splicing "." inbetween every key. This was incorrect for keys which required quoting (e.g. those with "." in the key itself, or other special characters).

Fix PropertyPaths generated by NewDetailedDiffFromObjectDiff

---

changelog/pending/20231020--cli--adds-a-new-pulumi-install-command-which-will-install-packages-and-plugins-for-a-project.yaml
pkg/cmd/pulumi/install.go
pkg/cmd/pulumi/pulumi.go
pkg/codegen/python/gen_program.go
pkg/codegen/testing/test/testdata/components-pp/python/components.py
pkg/codegen/testing/test/testdata/components-pp/python/exampleComponent.py
sdk/python/python.go
tests/smoke_test.go

Fixes https://github.com/pulumi/pulumi/issues/10990.
This also includes a couple of fixes for python to get the `TestLanguageConvertComponentSmoke` test working for it.
Firstly it fixes InstallDependencies to not create a venv if no venv path is set. The language host was trying to install a venv to the same directory as the program itself (that is not nested under "venv" or the like). But then because the runtime option wasn't set the execution wasn't using that created venv anyway.
Secondly the imports for components are not relative. We're not in a proper module when running a python program so relative imports to side-by-side component folders don't work.

Add install command

---

sdk/nodejs/cmd/dynamic-provider/index.ts
sdk/nodejs/package.json
sdk/nodejs/provider/server.ts
sdk/nodejs/runtime/mocks.ts
sdk/nodejs/tests/provider.spec.ts
sdk/nodejs/tests/runtime/langhost/run.spec.ts
sdk/nodejs/tests/runtime/props.spec.ts
sdk/nodejs/yarn.lock

Adds "@types/google-protobuf" to the nodesdk and changes `requires` to plain imports.

Add google-protobuf types

---

changelog/pending/20231028--engine--correctly-propogate-provider-errors-from-diffconfig.yaml
sdk/go/common/resource/plugin/provider_plugin.go

Fixes https://github.com/pulumi/pulumi/issues/14342.
I suspect this has just been a long standing typo. I can't see any reason to ignore this error.

Return errors from DiffConfig

---

changelog/pending/20231028--engine--support-name-in-http-plugin-download-urls.yaml
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_test.go

Allows `${NAME}` in the download url template string.

Support {NAME} in plugin download url

---

changelog/pending/20231030--cli--add-support-for-esc-file-projection.yaml
pkg/cmd/pulumi/config.go
pkg/cmd/pulumi/config_test.go
pkg/go.mod
pkg/go.sum
tests/go.sum

These changes add support for the ESC `files` projection to Pulumi IaC. This projection writes data to temporary files to disk and publishes the path of each file in a user-specified environment variable.

[cli] Support ESC files projection

---

.github/workflows/trigger-homebrew-event.yml
changelog/pending/20231030--ci--bump-homebrew-using-pulumis-fork-instead-of-pulumi-bots.yaml

The pulumi-bot fine-grained token is scoped to the Pulumi org, therefore the repositories it interacts with need to belong to pulumi.
This action was attempting to fork/clone the homebrew repo with the pulumi-bot user as its owner. It should use the pulumi org instead.
I've confirmed that I'm able to fork the repo with this token:
```
❯ gh repo fork --clone homebrew/homebrew-core --org pulumi
✓ Created fork pulumi/homebrew-core
```
Fixes #14412

Bump homebrew with pulumi's fork instead of pulumi-bot's

---

changelog/pending/20231030--engine--fix-parsing-of-property-paths-such-as-root-1-being-returned-from-providers.yaml
sdk/go/common/resource/config/map_test.go
sdk/go/common/resource/properties_path.go
sdk/go/common/resource/properties_path_test.go
tests/integration/integration_test.go

Fixes https://github.com/pulumi/pulumi/issues/14439.
Ideally we would treat this as an error, but it seems providers are building property paths of this format so we need to keep supporting it.
It is at least now tested, and clearly linked back to this issue so we don't inadvertantly remove support for it in the future.
Yet another element of the system that could be tightened up in a V4 release.

Support 'key.[index]' in property paths

---

changelog/pending/20231031--cli-new--adds-support-for-remote-zip-archive-templates-to-pulumi-new.yaml
sdk/go/common/workspace/templates.go
sdk/go/common/workspace/templates_zip.go
sdk/go/common/workspace/templates_zip_test.go

Fixes https://github.com/pulumi/pulumi.ai/issues/363
This change introduces a new accepted suffix to `pulumi new` HTTP arguments - `.zip`.
When a URL of the form `http[s]://<url>.zip` is provided to `pulumi new`, we send a GET request to `<url>` (without the .zip suffix) with the `accept` header set to `application/zip`. It is then up to whatever is hosted at that location to correctly return a binary zip archive in its response.
We then parse that response in memory and write each file to a tempdir as we do with current templates, which can then be picked up by the standard `pulumi new` templating logic.

Adds remote .zip archive support to `pulumi new`

---

changelog/pending/20230913--backend-filestate--file-locks-are-no-longer-taken-during-the-preview-phase-of-update.yaml
pkg/backend/filestate/backend.go

This aligns the filestate behavior with httpstate in that we won't take a lock during the preview phase of an update. Instead we take the lock at the point we start doing a non-preview apply
We've tried this once before (https://github.com/pulumi/pulumi/pull/8806) but got a couple of user reports about locking not working soon after it released, and so reverted it just in case. Further investigation into those user issues suggested they were due to user fault, not this change.
There's one comment from myself on Slack from around that time saying I'm not sure this change is correct, but even with that nudge and looking at it with fresh eyes I think it is. But worth having a hard think about this before hitting approve.

Move filestate locking to apply time

---

pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/import_test.go

This error was a bit confusing because it just said the Parent had no name, but what was really missing was an entry for that name in the nameTable telling us the URN.

Make import error a bit more clear

---

changelog/pending/20231101--sdk-python--fix-error-on-empty-invoke-returns.yaml
sdk/python/lib/pulumi/runtime/invoke.py
sdk/python/lib/test/langhost/invoke_empty_return/__init__.py
sdk/python/lib/test/langhost/invoke_empty_return/__main__.py
sdk/python/lib/test/langhost/invoke_empty_return/test_invoke_empty_return.py
sdk/python/lib/test/test_invoke.py

When an empty struct is returned from an invoke, the Python SDK was returning None, which causes the following error to be raised from generated provider Python SDKs when calling the invoke:
```
AssertionError: get can only be used with classes decorated with @input_type or @output_type
```
This is because the Python SDK is returning None if the return value isn't truthy, roughly:
```
ret_obj = getattr(resp, "return")
if ret_obj:
return ret_obj
return None
```
However, an empty struct isn't truthy, so we're returning None in that case, and generated provider Python SDKs can't handle that.
Other SDKs like the Node.js and Go SDKs don't have this problem.
This commit fixes the issue by removing the `if ret_obj` check, as it's not necessary. In practice, `ret_obj` is always going to be an …

[sdk/python] Fix error on empty invoke returns

---

changelog/pending/20231101--cli-new--adds-nested-directory-support-to-pulumi-new-zip.yaml
sdk/go/common/workspace/templates_zip.go
sdk/go/common/workspace/templates_zip_test.go

The previous ZIP implementation here only supported a flat .zip file structure - Pulumi Java projects often contain nested directories (and many templates will likely organize code in such a way that involves directories as well). This inspects each file during traversal of the ZIP archive, and creates any necessary directories it encounters along the way.

Adds nested directory support to pulumi new .zip

---

changelog/pending/20231021--auto-nodejs--add-refresh-option-for-up.yaml
sdk/nodejs/automation/stack.ts

Adding the `refresh` option to `up` in the NodeJS automation API
Mirror of this PR adding support for `refresh` in `preview` (https://github.com/pulumi/pulumi/issues/12740)

add refresh option for up in NodeJS automation API

---

changelog/pending/20231030--auto-nodejs--pin-atgrpc-grpc-js-to-v1-9-6-to-resolve-automation-api-hang-in-nodejs.yaml
sdk/nodejs/package.json
sdk/nodejs/tests/automation/localWorkspace.spec.ts
sdk/nodejs/yarn.lock

Fixes #13687 
A bug in @grpc/grpc-js v1.9.7 causes Automation API to hang. Pinning to
v1.9.6 resolves this hang.
See the added test case.

[sdk/nodejs] pin `@grpc/grpc-js` to `v1.9.6` to resolve automation API hang

---

changelog/pending/20230913--backend-filestate--file-locks-are-no-longer-taken-during-the-preview-phase-of-update.yaml
pkg/backend/filestate/backend.go

This reverts commit 7f1b75d2360317d8aea0e586e99e382553fa0cb3.

Revert "Move filestate locking to apply time (#13948)"

---

.github/workflows/trigger-homebrew-event.yml
changelog/pending/20231102--ci--additional-fixes-for-the-homebrew-release-job.yaml

Fine-grained tokens can't submit PRs against public repos, so we need to continue using classic PATs for this use case.
I'm removing the `org: pulumi` so it will continue to interact with the repo under the `pulumi-bot`. I think this should allow us to still restrict PATs on the pulumi org.
I've already added a `PULUMI_BOT_HOMEBREW_TOKEN` secret to the repo. 
Fixes https://github.com/pulumi/pulumi/issues/14412

[ci] More fixes for the homebrew release job

---

changelog/pending/20231102--programgen-go--fix-using-inline-invoke-expressions-inside-resources-objects-and-arrays.yaml
pkg/codegen/go/gen_program.go
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/go/gen_program_inline_invoke.go
pkg/codegen/go/gen_program_test.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/inline-invokes-pp/dotnet/inline-invokes.cs
pkg/codegen/testing/test/testdata/inline-invokes-pp/go/inline-invokes.go
pkg/codegen/testing/test/testdata/inline-invokes-pp/inline-invokes.pp
pkg/codegen/testing/test/testdata/inline-invokes-pp/nodejs/inline-invokes.ts
pkg/codegen/testing/test/testdata/inline-invokes-pp/python/inline-invokes.py

This PR fixes an issue in Go program where if users are writing invoke expressions inline inside other expressions, then that invoke is extracted into a temporary variable and then later referenced the same way it was used. This is because non-output-versioned invokes cannot be used directly since they return a tuple (InvokeResult, err) so we need to check for the error before proceeding. 
Fixes #14064

[go/program-gen] Fix using inline invoke expressions inside resources, objects and arrays

---

changelog/pending/20231103--sdk-python--add-provider-side-caching-for-dynamic-provider-deserialization.yaml
sdk/python/lib/pulumi/dynamic/__main__.py

Provider side fix for https://github.com/pulumi/pulumi/issues/6675, similar to change made to NodeJS in https://github.com/pulumi/pulumi/pull/6657.
This might also help with https://github.com/pulumi/pulumi/issues/14159, as investigation there looks like the issue might be due to memory pressure.

Add deserialisation cache to Python dynamic provider

---

changelog/pending/20231103--pkg--fixes-a-panic-in-property-mapping-logic.yaml
sdk/go/common/util/mapper/mapper_encode.go
sdk/go/common/util/mapper/mapper_test.go

Fixes a panic that occurs when attempting to encode certain values, for example a map that contains a nil value:
```go
bag := bagtag{
String:    "something",
StringOpt: "ohmv",
MapOpt: map[string]interface{}{
"a": "something",
"b": nil,   // this reflect.Value is of type Interface and IsNil is true.
},
}
_ = resource.NewPropertyMap(bag) // panic here
```
New tests are provided to cover the above scenario and to cover each type of value, including nil cases where appropriate.
Fixes: https://github.com/pulumi/pulumi-kubernetes/issues/2622
Follow-up to: https://github.com/pulumi/pulumi/pull/9810

Fix panic in mapper_encode

---

changelog/pending/20231106--cli-new--fix-panic-parsing-template-url.yaml
sdk/go/common/workspace/templates_zip.go
sdk/go/common/workspace/templates_zip_test.go

Fixes https://github.com/pulumi/pulumi/issues/14505.

Fix panic in isZIPTemplateURL

---

proto/.checksum.txt
proto/generate.sh
sdk/nodejs/proto/alias_pb.js
sdk/nodejs/proto/analyzer_pb.js
sdk/nodejs/proto/codegen/hcl_pb.js
sdk/nodejs/proto/codegen/loader_grpc_pb.js
sdk/nodejs/proto/codegen/loader_pb.js
sdk/nodejs/proto/codegen/mapper_grpc_pb.js
sdk/nodejs/proto/codegen/mapper_pb.js
sdk/nodejs/proto/converter_pb.js
sdk/nodejs/proto/engine_pb.js
sdk/nodejs/proto/errors_pb.js
sdk/nodejs/proto/language_pb.js
sdk/nodejs/proto/plugin_pb.js
sdk/nodejs/proto/provider_pb.js
sdk/nodejs/proto/resource_pb.js
sdk/nodejs/proto/source_pb.js
sdk/nodejs/proto/testing/language_grpc_pb.js
sdk/nodejs/proto/testing/language_pb.js

The proto/generate.sh script was trying to do some sed based fixups to the generated javascript files but wasn't correctly fixing up nested files.

Fix recursive fixups in JavaScript protobuf generation

---

changelog/pending/20231031--engine--import-can-now-import-a-parent-resource-in-the-same-deployment-as-a-child-resource.yaml
pkg/engine/lifecycletest/import_test.go
pkg/resource/deploy/import.go
pkg/resource/deploy/step.go

Allow `pulumi import` to import one resource and then use that resource as a parent for another imported resource.
Currently parents can only refer to resources that already exist in the deployment meaning if you want to do this today you have to do two imports.

Allow importing a parent and child resource at the same time

---

changelog/pending/20231110--engine--ignore-spurious-error-from-kubernetes-providers-diffconfig-method.yaml
sdk/go/common/resource/plugin/provider_plugin.go
sdk/go/common/resource/plugin/provider_plugin_test.go

Fixes https://github.com/pulumi/pulumi/issues/14529.

Ignore spurious error from kubernetes DiffConfig

---

pkg/backend/backend_test.go
pkg/codegen/testing/test/testdata/output-funcs-tfbridge20/go-extras/tests/codegen_test.go
pkg/codegen/testing/test/testdata/output-funcs/go-extras/tests/codegen_test.go
pkg/codegen/testing/test/testdata/plain-object-defaults/go-extras/tests/codegen_test.go
pkg/importer/hcl2_test.go

Prompted by https://github.com/pulumi/pulumi/pull/14534, replace all the cases of `V.(typeCast)` with the accessor methods instead.

Replace PropertyValue type casts with method calls

---

changelog/pending/20230908--cli-config--config-refresh-will-now-restore-secret-provider-config-from-the-last-deployment.yaml
pkg/cmd/pulumi/config.go
pkg/resource/stack/deployment.go
pkg/secrets/cloud/manager.go
pkg/secrets/passphrase/manager.go

Fixes https://github.com/pulumi/pulumi/issues/7282
This is fairly simple, just grab the last deployment from the stack (we should have one otherwise we wouldn't have any config to fetch either) and pull the SecretsProviders data out the deployment data and translate and insert it into the stack config.

Restore secrets provider in config refresh

---

changelog/pending/20231113--cli-new--simplifies-url-parsing-for-pulumi-new-zip.yaml
sdk/go/common/workspace/templates_zip.go

Currently, we add a bit of "cleverness" to our URL parsing, by removing `.zip` suffixes when we've determined one exists (and started down the path of pulumi new-ing a zip ref). That requires upstream API providers to host their zipfiles at a location _without_ that suffix, which precludes any existing .zip files hosted at places like github etc which may have that extension. 
This PR removes that logic so we serve as a simple passthrough for whichever URL we're passed (extending the existing contract).  It also depends on https://github.com/pulumi/pulumi.ai/pull/414 being merged and deployed.
Fixes https://github.com/pulumi/pulumi.ai/issues/415

Simplifies URL parsing for pulumi new <zip>

---

changelog/pending/20231031--engine--import-can-now-create-empty-component-resource-to-use-as-the-parent-of-other-imported-resources.yaml
pkg/cmd/pulumi/import.go
pkg/engine/deployment.go
pkg/engine/lifecycletest/import_test.go
pkg/resource/deploy/import.go
pkg/resource/deploy/step.go

Fixes https://github.com/pulumi/pulumi/issues/14444.
This adds two new flags to the import file to signal that a resource is a component, and also if that is a remote (MLC) component. The import system will create empty resources for those import descriptions, but importantly they can then be used as parents for other resources in the import deployment.
We need to know if it's a remote component to know if a provider should be looked up for it. We could probably get away with _just_ knowing if it's a component at import time and not doing any validation that the type token is well formed and the provider exists for MLCs. That makes import a little simpler for users (no need to set if it's remote or not) but pushes error cases downstream to when they actually try to `up` their program. It …

Allow `import` to create empty component resources

---

changelog/pending/20231113--engine--import-files-no-longer-need-parent-urns-in-the-name-table-for-resource-being-imported-in-the-same-file.yaml
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/import_test.go

This allows you to use the parent feature in an import file for another resource in the same deployment without having to fill in what the URN for that parent resource is in the name table.

Auto fill in URNs for parents in import files

---

changelog/pending/20231111--sdk-python--maintain-old-behavior-for-empty-kubernetes-invoke-results.yaml
sdk/python/lib/pulumi/runtime/invoke.py
sdk/python/lib/test/test_invoke.py

The hand-rolled invoke code in the Kubernetes Python SDK is not expecting empty dicts for empty results. Instead, it has code that checks for `None`.
In general, we want to keep the behavior of returning empty dicts rather than `None` for empty results, as this aligns with the behavior of other SDKs (Node.js and Go) and is actually the original behavior of the Python SDK (it regressed unintentionally in the v2 timeframe).
We're updating the Kubernetes Python SDK to be resilient to either getting an empty dict or `None` for invokes with empty results.
Additionally, to maintain compat with older versions of the Kubernetes Python SDK, we'll special case those invoke tokens. When an invoke's result is empty and the token is one of the Kubernete's function tokens, we'll return `None` rather …

[sdk/python] Maintain old behavior for empty k8s invoke results

---

pkg/cmd/pulumi/about_env.go
pkg/cmd/pulumi/config.go
pkg/cmd/pulumi/plugin_ls.go
pkg/cmd/pulumi/policy_group_ls.go
pkg/cmd/pulumi/policy_ls.go
pkg/cmd/pulumi/stack.go
pkg/cmd/pulumi/stack_ls.go
pkg/cmd/pulumi/stack_tag.go
pkg/cmd/pulumi/util.go
sdk/go/common/util/cmdutil/console.go

These changes colorize the header row of each table printed by the CLI using the `SpecHeadline` style (bold + pinkish). This improves the readability of the tables on rich terminals.

[cli] Colorize table headers

---

changelog/pending/20231115--engine--fix-ignore-changes-ignoring-secret-values.yaml
pkg/engine/lifecycletest/pulumi_test.go
sdk/go/common/resource/properties_path.go
sdk/go/common/resource/properties_path_test.go

Fixes https://github.com/pulumi/pulumi/issues/6272.
#6272 was failing because the type checks in `PropertyPath.Reset` were too strict. We'd check if a value was an object or array to correctly traverse it, but didn't handle that it might be a "secret object" or "secret array". 
Pretty simple fix, we can just unwrap any outer layers of secretness at each layer as we traverse.

Fix ignoreChanges to handle secrets

---

scripts/get-job-matrix.py

.NET 8 is released, we should ensure tests run against that now.

Run dotnet tests on 8

---

pkg/backend/httpstate/diffs.go
pkg/engine/lifecycletest/test_plan.go
sdk/go/common/promise/promise.go
sdk/go/common/promise/promise_test.go
sdk/go/common/resource/plugin/provider_plugin.go
sdk/go/common/resource/plugin/provider_plugin_test.go

Prompted by having another case in https://github.com/pulumi/pulumi/pull/14548 that looked like "this is just a promise".
We already had a mini-promise library for provider config in sdk/go/common/resource/plugin/provider_plugin.go. Plus a couple of places where we did a poor mans Go promise by having a WaitGroup plus a variable to set (see the two changes in /pkg).
This adds a little promise library to safely cover all three of these cases plus the case I'll be adding in #14548. It is _minimal_ adding just the features of promises needed for these initial cases. We can add to it as needed.
I suspect we've got a number of places in test code that could probably use this as well, but I haven't gone through that. I also suspect that having this type available will result in more places in …

Add a strict opinionated promise library

---

scripts/get-job-matrix.py

In general, our test matrix runs on the minimum supported version and latest version of each language runtime. Python 3.8.x is still a supported version so try running the tests on 3.8.x.

Update test matrix to run on Python 3.8.x

---

pkg/engine/lifecycletest/refresh_test.go
pkg/engine/lifecycletest/test_plan.go

Fixes https://github.com/pulumi/pulumi/issues/14588.

Don't use callerCtx for cancellation in runWithContext

---

changelog/pending/20231115--cli-import--generated-import-files-from-converter-plugins-omit-empty-optional-fields.yaml
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/import_test.go

Small fixup to the JSON annotations for `importFile` and a little test to verify that. Just want to ensure we don't write out generated import files with all the optional fields written out with empty values, they should just be omited.

Cleanup generated import files

---

pkg/resource/deploy/source_eval.go
sdk/go/common/resource/config/map.go
sdk/go/common/resource/config/map_test.go
sdk/go/common/resource/config/object.go
sdk/go/common/resource/config/object_test.go
sdk/go/common/resource/config/plaintext.go

- Plumb a `context.Context` parameter to pass to the decrypter
- Rephrase conversion over `config.Plaintext` values in order to decouple decryption and conversion

[config] Clean up toDecryptedPropertyValue

---

pkg/backend/apply_test.go
pkg/backend/cancellation_scope.go
pkg/backend/display/diff_test.go
pkg/backend/display/events.go
pkg/backend/display/events_test.go
pkg/backend/display/progress.go
pkg/backend/display/progress_test.go
pkg/backend/httpstate/backend.go
pkg/cmd/pulumi/replay_events.go
pkg/engine/destroy.go
pkg/engine/events.go
pkg/engine/import.go
pkg/engine/query.go
pkg/engine/refresh.go
pkg/engine/update.go

Small refactor I noticed while writing a test with engine events. We always had to call `NewEvent` with the tag and payload value for an event and these _had_ to match up else the engine panics. But we can just pass the payload and type switch to work out the tag. Means one less parameter to pass to `NewEvent` and pretty much no chance of it going wrong. To ensure there's really no chance I've added a generic union type so you can only pass payload types to this method now. 
Cancel had to be handled separately because it doesn't have a payload type, it's just nil.

Make `engine.NewEvent` type safe

---

changelog/pending/20231117--cli-engine--fix-an-issue-where-the-cli-could-panic-because-of-a-newly-introduced-event.yaml
pkg/backend/display/diff.go
pkg/backend/display/events.go
pkg/backend/display/json.go
pkg/backend/display/query.go
pkg/backend/display/watch.go
sdk/go/common/apitype/events.go

When introducing the PolicyLoadEvent I missed handling it in some cases.  Do so now to avoid panics because it's not handled properly.
Fixes #14598

handle PolicyLoadEvent in more cases

---

changelog/pending/20231117--engine--fix-a-panic-in-cancellation.yaml
pkg/resource/deploy/step_executor.go
sdk/go/common/promise/promise.go
sdk/go/common/promise/promise_test.go

Fixes https://github.com/pulumi/pulumi/issues/14611.
`atomic.Value` panics if a second value is written to it which isn't _exactly_ the same type. We were using this to atomically record any errors that happened, although where only interested in saving the first error.
This was fine if no or one error happened, or if multiple errors happened that all were the same error type. But if two errors if different error types happened `sync.Value` would panic.
Switched to use a promise completion source instead. If any error happens we use it to reject the completion source, we also log if this isn't the first error we've seen (a capabilitiy that `sync.Value` didn't give us). At the end of the step executor being used when `Errored()` is called we try to get the result of the completion source.

Use promise rather than `atomic.Value` to record step errors.

---

changelog/pending/20231115--sdk-go--add-project-template-fields.yaml
sdk/go/common/workspace/project.go
sdk/go/common/workspace/project.json

Add support for two new fields to a project template block:
* `DisplayName` which is used to store a user friendly template name
* `Tags` which is used to store additional template metadata that is author-defined (e.g. team, environment, etc.)
This information will be used in the near-term within the console but longer term could also be used within the CLI.
Since this change only adds optional fields I didn't think tests would be worthwhile. I can add tests if it's thought they would be valuable.

[sdk] add optional display name and tag fields to project templates

---

pkg/backend/apply.go
pkg/backend/display/display.go
pkg/engine/events.go
pkg/engine/lifecycletest/alias_test.go
pkg/engine/lifecycletest/pulumi_test.go
pkg/engine/update.go
sdk/go/common/channel/channel.go
sdk/go/common/channel/channel_test.go

Currently the engine skips sending some resource events to the event stream. Currently that's any "RemovePendingDelete" steps and anything to do with default providers.
This was added so that we wouldn't display "internal implemntation details" like default providers to the user in the tree or diff views.
However we wanted to use the engine event stream to support generating an import file from preview deployments (make an import for every resource that needs to be created). This mostly works except for the imports we also need to know some of the provider details, and while the event stream will tell us about explicit providers the skipping of default providers means we can't get their information in the import generater code.
So this moves this filtering out of the engine and to the …

Send all events to the engine event stream

---

changelog/pending/20231116--sdk-python--introduces-runtimeerror-when-we-detect-a-cycle-upon-adding-dependencies-to-the-graph.yaml
sdk/go/common/env/env.go
sdk/python/lib/pulumi/runtime/rpc.py
sdk/python/lib/test/langhost/component_dependencies/test_component_dependencies.py
sdk/python/lib/test/test_resource.py
tests/integration/integration_python_test.go
tests/integration/python/implicit-dependency-cycles/.gitignore
tests/integration/python/implicit-dependency-cycles/Pulumi.yaml
tests/integration/python/implicit-dependency-cycles/__main__.py

Currently, when we detect that we've created a cycle in the dependency graph, we early-exit. This works well enough for simple cycles, but when early exiting is not sufficient (as when providing a resource output as an argument to another resource's inputs), we will still fail to resolve the full dependency graph. This PR introduces an exception-by-default, as any cycles represent an unsafe/invalid dependency graph and should be resolved manually. We also provide an escape hatch to fall back to current behavior, in case users would prefer to retain the ability to create unsafe dependency graphs (potentially introducing infinite hangs when resolving those graphs).
Fixes https://github.com/pulumi/pulumi/issues/13551

[sdk/python] Adds a default exception when dependency cycles are created

---

changelog/pending/20231122--cli-config--add-a-command-to-create-an-esc-environment-from-stack-config.yaml
pkg/backend/backend.go
pkg/backend/mock.go
pkg/cmd/pulumi/config_env.go
pkg/cmd/pulumi/config_env_init.go
pkg/cmd/pulumi/config_env_init_test.go
pkg/cmd/pulumi/config_env_test.go
pkg/go.mod

This change adds a command, `pulumi config env init`, that creates a new environment for a stack based on the stack's configuration values.
From the usage:
* `pulumi config env init`
Creates an environment for a specific stack based on the stack's configuration values, then replaces the stack's configuration values with a reference to that environment. The environment will be created in the same organization as the stack.

[esc] Add a command to create an ESC env from stack config

---

.github/workflows/cron-direct-build.yml

We've seen some issues with dependencies being yanked. We'll try a direct build once a day so we get earlier warning of these before they go missing from the go build caches.

Try a direct build once a day

---

pkg/importer/hcl2.go
pkg/importer/hcl2_test.go
pkg/importer/testdata/cases.json

No user visible change here, just laying the groundwork for import to be able to have "logical names" (i.e. what's set in state and the URN) and "program names" (i.e. what the source code and import file use, must be unique).

GenerateHCL2Definition should respect logical names

---

changelog/pending/20231122--programgen-nodejs--fix-generated-readfile-function-so-that-it-includes-the-encoding-and-returns-a-string.yaml
pkg/codegen/nodejs/gen_program_expressions.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/read-file-func-pp/dotnet/read-file-func.cs
pkg/codegen/testing/test/testdata/read-file-func-pp/nodejs/read-file-func.ts
pkg/codegen/testing/test/testdata/transpiled_examples/readme-pp/nodejs/readme.ts

Small fix for generated `readFile` function so that it includes the encoding and returns a string
Fixes #14630

[typescrypt/program-gen] Fix generated readFile function so that it includes the encoding

---

changelog/pending/20231122--auto-go--fix-a-datarace-in-cloning-git-repos.yaml
sdk/go/auto/git.go

Fixes a datarace in setupGitRepo seen in CI:
```
=== FAIL: go/auto TestNewStackRemoteSource (44.69s)
==================
Read at 0x000002d35650 by goroutine 103:
github.com/pulumi/pulumi/sdk/v3/go/auto.setupGitRepo()
/Users/runner/work/pulumi/pulumi/sdk/go/auto/git.go:125 +0xf78
github.com/pulumi/pulumi/sdk/v3/go/auto.NewLocalWorkspace()
/Users/runner/work/pulumi/pulumi/sdk/go/auto/local_workspace.go:778 +0x435
github.com/pulumi/pulumi/sdk/v3/go/auto.NewStackRemoteSource()
/Users/runner/work/pulumi/pulumi/sdk/go/auto/local_workspace.go:1114 +0x2c4
github.com/pulumi/pulumi/sdk/v3/go/auto.TestNewStackRemoteSource()
/Users/runner/work/pulumi/pulumi/sdk/go/auto/local_workspace_test.go:465 +0x326
testing.tRunner()
/Users/runner/hostedtoolcache/go/1.21.1/x64/src/testing/testing …
```

Fix datarace in setupGitRepo

---

cmd/pulumi-test-language/interface.go

Because BindSpec was being passed nil for the loader parameter it was creating a new default plugin host, instead of using the mocked one we create as part of the test-language code.
No real observable effect as yet, but would of been an issue once we start having test schemas that refer to each other.

Fix test-language to not use the default loader for binding

---

sdk/go/common/workspace/plugins_install_test.go

This isn't currently getting picked up by the linter because it's behind a build tag and the linter doesn't run with those set.
It _should_ because it turns out loads of test files aren't being linted right now, but there's quite a few fixes that need to happen so linting doesn't then fail, so this is just one step towards that.

Fix some lint issues in plugins_install_test.go

---

changelog/pending/20231123--sdkgen--fixes-marshalling-the-plain-flag-from-object-or-resource-properties.yaml
pkg/codegen/schema/schema.go
pkg/codegen/schema/schema_test.go
pkg/codegen/testing/test/testdata/plain-properties-1.0.0.json
pkg/codegen/testing/utils/host.go

When marshalling a schema that has resources or types with plain properties, the `plain` flag was not preserved. This PR fixes it and adds a roundtrip test for the plain properties.

[schema] Fixes marshalling the "plain" flag from object or resource properties

---

.github/workflows/on-pr-close.yml
.github/workflows/pr-test-codegen-downstream.yml

Fixes #14530
Adds back downstream codegen tests
- aws
- gcp
- azure
- azuread
- random
- awsx

[ci] Add downstream codegen tests back

---

changelog/pending/20231121--sdk-go--Fix-optional-handling-on-nested-props.yaml
sdk/go/pulumi/provider.go
sdk/go/pulumi/provider_test.go
sdk/go/pulumi/rpc.go

When you had a provider that accepted a nested struct that had optional props. Those props were always empty. Example: https://github.com/MMartyn/pulumi-foo/tree/repro/optional-bug/examples/optional
From walking through the execution the tags weren't stripping the `,optional` out before looking up the property so it wasn't finding them and copying the values.

Fix optional handling on nested props

---

changelog/pending/20231127--auto-go--fixes-event-stream-lag-on-windows-runtime.yaml
sdk/go/auto/stack.go

Hey guys, first PR at Pulumi.
On windows (Windows 11) I have been getting event streaming lag using `optup.EventStreams` for the go automation sdk, basically I get no events until the file has stopped writing. This does not occur on other platforms.
We can fix this by polling on windows instead of using the default inotify within watchFile.

[auto] Fixes event stream lag on windows runtime

---

changelog/pending/20231129--engine--fix-root-directory-passed-to-langauge-plugins-when-starting-pulumi-in-a-subfolder.yaml
sdk/go/common/resource/plugin/context.go
tests/integration/integration_python_acceptance_test.go

Pretty sure this has been broken since forever.
Pretty sure it's only _mostly_ worked because we nearly always run pulumi from the directory with the Pulumi.yaml file and there's a bit of code in `buildArgsForNewPlugin` that calls `filepath.Abs(root)` before passing it to the language plugins. `Abs("")` will just resolve to the working directory, which as above is nearly always the one with the Pulumi.yaml file in it.

Actually save root on plugin.Context

---

pkg/cmd/pulumi/stack.go

This PR adds text for the `pulumi stack` command to clarify that you can also view the stack of the stack with it.
Fixes [this issue](https://github.com/pulumi/pulumi/issues/9677).

Add clarifying text for `pulumi stack` command

---

changelog/pending/20231022--sdkgen-dotnet--added-support-for-language-specific-settings-for-resources-and-support-for-overriding-resource-name-in-dotnet-codegen.yaml
pkg/codegen/dotnet/gen.go
pkg/codegen/dotnet/gen_program.go
pkg/codegen/dotnet/importer.go
pkg/codegen/schema/schema.go
pkg/codegen/schema/schema_test.go

This PR contains changes to support language specific settings for resources. This PR is a prerequisite to resolve a corresponding [bug](https://github.com/pulumi/pulumi-terraform-bridge/issues/1460) in the Terraform Bridge.
Fixes https://github.com/pulumi/pulumi-terraform-bridge/issues/1460

feat: Add support for language specific settings for resources

---

changelog/pending/20231129--sdk-nodejs--enable-resource-imports-for-nodejs-providers.yaml
sdk/nodejs/provider/provider.ts
sdk/nodejs/provider/server.ts

I was writing a typescript resource provider, but got errors that the the plugin didn't support imports, while the `read` method was implemented on the provider.
This PR also sets the `Inputs` on the `ReadResponse`, so imports will be supported.
Could not find existing issue
(None of the above, since the change is in js code)
There are no existing tests for the `server.ts` file. If really required for merging I could maybe take a look at a test for this use-case.

feat: enable imports from nodejs provider resources

---

tests/integration/valid-property-names/step1/.gitignore
tests/integration/valid-property-names/step1/Pulumi.yaml
tests/integration/valid-property-names/step1/index.ts
tests/integration/valid-property-names/step1/package.json
tests/integration/valid-property-names/step1/resource.ts
tests/integration/valid-property-names/step2/index.ts
tests/integration/valid-property-names/steps_test.go

Fixes #14571
Adds integration tests that check that resource property names that are
invalid property paths do not trigger errors in diff logic.
Internal Postmortem: https://docs.google.com/document/d/1kMcw3RUZZ98Aq5Na-f-oLNVWlDsdPAl8EdQmEVoQv1I

[testing] Add integration tests for regressions in property name parsing

---

changelog/pending/20231130--sdk-nodejs--use-local-storage-to-track-per-stack-error-log-count.yaml
sdk/nodejs/log/index.ts
sdk/nodejs/runtime/state.ts
sdk/nodejs/tests/automation/localWorkspace.spec.ts

Fixes #12521
The log module for the nodejs SDK keeps track of an error count in a global, this should be stored in the stack's local store.

Recover after a failed automatation run

---

tests/integration/integration_python_test.go

Running locally this test seems to be the one hanging intermitently. Suggest we merge this to skip it and see if CI improves.

Skip TestFailsOnImplicitDependencyCyclesPython

---

pkg/engine/lifecycletest/pulumi_test.go
pkg/resource/deploy/step_generator_test.go

Issue #9054 described a problem with `ignoreChanges` not working correctly when using square bracket notation.
- This PR extends some tests that verify property paths and the ignoreChanges mechanism.
- These tests demonstrate that the code exhibits the required behavior
- The behavior described in the issue does not currently reproduce with the scenario described in the issue report. This has been verified manually, and I have closed the issue as **can't repo**

Extended tests for property paths and ignoreChanges

---

pkg/codegen/schema/schema.go
pkg/codegen/schema/schema_test.go
pkg/codegen/testing/test/testdata/plain-properties-1.0.0.json

Follow up for #14648 because when I tried it against existing providers as follows:
```
~/.pulumi-dev/bin/pulumi package get-schema random
```
It marks all resource properties as plain even when they are not. This PR fixes it and extends the unit test to assert both plain and non-plain properties of resources and object types

[schema] Fix package get-schema marking resource properties as plain

---

scripts/retry

CI added log output to clarify success despite test failure output.
- `run tests` may end with a failing test being the last thing printed, but it was retried and passed.

[ci] improve test logging on retries

---

changelog/pending/20231201--auto-python--ensures-that-the-project_settings-has-a-main-directory-for-inline-programs-in-python.yaml
sdk/python/lib/pulumi/automation/_local_workspace.py
sdk/python/lib/test/automation/test_errors.py
sdk/python/lib/test/automation/test_local_workspace.py

Currently if no project settings are provided this is the default value for `main`, but if the caller providers a project_settings object without this set it will cause a module load issue if the inline program depends on other local python files. The current work-around is to put all the code in one file or set `work_dir`.
Fixes #7960

Sets the `main` project setting to the cwd for inline programs

---

changelog/pending/20231201--cli-display--fix-a-panic-in-diff-display-when-parsing-yaml-strings.yaml
pkg/backend/display/object_diff.go
pkg/backend/display/object_diff_test.go

To make sure all of the string was consumed by the YAML decoder, we'd call `yamlDecoder.Decode(nil)` to see if it returned an `io.EOF` error. However, if it's not EOF, the decoder panics when `nil` is passed-in. Instead, pass in a valid argument for cases that aren't EOF.
Fixes #14558

Fix a panic in diff display when parsing YAML strings

---

changelog/pending/20231128--engine--error-if-a-resources-parent-is-a-skipped-create.yaml
pkg/engine/lifecycletest/target_test.go
pkg/resource/deploy/step_generator.go

Fixes https://github.com/pulumi/pulumi/issues/14531.
We had a check in the step generator to not execute steps for a resource that had a dependency which was a skipped create. But this didn't check for parent or provider dependencies.

Error if a resource's parent is a skipped create

---

changelog/pending/20231128--engine--warn-if-sdks-are-trying-to-use-old-registerresource-style-stackreferences.yaml
pkg/engine/lifecycletest/pulumi_test.go
pkg/resource/deploy/builtins.go
pkg/resource/deploy/deployment.go
pkg/resource/deploy/import.go
pkg/resource/deploy/source_query.go

Noticed this while looking at https://github.com/pulumi/pulumi-yaml/issues/462 with @julienp.
StackReferences only really work properly when 'read'. When registered they don't behave as expected because they don't diff (no input properties change) so they don't update so they don't get the new stack output values.
Looks like all the SDKs but YAML we're doing this correctly, so I've updated the engine test to do a read and will change the check/diff/create methods to log a warning that the user SDKs must be old. At some point we can clean these up to just only allow reading of stack reference types.

Warn if StackReferences are registered instead of read

---

changelog/pending/20231130--engine--engine-now-prefers-stable-plugin-versions-to-pre-releases-when-no-explict-version-is-given.yaml
pkg/codegen/report/report_test.go
pkg/resource/deploy/deploytest/pluginhost.go
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_install_test.go
sdk/go/common/workspace/plugins_test.go

Fixes https://github.com/pulumi/pulumi/issues/14680.
Updated the plugin logic (which we still use when no explict version is given) to prefer selecting a stable version over a pre-release version when no explict requested version is given.

Prefer stable plugin release to pre-releases

---

.github/workflows/ci-run-test.yml
.github/workflows/ci.yml

Fixes #13835
Change CodeCov to only upload on completely if all jobs succeed. Consolidates CodeCov upload task in `ci-run-test.yml` to `ci.yml`.
There are extraneous commits that will be squashed before merging to retain commit `55e783c997021d9c5fae2252708ad35f62eb20c6` displaying a successful run for the reviewer.

[ci] Consolidate CodeCov Upload

---

pkg/backend/display/display.go
pkg/backend/display/object_diff.go
pkg/cmd/pulumi/stack.go
pkg/importer/hcl2.go
pkg/resource/deploy/deployment.go
pkg/resource/deploy/import.go
pkg/resource/deploy/snapshot.go
pkg/resource/deploy/step.go
pkg/resource/deploy/step_generator.go
pkg/resource/edit/operations.go
pkg/resource/stack/checkpoint.go
pkg/testing/integration/program.go
sdk/go/pulumi/mocks.go

With the introduction of component programs there will be mulitple "pulumi:pulumi:stack" resources in a program. We should therefore check against the qualified type of resources to see if they are the root stack, not just their direct type.

Check qualified type for root stackness

---

pkg/testing/integration/program.go

This PR fixes a small problem with `ProgramTest`, that the `With` function doesn't propagate the `PostPrepareProject` option  as it should.  e.g.
```go
options := baseOptions.With(integration.ProgramTestOptions{
PostPrepareProject: func(p *engine.Projinfo) error {
// ...
},
})
```
A follow-up to: https://github.com/pulumi/pulumi/pull/12302

[ProgramTest] Fix for PostPrepareProject option

---

changelog/pending/20231116--cli--add-import-file-to-pulumi-preview-to-generate-a-placeholder-import-file-for-every-resource-that-needs-to-create.yaml
pkg/backend/backend.go
pkg/backend/filestate/backend.go
pkg/backend/filestate/stack.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/stack.go
pkg/backend/mock.go
pkg/backend/stack.go
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/preview_test.go
tests/smoke_test.go
tests/testdata/import_node/.gitignore
tests/testdata/import_node/Pulumi.yaml
tests/testdata/import_node/index.ts
tests/testdata/import_node/package.json
tests/testdata/import_node/tsconfig.json

Fixes https://github.com/pulumi/pulumi/issues/12768.
This will generate an import file for every resource the preview wants to Create.

Add --import-file to pulumi preview

---

changelog/pending/20231204--engine--fix-handling-of-delete-failures-for-targeted-destroys.yaml
pkg/engine/lifecycletest/target_test.go
pkg/resource/deploy/deployment_executor.go
pkg/resource/deploy/deployment_executor_test.go

When doing a targeted destroy, if a delete operation for a resource fails, the resource was still being removed from the state. Instead, if the delete operation for a resource fails, it should remain in the state.
Fixes #8164
Fixes #14416

Fix handling of delete failures for targeted destroys

---

tests/stack_test.go

Hopefully this avoids the following check failures in CI (like [this](https://github.com/pulumi/pulumi/pull/14752/files#annotation_16170946342)):
```
SA5011: possible nil pointer dereference (staticcheck)
```
Oddly, I don't see these when running the linter locally.

chore: Fix staticcheck failures

---

.github/workflows/ci-run-test.yml

Part of #14765 
Python ProgramTests would flake during preparation, but pass on re-run. Python ProgramTests would use the hash of the `requirements.txt` to determine the directory to use as its virtualenv. When multiple Python ProgramTests `pip install` the same virtualenv, it would cause test failures which would pass on re-run since there would no longer be contention.
These failures typically are re-run in [CI / Integration Test / tests/integration 8/8 on ubuntu-latest/current](https://github.com/pulumi/pulumi/actions/runs/7118443964/job/19381751006?pr=14767#logs)

[ci] Python ProgramTests no longer re-use the same virtualenv.

---

sdk/nodejs/cmd/pulumi-language-nodejs/language_test.go

This test was skipped because of an issue with `@pulumi/pulumi` v3.96.0. The issue has now been addressed with the release of v3.96.1, so we can unskip the test.

Unskip test

---

sdk/go/auto/errors_test.go
sdk/go/auto/git_test.go
sdk/go/auto/local_workspace_test.go
sdk/go/common/resource/asset_test.go
sdk/go/common/resource/config/key_test.go
sdk/go/common/resource/config/map_test.go
sdk/go/common/resource/plugin/provider_plugin_test.go
sdk/go/common/resource/plugin/rpc_test.go
sdk/go/common/resource/resource_id_test.go
sdk/go/common/util/cmdutil/exit_test.go
sdk/go/common/util/gitutil/git_test.go
sdk/go/common/util/goversion/version_test.go
sdk/go/common/util/mapper/mapper_test.go
sdk/go/common/workspace/paths_test.go
sdk/go/common/workspace/plugins_install_test.go
sdk/go/common/workspace/plugins_test.go
sdk/go/common/workspace/project_test.go
sdk/go/common/workspace/templates_test.go
sdk/go/common/workspace/templates_zip_test.go
sdk/go/internal/types_test.go
sdk/go/pulumi-language-go/main_test.go
sdk/go/pulumi/config/config_test.go
sdk/go/pulumi/internals/outputs_test.go
sdk/go/pulumi/rpc_test.go
sdk/go/pulumi/stack_reference_test.go
sdk/go/pulumi/types_test.go
sdk/go/pulumix/types_ext_test.go
sdk/python/cmd/pulumi-language-python/main_test.go

This is a pass over all of /sdk to replace asserts that just checked we had an error with asserts for what the error value is.
Just checking for an error is a weak test that can result in error paths being broken and tests not detecting it.

Use EqualError/ErrorContains instead of Error

---

tests/smoke_test.go

Pointed out in another PR https://github.com/pulumi/pulumi/pull/14548#discussion_r1411431491.  
No need to check if a plugin is already installed with `plugin ls`, `install` will return success if the plugin is already present.

Just call plugin install directly in tests

---

changelog/pending/20231028--cli--the-cli-now-uses-the-yaml-converter-plugin-rather-than-yaml-convert-logic-linked-in.yaml
pkg/cmd/pulumi/convert.go
pkg/util/plugin.go
pkg/workspace/plugin.go
tests/smoke_test.go

We add some hooks to ensure we always use the version of pulumi-converter-yaml that matches the version of yaml we've linked the CLI to, this preserves the behaviour we have today that eject code matches the gen code.
At some point it will make sense to decouple these and often just default to the the latest converter instead.
This unlinks one part of the yaml codebase from the cli. We still need to do codegen and docgen, but this at least means breaking changes can be made to the eject interface without breaking the build because of the circular dependency cycle.

Use the yaml converter plugin rather than Eject

---

changelog/pending/20231204--engine--dont-validate-urns-this-was-causing-issues-with-unexpected-data-from-filestate-backends.yaml
sdk/go/common/resource/urn.go
sdk/go/common/resource/urn_test.go

Fix an issue with users with spaces in project names. They aren't technically `token.Name`s so this method was failing them, but they've happened to work up till now.

Don't validate URNs

---

.github/workflows/ci-run-test.yml

Bumps @actions/setup-go to v5.
.github/workflows/ci-run-test.yml uses @actions/setup-go@v3 which uses @actions/cache@v3.
This version suffers from a bug where it will hang forever when downloading a segment and will timeout the job.
According to https://github.com/actions/cache/blob/6a1a45d/tips-and-workarounds.md#cache-segment-restore-timeout v3.0.8 adds SEGMENT_DOWNLOAD_TIMEOUT_MINS with a default of 10 minutes which should alleviate our CI hangs.
Only applying this to `ci-run-test.yml` to limit the scope of the change.

[ci] Fix Run @actions/setup-go flake

---

pkg/cmd/pulumi/new_acceptance_test.go
pkg/cmd/pulumi/new_test.go
pkg/cmd/pulumi/stack_change_secrets_provider_test.go
pkg/cmd/pulumi/stack_ls_test.go

Fixes #14756
Flaky tests cause coverage to be rerun and drops coverage data making CodeCov data less reliable/usable.
One of the most commonly flaky tests is `TestCreatingProjectWithEmptyConfig`  in `pkg` which contains a large number of tests.
Moving this test to the top of the file appears to lead to less flakiness.

[test] fix `TestCreatingProjectWithEmptyConfig` flakiness

---

pkg/engine/lifecycletest/source_query_test.go
pkg/engine/lifecycletest/step_generator_test.go
pkg/engine/lifecycletest/test_plan.go

Moves coverage from 72% to 76% for `pkg/resource/deploy`.
Has temporary CI and test skip changes to enable more reliable coverage numbers.

[test] increase code coverage of `pkg/resource/deploy`

---

.github/workflows/ci-build-binaries.yml

See https://goreleaser.com/deprecations/#-rm-dist
Just a very minor thing I noticed while working on https://github.com/pulumi/pulumi/issues/14622, probably best to switch to non-deprecated options eventually.

replace deprecated option with non-deprecated one

---

changelog/pending/20230925--sdk-go--adds-stackchangesecretsprovider-to-go-automation-api.yaml
changelog/pending/20231121--auto-go--add-changesecretsprovider-to-workspace-and-stack-apis.yaml
sdk/go/auto/cmd.go
sdk/go/auto/local_workspace.go
sdk/go/auto/local_workspace_test.go
sdk/go/auto/stack.go
sdk/go/auto/workspace.go

Fixes https://github.com/pulumi/pulumi/issues/14035.

Adds StackChangeSecretsProvider to Go automation api

---

pkg/backend/httpstate/backend.go

Fixes https://github.com/pulumi/pulumi/issues/14757.
Fixes the help message when login fails to say:
Run pulumi login --help for alternative login options.
Rather than:
Run pulumi --help for alternative login options.

Fix login help

---

changelog/pending/20231211--sdk-nodejs--fix-a-bug-in-nodejs-providers-returning-empty-inputs-on-read.yaml
sdk/nodejs/provider/server.ts

Fixes https://github.com/pulumi/pulumi/issues/14819.
NodeJS providers started returning empty inputs rather than unknown inputs from Read.

Don't set inputs to empty if inputs was undefined

---

pkg/codegen/go/gen_test.go

One of a bunch of small PRs for go codegen to exercise pieces of code that have no coverage

[go] Unit test for LanguageResources(...)

---

sdk/nodejs/package.json
sdk/nodejs/tests/automation/util.ts
sdk/nodejs/yarn.lock

Currently we're using a random number for getting the test suffix. However given the birthday paradox and the number of tests we're running this doesn't seem to be good enough to keep our tests from being flaky.  Use a uuid instead, which is virtually guaranteed to be unique, and should eliminate this problem.
Fixes #8220 (hopefully)

use uuid instead of random number for test suffix

---

.github/workflows/ci-prepare-release.yml
.github/workflows/ci.yml
.github/workflows/on-merge.yml

Fixes #14817 
As a follow-up to #14804, we need to re-enable code coverage without releases being built with coverage. #14804 includes a test in the release job to catch `pulumi` being released with coverage data.
Also fixes the test to check that the pulumi binary is not built with coverage.
Background:
Coverage was disabled on merge jobs in order to fix [pulumi/pulumi#14799].
[pulumi/pulumi#14716] removed nightly coverage workflows in favor of collecting coverage on merges [pulumi/pulumi#14727].
The binaries built with coverage were used in the downstream prepare-release job causing a noticable bug [pulumi/pulumi#14799].

[ci] Re-enable code coverage and rebuild release binaries without coverage

---

changelog/pending/20231204--sdkgen-go--fix-generated-usage-documentation-for-enum-input-types.yaml
pkg/codegen/go/gen.go
pkg/codegen/testing/test/testdata/array-of-enum-map/go/example/pulumiEnums.go
pkg/codegen/testing/test/testdata/dashed-import-schema/go/plant-provider/pulumiEnums.go
pkg/codegen/testing/test/testdata/dashed-import-schema/go/plant-provider/tree/v1/pulumiEnums.go
pkg/codegen/testing/test/testdata/different-enum/go/plant/pulumiEnums.go
pkg/codegen/testing/test/testdata/different-enum/go/plant/tree/v1/pulumiEnums.go
pkg/codegen/testing/test/testdata/external-enum/go/example/local/pulumiEnums.go
pkg/codegen/testing/test/testdata/naming-collisions/go/example/pulumiEnums.go
pkg/codegen/testing/test/testdata/output-funcs-edgeorder/go/myedgeorder/pulumiEnums.go
pkg/codegen/testing/test/testdata/plain-and-default/go/foo/pulumiEnums.go
pkg/codegen/testing/test/testdata/provider-config-schema/go/configstation/pulumiEnums.go
pkg/codegen/testing/test/testdata/regress-node-8110/go/my8110/pulumiEnums.go
pkg/codegen/testing/test/testdata/simple-enum-schema/go/plant/pulumiEnums.go
pkg/codegen/testing/test/testdata/simple-enum-schema/go/plant/tree/v1/pulumiEnums.go
pkg/codegen/testing/test/testdata/simple-yaml-schema/go/example/pulumiEnums.go

[sdk-gen/go] Fix generated usage documentation for enum input types

---

sdk/go/common/resource/plugin/plugin.go

This incorrectly added `err` as a parameter:
```
-                       return nil, errors.Errorf("%v plugin [%v] did not begin responding to RPC connections", prefix, bin)
+                       return nil, fmt.Errorf("%v plugin [%v] did not begin responding to RPC connections: %w", prefix, bin, err)
```

Fix fmt.Errorf from 16d9f4c1670404c2cb2f15d2dd095f05dc8eec12

---

sdk/nodejs/Makefile

These tests are pretty close to hitting the timeout during regular runs (e.g. one successful run I picked randomly took ~194000ms).  The GitHub action runners don't have super reliable performance, so we can easily get pushed over this limit.
To make matters worse here, if we hit this timeout just at the right time, the test doesn't exit cleanly (potentially related to https://github.com/pulumi/pulumi-dotnet/issues/134), as I've seen a `pulumi preview` process stick around in that case, preventing the tests from shutting down).  This means we have to wait until the CI job times out after an hour until the failure is reported.
I'm not sure if we only got close to this timeout recently, or if this is a longer standing issue, but it reproduces well for me locally. Ideally of course the tests …

increase the timeout for automation API tests

---

sdk/nodejs/tests/runtime/langhost/run.spec.ts

This test is racy, as the langhost can sometimes take a little bit too long to be ready to accept connections successfully.  Just retry a few times in this case, to make sure it's ready to have the test run against it.
I haven't been able to reliable reproduce the flakyness locally, so there's no guarantee that this will actually do what it says successfully.  I think it's still worth a try and we can monitor CI to verify if this fixed the issue, and revert this PR if the same issue appears again.
Fixes https://github.com/pulumi/pulumi/issues/14841

langhost test: retry if the langhost is unavailable

---

changelog/pending/20231212--programgen-nodejs-python--fix-duplicated-import-statements-when-instantiating-a-component-multiple-times.yaml
pkg/codegen/nodejs/gen_program.go
pkg/codegen/python/gen_program.go
pkg/codegen/testing/test/testdata/components-pp/components.pp
pkg/codegen/testing/test/testdata/components-pp/dotnet/components.cs
pkg/codegen/testing/test/testdata/components-pp/go/components.go
pkg/codegen/testing/test/testdata/components-pp/nodejs/components.ts
pkg/codegen/testing/test/testdata/components-pp/python/components.py

This PR extends the `components` test program in PCL so that it instantiates a component with `options { range = <expr> }` to test that it is generating the right thing and increase code coverage in program-gen which has a special handling for the `range` option. Found a small bug where we duplicate imports for components if they are instantiated multiple times in the program and fixed it as well

[program-gen] Fix duplicated import statements when instantiating a component multiple times

---

changelog/pending/20231214--programgen-dotnet-go-nodejs-python--fix-generated-utility-functions-for-filebase64-filebase64sha256-sha1-and-mimetype.yaml
pkg/codegen/dotnet/utilities.go
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/go/gen_program_utils.go
pkg/codegen/nodejs/gen_program_expressions.go
pkg/codegen/nodejs/gen_program_utils.go
pkg/codegen/python/gen_program_expressions.go
pkg/codegen/testing/test/testdata/functions-pp/dotnet/functions.cs
pkg/codegen/testing/test/testdata/functions-pp/functions.pp
pkg/codegen/testing/test/testdata/functions-pp/go/functions.go
pkg/codegen/testing/test/testdata/functions-pp/nodejs/functions.ts
pkg/codegen/testing/test/testdata/functions-pp/python/functions.py
pkg/codegen/testing/test/testdata/throw-not-implemented-pp/dotnet/throw-not-implemented.cs

While writing program tests for generated helper utility functions `filebase64`, `filebase64sha256`, `sha1` and `mimeType` with the idea to increase code coverage, it turned out that those are completely broken in all of the languages containing syntax errors, missing imports and wrong indentation. This PR fixes them and extends the `functions` program to show how they now look like and to show that they compile. Also adding example usage of `stack()`, `project()` and `cwd()` in the test program.

[program-gen] Fix generated utility functions for filebase64, filebase64sha256, sha1 and mimeType

---

.github/workflows/on-merge.yml

If CI succeeds for the merge, we'll want to update the latest dev
version, as we know this is going to be merged, and we published the
binaries to AWS.  Dispatch the correct event to update that file in
the pulumi/docs repository.
/xref https://github.com/pulumi/pulumi/issues/14623

on-merge: add steps to update the latest dev version 

---

.github/workflows/on-merge.yml

The reason for this is twofold:
- Once ci-ok is run, GitHub deletes the merge queue branch, and thus the checkout in the update-dev-version step fails.
- If we do the update-dev-version after ci-ok, we might still merge the changes even though we haven't updated the dev version properly. This isn't a big deal, but can be confusing nonetheless.

do update-dev-version before ci-ok

---

changelog/pending/20231122--cli-import--import-can-now-distinguish-between-logical-names-and-source-names.yaml
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/import_test.go
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/preview_test.go
pkg/go.mod
tests/smoke_test.go

Fixes https://github.com/pulumi/pulumi/issues/14618.
This adds a new field to the import file "logicalName", which if set is used as the logical name (https://www.pulumi.com/docs/concepts/resources/names/#logicalname) of the resource. The original "name" field is then used just for codegen purposes (i.e. the source name).
If either field is not set then the other field is used to fill it in. If neither field is set it's an error.
Further the import system _no longer_ renames resources to try and make unique names, but it also no longer errors just because two resources of different types have the same name. The rules for uniqueness now match what's valid when writing a Pulumi program, but it is the users responsibility to make names unique and the import system will error if you try to …

Add LogicalName to import system

---

.github/workflows/ci-dev-release.yml
.goreleaser.yml

https://github.com/pulumi/pulumi/pull/14640/files#diff-42e26dc67aed8aa3edb2472b4403288c1699fb6dc47419b9a475f0f224fe4689 inadvertently got rid of the v prefix in the version in pulumi about. Add it back.  Also make sure we don't get a duplicate `v` prefix in the dev releases.
Fixes #14800

add the v prefix in the version in pulumi about back

---

build/common.mk

~sourcegraph.com/sourcegraph/appdash-data disappeared from proxy.golang.org.  As a very temporary workaround we can use goproxy.io, which still has it in its cache.  However we should still try to get rid of the dependency as a high priority.~
While trying to fix the sourcegraph.com/sourcegraph/appdash-data dependency disappearing issue, one idea that came to mind was trying to use a different goproxy.  We already have a `GOPROXY` variable set in our Makefiles, so just changing that should have worked.  However that variable had two problems:
- It was quoted in single quotes, which because this is a Makefile and not shell were added to the environment, confusing Go.
- The variable was not exported, so it would never actually be used. 
Fix these two problems, in case we need to use this in …

fix goproxy environment variable in makefile

---

changelog/pending/20231219--auto-nodejs--dont-mutate-original-stack-settings-when-saving.yaml
sdk/nodejs/automation/localWorkspace.ts
sdk/nodejs/tests/automation/localWorkspace.spec.ts

When writing out the stack settings, some keys get renamed (`secretsProvider` -> `secretsprovider`). We were mutating the stack settings object in place instead of working on a copy.
Fixes https://github.com/pulumi/pulumi/issues/14003

[auto/nodejs] don't mutate original stack settings when saving

---

sdk/nodejs/log/index.ts
sdk/nodejs/provider/server.ts
sdk/nodejs/runtime/mocks.ts
sdk/nodejs/runtime/resource.ts
sdk/nodejs/runtime/rpc.ts
sdk/nodejs/runtime/settings.ts
sdk/nodejs/runtime/state.ts
sdk/nodejs/tests/runtime/props.spec.ts

We need to synchronously check for transform support in `registerStackTransformation` and resource constructors when adding remote transform support to node (c.f. https://github.com/pulumi/pulumi/pull/14303). This change changes all the feature checks to be done at startup and then accessed via just a field lookup. Adding the "transform" feature to this set is clearly simple.
Sadly there's no single entry point to make these changes in. So we need to update entry point of construct/call, the entry point of programs, and test setup. Miss any one of these and current tests start failing.

Move nodejs feature checks to startup

---

.github/workflows/on-merge.yml

The latest-dev-version file is not supposed to include a 'v' prefix. However the `git describe` output includes it.  Strip that from the string before dispatching the CI job that updates the latest-dev-version file.

strip the v prefix from the latest-dev-version file

---

changelog/pending/20231213--cli-config--fixes-config-copy-command-to-also-copy-environments-from-the-source-stack.yaml
pkg/cmd/pulumi/config.go
pkg/cmd/pulumi/config_test.go
pkg/cmd/pulumi/stack_init.go
pkg/secrets/mock.go

This PR updates the copy config command to also copy the environments from the source stack to the destination stack. The list of environments in the destination stack's config will be overwritten.
Fixes #14564

Ensure that pulumi config cp also copies the environments from the source stack

---

changelog/pending/20231214--cli-config--adds-pulumi-config-env-ls-command.yaml
pkg/cmd/pulumi/config_env.go
pkg/cmd/pulumi/config_env_ls.go
pkg/cmd/pulumi/config_env_ls_test.go
sdk/go/common/workspace/project.go

Adds a `pulumi config env ls` command to list the environments imported into the stack configuration.
Fixes #14774

Add pulumi config env ls command

---

changelog/pending/20231220--cli-config--fix-pulumi-config-env-ls-json.yaml
pkg/cmd/pulumi/config_env.go
pkg/cmd/pulumi/config_env_ls.go
pkg/cmd/pulumi/config_env_ls_test.go

The `--json` flag for `pulumi config env ls` was not being correctly passed through, this fixes the issue. Also changed the default output of no envs from `null` to `[]` so automation api doesn't need to handle the null case in all languages.

Fix a bug in pulumi config env ls json output

---

changelog/pending/20231216--programgen--avoid-pretty-printing-large-object-graphs-when-a-resource-property-doesnt-type-check-when-binding-pcl-programs.yaml
pkg/codegen/hcl2/model/print_test.go
pkg/codegen/pcl/binder_resource.go

When we bind PCL program and a resource property doesn't type-check, we pretty print the type of the resource property in its _entirety_ in the error message and that includes nested objects, nested maps, nested lists, unions etc. instead of using type references: we pretty print the `model.Type` derived from `schema.Type` and this resolves the entire graph. 
This PR changes it such that we print the `schema.Type` in string form in the error message when we encounter a bind error 
in resource properties instead of fully resolving and printing the full `model.Type`. 
Fixes #14317

[program-gen/pcl] Avoid pretty printing large object graphs when encountering bind error in resource properties

---

changelog/pending/20231219--auto-nodejs--always-run-cleanup-for-refresh-and-destroy-commands.yaml
sdk/nodejs/automation/stack.ts

Ensure we always wait for the log promise and run cleanup for `refresh` and `destroy` to ensure log files get removed and any open pipes get closed.
Fixes https://github.com/pulumi/pulumi/issues/14879

[auto/nodejs] always run cleanup for refresh and destroy commands

---

.github/workflows/ci-dev-release.yml

GitHub actions interprets these quotes literally, so the version we end up with includes the quotes, and will therefore end up in the form of `v"1.0.0-11-gdeadbeef" in the output.  Remove the extra quotes as they are not needed.
It's a bit awkward to test this, but I *think* this should do the trick.

ci-dev-release: remove extra quotes

---

changelog/pending/20231219--programgen-go--fix-required-config-variables-of-type-bool-and-number.yaml
pkg/codegen/go/gen.go
pkg/codegen/go/gen_program.go
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/go/gen_test.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/config-variables-pp/config-variables.pp
pkg/codegen/testing/test/testdata/config-variables-pp/dotnet/config-variables.cs
pkg/codegen/testing/test/testdata/config-variables-pp/go/config-variables.go
pkg/codegen/testing/test/testdata/config-variables-pp/nodejs/config-variables.ts
pkg/codegen/testing/test/testdata/config-variables-pp/python/config-variables.py

While covering more parts of go codegen, I've seen that config variables are broken 😓 specifically when requiring config variables using `RequireFloat` it should be `RequireFloat64` and `RequireBoolean` should be `RequireBool`. 
Moreover, it seems that `RequireObject` doesn't work at all since the function signature doesn't match the way it was generated (see #14957) 
C# has a similar issue with optional untyped objects as config variables. For now have skipped compilation for those.

[program-gen/go] Fix required config variables of type bool and number

---

.github/workflows/ci-dev-release.yml

Unfortunately https://github.com/pulumi/pulumi/pull/14964 didn't quite do what we wanted it to, and the version number still contained the extra quotes.  Investigating a bit more, I now believe the "set-output" script is the culprit because it does some extra quoting. Since we don't need any extra escaping here, we can just write to the file containing the outputs directly instead, which will hopefully fix the issue.

avoid quotes in dev version number; take 2

---

changelog/pending/20231220--backend-service--exclude-internal-events-from-pulumi-cloud.yaml
pkg/backend/httpstate/state.go

Following up from https://github.com/pulumi/pulumi/commit/54c956af6d64638983eca50875d1dae704a18240 to also exclude the internal events from being sent to Pulumi Cloud.

Exclude internal events from those sent to the service

---

pkg/resource/deploy/deploytest/analyzer_test.go

Adds `pkg/resource/deploy/deploytest/analyzer_test.go` which adds missing coverage to `pkg/resource/deploy/deploytest/analyzer.go`
Note: disregard CI changes. will revert prior to merge.

[ci] `pkg/resource/deploy/deploytest/analyzer.go` coverage

---

.github/workflows/ci-dev-release.yml

In https://github.com/pulumi/pulumi/pull/14966 we tried to correct the quoting of the dev-version.  However the name written to the $GITHUB_OUTPUT file was wrong there.  Fix that.

correct name of the output

---

changelog/pending/20231221--auto-go-nodejs-python--adds-listenvironments-support.yaml
sdk/go/auto/local_workspace.go
sdk/go/auto/local_workspace_test.go
sdk/go/auto/stack.go
sdk/go/auto/workspace.go
sdk/nodejs/automation/localWorkspace.ts
sdk/nodejs/automation/stack.ts
sdk/nodejs/automation/workspace.ts
sdk/nodejs/tests/automation/localWorkspace.spec.ts
sdk/python/lib/pulumi/automation/_local_workspace.py
sdk/python/lib/pulumi/automation/_stack.py
sdk/python/lib/pulumi/automation/_workspace.py
sdk/python/lib/test/automation/test_local_workspace.py

Automation API support for `pulumi config env ls`
Fixes https://github.com/pulumi/pulumi/issues/14797

Automation API support for listing environments

---

.github/workflows/ci-dev-release.yml

For windows we generate zip files, not tar.gz, so make sure to also upload those.
Also upload the signature files a bit more explicitly.  Because we have two sign processes running (first for building the release artifacts and then the dev artifacts), we get .sig.sig files otherwise, but we don't need these, so be more selective here.

make sure to also upload zip files

---

pkg/cmd/pulumi/new_ai_test.go

Tests with mocked backend instances can't be run in parallel, since the backendInstance is a global.  Make these tests not parallel to avoid the race.
Fixes #14993

fix data race for mocked backendInstance

---

pkg/codegen/go/gen_program_expression_test.go
pkg/codegen/go/gen_program_expressions.go

This PR adds unit test for `argumentTypeName` and a few missing uncovered cases from `GenFunctionExpression` in Go program-gen. I did have to remove a check `Title(x) == "pulumi.Any"` that would never evaluate to `true` but I didn't think this warrants a changelog for the CLI

[go/program-gen] Add unit tests for argumentTypeName and go optional functions

---

changelog/pending/20231219--cli-display--warn-correctly-about-new-versions-being-availablen-when-using-the-cli-dev-channel.yaml
pkg/backend/httpstate/client/client.go
pkg/backend/httpstate/client/client_test.go
pkg/cmd/pulumi/pulumi.go
pkg/cmd/pulumi/pulumi_test.go
sdk/go/common/apitype/cli.go

When we have a dev version from the dev CLI channel installed, we want to warn whenever a new version is available, so the users can upgrade. Do that, and also reduce the amount of time the version information is cached, since we expect dev versions to be released much more frequently than regular releases.
This needs https://github.com/pulumi/pulumi-service/pull/17429 to be merged and deployed first.
Fixes #14641

correct version check when we have a dev version installed

---

pkg/resource/deploy/deploytest/provider.go
pkg/resource/deploy/deploytest/provider_test.go

Adds `pkg/resource/deploy/deploytest/provider_test.go` which adds missing coverage to `pkg/resource/deploy/deploytest/provider.go`
Note: disregard CI changes. will revert prior to merge. (Left solely to illustrate coverage changes).

[ci] `pkg/resource/deploy/deploytest/provider.go` coverage

---

pkg/resource/deploy/target_test.go

Adds `pkg/resource/deploy/target_test.go` which adds missing coverage to `pkg/resource/deploy/target.go`
Note: disregard CI changes. will revert prior to merge.

[ci] `pkg/resource/deploy/target.go` coverage

---

pkg/resource/deploy/source_error_test.go

Adds `pkg/resource/deploy/source_error_test.go` which adds missing coverage to `pkg/resource/deploy/source_error.go`
Note: disregard CI changes. will revert prior to merge.

[ci] `pkg/resource/deploy/source_error.go` coverage

---

pkg/resource/deploy/source_eval_test.go

Adds to `pkg/resource/deploy/source_eval_test.go` which adds missing coverage to `pkg/resource/deploy/source_eval.go`

[ci] `pkg/resource/deploy/source_eval.go` coverage

---

pkg/resource/deploy/import_test.go
pkg/resource/deploy/step.go
pkg/resource/deploy/step_executor_test.go
pkg/resource/deploy/step_generator_test.go
pkg/resource/deploy/step_test.go

covers
- step.go
- step_executor.go
- step_generator.go
- import.go
They all depend on an added field to steps that use providers in `Apply()`
steps query the deployment for providers. There is not a straightforward way of mocking a provider for a step. I've added a field called `provider plugin.Provider` to steps that use providers to be used instead of querying the Deployment with getProvider(). 
This approach aims to minimize the cognitive complexity and potential for errors in comparison to the branching alternative due to the behavior of `:=` and assigning the value to an existing value while also defining a new variable err.
```diff
-               prov, err := getProvider(s, s.provider)
-               if err != nil {
-                       return resource.StatusOK, nil, err
+ …
```

[ci] `pkg/resource/deploy/(step(_generator|_executor)?|import).go` coverage

---

changelog/pending/20231223--programgen-dotnet-python--allow-object-keys-to-be-template-expressions-such-as-static-quoted-strings.yaml
pkg/codegen/dotnet/gen_program_expressions.go
pkg/codegen/python/gen_program_expressions.go
pkg/codegen/testing/test/testdata/kubernetes-pod-pp/dotnet/kubernetes-pod.cs
pkg/codegen/testing/test/testdata/kubernetes-pod-pp/go/kubernetes-pod.go
pkg/codegen/testing/test/testdata/kubernetes-pod-pp/kubernetes-pod.pp
pkg/codegen/testing/test/testdata/kubernetes-pod-pp/nodejs/kubernetes-pod.ts
pkg/codegen/testing/test/testdata/kubernetes-pod-pp/python/kubernetes-pod.py

I've noticed while working with PCL generated from Kubernetes manifests that when an object property key is quoted for example `{ "key" = value }` instead of `{ key = value }` then program-gen for csharp and python _panic_ because they assume the object keys to be strictly a literal value expression and this type assertion fails:
```go
lit := item.Key.(*model.LiteralValueExpression)
```
This PR fixes this panic and allows program-gen to handle cases where the object keys are `TemplateExpression` assuming that it has one part which is a literal value expression (handling cases like `{ "key" = value }`)

[program-gen/csharp,python] Allow object keys to be template expressions

---

changelog/pending/20231225--programgen--fixes-type-annotating-nested-resource-properties-when-these-have-quoted-keys.yaml
pkg/codegen/pcl/binder_resource.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/kubernetes-template-quoted-pp/dotnet/kubernetes-template-quoted.cs
pkg/codegen/testing/test/testdata/kubernetes-template-quoted-pp/go/kubernetes-template-quoted.go
pkg/codegen/testing/test/testdata/kubernetes-template-quoted-pp/kubernetes-template-quoted.pp
pkg/codegen/testing/test/testdata/kubernetes-template-quoted-pp/nodejs/kubernetes-template-quoted.ts
pkg/codegen/testing/test/testdata/kubernetes-template-quoted-pp/python/kubernetes-template-quoted.py

When binding resource properties and annotating these with types from their schemas, we seem to skip this annotation process when resource properties and their nested objects use _quoted_ keys `{ "key" = <value> }` rather than using _literal_ keys `{ key = <value> }`. 
This results in issues such as https://github.com/pulumi/kube2pulumi/issues/60 where a csharp property name override was not correctly applied because 
1) kube2pulumi generated properties for resources that are quoted (this should be fine)
2) binding the resource properties skipped annotating the nested object with its corresponding schema type
3) program-gen in dotnet didn't have access to the schema type of the nested object to correctly apply the property override
This PR fixes this issue by extending PCL resource …

[program-gen/pcl] Fixes type-annotating nested resource properties when these have quoted keys

---

pkg/backend/display/tree_test.go

Fixes #15004
The `dirty` member of the interactive renderer is used in a separate goroutines and requires use of a lock to be set correctly.

Fix data rate in backend/display/tree_test.go

---

changelog/pending/20231219--sdk-go--fixes-fulfillvalue-error-when-joining-a-nil-output-state.yaml
sdk/go/internal/types.go

fixes fulfillValue error when joining a nil output state
Error can be reproduced using https://github.com/mheers/pulumi-azure-app-reg-helm-go-error

fixes fulfillValue error when joining a nil output state

---

changelog/pending/20240102--engine--default-parallel-operations-to-a-reasonable-limit.yaml
pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/refresh.go
pkg/cmd/pulumi/up.go
pkg/cmd/pulumi/watch.go

Fixes https://github.com/pulumi/pulumi/issues/14989.

Set a default limit for --parallel

---

sdk/go/common/diag/colors/diag.go
sdk/go/common/util/cmdutil/diag.go

This value was never actually used or correctly implemented, it was just being used as a sentinal value for `Set/GetGlobalColorization`. We can just use a pointer instead.

Remove Colorization.Auto

---

pkg/engine/journal.go
pkg/engine/lifecycletest/pulumi_test.go
pkg/engine/lifecycletest/test_plan.go

We were ignoring any error from closing the journal snapshot manager in test_plan. This is a small change to track that if it does fail.

Validate journal close in test_plan

---

changelog/pending/20240103--cli-new--fixes-repeated-ai-prompt-on-windows.yaml
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/new_ai.go
pkg/cmd/pulumi/new_ai_test.go

Switches the prompt to use the `promptForValue` function, which now accepts an empty type descriptor. This renders to the user as:
```console
$ pulumi new
Would you like to create a project from a template or using a Pulumi AI prompt? ai
Please select a language for your project: TypeScript
What cloud infrastructure would you like to build?
(try something like "a static website on AWS behind a CDN")
> an eks cluster
Sending prompt to Pulumi AI...
Pulumi AI response:
\`\`\`typescript
...
\`\`\`
View this conversation at:  https://www.pulumi.com/ai/conversations/13a802da-50b6-46e8-bc82-fd2f7ac6e364
Use this program as a template? refine
Tell Pulumi AI how to refine the previous program:
> add an awsx vpc
...
```
We're still a little inconsistent between the survey asked questions and those …

Fix AI prompt repetition on Windows

---

.github/workflows/release.yml
sdk/python/Makefile

Username/Password authentication is no longer supported. This PR migrates to using API Tokens per https://pypi.org/help/#apitoken. We use `__token__` for the username and the org-wide `PYPI_API_TOKEN` secret for the password.
Part of https://github.com/pulumi/pulumi/issues/15043
Reference:
- https://github.com/pulumi/ci-mgmt/issues/751
- https://github.com/pulumi/ci-mgmt/pull/767

Switch to API Token for PyPi uploads

---

changelog/pending/20240104--cli-state--fix-a-panic-in-pulumi-state-when-no-snapshots-are-available.yaml
pkg/cmd/pulumi/state.go
pkg/cmd/pulumi/state_delete.go
pkg/cmd/pulumi/state_rename.go
pkg/cmd/pulumi/state_unprotect.go

Currently when there are no snapshots, and a user calls `pulumi state delete` without specifying a URN, and no snapshot available, it panics.  Fix this panic, and give the user better error message in this case.
Fixes #15033

state delete: fix panic when there are no snapshots

---

.github/workflows/ci-run-test.yml

The windows tests keep failing, without a good indication of what is actually failing, and no logs in the "run tests".  Maybe adding the test command we're actually running will give us some additional information to help track the issue down.
Not sure if this will actually help with anything, but I also don't think it can hurt.
/xref https://github.com/pulumi/pulumi/issues/14992

show test command in test name

---

.github/workflows/release.yml

Turns out, we can't easily change the credentials of the Python publish step because it will run the publish command as defined in `v3.100.0` which is using the old username/password, rather than from `master` which has been updated to use the API token.
Instead, the wheel artifact from https://github.com/pulumi/pulumi/releases/tag/v3.100.0 has been manually published.
This change temporarily updates the release workflow to no longer do any SDK publishing steps, as these are now all complete. Once this has merged, I'll dispatch the release, which will run all subsequent release steps.
Then we can revert the temporary workflow changes.
Part of #15043

Temporary change to unblock v3.100.0 release

---

scripts/get-job-matrix.py

We're seeing a significant increase in costs with our use of large Windows runners. Temporarily disable Windows runners while we root cause.

Temporarily disable large Windows runners

---

cmd/pulumi-test-language/interface.go
pkg/backend/filestate/backend_test.go
pkg/backend/httpstate/backend_test.go
pkg/operations/resources_test.go
pkg/resource/stack/deployment_test.go
pkg/secrets/b64/provider.go

To support plugin based secret providers like (e.g. AGE https://github.com/pulumi/pulumi/issues/11493) the default secrets provider will need to become more complicated, requiring access to a plugin host at least.
As such for tests it will be simpler to have a basic secrets provider that only supports base64 and can be created without any setup.

Add Base64SecretsProvider for testing

---

CONTRIBUTING.md
Makefile

Add a make target to setup a go workspace. This is needed to make `gopls`, the go language server, work seamlessly when opening the root of the repo.

Add work target to initialize a go workspace

---

pkg/cmd/pulumi/util_remote.go

Noticed a typo in the --remote-git-branch flag's usage text.

fix typo in --remote-git-branch usage string

---

pkg/engine/lifecycletest/test_plan.go
pkg/resource/deploy/snapshot.go

This updates test_plan.go to verify that every partial snapshot is also a valid snapshot. This tests that the journal always writes out _valid_ snapshots even for scenarios where an update only partially ran.
While doing this it flagged up that the validation code was wrong for delete-before-create resources.
When we do a delete-before-create replacement we need to leave the "being replaced" resource in the snapshot. This is because while that resource is being replaced it might have dependents that are not being replaced, and so there is a period of time where _it_ is deleted but dependents are still referring to it. If we removed it from the snapshot at this point those dependent resources would not validate.
But in the case of two resources both being delete-before-create replaced you …

Verify partial journals in engine tests

---

changelog/pending/20231214--cli--adds-a-flag-to-insert-fragment-in-graph.yaml
pkg/cmd/pulumi/stack_graph.go
pkg/cmd/pulumi/stack_graph_test.go
pkg/graph/dotconv/print.go
pkg/graph/graph.go

This enables you to insert arbitrary dot inside the `digraph` element. This can be used to style the dot file. For example:
with the file `fragment.dot` having the contents:
```
rankdir=LR
ranksep=0.01
dpi=300
node [shape=rect style=filled fillcolor="#8a3391" fontcolor="white" fontname="Arial"]
edge [fontname="Arial" fontcolor="#83a3391" penwidth=2]
```
You could then call
`pulumu stack graph --dot-fragment "$(<fragment.dot)" stack.dot`
Which could be in a command pipeline like
`pulumu stack graph --dot-fragment "$(<fragment.dot)" stack.dot && dot -Tpng -O stack.dot && open stack.dot.png`
To generate and display a styled view of the graph without needing to hand edit the dot file in the process.

Adds a flag to graph command to insert fragment

---

sdk/python/lib/pulumi/runtime/rpc.py

[CI] Ignore python mypy typecheck on google.protobuf.pyext to re-enable CI builds

---

changelog/pending/20240109--engine--fix-an-uncommon-datarace-with-replace-steps.yaml
pkg/resource/deploy/step_executor.go

This fixes a data race between the snapshot system and the step executor for create before delete replacements.
When doing a create-before-delete replacement the step generator would issue two steps to the step executor. The first step being Create which would create the new resource instance and add that state to the snapshot system to be saved. The second being a replace step, which didn't interact with the snapshot system but is a step that executes. There's a bit of code in the executor that ran for every step to mutate the outputs to ensure secrets propagated correctly. This could run in parallel with the snapshot system trying to iterator over the outputs to serialise them out and causes a "concurrent map iteration and map write" error.
It is obviously very hard to write a test to …

Don't update new state outputs for replace steps

---

scripts/go-wrapper.sh

The intention if this environment variable is set, is that we want to run in coverage mode.  However in
6af5f0b39dbf8291c8a6461659bffa7f96f22647 that accidentally got lost. Fix it.
I noticed this while looking at https://github.com/pulumi/pulumi/pull/15120 and got confused what the script is trying to do.

go-wrapper: fix script if PULUMI_TEST_COVERAGE_PATH is set

---

changelog/pending/20240110--cli-import--import-file-now-omits-empty-resource-lists.yaml
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/import_test.go

`--import-file` now omits empty resource lists.

---

pkg/cmd/pulumi/about.go
pkg/cmd/pulumi/install.go
pkg/cmd/pulumi/plugin.go
pkg/engine/plugins.go
pkg/engine/update.go
proto/.checksum.txt
proto/pulumi/language.proto
sdk/go/common/resource/plugin/host.go
sdk/go/common/resource/plugin/langruntime.go
sdk/go/common/resource/plugin/langruntime_plugin.go
sdk/go/pulumi-language-go/main_test.go
sdk/proto/go/language.pb.go
sdk/python/lib/pulumi/runtime/proto/language_pb2.pyi

The project field on `GetProgramDependenciesRequest` and `GetRequiredPluginsRequest` was marked deprecated at the start of December. None of the language runtimes are using this, so this cleans up the engine side code so we don't need to thread a `*workspace.Project` down to the plugin layer to fill in these fields anymore.
I haven't fully removed them from the Protobuf structs yet, we probably could but just to give a little more time for people to get a clear usage error if still using it.

Clean up project usage

---

changelog/pending/20240117--cli--fix-a-panic-when-users-home-directory-could-not-be-looked-up.yaml
sdk/go/common/workspace/paths.go

Fixes https://github.com/pulumi/pulumi/issues/15159.
`user.Current()` can potentially return nil in cases where the user lookup fails, further there's a chance that `HomeDir` might be empty even if a user is found. This makes both of these cases an error, preventing a panic in the former and preventing trying to use "/.pulumi/" in the later.

Fix panic when looking up home

---

.golangci.yml
pkg/resource/provider/host.go
sdk/go/common/resource/plugin/check.go
sdk/go/common/resource/plugin/host_server.go

Follow on from https://github.com/pulumi/pulumi/pull/15164 after team discussion that importas was more value.
Opted to not make importas too strict to start. It still allows individual go files to import modules with ad-hoc names, but at least makes sure the "pulumirpc" module is always named the same.

Enable importas linter

---

changelog/pending/20240105--sdkgen--emit-a-warning-when-using-id-or-urn-as-resource-outputs.yaml
pkg/codegen/schema/bind.go
pkg/codegen/schema/schema_test.go

Emits a warning when binding properties of resources if we encounter a property with name `urn` or when we encounter a property with name `id` (only for resources which are not components / MLCs). This is a follow up PR for #15025

[schema] Emit a warning when using id or urn as resource properties

---

changelog/pending/20240117--sdk-python--allow-remote-components-to-use-output-property-called-id.yaml
sdk/python/lib/pulumi/resource.py
sdk/python/lib/pulumi/runtime/resource.py
sdk/python/lib/pulumi/runtime/rpc.py
tests/go.mod
tests/integration/construct_component_id_output/python/.gitignore
tests/integration/construct_component_id_output/python/Pulumi.yaml
tests/integration/construct_component_id_output/python/__main__.py
tests/integration/construct_component_id_output/python/component.py
tests/integration/construct_component_id_output/testcomponent-go/.gitignore
tests/integration/construct_component_id_output/testcomponent-go/PulumiPlugin.yaml
tests/integration/construct_component_id_output/testcomponent-go/main.go
tests/integration/integration_python_test.go

This PR updates the python SDK to allow remote components to have ID property. Adds an integration test which implements a component that had an output property `id` to ensure that we can have `id` as an output that doesn't get filtered out when serializing and deserializing property maps. 
Component instantiation looks like this in python
```python
import pulumi
from component import Component
component_a = Component("a", id="hello")
pulumi.export("id", component_a.id)
```
Where we expect `component_a.id` to equal `"{resource.ID}-{args.Id}" => "42-hello"` and the 42 is the (constant) ID of the resource created inside the component.

[python/sdk] Allow remote components to use output property called id

---

.github/workflows/pr-test-acceptance-on-dispatch.yml

These secrets are required for the acceptance tests to run correctly, as we're getting false failures otherwise.  This is safe, since we're also using these secrets in other CI jobs, and always review code before running the acceptance tests.
I noticed in https://github.com/pulumi/pulumi/pull/15173 that the tests introduced in https://github.com/pulumi/pulumi/pull/14649 are failing.

set up secrets in acceptance test job

---

.github/workflows/ci.yml

This secret needs to be defined here, so we can pass it through from the job dispatch.  This was missed in https://github.com/pulumi/pulumi/pull/15175.

define necessary secret in ci.yml

---

changelog/pending/20240118--sdk-go--parse-config-paths-strictly.yaml
sdk/go/common/resource/config/map.go
sdk/go/common/resource/config/map_test.go
sdk/go/common/resource/properties_path.go
sdk/go/common/resource/properties_path_test.go

We want to parse config paths more strictly and not allow something like "foo.[0]", but property paths everywhere else in the system need to tolerate those keys.
Because of circular dependency on _pulumi/esc_ I kept a function with old signature and added a new one. (instead of refactoring by adding new parameter and exposing it)
Fixes https://github.com/pulumi/pulumi/issues/14573.

[14573] Parse config paths strictly

---

changelog/pending/20240119--cli-display--improve-output-when-installing-policy-packs.yaml
pkg/backend/httpstate/policypack.go

Our display code sets up the terminal so it doesn't automatically do a CR for every new line (amongst other modifications).  However the policy pack code just uses regular Println's for output, messing up the formatting.
Fix this by manually adding the CR, improving this output.
Example output before:
```
$ pulumi preview
Previewing update (tgummerer-test/dev)
View in Browser (Ctrl+O): https://app.pulumi.com/tgummerer-test/pulumi-test-go/dev/previews/af23b7b8-6dd4-4e4e-b635-47eab4270b19
Installing policy pack aws-iso27001-compliance-ready-policies-typescript 0.0.1...
Loading policy packs...
Finished installing policy pack
Installing policy pack aws-python 0.0.1...
Finished installing policy pack
[...]
```
and after this change:
```
$ pulumi preview
Previewing update (tgummerer-test/dev) …
```

improve display for policy packs

---

sdk/python/cmd/pulumi-language-python/main_test.go

When creating a PyPi package, Python setuptools prior to v69 would record the name of a package in egg_info by replacing underscores with dashes. So after installing `pulumi-random==4.15.0`, `pip list` would report the package name as `pulumi-random`.
However, setuptools >= 69 now retains the underscore in egg_info (https://github.com/pypa/setuptools/pull/4159). So after installing the latest version of `pulumi-random==4.15.1`, `pip list` now reports the package name as `pulumi_random` instead of `pulumi-random`.
We use pip to list installed packages so we can determine which ones are Pulumi packages for `GetRequiredPlugins`.
It turns out that this change is largely benign for us. We don't really care if the reported name is `pulumi-random` or `pulumi_random`, because we will replace …

Update python langhost test for pulumi-random change

---

changelog/pending/20240122--engine--fix-a-bug-where-mapping-lookup-could-sometimes-lead-to-an-infinite-loop.yaml
pkg/codegen/convert/plugin_mapper.go
pkg/codegen/convert/plugin_mapper_test.go

Found by @GeoffMillerAZ a while back. Just tracked down exactly what caused it. The test added hangs if ran on the current version of the code.
Issue was we used to assume that we'd only stop looking for plugins once there weren't any more plugins to look at. But then we added `GetMappings` so we could see which providers a plugin mapped to up-front. So the check needs to actually be stop looking when there's no plugins _or_ when all the plugins left explicitly say they aren't for the current lookup.

Fix infinite loop bug in plugin_mapper

---

changelog/pending/20240122--cli-display--incremental-improvement-on-the-output-when-installing-plugins.yaml
sdk/go/common/workspace/plugins.go

We are using our terminal in raw mode, which means we're not getting CRs automatically added.  Add one after a progress bar has finished to improve the output slightly.
The final output after this looks like: 
```
$ pulumi preview                     
Please choose a stack, or create a new one: dev
Previewing update (dev):
Downloading plugin: 18.39 MiB / 18.39 MiB [========================] 100.00% 15s
[resource plugin docker-3.6.1] installing
Downloading plugin: 20.19 MiB / 20.19 MiB [========================] 100.00% 15s
[resource plugin awsx-1.0.5] installing
Downloading plugin: 164.18 MiB / 164.18 MiB [======================] 100.00% 32s
[resource plugin aws-5.42.0] installing
[...]
```
Which seems slightly better, but not a huge improvement, and the progress bar is unfortunately also …

add a CR before when finishing the progress bar

---

scripts/go-test.py

When `--rerun-fails` is specified and a test is re-run, the produced coverage data only contains the coverage from the failed but re-executed sub-tests. See https://github.com/gotestyourself/gotestsum/issues/274
This change sees how we fare with this disabled as we've recently done some work to address test flakiness. We'll be relying on the much less granular `./scripts/retry` for retries, which doesn't have the coverage problem. The downside is it will re-run all the tests.

Disable `--rerun-fails` in tests

---

changelog/pending/20240123--sdk-go--replace-a-deleted-type-used-by-pulumi-cloud-code.yaml
pkg/backend/filestate/backend.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/client/client.go
sdk/go/common/apitype/history.go

A type that is used by the Pulumi Cloud code was removed in [#15028](https://github.com/pulumi/pulumi/pull/15028/files#diff-52b25675ac0d98614d062fc1d1c9e60759f905cf7c60a9339402a62c23cc2c55L32-L33) - this PR replaces it.

Replace a type used by the service

---

.github/workflows/ci-build-sdks.yml

In preparation for supporting Python 3.12...
As of Python 3.12, `setuptools` is no longer installed by default into a virtual environment created with `python -m venv` (https://github.com/python/cpython/issues/95299). It must be explicitly installed via `python -m pip install setuptools`.

[ci] Install `setuptools` in virtual environment

---

pkg/testing/integration/program.go

In preparation for supporting Python 3.12...
I'm planning to remove `pulumi` from `requirements.txt` in a bunch of the integration tests (at least temporarily) because the current published version of `pulumi` can't be installed on Python 3.12 due to its dependency on `grpcio` which is broken on Python 3.12, and the tests specify a dependency on the locally built Pulumi Python SDK via `ProgramTestOptions.Dependencies`.
However, after removing `pulumi` from `requirements.txt` for `TestPythonStackTruncate/main_dir_specified`, the test started to fail due to a missing `pulumi` package. It shouldn't fail because the test additionally requires the locally built SDK via `ProgramTestOptions.Dependencies`.
The reason for the failure is because this test had a `main` specified in the project to a …

ProgramTest: Python: Use correct venv path for projects with `main` option

---

sdk/python/.pylintrc
sdk/python/requirements.txt

In preparation for supporting Python 3.12...
We need to be running a more recent version of pylint that runs on Python 3.12 (otherwise it errors). This required disabling some new lints that were resulting in new lint errors and fixing how `overgeneral-exceptions` is specified.

Upgrade pylint to 3.0.3

---

sdk/python/cmd/pulumi-language-python/main_test.go

In preparation for supporting Python 3.12...
The test is installing `pulumi-random` which currently depends on `pulumi`, which will fail on Python 3.12 because the currently released version of `pulumi` is pinned to a version of `grpcio` that doesn't work on Python 3.12.
Instead of depending on the public `pulumi` package, install the locally built Python SDK. Then install `pulumi-random`. That way, it'll be using a version of `grpcio` that works with Python 3.12.

[sdk/python] Fix test to install local Pulumi SDK

---

changelog/pending/20240104--cli-new--adds-pulumi-template-tag-to-pulumi-new-created-projects.yaml
pkg/backend/mock.go
pkg/backend/stack.go
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/new_test.go
sdk/go/common/apitype/core.go
sdk/go/common/resource/config/key.go
sdk/go/common/workspace/project.go

This modifies `pulumi new` to add a `pulumi:template` stack tag, set to the name or URL of the template.

Enable finding Pulumi projects created from Templates

---

pkg/codegen/schema/schema.go

Seen while running tests for another PR: https://github.com/pulumi/pulumi/actions/runs/7639934341/job/20814238592?pr=15232
```
Read at 0x00c0009e8480 by goroutine 46:
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*Package).TokenToModule()
/home/runner/work/pulumi/pulumi/pkg/codegen/schema/schema.go:873 +0x13e
github.com/pulumi/pulumi/pkg/v3/codegen/schema.packageDefRef.TokenToModule()
/home/runner/work/pulumi/pulumi/pkg/codegen/schema/package_reference.go:171 +0x84
github.com/pulumi/pulumi/pkg/v3/codegen/pcl.canonicalizeToken()
/home/runner/work/pulumi/pulumi/pkg/codegen/pcl/binder_schema.go:181 +0x10d
github.com/pulumi/pulumi/pkg/v3/codegen/pcl.(*packageSchema).initResourceMap()
/home/runner/work/pulumi/pulumi/pkg/codegen/pcl/binder_schema.go:111 +0x124 …
```

Fix a datarace

---

changelog/pending/20240119--sdk-python--add-support-for-python-3-12.yaml
scripts/get-job-matrix.py
sdk/python/lib/pulumi/dynamic/__main__.py
sdk/python/lib/pulumi/provider/server.py
sdk/python/lib/setup.py
sdk/python/requirements.txt
tests/integration/integration_python_acceptance_test.go
tests/smoke_test.go

Python 3.12 requires `grpcio` 1.59.0 or higher. Unfortunately, there is a regression in `grpcio` 1.58.0 through the latest version (currently 1.60.0) which causes any error returned from a Python gRPC server to be written to stderr, including UNIMPLEMENTED errors. This primarily affects Python dynamic providers, which don't have implementations for `CheckConfig` and `DiffConfig`, resulting in a traceback error being emitted to stderr when the engine calls these, which is visible to users. This `grpcio` regression has been fixed upstream, but the fix has not been released yet. We've been waiting for a 1.60.1 patch release.
This has not been great for our Python users who are using Python 3.12. It's particularly bad for new Pulumi users who are using Python 3.12 and are trying to get …

Support Python 3.12

---

scripts/go-test.py

Reverts pulumi/pulumi#15217.  Unfortunately there seem to be too many flakes left that we should address before doing this.

Revert "Disable `--rerun-fails` in tests"

---

changelog/pending/20240122--engine--fix-a-hang-in-preview-import-file.yaml
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/preview_test.go

Fixes https://github.com/pulumi/pulumi/issues/15068.
We can exit the loop building the preview file early if we encounter any errors. If we do that we stop reading the events channel which was causing the writers of that channel (the main engine loop) to block. This adds a deferred function to just make sure we fully drain that channel. 
P.S. Don't tempt me to write `channel.Scan`.

Fix hang in --preview-file

---

changelog/pending/20240125--programgen-nodejs--fixes-generated-expression-for-filebase64-function-to-use-fs-readfilesync-directly-with-base64-encoding-option.yaml
pkg/codegen/nodejs/gen_program_expressions.go
pkg/codegen/testing/test/testdata/functions-pp/nodejs/functions.ts

Fixes #15246 by correcting the generated expression for the `filebase64` function
-  [x] I have run `make lint` to verify my code passes the lint check

[program-gen/ts] Fixes generated expression for filebase64 function to use fs.readFileSync directly

---

sdk/nodejs/cmd/pulumi-language-nodejs/language_test.go
tests/integration/construct_component_configure_provider/python/requirements.txt
tests/integration/integration_python_acceptance_test.go
tests/smoke_test.go

- Unskip Python tests that needed to be skipped until v3.103.0 of the `pulumi` PyPi package was released with support for Python 3.12.
- Unskip Node.js test that needed to be skipped until v3.103.1 of the `@pulumi/pulumi` NPM package was published with a fix for the semver type issue.
Fixes #15195

Unskip tests

---

pkg/backend/display/object_diff.go
pkg/engine/events.go
pkg/resource/stack/deployment.go
pkg/resource/stack/deployment_test.go
sdk/go/common/resource/archive/archive.go
sdk/go/common/resource/archive/archive_test.go
sdk/go/common/resource/asset.go
sdk/go/common/resource/asset/asset.go
sdk/go/common/resource/asset_test.go
sdk/go/common/resource/mapper_test.go
sdk/go/common/resource/plugin/provider_plugin.go
sdk/go/common/resource/plugin/provider_plugin_test.go
sdk/go/common/resource/plugin/rpc.go
sdk/go/common/resource/plugin/rpc_test.go
sdk/go/common/resource/properties.go
sdk/go/common/resource/properties_diff_test.go
sdk/go/common/resource/sig/sig.go
sdk/go/common/resource/testing/rapid.go
sdk/go/pulumi/provider_test.go
sdk/go/pulumi/rpc.go
sdk/go/pulumi/rpc_test.go

This PR is motivated by https://github.com/pulumi/pulumi/pull/15145.
`resource.*` should be built on top of `property.Value`,[^1] which means that `resource`
needs to be able to import `property.Value`, and so `property` cannot import
`resource`. Since Assets and Archives are both types of properties, they must be moved out
of `resource`.
[^1]: For example: https://github.com/pulumi/pulumi/blob/a1d686227cd7e3c70c51bd772450cb0cd57c1479/sdk/go/common/resource/resource_state.go#L35-L36
This PR moves them to their own sub-folders in `resource`. Should `asset` and `archive`
live somewhere more high level, like `sdk/go/property/{asset,archive}`?

Move assets and archives to their own package

---

sdk/nodejs/package.json
sdk/nodejs/yarn.lock

We've previously pinned this to 1.9.6, because there was a bug that caused an automation API hang in 1.9.7.  There's been a few patch releases since, so let's try to upgrade again, as this could potentially fix some flaky
tests (https://github.com/pulumi/pulumi/issues/14841).
The PR doing the downgrade originally also introduced a test, so as long as that test is passing upgrading should be safe.
Fixes https://github.com/pulumi/pulumi/issues/14841

upgrade grpc-js to latest release

---

changelog/pending/20240104--auto-go--add-new-api-to-install-the-pulumi-cli-from-the-automation-api.yaml
sdk/go/auto/cmd.go
sdk/go/auto/cmd_test.go
sdk/go/auto/local_workspace.go
sdk/go/auto/local_workspace_test.go
sdk/go/auto/stack.go
sdk/go/auto/workspace.go
sdk/go/common/env/env.go

Provide a way for the Automation API to install the Pulumi CLI so that Automation API can be used in a more standalone manner.
https://github.com/pulumi/pulumi/issues/14987
⚠️ Needs https://github.com/pulumi/get.pulumi.com/pull/171 to be merged and deployed to production first.

[auto/go] Add new API to install the Pulumi CLI

---

changelog/pending/20240122--auto-python--add-new-api-to-install-the-pulumi-cli.yaml
sdk/python/Makefile
sdk/python/lib/pulumi/_version.py
sdk/python/lib/pulumi/automation/__init__.py
sdk/python/lib/pulumi/automation/_cmd.py
sdk/python/lib/pulumi/automation/_env.py
sdk/python/lib/pulumi/automation/_local_workspace.py
sdk/python/lib/pulumi/automation/_stack.py
sdk/python/lib/pulumi/automation/_workspace.py
sdk/python/lib/test/automation/test_cmd.py
sdk/python/lib/test/automation/test_local_workspace.py

Provide a way for the Automation API to install the Pulumi CLI so that Automation API can be used in a more standalone manner.
https://github.com/pulumi/pulumi/issues/14987

[auto/python] Add new API to install the Pulumi CLI

---

changelog/pending/20240124--engine--engine-will-now-error-if-aliases-request-a-parent-with-no-urn.yaml
pkg/engine/lifecycletest/alias_test.go
pkg/engine/lifecycletest/pulumi_test.go
pkg/resource/deploy/deploytest/resourcemonitor.go
pkg/resource/deploy/source_eval.go

Title sums it up. Some SDKs are sending `parent=""` rather than no parent at all to specify to the engine to use the default parent. Technically this isn't the intention of the protocol but given the SDKs are out we now need to support it. I've added a test to check this works and left a comment that it would be a nice tidy up to make in V4.
I've also changed the deploy tests to directly use the rpc protocol rather than `resource.Alias` this lets us write tests like "send an empty parent URN" which `resource.Alias` wasn't capable of expressing.

Test that an empty parent URN in an alias is treated as the default parent

---

pkg/engine/lifecycletest/test_plan.go

I noticed that `testBuilder.WithProvider(name, ...)` wasn't actually passing the name through to `deploytest.NewProviderLoader` and instead is always passing `"pkgA"`. This commit fixes that. No current tests are affected, as they all pass `"pkgA"` for the name anyway.

[tests] testBuilder: Use specified package name

---

sdk/go/auto/cmd.go
sdk/go/auto/cmd_test.go

We're seeing Go Automation API test failures on Windows. Looks like it's likely due to the use of `path.Join` (introduced in https://github.com/pulumi/pulumi/pull/15049 which merged about an hour ago; it's a separate question on how it was able to merge with failures on Windows). This PR changes those uses of `path` to `filepath`.
Note: No changelog because this hasn't been released yet.
This is currently blocking merges.
Fixes #15272

[sdk/go] Use `filepath.Join` rather than `path.Join`

---

changelog/pending/20240124--engine--fix-stack-name-validation-when-pulumi_disable_validation-isnt-set.yaml
pkg/backend/httpstate/client/client_test.go
pkg/resource/deploy/import_test.go
pkg/resource/deploy/source_eval_test.go
pkg/resource/deploy/step_generator_test.go
sdk/go/common/tokens/stack_name.go

The disable validation check for this was wrong (it did the assert if validation was disabled).

Fix stack name validation check

---

changelog/pending/20240127--sdkgen-go--remove-pulumix-references-from-generated-enums.yaml
pkg/codegen/go/gen.go
pkg/codegen/testing/test/testdata/array-of-enum-map/go/example/pulumiEnums.go
pkg/codegen/testing/test/testdata/dashed-import-schema/go/plant-provider/pulumiEnums.go
pkg/codegen/testing/test/testdata/dashed-import-schema/go/plant-provider/tree/v1/pulumiEnums.go
pkg/codegen/testing/test/testdata/different-enum/go/plant/pulumiEnums.go
pkg/codegen/testing/test/testdata/different-enum/go/plant/tree/v1/pulumiEnums.go
pkg/codegen/testing/test/testdata/external-enum/go/example/local/pulumiEnums.go
pkg/codegen/testing/test/testdata/naming-collisions/go/example/pulumiEnums.go
pkg/codegen/testing/test/testdata/output-funcs-edgeorder/go/myedgeorder/pulumiEnums.go
pkg/codegen/testing/test/testdata/provider-config-schema/go/configstation/pulumiEnums.go
pkg/codegen/testing/test/testdata/regress-node-8110/go/my8110/pulumiEnums.go
pkg/codegen/testing/test/testdata/simple-yaml-schema/go/example/pulumiEnums.go

This PR fixes build issues for Go SDKs where enums import the `pulumix` package without using it or sometimes using it with generated input interfaces for the enums for non-generic sdks. The problem was using the function `goPackageInfo` which reads the package info from the language section of the schema but not initializing `Generics` field to `none` when it is empty.

[sdk-gen/go] Remove pulumix references from generated enums in non-generic SDKs

---

changelog/pending/20240127--sdk-go--include-error-message-in-local-workspace-validation.yaml
sdk/go/common/workspace/project.go

If project settings are not valid `contract.Requiref(proj.Validate() == nil, "proj", "Validate()")` just returns `Validate()` which makes it difficult to debug why the call to `proj.Validate()` failed. This change captures the error returned by `proj.Validate()` and includes that as part of the message.

local workspace project validation should include error message

---

cmd/pulumi-test-language/interface.go
cmd/pulumi-test-language/l1empty_test.go
cmd/pulumi-test-language/l2resourcesimple_test.go

Adds a DisableSnapshotWriting flag to the conformance interface so that the tests we write for conformance itself that generate bad snapshots can opt out of PULUMI_ACCEPT behaviour. I tripped myself up earlier by running all the tests with PULUMI_ACCEPT=1 and then getting confused on why the bad snapshot tests were suddenly failing.

Add a flag to not write out bad snapshots

---

cmd/pulumi-test-language/interface.go
cmd/pulumi-test-language/l1empty_test.go
cmd/pulumi-test-language/l1main_test.go
cmd/pulumi-test-language/l2resourcesimple_test.go
cmd/pulumi-test-language/testdata/l1-main/main.pp
cmd/pulumi-test-language/testdata/snapshots/projects/l1-main/Pulumi.yaml
cmd/pulumi-test-language/testdata/snapshots_bad/projects/l2-resource-simple/Pulumi.yaml
cmd/pulumi-test-language/tests.go
pkg/codegen/nodejs/gen_program.go
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/projects/l1-main/Pulumi.yaml
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/projects/l1-main/subdir/.gitignore
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/projects/l1-main/subdir/index.ts
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/projects/l1-main/subdir/package.json
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/projects/l1-main/subdir/tsconfig.json

This adds a main option to the test, that is put into the Pulumi.yaml and sent to codegen.  This allows us to write a test that sets up "main" in a Pulumi.yaml file and test that "program directory" and "entry point" are respected. Doing this correctly also required some bug fixes in the conformance interface itself.

Test main in conformance tests

---

cmd/pulumi-test-language/interface.go
cmd/pulumi-test-language/runtime_options_test.go
cmd/pulumi-test-language/testdata/snapshots_runtime_options/projects/l1-empty/Pulumi.yaml

Adds a test that the conformance suite correctly passes on runtime options that a language emits during project code generation.

Test runtime options in conformance tests

---

.github/workflows/ci.yml

I was watching the merge queue quite closely today, and it's continually stuck waiting to run jobs on MacOS runners.  However when the jobs are running on them they tend to be faster than e.g. Windows runners, often running the tests assigned to them in 2 min, vs. 8 min on windows.
In addition we're spending quite a bit of time to setup the actual running of tests, and by spreading the tests out over multiple runners that time multiplies.  Given the macos runners are the most expensive ones that probably also adds up.
Given all that, we can reduce the number of MacOS runners we're using, while not trading that off against longer overall CI times, as those are limited by slower jobs.
Unfortunately this results in some duplication in the ci job, but I think the tradeoff here might be worth …

reduce the number of partitions for macos runners

---

changelog/pending/20240127--auto-python--inline-programs-can-now-be-defined-as-async-functions.yaml
sdk/python/cmd/pulumi-language-python-exec
sdk/python/lib/pulumi/automation/_server.py
sdk/python/lib/pulumi/automation/_workspace.py
sdk/python/lib/pulumi/runtime/stack.py
sdk/python/lib/test/automation/test_local_workspace.py

This updates the typing annotations and semantics of Python Automation API inline programs. It's now defined to be a callable that returns an optional awaitable of `None`. This supports both existing synchronous functions (should just return `None`) and now also supports async functions that return an `Awaitable` that eventually resolves to `None`.

Support async inline programs

---

changelog/pending/20240127--auto-go--remove-obsolete-note-from-fullyqualifiedstackname-comment.yaml
sdk/go/auto/stack.go

There is an obsolete note in the comment for `auto.FullyQualifiedStackName` regarding not using an FQDN with filestate backends which can cause some confusion since it is now supported.

auto.FullyQualifiedStackName doc fix

---

sdk/go/common/util/logging/log.go

This allows pulumi's log output to contain the location of where the log call was made from, rather than it always reporting the line in `log.go` where the glog call was made.
This changes
```
I0124 20:53:35.244319  169013 log.go:81] skipping update check
I0124 20:53:36.262079  169013 log.go:81] found username for access token
```
to
```
I0129 14:08:42.918230   38925 pulumi.go:231] skipping update check
I0129 14:08:45.056866   38925 backend.go:615] found username for access token
```
- This is hard to test because it is difficult to reliably intercept stderr from within go tests

Use the Depth variants in glog calls

---

pkg/backend/filestate/backend.go
pkg/backend/filestate/backend_test.go
pkg/backend/filestate/meta.go
pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/refresh.go
pkg/cmd/pulumi/state_upgrade.go
pkg/cmd/pulumi/up.go
pkg/cmd/pulumi/util.go
sdk/go/common/env/env.go
sdk/go/common/util/env/env.go
sdk/go/common/util/env/env_test.go
tests/integration/integration_test.go

We're moving away from referring to filestate as "self managed" backends, preferring to refer to this as "DIY" backends going forward.

Rename self-managed to diy-backend

---

changelog/pending/20240129--engine--fix-a-performance-issue-doing-unneeded-secret-encryption.yaml
pkg/resource/stack/deployment.go
pkg/resource/stack/deployment_test.go

While investigating into https://github.com/pulumi/pulumi/issues/15293 I noticed that `SerializePropertyValue` was always calling into `Encrypter.EncryptValue` (or `cachingCrypter.encryptSecret`) even when `showSecrets` was true and the cipher text wasn't being returned.
This is a simple move of that logic into the `!showSecrets` branch so it gets skipped entirely when the cipher text isn't needed.

Don't encrypt secrets to get ciphertext that isn't actually used

---

changelog/pending/20240127--sdk-python--remove-compatability-code-for-python-3-7-and-below.yaml
sdk/python/cmd/pulumi-language-python-exec
sdk/python/lib/pulumi/_types.py
sdk/python/lib/pulumi/automation/_server.py
sdk/python/lib/pulumi/runtime/rpc.py
sdk/python/lib/pulumi/runtime/stack.py
sdk/python/lib/pulumi/runtime/sync_await.py

We've bumped the minimum version on the package and haven't officially supported versions before 3.8 for a while now. 
This cleans up a load of code we had just for compat with 3.7 and lower.

Clean up legacy Py 3.7 support

---

.github/workflows/ci.yml

This TODO has been there since this 6ef7ef64d620dafda126e1623c92ea2ff4823031 was merged to the main branch, but the flag was always true, and the comment also tells us to set it to true.  Setting it to true is still the right thing, so let's just get rid of the confusing comment.
Just a minor cleanup I noticed while working on some CI stuff.

ci: remove unnecessary TODO

---

tests/smoke_test.go
tests/testdata/import_node/index.ts

TestPreviewImportFile could fail if the two resources registered in the opposite order to what the test expected.
https://github.com/pulumi/pulumi/actions/runs/7708946353/job/21009583196
This fixes the resources to always register in the same order via a `dependsOn` option, and then fixes the test to pass for that ordering.

Fix flakey test

---

scripts/get-job-matrix.py

v18.x is the LTS Maintenance release and v21.x is the Current release. https://nodejs.org/en/about/previous-releases

ci: Bump Node.js versions

---

pkg/engine/lifecycletest/provider_test.go
pkg/resource/deploy/source_eval.go
pkg/resource/deploy/source_eval_test.go

Noticed this while trying to prepare a PR for the transforms support. These tests were checking that we mutated a field on the request object itself. We no longer do that in the transform branch because everything has to go through the transform callbacks as well but it caused these tests to fail.
I've deleted these tests and written a new engine test to validate the system output is actually as expected.

Don't mutate RegisterResourceRequest

---

changelog/pending/20240130--pkg-testing--add-requireemptypreviewafterrefresh-option-to-programtest.yaml
pkg/testing/integration/program.go

While working on [this issue in Azure Native](https://github.com/pulumi/pulumi-azure-native/issues/2798), I realized that I don't see how to test the scenario that I care about. I need the following workflow:
1. Run `pulumi up` for the initial deployment.
2. Run `pulumi refresh` to pull changes from API.
3. Run `pulumi preview --expect-no-changes` to guarantee that there is no loop of `refresh/up` stepping over each other.
The existing `ExpectRefreshChanges` option is different. If it's set to false, the test would require no changes on step (2) above, which is a stronger requirement. Unfortunately, it's not always true in Azure Native, e.g. when a subresource changes properties of its parent resource. I want to enable "ExpectRefreshChanges: false" where possible, but I also want to …

Add RequireEmptyPreviewAfterRefresh option to ProgramTest

---

changelog/pending/20240131--cli--adds-a-preview-only-flag-to-pulumi-refresh.yaml
pkg/backend/backend.go
pkg/backend/diy/backend.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/snapshot.go
pkg/backend/stack.go
pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/refresh.go
pkg/cmd/pulumi/up.go
pkg/cmd/pulumi/util.go
pkg/cmd/pulumi/watch.go
tests/preview_only_test.go

Adds a `preview-only` flag to `pulumi refresh`.
Fixes #15301

Implement preview-only refresh

---

README.md

Node.js, Python, and .NET minimum versions are out-of-date. Rather than continuing to maintain the specific versions, link to the supported versions like we do in the documentation at https://www.pulumi.com/docs/languages-sdks/.

Update language runtime versions in README.md

---

changelog/pending/20240131--cli--adds-preview-only-flag-for-pulumi-destroy-and-pulumi-import.yaml
pkg/backend/diy/backend.go
pkg/backend/httpstate/backend.go
pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/import.go
tests/preview_only_test.go

Figured I could round out #1666 while I was in the area.
Fixes #15304 
Fixes #15303 
Fixes #1666

Add preview-only flag for destroy and import

---

changelog/pending/20240201--sdk-go--add-upgradeoutputs-to-marshaloptions.yaml
sdk/go/common/resource/plugin/rpc.go
sdk/go/common/resource/plugin/rpc_test.go

This adds a new option `UpgradeToOutputValues` to `MarshalOptions`. When set all `Computed` and `Unknown` values are _upgraded_ to `Output` values. This reduces the number of cases that need to be handled later in the codebase.

Add UpgradeToOutputValues to MarshalOptions

---

changelog/pending/20240202--auto-go--adds-support-for-pulumi-up-refresh-via-go-automation-api.yaml
sdk/go/auto/local_workspace_test.go
sdk/go/auto/optdestroy/optdestroy.go
sdk/go/auto/optpreview/optpreview.go
sdk/go/auto/optup/optup.go
sdk/go/auto/stack.go

Fixes https://github.com/pulumi/pulumi/issues/15351

Add a `Refresh` option for `Stack.Up()`, `Stack.Preview()` and `Stack.Destroy()`

---

changelog/pending/20240202--docs--add-kubernetes-as-a-supported-pulumi-convert-language.yaml
pkg/cmd/pulumi/convert.go

Adds `kubernetes` as a supported pulumi convert language. This will use https://github.com/pulumi/pulumi-converter-kubernetes.

Add kubernetes as supported pulumi convert language

---

changelog/pending/20240203--sdk-python--require-python-3-8-or-greater.yaml
sdk/python/README.md
sdk/python/lib/setup.py

Python 3.7 is unsupported and has been end-of-life since 6/27/2023. See https://devguide.python.org/versions/
This change updates the core SDK package to indicate that Python 3.8 or greater is required.
Fixes #15364

[sdk/python] Require Python >=3.8

---

pkg/codegen/testing/test/testdata/plain-and-default-go-generics-only/go/foo/moduleResource.go
pkg/codegen/testing/test/testdata/plain-and-default-go-generics-only/schema.json
pkg/codegen/testing/test/testdata/plain-and-default/docs/moduleresource/_index.md
pkg/codegen/testing/test/testdata/plain-and-default/dotnet/ModuleResource.cs
pkg/codegen/testing/test/testdata/plain-and-default/go-extras/tests/codegen_test.go
pkg/codegen/testing/test/testdata/plain-and-default/go/foo/moduleResource.go
pkg/codegen/testing/test/testdata/plain-and-default/go/foo/x/moduleResource.go
pkg/codegen/testing/test/testdata/plain-and-default/nodejs/moduleResource.ts
pkg/codegen/testing/test/testdata/plain-and-default/python/pulumi_foobar/module_resource.py
pkg/codegen/testing/test/testdata/plain-and-default/schema.json
pkg/codegen/testing/test/testdata/regress-py-14012/python/pulumi_foo/_inputs.py
pkg/codegen/testing/test/testdata/regress-py-14012/schema.json
pkg/codegen/testing/test/testdata/transpiled_examples/cue-random-pp/dotnet/dotnet.csproj
pkg/codegen/testing/test/testdata/transpiled_examples/getting-started-pp/dotnet/dotnet.csproj
pkg/codegen/testing/test/testdata/transpiled_examples/kubernetes-pp/dotnet/dotnet.csproj
pkg/codegen/testing/test/testdata/transpiled_examples/random-pp/dotnet/dotnet.csproj

A few of the test schema's were using snake_case names. Codegen doesn't actually deal well with that so was giving some odd snapshot results, this just fixes up the tests to use camelCase instead to get more standard codegen results out.

Use camelCase for schema names

---

changelog/pending/20231129--cli-display--add-suppress-progress-option-to-not-print-dots.yaml
pkg/backend/display/diff.go
pkg/backend/display/jsonmessage.go
pkg/backend/display/options.go
pkg/backend/display/query.go
pkg/backend/httpstate/backend.go
pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/refresh.go
pkg/cmd/pulumi/replay_events.go
pkg/cmd/pulumi/up.go
pkg/cmd/pulumi/watch.go
sdk/go/common/util/cmdutil/spinner.go

Adds support for suppressing the periodic "..." printing that can disrupt normal output stream.  This output is still deemed necessary to include by default for CI systems that might otherwise cancel an update that goes for a long time without printing anything.  But we now have an option to turn this off.
Notes:
1. We want to expose this via Automtation API, and may even want to default to off via Automation API?
Fixes https://github.com/pulumi/pulumi/issues/14069.
Related https://github.com/pulumi/pulumi/issues/11139.

Add `--suppress-progresss` flag to CLI

---

changelog/pending/20240205--backend-diy--fix-an-issue-where-state-stored-on-a-mounted-device-would-result-in-errors.yaml
pkg/backend/diy/backend.go
pkg/backend/diy/backend_test.go

In gocloud.dev 0.34.0 the behaviour for file:// URLs changed, making pulumi fail when the state is supposed to be written to a mounted directory.  See also https://github.com/pulumi/pulumi/issues/15352.
Restore the old behaviour by adding a `no_tmp_dir=true` flag to the URL, unless the user provided it themselves.  We also allow users to pass `no_tmp_dir=false` in the parameters, which will opt in to the new behaviour.
This actually implements option 2 from the linked issue since it was easy enough to do, though I don't expect may users to make use of it, since I don't think a lot of people care about the contents of whatever directory the state is stored in anyway, so additional temp files there don't really matter.
Fixes https://github.com/pulumi/pulumi/issues/15352

add no_tmp_dir query parameter to file:// URLs

---

changelog/pending/20240131--cli-state--fix-a-panic-when-trying-to-delete-a-provider-from-the-state-thats-still-referenced.yaml
pkg/cmd/pulumi/state_delete.go
pkg/resource/edit/operations.go
pkg/resource/edit/operations_test.go
pkg/resource/graph/dependency_graph.go
pkg/resource/graph/dependency_graph_test.go

In https://github.com/pulumi/pulumi/commit/30f59eb30a9b519766aa0e3d3e463a2b4667466b, we made sure that we
don't delete multiple resources, when a user is prompted to choose
between multiple resources with the same URN.
If there are non-unique URNs, we currently assume that we can just go
ahead and delete it, as there's still another resource that will
fulfill the requirements.
However that is not true if the dependent is a provider.  Providers
are identified by a {URN, ID} tuple.  Therefore even though after the
deletion of a provider with a specific URN there's still another one
with the same URN left, this is not good enough to fulfill the
dependency requirements.
If we don't have a unique URN, check again to make sure there's no
provider dependency on the condemned resource.  If there …

State: fix panic when deleting non-unique Provider

---

changelog/pending/20240203--sdk-python--upgrade-grpcio-to-1-60-1.yaml
sdk/python/lib/pulumi/dynamic/__main__.py
sdk/python/lib/pulumi/provider/server.py
sdk/python/lib/setup.py
sdk/python/requirements.txt

grpcio 1.60.1 includes a fix for the regression that results in a traceback being written to stderr for unimplemented gRPC methods. https://github.com/grpc/grpc/releases/tag/v1.60.1
This change upgrades to 1.60.1 and reverts the workarounds we put in place in https://github.com/pulumi/pulumi/pull/15190.
Note that we have an integration test for Python dynamic providers that ensures nothing unexpected is written to stderr: https://github.com/pulumi/pulumi/blob/16a1fb31c2040785dbbfb9de43d772d8e16fffaa/tests/integration/integration_python_acceptance_test.go#L111-L117
Fixes #15365

[sdk/python] Upgrade to grpcio 1.60.1

---

changelog/pending/20240206--engine--translate-all-computed-and-secret-values-to-outputvalues-for-construct-and-call-methods.yaml
pkg/engine/lifecycletest/pulumi_test.go
pkg/resource/deploy/deploytest/resourcemonitor.go
pkg/resource/deploy/source_eval.go
pkg/resource/deploy/source_eval_test.go

Stage 1 of updating how we deal with OutputValues in source_eval for transforms.
This makes two changes that should result in basically a no-op for standard resources, but update all Computed/Secret values to OutputValues for Call and Construct.
This is a no-op for standard resources because previously we set "KeepOutputs" to false when we unmarshalled them. That replaced all OutputValues with Computed/Secret. Now we do "UpdgradeOutputs" at the start of source_eval but then call "DowngradeOutputs" before passing the properties on to the rest of the system. So this is a complete no-op.
But for Call/Construct we used to use "KeepOutputs" but now we do "UpgradeOutputs". So values that previously got sent as Computed/Secret will now get sent as OutputValue. This _should_ be fine, all users of …

Upgrade output values in source_eval

---

changelog/pending/20240202--cli-state--fix-a-nil-reference-panic-in-the-state-edit-command.yaml
pkg/cmd/pulumi/state_edit.go
pkg/cmd/pulumi/state_edit_encoder.go
pkg/cmd/pulumi/state_edit_test.go

Fixes https://github.com/pulumi/pulumi/issues/15345.

Fix context in state edit command

---

pkg/engine/lifecycletest/alias_test.go
pkg/engine/lifecycletest/analyzer_test.go
pkg/engine/lifecycletest/delete_before_replace_test.go
pkg/engine/lifecycletest/golang_sdk_test.go
pkg/engine/lifecycletest/import_test.go
pkg/engine/lifecycletest/provider_test.go
pkg/engine/lifecycletest/pulumi_test.go
pkg/engine/lifecycletest/refresh_test.go
pkg/engine/lifecycletest/resource_reference_test.go
pkg/engine/lifecycletest/source_query_test.go
pkg/engine/lifecycletest/step_generator_test.go
pkg/engine/lifecycletest/target_test.go
pkg/engine/lifecycletest/update_plan_test.go
pkg/resource/deploy/deploytest/resourcemonitor.go
pkg/resource/deploy/deploytest/resourcemonitor_test.go
pkg/resource/deploy/source_eval_test.go

The only real change here is a new test in pkg/engine/lifecycletest/pulumi_test.go and the small fix up to the `deploytest.ResourceMonitor` to return the information needed for that test.

Add an engine test for Construct and Call dependency maps

---

.github/workflows/ci-test-docs-generation.yml

resourcedocsgen has been remved from the pulumi/docs repo in https://github.com/pulumi/docs/pull/10009, so now the related CI build fails.  Get it from the pulumi/registry repository instead, where it lives now.
Note that this requires https://github.com/pulumi/docs/pull/10053 to be merged first to update the script to no longer try to build the tool.
I'm not sure why the CI job didn't break earlier, the first time I noticed it being broken was in https://github.com/pulumi/pulumi/pull/14156.

build resourcedocsgen from registry

---

changelog/pending/20240208--components-go--component-providers-now-correctly-return-output-values-to-the-engine.yaml
pkg/engine/lifecycletest/pulumi_test.go
sdk/go/common/resource/plugin/provider_server.go

So it turned out that the server code for providers was set up to never return output values. I don't think any actual providers  used this code but it meant the tests running in GRPC mode started to fail.

Update engine test to use GRPC and fix issues

---

changelog/pending/20240208--engine--engine-no-longer-assumes-program-dependencies-are-specified-as-semantic-versions.yaml
cmd/pulumi-test-language/interface.go
pkg/cmd/pulumi/about.go
sdk/go/common/resource/plugin/langruntime.go
sdk/go/common/resource/plugin/langruntime_plugin.go

This weakens the contract of GetProgramDependencies that the versions returned are just "strings". The format of those strings is defined by the language plugin. This is especially useful for python which uses PEP440 not semantic versions for it's pip dependencies.
There wasn't anywhere in the system that took a strong dependency on these being semvers.

Program dependencies aren't necessarily semantic versions

---

pkg/codegen/docs/gen.go
pkg/codegen/docs/templates/enums.tmpl
pkg/codegen/testing/test/testdata/dashed-import-schema/docs/tree/v1/nursery/_index.md
pkg/codegen/testing/test/testdata/dashed-import-schema/docs/tree/v1/rubbertree/_index.md
pkg/codegen/testing/test/testdata/different-enum/docs/tree/v1/nursery/_index.md
pkg/codegen/testing/test/testdata/different-enum/docs/tree/v1/rubbertree/_index.md
pkg/codegen/testing/test/testdata/external-enum/docs/component/_index.md
pkg/codegen/testing/test/testdata/other-owned/docs/overlayresource/_index.md
pkg/codegen/testing/test/testdata/plain-and-default/docs/moduleresource/_index.md
pkg/codegen/testing/test/testdata/provider-config-schema/docs/provider/_index.md
pkg/codegen/testing/test/testdata/simple-enum-schema/docs/tree/v1/nursery/_index.md
pkg/codegen/testing/test/testdata/simple-enum-schema/docs/tree/v1/rubbertree/_index.md
pkg/codegen/testing/test/testdata/simple-resource-schema/docs/overlayresource/_index.md
pkg/codegen/testing/test/testdata/simple-yaml-schema/docs/typeuses/_index.md

Fixes: https://github.com/pulumi/registry/issues/3724
Fixes: https://github.com/pulumi/registry/issues/2966
This PR is to resolve the enum rendering issue. The enums were not being rendered on the page at all due to a misconfigured language choosable (i.e. `<pulumi-choosable>`) that wraps the enum section.  I found out this had to do with the lang property being set as `nodejs` when instead the choosable expects `javascript` or `typescript` as the valid values. I then followed the pattern of what we seem to be doing for the other pulumi-choosables which have this issue, which is to  have an if statement that sets it to `javascript,typescript` if `nodejs` is given.
This is how the rendering looks now. I have not adjusted any layouts of the template or anything along those lines, only fixed …

Fix enum rendering issue

---

changelog/pending/20240130--backend-diy--add-a-warning-that-non-project-mode-will-be-deprecated-at-some-point.yaml
pkg/backend/diy/backend.go
sdk/go/common/env/env.go

In preparation for deprecating non-project mode at some point. This is phase 1 of encouraging users off of legacy mode.
Any time a user opens a backend in legacy mode (either old states, or new states with DIY_BACKEND_LEGACY_LAYOUT set) we'll warn that non-project mode is due to deprecate this year.
They can disable this warning by setting PULUMI_DIY_BACKEND_ACKNOWLEDGE_LEGACY_WARNING to true.
The next phase (in a few months) will turn this into an error which they'll be able to opt out of by setting PULUMI_DIY_BACKEND_ACKNOWLEDGE_LEGACY_ERROR to true.
After that it will be a hard error and all non-project related code will be removed.

Warn about non-project mode

---

scripts/get-job-matrix.py

Go 1.22 has been released https://tip.golang.org/doc/go1.22.

Update tests to run on Go 1.21 and 1.22

---

changelog/pending/20240214--cli--fix-pulumi-destroy-to-fill-in-stack-config-with-the-secret-config-from-state-not-fresh-secret-config.yaml
pkg/cmd/pulumi/config.go
pkg/cmd/pulumi/crypto.go
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/stack_change_secrets_provider.go
tests/go.mod
tests/stack_test.go

While working on some other secret manager changes I found that `TestDestroySetsEncryptedkey` wasn't actually fully testing what we thought it was.
Firstly it was a bad name, we're checking for `encryptionsalt` being set not `encryptedkey`. But more importantly it wasn't checking that the salt stayed the same. 
Turned out `destroy` was loading the stack config, seeing no `encryptionsalt` and so new'ing up a brand new passphrase secret manager and state and then saving that to the stack config.
This is now fixed that the test asserts that the salt is exactly what's expected and I've fixed up the engine code to do this correctly.

Fix TestDestroySetsEncryptionsalt test and resulting bug

---

.github/workflows/ci-dev-release.yml
changelog/pending/20240129--sdk-nodejs-python--publish-dev-versions-of-the-nodejs-and-python-sdks.yaml
scripts/publish_npm.sh
scripts/pulumi-version.sh

Publish dev versions of the python and node SDKs, so we can consume them pre-release and make our releases more stable.
Also clean up the publish_npm.sh script a little bit, removing now unused cruft.

Publish dev versions of the python and node SDKs

---

.github/workflows/on-merge.yml

In https://github.com/pulumi/pulumi/pull/15299 we changed the versioning scheme of dev releases slightly, as npm and python have slightly different requirements.  However this also means that names of CLI dev releases changed, and thus downloads failed.
Fix that by updating the latest-dev-version file to the new versioning scheme.
Fixes https://github.com/pulumi/pulumi/issues/15443

correct latest-dev-version file

---

changelog/pending/20240213--sdk-nodejs--detect-npm-and-yarn-workspaces-setups-when-installing-dependencies.yaml
sdk/nodejs/Makefile
sdk/nodejs/cmd/pulumi-language-nodejs/main.go
sdk/nodejs/npm/testdata/nested/package.json
sdk/nodejs/npm/testdata/nested/project/index.ts
sdk/nodejs/npm/testdata/workspace/package.json
sdk/nodejs/npm/testdata/workspace/packages/some-package/package.json
sdk/nodejs/npm/testdata/workspace/project/package.json
sdk/nodejs/npm/workspaces.go
sdk/nodejs/npm/workspaces_test.go
sdk/nodejs/tsconfig.json
tests/integration/integration_nodejs_test.go
tests/integration/nodejs/npm-and-yarn-not-a-workspace/infra/Pulumi.yaml
tests/integration/nodejs/npm-and-yarn-not-a-workspace/infra/index.ts
tests/integration/nodejs/npm-and-yarn-not-a-workspace/infra/package.json
tests/integration/nodejs/npm-and-yarn-not-a-workspace/package.json
tests/integration/nodejs/npm-and-yarn-workspaces/infra/Pulumi.yaml
tests/integration/nodejs/npm-and-yarn-workspaces/infra/index.ts
tests/integration/nodejs/npm-and-yarn-workspaces/infra/package.json
tests/integration/nodejs/npm-and-yarn-workspaces/package.json
tests/integration/nodejs/npm-and-yarn-workspaces/packages/my-random/index.ts
tests/integration/nodejs/npm-and-yarn-workspaces/packages/my-random/package.json
tests/integration/nodejs/yarn-workspaces-nohoist/infra/Pulumi.yaml
tests/integration/nodejs/yarn-workspaces-nohoist/infra/index.ts
tests/integration/nodejs/yarn-workspaces-nohoist/infra/package.json
tests/integration/nodejs/yarn-workspaces-nohoist/package.json
tests/integration/nodejs/yarn-workspaces-nohoist/packages/my-random/index.ts
tests/integration/nodejs/yarn-workspaces-nohoist/packages/my-random/package.json

Make `pulumi install` detect npm and yarn workspaces setups and successfully install dependencies.
Fixes #15435

Detect npm and yarn workspaces setups
