.github/workflows/ci-dev-release.yml
For testing purposes we released a new dev SDK on every merge. However this is unnecessary once dev releases are working, and just clogs up the release page/uses extra storage space for the package hosts.
Only publish new dev releases when something actually changed in the SDK, otherwise we can skip publishing.
=> only publish dev releases when the SDK has changes

changelog/pending/20240201--auto-go--automation-api-support-for-pulumi-refresh-preview-only.yaml, sdk/go/auto/local_workspace_test.go, sdk/go/auto/stack.go
Adds Go automation API support for `pulumi refresh --preview-only`. 
Depends on #15330 
Fixes: #15302
=> [go] Automation API support for `pulumi refresh --preview-only`

pkg/backend/httpstate/backend.go, pkg/backend/httpstate/client/client.go, pkg/backend/httpstate/mock.go, pkg/cmd/pulumi/util_remote.go
Fixes https://github.com/pulumi/pulumi/issues/12493
=> Pass in a header to indicate where the deployment initiated

changelog/pending/20240104--docs--fixes-docs-generator-parent-module-computation.yaml, pkg/codegen/docs/gen.go, pkg/codegen/docs/package_tree_test.go
Fixes #14820
Fixes #14821
Fixes a bug in docs generator parent module computation that used to lead to duplicate files panics and undesirable documentation URL layout for affected providers such as [pulumi/fortios](https://github.com/pulumiverse/pulumi-fortios/issues).
Joint work with @tmeckel .
=> Fix docs generator parent module computation 

changelog/pending/20240204--programgen-dotnet-nodejs-python--emit-output-returning-json-serialization-methods-without-rewriting-applies-for-top-level-function-expression.yaml, pkg/codegen/dotnet/gen_program_expressions.go, pkg/codegen/dotnet/test.go, pkg/codegen/nodejs/gen_program_expressions.go, pkg/codegen/pcl/rewrite_apply.go, pkg/codegen/pcl/rewrite_apply_test.go, pkg/codegen/python/gen_program_expressions.go, pkg/codegen/testing/test/helpers.go, pkg/codegen/testing/test/testdata/aws-eks-pp/dotnet/aws-eks.cs, pkg/codegen/testing/test/testdata/aws-eks-pp/nodejs/aws-eks.ts, pkg/codegen/testing/test/testdata/aws-eks-pp/python/aws-eks.py, pkg/codegen/testing/test/testdata/aws-s3-folder-pp/dotnet/aws-s3-folder.cs, pkg/codegen/testing/test/testdata/aws-s3-folder-pp/nodejs/aws-s3-folder.ts, pkg/codegen/testing/test/testdata/aws-s3-folder-pp/python/aws-s3-folder.py, pkg/codegen/testing/test/testdata/python-regress-14037-pp/python/python-regress-14037.py
A while ago we started implementing [specialized JSON serialization methods](https://github.com/pulumi/pulumi/issues/12519) for Pulumi programs which can accept nested outputs without having to rewrite and combine applies. 
- `Output.SerializeJson` in .NET
- `pulumi.jsonStringify` in nodejs
- `pulumi.Output.json_dumps` in Python
This PR extends program-gen for TypeScript, C# and Python to start emitting these JSON serialization functions (when necessary). The PR special-cases the `toJSON` PCL function when rewriting applies so that nested outputs aren't rewritted.
Example PCL program and generated results:
> Also check out the downstream codegen tests to see improved generated examples
```
resource vpc "aws:ec2:Vpc" {
cidrBlock = "10.100.0.0/16"
instanceTenancy = "default"
}
resource …
```
=> [program-gen] Emit Output-returning JSON serialization methods without rewriting applies

changelog/pending/20240217--programgen--fix-infinite-recursion-when-binding-invoke-signature-into-promises-without-accounting-for-recursive-type-references.yaml, pkg/codegen/hcl2/model/type_eventuals.go, pkg/codegen/pcl/functions_test.go, pkg/codegen/testing/test/testdata/recursive-1.0.0.json, pkg/codegen/testing/utils/host.go
Fixes #15434 because using `ContainsPromises` doesn't account for recursive object references where as `ContainsEventuals` does.
=> [program-gen] Fix stack overflow when binding invoke that resolves to promise

changelog/pending/20240216--engine--test-and-fix-the-engine-filling-in-args-dependencies-to-provider-calls.yaml, pkg/engine/lifecycletest/pulumi_test.go, pkg/engine/lifecycletest/source_query_test.go, pkg/resource/deploy/deploytest/resourcemonitor.go, pkg/resource/deploy/deploytest/resourcemonitor_test.go, pkg/resource/deploy/source_eval.go
Adds argsDependencies support to the deploytest resource monitor and add some tests that the engine fills that map in with output values from args if the SDK hasn't filled it in.
We also need to do this the other way (if the SDK fills in argsDependencies but doesn't send output<T> values with those deps to args).
=> Ensure ArgsDependencies are filled in

changelog/pending/20240206--pkg-testing--add-a-installdevreleases-option-to-programtest-to-install-pulumi-dev-sdks.yaml, pkg/testing/integration/program.go
Add a new option `InstallDevReleases` to `ProgramTestOptions`, which will tell ProgramTest to upgrade each pulumi dependency to the latest dev release.  This includes the pulumi/pulumi SDKs and the provider SDKs.  The idea is to use this in the `pulumi/examples` and `pulumi/templates` repositories to get pre release testing there.
Fixes https://github.com/pulumi/pulumi/issues/15389
=> Enable program test to install dev releases of SDKs

.github/workflows/ci-run-test.yml, changelog/pending/20240216--sdk-nodejs--use-pnpm-as-package-manager-if-we-find-a-pnpm-lock-yaml-file.yaml, sdk/nodejs/npm/manager.go, sdk/nodejs/npm/manager_test.go, sdk/nodejs/npm/npm.go, sdk/nodejs/npm/pnpm.go, sdk/nodejs/npm/testdata/workspace-extended/package.json, sdk/nodejs/npm/testdata/workspace-extended/packages/some-package/package.json, sdk/nodejs/npm/testdata/workspace-extended/project/package.json, sdk/nodejs/npm/workspaces_test.go
Initial support pnpm. Note that this does not support pnpm workspaces yet.
This also does not handle passing the package manager through from `pulumi new`. Once a user manually runs pnpm, creating a pnpm-lock.yaml, we'll detect that and pnpm.
Fixes https://github.com/pulumi/pulumi/issues/15455
=> Use pnpm as package manager if we find a pnpm-lock.yaml file

changelog/pending/20240220--engine--fix-root-and-program-paths-to-always-be-absolute.yaml, pkg/resource/deploy/source_query_test.go, sdk/go/common/resource/plugin/host.go, sdk/go/common/resource/plugin/langruntime.go, tests/smoke_test.go, tests/testdata/relative_plugin_node/.gitignore, tests/testdata/relative_plugin_node/Pulumi.yaml, tests/testdata/relative_plugin_node/component.ts, tests/testdata/relative_plugin_node/index.ts, tests/testdata/relative_plugin_node/package.json, tests/testdata/relative_plugin_node/random.ts, tests/testdata/relative_plugin_node/tsconfig.json
Fixes https://github.com/pulumi/pulumi/issues/15467.
This tightens the restriction on paths passed to `NewProgramInfo`. Previously it allowed relative paths like "./providers/my_provider". That is now an error. This is correct behaviour. The fields of this structure are passed via protobuf and the descriptions for them in the proto spec are that they should always be absolute paths.
Where we build plugin paths we ensure that if they're relative we resolve them to what they are relative to. That is generally _not_ the current working directory so `filepath.Abs` doesn't do the right thing here.
=> Ensure project plugins are absolute paths

changelog/pending/20240223--sdk-nodejs--upgrade-to-atgrpc-grpc-js-1-10-1.yaml, sdk/nodejs/automation/stack.ts, sdk/nodejs/cmd/dynamic-provider/index.ts, sdk/nodejs/package.json, sdk/nodejs/provider/server.ts, sdk/nodejs/tests/runtime/langhost/run.spec.ts, sdk/nodejs/yarn.lock
Fixes https://github.com/pulumi/pulumi/issues/15499
This should be safe, as we are effectively already running 1.10.1. This makes this the new minimum so we can remove the `server.start` calls (the server is started in `server.bindAsync`) that cause deprecation warnings to be printed in Automation API or when using dynamic providers with nodejs.
=> Upgrade to grpc-js 1.10.1 and remove calls to deprecated server.start

changelog/pending/20240223--docs--adds-ability-to-process-docs-without-examples-logic-using-start-pulumicodechooser-markers-in-incoming-schema-descriptions.yaml, pkg/codegen/docs/description.go, pkg/codegen/docs/description_test.go, pkg/codegen/docs/examples.go, pkg/codegen/docs/templates/resource.tmpl, pkg/codegen/docs/test_data/certificate-validation-description-in.md, pkg/codegen/docs/test_data/certificate-validation-description-out.md, pkg/codegen/docs/test_data/lambda-description-in.md, pkg/codegen/docs/test_data/lambda-description-out.md
This pull request depends on corresponding changes in the pulumi-terraform bridge.
The bridge will mark up each code section it finds (not just ones found under an "Example Usage" header) with an HTML comment - currently this will be `` and `` but the name is subject to change.
In this PR, we are adding logic to detect if an incoming Description block has an `{{% examples }}` shortcode markup: if yes, we will process it as before. If no, we will switch to new functionality that relies on documentation with code sections having no short codes, no "Examples Section" logic, and will generate every code section it finds in an incoming schema that is in the Description/Content section of a registry page with a chooser and language choosables.
This work is part of …
=> Add ability to process docs without dedicated Examples logic

changelog/pending/20240209--pkg--adds-simple-vim-keyboard-shortcuts-to-the-live-tree-view-j-k-g-g-ctrl-f-ctrl-b-and-also-wires-up-home-and-end-keys.yaml, pkg/backend/display/internal/terminal/term.go, pkg/backend/display/tree.go, pkg/backend/display/tree_test.go
Updates the terminal support for the tree view in Pulumi CLI
This adds the vim shortcuts :
`j` &ndash; down
`k` &ndash; up
`Ctrl+F` &ndash; page down 
`Ctrl+B` &ndash; page up
`g` &ndash; home
`G` &ndash; end
Also adds Home and End key support
=> Add vim shortcuts and Home and End Keys to terminal

changelog/pending/20240226--ci--use-system_pullrequest_sourcecommitid-for-az-pipeline-on-gh-pr.yaml, sdk/go/common/util/ciutil/az_pipelines.go
Use `SYSTEM_PULLREQUEST_SOURCECOMMITID` when AZ pipelines checks against a Github PR. Fix made based on investigation from @blampe in #15072 
Fixes #15072
=> Use `SYSTEM_PULLREQUEST_SOURCECOMMITID` for AZ pipeline on GH PR

changelog/pending/20240223--sdk-nodejs--replace-deprecated-read-package-tree-with-atnpmcli-arborist.yaml, sdk/nodejs/package.json, sdk/nodejs/runtime/closure/codePaths.ts, sdk/nodejs/tsconfig.json, sdk/nodejs/types/arborist.d.ts, sdk/nodejs/yarn.lock, tests/integration/integration_nodejs_test.go, tests/integration/nodejs/codepaths-workspaces/infra/index.ts, tests/integration/nodejs/codepaths/Pulumi.yaml, tests/integration/nodejs/codepaths/index.ts, tests/integration/nodejs/codepaths/package.json, tests/integration/nodejs/codepaths/tsconfig.json
read-package-tree is deprecated. Additionally it has a dependency that is flagged by security scanners.
Fixes https://github.com/pulumi/pulumi/issues/9129
Ref https://github.com/pulumi/pulumi/issues/12688
=> Replace deprecated read-package-tree with @npmcli/arborist

changelog/pending/20240226--cli-state--pulumi-state-edit-exit-immediatly-when-no-change-was-made.yaml, pkg/cmd/pulumi/state_edit.go
The current behavior of `pulumi state edit` when the edited file is unchanged is to prompt the user to `accept`, `edit`, `reset` or `cancel`. Since the file is unchanged, `accept` and `cancel` do the same thing. `edit` (again) is the same as `reset` which is the same as running the command from scratch.
The feature would be much easier to use if a no-op edit simply exited. If the user wants to edit again, they can just run `!!` to repeat the command.
=> Exit no-op `pulumi state edit`

.github/workflows/ci-dev-release.yml
Currently we release a new dev SDK when nothing changed because the condition here is set incorrectly.  We want to create a new release when the exit code is non-zero, so we need to check for `if ! git diff`.
=> fix diff check for releasing dev SDKs

.github/workflows/on-pr.yml, .github/workflows/on-release.yml, .github/workflows/release-pr.yml, .github/workflows/release.yml, changelog/pending/20240226--pkg--tag-new-pkg-versions-on-a-commit-on-the-main-branch.yaml
Post release, we need to update the changelog (clear out all the pending entries), and update the go.mod in pkg, and also tag the latest version of that.  Currently we create a new PR for that. However since we are using squash merges, and need to do the tagging while creating the PR, we're tagging a commit that doesn't end up on the main branch.  This means the Go tooling doesn't work properly with pkg.  See also https://github.com/pulumi/pulumi/issues/15458.
There is nothing really we are doing with that PR other than merging it (in fact queue-merge is set to true, so it should be queued and merged automatically, but that doesn't seem to work).
Because of that, we can just tag the release, and push it straight to the main branch instead.  This removes one human step from the release …
=> push post-release changelog and go.mod updates straight to master

pkg/codegen/nodejs/gen_test.go, pkg/codegen/nodejs/test.go, sdk/nodejs/cmd/pulumi-language-nodejs/language_test.go, sdk/nodejs/package.json, tests/integration/integration_nodejs_acceptance_test.go, tests/integration/integration_nodejs_test.go
In #15426 we added glob and @types/glob to dependencies, but since glob is not exposed in our public API, @types/glob should be a devDependency.
Fixes #15556
=> Move @types/glob to dev dependencies

.github/workflows/on-pr.yml, .github/workflows/on-release.yml, .github/workflows/release-pr.yml, .github/workflows/release.yml
This PR reverts the change from https://github.com/pulumi/pulumi/pull/15515 because it's currently broken, and even if we fix the problem where it is broken, I'm not sure we can make it work without unchecking the "Do not allow bypassing the above settings" in `master`'s branch protection rules, which I think we do want to keep checked (some more details in #15554).
An additional commit also temporarily disables tagging `pkg/<version>` in the workflow. Instead, that will have to be done manually as part of the release process when the change lands in `master`. As a fast follow, I'd like to see if there's a way we can automate adding the tag after the change lands in master, perhaps if the PR has a certain label or is named a certain way?
I mainly want to do this because it looks like we …
=> Revert "push post-release changelog and go.mod updates straight to master"

tests/integration/integration_python_acceptance_test.go
This test was disabled on MacOS due to what looks like a failure to acquire a plugin.  This probably worked accidentally (and is working accidentally on other platforms) because presumably the plugin gets acquired by another test and is thus available.  We should however not rely on that, end enable plugin acquisition where necessary.  With that we also fix the test on MacOS and can unskip it.
This addresses part of https://github.com/pulumi/pulumi/issues/15240.  Note that I don't think it fixes the flakyness, looking back through the test logs I think I was conflating two separate things here.
=> acquire plugin in python acceptance test

pkg/backend/httpstate/client/api_endpoints.go
Before this change looking at traces per instructions below had a span marked "unknown". The span actually belongs to the batchDecrypt endpoint.
https://www.pulumi.com/docs/support/troubleshooting/#performance
With the changes the span is labelled as you would expect.
=> Label the batchDecrypt endpoint

sdk/go/common/testing/environment.go, tests/smoke_test.go
Should help with issues like https://github.com/pulumi/pulumi/issues/15240, and other cases of test case contamination. 
Run every new `testing.Environment` with a new PULUMI_HOME.
=> Use a new PULUMI_HOME for every test environment

pkg/codegen/schema/loader.go
Not clear why this nil check was ever included. We should use the cache even if a version wasn't given.
=> Remove check for version==nil in PluginLoader

.github/workflows/ci.yml
I keep getting "PR run failed" email notifications even when all the checks in a PR succeeds. It looks like this may be due to the following two errors in the workflow:
It looks like we're getting these errors because `ACCEPTANCE_TEST_MATRIX_WIN` and `ACCEPTANCE_TEST_MATRIX_MACOS` envvars aren't being set for PRs.
https://github.com/pulumi/pulumi/blob/3d45f4f5db247885d50465c9aaca2848da3c9189/.github/workflows/ci.yml#L187-L188
https://github.com/pulumi/pulumi/blob/3d45f4f5db247885d50465c9aaca2848da3c9189/.github/workflows/ci.yml#L204-L205
Which end up feeding into here:
https://github.com/pulumi/pulumi/blob/3d45f4f5db247885d50465c9aaca2848da3c9189/.github/workflows/ci.yml#L362-L363
https://github.com/pulumi/pulumi/blob/3d45f4f5db247885d50465c9aaca2848da3c9189/.github/workflows/ci.yml#L387-L …
=> ci: Fix PR workflow errors

changelog/pending/20240301--pkg-testing--make-programtest-use-a-temporary-pulumi_home-for-each-test.yaml, pkg/testing/integration/command.go, pkg/testing/integration/program.go
Currently program test runs all programs with PULUMI_HOME unset.  This means that if programs run in parallel they share the same directory. E.g. for login this means running in parallel only works if we always log into the same backend, and there is no racyness between tests.
Set PULUMI_HOME to a temp directory, so each program test has its own setup.
Fixes https://github.com/pulumi/pulumi/issues/15240
This complements https://github.com/pulumi/pulumi/pull/15559
=> set PULUMI_HOME in ProgramTests

pkg/backend/display/progress.go, tests/integration/integration_test.go
It is possible for multiple local policy packs to have the same name. When there are policy violation, we currently only show one of the paths for those policy packs (as we consider them the same policy pack because it has the same name).
Display both of the paths in this case to avoid any confusion.  Also sort the names, so the test we have for this is deterministic.
I think in ideal world it would be better to just error out if there are multiple policy packs with the same name, but given this behaviour worked for a long time I wouldn't be surprised if that ends up breaking some use case, so I'd be a bit worried about doing that now.
A possible alternative would be to not consider policy packs with the same name as a single policy pack, but if we name it differently I could imagine …
=> show all paths when we have multipe local policy packs with the same name

cmd/pulumi-test-language/internal_test.go, cmd/pulumi-test-language/l1empty_test.go, cmd/pulumi-test-language/l1main_test.go, cmd/pulumi-test-language/l2destroy_test.go, cmd/pulumi-test-language/l2resourcesimple_test.go, cmd/pulumi-test-language/runtime_options_test.go
Currently conformance tests can't be run in parallel because the engine will internally chdir, and have some global state.  This is tracked in https://github.com/pulumi/pulumi/issues/13945.  This means also the tests testing the pulumi-test-language program can't run in parallel, or they will be flaky.
Make them execute serially and link to the issue mentioned above to de-flake them.
Fixes #15580
=> don't run conformance test tests in parallel

.github/workflows/pr-test-codegen-downstream.yml
This PR adds a prefix to the titles of PRs created in provider repos for downstream tests. It'd make it easier for provider maintainers to recognise test PRs from real upgrades and help with not automatically raising P1 issues on the PR CI failing.
We added a similar change to the bridge: https://github.com/pulumi/pulumi-terraform-bridge/pull/1726
=> Add a title prefix to downstream test PRs

pkg/backend/display/jsonmessage.go, pkg/backend/display/progress.go, pkg/backend/display/tree.go, pkg/backend/display/tree_test.go, pkg/backend/httpstate/state.go
This removes a scenario where events could not be persisted to the cloud because they were waiting on the same event being displayed
~This uses the same buffer size for both the display and persist channels~ [Removed  to make PR a single change]
The primary change, however, is to stop rendering the tree every time a row is updated, instead, theis renders when the display actually happens in the the `frame` call. The renderer instead simply marks itself as dirty in the `rowUpdated`, `tick`, `systemMessage` and `done` methods and relies on the frame being redrawn on a 60Hz timer (the `done` method calls `frame` explicitly). This makes the rowUpdated call exceedingly cheap (it simply marks the treeRenderer as dirty) which allows the ProgressDisplay instance to service the display events …
=> Decouple persist and display events

changelog/pending/20240228--pkg--schema-newpluginloader-now-respects-pulumi_debug_providers-which-enables-pulumi-yaml-programs-to-work-correctly-with-this-feature.yaml, pkg/codegen/schema/loader.go, pkg/codegen/schema/schema_test.go, sdk/go/common/resource/plugin/provider_plugin.go, sdk/go/common/resource/plugin/provider_plugin_test.go
With this change pulumi-yaml can pick up local provider and attach to it from PULUMI_DEBUG_PROVIDERS for the purposes of schema resolution, which enables using non-existent test-only providers. Before the change it would fail hard trying to download it.
=> Schema loader made to respect PULUMI_DEBUG_PROVIDERS

changelog/pending/20240304--cli-new--strip-credentials-and-query-strings-from-template-urls-saved-to-project.yaml, pkg/cmd/pulumi/new.go, pkg/cmd/pulumi/new_test.go
This change strips credentials and query strings from template URLs that are saved in the generated projects from `pulumi new`.
Note: I considered a different approach where we'd only keep templates from the default templates repo or Pulumi AI. However, the implementation ended up being more complex to figure out what was a default template (and not a local file path, for example), and this way other sources are still included to help with code searches and other tools to identify the source of a project.
Fixes #15431
=> [cli/new] Strip sensitive data from template URLs

pkg/backend/display/progress.go
We're doing a sort here, so the output is consistent.  However we sort the policyKeys array, which is no longer used at this point, instead of the policyNames array, which is being displayed just after this point.  Fix this typo.
I noticed this while reading the code for https://github.com/pulumi/pulumi/pull/15582.
=> display/progress: sort the correct array

.github/scripts/get-changelog, Makefile
This is another step to get our changelog more consistent.  Upgrading go-change to the latest version makes it include
https://github.com/pulumi/go-change/pull/25, which means it will suggest the correct imperative form for changelog messages.
Also this tool now lives in the pulumi org.
=> update go-change to the latest version

changelog/pending/20240305--sdk-python--add-support-for-asynchronous-invokes-via-a-new-invoke_async-function.yaml, sdk/python/lib/pulumi/runtime/__init__.py, sdk/python/lib/pulumi/runtime/invoke.py, sdk/python/lib/test/langhost/invoke/__main__.py, sdk/python/lib/test/langhost/invoke/test_invoke.py, sdk/python/lib/test/langhost/invoke_empty_return/__main__.py
This commit adds a new `pulumi.runtime.invoke_async` function that allows calling invokes asynchronously. The initial intended use for this is inside the Kubernetes Python SDK's `yaml.ConfigFile`, `yaml.ConfigGroup`, `helm`, `kustomize`, etc. components to avoid stalls in resource registrations which severely limits parallelism.
I'd love to add some kind of benchmark, perhaps along the lines of the repro in #15462, but we can add that as a fast-follow.
Part of #15462 and #15591
After this is merged and released, we can ship an updated version of the Kubernetes Python SDK that makes use of it.
=> [sdk/python] Add an `invoke_async` function

changelog/pending/20240305--backend-service--make-decrypt-encrypt-network-calls-retryable-to-help-work-around-network-hiccups.yaml, pkg/backend/httpstate/client/client.go
By default our HTTP client retries all GET requests.  However these post requests are also idempotent, as we just expect to encrypt/decrypt a single value, without changing anything on the server side.  Retry them, so network errors won't abort the pulumi program.
There's also some log decryption events that might be retryable, but I'm not sure about them, so I left them alone for now.
Fixes https://github.com/pulumi/pulumi/issues/15236
=> allow retries for encrypt/decrypt API calls

.gitignore, changelog/pending/20240229--sdk-nodejs--add-experimental-support-to-the-nodejs-sdk-for-the-new-transforms-system.yaml, sdk/nodejs/cmd/pulumi-language-nodejs/proxy.go, sdk/nodejs/cmd/run/run.ts, sdk/nodejs/resource.ts, sdk/nodejs/runtime/callbacks.ts, sdk/nodejs/runtime/mocks.ts, sdk/nodejs/runtime/resource.ts, sdk/nodejs/runtime/rpc.ts, sdk/nodejs/runtime/settings.ts, sdk/nodejs/runtime/stack.ts, sdk/nodejs/runtime/state.ts, tests/integration/transforms/nodejs/simple/Pulumi.yaml, tests/integration/transforms/nodejs/simple/index.ts, tests/integration/transforms/nodejs/simple/package.json, tests/integration/transforms/nodejs/simple/random.ts, tests/integration/transforms/transforms_nodejs_test.go
This adds a new experimental feature to the NodeJS SDK to register remote transform functions. These are currently all prefixed 'X' to show they're experimental.
These transform functions will run even for resources created inside MLCs.
=> NodeJS transforms

changelog/pending/20240305--cli--fix-a-panic-when-the-secrets-provider-is-missing-from-the-deployment-snapshot.yaml, pkg/resource/stack/deployment.go, pkg/resource/stack/deployment_test.go
When a serialized deployment doesn't include a secrets provider configuration, but does include ciphertexts, currently we end up with a panic.  Error out earlier if this is the case to avoid the panic.
This fixes the panic seen in https://github.com/pulumi/pulumi/issues/15547 and https://github.com/pulumi/pulumi/issues/14761, but it doesn't quite explain why this is happening in the first place.  I asked for some more info from the users in these issues for that. 
Putting this up as PR anyway in case anyone has any idea of why this could be happening in the first place.  I've tried spelunking through the code, but nothing obvious stood out.  It is possible that these were still v2 snapshots that included no secrets manager, but I would be somewhat surprised if those still existed in the …
=> fix panic on deserializing deployment

sdk/nodejs/runtime/settings.ts
A console log slipped through in https://github.com/pulumi/pulumi/pull/15532
=> Remove stray console.log

changelog/pending/20240222--sdk-nodejs--properly-capture-nodejs-crypto-and-global-crypto-in-node-19.yaml, sdk/nodejs/runtime/closure/parseFunction.ts, sdk/nodejs/tests/runtime/tsClosureCases.ts
Fixes https://github.com/pulumi/pulumi/issues/15479
=> Properly capture nodejs:crypto and global.crypto

changelog/pending/20240307--engine--downgrade-remediate-policy-violations-to-mandatory.yaml, pkg/engine/lifecycletest/analyzer_test.go, pkg/resource/deploy/step_generator.go
Policy violations should not have a remediate enforcement level. The Policy SDK currently downgrades the level from remediate to mandatory for resource policy violations, but isn't currently doing that for stack policies. A change to the Policy SDK is in-progress to do that.
This change applies the same behavior to the engine. If a resource policy still has a violation after running remediations and the level is remediate, "downgrade" the level to mandatory. Similarly, if a stack policy has a violation with a remediate level, downgrade it to mandatory.
This avoids a panic when getting a policy violation from a stack policy and the enforcement level is remediate.
Related: https://github.com/pulumi/pulumi-policy/pull/339
Fixes https://github.com/pulumi/pulumi-policy/issues/332
=> Downgrade remediate policy violations to mandatory

changelog/pending/20240305--programgen-go--fix-optional-primitive-values-being-derefrenced.yaml, pkg/codegen/go/gen_program_expressions.go, tests/testdata/codegen/components-pp/go/exampleComponent.go
Fixes #15524 where the primitive optional types were being derefrenced. It took me a while to figure where the problem was because I couldn't really reproduce the original issue with a new PCL program. The `aws-optionals-pp` test case program in PCL would repro the issue when converted from the CLI via `convert --from pcl` but not from the unit tests even when using the exact same schema 🤔 this was really weird. That said, the fix turned out straightforward and it does fix the same issue in generated component resources.
=> [program-gen/go] Fix optional primitive values being derefrenced

changelog/pending/20240306--programgen-dotnet-go-python--fix-panic-when-generating-programs-for-mlc-packages-where-they-include-type-references-to-external-packages.yaml, pkg/codegen/dotnet/gen_program.go, pkg/codegen/dotnet/test.go, pkg/codegen/go/gen_program.go, pkg/codegen/nodejs/test.go, pkg/codegen/python/gen_program.go, pkg/codegen/testing/test/helpers.go, pkg/codegen/testing/test/program_driver.go, pkg/codegen/testing/utils/host.go, tests/testdata/codegen/aws-static-website-0.4.0.json, tests/testdata/codegen/aws-static-website-pp/aws-static-website.pp, tests/testdata/codegen/aws-static-website-pp/dotnet/aws-static-website.cs, tests/testdata/codegen/aws-static-website-pp/go/aws-static-website.go, tests/testdata/codegen/aws-static-website-pp/nodejs/aws-static-website.ts, tests/testdata/codegen/aws-static-website-pp/python/aws-static-website.py
For an MLC package such as `aws-static-website`, it has some types which are referenced from the `aws` package. Program-gen assumes packages are inferred from resources and invokes, not types which caused panics in Go (#15597), dotnet and python (https://github.com/pulumi/pulumi-converter-constructor-syntax/issues/2)
This PR fixes those panics. In Go the panic was due to using package name instead of the package reference from the imported type. In dotnet and python was due to assuming no external type references. Now we generate nice code for all these languages. 
That said, there is still an issue of resolving imports for the packages of these external types. It works in Go, TypeScript doesn't need it but dotnet and python do. That is why the latter are added in `SkipCompile` in the …
=> [program-gen] Fix panic when generating programs for MLC packages using external types

pkg/cmd/pulumi/preview.go, pkg/cmd/pulumi/up.go
The --config option also saves the given configuration to the stack config file.  Document that to avoid confusion for the user.
=> document --config option during preview

pkg/backend/httpstate/snapshot_test.go
These tests are currently flaky when run in parallel.  Since the proper fix is a bit more involved, and we really want to turn of rerunning tests on failures, make them not run in parallel for the time being.  We'll keep https://github.com/pulumi/pulumi/issues/15461 open to remind us to fix this properly and get them running in parallel again.
=> mark snapshot tests as non-parallel

sdk/nodejs/package.json, sdk/nodejs/yarn.lock
In https://github.com/pulumi/pulumi/pull/15617 we added picomatch 4.0.1 as dependency, but `fdir` wants 3.0.1 https://github.com/thecodrr/fdir/blob/3c608bd6c87d29534dd7b37a828db43ffcbf9ab3/package.json#L81
Everything works with 4.0.1, but in some situations it can result in a warning being logged during `npm install`.
=> Use picomatch 3.0.1 as peer dependency for fdir

changelog/pending/20240312--cli-state--add-yes-to-state-upgrade.yaml, pkg/cmd/pulumi/state_upgrade.go, pkg/cmd/pulumi/state_upgrade_test.go
Fixes https://github.com/pulumi/pulumi/issues/15646
Small change to add `--yes` to `state upgrade` allowing it to be used in non-interactive environments.
=> Add --yes to state upgrade

sdk/nodejs/automation/server.ts
Currently when there are errors we just say "one or more errors occurred", without anymore explanation.  Actually print the error which will help when debugging issues here.
This would have helped debug https://github.com/pulumi/pulumi/issues/15239.
=> improve error message when gRPC fails

cmd/pulumi-test-language/tests.go
The second number when creating a slice is non-inclusive, so the current sort.Slice function here didn't actually sort anything, since we were just passing in a single element.  Pass in the right slice.
Fixes #15657
=> l2-destroy test: sort the correct part of the slice

pkg/cmd/pulumi/import_test.go
Test that if a component resource tries to define an ID we error.
=> Add a missing test for the import system

changelog/pending/20240312--cli--make-pulumi-dn-an-alias-for-pulumi-destroy.yaml, pkg/cmd/pulumi/destroy.go
We already support "down" as an alias for "destroy", which has nice symmetry of "up" => "down". This change goes further by adding "dn" as another alias for "destroy". "dn" is "up" rotated 180 degrees :-)
=> Make "pulumi dn" an alias for "pulumi destroy"

changelog/pending/20240313--sdkgen-python--replace-on-changes-values-should-be-camelcased-not-kebab_cased.yaml, pkg/codegen/python/gen.go, tests/testdata/codegen/replace-on-change/docs/norecursive/_index.md, tests/testdata/codegen/replace-on-change/dotnet/NoRecursive.cs, tests/testdata/codegen/replace-on-change/go/example/noRecursive.go, tests/testdata/codegen/replace-on-change/nodejs/noRecursive.ts, tests/testdata/codegen/replace-on-change/python/pulumi_example/no_recursive.py, tests/testdata/codegen/replace-on-change/schema.json
When replaceOnChanges is set in the schema for a property with a multi-word name, currently, Python SDK generation incorrectly puts its Python name into replace_on_changes.
This is wrong, because these property names are passed to the engine and they should be engine names (i.e. schema names). All other languages (Node.js, .NET, Go) do this correctly.
This PR adds a test case and fixes the Python generation to use the same naming as all other SDKs.
Fixes #15665
=> [sdkgen/python] Replace-on-changes values should be camelCased

pkg/engine/lifecycletest/pulumi_test.go, pkg/operations/operations_aws.go, pkg/operations/operations_cloud_aws.go, pkg/operations/operations_gcp.go, sdk/go/common/resource/urn.go, sdk/go/common/resource/urn/urn.go, sdk/go/common/resource/urn/urn_test.go, sdk/go/common/tokens/stack_type.go
This change follows on https://github.com/pulumi/pulumi/pull/15157, to allow https://github.com/pulumi/pulumi/pull/15145 to be imported by `resource`. This is the last module import cycle change necessary for `resource` to import `property` (as in https://github.com/pulumi/pulumi/pull/15145).
Like https://github.com/pulumi/pulumi/pull/15157, this change is *100% backwards* compatible.
=> Move resource.URN to urn.URN

pkg/codegen/docs/gen.go, pkg/codegen/docs/utils.go, tests/testdata/codegen/embedded-crd-types/docs/component/_index.md, tests/testdata/codegen/enum-reference/docs/myModule/iamresource/_index.md, tests/testdata/codegen/external-enum/docs/component/_index.md, tests/testdata/codegen/external-resource-schema/docs/argfunction/_index.md, tests/testdata/codegen/external-resource-schema/docs/cat/_index.md, tests/testdata/codegen/external-resource-schema/docs/component/_index.md, tests/testdata/codegen/external-resource-schema/docs/workload/_index.md, tests/testdata/codegen/hyphen-url/docs/registrygeoreplication/_index.md, tests/testdata/codegen/methods-return-plain-resource/docs/configurer/_index.md, tests/testdata/codegen/plain-schema-gh6957/docs/staticpage/_index.md, tests/testdata/codegen/simple-methods-schema/docs/foo/_index.md
intermediary fix for: https://github.com/pulumi/pulumi/issues/12765
For types that are defined in an external package, we do not render a description and its links are broken. This is an intermediary solution until we can render out nested types defined in external packages on the page or derive the resource page in the external package that contains the type definition. This PR identifies if a property type is externally defined and places a message indicating the type is defined externally in the description field.
=> Update descriptions for property types defined in an external package

changelog/pending/20240315--auto-go--support-for-remote-deployment-executor-image.yaml, pkg/cmd/pulumi/util_remote.go, sdk/go/auto/local_workspace.go, sdk/go/auto/remote_workspace.go, sdk/go/auto/remote_workspace_test.go, sdk/go/auto/stack.go, sdk/go/common/apitype/deployments.go
Adds Go Automation API support for specifying custom executor images for remote deployments.
Part of: https://github.com/pulumi/pulumi/issues/15693
=> [auto/go] Support for remote deployment executor image

sdk/go/pulumi/context.go, sdk/go/pulumi/transform.go, tests/integration/transforms/go/simple/main.go
Transform functions are async grpc calls. Make that clear by having a `context.Context` on the function parameters. This also allows users to gracefully handle cancellation if wanted, and will probably be useful for tracing/logging.
=> Add context.Context to transform functions

changelog/pending/20240313--engine--test-and-fix-the-engine-filling-in-property-dependencies-to-provider-constructs.yaml, pkg/engine/lifecycletest/pulumi_test.go, pkg/resource/deploy/source_eval.go
Similar to https://github.com/pulumi/pulumi/pull/15450 but for RegisterResource.
=> Ensure PropertyDependencies are filled in

pkg/engine/lifecycletest/pulumi_test.go, pkg/resource/deploy/source_eval.go
We're doing more and more manipulation of these URN slices. We should just make these sets to make it simpler to manipulate them without worrying about order or duplicates.
=> Use sets for dependencies inside the engine

changelog/pending/20240315--cli-display--fix-superfluous-newlines-being-written-during-updates.yaml, pkg/backend/display/jsonmessage.go, pkg/backend/display/progress.go, pkg/backend/display/tree.go, pkg/backend/display/tree_test.go
This reverts commit ff7a7b4975356e92f843ba3d2270b6b6a9ac2329.
Fixes https://github.com/pulumi/pulumi/issues/15668.
=> Revert "Decouple persist and display events (#15529)"

changelog/pending/20240317--cli-plugin--fix-installing-local-language-plugins-on-windows.yaml, sdk/go/common/workspace/plugins.go
=> Append .exe when installing local language plugins

sdk/nodejs/tests/automation/localWorkspace.spec.ts
This test was flaky in https://github.com/pulumi/pulumi/issues/15239. However since it only flaked occasionally, we ignored this for a while, even though a test failure here actually indicated a deeper problem in grpc-js, which could even lead to stacks being completely destroyed (https://github.com/pulumi/pulumi/issues/15390).
The flaky test and the stacks being destroyed had different symptoms, but it was the same root cause of a bug in grpc-js.  Unfortunately the latter is hard to reproduce in a test, since it only happens very infrequently.
However this test being flaky indicates deeper problems.  Increase the amount of stacks we run through in parallel here to make it more likely that this test fails when there are actual errors, making it harder for us to ignore, and hopefully …
=> make parallel test more likely to fail when there are problems

.github/workflows/ci-run-test.yml
Before every CI job we currently check whether the Go cache is primed, and if not compile all the tests to prime it.  However that check is currently wrong.  `steps.setup-go.outputs.cache-hit` is a boolean variable, however we compare it against a string 'true'.   Since we are comparing for inequality, this check is always true, so we are always priming the cache, even if it is already primed.  
Fix this check, so we can only prime the cache when it needs to be and don't waste extra CI time to prime the cache when it already might be.
h/t again to @iamricard for noticing that we are taking a long time to prime the cache in some cases.
=> properly check if the cache is primed

changelog/pending/20240318--engine--fix-a-panic-when-updating-provider-version-in-a-run-using-target.yaml, pkg/engine/lifecycletest/target_test.go, pkg/resource/deploy/step_generator.go
Fixes https://github.com/pulumi/pulumi/issues/15704.
When doing a targeted run the source evaluator isn't aware of targets but it is responsible for registering default providers. As such on getting a resource event with a new provider version (e.g 1.0 -> 2.0) it will send of a registration for the new version it's seen, which as a default provider the step generator will accept and add to state (this is probably ok).
However when the step generator runs for the resource using this provider it will see it's not targetted and ignore its new goal state just reusing its old state. This old state will be referring to the old version of the provider (e.g "default_aws_1_0_0" rather than "default_aws_2_0_0"), which was causing a panic in the step generator when trying to build the overall stack …
=> Fix panic when changing untargetted provider versions

changelog/pending/20240315--engine--transform-functions-are-sent-output-values-with-property-dependency-information.yaml, pkg/engine/lifecycletest/transformation_test.go, pkg/resource/deploy/source_eval.go
This engine change is necessary for correct dependency tracking of properties through transform functions.
Unlike other parts of the runtime/provider/engine interface transform functions do not have a property dependencies map sent or returned. Transforms rely entirely on the dependency arrays in output values for their dependency tracking.
This change takes the property dependency map and upgrades all the input properties to be output values tracking those same dependencies (if a property doesn't have any dependencies it doesn't need to be upgraded to an output value).
This upgrade is only done if we're using transform functions, there's currently no need to do this unless we're using transforms.
After running the transforms we downgrade the output values back to plain/secret/computed …
=> Send output values to transforms for dependency tracking

changelog/pending/20240320--sdk-go--fix-lookup-of-plugin-and-program-dependencies-when-using-go-workspaces.yaml, sdk/go/pulumi-language-go/main.go, sdk/go/pulumi-language-go/main_test.go, sdk/go/pulumi-language-go/testdata/sample/prog-gowork/README, sdk/go/pulumi-language-go/testdata/sample/prog-gowork/go.work, sdk/go/pulumi-language-go/testdata/sample/prog-gowork/other/go.mod, sdk/go/pulumi-language-go/testdata/sample/prog-gowork/other/other.go, sdk/go/pulumi-language-go/testdata/sample/prog-gowork/prog/Pulumi.yaml, sdk/go/pulumi-language-go/testdata/sample/prog-gowork/prog/go.mod, sdk/go/pulumi-language-go/testdata/sample/prog-gowork/prog/main.go
Fixes https://github.com/pulumi/pulumi/issues/15741.
`go list -m` returns all modules in a workspace if inside a Go workspace. We only need the one module found in the Pulumi program directory (or above it). So we set `GOWORK=off` before calling `go list -m`.
=> Fix lookup module deps with go.work files

pkg/engine/deployment.go, pkg/resource/deploy/deployment.go, pkg/resource/deploy/step_generator.go, pkg/resource/deploy/step_generator_test.go, sdk/go/common/workspace/project.go
This option is always true these days, and we don't expect to set it false for anything.  Remove the flag for a bit of code cleanup.
=> Remove trustDependencies option

pkg/codegen/testing/test/helpers.go
We're currently failing tests because of a nuget error.  It looks like Pulumi.Awsx has started depending on the 3.60 dotnet SDK version, but we're still using 3.59 here.  It looks like this ends up in test as nuget complains about "error NU1605: Warning As Error: Detected package downgrade: Pulumi from 3.60.0 to 3.59.0. Reference the package directly from the project to select a different version."
Not sure if this is the actual fix, not knowing much about dotnet, but it looks like it might be the problem.
Right now the merge queue fails consistently because of this error.
=> codegen testing: use latest pulumi dotnet version

changelog/pending/20240320--engine--handle-that-assets-and-archives-can-be-returned-from-providers-without-content.yaml, pkg/backend/display/object_diff.go, sdk/go/common/resource/archive/archive.go, sdk/go/common/resource/asset/asset.go, sdk/go/common/resource/asset_test.go
Fixes https://github.com/pulumi/pulumi/issues/15729.
This fixes Assets and Archives to allow four states, as opposed to the three that https://github.com/pulumi/pulumi/pull/14007 had enforced.
An asset can either be Text, Path, Uri, or none. That is `IsText`, `IsPath`, and `IsURI` can all return false. Similarly for archives except with Assets instead of Text.
This happens when a provider returns an Assert (or Archive) with a hash value set, but no other contents. 
The Asset and Archive objects have been updated to handle this case, and a number of places in the CLI that asserted that one of IsText/IsPath/IsURI were true have been fixed up to handle the case of all three being false.
=> Asset and Archive can have missing contents

pkg/engine/lifecycletest/delete_before_replace_test.go, pkg/go.mod
Fixes https://github.com/pulumi/pulumi/issues/15749.
=> Fix flaky TestPropertyDependenciesAdapter

changelog/pending/20240319--engine--add-a-continue-on-error-flag-to-pulumi-destroy.yaml, pkg/backend/backend.go, pkg/cmd/pulumi/destroy.go, pkg/engine/deployment.go, pkg/engine/lifecycletest/pulumi_test.go, pkg/engine/update.go, pkg/resource/deploy/deployment.go, pkg/resource/deploy/deployment_executor.go, pkg/resource/deploy/step_executor.go, pkg/resource/deploy/step_generator.go
Implement a `--continue-on-error` flag for `pulumi destroy`.  This makes sure we continue processing destroys even if errors occur.  We will only continue for resources which do not depend on the failed resource, to make sure we always have a valid snapshot available, and to not leave any orphaned resources behind.
Resources that fail to destroy will still continue to be managed by pulumi, and the process ends in an error to indicate to the user that there were problems and the destroy didn't succeed cleanly.
The output will continue to be the same as for failed destroys, except we now may succeed in destroying more resources than before.
/cc https://github.com/pulumi/pulumi/issues/3304
=> destroy: implement --continue-on-error

scripts/reversion.js, scripts/set-version.py, sdk/nodejs/version.ts
Fixes https://github.com/pulumi/pulumi/issues/15756.
Fix the set-version script to also set the .ts file with the version correctly.
Fix reversion to replace the currently expected hardcoded version with the given dynamic version.
=> Fix version scripts

tests/integration/construct_component_configure_provider/python/requirements.txt, tests/integration/integration_python_acceptance_test.go
Update TLS library to a more recent version that doesn't have the old "install the plugin as part of setup.py" logic.
Then enable the engine to do the plugin download for this test by disabling `PULUMI_DISABLE_AUTOMATIC_PLUGIN_ACQUISITION`. Should make the test less flaky as the engine is managing the download and can retry, but at least makes the error much more clear if it does fail.
=> Make TestConstructComponentConfigureProviderPython less flaky

changelog/pending/20240323--programgen-dotnet-go--fixes-emited-code-for-object-expressions-assigned-to-properties-of-type-any.yaml, pkg/codegen/dotnet/gen_program_expressions.go, pkg/codegen/dotnet/test.go, pkg/codegen/go/gen_program_expressions.go, pkg/codegen/nodejs/test.go, pkg/codegen/testing/test/helpers.go, pkg/codegen/testing/test/program_driver.go, pkg/codegen/testing/utils/host.go, tests/testdata/codegen/using-object-as-input-for-any-pp/dotnet/using-object-as-input-for-any.cs, tests/testdata/codegen/using-object-as-input-for-any-pp/go/using-object-as-input-for-any.go, tests/testdata/codegen/using-object-as-input-for-any-pp/nodejs/using-object-as-input-for-any.ts, tests/testdata/codegen/using-object-as-input-for-any-pp/python/using-object-as-input-for-any.py, tests/testdata/codegen/using-object-as-input-for-any-pp/using-object-as-input-for-any.pp
Fixes #15769 by specifically handling object expressions that are annotated as `Any` and emitting the correct code.
- In case of Go, expression `X` is emitted as `pulumi.Any(X)` where the type name here is `map[string]interface{}`. 
- In case of C#, we generate `Dictionary<string, object?>` expressions (similar to what we do inside `toJSON` calls)
- Updates the test aws-native schema from 0.13.0 to 0.99.0
=> [program-gen/go,dotnet] Fixes emited code for object expressions assigned to properties of type Any

pkg/resource/stack/deployment.go, pkg/resource/stack/secrets.go
Was looking at secret code and saw this was an easy fix up of a `context.TODO()` call.
=> Add `context.Context` to `cachingCrypter.encryptSecret`

pkg/backend/diy/backend_legacy_test.go, pkg/backend/diy/backend_test.go, pkg/backend/diy/state.go, pkg/backend/httpstate/snapshot.go, pkg/backend/httpstate/snapshot_test.go, pkg/cmd/pulumi/stack_change_secrets_provider.go, pkg/cmd/pulumi/stack_change_secrets_provider_test.go, pkg/cmd/pulumi/stack_export.go, pkg/cmd/pulumi/stack_import.go, pkg/cmd/pulumi/state.go, pkg/cmd/pulumi/state_edit_encoder.go, pkg/resource/deploy/snapshot.go, pkg/resource/stack/checkpoint.go, pkg/resource/stack/deployment.go, tests/stack_test.go
There were a number of places where we passed a `Snapshot` and a `secret.Manager` as arguments to a method, where if the `Manger` was nil we'd fall back to the `Snapshot.SecretManager` (which could also be nil).
Turns out in all but one place this was always passed as nil or just as directly the snapshot's `SecretManager` field.
The one place it differed was in `pkg/cmd/pulumi/stack_change_secrets_provider.go` where we're changing the secret manager, but it's fine to just set the snapshot's `SecretManager` field to the new manager.
=> Always use the snapshot secret manager

pkg/go.mod
We have resolved this issue and upgraded gocolud.dev in the meantime, so we can remove this comment now.
=> Remove outdated comment in go.mod

changelog/pending/20240325--sdk-nodejs--export-automation-tag-tagmap-type.yaml, sdk/nodejs/automation/cmd.ts, sdk/nodejs/automation/index.ts, sdk/nodejs/automation/localWorkspace.ts, sdk/nodejs/automation/workspace.ts, sdk/nodejs/resource.ts, sdk/nodejs/runtime/mocks.ts, sdk/nodejs/runtime/stack.ts, sdk/nodejs/stackReference.ts
Noticed a couple warnings when building the docs using typedoc.
- Fix some typedoc `@param` tags
- Export automation.tag.TagMap type
Ref: https://github.com/pulumi/docs/pull/10964
=> Export automation.tag.TagMap type & @param tag fixes

changelog/pending/20240324--programgen-dotnet--fixed-generated-code-for-a-list-of-resources-used-in-resource-option-dependson.yaml, pkg/codegen/dotnet/gen_program.go, pkg/codegen/testing/test/program_driver.go, tests/testdata/codegen/aws-fargate-pp/dotnet/aws-fargate.cs, tests/testdata/codegen/aws-resource-options-4.26-pp/dotnet/aws-resource-options-4.26.cs, tests/testdata/codegen/aws-resource-options-5.16.2-pp/dotnet/aws-resource-options-5.16.2.cs, tests/testdata/codegen/depends-on-array-pp/depends-on-array.pp, tests/testdata/codegen/depends-on-array-pp/dotnet/depends-on-array.cs, tests/testdata/codegen/depends-on-array-pp/go/depends-on-array.go, tests/testdata/codegen/depends-on-array-pp/nodejs/depends-on-array.ts, tests/testdata/codegen/depends-on-array-pp/python/depends-on-array.py
Fixes #14462 by special casing how we handle `dependsOn` and generating `DependsOn = { ... }` instead of `DependsOn = new[] { ... }`
=> [program-gen/csharp] Fixes generated code for a list of resources used in resource option DependsOn

changelog/pending/20240320--sdk-python--improve-the-error-message-when-depends_on-is-passed-objects-of-the-wrong-type.yaml, sdk/python/lib/pulumi/resource.py, sdk/python/lib/pulumi/runtime/mocks.py, sdk/python/lib/pulumi/runtime/rpc.py, sdk/python/lib/test/test_resource.py
Fixes https://github.com/pulumi/pulumi/issues/13917.
Improves the error message for async type errors to match the error message users would get for sync type errors.
This also fixes the mock.test function to clear the RPCManager between tests so an exception in one test doesn't cause other tests to fail.
=> Type check depends_on is only passed Resource instances

.gitignore
csdevkit seems to really want to make this directory and I will accidentally `git add` eventually if not ignored.
=> Ignore .mono directory

changelog/pending/20240325--engine--fix-the-engine-trying-to-delete-a-protected-resource-caught-in-a-replace-chain.yaml, pkg/engine/lifecycletest/delete_before_replace_test.go, pkg/resource/deploy/step_generator.go
Fixes https://github.com/pulumi/pulumi/issues/15763.
When doing a replace chain we need to check if the resources implicated for deletion in the chain are actually ok to delete (i.e. they don't have `protect` set). This change fixes the step generator to check that when building the delete chain, and adds a test for it as well.
Sadly because of the nature of the system you have to `state unprotect` these resources if you actually want them replaced, you can't just change `protect` in the resource options in the program. This is because at the point we're processing the "to be replaced" resource we've only got the old state for the implicated resource because we won't have got it's new goal state yet because it depends on the resource we're currently processing.
=> Check for protect in replace chains

.github/workflows/pr-test-codegen-downstream.yml
This helps the providers team not go get P1 in our inbox when the downstream test fail by distinguishing tests from "production" runs such as upgrading to a known-good version of the bridge . 
=> Do not open P1s on upgrade tests

changelog/pending/20240326--sdk-python--the-python-sdk-only-waits-for-pending-outputs-not-all-pending-asyncio-tasks.yaml, sdk/python/lib/pulumi/output.py, sdk/python/lib/pulumi/runtime/mocks.py, sdk/python/lib/pulumi/runtime/settings.py, sdk/python/lib/pulumi/runtime/stack.py, sdk/python/lib/test/test_output.py, tests/integration/integration_python_test.go, tests/integration/python_await/asyncio_tasks/.gitignore, tests/integration/python_await/asyncio_tasks/Pulumi.yaml, tests/integration/python_await/asyncio_tasks/__main__.py
Fixes https://github.com/pulumi/pulumi/issues/6762.
=> Add a test and fix that we don't wait for tasks, just outputs

changelog/pending/20240325--auto-go-nodejs-python--make-sure-to-read-complete-lines-before-trying-to-deserialize-them-as-engine-events.yaml, sdk/go.mod, sdk/go.sum, sdk/go/auto/stack.go, sdk/go/auto/stack_test.go, sdk/nodejs/automation/stack.ts, sdk/python/lib/pulumi/automation/_stack.py, sdk/python/lib/test/automation/test_stack.py, tests/go.mod, tests/go.sum
When tailing the event log in automation API we currently have nothing that makes sure we read only complete lines.  This means if the OS happens to flush an incomplete line for whatever reason (or the Go JSON encoder does, which we're using to write these lines), we might read a line that is incompletely written, and thus will fail to JSON decode it.
Since the JSON encoder always writes a newline at the end of each string, we can also make sure that the line we read ends with a newline and otherwise wait for the rest of the line to be written.
The library we use in Go provides a convenient setting for this, while in python and nodejs we need to add some code to do this ourselves.
Fixes https://github.com/pulumi/pulumi/issues/15235
Fixes https://github.com/pulumi/pulumi/issues/15652
Fixes …
=> automation: only read complete lines before trying to deserialize

scripts/go-test.py
Reverts pulumi/pulumi#15234 to disable the `--rerun-fails` option again.  We've done quite a bit of work for flaky tests (there's only some rare cases left after https://github.com/pulumi/pulumi/pull/15642 gets merged), so we should be able to disable this option again now, and have it as a forcing function to keep tests non-flaky.
=> Revert "Revert "Disable `--rerun-fails` in tests""

.github/workflows/release.yml
Currently we run update-homebrew-tap in parallel to the other jobs. That means it could complete before we updated the blobs on S3, and before the version number on pulumi.com/pulumi-version is updated.
That in turn can make the CI fail, raising a P1.
Since all this happens within a pretty sort time, the easiest way to work around this is to just do the homebrew tap update last, after pulumi.com/pulumi-version is updated.  This delays the homebrew tap update, but only by a short amount of time.
Fixes https://github.com/pulumi/homebrew-tap/issues/24
=> only update homebrew tap after pulumi-version is updated

changelog/pending/20240322--sdk-nodejs--make-function-serialization-work-with-typescript-4-and-5.yaml, sdk/nodejs/Makefile, sdk/nodejs/runtime/closure/rewriteSuper.ts, sdk/nodejs/tests/runtime/closure-integration-tests.ts, sdk/nodejs/tests/runtime/testdata/closure-tests/cases/151-Capture-config-created-on-the-outside/snapshot.~3.8.3.txt, sdk/nodejs/tests/runtime/testdata/closure-tests/cases/152-Capture-config-created-on-the-inside/snapshot.txt, sdk/nodejs/tests/runtime/testdata/closure-tests/cases/152-Capture-config-created-on-the-inside/snapshot.~3.8.3.txt, sdk/nodejs/tests/runtime/testdata/closure-tests/cases/156-Deconstructing-async-function/snapshot.^5.2.0.txt, sdk/nodejs/tests/runtime/testdata/closure-tests/cases/158-Deconstructing-async-arrow-function/snapshot.^5.2.0.txt, sdk/nodejs/tests/runtime/testdata/closure-tests/test.ts, sdk/nodejs/tsconfig.json
Builds on top of https://github.com/pulumi/pulumi/pull/15753
Fixes https://github.com/pulumi/pulumi/issues/15735
There are a couple breaking changes in the typescript API that we use in `sdk/nodejs/runtime/closure/rewriteSuper.ts`. This PR adds a shim that is used to bridge the differences and versions the snapshots where needed.
This does not make typescript a peer dependency yet. Instead the tests force a specific version to be used via [yarn resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/).
=> Make function serialization work on typescript 4 and 5

changelog/pending/20240327--auto-go-python--use-the-full-path-when-running-pulumi-from-a-custom-cli-install.yaml, sdk/go/auto/cmd.go, sdk/go/auto/cmd_test.go, sdk/python/lib/pulumi/automation/_cmd.py
Fixes https://github.com/pulumi/pulumi/issues/15796
Turns out nodejs already uses the [full command name](https://github.com/pulumi/pulumi/blob/bc4a9ad59ba23cef43c27355bb2e2b82d664a12a/sdk/nodejs/automation/cmd.ts#L176).
Fixed for python and go.
=> Use the full path when running pulumi from a custom CLI install

pkg/cmd/pulumi/import.go, pkg/codegen/docs/templates/resource.tmpl, tests/testdata/codegen/azure-native-nested-types/docs/documentdb/sqlresourcesqlcontainer/_index.md
Adds a link to the Import docs from the API docs (to help answer questions about how import works, where to look for identifiers, etc.) and adds a line break to the `import --help` CLI output. (Sorry, my bad!)
Fixes https://github.com/pulumi/registry/issues/3039.
=> Add a link to the Import documentation from API docs pages

changelog/pending/20240326--sdk-python--adds-typechecker-runtime-option-to-the-python-language-host.yaml, sdk/python/cmd/pulumi-language-python/main.go, tests/integration/integration_python_acceptance_test.go, tests/integration/python/mypy/.gitignore, tests/integration/python/mypy/Pulumi.yaml, tests/integration/python/mypy/__main__.py, tests/integration/python/mypy/requirements.txt, tests/integration/python/pyright/.gitignore, tests/integration/python/pyright/Pulumi.yaml, tests/integration/python/pyright/__main__.py, tests/integration/python/pyright/requirements.txt
Fixes https://github.com/pulumi/pulumi/issues/15724.
This adds a new runtime option to the python language host `typeChecker` which can be set to either "mypy" or "pyright". If it's set the language host will run the mypy/pyright module before running the program.
=> Add 'typechecker' option to python runtime

.github/workflows/ci-dev-release.yml
In the on-push job, we are already on `master`.  Therefore diff
`master...HEAD` will never result in any changes.  Also we need to
deepen the fetch here so we have an actual previous commit to compare
with.
In addition to that, it looks like this actually results in a string
output not a boolean, so we need to check against that, or the
condition will always evaluate to true.
I'm actually still not quite sure this is doing the right thing, but I'll keep an eye on it.
=> fix checking for changes in on push job 

.github/workflows/ci-build-binaries.yml, .github/workflows/ci-info.yml, .github/workflows/ci-lint.yml, .github/workflows/ci-test-docs-generation.yml, .github/workflows/ci.yml, .github/workflows/cron-direct-build.yml, .github/workflows/on-pr-changelog.yml, .github/workflows/pr-test-codegen-downstream.yml, .github/workflows/release-pr.yml
Upgrade all workflows to the latest version of actions/setup-go (which uses node 20 runtime).
=> ci: Use the latest version of actions/setup-go

.github/workflows/ci-build-sdks.yml, .github/workflows/ci-lint.yml, .github/workflows/ci-run-test.yml, .github/workflows/ci-test-docs-generation.yml, .github/workflows/pr-test-codegen-downstream.yml, .github/workflows/release.yml
Upgrade all workflows to the latest version of actions/setup-python (which uses node 20 runtime).
=> ci: Use the latest version of actions/setup-python

.github/workflows/ci-build-sdks.yml, .github/workflows/ci-dev-release.yml, .github/workflows/ci-lint.yml, .github/workflows/ci-run-test.yml, .github/workflows/ci-test-docs-generation.yml, .github/workflows/pr-test-codegen-downstream.yml, .github/workflows/release.yml
Upgrade all workflows to the latest version of actions/setup-node (which uses node 20 runtime).
=> ci: Use the latest version of actions/setup-node

.github/workflows/ci-run-test.yml, .github/workflows/on-push.yml, .github/workflows/pr-test-codegen-downstream.yml, .github/workflows/release.yml
Upgrade all workflows to the latest version of jaxxstorm/action-install-gh-release (which uses node 20 runtime).
=> ci: Use latest version of jaxxstorm/action-install-gh-release

.github/workflows/ci-run-test.yml
As of v3 gradle/gradle-build-action has been superseded by gradle/actions/setup-gradle. Move to the latest version of that, which runs on node 20.
For more details, see https://github.com/gradle/gradle-build-action/blob/main/README.md
=> ci: Replace gradle-build-action with actions/setup-gradle

.github/workflows/on-pr-changelog.yml, .github/workflows/pr-test-acceptance-on-dispatch.yml, .github/workflows/pr-test-docs-generation-on-dispatch.yml
Upgrade all workflows to the latest version of peter-evans/create-or-update-comment (which uses node 20 runtime).
=> ci: Use latest version of peter-evans/create-or-update-comment

.github/workflows/ci-lint.yml
Upgrade all workflows to the latest version of golangci/golangci-lint-action (which uses node 20 runtime).
=> ci: Use latest version of golangci/golangci-lint-action

.github/workflows/ci-run-test.yml, .github/workflows/pr-test-codegen-downstream.yml
Upgrade all workflows to the latest version of actions/setup-java (which uses node 20 runtime).
=> ci: Use latest version of actions/setup-java

.github/workflows/ci-build-binaries.yml, .github/workflows/ci-build-sdks.yml, .github/workflows/ci-dev-release.yml, .github/workflows/ci-info.yml, .github/workflows/ci-lint.yml, .github/workflows/ci-prepare-release.yml, .github/workflows/ci-run-test.yml, .github/workflows/ci-test-docs-generation.yml, .github/workflows/ci.yml, .github/workflows/cron-direct-build.yml, .github/workflows/on-pr-changelog.yml, .github/workflows/on-push.yml, .github/workflows/on-release.yml, .github/workflows/pr-test-codegen-downstream.yml, .github/workflows/rebase.yml, .github/workflows/release-homebrew-tap.yml, .github/workflows/release-pr.yml, .github/workflows/release.yml, .github/workflows/sign.yml, .github/workflows/trigger-release-docs-event.yml
Upgrade all workflows to the latest version of actions/checkout (which uses node 20 runtime).
=> ci: Use latest version of actions/checkout

.github/workflows/ci.yml
Upgrade all workflows to the latest version of actions/cache (which uses node 20 runtime).
=> ci: Use latest version of actions/cache

.github/workflows/on-pr.yml
Upgrade all workflows to the latest version of dorny/paths-filter (which uses node 20 runtime).
=> ci: Use latest version of dorny/paths-filter

.github/workflows/on-pr-changelog.yml
Upgrade all workflows to the latest version of peter-evans/find-comment (which uses node 20 runtime).
=> ci: Use latest version of peter-evans/find-comment

changelog/pending/20240329--sdk-nodejs--update-builtin-module-list-for-function-serialization.yaml, sdk/nodejs/runtime/closure/createClosure.ts, sdk/nodejs/tests/runtime/testdata/closure-tests/cases/171-fs-promises/index.ts, sdk/nodejs/tests/runtime/testdata/closure-tests/cases/171-fs-promises/snapshot.txt, sdk/nodejs/tests/runtime/testdata/closure-tests/cases/171-fs-promises/snapshot.~3.8.3.txt
Update the list of node modules detected as builtin during function serialisation.
This helps with some of the cases in https://github.com/pulumi/pulumi/issues/5294 (notably trying to use `fs/promises`).
=> Update builtin module list for function serialization

changelog/pending/20240403--auto-go--avoid-flakyness-when-reading-the-event-log-from-pulumi-commands.yaml, sdk/go/auto/stack.go
The library we're using unfortunately has a race condition that's especially worse when using polling to check for new changes of the file.  Avoid this racyness by sleeping for a bit for now, but really this should be fixed upstream ideally.
I opened a upstream issue for this in https://github.com/nxadm/tail/issues/67.  I think we should merge this in the meantime, as it makes this work, even though it's very hacky. 
I tested this in https://github.com/pulumi/pulumi/pull/15853, where I could no longer reproduce the failure we've seen before.
Fixes https://github.com/pulumi/pulumi/issues/15659
Fixes https://github.com/pulumi/pulumi/issues/15235
=> avoid racyness from the polling library

changelog/pending/20240403--cli--support-always-fully-qualifying-stack-names-in-cli-output.yaml, pkg/backend/diy/backend.go, pkg/backend/diy/backend_test.go, pkg/backend/httpstate/backend_test.go, pkg/backend/httpstate/stack.go, pkg/cmd/pulumi/pulumi.go, sdk/go/common/util/cmdutil/stack.go
This commit adds the `--fully-qualify-stack-names` (or `-Q` for short) global command-line argument, which when supplied will always print stack names in the fully-qualified form of `organization/project/stack`. Fixes #11081.
=> Support always qualifying stack names (#11081)

pkg/backend/httpstate/backend.go
Found by @Frassle
We were dereferencing the response pointer before checking the returned error, resulting in a nil pointer dereference.
Fixes https://github.com/pulumi/pulumi/issues/15860
=> Fix nil pointer dereference in pulumi new --ai

changelog/pending/20240405--sdk-python--improve-types-of-getters-in-python-sdk.yaml, sdk/python/lib/pulumi/_types.py
This commit strengthens the type of the `@pulumi.getter` decorator so that tools like Pyright infer the type of the decorated function correctly. Prior to this, decorated properties could be inferred as having the type `Any`. This is particularly troublesome when using methods such as `apply`:
```python
x = random.RandomString("x", ...)
y = x.result.apply(lambda value: f"y-{value}")
```
Here, `x.result` having the type `Any` means that `value` will end up being `Unknown`, providing no useful type information inside the lambda. With this commit, `result` will correctly be inferred as having the type `Output[str]`, and thus `value` will be typed as `str`. Fixes #12557.
=> Type functions decorated by `@pulumi.getter`

sdk/go/pulumi/generate/templates/types_builtins_test.go.template, sdk/go/pulumi/types_builtins_test.go
Likewise `require.NoError` instead of `require.Nil`, and `assert.Error` rather than `assert.NotNil`.
The error variants of these functions print the errors nicer for test failures using `Error()` rather than `GoString()`.
=> Use `assert.NoError` rather than `assert.Nil`

changelog/pending/20240408--sdk-nodejs--handle-serialization-of-aliases-for-well-known-native-functions.yaml, sdk/nodejs/runtime/closure/createClosure.ts, sdk/nodejs/tests/runtime/testdata/closure-tests/cases/172-alias-builtins/index.ts, sdk/nodejs/tests/runtime/testdata/closure-tests/cases/172-alias-builtins/snapshot.txt
Emit expressions for aliased native functions https://github.com/pulumi/pulumi/issues/5294#issuecomment-2031404191
=> Handle serialization of aliases for well known native functions

pkg/codegen/nodejs/test.go
Whenever yarn runs it holds a global lock, preventing any other yarn process from running.  Since our tests potentially try to run multiple yarn processes in parallel, this reduces the potential for parallelism in the tests dramatically.
By using `npm install` instead of `yarn install`, and runnig `tsc` directly instead of using `yarn run`, the time to run this test goes from >500s to ~90s when trying to run `nodejs/gen_program_test/batch1` locally.
Similar improvements can be expected from the other batches.  This should also help speed up CI, since this is part of the long tail of long running tests.
This is another thing I noticed during the hackathon (running all tests locally with bazel the difference was even more extreme).
=> use yarn less in nodejs codegen tests

changelog/pending/20240409--programgen-dotnet--removes-trailing-whitespace-from-emitted-dependson-resource-option-expressions.yaml, pkg/codegen/dotnet/gen_program.go, tests/testdata/codegen/aws-fargate-pp/dotnet/aws-fargate.cs, tests/testdata/codegen/aws-resource-options-4.26-pp/dotnet/aws-resource-options-4.26.cs, tests/testdata/codegen/aws-resource-options-5.16.2-pp/dotnet/aws-resource-options-5.16.2.cs, tests/testdata/codegen/depends-on-array-pp/dotnet/depends-on-array.cs
Fixes #15852 by removing the trailing whitespace from each expression emitted in the `DependsOn` array
=> [csharp/program-gen] Removes trailing whitespace from emitted DependsOn resource option expressions

changelog/pending/20240409--sdk-go--fix-provider-and-providers-options-in-go-transform-functions.yaml, sdk/go/pulumi/context.go
Fixes https://github.com/pulumi/pulumi/issues/15881.
=> Fix marshalling Provider and Providers options from Go transforms

changelog/pending/20240409--sdk-nodejs--correctly-serialise-functions-whose-code-would-make-use-of-reserved-identifiers.yaml, sdk/nodejs/runtime/closure/serializeClosure.ts, sdk/nodejs/tests/runtime/testdata/closure-tests/cases/175-reserved-identifier-shadowing/index.js, sdk/nodejs/tests/runtime/testdata/closure-tests/cases/175-reserved-identifier-shadowing/node_modules/lib.js, sdk/nodejs/tests/runtime/testdata/closure-tests/cases/175-reserved-identifier-shadowing/snapshot.txt, tests/integration/dynamic/nodejs-reserved-identifier-shadowing/Pulumi.yaml, tests/integration/dynamic/nodejs-reserved-identifier-shadowing/index.ts, tests/integration/dynamic/nodejs-reserved-identifier-shadowing/package.json, tests/integration/integration_nodejs_test.go
This commit addresses part of #11942, in which we fail to serialise closures whose code would use reserved identifiers like `exports`. This is due to a change we made where module imports are hoisted to avoid importing the same module multiple times. Previously, code adopted a strategy of passing all dependencies using a `with` statement, viz.:
```typescript
function x() {
return (function () {
with({ fooBarBaz: require("foo/bar/baz"), ... }) {
// Use of fooBarBaz
}
}).apply(...)
}
function y() {
return (function () {
with({ fooBarBaz: require("foo/bar/baz"), ... }) {
// Use of fooBarBaz
}
}).apply(...)
}
```
This was changed to remove the duplicate imports, yielding code like:
```typescript
const fooBarBaz = require("foo/bar/baz")
function x() {
return (function () {
with({ ... }) {
// …
```
=> Support serialising reserved NodeJS identifiers

changelog/pending/20240410--sdk-nodejs--allow-apply-to-have-unknown-values-during-updates.yaml, sdk/nodejs/output.ts, sdk/nodejs/tests/output.spec.ts, sdk/python/lib/pulumi/output.py, sdk/python/lib/test/test_next_serialize.py
Currently during updates we try to make the values known during apply, even if they are marked unknown.  This results in knows that should really still be unknown.
Note that this behaviour is currently encoded in tests, which also needed to change.
=> allow unknowns in apply during update

pkg/resource/deploy/source_eval_test.go
The ordering of this array isn't guaranteed, so use ElementsMatch instead of Equal to compare to avoid the flakyness.
I noticed this test being flaky while working on bazel, but also noticed it in CI logs, here: https://github.com/pulumi/pulumi/actions/runs/8646652290/job/23706586759?pr=15906
=> Make sure TestCall test doesn't flake

changelog/pending/20240411--cli--add-no-plugins-and-no-dependencies-to-pulumi-install.yaml, pkg/cmd/pulumi/install.go
Raised on Slack. User would like to be able to use `pulumi install` but just for dependency installation, skipping the plugins. Makes sense to also support the opposite while here, i.e. just plugins.
=> Add --no-plugins and --no-dependencies to `pulumi install`

changelog/pending/20240411--cli--fix-some-commands-that-didnt-respect-disable-integrity-checking.yaml, pkg/backend/snapshot.go, pkg/cmd/pulumi/stack_import.go, pkg/cmd/pulumi/state.go, pkg/cmd/pulumi/state_edit.go
This would have helped with https://github.com/pulumi/pulumi/issues/15831 as the `destroy` would have been able to run instead of err'ing on the first save because of the already broken snapshot.
=> Add some missing checks for DisableIntegrityChecking

.github/workflows/ci-build-binaries.yml, .github/workflows/ci-dev-release.yml, .github/workflows/ci.yml, .goreleaser.yml, changelog/pending/20240409--cli--dev-cli-is-now-built-with-race-detection-turned-on.yaml, pkg/backend/httpstate/state.go, pkg/cmd/pulumi/import.go, pkg/resource/deploy/import.go, pkg/resource/deploy/snapshot.go, pkg/resource/deploy/snapshot_test.go, pkg/resource/deploy/state_builder.go, pkg/resource/deploy/step.go, pkg/resource/deploy/step_executor.go, pkg/resource/stack/deployment.go, scripts/go-wrapper.sh, sdk/go/common/resource/resource_state.go
Combining #15120 and #15124 and including fixes to allow tests to pass.
Enable race detection in the binary we're using for integration tests. This will allow us to catch more data races before they get into any release. This does mean the binary we're using for integration tests is slightly different from the binary we're releasing, however that's already the case as we're running a binary with coverage enabled for them. Later we rebuild the binary we're actually releasing.
This requires us to fix the race between snapshot code, display code, and the step executor. I've done that by adding a lock to the State struct. This does not feel great, but it's a quick way to fix this and get race detection running (and unblocks #15871 which was also hitting the race detector because it started …
=> Run integration tests with race detection

pkg/backend/inmemoryPersister.go, pkg/backend/snapshot.go, pkg/engine/combinedManager.go, pkg/engine/lifecycletest/delete_before_replace_test.go, pkg/engine/lifecycletest/refresh_test.go, pkg/engine/lifecycletest/test_plan.go, pkg/resource/deploy/step.go, pkg/resource/deploy/step_executor.go
This tests the production snapshot manager against the journalling snapshot system in engine tests. This should ensure that both systems produce similar (we ignore exact resource ordering, as long as both are valid) results.
=> Test SnapshotManager and Journal in engine tests

changelog/pending/20240412--auto-go-nodejs-python--add-support-for-continue-on-error-parameter-in-the-automation-api.yaml, sdk/go/auto/optdestroy/optdestroy.go, sdk/go/auto/stack.go, sdk/nodejs/automation/stack.ts, sdk/python/lib/pulumi/automation/_stack.py
Automation API Destroy in Node/Python/Go now has `--continue-on-error`
Resolves #15919 (pending .NET)
.NET is interesting because we probably want to add it to `UpdateOptions` once `up` has it and not to `DestroyOptions` (that inherit from `UpdateOptions`). I'll probably skip it for now.
=> Add support for continue-on-error parameter of the destroy command to the Automation API

pkg/secrets/cloud/aws_test.go, pkg/secrets/cloud/gcp_test.go
Add tests with fixed keys for GCP and AWS, similar to what we added for Azure in https://github.com/pulumi/pulumi/pull/15187.
Fixes https://github.com/pulumi/pulumi/issues/15414
=> Add fixed key tests for GCP and AWS key management

tests/testprovider/.gitignore, tests/testprovider/echo.go, tests/testprovider/fails_on_create.go, tests/testprovider/fails_on_delete.go, tests/testprovider/main.go, tests/testprovider/random.go
This PR enhances the testprovider to have a Pulumi schema, e.g. to be able to use it with Pulumi YAML.
Related to https://github.com/pulumi/pulumi/issues/15788
=> test: schema support for testprovider

pkg/backend/diy/backend.go, pkg/backend/httpstate/backend.go
This stops the CLI warning about `error: Snapshot write failed: failed to save snapshot: [403] Updating the checkpoint is not permitted for preview operations.` on every preview operation.
=> Fix warning about Snapshot write failed for previews

pkg/backend/display/events.go, pkg/backend/display/json.go, pkg/backend/diy/backend_legacy_test.go, pkg/backend/diy/backend_test.go, pkg/backend/httpstate/snapshot.go, pkg/backend/httpstate/snapshot_test.go, pkg/cmd/pulumi/stack_change_secrets_provider.go, pkg/cmd/pulumi/stack_change_secrets_provider_test.go, pkg/cmd/pulumi/stack_export.go, pkg/cmd/pulumi/stack_import.go, pkg/cmd/pulumi/stack_output.go, pkg/cmd/pulumi/state.go, pkg/cmd/pulumi/state_edit_encoder.go, pkg/importer/hcl2_test.go, pkg/importer/language_test.go, pkg/resource/stack/checkpoint.go, pkg/resource/stack/deployment.go, pkg/resource/stack/deployment_test.go, pkg/resource/stack/plan.go, pkg/resource/stack/secrets_test.go, tests/stack_test.go
SerializePropertyValue needed a `context.Context` object to pass to the `config.Encrypter`. It was using `context.TODO()`, this change instead accepts a context on the parameters and lifts that up to SerializeProperties, SerializeResource, SerializeOperation, and SerializeDeployment.
There were a few call sites for those methods that already had a context on hand, and they now pass that context. The other calls sites now use `context.TODO()`, we should continue to iterate in this area to ensure everywhere that needs a context has one passed in.
=> Lift context parameter to SerializeDeployment/Resource/Operations/Properties

changelog/pending/20240415--backend-diy--fix-race-condition-when-listing-stacks.yaml, pkg/backend/diy/backend.go
When listing stacks, we currently try to get all the stacks from the backend, and then get the checkpoint to for each stack to show the summary.
However there's a race between listing the stacks and getting the checkpoints, so the checkpoint may be missing by the time we get to that part of the code.
Unfortunately the errors we're getting form getCheckpoint are not structured, so we can't tell if we got a 404 from the cloud here, so the next best option we have is re-checking whether the stack still exists.
This is another attempt at fixing https://github.com/pulumi/pulumi/issues/15658.
=> Fix race condition when listing stacks

changelog/pending/20240402--engine--resource-transforms-on-component-resources-now-apply-to-children-correctly.yaml, pkg/engine/lifecycletest/transformation_test.go, pkg/resource/deploy/source_eval.go
Fixes https://github.com/pulumi/pulumi/issues/15843.
This tracks parent information separate from Goal information (as that was only generated and saved for custom, not component, resources).
We also need to keep track of the transform list between the first RegisterResource starting a remote component construction and the remote component _actually_ registering itself. This means we save the transform list correctly once the component is registered inside the remote process allowing other resource registrations in the remote process to see that saved transform list. 
If we just wait till the Construct call is done then none of the inner children pick up the transform list.
=> Save component resources as parents

changelog/pending/20240415--sdk-go--allow-unknowns-during-pulumi-up.yaml, sdk/go/pulumi/context.go
Currently we reject all unknowns during `pulumi up`.  However we are soon going to allow them to come through via `up --continue-on-error`, and thus should no longer error out when we have them.
This is a similar preparatory PR to https://github.com/pulumi/pulumi/pull/15898, except that Go deals with the unknowns a little different, so we don't need to treat apply specially, but the marshalling.
=> go: allow unknowns during update

sdk/nodejs/tests/sxs_ts_test/package~3.8.3.json
With the release of v3.113.0, `@pulumi/pulumi` has an optional peer dependency on `typescript`. If trying to use `tsc` directly, you must explicitly add `typescript` as a dependency in your `package.json`. We're calling `tsc` for this test, so we need to add an explicit dependency.
Note: This could be a `devDependency`, but the `package.json` files for the other test cases list the `typescript` dependency as a regular `dependency` (see [this](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/tests/sxs_ts_test/package%5E3.json) and [this](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/tests/sxs_ts_test/package%5E4.json)), so doing the same here.
Fixes https://github.com/pulumi/pulumi/issues/15949
=> Add missing `typescript` dependency to sxs_ts_test

sdk/go/common/util/fsutil/copy.go
Bazel builds create symlinks of each file.  We still want to copy these into test directories etc., so allow CopyFile to do that.  This is a prerequisite for getting pulumi-yaml to build in Bazel.
We hide this with an environment variable, as that's easy to set during Bazel builds, but does not affect this function during regular usage.
=> Allow CopyFile to copy symlinks

pkg/codegen/testing/test/helpers.go
Since we released a new SDK we should also update the version here. Otherwise tests might end up failing as soon as a provider we're using in the tests depends on the new dotnet SDK version.
Saw https://github.com/pulumi/pulumi/pull/15955 and realized we ran into issues with this last time.
=> update dotnet SDK version in codegen tests

.github/ISSUE_TEMPLATE/flaky_test.yaml
I keep reporting these, but it's kind of annoying to always add the right labels and have them kind of consistent.  Add an issue template to make reporting these flakes a little easier, which hopefully makes people more likely to open issues, and thus track the flakes.
=> add issue template for flaky tests

pkg/cmd/pulumi/new.go
When running `pulumi new` and choosing a template, it says _“Please choose a template (51/227 shown)”_ which is probably correct (haven’t counted), but then when I type to narrow it down, the number of shown templates never changes.
This PR removes the number of templates shown from the message so it just says how many there are in total.
I did look into making the number of shown templates update correctly but couldn't find a hook in the Survey package that allows this. I also thought it's not worth much effort since [Survey is deprecated in favor of Bubbletea](https://github.com/AlecAivazis/survey?tab=readme-ov-file).
- [ x] I have run `make tidy` to update any new dependencies
- [ x] I have run `make lint` to verify my code passes the lint check
_Unfortunately, I couldn't find …
=> Replace non-updating filtered template counter

changelog/pending/20240418--backend--fix-incorrect-dependency-sorting-in-snapshot.yaml, pkg/backend/snapshot.go
Just use slices.Sort instead of sort.Slice.
=> [backend] Fix dependency sorting in mustWrite

pkg/cmd/pulumi/package_gen_sdk.go
Some schemas can't contain the correct version as they need to be committed. Therefore allow the option to set the version in the schema at the point of generation.
- There appears to be no existing tests for this command.
- No changelog required as this is still a hidden command for internal use.
=> Allow setting version during generation

changelog/pending/20240417--engine--dont-bail-at-preview-when-a-protected-resource-needs-replacement.yaml, pkg/engine/lifecycletest/pulumi_test.go, pkg/resource/deploy/step_generator.go
Don't bail at preview when a protected resource needs replacement, just error. This makes sure that users can see the actual diff that causes the replacement.
Fixes #5027
Before:
```
$ pulumi preview
Type                                     Name                  Plan     Info
pulumi:pulumi:Stack                      azure-native-ts-dev2           
└─ azure-native:resources:ResourceGroup  rg                             1 error
Diagnostics:
azure-native:resources:ResourceGroup (rg):
error: unable to replace resource "urn:pulumi:dev2::azure-native-ts::azure-native:resources:ResourceGroup::rg"
as it is currently marked for protection. To unprotect the resource, remove the `protect` flag from the resource in your Pulumi program and run `pulumi up`
$ pulumi preview --diff
pulumi:pulumi:Stack: …
```
=> Don't bail at preview when a protected resource needs replacement

changelog/pending/20240418--backend-diy-service--elide-state-file-writes-for-unchanged-component-outputs.yaml, pkg/backend/snapshot.go, pkg/backend/snapshot_test.go
These changes elide checkpoint writes for RegisterResourceOutputs steps if the associated resource's outputs have not changed. This can eliminate unnecessary snapshot writes for stacks with large numbers of component resources whose outputs do not change.
=> [snapshot] Elide writes for RRO with no changes

pkg/cmd/pulumi/package_gen_sdk.go, pkg/codegen/dotnet/gen.go, pkg/codegen/dotnet/gen_program.go, pkg/codegen/dotnet/gen_test.go
This isn't quite enough for dotnet conformance to pass on everything yet, but it's a start and gets the L1 programs passing.
=> Fixes to pass dotnet conformance

pkg/backend/httpstate/backend.go
Replace the link that we print to point to stack references docs. The old link is for `pulumi.io` that isn't used anywhere else,
and also I think it goes to a wrong page and non-existing anchor.
[The page](https://github.com/pulumi/pulumi-hugo/blob/master/themes/default/content/docs/using-pulumi/stack-outputs-and-references/index.md?plain=1) doesn't seem to have a short link defined.
=> Change the link to Stack References docs

changelog/pending/20240419--cli-about--add-plugin-kind-to-the-about-output.yaml, pkg/cmd/pulumi/about.go
Fixes https://github.com/pulumi/pulumi/issues/15992.
=> Add plugin kind to about output

.github/workflows/ci.yml, build/common.mk, changelog/pending/20240419--engine--remove-locks-between-snapshot-and-executor-systems.yaml, pkg/backend/inmemoryPersister.go, pkg/cmd/pulumi/import.go, pkg/engine/lifecycletest/refresh_test.go, pkg/resource/deploy/import.go, pkg/resource/deploy/snapshot.go, pkg/resource/deploy/snapshot_test.go, pkg/resource/deploy/state_builder.go, pkg/resource/deploy/step.go, pkg/resource/deploy/step_executor.go, pkg/resource/stack/deployment.go, sdk/go/common/resource/resource_state.go
This reverts the sdk and pkg changes from commit 655b76d030cc76708fd8e21dc69916518fa926f7.
It also disables race detection from all builds and tests.
Fixes https://github.com/pulumi/pulumi/issues/15991.
=> Revert "Run integration tests and dev builds with race detection"

pkg/backend/httpstate/snapshot_test.go
These tests can all exhibit the same issue as described in https://github.com/pulumi/pulumi/issues/15461.  Temporarily disable parallelism for them.
=> disable parallelism for all snapshot tests

pkg/cmd/pulumi/config.go, pkg/cmd/pulumi/config_test.go, pkg/cmd/pulumi/destroy.go, pkg/cmd/pulumi/import.go, pkg/cmd/pulumi/logs.go, pkg/cmd/pulumi/preview.go, pkg/cmd/pulumi/refresh.go, pkg/cmd/pulumi/up.go, pkg/cmd/pulumi/watch.go, sdk/go/common/workspace/config.go, sdk/go/common/workspace/project_test.go
`mergeConfig` uses `Crypter.Encrypt` that needs a context and was using `context.TODO()`. This lifts that to a context parameter and fixes up all call sites.
=> Lift context parameter for ApplyProjectConfig

.github/workflows/ci-dev-release.yml
Currently the sign workflow only depends `build-release`.  However it also needs the SDKs being built, so add a dependency on that.
This usually works because the release builds takes longer, so it just works, but we should make the dependencies explicit.
Fixes https://github.com/pulumi/pulumi/issues/16016
=> fix dev release dependencies

pkg/secrets/cloud/gcp_test.go
We're doing the same thing for Azure and AWS, and it's convenient if these tests are skipped locally when the right credentials aren't set. This won't have any effect in CI.
=> skip GCP tests if credentials are not set

changelog/pending/20240416--auto-go-nodejs-python--add-support-for-the-continue-on-error-parameter-of-the-up-command-to-the-automation-api.yaml, sdk/go/auto/optup/optup.go, sdk/go/auto/stack.go, sdk/nodejs/automation/stack.ts, sdk/python/lib/pulumi/automation/_stack.py
Users are already able to use --continue-on-error for destroy in the automation API.  Implement the same for `up` as well.
This should only be merged after https://github.com/pulumi/pulumi/pull/15740 is.  (Note that this still includes the commits from there, I will rebase once that PR is merged, hence this is only a draft PR for now)
=> Implement --continue-on-error for up in Automation API

changelog/pending/20240419--sdk-nodejs--fix-a-race-condition-that-could-cause-the-nodejs-runtime-to-terminate-before-finishing-all-work.yaml, sdk/nodejs/runtime/resource.ts, tests/integration/transforms/nodejs/single/Pulumi.yaml, tests/integration/transforms/nodejs/single/index.ts, tests/integration/transforms/nodejs/single/package.json, tests/integration/transforms/nodejs/single/random.ts, tests/integration/transforms/transforms_nodejs_test.go
Fixes https://github.com/pulumi/pulumi/issues/15973.
Ensures that the `rpcDone` promise covers the whole async operation atomically.
=> Ensure NodeJS SDK awaits full logical operations

changelog/pending/20240422--sdk-python--fix-an-exception-when-setting-providers-resource-option-with-a-dict.yaml, sdk/python/lib/pulumi/resource.py, sdk/python/lib/pulumi/runtime/_callbacks.py, tests/integration/transforms/go/simple/main.go, tests/integration/transforms/go/simple/random.go, tests/integration/transforms/nodejs/simple/index.ts, tests/integration/transforms/nodejs/simple/random.ts, tests/integration/transforms/python/simple/__main__.py, tests/integration/transforms/python/simple/random_.py, tests/integration/transforms/transforms_test.go, tests/testprovider/component.go, tests/testprovider/main.go
Fixes https://github.com/pulumi/pulumi/issues/15984.
The bug was actually caused by a longstanding mistake in `_collapse_providers` that didn't iterate the providers correctly if it was passed as a `dict`. But worth having this test in full to sanity check the other languages as well.
=> Test setting and changing providers on component resources via transforms

changelog/pending/20240423--sdk-python--workaround-lazy-module-loading-regression.yaml, sdk/python/lib/pulumi/_utils.py, sdk/python/lib/test/data/lazy_import_test/__init__.py, sdk/python/lib/test/data/lazy_import_test/y.py, sdk/python/lib/test/test_utils.py
A regression was introduced in Python 3.11.9 and 3.12.3 that breaks lazy loaded `config` modules in generated Pulumi provider Python SDKs. It's unclear if this is going to be addressed in subsequent patch releases of Python, so we workaround the problem by using a copy of the Python stdlib's `_LazyModule` and `LazyLoader` classes that don't have the regression, as suggested by the Python maintainers.
Fixes #15882
=> [sdk/python] Workaround lazy module regression

pkg/engine/deployment.go
Remove the Chdir we currently do in the engine.  This probably was
required at one point, but it no longer is.
The engine itself doesn't do anything with the CWD.  At the time the
deployment is running all the data it needs has already been read, and
all it does at this point is communicated with the language plugin and
the providers.
Those providers are already started with the correct CWD passed in to
its execution (see https://github.com/pulumi/pulumi/blob/f1f4d223f4ad275f7ade1e34b6229931cf7636ac/sdk/go/common/resource/plugin/plugin.go#L377).
And as these subprocesses are executed as binaries, they are
unaffected by the Chdir anyway.  Remove the Chdir, as it unlocks
further improvements, especially in tests.
If this fails in some manner, it should be pretty obvious, as the program …
=> remove chdir

cmd/pulumi-test-language/internal_test.go, cmd/pulumi-test-language/l1empty_test.go, cmd/pulumi-test-language/l1main_test.go, cmd/pulumi-test-language/l2continue_on_error_test.go, cmd/pulumi-test-language/l2destroy_test.go, cmd/pulumi-test-language/l2resourcesimple_test.go, cmd/pulumi-test-language/runtime_options_test.go
Thanks to @tgummerer merging https://github.com/pulumi/pulumi/pull/15607 it looks like these tests are now safe to run in parallel.
=> Run pulumi-test-language tests in parallel

changelog/pending/20240426--auto-python--ensure-async-context-is-not-shared-between-multiple-programs.yaml, sdk/python/lib/pulumi/automation/_server.py, sdk/python/lib/pulumi/automation/_stack.py, sdk/python/lib/pulumi/runtime/settings.py
Looks like this should help with some async context tracking for python. We make a fresh context for running the Automation API program and so don't need to reset globals on exit.
We also fix `configure` to set the context variables rather than overwriting the `SETTINGS` object itself which is just a plain global.
=> Use a fresh context for automation api runs

changelog/pending/20240426--cli-display--fix-output-of-the-diff-display-making-sure-it-shows-diffs-from-refreshes.yaml, pkg/backend/display/display.go, pkg/resource/deploy/step.go
When displaying diff events, we currently try to hide non-logical replacement steps unless we specifically enable showing them.  However we currently do that for all non-logical operations, regardless whether they are replacement steps or not.
In particular a RefreshStep is non-logical, but it's also not a replacement step.  We still want to show them during the diff because their output can be important.  Especially if the user just requested a diff it doesn't make sense to hide the diff from them at the same time.
The intention here is to only hide replacement steps, so do that.
The full diff with the display tests is here: https://gist.github.com/tgummerer/fcd012f13669a9cdc39530cde7770260  It's unedited, so it includes some flakyness which isn't interesting.
I looked it over, and I …
=> display: only hide replacement steps in diff

changelog/pending/20240425--sdk-python--fix-a-memory-leak-in-tracking-outputs.yaml, sdk/python/lib/pulumi/output.py, sdk/python/lib/pulumi/runtime/settings.py, sdk/python/lib/pulumi/runtime/stack.py, tests/integration/integration_python_test.go, tests/integration/python_await/output_leak/.gitignore, tests/integration/python_await/output_leak/Pulumi.yaml, tests/integration/python_await/output_leak/__main__.py
Fixes https://github.com/pulumi/pulumi/issues/16055.
https://github.com/pulumi/pulumi/pull/15744 added precise output tracking to the python runtime, so that we can error correctly on any output that raises an exception, and don't wait for all async tasks that are running which could be unrelated to the pulumi program.
Unfortunately that change had a memory leak where it tracked all outputs for the entire run of the program. Not an issue for our small programs in the tests but problematic when a program ends up making thousands of resources with tens of thousands of output values.
This cleans the outputs up from the tracking list as they complete successfully.
=> Cleanup output futures list as they complete

cmd/pulumi-test-language/interface.go, sdk/nodejs/cmd/pulumi-language-nodejs/language_test.go
Had to make a fix in the test runner to not do sdk-gen in parallel, but otherwise this was a fairly simple change to the node tests.
=> Run NodeJS conformance tests in parallel

pkg/backend/display/diff.go, pkg/backend/display/events.go
In some cases we only display full seconds, particularly when rendering the summary event, and when converting the engine event for use in the API.  However we are currently not consistent with that, rounding up in the display code and rounding down when converting the engine event.
It probably doesn't matter what exactly we are doing here, but for writing display snapshot tests it does.  Let's split the difference here, and always round up, so we never give the impression that the operation took no time.
It doesn't look like Pulumi Cloud shows this at all, so it probably doesn't matter for users, and we could just round up for everyone as well.  I don't have strong opinions about that.
=> be consistent in the way we round seconds

sdk/python/lib/test/langhost/invoke_types/outputs.py, sdk/python/lib/test/langhost/types/__main__.py, sdk/python/lib/test/test_next_serialize.py, sdk/python/lib/test/test_resource.py, sdk/python/lib/test/test_translate_output_properties.py, sdk/python/lib/test/test_types_input_type.py, sdk/python/lib/test/test_types_input_type_types.py, sdk/python/lib/test/test_types_output_type.py, sdk/python/lib/test/test_types_resource_types.py, sdk/python/lib/test/test_utils.py
This fixes up a load of '[un]expected return statement' errors in the tests. Mostly property getters which I've filled in with `pulumi.get` but some of the tests were explictly checking things worked when the getter was an empty method body.
=> Start mypy linting lib/test

changelog/pending/20240426--auto-go-nodejs-python--add-support-for-import-file-option-on-preview-with-automation-api.yaml, pkg/cmd/pulumi/preview.go, sdk/go/auto/optpreview/optpreview.go, sdk/go/auto/stack.go, sdk/nodejs/automation/stack.ts, sdk/python/lib/pulumi/automation/_stack.py
=> add support for --import-file when using the Automation API

tests/smoke_test.go
This test is currently broken (probably because of an upstream provider change).  Skip it temporarily so we can keep working on pulumi/pulumi.  This should be addressed as part of https://github.com/pulumi/pulumi/issues/16086.
=> temporarily skip TestLanguageNewSmoke for java

changelog/pending/20240430--backend-diy-service--promote-snapshot-closure-errors-from-diagnostics-to-actual-errors.yaml, pkg/backend/diy/backend.go, pkg/backend/httpstate/backend.go
When we finish an operation and close the snapshot manager, the snapshot manager may perform a final write if there are unflushed changes (e.g. refresh changes whose writes were elided at the time). Things may go wrong at this point -- if something is wrong with the snapshot, the integrity check following this write could fail; if a write error occurs, pieces of the snapshot may be missing. In these cases, we really don't want to swallow the error or report it as "just" a diagnostic, because it's a real problem that will almost certainly rear its head on the next Pulumi invocation when we attempt (and fail) to read the snapshot (or worse, operate with an incomplete one). This commit changes the existing flow to report all snapshot close errors as bonafide failures, even if the actual …
=> Report snapshot write errors as actual errors

changelog/pending/20240410--cli-engine--fixes-15564-expect-no-changes-now-causes-pulumi-cli-to-fail-if-the-only-changes-are-output-changes.yaml, pkg/backend/display/progress.go, pkg/backend/httpstate/snapshot_test.go, pkg/cmd/pulumi/stack_history.go, pkg/engine/lifecycletest/alias_test.go, pkg/engine/lifecycletest/analyzer_test.go, pkg/engine/lifecycletest/delete_before_replace_test.go, pkg/engine/lifecycletest/golang_sdk_test.go, pkg/engine/lifecycletest/import_test.go, pkg/engine/lifecycletest/pending_delete_test.go, pkg/engine/lifecycletest/provider_test.go, pkg/engine/lifecycletest/pulumi_test.go, pkg/engine/lifecycletest/refresh_test.go, pkg/engine/lifecycletest/target_test.go, pkg/engine/lifecycletest/test_plan.go, pkg/engine/update.go, pkg/resource/deploy/step.go, tests/integration/integration_test.go
This adds a pseudo op `OpOutputChange` to the set of changes that are recorded in `display.ResourceChanges` to count the number of output changes, this is then included in the check used to evaluate the `--expect-no-changes` flag
When resource outputs are registered, they are checked against their previous value using existing functionality, the total count of changes is then added
The internal capability is validated with an engine test, the cli is validated using an integration test
This will break user workflows that depend on the previous behavior
Fixes #15564
=> The `--expect-no-changes` flag checks for output diffs

changelog/pending/20240430--cli-display--avoid-showing-a-diff-when-the-provider-returns-diff_none.yaml, pkg/backend/display/diff.go, pkg/backend/display/rows.go, pkg/backend/display/testdata/not-truncated/template-body.json.stdout.txt, pkg/backend/display/testdata/not-truncated/up-2.json.stdout.txt, pkg/backend/display/testdata/not-truncated/up-4.json.stdout.txt, pkg/backend/display/testdata/not-truncated/up-5.json.interactive-100x80-cooked.stdout.txt, pkg/backend/display/testdata/not-truncated/up-5.json.interactive-100x80.stdout.txt, pkg/backend/display/testdata/not-truncated/up-5.json.interactive-200x80-cooked.stdout.txt, pkg/backend/display/testdata/not-truncated/up-5.json.interactive-200x80.stdout.txt, pkg/backend/display/testdata/not-truncated/up-5.json.interactive-80x24-cooked.stdout.txt, pkg/backend/display/testdata/not-truncated/up-5.json.interactive-80x24.stdout.txt, pkg/backend/display/testdata/not-truncated/up-5.json.non-interactive.stdout.txt, pkg/backend/display/testdata/not-truncated/up-5.json.stdout.txt, pkg/backend/display/testdata/not-truncated/up.json.interactive-100x80-cooked.stdout.txt, pkg/backend/display/testdata/not-truncated/up.json.interactive-100x80.stdout.txt, pkg/backend/display/testdata/not-truncated/up.json.interactive-200x80-cooked.stdout.txt, pkg/backend/display/testdata/not-truncated/up.json.interactive-200x80.stdout.txt, pkg/backend/display/testdata/not-truncated/up.json.interactive-80x24-cooked.stdout.txt, pkg/backend/display/testdata/not-truncated/up.json.interactive-80x24.stdout.txt, pkg/backend/display/testdata/not-truncated/up.json.non-interactive.stdout.txt, pkg/backend/display/testdata/not-truncated/up.json.stdout.txt, pkg/backend/display/testdata/not-truncated/webserver-userdata.json.stdout.txt, pkg/backend/display/testdata/truncated/up-truncate.json.stdout.txt
Fixes https://github.com/pulumi/pulumi/issues/15944.
=> Never show property diffs for OpSame

changelog/pending/20240502--sdk--updating-python-dynamic-provider-types.yaml, sdk/python/lib/pulumi/dynamic/dynamic.py
Updating python dynamic provider types for inputs to Dict[str, Any], from Any. I also added a Union so it was backward compatible, and doesn't immediately throw type errors for users.
=> Updating python dynamic provider types for inputs to Dict[str, Any]

changelog/pending/20240502--backend--fix-concurrent-reads-from-and-writes-to-display-resource-timer-maps.yaml, pkg/backend/display/progress.go
This should fix #16085, in which we are getting concurrent reads and writes to the `opStopwatch` maps.
=> Lock access when writing event timings in display

pkg/backend/httpstate/snapshot_test.go
We had to remove the parallelism here because these tests were flaky because the engine Chdir'd to the plugin directory. (See also https://github.com/pulumi/pulumi/issues/15461).
However we have since removed this Chdir, so these tests should no longer be flaky even when run in parallel.
Fixes https://github.com/pulumi/pulumi/issues/15461
=> reenable parallelism in httpstate snapshot_test

.github/workflows/pr-test-codegen-downstream.yml, changelog/pending/20240503--programgen-python--sort-generated-requirements-txt-files-when-generating-python-programs.yaml, pkg/codegen/python/gen_program.go, sdk/python/cmd/pulumi-language-python/testdata/setuppy/projects/l2-failed-create-continue-on-error/requirements.txt
A couple of our tests now generate multi-line `requirements.txt` whose order is dependent on that in which we enumerate packages when testing. This PR changes this so that we always sort them, meaning we can consistently check against snapshotted results (as opposed to having flaky tests that only pass when the generated order matches the one we happened to snapshot last).
Fixes https://github.com/pulumi/pulumi/issues/16113
=> Sort `requirements.txt` files when generating Python code

changelog/pending/20240503--engine--fix-folder-archive-outside-of-cwd.yaml, cmd/pulumi-test-language/l2resourceasset_test.go, cmd/pulumi-test-language/testdata/l2-resource-asset-archive/folder/test.txt, cmd/pulumi-test-language/testdata/l2-resource-asset-archive/subdir/main.pp, cmd/pulumi-test-language/testdata/snapshots/projects/l2-resource-asset-archive/folder/test.txt, cmd/pulumi-test-language/tests.go, sdk/go/common/resource/archive/archive.go, sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsc/projects/l2-resource-asset-archive/folder/test.txt, sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsc/projects/l2-resource-asset-archive/subdir/index.ts, sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsnode/projects/l2-resource-asset-archive/folder/test.txt, sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsnode/projects/l2-resource-asset-archive/subdir/index.ts, sdk/python/cmd/pulumi-language-python/testdata/setuppy/projects/l2-resource-asset-archive/folder/test.txt, sdk/python/cmd/pulumi-language-python/testdata/setuppy/projects/l2-resource-asset-archive/subdir/__main__.py, sdk/python/cmd/pulumi-language-python/testdata/toml/projects/l2-resource-asset-archive/folder/test.txt, sdk/python/cmd/pulumi-language-python/testdata/toml/projects/l2-resource-asset-archive/subdir/__main__.py
Fixes https://github.com/pulumi/pulumi/issues/16092.
Last part of the fix started in https://github.com/pulumi/pulumi/pull/16100. That last PR fixed assets and archive files, but not archive folders.
=> Fix folder archives in the engine

changelog/pending/20240502--engine--normalize-provider-version-during-default-provider-lookup.yaml, pkg/resource/deploy/source_eval.go, pkg/resource/deploy/source_eval_test.go
This PR addresses a problem that leads to two default providers for a given package+version. The problem occurs when given a combination of unversioned and versioned provider requests, as can occur in multi-language programs.
The fix is as follows: given an unversioned provider request, apply the default version before looking into the provider cache.
Fixes #16108 
Given the example program from #16108 plus this fix, the stack state has one provider as expected:
```jsonl
{
"urn": "urn:pulumi:dev::issue-1939-nodejs::pulumi:providers:kubernetes::default_4_10_0",
"custom": true,
"id": "c19b65b0-dd5a-432f-8c75-d7544de782ec",
"type": "pulumi:providers:kubernetes",
"inputs": {
"version": "4.10.0"
},
"outputs": {
"version": "4.10.0"
},
"created": "2024-05-02T21:22:09.72166Z",
"modified": …
```
=> Canonicalize provider version during default provider lookup

sdk/nodejs/cmd/pulumi-language-nodejs/language_test.go, sdk/python/cmd/pulumi-language-python/language_test.go
This debug log output can get way too long, and GitHub Actions logs can't even display it anymore when there are test failures.  Cut each individual message short, with an escape hatch in case someone wants to run with the full output locally.
I had a look at the test failure in https://github.com/pulumi/pulumi/pull/16116 and it seems like it's still having the same issue.  Looking again at the test output it's actually this t.Log that includes the registered resource outputs, that contains the large amounts of data.  I arbitrarily decided to make the cutoff 100 chars, but that could be adjusted.
=> truncate debug log output in conformance tests

sdk/nodejs/cmd/pulumi-language-nodejs/language_test.go, sdk/python/cmd/pulumi-language-python/language_test.go
Sometimes we show hundreds of repeated messages in the logs, e.g. "waiting for quiescence; 3 outputs outstanding".  This just makes the logs harder to read.  Since we need to wait for the test to finish before any of this is shown anyway, only log each message once and show a little blurb about how often the message has been repeated.
(Note that for simplicity if the last message is repeated we don't show the same blurb, but that should be okay since the last messages we're logging are always different.)
Based on https://github.com/pulumi/pulumi/pull/16117 where I noticed this, and I didn't want to rebase it to avoid conflicts.
=> avoid showing repeated messages

changelog/pending/20240506--cli-display--fix-a-deadlock-in-the-display-code.yaml, pkg/backend/display/progress.go, pkg/backend/display/tree_test.go
The `m` mutex deadlocks in the display code.  Split it up into an event mutex that works as it did before
https://github.com/pulumi/pulumi/pull/16101, and add a separate mutex for the stopwatch, to avoid any deadlocks here.
Fixes https://github.com/pulumi/pulumi/issues/16127
=> fix deadlock in stopwatch mutex

sdk/go/common/apitype/deployments.go
- Adding marshalling logic to match pulumi service [here](https://github.com/pulumi/pulumi-service/blob/7cb3e4a314cee068b7cc374c0eb01645e225b240/pkg/apitype/workflow.go#L256) for [issue in pulumi cloud provider](https://github.com/pulumi/pulumi-pulumiservice/issues/262)
- Just model logic
- No need for changelog, just internal model bugfix
=> Adding unmarshaling logic for DockerImage

changelog/pending/20240507--sdk-python--fix-typings-for-from_input-and-all-to-not-return-never-types.yaml, sdk/python/lib/pulumi/output.py
Fixes https://github.com/pulumi/pulumi/issues/16027.
Seems mypy was having issues with Outputs being passed into these methods and tracking that they should have just been returning the same Output in the result. Adding these extra overloads seems to have appeased the type checker when using these methods.
=> Fix overloads for all and from_input to not return `Never` types

pkg/codegen/pcl/binder_component.go
Close files in PCL parser after parsing.
=> fix: close files in PCL binder

changelog/pending/20240508--sdk-nodejs--dont-load-punycode-module-in-function-serialization-code.yaml, sdk/nodejs/runtime/closure/createClosure.ts
Fixes https://github.com/pulumi/pulumi/issues/15545
https://nodejs.org/api/deprecations.html#dep0040-nodepunycode-module
=> Don't load punycode module in function serialization code

sdk/nodejs/cmd/pulumi-language-nodejs/main.go
Seems like we should now recommend this instead, right?
=> Suggest pulumi install in error message instead of yarn install

.github/workflows/ci.yml, build/common.mk, changelog/pending/20240508--engine--fix-dataraces-between-snapshot-and-deployment-systems.yaml, pkg/backend/inmemoryPersister.go, pkg/cmd/pulumi/import.go, pkg/engine/lifecycletest/refresh_test.go, pkg/resource/deploy/import.go, pkg/resource/deploy/snapshot.go, pkg/resource/deploy/snapshot_test.go, pkg/resource/deploy/state_builder.go, pkg/resource/deploy/step.go, pkg/resource/deploy/step_executor.go, pkg/resource/stack/deployment.go, sdk/go/common/resource/resource_state.go, tests/testprovider/echo.go, tests/testprovider/fails_on_delete.go
This reverts commit 75340dd94203da02e44ca5f8beb55d9063d302ef.
Fixes https://github.com/pulumi/pulumi/issues/16018.
This re-enables the locking and race detection. The locking is more finely scoped to not be held over provider methods like Read/Update.
=> Revert "Revert "Run integration tests and dev builds with race detection" (#15998)"

changelog/pending/20240509--sdk-python--fix-a-race-condition-in-output-handling.yaml, sdk/python/lib/pulumi/output.py
Fixes https://github.com/pulumi/pulumi/issues/16154.
=> Fix a race condition in python output handling

changelog/pending/20240501--sdk-python--provide-more-descriptive-exception.yaml, sdk/python/lib/pulumi/runtime/resource.py, sdk/python/lib/pulumi/runtime/rpc.py, sdk/python/lib/test/test_next_serialize.py
=> More descriptive exception in serialize_property

changelog/pending/20240510--sdk-nodejs--return-the-underlying-error-if-we-cant-locate-the-pulumi-sdk.yaml, sdk/nodejs/cmd/pulumi-language-nodejs/main.go
When locating the pulumi SDK fails with an error other than
MODULE_NOT_FOUND, return the underlying error instead of our default
error message asking to run `pulumi install`. This is helpful when
there's a typo in package.json and it can't be parsed.
Fixes https://github.com/pulumi/pulumi/issues/4973
=> Return the underlying error if we can't locate the pulumi SDK

changelog/pending/20240510--sdk-nodejs--return-error-in-rpc-response-instead-of-exiting-in-the-language-runtime.yaml, sdk/nodejs/cmd/pulumi-language-nodejs/main.go
If we can't start the node process for some reason, report back the error via RPC instead of exiting immediately.
Fixes https://github.com/pulumi/pulumi/issues/11706
Instead of:
we get
=> Return error in RPC response instead of exiting in the language runtime

pkg/backend/backend.go
This field was something I tried to use during development, but then decided to only use it in the engine options.  Remove it to avoid further confusion.
=> remove extraneous `ContinueOnError` field

changelog/pending/20240513--sdk-go--prefer-plugindownloadurloverrides-over-plugindownloadurl-specified-in-the-package.yaml, sdk/go/common/workspace/plugins.go, sdk/go/common/workspace/plugins_test.go
Overriding plugin download URLs with compilation flags was originally added in #8798. Its intent was allowing our customers to override download locations for all plugins, so that only trusted pre-approved plugins could be downloaded.
Since then, we've added `PluginDownloadURL` for a package, which is the default URL for that package's binary if it's shipped outside our Pulumi org. Currently, `PluginDownloadURL` takes precedence over `pluginDownloadURLOverrides`, which means it's impossible to override third-party package binary locations.
This PR changes plugin source resolution to flip the priority of those two. If an override matches regex, its URL will take priority over the default `PluginDownloadURL` specified in the package.
I have added tests to verify `pluginDownloadURLOverrides` …
=> Prefer pluginDownloadURLOverrides over PluginDownloadURL specified in the package

changelog/pending/20240513--docs--resource-docs-emit-supporting-types-beyond-the-200-limit.yaml, pkg/codegen/docs/gen.go, pkg/codegen/docs/templates/resource.tmpl
Originally motivated by uncontrolled pseudo-recurcive type expansion in AWS WafV2, we've limited the number of types that we should in the docs to 200: https://github.com/pulumi/pulumi/pull/12070
Our large customer that publishes their own packages and docs came back to us and said they have legitimate use cases with more than 200 types: #15507
I've grabbed stats about our current packages and still found a few offenders:
```
"aws:lex/v2modelsIntent:V2modelsIntent" 920
"aws:wafv2/ruleGroup:RuleGroup" 310
"aws:wafv2/webAcl:WebAcl" 523
"azure-native:datafactory:Dataset" 256
"azure-native:datafactory:LinkedService" 299
"azure-native:datafactory:Pipeline" 618
"azure-native:datamigration:ServiceTask" 291
"azure-native:datamigration:Task" 291
"aws-native:quicksight:Analysis" 589 …
```
=> Resource docs: emit supporting types beyond the 200 limit

pkg/codegen/testing/test/helpers.go
Update to the latest dotnet version.  Pulumi.Awsx started depending on that, so using an earlier version makes the tests fail.
This happened a few times now, so we should really fix this in a way that doesn't require us to hardcode this version.  But I want to get the merge queue unblocked, and this is probably the quickest way to do that.
=> update dotnet version in tests to latest

changelog/pending/20240516--backend-diy--rewrite-deletedwith-references-when-renaming-stacks.yaml, pkg/backend/diy/backend_test.go, pkg/resource/edit/operations.go
When renaming a stack, we need to rewrite URN references to use the new stack name instead of the old one. Presently such references can occur as:
* `Parent` references
* `Provider` references
* `Dependencies`
* `PropertyDependencies`
* `DeletedWith` references
The current renaming implementation fails to rewrite `DeletedWith` references. Previously this went unnoticed since such references were also omitted when checking snapshot integrity. Now that integrity checks correctly inspect `DeletedWith` properties, the omission during rename has been surfaced. This commit fixes renaming to handle `DeletedWith` correctly. A follow-up should also ensure that renaming checks integrity itself prior to operation completion.
Fixes #16215
=> Rewrite `DeletedWith` properties when renaming stacks

sdk/nodejs/cmd/pulumi-language-nodejs/language_test.go, sdk/python/cmd/pulumi-language-python/language_test.go
We initially introduced this limit for log messages in https://github.com/pulumi/pulumi/pull/16117.  However I've since realized that these log messages also include useful stacktraces (when the program being tested throws an exception), which are a bit longer.
The intention here is really to avoid *really* long messages, so increase the maximum message size a little to still avoid those, but allow us to see more of the stacktrace that should hopefully be useful for debugging.
The number is mostly still based on a guesstimate of what's useful, but it's easy to tweak if we need to tweak it further.
=> language_test: allow more characters in the log before truncating

changelog/pending/20240517--engine--check-property-dependencies-and-deleted-with-relationships-for-target-dependents.yaml, pkg/resource/deploy/step_generator.go, pkg/resource/deploy/step_generator_test.go
The `--target-dependents` flag instructs Pulumi to include dependents of specified targets. Presently we check dependencies, parents and providers, but not property dependencies and `DeletedWith` relationships. This commit fixes this so that these relationships are correctly checked.
=> Check property dependencies and `DeletedWith` for target dependents

pkg/resource/deploy/builtins.go
=> Lock state access in `builtinProvider.getResource`

sdk/nodejs/cmd/pulumi-language-nodejs/language_test.go, sdk/python/cmd/pulumi-language-python/language_test.go
The engine can call Log in parallel, so we need to lock to maintain our `previousMessage` correctness.
=> Fix race in language conformance tests Log method

changelog/pending/20240515--engine--guess-id-references-of-dependant-resources-when-generating-code-for-import-operations.yaml, pkg/importer/hcl2.go, pkg/importer/hcl2_test.go, pkg/importer/language.go
Taking an initial attempt at #10025 where we now try to guess ID references of dependant resources instead of writing out the IDs as literal values. 
Instead of:
```hcl
// has ID=provider-generated-bucket-id-abc123
resource exampleBucket "aws:s3/bucket:Bucket" {}
resource exampleBucketObject "aws:s3/bucketObject:BucketObject" {
bucket = "provider-generated-bucket-id-abc123"
storageClass = "STANDARD"
}
```
We generate:
```hcl
resource exampleBucket "aws:s3/bucket:Bucket" {}
resource exampleBucketObject "aws:s3/bucketObject:BucketObject" {
bucket = exampleBucket.id
storageClass = "STANDARD"
}
```
This implies a dependency between `exampleBucketObject` and `exampleBucket` without explicitly being added into the `dependsOn` array (it would be redundant)
=> [engine/import] Guess ID references of dependant resources when generating code for import operations

changelog/pending/20240510--sdk-python--use-a-separate-type-variable-for-static-methods-on-output.yaml, changelog/pending/20240515--sdk-python--relax-output-all-types-to-better-match-the-implementation.yaml, sdk/python/lib/pulumi/output.py
Pyright >= 1.1.354 assumes the typevar is Unknown if the generic class
that holds the staticmethods has no default type parameter, however in
our case the staticmethods have no link to the class's typevar.
Fixes https://github.com/pulumi/pulumi/issues/15914
Fixes https://github.com/pulumi/pulumi/issues/16194
=> Use a separate type variable for static methods on Output

pkg/cmd/pulumi/org.go
fixes: https://github.com/pulumi/docs/issues/11869
Updates the command description to be more explicit that this only alters default org configuration locally.
=> Update set-default command description

.github/workflows/ci-build-binaries.yml, .github/workflows/ci.yml, .gitignore, .goreleaser.yml, Makefile, pkg/backend/display/wasm/main.go, pkg/codegen/schema/loader.go, pkg/codegen/schema/loader_js.go, pkg/codegen/schema/loader_mmap.go, sdk/go/common/util/cmdutil/child_js.go, sdk/go/common/util/cmdutil/child_unix.go, sdk/go/common/util/cmdutil/console.go, sdk/go/common/util/cmdutil/console_input.go, sdk/go/common/util/cmdutil/console_input_js.go, sdk/go/common/util/cmdutil/term_js.go, sdk/go/common/util/cmdutil/term_unix.go, sdk/go/common/util/rpcutil/pty_js.go
These changes contain some minor refactorings to conditionally disable the use of packages that are cannot be built for `GOOS=js GOARCH=wasm`. With these edits, `pkg/display` can be built targeting WASM.
These changes act as a safeguard to ensure that we are not adding additional code that will _prevent_ building `pkg/display` for WASM targets. They are not sufficient to produce a version of the display renderer that is appropriate for actual use in a WASM environment:
- The current renderer API is not well-suited for use outside the context of the CLI
- The current event stream format has no versioning data
- Actually building this code into a WASM module results in an unpleasantly large file (70M uncompressed, 13M gzipped)
These changes also add a size gate for the built WASM module. …
=> [display] Enable WASM compilation

.github/workflows/release-homebrew-tap.yml
We're in the process of renaming the main branch in our repos to `main` from `master`.  I'm planning to do homebrew-tap next, and this `git push` will need to be updated to keep that working.
This is meant to be merged right after the branch is renamed in that repo.
=> update homebrew tap push to use `main`

changelog/pending/20240529--sdk--improve-plugin-parameterize-interface.yaml, pkg/cmd/pulumi/package.go, pkg/resource/deploy/builtins.go, pkg/resource/deploy/deploytest/provider.go, pkg/resource/deploy/providers/registry.go, sdk/go/common/resource/plugin/provider.go, sdk/go/common/resource/plugin/provider_plugin.go, sdk/go/common/resource/plugin/provider_server.go, sdk/go/common/resource/plugin/provider_unimplemented.go
`plugin.Provider` exists to provide a low-level abstraction *on top of* the gRPC interface. It should not expose the gRPC types directly. The key diff in this commit is:
```patch
-	Parameterize(
-		ctx context.Context, req *pulumirpc.ParameterizeRequest,
-	) (*pulumirpc.ParameterizeResponse, error)
+	Parameterize(parameters ParameterizeParameters) (string, *semver.Version, error)
```
```patch
+type ParameterizeParameters interface {
+	isParameterizeParameters()
+}
+
+type (
+	ParameterizeArgs struct {
+		Args []string
+	}
+
+	ParameterizeValue struct {
+		Name    string
+		Version *semver.Version
+		// Value must be one of:
+		// - nil
+		// - bool
+		// - int, int32, int64
+		// - uint, uint32, uint64
+		// - float32, float64
+		// - string
+		// - []byte
+		// - map[string]interface{}
+ …
```
=> Abstract plugin.Parameterize away from the gRPC interface

changelog/pending/20240524--engine--fix-panic-with-continue-on-error-on-delete-after-failed-create.yaml, pkg/engine/lifecycletest/continue_on_error_test.go, pkg/resource/deploy/deployment_executor.go, pkg/resource/deploy/step_executor.go, pkg/resource/graph/dependency_graph.go
For deleting resources when `--continue-on-error` is given, we look up a failed resources transitive dependencies in the dependency graph. This is used to skip those resources from being destroyed to keep the dependency chains correctly intact.
The errors for looking these dependencies up are recorded in the step executor, whenever a resource execution fails.  This includes errors from resources that are supposed to be created.
However when a resource fails to create that resource does not exist in the dependency graph at all, so we cannot look it up, and we get a panic because we try to access a nil pointer.
When deleting resources we do not need to care about resources that failed earlier, so we can just clear the errored steps before going ahead with the deletes.
Fixes …
=> fix panic with --continue-on-error on delete after failed create

changelog/pending/20240529--sdk-go-nodejs-python--make-stack-transforms-a-stable-non-experimental-feature.yaml, sdk/go/pulumi/context.go, sdk/go/pulumi/resource.go, sdk/go/pulumi/transform.go, sdk/nodejs/runtime/stack.ts, sdk/python/lib/pulumi/runtime/__init__.py, sdk/python/lib/pulumi/runtime/stack.py, tests/integration/transforms/go/simple/main.go, tests/integration/transforms/nodejs/simple/index.ts, tests/integration/transforms/nodejs/single/index.ts, tests/integration/transforms/python/simple/__main__.py
Registering stack transforms is now non-experimental. This change updates the function signatures in the Go, Node.js, and Python SDKs along with associated types and comments.
Follow-up to #16080
=> Flip stack transforms to non-experimental

changelog/pending/20240517--docs--fix-generating-constructor-examples-for-resources-that-have-enumeric-enums-as-input.yaml, pkg/codegen/docs/constructor_syntax_generator.go, pkg/codegen/docs/constructor_syntax_generator_test.go, pkg/codegen/dotnet/gen_program_expressions.go, pkg/codegen/go/gen_program_expressions.go, pkg/codegen/pcl/binder_schema.go, pkg/codegen/python/gen_program_expressions.go, tests/testdata/codegen/dashed-import-schema/docs/tree/v1/nursery/_index.md, tests/testdata/codegen/dashed-import-schema/docs/tree/v1/rubbertree/_index.md, tests/testdata/codegen/different-enum/docs/tree/v1/nursery/_index.md, tests/testdata/codegen/different-enum/docs/tree/v1/rubbertree/_index.md, tests/testdata/codegen/enum-reference/docs/myModule/iamresource/_index.md, tests/testdata/codegen/external-enum/docs/component/_index.md, tests/testdata/codegen/legacy-names/docs/example_resource/_index.md, tests/testdata/codegen/plain-and-default/docs/moduleresource/_index.md, tests/testdata/codegen/simple-enum-schema/docs/tree/v1/nursery/_index.md, tests/testdata/codegen/simple-enum-schema/docs/tree/v1/rubbertree/_index.md
Fixes #16191 
The original issue is that the intermediate PCL we generate used enum names instead of enum values for numeric enum inputs. This PR changes it so that the PCL program now uses the first numeric value for the first enum case then subsequently fixing downstream program-gen bugs that didn't know how to handle numeric values as inputs for enums.
=> [docs] Fix generating constructor examples for resources that have numeric enums as input

changelog/pending/20240530--sdk--exchange-parsetolerant-for-parse-in-plugin-provider-parameterize.yaml, changelog/pending/20240530--sdk--require-consumers-to-set-an-explicit-forward-compatibility-policy-for-forward-compatibility-in-plugin-provider.yaml, pkg/cmd/pulumi/package.go, pkg/resource/deploy/builtins.go, pkg/resource/deploy/deploytest/provider.go, pkg/resource/deploy/providers/registry.go, sdk/go/common/resource/plugin/provider.go, sdk/go/common/resource/plugin/provider_plugin.go, sdk/go/common/resource/plugin/provider_server.go, sdk/go/common/resource/plugin/provider_unimplemented.go
This PR is best reviewed commit by commit:
- bbe1fc6b2f906f3f7a291cd13247b3d40cf33ab8 exchanges `ParseTolerant` for `Parse` in `Parameterize`.
- 76df18be56c1b01573f80f876f3b2a878fb1f9e7 updates the `Parameterize` interface for forward compatibility.
- 746c057668a2db8889ce6bd04eaf7392dd3d92c3 requires implementors of `plugin.Provider` to make a forward compatibility choice explicitly. This is similar to what we require for gRPC already. Since this will release with bbe1fc6b2f906f3f7a291cd13247b3d40cf33ab8, consumers will already need to update their `plugin.Provider` implementor, minimizing the disturbance.
=> Plugin interface cleanup

changelog/pending/20240531--auto-go--add-missing-continueonerror-option-function.yaml, sdk/go/auto/optup/optup.go
This [PR](https://github.com/pulumi/pulumi/pull/15953) added support for `continue-on-error` to the Automation API. However this hardly usable without the corresponding function Option
=> Add ContinueOnError() method for optup

changelog/pending/20240603--backend-service--improve-error-reporting-when-policy-pack-download-fails.yaml, pkg/backend/httpstate/client/client.go
The HTTP client in Go only returns an error if there is a protocol level failure, or an error caused by client policy (which we don't use).  However the policy pack can fail to be downloaded, and return a non 200 HTTP status.  This should still be considered an error.
Currently we would only detect this when trying to unpack the policy pack.  Catching and returning this error earlier allows us to give better information about the failure to the user.
I got curious about https://github.com/pulumi/pulumi/issues/16275, and did a short dive into the code.  It looks like this should give us a better error message there.
=> Improve error handling when downloading policy packs

sdk/nodejs/automation/events.ts, sdk/nodejs/output.ts, sdk/nodejs/resource.ts, sdk/nodejs/utils.ts
This commit fixes a few errant documentation comments that use `//` instead of the recognised `/**`. This should hopefully improve documentation generation as well as hover-over documentation provided by e.g. TSServer.
=> Fix documentation comments in the NodeJS SDK

changelog/pending/20240524--auto-go-nodejs-python--add-support-for-all-parameter-of-the-stack-ls-command-to-the-automation-api.yaml, sdk/go/auto/local_workspace.go, sdk/go/auto/local_workspace_test.go, sdk/go/auto/optlist/optlist.go, sdk/go/auto/workspace.go, sdk/nodejs/automation/localWorkspace.ts, sdk/nodejs/automation/workspace.ts, sdk/nodejs/tests/automation/localWorkspace.spec.ts, sdk/python/lib/pulumi/automation/_local_workspace.py, sdk/python/lib/pulumi/automation/_workspace.py, sdk/python/lib/test/automation/test_local_workspace.py
Adds Go/Nodejs/Python automation API support for pulumi stack ls --all.
Fixes: [#14226](https://github.com/pulumi/pulumi/issues/14226)
=> Add support for `--all` parameter of the `stack ls` command to the Automation API

pkg/backend/httpstate/backend.go
Refine the error message when a full stack name is not supplied outside a project directory
Context:
1. Open a brand-new clean directory that is not a child directory to any Pulumi program.
2. Run `pulumi stack init dev`
3. CLI doesn't have a project name at this point, because it has not Pulumi.yaml. So, the user needs to supply the full name.
Fixes https://github.com/pulumi/pulumi/issues/15967
=> Refine the error message when a full stack name is not supplied

changelog/pending/20240603--cli-new--populate-pulumi-template-tag-also-for-interactively-selected-templates.yaml, pkg/cmd/pulumi/new.go, pkg/cmd/pulumi/new_test.go
The following lines are added to `Pulumi.yaml` after a `pulumi new` command:
```yaml
config:
pulumi:tags:
value:
pulumi:template: alicloud-fsharp
```
where `pulumi:template` points to a name or a URL of the template that was used for project instantiation.
The problem is that this currently works only if the template name is specified as a CLI argument, not selected interactively. This PR fixes the field population for the interactive case by using `template.Name` for the tag value, not just the input argument.
Fixes https://github.com/pulumi/pulumi/issues/16037
=> Populate pulumi:template tag also for interactively selected templates

sdk/go/common/workspace/plugins.go, sdk/go/common/workspace/plugins_test.go
Reverts pulumi/pulumi#16186
Resolves https://github.com/pulumi/pulumi/issues/16316
=> Revert "Prefer pluginDownloadURLOverrides over PluginDownloadURL specified in the package"

.github/workflows/pr-test-acceptance-on-dispatch.yml
Name the CI test appropriately to make use of the skipping functionality introduced in https://github.com/pulumi/home/pull/3457.
Fixes: https://github.com/pulumi/pulumi/issues/14026
=> avoid new issues being created when dispatched acceptance tests fail

changelog/pending/20240604--sdk-python--autoinstall-dependencies-using-poetry-in-getrequiredplugins.yaml, sdk/python/cmd/pulumi-language-python/main.go, sdk/python/toolchain/pip.go, sdk/python/toolchain/poetry.go, sdk/python/toolchain/toolchain.go, tests/integration/integration_python_acceptance_test.go, tests/integration/python/poetry/.gitignore, tests/integration/python/poetry/Pulumi.yaml, tests/integration/python/poetry/__main__.py, tests/integration/python/poetry/poetry.toml, tests/integration/python/poetry/pyproject.toml
Refactor pip specific `prepareVirtualEnvironment` and expose functionality via Toolchain.EnsureVenv.
This makes it so that calls to `pulumi up/refresh/etc` create the poetry managed virtual env if it does not exist yet.
Stacked on top of https://github.com/pulumi/pulumi/pull/16315
Ref https://github.com/pulumi/pulumi/issues/15937
=> Autoinstall dependencies using Poetry in GetRequiredPlugins

changelog/pending/20240606--cli-config-new--fix-non-interactive-flag-for-new-and-config-env-commands.yaml, pkg/cmd/pulumi/config_env.go, pkg/cmd/pulumi/config_env_add.go, pkg/cmd/pulumi/config_env_init.go, pkg/cmd/pulumi/config_env_ls.go, pkg/cmd/pulumi/config_env_rm.go, pkg/cmd/pulumi/new.go
The command line flags are not parsed yet when the command definition is
created. We need to wait until we're in the command's `Run` method
before we can read the flags.
=> Fix non-interactive flag for 'new' and 'config env' commands

changelog/pending/20240530--programgen-go--fix-union-type-type-resolution-in-go-program-generation.yaml, pkg/codegen/pcl/binder_resource.go, tests/testdata/codegen/azure-native-v2-eventgrid-pp/azure-native-v2-eventgrid.pp, tests/testdata/codegen/azure-native-v2-eventgrid-pp/dotnet/azure-native-v2-eventgrid.cs, tests/testdata/codegen/azure-native-v2-eventgrid-pp/go/azure-native-v2-eventgrid.go, tests/testdata/codegen/azure-native-v2-eventgrid-pp/nodejs/azure-native-v2-eventgrid.ts, tests/testdata/codegen/azure-native-v2-eventgrid-pp/python/azure-native-v2-eventgrid.py, tests/testdata/codegen/basic-unions-pp/go/basic-unions.go, tests/testdata/codegen/unions-inline/docs/exampleserver/_index.md
Fixes https://github.com/pulumi/pulumi-azure-native/issues/1554 
The problem here is that when we compute `InputType: model.Type` in `pcl.Resource`, we map the types of input properties of resources from `schema.Type` into `model.Type`. When one of these properties is a `schema.UnionType` (union of objects to be exact), we map that _as is_ to `model.UnionType` which trips up Go program-gen as it doesn't know how to reduce the type to the actual _selected_ object type based on the resource inputs. 
The way to fix this is not in Go program-gen, instead we _reduce_ the computed union types during the binding phase into the actual object types based on the resource inputs so that all program generators only work against explicit objects rather than having to deal with unions of objects
```pcl …
```
=> [go/program-gen] Fix union type type resolution in Go program generation

changelog/pending/20240606--programgen-nodejs--sort-depdencies-in-generateproject.yaml, pkg/codegen/nodejs/gen_program.go
This helps avoiding flakiness in tests using snapshots.
```
=== FAIL: . TestLanguage/forceTsc=true-/l2-failed-create-continue-on-error (54.39s)
language_test.go:242: program snapshot validation failed:
expected file package.json does not match actual file:
--- expected
+++ actual
@@ -6,7 +6,7 @@
"dependencies": ***
"typescript": "^4.0.0",
"@pulumi/pulumi": "ROOT/artifacts/pulumi-pulumi-CORE.VERSION.tgz",
-		"@pulumi/fail_on_create": "ROOT/artifacts/pulumi-fail_on_create-4.0.0.tgz",
-		"@pulumi/simple": "ROOT/artifacts/pulumi-simple-2.0.0.tgz"
+		"@pulumi/simple": "ROOT/artifacts/pulumi-simple-2.0.0.tgz",
+		"@pulumi/fail_on_create": "ROOT/artifacts/pulumi-fail_on_create-4.0.0.tgz"
```
Fixes https://github.com/pulumi/pulumi/issues/16340
=> Sort depdencies in GenerateProject

changelog/pending/20240606--cli-import--add-flag-json-to-pulumi-import-which-would-serialize-the-import-diffs-operations-and-overall-output-as-json.yaml, pkg/cmd/pulumi/import.go
Small addition for `pulumi import` so that it prints out import diffs and operations as JSON, not just using the default display.
=> [cli/import] Add flag --json which would serialize the import diffs, operations, and overall output as JSON

changelog/pending/20240607--cli-new--allow-passing-runtime-options-as-args-in-pulumi-new.yaml, pkg/cmd/pulumi/new.go, tests/integration/integration_python_acceptance_test.go
Stacked on top of https://github.com/pulumi/pulumi/pull/16346
Fixes https://github.com/pulumi/pulumi/issues/16348
=> Allow passing runtime options as args in pulumi new

changelog/pending/20240611--sdk-nodejs--only-look-for-main-in-package-json-if-no-entyrpoint-was-set-via-pulumi-yaml.yaml, sdk/nodejs/cmd/run/run.ts, tests/integration/integration_nodejs_test.go, tests/integration/nodejs/main-overrides-package-json/Pulumi.yaml, tests/integration/nodejs/main-overrides-package-json/entrypoint.js, tests/integration/nodejs/main-overrides-package-json/index.js, tests/integration/nodejs/main-overrides-package-json/package.json
`main` in Pulumi.yaml is supposed to take precedence over `main` in `package.json`, but we inadvertently broke this in https://github.com/pulumi/pulumi/commit/cf1189bf2c9a31b7d0ca7aa280661af892029aa4
Fixes https://github.com/pulumi/pulumi/issues/16274
=> Only look for main in package.json if no entyrpoint was set via Pulumi.yaml

pkg/engine/deployment.go, pkg/engine/deployment_test.go, pkg/engine/destroy.go, pkg/engine/import.go, pkg/engine/refresh.go, pkg/engine/update.go, pkg/resource/deploy/deployment.go, pkg/resource/deploy/deployment_executor.go, pkg/resource/deploy/deployment_test.go, pkg/resource/deploy/import.go, pkg/resource/deploy/import_test.go, pkg/resource/deploy/source.go, pkg/resource/deploy/source_error.go, pkg/resource/deploy/source_error_test.go, pkg/resource/deploy/source_eval.go, pkg/resource/deploy/source_eval_test.go, pkg/resource/deploy/source_null.go, pkg/resource/deploy/step.go, pkg/resource/deploy/step_executor.go, pkg/resource/deploy/step_executor_test.go, pkg/resource/deploy/step_generator.go, pkg/resource/deploy/step_generator_test.go, pkg/resource/deploy/step_test.go
There are a number of parts of the deployment process that require context about and configuration for the operation being executed. For instance:
* Source evaluation -- evaluating programs in order to emit resource registrations
* Step generation -- processing resource registrations in order to generate steps (create this, update that, delete the other, etc.)
* Step execution -- executing steps in order to action a deployment.
Presently, these pieces all take some form of `Options` struct or pass explicit arguments. This is problematic for a couple of reasons:
* It could be possible for different parts of the codebase to end up operating in different contexts/with different configurations, whether due to different values being passed explicitly or due to missed copying/instantiation.
* …
=> Clean up deployment options

changelog/pending/20240612--sdk-nodejs--update-current-nodejs-version-to-22-x.yaml, scripts/get-job-matrix.py
The current nodejs version is 22.x https://nodejs.org/en/about/previous-releases
This might help us with GH actions failing on the node download step. The node-setup action will download LTS versions from https://github.com/actions/node-versions/blob/main/versions-manifest.json, and fallback to the official nodejs.org download if not found. Since we had node set to 21.x before, it was always downloading from nodejs.org, which seems to be fairly flakey.
This won't fix it once we test against 23.x though :/
=> Update current nodejs version to 22.x

changelog/pending/20240611--sdk-python--make-sure-no-resource-registrations-are-in-progress-while-stack-transforms-are-being-registered.yaml, sdk/python/lib/pulumi/runtime/rpc_manager.py, sdk/python/lib/pulumi/runtime/stack.py
For transforms, we want to make sure all resources are registered before registering them, and that no resource registration happens while the transform is being registered in the engine.
The latter is already given, since `register_stack_transform` happens synchronously, so no new RegisterResource calls can be started while the transforms are registered.
For the former, we can make use of the event loop.  Since all of the rpc calls are being put on the event loop, we can make sure to wait for them to finish before re start registering the transforms.  Note that we can't just wait for all tasks to finish because there might be more than RPCs in flight.  However when the RPCs finished we can be certain that the resources are registered in the engine, and registering the stack transforms is …
=> wait for RPCs to finish before registering stack transforms

sdk/go/auto/test/errors/compilation_error/typescript/package-lock.json, sdk/go/auto/test/errors/runtime_error/javascript/package-lock.json, sdk/go/auto/test/errors/runtime_error/typescript/package-lock.json, sdk/nodejs/tests/automation/data/tcfg/package-lock.json, sdk/python/lib/test/automation/errors/compilation_error/typescript/package-lock.json, sdk/python/lib/test/automation/errors/runtime_error/javascript/package-lock.json, sdk/python/lib/test/automation/errors/runtime_error/typescript/package-lock.json, tests/integration/nodejs/esm-srcdir-ts/package-lock.json
Many of our tests test JavaScript/TypeScript behaviour and thus rely on `package.json` files specifying dependencies and `package-lock.json` files pinning those dependencies. While the dependencies we use in our tests are minimal and their bounds haven't changed (nor maybe have much reason to change), the transitive dependency set is potentially large and worth keeping up-to-date (e.g. for security reasons, or just keeping Dependabot happy). This commit thus regenerates all the `package-lock.json` files associated with tests that Dependabot has previously recommended we bump.
* Closes #13478
* Closes #13473
* Closes #13472 
* Closes #13471 
* Closes #13470 
* Closes #13469 
* Closes #13468 
* Closes #13467
* Closes #13424 
* Closes #13419
* Closes #13418 
* Closes #13414
* Closes #13412 …
=> Regenerate test `package-lock.json` files

changelog/pending/20240612--cli-engine--fix-continue-on-error-running-indefinitely-when-a-resource-fails-to-be-created-or-updated.yaml, pkg/engine/lifecycletest/continue_on_error_test.go, pkg/resource/deploy/step.go
This PR ensures that we only run the `StepCompleteFunc` if the step is successful. If not, we should use the step's `Fail` method to register the result. Previously, when a user runs a pulumi up operation with `--continue-on-error`, the engine would register the result twice, once in https://github.com/pulumi/pulumi/blob/ee6ec150d8237d472196da9e87265b6b0f24e6af/pkg/resource/deploy/step_executor.go#L342 and if a failure occurs, it is re-registered in https://github.com/pulumi/pulumi/blob/ee6ec150d8237d472196da9e87265b6b0f24e6af/pkg/resource/deploy/step_executor.go#L373
I suspect that the double registration is the cause of the user facing error. Since this would only occur for create and update steps, it also explains why the error doesn't occur during deletions.
Testing:
- Manually ran …
=> Fix --continue-on-error running indefinitely when a resource fails to be created or updated

changelog/pending/20240605--sdk-nodejs--add-options-to-workspace-removestack.yaml, sdk/nodejs/automation/localWorkspace.ts, sdk/nodejs/automation/workspace.ts, sdk/nodejs/tests/automation/localWorkspace.spec.ts, sdk/python/lib/pulumi/automation/__init__.py, sdk/python/lib/pulumi/automation/_local_workspace.py, sdk/python/lib/pulumi/automation/_workspace.py, sdk/python/lib/test/automation/test_local_workspace.py
This PR adds an optional `opts` argument to the NodeJS SDK `Workspace::removeStack` method, which has `force` and `preserveConfig` optional booleans. Setting these bools to true will add their corresponding CLI flag to the command.
Fixes #16332
=> Add removeStack options to NodeJS Auto API SDK

changelog/pending/20240612--sdk-go--suggest-valid-attributes-with-similar-names-to-unrecognised-ones-when-validating-project-definitions.yaml, sdk/go/common/workspace/project.go, sdk/go/common/workspace/project_test.go
This PR improves the error messages produced during project schema validation so that, where possible, we suggest valid attribute names that the user may have meant to type. For instance, if they provide a "Name" attribute where we wanted "name" (lowercase "n"), we'll now say so. Where there is not a close match, we'll enumerate the full list of
valid names to try and guide the user.
Matching is implemented using Levenshtein distances and ignores case. Some examples of the new functionality:
* `{"Name": ...}` yields `project is missing a 'name' attribute; found 'Name' instead`
* `{..., "rutnime": ...}` yields `project is missing a 'runtime' attribute; found 'rutnime' instead`
* `{..., "template": {"displayNameDisplayName": ...}, ...}` yields `'displayNameDisplayName' not allowed; the …
=> Better error messages for schema validation

changelog/pending/20240614--engine--fix-a-panic-when-ignoring-wildcard-values-with-arrays-of-different-length.yaml, sdk/go/common/resource/properties_path.go, sdk/go/common/resource/properties_path_test.go
The panic occurred during pulumi preview while calculating values for ignored changes with a `*` wildcard
```
{ignoreChanges: ["defaultActions[*].forward.targetGroups[*].weight"]}
```
when compared arrays had different length. We weren't checking the array boundaries carefully, and thus panicing when going out of bounds.
After the fix, the same repro in the issue leads to a preview error
> cannot ignore changes to the following properties because one or more elements of the path are missing: "defaultActions[*].forward.targetGroups[*].weight"
This seems consistent with other code branches and tests, where `reset` returns false for non-matching shapes. User's expectation may be that we succeed in this case - curious to get a take from ones who implemented the wildcard feature in the past. …
=> Fix a panic when ignoring wildcard values with arrays of different length

changelog/pending/20240616--cli-plugin--fix-plugin-install-command-when-plugin-type-is-tool.yaml, pkg/util/plugin.go, sdk/go/common/workspace/plugins.go
When trying to install a plugin of type `tool` from GitHub, the Pulumi convention is to have these plugins available in repositories named `pulumi-tool-<name>` so that we can install them via the CLI as follows:
```
pulumi plugin install tool <name>
```
However, today this fails because we don't prefix the repository name correctly with `"pulumi-tool-"`. This PR fixes that. Tested against [Zaid-Ajaj/pulumi-tool-importer](https://github.com/Zaid-Ajaj/pulumi-tool-importer)
Also removes hardcoded plugin download URL for known converter plugins of mine. These are moved to the `pulumi` organisation and no longer require a separate URL.
=> [cli/plugin] Fix plugin install command when plugin type is tool

changelog/pending/20240614--sdk-python--dont-incorrectly-emit-deprecation-warnings-for-non-deprecated-properties.yaml, pkg/codegen/python/gen.go, sdk/python/lib/pulumi/__init__.py, sdk/python/lib/pulumi/_types.py, sdk/python/lib/pulumi/deprecated.py, sdk/python/lib/pulumi/resource.py, sdk/python/lib/test/test_deprecated.py, tests/testdata/codegen/regress-py-12546/python/pulumi_plant/tree/v1/rubber_tree.py
Presently, the Python SDK incorrectly emits deprecation warnings for properties even if user code does not reference them. This is due to various pieces of code in the SDK that enumerate properties e.g. for the purpose of serialisation/RPC calls. In enumerating properties, their getters are invoked, triggering the deprecation warnings.
There isn't currently a way for us to detect which properties may or may not be deprecated and handle them appropriately, so this commit introduces one. Deprecation messages are moved into a new decorator, `@pulumi.deprecated`. This decorator accepts a `Callable` and wraps it, making two changes:
* Before the decorated `Callable`'s execution, deprecation messages are printed.
* The returned `Callable` is tagged with a new reserved property, …
=> Don't incorrectly emit deprecated warnings

pkg/cmd/pulumi/deployment.go, pkg/cmd/pulumi/pulumi.go, sdk/go/common/workspace/loaders.go, sdk/go/common/workspace/paths.go, sdk/go/common/workspace/paths_test.go, sdk/go/common/workspace/project.go
- Add new deployment settings pull command: this command will pull the deployment settings from pulumi cloud and generate the new deployment file. For now it will be hidden until we have completed the whole feature.
- Add support for the new deployment file, this will contain all the deployment related information (for now just the settings), example:
```
settings:
-executorContext: {}
sourceContext:
git:
branch: main
repoDir: .
gitHub:
repository: glena/test-action
deployCommits: true
previewPullRequests: false
operationContext:
preRunCommands: []
operation: ""
environmentVariables: {}
options:
skipInstallDependencies: false
skipIntermediateDeployments: true
shell: ""
deleteAfterDestroy: false
remediateIfDriftDetected: false
agentPoolID: ...
```
Fixes …
=> Update pu/pu to support the new settings pull command + new deployment file

changelog/pending/20240227--sdk-nodejs--detect-pnpm-workspaces-when-running-pulumi-install.yaml, pkg/testing/integration/program.go, sdk/nodejs/npm/testdata/not-a-workspace/package.json, sdk/nodejs/npm/testdata/pnpm-workspace/package.json, sdk/nodejs/npm/testdata/pnpm-workspace/packages/my-component/package.json, sdk/nodejs/npm/testdata/pnpm-workspace/pnpm-workspace.yaml, sdk/nodejs/npm/testdata/pnpm-workspace/project/package.json, sdk/nodejs/npm/workspaces.go, sdk/nodejs/npm/workspaces_test.go, tests/integration/integration_nodejs_test.go, tests/integration/nodejs/pnpm-workspace/infra/Pulumi.yaml, tests/integration/nodejs/pnpm-workspace/infra/index.ts, tests/integration/nodejs/pnpm-workspace/infra/package.json, tests/integration/nodejs/pnpm-workspace/package.json, tests/integration/nodejs/pnpm-workspace/packages/my-random/index.ts, tests/integration/nodejs/pnpm-workspace/packages/my-random/package.json, tests/integration/nodejs/pnpm-workspace/pnpm-lock.yaml, tests/integration/nodejs/pnpm-workspace/pnpm-workspace.yaml
Detect pnpm workspaces and run `pulumi install` from the workspace root. Note that this change does not address issues with function serialisation in pnpm workspaces.
Fixes https://github.com/pulumi/pulumi/issues/15512
=> Detect pnpm workspaces

pkg/codegen/pcl/rewrite_apply.go, pkg/go.mod, pkg/go.sum, sdk/go/pulumi-language-go/go.mod, sdk/go/pulumi-language-go/go.sum, sdk/nodejs/cmd/pulumi-language-nodejs/go.mod, sdk/nodejs/cmd/pulumi-language-nodejs/go.sum, sdk/python/cmd/pulumi-language-python/go.mod, sdk/python/cmd/pulumi-language-python/go.sum, tests/go.mod, tests/go.sum
The gedex/inflector (singularization/pluralization) library has been seemingly abandoned: still no go module support, no changes in years, etc. It was decided that we want to fork it and maintain ourselves to ensure both a) stability and backwards compatibility b) modernization and quality.
This PR switches the inflector library. The next step will be TF bridge.
There are no functional changes in behavior - the library code is exactly the same.
=> Vendor the inflector library

changelog/pending/20240620--sdk-python--add-virtual_env-environment-variable-when-running-inside-a-virtual-environment.yaml, sdk/python/toolchain/pip.go, sdk/python/toolchain/pip_test.go
Activating a virtual environment sets a VIRTUAL_ENV environment variable. Replicate this behaviour in `ActivateVirtualEnv` function.
https://docs.python.org/3/library/venv.html#how-venvs-work
> When a virtual environment has been activated, the VIRTUAL_ENV environment variable is set to the path of the environment
=> Add VIRTUAL_ENV to env var when running in a venv

changelog/pending/20240617--sdk--instruct-the-user-to-use-pulumi-install-when-using-generate-only.yaml, pkg/cmd/pulumi/new.go, pkg/cmd/pulumi/policy_new.go, tests/integration/integration_python_acceptance_test.go
When running with `--generate-only`, the user can run `pulumi install` to install all dependencies. This takes care of creating virtual environments or node_modules, respecting the options specified in Pulumi.yaml. This also removes language specific code from the CLI.
=> Instruct the user to use 'pulumi install' when using --generate-only

changelog/pending/20231215--sdk-python--fix-python-sdk-docs-by-escaping-the-trailing-underscore-in-a-docstring.yaml, sdk/python/lib/pulumi/resource.py
The trailing underscore in this docstring [needs to be escaped](https://github.com/sphinx-doc/sphinx/issues/519) for it to render properly with Sphinx.
[Currently](https://www.pulumi.com/docs/reference/pkg/python/pulumi/#pulumi.ResourceOptions), it's rendered as `import` without the trailing underscore:
It should be rendered as `import_`:
This change should fix that.
This is a follow-up from https://github.com/pulumi/pulumi-hugo/issues/434
=> [sdk/python] Escape trailing underscore in docstring

.github/workflows/download-pulumi-cron.yml
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
> The `macos-11` label has been deprecated and will no longer be available after 28 June 2024
=> ci: Bump `macos-11` runner to `macos-12`

sdk/nodejs/output.ts
Raised by @lunaris in onboarding, we don't advertise the [Pulumi ESLint Plugin](https://github.com/pulumi/eslint-plugin-pulumi). As using an output in a template literal is one of the most common avenues to discovering this issue, perhaps we should advertise the plugin here?
What's lacking from this is documentation, but I imagine that users will see this, create issues, and that will drive improvements either in the base SDK or the ESLint Plugin.
=> fix: advise people of the ESLint Plugin for catching interpolation issues

changelog/pending/20240621--sdk-nodejs--avoid-an-unhandled-error-when-dependencies-is-missing-from-package-json-during-closure-serialization.yaml, sdk/nodejs/runtime/closure/codePaths.ts, tests/integration/integration_nodejs_test.go, tests/integration/nodejs/codepaths-no-dependencies/Pulumi.yaml, tests/integration/nodejs/codepaths-no-dependencies/index.ts, tests/integration/nodejs/codepaths-no-dependencies/package.json, tests/integration/nodejs/codepaths-no-dependencies/tsconfig.json
Avoid an unhandled error when `dependencies` is missing from `package.json` during closure serialization.
Fixes #16076
=> [sdk/nodejs] Allow missing package.json dependencies

changelog/pending/20240618--cli-new--add-packagemanager-prompt-to-pulumi-new-for-nodejs.yaml, pkg/backend/httpstate/policypack.go, pkg/testing/integration/util.go, sdk/go/common/workspace/plugins.go, sdk/nodejs/cmd/pulumi-language-nodejs/main.go, sdk/nodejs/cmd/pulumi-language-nodejs/main_test.go, sdk/nodejs/npm/manager.go, sdk/nodejs/npm/manager_test.go, tests/integration/integration_nodejs_acceptance_test.go, tests/integration/integration_python_acceptance_test.go
https://github.com/pulumi/pulumi/pull/16346 introduced the capability to query the language runtime for additional prompts. We use this to let the user pick a package manager among npm, yarn and pnpm during `pulumi new` when using the nodejs runtime.
When there is no explicitly configured package manager, we re-use the previous behaviour for determining the package manager (check `PULUMI_PREFER_YARN` env variable, look for lock files).
Defaults to `npm` when running `new` in non-interactive mode.
=> Add packagemanager prompt to pulumi new for nodejs

changelog/pending/20240621--sdk-go-nodejs-python--add-register-resource-transform-alias-for-register-stack-transform.yaml, sdk/go/pulumi/context.go, sdk/nodejs/runtime/stack.ts, sdk/python/lib/pulumi/runtime/__init__.py, sdk/python/lib/pulumi/runtime/stack.py
In subsequent PRs we're going to introduce transforms for Calls, Invokes and Reads.  Add an alias to the current register stack transforms functions, and deprecate the old version.   This is both for consistency, and because it's a bit confusing that register stack transforms only works for register resource calls, and not other types of pulumi operations.
/xref https://github.com/pulumi/pulumi/issues/16171
=> add RegisterResourceTransform as alias for RegisterStackTransform

changelog/pending/20240621--engine--fix-provider-delete-s-broken-by-16302.yaml, sdk/go/common/resource/plugin/provider_plugin.go
#16302 (78c48204e056d58217bda37c187e2ade5929c040) introduced a regression whereby outputs are mixed up with inputs for provider `Delete`s. This commit fixes the behaviour so that it matches that before the refactoring.
Fixes #16440
=> Fix provider `Delete`

changelog/config.yaml, changelog/pending/20240621--cli-install--make-pulumi-install-work-for-policy-packs.yaml, pkg/cmd/pulumi/install.go, pkg/cmd/pulumi/policy_new.go, pkg/cmd/pulumi/util.go, tests/integration/integration_test.go
With https://github.com/pulumi/pulumi/pull/16411 we removed the manual
instructions telling users how to create virtual environments and
installing dependencies after generating a project with
`--generate-only`. Instead users are instructed to call `pulumi
install`.
However, this also removed the manual installation instructions for
Policy Packs, but `pulumi install` did not know how to deal with Policy
Packs. This PR makes `pulumi install` work for Policy Packs.
Fixes https://github.com/pulumi/pulumi/issues/16437
=> Make pulumi install work for policy packs

changelog/pending/20240621--sdk-python--dont-lift-dunder-attributes-on-output-s.yaml, sdk/python/lib/pulumi/output.py, sdk/python/lib/test/test_output.py
`Output`s are a central part of Pulumi programs. As well as tracking dependencies between resources (e.g. that `A`'s input `x` comes from `B`'s output `y`), they allow us to specify that some value will only be available at a future point (e.g. after a resource has been created or updated). This is typically done in each language by implementing `Output`s using some asynchronous or future value, such as NodeJS's `Promise`. In Python, we use `asyncio` `Task`s.
In order to make `Output`s ergonomic to use, we implement "lifting" of properties in languages that support it. Suppose for instance we have an object `c` that is an instance of the following class `C`:
```python
class C:
x: str
y: int
def __init__(self, x: str, y: int) -> None:
self.x = x
self.y = y
c = C("x", 42)
```
Because `c: …
=> Don't lift dunder attributes on Python `Output`s

changelog/pending/20240621--sdk-nodejs--fix-race-condition-when-registering-stack-transforms.yaml, sdk/nodejs/runtime/callbacks.ts
When registering a stack transform we want to make sure it is finished before any of the subsequent resource registrations are being run.  We try to do this with a `.then`/`.finally` construct.  However the callback that's passed to the `registerStackTransform` function is called asynchronously, and thus the `.finally` may run before the stack transform is actually finished.
Fix this by creating a new promise, and only resolving/rejecting it when the callback has finished running.
Fixes https://github.com/pulumi/pulumi/issues/15639
=> fix race condition when registering stack transform

changelog/pending/20240621--sdk-go--fix-concurrent-map-write-when-registering-transform-callbacks.yaml, sdk/go/pulumi/callback.go
These callbacks can be registered concurrently in Goroutines during register resource calls, making it possible that we write to the map concurrently.  Introduce a lock to avoid that.
Fixes https://github.com/pulumi/pulumi/issues/16203
=> fix potential concurrent map write in Go transforms

changelog/pending/20240624--engine--fix-an-issue-with-asset-archives-not-working-with-paths-outside-the-working-directory.yaml, cmd/pulumi-test-language/l2resourceasset_test.go, cmd/pulumi-test-language/testdata/l2-resource-asset-archive/subdir/main.pp, cmd/pulumi-test-language/tests.go, sdk/go/common/resource/archive/archive.go, sdk/go/common/resource/asset.go, sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsc/projects/l2-resource-asset-archive/subdir/index.ts, sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsnode/projects/l2-resource-asset-archive/subdir/index.ts, sdk/python/cmd/pulumi-language-python/testdata/setuppy/projects/l2-resource-asset-archive/subdir/__main__.py, sdk/python/cmd/pulumi-language-python/testdata/toml/projects/l2-resource-asset-archive/subdir/__main__.py
Fixes https://github.com/pulumi/pulumi/issues/16092.
Hopefully the really last part of the fixes started by https://github.com/pulumi/pulumi/pull/16100 and https://github.com/pulumi/pulumi/pull/16119. This fixes the working directory handling for asset archives.
=> Add asset archive test to conformance tests

changelog/pending/20240621--cli--set-the-continue-on-error-flag-with-pulumi_continue_on_error-environment-variable.yaml, pkg/cmd/pulumi/destroy.go, pkg/cmd/pulumi/flags_test.go, pkg/cmd/pulumi/up.go, sdk/go/common/env/env.go
If the `PULUMI_CONTINUE_ON_ERROR` environment variable is set to a truthy value, it will have the effect of `--continue-on-error` for `up` and `destroy` commands. This helps streamline setting the flag, including through Automation API and Deployments.
Part of #16405 but only for `--continue-on-error` that was specifically requested by a customer. If this lands, we can apply the same pattern elsewhere.
=> Set the --continue-on-error flag with PULUMI_CONTINUE_ON_ERROR environment variable

changelog/pending/20240620--sdk-nodejs--parallelize-construct-and-call-calls-in-the-node-js-sdk.yaml, sdk/nodejs/provider/server.ts
Due to global state issues in the nodejs runtime, we serialized MLC construct requests in #6452.
This had the downside that cloud resources were not created in parallel if multiple instances of the same component were instantiated in the same program.
This change removes the serialization of Construct and Call calls and moves the uncaught error handling into a generic handler that keeps track of all inflight Call/Construct callbacks and responds to them in case of a uncaught error in user code.
The global state issues were already fixed in #10568
Fixes #7629
=> Parallelize Construct and Call calls in the Node.js SDK

pkg/cmd/pulumi/config_env_add_test.go
In this test we're trying to test the console output, when saving properties. We do so by passing "n" to stdin, which then denies the request.  However this is somewhat flaky, because the library sending the confirmation prompt may be able to print the prompt in full before recognizing the character we send on stdin.
There's nothing really wrong with that other than it makes the test flake.  So let's clean the extra output from stdout in case it happens, as it either happening or not happening is just fine.
Fixes https://github.com/pulumi/pulumi/issues/15965
This should hopefully allow us to merge https://github.com/pulumi/pulumi/pull/15960
=> unflake TestConfigEnvAddCmd/no_effects

pkg/cmd/pulumi/deployment.go
New set of commands to manage the stack's deployment settings:
- deployment settings init: initializes the deployment file with information from the environment for the current stack
- deployment settings update: overrides the deployment settings in pulumi cloud with the ones in the deployment file
- deployment settings destroy: clears the deployment settings for the current stack
Fixes # https://github.com/pulumi/pulumi-service/issues/20379
=> New Deployment Settings commands to init, update and clear the config

sdk/go/common/util/cmdutil/term_test.go, sdk/go/common/util/cmdutil/testdata/graceful.py
It is unsafe to call `print` in a Python signalhandler. Instead we set a
flag and check this in the main busy loop.
Fixes https://github.com/pulumi/pulumi/issues/16472
=> Fix TestTerminate_gracefulShutdown/python flake

pkg/cmd/pulumi/config_env_add_test.go
#16477 attempted to fix the flake in the same way as #16468, but the replacement string was incorrect. There should be two spaces between "Yes" and "No" in the replacement string.
Refactor the fix into a helper function, with a comment explaining why we're doing it.
Fixes #16474
=> Fix TestConfigEnvAddCmd flake

changelog/pending/20240624--cli-display--print-a-fully-qualified-stack-name-on-pulumi-stack-show-name-fully-qualify-stack-names.yaml, pkg/cmd/pulumi/stack.go, pkg/cmd/pulumi/stack_test.go
Make `pulumi stack --show-name -Q` print a full stack name including the org and project names:
```
pulumi stack --show-name -Q
mikhail-pulumi-corp/tmp3/dev
```
The actual change is very simple (see the second commit) but I needed to refactor the entire command to be able to easily mock inputs and outputs. Let me know if that makes things worse and I should just do the one-line change without the refactoring.
Fixes https://github.com/pulumi/pulumi/issues/16445
=> Show a fully qualified stack name in `pulumi stack --show-name -Q`

pkg/backend/httpstate/token_source_test.go
The current numbers are too tight on the busy CI runners, where sometimes running the test itself is just a bit slow.  Try to fudge the numbers a bit to make this test less likely to flake.  This won't completely eliminate the problem, but hopefully make it *much* less likely.
=> fudge numbers to avoid flakyness in token renewal tests

pkg/backend/httpstate/token_source_test.go
We attempted to adjust the numbers to help address the flakiness in #16495, but still seeing occurrences of this even with that change. Temporarily skip the test to help unblock merges.
=> Temporarily skip flaky TestTokenSource test

pkg/secrets/cloud/manager_test.go
Creating the secret manager seems to flake frequently for reasons seemingly unrelated to the test itself, but rather cloud provider flakyness.  In particular the AWS backend seems to be somewhat flaky.
Try to work around this by retrying a few times with a backoff.
Fixes https://github.com/pulumi/pulumi/issues/16410 (hopefully).
=> cloud backend test: retry creating secrets manager

changelog/pending/20240627--sdk-nodejs--fix-non-blocking-stdout-err-with-nodejs.yaml, sdk/nodejs/cmd/pulumi-language-nodejs/main.go
Node will sometimes set stdout or stderr into non-blocking mode, but go
will not notice this. When go attempts to write, we get an error: `write
/dev/stdout: resource temporarily unavailable`. To avoid this issue, we
copy the output of the command to the stdout and stderr of the go
process.
https://github.com/golang/go/issues/58408#issuecomment-1423621323
Fixes https://github.com/pulumi/pulumi/issues/16503
=> Fix non-blocking stdout/err with nodejs

.github/workflows/ci.yml, .github/workflows/on-merge.yml
Whenever anything fails in CI, we don't want to continue the rest of the CI builds to save time and resources.  Setting the fail-fast property should abort the jobs when anything fails.
=> fail fast whenever a job fails

pkg/backend/httpstate/token_source_test.go
`TestTokenSourceWithQuicklyExpiringInitialToken` is flaking like `TestTokenSource`. Skip it like we did in #16501.
=> Skip TestTokenSourceWithQuicklyExpiringInitialToken

pkg/cmd/pulumi/state.go, pkg/cmd/pulumi/state_move.go, pkg/cmd/pulumi/state_move_test.go, pkg/resource/graph/dependency_graph.go, pkg/resource/stack/checkpoint.go, sdk/go/common/resource/urn/urn.go
Implement a skeleton command for `pulumi state move`.  This can so far only more a single resource from one stack to another, including copying the provider it needs, and leave valid state files behind.
These state files are not written to the backend yet, nor is there any kind of UI.  Further PRs will build on top of this.
The command is intentionally commented out so this can be merged independently.
---
Based on discussions in the last retro, I'm trying something new here and try to split the PR up some more into chunks that can be individually merged, but are not completely ready yet.  The code added here is essentially dead code at this point, but provides a skeleton to incrementally add pieces.
To give an idea of where this is headed, the next things I'm planning to work on here …
=> implement skeleton command for `pulumi state move`

scripts/get-job-matrix.py
Listing tests sometimes fails for reasons that are hard to understand. Also show stdout and stderr in the CI output to make it easier to track down why it failed.
I can't for the life of me figure out what's going on in https://github.com/pulumi/pulumi/pull/16493, and I think this might help.
=> also show stdout and stderr when listing tests fails

changelog/pending/20240626--sdk-nodejs--fix-construct-and-call-calls-in-the-node-js-sdk-sharing-state.yaml, sdk/nodejs/provider/server.ts
In #16428 we parallelized the call&construct calls of the node provider server. It was wrongly assumed that the state of the settings are localized to the current call, but that is only done when running in `asyncLocalStorage.run`.
This change wraps the call&construct calls in `asyncLocalStorage.run` to correctly localize state.
Addresses https://github.com/pulumi/pulumi/pull/16428#issuecomment-2190932525
=> Wrap call&construct of node provider server in AsyncLocalStorage

.github/workflows/ci-build-binaries.yml, .github/workflows/ci-info.yml, .github/workflows/ci-run-test.yml, .github/workflows/ci-test-docs-generation.yml, .github/workflows/on-push.yml, .github/workflows/pr-test-codegen-downstream.yml
PULUMI_BOT_TOKEN is a shared resource across the company and we should be using it as little as possible.  This will hopefully help us bump into the API rate limit less.
Do this using a combination of
- not installing stuff we don't seem to need
- using `secrets.GITHUB_TOKEN` instead.  `secrets.GITHUB_TOKEN` is scoped per repository, so any excessive usage is solely on us to fix.
I'm not entirely sure if this is going to make things better or worse, but I've seen internal complaints about pulumi-bot getting rate limited, and this should help with that.
=> reduce the usage of PULUMI_BOT_TOKEN

.github/workflows/ci-run-test.yml
#16521 deleted the top-level line that declared the `GITHUB_TOKEN` envvar in `ci-run-test.yml`. This has the downside that when running tests, the envvar isn't set, so when we try to do plugin acquisition, we quickly hit rate limits. This commit sets the envvar for the step running the tests.
=> ci: Set `GITHUB_TOKEN` when running tests

.github/workflows/ci-build-binaries.yml, .github/workflows/ci-build-sdks.yml, .github/workflows/ci-dev-release.yml, .github/workflows/ci-prepare-release.yml, .github/workflows/ci-run-test.yml, .github/workflows/ci.yml, .github/workflows/sign.yml
v2 of `actions/upload-artifact` and `actions/download-artifact` will be deprecated on June 30, 2024. This commit bumps the versions of these actions to v4. The main breaking change between v2/v3 and v4 is that artifacts are now immutable, so multiple uploads to artifacts with the same name will fail by default. In this case there are two options -- use different names, and recollect the artifacts later with a modified `download-artifact` instantiation, or pass `overwrite: true` to calls which will happen later to first delete the artifact and create a new one in its place. It _appears_ that we only fall foul of repeated uploads in one place, and that for this case we can use `overwrite`, so that is the approach this commit takes.
=> Update `upload-artifact` and `download-artifact` actions

sdk/nodejs/cmd/pulumi-language-nodejs/main.go
Fix a typo "packagemangager" -> "package manager"
=> Fix a typo in user prompt

changelog/pending/20240628--auto--protect-access-to-transport-unsupportedcapabilities-inside-repo-fetchcontext.yaml, sdk/go/auto/git.go
repo.FetchContext reads transport.UnsupportedCapabilities, which we modify, leading to a potential data race in oncurrent calls to setupGitRepo.
Wrap the call to repo.FetchContext with the global transportMutex.
Fixes https://github.com/pulumi/pulumi/issues/16516
=> Protect access to transport.UnsupportedCapabilities inside repo.FetchContext

changelog/pending/20240627--sdk-python--wait-for-pending-tasks-before-shutting-down-python-programs.yaml, sdk/python/cmd/pulumi-language-python-exec
Fixes https://github.com/pulumi/pulumi/issues/16025.
Looks like shutting down the executor and waiting for it to finish pending tasks should stop callbacks being triggered after we then close the event loop.
=> Make sure the aio executor shutsdown before the event loop

changelog/pending/20230928--sdk-python--adds-exclude-protect-to-destroy-command.yaml, sdk/python/lib/pulumi/automation/_stack.py, sdk/python/lib/test/automation/test_local_workspace.py
This commit rebases @Maradonna90's PR #14066 to add support for `destroy`'s `--exclude-protected` argument to the Python automation SDK. This addresses the Python part of #12733.
Closes #14066
=> Support `--exclude-protected` for `destroy` in the Python automation SDK

changelog/pending/20240626--sdk-nodejs-python--display-an-actionable-error-message-when-dependency-installation-fails.yaml, pkg/cmd/pulumi/new.go, sdk/nodejs/cmd/pulumi-language-nodejs/main.go, sdk/nodejs/npm/npm.go, sdk/nodejs/npm/pnpm.go, sdk/nodejs/npm/yarn.go, sdk/python/toolchain/poetry.go
When the dependency installation fails because we could not find the
packagemanager executable, tell the user how to remedy the error and
finish the dependency installation.
Example:
```
The packagemangager to use for installing dependencies pnpm
Installing dependencies...
error: installing dependencies failed: Could not find `pnpm` executable.
Install pnpm from https://pnpm.io/installation and make sure it is in your PATH.
Run `pulumi install` to complete the installation.
```
=> Display an actionable error message when dependency installation fails

.github/workflows/on-merge.yml
This might actually kill all jobs instead of just the jobs related to the failed one.
=> mark the whole CI workflow as fail-fast

.github/workflows/ci-run-test.yml, .github/workflows/ci.yml, .github/workflows/on-merge.yml
We recently tried to remove the retry script from this repo.  However there were too many flaky tests, which made merging anything very difficult.  This was however a very useful exercise to remove some flaky tests, which would be useful to continue doing.
To compromise on that, run tests with retries in the merge queue, but don't do retries in other situations, such as PRs.  It's easier to retry tests manually there anyway, but flaky tests are still going to be more likely to be noticed.
=> only retry tests when they are running in the merge queue

pkg/backend/httpstate/backend.go, pkg/backend/httpstate/mock.go, pkg/cmd/pulumi/deployment.go, pkg/cmd/pulumi/destroy.go, pkg/cmd/pulumi/preview.go, pkg/cmd/pulumi/refresh.go, pkg/cmd/pulumi/up.go, pkg/cmd/pulumi/util_remote.go, pkg/go.sum, sdk/go/common/apitype/deployments.go
Add new deployment run command
Fixes https://github.com/pulumi/pulumi-service/issues/20500
=> Update pu/pu to support deployment run command

changelog/pending/20240701--sdk-python--provide-installation-instructions-for-the-python-typechecker.yaml, sdk/python/cmd/pulumi-language-python/main.go, tests/integration/integration_python_acceptance_test.go, tests/integration/python/pyright-missing/.gitignore, tests/integration/python/pyright-missing/Pulumi.yaml, tests/integration/python/pyright-missing/__main__.py, tests/integration/python/pyright-missing/requirements.txt
When the typechecker option is set, but the selected typechecker is not installed in the project's virtual environment, the pulumi operation will fail with an unhelpful message like `mypy failed: exit status 1`.
To make this more actionable, we check if the typechecker is installed, and if not, we provide installation instructions to remediate the issue.
=> Provide installation instructions for the python typechecker

changelog/pending/20240701--cli--disable-default-cobra-completions-in-the-cli.yaml, pkg/cmd/pulumi/pulumi.go
The Pulumi CLI provides a customised shell completion command, `gen-completion`, that can be used to generate scripts that enable tab completion in shells such as Bash and Zsh. When providing custom generation commands, Cobra (the library we use to build the Pulumi CLI) [recommends disabling the default completion command](https://github.com/spf13/cobra/blob/main/site/content/completions/_index.md#adapting-the-default-completion-command). This commit rebases @EthanOrlander's work in #7842 on `master` and disables the default command in the recommended manner.
This is technically a breaking change in the interface of the CLI, but since we'd (presumably) rather that users were only using the officially supported completions that Pulumi itself maintains, this feels like us fixing a bug/the …
=> Disable default Cobra completion commands

sdk/nodejs/runtime/mocks.ts, sdk/nodejs/tests_with_mocks/mocks.spec.ts
This commit incorporates the tests introduced by @henriiik in #8585 into the existing test suite for the NodeJS SDK mocks. SDK mocks provide a means for users wishing to unit test their Pulumi programs to stub out various bits of Pulumi behaviour. Previously, those wanting to stub out resource reads (through `.get` static methods) would encounter crashes or use untested code paths. With the crashes fixed in previous commits, this commit adds some tests. Moreover, we fix an error whereby mock reads force a non-custom (component) resource, when in reality it should be the other way around (since reads don't make sense for component resources).
Closes #8585
=> Fix NodeJS SDK mocking of custom resource reads

pkg/cmd/pulumi/state_move.go, sdk/go/common/resource/urn/urn.go, sdk/go/common/resource/urn/urn_test.go
When a resource is moved between stacks in different projects we also need to rewrite project part of the URNs.  Do that here.  Moving between different projects already works by virtue of the requireStack function supporting that when providing the fully qualified name of the stack.
There is some awkwardness here as old diy backends may not return a project name, in which case we error out here.  Curious if anyone has thought about what to do here.  Is erroring out the best we can do?  What happens if we don't rewrite the project name in this case?
=> rewrite the URN when resources are being moved between projects

.github/workflows/ci.yml
Upgrade the `codecov/codecov-action` to `v4` to avoid warnings (it supports Node 20):
https://github.com/pulumi/pulumi/actions/runs/9752874835
=> Upgrade `codecov/codecov-action`

.github/workflows/ci-dev-release.yml, .github/workflows/pr-test-codegen-downstream.yml, .github/workflows/release.yml
Upgrade to the latest version of the `aws-actions/configure-aws-credentials` action to avoid warnings:
https://github.com/pulumi/pulumi/actions/runs/9753818750
=> Upgrade `aws-actions/configure-aws-credentials`

changelog/pending/20240520--engine--guess-references-to-deeply-nested-properties-between-dependant-resources-during-import.yaml, pkg/cmd/pulumi/import.go, pkg/importer/hcl2.go, pkg/importer/hcl2_test.go, pkg/importer/language.go, pkg/importer/language_test.go
Following up and extending #16208 such that now we guess references to _properties_ `name` and `arn` between dependant resources when running an import based on their literal data retrieved from providers.
=> [engine/import] Guess references to properties between dependant resources during import

pkg/codegen/schema/bind.go, pkg/codegen/schema/pulumi.json, pkg/codegen/schema/schema.go
This adds the parameterisation spec to the pulumi schema. This will allow providers to take a dependency on these types to start defining parameterized schemes from tfbridge.
They _should not_ be considered completely stable. We may still need to change things here as work continues.
=> Add Paramaterization to the Pulumi schema

changelog/pending/20240702--programgen-python--fix-python-program-generation-for-remote-assets.yaml, pkg/codegen/python/gen_program_expressions.go, tests/testdata/codegen/assets-archives-pp/python/assets-archives.py
This commit fixes Python code generation (specifically, program generation) whereby we were previously emitting calls to the non-existent `remoteAsset` function/constructor. We now use the (correct) `RemoteAsset` constructor, in line with other asset types exposed by the Python SDK.
=> Fix Python program generation for remote assets

.github/workflows/on-pr.yml
This is always safe because we're running all tests in the merge queue again.  Having ci-ok is mostly useful for us as a check so we don't drop stuff on the merge queue that won't succeed anyway.
=> always mark ci-ok as green for community PRs

cmd/pulumi-test-language/l2resourceasset_test.go, cmd/pulumi-test-language/testdata/l2-resource-asset-archive/subdir/main.pp, cmd/pulumi-test-language/tests.go, sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsc/projects/l2-resource-asset-archive/subdir/index.ts, sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsnode/projects/l2-resource-asset-archive/subdir/index.ts, sdk/python/cmd/pulumi-language-python/testdata/setuppy/projects/l2-resource-asset-archive/subdir/__main__.py, sdk/python/cmd/pulumi-language-python/testdata/toml/projects/l2-resource-asset-archive/subdir/__main__.py
Conformance tests allow us to test functionality regardless of programming language used, by setting up a test program using PCL and making assertions about program state before and after various operations. This commit adds a set of conformance tests for remote assets (that is, assets that must be retrieved from some URI), which have until now been untested in this regard.
=> Add conformance tests for remote assets

changelog/pending/20240703--sdk-nodejs--add-dependson-to-invokeoptions-in-the-nodejs-sdk.yaml, sdk/nodejs/invoke.ts, sdk/nodejs/runtime/dependsOn.ts, sdk/nodejs/runtime/invoke.ts, sdk/nodejs/runtime/resource.ts, sdk/nodejs/tests/runtime/langhost/cases/043.depends_on_non_resource/index.js, sdk/nodejs/tests/runtime/langhost/cases/075.invoke_depends_on/index.js, sdk/nodejs/tests/runtime/langhost/cases/076.invoke_depends_on_non_resource/index.js, sdk/nodejs/tests/runtime/langhost/run.spec.ts, sdk/nodejs/tsconfig.json
This commit adds support for passing `dependsOn` to invokes (whether streamed or not) in the NodeJS SDK. This allows programs to ensure that certain invokes are executed after things they depend on, even if that dependency is not implicitly captured with an input-output relationship.
Part of #14243
=> Implement `dependsOn` for invokes in the NodeJS SDK

.github/workflows/on-pr.yml
In #16567 we added a step for skipping `ci-ok` for community PRs (since these PRs have their acceptance tests run in a workflow separate to the PR being checked). However, we didn't modify the default step not to run in this case, so we still see failures for community PRs. This commit fixes that.
=> Fix conditional execution of `ci-ok` for community PRs

changelog/pending/20240703--backend-service--retry-post-requests-that-time-out-during-handshake-timeouts.yaml, pkg/backend/httpstate/client/api.go, sdk/go/common/util/httputil/http.go
We've had quite a few test flakes that happen because of TLS handshake timeouts to the service backend.  These are usually during stack creation (which happens a lot during tests), which are POST requests.
POST requests are not generally safe to retry, because the request could already have been sent to the backend and an action taken, but the client couldn't read the response.  However when there is a TLS handshake failure, the request can never have made it to the backend, so these errors are safe to retry.
This should hopefully help with https://github.com/pulumi/pulumi/issues/16529.
=> retry post requests that timeout during handshake

pkg/backend/backend.go, pkg/backend/diy/backend.go, pkg/backend/httpstate/backend.go, pkg/backend/httpstate/client/client.go, pkg/backend/mock.go, pkg/cmd/pulumi/deployment.go, sdk/go/common/apitype/deployments.go, sdk/go/common/util/cmdutil/console.go, sdk/go/common/util/gitutil/git.go, sdk/go/common/util/gitutil/git_test.go, sdk/go/common/workspace/loaders.go
- Turns `deployment settings init` command a wizard
- Adds new `deployment settings env` command to manage env variables (including secrets encryption)
- Adds new `deployment settings set` command to configure individual settings (including secrets encryption)
https://asciinema.org/a/QhuWHAvkmeAmVJkYqkCP0P6wb
Fix https://github.com/pulumi/pulumi-service/issues/20567
Fix https://github.com/pulumi/pulumi-service/issues/20576
=> New deployment settings wizards and environment variables management comands

changelog/pending/20240703--docs--fix-generating-constructor-syntax-examples-for-kubernetes.yaml, pkg/codegen/docs/constructor_syntax_generator.go, pkg/codegen/go/gen_program_expressions.go, pkg/codegen/go/gen_program_ternaries.go, tests/testdata/codegen/azure-native-pp/go/azure-native.go, tests/testdata/codegen/kubernetes-pod-pp/go/kubernetes-pod.go, tests/testdata/codegen/kubernetes20/docs/core/v1/configmap/_index.md, tests/testdata/codegen/kubernetes20/docs/core/v1/configmaplist/_index.md, tests/testdata/codegen/kubernetes20/docs/helm/v3/release/_index.md, tests/testdata/codegen/kubernetes20/docs/yaml/configgroup/_index.md, tests/testdata/codegen/kubernetes20/docs/yaml/v2/configgroup/_index.md
In this PR we fix generating constructor syntax examples for Kubernetes. The problem initially was due to generating a PCL program with syntax errors for the kubernetes schema. The syntax error was happening because we emitted properties `$ref` and `$schema` which are not valid identifiers in PCL. Fixing this was simple enough, we only needed to quote these properties that start with dollar signs and we get a valid PCL program. 
Full PCL program for kubernetes: https://gist.github.com/Zaid-Ajaj/abe899430a0b5f99a428934dcac75d52
However, the valid PCL program wouldn't convert to Go with program-gen and it would hang without showing any errors or stack traces. I wrote a script to split the programs for each resource and convert each separately. This way I narrowed down the problem to this …
=> [docs/go-program-gen] Fix generating constructor syntax examples for kubernetes

changelog/pending/20240703--sdk-go--fix-slice-bounds-out-of-range-panic-in-fixuppath.yaml, sdk/go/auto/cmd.go, sdk/go/auto/cmd_test.go
I noticed that sst currently panics if an environment variable's name is shorter than 5 characters. This fixes the root cause.
```
V=1 sst deploy --stage=dev 
SST ❍ ion 0.0.416  ready!
➜  App:        myapp
Stage:      dev
~  Deploying
panic: runtime error: slice bounds out of range [:5] with length 3
goroutine 1 [running]:
github.com/pulumi/pulumi/sdk/v3/go/auto.fixupPath({0x140018ec408, 0xb1, 0x1400013dfc0?}, {0x1400013dfc0, 0x32})
/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.115.2/go/auto/cmd.go:324 +0x270
github.com/pulumi/pulumi/sdk/v3/go/auto.pulumiCommand.Run({{0x3, 0x73, 0x2, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}}, {0x1400013dfc0, ...}}, ...)
/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.115.2/go/auto/cmd.go:273 +0x394 …
```
=> Fix slice bounds out of range panic in fixupPath

changelog/pending/20240702--sdk-nodejs--fix-creating-a-closure-with-object-getters-and-setters.yaml, sdk/nodejs/runtime/closure/parseFunction.ts, sdk/nodejs/tests/runtime/testdata/closure-tests/cases/176-getter/index.ts, sdk/nodejs/tests/runtime/testdata/closure-tests/cases/176-getter/snapshot.txt
Fixes #16541 
Hi,
this is an attempt to fix #16541 , feedback is greatly appreciated!
I was not able to test if the result works as expected, I just adjusted the code and manually created a test snapshot from the mocha console output until I thought it looked right.
Could someone tell me...
1. how to actually build the `@pulumi/pulumi` package and how to test the fixes quickly?
2. how to create a snapshot for a new closure test?
3. if there is a quick way to write the TypeScript code in this project, set breakpoints and run tests against it?
- I plan to investigate the pnpm bundling bug of the `CallbackFunction` but working on this and testing the code is extremely tedious right now as I do not know your secrets (yet 😀)
- I didn't find these infos in the `CONTRIBUTING.md` and other …
=> Fix usage of getters and setters in Lambda callback functions

.github/workflows/on-pr.yml
This will fail because we don't have the repo checked out. We don't
require this to pass for community PRs (tests are run "manually" via a
maintainer command), so skip it to keep things tidyer.
=> Skip the inspect step for community PRs

changelog/pending/20240708--cli-new--use-default-values-for-language-specific-prompts-when-using-yes.yaml, pkg/cmd/pulumi/new.go, tests/integration/integration_python_acceptance_test.go
When passing `yes` in interactive mode (or non-interactive mode), language specific options should use their deafult values without prompting the user.
=> Use default values for language specific prompts when using --yes

changelog/pending/20240705--programgen-go--do-not-emit-index-module-for-resources-without-a-schema.yaml, pkg/codegen/go/gen_program.go, tests/testdata/codegen/unknown-invoke-pp/go/unknown-invoke.go, tests/testdata/codegen/unknown-resource-pp/go/unknown-resource.go
For resources that don't have a schema, we emit a best guess for how they are declared and how imports should be emitted. For these resources we emit `index.{ResourceName}` if that resource is from the index module, however this is not how resources are usually generated, instead we should generate `{packageName}.{ResourceName}` for resources from the index module which is what this PR resolves. 
Fixes #16461
=> [go/program-gen] Do not emit index module for resources without a schema

changelog/pending/20240704--docs--fix-generating-constructor-syntax-examples-in-go-for-package-awsx.yaml, pkg/codegen/go/gen_program_expressions.go, pkg/codegen/pcl/binder_resource.go, pkg/codegen/pcl/binder_test.go, tests/testdata/codegen/aws-static-website-pp/dotnet/aws-static-website.cs, tests/testdata/codegen/embedded-crd-types/docs/component/_index.md, tests/testdata/codegen/enum-reference/docs/myModule/iamresource/_index.md, tests/testdata/codegen/external-resource-schema/docs/component/_index.md, tests/testdata/codegen/simple-plain-schema/docs/component/_index.md
Currently, when generating docs for the AWSX package, Go constructor syntax examples were not generated due to a panic. This causes all constructor examples to not be emitted in the docs. 
The panic occurred when trying to get the version of referenced packages in the PCL program to emit import paths. However, _transitive_ package references were not resolved in the PCL binder when binding resource types. This PR fixes the problem such that now we do find the transitive package references from any input or output property of the resources being bound. 
In the case of the awsx package, the top-level package is awsx itself and aws is the transitive dependency. Anytime in codegen we call `program.PackageReferences()` we should get both of them. Added a unit test for this as well. 
Testing …
=> [docs/go-program-gen] Fix generating constructor syntax examples in Go for package awsx

pkg/cmd/pulumi/state_move.go, pkg/cmd/pulumi/state_move_test.go
Add more tests for moving children, and for breaking dependencies/property dependencies/deleted with attributes.
This also fixes a couple of bugs that were discovered while testing.
Depends on: https://github.com/pulumi/pulumi/pull/16527
=> state_move: add more tests and a couple of fixes

.github/workflows/ci-build-binaries.yml, .github/workflows/ci-lint.yml, .github/workflows/ci-run-test.yml, .github/workflows/ci-test-docs-generation.yml, changelog/pending/20240710--ci--use-latest-patch-version-of-go-in-ci.yaml
We pass a version like `1.22.x` for go, which results in the setup-go
action using a cached version, even if there is a more recent release
available. Set `check-latest: true` to ensure we're always using the latest
release, picking up any security fixes.
Unblocks https://github.com/pulumi/pulumi/pull/16608
=> Use latest patch version of go in CI

pkg/codegen/schema/pulumi.json, pkg/codegen/schema/schema.go
Follow on to https://github.com/pulumi/pulumi/pull/16606. Allow the schema to express any bytes value.
=> Change parameterization in schemas to base64 strings

sdk/nodejs/automation/cmd.ts, sdk/nodejs/automation/config.ts, sdk/nodejs/automation/errors.ts, sdk/nodejs/automation/events.ts, sdk/nodejs/automation/localWorkspace.ts, sdk/nodejs/automation/minimumVersion.ts, sdk/nodejs/automation/projectSettings.ts, sdk/nodejs/automation/remoteStack.ts, sdk/nodejs/automation/remoteWorkspace.ts, sdk/nodejs/automation/server.ts, sdk/nodejs/automation/stack.ts, sdk/nodejs/automation/stackSettings.ts, sdk/nodejs/automation/tag.ts, sdk/nodejs/automation/workspace.ts
This commit improves the TypeScript TypeDocs for `automation` modules in the NodeJS SDK. Specifically:
* It adds documentation to interfaces, properties, etc. that are missing it.
* It transforms would-be TypeDoc comments erroneously written using either `/*` (a single asterisk) or `//` (a normal line comment) to actual TypeDoc comments.
* It standardises on TypeDoc's `{@link Name}` syntax for linking identifiers, as opposed to the mixture of backticks and square brackets we have today. This helps IDEs as well as (hopefully) improving any rendered documentation.
* It fixes typos and generally cleans up the formatting here and there, as well as introducing more consistency where the same concepts crop up in multiple places.
=> Improve TypeDocs for `sdk/nodejs/automation`

pkg/cmd/pulumi/state_move.go, pkg/cmd/pulumi/state_move_test.go
When the user tries to move a resource that would end up being a duplicate in the destination stack, we need to prevent that, to avoid a broken state file.
Error out in this case.
Depends on: https://github.com/pulumi/pulumi/pull/16543
=> error out on duplicate providers/resources

changelog/pending/20240711--cli-state--introduce-a-state-move-command-that-can-be-used-to-move-resources-between-stacks-projects.yaml, pkg/cmd/pulumi/state_move.go
Now that we implemented all the features for this command we can remove the hidden flag, and actually start letting users use it.
=> state_move: mark command as non-hidden

pkg/codegen/schema/mock_pulumi_schema.go
Part of pulumi/pulumi-yaml#599.
Pulumi YAML uses the schema defined here to type check outputs from the `pulumi:pulumi:StackReference` resource. This changes the type of `outputs` from `map[string]string` to `map[string]any`, permitting list, map, and numeric outputs to be used as inputs to other resources.
To release this fix, we will need to release Pulumi twice and YAML once if we are to use our ordinary release process:
1. Merge this PR.
2. Release sdk and pkg dependencies with this update applied.
3. Merge https://github.com/pulumi/pulumi-yaml/pull/600
4. Create and merge a PR to update Pulumi YAML's dependency on `github.com/pulumi/pkg/v3`, as YAML links to the schema loader and will read the updated schema here:
https://github.com/pulumi/pulumi/blob/7f48ca370d12e6d7fee29b7e1b6f87c9f …
=> Fix incorrect YAML type checking of StackReference outputs

changelog/pending/20240711--sdk-nodejs--dont-count-plugins-from-a-nested-policy-pack-in-getrequiredplugins.yaml, sdk/nodejs/cmd/pulumi-language-nodejs/main.go, sdk/nodejs/cmd/pulumi-language-nodejs/main_test.go
For nodejs we look at the node_modules of all child directories of the
root path to find the required plugins. When a policy pack is nested
within a pulumi project, we were including its dependencies in the list
of required plugins. To avoid this, we stop recursing once we see a
directory that has a PulumiPolicy.yaml.
Fixes https://github.com/pulumi/pulumi/issues/16604
=> Don't count plugins from a nested policy pack in GetRequiredPlugins

changelog/pending/20240711--cli-new--install-policy-or-project-dependencies-based-on-nearest-configuration-file.yaml, pkg/cmd/pulumi/install.go, tests/integration/integration_test.go
When a policy pack is nested within a project, or vice-versa, install
the appropriate dependencies, based on where the command is run from.
If there are both policy pack and project files in the parent
directories of the current working directory, pick the one that is
closest.
Fixes https://github.com/pulumi/pulumi/issues/16605
=> Install policy or project dependencies based on nearest configuration file

pkg/cmd/pulumi/state_move.go
Correct the usage text, and mark the command not as non-experimental. The command should be ready for regular usage, so I think the "EXPERIMENTAL" comment can be dropped now.
=> state_move: improve usage text

changelog/pending/20240712--engine--fix-an-issue-where-pulumi-up-continue-on-error-could-result-in-a-snapshot-integrity-failure.yaml, pkg/engine/lifecycletest/continue_on_error_test.go, pkg/resource/deploy/deployment_executor.go
When running `pulumi up --continue-on-error`, we can't bring up new resources that have dependencies that have failed, or have been skipped.  Since the resource would have a failed dependency, that dependency would not be in the snapshot, resulting in a snapshot integrity failure.  Also it simply does not make sense to `up` a resource that has a failed dependency.
We took care of that for the regular dependency relationship, however at the time we missed doing the same for other types of dependencies, namely parent-child relationships, deleted with relationships and property dependencies.
This can result in snapshot integrity failures for example when a parent fails to be created, but we still do the resource creation of the child, such as what happened in …
=> continue-on-error: respect all dependency relationships

changelog/pending/20240712--sdk-nodejs--fix-lookup-for-pulumi-run-script-when-using-volta-to-manage-nodejs.yaml, sdk/nodejs/cmd/pulumi-language-nodejs/main.go
We run a short script with nodejs to find the path to the nodejs SDK
entrypoint. In https://github.com/pulumi/pulumi/pull/16160 this script
was changed and used newlines.
This broke when using the Volta package manager to manage different
nodejs versions. Volta adds shim programs into the user's path that
routes to the correct nodejs executable. Seemingly Volta does not handle
the newlines in the arguments.
To fix this, we ensure that the script is on a single line.
Fixes https://github.com/pulumi/pulumi/issues/16393
=> Fix lookup for pulumi run script when using Volta to manage nodejs

changelog/pending/20240710--sdk-go--add-support-for-invoke-transforms.yaml, sdk/go/pulumi/context.go, sdk/go/pulumi/transform.go, tests/integration/transforms/go/simple/main.go, tests/integration/transforms/go/simple/random.go, tests/integration/transforms/transforms_test.go, tests/testprovider/main.go
Add support to the Go SDK for invoke transforms.  This only adds support for setting transforms globally, not yet via a resource option, which resource transforms allow.
=> add Go support for invoke transforms

sdk/nodejs/asset/archive.ts, sdk/nodejs/asset/asset.ts, sdk/nodejs/dynamic/index.ts, sdk/nodejs/errors.ts, sdk/nodejs/invoke.ts, sdk/nodejs/iterable/index.ts, sdk/nodejs/log/index.ts, sdk/nodejs/metadata.ts, sdk/nodejs/output.ts, sdk/nodejs/provider/internals.ts, sdk/nodejs/provider/provider.ts, sdk/nodejs/provider/server.ts, sdk/nodejs/queryable/index.ts, sdk/nodejs/resource.ts, sdk/nodejs/stackReference.ts, sdk/nodejs/tsutils.ts, sdk/nodejs/utils.ts
This commit improves the TypeScript TypeDocs for the remaining modules in the NodeJS SDK. Specifically:
* It adds documentation to interfaces, properties, etc. that are missing it.
* It transforms would-be TypeDoc comments erroneously written using either `/*` (a single asterisk) or `//` (a normal line comment) to actual TypeDoc comments.
* It standardises on TypeDoc's `{@link Name}` syntax for linking identifiers, as opposed to the mixture of backticks and square brackets we have today.
* It fixes typos and generally cleans up the formatting here and there, as well as introducing more consistency where the same concepts crop up in multiple places.
=> Improve TypeDocs for `sdk/nodejs`

sdk/nodejs/runtime/asyncIterableUtil.ts, sdk/nodejs/runtime/callbacks.ts, sdk/nodejs/runtime/closure/codePaths.ts, sdk/nodejs/runtime/closure/createClosure.ts, sdk/nodejs/runtime/closure/parseFunction.ts, sdk/nodejs/runtime/closure/rewriteSuper.ts, sdk/nodejs/runtime/closure/serializeClosure.ts, sdk/nodejs/runtime/closure/utils.ts, sdk/nodejs/runtime/closure/v8.ts, sdk/nodejs/runtime/closure/v8Hooks.ts, sdk/nodejs/runtime/config.ts, sdk/nodejs/runtime/debuggable.ts, sdk/nodejs/runtime/invoke.ts, sdk/nodejs/runtime/mocks.ts, sdk/nodejs/runtime/resource.ts, sdk/nodejs/runtime/rpc.ts, sdk/nodejs/runtime/settings.ts, sdk/nodejs/runtime/stack.ts, sdk/nodejs/runtime/state.ts
This commit improves the TypeScript TypeDocs for `runtime` modules in the NodeJS SDK. Specifically:
* It adds documentation to interfaces, properties, etc. that are missing it.
* It transforms would-be TypeDoc comments erroneously written using either `/*` (a single asterisk) or `//` (a normal line comment) to actual TypeDoc comments.
* It standardises on TypeDoc's `{@link Name}` syntax for linking identifiers, as opposed to the mixture of backticks and square brackets we have today.
* It fixes typos and generally cleans up the formatting here and there, as well as introducing more consistency where the same concepts crop up in multiple places.
=> Improve TypeDocs for `sdk/nodejs/runtime`

.github/workflows/ci-info.yml, .github/workflows/ci-prepare-release.yml, .github/workflows/on-pr-changelog.yml, .github/workflows/on-pr.yml, .github/workflows/pr-test-codegen-downstream.yml
There's a few instances where I *think* we can use the GITHUB_TOKEN we get from actions, so we can try to avoid ratelimits.
All of these jobs should be running during PRs, so it should be relatively safe if the CI tests pass.
=> try to further reduce the pulumi bot token usage

pkg/codegen/go/gen_program.go
Rather than writing a go.mod with string lerping, this uses the "golang.org/x/mod/modfile" to construct and render the go.mod files we generate for programs.
=> Use modfile to generate the go.mod in GenerateProgram

changelog/pending/20240715--pkg-testing--clean-up-pulumi_home-after-program-test.yaml, pkg/testing/integration/program.go
Clean up the temporary `PULUMI_HOME` directory we create during a program test.
This is necessary to reclaim the disk space of the plugins that were downloaded
during the test.
In pulumi-aws we started seeing test failures because the CI runners started running out of disk space due to plugins in `PULUMI_HOME` not being cleaned up.
=> Clean up PULUMI_HOME after program test

changelog/pending/20240715--sdkgen-go--importbasepath-will-default-to-a-pulumi-github-base-path.yaml, pkg/codegen/go/gen.go, tests/testdata/codegen/output-funcs-edgeorder/go/myedgeorder/init.go, tests/testdata/codegen/output-funcs-edgeorder/go/myedgeorder/listConfigurations.go, tests/testdata/codegen/output-funcs-edgeorder/go/myedgeorder/listProductFamilies.go, tests/testdata/codegen/output-funcs-edgeorder/go/myedgeorder/provider.go, tests/testdata/codegen/output-funcs-edgeorder/go/myedgeorder/pulumiTypes.go, tests/testdata/codegen/provider-config-schema/go/configstation/config/config.go, tests/testdata/codegen/provider-config-schema/go/configstation/config/pulumiTypes.go, tests/testdata/codegen/provider-config-schema/go/configstation/funcWithAllOptionalInputs.go, tests/testdata/codegen/provider-config-schema/go/configstation/init.go, tests/testdata/codegen/provider-config-schema/go/configstation/provider.go, tests/testdata/codegen/provider-config-schema/go/configstation/pulumiTypes.go
This fixes go package generation so users don't _have_ to set the import base path explicitly in the go info part of the schema. This only really helps our packages (because we assume the path is "github.com/pulumi") but it fixes some of the generated test data and should also work for local SDKs, where they aren't _really_ at "github.com/pulumi" but also that it doesn't matter what URL is used as long as it's a valid one.
Fixes https://github.com/pulumi/pulumi/issues/13756
=> Default the import base path to something sensible

changelog/pending/20240715--sdk-python--fix-yaml-serialization-of-project-settings-in-the-python-automation-api.yaml, sdk/python/lib/pulumi/automation/__init__.py, sdk/python/lib/pulumi/automation/_local_workspace.py, sdk/python/lib/pulumi/automation/_project_settings.py, sdk/python/lib/test/automation/test_project_settings.py
The Python Automation API SDK serializes project settings (the contents of `Pulumi.yaml` files) using Python's `pyyaml` package. Project settings in the Python Automation API SDK are represented as instances of the `ProjectSettings` class. By default, `pyyaml` will serialize class instances as YAML objects "tagged" with a string that indicates their class. This is so that, upon deserialization, it can construct objects of the appropriate class (as opposed to, just dictionaries). As an example, the following Python program:
```python
class Person:
def __init(self, name: str, age: int) -> None:
self.name = name
self.age = age
will = Person("will", 37)
yaml.dump(will)
```
will produce the following YAML:
```yaml
!!python/object:__main__.Person
age: 37
name: will
```
The string …
=> Fix YAML serialization of project settings in the Python Automation API

changelog/pending/20240716--sdk-python--fix-a-recursionerror-with-deeply-nested-componentresources.yaml, sdk/python/lib/pulumi/runtime/rpc.py
CPython doesn't optimize tail recursion, and because of that has a fairly low recursion limit set to avoid stack overflows.  This also means that where we rely on recursion we are prone to raising `RecursionError`s.  In this particular case, `_add_dependency` relies on recursion for finding all the child dependencies.
When deeply nested trees of `ComponentResources` are used, `_add_dependencies` can end up raising such an error.
Rewrite the function to be iterative instead of recursive to avoid that.
Fixes https://github.com/pulumi/pulumi/issues/16328
(I didn't manage to reproduce the exact stacktrace of the above issue, so there might be another thing hidden there.  But this should help with it either way)
=> sdk/python: avoid maximum recursion depth error

changelog/pending/20240716--cli-state--fix-resources-to-be-moved-not-being-shown-in-pulumi-state-move.yaml, pkg/cmd/pulumi/state_move.go, pkg/cmd/pulumi/state_move_test.go
At some point while moving the code around we lost the output for the resources to be moved.  We would look for them in the source snapshot for correct ordering, but the code happened after the URN renaming, so the resources would not match the ones in the source snapshot anymore.
Fix this by using the resourcesToMoveOrdered list to print the resources, and also moving this code a bit earlier, as we want to show the resource URNs from the source snapshot, instead of the rewritten ones.
=> state_move: show resources to be moved correctly

tests/integration/integration_nodejs_test.go
This commit fixes a small error in one of our integration tests that happened to be spotted in #14543, but was never addressed separately/has not been addressed since that PR has not yet been merged.
=> Fix an incorrect error check in NodeJS integration tests

changelog/pending/20240712--cli-new--fix-incorrect-caching-of-git-auth-method-in-error-cases.yaml, sdk/go/common/util/gitutil/git.go, sdk/go/common/util/gitutil/git_test.go
urlAuthParser.Parse caches auth methods. To avoid caching the auth
method when running into an error, we first checked that the auth method
is not nil. However we ran into a classic Go issue where a nil value of
a concrete type is assigned to a variable of an interface type, making 
it not equal to nil.
https://go.dev/doc/faq#nil_error
https://go.dev/play/p/AOSdCWd3XC1
Fixes https://github.com/pulumi/pulumi/issues/16637
=> Fix incorrect caching of git auth method in error cases

changelog/pending/20240716--cli-state--fix-panic-in-state-move-when-either-the-source-or-destination-stack-are-empty.yaml, pkg/cmd/pulumi/state_move.go, pkg/cmd/pulumi/state_move_test.go
Currently when we have stacks with no snapshot, `pulumi state move` fails because it tries to use a nil pointer.  Handle this scenario correctly by:
- erroring out if there is no snapshot in the source stack.  In this case there are no resources that can be moved, so there's nothing more that we can do other than showing the error.
- creating a snapshot in the destination stack if necessary.  It's valid to move a resource to a currently empty stack, so we'll make this work.
=> state_move: handle empty stacks correctly

changelog/pending/20240716--sdk-python--dont-use-indentation-in-converted-pyproject-toml-files.yaml, changelog/pending/20240716--sdk-python--dont-use-indentation-in-pyproject-toml.yaml, sdk/python/toolchain/poetry.go, sdk/python/toolchain/poetry_test.go, tests/integration/integration_python_acceptance_test.go
When converting from a requirements.txt to a pyproject.toml, we were
previously indenting each logical level in the file. Disable the
indentation to match the style of pyproject.toml files as generated
directly by Poetry.
Fixes https://github.com/pulumi/pulumi/issues/16657
=> Don't use indentation in converted pyproject.toml files

changelog/pending/20240715--sdk-python--use-python-names-for-dictionary-literals-when-inside-a-typed-dictionary-input.yaml, pkg/codegen/python/gen_program.go, pkg/codegen/python/gen_program_expressions.go, tests/testdata/codegen/typeddict-pp/python/typeddict.py
When generating literals for inputs that have TypedDict types, we want
to use the pythonic names (snake_case) for keys.
We also have to take care of tracking the fact that we’re inisde a
TypedDict for nested dicts.
Fixes https://github.com/pulumi/pulumi/issues/16646
=> Use python names for dictionary literals when inside a typed dictionary input

changelog/pending/20240716--sdk-go-nodejs-python--support-remove-for-destroy-in-the-go-nodejs-and-python-automation-api-sdks.yaml, sdk/go/auto/local_workspace_test.go, sdk/go/auto/optdestroy/optdestroy.go, sdk/go/auto/stack.go, sdk/nodejs/automation/stack.ts, sdk/nodejs/tests/automation/localWorkspace.spec.ts, sdk/python/lib/pulumi/automation/_stack.py, sdk/python/lib/test/automation/test_local_workspace.py
By default, `pulumi destroy` removes all resources within a stack but leaves the stack and its configuration intact. If one passes the `--remove` option to `destroy`, however, the stack and its configuration will also be removed once the resources within the stack have been deleted. This commit updates the work of @Moon1706 in #11080 to add `remove` as an option to the Go, NodeJS and Python Automation API SDKs' `destroy` methods, which then perform an analogous clean-up.
Closes #11080
=> Support `--remove` for `destroy` in the Go, NodeJS and Python Automation API SDKs

changelog/pending/20240716--cli-state--warn-when-an-argument-matches-no-urn-in-the-source-snapshot-and-error-out-when-no-resources-are-being-moved-in-pulumi-state-move.yaml, pkg/cmd/pulumi/state_move.go, pkg/cmd/pulumi/state_move_test.go
Currently when no resources are moved, we just show no resources being moved, but let the command continue.  This can be quite confusing to the user.  Error out in that case instead.  Also when an argument doesn't match any resources in the source snapshot, we now warn the user about that.
=> state_move: warn no resources are matched/error out when no resources move

sdk/go/pulumi-language-go/main.go, sdk/go/pulumi-language-go/main_test.go, sdk/go/pulumi-language-go/testdata/sample/dep/go.mod, sdk/go/pulumi-language-go/testdata/sample/dep/plug.go, sdk/go/pulumi-language-go/testdata/sample/indirect-dep/go.mod, sdk/go/pulumi-language-go/testdata/sample/indirect-dep/indirect.go, sdk/go/pulumi-language-go/testdata/sample/plugin/go.mod, sdk/go/pulumi-language-go/testdata/sample/plugin/plug.go, sdk/go/pulumi-language-go/testdata/sample/plugin/pulumi-plugin.json, sdk/go/pulumi-language-go/testdata/sample/prog-gowork/go.work.sum, sdk/go/pulumi-language-go/testdata/sample/prog-gowork/prog/go.mod, sdk/go/pulumi-language-go/testdata/sample/prog-gowork/prog/go.sum, sdk/go/pulumi-language-go/testdata/sample/prog-gowork/prog/main.go, sdk/go/pulumi-language-go/testdata/sample/prog-subdir/go.mod, sdk/go/pulumi-language-go/testdata/sample/prog-subdir/go.sum, sdk/go/pulumi-language-go/testdata/sample/prog-subdir/infra/main.go, sdk/go/pulumi-language-go/testdata/sample/prog/go.mod, sdk/go/pulumi-language-go/testdata/sample/prog/go.sum, sdk/go/pulumi-language-go/testdata/sample/prog/main.go
For conformance testing we want "replace" directives to be respected since they change the version of the dependency. These tests were all written using replace directives instead of just normal real dependencies and so fixing the Go host to respect "replace" broke these tests. 
This rewrites the tests to use real dependencies pulled from a separate repo at https://github.com/pulumi/go-dependency-testdata.
=> Change Go dependency tests to use real dependencies

cmd/pulumi-test-language/interface.go, pkg/codegen/go/gen_program.go, pkg/codegen/go/gen_program_test.go, scripts/tidy.sh, sdk/go/pulumi-language-go/language_test.go, sdk/go/pulumi-language-go/main.go, sdk/go/pulumi-language-go/testdata/projects/l1-empty/Pulumi.yaml, sdk/go/pulumi-language-go/testdata/projects/l1-empty/go.mod, sdk/go/pulumi-language-go/testdata/projects/l1-empty/main.go
Enable the l1-empty test for Go.
This required some changes in reporting versions from the Go language host (replaced dependencies don't really have a version anymore, because they've been replaced by a local artefact and that doesn't contain any version info itself). This then cascaded that the conformance test had to be less strict about checking versions from GetDependencies because Go now returns empty versions for these local deps.
=> Enable the l1-empty test for Go

sdk/go/common/resource/properties.go
Doesn't look like anything uses this, and chances are we'll want to add _actual_ sets of property values at some point which clashes with this name.
=> Remove unused PropertySet type

sdk/go/pulumi/context.go, sdk/go/pulumi/mocks.go, tests/integration/transforms/go/simple/main.go
This is more consistent with `RegisterResourceTransform`.  The `RegisterStackInvokeTransform` version has not been released yet, so we still have the option of making this consistent.
=> name invoke transforms RegisterInvokeTransform in the Go SDK

changelog/pending/20240717--sdk-python--validate-that-we-have-poetry-1-8-0.yaml, sdk/python/toolchain/poetry.go, sdk/python/toolchain/poetry_test.go
The pyproject.toml files we generated when using the Poetry toolchain
require Poetry >= 1.8.0. Validate that we have at least this version,
and report a descriptive error if not.
Fixes https://github.com/pulumi/pulumi/issues/16656
Doc update: https://github.com/pulumi/docs/pull/12293
=> Validate that we have Poetry >= 1.8.0

pkg/cmd/pulumi/convert.go, pkg/cmd/pulumi/package.go, pkg/cmd/pulumi/plugin_run.go, pkg/codegen/schema/loader.go
While looking at https://github.com/pulumi/pulumi/issues/16469, I noticed a lot of the missing errors were a bit repetitive for the not-a-missing-error case and disable-plugin-acquisition case. So this rejigs the if statements a bit to make them all a bit more standard of "if not a missing error, or if disable plugin acquisition is set, then just err immediately, else retry".
=> Refactor MissingError handling

changelog/pending/20240717--sdk-go--disallow-outputstate-from-being-deepcopied.yaml, sdk/go/common/util/deepcopy/copy.go, sdk/go/common/util/deepcopy/copy_test.go
We have this deepcopy utility in our public API, but it does not work properly on structs with unexported values.  Make a note of that, and also disallow OutputState from being copied, since OutputState has required unexported fields that we can't deepcopy.
Not sure if we should special case `OutputState` here, which I've done since that has come up in particular, or maybe even disallow deepcopy'ing any values that have unexported fields?  That would be a breaking change though, so I've shied away from it for now.
Fixes https://github.com/pulumi/pulumi/issues/16634
=> disallow OutputState to be deepcopied

changelog/pending/20240718--sdk-nodejs--pin-node-to-22-4-x-to-workaround-breakage.yaml, scripts/get-job-matrix.py
Node 22.5.0 breaks yarn, the installation stops half way through with a
succesfull exit code. Pin to 22.4.x for now to work around this.
Follow up to unpin https://github.com/pulumi/pulumi/issues/16707
=> Pin node to 22.4.x to workaround breakage

changelog/pending/20240718--sdk-python--add-support-for-invoke-stack-transforms.yaml, sdk/python/lib/pulumi/__init__.py, sdk/python/lib/pulumi/invoke.py, sdk/python/lib/pulumi/runtime/__init__.py, sdk/python/lib/pulumi/runtime/_callbacks.py, sdk/python/lib/pulumi/runtime/settings.py, sdk/python/lib/pulumi/runtime/stack.py, tests/integration/transforms/python/simple/__main__.py, tests/integration/transforms/python/simple/random_.py, tests/integration/transforms/transforms_test.go
Similar to the NodeJS and Go SDK previously, also add support for stack invoke transforms to Python.
=> sdk/python: add support for stack invoke transforms

changelog/pending/20240718--cli--avoid-duplicate-error-prefix-with-expect-no-changes.yaml, pkg/cmd/pulumi/refresh.go, pkg/cmd/pulumi/up.go
When printing an error we already prefix it with a `error:` prefix. Therefore new errors should not include that prefix again, otherwise we'll end up with a line like:
error: error: no changes were expected but changes occurred
Just a small cleanup I noticed while testing something else.
(From a quick look at `git grep "\"error:"` I couldn't find other instances of this)
=> avoid duplicate error: prefix with `--expect-no-changes`

changelog/pending/20240718--cli--allow-specifying-project-names-when-converting-with-pulumi-convert-name.yaml, pkg/cmd/pulumi/convert.go, pkg/cmd/pulumi/convert_test.go
When converting a project from one language to another, `pulumi convert` will default to producing a project named after the source directory. So if one converts a project in `some_directory`, the resulting `Pulumi.yaml` will specify `name: some_directory`. This is generally the right behaviour, since conversion often implies that the target will supplant the source (and thus should use the same name). However, there are cases where it can be useful to override this default. This commit takes @FonsecaGoncalo's work in #15034 and extends `pulumi convert` so that it accepts an optional `--name` argument, which if supplied (and valid) will be used instead. As well as rebasing this work, we add a couple of tests to make sure that both cases work.
Fixes #14645
Closes #15034
=> Allow specifying project names with `pulumi convert`

changelog/pending/20240718--cli--add-support-for-deletedwith-to-pulumi-convert.yaml, pkg/codegen/dotnet/gen_program.go, pkg/codegen/go/gen_program.go, pkg/codegen/nodejs/gen_program.go, pkg/codegen/pcl/binder_resource.go, pkg/codegen/pcl/resource.go, pkg/codegen/python/gen_program.go, pkg/codegen/testing/test/program_driver.go, tests/testdata/codegen/aws-s3-folder-pp/aws-s3-folder.pp, tests/testdata/codegen/aws-s3-folder-pp/go/aws-s3-folder.go, tests/testdata/codegen/aws-s3-folder-pp/nodejs/aws-s3-folder.ts, tests/testdata/codegen/aws-s3-folder-pp/python/aws-s3-folder.py
This commit extends PCL so that it knows about the `DeletedWith` resource option. With this, we can give `pulumi convert` the ability to preserve `DeletedWith` resource options when converting programs.
Part of https://github.com/pulumi/pulumi-yaml/pull/437
=> Add support for `DeletedWith` to `pulumi convert`

changelog/pending/20240718--programgen-go--fix-emiting-literal-values-as-stack-outputs.yaml, pkg/codegen/go/gen_program.go, pkg/codegen/testing/test/program_driver.go, tests/testdata/codegen/output-literals-pp/go/output-literals.go
Splitting off just the codegen changes from https://github.com/pulumi/pulumi/pull/16698 to see if they pass CI.
=> Fix literal values in generated Go stack outputs

build/common.mk
Don’t format files in .git and sdk/proto using gofumpt. The go files in sdk/proto are generated. If you have a branch name that ends with `.go`, gofumpt attempts to format this, which will fail.
=> Exclude .git and sdk/proto from gofumpt

changelog/pending/20240719--cli-state--improve-readability-of-the-resources-to-be-moved-output-of-the-state-move-command.yaml, pkg/cmd/pulumi/state_move.go, pkg/cmd/pulumi/state_move_test.go
Change the output for resources to be moved from
```
Planning to move the following resources from dev to dev2:
urn:pulumi:dev::aws-ts::pulumi:providers:aws::Provider_A
urn:pulumi:dev::aws-ts::aws:iam/role:Role::Role_A
Do you want to perform this move?  [Use arrows to move, type to filter]
yes
> no
```
to
```
Planning to move the following resources from dev to dev2:
- urn:pulumi:dev::aws-ts::pulumi:providers:aws::Provider_A
- urn:pulumi:dev::aws-ts::aws:iam/role:Role::Role_A
Do you want to perform this move?  [Use arrows to move, type to filter]
yes
> no
```
for better readability.
=> improve UI output

pkg/codegen/go/gen_program.go, sdk/go/pulumi-language-go/language_test.go, sdk/go/pulumi-language-go/testdata/projects/l1-main/Pulumi.yaml, sdk/go/pulumi-language-go/testdata/projects/l1-main/subdir/go.mod, sdk/go/pulumi-language-go/testdata/projects/l1-main/subdir/main.go
Enables the l1-main conformance test for Go. This required fixing up Go programgen to respect the "main" attribute in the projects Pulumi.yaml if present.
=> Enable l1-main for Go conformance tests

changelog/pending/20240722--cli-state--reparent-providers-correctly-in-state-move.yaml, pkg/cmd/pulumi/state_move.go, pkg/cmd/pulumi/state_move_test.go
Currently when a providers Parent is not moved, we just try to rewrite the current one using the regular URN rewrite mechanism.  This is not correct.
Instead, we need to make sure to do the same thing as we do for regular resources.  Namely if the parent is not being moved into the destination, we want the parent to be the root stack of the destination.
=> state_move: reparent provider correctly

pkg/cmd/pulumi/convert.go
This help text was inconsistent with the other bool flags, make it consistent.
While there also remove a bunch of unnecessary nolint flags.
(noticed in https://github.com/pulumi/pulumi/pull/16708#pullrequestreview-2187685264)
=> convert: make the help texts more consistent

changelog/pending/20240719--cli-state--disallow-provider-moves-in-the-state-move-command.yaml, pkg/cmd/pulumi/state_move.go, pkg/cmd/pulumi/state_move_test.go
The `state move` command is designed to move resources with an underlying physical resource.  Otherwise it's easy enough to just re-create a resource in the resulting program.  Especially for providers, we usually don't want to move them, but rather want to copy them over.  Since there is not much point in moving a provider, just disallow that and error out if a user tries to do that.
=> state_move: disallow provider moves

changelog/pending/20240720--sdk-python--exclude-pulumi_policy-from-plugin-determination.yaml, sdk/python/cmd/pulumi-language-python/main.go, sdk/python/cmd/pulumi-language-python/main_test.go, sdk/python/cmd/pulumi-language-python/testdata/sdks/foo-1.0.0/pulumi_foo/pulumi-plugin.json, sdk/python/cmd/pulumi-language-python/testdata/sdks/foo-1.0.0/setup.py
In the Python language host, we hardcode that `pulumi-policy` doesn't have an associated resource (provider) plugin, because we know it doesn't have one.
However, this hardcode no longer works with the latest version of `pulumi-policy` (v1.11.0) because it was built with a newer version of `setuptools` which has a behavior change where the package name in the metadata will now allow underscores, instead of having underscores replaced with hyphens (https://github.com/pypa/setuptools/pull/4159). This means that the package name reported from `pip list` is now `pulumi_policy` instead of `pulumi-policy`, which doesn't match the hardcoded list.
Note that this change is really only to help with `pulumi-policy` v1.11.0. Future versions of `pulumi-policy` will have a `pulumi-plugin.json` file in …
=> Exclude `pulumi_policy` from plugin determination

changelog/pending/20240722--engine--fix-panics-due-to-different-length-ignorechanges-arrays.yaml, sdk/go/common/resource/properties_path.go, sdk/go/common/resource/properties_path_test.go
The `ignoreChanges` resource option accepts a list of paths into a resource that should be ignored when computing whether or not something has changed. For example:
```typescript
const r = new Resource(
"r",
{
a: "a",
b: [1, 2],
c: { d: "d" },
},
{
ignoreChanges: [
"a",
"b[*]",
],
}
)
```
Here, when diffing `r`, Pulumi will ignore changes to `a` (due to the path `"a"`) as well as changes to any element of `b` (due to the _wildcard_ path `"b[*]"`). Under the hood, `ignoreChanges` is implemented partly by "resetting" pieces of a resource's state to older values -- that is, rather than ignoring changes that might be reported, Pulumi will undo the changes before they are used altogether.
In #16406, a panic encountered when resetting children of arrays of different length was fixed. This …
=> Fix panics due to different length `ignoreChanges` arrays

changelog/pending/20240722--cli-state--allow-a-provider-with-the-same-urn-and-id-to-already-be-in-the-snapshot.yaml, pkg/cmd/pulumi/state_move.go, pkg/cmd/pulumi/state_move_test.go
When a provider with the same URN and ID already exists in the destination snapshot, we can assume it's the provider that has been copied over.  This is e.g. useful when running the state move command multiple times with different resources that have the same provider.
This also allows moving resources back and forth between stacks.
=> state_move: don't conflict if destination provider with same URN and ID exists

pkg/codegen/go/gen_program_expressions.go, pkg/codegen/go/gen_program_test/batch1/gen_program_test.go, pkg/codegen/testing/test/program_driver.go, sdk/go/pulumi-language-go/language_test.go, sdk/go/pulumi-language-go/testdata/projects/l1-output-number/Pulumi.yaml, sdk/go/pulumi-language-go/testdata/projects/l1-output-number/go.mod, sdk/go/pulumi-language-go/testdata/projects/l1-output-number/main.go, tests/testdata/codegen/single-or-none-pp/go/single-or-none.go, tests/testdata/codegen/throw-not-implemented-pp/go/throw-not-implemented.go
This required fixing `__convert` in Go programgen to handle expressions that needed to result in input-y values. This also fixed the "single-or-none" codegen test.
=> Enable l1-output-number conformance test for Go

pkg/codegen/go/gen_program.go, pkg/codegen/go/gen_program_expression_test.go, pkg/codegen/go/gen_program_expressions.go
Noticed this while fixing https://github.com/pulumi/pulumi/pull/16753. The first parameter to argumentTypeName was totally unused.
=> Remove an unused parameter from argumentTypeName

changelog/pending/20240720--sdk-nodejs--ensure-no-output-is-lost-for-nodejs-commands-when-stdout-is-slow.yaml, sdk/nodejs/cmd/pulumi-language-nodejs/main.go, sdk/nodejs/cmd/pulumi-language-nodejs/main_test.go
Nodejs sometimes sets stdout/stderr to non-blocking mode. When a nodejs subprocess is directly handed the go process's stdout/stderr file descriptors, nodejs's non-blocking configuration goes unnoticed by go, and a write from go can result in an error `write /dev/stdout: resource temporarily unavailable`.
The solution to this is to not provide nodejs with the go process's stdout/stderr file descriptors, and instead proxy the writes through something else. In https://github.com/pulumi/pulumi/pull/16504 we used Cmd.StdoutPipe/StderrPipe for this. However this introduced a potential bug, as it is not safe to use these specific pipes along with Cmd.Run. The issue is that these pipes will be closed as soon as the process exits, which can lead to missing data when stdout/stderr are slow, or …
=> Ensure no output is lost for nodejs commands when stdout is slow

tests/about_test.go, tests/config_test.go, tests/integration/integration_acceptance_test.go, tests/integration/integration_go_test.go, tests/integration/integration_nodejs_acceptance_test.go, tests/integration/integration_nodejs_test.go, tests/integration/integration_python_acceptance_test.go, tests/integration/integration_python_test.go, tests/integration/integration_test.go, tests/integration/policy/policy_test.go, tests/integration/targets/targets_test.go, tests/preview_only_test.go, tests/roundtrip_test.go, tests/stack_test.go
Ensure we always run `Environment.DeleteIfNotFailed` in our Environment based tests.
Also standardize on this instead of manually checking with `if t.Failed` and calling `Environment.DeleteEnvironment()`.
=> Run Environment.DeleteIfNotFailed after tests complete

scripts/get-job-matrix.py
Reverts pulumi/pulumi#16709
The underlying issue has been fixed in node 20.5.1 https://github.com/nodejs/node/issues/53902
Fixes https://github.com/pulumi/pulumi/issues/16707
=> Revert "Pin node to 22.4.x to workaround breakage"

changelog/pending/20240723--cli-state--fix-the-dependency-information-in-the-state-move-command.yaml, pkg/cmd/pulumi/state_move.go, pkg/cmd/pulumi/state_move_test.go
Currently we show the dependency information incorrectly, showing something like
```
urn:pulumi:dev::pulumi-demo-move::random:index/randomPet:RandomPet::a-random-pet has a dependency on urn:pulumi:dev::pulumi-demo-move::random:index/randomPet:RandomPet::a-random-pet
```
This is obviously nt what we intended, and we should show the dependency information correctly.  Fix this.
=> correctly display the dependency information in state move

changelog/pending/20240718--sdk-nodejs--detect-possible-oom-errors-when-nodejs-crashes.yaml, changelog/pending/20240720--sdk-nodejs--ensure-no-output-is-lost-for-nodejs-commands-when-stdout-is-slow.yaml, sdk/nodejs/cmd/pulumi-language-nodejs/main.go, sdk/nodejs/cmd/pulumi-language-nodejs/main_test.go, tests/integration/integration_nodejs_test.go, tests/integration/nodejs/oom/Pulumi.yaml, tests/integration/nodejs/oom/index.js, tests/integration/nodejs/oom/package.json, tests/integration/nodejs/oom/tsconfig.json
The typical nodejs OOM messages are sometimes obscured by our use of the
debugger API, making this hard to diagnose. Provide an actionable error
message when we detect a normal or obscured OOM crash.
Fixes https://github.com/pulumi/pulumi/issues/16596
=> Detect possible OOM errors when nodejs crashes

changelog/pending/20240723--sdk-python--stricter-types-for-config-get_xxx-when-a-deafult-is-provided.yaml, sdk/python/lib/pulumi/config.py
When calling config.get_XXX with a default value, we know the return
type is never None. Add typing overloads to indicate this. This makes
typing much more pleasant:
```python
server = config.get("server", "example.com") # now str, previously str | None
```
Fixes https://github.com/pulumi/pulumi/issues/16766
=> Provide stricter types for config.get_XXX when a default is provided

changelog/pending/20240723--cli-state--fix-calculation-of-the-resources-that-are-remaining-in-the-source-stack.yaml, pkg/cmd/pulumi/state_move.go, pkg/cmd/pulumi/state_move_test.go
Currently we calculate the remaining resources when matching the argument.  That however means that we calculated them too early, when we don't yet know about the child resources and possible parent resources (when `--target-parents` is given).
This means the move then thinks these resources are left behind, and breaks dependencies to them.  This is not correct.  Move the calculation further down, when we calculated all resources that will be moved.
Fixes: https://github.com/pulumi/pulumi/issues/16777
=> state_move: calculate remaining resources only when we know all moved resources

changelog/pending/20240724--cli-state--improve-how-moving-the-root-stack-is-handled-in-pulumi-state-move.yaml, pkg/cmd/pulumi/state_move.go, pkg/cmd/pulumi/state_move_test.go
The root stack is a special resource, in that it's supposed to exist in every snapshot. Moving it as we do other resources (and thus re-parenting it on the existing root stack) doesn't quite make sense.
However it does make sense for moving it to mean "move all the children of the root stack", and moving it thusly. We can easily achieve this by just removing the rootstack from the resources to be moved, as it already exists in the destination snapshot, and all the children will be re-parented correctly to the destination root stack.
Fixes https://github.com/pulumi/pulumi/issues/16778
=> state_move: don't move root stack explicitly

pkg/cmd/pulumi/state_move.go, pkg/cmd/pulumi/state_move_test.go
A couple minor UI tweaks, to make the broken dependencies a list, and print a few more newlines to make the blocks more clearly visible. Also avoid a double newline if there are no broken dependencies.
=> state_move improve output slightly

changelog/pending/20240710--auto-nodejs--implement-stack-import-in-automation-api-to-specify-and-import-resources-into-a-stack.yaml, sdk/nodejs/automation/stack.ts, sdk/nodejs/tests/automation/data/import/Pulumi.yaml, sdk/nodejs/tests/automation/data/import/expected_generated_code.txt, sdk/nodejs/tests/automation/localWorkspace.spec.ts
Addressing https://github.com/pulumi/pulumi/issues/8237 starting with NodeJS
This PR implements `Stack.import(...)` in NodeJS automation API and allows the user to specify resources and other import options to perform the import. Here is an example of how it looks like from the user's perspective:
```ts
// importing resources from a list of import definitions
// can also specify nameTable: { ... }
const result = await stack.import({
protect: false,
resources: [
{  
type: "random:index/randomPassword:RandomPassword",
name: "randomPassword",
id: "supersecret"
}
]
})
// see the generated code from the import
console.log(result.generatedCode)
```
In addition to specifying resources, we can also specify a converter to import resources with:
```ts
// pulumi import --from terraform …
```
=> [autmation/nodejs] Implement Stack.import() to specify and import resources into a stack

tests/config_test.go
This test has started failing due to changes in the pulumi service. This has been raised to the ESC team to look at. For now skip to unblock pulumi/pulumi pipelines.
=> Skip TestConfigCommandsUsingEnvironments

sdk/nodejs/cmd/pulumi-language-nodejs/main_test.go
Some tests were writing directly to os.Stdout, causing noise for other
tests. For `TestRunWithOutputDoesNotMissData` we don't need to write
anything, we only need a slow writer. For `TestNonblockingStdout` we
need to more carefully emulate the behaviour seen with os.Stdout.
We can do this using a named pipe initially opened from Go without
O_NONBLOCK. This ensures that Go thinks this file descriptor is blocking
and does not add the file to its internal poller that handles
non-blocking IO. As previously, we then trick Go by changing the file to
be non-blocking behind its back and trigger the bug.
=> Don't use os.Stdout in tests

changelog/pending/20240719--auto-go--implement-stack-importresources-for-batch-importing-resources-into-a-stack-via-the-automation-api.yaml, sdk/go/auto/local_workspace_test.go, sdk/go/auto/optimport/optimport.go, sdk/go/auto/stack.go, sdk/go/auto/test/import/Pulumi.yaml, sdk/go/auto/test/import/expected_generated_code.yaml
Addressing https://github.com/pulumi/pulumi/issues/8237 for Go.
Implements a new function `Stack.ImportResources(...)` for batch importing resources via the Go automation API.
=> Implement Stack.ImportResources() for batch importing resources into a stack via the automation API

sdk/go/common/apitype/stacks.go
This data will be filed by the Pulumi service and will be used by Copilot to provide clickable links to objects
=> Add links to StackSummary to for clients like Copilot

sdk/go/Makefile
This target is currently broken, because the `shell` command in Make doesn't seem to take the `cd pulumi-language-go` into account, and run from the PWD of the `make` invocation instead.  This leads to us trying to run all the `sdk/go` tests from the `pulumi-language-go` directory, which means the test runs use `pulumi-language-go/go.mod` for dependency resolution for the tests in `sdk/go` proper.  This then fails.
Fix it by cd'ing to the right directory before getting the list of tests.
=> sdk/go: fix test_fast Makefile target

changelog/pending/20240712--cli-plugin--enable-overriding-plugin-download-urls-for-air-gapped-environments-with-an-environment-variable.yaml, sdk/go/common/env/env.go, sdk/go/common/workspace/plugins.go, sdk/go/common/workspace/plugins_test.go
Pulumi plugin binaries can be downloaded by the CLI from multiple sources. By default, it's downloaded from Pulumi's GitHub releases or get.pulumi.com, but plugins can also specify their binary sources via the `PluginDownloadURL` schema option. They can point to custom GitHub, Gitlab, or HTTP locations.
Enterprise customers ask for a way to isolate the CLI from downloads from random locations and to configure the CLI to go to their internal pre-approved artefact location instead. This way, Pulumi can run in "air-gapped" environments (which still have access to Cloud APIs, of course).
Related issues:
- https://github.com/pulumi/pulumi/issues/14459
- https://github.com/pulumi/pulumi/issues/16240
Currently, there is a basic mechanism to do so via the variable `pluginDownloadURLOverrides`, …
=> URL-based plugin source overrides via env var

.github/workflows/download-pulumi-cron.yml
This cron job periodically checks whether package managers have the updated version of pulumi to install.  This is a very useful check to make sure our automation works correctly.
However some of the package managers (homebrew and chocolatey in particular) take a while to act on pulumi-bot's PRs, and thus the versions are frequently not up to date when this cron job runs shortly after a release.  This is just how these package managers work and nothing to worry about.
We shouldn't get an issue every time this happens.  The important thing here is that the version gets updated eventually.  For homebrew and chocolatey we therefore also allow the version to be the previous version.  This means it will take a bit longer for us to notice if a pulumi isn't updated in these package managers, but …
=> Download Pulumi Cron: allow previous version for homebrew and chocolatey

pkg/engine/lifecycletest/alias_test.go, pkg/engine/lifecycletest/continue_on_error_test.go, pkg/engine/lifecycletest/delete_before_replace_test.go, pkg/engine/lifecycletest/golang_sdk_test.go, pkg/engine/lifecycletest/import_test.go, pkg/engine/lifecycletest/parameterized_test.go, pkg/engine/lifecycletest/pending_replace_test.go, pkg/engine/lifecycletest/provider_test.go, pkg/engine/lifecycletest/pulumi_test.go, pkg/engine/lifecycletest/refresh_legacy_diff_test.go, pkg/engine/lifecycletest/refresh_test.go, pkg/engine/lifecycletest/resource_reference_test.go, pkg/engine/lifecycletest/retain_on_delete_test.go, pkg/engine/lifecycletest/source_query_test.go, pkg/engine/lifecycletest/step_generator_test.go, pkg/engine/lifecycletest/target_test.go, pkg/engine/lifecycletest/transformation_test.go, pkg/engine/lifecycletest/update_plan_test.go, pkg/resource/deploy/deploytest/provider.go, pkg/resource/deploy/deploytest/provider_test.go, pkg/resource/deploy/source_eval_test.go, pkg/resource/deploy/step_test.go
In #16302, provider methods were normalised to the form `Method(context.Context, MethodRequest) (MethodResponse, error)`. This commit makes the same changes to the lifecycle tests, both for consistency and discoverability when writing stubs for provider methods.
=> Update lifecycle test APIs to match provider APIs

pkg/testing/integration/program.go
With this change users can inline ProgramTest call and get back the sequence with ProgramTestManualLifeCycle to edit further, making it more obvious how to customize this.
=> refactor: make ProgramTest inline better

changelog/pending/20240726--sdkgen-go-nodejs-python--fix-generation-of-nested-plain-input-types.yaml, pkg/codegen/schema/schema.go, pkg/codegen/schema/schema_test.go, tests/testdata/codegen/plain-properties-1.0.0.json
Fixes https://github.com/pulumi/pulumi/issues/16810.
The container types already marshalled correctly here, but other types like refs and primitives didn't keep their Plain attribute.
=> Fix marshalling of plain properties

pkg/codegen/python/gen.go, sdk/python/lib/pulumi/resource.py, sdk/python/lib/pulumi/runtime/resource.py, tests/integration/python/parameterized/sdk/python/pulumi_pkg/provider.py, tests/integration/python/parameterized/sdk/python/pulumi_pkg/random.py
In adding support for parameterized providers to the Python SDK, some variables erroneously used `camelCase` instead of `snake_case`. This commit cleans that up ahead of general release.
=> Use `snake_case` for package refences in the Python SDK

proto/.checksum.txt, proto/pulumi/provider.proto, sdk/nodejs/proto/provider_grpc_pb.js, sdk/proto/go/provider.pb.go, sdk/python/lib/pulumi/runtime/proto/provider_pb2.pyi
This change adds comments in the protobuf definitions of the Engine<->Provider protocol to highlight that the `news` value passed to the provider may be influenced by the state, specifically the old inputs stored in the state, in an Update scenario, and pre-processed to implement ignoreChanges at the engine level. This was not entirely obvious when analyzing provider behavior, and it helps having this documented in the proto files.
Note that this is especially confusing since the engine is also passing ignoreChanges to the provider as if to say "please implement it on your end". This is indeed something that is used to suppress any residual diffs, say in Terraform-bridged providers, but what's not obvious is that the engine performs a bit of processing here already.
The relevant …
=> Document news ignore changes processing in the provider protocol

tests/config_test.go
This test was failing due to a bug in the ESC API. Re-enable it now that the bug has been fixed.
Fixes #16791.
=> [config] Re-enable TestConfigCommandsUsingEnvironments

changelog/pending/20240801--programgen-go--sprintf-go-programgen.yaml, pkg/codegen/go/gen_program_expressions.go, tests/integration/aliases/go/retype_parents/step2/main.go, tests/testdata/codegen/aws-eks-pp/go/aws-eks.go, tests/testdata/codegen/output-funcs-tfbridge20/go-extras/tests/codegen_test.go, tests/testdata/codegen/simple-range-pp/go/simple-range.go
Noticed by @thomas11 on Slack (https://pulumi.slack.com/archives/C02FXTZEZ6W/p1722410344206549). We had a number of places doing `pulumi.String(fmt.Sprintf(template, args))`, when they could just use `pulumi.Sprintf`. This updates programgen to use that.
=> Use pulumi.Sprintf in program gen

tests/integration/aliases/go/retype_parents/step2/main.go
This is a quick follow-up to https://github.com/pulumi/pulumi/pull/16852 which tweaked some code to use `pulumi.Sprintf`. The same lines can be simplified further: there's no need to specify `pulumi.StringInput` since the result of `pulumi.Sprintf` (`pulumi.StringOutput`) satisfies `pulumi.StringInput`.
=> Tiny cleanup to an integration test

changelog/pending/20240729--sdk-nodejs--fix-resource-reference-serialization-when-multiple-copies-of-atpulumi-pulumi-are-present.yaml, sdk/nodejs/runtime/rpc.ts, sdk/nodejs/runtime/state.ts, sdk/nodejs/tests/runtime/langhost/cases/015.runtime_sxs/index.js
Rather than saving package/module registrations in a module variable, save them in the store where other state is stored. This way, if there are multiple copies of `@pulumi/pulumi`, they'll use the same store, rather than having separate copies of registrations.
Fixes #13223
=> [sdk/nodejs] Save pkg/mod registrations on async local store

changelog/pending/20240802--cli-state--include-the-stack-name-in-the-passhprase-prompt-in-state-move.yaml, pkg/cmd/pulumi/state_move.go, pkg/cmd/pulumi/state_move_test.go, pkg/resource/stack/secrets.go, pkg/secrets/passphrase/manager.go
When moving resources between projects that use the passphrase secret manager, we automatically prompt for the secret, unless PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE are set. Unfortunately that can be a bit confusing when moving resources between different projects, because the prompt does not specify in any way which stack the passphrase is for.
Fix this by adding a little bit of output to the prompt, showing the user the stack name for which they are supposed to enter the passphrase.
=> state_move: include stack name in the passhprase prompt

changelog/pending/20240730--cli-state--fix-moving-resources-with-secrets-when-the-destination-stack-has-no-secrets-manager-defined.yaml, pkg/cmd/pulumi/state_move.go, pkg/cmd/pulumi/state_move_test.go
The destination snapshot currently doesn't necessarily have a secrets manager set up, e.g. if the stack was just initialized with `pulumi stack init <stack>`.
At the same time, any secrets we're moving need to be re-encrypted with the secret manager in the destination stack.  If the secret manager is not defined there this means we'll create a panicCrypter, and `pulumi state move` will panic.
To prevent this, make the destination stack use the source secret manager if the secret manager is not already defined there.
Fixes https://github.com/pulumi/pulumi/issues/16835
=> state_move: set up a secret manager in the dest stack if it doesn't exist

changelog/pending/20240730--engine--provider-internal-state-is-now-seperated-from-provider-user-config.yaml
I noticed this one standing out slightly, and it would be nice to make it conform to our usual style before the 3.128.0 release.
=> make all changelog entries conform to our style

cmd/pulumi-test-language/interface.go, cmd/pulumi-test-language/internal_test.go, cmd/pulumi-test-language/providers/bad_provider.go, cmd/pulumi-test-language/testdata/internal-bad-schema/main.pp, cmd/pulumi-test-language/tests.go
This is in order to support parameterized packages, which show up in the PCL source code, but aren't a true separate provider we can list as a provider in the test case.
Instead of just generating SDKs for each provider listed as used in the test, we parse and bind the PCL program and ask it what packages it needs. For todays tests, this is fundementally the same set of packages either way. But once we add parameterized packages with "package" blocks there could be other packages returned.
=> Parse conformance programs to decide which packages are needed for SDKs

pkg/cmd/pulumi/package.go, pkg/resource/deploy/providers/provider.go, pkg/resource/deploy/providers/registry.go, pkg/resource/deploy/source_eval.go, sdk/go/common/resource/plugin/provider.go, sdk/go/common/resource/plugin/provider_plugin.go, sdk/go/common/resource/plugin/provider_server.go
Make this more clear by passing plain value of `semver.Version` instead of a pointer for these cases.
This also gets rid of some incorrect empty string checks which would have passed a nil version onwards rather than error'ing (as they should have).
=> Package versions are required for parameterized packages

changelog/pending/20240806--sdk-go--newpropertymapfrommap-will-flow-propertyvalues-through-it-rather-than-dropping-them.yaml, sdk/go/common/resource/properties.go, sdk/go/common/resource/properties_test.go
Fixes https://github.com/pulumi/pulumi/issues/16889
Currently `resource.NewPropertyMapFromMap` will drop any `resource.PropertyValue`s from the input map. This is demonstrated succinctly by Ian in the linked ticket:
```go
package main
import (
"fmt"
"github.com/pulumi/pulumi/sdk/v3/go/common/resource"
)
func main() {
fmt.Println(resource.NewObjectProperty(resource.NewPropertyMapFromMap(map[string]any{
"foo": resource.NewObjectProperty(resource.NewPropertyMapFromMap(map[string]any{
"bar": resource.NewNumberProperty(0),
})),
})))
fmt.Println(resource.NewObjectProperty(resource.NewPropertyMapFromMap(map[string]any{
"foo": map[string]any{"bar": 0},
})))
}
```
```
{map[foo:{map[]}]}
{map[foo:{map[bar:{0}]}]}
```
This PR updates `NewPropertyMapFromMap` to instead flow these values through …
=> Flow PropertyValues through NewPropertyMapFromMap

tests/integration/integration_nodejs_test.go, tests/integration/resource_refs_get_resource/nodejs/index.ts
This test was flaky for the same reasons as
TestResourceRefsGetResourceGo, so we can also fix it the same way (see https://github.com/pulumi/pulumi/pull/16897 for the fix of that).
Namely we wait for a bit for the resource to be able to be read.  This way we can unskip the test.
Fixes https://github.com/pulumi/pulumi/issues/11677
=> re-enable TestResourceRefsGetResourceNode

pkg/cmd/pulumi/deployment_settings_config.go, pkg/cmd/pulumi/deployment_settings_config_test.go
On Pulumi Deployments, we support public bare git repos (no credentials required). This PR adds support for configuring a bare git repo without credentials (previously it only allowed to configure it with SSH key or with password).
=> Add support for public bare git repos on deployment settings

changelog/pending/20240807--sdkgen-go--go-sdks-will-default-the-import-path-based-on-the-publisher-and-repository-schema-fields.yaml, pkg/codegen/go/gen.go, pkg/codegen/go/gen_program.go, pkg/codegen/schema/package_reference.go, sdk/go/pulumi-language-go/main.go, sdk/go/pulumi-language-go/testdata/projects/l2-resource-simple/go.mod, sdk/go/pulumi-language-go/testdata/projects/l2-resource-simple/main.go, sdk/go/pulumi-language-go/testdata/sdks/simple-2.0.0/go.mod, sdk/go/pulumi-language-go/testdata/sdks/simple-2.0.0/simple/init.go, sdk/go/pulumi-language-go/testdata/sdks/simple-2.0.0/simple/provider.go, sdk/go/pulumi-language-go/testdata/sdks/simple-2.0.0/simple/resource.go, tests/testdata/codegen/output-funcs-edgeorder/go/myedgeorder/init.go, tests/testdata/codegen/output-funcs-edgeorder/go/myedgeorder/listConfigurations.go, tests/testdata/codegen/output-funcs-edgeorder/go/myedgeorder/listProductFamilies.go, tests/testdata/codegen/output-funcs-edgeorder/go/myedgeorder/provider.go, tests/testdata/codegen/output-funcs-edgeorder/go/myedgeorder/pulumiTypes.go, tests/testdata/codegen/provider-config-schema/go/configstation/config/config.go, tests/testdata/codegen/provider-config-schema/go/configstation/config/pulumiTypes.go, tests/testdata/codegen/provider-config-schema/go/configstation/funcWithAllOptionalInputs.go, tests/testdata/codegen/provider-config-schema/go/configstation/init.go, tests/testdata/codegen/provider-config-schema/go/configstation/provider.go, tests/testdata/codegen/provider-config-schema/go/configstation/pulumiTypes.go, tests/testdata/codegen/simple-splat-pp/go/simple-splat.go, tests/testdata/codegen/using-dashes-pp/go/using-dashes.go
Currently we generate an "internal" package in our Go sdks that the other packages in the sdk need to import. This requires them to know the base import path (because Go doesn't have relative imports).
We also want to start writing out go.mod files as part of codegen rather than provider authors manually adding them in the sdk directory above. This _also_ requires the import path for the module.
Rather than requiring every user to specify the base import path in the schema "go language" section we improve the default behaviour to use the provider and repository fields from the schema that users are probably filling in anyway.
=> Use publisher and repository fields to default the Go import path

.github/workflows/ci.yml
We are seeing the job “tests on windows-latest/current” fail in the merge queue somewhat regularly. The job shows up as skipped in the GHA UI, and the summary has a message
> The hosted runner encountered an error while running your job. (Error Type: Disconnect).
This usually happens because the machine becomes unresponsive and GitHub Actions throws out the runner.
Split the windows acceptance tests into 2 partitions to distribute the load on 2 runners.
=> Split windows acceptance tests into 2 partitions

tests/integration/integration_python_test.go, tests/integration/python/config-getter-types/.gitignore, tests/integration/python/config-getter-types/Pulumi.yaml, tests/integration/python/config-getter-types/__main__.py, tests/integration/python/config-getter-types/requirements.txt
Fixes https://github.com/pulumi/pulumi/issues/16879
I verified that the test fails without the additional overloads from https://github.com/pulumi/pulumi/pull/16878.
=> Add regression test for config overloads

pkg/codegen/dotnet/gen.go, pkg/codegen/dotnet/gen_program.go, pkg/codegen/dotnet/gen_program_expressions.go, pkg/codegen/dotnet/utilities.go
When running .NET conformance tests, we use local nuget packages for testing, generating from the `Pack` method of language plugins. This PR extracts the version and package name correctly from the local dependencies map and adds to the generated program and generated sdks
=> Fix up local dependencies in .NET codegen

pkg/cmd/pulumi/package_add.go
The locally generated SDKs can be installed using the project's package management tool, such as poetry, pip, npm ...
Detect the appropriate tool and print out instructions. This logic really should live in the language runtimes, where the detection is a bit more elaborate, but for the initial preview release, this works well enough.
pip example:
```
Successfully generated a Python SDK for the random package at /Users/julien/tmp/test-add-2/sdks/random
To use this SDK in your Python project, run the following command:
echo sdks/random >> requirements.txt
pulumi install
You can then import the SDK in your Python code with:
import pulumi_random as random
```
pnpm example:
```
Successfully generated a Nodejs SDK for the random package at /Users/julien/tmp/test-add-pnpm/sdks/random
To use this …
```
=> Add Nodejs and Python instructions for `package add`

pkg/cmd/pulumi/package_add.go
for example with the random provider, it will print:
```
Successfully generated a .NET SDK for the random package at /path/to/program/sdks/random
To use this SDK in your .NET project, run the following command:
dotnet add reference sdks/random
You also need to add the following to your .csproj file of the program:
<DefaultItemExcludes>$(DefaultItemExcludes);sdks/**/*.cs</DefaultItemExcludes>
You can then use the SDK in your .NET code with:
using Pulumi.Random;
```
=> .NET link instructions in pulumi package add

pkg/cmd/pulumi/package_add.go
for example with the random provider, it will print:
```
Successfully generated a Go SDK for the random package at /home/fraser/projects/example-go/sdks/random
To use this SDK in your Go project, run the following command:
go mod edit -replace example.com/pulumi-random/sdk/go/random=sdks/random
You can then use the SDK in your Go code with:
import "example.com/pulumi-random/sdk/go/random"
```
=> Go link instructions in pulumi package add

changelog/pending/20240812--programgen-python--fix-generated-apply-calls-with-pulumi-all.yaml, pkg/codegen/python/gen_program.go, pkg/codegen/python/gen_program_expressions.go, tests/testdata/codegen/iterating-optional-range-expressions-pp/python/iterating-optional-range-expressions.py, tests/testdata/codegen/transpiled_examples/azure-app-service-pp/python/azure-app-service.py
Noticed while working on another codegen related task. Python apply calls weren't being generated correctly, they looked valid but they didn't actually execute. They would fail with an error that the lambda had been called without all required positional arguments.
This fixes it to use `all` in dictionary form and to index into the dictionary in the lambda body.
=> Fix apply in python

pkg/backend/httpstate/client/client_test.go, pkg/cmd/pulumi/deployment_settings_utils_test.go, pkg/cmd/pulumi/util.go, sdk/go/common/apitype/deployments.go
This PR fixes deployment settings serialization/deserialization:
- `repoUrl` was being incorrectly serialized as `repoURL`, which for JSON was not a problem as it is case insensitive ([To unmarshal JSON into a struct, Unmarshal matches incoming object keys to the keys used by Marshal ..., preferring an exact match but also accepting a case-insensitive match.](https://pkg.go.dev/encoding/json#Unmarshal)), but YAML is case sensitive.
- `time.Duration` unmarshalling failed as it was not consistent with the way the service "stringifies" the durations. I am bringing the custom marshallers implemented under `DurationMarshaller` (it is called `WorkflowTimeout` in the service but since there is no notion of Workflows here, I renamed to something more explicit).
=> Fix deployment settings serialization and keys consistency

changelog/pending/20240813--sdk-python--fix-the-type-of-stackreference-outputs-to-be-dict-str-any.yaml, sdk/python/lib/pulumi/stack_reference.py
Fixes https://github.com/pulumi/pulumi/issues/16955.
`dict` is the same as `Dict[unknown, unknown]` but for stack references we know the keys are strings, and it's more useful to treat the values as any than unknown.
=> Fix StackReference.outputs typing

cmd/pulumi-test-language/interface.go, cmd/pulumi-test-language/test_host.go, cmd/pulumi-test-language/tests.go
We have a load of engine logic in the grpc layer for providers. Skipping that and going directly to the Provider objects doesn't give an accurate test of how the engine will work from these tests.
This is _really_ needed when we want to test things like the engine options to disable various resource properties (e.g. resource references, or disable provider preview). Currently all that engine logic lives in the provider client grpc layer (well it would if it was complete). 
This PR doesn't add tests for any of that but splits the test_host into its own file and handles the grpc wrapping. It's questionable if we care that much about these old untested flags (like disable outputs), but we will want to make use of this change for testing any new flags (e.g. adding integer support and checking …
=> Use grpc providers in conformance tests

changelog/pending/20240813--sdk-python--fix-the-type-of-stackreference-outputs-to-be-dict-str-any.yaml, sdk/python/Makefile, sdk/python/lib/pulumi/stack_reference.py, sdk/python/lib/test_types/stack_reference.py, sdk/python/pyrightconfig.json, sdk/python/requirements.txt
Updates the type for the `outputs` property of the `StackReference` class to be a `dict[str, Any]` instead of a `dict` (with unknown keys and values). This change fixes the type error in the referenced issue.
Fixes #16955
=> Fix Pyright type checking of "StackReference#outputs"

sdk/go/common/util/executable/executable.go
Found by https://github.com/uber-go/nilaway
If Stat returned an error other than `IsNotExist` we would attempt to dereference the fileInfo and trigger a nil access.
This fixes it so Stat errors are returned as errors (except for `IsNotExist`).
=> Fix potential nil panic in FindExecutable

changelog/pending/20240814--docs--use-componentresourceoptions-for-components.yaml, pkg/codegen/docs/gen.go, tests/testdata/codegen/embedded-crd-types/docs/component/_index.md, tests/testdata/codegen/enum-reference/docs/myModule/iamresource/_index.md, tests/testdata/codegen/hyphen-url/docs/registrygeoreplication/_index.md, tests/testdata/codegen/methods-return-plain-resource/docs/configurer/_index.md, tests/testdata/codegen/other-owned/docs/barresource/_index.md, tests/testdata/codegen/other-owned/docs/fooresource/_index.md, tests/testdata/codegen/other-owned/docs/otherresource/_index.md, tests/testdata/codegen/plain-schema-gh6957/docs/staticpage/_index.md, tests/testdata/codegen/simple-methods-schema-single-value-returns/docs/foo/_index.md, tests/testdata/codegen/simple-methods-schema/docs/foo/_index.md, tests/testdata/codegen/simple-plain-schema-with-root-package/docs/component/_index.md, tests/testdata/codegen/simple-plain-schema/docs/component/_index.md, tests/testdata/codegen/simple-resource-schema-custom-pypackage-name/docs/otherresource/_index.md, tests/testdata/codegen/simple-resource-schema/docs/barresource/_index.md, tests/testdata/codegen/simple-resource-schema/docs/fooresource/_index.md, tests/testdata/codegen/simple-resource-schema/docs/otherresource/_index.md, tests/testdata/codegen/simple-yaml-schema/docs/otherresource/_index.md
Use `ComponentResourceOptions` instead of `CustomResourceOptions` for components (for the SDKs that have `ComponentResourceOptions`) in generated docs.
Fixes #16928
=> [docs] Use `ComponentResourceOptions` for components

sdk/python/lib/test/automation/test_local_workspace.py, sdk/python/lib/test/langhost/inheritance_translation/__main__.py, sdk/python/lib/test/langhost/input_values_for_outputs/__main__.py, sdk/python/lib/test/langhost/output_property_dependencies/__main__.py, sdk/python/lib/test/langhost/stack_output/__main__.py, sdk/python/lib/test/test_broken_dynamic_provider.py, sdk/python/lib/test/test_deprecated.py, sdk/python/lib/test/test_monitor_termination.py, sdk/python/lib/test/test_resource.py, sdk/python/lib/test/test_stack_reference.py, sdk/python/lib/test/test_stack_registers_outputs.py, sdk/python/lib/test/test_types_input_type.py, sdk/python/lib/test/test_types_output_type.py
These were found by running `python -m pylint ./lib/test --rcfile=.pylintrc` in the python SDK folder. Currently we don't consistently run pylint (or mypy for that matter) against the test folder and it's built up a number of issues before we can turn it on.
This PR fixes some of the smaller less common ones, a baby step towards getting the tests fully linted and type checked. Each issue is resolved in a single commit named for the pylint issue it fixed.
=> Fixing a few pylint errors in the python test folder

sdk/go/common/resource/plugin/provider_plugin.go
Found by https://github.com/uber-go/nilaway
If an `InitError` was constructed without any reasons (possible, nothing checks this on the grpc boundary) then `Error` would panic.
This fixes it to instead return a default error message.
=> Fix potential nil panic in InitError.Error

changelog/pending/20240814--backend-service--prefer-pulumi_access_token-set-in-the-environment-over-the-one-stored-in-the-config-when-they-dont-match.yaml, pkg/backend/httpstate/backend.go
The common order of priority for configuration is (in descending order of priority):
- command line flags
- environment variables
- configuration
When a user uses the `PULUMI_ACCESS_TOKEN` environment variable, we also currently save this to a configuration file.  While it could be considered somewhat questionable writing the secret in the environment variable to disk in the first place, it is somewhat likely that users rely on that behaviour and we don't want to change that.
However it is also very confusing to users that if they change the `PULUMI_ACCESS_TOKEN` environment variable that we still keep re-using the access token that is already stored in the configuration.  It could potentially be considered a breaking to prefer the `PULUMI_ACCESS_TOKEN` variable over the access token set …
=> prefer environment over config for PULUMI_ACCESS_TOKEN

pkg/codegen/dotnet/gen.go
Fixes https://github.com/pulumi/pulumi-dotnet/issues/320
If conditions here were such that we could try to add the 'version.txt' file twice if both SupportPack and RespectSchemaVersion were both set.
=> Don't add 'version.txt' file twice if RespectSchemaVersion and SupportPack are set

changelog/pending/20240813--cli--warn-that-query-is-planned-to-be-removed.yaml, pkg/cmd/pulumi/query.go
```
$ pulumi query
warning:
================================================================================
query was an experimental command that we have opted to discontinue. It is due
to be removed in a future release before the end of this year (2024).
If you have any feedback or concerns, please let us know by commenting on the
issue at https://github.com/pulumi/pulumi/issues/16964.
================================================================================
```
=> Add a warning to `pulumi query` that we plan to remove it

changelog/pending/20240813--sdk-nodejs--fix-type-checking-of-output-record-string-any.yaml, sdk/nodejs/output.ts, sdk/nodejs/tests/stackReference.spec.ts
This change fixes the TypeScript checking of output "any" maps. Previously, as in the referenced issue, an `Output<Record<string, any>>` had unusable properties with the lifting mechanisms in TypeScript. That is, for such an output `foo`, using `foo["bar"]` would typically result in a type error, as the type would be:
```typescript
pulumi.OutputInstance<unknown> | pulumi.Output<any>
```
This union type with unknown results in a type error on trying to use `foo["bar"].apply(...)`. This is caused by the conditional type of `Lifted<T>` having a condition `T[P] extends OutputInstance<infer T1>` evaluating to the true branch, with `T1` inferred as `unknown`.
This is because `any extends OutputInstance<unknown>`.
Adding a strict check for `any` in the conditional type `Lifted<T>` fixes the …
=> Fix TypeScript checking of Output maps of "any" values

changelog/pending/20240815--cli-package--allow-pulumi-package-add-to-work-with-arbitrary-schema-sources.yaml, pkg/cmd/pulumi/package_add.go
`schemaFromSchemaSource` is capable of taking multiple types of sources (plugin, plugin@version, path to plugin). If the plugin is specified (possible with a version), then it is already capable of downloading the plugin. 
We don't need to call `pluginInstallCommand.Run`, and by doing so we prevent `pulumi package add` from accepting different source kinds.
=> Don't call pluginInstallCommand, defer to schemaFromSchemaSource

pkg/codegen/testing/test/program_driver.go, tests/testdata/codegen/aws-s3-folder-pp/dotnet/aws-s3-folder.cs
The Python and .NET issues are no longer present, so we no longer need to skip these.
Fixes #8062
=> [programgen] Unskip some Python and .NET tests

pkg/cmd/pulumi/state_edit.go
This help text was just wrong before (probably copy pasted).  Correct it.
=> fix help text for --stack in state edit

pkg/cmd/pulumi/util_remote.go
I noticed this variable being misspelled (although the argument luckily is spelled correctly already.  Fix it.
=> correct spelling of variable

pkg/cmd/pulumi/convert-trace.go
The trace-file is required, not optional.  Use angle brackets instead of square ones to denote that properly.
=> fix usage string for convert-trace

changelog/pending/20240815--docs--show-envvars-for-provider-nested-types.yaml, pkg/codegen/docs/gen.go, pkg/codegen/docs/gen_function.go, tests/testdata/codegen/kubernetes20/docs/provider/_index.md, tests/testdata/codegen/plain-object-defaults/docs/provider/_index.md, tests/testdata/codegen/plain-object-disable-defaults/docs/provider/_index.md
Some providers have nested types whose properties can also be configured via envvars. Until now, only top-level (non-nested) envvars are shown. This change also shows the envvars for nested types.
Fixes #8323
=> Provider docs: Show envvars for nested types

changelog/pending/20240816--cli--show-a-better-message-when-logging-out-with-all.yaml, pkg/cmd/pulumi/logout.go
When logging out with `--all` you get a bad message:
```
$ pulumi logout --all
Logged out of
```
This is because with `--all` there is no cloud URL to print out at the end.
This change improves the message to say "Logged out of everything".
Fixes #16997
=> Show a better message when logging out with --all

changelog/pending/20240815--auto-go--add-remote-automation-api-support-for-choosing-a-deployment-runner-pool.yaml, pkg/cmd/pulumi/util_remote.go, sdk/go/auto/local_workspace.go, sdk/go/auto/remote_workspace.go, sdk/go/auto/stack.go
Adds support to the automation API for specifying a pool of deployment runners. Follows:
- #16492
Fixes #16987
=> Add Go automation API for deployment runners

.github/workflows/ci.yml, .github/workflows/on-pr.yml, .github/workflows/pr-test-acceptance-on-dispatch.yml
With recent changes reducing pressure on minimizing build times, and to support implementing #16960, we can now build all binaries in pull request CI.
Prerequisite for #16960
=> Build all binaries in pull requests

changelog/pending/20240805--engine--allow-provider-to-be-unknown-during-preview.yaml, pkg/engine/lifecycletest/pulumi_test.go, pkg/resource/deploy/source_eval.go, sdk/go/common/resource/plugin/provider_plugin.go
Currently when a provider is not known when trying to call construct, we error out.  A provider not being known can however legitimately happen during a preview, for example when setting up an eks cluster, and then using that kubeconfig to set up a kubernetes provider.
Users can currently work around that by using `--skip-preview`, and only going through the actual up, where the provider is known.  This is however not a great user experience.
Return a specific error from the provider Construct call, which we can then use in the resource monitor to fake constructing a resource with all unknown outputs.  This way the preview can still succeed, but any dependencies will also end up being unknown.
Fixes https://github.com/pulumi/pulumi/issues/16331
=> create unknowns when the provider is not known during construct

changelog/pending/20240809--sdk-go--unmarshal-pointers-correctly-if-destination-type-is-any.yaml, sdk/go/pulumi/resource_test.go, sdk/go/pulumi/rpc.go, sdk/go/pulumi/rpc_test.go
Currently when unmarshalling resource references into a destination that's of type `any`, we loose the pointer information, and just marshal it into the base type, because the destination is not a pointer type.
However for resource references that's not quite correct, as we do want to unmarshal it to the pointer type, so it can be a `pulumi.Resource`, and be used as such.  Make that so here.
Fixes https://github.com/pulumi/pulumi/issues/15788
This could be considered a breaking change, though I think we can consider this a bugfix instead.
=> unmarshal pointers correctly if destination type is any

changelog/pending/20240821--sdkgen-go--use-provided-importbasepath-for-parameterized-sdks.yaml, pkg/cmd/pulumi/package_add.go, pkg/codegen/go/gen.go, tests/integration/go/parameterized/go.mod, tests/integration/go/parameterized/go.sum, tests/integration/go/parameterized/sdk/go/pkg/go.mod, tests/integration/integration_go_test.go
When generating a parameterized SDK, the dynamic tf bridge [provides the appropriate ImportBasePath](https://github.com/pulumi/pulumi-terraform-bridge/blob/87006ca9216a94d8552f1836bdf5b079fa6c7aca/dynamic/info.go#L62) for us, use it instead of trying to determine it ourselves.
Fixes https://github.com/pulumi/pulumi/issues/17018
=> Use provided ImportBasePath for parameterized SDKs

changelog/pending/20240821--sdkgen-nodejs--set-minimum-version-of-core-sdk-when-using-parameterization.yaml, pkg/codegen/nodejs/gen.go, tests/integration/nodejs/parameterized/sdk/nodejs/package.json
When generating an SDK with parameterization (aka local SDK), we need `@pulumi/pulumi@^3.129.0` as the core SDK dependency. Older versions do not support the packageRef argument added the runtime calls.
Fixes https://github.com/pulumi/pulumi/issues/17020
=> Set minimum version of core SDK when using parameterization

pkg/codegen/testing/test/helpers.go, scripts/get-language-providers.sh
See https://github.com/pulumi/pulumi-dotnet/releases/tag/v3.66.2
=> Bump .NET version after 3.66.2 release

sdk/go/common/util/cmdutil/exit.go, sdk/go/common/util/cmdutil/exit_test.go
When an error occurs in Go, there is often a need to "wrap" the error and propagate it upwards. For instance, if a "file not found" error occurs while trying to read a `Pulumi.yaml`, we want to surface both those pieces of information to the consumer of the error. Since 1.13, Go provides support for natively wrapping errors using e.g. the `%w` format specified in `fmt.Errorf` and the `Unwrap() []error` interface method. Prior to 1.13. libraries such as `multierror` provided a similar function in the absence of standard-library support.
Due to its age, the `pulumi/pulumi` codebase uses both Go-native error wrapping and `multierror`. It would likely be good to converge on the former and lose a dependency/remove extraneous code paths. One key difference between the two approaches is in how …
=> Clean up multi-error rendering

changelog/pending/20240822--sdk-nodejs--prevent-double-close-on-oom-detection-channel.yaml, sdk/nodejs/cmd/pulumi-language-nodejs/main.go
While looking at https://github.com/pulumi/pulumi/issues/17040 I noticed that the condition in the OOM detection was missing parentheses. This could potentially make us call `close(o.waitChain)` twice, resulting in a panic. In practice this does not happen because we only ever see at most one of the two strings we are looking for.
Note that this does *not* fix https://github.com/pulumi/pulumi/issues/17040
=> Prevent double close on OOM detection channel

changelog/pending/20240822--sdk-nodejs--fix-nodejs-oom-detection-condition.yaml, sdk/nodejs/cmd/pulumi-language-nodejs/main.go, tests/integration/nodejs/oom/index.js
The condition had a single `=` in the string instead of a `==`.
This PR also ensures that stop scanning for errors when the process ends, so we don’t wait for the scanning timeout in case the node process crashes with another error.
Fixes https://github.com/pulumi/pulumi/issues/17040
=> Fix NodeJS OOM detection condition

changelog/pending/20240820--programgen--improve-the-error-message-for-an-invalid-method-name.yaml, pkg/codegen/schema/bind.go
As part of investigating https://github.com/pulumi/pulumi/issues/17025, I got an un-actionable error message when trying to come up with something that would fit with `Call`. This improves the error message.
=> Improve the error message for an invalid method name

changelog/pending/20240815--cli-install--fix-installation-of-dependencies-that-do-not-specify-a-version-eg-yaml.yaml, pkg/cmd/pulumi/install.go, tests/smoke_test.go
Previously, unlike pulumi up, pulumi install did not get latest version of one is not specified for dependencies/plugins.
YAML allows there to not be a version specified so this caused an issue in YAML.
Fixes #16920
=> Get latest version if one not specified in pulumi manifest

changelog/pending/20240822--cli-display--print-panic-banners-for-snapshot-integrity-errors.yaml, pkg/cmd/pulumi/errors.go, pkg/resource/deploy/snapshot.go
Snapshot integrity errors are generally indicative of a serious issue in the Pulumi engine. When they occur, we'd like users to file issues with as much detail as possible so that we can track them down and fix them. This commit adds a new custom error type for snapshot integrity errors and a case to the top-level error handler that spots these errors and prints out a banner asking the user to file an issue.
Fixes #16950
=> Print panic banners for snapshot integrity errors

changelog/pending/20240823--sdkgen-go--update-package-add-instructions-for-go.yaml, pkg/cmd/pulumi/package_add.go
In https://github.com/pulumi/pulumi-terraform-bridge/pull/2345 we set the `RootPackageName` so that local SDKs generate a flat structure without an extra layer of nesting. Update the instructions to no longer add the package name to the linking instructions.
Fixes https://github.com/pulumi/pulumi/issues/17054
=> Update package add instructions for go

pkg/secrets/passphrase/manager.go
Pointed out in https://github.com/pulumi/home/issues/3601#issuecomment-2306413266.
If DecryptValue fails we don't currently propagate the information about that error anywhere, instead just returning a ErrIncorrectPassphrase error. This adds a log statement so we can at least ask users to run with `-v=7` to see what error is happening.
=> Log error in symmetricCrypterFromPhraseAndState

changelog/pending/20240826--auto-go--include-panic-value-in-message-for-non-error-panics.yaml, sdk/go/auto/stack.go
Panic values can be arbitrary values, and are often plain strings
=> Include panic value in message for non-error panics

changelog/pending/20240827--pkg--remove-ds-auto-api-dependency-on-tests.yaml, pkg/cmd/pulumi/deployment_settings_config_test.go, pkg/cmd/pulumi/deployment_settings_utils_test.go, pkg/go.mod, pkg/go.sum
Initially I relied `auto.NewLocalWorkspace` to setup the tests workspace and clone the sample git repo. This is required for testing git specific logic (like repo url calculation and remote/branch lookup).
The automation api relies on the pulumi binary to to operate but we don't rely on any of its features on these tests. To simplify it and remove the need of having the binary in the path, I am replacing it by a simple logic to clone the repo in a tmp directory.
=> Do not rely on auto api for cloning repos on ds tests

changelog/pending/20240820--cli-display--improve-rendering-of-update-diffs-in-some-circumstances.yaml, pkg/backend/apply.go, pkg/backend/display/diff.go, pkg/backend/display/diff_test.go, pkg/backend/display/testdata/json-yaml/json-text-change.json.create-diff.txt, pkg/backend/display/testdata/json-yaml/json.json.create-diff.txt, pkg/backend/display/testdata/json-yaml/yaml-text-change.json.create-diff.txt, pkg/backend/display/testdata/json-yaml/yaml.json.create-diff.txt, pkg/backend/display/testdata/not-truncated/failed-stacks-dont-rewrite-operations.json.create-diff.txt, pkg/backend/display/testdata/not-truncated/stack-output-resource-diff.json.create-diff.txt, pkg/backend/display/testdata/not-truncated/template-body.json.create-diff.txt, pkg/backend/display/testdata/not-truncated/up-2.json.create-diff.txt, pkg/backend/display/testdata/not-truncated/up-3.json.create-diff.txt, pkg/backend/display/testdata/not-truncated/up-4.json.create-diff.txt, pkg/backend/display/testdata/not-truncated/up-5.json.create-diff.txt, pkg/backend/display/testdata/not-truncated/up.json.create-diff.txt, pkg/backend/display/testdata/not-truncated/url-encoded-stack-output-diff.json.create-diff.txt, pkg/backend/display/testdata/not-truncated/webserver-userdata.json.create-diff.txt, pkg/backend/display/testdata/truncated/up-truncate.json.create-diff.txt
This fixes a bug found while working on another internal issue. This bug is reproduced in the first commit which adds tests, clearly showing the behavior of the incoherent rendering. The second commit makes the change and updates the tests.
Fixes #17028
Fixes all outputs being printed adjacent without context, as seen in the linked issue and the first commit:
```
--outputs:--
readme: "line 1\nline2\nline3\nline4"
--outputs:--
arn                : "arn:aws:iam::616138583583:role/eks-role-24b1266"
assumeRolePolicy   : (json) {
Statement: [
[0]: {
Action   : "sts:AssumeRole"
Effect   : "Allow"
Principal: {
Service: "eks.amazonaws.com"
}
Sid      : ""
}
]
Version  : "2008-10-17"
}
createDate         : "2022-02-09T23:14:50Z"
id                 : "eks-role-24b1266"
inlinePolicies     : [
[0]: { …
```
=> Fix rendering of output events in rendering update diffs

cmd/pulumi-test-language/go.mod, cmd/pulumi-test-language/go.sum, pkg/backend/backend.go, pkg/backend/httpstate/environments.go, pkg/backend/mock.go, pkg/cmd/pulumi/config_env.go, pkg/cmd/pulumi/config_env_init.go, pkg/cmd/pulumi/config_env_init_test.go, pkg/cmd/pulumi/config_env_ls_test.go, pkg/cmd/pulumi/config_env_test.go, pkg/go.mod, pkg/go.sum, sdk/go/pulumi-language-go/go.mod, sdk/go/pulumi-language-go/go.sum, sdk/nodejs/cmd/pulumi-language-nodejs/go.mod, sdk/nodejs/cmd/pulumi-language-nodejs/go.sum, sdk/python/cmd/pulumi-language-python/go.mod, sdk/python/cmd/pulumi-language-python/go.sum, tests/go.mod, tests/go.sum, tests/integration/construct_component_configure_provider/testcomponent-go/go.mod, tests/integration/construct_component_configure_provider/testcomponent-go/go.sum
This adds supports for ESC Projects (including `pulumi config env` commands)
The main functional changes are to `pulumi config env init`.
(This PR will merge into the `features/esc-projects` branch, only merging to master when we publicly rollout ESC Projects)
(my stack is test_project/random5)
```bash
❯ pulumi config env init
Creating environment test_project/random5 for stack random5...
Value
{
"pulumiConfig": {}
}
Definition
values:
pulumiConfig: {}
error: prompt aborted
❯ pulumi config env init --env abc
Creating environment test_project/abc for stack random5...
Value
{
"pulumiConfig": {}
}
Definition
values:
pulumiConfig: {}
error: prompt aborted
❯ pulumi config env init --env abc/def
Creating environment abc/def for stack random5...
Value
{
"pulumiConfig": {}
}
Definition
values: …
```
=> Add support for ESC Projects

pkg/codegen/testing/utils/host.go, pkg/resource/deploy/deploytest/pluginhost.go, pkg/resource/deploy/deploytest/pluginhost_test.go
These plugins aren't really on disk and setting the path attribute confuses other parts of the system. Instead just make them work like normal in-memory plugins that happen to read their schemas from testdata.
=> Remove path usage from deploytest

changelog/pending/20240827--cli-state--succeed-when-theres-already-a-provider-with-an-identical-urn-in-the-destination-stack-if-the-inputs-match.yaml, pkg/cmd/pulumi/state_move.go, pkg/cmd/pulumi/state_move_test.go
Currently when there's already a provider in the destination stack with the same URN as a provider in the source stack (for a resource that is about to be moved) we error out, unless the IDs match. This is done so we don't assign a provider to a resource that won't work for it (e.g. provider with the same name but that have different AWS region setups).
However we can be a little bit smarter than this, and assign a resource a provider from the destination stack as long as all the provider inputs match.  If all the inputs match, we can assume that the provider will give us a valid situation for the resource.
Fixes https://github.com/pulumi/pulumi/issues/16983
=> state_move: allow providers with same URN if inputs match

changelog/pending/20240823--sdk-nodejs--respect-node-version-and-nvmrc-files-in-pulumi-install.yaml, sdk/nodejs/cmd/pulumi-language-nodejs/main.go, sdk/nodejs/cmd/pulumi-language-nodejs/main_test.go
When using the `--use-language-version-tools` flag with `pulumi install`, and `fnm` is installed, we look for `.nvmrc` and `.node-version` files and install the requested version.
This is meant to be used within containers where we don’t run within a shell. When running locally, fnm, nvm and similar tools manage the nodejs version via their shell integration and ensure the correct version is set.
pulumi-docker-containers makes use of this in https://github.com/pulumi/pulumi-docker-containers/pull/253
=> Respect .node-version and .nvmrc files in `pulumi install`

pkg/cmd/pulumi/new_acceptance_test.go, sdk/go/common/env/env.go, sdk/go/common/workspace/creds.go
Looking into writing some mocked tests for `state destroy` this env var is touched on the login path and is currently not in our "env" system so tricky to mock out. This is a small PR to just lift it into the env system without worrying about plumbing the env instance all the way down to where it's used (yet).
=> Make a PULUMI_BACKEND_URL an env.Var instance

.readthedocs.yaml, docs/Makefile, docs/requirements.txt, docs/sphinx/conf.py
Rather than embedding commands into the `.readthedocs.yaml` configuration file, this commit has Read the Docs simply call the existing `docs/Makefile`'s `build` target, so that we can centralise instructions for building documentation in one place.
=> Have Read the Docs use `docs/Makefile`

pkg/cmd/pulumi/env.go
The esc library already defines a default pulumi workspace implementation. We can just use that rather than having another copy here as well.
=> Use esc/workspace.DefaultPulumiWorkspace in env cmd

pkg/backend/httpstate/backend.go, pkg/backend/httpstate/stack.go, pkg/cmd/pulumi/org.go, pkg/cmd/pulumi/org_search.go, pkg/cmd/pulumi/org_search_ai.go, pkg/cmd/pulumi/policy_publish.go, pkg/cmd/pulumi/util.go, pkg/workspace/creds.go, sdk/go/common/workspace/creds.go
In preparation for moving `workspace.GetCurrentCloudURL` to the package workspace we need to move `GetBackendConfigDefaultOrg` first.
(N.B. this also uses `workspace.GetPulumiConfig` which we also want to move, but will take a bit longer)
=> Move GetBackendConfigDefaultOrg to pkg workspace

.github/workflows/ci-run-test.yml, sdk/python/scripts/test_auto.sh, sdk/python/scripts/test_fast.sh
We currently observe that coverage data for Node.js and Python SDKs are not stable between multiple master commits.
My working theory on what happens, taking Node.js as an example:
- Our test runs are spread between multiple independent actions
- Each node-testing action produces coverage data
- We then call the `nyc report` command to produce the `cobertura-coverage.xml` file
- The XML file gets uploaded inside a `coverage-*` artifacts
- We then download all coverage files with `merge-multiple: true` option [here](https://github.com/pulumi/pulumi/blob/master/.github/workflows/ci.yml#L445)
- Only one (random) `cobertura-coverage.xml` file survives and is uploaded to Codecov
- The resulting data are noisy
A similar clash happens for Python too.
This PR adds UUID suffixes to coverage file …
=> Give Node.js and Python coverage files unique names to improve code coverage quality

pkg/backend/httpstate/backend.go, pkg/backend/httpstate/backend_test.go, pkg/cmd/pulumi/logout.go, pkg/cmd/pulumi/pulumi.go, pkg/workspace/context.go, pkg/workspace/mock.go
Add GetStoredCredentials to the package workspace interface. We can't remove the old copy of the code in sdk/go/common, but everywhere in pkg has been updated to use the interface call instead. 
This also allowed the writing of a few more test cases for the `ValueOrDefaultURL` method in the httpstate package.
=> Add GetStoredCredentials to pkg workspace

changelog/pending/20240829--cli--include-all-engine-events-in-the-event-log.yaml, pkg/backend/display/display.go, pkg/backend/display/display_test.go, tests/integration/integration_nodejs_test.go
In https://github.com/pulumi/pulumi/pull/14607 we introduced filtering of engine events before they are displayed.  However in the process we also started filtering them from the event log.  The event log is used for two things, the automation API and debugging.  The automation API already ignores events it doesn't know about (and it should because a new version of the CLI can always introduce new events that aren't filtered), and for debugging it is very useful to have all events in the event log.
In fact we are going to introduce a new debugging event, which the automation API will need (plugins for IDEs are going to be written using the automation API to intercept the engine events).
Move the filtering after the writing to the event log, so we always have all events there, but still …
=> Include all engine events in the event log

pkg/cmd/pulumi/plugin.go, sdk/go/common/workspace/plugins.go, sdk/go/common/workspace/plugins_test.go
Before this fix GetPluginInfo would error because stat on the expected `pulumi-resource-exe` file would fail (because it didn't exist). This fixes it to fallback to looking at the folder instead.
=> Fix GetPluginInfo with shimless project plugins

docs/documentation.md, docs/sphinx/conf.py
This commit documents how developer documentation is deployed to Read the Docs. It also fixes up some configuration options for displaying and expanding the sidebar tables of contents.
=> Document developer documentation deployments

docs/.gitignore, docs/Makefile, docs/README.md, docs/documentation.md, docs/make.py, docs/references/README.md, docs/references/proto.md.tmpl, docs/sphinx/conf.py, proto/README.md
Protocol buffer (Protobuf) definitions are the source of truth for many of the types and interfaces used across Pulumi products. Documentation written in Protobuf files is already used to generate commented code e.g. when producing gRPC stubs and clients. This commit extends this to generate reference developer documentation from our Protobuf files using the `protoc-gen-doc` plugin for `protoc`, which exports Protobuf documentation as Markdown. This is then incorporated into the build process for our developer documentation so that we can refer to Protobuf types and gRPC services and messages across our documentation.
In order to provide a degree of portability, and also not to require developers (or the Read the Docs build process) to download and manage the `protoc` / `protoc-gen-doc` …
=> Generate reference documentation from Protobufs

docs/.gitignore, docs/Makefile, docs/README.md, docs/architecture/README.md, docs/architecture/deployment-execution/README.md, docs/architecture/deployment-execution/providers.md, docs/architecture/deployment-execution/resource-registration.md, docs/architecture/deployment-execution/state.md, docs/architecture/mlcs.md, docs/documentation.md, docs/make.py, docs/references/README.md, docs/references/proto.md.tmpl, docs/sphinx/conf.py, proto/README.md
This commit ports over some of the old content from `developer-docs`. While there we flesh out some bits, freshen up others by linking to our newly-generated Protobuf documentation, and migrate the various diagrams to Mermaid so that they can e.g. support zooming in the browser with D3.
=> Flesh out architecture documentation

changelog/pending/20240830--pkg--added-newcachedloader-for-caching-schema-loads.yaml, pkg/codegen/schema/loader.go, pkg/codegen/schema/loader_cached.go, pkg/codegen/schema/loader_cached_test.go
Currently all the caching logic for schemas is in `pluginLoader` itself, that means other loader implementations (like the grpc `LoaderClient`) don't do any caching.
This splits the cache logic out of `pluginLoader` into a new `cachedLoader`. `NewPluginLoader` internally wraps with that new type (unless `cacheOptions.disableFileCache` is set). But other loaders can now call `NewCachedLoader` to get a caching layer added. We'll want to go through the grpc codegen and converter implementations to make use of this.
=> Split caching logic into it's own type to use with LoaderClient

.goreleaser.yml, cmd/pulumi-test-language/go.mod, cmd/pulumi-test-language/go.sum, pkg/backend/diy/backend.go, pkg/backend/diy/backend_test.go, pkg/cmd/pulumi/pulumi.go, pkg/go.mod, pkg/go.sum, pkg/testing/integration/program.go, sdk/go.mod, sdk/go.sum, sdk/go/common/tools/paths.go, sdk/go/common/workspace/paths.go, sdk/go/pulumi-language-go/go.mod, sdk/go/pulumi-language-go/go.sum, sdk/nodejs/cmd/pulumi-language-nodejs/go.mod, sdk/nodejs/cmd/pulumi-language-nodejs/go.sum, sdk/python/cmd/pulumi-language-python/go.mod, sdk/python/cmd/pulumi-language-python/go.sum, tests/go.mod, tests/go.sum, tests/integration/construct_component_configure_provider/testcomponent-go/go.mod, tests/integration/construct_component_configure_provider/testcomponent-go/go.sum, tests/integration/construct_component_provider_propagation/go/go.mod, tests/integration/construct_component_provider_propagation/go/go.sum, tests/integration/construct_component_resource_options/go/go.mod, tests/integration/construct_component_resource_options/go/go.sum, tests/integration/construct_nested_component/go/go.mod, tests/integration/construct_nested_component/go/go.sum
This change switches back to using the stdlib's `os/user` to get the current user. We originally used `os/user` but moved to a drop-in replacement (https://github.com/tweekmonster/luser) in #5065 which worked better without `cgo` at the time. However, https://github.com/tweekmonster/luser no longer appears to be maintained and the stdlib's `os/user` has a pure Go implementation (which doesn't require `cgo`) which has improved since then, so we should be able to switch back to it now.
Commits:
1. Update the *.go files
2. Result of running `make tidy`
Fixes #17123
=> Switch back to `os/user` to get the current user

pkg/engine/lifecycletest/loader_test.go, sdk/go/pulumi-language-go/main.go, sdk/nodejs/cmd/pulumi-language-nodejs/main.go, sdk/python/cmd/pulumi-language-python/main.go
Also close the loader client connection when finished with it.
=> Use cached loader in RPC codegen functions

sdk/nodejs/tests/runtime/closure-integration-tests.ts
Tests for Nodejs closure serialisation are currently failing due to a bug in the node types, see https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/70432
=> Pin @types/node in closure tests

.github/workflows/ci-lint.yml, CONTRIBUTING.md, changelog/pending/20240903--ci--run-ci-with-go-1-22-and-1-23.yaml, scripts/get-job-matrix.py
Go 1.23 was released a couple weeks ago https://go.dev/blog/go1.23, update CI to use the 2 latest versions.
=> Update tests to run on Go 1.22 and 1.23

pkg/cmd/pulumi/preview.go, pkg/cmd/pulumi/up.go
After adding the engine bits for debugging in a previous PR (https://github.com/pulumi/pulumi/pull/17072), implement the option in the CLI that triggers it.  This by itself will have no effect still until the language runtimes have support for it. Therefore we keep it disabled until we've implemented this in the respective language runtimes.
The language runtime implementations will follow in subsequent PRs. I'm a bit unsure about the naming of the flag.  Maybe `--run-in-debugger` would be a better name?  Would be great to get some opinions on that (or any other suggestions fi someone has an idea).
=> wire up command line interface for running programs under a debugger

proto/.checksum.txt, proto/pulumi/provider.proto, sdk/proto/go/provider.pb.go, sdk/python/lib/pulumi/runtime/proto/provider_pb2.pyi
Prompted by https://github.com/pulumi/pulumi-azure-native/issues/3546. This documents that the `diffs` key in the diff response only supports top level property keys, not paths.
=> Document that 'diffs' only supports top level keys

changelog/pending/20240820--cli-display-plugin--render-download-progress-as-part-of-system-messages-during-pulumi-operations.yaml, pkg/backend/display/diff.go, pkg/backend/display/events.go, pkg/backend/display/json.go, pkg/backend/display/jsonmessage.go, pkg/backend/display/progress.go, pkg/backend/display/progress_bar.go, pkg/backend/display/progress_bar_test.go, pkg/backend/display/query.go, pkg/backend/display/tree.go, pkg/backend/display/watch.go, pkg/backend/httpstate/state.go, pkg/engine/deployment.go, pkg/engine/destroy.go, pkg/engine/events.go, pkg/engine/plugins.go, pkg/engine/progress.go, pkg/engine/progress_test.go, pkg/engine/query.go, pkg/engine/refresh.go, pkg/engine/update.go, sdk/go/common/apitype/events.go
When running a Pulumi operation such as a preview or an update, Pulumi will detect if plugins (e.g. an AWS provider) are missing and download and install them appropriately. Presently the user experience when this happens isn't great (see e.g. https://github.com/pulumi/pulumi/issues/14250), making it hard for the user to see what is happening/what is taking so long when required plugins are large.
This commit attempts to rectify this by continuing the work in https://github.com/pulumi/pulumi/pull/16094 that tracks download progress using engine events. In doing so, we are able to render multiple downloads as part of the existing "system messages" panel in the Pulumi output, and provide a clean view of what is going on when downloads must occur before program execution. Moreover, we …
=> Use events to report downloads as system messages

pkg/resource/deploy/step_generator.go
pulumi/pulumi#624 has been fixed for a number of years, delete before replace operations are now safe.
=> Cleanup old comment

pkg/codegen/schema/loader.go, pkg/codegen/schema/loader_test.go
We weren't passing Name and Version to `plugin.ParameterizeValue` when called in the schema loader. This information is supposed to be passed to `Parameterize` as its very common and saves the provider having to encode it into the byte value.
=> Fix bug in param loader

changelog/pending/20240903--engine--fix-panic-with-user-specified-plugin-paths.yaml, sdk/go/common/workspace/plugins.go, sdk/go/common/workspace/plugins_test.go
When the user specifies a provider with a specific path in the `Pulumi.yaml`, we later in the program assert that the path that was passed in also matches with the path where we found the plugin. We do this by using a string comparison, however that doesn't work if the path the user passes is not clean, e.g. has a trailing slash, or has a double slash, or some such.
Fix this by using `filepath.Clean` on the user supplied path, which these things up.
I was also briefly wondering if this works properly if the user passes in a path that is a symlink (it does), and wrote a test for that, checking that behaviour.
Fixes https://github.com/pulumi/pulumi/issues/17130
=> plugins: don't panic when the given path is not clean

.github/workflows/ci.yml, .github/workflows/on-merge.yml, .github/workflows/on-pr.yml, .github/workflows/pr-test-acceptance-on-dispatch.yml
Acceptance tests on Windows sometimes fail for mysterious reasons. It's unclear to me whether this is because the tests sometimes genuinely take too many resources, and break the windows host, or whether it's instability of the windows CI runners in general (it could also be both).
This is very annoying during merges, because for any failed test we need to re-do the merge, which means re-running all tests, which is both expensive and slow.
Instead, run the acceptance tests on windows during PRs always, but don't run them during merge.
I think this is okay to do because if there is a mismerge, I don't expect exclusively windows tests to fail, but I expect that to also affect Linux and MacOS runners.  It seems very unlikely for a Windows specific problem to pop up only when multiple PRs are …
=> run acceptance tests for windows on PR rather than on merge

pkg/backend/diy/state.go, pkg/backend/httpstate/state.go, pkg/cmd/pulumi/errors.go, pkg/resource/deploy/snapshot.go
Snapshot integrity errors generally happen for one of two reasons:
* We just *wrote* a snapshot with an issue.
* We just attempted to *read* a snapshot with an issue.
As much as possible, we want to capture errors and issues at the point of *writing* the snapshot, since that will generally be where the bug that caused the integrity issue lies. This commit updates snapshot integrity errors to carry awareness of whether they happened during a read or write, and modifies the panic message to nudge users to hunt down the failing write operation if the panic they are seeing relates to a read.
=> Improve snapshot integrity panics depending on operation

Makefile
Lifecycle tests (located in `pkg/engine/lifecycletest`) allow us to exercise the various engine code paths controlling the resource lifecycle -- step generation, step execution, and so on. It's often useful when working in the engine (e.g. hunting down a snapshot integrity issue) to just run the lifecycle tests. This commit adds a target to the `Makefile` to do just that.
=> Add a `test_lifecycle` target to `Makefile`

sdk/go/auto/optpreview/optpreview.go, sdk/go/auto/optup/optup.go, sdk/go/auto/stack.go, sdk/nodejs/automation/stack.ts, sdk/python/lib/pulumi/automation/_stack.py
The VSCode extension will make use of the automation API, so we'll need to be able to pass the flag through there.  While the VSCode extension will only use the TypeScript API, let's add the flag to every language in case someone finds a use for it.
Fixes https://github.com/pulumi/pulumi/issues/17174
=> add the attach-debugger flag to automation API

.github/workflows/ci.yml
For some reason that is unclear to me we currently set the fail-fast strategy to `inputs.fail-fast` for all types of tests apart from the windows tests.  This means we will also fail-fast these tests when running the PR tests (where we recently started to run the windows tests).
However on PRs it's convenient to not fail-fast, as it's useful to have the test results for all tests, *and* for flakes not having fail-fast enabled means fewer tests to re-run.  Setting this means we'll fail-fast wherever we fail fast for other tests (currently just in the merge queue I believe, where we don't run the windows tests anymore), but we'll keep running tests on PR.
=> use passed in fail-fast strategy for windows tests

changelog/pending/20240905--sdkgen-python--correctly-case-python-package-names-in-package-add-link-instructions.yaml, pkg/cmd/pulumi/package_add.go
When we print out instructions for linking a local Python SDK in response to running `package add`, we incorrectly use the Pulumi package name, which may not be a valid Python package name. This commit fixes this to use the specified Python package name override if provided, or the correctly-cased Pulumi package name if not.
Fixes #17149
=> Correctly case Python package names in `package add` link instructions

pkg/cmd/pulumi/main.go
In #17144, the text of the snapshot integrity error message was tweaked to better explain read vs. write scenarios to users. This commit "backports" the cosmetic changes from that PR to the panic error message, on which that message was originally based.
=> Sync panic error message with similar messages

sdk/nodejs/tests/runtime/closure-integration-tests.ts
@types/node regularly drops support for older typescript versions. To ensure our tests do not break when this happens, we can use release tags that point to the latest supported version of @types/node for each ts version.
Fixes https://github.com/pulumi/pulumi/issues/17135
=> Use @types/node matching the ts version for integration tests

.github/workflows/ci-run-test.yml, sdk/go/pulumi-language-go/go.mod, sdk/go/pulumi-language-go/go.sum, sdk/go/pulumi-language-go/main.go, tests/go.mod, tests/go.sum, tests/integration/integration_go_test.go
Add debugging support for the Go language.  The scaffolding for this was put in place previously in https://github.com/pulumi/pulumi/pull/17072 and then https://github.com/pulumi/pulumi/pull/17087.
To start the debugging, we're starting the program under dlv, and send the debugging information to the engine, which will emit an engine event and print information to the user to allow attaching the
debugger.   For Golang the only thing we're printing for the user is
the port number, which is enough to reconstruct the information to
attach a debugger using the DAP protocol.
E.g. for emacs the following setup is needed to be able to use this in `dap-mode`:
```
(dap-register-debug-template "Go: Attach to Delve"
(list :type "go"
:request "attach"
:name "Attach to Delve"
:mode "remote"
:host …
```
=> add debugging support to Go language host

changelog/pending/20240906--cli--recover-from-zero-byte-credentials-json-files.yaml, sdk/go/common/workspace/creds.go
Pulumi stores credentials in a `credentials.json`. If a non-atomic operation that writes this file is interrupted, we may end up with a zero-byte `credentials.json` file. Presently, this will create a situation where the user has to manually remove the file before e.g. `pulumi login` will work and retrieve new credentials again (see #11017 for an example). This commit changes this behaviour, spotting empty credentials files and returning an empty set of credentials instead of throwing an error.
Fixes #11017
=> Recover from zero-byte `credentials.json` files

docs/sphinx/conf.py
This commit enables GitHub links for our developer documentation, enabling viewers to quickly view the source code for a page, suggest an edit using the GitHub web interface, or report an issue.
=> Add GitHub links to developer documentation

sdk/go/common/promise/promise_test.go
Similar to https://github.com/pulumi/pulumi/pull/17196, this package was nearly at 100% coverage. Just needed a couple of small tests to bring it up.
=> Add tests to sdk/go/common/promise for coverage

sdk/nodejs/output.ts, sdk/python/lib/pulumi/output.py
The previous version was technically correct in that you _shouldn't_ create resources within an apply function but was incorrect that it is not allowed
=> Updated nodejs and python sdk docs on outputs

.github/workflows/ci.yml
PULUMI_BOT_TOKEN is a company wide resource that we shouldn't use in CI.  Before upgrading to GitHub enterprise it used to be that bots had a higher rate limit than tokens for CI runs, however that is no longer the case since we upgraded the GitHub subscription.
This seemingly has not been used in this workflow for a while in the first place.  Remove it to make sure it isn't accidentally used in the future, and to avoid confusion from the comment that still mentions increasing the rate limit.
=> remove PULUMI_BOT_TOKEN secret from being used by ci.yml

changelog/pending/20240731--cli-display--fix-deletes-not-being-show-in-refresh-when-using-json-output.yaml, pkg/backend/display/json.go
Introduced in https://github.com/pulumi/pulumi/pull/16146
@lukehoban
=> Fix deletes not being show in `refresh` when using json output

changelog/pending/20240901--sdkgen-go--allow-output-versioned-invokes-to-resolve-and-maintain-secrets.yaml, pkg/codegen/go/gen.go, sdk/go/pulumi/context.go, tests/testdata/codegen/assets-and-archives/go/example/getAssets.go, tests/testdata/codegen/external-resource-schema/go/example/argFunction.go, tests/testdata/codegen/functions-secrets/go/mypkg/funcWithSecrets.go, tests/testdata/codegen/go-overridden-internal-module-name/go/example/argFunction.go, tests/testdata/codegen/output-funcs-edgeorder/go/myedgeorder/listConfigurations.go, tests/testdata/codegen/output-funcs-edgeorder/go/myedgeorder/listProductFamilies.go, tests/testdata/codegen/output-funcs-tfbridge20/go/mypkg/getAmiIds.go, tests/testdata/codegen/output-funcs-tfbridge20/go/mypkg/listStorageAccountKeys.go, tests/testdata/codegen/output-funcs/go-extras/tests/codegen_test.go, tests/testdata/codegen/output-funcs/go/mypkg/funcWithAllOptionalInputs.go, tests/testdata/codegen/output-funcs/go/mypkg/funcWithDefaultValue.go, tests/testdata/codegen/output-funcs/go/mypkg/funcWithDictParam.go, tests/testdata/codegen/output-funcs/go/mypkg/funcWithListParam.go, tests/testdata/codegen/output-funcs/go/mypkg/getBastionShareableLink.go, tests/testdata/codegen/output-funcs/go/mypkg/getClientConfig.go, tests/testdata/codegen/output-funcs/go/mypkg/getIntegrationRuntimeObjectMetadatum.go, tests/testdata/codegen/output-funcs/go/mypkg/listStorageAccountKeys.go, tests/testdata/codegen/plain-object-defaults/go/example/funcWithAllOptionalInputs.go, tests/testdata/codegen/plain-object-disable-defaults/go/example/funcWithAllOptionalInputs.go, tests/testdata/codegen/provider-config-schema/go/configstation/funcWithAllOptionalInputs.go, tests/testdata/codegen/regress-8403/go/mongodbatlas/getCustomDbRoles.go, tests/testdata/codegen/simple-resource-schema-custom-pypackage-name/go/example/argFunction.go, tests/testdata/codegen/simple-resource-schema/go/example/argFunction.go, tests/testdata/codegen/simple-yaml-schema/go/example/argFunction.go, tests/testdata/codegen/urn-id-properties/go/urnid/test.go
Partially addressing #12710
This PR extends Go SDK-gen, specifically for output-versioned invokes such that they no longer rely on the plain invokes for their function body. 
We do this by implementing and using a sdk function `InvokePackageRaw` which is similar to `InvokePackage` except that it doesn't fail on secrets and actually returns a boolean indicating whether the invoke response contained any secrets. This way, the generated output-versioned invokes can immediately wrap the response as a secret if necessary and more importantly, not failing immediately if the response contained secrets. 
The sdk-gen test `output-funcs` actually do a runtime test for the newly generated function body and it passes. ~~However, I don't think it covers the _if secret then wrap as secret_ path~~ but …
=> [go] Allow output-versioned invokes to resolve and maintain secrets

changelog/pending/20240909--cli-state--show-the-full-set-of-delete-commands-necessary-to-remove-resources-from-the-source-stack-if-writing-to-it-fails.yaml, pkg/backend/diy/backend.go, pkg/cmd/pulumi/state_move.go, pkg/cmd/pulumi/state_move_test.go
Before actually writing the source stack, we have no way of knowing we can write it.  The same is true for writing the destination stack. This means if the one we write later fails to write, we get an incompletely moved state.
We've decided to move the destination stack first, and then the source stack, so resources are always tracked.  The error message also mentions cleaning up the source stack, however it's not completely obvious how to do that.  Since we know the resources that were supposed to be moved (and successfully been written to the destination stack at this point), we can give the user better instructions on how to clean up the resources.
Do that by giving them a full set of `pulumi state delete` commands they can run to clean up the source stack.
Fixes …
=> state move: show full set of delete commands when writing source stack fails

docs/architecture/deployment-execution/state.md
This fills out the developer documentation on state and state snapshots. As part of this we document the infamous class of snapshot integrity errors, including possible causes and guidelines for avoiding and debugging them.
Fixes #17206
=> Document state and snapshots

changelog/pending/20240910--engine--fix-parameterized-providers-not-downloading-correctly-when-found-from-state.yaml, pkg/engine/plugins.go, pkg/engine/update.go
Also deleted `RunInstallPlugins` because nothing was using it.
Without this fix we would report a parameterized plugin in state back as the parameterized package name, e.g. "random" instead of the base plugin "terraform-provider".
=> Fix gatherPluginsFromSnapshot incorrectly spec'ing parameterized providers

changelog/pending/20240909--cli-state--try-to-revert-changes-to-destination-stack-if-we-are-unable-to-save-the-source-stack-in-state-move.yaml, pkg/cmd/pulumi/state_move.go, pkg/cmd/pulumi/state_move_test.go
As explained in https://github.com/pulumi/pulumi/pull/17205, we need to save one stack after another when doing a state move.  The mentioned PR introduces a better error output, so the user can get themselves out of the broken situation.
However we can do a bit better.  If we fail to save the source stack for any reason, we can still try to revert the changes from the destination stack, bringing us back to the original situation, without the user having to intervene manually, which is usually preferable for users.  If we fail to do *that*, we still display the list of commands the user can use to get themselves out of the situation.
Unfortunately this makes that latter output very hard to test, since we'd have to first succeed in saving the destination stack and on the next attempt fail, …
=> state move: revert dest changes if source can't be saved

changelog/pending/20240910--cli-about--fix-language-plugins-always-having-unknown-version-in-about.yaml, cmd/pulumi-test-language/interface.go, cmd/pulumi-test-language/test_host.go, sdk/go/common/resource/plugin/host.go, sdk/go/common/resource/plugin/langruntime_plugin.go
Fixes https://github.com/pulumi/pulumi/issues/17215.
I think every language plugin should respond ok to GetPluginInfo but to be defensive I've made it a warning if the call fails and we just fall back the current behavior of not setting the version.
=> Lookup language plugin versions by querying the plugin

changelog/pending/20240910--sdk-dotnet--update-dotnet-to-3-67-0.yaml, pkg/codegen/testing/test/helpers.go, scripts/get-language-providers.sh
To be merged after https://github.com/pulumi/pulumi-dotnet/pull/342 has been merged and the release has been built.
=> upgrade pulumi-dotnet to 3.67.0

cmd/pulumi-test-language/test_host.go, pkg/cmd/pulumi/package.go, pkg/codegen/convert/plugin_mapper.go, pkg/codegen/schema/loader.go, pkg/codegen/schema/loader_test.go, pkg/resource/deploy/deploytest/pluginhost.go, pkg/resource/deploy/deploytest/pluginhost_test.go, pkg/resource/deploy/import_test.go, pkg/resource/deploy/providers/registry.go, pkg/resource/deploy/providers/registry_test.go, pkg/resource/deploy/source_query_test.go, sdk/go/common/resource/plugin/host.go, sdk/go/common/resource/plugin/mock.go, sdk/go/common/workspace/plugins.go
Plugins are the core means by which Pulumi may be extended. Language hosts, resource providers, analyzers, and converters, for instance, are all kinds of plugin. Plugins are loaded by a plugin `Host`, which also offers convenience methods for loading specific kinds of plugin such as those mentioned above.
The `Provider` method on `Host` currently accepts a name and version. This is not ideal, since there are several other parameters that may affect the plugin to be loaded, as well as what operations may be run on it when it is loaded:
* Custom download URLs and checksums may be desirable to control where a plugin is retrieved from, and to verify a plugin's integrity.
* Parameterization means that while the `aws` provider is desired, it is actually provided by a dynamically-bridging …
=> Have `Host.Provider` accept a `PackageDescriptor`

changelog/pending/20240912--sdk-nodejs--fix-closure-serialization-when-using-the-pulumi-sdk-inside-anonymous-functions.yaml, sdk/nodejs/resource.ts, sdk/nodejs/runtime/resource.ts
Several Pulumi NodeJS SDKs support passing NodeJS closures directly to resources in lieu of e.g. source files that must be managed separately on the file system. The example below, for instance, shows how a NodeJS closure can be used to declare an AWS Lambda that responds to objects being created in an S3 bucket:
```typescript
const bucket = new aws.s3.Bucket("my-bucket")
bucket.onObjectCreated("listener", () => {
console.log("An object was created in the S3 bucket!")
})
```
Under the hood, Pulumi serializes the passed closure to a piece of code and takes care of packaging that code appropriately for use as a Lambda function. This serialization is non-trivial: for packaged code to work, Pulumi must be careful to capture and serialize the transitive dependency graph of the closure passed …
=> Try and avoid serializing `runtime/resource.js`

pkg/backend/display/progress.go, pkg/backend/httpstate/backend.go, pkg/backend/httpstate/client/client.go, pkg/cmd/pulumi/up.go, sdk/go/common/apitype/deployments.go, sdk/go/common/apitype/updates.go
Link to Copilot ("why did this fail") will not be offered to users for whom Copilot is not enabled in the org of the project.
The new API is being introduced in https://github.com/pulumi/pulumi-service/pull/22202.
Fixes https://github.com/pulumi/pulumi.ai/issues/1238
=> Use AI settings from CreateUpdate to determine if Copilot is enabled

sdk/go/common/workspace/paths.go
Pointed out in https://github.com/pulumi/pulumi/pull/17239#discussion_r1756396738. We can just use `Is` here we don't need to unwrap with `As` first.
=> Just use errors.Is instead of As and Is

changelog/pending/20240912--sdk-python--add-debugpy-as-a-dependency-to-improve-the-debugging-experience.yaml, sdk/python/lib/setup.py, sdk/python/requirements.txt
To improve the E2E experience of debugging Python Pulumi programs, add `debugpy` as a dependency of the Pulumi Python SDK so that it will be available for use without the user having to install it manually.
=> [sdk/python] Add dependency on `debugpy`

pkg/cmd/pulumi/crypto.go, pkg/cmd/pulumi/util.go
Little code cleanup, I noticed this method still took the stack parameter but doesn't use it anymore.
=> needsSaveProjectStackAfterSecretManger doesn't need stack parameter

pkg/engine/lifecycletest/target_test.go
Add a test for https://github.com/pulumi/pulumi/issues/14254, which happened to have been "fixed" in https://github.com/pulumi/pulumi/pull/15716. We didn't notice this at the time, and almost regressed this fix in https://github.com/pulumi/pulumi/pull/17245.
Adding a test to ensure we don't regress this.
Fixes https://github.com/pulumi/pulumi/issues/14254.
=> Add a test for #14254

changelog/pending/20240910--cli-package--make-out-optional-within-pulumi-package-get-mapping.yaml, pkg/cmd/pulumi/package_extract_mapping.go, tests/smoke_test.go
`--out` should be optional, with the default to pipe to stdout. This mirrors how `pulumi package get-schema` works, allowing intuitive piping like:
```console
$ pulumi package get-mapping terraform aws | jq '<query>'
```
The change is non-breaking.
=> Make the `--out` argument optional for `pulumi package get-mapping`

changelog/pending/20240916--cli--add-an-attach-debugger-flag-for-pulumi-preview-and-pulumi-up-that-makes-pulumi-attach-a-debugger-to-the-running-program-and-allows-attaching-to-it.yaml, pkg/cmd/pulumi/preview.go, pkg/cmd/pulumi/up.go
Now that all the SDKs support attaching a debugger, we no longer need to hide this flag from the command line options, and can release it to everyone.
=> unhide --attach-debugger flag

changelog/pending/20240910--auto-nodejs-python--add-startdebuggingevent-to-the-automation-api.yaml, sdk/nodejs/automation/events.ts, sdk/python/lib/pulumi/automation/events.py
To allow users of the automation API use debugging events, add them as types.
I couldn't find an easy way to add tests for this, without running things under a debugger, which is tricky in tests.  If anyone has a good idea please lmk.
Fixes https://github.com/pulumi/pulumi/issues/17210
=> add debugging events to automation API

sdk/go/internal/cmd.go, sdk/go/internal/cmd_test.go, sdk/nodejs/runtime/settings.ts, sdk/python/lib/pulumi/_utils.py, sdk/python/lib/pulumi/runtime/settings.py
Couple of things pointed out by @lunaris while reviewing https://github.com/pulumi/pulumi/pull/17153.
First use `get` instead of `if` for looking up in python dictionaries: https://github.com/pulumi/pulumi/pull/17153#discussion_r1758413156
Second to use `Promise.all` to collect all feature supports at once: https://github.com/pulumi/pulumi/pull/17153#discussion_r1752320486
=> Couple of monitor support code cleanups from review

cmd/pulumi-test-language/go.mod, cmd/pulumi-test-language/go.sum, pkg/go.mod, pkg/go.sum, sdk/go/pulumi-language-go/go.mod, sdk/go/pulumi-language-go/go.sum, sdk/nodejs/cmd/pulumi-language-nodejs/go.mod, sdk/nodejs/cmd/pulumi-language-nodejs/go.sum, sdk/python/cmd/pulumi-language-python/go.mod, sdk/python/cmd/pulumi-language-python/go.sum, tests/go.mod, tests/go.sum, tests/integration/construct_component_configure_provider/testcomponent-go/go.mod, tests/integration/construct_component_configure_provider/testcomponent-go/go.sum
It's currently set to a specific commit with all the functionality of v0.10.0 before that version of ESC was tagged. This change updates it to the released version.
From https://github.com/pulumi/esc/compare/v0.9.1...v0.10.0
=> Update ESC dependency to v0.10.0

changelog/pending/20240917--engine--generated-and-matched-aliases-are-written-to-debug-logs.yaml, pkg/resource/deploy/step_generator.go
Part of fixing https://github.com/pulumi/pulumi/issues/17279. This logs the generated aliases, the matched alias, and the old URN it matched to in the V(7) debug logs.
=> Log alias generation to V(7)

changelog/pending/20240913--cli-display--show-the-count-of-unchanged-resources.yaml, pkg/backend/display/progress.go, pkg/backend/display/progress_test.go, pkg/backend/display/testdata/not-truncated/failed-stacks-dont-rewrite-operations.json.interactive-no-show-sames.stdout.txt, pkg/backend/display/testdata/not-truncated/stack-output-resource-diff.json.interactive-no-show-sames.stdout.txt, pkg/backend/display/testdata/not-truncated/template-body.json.interactive-no-show-sames.stdout.txt, pkg/backend/display/testdata/not-truncated/up-2.json.interactive-no-show-sames.stdout.txt, pkg/backend/display/testdata/not-truncated/up-3.json.interactive-no-show-sames.stdout.txt, pkg/backend/display/testdata/not-truncated/up-4.json.interactive-no-show-sames.stdout.txt, pkg/backend/display/testdata/not-truncated/up-5.json.interactive-no-show-sames.stdout.txt, pkg/backend/display/testdata/not-truncated/up.json.interactive-no-show-sames.stdout.txt, pkg/backend/display/testdata/not-truncated/url-encoded-stack-output-diff.json.interactive-no-show-sames.stdout.txt, pkg/backend/display/testdata/not-truncated/webserver-userdata.json.interactive-no-show-sames.stdout.txt, pkg/backend/display/tree.go, sdk/go/common/diag/colors/colors.go
The Pulumi CLI does not show details of unchanged resources by default, since generally it is expected that users only care about what *will* change when they run their Pulumi program. If the number of unchanged resources is large, or if no resources have changed, the CLI may spend long periods of time displaying nothing, or appearing to have hung. The `--show-sames` argument instructs the CLI to show unchanged resources, but if the number is large, then this can result in an overly noisy display, which is not desirable either.
This commit adapts the work of #15975 to display a count of unchanged resources when `--show-sames` is not enabled. In doing so we can indicate to the user that progress is being made without introducing noise or clutter. When the operation is complete, the count …
=> Show the count of unchanged resources

changelog/pending/20240909--auto-nodejs-python--support-refresh-consistently-in-up-preview-destroy.yaml, sdk/nodejs/automation/stack.ts, sdk/nodejs/tests/automation/localWorkspace.spec.ts, sdk/python/lib/pulumi/automation/_stack.py, sdk/python/lib/test/automation/test_local_workspace.py
Currently refresh support is inconsistent in automation API.  Go supports it for up, preview and destroy, NodeJS only supports it for up and preview, and Python doesn't support it at all.  Support it for all three in up, preview and destroy.
The important bit is supporting it for NodeJS (see https://github.com/pulumi/actions/pull/1278#pullrequestreview-2290185113), but it's best to support it consistently when we can.
=> auto: support refresh consistently in up/preview/destroy

changelog/pending/20240909--auto-nodejs--support-an-abort-channel-for-gracefully-canceling-operations.yaml, sdk/nodejs/automation/cmd.ts, sdk/nodejs/automation/stack.ts, sdk/nodejs/tests/automation/localWorkspace.spec.ts
This PR adds support to the auto api for a cancelation signal to be sent by the caller, causing graceful shutdown of the Pulumi deployment operation (`preview`, `up`, `refresh`, `destroy`).
Uses the standard `AbortSignal` API.
Related: #13160
=> [nodejs] cancelation support for auto api

pkg/cmd/pulumi/convert.go, pkg/cmd/pulumi/convert_test.go, pkg/cmd/pulumi/import.go, pkg/go.mod, pkg/go.sum, tests/go.sum
Bringing yaml inline with other languages, and removing a couple more dependencies from the yaml<->pulumi cyclic build.
We still depend on the yaml package for docsgen.
=> Use RPC methods for yaml codegen

changelog/pending/20240917--cli-state--support-falling-back-to-snapshot-secret-managers-when-pulumi_fallback_to_state_secrets_manager-is-set.yaml, pkg/cmd/pulumi/config.go, pkg/cmd/pulumi/config_env.go, pkg/cmd/pulumi/config_env_init.go, pkg/cmd/pulumi/config_test.go, pkg/cmd/pulumi/crypto.go, pkg/cmd/pulumi/crypto_test.go, pkg/cmd/pulumi/destroy.go, pkg/cmd/pulumi/import.go, pkg/cmd/pulumi/logs.go, pkg/cmd/pulumi/new.go, pkg/cmd/pulumi/preview.go, pkg/cmd/pulumi/refresh.go, pkg/cmd/pulumi/stack_change_secrets_provider.go, pkg/cmd/pulumi/stack_history.go, pkg/cmd/pulumi/stack_init.go, pkg/cmd/pulumi/up.go, pkg/cmd/pulumi/watch.go, sdk/go/common/env/env.go, tests/smoke_test.go
Secrets providers are the means by which Pulumi manages the encryption and decryption of secrets. Since secrets may be present in both the state (e.g. sensitive resource outputs) and a stack's configuration (API keys, etc.), so can secrets providers be persisted/specified in both these places.
Currently, if a stack configuration does not exist, or does not specify a secrets provider, a default will be instantiated. This is true even when there is a state snapshot that *does* specify a provider. Consider as an example the following sequence of events:
* A new Pulumi stack, `dev`, is created with a cloud backend and a passphrase secrets provider. The fact that a passphrase provider is in use is persisted to `Pulumi.dev.yaml`.
* `pulumi up -s dev` is run in the new stack. The passphrase …
=> Support falling back to snapshot secret managers

sdk/go/pulumi-internal/netutil/netutil.go, sdk/go/pulumi-internal/netutil/netutil_test.go, sdk/go/pulumi-language-go/main.go, sdk/python/cmd/pulumi-language-python/main.go
In languages where we need to attach the debugger to a port, we have some choice which port we can give the user.  For using the debugging feature on the command line, it is convenient to have the port always be the same.  Let's try to do that, but go to higher ports if the port we chose is already in use for some reason.
The ports chosen here are "randomly" chosen high ports that are unlikely to be used already.
Thanks @mikhailshilkov for the suggestion of this.
=> try to choose a consistent port for debugging

sdk/python/lib/pulumi/runtime/settings.py, tests/integration/integration_python_test.go
Trying to split up https://github.com/pulumi/pulumi/pull/17283 as something in it keeps failing CI.
This fixes the `_sync_monitor_supports_parameterization` method (which is currently not being used due to codegen bugs) to refer to the correct flag.
Also update the test that we need to keep skipping till a later version with the codegen fixes is released.
=> Fix _sync_monitor_supports_parameterization

pkg/backend/httpstate/backend.go, pkg/cmd/pulumi/up.go, sdk/go/common/env/env.go
- `PULUMI_SHOW_COPILOT_LINK` env var is no longer recognized. Instead, off-by-default `PULUMI_SUPPRESS_COPILOT_LINK` can be used to suppress the link generation
- Since we changed the logic a few times, I added more level 7 logging to ease troubleshooting. The log will look like this:
```
Copilot in org 'pulumi' is enabled for user 'artur-pulumi-corp' but the environment variable PULUMI_SUPPRESS_COPILOT_LINK suppresses the link to Copilot in diagnostics
```
=> Enable Copilot link by default

pkg/codegen/python/gen.go, tests/integration/integration_python_test.go, tests/integration/python/parameterized/sdk/python/setup.py
We haven't shipped 3.134.0 yet, so this can be 3.134.0 rather than 3.134.1.
=> Fix Python min parameterization version

.github/workflows/ci.yml
Currently we make running the tests depend on linting the program. This occasionally saves some GitHub actions runner time, when the lint step detects that the build is failing.  However in many cases it's quite inconvenient, especially if the lint error is really just a lint error (e.g. because of a long line or something).
In that case the submitter of the PR has to fix the lint first, and then push those changes, and wait for CI all over again, which can add a considerable amount of time (especially since CI is kinda slow, so at least I usually end up doing something else and checking back later).
In addition it adds to the time it takes to run all tests in total, as the tests can't be run in parallel with linting (and linting takes more than a minute).
Allow the tests to run in …
=> allow tests to run in parallel with linting

pkg/codegen/schema/loader.go
This was checking disableFileCache to disable the memory cache, rather than disableEntryCache.
This is only used in tests, so probably no real impact.
=> Fix check for disableEntryCache in newPluginLoaderWithOptions

changelog/pending/20240919--sdkgen-nodejs--bump-valid-nodejs-version-to-v3-133-the-one-that-contains-invokeoutput-and-friends.yaml, pkg/codegen/nodejs/gen.go, tests/testdata/codegen/assets-and-archives/nodejs/package.json, tests/testdata/codegen/config-variables/nodejs/package.json, tests/testdata/codegen/embedded-crd-types/nodejs/package.json, tests/testdata/codegen/external-node-compatibility/nodejs/package.json, tests/testdata/codegen/external-resource-schema/nodejs/package.json, tests/testdata/codegen/functions-secrets/nodejs/package.json, tests/testdata/codegen/legacy-names/nodejs/package.json, tests/testdata/codegen/methods-return-plain-resource/nodejs/package.json, tests/testdata/codegen/output-funcs-edgeorder/nodejs/package.json, tests/testdata/codegen/output-funcs-tfbridge20/nodejs/package.json, tests/testdata/codegen/output-funcs/nodejs/package.json, tests/testdata/codegen/regress-node-8110/nodejs/package.json, tests/testdata/codegen/secrets/nodejs/package.json, tests/testdata/codegen/simple-methods-schema-single-value-returns/nodejs/package.json, tests/testdata/codegen/simple-resource-schema/nodejs/package.json, tests/testdata/codegen/unions-inline/nodejs/package.json, tests/testdata/codegen/unions-inside-arrays/nodejs/package.json, tests/testdata/codegen/urn-id-properties/nodejs/package.json, tests/testdata/codegen/using-shared-types-in-config/nodejs/package.json
Version v3.133.0 includes #17237 which adds new SDK functions `invokeOutput` and `invokeSingleOutput`, this PR changes sdk-gen such that the required `@pulumi/pulumi` dependency is that one that contains the former primitives.
=> [sdk-gen/nodejs] Bump valid nodejs version to v3.133 the one that contains invokeOutput and friends

changelog/pending/20240920--cli-config--fix-help-text-for-config-set-command.yaml, pkg/cmd/pulumi/config.go
For the nested config we currently have an extra `.`, which makes the command fail.  Removing the dot will make the command work as documented.
Fixes https://github.com/pulumi/pulumi/issues/17313
=> fix help text for pulumi config set

changelog/pending/20240920--sdkgen-python--fix-python-defaulting-to-generating-typed-dicts-for-input-types.yaml, pkg/codegen/python/gen_program.go, tests/testdata/codegen/assets-and-archives/docs/resourcewithassets/_index.md, tests/testdata/codegen/basic-unions-pp/python/basic-unions.py, tests/testdata/codegen/legacy-names/docs/example_resource/_index.md, tests/testdata/codegen/overlay-supported-languages/docs/overlayresource/_index.md, tests/testdata/codegen/overlay-supported-languages/docs/overlayresourceconstrainedlanguages/_index.md, tests/testdata/codegen/overlay-supported-languages/docs/resource/_index.md, tests/testdata/codegen/unions-inline/docs/exampleserver/_index.md, tests/testdata/codegen/unions-inside-arrays/docs/exampleserver/_index.md, tests/testdata/codegen/using-shared-types-in-config/docs/user/_index.md
https://github.com/pulumi/pulumi/pull/16704 correctly defaulted typed dicts to false for external schemas in sdk-gen but incorrectly turned them on for external schemas in program-gen iff the schema had any other python language options.
This fixes the latter to assume that typed dicts can be used in program-gen. This should be fine because even the old class style could be passed dict arguments as well, but we'll use the class style if the schema explicitly says to use it.
=> Fix python typed dicts to be enabled by default

pkg/cmd/pulumi/preview.go
Added the word "to" in order to fix a typo and ensure both long and short description formats are consistent.
=> Fix Typo in preview.go Description

changelog/pending/20240922--engine--fix-token-expired-errors-due-to-network-issues.yaml, pkg/backend/httpstate/state.go, pkg/backend/httpstate/token_source.go, pkg/backend/httpstate/token_source_test.go
Currently the token source loop will stop if `refreshToken` ever returns an error, regardless of what that error is. While the API call to the service does have some retry logic at it's level it can still potentially return an error just due to transient network/server conditions. In that case the refreh loop will just stop working and the token will eventually expire.
This changes the token source to keep going until it gets a specific `expiredTokenError` error. This should make it more resilient to network issues.
Towards fixing https://github.com/pulumi/pulumi/issues/7094.
=> Keep the token source loop going in the face of errors

pkg/cmd/pulumi/state_move.go, pkg/cmd/pulumi/state_rename.go, pkg/resource/deploy/deployment_executor.go, pkg/resource/deploy/snapshot.go, pkg/resource/deploy/step_generator.go, pkg/resource/graph/dependency_graph.go, sdk/go/common/resource/resource_state.go, sdk/go/common/resource/resource_state_test.go
Resources can depend on others in a number of ways -- provider references, parent-child relationships, dependencies and property dependencies, and deleted-with relationships. With all these linkages to keep track of, it's easy for one to be missed and bugs to be introduced, and indeed this has happened on numerous occasions. This commit attempts to make it harder to introduce bugs where dependencies are missed by adding a new `GetAllDependencies` method to `resource.State`. The idea is not that this will make all traversals of dependencies shorter and neater (though in many cases it does), but that it will force iterations over a resource's dependency set to account for all possible relations appropriately, and discard any that are not important explicitly.
> [!NOTE]
> In some cases the …
=> Centralize resource state dependency traversal

sdk/go/common/apitype/stacks.go
When creating a stack, there are cases where it would be valuable to be able to initialise the stack with a known state snapshot (such as one containing a non-default secrets manager, as discussed in #16890, for instance). This commit begins adding support by this by extending the API types for stack creation to take an `UntypedDeployment`. When this is released, changes to relevant backends (DIY and Pulumi Cloud) can be implemented to support the new field, at which point the CLI can then be modified to take advantage of it.
=> Allow passing an initial state at stack creation

tests/integration/integration_python_acceptance_test.go
Poetry uses a cache for packages to speed up installation of the venv. It seems like the primitives it uses for that are causing issues when running multiple instances of poetry in parallel that are installing the same packages.  This seems to happen only on Windows.  Make these tests run sequentially on Windows to avoid this test flakyness.
There's an upstream issue for poetry that describes this as well (https://github.com/python-poetry/poetry/issues/7370)
https://github.com/pulumi/pulumi/issues/17183
=> don't run tests using poetry in parallel on windows

changelog/pending/20240923--engine--retry-token-refresh-errors-immediately.yaml, pkg/backend/httpstate/token_source.go
If we hit an error trying to refresh the token source (and it's not an expired token error) then retry right away. This stops two error cases.
Firstly in GetToken where we may return the state token, and secondly on the timer where the duration between now and the next refresh tick might push us over the time limit before the token expires.
=> Retry token errors immediately

changelog/pending/20240924--sdk-python--always-unwrap-value-from-invokeresult-in-invoke_async.yaml, sdk/python/lib/pulumi/runtime/invoke.py, sdk/python/lib/test/langhost/invoke/__main__.py
In #17275 I changed `invoke_async` to return `InvokeResult`, however this variant of the invoke should always unwrap `value` from the `InvokeResult`. 
Reverted a changed test in #17275 thinking it was syntactic, however it was not since it unwrapped the value in the test whereas the unwrapping should have happened in the function implementation of `invoke_async`
```diff
async def await_invoke_async():
value = await invoke_async(
"test:index:MyFunction", props={"value": 41, "value2": get_value2()}
)
return value["value"]
```
Fixes #17347
=> [sdk/python] Always unwrap value from InvokeResult in invoke_async

proto/.checksum.txt, proto/pulumi/provider.proto, sdk/nodejs/proto/provider_grpc_pb.js, sdk/proto/go/provider_grpc.pb.go, sdk/python/lib/pulumi/runtime/proto/provider_pb2_grpc.py, sdk/python/lib/pulumi/runtime/proto/provider_pb2_grpc.pyi
Following up on https://github.com/pulumi/pulumi-gcp/issues/2405, this PR adds a comment to Configure explaining that ConfigureRequest.args may contain secrets.
=> Document secrets configure behavior

changelog/pending/20240924--sdk-nodejs--short-circuit-output-invokes-if-inputs-contains-unknowns.yaml, sdk/nodejs/output.ts, sdk/nodejs/runtime/invoke.ts, sdk/nodejs/runtime/rpc.ts, tests/testdata/codegen/output-funcs/nodejs-extras/tests/codegen.spec.ts
#17237 introduced output invokes that don't rely on plain invokes, however since they now no longer await inputs in the generated provider sdks and instead await them in the core sdk, we should short-circuit the output invoke if it contained any unknown values so that the behaviour matches what was happening before the change. 
Fixes #17363
=> [sdk/nodejs] Short-circuit output invokes if inputs contains unknowns

pkg/backend/httpstate/state.go, pkg/backend/httpstate/token_source.go, pkg/backend/httpstate/token_source_test.go
This reverts commit f3a8271fd02364d9a7af8b406245d041e26f5688 and 89bb75fe2c066e697e3412ae26da1c3670a36e4d.
These seem to have causes a massive increase in 403 traffic against the service. Reverting until we investigate and fix.
=> Revert #17338 and #17127

cmd/pulumi-test-language/interface.go, pkg/backend/backend.go, pkg/backend/diy/backend.go, pkg/backend/diy/backend_legacy_test.go, pkg/backend/diy/backend_test.go, pkg/backend/httpstate/backend.go, pkg/backend/httpstate/backend_test.go, pkg/backend/httpstate/client/client.go, pkg/backend/mock.go, pkg/cmd/pulumi/stack_init_test.go, pkg/cmd/pulumi/state_move_test.go, pkg/cmd/pulumi/util.go
There are a number of cases where it would be useful to be able to seed a newly-created stack with an initial state. #17037 and its underlying issue, for instance, could be resolved by persisting a non-default secrets manager as part of stack initialisation rather than as a separate subsequent operation. This commit starts the journey to enabling this, adding an `initialState` parameter to the `Backend.CreateStack` interface method.
=> Let `Backend.CreateStack` accept an initial state

cmd/pulumi-test-language/interface.go, pkg/backend/backend.go, pkg/backend/diy/backend.go, pkg/backend/diy/backend_legacy_test.go, pkg/backend/diy/backend_test.go, pkg/backend/httpstate/backend.go, pkg/backend/httpstate/backend_test.go, pkg/backend/httpstate/client/client.go, pkg/backend/mock.go, pkg/backend/stack.go, pkg/cmd/pulumi/stack_init_test.go, pkg/cmd/pulumi/state_move_test.go, pkg/cmd/pulumi/util.go
There are a number of cases where it would be useful to be able to seed a newly-created stack with an initial state. #17037 and its underlying issue, for instance, could be resolved by persisting a non-default secrets manager as part of stack initialisation rather than as a separate subsequent operation. In such cases, we want to be able to create a secrets manager for a stack before it has been created. Presently, the `Stack` interface offers `DefaultSecretManager` for asking what the default secret manager for a *stack* should be, but there is no way to ask a `Backend` what the default manager for *stacks associated with that backend* should be. This commit adds a `DefaultSecretManager` method to the `Backend` interface, along with appropriate implementations for DIY and HTTP backends.
=> Allow `Backend`s to define `DefaultSecretManager`s

pkg/cmd/pulumi/stack_change_secrets_provider.go, pkg/cmd/pulumi/state_move.go, pkg/cmd/pulumi/util.go
This commit is in preparation for creating secrets managers as part of state initialisation.
=> Rename `createSecretsManager` to `createSecretsManagerForExistingStack`

pkg/backend/diy/backend.go, pkg/backend/diy/backend_test.go, pkg/backend/diy/snapshot.go, pkg/backend/diy/state.go, pkg/cmd/pulumi/stack_change_secrets_provider.go, pkg/cmd/pulumi/state_move.go, pkg/cmd/pulumi/util.go
There are a number of cases where it would be useful to be able to seed a newly-created stack with an initial state. #17037 and its underlying issue, for instance, could be resolved by persisting a non-default secrets manager as part of stack initialisation rather than as a separate subsequent operation. Now that `Backend.CreateStack` accepts an initial state, we can modify implementations to actually persist the new parameter. This commit does so for the DIY backend.
=> Persist initial states in DIY backend

changelog/pending/20240926--sdk-nodejs--fix-dependency-installation-for-nodejs-projects-with-a-main-property.yaml, sdk/nodejs/npm/manager.go, tests/integration/integration_nodejs_test.go, tests/integration/nodejs/pulumi-main/Pulumi.yaml, tests/integration/nodejs/pulumi-main/package.json, tests/integration/nodejs/pulumi-main/src/index.ts
After running the package manager installation, we check that a `node_modules` directory exists. This check was done relative to the "Program Directory", however the `node_modules` directory is created next to `package.json`, which itself is often in the "Project Directory". When `Pulumi.yaml` specifies a `main` property, these two directories are different, and the check fails.
We probably did not run into this earlier, because for nodejs you often don't use Pulumi's `main`, but instead use the nodejs `main` in `package.json`.
Fixes https://github.com/pulumi/pulumi/issues/17292
=> Fix dependency installation for nodejs projects with a main property

changelog/pending/20240924--engine--disable-the-enviromental-github_token-on-401-responses.yaml, sdk/go/common/workspace/plugins.go, sdk/go/common/workspace/plugins_test.go
Part one of fixing https://github.com/pulumi/pulumi/issues/17217. This disables and retries the plugin http request without GITUHB_TOKEN if we get a 401 error.
This should help with cases where people have tokens that don't have access to public resources. We'll see the 401 and retry without the token set.
This doesn't fix the other part of #17217 to retry 403 error without the token.
=> Invalidate GITHUB_TOKEN on 401

pkg/backend/httpstate/state.go, pkg/backend/httpstate/token_source.go, pkg/backend/httpstate/token_source_test.go, pkg/go.mod, pkg/go.sum, tests/go.sum
This reenables the token source tests as they should now be deterministic, no longer relying on `time.Sleep`.
=> Add clockwork for deterministic time testing

proto/.checksum.txt, proto/pulumi/language.proto, sdk/proto/go/language.pb.go, sdk/python/lib/pulumi/runtime/proto/language_pb2.pyi
For the fields that have alternatives, we can document them to save everyone that stumbles upon these some time.  Do that here.
=> language.proto: document deprecated fields better

changelog/pending/20240928--sdkgen--validate-schema-version-is-provided-when-package-supports-packing.yaml, pkg/codegen/schema/bind.go, pkg/codegen/schema/schema_test.go
When a schema has `SupportsPack` enabled, then it must embed a version. This test adds a validation that returns an error diagnostic when that requirement is not met. 
Follow up for (but not depending upon) #17409
=> [schema] Validate version is provided when package supports packing

changelog/pending/20240928--sdkgen-go--fix-nested-string-map-map-map-properties.yaml, sdk/go/pulumi/generate/main.go, sdk/go/pulumi/types_builtins.go, sdk/go/pulumi/types_builtins_test.go, tests/testdata/codegen/go-nested-collections/go/repro/foo.go, tests/testdata/codegen/go-nested-collections/schema.json
This is to unblock https://github.com/pulumi/pulumi/issues/17415. We add `StringMapMapMap` to the Go SDK and a test to check that sdk-gen can use that type.
Really this ought to be a conformance test, but to unblock this quickly just added a sanity check in the old codegen tests.
=> Add StringMapMapMap to Go SDK

changelog/pending/20240927--cli-config--improve-usage-string-for-config-env-add-rm-commands.yaml, pkg/cmd/pulumi/config_env_add.go, pkg/cmd/pulumi/config_env_rm.go
Make it clear which arguments are required for these commands, and that add takes multiple environments as argument.
Output before:
```
$ pulumi config env add
Adds environments to the end of a stack's import list. Imported environments are merged in order
per the ESC merge rules. The list of stacks behaves as if it were the import list in an anonymous
environment.
Usage:
pulumi config env add [flags]
[...]
error: requires at least 1 arg(s), only received 0
```
Output after:
```
$ pulumi config env add
Adds environments to the end of a stack's import list. Imported environments are merged in order
per the ESC merge rules. The list of stacks behaves as if it were the import list in an anonymous
environment.
Usage:
pulumi config env add <environment-name>... [flags]
[...]
error: requires at …
```
=> improve the usage string for the config env add/rm commands

pkg/backend/diy/backend.go, pkg/backend/diy/backend_test.go, pkg/backend/diy/snapshot.go, pkg/backend/diy/state.go, pkg/backend/httpstate/backend.go, pkg/cmd/pulumi/stack_change_secrets_provider.go, pkg/cmd/pulumi/state_move.go, pkg/cmd/pulumi/util.go
There are a number of cases where it would be useful to be able to seed a newly-created stack with an initial state. #17037 and its underlying issue, for instance, could be resolved by persisting a non-default secrets manager as part of stack initialisation rather than as a separate subsequent operation. Now that `Backend.CreateStack` accepts an initial state, we can modify implementations to actually persist the new parameter. This commit does so for the HTTP backend.
=> Persist initial states in HTTP backend

pkg/backend/diy/backend_legacy_test.go, pkg/backend/diy/backend_test.go, pkg/backend/snapshot.go, pkg/backend/snapshot_test.go, pkg/cmd/pulumi/state_delete_test.go, pkg/cmd/pulumi/state_move_test.go, pkg/engine/journal.go, pkg/resource/deploy/deployment_test.go, pkg/resource/deploy/snapshot.go, pkg/resource/edit/operations_test.go, pkg/resource/stack/deployment.go, sdk/go/common/apitype/core.go
This commit introduces a `Metadata` field to state snapshots. The initial use case for this field will be tracking snapshot integrity errors, so that better messages can be produced for users and better diagnostic information preserved for contributors. When this commit is merged, support for persisting the field will be added to backends appropriately, before use cases such as the above can be implemented.
=> Introduce snapshot metadata

pkg/graph/toposort.go, pkg/resource/deploy/snapshot.go, pkg/resource/deploy/snapshot_test.go
An important precondition of Pulumi state snapshots is that they are *topologically sorted* with respect to dependencies. That is, each resource in a state snapshot *must* appear *after* those that it depends on (where "depends" here means any kind of dependency relationship -- `Provider`, `Parent`, `DeletedWith`, and so on). The `Snapshot.VerifyIntegrity` method checks this property (among others) and, upon failure, yields a snapshot integrity error.
It turns out that we don't currently have the ability to explicitly sort or re-sort a state snapshot. There are a couple of reasons for this:
* Snapshots are typically built in response to resource registrations from a program, and we require that these registrations are sent in topological order. Indeed, for imperative languages, such as …
=> Support topologically sorting snapshots

changelog/pending/20241001--cli-new--check-zipped-templates-for-pulumi-yaml-files.yaml, sdk/go/common/workspace/templates_zip.go, sdk/go/common/workspace/templates_zip_test.go
This commit strengthens the validation of project templates supplied as `.zip` archives, checking them for a `Pulumi.yaml` before copying the contents.
Closes #14824
=> Check zipped templates for `Pulumi.yaml` files

changelog/pending/20241001--engine--fix-a-panic-when-multiple-component-provider-construct-calls-fail.yaml, pkg/resource/deploy/source_eval.go, pkg/resource/deploy/source_eval_test.go
When we're getting an error, we want to abort the source iterator by closing the abort channel.  However, multiple RegisterResource requests can already be in progress at that time, since they are bbeing run in parallel.  When two of those result in an error, we try to close the channel twice, which in turn results in a panic because Go doesn't allow that.
Instead what we should do here is send a value to the abort channel, which will then poison the iterator, similar to how closing the channel would poison it.
Fixes https://github.com/pulumi/pulumi/issues/17438
=> send a value to the abortchan instead of closing it

pkg/resource/deploy/snapshot.go, pkg/resource/deploy/snapshot_test.go
An important precondition of Pulumi state snapshots is that there are no *dangling references* -- that is, references to resources which do not exist in the snapshot. Snapshots which have such references will yield snapshot integrity errors when `Snapshot.VerifyIntegrity` is called. This commit introduces the `Snapshot.Prune` method, which walks a snapshot and removes dangling references. The snapshot is assumed to be toplogically sorted and URN changes due to dangling parent references are propagated appropriately. In combination with the recently added `Topsort` method, this should set us in good stead for introducing a `state repair` command to automatically clean up many kinds of invalid snapshots.
=> Support pruning snapshots

changelog/pending/20241002--sdk-yaml--fix-pulumi-config-set-behaviour-to-append-to-end-of-file.yaml, sdk/go/common/util/yamlutil/edit.go, sdk/go/common/util/yamlutil/edit_test.go, sdk/go/common/workspace/project_test.go, tests/config_test.go, tests/roundtrip_test.go
This fix does not append new nodes when encountered but instead adds them to the end after all nodes are processed.
I also took to opportunity to rename new to newNode to not shadow the keyword.  Suprising that go even allows this.
Fixes: #14860
=> Preserve ordering when editing stack config.

changelog/pending/20241003--cli-new--respect-existing-stack-configuration-when-initialising-secret-managers.yaml, pkg/backend/backend.go, pkg/backend/diy/backend.go, pkg/backend/httpstate/backend.go, pkg/backend/mock.go, pkg/cmd/pulumi/config.go, pkg/cmd/pulumi/stack_init_test.go, pkg/cmd/pulumi/util.go, pkg/cmd/pulumi/util_test.go, tests/smoke_test.go
In #17387 we modified `stack init` to persist an initial secrets manager as part of stack creation (in contrast to only persisting it on subsequent updates as needed). As part of this change, we made it possible to create secrets managers without an existing stack. In doing so, we assumed that the absence of a stack also implied the absence of stack configuration. Consequently, we introduced a bug -- if a user had supplied a stack configuration (e.g. `Pulumi.<stack>.yaml`) *prior* to creating a stack (`dev` in this case) in the backend, we would ignore that configuration and potentially clobber it with a fresh (and likely useless) secrets provider. This was flagged in #17457.
In this commit, we refine the new pre-creation secrets manager initialisation code so that it will attempt to load …
=> Respect existing stack configuration when initialising secret managers

.github/workflows/pr-test-acceptance-on-dispatch.yml
In https://github.com/pulumi/pulumi/pull/17193 I removed PULUMI_BOT_TOKEN from being used in ci.yml completely.  Unfortunately this broke the dispatching of the acceptance tests in community PRs, as they still pass the PULUMI_BOT_TOKEN through, but GitHub actions is unhappy with the extra secret being passed.
Stop passing this secret through to fix running those tests.
=> community-pr tests: don't pass PULUMI_BOT_TOKEN to ci.yml

.github/workflows/ci-run-test.yml
Some jobs on Ubuntu are failing during merge because they're running out of disk space. Use the `jlumbroso/free-disk-space` to free up some space.
https://github.com/pulumi/pulumi/actions/runs/11168927953/job/31048549192
=> ci: Free disk space on Ubuntu

changelog/pending/20241001--cli-state--introduce-the-state-repair-command.yaml, pkg/cmd/pulumi/state.go, pkg/cmd/pulumi/state_repair.go, pkg/cmd/pulumi/state_repair_render.go, pkg/cmd/pulumi/state_repair_test.go, pkg/cmd/pulumi/util.go
Before performing any operation, Pulumi will by default check that the state it is operating on is well-formed -- that all resources referenced in the state (e.g. as dependencies) actually exist in that state, and that resources are correctly ordered so that states that depend on others appear after those that they require. If these well-formedness checks fail, Pulumi will refuse to continue and report a "snapshot integrity error".
Such errors are both frustrating and scary. Frustrating because it's Pulumi's fault and now something has to be done before we can proceed. Scary because the only options for proceeding are:
* Run another operation with `--disable-integrity-checking`, hoping that the broken state a. won't affect the operation being run negatively and b. that when the operation …
=> Introduce the `state repair` command

pkg/resource/deploy/snapshot_test.go
The property map in the results list is not necessarily ordered. Instead of making sure that we have an equal object for the prune, let's just check if the elements match, since that's what we care about.  This fixes some flakyness because of map ordering.
Note that we don't need to do the same for snap.Resources, and it's better that way, because we care about the ordering of the resources in the snapshot.
Fixes https://github.com/pulumi/pulumi/issues/17476
cc @lunaris
=> snapshot prune: check that the elements match instead of equals

changelog/pending/20241004--sdk-nodejs--maintain-secretness-and-input-dependencies-of-output-invokes.yaml, sdk/nodejs/cmd/pulumi-language-nodejs/language_test.go, sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsc/projects/l2-invoke-dependencies/.gitignore, sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsc/projects/l2-invoke-dependencies/Pulumi.yaml, sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsc/projects/l2-invoke-dependencies/index.ts, sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsc/projects/l2-invoke-dependencies/package.json, sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsc/projects/l2-invoke-dependencies/tsconfig.json, sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsc/projects/l2-invoke-secrets/.gitignore, sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsc/projects/l2-invoke-secrets/Pulumi.yaml, sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsc/projects/l2-invoke-secrets/index.ts, sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsc/projects/l2-invoke-secrets/package.json, sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsc/projects/l2-invoke-secrets/tsconfig.json, sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsnode/projects/l2-invoke-dependencies/.gitignore, sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsnode/projects/l2-invoke-dependencies/Pulumi.yaml, sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsnode/projects/l2-invoke-dependencies/index.ts, sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsnode/projects/l2-invoke-dependencies/package.json, sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsnode/projects/l2-invoke-dependencies/tsconfig.json, sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsnode/projects/l2-invoke-secrets/.gitignore, sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsnode/projects/l2-invoke-secrets/Pulumi.yaml, sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsnode/projects/l2-invoke-secrets/index.ts, sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsnode/projects/l2-invoke-secrets/package.json, sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsnode/projects/l2-invoke-secrets/tsconfig.json, sdk/nodejs/runtime/invoke.ts, sdk/nodejs/runtime/rpc.ts, sdk/nodejs/tests/runtime/rpc.spec.ts, sdk/nodejs/tsconfig.json
Addresses the nodejs part of #17474, it does the following
- Keeping track of secretness of inputs
- Unwraps the inputs such that they are sent as plain values to the engine
- Marks the invoke result as secret if any of the inputs is a secret
- Marks the dependencies of the output invoke response being the list of all dependencies of the inputs
- Enables conformance tests `l2-invoke-secrets` and `l2-invoke-dependencies`
- Adds unit tests for newly added function `unwrapSecretValues`
=> [sdk/nodejs] Maintain secretness and input dependencies of output invokes

changelog/pending/20241005--sdk-python--update-python-grpcio-to-1-66-2.yaml, sdk/python/lib/setup.py, sdk/python/requirements.txt
To support the upcoming Python 3.13 release, we need to upgrade grpcio to 1.66.2 https://github.com/grpc/grpc/releases/tag/v1.66.2
Update pulumi-policy after this is released https://github.com/pulumi/pulumi-policy/pull/361
Ref https://github.com/pulumi/pulumi/issues/17484
=> Update python grpcio to 1.66.2 to support Python 3.13

changelog/pending/20241006--sdk-nodejs--exclude-tests-from-the-nodejs-npm-package.yaml, sdk/nodejs/.npmignore, sdk/nodejs/Makefile
Add an .npmignore file to exclude tests from the npm package.
Fixes https://github.com/pulumi/pulumi/issues/17471
=> Exclude tests from the nodejs npm package

changelog/pending/20241007--sdk-python--target-python-3-8-for-linting-sdk.yaml, scripts/get-job-matrix.py, sdk/python/.pylintrc, sdk/python/lib/pulumi/output.py, sdk/python/lib/pulumi/runtime/resource.py, sdk/python/mypy.ini
We still support Python 3.8 (EOL 2024-10-31). Pylint and MyPy should target this version to ensure the SDK remains compatible with these versions.
This change revaled some issues with our typings, which were not compatible with Python 3.8 or 3.9. Since types are ignored at runtime, this did not cause any issues with using the SDK on these versions. Our test suite runs against the minumum supported verison, and would catch regressions here, however typechecking on these older versions would flag these issues.
=> Target Python 3.8 for linting SDK

changelog/pending/20241005--sdk-python--handle-nested-structures-properly-when-unwrapping-secrets-from-invoke-inputs.yaml, sdk/python/lib/pulumi/runtime/rpc.py, sdk/python/lib/test/test_next_serialize.py
Follow up for https://github.com/pulumi/pulumi/pull/17460 including tests. We needed to handle values of type `struct_pb2.Value` when unwrapping secrets from invoke inputs. 
> Linting is failing locally using pylint (missing `Module 'google.protobuf.struct_pb2' has no 'Value' member (no-member)` but mypy reports no issues. Maybe CI is fine though
=> [sdk/python] Handle nested structures properly when unwrapping secrets from invoke inputs

changelog/pending/20241001--cli-display--hide-show-secrets-with-save-plan.yaml, pkg/cmd/pulumi/preview.go
`--show-secrets` implies that https://github.com/pulumi/pulumi/issues/9830 is implemented for `pulumi preview`, but it has not been. Instead `pulumi preview` only applies to `--save-plan`, which is hidden by default. This PR does 2 things:
1. It hides `--show-secrets` when `--save-plan` is also hidden.
2. It adds a warning when `--show-secrets` is true but `--save-plan` is unset.
This makes the use of `--show-secrets` less confusing.
=> Hide `pulumi preview`'s `--show-secrets` with `--save-plan`

sdk/nodejs/tests/automation/localWorkspace.spec.ts
This test was always meant to be run locally.  When I introduced the withTestBackend function I missed that, and made it run with the cloud backend accidentally, which results in stackname conflicts.  Revert that part and make it always run locally again.
=> always run multiple stacks concurrently test locally

changelog/pending/20240922--engine--fix-token-expired-errors-due-to-network-issues.yaml, pkg/backend/httpstate/state.go, pkg/backend/httpstate/token_source.go, pkg/backend/httpstate/token_source_test.go
Currently the token source loop will stop if `refreshToken` ever returns
an error, regardless of what that error is. While the API call to the
service does have some retry logic at it's level it can still
potentially return an error just due to transient network/server
conditions. In that case the refreh loop will just stop working and the
token will eventually expire.
This changes the token source to keep going until it gets a specific
`expiredTokenError` error. This should make it more resilient to network
issues.
Towards fixing https://github.com/pulumi/pulumi/issues/7094.
(This is basically a revert of the revert of https://github.com/pulumi/pulumi/pull/17127, and adds a little bit more logging. We reverted that PR originally because something was causing excessive requests to the …
=> Keep the token source loop going in the face of errors 

sdk/nodejs/cmd/pulumi-language-nodejs/language_test.go
For some obscure reason in my environment on a Mac "$TMPDIR" contains two slashes. I suspect this has to do with starting Emacs from Shortcuts.
echo "$TMPDIR"
/var/folders/gd/3ncjb1lj5ljgk8xl5ssn_gvc0000gn/T/com.apple.shortcuts.mac-helper//
This breaks conformance tests for me though. The workaround added to the tests is taking filepath.Abs that normalizes the TMPDIR.
=> Fix language conformance tests for TMPDIR with //

changelog/pending/20241003--cli--allow-memory-profile-to-be-written-occasionally-in-case-of-crash.yaml, sdk/go/common/util/cmdutil/profile.go
If you don't do this the memory profile will never be written because
you do not close cleanly.  It will pollute with GC, but memory and cpu
profiles should be taken separately anyways.
=> Write memory profile occasionally when profiling in case of crash/OOM.

pkg/cmd/pulumi/gen_markdown.go
We recently moved these docs from `/docs/cli/commands` to `/docs/iac/cli/commands`. This PR adjusts the path used to generate links between CLI docs to match the new location.
=> Adjust the link path used in generated CLI docs

changelog/pending/20241010--programgen--detect-and-error-on-binding-component-nodes-in-pcl-programs-that-self-reference-their-source.yaml, pkg/codegen/pcl/binder_component.go, pkg/codegen/pcl/binder_test.go
Recently we have been encountering out of memory errors when trying to convert terraform modules. Found out that the problem is two-fold:
- pulumi-terraform-converter rewriting `module example "../../"` (tf) into `component example "./."` (pcl) 
- we try to bind component `example` but it reads its source from the same directory as the program of the component, causing an infinite recursion.
This PR fixes part 2 of the issue, erroring out if the component's source is the same as the current binder directory path. 
Partially addresses https://github.com/pulumi/pulumi-converter-terraform/issues/194 we still need to fix part 1 on the converter side of things
=> [pcl] Detect and error on binding component nodes that self-reference their source

docs/architecture/README.md, docs/architecture/deployment-execution/resource-registration.md, docs/architecture/providers.md, docs/architecture/types/README.md
Pulumi is built on top of a core type system that is loosely "specified" by the gRPC/Protocol buffer definitions we expose and a set of core implementations in e.g. the Pulumi engine. Historically we documented this type system as part of the old developer documentation. This commit ports that content to the new documentation, tidying it up and correcting things that have since changed/may no longer be the case.
=> Port over developer documentation on Pulumi types

changelog/pending/20241011--sdk-go--improve-error-message-when-credentials-file-invalid.yaml, sdk/go/common/workspace/creds.go
We're seeing this error from esc ([issue](https://github.com/pulumi/esc/issues/401)) which is confusing because it recommends `pulumi login` when using `esc login`. Additionally, rerunning `pulumi login` (or `esc login`) as the message suggests doesn't actually fix anything. I think a better error message is to suggest fixing or deleting the invalid credentials file - open to suggestions though
Testing:
```
❯ go run ./cmd/pulumi login
error: could not determine current cloud: failed to read Pulumi credentials file. Please fix or delete invalid credentials file: '/Users/sean/.pulumi/credentials.json': invalid character 'a' looking for beginning of value
exit status 255
```
=> Improve invalid credentials error message

pkg/resource/deploy/deployment.go
I noticed it isn't used anywhere
=> Remove unused deployment option

changelog/pending/20241017--programgen--fix-pcl-bind-error-cannot-iterate-over-a-value-of-type-number-when-conditionals-are-used-in-range-expressions.yaml, pkg/codegen/pcl/binder_resource.go, pkg/codegen/pcl/binder_test.go
Often when converting terraform modules such as tf VPC module, the range expression of resources is a conditional expression of the form `if should_create_resource ? N : 0`. 
These expressions resolve their type to one of `int`, `bool`, `Output[int]` or `Output[bool]`. Any other type we assume we are dealing with a collection that we are trying to iterate over. However if the conditional expression resolves to `optional(int)` then we think it is a collection, try to get it's key-value pair types and error with "cannot iterate over a value of type number"
This PR fixes this problem by unwrapping `int` from `optional(int)` when encountered in these range expressions. 
I was able to isolate a subset of the converted PCL from terraform VPC module where this problem occurs and created a unit …
=> [program-gen] Fix PCL bind error "cannot iterate over a value of type number"

CONTRIBUTING.md
This adds a small section in CONTRIBUTING.md pointing out where to find developer documentation.
=> Link developer docu in CONTRIBUTING.md

pkg/backend/httpstate/snapshot_test.go, pkg/engine/lifecycletest/alias_test.go, pkg/engine/lifecycletest/analyzer_test.go, pkg/engine/lifecycletest/continue_on_error_test.go, pkg/engine/lifecycletest/delete_before_replace_test.go, pkg/engine/lifecycletest/framework/framework.go, pkg/engine/lifecycletest/golang_sdk_test.go, pkg/engine/lifecycletest/import_test.go, pkg/engine/lifecycletest/loader_test.go, pkg/engine/lifecycletest/parameterized_test.go, pkg/engine/lifecycletest/pending_delete_test.go, pkg/engine/lifecycletest/pending_replace_test.go, pkg/engine/lifecycletest/provider_test.go, pkg/engine/lifecycletest/pulumi_test.go, pkg/engine/lifecycletest/refresh_legacy_diff_test.go, pkg/engine/lifecycletest/refresh_test.go, pkg/engine/lifecycletest/resource_reference_test.go, pkg/engine/lifecycletest/retain_on_delete_test.go, pkg/engine/lifecycletest/source_query_test.go, pkg/engine/lifecycletest/step_generator_test.go, pkg/engine/lifecycletest/target_test.go, pkg/engine/lifecycletest/transformation_test.go, pkg/engine/lifecycletest/update_plan_test.go
Lifecycle tests exist to test the Pulumi engine, allowing us to mock providers and programs and resource registrations before executing specific operations. We'd like to extend our lifecycle test suite to support fuzzing the engine -- that is, generating test cases to exercise edge cases that we might otherwise struggle to find manually. Presently, the framework underpinning the lifecycle tests is defined in a single `test_plan.go` module that sits alongside the `_test.go` files themselves. This means that it's not really possible to factor out or neatly extend the framework (e.g. by adding a `fuzzing` submodule) without introducing circular imports (since tests in `lifecycletest` will import `fuzzing`, which imports the framework from `lifecycletest`).
This commit therefore pulls out …
=> Factor out the lifecycle testing framework

changelog/pending/20241022--docs--fix-spacing-and-formatting-of-stack-init-commands-long-doc.yaml, pkg/cmd/pulumi/stack_init.go
This PR makes the spacing/formatting of the last two examples match the rest of the `stack init` command's long doc.
This'll fix the [markdown generated][1], which is currently rendered [like so][2]:
[1]: https://github.com/pulumi/docs/blob/master/content/docs/iac/cli/commands/pulumi_stack_init.md
[2]: https://www.pulumi.com/docs/iac/cli/commands/pulumi_stack_init/
=> Clean up stack init command's long doc

changelog/pending/20241026--cli--add-interactive-account-selection-to-pulumi-login-command.yaml, pkg/cmd/pulumi/login.go
Add ability to interactively select account to login to using previously authenticated accounts.
https://github.com/user-attachments/assets/c9e1458d-441b-4e08-86d0-37f20908b076
=> add interactive account selection to pulumi login

changelog/pending/20241016--docs--update-function-comments-to-remove-outdated-diy-backend-note.yaml, sdk/go/auto/remote_stack.go, sdk/go/auto/stack.go, sdk/nodejs/automation/remoteStack.ts, sdk/nodejs/automation/stack.ts, sdk/python/lib/pulumi/automation/_remote_stack.py, sdk/python/lib/pulumi/automation/_stack.py
As per https://github.com/pulumi/pulumi/pull/9100, `pulumi cancel` is supported for filestate/DIY/self-managed backends.
=> Update function comments to remove outdated DIY backend note

pkg/engine/lifecycletest/fuzzing/pretty.go, pkg/engine/lifecycletest/fuzzing/resource.go, pkg/engine/lifecycletest/fuzzing/stack.go, pkg/go.mod
Snapshot integrity errors are very problematic when they occur and can be hard to spot and prevent. To this end, #17213 outlines a plan to introduce [fuzzing](https://en.wikipedia.org/wiki/Fuzzing) to our suite of lifecycle tests in order to find cases and executions which might violate snapshot integrity. This commit kicks this off by introducing a `fuzzing` package to the suite and adding types and generators (from the `pgregory.net/rapid` library) for generating random resources. The idea is that from resources we can progress to generating random snapshots; from there to programs and provider configurations and so on; and with all these pieces execute random tests in an attempt to find snapshot integrity bugs before our customers do.
Part of #17213
=> Support generating random resources in lifecycle tests

pkg/engine/lifecycletest/fuzzing/pretty.go, pkg/engine/lifecycletest/fuzzing/resource.go, pkg/engine/lifecycletest/fuzzing/snapshot.go, pkg/engine/lifecycletest/fuzzing/stack.go, pkg/go.mod
Snapshot integrity errors are very problematic when they occur and can be hard to spot and prevent. To this end, #17213 outlines a plan to introduce [fuzzing](https://en.wikipedia.org/wiki/Fuzzing) to our suite of lifecycle tests in order to find cases and executions which might violate snapshot integrity. This commit extends the `fuzzing` package of the suite to support generating random valid snapshots, the idea being that this will enable us to generate good starting states for our property tests. A snapshot contains a number of random resources which may depend on one another in valid ways. Snapshots may also contain deleted resources which have not yet been cleaned from the snapshot.
Part of #17213
=> Support generating random snapshots in lifecycle tests

pkg/engine/lifecycletest/fuzzing/pretty.go, pkg/engine/lifecycletest/fuzzing/program.go, pkg/engine/lifecycletest/fuzzing/resource.go, pkg/engine/lifecycletest/fuzzing/snapshot.go, pkg/engine/lifecycletest/fuzzing/stack.go, pkg/go.mod
Snapshot integrity errors are very problematic when they occur and can be hard to spot and prevent. To this end, #17213 outlines a plan to introduce [fuzzing](https://en.wikipedia.org/wiki/Fuzzing) to our suite of lifecycle tests in order to find cases and executions which might violate snapshot integrity. This commit extends the `fuzzing` package of the suite to support generating random programs. A program is based upon a snapshot and may randomly append and prepend new resources and copy, drop or update existing ones.
Part of #17213
=> Support generating random programs in lifecycle tests

sdk/go/common/slice/slice.go
This handles the pathological case where the length of an input to Map or MapError is 0.
=> Nit: Use slice.Prealloc in slice.Map and slice.MapError

pkg/engine/lifecycletest/fuzzing/provider.go
Snapshot integrity errors are very problematic when they occur and can be hard to spot and prevent. To this end, #17213 outlines a plan to introduce [fuzzing](https://en.wikipedia.org/wiki/Fuzzing) to our suite of lifecycle tests in order to find cases and executions which might violate snapshot integrity. This commit extends the `fuzzing` package of the suite to support generating random providers. A provider may configure operations such as `Create`, `Diff`, etc. to fail or succeed in a number of ways (e.g. no diff, changes, replaces, etc.) on a per-URN basis, so as to exercise a variety of code paths in step generation/execution.
Part of #17213
=> Support generating random providers in lifecycle tests

developer-docs/providers/implementers-guide.md, proto/.checksum.txt, proto/pulumi/provider.proto, sdk/proto/go/provider.pb.go, sdk/python/lib/pulumi/runtime/proto/provider_pb2.pyi
Recommend newer providers read Configure data from `args` instead of `variables`. There still are providers notably `azure-native` and `kubernetes` that rely on `variables`.
Context: https://docs.google.com/document/d/1cnBJzAGWMnjjj2Q5fDdVcq0DcrWd-OqvPPlSxQV50R4/edit?usp=sharing
=> Document that args should be read from in preference to variables

changelog/pending/20241030--sdk-nodejs--support-nodejjs-23.yaml, scripts/get-job-matrix.py
Set Node.js (released October 16th) as the current version.
=> Support Node.js 23

pkg/engine/lifecycletest/README.md, pkg/engine/lifecycletest/fuzzing/README.md, pkg/engine/lifecycletest/fuzzing/fixture.go, pkg/engine/lifecycletest/fuzzing/plan.go
Snapshot integrity errors are very problematic when they occur and can be hard to spot and prevent. To this end, #17213 outlines a plan to introduce [fuzzing](https://en.wikipedia.org/wiki/Fuzzing) to our suite of lifecycle tests in order to find cases and executions which might violate snapshot integrity. This commit extends the `fuzzing` package of the suite to support generating random fixtures and adds documentation for the tactics employed when doing so.
A fixture comprises an initial snapshot, a program to run against that initial snapshot, a set of providers to use during that program's execution, and an operation to run. Fixtures can then be generated as part of a Rapid property test, allowing us to fuzz random combinations in order to hunt down snapshot integrity issues.
Part of …
=> Support generating random fixtures in lifecycle tests

cmd/pulumi-test-language/tests.go
The asserts in gRPC Configure tests are strengthened to check that no secret material is leaked into the Pulumi-tracked state.
=> Assert that secrets do not leak in the gRPC tests

pkg/engine/lifecycletest/fuzzing/README.md, pkg/engine/lifecycletest/fuzzing/fixture.go, pkg/engine/lifecycletest/fuzzing/reprogen.go
In #17623 and the PRs that followed it, we added fuzz testing capabilities to the engine's lifecycle test suite, with a view to randomly generating test cases in the hopes of proactively finding snapshot integrity bugs in our code. This commit extends the fuzzing library to generate a reproducing lifecycle test case in the event that a snapshot integrity error is found, hopefully aiding in debugging and pinning down the exact cause of the error. Code is written to a file in a temporary directory, which may optionally be overridden using an environment variable. This might be useful in e.g. a GitHub action that fuzzes periodically so that failing cases' reproductions can be made available as artifacts for download.
Part of #17213
=> Generate reproductions for fuzz failures

pkg/engine/lifecycletest/fuzzing/program.go, pkg/engine/lifecycletest/fuzzing/resource.go, pkg/engine/lifecycletest/fuzzing/snapshot.go
In #17623 and the PRs that followed it, we added fuzz testing capabilities to the engine's lifecycle test suite, with a view to randomly generating test cases in the hopes of proactively finding snapshot integrity bugs in our code. This commit extends the fuzzer so that it randomly parents, re-parents, and aliases reparented resources, covering the various parent/child relationships that these actions lead to and which can result in snapshot integrity issues if handled improperly. In particular, we can now fuzz the following:
* Randomly parenting a resource to another resource in an initial snapshot.
* Randomly updating a resource in a program to either add, remove, or change an existing parent.
* Randomly aliasing a resource whose parent (and consequently URN) has been changed by a …
=> Add the ability to fuzz parents and aliases

.github/workflows/ci-build-binaries.yml
While working on https://github.com/pulumi/pulumi/pull/17364 I ran into this, and this permission seems unused.
=> Remove unused id-token: write permission ci-build-binaries

codecov.yml
Everything in the lifecycletest package is test code, and thus doesn't make a lot of sense to count against code coverage.  Exclude it.
=> exclude lifecycletest from codecov

cmd/pulumi-test-language/interface_test.go
In #17589 we added the `package` block to PCL in order to support parameterized providers. As part of this work, we added an initial set of language conformance tests for parameterized providers. Presently there are some workarounds involved in doing so as historically we have only tested non-parameterized providers. This commit introduces one that we missed, without which some assertions currently fail since they are unaware of parameterized providers.
=> Fix language conformance tests

docs/architecture/deployment-execution/README.md, docs/architecture/deployment-execution/import.md
The old developer documentation had content on importing resources using both the `import` resource option and the `pulumi import` command. This commit ports this work over to the new documentation pages, updating it where appropriate to reflect the current state of affairs.
=> Port over documentation on importing resources

.github/workflows/ci-dev-release.yml, .github/workflows/ci-prepare-release.yml, .github/workflows/ci-run-test.yml, .github/workflows/ci.yml, .github/workflows/sign.yml
In CI we want to have binaries that emit coverage and have race detection built in.  However we don't want that in release builds, as neither of these things is useful there, and is just slowing down the binary.  We currently achieve this by rebuilding the binaries after all the tests have run.
However building the binaries takes additional time (~3min currently). Wit the introduction of the artifact-suffix option in `ci-build-binaries` we can now do better, and build the release binaries in parallel with running the tests.  Do that here to save some time when running CI.
(this is a follow up from https://github.com/pulumi/pulumi/pull/17364/files#r1827550113)
=> build release binaries in parallel with other CI steps

pkg/cmd/pulumi/org_search.go
As part of https://github.com/pulumi/home/issues/3583 documentation is updated to recommend BucketV2 usage over Bucket. Part of the documentation is generated automatically from `pulumi --help`. To get this right the Pulumi CLI itself needs to be updated. This change updates the example used in `pulumi --help` to use BucketV2 instead of Bucket.
=> Update pulumi --help documentation to use bucketv2/BucketV2

changelog/pending/20241104--engine--disable-the-enviromental-github_token-on-403-responses.yaml, sdk/go/common/workspace/plugins.go, sdk/go/common/workspace/plugins_test.go
Similar to what we did in https://github.com/pulumi/pulumi/pull/17351, we should also invalidate the GITHUB_TOKEN when the GitHub API returns a 403, which can happen in some cases when the token isn't valid.
Fixes https://github.com/pulumi/pulumi/issues/17217
=> plugin download: also invalidate GITHUB_TOKEN on 403

proto/.checksum.txt, proto/pulumi/provider.proto, sdk/nodejs/proto/provider_grpc_pb.js, sdk/proto/go/provider.pb.go, sdk/proto/go/provider_grpc.pb.go, sdk/python/lib/pulumi/runtime/proto/provider_pb2.pyi, sdk/python/lib/pulumi/runtime/proto/provider_pb2_grpc.py, sdk/python/lib/pulumi/runtime/proto/provider_pb2_grpc.pyi
This commit fleshes out the documentation for the `CheckConfig` method of resource providers.
=> Document `ResourceProvider.CheckConfig`

pkg/backend/httpstate/backend.go, pkg/backend/httpstate/state.go
Simplify keeping the machine running in the service backend.  Instead of splitting it up, we can simply make sure to keep the computer running for the whole apply.  This also removes the risk of the resetSleep function being nil, and potentially panic'ing.  (This is currently not possible, but the setup we currently have is somewhat brittle)
Thanks @lunaris for pointing this out.
=> simplify the keep running in the service backend

.github/workflows/ci-run-test.yml
Currently we are setting the timout in our CI jobs to 60 minutes.  We also set the timeout for Go tests to 1h (see GO_TEST_FLAGS in build/common.mk).  This means the GitHub action times out before the `go test` does, which in turn means that if there are timeouts there's no information of what timed out.  Normally Go test prints the current stack trace of every goroutine that is currently running.
By raising the GitHub actions imposed timeout to 70 minutes, we'll allow `go test` to time out first, which should provide helpful debuging information in the case of timeouts.
(one example of this happening is here: https://github.com/pulumi/pulumi/actions/runs/11702940046/job/32592316950?pr=17567)
=> increase the timeout for running CI tests

changelog/pending/20240918--engine--persist-metadata-about-snapshot-integrity-errors.yaml, pkg/backend/diy/state.go, pkg/backend/httpstate/diffs_post_1.20.go, pkg/backend/httpstate/state.go, pkg/backend/httpstate/testdata/snapshot_test.json, pkg/backend/snapshot.go, pkg/backend/snapshot_test.go, pkg/cmd/pulumi/errors.go, pkg/resource/deploy/snapshot.go
In #17047, we introduced a panic-like error banner for snapshot integrity issues. In #17144, we improved this to prompt users to provide information about the operation that *wrote* an invalid snapshot, should the error be encountered on a later *read*. In this commit, we take things one step further, persisting the writing command to the snapshot as metadata in the event that we are about to write an invalid snapshot. Should an error be encountered on a later read, we are now able to pluck the metadata out of the snapshot and include it in the error banner ourselves. This should hopefully further improve the situation when it comes to tracking down bugs in the engine.
Note that, like all changes to snapshot persistence, new snapshot fields (in this case, the metadata we now collect) may …
=> Persist metadata about snapshot integrity errors

changelog/pending/20241106--sdk-go--workspace-copytemplatefiles-overwrites-directories-when-called-with-force-true.yaml, sdk/go/common/workspace/templates.go, sdk/go/common/workspace/templates_test.go
`workspace.CopyTemplateFiles()` can be called with `force=true`, which currently allows files to be overwritten, but errors when trying to overwrite directories. This commit enables overwriting directories when called with `force=true`.
Fixes #17653
=> workspace.CopyTemplateFiles overwrite dirs with force

changelog/pending/20241104--sdk-python--allow-accessing-configuration-in-python-dynamic-providers.yaml, pkg/cmd/pulumi/package.go, pkg/resource/deploy/target.go, sdk/go/common/resource/plugin/context.go, sdk/go/common/resource/plugin/host.go, sdk/go/common/resource/plugin/provider_plugin.go, sdk/python/lib/pulumi/dynamic/__init__.py, sdk/python/lib/pulumi/dynamic/__main__.py, sdk/python/lib/pulumi/dynamic/config.py, sdk/python/lib/pulumi/dynamic/dynamic.py, sdk/python/lib/test/dynamic/test_config.py, tests/integration/dynamic/python-config-separate-module/Pulumi.yaml, tests/integration/dynamic/python-config-separate-module/__main__.py, tests/integration/dynamic/python-config-separate-module/provider.py, tests/integration/dynamic/python-config/Pulumi.yaml, tests/integration/dynamic/python-config/__main__.py, tests/integration/dynamic/python-secrets/__main__.py, tests/integration/integration_python_test.go
Python dynamic providers get serialised and deserialised, and run in the `pulumi-python` plugin process. This causes issues when trying to use `pulumi.config.Config` in a dynamic provider:
* Using `Config` at runtime fails because the process is not setup with the current configuration
* When the dynamic provider implementation is in the `__main__` module, the dynamic provider serialization attempts to serialize the global `SETTINGS` object, which pulls in protobuf definitions, which are not serializable by `dill`.
To provide a stable API to access configuration in dynamic providers, the provider classes  (ResourceProvider) can now implement a `configure` method which is called during provider initialization.
```python
class SimpleProvider(ResourceProvider):
password: str
def …
```
=> Allow accessing configuration in Python dynamic providers

changelog/pending/20241107--pkg--allow-generating-docs-in-parallel.yaml, pkg/codegen/docs/gen.go, pkg/codegen/docs/gen_test.go, pkg/codegen/docs/package_tree_test.go, pkg/codegen/docs/utils.go
Add support for calling `GeneratePackage` and `GeneratePackageTree` in parallel. State is already encapsulated via `*docGenContext`, and tests of `GeneratePackage` already run in parallel, this just exposes the context abstraction to users.
=> Add `codegen/docs.NewContext` and supported methods

pkg/backend/backend.go, pkg/cmd/pulumi/config.go, pkg/cmd/pulumi/destroy.go, pkg/cmd/pulumi/import.go, pkg/cmd/pulumi/preview.go, pkg/cmd/pulumi/refresh.go, pkg/cmd/pulumi/up.go, pkg/cmd/pulumi/util.go, pkg/cmd/pulumi/util_test.go, pkg/cmd/pulumi/watch.go
Related: https://github.com/pulumi/pulumi-service/pull/23672
We want to be able to track which ESC environments are depended on by which stacks on the cloud side, so this passes the list of imported envs as metadata on stack update
=> Pass ESC Environments on stack update

changelog/pending/20241107--sdk-python--log-a-message-about-deleting-requirements-txt-when-converting-to-using-poetry.yaml, sdk/python/toolchain/poetry.go, tests/integration/integration_python_acceptance_test.go
Follow up to https://github.com/pulumi/pulumi/pull/17609#discussion_r1832695404
When we convert a requirements.txt based project to use Poetry & pyproject.toml, inform the user that requirements.txt was deleted and that dependencies are tracked in pyproject.toml.
=> Log a message about deleting requirements.txt when converting to using Poetry

sdk/nodejs/tests/runtime/langhost/run.spec.ts
While adding a new test in https://github.com/pulumi/pulumi/pull/17632 I noticed that assertions or thrown errors in the log callback are not actually checked. This PR fixes this by tracking any error thrown from the callback and then failing the test if one was found.
Somewhat surprisingly, we did not break anything, even though the tests didn't always check what we thought they did. I validated the fix by intentionally breaking some of the tests and asserting that they started failing.
=> Fix checking assertions in the log callback of nodejs engine tests

changelog/pending/20241107--engine--fix-frequent-retries-on-403-errors-when-the-update-token-expires.yaml, pkg/backend/httpstate/state.go, pkg/backend/httpstate/token_source_test.go
In the token source loop, when a 403 error happens, there's no way it's going to succeed in the future, and we want to abort it.  We try to do so currently, however we're passing the incorrect type to `errors.As`, and thus never get an expiredTokenError, and never abort the loop.
Note that we are no longer retrying this in a tight loop, but if someone calls `GetToken` frequently for whatever reason, we'd still end up in the same situation as in https://github.com/pulumi/home/issues/3660.
Fix that, and add a test that reproduces the whole round trip through the client by setting up a fake http server.
Fixes https://github.com/pulumi/pulumi/issues/17551
=> stop the token source loop correctly on 403 errors

.github/workflows/ci.yml, .github/workflows/on-pr.yml, codecov.yml
Codecov numbers should be stable enough now to enable them for PRs as well.
=> enable coverage for PRs

Makefile, docs/architecture/deployment-execution/state.md, pkg/engine/lifecycletest/fuzz_test.go, pkg/engine/lifecycletest/fuzzing/README.md, pkg/engine/lifecycletest/fuzzing/plan.go, pkg/engine/lifecycletest/fuzzing/provider.go, pkg/engine/lifecycletest/fuzzing/resource.go, pkg/engine/lifecycletest/fuzzing/snapshot.go
In #17623 through #17627 and some follow-up PRs, we built out a framework for fuzzing lifecycle tests in order to help track down snapshot integrity violations in the Pulumi engine. All that remains now is to actually provide ways to trigger a fuzzing run in useful ways. This commit kicks this off by introducing two Go test functions that can be run with `go test` or our `Makefile`:
* `TestFuzz` -- this runs the fuzzer and generates a brand new set of scenarios (1,000 by default) and checks whether any of them result in a snapshot integrity error. This test is skipped unless an environment variable is set (which the `Makefile` handles if one runs `make test_lifecycle_fuzz`). The intended purpose of this test is to back one or more CI workflows that will run periodically in order to slowly …
=> Add Go tests for fuzzing the engine

pkg/cmd/pulumi/util.go, pkg/cmd/pulumi/util_test.go, sdk/go/common/apitype/updates.go
We would like to move this type to apitype so it can be reused in the service
=> Move EscEnvironmentMetadata to apitype

changelog/pending/20241108--sdk-nodejs--implement-runplugin-for-the-nodejs-language-runtime.yaml, sdk/nodejs/cmd/pulumi-language-nodejs/main.go, sdk/nodejs/cmd/run-plugin/index.ts, sdk/nodejs/cmd/run-plugin/run.ts, sdk/nodejs/cmd/run-policy-pack/index.ts, sdk/nodejs/cmd/run-policy-pack/run.ts, sdk/nodejs/cmd/run/index.ts, sdk/nodejs/tsconfig.json
Implement RunPlugin for NodeJS. This follows a similar path as the rest of the language runtime does, spawning a NodeJS program, which in turn runs the plugin itself.  The run-plugin code was cribbed from run-policy-pack, which works similarly.
Note that this means that in addition to a recent language runtime, this also requires the plugin to reference a recent version of the Pulumi SDK.  Since the main purpose of implementing this is supporting a new feature that should be okay though.
Fixes https://github.com/pulumi/pulumi/issues/17663
=> implement RunPlugin for nodejs

.github/workflows/cron-test-all.yml, scripts/get-job-matrix.py
Currently we run all tests twice when running the tests in the merge queue.  Once with the oldest version of all languages we support, and once with the most recent one.  This leaves out all of the ones in the middle.
Ideally we would like to test all of those as well, but that's way too expensive to do on every merge.  Instead add a cron job that does exactly this test once a day.  If it fails this will automatically open an issue for us to take a look.
This will end up being quite a lot of jobs, so we're trying to run after the workday finished in the Americas, and before it starts in Europe, as to not overwhelm CI too much, as most employees will be asleep (apart from @brandonpollack23, but hopefully there's still enough CI runners left to pick up those jobs).
One potential downside is …
=> run the full language matrix of tests daily

changelog/pending/20241111--sdk-nodejs--support-parameterization-for-typescript-providers.yaml, sdk/nodejs/provider/provider.ts, sdk/nodejs/provider/server.ts
Parameterized providers are currently only possible to use in Go. However we want to bring this functionality to other languages as well.  Implement this in NodeJS.
There's potentially still an API design question here.  I've split the parameterize method up into `parameterizeValue` and `parameterizeArgs` functions, which should be easier to use for the implementer, as TypeScript doesn't support overloading with different types.  Curious about peoples thoughts on that.
Fixes https://github.com/pulumi/pulumi/issues/17733
=> implement parameterize in the NodeJS provider interface

developer-docs/providers/implementers-guide.md
We already have documentation for these, so just add a sentence and a link to the docs that have some more information on this.
=> document property paths in the providers implementers guide

changelog/pending/20241113--sdk-nodejs--fix-pnpm-pack-for-pnpmat9-13.yaml, sdk/nodejs/npm/pnpm.go
For pnpm versions <9.13, pnpm pack outputs a single line with the name
of the tarball. On pnpm versions >=9.13, pnpm pack lists all the packed
files, and the last line is the tarball.
https://github.com/pnpm/pnpm/pull/8707
=> Fix pnpm pack for pnpm@9.13

changelog/pending/20241113--sdk-python--fix-an-exception-in-automation-api-when-reading-whoami-results.yaml, sdk/python/lib/pulumi/automation/_local_workspace.py
Fixes https://github.com/pulumi/pulumi/issues/17734.
There were a couple of places in the python automation API where we would read in JSON data from the CLI and [splat](https://docs.python.org/3/tutorial/controlflow.html#unpacking-argument-lists) the data into a constructor to return that data in a typed python class.
This hits issues whenever new data is returned from the CLI that the python class has not yet been updated to understand (see https://github.com/pulumi/pulumi/issues/17734 for the motivating example this time round).
While it's easy to add the new field to the class to fix the issue, we'll just hit this again if we ever add any other new fields.
This PR removes the splat operator and just explicitly lists out the arguments to set. This also allows the python name to differ …
=> Replace splats with explict property copying for JSON data

.github/workflows/cron-test-all.yml
ci.yml that we're calling from here needs these permissions.  The calling workflow needs to include them as well, otherwise the callee is not allowed to get them.  Fix that.
I think we didn't get an issue open because of this failure because the workflow never really ran.  I'll keep an eye on it for the next days though to make sure issues are opened correctly.
=> add missing permissions to the cron-test-all job

docs/requirements.txt, sdk/nodejs/yarn.lock
This commit packages up a few Dependabot security updates:
* Bumps the `pip` group with 1 update in the `/docs` directory:
- [starlette](https://github.com/encode/starlette) from 0.38.0 to 0.40.0
- [Release notes](https://github.com/encode/starlette/releases)
- [Changelog](https://github.com/encode/starlette/blob/master/docs/release-notes.md)
- [Commits](https://github.com/encode/starlette/compare/0.38.0...0.40.0)
* Bumps the `npm_and_yarn group` with 1 update in the `/sdk/nodejs` directory:
- [path-to-regexp](https://github.com/pillarjs/path-to-regexp) from 6.2.2 to 6.3.0
- [Release notes](https://github.com/pillarjs/path-to-regexp/releases)
- [Changelog](https://github.com/pillarjs/path-to-regexp/blob/master/History.md)
- [Commits](https://github.com/pillarjs/path-to-regexp/compare/v6.2. …
=> Bump some dependencies recommended by Dependabot

changelog/pending/20241113--engine--pass-correct-working-directory-to-runplugin.yaml, sdk/go/common/resource/plugin/langruntime_plugin.go, sdk/go/common/resource/plugin/langruntime_test.go
RunPlugin expects the working directory of the program to be passed in in the plugin request.  This was the case until
https://github.com/pulumi/pulumi/pull/15191.  In that PR we switched from passing pwd (which is the same as `ctx.Pwd` a layer above) to minfo.GetProgramDirectory(), which is the path from which the plugin is executed.  Fix this by passing in `info.WorkingDirectory`, which a layer above is `ctx.Pwd`.
Add a test for this as well to make sure we're not regressing this again.
Likely nobody noticed this, because most plugins probably don't rely on this path, and most providers are not being run using `RunPlugin`.
=> pass correct working directory to RunPlugin

pkg/engine/lifecycletest/fuzzing/program.go, pkg/engine/lifecycletest/fuzzing/reprogen.go, pkg/engine/lifecycletest/fuzzing/resource.go, pkg/engine/lifecycletest/fuzzing/snapshot.go
Fuzzed lifecycle tests work slightly differently to their handwritten counterparts. A handwritten test will typically "start from nothing". An initial snapshot is built from an empty state and starting program, before subsequent operations are executed on this state to test behaviour. In constrast, fuzzed tests create arbitrary starting snapshots "out of thin air", before running an operation to see if a bug can be triggered. Ideally, any starting state conjured by a fuzz test is actually reproducible from an empty state and some combination of operations, but it may be that this is not the case, or that the number of operations required to reach the state is very high. In such cases, it is handy to have the exact code the fuzz test used to hand when reproducing and isolating behaviour. …
=> Generate more accurate reproductions when fuzzing

Makefile, sdk/nodejs/Makefile, sdk/python/Makefile
Some of the linters we're using have an option to fix some of the lint errors they are finding.  This obviously only works for the simple cases, and nothing too complex, but can still be useful.
Since there are a bunch of different tools we're using, it's not always easy to remember which option needs to be passed to which tool. Add `lint_fix` Makefile targets that pass these options to our linters where available, to help fix these issues more easily.
=> add lint_fix Makefile targets

.github/workflows/cron-test-all.yml
The ci.yml workflow needs the 'id-token: write' permission.  I tried to fix this in https://github.com/pulumi/pulumi/pull/17764, but apparently the permissions also need to be passed in from here.  This should hopefully make it run properly.
=> pass correct permissions to the ci.yml workflow

changelog/pending/20241112--sdk-python--fix-merging-invokeoptions-version.yaml, sdk/python/lib/pulumi/invoke.py, sdk/python/lib/test/test_invoke.py
`InvokeOptions.version` was defaulting to the empty string `""` and not `None`, see https://github.com/pulumi/pulumi/blob/1a97d95583a491bb32ec24fe71817f1627f1cf58/sdk/python/lib/pulumi/invoke.py#L57
While working on https://github.com/pulumi/pulumi/issues/17749 I noticed that the merge function was not expecting the empty string, and clearing out the version on merge when it probably shouldn't.
Since this is typed as `Optional[str]`, code that uses this value already has to deal with `None`, and we can update it to default to `None` instead.
=> Fix merging InvokeOptions.version

pkg/cmd/pulumi/new.go, pkg/cmd/pulumi/policy_new.go, pkg/cmd/pulumi/up.go, sdk/go/common/util/gitutil/git.go, sdk/go/common/workspace/templates.go, sdk/go/common/workspace/templates_test.go
Pass a context to the git clone utilities.  In the future we want to be able to use them to download plugins, which should be cancellable. Pass the context through to allow this.
In theory this is not backwards compatible for this API, but we've recently been allowing similar changes (e.g. in https://github.com/pulumi/pulumi/pull/17621), so I think this is okay to do.
=> pass context to git clone utilities

changelog/pending/20241120--sdk-go--split-public-and-internal-representation-of-invokeoptions.yaml, sdk/go/pulumi/resource.go, sdk/go/pulumi/resource_test.go
In preparation for allowing the DependsOn and DependsOnInputs options to work for (Output form) invokes, we split the public and internal representations of InvokeOptions.
This matches resourceOptions and ResourceOptions, where the public type is a snapshot of the private type. The private parameterization field is moved to the private invokeOptions type.
=> Split public and internal representation of InvokeOptions

changelog/pending/20241121--cli-new--allow-urls-without-a-scheme-for-downloading-templates.yaml, sdk/go/common/util/gitutil/git.go, sdk/go/common/util/gitutil/git_test.go
For remote plugins we want to allow URLs without a scheme to be used for specifying the plugin location.  We want to be consistent with this for example for downloading templates in pulumi new.
Allow this parsing of Git URLs in the git utility.
=> allow URLs without template for downloading git repos
