pkg/testing/integration/program.go
Needed to support tests written in JavaScript (instead of TypeScript).
=> Support SkipBuild in integration test framework

pkg/backend/local/progress.go
Fixes https://github.com/pulumi/pulumi/issues/1602
=> Print out a 'still working' message every 20 seconds when in non-interactive mode.

sdk/nodejs/resource.ts
Fixes https://github.com/pulumi/pulumi/issues/1445
=> Tiny tweak to error message.

sdk/nodejs/resource.ts, sdk/nodejs/runtime/resource.ts, tests/integration/duplicate_urns/step4/index.ts
=> Allow `dependsOn` to accept a Resource | Resource[]

cmd/util.go
In #1341 we promoted a class of errors in fetching git metadata from
glog messages to warnings printed by the CLI. On the asumption that
when we got warnings here they would be actionable.
The major impact here is that when you are working in a repository
which does not have a remote set to GitHub (common if you have just
`git init`'d a repository for a new project) or you don't call your
remote `origin` or you use some other code provider, we end up
printing a warning during every update.
This change does two things:
- Restructure the way we detect metadata to attempt to make progress
when it can. We bias towards returning some metadata even when we
can't determine the complete set of metadata.
- Use a multierror to track all the underlying failures from our
metadata probing and move it …
=> Move git related warnings back to glog statements

Makefile, build/common.mk, sdk/go/Makefile, sdk/nodejs/Makefile, sdk/python/Makefile
This will put everything in $GOPATH/bin which is fine for Homebrew needs I think.
=> Added dist target for make, will help with Homebrew

pkg/util/testutil/ci.go
Our existing logic was ported from an existing NPM package. However,
our port was incorrect, which is unsurprising given the style of the
source code.
I have rewritten the logic to be more idomatic golang, while keeping
the overall detection logic intact.
Our detection is still based on the presence of environment
variables.
Fixes: #1646
=> Rework CI detection logic

cmd/destroy.go, cmd/preview.go, cmd/refresh.go, cmd/up.go, tests/integration/double_pending_delete/step1/index.ts, tests/integration/double_pending_delete/step2/index.ts, tests/integration/double_pending_delete/step3/index.ts, tests/integration/double_pending_delete/step4/index.ts
=> Default to a parallelism fanout of 10

README.md
We don't show any code in our README, which is a shame, because we're
all about the code! This should help grok what Pulumi is more quickly.
=> Add a couple examples to the README

pkg/engine/lifecycle_test.go
Follow-up to https://github.com/pulumi/pulumi/pull/1770.
=> Add test for pulumi/pulumi#1770

cmd/new.go
=> Add `-g` shorthand for `--generate-only`

cmd/stack_rm.go
=> Tweak help text for `pulumi stack rm -f`

sdk/nodejs/cmd/pulumi-language-nodejs/main.go
The plugin host can ask the language host to provide a list of
resource plugins that it thinks will be nessecary for use at
deployment time, so they can be eagerly loaded.
In NodeJS (the only language host that implements this RPC) This works
by walking the directory tree rooted at the CWD of the project,
looking for package.json files, parsing them and seeing it they have
some marker property set. If they do, we add information about them
which we return at the end of our walk.
If there is *any* error, the entire operation fails. We've seen a
bunch of cases where this happens:
- Broken symlinks written by some editors as part of autosave.
- Access denied errors when part of the tree is unwalkable (Eric ran
into this on Windows when he had a Pulumi program at the root of his
file system. …
=> Do not make errors during plugin discovery fatal

sdk/nodejs/runtime/closure/codePaths.ts
=> Fix issue where we were sometimes filtering out certain node modules innapropriately.

pkg/engine/plan.go, pkg/engine/update.go, pkg/resource/deploy/plan.go, pkg/resource/deploy/plan_executor.go, pkg/resource/deploy/step_generator.go
Nothing actually uses this information.
=> Remove deploy.PlanSummary.

pkg/testing/integration/program.go
Often when the test fails, you'll want to use the web console to
investigate the stack, looking at detailed log messages, for
example. But since we always delete the stack today, you often can't.
Stop running `pulumi stack rm` when the test fails, however do run a
`pulumi destroy` so we at least clean up any resources the stack may
have allocated during testing.
Fixes #1722
=> Do not delete failed stacks from integration tests

pkg/testing/integration/program.go
Allows working around bugs in refresh (such as https://github.com/pulumi/pulumi-terraform/issues/241).
=> Allow skipping refresh step in integration tests

cmd/util.go, pkg/util/cmdutil/diag.go
Fixes https://github.com/pulumi/pulumi/issues/1395
=> Disable colors if we're not in an interactive session.

sdk/nodejs/runtime/closure/codePaths.ts, sdk/nodejs/runtime/closure/createClosure.ts, sdk/nodejs/runtime/closure/parseFunction.ts, sdk/nodejs/runtime/closure/serializeClosure.ts, sdk/nodejs/runtime/index.ts, sdk/nodejs/tests/runtime/closure.spec.ts
Partial fix for https://github.com/pulumi/pulumi/issues/1876
Will have to consume downstream in @pulumi/aws and @pulumi/azure
=> Provide helper to compute whihc sub-packages should be included even if we would exclude a higher package.

sdk/nodejs/cmd/pulumi-language-nodejs/main.go
Instead of trying to probe for the normal path ourselves, just use
node's `require.resolve` statement to find `@pulumi/pulumi/cmd/run`.
This allows run to be found in cases where either yarn workspaces are
used, or the module has been installed globally.
Part of #1868
=> Use `require.resolve` to find `@pulumi/pulumi/cmd/run`

sdk/nodejs/tests/runtime/langhost/run.spec.ts
For some reason, our current gRPC test setup has become flaky now that
we are spinning up two gRPC servers. Hopefully merging them into one
helps clarify what's going on.
=> Combine two gRPC servers into one for testing

cmd/pulumi.go
=> Added short description to pulumi root cmd

pkg/backend/httpstate/backend.go
In order to present a message with a link to a user's access tokens in
the service, we have to convert the API server's URL to the URL for
the console.  We understand how to do this for servers that look like
our servers (i.e. their host name is `api.<whatever>`), but in general
we can't do this.
Rewrite the code such that we only print a message about how to find
your access tokens (and offer browser based login) only in cases where
we are able to construct a URL to the console.
Fixes #1930
=> Don't print junk when a unrecognized URL is passed to `pulumi login`

pkg/backend/display/progress.go
Old:
New:
Fixes https://github.com/pulumi/pulumi/issues/1942.
=> Fix preview display for replacements

pkg/backend/display/rows.go
It's useful to show a diff whenever a user toggles the protect bit on a
resource, so they can be sure that it has actually occurred.
Fixes pulumi/pulumi#1777. Example where I am adding a `protect: true` to a resource that previously didn't have it:
=> Display diff when Protect bit changes

cmd/util.go
This pull request adds checks for a set of predefined environment variables:
- `PULUMI_CI_SYSTEM`
- `PULUMI_CI_BUILD_ID`
- `PULUMI_CI_BUILD_TYPE`
- `PULUMI_CI_BUILD_URL`
- `PULUMI_CI_PULL_REQUEST_SHA`
If `PULUMI_CI_SYSTEM` is set in the environment, CI configuration is extracted from the remaining variables for sending to the backend, and disables the checks for supported systems (currently only Travis CI).
This increases the flexibility of the Pulumi CLI by not requiring specific support for particular CI systems to be added, provided the necessary environment variables are configured for the job - this should be possible for at least TeamCity, Jenkins, AWS CodeBuild, Azure DevOps Pipelines, and likely most other systems.
This should not replace native support for detecting more CI …
=> Allow any configured CI to use the GitHub app

pkg/testing/integration/program.go
Add two command-line options to the test framework, "-dirs" and
"list-dirs". The former accepts a regex that is used to select which
integration tests to run. The latter lists available integration tests
without running them.
=> Improve integration test usability.

sdk/nodejs/config.ts
=> Fix requireObject docs

Gopkg.lock, pkg/backend/apply.go, pkg/backend/display/display.go, pkg/backend/display/progress.go, pkg/backend/display/rows.go, pkg/backend/filestate/backend.go, pkg/backend/httpstate/backend.go, pkg/backend/httpstate/state.go, pkg/diag/colors/colors.go, pkg/diag/sink.go, pkg/engine/diff.go, pkg/engine/eventsink.go, pkg/resource/deploy/step.go, pkg/resource/stack.go, pkg/util/cmdutil/diag.go, tests/integration/integration_test.go
Particularly in light of the removal of the light black colors, and in an attempt to make a(n admittedly minor) dent in https://github.com/pulumi/pulumi/issues/1851, this PR contains a number of CLI UX improvements. I'm sure some will be controversial -- or perhaps nobody will care about nitpicking this level of UI detail but me -- however I believe the CLI feels much more streamlined with these changes.
=> Make a smattering if CLI UX improvements

README.md
=> Add link to full installation instructions

cmd/stack_ls.go, cmd/stack_rm.go
These commands ought to work even when you don't have a Pulumi.yaml:
$ pulumi stack ls --all
$ pulumi stack rm some-random-stack
They didn't previously, now they do. This fixes pulumi/pulumi#1556.
=> Support some stack operations w/out a Pulumi.yaml

cmd/util.go
Before we start processing an update, we call `addGitMetadata` in `util.go` to add metadata about the current environment to the update. e.g. the current Git commit, the origin's repo name, etc.
#1319 changed the way we check if the repo is dirty from using a git library, to just shelling out to `git` directly. (And in-turn having a pretty massive perf boost.)
However, there are some very unlikely scenarios where this could lead to the git repo being considered dirty when the repo for the update should not. (By "unlikely" I mean, the original change landed 5-months ago and we only just now noticed when writing new tests.)
When we shell out to git, we don't specify the working directory. So it runs from the processes CWD (i.e. `pulumi`). However, we should set the CWD for the `git` process …
=> Check git status from project repo, not cwd

cmd/stack_init.go
=> Add note about create a stack in an organization to the help

pkg/engine/lifecycle_test.go, pkg/engine/update.go
Whenever an update fails partially, it gives the engine back some state
bag of outputs that should be persisted to the snapshot. When saving
this state, we shouldn't save the inputs that triggered the update that
failed, since the resource that exists will never have been updated
successfully with those inputs.
Instead of saving the new inputs on partial failed updates, this commit
saves the old inputs and the new outputs. The new outputs will likely
need to be refreshed to be useful, but the old inputs will be correct
from the perpsective of the Pulumi program that generated the last
successful update.
Fixes pulumi/pulumi#2011
=> Save old inputs on partial update failures

sdk/nodejs/runtime/closure/codePaths.ts
Fixes https://github.com/pulumi/pulumi/issues/2031
=> Deal with circularities in package structure when computing codepaths.

cmd/stack_ls.go, cmd/util.go, tests/integration/integration_test.go
We've had multiple users ask for this, so let's do it proactively
instead of waiting for #496
Fixes #2018
=> Add `--json` flag to `pulumi stack ls`

sdk/nodejs/runtime/closure/createClosure.ts
Should be reviewed with whitespace difference off.  This is juts a move of some initilization code into a helper function.
=> Cleanup a little code in closure creation.

sdk/nodejs/tests/runtime/closure.spec.ts
I'm tweaking the internals on how we do Output serialization in the node11 branch.  I want some beefed up testing here so i don't break anything.
=> Add test with complex output scenarios.

pkg/backend/display/display.go
Fixes https://github.com/pulumi/pulumi/issues/1610
=> Round time to the nearest second to clean up our display

pkg/backend/display/display.go
Fixes https://github.com/pulumi/pulumi/issues/2038
=> Include diagnostic prefix in the output for the diff display.

pkg/resource/deploy/plan.go
Just what it says on the tin.
Fixes #2030.
=> Do not assert on duplicate resources.

sdk/nodejs/tests/runtime/tsClosureCases.ts
This test fails non-deterministically.
#2182 tracks fixing this.
=> Disable the config capture test

cmd/stack_ls.go
When an update is in progress, `pulumi stack ls` was showing the LAST
UPDATE time as "a long while ago" because the service API returns 0 as
the last update time.
Handle this case correctly, displaying "in progress" for the update
time. When using JSON output, we don't include the update time (just
like a stack that has never been updated) but we do set the
`updateInProgress` property of the returned object
Fixes #2042
=> Correctly handle in progress updates in `pulumi stack ls`

pkg/workspace/plugins.go
=> Download plugins to temp folder before installing

sdk/nodejs/tests/runtime/deploymentOnlyModule/config.ts, sdk/nodejs/tests/runtime/deploymentOnlyModule/index.ts, sdk/nodejs/tests/runtime/deploymentOnlyModule/runtimeConfig.ts, sdk/nodejs/tests/runtime/tsClosureCases.ts
Fixes https://github.com/pulumi/pulumi/issues/2182
=> Reenable tests.

pkg/workspace/plugins.go
This is code that should have been part of #2211 but was accidently
dropped during a rebase when responding to CR feedback.
When two installs for the same plugin are racing, the second one will
see the destination directory already exists and fail. We can safely
ignore this error.
=> Do not fail `plugin install` when the destination folder exists

sdk/python/cmd/pulumi-language-python/main.go, tests/integration/integration_test.go
'python' is not usually symlinked to 'python3' on most distros unless
you are already running in a virtual environment. Launching 'python3'
explicitly ensures that we will either launch the program successfully
or immediately fail, instead of launching the program with Python 2 and
failing with syntax errors at runtime.
This commit also emits an error message asking users to install Python
3.6 or later if we failed to find the 'python3' executable.
=> Launch Python programs with 'python3' by default

pkg/apitype/events.go, pkg/backend/httpstate/state.go
(PR description to come later. Just creating so Travis will publish the build and I can test out Service-side changes based on the published drop.)
=> Incorporate feedback on Engine Events API

pkg/testing/integration/program.go
We've copied this function in a few different repos now.  Just moving it down to the base integration testing lib so they can refer to this common copy.
=> Add test helper function.

pkg/engine/diff.go, pkg/resource/properties.go
Fixes https://github.com/pulumi/pulumi/issues/2093
=> Use 'output<...>' as our terminology for 'computed' properties.

README.md
=> Add Roadmap to README

CHANGELOG.md
Handle the fallout from the cherry-pick.
Note this commit should be merged using a merge commit.
=> Merge v0.16.8 into master

pkg/engine/lifecycle_test.go
This test had been intermittently failing due to a race condition. Its
implementation of `plugin.Provider.Read` was intended to ensure that
the cancellation of a refresh operation occurred. As written, it was
only able to ensure that the cancellation was requested.
These changes ensure that cancellation has been acknowledged by the engine by
implementing providing an implementation for `plugin.Provider.Cancel`
that closes a channel on which the implementation of `Read` waits.
=> Fix TestCanceledRefresh

pkg/backend/httpstate/state.go
We continue to do so when `--debug` has been passed, similar to how
these events are elided from the local display when you are not in a
debug context.
=> Do not send "diag" events to the service, by default

pkg/resource/plugin/provider.go
=> Small typo in comment

pkg/testing/integration/program.go
setuptools's "develop" action is not safe to run concurrently when
targeting the same source tree. In order to work around this, this
commit explicitly serializes package installations.
Fixes https://github.com/pulumi/pulumi/issues/2365. I learned a lot today...
=> Serialize package installs in test framework

pkg/resource/asset.go
When constructing an Archive based off a directory path, we would
ignore any symlinks that we saw while walking the file system
collecting files to include in the archive.
A user reported an issue where they were unable to use the
[sharp](https://www.npmjs.com/package/sharp) library from NPM with a
lambda deployed via Pulumi. The problem was that the library includes
native components, and these native components include a bunch of
`*.so` files. As is common, there's a regular file with a name like
`foo.so.1.2.3` and then symlinks to that file with the names
`foo.so.1.2`, `foo.so.1` and `foo.so`. Consumers of these SOs will
try to load the shorter names, i.e. `foo.so` and expect the symlink to
resolve to the actual library.
When these links are not present, upstack code fails to load. …
=> Include symlink'd regular files in directory archives

CHANGELOG.md, sdk/nodejs/runtime/invoke.ts
InvokeRequest is defined in provider_pb.js not resource_pb.js. Require
that module instead.
=> Ensure InvokeRequest is defined

examples/dynamic-provider/class-with-comments/.gitignore, examples/dynamic-provider/class-with-comments/Pulumi.yaml, examples/dynamic-provider/class-with-comments/index.ts, examples/dynamic-provider/class-with-comments/package.json, examples/examples_test.go, sdk/nodejs/runtime/closure/parseFunction.ts, sdk/nodejs/tslint.json
Fixes https://github.com/pulumi/pulumi/issues/2428
=> Fix issue with comments throwing off function/class serialization

CHANGELOG.md, sdk/nodejs/runtime/resource.ts, sdk/nodejs/tests/runtime/langhost/cases/021.parent_child_dependencies/index.js, sdk/nodejs/tests/runtime/langhost/run.spec.ts
Fixes https://github.com/pulumi/pulumi/issues/2470
=>  Fix deadlock when waiting for transitive dependencies 

sdk/nodejs/output.ts, sdk/nodejs/runtime/closure/createClosure.ts, sdk/nodejs/runtime/resource.ts, sdk/nodejs/runtime/rpc.ts, sdk/nodejs/tests/output.spec.ts
This has side-by-side issues in downstream CI, necessitating a more involved roll-out strategy.
=> Rolling back toString/toJSON change

sdk/nodejs/asset/archive.ts, sdk/nodejs/asset/asset.ts, sdk/nodejs/errors.ts, sdk/nodejs/output.ts, sdk/nodejs/resource.ts, sdk/nodejs/runtime/closure/createClosure.ts, sdk/nodejs/tsconfig.json, sdk/nodejs/utils.ts
This is a precursor to https://github.com/pulumi/pulumi/pull/2353 (where we proxy member lookups on an output).
Isolating out to make the rest of hte PR easier to review.
=> Implement rtti checks more consistently

CHANGELOG.md, Gopkg.lock, sdk/nodejs/cmd/pulumi-language-nodejs/main.go
Fixes https://github.com/pulumi/pulumi/issues/2501
Message looks like this:
=> Do a version check and emit a warning if major/minor versions of @pulumi/pulumi do not match.

cmd/pulumi.go
Noticed that I'd missed this right after merging.
=> Hook up stderr when running brew command

sdk/nodejs/config.ts
See attached image for an example of the impact:
This enables exhaustiveness checking in switch statements, code completion and inference on checking the return value, etc.
If `allowedValues` is a `string[]`, then the constraint `K` resolves to `string`. Should be backwards compatible.
I signed off this commit as a DCO and would be willing to sign a CLA.
=> Support string literal bounds and return types on Config#get and Config#require

pkg/diag/errors.go, pkg/resource/deploy/plan_executor.go, pkg/resource/deploy/step_generator.go
Followup to https://github.com/pulumi/pulumi/pull/2572
=> Use result.Result pattern in more places.

pkg/diag/errors.go, pkg/resource/deploy/plan_executor.go, pkg/resource/deploy/step_generator.go
This reverts commit 99496afcfd993f50153b2776dc3086beffa7f27b.
=> Revert "Use result.Result pattern in more places. (#2573)"

CHANGELOG.md, sdk/nodejs/Makefile, sdk/nodejs/runtime/closure/createClosure.ts, sdk/nodejs/tests/runtime/jsClosureCases_10_4.js, sdk/nodejs/tests/runtime/jsClosureCases_8.js, sdk/nodejs/tests/runtime/tsClosureCases.ts
Fixes https://github.com/pulumi/pulumi/issues/2115
=> Add support for serializing bigints

CHANGELOG.md, sdk/nodejs/runtime/closure/parseFunction.ts, sdk/nodejs/tests/runtime/tsClosureCases.ts
Fixes https://github.com/pulumi/pulumi/issues/2544
=> Fix issue where we could not serialize an arrow-function with a deconstructed parameter.

sdk/nodejs/runtime/closure/parseFunction.ts
Fixes https://github.com/pulumi/pulumi/issues/2530
=> Be resilient to 3rd party libraries placing an __awaiter function on the global object.

Makefile, sdk/nodejs/runtime/resource.ts, sdk/nodejs/tests/runtime/langhost/cases/043.depends_on_non_resource/index.js, sdk/nodejs/tests/runtime/langhost/run.spec.ts, sdk/python/lib/pulumi/resource.py, sdk/python/lib/pulumi/runtime/resource.py, sdk/python/lib/test/langhost/invalid_property_dependency/__init__.py, sdk/python/lib/test/langhost/invalid_property_dependency/__main__.py, sdk/python/lib/test/langhost/invalid_property_dependency/test_invalid_property_dependency.py
Fixes https://github.com/pulumi/pulumi/issues/2462
=> Ensure that the values in 'dependsOn' are actually Resources.

tests/integration/integration_test.go
This fixes a nightly test failure that only occurs on Node.js 11,
due to the JSON output including a diagnostics message the Node.js
runtime prints to stderr during the test run.
=> Ignore spurious warning on Node.js 11

CHANGELOG.md, examples/examples_test.go, pkg/backend/filestate/backend.go, pkg/testing/integration/program.go
Fixes https://github.com/pulumi/pulumi/issues/2693
=> Fix local file:// stacks on Windows.

CHANGELOG.md
Be consistent with previous date formats (and use a format that's less ambiguous).
=> ~CHANGELOG: Change date format of recent release

README.md
Easier on the eyes this way IMO
=> Make the timer demo more concise

CHANGELOG.md, cmd/login.go, pkg/backend/filestate/backend.go, pkg/backend/filestate/bucket.go, pkg/backend/filestate/state.go
Fixes https://github.com/pulumi/pulumi/issues/2693
=> Always normalize paths to forward slashes to properly work with gocloud

CHANGELOG.md
Was merged into the 17.11 changelog
=> Move windows path fix changelog entry to 17.13

cmd/util.go, pkg/backend/updates.go
Also, don't set the values using those keys in the environment metadata bag anymore.
=> Remove the GitHubLogin and GitHubRepo update metadata keys

sdk/nodejs/package.json
See https://docs.npmjs.com/files/package.json#repository for guidence
from NPM on how to do this.
Replaces https://github.com/pulumi/pulumi/pull/2565.
=> Fix `repository` section of `package.json`

sdk/python/lib/test/langhost/util.py
Accidentally added in the last PR.
=> Remove logging code

CHANGELOG.md, pkg/util/cmdutil/console.go
=> Don't print emojis in non-interactive mode

CHANGELOG.md, sdk/nodejs/runtime/stack.ts
Fixes https://github.com/pulumi/pulumi/issues/2910
=> Support the exported value of a stack being a Promise/Output itself

pkg/apitype/policy.go
Putting this here as the CLI will use the `/latest` endpoint to get the policy pack for diffs
=> add GetPolicyPackResponse

sdk/python/lib/pulumi/dynamic/dynamic.py
=> Restore the old pickler in a `try/finally`

sdk/nodejs/cmd/run-policy-pack/index.ts, sdk/nodejs/cmd/run-policy-pack/run.ts
=> Remove unnecessary exports

CHANGELOG.md
Continuation of https://github.com/pulumi/pulumi/pull/2958 with additional CHANGELOG fixes.
=> changelog: fix header for 0.17.24 release

CHANGELOG.md, sdk/python/.pylintrc, sdk/python/lib/pulumi/config.py
=> Add get_object functions to Python SDK

CHANGELOG.md
Link to correct bug for custom timeouts entry.
=> Fix bug link in changelog.

pkg/backend/display/progress.go, pkg/resource/deploy/plan_executor.go, pkg/resource/deploy/step_generator.go
See commit messages for more information.
Fixes pulumi/pulumi-policy#25.
Fixes pulumi/pulumi-policy#31.
=> Fix various policy reporting issues

pkg/backend/httpstate/client/client.go
=> Signal policy publish operation completion to the service

README.md
Tactical improvement to make the getting started experience easier to find from the project homepage.
=> Highlight the Get Started guide in the README

cmd/destroy.go, cmd/new.go, cmd/plugin.go, cmd/policy_publish.go, cmd/preview.go, cmd/query.go, cmd/refresh.go, cmd/up.go, cmd/util.go, pkg/resource/plugin/analyzer_plugin.go, sdk/nodejs/dist/pulumi-analyzer-policy
Fixes pulumi/pulumi-policy#36.
Fixes pulumi/pulumi-policy#37.
=> Improve "project not found" error messages

pkg/backend/httpstate/client/client.go
Companion to the breaking change at pulumi/pulumi-service#3842.
Don't merge this until the breaking change mentioned goes to prod today.
=> Use S3 URL for policy pack download

CHANGELOG.md, sdk/nodejs/runtime/invoke.ts
- Report all failures
- Use appropriate member functions to access failure details
Fixes https://github.com/pulumi/pulumi-terraform/issues/396
=> Fix invoke error reporting.

pkg/util/ciutil/detect.go, pkg/util/ciutil/jenkins.go
=> Add support for detecting Jenkins CI env vars.

sdk/python/lib/setup.py
Fixes https://github.com/pulumi/pulumi/issues/2888
=> Do not include 'test' package in our python library.

CHANGELOG.md, pkg/util/buildutil/semver.go, scripts/get-version, scripts/publish_packages.sh
- Update scripts/get-version and friends to understand the new -alpha
and -beta tags
- Update the CHANGELOG
=> Prepare for the v1.0.0-beta.1 release.

pkg/resource/deploy/builtins.go, sdk/nodejs/stackReference.ts, sdk/python/lib/pulumi/stack_reference.py
Address post commit feedback from Cyrus on
pulumi/pulumi#3071
=> Respond to PR feedback

cmd/new.go, cmd/stack_init.go, cmd/up.go
=> Add CLI docs on --secrets-provider

CHANGELOG.md, pkg/util/logging/log.go, pkg/util/logging/log_test.go
=> Skip non-utf8 secrets when regexing logs

cmd/new.go, cmd/stack_init.go, cmd/util.go, pkg/backend/backend.go, pkg/backend/backend_test.go, pkg/backend/filestate/backend.go, pkg/backend/httpstate/backend.go, pkg/backend/httpstate/policypack.go
Part of https://github.com/pulumi/pulumi/issues/2421#issuecomment-519949416
=> Add a hint about the org name in stack in pulumi new

pkg/testing/integration/program.go
This will allow us to install a latest version from PyPi or NPM
and then yarn link / pip install from local machine and test that
no changes are introduced when this occurs
If the flag is not passed, then the dependencies are installed
as before where we prefer a local package to be linked / installed
Linked to #2757
=> Allow Acceptance Tests to pass a flag that runs an upgrade test

cmd/destroy.go
=> Add a hint about stack rm after successful destroy

cmd/plugin_install.go, pkg/engine/plugins.go, pkg/workspace/plugins.go
=> Show a progress bar for plugin installation during pulumi up

pkg/testing/integration/program.go
This matches what we tell our customers to do and makes some
downstream testing stuff for beta versions of our python packages
easier (since `pip` has a more straightforward package selection
algorithm than `pipenv`)
=> Use pip and not pipenv for installing dependencies during testing

cmd/preview.go, cmd/up.go
Fixes https://github.com/pulumi/pulumi-policy/issues/89.
=> Requite debug env var for --policy-pack

pkg/workspace/plugins.go
When installing plugins, we download the plugin into a temporary
folder, unpack it and then move that folder into its final
location (as an atomic operation). We do this so that if the download
fails in some way, we would not "poision" our plugin cache.
In order to ensure the move into the final location happens
atomically, we download the plugin into a folder with a `.tmpXXXXXX`
suffix inside the plugin root itself.  However, we were not ignoring
this folder when enumarating plugins. This would cause some weird
behaviors:
- When a plugin was being installed `pulumi plugin ls` would show a
plugin with a version like `v1.0.0-rc.1.tmp123456`.
- For cases where the version of the plugin had applied
metadata (e.g. our alpha builds where we append the commit hash to the
version via …
=> Ignore plugins which are being installed

sdk/nodejs/tests/runtime/langhost/run.spec.ts
Fixes https://github.com/pulumi/pulumi/issues/2472
=> Reenable test.

CHANGELOG.md, pkg/util/gitutil/git.go, pkg/util/gitutil/git_test.go
Resolves https://github.com/pulumi/customer-support/issues/31
=> Fix parsing of Gitlab urls w subgroups

sdk/python/lib/pulumi/resource.py
Fixes https://github.com/pulumi/pulumi/issues/3235
=> Coerce dictionary values to a list.

CHANGELOG.md, pkg/util/ciutil/codefresh.go, pkg/util/ciutil/detect.go, pkg/util/ciutil/systems.go, pkg/util/ciutil/vars_test.go
Related to #2106.
This is a mirror of the PR (#3247) raised by @fernandocarletti to add the Codefresh CI detection.
=> Add codefresh CI detection. Thanks to @fernandocarletti.

CHANGELOG.md, cmd/preview.go, cmd/up.go, cmd/util.go
=> Add the config array option to the preview command.

pkg/apitype/events.go, pkg/backend/display/diff.go, pkg/backend/display/events.go, pkg/backend/display/progress.go, pkg/backend/display/rows.go, pkg/backend/display/tableutil.go, pkg/engine/events.go, pkg/engine/plan.go, pkg/engine/update.go
Fixes pulumi/pulumi-policy#69.
=> Print PolicyPacks run as part of update summary

.travis.yml, scripts/update_homebrew.sh
This script will run during OS X legs, and will open a PR to update the
Homebrew formula for Pulumi on each new release.
=> Add scripting for updating the Homebrew formula.

sdk/nodejs/tests/runtime/langhost/run.spec.ts
Test only change.  But if you do want to review, disable whitespace.
=> Enable some tests that weren't actually running

sdk/nodejs/resource.ts, sdk/nodejs/runtime/invoke.ts
This restores the original code we have here: https://github.com/pulumi/pulumi/pull/3325/files#diff-7c07ef8b295270abd0172faa87391648L54
which i refactored improperly.
Also removed the upgrade warning.
Fixes #3358.
=> Properly handle providers with unknown Ids

pkg/engine/lifecycle_test.go, pkg/resource/deploy/step_generator.go
Fixes https://github.com/pulumi/pulumi/issues/3365
=> Fix crash when specifying update-target that doesn't exist.

Makefile, build/common.mk, pkg/testing/integration/program.go, scripts/get-version, scripts/make_release.sh, scripts/publish_packages.sh, sdk/dotnet/Makefile, sdk/go/Makefile, sdk/nodejs/Makefile
WIP: easier to review with whitespace changes off.
=> Add publishing to nuget support

CHANGELOG.md, cmd/stack.go
=> Print a tree view in `pulumi stack`.

cmd/stack_graph.go, pkg/graph/dotconv/print.go
- Add a note to the usage about the output file
- Label dependency edges with property names
Fixes #1840.
=> Improve `stack graph`.

CONTRIBUTING.md
Documenting a few implicit dependencies. This was enough to get up and running, but if there are better ways to accomplish this please let me know.
=> Document implicit dependencies in Contributing.md

sdk/dotnet/Makefile
Instead of 1.5.0-preview-, produce 1.5.0-preview.
=> Remove the hanging '-' from .NET versions.

sdk/dotnet/Pulumi.FSharp/Library.fs
Some helper functions to make the existing example simpler and more idiomatic
See https://github.com/pulumi/examples/pull/445/files#diff-e31ba349f65ba4ebf1edd90425272687 for usage examples
=> F# helpers

sdk/dotnet/Pulumi.Tests/Core/InputMapTests.cs, sdk/dotnet/Pulumi/Core/InputMap.cs, sdk/dotnet/Pulumi/PublicAPI.Unshipped.txt
One target scenario is to combine app settings from a reusable component and its arguments
=> Method to merge input maps

CHANGELOG.md, pkg/engine/lifecycle_test.go, sdk/go/pulumi/context.go, sdk/go/pulumi/resource.go
https://github.com/pulumi/pulumi/issues/3489
Includes tests to verify that the option is passed through.
=> Add support to the go sdk for IgnoreChanges

sdk/nodejs/tests/runtime/langhost/cases/060.provider_invokes/index.js, sdk/nodejs/tests/runtime/langhost/cases/061.provider_in_parent_invokes/index.js
=> Skip tests that hang on Node 12.11.x+

sdk/dotnet/Pulumi.Tests/Serialization/InternalPropertyTests.cs, sdk/dotnet/Pulumi/Serialization/Deserializer.cs
Fixes https://github.com/pulumi/examples/issues/476
=> Filter out internal properties when deserializing data

CHANGELOG.md, pkg/engine/lifecycle_test.go, sdk/go/pulumi/context.go
Fixes https://github.com/pulumi/pulumi/issues/1530
=> Fix go SDK ReadResource

sdk/dotnet/Pulumi/Log.cs, sdk/dotnet/Pulumi/PublicAPI.Unshipped.txt
A tiny convenience method.
@CyrusNajmabadi What does `ephemeral` mean in the context of errors?
=> Helper method to log an exception in .NET

sdk/nodejs/Makefile, sdk/nodejs/config.ts, sdk/nodejs/output.ts, sdk/nodejs/runtime/resource.ts, sdk/nodejs/runtime/rpc.ts, sdk/nodejs/stackReference.ts, sdk/nodejs/tests/output.spec.ts, sdk/nodejs/tests/unwrap.spec.ts, sdk/nodejs/utils.ts
Followup to https://github.com/pulumi/pulumi/pull/3663 after we discoverd a sxs issue there.
=>  Support sxs with old outputs with sync resources only. 

sdk/python/cmd/pulumi-language-python/main.go
=> Fallback to looking for `python` when launching Python language host

CHANGELOG.md, sdk/dotnet/Pulumi.Tests/StackTests.cs, sdk/dotnet/Pulumi/AssemblyAttributes.cs, sdk/dotnet/Pulumi/Deployment/Deployment.Runner.cs, sdk/dotnet/Pulumi/Deployment/Deployment_RootResource.cs, sdk/dotnet/Pulumi/Deployment/Deployment_Run.cs, sdk/dotnet/Pulumi/Deployment/IDeploymentInternal.cs, sdk/dotnet/Pulumi/Deployment/IRunner.cs, sdk/dotnet/Pulumi/PublicAPI.Unshipped.txt, sdk/dotnet/Pulumi/Serialization/Attributes.cs, sdk/dotnet/Pulumi/Serialization/OutputCompletionSource.cs, sdk/dotnet/Pulumi/Stack.cs, tests/integration/integration_test.go, tests/integration/stack_component/dotnet/.gitignore, tests/integration/stack_component/dotnet/Program.cs, tests/integration/stack_component/dotnet/Pulumi.yaml, tests/integration/stack_component/dotnet/StackComponent.csproj
Resolves #3619. Async scenarios need to be handled ad-hoc for now (happen inside an `Apply`).
=> First-class Stack component for .NET

CHANGELOG.md, sdk/nodejs/package.json
Fixes https://github.com/pulumi/pulumi/issues/3732
=> Lock dep ts-node to v8.5.4

sdk/nodejs/dynamic/index.ts, sdk/proto/provider.proto, sdk/python/lib/pulumi/dynamic/dynamic.py
I _believe_ these are all the places that need to be changed. There are other occurrences of this, but they're in files that say "DO NOT EDIT".
=> Fixed 'transacational' misspelling.

CHANGELOG.md
=> update changelog for #3704

pkg/resource/plugin/plugin.go
WIP.  Trying things out downstream.
=> Handle all errors for now.

sdk/go/pulumi/printf_test.go
=> Add coverage for pulumi.Fprintf.

pkg/backend/snapshot.go, tests/integration/targets/targets_test.go, tests/integration/targets/untargeted_create/Pulumi.yaml, tests/integration/targets/untargeted_create/index.ts, tests/integration/targets/untargeted_create/package.json, tests/integration/targets/untargeted_create/step1/index.ts
Fixes https://github.com/pulumi/pulumi/issues/3790
=> Ensure that resources not specified by --target do not get added to checkpoint file.

.appveyor.yml, build.proj, examples/examples_test.go, pkg/engine/project.go, pkg/testing/integration/program.go, tests/integration/aliases/aliases_test.go, tests/integration/config_capture_e2e/nodejs/index.ts, tests/integration/integration_test.go, tests/integration/transformations/transformations_test.go
Fixes: https://github.com/pulumi/home/issues/583
To-Do:
=> Running our pulumi/pulumi examples on Windows

pkg/codegen/dotnet/gen.go, pkg/codegen/nodejs/gen.go, pkg/codegen/schema/schema.go
This is the schema-based version of
https://github.com/pulumi/pulumi-terraform-bridge/pull/96.
=> Add schema support for deprecated properties.

CHANGELOG.md, sdk/go/pulumi/alias.go, sdk/go/pulumi/context.go, sdk/go/pulumi/resource.go, sdk/go/pulumi/rpc_test.go, tests/integration/aliases/aliases_test.go, tests/integration/aliases/go/adopt_into_component/step1/Pulumi.yaml, tests/integration/aliases/go/adopt_into_component/step1/main.go, tests/integration/aliases/go/adopt_into_component/step2/main.go, tests/integration/aliases/go/rename/step1/Pulumi.yaml, tests/integration/aliases/go/rename/step1/main.go, tests/integration/aliases/go/rename/step2/main.go, tests/integration/aliases/go/rename_component/step1/Pulumi.yaml, tests/integration/aliases/go/rename_component/step1/main.go, tests/integration/aliases/go/rename_component/step2/main.go, tests/integration/aliases/go/rename_component_and_child/step1/Pulumi.yaml, tests/integration/aliases/go/rename_component_and_child/step1/main.go, tests/integration/aliases/go/rename_component_and_child/step2/main.go, tests/integration/aliases/go/retype_component/step1/Pulumi.yaml, tests/integration/aliases/go/retype_component/step1/main.go, tests/integration/aliases/go/retype_component/step2/main.go
Fixes https://github.com/pulumi/pulumi/issues/2924
I will add integration tests for the rest of the scenarios (component, retype, etc) shortly, but this is ready for a look now.
=> Go aliases

pkg/resource/plugin/provider_plugin.go
https://github.com/pulumi/pulumi-azure/issues/461
cc @stack72
=> Marshal non-string provider config

go.mod, go.sum, pkg/codegen/docs/gen.go, pkg/codegen/docs/gen_test.go
Many TODOs and follow-ups remain, but this is the start of our schema-based docs generation.
=> Initial schema-based docs gen

pkg/resource/plugin/analyzer_plugin.go, pkg/resource/plugin/plugin.go
Improve an error message when trying to load a policy pack that isn't found.
Currently, the error is accurate... but unwieldy:
``` 
error: policy pack "/Users/chris/go/src/github.com/pulumi/pulumi-service/examples/resources/does/not/exist" failed to start: failed to load plugin /Users/chris/.pulumi/bin/pulumi-analyzer-policy: fork/exec /Users/chris/.pulumi/bin/pulumi-analyzer-policy: no such file or directory
```
With this change, we look for the `syscall.ENOENT` error and just provide a shorter message:
```
error: policy pack plugin not found at "/Users/chris/go/src/github.com/pulumi/pulumi-service/examples/resources/does/not/exist"
```
... to be honest though, I honestly don't know why we are seeing this error in the first place.
From the Golang code, `cmd.Start()` is documented as …
=> Improve error message for policy pack not found

CHANGELOG.md, cmd/policy.go, cmd/policy_disable.go, cmd/policy_enable.go, cmd/policy_group_ls.go, cmd/policy_ls.go, cmd/policy_new.go, cmd/policy_publish.go, cmd/policy_rm.go, cmd/preview.go, cmd/pulumi.go, cmd/up.go, cmd/watch.go
Fixes #3985
@ekrengel, I don't think there's any reason to hold back on this, but let me know if you think we should wait until any more of this milestone's work has landed.
=> Don't mark policy and watch commands as experimental

CHANGELOG.md, sdk/dotnet/Pulumi/Serialization/Converter.cs
=> Relax the type check to accomodate what YAML parser returns

CHANGELOG.md, pkg/workspace/templates.go, pkg/workspace/templates_test.go
Fixes: #4013
Without this, we are in a situation where we have a cyclic import
=> Stop new projects starting with the word Pulumi

CHANGELOG.md, pkg/codegen/go/gen.go, sdk/go/pulumi-language-go/main.go, sdk/go/pulumi/run.go
=> Revert "WIP: GetRequiredPlugins for Go"

CHANGELOG.md, cmd/login.go
Related https://github.com/pulumi/pulumi/issues/3194
=> Improve documentation of URL formats for `pulumi login`

CHANGELOG.md, sdk/dotnet/Pulumi/PublicAPI.Unshipped.txt, sdk/dotnet/Pulumi/Resources/StackOptions.cs, sdk/dotnet/Pulumi/Stack.cs, tests/integration/transformations/dotnet/simple/.gitignore, tests/integration/transformations/dotnet/simple/Program.cs, tests/integration/transformations/dotnet/simple/Pulumi.yaml, tests/integration/transformations/dotnet/simple/Transformations.csproj, tests/integration/transformations/transformations_test.go
Resolves #3870
Depends on the `Pulumi.Random` provider which is used in integration tests.
=> Add Stack Transformations to .NET SDK

CHANGELOG.md, dist/pulumi/Dockerfile
=> Test PR 3893

pkg/codegen/go/gen.go
- Add GoInfo struct to improve control of package imports and names
- Fix import recursion bug
- Add support for aliased imports
=> Update Go SDK generator to support k8s

pkg/codegen/go/gen.go
=> Fix Go generation

CHANGELOG.md, sdk/go/pulumi/generate.go, sdk/go/pulumi/types_builtins.go, sdk/go/pulumi/types_builtins_test.go
fixes https://github.com/pulumi/pulumi/issues/4135
=> Add missing builtin MapArray to the Go SDK

.travis.yml, CHANGELOG.md
=> Stop testing on Node 8, start testing on Node 13

sdk/nodejs/cmd/pulumi-language-nodejs/main.go
=> Allow pulumi/pulumi 1.x and 2.x to be used SxS

sdk/go/pulumi/log.go
=> Fix Go Logging Bug

scripts/get-version, scripts/get-version.ps1
Fixes https://github.com/pulumi/pulumi/issues/4227
=> update get-version to understand submodule tags

CHANGELOG.md, dist/actions/entrypoint.sh
The original motivation for this came from #4223. I am opening this PR to facilitate running the PR build.
=> Update the GitHub Actions container to allow users to pass a cloud url

pkg/codegen/docs/gen.go, pkg/codegen/docs/templates/resource.tmpl, pkg/codegen/go/gen.go, pkg/codegen/schema/schema.go, sdk/go.sum
Part of https://github.com/pulumi/home/issues/734.
=> Add package details and atttribution to schema

CHANGELOG.md, sdk/go/pulumi/types.go, sdk/go/pulumi/types_test.go
=> [Go] Ensure Apply handles `nil` output values

pkg/cmd/policy.go, pkg/cmd/policy_disable.go, pkg/cmd/policy_enable.go, pkg/cmd/policy_group_ls.go, pkg/cmd/policy_ls.go, pkg/cmd/policy_new.go, pkg/cmd/policy_publish.go, pkg/cmd/policy_rm.go, pkg/cmd/policy_validate.go, pkg/cmd/preview.go, pkg/cmd/up.go, pkg/cmd/watch.go
=> Remove [PREVIEW] from policy commands

pkg/codegen/hcl2/model/attribute.go, pkg/codegen/hcl2/model/binder_expression.go, pkg/codegen/hcl2/model/binder_expression_test.go, pkg/codegen/hcl2/model/block.go, pkg/codegen/hcl2/model/body.go, pkg/codegen/hcl2/model/expression.go, pkg/codegen/hcl2/model/printer.go, pkg/codegen/hcl2/model/type_opaque.go, pkg/codegen/hcl2/model/type_scope.go, pkg/codegen/hcl2/model/utilities.go, pkg/codegen/hcl2/model/visitor.go
- Improve support for printing and triva
- Add support for HCL2 type functions
- Add visitors for body items
=> Various updates to the HCL2 semantic model.

pkg/codegen/nodejs/gen_intrinsics.go, pkg/codegen/nodejs/gen_program.go, pkg/codegen/nodejs/gen_program_expressions.go, pkg/codegen/nodejs/gen_program_lower.go, pkg/codegen/nodejs/utilities.go
This code generator processes a bound Pulumi program represented using
an HCL2-based IR and converts it to an equivalent NodeJS program.
=> Add a code generator for NodeJS programs.

pkg/codegen/python/gen_intrinsics.go, pkg/codegen/python/gen_program.go, pkg/codegen/python/gen_program_expressions.go, pkg/codegen/python/gen_program_lower.go, pkg/codegen/python/utilities.go
This code generator processes a bound Pulumi program represented using
an HCL2-based IR and converts it to an equivalent Python program.
=> Add a code generator for Python programs.

pkg/cmd/pulumi.go
=> Only show the update version warning message in interactive mode

dist/pulumi/Dockerfile
=> feat: use node 12 in docker image

pkg/codegen/docs/gen.go
Group required properties for resource at top of properties list.
https://github.com/pulumi/docs/issues/2870
=> Group required properties at top of properties list

pkg/codegen/hcl2/model/attribute.go, pkg/codegen/hcl2/model/binder_expression.go, pkg/codegen/hcl2/model/block.go, pkg/codegen/hcl2/model/body.go, pkg/codegen/hcl2/model/expression.go, pkg/codegen/hcl2/model/printer.go, pkg/codegen/hcl2/syntax/comments.go, pkg/codegen/hcl2/syntax/comments_test.go, pkg/codegen/hcl2/syntax/testdata/comments_all.hcl, pkg/codegen/hcl2/syntax/tokens.go
And improve test coverage for the same.
=> Fix treatment of trivia in template expressions.

pkg/codegen/hcl2/model/attribute.go, pkg/codegen/hcl2/model/binder_expression.go, pkg/codegen/hcl2/model/binder_expression_test.go, pkg/codegen/hcl2/model/block.go, pkg/codegen/hcl2/model/expression.go, pkg/codegen/hcl2/syntax/comments.go, pkg/codegen/hcl2/syntax/comments_test.go, pkg/codegen/hcl2/syntax/testdata/comments_all.hcl, pkg/codegen/hcl2/syntax/tokens.go
- Parentheses were not handled properly
- Literals inside of template control sequences were not handled
properly
These changes also improve test coverage for the printers.
=> Fix various printing issues.

pkg/codegen/docs.go, pkg/codegen/docs/gen.go, pkg/codegen/docs/gen_function.go, pkg/codegen/dotnet/doc.go, pkg/codegen/dotnet/doc_test.go, pkg/codegen/go/doc.go, pkg/codegen/nodejs/doc.go, pkg/codegen/nodejs/doc_test.go, pkg/codegen/python/doc.go
Related: https://github.com/pulumi/docs/pull/2889
=> [codegen] Generate correct links to v>=2 of Go packages

pkg/codegen/dotnet/gen.go
=> Use Config.Get for string-based token types in .NET code gen

pkg/codegen/hcl2/binder.go, pkg/codegen/hcl2/binder_nodes.go, pkg/codegen/hcl2/binder_resource.go, pkg/codegen/hcl2/model/attribute.go, pkg/codegen/hcl2/model/binder_expression.go, pkg/codegen/hcl2/model/block.go, pkg/codegen/hcl2/model/body.go, pkg/codegen/hcl2/model/traversable.go, pkg/codegen/hcl2/model/type_union.go, pkg/codegen/python/gen_program_lower.go
When this tolerance is enabled, diagnostics will not be emitted for
missing variables.
=> HCL2: support for tolerating missing variables.

pkg/codegen/docs/gen.go, pkg/codegen/docs/templates/package_details.tmpl
Issue: https://github.com/pulumi/docs/issues/2984
=> Add version to package details

pkg/codegen/docs/templates/resource.tmpl
Issue: https://github.com/pulumi/docs/issues/2963
Polish up the experience around inputs and outputs properties.
=> Polish input and output props

CHANGELOG.md, pkg/cmd/pulumi/state_unprotect.go
=> Protect against panic when unprotecting state with no resources

tests/containers/containers_test.go
I fixed this locally when creating the new docker containers so it's
time to push this back to master
=> Ensure yes is passed when creating a new template in a container

pkg/codegen/schema/schema.go
A change required for https://github.com/pulumi/pulumi-terraform-bridge/issues/169
=> C# name resolution

pkg/codegen/hcl2/rewriters.go
This will make some incoming fixes that address nested applies easier to
write and understand.
=> Apply rewriter: separate global and expr data

pkg/codegen/hcl2/binder.go, pkg/codegen/hcl2/binder_schema.go, pkg/codegen/hcl2/functions.go, pkg/codegen/hcl2/model/diagnostics.go, pkg/codegen/hcl2/model/expression.go
- Load packages referenced by all node types, not just resource nodes
- Fix trivia detection
=> [hcl2] Fix package loading and trivia detection

pkg/codegen/nodejs/gen.go, pkg/codegen/nodejs/importer.go
This is a backport of https://github.com/pulumi/pulumi-terraform-bridge/pull/185
=> Add support for NPM Resolutions to nodejs codegen

pkg/codegen/hcl2/binder_resource.go, pkg/codegen/hcl2/model/expression.go, pkg/codegen/hcl2/model/utilities.go, pkg/codegen/internal/test/testdata/aws-eks.pp, pkg/codegen/internal/test/testdata/aws-eks.pp.py, pkg/codegen/internal/test/testdata/aws-eks.pp.ts, pkg/codegen/internal/test/testdata/aws-s3-folder.pp.ts, pkg/codegen/nodejs/gen_program.go, pkg/codegen/nodejs/gen_program_expressions.go, pkg/codegen/python/gen_program.go, pkg/codegen/python/gen_program_quotes.go, pkg/codegen/python/gen_program_quotes_test.go, pkg/codegen/python/utilities_test.go
- Determine variable types for ranged resources by typechecking an
equivalent expression
- Detect top-level await in NodeJS and generate an async main
- Fix `pulumi.all` generation for NodeJS
=> [codegen/*] Improve range type binding + codegen.

sdk/nodejs/tests/unwrap.spec.ts
=> Avoid TS compiler error

pkg/codegen/docs/gen.go, pkg/codegen/docs/gen_kubernetes.go
Related to https://github.com/pulumi/docs/issues/3219.
The docs PR https://github.com/pulumi/docs/pull/3223 has the preview of the changes to the links with these fixes.
=> [codegen/docs] Fix kubernetes resource docs links for overlay resources

pkg/testing/integration/program.go
Fixes: #4585
This was happening by default in the test framework and then again
in the go language runtime
Also we were replacing a module and then running go mod tidy - this
is unnecessary - go mod download is sufficient here to ensure we
have the correct dependency we need. The tidy may have been removing
the replacements added
=> Ensure Go build is an optional step in integration testing framework

tests/containers/containers_test.go
Our container runtime tests are currently failing on CI on Linux because they mount a volume (e.g. folder in temp directory) into a docker image and then start it. The container then proceeds to add new files to that volume (e.g. the built output of the Pulumi program).
This is preventing the test cases from cleaning up correctly, because by default Docker runs the container as user id 0 or root. Which means that the current user doesn't actually have permissions to delete those temp directories created. (And instead we get `unlike at: ... : permission denied`. errors.)
> Note that this doesn't happen on macOS, or at least I am able to run these tests locally without any issues.
I've tried several approaches for working around this, but nothing seems to work. (The most promising approach …
=> Ignore test issue in container runtime tests

CHANGELOG.md
=> Add missing CHANGELOG due to v2.1.1 patch release

dist/actions/Dockerfile
Fixes: #4457
This is required since 2.0
=> Pass yes as a parameter to the actions entrypoint

dist/actions/entrypoint.sh
=> Run npm ci if lock or shrinkwrap file found

Makefile, build/common.mk, sdk/dotnet/Makefile, sdk/go/Makefile, sdk/nodejs/Makefile, sdk/python/Makefile
This is necessary for the Homebrew build.
=> Add a brew target.

pkg/codegen/go/gen_program.go, pkg/codegen/go/gen_program_test.go, pkg/codegen/internal/test/testdata/aws-s3-logging.pp.go
This sets up all of the boilerplate for `gen_program` and the relevant testing for go.
Nothing fancy yet, just generating a scaffold program "by hand". Should be faster going forward now that I have my head wrapped around what is required. 
There isn't much to review in this PR, but opening now in the spirit of splitting this into smaller chunks. Happy to alter that if this granularity is too fine.
=> go gen_program shell + test + sample

tests/integration/integration_test.go
Currently we only test the secrets provider for AWS. This adds an
integration test for Azure & GCP
Fixes #3761
=> Add integration tests for gcp and azure

pkg/codegen/docs/gen.go, pkg/codegen/docs/templates/constructor_params.tmpl, pkg/codegen/docs/templates/resource.tmpl, pkg/codegen/docs/templates/utils.tmpl, pkg/codegen/python/doc.go
Issue: https://github.com/pulumi/docs/issues/3179
=> Link Python and Go constructors

sdk/dotnet/Pulumi.Tests/AssertEx.cs, sdk/dotnet/Pulumi/Serialization/Converter.cs
new version of dotnet is getting picked up in CI
=> fix dotnet error

pkg/cmd/pulumi/config.go, pkg/cmd/pulumi/pulumi.go, pkg/cmd/pulumi/state_delete.go
Fixes https://github.com/pulumi/docs/issues/3372
=> Fix single-quote examples in command help

pkg/codegen/dotnet/gen_program.go, pkg/codegen/dotnet/utilities.go
I've been running my [example compilation tool](https://github.com/mikhailshilkov/compile-csharp-examples) through more repositories (AWS, Azure, AzureAD, Random, GCP) and fixed a couple of issues that I found.
=> Small bug fixes in C# codegen

pkg/codegen/go/gen_program.go, pkg/codegen/go/gen_program_expression_test.go, pkg/codegen/go/gen_program_expressions.go, pkg/codegen/go/gen_program_ternaries.go
Go doesn't support ternary expressions so we must convert:
```
true ? 1 : 0
```
into a temp variable and assignment within if/else:
```go
var tmp0 float64
if true {
tmp0 = 1
} else {
tmp0 = 0
}
```
Need more conditional test cases for things like assignment within object cons, and nesting, but this seems like enough to review for now.
=> [Go Program Gen] binary, unary, and initial conditional expression support

pkg/cmd/pulumi/login.go
Fixes https://github.com/pulumi/docs/issues/1718
=> Clarify backend login help text

pkg/codegen/nodejs/gen.go, pkg/codegen/nodejs/importer.go
Related to https://github.com/pulumi/pulumi-kubernetes/issues/1053
=> Add k8s compatibility mode for NodeJS codegen

sdk/go/common/workspace/plugins.go
=> Escape the path to ensure we fetch plugins correctly

pkg/codegen/nodejs/gen.go
Follow up on feedback for https://github.com/pulumi/pulumi/pull/4730
Related to pulumi/pulumi-kubernetes#1053
=> Address NodeJS codegen feedback

pkg/codegen/nodejs/gen.go
If the source file for a resource or function definition would collide
with a reserved filename (e.g. `index.ts`), append an underscore to its
filename (e.g. `index_.ts`).
=> [codegen/nodejs/sdk] Do not write reserved files.

pkg/codegen/python/gen.go
=> Ensuring a property level deprecation warning is set for python codegen

pkg/codegen/nodejs/gen.go
If the type of a configuration variable is a token type (i.e. a type
provided by an overlay) with the underlying type string, call
`config.get` rather than `config.getObject`. This fixes a regression in
the `aws.config.region` variable.
=> [codegen/nodejs/sdk] Fix token type config getter.

pkg/codegen/nodejs/gen.go
Related to pulumi/pulumi-kubernetes#1053
=> Fix codegen for schema-based NodeJS SDKs

pkg/codegen/python/gen.go, pkg/codegen/python/gen_program.go, pkg/codegen/python/importer.go
=> [codegen/python] Allow import path overrides

CHANGELOG.md, sdk/go/pulumi/config/config.go, sdk/go/pulumi/config/config_test.go, sdk/go/pulumi/config/get.go, sdk/go/pulumi/config/require.go, sdk/go/pulumi/config/try.go, sdk/go/pulumi/templates/config-config.go.template, sdk/go/pulumi/templates/config-get.go.template, sdk/go/pulumi/templates/config-require.go.template, sdk/go/pulumi/templates/config-try.go.template
Fixes https://github.com/pulumi/pulumi/issues/4664
=> Use appropriate types for go config methods

pkg/codegen/python/gen.go, pkg/codegen/python/gen_test.go
=> [codegen/python] Fix relative import path

pkg/codegen/python/gen.go
=> [codegen/python] - Exclude nested docs for k8s

pkg/codegen/python/gen.go
=> [codegen/python] Handle extra files

sdk/dotnet/Pulumi/Stack.cs, sdk/nodejs/runtime/stack.ts
Related: https://github.com/pulumi/docs/pull/3615
=> Ensuring references to v2 pulumi packages are up to date

pkg/codegen/python/gen.go, pkg/codegen/python/importer.go
PR in pulumi/kubernetes: https://github.com/pulumi/pulumi-kubernetes/pull/1160
=> [codegen/python] Remaining k8s updates

pkg/codegen/python/gen.go
=> [codegen/python] Add missing props to casing table

pkg/codegen/python/gen.go
=> [codegen/python] Allow setting constant values for props

pkg/codegen/go/gen_program_expression_test.go
Until we take care of https://github.com/pulumi/pulumi/issues/4885
=> skip transient test

tests/integration/integration_test.go
=> Skip python tests during investigation

pkg/codegen/python/gen.go
=> [codegen/python] Only add item to map if it doesn't already exist.

pkg/codegen/dotnet/gen.go
Related to https://github.com/pulumi/pulumi-kubernetes/issues/1183
=> [codegen/dotnet] Add LanguageResource for downstream codegen

pkg/codegen/schema/schema.go
=> [codegen] Add Secret field to Property schema

pkg/codegen/dotnet/gen.go, pkg/codegen/go/gen.go, pkg/codegen/nodejs/gen.go, pkg/codegen/python/gen.go
Fix #4941 
Here's what this looks like in the k8s code: https://github.com/pulumi/pulumi-kubernetes/compare/lblackstone/additional-secret-outputs
=> [codegen] Set additionalSecretOutputs for secret props

sdk/go/pulumi/context.go, sdk/go/pulumi/resource.go
=> Adding the ability to specify a version as a ResourceOption

pkg/backend/display/diff.go, pkg/backend/display/display.go, pkg/backend/display/events.go, pkg/backend/display/json.go, pkg/backend/display/progress.go, pkg/backend/display/rows.go, pkg/backend/display/watch.go, pkg/backend/snapshot.go, pkg/engine/diff.go, pkg/engine/events.go, pkg/engine/lifecycle_test.go, pkg/engine/plan.go, pkg/engine/update.go, pkg/resource/deploy/plan.go, pkg/resource/deploy/plan_executor.go, pkg/resource/deploy/source.go, pkg/resource/deploy/source_error.go, pkg/resource/deploy/source_eval.go, pkg/resource/deploy/source_fixed.go, pkg/resource/deploy/source_null.go, pkg/resource/deploy/step.go, pkg/resource/deploy/step_executor.go, pkg/resource/deploy/step_generator.go
Reverts pulumi/pulumi#4934
Fixes: #4986
=> Revert "Narrow a few interfaces."

CHANGELOG.md, dist/actions/entrypoint.sh
Solves #4871
I wasn't able to test it much in deep, but from my simple tests, it seems fine.
Ping @justinvp
PD, this maybe should be an issue itself, but i think there is no CI for the action
=> Add logic to parse pulumi venv

pkg/codegen/python/gen.go
Related: https://github.com/pulumi/pulumi/pull/4948
The tables and utilities modules are only used internally, so adding underscores so they don't show up in consumers' Intellisense.
Before:
After:
=> [codegen/python] Add underscores to private modules to avoid exporting them.

pkg/codegen/docs/templates/resource.tmpl
=> Fix semicolon in python docs

CHANGELOG.md, dist/actions/entrypoint.sh
There was an error in the logic.
This breaks the action if no venv is not defined.
=> Fix logic on venv

CHANGELOG.md, pkg/cmd/pulumi/crypto.go, pkg/cmd/pulumi/crypto_http.go, pkg/cmd/pulumi/stack.go, pkg/cmd/pulumi/stack_change_secrets_provider.go, pkg/cmd/pulumi/util.go
Fixes: #481
https://asciinema.org/a/ftLCUrN0NPMCTFQo83T1VYrGn
=> Add the ability to change secrets provider

CHANGELOG.md, pkg/cmd/pulumi/stack_init.go
=> Add ability to create a stack based on an existing stack

scripts/build-docker.sh
=> Trigger deployment for chocolatey package

pkg/codegen/python/gen.go
One way to fix #5050. Alternatively, we could add `resource_name` to `PyName` as another "keyword" or another special case, I believe that would fix the issue at the level of case mappings.
I'm new to the Python SDK, so I'm totally open to other suggestions.
=> Handle resource_name properties to avoid conflicts in Python codegen

pkg/codegen/internal/test/testdata/kubernetes-pod.pp.py, pkg/codegen/python/gen_program.go
Fixes: https://github.com/pulumi/pulumi/issues/5106
=> [codegen/python] - Fix python resource tokens

pkg/codegen/internal/test/testdata/kubernetes-operator.pp.py, pkg/codegen/python/gen_program.go
=> [codegen/python] - Normalize module names in program gen

CHANGELOG.md, sdk/python/lib/pulumi/dynamic/__main__.py
=> Fix support for CheckFailures in Python Dynamic Providers

sdk/nodejs/tests/unwrap.spec.ts
I believe this will address the TS compiler error that some of us are seeing, but I can't reliably repro it locally, so I don't know for sure.
@jaxxstorm, want to try these changes locally on your machine?
=> Work around TS compiler error

CHANGELOG.md, pkg/backend/apply.go, pkg/backend/display/options.go, pkg/backend/filestate/backend.go, pkg/backend/httpstate/backend.go, pkg/cmd/pulumi/destroy.go, pkg/cmd/pulumi/preview.go, pkg/cmd/pulumi/refresh.go, pkg/cmd/pulumi/up.go, pkg/cmd/pulumi/watch.go, tests/integration/integration_test.go
This reverts commit f8d929d197b3cc5b4a8dbac5bf207587e93fcb2c.
=> Revert "Added --suppress-permalink option (#5177)"

pkg/codegen/go/gen.go, pkg/codegen/go/gen_crd2pulumi.go, pkg/codegen/go/gen_program.go
Came across this while debugging another issue.
=> fix unchecked type assertion

pkg/codegen/python/gen.go
This avoids conflicting with the built-in `@property` decorator function for other properties.
Fixes https://github.com/pulumi/pulumi/issues/5214
=> [codegen/python] Emit properties named "property" last

pkg/codegen/nodejs/gen.go
An extra constructor overload was recently added to pass undefined state from `get` for resources that do not have any state inputs (notably Kubernetes resources). This ended up breaking PaC's `validateResourceOfType`, which relies on type inference in common usage to determine the resource's args type based on the signature of the constructor.
This constructor overload isn't necessary. Instead, we can remove it and modify how the constructor is called inside `get`. This also makes it so we're not exposing details about `get`'s implementation in the public API.
To make it easier to review, [here's the diff](https://github.com/pulumi/pulumi-kubernetes/commit/87274916427e5f309029a8e562a1fe5d9fa5485d) of just these changes for Kubernetes against [Levi's …
=> [codegen/nodejs] Remove unnecessary ctor overload

sdk/nodejs/tests/unwrap.spec.ts
Reverts change from https://github.com/pulumi/pulumi/pull/5280
=> Simplify type assertion in unwrap.spec.ts

CHANGELOG.md, sdk/go/x/auto/errors.go, sdk/go/x/auto/errors_test.go, sdk/go/x/auto/example_test.go, sdk/go/x/auto/local_workspace.go
=> Add IsSelectStack404Error and IsCreateStack409Error

CHANGELOG.md, sdk/go/x/auto/example_test.go, sdk/go/x/auto/local_workspace.go, sdk/go/x/auto/local_workspace_test.go, sdk/go/x/auto/stack.go
=> feat(autoapi): add Upsert methods for stacks

CHANGELOG.md, sdk/go/x/auto/example_test.go, sdk/go/x/auto/local_workspace.go, sdk/go/x/auto/local_workspace_test.go
=> Allow passing a non-default secrets provider to AutomationAPI

CHANGELOG.md, sdk/dotnet/Pulumi/Deployment/Deployment.Runner.cs
=> Prevent concurrency issues when completing tasks

CHANGELOG.md, sdk/go/x/auto/README.md, sdk/go/x/auto/cmd.go, sdk/go/x/auto/example_test.go, sdk/go/x/auto/local_workspace.go, sdk/go/x/auto/local_workspace_test.go, sdk/go/x/auto/optdestroy/optdestroy.go, sdk/go/x/auto/optrefresh/optrefresh.go, sdk/go/x/auto/optup/optup.go, sdk/go/x/auto/stack.go
Supersedes https://github.com/pulumi/pulumi/pull/5329 (same content reviewed by @metral but just rebased)
closes #5224 for now until we address structured output
=> Automation API - add the ability to stream progress updates during up/refresh/destroy

CHANGELOG.md, sdk/go/x/auto/example_test.go, sdk/go/x/auto/local_workspace_test.go, sdk/go/x/auto/stack.go
=> feat(autoapi): add GetPermalink for operation result

sdk/go/x/auto/example_test.go, sdk/go/x/auto/local_workspace.go
=> Update the docs and examples for Automation API for private git repos

pkg/codegen/internal/test/testdata/schema/bad-enum-1.json, pkg/codegen/internal/test/testdata/schema/bad-enum-2.json, pkg/codegen/internal/test/testdata/schema/bad-enum-3.json, pkg/codegen/internal/test/testdata/schema/bad-enum-4.json, pkg/codegen/internal/test/testdata/schema/good-enum-1.json, pkg/codegen/internal/test/testdata/schema/good-enum-2.json, pkg/codegen/internal/test/testdata/schema/good-enum-3.json, pkg/codegen/internal/test/testdata/schema/good-enum-4.json, pkg/codegen/schema/schema.go, pkg/codegen/schema/schema_test.go
=> Only allow type-matching enum values

.github/workflows/master.yml, .goreleaser.prerelease.yml, .goreleaser.yml, Makefile, scripts/publish_npm.sh, sdk/dotnet/Makefile, sdk/go/x/auto/errors_test.go, sdk/nodejs/Makefile, sdk/python/Makefile
This switches master builds to using github actions rather than travis
=> Switch master builds to github actions

pkg/codegen/internal/test/testdata/schema-simple.json, pkg/codegen/python/gen_test.go, pkg/codegen/schema/schema.go, pkg/codegen/schema/schema_test.go
=> [codegen/schema]: Add ResourceType to support resource refs

pkg/codegen/internal/test/testdata/schema-simple.json, pkg/codegen/python/doc.go, pkg/codegen/python/gen.go, pkg/codegen/python/gen_test.go
=> [codegen/python] Handle ResourceType

.github/workflows/container-build.yml
=> Tag sdk containers as latest

dist/pulumi/Dockerfile, docker/go/Dockerfile, docker/go/Dockerfile.alpine, docker/go/Dockerfile.ubi
=> Bump the Go version in our containers to be latest v1.14.x version - our latest tested version

.github/workflows/container-build.yml, .github/workflows/release.yml
This PR moves all the release workflows (that I can find) to GHA.
This is very much a work in progress, and we'll iterate from here.
=> Implement release workflow

CHANGELOG.md, sdk/go/x/auto/example_test.go, sdk/go/x/auto/local_workspace.go, sdk/go/x/auto/local_workspace_test.go
=> feat(autoapi): expose EnvVars LocalWorkspaceOption to set in ctor

pkg/backend/filestate/backend.go, pkg/backend/filestate/backend_test.go
=> Fix panic with logs

CHANGELOG.md, pkg/cmd/pulumi/crypto_local.go
Fix https://github.com/pulumi/pulumi/issues/5223
=> Quit if a static passphrase is invalid

pkg/codegen/go/gen_program.go, pkg/codegen/go/gen_program_expressions.go, pkg/codegen/internal/test/host.go, pkg/codegen/internal/test/providers.go, pkg/codegen/internal/test/testdata/azure-sa.pp, pkg/codegen/internal/test/testdata/azure-sa.pp.cs, pkg/codegen/internal/test/testdata/azure-sa.pp.go, pkg/codegen/internal/test/testdata/azure-sa.pp.py, pkg/codegen/internal/test/testdata/azure-sa.pp.ts
- Also adds test scaffolding for azure provider and adds a basic config generation test
=> [codegen] Add support for config generation in go programgen

pkg/codegen/schema/schema.go
=> [codegen/schema] - Add deprecation messages for enum values

pkg/codegen/dotnet/gen_program.go, pkg/codegen/internal/test/testdata/azure-sa.pp, pkg/codegen/internal/test/testdata/azure-sa.pp.cs, pkg/codegen/internal/test/testdata/azure-sa.pp.go, pkg/codegen/internal/test/testdata/azure-sa.pp.py, pkg/codegen/internal/test/testdata/azure-sa.pp.ts, pkg/go.sum
Fixes https://github.com/pulumi/pulumi-azure-nextgen/issues/42
=> Fix config params and default handling for .NET programgen

tests/integration/integration_dotnet_test.go, tests/integration/transformations/transformations_dotnet_test.go
Just fix the warning from gofmt command.
=> fix: fix the warning from gofmt command.

pkg/resource/edit/operations.go, sdk/go/common/util/executable/executable.go
Fixes: #5131
Fixes: #5016
Fixes: #4803
=> Protect against panic in finding go executable and finding resources

CHANGELOG.md, sdk/go/x/auto/example_test.go, sdk/go/x/auto/git.go, sdk/go/x/auto/local_workspace.go
=> Add the ability to specify privateKey contents to AutomationAPI

sdk/go/common/resource/plugin/provider_plugin.go
I believe the `Update` invocation is missing a value for `Preview`
=> Pass the preview flag to Update

CHANGELOG.md, pkg/backend/display/json.go
=> Ensure policy events do not cause a panic when using preview --json

.github/workflows/windows-build.yml
Missed one of the windows workflows in #5662
=> Fix windows-build workflow

CHANGELOG.md, sdk/go/pulumi/types_builtins.go
Solves https://github.com/pulumi/pulumi/issues/5647
=> Add boolean values to Go SDK (#5647)

pkg/codegen/dotnet/gen.go
Fixes https://github.com/pulumi/pulumi/issues/5707
=> [codegen/dotnet] - Fix isValueType to include enums

pkg/codegen/dotnet/gen.go, pkg/codegen/dotnet/gen_test.go, pkg/codegen/dotnet/utilities.go, pkg/codegen/nodejs/gen.go, pkg/codegen/nodejs/gen_test.go, pkg/codegen/nodejs/utilities.go
=> [codegen/dotnet,nodejs] - Improve makeSafeEnumName

pkg/codegen/dotnet/gen_test.go, pkg/codegen/dotnet/utilities.go, pkg/codegen/nodejs/utilities.go, pkg/codegen/utilities.go
We will use these replacements for all languages, so extracting them into a common function.
=> [codegen/*] - Extract common enum name replacer

.github/workflows/master.yml, .github/workflows/pull-request.yml, .github/workflows/release.yml, CHANGELOG.md, sdk/python/cmd/pulumi-language-python-exec
Fixes https://github.com/pulumi/pulumi/issues/5676
=> Support python 3.9 on windows

pkg/codegen/go/gen.go
Fix generation for https://github.com/pulumi/pulumi-azure-nextgen/issues/126
Other languages to be tracked in https://github.com/pulumi/pulumi/issues/5743
=> Parse string arrays from env in Go first-class provider

CHANGELOG.md, sdk/dotnet/Pulumi/Pulumi.csproj
Resolve #5570 and prepare the fix for #4224
=> Update .NET Grpc to the latest and Protobuf to Pulumi fork

Makefile, pkg/testing/integration/command.go, pkg/testing/integration/program.go, pkg/testing/integration/program_test.go, pkg/testing/integration/util.go, sdk/go/x/auto/errors_test.go, sdk/python/Makefile, sdk/python/Pipfile, sdk/python/Pipfile.lock
=> Reduce verbosity on tests

.github/workflows/release.yml
Fixes: #5738
This will ensure we find any potential issues after a release
=> Trigger Template and Examples tests on a release

sdk/dotnet/Pulumi/Deployment/Deployment_Invoke.cs, sdk/dotnet/Pulumi/Deployment/Deployment_ReadOrRegisterResource.cs, sdk/dotnet/Pulumi/PublicAPI.Shipped.txt, sdk/dotnet/Pulumi/Resources/ResourceOptions.cs, sdk/dotnet/Pulumi/Resources/ResourceOptions_Copy.cs, sdk/dotnet/Pulumi/Resources/ResourceOptions_Merge.cs, tests/integration/get_resource/dotnet/.gitignore, tests/integration/get_resource/dotnet/GetResource.csproj, tests/integration/get_resource/dotnet/Program.cs, tests/integration/get_resource/dotnet/Pulumi.yaml, tests/integration/integration_dotnet_test.go
Resolve https://github.com/pulumi/pulumi/issues/5796
=> Add support for getResource to the .NET SDK

pkg/codegen/internal/test/testdata/aws-fargate.pp.py, pkg/codegen/internal/test/testdata/resource-options.pp.py, pkg/codegen/python/gen_program.go
=> Ensure the correct qualified code is emitted for Python ResourceOptions

pkg/cmd/pulumi/import.go, pkg/resource/deploy/deployment_executor.go, pkg/resource/deploy/import.go
=> Ensure we don't panic or write import helper text on import errors

pkg/codegen/docs/gen.go, pkg/codegen/docs/gen_test.go, pkg/codegen/internal/test/testdata/kubernetes-operator.pp.py, pkg/codegen/internal/test/testdata/kubernetes-pod.pp.py, pkg/codegen/internal/test/testdata/kubernetes-template.pp.py, pkg/codegen/python/doc.go, pkg/codegen/python/gen_program.go, pkg/codegen/python/importer.go
Related: https://github.com/pulumi/pulumi-terraform-bridge/pull/300
Resolves: #5145
=> Remove UsesIOClasses check.

sdk/nodejs/provider/server.ts, sdk/nodejs/resource.ts, sdk/nodejs/runtime/resource.ts, sdk/nodejs/runtime/rpc.ts, sdk/nodejs/tests/runtime/registrations.spec.ts, sdk/nodejs/tsconfig.json, sdk/python/lib/pulumi/runtime/rpc.py, tests/integration/get_resource/nodejs/.gitignore, tests/integration/get_resource/nodejs/Pulumi.yaml, tests/integration/get_resource/nodejs/index.ts, tests/integration/get_resource/nodejs/package.json, tests/integration/integration_nodejs_test.go
And update Node's resource ref deserialization to match Python.
Also, fixed a bug in Python resource ref deserialization that I noticed.
Fixes https://github.com/pulumi/pulumi/issues/5798
=> Add support for getResource to Node.js SDK

pkg/codegen/docs/gen.go
Related to https://github.com/pulumi/pulumi-eks/issues/447
=> [codegen/docs] Exclude eks package API links

sdk/dotnet/Pulumi.Tests/Pulumi.Tests.csproj, sdk/dotnet/Pulumi/Pulumi.csproj
=> Bump Grpc NuGet packages to 2.34.0

CHANGELOG.md, sdk/go/common/util/ciutil/jenkins.go
close #5889
Signed-off-by: Aylei <rayingecho@gmail.com>
=> [ciutil] Correct system name of Jenkins CI

pkg/codegen/docs/gen.go, pkg/codegen/docs/gen_test.go, pkg/go.mod
Fixes: https://github.com/pulumi/docs/issues/4629
=> [codegen/docs] - Improve resource doc titles

CHANGELOG.md, pkg/resource/deploy/import.go
=> Prevent panic when using `pulumi import` with local backend

CHANGELOG.md, sdk/python/lib/pulumi/runtime/mocks.py, sdk/python/lib/test_with_mocks/resources.py, sdk/python/lib/test_with_mocks/test_testing_with_mocks.py
Part of #5832
Related to https://github.com/pulumi/pulumi/pull/5914
=> [sdk/python] Implement getResource in the mock monitor

pkg/codegen/docs.go, pkg/codegen/docs/gen.go, pkg/codegen/docs/templates/enums.tmpl, pkg/codegen/docs/templates/properties.tmpl, pkg/codegen/docs/templates/resource.tmpl, pkg/codegen/dotnet/doc.go, pkg/codegen/go/doc.go, pkg/codegen/internal/test/testdata/simple-enum-schema/nodejs/types/enums/index.ts, pkg/codegen/nodejs/doc.go, pkg/codegen/python/doc.go
Example output: http://pulumi-docs-origin-pr-4772-e7ffea5b.s3-website.us-west-2.amazonaws.com/docs/reference/pkg/aws/lambda/function/#runtime
Fixes: #5437
=> [codegen/docs] - Add enums to docs

.github/workflows/run-build-and-acceptance-tests.yml, pkg/engine/lifeycletest/delete_before_replace_test.go, pkg/engine/lifeycletest/golang_sdk_test.go
https://github.com/pulumi/pulumi/pull/5951 broke [linting](https://github.com/pulumi/pulumi/runs/1560246996)
=> Fix linting.

pkg/cmd/pulumi/import.go
=> make import command help a little clearer

.github/workflows/pr.yml
fixes #5918 
see https://github.com/bsdlp/pulumi/pull/2/checks?check_run_id=1567982647 in action
=> fixes lint checkout target for prs

sdk/python/lib/test/test_next_serialize.py
- Reset the runtime prior to each test
- Use the SDK's `test` decorator instead of `async_test`
- Rename a couple classes to avoid warnings from pytest
=> Improve Python serialization test harness.

sdk/go/pulumi/resource_test.go, sdk/go/pulumi/rpc.go, sdk/go/pulumi/rpc_test.go
=> [sdk/go] Update RegisterResource[Package/Module] interface

sdk/dotnet/Pulumi/Stack.cs, sdk/nodejs/runtime/stack.ts
=> Update PulumiStackType comments in dotnet and nodejs

sdk/go/common/apitype/history.go
=> Export UpdateID as part of the UpdateInfo event that comes from the SaaS

CHANGELOG.md, pkg/cmd/pulumi/policy_rm.go
Fixes: #4292
[![asciicast](https://asciinema.org/a/ITN9o6AOVKbLpNSQBEJjQ9Ndf.svg)](https://asciinema.org/a/ITN9o6AOVKbLpNSQBEJjQ9Ndf)
=> [CLI] Add a confirmation prompt when deleting a policy pack

CHANGELOG.md, sdk/nodejs/x/automation/localWorkspace.ts, sdk/nodejs/x/automation/stack.ts
We need to figure out #6050 before we can make config ops parallel.
=> Revert bulk config ops in nodejs auto-api

CHANGELOG.md, sdk/nodejs/tests/automation/localWorkspace.spec.ts, sdk/nodejs/x/automation/localWorkspace.ts, sdk/nodejs/x/automation/stack.ts, sdk/nodejs/x/automation/workspace.ts
Resolves: https://github.com/pulumi/pulumi/issues/5531
=> [automation-api/nodejs] - Support recovery workflow

.github/workflows/trigger-container-build-event.yml
=> Adding the pulumi.ecr.aws images as part of the docker images release

CHANGELOG.md, sdk/go/x/auto/stack.go
Fixes: https://github.com/pulumi/pulumi/issues/6091
=> [auto/go] - Set DryRun on RunInfo

CHANGELOG.md, sdk/python/lib/pulumi/output.py, sdk/python/lib/test/test_next_serialize.py
=> [sdk/python] Adding pulumi.unsecret and pulumi.is_secret

CHANGELOG.md, pkg/backend/backend.go, pkg/backend/filestate/backend.go, pkg/backend/httpstate/backend.go, pkg/backend/mock.go, pkg/cmd/pulumi/logout.go, sdk/go/common/workspace/creds.go
=> Add support for pulumi logout --all

sdk/go/pulumi/resource.go, sdk/go/pulumi/resource_test.go, sdk/go/pulumi/rpc.go, sdk/go/pulumi/rpc_test.go
=> Revert "Add resource ref unit tests for the Go SDK."

pkg/testing/integration/program.go
=> Add an option to be able to stack export showing secrets for use in ExtraRuntimeValidation

.goreleaser.prerelease.yml, .goreleaser.yml
=> try an arm64 build

pkg/engine/events.go, pkg/engine/lifeycletest/pulumi_test.go, pkg/engine/lifeycletest/resource_reference_test.go, pkg/resource/stack/deployment.go, sdk/go/common/resource/plugin/rpc.go, sdk/go/common/resource/plugin/rpc_test.go, sdk/go/common/resource/properties.go, sdk/go/common/resource/properties_diff.go, sdk/go/pulumi/rpc.go
=> Revert "Fix resource-ref-as-ID marshaling."

sdk/python/lib/pulumi/x/automation/__init__.py
Some minor docstring fixups to improve the python SDK doc generation 
Related PR: https://github.com/pulumi/docs/pull/5007
=> Docstring fixups

scripts/publish_npm.sh
=> Ensure nightly and master builds with an alpha build version are tagged dev

.github/workflows/artifact-cleanup.yml, .github/workflows/master.yml, .github/workflows/run-build-and-acceptance-tests.yml, build.proj
Related: #6110
This is the first part of the work to allow us to be able to test multiple versions of supported languages
=> Split the windows build + testing to be separate jobs to allow for future language matrix tests

build.proj
=> Revert "Ensuring all of the windows cmd binaries are included in the master builds"

CHANGELOG.md, sdk/python/lib/pulumi/output.py, sdk/python/lib/test/langhost/output_all/__main__.py, sdk/python/lib/test/langhost/output_all/test_output_all.py, sdk/python/lib/test/test_next_serialize.py
=> [sdk/python] - Allow kwargs in Output.all() to create a dict

pkg/codegen/internal/test/testdata/external-resource-schema/nodejs/cat.ts, pkg/codegen/internal/test/testdata/external-resource-schema/nodejs/component.ts, pkg/codegen/internal/test/testdata/external-resource-schema/nodejs/workload.ts, pkg/codegen/internal/test/testdata/simple-enum-schema/nodejs/tree/v1/rubberTree.ts, pkg/codegen/internal/test/testdata/simple-resource-schema/nodejs/otherResource.ts, pkg/codegen/internal/test/testdata/simple-resource-schema/nodejs/resource.ts, pkg/codegen/nodejs/gen.go
=> Don't mutate the `opts` argument in resource constructors in Node.js

sdk/nodejs/package.json, sdk/nodejs/tests/runtime/langhost/run.spec.ts
=> [sdk/nodejs] Update @grpc/grpc-js dependency

pkg/codegen/docs/gen.go, pkg/codegen/docs/gen_function.go, pkg/codegen/docs/gen_test.go
Fixes: https://github.com/pulumi/docs/issues/5209
=> [codegen/docs] - Standardize function and resource titles.

pkg/codegen/docs/gen.go
In response to: https://github.com/pulumi/pulumi/pull/6325#issuecomment-780303098
Also fixes a linting issue that got merged to master.
=> [codegen/docs] - More doc title fixes

sdk/go/common/resource/plugin/provider_server.go
Copy/paste bug I noticed in provider_server.go
=> Fix copy/paste bug in provider_server.go

CHANGELOG.md, sdk/dotnet/Pulumi.FSharp/Library.fs
New instance of https://github.com/pulumi/pulumi/pull/5077
=> Support StackOptions in F# functions

pkg/codegen/hcl2/model/type.go, pkg/codegen/hcl2/model/type_list.go, pkg/codegen/hcl2/model/type_map.go, pkg/codegen/hcl2/model/type_none.go, pkg/codegen/hcl2/model/type_object.go, pkg/codegen/hcl2/model/type_opaque.go, pkg/codegen/hcl2/model/type_output.go, pkg/codegen/hcl2/model/type_promise.go, pkg/codegen/hcl2/model/type_set.go, pkg/codegen/hcl2/model/type_test.go, pkg/codegen/hcl2/model/type_tuple.go, pkg/codegen/hcl2/model/type_union.go
Extends https://github.com/pulumi/pulumi/pull/5404 to fix https://github.com/pulumi/pulumi/issues/5228 for all Azure NextGen program examples
=> Avoid stack overflow in Azure NextGen program examples

pkg/codegen/python/gen.go
Fixes: https://github.com/pulumi/pulumi-vsphere/issues/127
=> Add triple quotes around deprecation warnings.

.github/workflows/run-codegen-test.yml
=> Ensuring that changes to codegen runs a test against azure-nextgen

CHANGELOG.md, sdk/go/pulumi/templates/types_builtins.go.template, sdk/go/pulumi/templates/types_builtins_test.go.template, sdk/go/pulumi/types_builtins.go, sdk/go/pulumi/types_builtins_test.go
=> [sdk/go] Don't panic on Elem and Index operations

.github/workflows/master.yml, .github/workflows/prerelease.yml, .github/workflows/release.yml, .goreleaser.prerelease.yml, .goreleaser.yml, CHANGELOG_PENDING.md, sdk/go/common/workspace/plugins.go
Related: #4868
Also adds the arm64 build and deployment steps via goreleaser
=> [cli] Add ability to consume arm64 plugins from pulumi cli

CHANGELOG_PENDING.md, sdk/go/common/util/executable/executable.go, sdk/go/common/util/executable/executable_test.go
Replaces #6268 - that PR was just out of date and needed rebased - wanted to rebase and then run tests - the origin user still have the commit history here
Fixes" #6223
=> Add support when GOPATH has multiple folders

CHANGELOG_PENDING.md, sdk/nodejs/x/automation/stack.ts
Missed a couple of `OpType`'s and realized we were missing `onOutput` from `PreviewOptions`.
=> [automation/nodejs] - Fix missing OpTypes and PreviewOptions

sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
=> Skip breaking dotnet automation api test

sdk/dotnet/Pulumi.Automation/Commands/LocalPulumiCmd.cs
This was a weird one. Essentially we had a race condition on process completion.
The child process would exit, the `Exited` event would be triggered - and we would `.ToString()` our `StringBuilder`s before our `OutputDataReceived` and `ErrorDataReceived` handlers were able to run to EOF. So our captured output from those streams was leaky leading to weird inconsistent results.
[Here](https://github.com/dotnet/runtime/issues/18789#issuecomment-252324082) is the relevant comment on a dotnet runtime issue that gave me the solution.
=> [automation/dotnet] - Fix child process stream capture

sdk/go/x/auto/local_workspace.go, sdk/go/x/auto/local_workspace_test.go, sdk/go/x/auto/workspace.go, sdk/nodejs/tests/automation/localWorkspace.spec.ts, sdk/nodejs/x/automation/localWorkspace.ts, sdk/nodejs/x/automation/workspace.ts, sdk/python/lib/pulumi/x/automation/_local_workspace.py, sdk/python/lib/pulumi/x/automation/_workspace.py, sdk/python/lib/test/automation/test_local_workspace.py
Follow-up from feedback on https://github.com/pulumi/pulumi/pull/6590
=> [automation/nodejs,go,python] - Expose pulumiVersion as string

sdk/dotnet/Pulumi.Automation.Tests/LocalPulumiCmdTests.cs, sdk/dotnet/Pulumi.Automation/Commands/LocalPulumiCmd.cs, sdk/dotnet/Pulumi.Automation/Pulumi.Automation.csproj
Moves from System.Diagnostics.Process to CliWrap for managing pulumi sub-process.
As discussed in https://github.com/pulumi/pulumi/pull/6572 - this is the rebased version of https://github.com/pulumi/pulumi/pull/6640 that was reviewed already.
=> Use CliWrap for subprocess management

CHANGELOG_PENDING.md, sdk/go/x/auto/local_workspace.go, sdk/go/x/auto/local_workspace_test.go, sdk/go/x/auto/test/correct_project/Pulumi.yaml, sdk/nodejs/tests/automation/data/correct_project/Pulumi.yaml, sdk/nodejs/tests/automation/localWorkspace.spec.ts, sdk/nodejs/x/automation/localWorkspace.ts, sdk/python/lib/pulumi/x/automation/_local_workspace.py, sdk/python/lib/test/automation/data/correct_project/Pulumi.yaml, sdk/python/lib/test/automation/test_local_workspace.py
Go, nodejs and python part of #6632
=> [automation/go,nodejs,python] - Respect existing project settings

pkg/codegen/go/gen.go, pkg/codegen/go/gen_test.go, pkg/codegen/internal/test/testdata/simple-resource-schema/go/example/pulumiTypes.go, pkg/codegen/internal/test/testdata/simple-resource-schema/schema.json, sdk/go/pulumi/generate.go, sdk/go/pulumi/types_builtins.go, sdk/go/pulumi/types_builtins_test.go
Fixes https://github.com/pulumi/pulumi-azure-native/issues/353
Fixes https://github.com/pulumi/pulumi/issues/6297
With this we are able to cover all constructs required by azure-native go SDK be compiled. I was able to confirm by compiling all the top-level namespaces locally.
*Update* - this PR is ready for review
=> [codegen/go] Support nested collection types

.github/workflows/run-build-and-acceptance-tests.yml, sdk/nodejs/output.ts, sdk/nodejs/runtime/config.ts, sdk/nodejs/runtime/rpc.ts, sdk/nodejs/tests/runtime/settings.spec.ts, sdk/nodejs/x/automation/server.ts, sdk/python/lib/pulumi/config.py, sdk/python/lib/pulumi/dynamic/dynamic.py, sdk/python/lib/pulumi/output.py, sdk/python/lib/pulumi/runtime/resource.py, sdk/python/lib/pulumi/runtime/rpc.py, sdk/python/lib/pulumi/runtime/settings.py, sdk/python/lib/pulumi/runtime/stack.py, sdk/python/lib/pulumi/x/automation/__init__.py, sdk/python/lib/pulumi/x/automation/_local_workspace.py, sdk/python/lib/pulumi/x/automation/_project_settings.py, sdk/python/lib/pulumi/x/automation/_server.py, sdk/python/lib/pulumi/x/automation/_stack.py, sdk/python/lib/pulumi/x/automation/_stack_settings.py, sdk/python/lib/pulumi/x/automation/_workspace.py, sdk/python/lib/pulumi/x/automation/errors.py
Just what it says on the tin. Fixes #6628.
=> Run SDK lint jobs

sdk/dotnet/Pulumi/Serialization/ResourcePackages.cs
It seems reasonable that if an assembly does not reference Pulumi.dll that defines Resource type, then it cannot contain types that inherit from Resource, and therefore we can skip GetTypes() for that assembly. This saves some System.Type traversals (4000 -> 200 in our test). More importantly it seems to help with an issue @orionstudt had in their PR where this code blows up on trying to GetType() from Castle dynamic assembly.
=> Shortcut resource packages scan

.github/workflows/run-containers-build.yml
=> GHA Workflow job to test containers changes

pkg/cmd/pulumi/stack.go
Moved contribution from pulumi/doc repo
=> fix typo in pulumi stack cli docs

.gitignore
=> add obj dirs to gitignore

CHANGELOG_PENDING.md, sdk/nodejs/x/automation/server.ts, sdk/nodejs/x/automation/stack.ts
Fixes https://github.com/pulumi/pulumi/issues/6756
=> do not run the promise checker for inline programs when an error has occured

sdk/python/lib/pulumi/automation/_stack_settings.py, sdk/python/lib/test/automation/test_local_workspace.py
Marking this no-changelog-required because we're in a weird in-between state and this will go out as a patch fix so the changelog will be added during release.
Changelog entry:
Bugfix:
- [automation/python] - Fix serialization bug in `StackSettings`
=> [automation/python] - Fix stack settings serialization

CHANGELOG_PENDING.md, sdk/nodejs/resource.ts, sdk/nodejs/runtime/resource.ts
Resolve providers references and include the resulting refs in the
providers field of RegisterResourceRequest that was added in
d297db3.
=> [sdk/nodejs] Handle providers for RegisterResourceRequest

sdk/dotnet/Pulumi.Automation/Pulumi.Automation.csproj, sdk/dotnet/Pulumi/Pulumi.csproj
=> [sdk/dotnet] Bump Grpc NuGet packages to 2.37.0

sdk/dotnet/Pulumi.Automation/Pulumi.Automation.csproj
=> [automation/dotnet] Enable SourceLink with embedded PDB

CHANGELOG_PENDING.md, pkg/codegen/dotnet/templates.go, sdk/dotnet/Pulumi.Automation/Pulumi.Automation.csproj, sdk/dotnet/Pulumi.FSharp/Pulumi.FSharp.fsproj, sdk/dotnet/Pulumi/Pulumi.csproj
=> [sdk/dotnet] Enable deterministic builds

.github/PULL_REQUEST_TEMPLATE.md
=> Proposal: PULL_REQUEST_TEMPLATE.md

CHANGELOG_PENDING.md, sdk/dotnet/Pulumi.Automation/Pulumi.Automation.csproj
=> [auto/dotnet] Bump YamlDotNet to 11.1.1

pkg/codegen/docs/README.md
To make this easier for future generations. 😄
=> Add a note to a README about regenerating test data

CHANGELOG_PENDING.md, sdk/python/lib/pulumi/automation/__init__.py
Export missing Automation API `ProjectBackend` class
Didn't add a test because I'm just exporting a type.
=> [automation/python] - Export ProjectBackend class

sdk/python/lib/test_with_mocks/test_testing_with_mocks.py
Skipping flaky test as discussed in https://github.com/pulumi/pulumi/issues/6561
=> Skip flaky python test

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, CHANGELOG_PENDING.md
=> Add vs code dev container

CHANGELOG_PENDING.md, pkg/resource/stack/deployment.go, pkg/resource/stack/deployment_test.go
=> Error instead of assert on invalid resource in state file

CHANGELOG_PENDING.md, sdk/dotnet/Pulumi/Deployment/Deployment.Logger.cs, sdk/dotnet/Pulumi/Deployment/Deployment.Runner.cs, sdk/dotnet/Pulumi/Deployment/Deployment.cs, sdk/dotnet/Pulumi/Deployment/Deployment_Inline.cs, sdk/dotnet/Pulumi/Deployment/Deployment_Run.cs, sdk/dotnet/Pulumi/Deployment/IDeploymentInternal.cs, sdk/dotnet/Pulumi/Pulumi.csproj
Fixes #7093.
@mikhailshilkov @orionstudt PTAL
=> [dotnet/sdk] Use source context with serilog

.github/workflows/master.yml
=> Adding a workflow dispatch to GHA to test master builds from branches

sdk/nodejs/config.ts
See https://github.com/pulumi/docs/pull/6094.
=> Fix a typo

sdk/dotnet/Pulumi/Core/OutputUtilities.cs
Editing doc comment to be more explicit.
=> Edit doc comment

pkg/codegen/utilities.go, pkg/codegen/utilities_test.go
This came up in https://github.com/pulumi/pulumi-google-native/pull/109/files/2abc32e32c575602f5c440c394d52e96f50f0711..c0bfbaeb116a1c8455dc54d50cc1e395dcd99be8#r647669460
=> Add helper methods to StringSet

.goreleaser.yml
=> Ensure we announce the release to GitHub Discussions

CHANGELOG_PENDING.md, pkg/codegen/internal/test/testdata/simple-enum-schema/python/pulumi_plant/tree/v1/_enums.py, pkg/codegen/python/gen.go
Fixes # https://github.com/pulumi/pulumi/issues/7375
=> [codegen/python] - Include python enum docstrings

sdk/python/lib/pulumi/automation/_stack.py, sdk/python/lib/pulumi/automation/events.py, sdk/python/lib/pulumi/dynamic/__main__.py, sdk/python/lib/pulumi/resource.py
=> Fix pylint issues

CHANGELOG_PENDING.md
=> Cleanup changelog

CODE-OF-CONDUCT.md
Some small updates to the Code of Conduct (scoped to community guidelines)
=> Draft updates to Code of Conduct for guidelines

sdk/go/common/resource/plugin/plugin.go, sdk/python/lib/pulumi/provider/server.py, tests/integration/integration_nodejs_test.go
Continue with the https://github.com/pulumi/pulumi/pull/7404 adapted to pass python tests.
=> Quick fix for provider flag ordering

sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
Issue to track the test: https://github.com/pulumi/pulumi/issues/7467
=> Turn off flakey test

pkg/codegen/internal/test/sdk_driver.go
Add support for skipping testcases when run against specific languages.
=> [codegen/test] Optionally skip testcases.

pkg/codegen/nodejs/gen.go
Move ImportLanguages logic into generateModuleContextMap
rather than duplicating this work.
=> [codegen] Refactor generateModuleContextMap

pkg/codegen/internal/test/testdata/types.json, pkg/codegen/internal/test/type_driver.go, pkg/codegen/schema/schema.go
- Add another regression test for #7454
- Add tests for singly-nested plain collections
=> [codegen] Add more type tests.

pkg/cmd/pulumi/import.go
Fixes: https://github.com/pulumi/pulumi/issues/7477
=> Fix typo: genrated->generated

pkg/engine/lifeycletest/pulumi_test.go, pkg/resource/deploy/deploytest/resourcemonitor.go
Add inner-loop tests for methods in `pkg/engine/lifecycletest`
Part of #7072
=> Add methods lifecycle tests

.github/workflows/master.yml
=> Trigger examples tests on merge to master

pkg/codegen/go/gen.go
This commit modifies the Go code generator to use configured aliases for the root package name of a Go module. This is useful when a version 2 package is present, as it prevents generation of identifiers such as "v2" which were produced by the old logic.
No test coverage appears to exist for this path.
This is not a user-facing change.
=> Respect package import alias for top-level module

pkg/codegen/internal/test/testdata/provider-config-schema/python/setup.py, pkg/codegen/internal/test/testdata/simple-yaml-schema/python/setup.py
The PR for these codegen changes (#7479) was opened before these tests were added.
=> Fix codegen tests

CHANGELOG.md, CHANGELOG_PENDING.md
Also some cleanup:
* Consistently use `.` at the end of titles.
* Add some missing PR numbers
* Consistently don't use ` - ` inside title.
=> Fix CHANGELOG for 7541

sdk/dotnet/Pulumi.Tests/Deployment/DeploymentRunnerTests.cs
Test would fail if rep 100x. With the polling, it does not fail 100x.
=> Fix new flaky test by polling for logs

CHANGELOG.md
=> Prepare for v3.9.0 release

.github/workflows/master.yml, .github/workflows/run-build-and-acceptance-tests.yml, scripts/test_subsets.py
=> Apply the same build tricks we run on PRs to master workflow

.github/workflows/release.yml, scripts/test_subsets.py
=> Fan out release workflow

sdk/go/common/workspace/paths.go
follow up from https://github.com/pulumi/pulumi/issues/7000
=> improve error message when flag passed to -s is not fully qualified

sdk/nodejs/runtime/resource.ts
follow up from https://github.com/pulumi/pulumi/pull/7704
RPC queue should be freed in a finally block in `prepareResource`
=> free prepResource in finally

README.md
=> Fix license badge in readme

pkg/codegen/dotnet/gen_program.go, pkg/codegen/dotnet/gen_program_expressions.go, pkg/codegen/dotnet/utilities.go, pkg/codegen/go/gen_program_expressions.go, pkg/codegen/go/gen_program_utils.go, pkg/codegen/hcl2/functions.go, pkg/codegen/nodejs/gen_program.go, pkg/codegen/nodejs/gen_program_expressions.go, pkg/codegen/python/gen_program_expressions.go
Implemented Terraform's `sha1()` function for all 4 languages, solving a total of 20 code generation errors in the AWS provider
=> Implemented `sha1()` support for Code Generator

sdk/go.mod, sdk/go.sum, sdk/go/common/resource/plugin/rpc_rapid_test.go
=> Property-check turnaround

sdk/python/lib/pulumi/config.py, sdk/python/lib/pulumi/dynamic/__main__.py, sdk/python/lib/pulumi/runtime/config.py, sdk/python/lib/pulumi/runtime/settings.py, sdk/python/lib/pulumi/runtime/stack.py
Fixes lint issues highlighted by pylint 2.11.0
=> Fix python lint issues

pkg/backend/display/options.go, pkg/backend/filestate/backend.go, pkg/backend/httpstate/backend.go, pkg/cmd/pulumi/destroy.go, pkg/cmd/pulumi/import.go, pkg/cmd/pulumi/preview.go, pkg/cmd/pulumi/refresh.go, pkg/cmd/pulumi/up.go, pkg/cmd/pulumi/watch.go
Clean up some nits and comments
=> Rename PermaLink to Permalink

pkg/go.mod, pkg/go.sum, pkg/resource/stack/deployment.go, pkg/resource/stack/deployment_test.go, sdk/go/common/resource/plugin/rpc_rapid_test.go, sdk/go/common/resource/properties_diff.go, sdk/go/common/resource/testing/assert.go, sdk/go/common/resource/testing/rapid.go
And use those generators to test property value serialization and
deserialization paths.
=> [testing] Add rapid generators for PropertyValues.

pkg/codegen/internal/test/sdk_driver.go, pkg/codegen/internal/test/testdata/.gitignore, pkg/codegen/internal/test/testdata/resource-args-python-case-insensitive/docs/codegen-manifest.json, pkg/codegen/internal/test/testdata/resource-args-python-case-insensitive/dotnet/codegen-manifest.json, pkg/codegen/internal/test/testdata/resource-args-python-case-insensitive/go-extras/tests/go_test.go, pkg/codegen/internal/test/testdata/resource-args-python-case-insensitive/go/codegen-manifest.json, pkg/codegen/internal/test/testdata/resource-args-python-case-insensitive/nodejs/codegen-manifest.json, pkg/codegen/internal/test/testdata/resource-args-python-case-insensitive/python/codegen-manifest.json
Follow up to undo the effects of a recent bad merge.
=> Fix master build

CHANGELOG.md
=> Prep for 3.13.0 release

pkg/codegen/internal/test/testdata/output-funcs/nodejs/funcWithAllOptionalInputs.ts, pkg/codegen/internal/test/testdata/output-funcs/nodejs/funcWithConstInput.ts, pkg/codegen/internal/test/testdata/output-funcs/nodejs/funcWithDefaultValue.ts, pkg/codegen/internal/test/testdata/output-funcs/nodejs/funcWithDictParam.ts, pkg/codegen/internal/test/testdata/output-funcs/nodejs/funcWithListParam.ts, pkg/codegen/internal/test/testdata/output-funcs/nodejs/getClientConfig.ts
Fixes the effects of bad automatic merge of the previous PR.
=> Fix build by accepting nodejs codegen output

CHANGELOG_PENDING.md
=> Release cleanup

sdk/python/lib/test/langhost/output_property_dependencies/__init__.py, sdk/python/lib/test/langhost/output_property_dependencies/__main__.py, sdk/python/lib/test/langhost/output_property_dependencies/test_output_property_dependencies.py, sdk/python/lib/test/langhost/util.py
Ensure that output property dependencies are deserialized and translated
properly.
Fixes #7444.
=> [sdk/python] Add a smoke test for output deps

pkg/codegen/docs/gen.go
Just as the title states...
- Adding an entry to an existing lookup map
- This is not a user-facing change
- N/A
=> [codegen/docs] Add Nomad to the docs gen title lookup

.github/workflows/master.yml, .github/workflows/prerelease.yml, .github/workflows/release.yml, .github/workflows/run-build-and-acceptance-tests.yml, pkg/codegen/internal/test/sdk_driver.go, sdk/python/Makefile
=> Try an alternative pipenv install method

CHANGELOG.md
=> Prepare for v3.17.1 release

pkg/go.mod, tests/go.mod
=> Update pkg -> sdk dependency for 3.17.1

pkg/resource/graph/dependency_graph_rapid_test.go
Beginnings of formalizing and PBT-testing the dependency graph. This has been a starting point of many experiments for me in verifying PRs touching dependencies, and has been very useful to me, I think we can grow formalizations from here. I suggest checking it in as it will continue catching interesting changes even in the current form.
=> Dependency graph formalization and PBT tests

CHANGELOG_PENDING.md, sdk/go/common/util/ciutil/buildkite.go, sdk/go/common/util/ciutil/detect.go, sdk/go/common/util/ciutil/vars_test.go
This adds a custom CI detector for the Buildkite CI/CD system.
=> Added a buildkite detector for detecting the correct env vars in CI

pkg/codegen/internal/test/program_driver.go, sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs, sdk/go/common/resource/asset_test.go, sdk/nodejs/tests/automation/localWorkspace.spec.ts, tests/integration/integration_dotnet_test.go, tests/integration/integration_nodejs_test.go, tests/integration/integration_python_test.go, tests/integration/targets/targets_test.go, tests/stack_test.go
=> Skip flaky tests until we can fix and investigate them

CHANGELOG_PENDING.md, pkg/codegen/hcl2/model/expression.go, pkg/codegen/internal/test/helpers.go, pkg/codegen/internal/test/program_driver.go, pkg/codegen/internal/test/testdata/aws-fargate-pp/nodejs/aws-fargate.ts, pkg/codegen/internal/test/testdata/output-funcs-aws-pp/nodejs/output-funcs-aws.ts, pkg/codegen/internal/test/testdata/output-funcs-aws-pp/output-funcs-aws.pp, pkg/codegen/nodejs/gen_program_expressions.go, pkg/codegen/pcl/invoke.go
=> Programgen support for fnOutput forms in node (#7949)

CHANGELOG_PENDING.md, pkg/codegen/internal/test/program_driver.go, pkg/codegen/internal/test/testdata/aws-fargate-pp/python/aws-fargate.py, pkg/codegen/internal/test/testdata/output-funcs-aws-pp/python/output-funcs-aws.py, pkg/codegen/python/gen_program_expressions.go
=> Programgen support for fn_output forms in Python (#7949)

CHANGELOG_PENDING.md, pkg/codegen/go/gen.go, pkg/codegen/go/gen_program.go, pkg/codegen/go/gen_program_expressions.go, pkg/codegen/go/gen_program_optionals.go, pkg/codegen/internal/test/program_driver.go, pkg/codegen/internal/test/testdata/aws-fargate-pp/go/aws-fargate.go, pkg/codegen/internal/test/testdata/output-funcs-aws-pp/go/output-funcs-aws.go
=> Go implementation of fn.Output program gen (#7949)

CHANGELOG_PENDING.md
For after release is complete.
=> Cleanup CHANGELOG_PENDING.md

README.md
=> Change build green link from travis to github

CONTRIBUTING.md
Updates to the CONTRIBUTING guide based on my experience getting `pulumi/pulumi` built as part of testing #2318.
=> Update CONTRIBUTING.md with latest information

sdk/go/common/apitype/stacks.go
=> Adding a Log3rdPartyDecryptionEventType for logging 3rd party secrets provider decryption

.gitpod/Dockerfile
=> add pulumictl to gitpod

developer-docs/providers/implementers-guide.md
Add detail in developer docs about how to implement cancellation in providers
=> Add notes about implementing cancellation

pkg/codegen/internal/test/sdk_driver.go, pkg/codegen/internal/test/testdata/nested-module-thirdparty/nodejs/package.json, pkg/codegen/internal/test/testdata/nested-module-thirdparty/schema.json, pkg/codegen/internal/test/testdata/nested-module/nodejs/package.json, pkg/codegen/internal/test/testdata/nested-module/schema.json, pkg/codegen/internal/test/testdata/regress-8403/nodejs/package.json, pkg/codegen/internal/test/testdata/regress-8403/schema.json, pkg/codegen/internal/test/testdata/resource-property-overlap/nodejs/package.json, pkg/codegen/internal/test/testdata/resource-property-overlap/schema.json, pkg/codegen/internal/test/testdata/simple-methods-schema/nodejs/package.json, pkg/codegen/internal/test/testdata/simple-methods-schema/schema.json
Fixes some broken `sdk_driver` tests by adding correct dependencies for NodeJS.
=> Add dependencies to enable tests

pkg/cmd/pulumi/doc.go, pkg/cmd/pulumi/doc_reader.go, pkg/codegen/schema/schema.go, pkg/go.mod, pkg/go.sum, tests/go.mod, tests/go.sum
This all fits together basically as expected.
=> add terminal docs pager

.gitignore, .gitpod.yml, CONTRIBUTING.md, build/common.mk, pkg/testing/integration/program.go, sdk/nodejs/README.md
=> Move `PULUMI_ROOT` to `$HOME/.pulumi-dev`

pkg/cmd/pulumi/doc.go, pkg/cmd/pulumi/doc_reader.go
This converts non-primitive types into links for the pagination to consume.
=> Add internal links

.github/workflows/master.yml, .github/workflows/prerelease.yml, .github/workflows/release.yml, .github/workflows/run-build-and-acceptance-tests.yml, .github/workflows/run-codegen-test.yml, .github/workflows/run-docs-generation.yml
=> Update to 1.3.0 ov action-install-gh-release

pkg/cmd/pulumi/doc.go
- Default to Typescript for code examples when invoked outside the
context of a Pulumi project
- Add a flag to allow the user to specify the language for code examples
=> Allow `pulumi doc` outside of a project.

pkg/cmd/pulumi/doc.go
Allows adding schema not served by a provider via the `--schema` flag.
=> Allow specifying schema files

.github/workflows/run-build-and-acceptance-tests.yml
=> Fix non-existing build ref

sdk/go/common/apitype/stacks.go
This is a set of API types that I can use to fix #6445
=> Adding API Types for Bulk Decryption of Secrets

CHANGELOG.md
=> Prepare for v3.21.0 release

pkg/go.mod, tests/go.mod
=> Update pkg -> sdk dependency v3.21.0

sdk/go/common/resource/config/map.go, sdk/go/common/resource/config/value.go, sdk/go/common/resource/config/value_test.go
=> Unify Map and Value number exporting
