pulumi/pulumi

changelog/pending/20241122--engine--send-the-same-program-arguments-to-shimless-and-binary-plugins.yaml
sdk/go/common/resource/plugin/plugin.go

Noticed this small discrepancy while looking at the code for component provider support. We should be passing the same args for shimless and binary programs, but we were only passing -v/--logtostderr/--tracing to the binary programs.

Send same args to shimless and binary plugins

---

changelog/pending/20241125--sdk-python--uv-toolchain-preserve-env-vars-when-executing-uv-command.yaml
sdk/python/toolchain/uv.go

Correctly set up environment when executing `uv` command. fixes https://github.com/pulumi/pulumi/issues/17848

python uv: preserve env-vars when executing uv command (fix #17848)

---

changelog/pending/20241125--sdkgen-dotnet--fix-parameterized-packages-to-have-version-txt.yaml
pkg/codegen/dotnet/gen.go

Noticed this while trying to add parameterise to the dotnet sdk. It couldn't generate a valid local sdk, we must have missed testing this when adding local gen-sdk support for parameterised packages.

Fix parameterised dotnet packages to have version.txt

---

sdk/go/pulumi/types.go

I've been working with our Go SDK and both of these would have helped me.
The exact syntax for `pulumi.All` isn't obvious (and could be improved IMO).
The caveat in `pulumi.JSONMarshal` is extremely non-obvious, and should be called out in our documentation until it is fixed.
TODO: After this merges, comment on https://github.com/pulumi/pulumi/issues/12460 that the caveat needs to be removed after the issue is fixed.

Add some examples and caveats for the Go SDK

---

changelog/pending/20241125--cli--fix-login-interactive-when-no-accounts-are-in-the-credentials-file.yaml
pkg/cmd/pulumi/login.go

Spotted by @thomas11 in internal slack:
```
pulumi login --interactive
error: no account selected; please use `pulumi login --interactive` to choose one
```
Looks like this was from loading an empty credentials file in interactive mode and then immediately error'ing that there was no account to choose.

Fix login --interactive when no accounts are in the credentials file

---

.goreleaser.yml
changelog/pending/20241126--cli--reduce-binary-size-by-stripping-debug-information.yaml

Strip the symbol table and DWARF debug information from the production
and dev releases. Note that stack traces don't lose any information from this change.
Binary size is reduced by ~30%:
* pulumi: 94M -> 67M
* pulumi-language-python: 33M -> 23M
Also use `-trimpath` for tidier module paths in stack traces. Before:
```
runtime/debug.Stack()
/opt/homebrew/Cellar/go/1.23.2/libexec/src/runtime/debug/stack.go:26 +0x64
github.com/pulumi/pulumi/pkg/v3/resource/deploy.SnapshotIntegrityErrorf({0x1060e97ad?, 0x40?}, {0x14000dbd1b8?, 0x40?, 0x40?})
/Users/julien/Projects/pulumi/pulumi/pkg/resource/deploy/snapshot.go:617 +0x30
```
With `-trimpath` absolute file system paths will begin either a module path@version (when using modules) or a plain import path (when using the standard library)
``` …
```

Reduce binary size by stripping debug information

---

changelog/pending/20241126--cli-new--fix-new-to-work-with-local-template-directories-again.yaml
sdk/go/common/util/gitutil/git.go
sdk/go/common/util/gitutil/git_test.go
tests/integration/integration_test.go

Fixes https://github.com/pulumi/pulumi/issues/17862.
This reverts commit cfe2ccd36ec8d5990291e0779b1936aafb7f9968.

Revert "allow URLs without template for downloading git repos (#17824)"

---

pkg/codegen/dotnet/gen.go
pkg/codegen/go/gen.go
pkg/codegen/nodejs/gen.go
pkg/codegen/python/gen.go
pkg/codegen/schema/bind.go
pkg/codegen/schema/schema.go

There's no need to have this in the Parameterization.BaseProvider section. There's only ever one plugin being referenced by a package, and thus one PluginDownloadURL and the field is already in the top level of the package schema. So just use that, don't duplicated/move it.

Remove PluginDownloadURL from Parameterization

---

changelog/pending/20241126--sdkgen--include-parameterization-details-in-pulumi-plugin-json.yaml
pkg/codegen/dotnet/gen.go
pkg/codegen/go/gen.go
pkg/codegen/nodejs/gen.go
pkg/codegen/python/gen.go
sdk/go/common/resource/plugin/plugin.go
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsc/sdks/subpackage-2.0.0/package.json
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsnode/sdks/subpackage-2.0.0/package.json
sdk/python/cmd/pulumi-language-python/testdata/classes/sdks/subpackage-2.0.0/pulumi_subpackage/pulumi-plugin.json
sdk/python/cmd/pulumi-language-python/testdata/setuppy/sdks/subpackage-2.0.0/pulumi_subpackage/pulumi-plugin.json
sdk/python/cmd/pulumi-language-python/testdata/toml/sdks/subpackage-2.0.0/pulumi_subpackage/pulumi-plugin.json

Part of https://github.com/pulumi/pulumi/issues/17507
For importing resources of parameterized resources we need to be able to find the parameterized package descriptions without running the users program. This is the first part of fixing that. We add the parameterized information about the package into it's pulumi-plugin.json file, so this file now describes the overall package not just the base provider plugin.
Once this is merged there are two follow ups;
1) See about fixing sdk-gen to not emit the large byte value twice (in the source code where we currently have it, and now in the pulumi-plugin.json). We can probably fix all the sdks to just read from the embedded plugin file.
2) Update the language hosts to support a "GetAllPackages" instead of "GetAllPlugins" to read out this …

Add 'parameterization' to pulumi-plugin.json

---

changelog/pending/20241125--sdk-nodejs--throw-from-output-on-circular-structures.yaml
sdk/nodejs/output.ts
sdk/nodejs/tests/output.spec.ts

Note to reviewers: Review each commit separately. The first commit contains only formatting changes (no functional changes). The actual fix is in the second commit.
---
`pulumi.output(...)` cannot handle circular structures. Passing one to `output()` will currently result in a "Maximum call stack exceeded" error.
This commit adds a better error message for when a circular structure is detected, so that users know what the actual problem is and can address it. The error that is thrown is similar to the error thrown when passing a circular structure to `JSON.stringify()`.
Note: It may be possible to make circular structures work with `output()`, but it would require more time/effort to get the implementation right and not regress the perf fix from https://github.com/pulumi/pulumi/pull/3851. …

[sdk/nodejs] Throw from output() on circular structures

---

changelog/pending/20241202--cli-install--dont-recreate-virtualenvs-when-using-venv.yaml
sdk/python/toolchain/uv.go
sdk/python/toolchain/uv_test.go

Preserve the existing virtualenv when running EnsureVenv. While
recreating is very fast with uv, editors and LSPs notice the file
changes and reparse the venv.
Fixes https://github.com/pulumi/pulumi/issues/17831

Don't recreate virtualenvs when using venv

---

pkg/backend/display/display.go
pkg/backend/httpstate/state.go
pkg/channel/channel.go
pkg/channel/channel_test.go

`sdk/go/common/channel` is home to a single helper function, `FilterRead`, that is [only used
internally](https://github.com/search?q=%28org%3Apulumiverse+OR+org%3Apulumi%29+%22FilterRead%22&type=code) and doesn't need to be part of the public API that `sdk/go/common` in theory comprises. This commit moves it into `pkg/channel` to try and reduce unnecessary surface in `sdk/go/common`.

Move `sdk/go/common/channel` to `pkg`

---

changelog/pending/20241202--auto-nodejs--dont-hang-indefinitely-on-failed-inputs.yaml
sdk/nodejs/runtime/resource.ts
sdk/nodejs/tests/automation/localWorkspace.spec.ts

Ensure we always mark the register resource RPC call as completed, even
when an error occurs.
Fixes https://github.com/pulumi/pulumi/issues/17613

Don't hang indefinitely on failed inputs

---

changelog/pending/20241203--auto-python--catch-baseexception-in-automation-api-server.yaml
sdk/python/lib/pulumi/automation/_server.py
sdk/python/lib/test/automation/test_local_workspace.py

Automation API is useful for writing tests for Pulumi programs, and a
user could write a test as follows:
```python
def program():
with pytest.raises(ValueError):
_a = 1 + 2  # No error here, pytest.raises should fail
stack = create_stack("mystack", program=program, project_name="proj")
with pytest.raises(InlineSourceRuntimeError):
stack.preview()
```
If the block in `pytest.raises` does not raise the expected error or any
error, `pytest.raises` fails the test by raising an `OutcomeException`.
This exception class inherits from `BaseException`, not `Exception`, so
we would previously not catch this, and fail to report an error from the
automation API server's `Run` method, causing the call to `stack.preview`
to hang indefinitely.
Fixes https://github.com/pulumi/pulumi/issues/17133

Catch BaseException in automation API server

---

changelog/pending/20241204--cli--suggest-state-repair-as-part-of-integrity-panics.yaml
pkg/cmd/pulumi/errors.go

When the Pulumi CLI encounters a snapshot integrity error, we emit an error message asking the user to file an issue. We don't however give them much advice on how to proceed. In #17445 we introduced the `state repair` command, which can fix a large number of issues that cause snapshot integrity failures. In this commit, we inform users of `state repair` in the hope that it might unblock them, or offer a neater solution than e.g. `state delete` and the like that we've previously observed people using. As a fallback, we also mention the `--disable-integrity-checking` flag that users have used previously, to make it a bit more discoverable.
Fixes #4984

Suggest `state repair` as part of integrity panics

---

pkg/cmd/pulumi/plan/plan.go
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/up.go
pkg/cmd/pulumi/util.go

This commit continues the process of breaking up
`pkg/cmd/pulumi/util.go` by hoisting out functions for reading and writing plans to their own subpackage.

Break out plan I/O from `pkg/cmd/pulumi/util`

---

pkg/codegen/go/gen_program_expressions.go

Issue #7645 tracks a TODO that is at this point over 3 years old and clearly not contributing anything to Go code generation. This commit removes it so that we can close the noisy issue. Git will preserve it if we ever need to dig it out again!
Closes #7645

Remove dead code from Go program generation

---

pkg/cmd/pulumi/about_env.go
pkg/cmd/pulumi/config.go
pkg/cmd/pulumi/config_env.go
pkg/cmd/pulumi/plugin_ls.go
pkg/cmd/pulumi/policy_group_ls.go
pkg/cmd/pulumi/policy_ls.go
pkg/cmd/pulumi/stack.go
pkg/cmd/pulumi/stack_ls.go
pkg/cmd/pulumi/stack_tag.go
pkg/cmd/pulumi/ui/table.go
pkg/cmd/pulumi/util.go

This commit continues the process of breaking up
`pkg/cmd/pulumi/util.go` by hoisting out functions for printing tabular data to a new `ui` subpackage.

Break out table rendering from `pkg/cmd/pulumi/util`

---

pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/util.go

This commit continues the process of breaking up
`pkg/cmd/pulumi/util.go` by moving the `buildStackName` function so that it is next to its only use site in `pulumi new`.

Move `pulumi new` helpers out of `pkg/cmd/pulumi/util`

---

pkg/cmd/pulumi/about.go
pkg/cmd/pulumi/config.go
pkg/cmd/pulumi/config_env.go
pkg/cmd/pulumi/logs.go
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/plugin_ls.go
pkg/cmd/pulumi/policy_group_ls.go
pkg/cmd/pulumi/policy_ls.go
pkg/cmd/pulumi/stack.go
pkg/cmd/pulumi/stack_history.go
pkg/cmd/pulumi/stack_ls.go
pkg/cmd/pulumi/stack_output.go
pkg/cmd/pulumi/stack_tag.go
pkg/cmd/pulumi/state_edit_encoder.go
pkg/cmd/pulumi/ui/json.go
pkg/cmd/pulumi/ui/json_test.go
pkg/cmd/pulumi/util.go
pkg/cmd/pulumi/util_test.go
pkg/cmd/pulumi/whoami.go

This commit continues the process of breaking up
`pkg/cmd/pulumi/util.go` by hoisting out functions for printing JSON to their own subpackage.

Break out JSON helpers from `pkg/cmd/pulumi/util`

---

pkg/backend/httpstate/policypack.go

This is helpful when debugging policy pack download URLs.

Log policy pack download URLs

---

changelog/pending/20241204--sdkgen-go--fix-writing-of-go-mod-files-for-parameterized-packages.yaml
pkg/codegen/dotnet/gen.go
pkg/codegen/nodejs/gen.go
pkg/codegen/python/gen.go
pkg/codegen/schema/bind.go
pkg/codegen/schema/package_reference.go
pkg/codegen/schema/schema.go

SupportPack was added to write out sdks in a new style appropriate for use in conformance tests and for local sdks. When adding parameterized we tried to treat them the same, always writing out in the new style. But we we're inconsistent and didn't always check for "parameterization != nil" at the same time as "supportPack". 
This changes the schema loader to just do that as part of marshal/unmarshal schema.
The only thing this actually affects is Go sdkgen in that parameterized providers now write out their top level go.mod as expected.

Enable support pack for all parameterized packages

---

pkg/cmd/pulumi/package_add.go
pkg/codegen/go/gen.go
tests/integration/go/parameterized/go.mod

This code wrote a go.mod file one folder below where we actually expected a go.mod file to be written according to SupportPack, since https://github.com/pulumi/pulumi/pull/17923 was merged we were writing out both. This removes the nested go.mod, fixes the integration test that was using that instead of the top level go.mod, and fixes `package add` to refer to the top level go.mod.

Remove second go.mod in parameterized packages

---

changelog/pending/20241205--sdk-dotnet--upgrade-pulumi-dotnet-to-3-71-0.yaml
pkg/codegen/testing/test/helpers.go
scripts/get-language-providers.sh

Pull in the latest release. This unblocks .NET codegen for the new DependsOn option for invokes.

Upgrade pulumi-dotnet to 3.71.0

---

pkg/cmd/pulumi/about/about.go
pkg/cmd/pulumi/about/about_env.go
pkg/cmd/pulumi/about/about_test.go
pkg/cmd/pulumi/pulumi.go

This commit breaks out the `about` command and its subcommands into a new subpackage of `pkg/cmd/pulumi`. In doing so we are able to better encapsulate the components of the command and more clearly delineate the "APIs" of each command hierarchy.

Break out `pulumi about`

---

pkg/cmd/pulumi/ai.go
pkg/cmd/pulumi/convert-trace.go
pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/plugin_rm.go
pkg/cmd/pulumi/policy_rm.go
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/pulumi.go
pkg/cmd/pulumi/query.go
pkg/cmd/pulumi/refresh.go
pkg/cmd/pulumi/replay_events.go
pkg/cmd/pulumi/stack_rm.go
pkg/cmd/pulumi/state_delete.go
pkg/cmd/pulumi/state_edit.go
pkg/cmd/pulumi/state_rename.go
pkg/cmd/pulumi/state_unprotect.go
pkg/cmd/pulumi/up.go
pkg/cmd/pulumi/util.go
pkg/cmd/pulumi/util_remote.go
pkg/cmd/pulumi/view-trace.go
pkg/cmd/pulumi/watch.go

Some of our environment variables have helper functions -- e.g. `skipConfirmations` instead of `env.SkipConfirmations.Value`. We don't define these functions for all variables, nor do we use them consistently for the ones that do have them defined, so this commit removes them. In doing so `util.go` gets a bit smaller again and the dependencies on `sdk/go/common/env` (which we'd like to remove some day) become clearer.

Clean up environment variable checks in `pkg/cmd`

---

pkg/cmd/pulumi/ai/ai.go
pkg/cmd/pulumi/ai/ai_web.go
pkg/cmd/pulumi/pulumi.go

This commit breaks out the `ai` command and its subcommands into a new subpackage of `pkg/cmd/pulumi`. In doing so we are able to better encapsulate the components of the command and more clearly delineate the "APIs" of each command hierarchy.

Break out `pulumi ai`

---

pkg/cmd/pulumi/deployment_settings_utils.go
pkg/cmd/pulumi/login.go
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/new_ai.go
pkg/cmd/pulumi/policy_new.go
pkg/cmd/pulumi/state.go
pkg/cmd/pulumi/state_edit.go
pkg/cmd/pulumi/state_move.go
pkg/cmd/pulumi/state_rename.go
pkg/cmd/pulumi/state_repair.go
pkg/cmd/pulumi/ui/survey.go
pkg/cmd/pulumi/util.go

This commit continues pushing more of `pkg/cmd/pulumi/util.go` into better namespaces. This time, it's the turn of several of our `survey` helpers to move to `ui`.

Split out more `survey` helpers into `ui`

---

pkg/cmd/pulumi/package_add.go

This change adds some documentation to `pulumi package add`, notably how `<package>` parameter may resolve resource plugin references, local binaries, or local Pulumi package schema files.

Improve CLI help for "pulumi package add"

---

changelog/pending/20241209--backend-diy--show-a-more-correct-url-for-lock-files-in-error-messages.yaml
pkg/backend/diy/lock.go
pkg/backend/diy/lock_test.go

In the DIY backend, when a stack is locked, we attempt to show the URL to the lock file in the error message we show to users. The URL is naively created by concatenating the baseURL with the path to the lock file. But this naive concatenation isn't correct when there are query params in the base URL. This change fixes that by concatenating the path of a parsed URL. If for some reason we can't parse the URL, we fall back to the naive concatenation we were doing previously.
Fixes #17762

[backend/diy] Show a more correct URL for lock files

---

changelog/pending/20241206--sdk-nodejs--add-getschema-to-provider-interface.yaml
sdk/nodejs/provider/provider.ts
sdk/nodejs/provider/server.ts

Originally implemented in https://github.com/pulumi/pulumi/pull/6892, node's Provider interface has a `schema` property of type string. As such, it's required to be set unconditionally at provider class instantiation, not loaded dynamically on demand. This puts an unneeded burden on provider startup to load or calculate the entire schema even though it may never be needed.
This PR adds a `getSchema?: () => Promise<string>;` method in line with gRPC interface functionality. `schema` is still present for backwards compatibility. The server will use `schema` if it's defined, or `getSchema` if not.

[sdk/nodejs] Add getSchema to Provider interface

---

changelog/pending/20241203--sdk-nodejs-python--update-python-and-nodejs-to-use-the-new-getrequiredpackage-functionality.yaml
cmd/pulumi-test-language/interface.go
cmd/pulumi-test-language/l2resourcesimple_test.go
pkg/codegen/go/gen.go
pkg/codegen/nodejs/gen.go
pkg/codegen/python/gen.go
sdk/go/pulumi-language-go/main.go
sdk/go/pulumi-language-go/main_test.go
sdk/go/pulumi-language-go/testdata/sdks/alpha-3.0.0-alpha.1.internal/alpha/pulumi-plugin.json
sdk/go/pulumi-language-go/testdata/sdks/asset-archive-5.0.0/assetarchive/pulumi-plugin.json
sdk/go/pulumi-language-go/testdata/sdks/config-9.0.0/config/pulumi-plugin.json
sdk/go/pulumi-language-go/testdata/sdks/config-grpc-1.0.0/configgrpc/pulumi-plugin.json
sdk/go/pulumi-language-go/testdata/sdks/fail_on_create-4.0.0/fail_on_create/pulumi-plugin.json
sdk/go/pulumi-language-go/testdata/sdks/large-4.3.2/large/pulumi-plugin.json
sdk/go/pulumi-language-go/testdata/sdks/primitive-7.0.0/primitive/pulumi-plugin.json
sdk/go/pulumi-language-go/testdata/sdks/primitive-ref-11.0.0/primitiveref/pulumi-plugin.json
sdk/go/pulumi-language-go/testdata/sdks/ref-ref-12.0.0/refref/pulumi-plugin.json
sdk/go/pulumi-language-go/testdata/sdks/secret-14.0.0/secret/pulumi-plugin.json
sdk/go/pulumi-language-go/testdata/sdks/simple-2.0.0/simple/pulumi-plugin.json
sdk/go/pulumi-language-go/testdata/sdks/simple-invoke-10.0.0/simpleinvoke/pulumi-plugin.json
sdk/go/pulumi-language-go/testdata/sdks/subpackage-2.0.0/subpackage/pulumi-plugin.json
sdk/nodejs/cmd/pulumi-language-nodejs/main.go
sdk/nodejs/cmd/pulumi-language-nodejs/main_test.go
sdk/python/cmd/pulumi-language-python/main.go
sdk/python/cmd/pulumi-language-python/main_test.go

This also updates Python, Go, and NodeJS to use GetRequiredPackages instead of GetRequiredPlugins, as they get tested via conformance testing.

Conformance tests check GetRequiredPackages

---

pkg/cmd/pulumi/cmd/time.go
pkg/cmd/pulumi/logs.go
pkg/cmd/pulumi/plugin_ls.go
pkg/cmd/pulumi/stack_history.go
pkg/cmd/pulumi/stack_ls.go

Presently, a shared `timeFormat` is used in several places in `pkg/cmd/pulumi` to format timestamps using the `time.Time.Format` method. This commit pulls this functionality into a `cmdTime` subpackage so that we don't need the shared variable and resulting duplication.

Abstract time formatting in `pkg/cmd/pulumi`

---

pkg/cmd/pulumi/config/config.go
pkg/cmd/pulumi/config/config_env.go
pkg/cmd/pulumi/config/config_env_add.go
pkg/cmd/pulumi/config/config_env_add_test.go
pkg/cmd/pulumi/config/config_env_init.go
pkg/cmd/pulumi/config/config_env_init_test.go
pkg/cmd/pulumi/config/config_env_ls.go
pkg/cmd/pulumi/config/config_env_ls_test.go
pkg/cmd/pulumi/config/config_env_rm.go
pkg/cmd/pulumi/config/config_env_rm_test.go
pkg/cmd/pulumi/config/config_env_test.go
pkg/cmd/pulumi/config/io.go
pkg/cmd/pulumi/config/io_test.go
pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/env.go
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/logs.go
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/pulumi.go
pkg/cmd/pulumi/refresh.go
pkg/cmd/pulumi/up.go
pkg/cmd/pulumi/watch.go

Continuing with the clean-up of `pkg/cmd/pulumi`, this factors out the `config ...` hierarchy, along with shared functions that are used by other commands for loading configuration.

Break out `config ...` commands into their own package

---

pkg/cmd/pulumi/cmd/terminal.go
pkg/cmd/pulumi/cmd/terminal_test.go
pkg/cmd/pulumi/login.go
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/policy_new.go
pkg/cmd/pulumi/pulumi.go
pkg/cmd/pulumi/refresh.go
pkg/cmd/pulumi/state/io.go
pkg/cmd/pulumi/state/state.go
pkg/cmd/pulumi/state/state_delete.go
pkg/cmd/pulumi/state/state_delete_test.go
pkg/cmd/pulumi/state/state_edit.go
pkg/cmd/pulumi/state/state_edit_encoder.go
pkg/cmd/pulumi/state/state_edit_test.go
pkg/cmd/pulumi/state/state_move.go
pkg/cmd/pulumi/state/state_move_test.go
pkg/cmd/pulumi/state/state_rename.go
pkg/cmd/pulumi/state/state_rename_test.go
pkg/cmd/pulumi/state/state_repair.go
pkg/cmd/pulumi/state/state_repair_render.go
pkg/cmd/pulumi/state/state_repair_test.go
pkg/cmd/pulumi/state/state_unprotect.go
pkg/cmd/pulumi/state/state_upgrade.go
pkg/cmd/pulumi/state/state_upgrade_test.go
pkg/cmd/pulumi/util.go

This commit factors the `state ...` command hierarchy into its own `state` subpackage, continuing the clean up of `pkg/cmd/pulumi`.

Break out the `state ...` command hierarchy

---

pkg/engine/update.go

Remove unused function

---

changelog/pending/20241203--cli--autonaming-configuration-in-experimental-mode.yaml
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/up.go
pkg/engine/deployment.go
pkg/engine/update.go
pkg/go.mod
pkg/resource/autonaming/config.go
pkg/resource/autonaming/config_test.go
pkg/resource/autonaming/json.go
pkg/resource/autonaming/pattern.go
pkg/resource/autonaming/pattern_test.go
pkg/resource/autonaming/strategy.go
pkg/resource/autonaming/strategy_test.go
pkg/resource/deploy/deployment.go
pkg/resource/deploy/step_generator.go
sdk/go/common/resource/plugin/provider.go
sdk/go/common/resource/plugin/provider_plugin.go
sdk/go/common/resource/plugin/provider_server.go
tests/integration/autonaming/Pulumi.yaml
tests/integration/autonaming/index.ts
tests/integration/autonaming/package.json
tests/integration/integration_nodejs_test.go
tests/testprovider/main.go
tests/testprovider/named.go

CLI-side implementation of #17592 towards #1518
It adds autonaming configuration support to `up` and `preview` commands if the `PULUMI_EXPERIMENTAL` flag is enabled. Users can specify `pulumi:autonaming` configuration and get names customized across their resources, once the provider-side feature lands everywhere. Example:
```yaml
pulumi:autonaming:
mode: default
providers:
aws:
pattern: ${name}_${hex(4)}  # AWS - use underscore and shorter suffix
azure-native:
mode: verbatim  # disable name mangling for Azure
resources:
"azure-native:storage:Account": ${name}${string(6)}  # storage accounts are globally unique, so add a suffix
```
All the significant changes are isolated inside the new `pkg/resource/autonaming` module, all the rest is wiring of parameters from cmd to provider.
See #17592 …

Autonaming configuration in experimental mode

---

changelog/pending/20241210--sdk-go--fix-a-defer-leak-when-writing-memory-profiles.yaml
sdk/go/common/util/cmdutil/profile.go

This fixes a defer leak that has been added during the review of #17461.
Calling defer in a loop allocates memory (stack or heap depending on the Go version) and doesn't execute the deferred functions until the loop is over.
In this case, since the loop runs forever, it would be even worse.
This commit proposes as fix to simply remove the defer and move the close to its original place in the first iteration of the PR. This is safe to do since there are no retuns in-between.
We could also refactor the loop to call instead writeMemoryProfile (as was suggested in the PR review). In that case, if the defer is inside writeMemoryProfile, then it can be safely called from the loop.
More info about Go defer: https://victoriametrics.com/blog/defer-in-go/

cmdutil/profile: do not defer in loop

---

pkg/cmd/pulumi/convert.go
pkg/cmd/pulumi/diag/diag.go
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/package_gen_sdk.go

Currently we have some shared code for handling diagnostics between commands like `gen-sdk` and `convert`. This commit factors this out into a `diag` subpackage so that these command hierarchies can be split without introducing circular dependencies.

Break out diagnostic printing functions in `pkg/cmd`

---

pkg/cmd/pulumi/packagecmd/package.go
pkg/cmd/pulumi/packagecmd/package_add.go
pkg/cmd/pulumi/packagecmd/package_extract_mapping.go
pkg/cmd/pulumi/packagecmd/package_extract_schema.go
pkg/cmd/pulumi/packagecmd/package_gen_sdk.go
pkg/cmd/pulumi/packagecmd/package_pack_sdk.go
pkg/cmd/pulumi/packagecmd/package_publish.go
pkg/cmd/pulumi/pulumi.go

Continuing with the clean-up of `pkg/cmd/pulumi`, this factors out the `package ...` hierarchy.

Break out the `package ...` command hierarchy

---

pkg/cmd/pulumi/deployment/deployment.go
pkg/cmd/pulumi/deployment/deployment_run.go
pkg/cmd/pulumi/deployment/deployment_settings_config.go
pkg/cmd/pulumi/deployment/deployment_settings_config_test.go
pkg/cmd/pulumi/deployment/deployment_settings_ops.go
pkg/cmd/pulumi/deployment/deployment_settings_utils.go
pkg/cmd/pulumi/deployment/deployment_settings_utils_test.go
pkg/cmd/pulumi/deployment/remote.go
pkg/cmd/pulumi/deployment/remote_test.go
pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/pulumi.go
pkg/cmd/pulumi/refresh.go
pkg/cmd/pulumi/up.go

Continuing with the clean-up of `pkg/cmd/pulumi`, this factors out the `deployment ...` hierarchy.

Break out the `deployment ...` command hierarchy

---

changelog/pending/20241210--engine--warn-if-refresh-or-destroy-use-older-plugins.yaml
pkg/engine/destroy.go
pkg/engine/plugins.go
pkg/engine/plugins_test.go
pkg/engine/refresh.go

`refresh` and `destroy` operations do not run the user program, and instead rely on the plugin versions specified in the state. This can lead to confusing behavior where a user has updated a provider dependency in their program, but these operations ignore that setting. This change prints a warning if either of these operations will use an older plugin version than the one specified in the program dependencies.
> [!NOTE]  
> This may be redundant once a fix for #12177 lands.

Warn if `refresh` or `destroy` use older plugins

---

pkg/cmd/pulumi/packagecmd/package_gen_sdk.go

This is a small UX improvement:
Before:
```
𝛌 pulumi package gen-sdk --language typescript terraform-provider registry.opentofu.org/Azure/alz 0.11.1
Downloading provider: terraform-provider
```
After:
```
𝛌 pulumi package gen-sdk --language typescript terraform-provider registry.opentofu.org/Azure/alz 0.11.1
Downloading provider: terraform-provider
SDKs have been written to ./sdk
```

`pulumi package gen-sdk`: Write where the SDK was generated to

---

pkg/cmd/pulumi/plugin/plugin.go
pkg/cmd/pulumi/plugin/plugin_install.go
pkg/cmd/pulumi/plugin/plugin_install_test.go
pkg/cmd/pulumi/plugin/plugin_ls.go
pkg/cmd/pulumi/plugin/plugin_rm.go
pkg/cmd/pulumi/plugin/plugin_run.go
pkg/cmd/pulumi/pulumi.go

Continuing with the clean-up of `pkg/cmd/pulumi`, this factors out the `plugin ...` hierarchy.

Break out the `plugin ...` command hierarchy

---

pkg/cmd/pulumi/pulumi.go
pkg/cmd/pulumi/trace/convert.go
pkg/cmd/pulumi/trace/io.go
pkg/cmd/pulumi/trace/view.go

Continuing with the clean-up of `pkg/cmd/pulumi`, this factors out the `convert-trace` and `view-trace` commands into a `trace` subpackage.

Break out `*-trace` commands

---

changelog/pending/20241211--sdk-go--return-when-resolving-rejecting-the-invokeoutput-output.yaml
sdk/go/pulumi/context.go
sdk/go/pulumi/context_test.go

This does not seem to cause any issues because Output guards against double calls, but we should return after rejecting/returning and not rely on output being defensive.

Return when rejecting the InvokeOutput output on error

---

codecov.yml

This PR sets the target coverage for net-new code in PR to 80%. The check will fail if patch coverage is below that. I've set threshold to 5% to allow some minimal drop in coverage if the overall goal is still achieved.
We'll have to learn what the exact numbers should be over time, but this is a start.
When the check fails, the GH experience will look like this:
Note that:
1. "Merge when ready" button is not green but it's also not disabled, so we can merge without the check succeeding. We shouldn't normally do this, but we can for situations when we explicitly deem this check unhelpful.
2. Cove coverage checks will only appear if all tests succeed and coverage data is uploaded to codecov.
3. There is a small delay between ci-ok check succeeding and code coverage appearing.
4. If a PR is …

Fail codecov CI check based on patch coverage goal

---

cmd/pulumi-test-language/test_host.go
pkg/engine/plugins.go

gatherPluginsFromProgram historically would return the language plugin as well as provider plugins. Nothing in the system made use of that language plugin, and making this function just return providers makes it a lot clearer on changing this to return "packages" rather than "plugins" for parameterization support.

Only return providers from gatherPluginsFromProgram

---

sdk/python/cmd/pulumi-language-python/main.go

There is an [issue](https://github.com/pulumi/pulumi/issues/18023) with `pulumi-plugin.json` not being read when using the `uv` package manager. This is a quick fix to treat esc-sdk as a non-plugin
Fixes https://github.com/pulumi/esc-sdk/issues/57

Quick fix to treat esc-sdk as a non-plugin

---

cmd/pulumi-test-language/grpc.go
cmd/pulumi-test-language/interface.go
cmd/pulumi-test-language/interface_test.go
cmd/pulumi-test-language/tests.go
cmd/pulumi-test-language/tests/assert.go
cmd/pulumi-test-language/tests/types.go

This commit moves the core of the conformance testing framework into a `tests` subpackage. From here, the plan would be to split out e.g. `tests/l1_empty.go` etc. to factor out the tests themselves, since `tests.go` and the `languageTests` array is getting quite big at this point. Having the tests factored a bit better might also open the door for discussing per-test providers and the like (though this may not be feasible).

Factor out conformance testing framework

---

pkg/cmd/pulumi/auth/login.go
pkg/cmd/pulumi/auth/logout.go
pkg/cmd/pulumi/pulumi.go

Continuing with the clean-up of `pkg/cmd/pulumi`, this factors out the `login` and `logout` commands into an `auth` subpackage.

Break out the `login` and `logout` commands

---

changelog/pending/20241212--programgen-dotnet--emit-local-dependencies-in-restore-sources-deterministically.yaml
pkg/codegen/dotnet/gen.go
pkg/codegen/dotnet/gen_program.go

Required for https://github.com/pulumi/pulumi-dotnet/pull/314 we need the generated restore sources to be emitted deterministically so that the generated code and tests are stable between local and CI runs

[codegen/dotnet] Emit local dependencies in restore sources deterministically

---

pkg/cmd/pulumi/logs/logs.go
pkg/cmd/pulumi/logs/logs_test.go
pkg/cmd/pulumi/pulumi.go

Continuing with the clean-up of `pkg/cmd/pulumi`, this factors out the `logs` command into its own subpackage.

Break out the `logs` command

---

changelog/pending/20241206--cli-plugin--log-plugin-unstructured-output-to-debug-instead-of-info.yaml
sdk/go/common/resource/plugin/plugin.go
tests/integration/integration_go_test.go

This commit changes the log level from plugin stdout&stderr to debug, from info. This
change is significant because info is shown by default to users, but debug is not. While
this is a change of plugin aesthetics, it does not effect any runtime behavior. All
plugins, both component providers and custom resource providers, are effected.
> [!IMPORTANT]
> This is a breaking change, in that information which used to be displayed to users will
> now be hidden by default.
>
> We will need to share this change with our users before rolling it out.
The providers team has met and believe that this is the best approach for our
ecosystem. For a full discussion on why this change is necessary, see
[this doc](https://docs.google.com/document/d/1yYrwTwsNoayaIzKyG1l5cl0MjJxiHLsH4NqAvZkQN-I/edit?tab=t.0#h …

Log Plugin stdout & stderr as debug (instead of info)

---

changelog/pending/20241205--auto-go--add-configfile-to-getconfig-and-setconfig-operations.yaml
sdk/go/auto/local_workspace.go
sdk/go/auto/local_workspace_test.go
sdk/go/auto/stack.go
sdk/go/auto/workspace.go

Add ConfigFile to ConfigOptions for GetConfig and SetConfig operations to allow for users to specify a config file to read and write to during these operations.
Add a new GetAllConfigWithOptions function to allow users to specify a config file to read from and also if they want to show secrets
Error handling has been added to operations that do not support specific config options such as SetAllConfigWithOptions returning a newAutoError if ShowSecrets is set to true in the ConfigOptions.
GetAllConfig has been refactored to use the new GetAllConfigWithOptions function to follow the pattern the other functions are using.
Test cases have been added to test the new functionality and error handling and also to verify that the GetallConfig refactor works as it previously did.

Add ConfigFile to GetConfig and SetConfig Ops In Go Automation API

---

.github/workflows/download-pulumi-cron.yml

This was originally included in the download cron workflow, but had to be removed because there wasn't a reliable way to use the winget CLI from GitHub's runners. There's now a GitHub Action available for installing the winget CLI, which we should be able to use now for this.
I temporarily set up the workflow to run on PRs (now removed). You can see a successful run here: https://github.com/pulumi/pulumi/actions/runs/10407763146/job/28823717019?pr=16980
Fixes #11342

Add winget install test back to download cron workflow

---

changelog/pending/20241213--cli-install--avoid-unnecessary-node-js-installations.yaml
sdk/nodejs/cmd/pulumi-language-nodejs/main.go
sdk/nodejs/cmd/pulumi-language-nodejs/main_test.go

When running `pulumi install --use-language-version-tools`, and `fnm` is installed on the system, we will automatically install the Node.js version specified in `.nvmrc` or `.node-version`.
When the file does not specify the full version, for example `22`, we would always install the latest release of Node.js 22, even if another point release of Node.js 22 is already present on the system. This is unnecessary, and we should use the available version.
This mostly affects Pulumi Deployments, where this installation flag is used by default. Whenever we release a new version of Pulumi, we also release new versions of the docker containers. These containers include the latest version of Node.js (22, and other versions) at the time of release, so the pre-installed version is usually very …

Avoid unnecessary Node.js installations

---

changelog/pending/20241213--sdkgen-dotnet--compute-restore-sources-from-local-dependencies-and-referenced-packages.yaml
pkg/codegen/dotnet/gen.go
pkg/codegen/utilities_test.go
pkg/codegen/utilities_types.go

When emitting the restore sources from local dependencies in .NET which are local nuget packages, we should only add the relevant ones:
- `pulumi` core sdk if it is part of the local dependencies
- any other package that is referenced by the schema and is also part of the local dependencies
Replaces #18035 
Required for https://github.com/pulumi/pulumi-dotnet/pull/314

[sdkgen/dotnet] Compute restore sources from local dependencies and referenced packages

---

cmd/pulumi-test-language/tests/l2_resource_alpha.go
cmd/pulumi-test-language/tests/l2_resource_asset_archive.go
cmd/pulumi-test-language/tests/l2_resource_config.go
cmd/pulumi-test-language/tests/l2_resource_parent_inheritance.go
cmd/pulumi-test-language/tests/l2_resource_primitives.go
cmd/pulumi-test-language/tests/l2_resource_secret.go
cmd/pulumi-test-language/tests/l2_resource_simple.go
cmd/pulumi-test-language/tests/tests.go

This change breaks out the L2 `resource-*` conformance tests into their own files.

Break out L2 resource conformance tests

---

changelog/pending/20241216--sdkgen-go--skip-testpackageaddgoparameterized.yaml
tests/integration/integration_go_test.go

This test is failing after 0.4.0 of pulumi-terraform-provider was released
Unskipping tracked in https://github.com/pulumi/pulumi/issues/18048

Skip TestPackageAddGoParameterized

---

proto/.checksum.txt
proto/pulumi/provider.proto
sdk/nodejs/proto/provider_grpc_pb.js
sdk/proto/go/provider.pb.go
sdk/proto/go/provider_grpc.pb.go
sdk/python/lib/pulumi/runtime/proto/provider_pb2.pyi
sdk/python/lib/pulumi/runtime/proto/provider_pb2_grpc.py
sdk/python/lib/pulumi/runtime/proto/provider_pb2_grpc.pyi

Resolves #17612 - we had two incidents caused by a mismatch of expectations between the engine and a provider on how `Diff` should behave exactly.
In a way a follow-up to #17683.

Document provider Diff response requirements

---

pkg/cmd/pulumi/console/console.go
pkg/cmd/pulumi/pulumi.go

Continuing with the clean-up of `pkg/cmd/pulumi`, this factors out the `console` command.

Break out the `console` command

---

pkg/cmd/pulumi/cancel/cancel.go
pkg/cmd/pulumi/pulumi.go

Continuing with the clean-up of `pkg/cmd/pulumi`, this factors out the `cancel` command.

Break out the `cancel` command

---

changelog/pending/20241216--sdk-python--fix-hang-on-error-when-using-uv-on-windows.yaml
sdk/python/toolchain/pip.go
sdk/python/toolchain/toolchain.go
sdk/python/toolchain/uv.go
tests/integration/integration_python_acceptance_test.go
tests/integration/python/uv-with-error/Pulumi.yaml
tests/integration/python/uv-with-error/__main__.py
tests/integration/python/uv-with-error/pyproject.toml

When using uv we were running Python as `uv run python`, since that conveniently
handles the virtualenv for us. This results in a process tree of
`python-language-runtime -> uv -> python`. This is problematic because on error
we kill the plugin and its children, but not the children of the children. On
macOS and Linux, when uv is killed, it kills its children, so we have no problem
here. On Windows however, it does not, and we end up with an orphaned Python
process that's busy-waiting in the eventloop and never exits.
To avoid this issue, we run Python the same way as we do when using Poetry or Pip.
Fixes https://github.com/pulumi/pulumi/issues/17877

Fix hang on error when using uv on Windows

---

pkg/cmd/pulumi/install/install.go
pkg/cmd/pulumi/pulumi.go

Continuing with the clean-up of `pkg/cmd/pulumi`, this factors out the `install` command.

Break out the `install` command

---

pkg/cmd/pulumi/pulumi.go
pkg/cmd/pulumi/schema/schema.go
pkg/cmd/pulumi/schema/schema_check.go

Continuing with the clean-up of `pkg/cmd/pulumi`, this factors out the `schema ...` hierarchy.

Break out the `schema ...` hierarchy

---

sdk/go/common/tail/tail_test.go

If we remove the file tail is reading before we call `tail.Stop()`, the latter may or may not return an error depending on what state it is in.  Fix this by asserting that there is no error, and removing the file after calling `tail.Stop()`.

fix racy TestBlockUntilExists test

---

pkg/backend/diy/state.go

We're currently trying to backup files unconditonally in this function.  However the file doesn't necessarily exist when we call it (by design).
In the future we want to introduce retries for at least the bucket.Delete function, so calling that on a file that doesn't exist would slow down the process.  It really only makes sense to create a backup if the file does actually exist, so do that.  If we get an error back from the exists function we still go ahead and try to create the backup anyway.
This needs to be merged before https://github.com/pulumi/pulumi/pull/18059

don't make backups if the object doesn't exist

---

pkg/testing/integration/program.go

`ProgramTestOptions` has this option:
```go
// PreviewCommandlineFlags specifies flags to add to the `pulumi preview` command line (e.g. "--color=raw")
PreviewCommandlineFlags []string
```
However, ProgramTest runs `preview` twice, once before create and then after refresh. The second run ignores `PreviewCommandlineFlags` which I assume was an oversight. This PR fixes that.
The concrete use case is that I was working on a test where the second preview run failed but it didn't tell me why; just "_no changes were expected but changes were proposed_". With this PR I was able to add `UpdateCommandlineFlags:  []string{"--diff"}` to my test and saw the property that changed unexpectedly.

Honor opts.PreviewCommandlineFlags in preview after refresh

---

changelog/pending/20241217--backend-diy--retry-deletes-of-lock-files-if-they-fail.yaml
pkg/backend/diy/bucket.go
pkg/backend/diy/bucket_test.go

Cloud infrastructure can occasionally hiccup.  This can be noticable when we try to delete a lock file from a bucket, and the delete fails. In that case we currently just error out, making the user to a `pulumi cancel` later.
We can do better here and actually retry the delete a few times with backoff.  This should work around temporary hiccups.  Deletes are an operation that should always be safe to retry, as even if an earlier request goes through, the object can't be deleted twice.
Fixes https://github.com/pulumi/pulumi/issues/17876

retry deletes in a bucket if they fail

---

pkg/cmd/pulumi/pulumi.go
pkg/cmd/pulumi/query/query.go

Continuing with the clean-up of `pkg/cmd/pulumi`, this factors out the `query` command.

Break out the `query` command

---

sdk/go/common/tail/tail.go
sdk/go/common/tail/tail_test.go

In https://github.com/pulumi/pulumi/pull/18044 we vendored the nxadm/tail library and pulled in a couple of changes from upstream to avoid race conditions.
However the changes from upstream were not sufficient. Namely, one of the changes was to try and avoid exiting early if tail is meant to stop at the next EOF.  It did so by setting the earlyExitChan to `nil` if tail was requested to shut down with a stopAtEOF error. However it is possible that stopAtEOF is written to the earlyExitChan after we checked `tail.Err()`, but before we get to the select.
In that case we can still get an early exit on EOF, which we don't want.  Move the check for the stopAtEOF error into the earlyExitChan case. At this point tail.Err() is guaranteed to be set correctly, if the user requested a stop at eof. …

fix race condition in tail better

---

pkg/cmd/pulumi/env/env.go
pkg/cmd/pulumi/pulumi.go

Continuing with the clean-up of `pkg/cmd/pulumi`, this factors out the `env` command.

Break out the `env` command

---

pkg/cmd/pulumi/completion/gen.go
pkg/cmd/pulumi/markdown/gen.go
pkg/cmd/pulumi/pulumi.go

This commit finishes the clean-up of `pkg/cmd/pulumi`, breaking out the `gen-completion` and `gen-markdown` commands.

Break out remaining commands

---

changelog/pending/20241212--engine--change-loader-server-to-use-package-load-v2-so-it-can-include-paramaterization.yaml
pkg/codegen/schema/loader_server.go

This change is required to support parameterization of providers.
It is part of the work required for pulumi/pulumi#18019

Use LoadPackageV2 in loader server

---

.gitattributes

These files show up in PRs all the time, and clutter PRs making them harder to read.  According to
https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github, we can use this gitattribute to make them not show up in diffs (which I think means they are collapsed in PR reviews).

add hide lifecycletest testdata in diffs by default

---

sdk/go/common/util/cmdutil/term_test.go

It looks like python is occasionally slow in CI, so allow some extra time for it to shut down to hopefully fix the flake.
Also make the "Took too long to kill child process" case take a little longer, so we can actually observe what happens in TerminateProcessGroup and the following asserts, rather than shutting the test down.  The test is still correct, as if we're hitting the 400ms timeout the first assert in the goroutine will trigger.
Fixes https://github.com/pulumi/pulumi/issues/18074

unflake unhandledInterrupt test

---

changelog/pending/20241219--auto-go--fix-debug-flag-in-automation-api.yaml
sdk/go/auto/stack.go

Append debug flags after subcommand to account for non global flags like "debug"
Fixes #15305

Append debug flags after subcommand to account for non global flags like "debug"

---

changelog/pending/20241212--engine--warn-if-refresh-or-destroy-use-older-parameterized-packages.yaml
pkg/engine/destroy.go
pkg/engine/plugins.go
pkg/engine/plugins_test.go
pkg/engine/refresh.go
pkg/engine/update.go
pkg/resource/deploy/providers/provider.go
pkg/resource/deploy/providers/registry.go
sdk/go/common/workspace/plugins.go
tests/smoke_test.go

This updates the warnings added by https://github.com/pulumi/pulumi/pull/12196 to also warn about updates to parameterized packages, not just plugins. 
Before this the warning would kick in if the underlying parameterised plugin was updated (e.g. terraform-provider went from 0.3.0 to 0.3.1) but it wouldn't warn if the user had regenerated the parameterised package (e.g hashicorp/random 3.6.0 to hashicorp/random 3.6.3). This change fixes it so the later will now print the expected warning.
It also fixes it so the warning refers to the package name, not the plugin name (i.e. in the above terraform random example we print 'random 3.6.3' not 'terraform-provider 0.3.1').
Part of https://github.com/pulumi/pulumi/issues/17507

Update the refresh/destroy warnings for parameterized packages

---

.github/workflows/pr-test-codegen-downstream.yml

This has been broken for a while because the AWSX repo works differently from the bridge providers and has changed since the workflow was originally setup. https://github.com/pulumi/pulumi/issues/16954 tracks re-enabling.

Temporarily skip downstream AWSX test

---

changelog/pending/20241213--cli-install--avoid-unnecessary-node-js-installations.yaml
changelog/pending/20241220--sdk-nodejs--reverts-18041.yaml
sdk/nodejs/cmd/pulumi-language-nodejs/main.go
sdk/nodejs/cmd/pulumi-language-nodejs/main_test.go

Reverts pulumi/pulumi#18041
We can't use `fnm use` in an environment without a persistent shell.

Revert "Avoid unnecessary Node.js installations"

---

changelog/pending/20241220--auto-go--return-error-if-no-inline-program-specified.yaml
sdk/go/auto/local_workspace.go
sdk/go/auto/local_workspace_test.go

The fix is described by Fraser here: https://github.com/pulumi/pulumi/issues/15877#issuecomment-2076785682
In summary the program uses the current directory as the project directory to run instead of an inline program when one is not specified. This causes pulumi up to be invoked in the current directory (again), potentially causing an infinite loop.
Fixes #15877

Fix infinite looping of calls of pulumi program when missing inline program

---

changelog/pending/20241222--auto-go--support-clear-pending-creates-to-go-automation-api-previewrefresh-and-refresh.yaml
sdk/go/auto/optrefresh/optrefresh.go
sdk/go/auto/stack.go
sdk/go/auto/stack_test.go

Support `--clear-pending-creates` for `refresh` command in Go Automation API.

---

changelog/pending/20241220--cli-new--provide-a-better-error-message-when-pulumi-new-ai-generates-a-program-with-errors.yaml
sdk/go/common/workspace/templates_zip.go
sdk/go/common/workspace/templates_zip_test.go

When trying to download a ZIP (e.g. for an AI response in pulumi new), we currently don't check the response code, and just feed whatever we are getting from the server into the zip parser.  The AI at the same time response with a 500 if the program it generated is not valid, which is always a possibility with LLMs.
This results in confusing error messages when the AI fails to generate a correct program: "error: failed to retrieve zip archive: zip: not a valid zip file".
We can do better here, and check the error code.  Helpfully Pulumi AI also tells us what is wrong in the response body, so we can include that in the error message.
This results in an error message like (in a failing example I tried):
```
error: failed to retrieve zip archive: failed to download template: 500 Internal …
```

return a meaningful error when getting a zip template fails

---

changelog/pending/20241220--cli-new--provide-a-more-meaningful-message-for-the-language-flag.yaml
pkg/cmd/pulumi/newcmd/new.go

The `--language` flag in `pulumi new` implies using Pulumi AI.
However this is not super clear for users, so let's return a better
error message that points users in the right direction, to either log
in to Pulumi Cloud to be able to use Pulumi AI, or use a different flag.
Fixes https://github.com/pulumi/pulumi/issues/15003

return a more meaningful message for new --language

---

changelog/pending/20241223--sdk-go--fix-panic-when-diffing-computed-property-values.yaml
sdk/go/common/resource/properties_diff.go
sdk/go/common/resource/properties_diff_test.go

In property diff we currently don't treat computed values.  This means we're going to try to compare them with `==`, which panics.  Allow computed property values to be diffed correctly.
Fixes https://github.com/pulumi/pulumi/issues/14619

property diff: avoid panic'ing when computed values are present

---

changelog/pending/20241223--cli-engine--clarify-the-usage-string-for-the-expect-no-changes-flag.yaml
pkg/cmd/pulumi/operations/refresh.go
pkg/cmd/pulumi/operations/up.go

When using --expect-no-changes in pulumi up and pulumi refresh, the CLI applies the changes first, and then checks if there were any later, only erroring out at that point, after having applied the changes.
This is currently not very clear from either the name of the flag, nor the usage string.  Improve the usage string to make this clearer.
We could  potentially also "rename" this flag, by hiding the one with the old name, and introducing a new one doing the same thing, which would be a backwards compatible change.  I couldn't come up with a better name for the flag though (error-on-changes is the best I could come up with, but I don't think it conveys this any better).
Fixes https://github.com/pulumi/pulumi/issues/10967

clarify usage string for --expect-no-changes

---

changelog/pending/20241224--programgen-go--fix-importing-module-names-in-go-programs-that-arent-lower-case.yaml
pkg/cmd/pulumi/convert/convert.go
pkg/codegen/go/gen_program.go
tests/testdata/codegen/synthetic-resource-properties-pp/go/synthetic-resource-properties.go

When importing provider modules in Go programs, we must make sure the module is in lowercase 
Fixes #14845

[programgen/go] Fix importing module names that aren't lower-case

---

changelog/pending/20241227--sdk-python--move-pyright-configuration-into-pyproject-toml.yaml
sdk/python/cmd/pulumi-language-python/main.go
sdk/python/pyproject.toml
sdk/python/pyrightconfig.json

Now that we have a pyproject.toml, we can move the configuration for most python tools there, instead of having separate files for each tool.

Move pyright configuration into pyproject.toml

---

sdk/go/common/resource/plugin/plugin.go

Noticed this while doing some tests with a new provider that was crashing on startup. `plugin.Close` can get called before `Conn` is set, leading to a nil access violation trying to get the connection state.

Fix nil access violation in plugin.Close

---

sdk/python/lib/test/automation/test_errors.py
sdk/python/lib/test/automation/test_isolation.py
sdk/python/lib/test/automation/test_local_workspace.py
sdk/python/lib/test/automation/test_utils.py

Similar to the nodejs automation API tests in
https://github.com/pulumi/pulumi/pull/17393, we also want to be able to run the python tests using the DIY backend, rather than just the cloud backend.  The only changes necessary here are making sure we use the right organization name (which is always "organization" for the DIY backend), and making sure the stacks are removed forcefully (for some reason they seem to think they have resources, even if the up fails with a compilation error).
When PULUMI_ACCESS_TOKEN is set, the tests will still run with the cloud backend.
Making progress towards https://github.com/pulumi/pulumi/pull/17192

make python auto api tests work with DIY backend

---

pkg/cmd/pulumi/convert/convert.go
pkg/cmd/pulumi/operations/import.go
pkg/cmd/pulumi/plugin/plugin_install.go
pkg/cmd/pulumi/plugin/plugin_run.go
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_test.go

We want to be able to get plugins from arbitrary git repositories.  To do this, we need to parse the URL we get passed, so we can resolve it properly.
Introduce a new NewPluginSpec helper to do that, so we can use it consistently throughout the codebase.
Also extend this method to recognize such plugin names, and deal with them appropriately, setting the `PluginDownloadURL`, and specifying that this is a remote plugin.
Note that we also need to mangle the names slightly, as `/` will create new subfolders on the filesystem, which doesn't work well with our current plugin detection mechanisms.  Rather than trying to make that work, replace them with `_`, which currently cannot be used in plugin names, and thus are safe to re-use here.
This is the first step towards allowing users to specify …

add NewPluginSpec helper function

---

changelog/pending/20241230--sdk-python--fix-dynamic-providers-when-using-poetry-or-uv.yaml
sdk/python/dist/pulumi-resource-pulumi-python
sdk/python/dist/pulumi-resource-pulumi-python.cmd
tests/integration/integration_python_test.go
tests/integration/python/dynamic-provider/pip/Pulumi.yaml
tests/integration/python/dynamic-provider/pip/__main__.py
tests/integration/python/dynamic-provider/poetry/Pulumi.yaml
tests/integration/python/dynamic-provider/poetry/__main__.py
tests/integration/python/dynamic-provider/uv/Pulumi.yaml
tests/integration/python/dynamic-provider/uv/__main__.py

Use the correct virtual environment when starting the python interpreter for dynamic providers. The `virtualenv` option is not set when using Poetry or uv. Look at the `toolchain` option instead to determine the path to the virtual environment.

Fix dynamic providers when using Poetry or uv

---

changelog/pending/20250103--sdk-python--avoid-calling-invokes-with-dependencies-on-unknown-resources.yaml
sdk/python/lib/pulumi/runtime/_depends_on.py
sdk/python/lib/pulumi/runtime/invoke.py
sdk/python/lib/pulumi/runtime/resource.py
sdk/python/lib/pulumi/runtime/rpc.py
sdk/python/lib/test/test_invoke.py

Python implementation of https://github.com/pulumi/pulumi/pull/18133
DependsOn for resources is an ordering constraint for register resource calls. If a resource R1 depends on a resource R2, the register resource call for R2 will happen after R1. This is ensured by awaiting the URN for each resource dependency before calling register resource.
For invokes, this causes a problem when running under preview. During preview, register resource immediately returns with the URN, however this does not tell us if the resource "exists".
Instead of waiting for the dependency's URN, we wait for the ID. This tells us that whether a physical resource exists (if the state is in sync), and we can avoid calling the invoke when it is unknown.
The following example fails without this change:
```python …
```

Avoid calling invokes with dependencies on unknown resources

---

sdk/nodejs/runtime/dependsOn.ts
sdk/nodejs/runtime/resource.ts
sdk/nodejs/runtime/rpc.ts

This PR has no functional changes. We want to use this function in invokes, move it to the dependsOn package in preparation of that.

Move getAllTransitivelyReferencedResourceURNs to dependsOn

---

sdk/go/auto/cmd_test.go
sdk/go/auto/testdata/slow/main.go

If this test takes more than 2 seconds to start the pulumi operation it fails. Instead of relying on timing, have the test program write a sentinel file that we look for. This lets us reliably wait for the correct test conditions, even on overlaoded GHA runners.

Unflake TestRunCanceled

---

cmd/pulumi-test-language/tests/l2_map_keys.go
cmd/pulumi-test-language/tests/l2_provider_grpc_config.go

These got lost during the reorganisation of conformance tests, possibly due to a bad merge conflict, so this puts them back.

Re-add `l2-map-keys` and `l2-provider-grpc-config`

---

changelog/pending/20250107--cli-plugin--show-plugin-kind-in-plugin-rm-correctly-also-show-the-usage-string-if-the-plugin-type-is-incorrect.yaml
pkg/cmd/pulumi/plugin/plugin_rm.go

Currently when the user uses an unrezognized plugin type in `pulumi plugin rm` we currently just show
```
error: unrecognized plugin kind:
```
This is unintuitive, and unintended, as we only check the plugintype after printing the error message.
To further help the user also print the ussage string.
Fixes https://github.com/pulumi/pulumi/issues/18144

plugin rm: show unrecognized kind correctly and usage string

---

changelog/pending/20250108--auto-go--add-color-option-to-optdestroy-optpreview-optrefresh-and-optup-packages-to-allow-explicit-configuration-of-output-color.yaml
sdk/go/auto/optdestroy/optdestroy.go
sdk/go/auto/optpreview/optpreview.go
sdk/go/auto/optrefresh/optrefresh.go
sdk/go/auto/optup/optup.go

Currently, the Options struct has a field for color, but there is not functions exposed to set this field in go. This change adds the ability to set the color setting for output. optdestroy, optpreview, optrefresh, and optup all have a new function to set the color setting.
To use the new color setting, you can set the color field in the Options struct like the following:
```go
_, err = s.Up(ctx, stdoutStreamer, optup.Color("always"))
fmt.Printf("Failed to update stack: %v\n\n", err)
os.Exit(1)
}
```
Fixes https://github.com/pulumi/pulumi/issues/18183

go automation api support for colorize output

---

tests/integration/integration_go_test.go

The terraform converter relies on v0.6.0 of the resource plugin.  Pin that to fix the test.

fix TestConvertTerraformProviderGo test

---

pkg/codegen/dotnet/gen_program.go
pkg/codegen/dotnet/gen_program_expressions.go
pkg/codegen/go/gen_program.go
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/hcl2/model/type_object.go
pkg/codegen/hcl2/model/type_test.go
pkg/codegen/pcl/binder_schema.go
pkg/codegen/pcl/invoke.go
pkg/codegen/pcl/utilities.go

In our model of PCL based on HCL syntax, we define a number of types according to Pulumi's type system. Among these is `ObjectType`, the type of objects of the form `{ k_1: t_1, ..., k_n: t_n }`, where each key `k_i` maps to a nested type `t_i`. Object types crop up all over the place -- as sets of resource input properties, resource outputs themselves, and as arguments to function calls, for instance.
Because object types are so prevalent, it is often useful to be able to link them to metadata about their intended use. For instance, in code generation, we might like to know if an object type corresponds to a "bare" object literal or an instance of some named class. To this end, object types support _annotations_, and such annotations are used in e.g. .Net and Python codegen as hinted …

Clean up and test PCL object type annotations

---

changelog/pending/20250110--auto-go--fix-rejection-of-nil-inline-programs-in-the-go-automation-api.yaml
sdk/go/auto/local_workspace.go
sdk/go/auto/local_workspace_test.go

This reverts commit 119057414d3598fbab20b7878558baf8f29602a5. Introduced in #18086, this commit introduced a check for `nil` inline programs when running Go automation API functions, which fixed the original issue but has unfortunately created a breaking change in cases where there is a legitimate need to pass a `nil` program (such as to a `destroy` operation).
Fixes #18213
Reopens #15877

Revert "Fix infinite looping of calls of pulumi program when missing inline program (#18086)"

---

changelog/pending/20250109--sdk-nodejs-python--wait-for-resource-in-the-input-property-dependencies.yaml
sdk/nodejs/runtime/invoke.ts
sdk/nodejs/tests/runtime/langhost/cases/078.invoke_output_input_dependencies/index.js
sdk/nodejs/tests/runtime/langhost/run.spec.ts
sdk/python/lib/pulumi/runtime/invoke.py
sdk/python/lib/test/test_invoke.py

Besides the explicitly provided resources from the `dependsOn` option, we need to also take into account the resource dependencies from the invoke’s arguments.

Wait for resources in the input property dependencies

---

changelog/pending/20250108--sdk-python--fix-callbackserver-shutdown.yaml
sdk/python/lib/pulumi/runtime/_callbacks.py
tests/integration/integration_python_test.go
tests/integration/python/excepthook/.gitignore
tests/integration/python/excepthook/Pulumi.yaml
tests/integration/python/excepthook/__main__.py
tests/integration/python/excepthook/requirements.txt

When using transforms, we spin up a GRPC server within the Python runtime to run the transforms. During shutdown of the Python runtime, this server would print errors when running in Python 3.12 or higher.
By using the [wait_for_termination](https://grpc.github.io/grpc/python/grpc_asyncio.html#grpc.aio.Server.wait_for_termination) instead of [stop](https://grpc.github.io/grpc/python/grpc_asyncio.html#grpc.aio.Server.stop) we avoid these errors.
Fixes https://github.com/pulumi/pulumi/issues/18176

Fix callbackserver shutdown

---

changelog/pending/20250109--pkg--add-a-call-intrinsic-to-pcl.yaml
pkg/codegen/dotnet/gen_program.go
pkg/codegen/dotnet/gen_program_expressions.go
pkg/codegen/go/gen_program.go
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/hcl2/model/type_object.go
pkg/codegen/hcl2/model/type_test.go
pkg/codegen/pcl/binder.go
pkg/codegen/pcl/binder_resource.go
pkg/codegen/pcl/binder_schema.go
pkg/codegen/pcl/binder_test.go
pkg/codegen/pcl/call.go
pkg/codegen/pcl/invoke.go
pkg/codegen/pcl/utilities.go
pkg/codegen/testing/utils/host.go
tests/testdata/codegen/component-13.3.7.json

In order for PCL to serve as an authoritative intermediate language for Pulumi programs, it needs to be able to express all the concepts available to a Pulumi program written in a high-level programming language. Put another way, it must be capable of expressing all the functionality exposed by the `ResourceMonitor` interface. Presently, the ability to `Call` methods on component resources is not available in PCL. This change adds a new `call` intrinsic to fix that.
`call` has three required arguments: the receiver (that will become the `__self__` argument under the hood), the method name (that must exist in the resource's `Methods` map in schema), and an object of arguments (whose specifications must appear in the corresponding `Function` in the schema). An example use of `call` might …

Add a `call` intrinsic to PCL

---

changelog/pending/20241212--cli-import--import-can-now-import-resources-defined-in-parameterized-packages.yaml
pkg/engine/deployment.go
pkg/engine/plugins.go
pkg/engine/plugins_test.go
pkg/engine/update.go
pkg/resource/deploy/import.go
pkg/resource/deploy/providers/provider.go
pkg/resource/deploy/source_eval.go
pkg/resource/deploy/source_eval_test.go
pkg/resource/deploy/source_query.go
sdk/go/common/workspace/plugins.go
tests/smoke_test.go

The `pulumi import` command allows users to import existing provider resources into a Pulumi stack, accepting the type of resource to import, a name for the resource that will be created in the stack, and some "ID" that identifies the existing resource in the provider. Historically, the type has been sufficient to infer which provider offers the resource, since package names were in a one-to-one correspondence with plugin names. Now that we support parameterized providers, however, this is no longer the case -- we might wish to import a `random:index/id:Id`, but where the `random` package is a dynamically-bridged instance of the Terraform `random` provider produced by the `terraform-provider` plugin.
This change makes `import` aware of parameterizations by letting it deal with …

Support parameterized packages in `pulumi import`

---

changelog/pending/20241212--cli-import--import-can-now-import-resources-from-parameterized-providers.yaml
pkg/cmd/pulumi/operations/import.go
pkg/importer/hcl2.go
pkg/importer/hcl2_test.go
pkg/importer/language.go
pkg/importer/language_test.go
pkg/importer/testdata/cases.json
tests/smoke_test.go

Follow on PR to https://github.com/pulumi/pulumi/pull/18038. This adds support to the import code generator to support resources from parameterized packages.
This requires two things. Firstly we need the whole state when generating code so we can look up providers (there was a very old TODO comment that we should have been doing this anyway so we used the correct package versions). Looking up the provider means we can pull all the package information off it to look up the schema correctly.
We also emit that package information to the generated PCL as `package` blocks, so that the language code generator also has full access to the package information so it can correctly load schemas inside its GenerateProgram call.
Part of https://github.com/pulumi/pulumi/issues/17507

Support codegen for parameterised imports

---

changelog/pending/20250110--cli--allow-specifying-a-version-with-pulumi-convert-from-plugin-at-version.yaml
pkg/cmd/pulumi/convert/io.go

This uses the same syntax for `<plugin>@<version>` as is used in `pulumi package get-schema <plugin@version|file>`.
This is motivated by the way the bridge shells out to the converter for example conversion. We would like to move away from ambient plugins to hermetic builds.

Allow specifying a version with `pulumi convert --from=<plugin>@<version>`

---

changelog/pending/20250113--cli--enable-autonaming-configuration-in-non-experimental-mode.yaml
pkg/cmd/pulumi/operations/preview.go
pkg/cmd/pulumi/operations/up.go
tests/integration/integration_nodejs_test.go

https://github.com/pulumi/pulumi/pull/17916 introduced auto-naming configuration behind PULUMI_EXPERIMENTAL flag. This PR removes that experimental requirement so that the feature becomes available by default. Blog post in https://github.com/pulumi/docs/pull/13763.

Enable Autonaming Configuration in non-experimental mode

---

pkg/codegen/pcl/README.md

This commit extends the PCL `README` with a brief overview of the high-level building blocks of a PCL program, so that newcomers to working with it can (hopefully) make sense of it a bit more quickly.

Add some PCL cheatsheet-style documentation

---

changelog/pending/20250113--cli--retrieve-git-metadata-from-the-environment-if-not-running-in-a-repository.yaml
pkg/cmd/pulumi/metadata/metadata.go
pkg/cmd/pulumi/metadata/metadata_test.go

When running a Pulumi operation, we attempt to gather various bits of metadata, such as information about the commit, committer, author, and so on from the available version control system (VCS). In some situations, Pulumi is being run from a context where it doesn't have access to e.g. a `.git` folder, and so this information isn't added. This change allows this information to be added explicitly by setting a set of environment variables, enabling functionality that hangs off this metadata (e.g. that of the Pulumi GitHub action) to work correctly in these cases. The variables in question are:
* `PULUMI_VCS_REPO_OWNER`: The owner of the repository
* `PULUMI_VCS_REPO_NAME`: The name of the repository
* `PULUMI_VCS_REPO_KIND`: The kind of repository (e.g. `github.com`)
* …

Retrieve Git metadata from the environment

---

pkg/cmd/pulumi/metadata/metadata_test.go

The Pulumi CLI has a number of environment variables that can be set in order to supply metadata to a Pulumi operation. Some of these are inferred from/set by CI systems Pulumi expects to work with. When adding more variables to set Git metadata, a test was added to confirm that CI-set variables were used as a fallback. Unfortunately, it seems there is maybe a race (or just an outright bug) that causes this test to fail in our CI due to clashes with variables that are set by the test and variables that are set by the actual CI system. For now, this change removes this test to get CI passing again. Indeed, this is perhaps the reason these variables were not tested previously.

Remove failing test for loading Git metadata from CI

---

changelog/pending/20250115--cli-plugin--passthrough-unstructured-logs-from-dynamic-providers.yaml
sdk/go/common/resource/plugin/plugin.go

Adding the ability for structured logs to work correctly in dynamic providers is technically difficult. To maximize the transparency between dynamic providers and Pulumi programs, we have opted in the short term to simply restore `print`/`console.log` functionality to dynamic providers.
Fixes https://github.com/pulumi/pulumi/issues/18249

Passthrough unstructured logs from dynamic providers

---

.github/workflows/on-release-manual-dispatch.yml
.github/workflows/release.yml

This commit contains two changes:
1. Temporarily comment out jobs that have already successfully run in the `release.yml` workflow. See
https://github.com/pulumi/pulumi/actions/runs/12800055604/job/35687624699
2. Add a way to manually dispatch a release via `on-release-manual-dispatch.yml` workflow. The new file is a copy of `on-release.yml`, but setup to allow manual trigger with input variables, rather than being triggered by a release.
This change will be reverted after v3.146.0 is fully released.

Temporary changes to unblock v3.146.0 release

---

.github/workflows/release.yml
changelog/pending/20250116--sdk-python--manage-the-publish-dependencies-in-pyproject-toml.yaml
sdk/python/Makefile
sdk/python/pyproject.toml
sdk/python/uv.lock

Instead of installing `twine` in the CI job, have it as a part of the dev dependencies.

Manage the publish dependencies in pyproject.toml

---

pkg/codegen/pcl/binder_resource.go
pkg/codegen/pcl/call.go

In #18206 we introduced the `call` intrinsic to PCL. As part of making this work, we improved the annotating of PCL expressions with their schema resource types, allowing us to e.g. type-check `call` expressions by traversing the schema attached to a receiver expression. The type we introduced to support these annotations, `resourceAnnotation`, was initially made private, since it was only used within the package. However, in now trying to add `call` to e.g. Java, it's become apparent that it would be valuable to access the annotation from other packages. This change thus makes it public.
The other option here is to always wrap the receiver ("self") in a `__convert` that binds its schema type, but since the annotation is already attached this seems simpler and a bit cleaner. In the long …

Allow resource annotations to be publicly queried

---

pkg/cmd/pulumi/packagecmd/project_sdk_link.go
pkg/cmd/pulumi/packagecmd/project_sdk_link_test.go

Resolve https://github.com/pulumi/pulumi/issues/18281
The import identifier is read from package information, or converted to camelCase. The imported module is now `@pulumi/foo` not `foo`.
Before:
```
You can then import the SDK in your TypeScript code with:
import * as docker-build from "docker-build"
```
after
```
You can then import the SDK in your TypeScript code with:
import * as dockerBuild from "@pulumi/docker-build";
```
I haven't found any existing test corpus, so I made the simplest possible refactoring to test my change in isolation.

Improve instructions that we print for importing a Node.js generated SDK

---

.github/workflows/cron-direct-build.yml
changelog/pending/20250117--cli--update-go-mod-to-require-go1-22.yaml
cmd/pulumi-test-language/go.mod
developer-docs/go.mod
pkg/go.mod
sdk/go.mod
sdk/go/pulumi-language-go/go.mod
sdk/nodejs/cmd/pulumi-language-nodejs/go.mod
sdk/python/cmd/pulumi-language-python/go.mod
tests/go.mod
tests/integration/construct_component_configure_provider/testcomponent-go/go.mod
tests/integration/construct_component_provider_propagation/go/go.mod
tests/integration/construct_component_resource_options/go/go.mod
tests/integration/construct_nested_component/go/go.mod

We officially support the two latest releases of Go.  In https://github.com/pulumi/pulumi/pull/17827, we started using tar.AddFS, which was introduced in Go 1.22.  Since Go 1.23 is already out, we can drop support for Go 1.21, and reflect that in our go.mod files.
Fixes https://github.com/pulumi/pulumi/issues/18273

upgrade go toolchain to 1.22

---

changelog/pending/20250117--sdk-nodejs-python--fix-handling-of-dependencyresource-when-checking-invoke-deps.yaml
sdk/nodejs/runtime/invoke.ts
sdk/nodejs/tests/runtime/langhost/cases/077.invoke_output_depends_on_unknown_component/index.js
sdk/python/lib/pulumi/runtime/invoke.py
sdk/python/lib/test/test_invoke.py

In Python and Node.js, the DependencyResource class inherits from CustomResource, however the `id` is not set for these. Guard against this when validating an invoke’s dependencies.

Fix handling of DependencyResource when checking invoke deps

---

sdk/python/toolchain/toolchain_test.go

The latest version of pulumi-random requires Python >= 3.9, but the generated pyproject.toml files claim the project should run with >= 3.8, leading to unresolvable deps.
Because the latest version of `pulumi-random` now also pulls in the version of `pulumi` that has an explicit dependency on `pip`, we need to adjust the code for that.
As a follow up, we should update this test to not use `pulumi-random`, but a mock package instead, to avoid similar issues on the next bump of the minimum support Python version.

Fix TestListPackages

---

.github/workflows/ci-dev-release.yml

The change in https://github.com/pulumi/pulumi/pull/18261 broke the dev release. Setup up in the ci-dev-release job so that we can run the publish make target.
Fixes https://github.com/pulumi/pulumi/issues/18263

Fix dev releases for the Python SDK

---

changelog/pending/20250117--engine--skip-acquiring-program-packages-during-refresh-when-running-inline-automation-programs.yaml
pkg/cmd/pulumi/operations/refresh.go
pkg/engine/plugins.go
pkg/engine/refresh.go
pkg/engine/update.go

When https://github.com/pulumi/pulumi/pull/12196 was added to Pulumi CLI v3.143.0+ it made it such that when performing a `refresh`, the CLI would gather the dependencies of the program, compare them against the dependencies from the state/snapshot and warn if there are mismatches. To gather the dependencies of the program, the CLI would spin up a language plugin and call `GetRequiredPackages()` to get the set of dependencies. This usually works fine, however the PR does not account for _inline_ automation API programs where the language host isn't usually involved or needed to begin with.
This I believe is the root cause of https://github.com/pulumi/pulumi-dotnet/issues/443: a user that runs their standalone dotnet binaries with inline programs (in an environment without `dotnet` in the …

[engine/refresh] Skip acquiring program packages during refresh when running inline automation programs

---

changelog/pending/20250121--sdk-nodejs-python--permit-output-arguments-in-plain-invokes-for-backwards-compatibility.yaml
sdk/go/pulumi/context_test.go
sdk/nodejs/runtime/invoke.ts
sdk/nodejs/tests/runtime/langhost/cases/079.invoke_plain_takes_output/index.js
sdk/nodejs/tests/runtime/langhost/run.spec.ts
sdk/python/lib/pulumi/runtime/invoke.py
sdk/python/lib/test/test_invoke.py

Plain invokes happen to serialize arguments, which allows passing in output types. With https://github.com/pulumi/pulumi/pull/18204 we started checking if the resource dependencies of the arguments (and from `dependsOn`) are known, and returned unknown if not. However this broke backwards compatibility for plain invokes in the TypeScript and Python SDKs. 
This PR ensures that we only check the dependencies if we are using output form invokes. In Python and TypesScript, arguments of output type decay to  promises/tasks, without dependency information, when passed to plain invokes.

Permit output arguments in plain invokes for backwards compatibility

---

changelog/pending/20250121--cli-config--improve-documentation-for-pulumi-config-set.yaml
pkg/cmd/pulumi/config/config.go

Top level values are always written to the configuration as string. For paths we distinguish between booleans, numbers and strings. Everything that's not a bool or a number is treated as a string.
Fixes https://github.com/pulumi/pulumi/issues/18064

document the parsing behaviour of pulumi config set

---

docs/architecture/providers/README.md
docs/architecture/providers/built-in.md
docs/architecture/types/README.md

As part of the recently added conformance tests for testing components, we now have better coverage (and a better understanding of) resource references and their hydration, which is handled by the built-in provider. This small change makes a start at writing some of this down, adding a section for the built-in provider and adjusting the documentation we have on resource references to reference it.

Add some skeletal documentation on the built-in provider

---

pkg/codegen/pcl/binder_resource.go
pkg/codegen/pcl/call.go

This is a follow-up to #18276, in which we made the `ResourceAnnotation` type public, but forgot to also make its `node` field public at the same time. Doing this should actually make the type usefully accessible to other packages, so that we can proceed with e.g. implementing `Call` in Java as intended.

Allow resource annotations to be publicly queried, for real

---

pkg/cmd/pulumi/config/config.go
pkg/cmd/pulumi/config/config_test.go

Add test infrastructure to test the `pulumi config set` command, and add a simple test for it.  This test isn't meant to comprehensively test everything in the command, but rather as a start to be able to add more tests more easily as we go and add more features.
I wanted to add tests for https://github.com/pulumi/pulumi/pull/18287, but without the test infrastructure in place it's rather painful.  This is a step towards that, so #18287 can be tested properly.

add test infrastructure for `pulumi config set`

---

changelog/pending/20250122--cli-config--introduce-type-flag-for-config-set.yaml
pkg/cmd/pulumi/config/config.go
pkg/cmd/pulumi/config/config_test.go
sdk/go/common/resource/config/map.go
sdk/go/common/resource/config/value.go

Config values in `pulumi config set` are marshalled according to certain rules (everything on the top level is a string), and for paths, true/false becomes a boolean, integers not starting with a 0 become integers and everything else becomes strings.
This leaves floats out, and someone might want to store a number or a bool as a string instead.  Add a `--type` flag to pulumi config set to force the type.  This type also applies to top level config elements.
Fixes https://github.com/pulumi/pulumi/issues/5442

allow setting the type of the config value in pulumi config set

---

build/common.mk
cmd/pulumi-test-language/interface.go
cmd/pulumi-test-language/l2_destroy_test.go
cmd/pulumi-test-language/providers/simple_invoke_provider.go
cmd/pulumi-test-language/providers/simple_provider.go
cmd/pulumi-test-language/tests/l2_failed_create_continue_on_error.go
cmd/pulumi-test-language/tests/types.go

This PR adds a preview step to every conformance test with the ability to assert certain aspects of the resource changes and the generated plan via an `AssertPreview` function. When the tests do not specify an `AssertPreview` function, we give a default implementation that simply checks whether the preview is successful. 
The PR makes slight changes to a couple conformance provider implementations such that they don't hard fail when encountering unknown values (during preview)
Fixes #18296

Preview conformance tests

---

pkg/cmd/pulumi/packagecmd/project_sdk_link.go

Small little fix, we don't need to create a plugin host at this point in the code because we already have a full plugin context from above.

Don't create two plugin hosts in ProviderFromSource

---

changelog/pending/20250128--sdk-python--allow-pip-25.yaml
sdk/python/pyproject.toml
sdk/python/uv.lock

Pip 25 was released and this version works fine, allow it in our dependencies.
This should avoid dependency installation getting confused when trying to upgrade pip in a venv, which has lead to some test flakiness. Note that this seems to happen due to parallel tests using the global evnironment, and does not seem to be an issue in normal usage.

Allow pip 25

---

changelog/pending/20250128--sdk-python--make-runplugin-to-default-to-using-a-virtualenv.yaml
sdk/python/cmd/pulumi-language-python/main.go
tests/integration/integration_go_test.go
tests/integration/run_plugin/provider-python/__main__.py

For Python plugins `PluginSpec.InstallDependencies` always installs plugin dependencies into a virtual environment named `venv` in the plugin's directory.
Python's `RunPlugin` reads the options from `PulumiPlugin.yaml` to determine the toolchain to use. If no toolchain options are set, this proceeds to use the dependencies from the global Python installation, which is not what we want to happen. Instead, we should default to `toolchain: pip` (the default already) with `virtualenv: venv`, to match the installation step.
Fixes https://github.com/pulumi/pulumi/issues/18347

Make RunPlugin default to using a virtualenv

---

changelog/pending/20250129--cli-new--improve-docs-for-disambiguating-repositories-on-hosts-where-the-url-is-ambiguous.yaml
pkg/cmd/pulumi/newcmd/new.go

We support this disambiguation mechanism, but it's not widely known, and I don't think it's documented anywhere.  Add it to the documentation for `pulumi new` to publicise this feature a bit more widely.
Fixes https://github.com/pulumi/pulumi/issues/17582 (I don't think we can do much better here, but happy to leave the issue open if others disagree)

add some documentation for appending .git to the URL to disambiguate

---

changelog/pending/20250130--sdk-nodejs--use-the-corepack-executable-from-dev-dependencies.yaml
sdk/nodejs/package.json
sdk/nodejs/tests/runtime/install-package-tests.ts
sdk/nodejs/yarn.lock

The corepack version that ships with current nodejs releases uses old keys to verify signatures, causing the installation of the latest pnpm and npm versions, which use a newer key, to fail. Instead of relying on an implicit corepack version, include a version with recent signatures (>=0.31.0) in our dev dependencies, and use that in our tests.
Fixes https://github.com/pulumi/pulumi/issues/18338

Use the corepack executable from dev dependencies

---

changelog/pending/20250129--cli-config--fix-parsing-of-config-keys-with-paths-and-colons-in-path-segments.yaml
pkg/cmd/pulumi/config/config.go
pkg/cmd/pulumi/config/io.go
pkg/cmd/pulumi/config/io_test.go
pkg/cmd/pulumi/newcmd/config.go

Currently, the following command fails:
```
$ pulumi config set pulumi:autonaming.providers.aws.resources.aws:s3/bucket:Bucket.mode verbatim --path=true
error: invalid configuration key: could not parse pulumi:autonaming.providers.aws.resources.aws:s3/bucket:Bucket.mode as a configuration key (configuration keys should be of the form `<namespace>:<name>`)
```
because we expect 0 to 2 `:` symbols in the configuration key string.
This expectation is too strict for the `path: true` case, because colons may appear in non-top path segments, as in the above example. The command above should produce
```
config:
pulumi:autonaming:
providers:
aws:
resources:
aws:s3/bucket:Bucket:
mode: verbatim
```
This PR modifies `ParseConfigKey` behavior to allow that. `ParseConfigKey` now accepts whether the …

Fix parsing of config keys with paths and colons in path segments

---

sdk/go/auto/cmd_test.go

This test currently flakes sometimes because the stdiout is "signal: interrupt" instead of "error: preview canceled".  This can happen depending on when exactly the preview is canceled.
It would be nicer if the error always said "preview canceled", but the important thing is that we interrupt the preview successfully, and it's probably not worth our time right now to figure out exactly where this is flaky and why we're not getting the nice output in some rare cases.
It is however important that the test is not flaky, so let's just fix the test to also accept "signal: interrupt" as potential output when the preview is canceled.
Fixes https://github.com/pulumi/pulumi/issues/18389

fix flaky TestRunCanceled

---

tests/smoke_test.go

Re-enabling is tracked in https://github.com/pulumi/pulumi/issues/18414

Skip TestDestroyUpgradeWarningParameterized on Windows

---

changelog/pending/20250131--sdk-python--add-infrastructure-to-bootstrap-providers-from-component-resources.yaml
sdk/python/lib/pulumi/provider/experimental/__init__.py
sdk/python/lib/pulumi/provider/experimental/analyzer.py
sdk/python/lib/pulumi/provider/experimental/component.py
sdk/python/lib/pulumi/provider/experimental/host.py
sdk/python/lib/pulumi/provider/experimental/metadata.py
sdk/python/lib/pulumi/provider/experimental/provider.py
sdk/python/lib/pulumi/provider/experimental/schema.py
sdk/python/lib/test/provider/experimental/test_provider.py
tests/integration/component_provider/python/component-provider-host/Pulumi.yaml
tests/integration/component_provider/python/component-provider-host/provider/PulumiPlugin.yaml
tests/integration/component_provider/python/component-provider-host/provider/__main__.py
tests/integration/component_provider/python/component-provider-host/provider/component.py
tests/integration/integration_python_test.go

Add a `component_provider_host` function that allows creating providers in Python that host ComponentResources. The ComponentResources are automatically detected from the plugin’s source code, and their schema is infered based on the Python type annotations.
This first PR in the series lays out the ground work and wires everything up. The detected ComponentResources can be constructed, but no properties are infered yet.
Fixes https://github.com/pulumi/pulumi/issues/18372

[Experimental] Add infrastructure to bootstrap providers from component resources

---

cmd/pulumi-test-language/interface.go
pkg/cmd/pulumi/install/install.go
pkg/cmd/pulumi/newcmd/install.go
pkg/cmd/pulumi/policy/io.go
pkg/resource/deploy/deploytest/languageruntime.go
pkg/resource/deploy/deploytest/languageruntime_test.go
pkg/resource/deploy/source_query_test.go
pkg/util/cmdutil/install_dependencies.go
sdk/go/common/resource/plugin/langruntime.go
sdk/go/common/resource/plugin/langruntime_plugin.go
sdk/nodejs/cmd/pulumi-language-nodejs/main.go

The `InstallDependencies` method of the language host gRPC interface supports streaming back data for the standard output and error of the processes being executed by the language host (e.g. `npm install` for NodeJS). Presently however, we do not expose these streams in the higher-level `LanguageHost` Go interface. This commit changes that, having `LanguageHost`'s `InstallDependencies` method return a pair of `io.Reader`s for standard output and error respectively, as well as a channel that will be closed when the operation completes. This transforms `InstallDependencies` to an asynchronous call and so call sites are modified appropriately to drain the readers and block on the `done` channel's closure. With this change, we can modify the language conformance test server to capture …

Stream standard output and error when installing dependencies

---

docs/architecture/plugins.md
proto/.checksum.txt
proto/pulumi/language.proto
sdk/nodejs/proto/language_grpc_pb.js
sdk/proto/go/language.pb.go
sdk/proto/go/language_grpc.pb.go
sdk/python/lib/pulumi/runtime/proto/language_pb2.pyi
sdk/python/lib/pulumi/runtime/proto/language_pb2_grpc.py
sdk/python/lib/pulumi/runtime/proto/language_pb2_grpc.pyi

This commit fleshes out documentation for the `LanguageRuntime` gRPC service which underpins Pulumi's language runtimes. The documentation is pretty complete already for the most part -- this commit just adds some cross-references to various bits and pieces, some concrete examples here and there, and fills in the gaps.

Flesh out documentation for language runtime gRPCs

---

tests/integration/integration_python_test.go

I've seen this test flake/fail a few times, but unfortunately there's not much to go on for debugging it.  Add the full list of dependencies to the output to see if that helps a bit to shed light on what's happening.

add additional debugging output to TestConvertTerraformProviderPython

---

cmd/pulumi-test-language/README.md

I had some trouble getting the Stack resoruce for my conformance test I
was writing in python, which is swapped.  I searched the docs but no
mention of it and I had to figure this out through a bit of
experimentation.  Leaving a breadcrumb for the next person.

Add some clarification around conformance test stack resources.

---

CONTRIBUTING.md

The contributing guide mentions https://github.com/pulumi/pulumi/issues/208 but that issue was resolved a long time ago. I don't think we need to mention it in the guide anymore.

Remove Mention of Resolved Issue in CONTRIBUTING.md

---

changelog/pending/20250204--cli-config--fix-setting-indexed-top-level-config-keys.yaml
pkg/cmd/pulumi/config/config.go
pkg/cmd/pulumi/config/io.go
pkg/cmd/pulumi/config/io_test.go
pkg/cmd/pulumi/newcmd/config.go

https://github.com/pulumi/pulumi/pull/18378 has unfortunately led to a regression in previously working `pulumi config` commands that utilize both an explicit namespace and a top-level "indexer" syntax for config keys, for example
```
pulumi config set-all --path --plaintext 'example:["foo"]=bar'
```
This PR revamps the implementation of #18378. Since `resource.ParsePropertyPathStrict` is not namespace-aware and can return erroneous empty keys, I've substituted it with a manual piece of path parcing. It breaks down the path by two possible delimeters `.` and `[` and parses the first (top) segment with its namespace, then uses that namespace to construct the entire key.
A few tes cases added to cover potential use cases.
Fix https://github.com/pulumi/pulumi/issues/18443

Fix setting indexed top-level config keys with path=true

---

changelog/pending/20250204--engine--filter-__internal-keys-when-calling-providers-diffconfig.yaml
pkg/engine/lifecycletest/provider_test.go
pkg/resource/deploy/providers/registry.go
pkg/resource/deploy/step_generator.go

Noticed this while looking into https://github.com/pulumi/pulumi/issues/18449. 
Whenever we call provider methods to do with config (e.g. DiffConfig) we should filter out the "__internal" key that the engine adds to state for tracking engine internal data. We were doing this correctly everywhere except in one place in the step generator when calculating diffs due to provider changes. 
This fixes that place up and also adds a test to check we don't regress this.

Filter __internal keys when calling provider diff

---

pkg/codegen/go/gen.go
sdk/go/pulumi-language-go/testdata/sdks/goodbye-2.0.0/go.mod
sdk/go/pulumi-language-go/testdata/sdks/subpackage-2.0.0/go.mod

This incorporates a breaking change that was added in v3.147.0.
Fixes https://github.com/pulumi/pulumi/issues/18384.

Bump minimum pulumi version for Parameterized Go codegen to v3.147.0

---

tests/smoke_test.go

These tests are very flaky.  Disable them temporarily until we can fix them.
/cc https://github.com/pulumi/pulumi/issues/18451

temporarily skip TestLanguageConvert tests for java for windows

---

changelog/pending/20250204--engine--the-engine-will-correctly-use-old-state-for-provider-config-with-no-reported-differences.yaml
pkg/engine/lifecycletest/provider_test.go
pkg/resource/deploy/step.go

Prompted by https://github.com/pulumi/pulumi-docker/issues/1339
As part of investigating this issue it transpired that the engine currently uses the new inputs for provider configuration, even if the provider says there's no difference between the old inputs and the new inputs. 
This leads to inconsistencies when a provider reports no diff, but the values have actually changed. Worse this leads to inconsistencies of if the new or old inputs are used based on the order of operations.
In a normal update the new inputs from the program (or config) would be used to configure the provider, but in a refresh update (e.g. `up --refresh`) the engine would first configure the provider based on the old inputs saved in state. As diff then reported "no diff" the engine would never re-initialize and …

Use old inputs for Same steps

---

changelog/pending/20250131--sdk-python--experimental-camelcase-property-names.yaml
sdk/python/lib/pulumi/provider/experimental/analyzer.py
sdk/python/lib/pulumi/provider/experimental/component.py
sdk/python/lib/pulumi/provider/experimental/provider.py
sdk/python/lib/pulumi/provider/experimental/util.py
sdk/python/lib/test/provider/experimental/test_analyzer.py
sdk/python/lib/test/provider/experimental/test_util.py
tests/integration/component_provider/python/component-provider-host/Pulumi.yaml
tests/integration/component_provider/python/component-provider-host/provider/component.py
tests/integration/integration_python_test.go

Names need to be camel cased in the schema. Going from snake_case to camelCase is fine, however for the opposite direction we need to keep track of the original names. For example `URL` might have been `u_r_l` or `URL` originally.
With the mapping in place, we can send inputs into the component, and retrive the outputs.
Ref https://github.com/pulumi/pulumi/issues/18366

[Experimental] Handle inputs and outputs

---

sdk/go/auto/stack_test.go

This test has been really flaky in the last days (all the flakes I remember were on Windows).  Disable it for now, and track re-enabling it in https://github.com/pulumi/pulumi/issues/18459.

skip flaky TestUpdatePlans test on windows

---

pkg/codegen/schema/pulumi.json

The "?P" capturing group is a Go specific regex feature (https://github.com/google/re2/wiki/Syntax), not part of ECMA 262 (javascript) which json schema is specified to use.
This removes the ?P syntax from the pulumi metaschema for better support with JSON schema libraries.

Remove groups from json schema regex

---

changelog/pending/20250206--cli-display--preview-now-always-prints-resource-summaries-even-after-errors.yaml
pkg/backend/display/diff.go
pkg/backend/display/progress.go
pkg/backend/display/progress_test.go

This changes the CLI to always print the resource summary at the end of previews. Like `up` in the case of errors this might not match what the program _wants_ to do. But errors in preview are unusual, the main one being due to trying to delete protected resources.
Users have requested that they still want to see the summary if the only error is protect deletes (see
https://github.com/pulumi/pulumi/issues/18103).
Fixes https://github.com/pulumi/pulumi/issues/18103.

Always print summaries in preview

---

sdk/python/scripts/test_auto.sh
sdk/python/scripts/test_fast.sh

Without `--append` we overwrite the coverage data. For `test-fast` that means we only get the coverage from `lib/test_with_mocks` 🤦

Append coverage data

---

pkg/testing/integration/program.go

This allows tests to set the PULUMI_HOME directory, rather than always using a new temp directory. Mostly intended for benchmarking where we want a prewam run of `ProgramTest` followed by the real run but both need to use the same PULUMI_HOME so that plugins only get downloaded on the prewarm run.

Add PulumiHomeDir to ProgramTestOptions

---

changelog/pending/20250205--cli-package--fix-package-add-and-code-generation-when-package-name-contains-dashes.yaml
pkg/cmd/pulumi/packagecmd/project_sdk_link.go
pkg/codegen/go/gen.go
tests/integration/integration_go_test.go

When trying to `pulumi package add` that contains a `-` in its name, we currently fail twofold:
1) The package is generated into a folder
`sdks/<name>/<name-with-dashes-removed>` by the combination of go
codegen and `package add`.  However we currently try to look in
`sdks/<name>/<name>`, which fails if `name` contains any dashes.
2) If the package added is coming as parameterized package from
terraform-provider, it includes a `-` in the RootPackageName, which
in turn breaks code generation, as Go doesn't allow dashes in
package names.  Arguably this is a bug in the terraform-provider,
but given its buggy, and it's not super clear why, let's fix it
here as well.
Fixes https://github.com/pulumi/pulumi/issues/18455

Go: fix packages/Go SDK generation when name contains "-"

---

changelog/pending/20250205--cli-import--fix-the-declaration-of-parameterized-providers-in-import-json-files.yaml
pkg/engine/deployment.go
pkg/resource/deploy/import.go
pkg/resource/deploy/import_test.go
pkg/resource/deploy/providers/provider.go
tests/smoke_test.go

An alternative take on https://github.com/pulumi/pulumi/pull/18259
Noted while looking at that PR that we were duplicating information into the import file (the parameterized package name, was already part of the type token, and was being declared in the parameterization block).
Parameterization is awkward because in some places we have the plugin name at the root level (e.g. for package descriptors) and in other places the plugin name is in the parameterisation block (e.g. in schema).
This results in quite a lot of book keeping of when we need to flip from one to the other. Imports are another case of this.
The import file already defines "type" which specifies the package name as part of that. So it needs the base plugin name as extra information in the parameterisation block.
But …

Rejig import files to record base plugin names and versions in the paramterisation block

---

changelog/pending/20250206--cli-plugin--improve-the-warning-when-using-plugins-from-path.yaml
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_test.go

For bundled plugins this will now also print what the expected path was in the warning.
Old:
```
warning: using pulumi-language-nodejs from $PATH at /tmp/TestAmbientBundledPluginsWarn10582890/001/pulumi-language-nodejs
```
New:
```
warning: using pulumi-language-nodejs from $PATH at /tmp/TestAmbientBundledPluginsWarn10582890/001/pulumi-language-nodejs expected /tmp/go-build809231495/b001/pulumi-language-nodejs
```
This only applies to bundled plugins (like the language plugins), other plugins like resource providers don't have a single expected location, instead we would have looked them up in the ~/.pulumi/plugins folder.

Improve the warning when using plugins from PATH

---

sdk/python/lib/pulumi/provider/experimental/analyzer.py
sdk/python/lib/test/provider/experimental/test_analyzer.py
tests/integration/integration_python_test.go

The module should be relative to the provider, not CWD. This also fixes
running `pulumi package get-schema` from a path that's not a parent of
the provider code.

[Experimental/Components] Ensure component and type module is relative to the provider

---

.gitignore
Makefile
build/common.mk
sdk/go/Makefile
sdk/nodejs/Makefile
sdk/python/Makefile

This PR re-writes the ensure executable target to depend on expansion instead of content, allowing a target with a `.make/ensure/*` dependency to be up to date. This prevents unnecessary work on repeated builds.

Don't always rebuild targets with `%.ensure` dependencies

---

.github/workflows/ci-run-test.yml

When running in the merge queue, the branch is something like
`gh-readonly-queue/master/pr-18479-698d5ab6caba2dc23d64be1c1df00f57c9a6b8cb`.
Detect this and override the branch to be `master`.

Detect when we are in the merge queue and override the branch name

---

.github/workflows/ci-run-test.yml

We can upload all the files in the junit directory. This should help the action succeeding on windows.

Don’t set the files option codecov/test-results-action

---

changelog/pending/20250208--engine--fix-a-potential-panic-for-corrupted-secret-values.yaml
sdk/go/common/resource/config/crypt.go

If a secret value (of the form "v1:\<nonce\>:\<ciphertext\>") was corrupted with an improperly sized nonce field the system would panic when calling `aesgcm.Open`. This adds a check to instead error in this case, rather than panicking.
This likely has little impact on usage apart from getting a nice error rather than a panic in this case. Generally if secret decryption fails for any reason the CLI is incapable of doing anything else anyway.
Fixes https://github.com/pulumi/home/issues/3889

Fix panic for corrupted secret values

---

changelog/pending/20250208--cli-state--add-all-to-state-delete.yaml
pkg/cmd/pulumi/state/state_delete.go
pkg/cmd/pulumi/state/state_delete_test.go

Adds a `--all` flag to `pulumi state delete`. This simply iterates backwards to remove each resource from state, still respecting `protect` flags.
Fixes https://github.com/pulumi/pulumi/issues/2437

Add --all to state delete

---

changelog/pending/20250207--sdk-python--experimental-components-infer-plain-types.yaml
sdk/python/lib/pulumi/provider/experimental/analyzer.py
sdk/python/lib/pulumi/provider/experimental/component.py
sdk/python/lib/pulumi/provider/experimental/schema.py
sdk/python/lib/test/provider/experimental/test_analyzer.py
tests/integration/component_provider/python/component-provider-host/Pulumi.yaml
tests/integration/component_provider/python/component-provider-host/provider/component.py
tests/integration/integration_python_test.go

When inferring types, we should set the plain attribute on the types, depending on whether types can be outputs or not.
Fixes https://github.com/pulumi/pulumi/issues/18482

[Experimental/Components] Infer plain types

---

.gitignore
sdk/python/scripts/test_auto.sh
sdk/python/scripts/test_fast.sh

Follow up to https://github.com/pulumi/pulumi/pull/18479 which collects report for Go tests. This now adds Junit reports for Python tests.
Example results https://app.codecov.io/gh/pulumi/pulumi/tests/julienp%2Fgather-junit-info-for-python?term=lib.test.provider.experimental.test_analyzer

Collect junit reports for python tests

---

changelog/pending/20250207--sdk-python--experimental-components-check-for-required-inputs.yaml
sdk/python/lib/pulumi/provider/experimental/provider.py
sdk/python/lib/test/provider/experimental/test_provider.py
sdk/python/lib/test/provider/experimental/testdata/missing-input/component.py

While SDKS or the runtime (in the case of YAML) do some validation of the inputs, the provider should still check the inputs itself and raise an error if anything is missing.
Fixes https://github.com/pulumi/pulumi/issues/18458
Ref https://github.com/pulumi/pulumi/issues/18458

[Experimental/Components] Check for required inputs

---

pkg/cmd/pulumi/newcmd/new.go
pkg/cmd/pulumi/newcmd/template.go
sdk/go/common/workspace/project.go
sdk/go/common/workspace/templates.go

This PR applies two refactors:
- It removes the `Important` field from our template presentation layer, since we don't do anything with it in our code.
- It removes the `showAll` parameter from `templatesToOptionArrayAndMap`, since it is always set to `true`.
Neither change has any effect on the behavior of the built binary.

Remove unused `pulumi new` template code

---

changelog/pending/20250207--pkg--change-bulkdecrypt-to-return-list-instead-of-map.yaml
pkg/cmd/pulumi/config/io_test.go
pkg/engine/lifecycletest/pulumi_test.go
pkg/resource/deploy/source_eval_test.go
pkg/resource/stack/deployment.go
pkg/resource/stack/secrets.go
pkg/resource/stack/secrets_test.go
pkg/secrets/mock.go
pkg/secrets/passphrase/manager.go
pkg/secrets/service/manager.go
sdk/go/common/resource/config/crypt.go
sdk/go/common/resource/config/value_test.go

In preparation for introducing a `BulkEncrypt([]string) []string` where inputs and outputs are correlated based on order, it will also be good to use the same pattern of access for the existing decrypt methods. This does not yet change the pattern of how these values are returned by the service for bulk decryption - only how the library functions operate.
Most critical changes:
- mapDecrypter.BulkDecrypt (pkg/resource/stack/secrets.go) - added missing test coverage here.
- serviceCrypter.BulkDecrypt (pkg/secrets/service/manager.go) - already covered by existing tests.
This changes the interface within sdk/go/common/resource/config but this does not appear to be implemented outside of pulumi/pkg based on GitHub search.

Swap BulkDecrypt to return list

---

changelog/pending/20250210--engine--apply-autonaming-strategy-only-to-custom-resources-not-components.yaml
pkg/resource/deploy/step_generator.go
tests/integration/autonaming/index.ts
tests/integration/integration_nodejs_test.go

We currently try calculating auto-naming strategy even for component resources, which doesn't make much sense. It turns out components can have type tokens of arbitrary shape (i.e. not necessarily `package:module:name` but can be anything), which trips our autonaming calculation expectations.
The PR dodges that problem by (correctly) not calculating any autonaming strategy for component resources, only for custom resources.
An integration test creates a component resource with an unusual type token and makes sure the deployment goes well and component URN is what we expect (there is no `name` property).
Resolve https://github.com/pulumi/pulumi/issues/18499

Apply autonaming strategy only to custom resources, not components

---

changelog/pending/20250207--backend-service--dont-send-github-owner-and-github-repo-tags-to-the-service.yaml
pkg/backend/stack.go
sdk/go/common/apitype/core.go

Fixes https://github.com/pulumi/pulumi/issues/18330
Consumers of these tags have had 6 years to migrate to the new `"vcs:owner"`, `"vcs:repo"` and `"vcs:kind"` tags.

Don't attach "gitHub:repo" and "gitHub:owner" as implicit config

---

changelog/pending/20250211--auto-go--include-stderr-when-installpulumicommand-fails.yaml
sdk/go/auto/cmd.go

When the command installation fails, we currently include the error and stdout. `exec.ExitError` also contains the stderr of the command, which is often more relevant when there is a failure, but hides it away unless it's specifically used.
Add it to the error we return from `InstallPulumiCommand`.  This will hopefully help debugging CI failures we've been dealing with today, but also more generally should help users debug why the command fails if it does.

add more info when command installation fails

---

.github/workflows/ci-run-test.yml

Re-opened from https://github.com/pulumi/pulumi/pull/18495
I attempted to fix this in https://github.com/pulumi/pulumi/pull/18488, but that didn't work.
Here's a recent run for a merge to master https://github.com/pulumi/pulumi/actions/runs/13277574078/job/37069992311#step:44:92, and the branch is "branch": "gh-readonly-queue/master/pr-18424-71f2757f917e853f92e09f63e21420bda653b944"
Here's a run for the daily cron job on master https://github.com/pulumi/pulumi/actions/runs/13278773496/job/37073210482 and of course there is is `master`. This is what's been updating the stats in codecov.

Set branch name for test reports on merge

---

changelog/pending/20250212--sdk-python--fix-source-position-information-to-point-to-user-code-not-provider-sdks.yaml
sdk/python/lib/pulumi/runtime/resource.py
sdk/python/lib/test/langhost/source_position/__main__.py
sdk/python/lib/test/langhost/source_position/test_source_position.py

Fixes https://github.com/pulumi/pulumi/issues/18478
At some point python SDKs started using an `__internal_init__` method as part of generated resource constructors. This changed the expected height of user code in the stack traces we grab for setting `sourcePosition` and our tests never picked this up because they used a handwritten SDK that only had an `__init__` method.
This updates the test so that one resource has an `__internal_init__` that is called by `__init__` and then fixes `get_source_position` so it can handle both cases. It does this by looking up the stack for the third `__init__` call and then picking the frame above that. 
Still a bit brittle, but I think it's the best you can do by just looking at function names, and we're probably not going to add anymore classes into …

Fix python source positions for new SDKs

---

changelog/pending/20250212--engine--changes-to-source-position-metadata-will-be-batched-in-the-snapshot-system.yaml
pkg/backend/snapshot.go
pkg/backend/snapshot_test.go

Fixes https://github.com/pulumi/pulumi/issues/18478
This changes SourcePosition to not be considered an change that requires an immediate snapshot write. This lets us elide the actual snapshot write for each source position change until either a "must write" change happens, or the end of the deployment.
Nothing in the system uses source position for correctness, so if pulumi does crash and fails to ever write the updated source position change it won't break anything in the system on the next run. It will just be display metadata will be out of date for users looking in the console. But on the next successful update they'll all get updated and attempted to write again.
For large projects with hundreds of resources this change could save many writes that would normally get triggered by …

Elide SourcePosition changes

---

Makefile
sdk/python/Makefile
tests/integration/main_test.go

One of the most common pitfalls for me is forgetting to rebuild the binaries before running the integration tests.  There's currently no automated way to do it, and since the integration tests just pick up the binaries from $PATH they just use whatever is currently installed on the system.
This PR introduces a new environment variable that can be set, that makes the integration tests automatically build the binary into a `bin` folder in the local repository.  This folder is then added to the path, so `pulumi` and the language hosts from that path are being used instead of the system version.
Naturally this adds a little bit of time to integration tests, but only if the envrionment variable is set. Locally to me this seems like a good tradeoff, since integration tests are most of the time …

allow integration tests to automatically rebuild binaries

---

docs/architecture/testing/integration.md

We have this new environment variable to automate rebuilding binaries. Document it as the default way for building integration tests, as it should be more convenient for users running the tests.

document PULUMI_INTEGRATION_REBUILD_BINARIES

---

changelog/pending/20250213--backend-service--add-bulk-encrypte-service-types.yaml
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/client/client.go
sdk/go/common/apitype/service.go
sdk/go/common/apitype/stacks.go

Extracted from https://github.com/pulumi/pulumi/pull/18576 in order to create the service types to be consumed by the service so we can implement and test the service in parallel with https://github.com/pulumi/pulumi/pull/18576.
1. ~Refactor the existing "capabilities" to be exposed as part of the `Backend` interface and not only as part of the backend internals.~
2. Create the service types (request, response & capability) and implement within the client.

Add bulk encrypt service types

---

changelog/pending/20250213--sdk-nodejs--experimental-components-instantiation-components.yaml
sdk/nodejs/provider/experimental/analyzer.ts
sdk/nodejs/provider/experimental/provider.ts
sdk/nodejs/tests/provider/experimental/provider.spec.ts
sdk/nodejs/tsconfig.json
tests/integration/component_provider/.gitignore
tests/integration/component_provider/nodejs/component-provider-host/python/Pulumi.yaml
tests/integration/component_provider/nodejs/component-provider-host/python/__main__.py
tests/integration/component_provider/nodejs/component-provider-host/yaml/Pulumi.yaml
tests/integration/component_provider/python/recursive-types/.gitignore
tests/integration/integration_nodejs_test.go

Make it possible to instantiate a component and return its URN. We don’t have schema inference yet, besides the component name, so inputs and outputs are ignored.
Part of https://github.com/pulumi/pulumi/issues/18367

[Experimental/Components] Instantiate components

---

pkg/backend/httpstate/backend.go
pkg/backend/httpstate/backend_test.go
pkg/backend/httpstate/client/client_test.go
pkg/backend/httpstate/mock.go
pkg/backend/httpstate/snapshot.go
pkg/backend/httpstate/snapshot_test.go
pkg/cmd/pulumi/backend/login_manager.go
pkg/cmd/pulumi/org/org_search_test.go
sdk/go/common/apitype/service.go
sdk/go/common/apitype/service_test.go

Simplify & expose capabilities for a backend for wider use outside the backend class itself.
- Refactor the existing "capabilities" to be exposed as part of the Backend interface and not only as part of the backend internals.
- Use a `Promise` to encapsulate the pre-fetch and caching h/t @Frassle 
Stacked on top of:
- https://github.com/pulumi/pulumi/pull/18588

Refactor capabilities

---

changelog/pending/20250212--cli-config--fix-reading-yaml-config-with-uint64-sized-numbers.yaml
sdk/go/common/resource/config/map.go
sdk/go/common/resource/config/map_test.go
sdk/go/common/resource/config/object.go
sdk/go/common/resource/config/plaintext.go
sdk/go/common/resource/config/plaintext_test.go
sdk/go/common/workspace/project_test.go

Fixes https://github.com/pulumi/pulumi/issues/18581
This adds uint64 support to the `config.object` and `config.Plaintext` types. Pretty much a copy of int64 handling, but it means we can roundtrip uint64 without loss of precision. More importantly it means we no longer panic on reading a config file with big numbers like 18446744073709551615 in it.

Support uint64 values in config

---

changelog/pending/20250212--cli-display--add-show-secrets-args-to-pulumi-up-and-pulumi-preview-showing-secrets-in-the-cli-output-fixing-9830.yaml
pkg/backend/display/diff.go
pkg/backend/display/object_diff.go
pkg/backend/display/object_diff_test.go
pkg/backend/display/options.go
pkg/backend/display/progress.go
pkg/backend/diy/backend.go
pkg/cmd/pulumi/operations/preview.go
pkg/cmd/pulumi/operations/up.go
pkg/engine/events.go
pkg/engine/update.go

This PR tries to solve https://github.com/pulumi/pulumi/issues/9830
I expected the change to be simpler but since `filterPropertyValues` override any secret with the `[secret]` ([here](https://github.com/pulumi/pulumi/blob/master/pkg/engine/events.go#L685)) value I needed to change that first.
I will add some new tests, update the `preview` command as well, and add a changelog. But first I'd like some feedback to make sure that I started in the correct direction and that I did not miss something.

Add --show-secrets flag for up command

---

pkg/resource/deploy/providers/registry_test.go
pkg/resource/deploy/source_query.go
pkg/resource/deploy/step.go
pkg/resource/deploy/step_test.go

We never saw these in practice because the gRPC layer always fills them in, but if running engine tests without grpc we'd be missing this data on the requests.
Noticed this while working on some tests for the new refresh logic and tried to use `Name` and it was empty.

Fix passing of Name and Type to some provider methods

---

changelog/pending/20250214--sdk-nodejs--experimental-components-hook-up-inputs-and-outputs-in-the-provider.yaml
sdk/nodejs/provider/experimental/provider.ts
tests/integration/component_provider/nodejs/component-provider-host/provider/component.ts
tests/integration/component_provider/nodejs/component-provider-host/python/__main__.py
tests/integration/component_provider/nodejs/component-provider-host/yaml/Pulumi.yaml
tests/integration/integration_nodejs_test.go

This passes outputs back from the provider's Construct call, making the
components work end-to-end.
Fixes https://github.com/pulumi/pulumi/issues/18367

[Experimental/Components] Hook up inputs & outputs in the provider

---

pkg/cmd/pulumi/config/config.go

This is wrapping an error so should be %w, not %g which is for floats.

Fix format specifier for config set error

---

.mise.toml
docs/README.md
docs/contributing/README.md
docs/contributing/development.md
docs/documentation/README.md
docs/documentation/diagrams.md
docs/documentation/writing.md

This commit adds [Mise](https://mise.jdx.dev) to the repository as a means to standardise on the development tooling used for working with `pulumi/pulumi`. It also stubs out some introductory documentation on it and cleans up/gathers some of the existing pages we have on contributing to the repository. As we flesh this out, we should hope to clean out the cruft from/restructure `CONTRIBUTING.md` to make it more accessible/point to these pages instead.

Add Mise to `pulumi/pulumi`

---

changelog/pending/20250217--pkg--do-not-cache-schema-if-we-never-read-it-back.yaml
pkg/codegen/schema/loader.go

This change makes is so that Pulumi (and plugins like pulumi-yaml) will not write schema cache if we do not read it back. In particular, this affects plugins from PATH that is usually read-only and version is nil, and hence writing the schema cache would fail.
Related discussion: https://github.com/pulumi/pulumi/pull/10971#discussion_r990558593

Do not cache schema if we never read it back

---

changelog/pending/20250219--engine--send-parent-urn-to-resource-transforms.yaml
pkg/engine/lifecycletest/transformation_test.go
pkg/resource/deploy/source_eval.go

Fixes #18643
The engine wasn't filling in the parent URN for resource transform requests. Looks like all the SDKs already have the code to receive this.

Fix sending parent in resource transforms

---

changelog/pending/20250220--sdk-nodejs--improve-type-inference-for-output-and-unwrap-when-used-on-tuples.yaml
sdk/nodejs/output.ts
sdk/nodejs/tests/output.spec.ts

Currently, if we try to call `all` on a structure involving tuples, they are treated as `Array<X | Y>` instead of `[X, Y]`, which means that `[X, Y]` will unwrap to `UnwrappedArray<X | Y>`, rather than the much more precise `[Unwrap<X>, Unwrap<Y>]`.
This PR implements @justinvp's [suggested fix](https://github.com/pulumi/pulumi/issues/17704#issuecomment-2467426573), and adds a couple tests to ensure that the type inference does indeed behave correctly.
With this change, I managed to compile the [expected behaviour example](https://github.com/pulumi/pulumi/issues/17704#issuecomment-2460209864) successfully, which I then condensed into the labelled test.
Fixes #17704

Fixes: #17704 - feat(sdk/nodejs): infer a more direct type when `Unwrap`ping tuples

---

sdk/go/common/testing/util.go

I recently run into a flake where a random stack name had a name clash (https://github.com/pulumi/pulumi/actions/runs/13434278928/job/37533061535?pr=18631).
Double the number of random bytes to hopefully avoid this in the future.

add more randomness to random stack names

---

changelog/pending/20250220--auto-nodejs--support-clear-pending-creates-in-the-nodejs-automation-api.yaml
sdk/nodejs/automation/stack.ts

The `--clear-pending-creates` flag already exists for [the Go API](https://github.com/pulumi/pulumi/pull/18101/files), but didn't previously exist for NodeJS. This PR adds the flag as an option to `RefreshOptions` to mimic the behaviour of Go's code.
I couldn't find any tests for checking that options are added correctly in NodeJS, but I manually tested it by logging the command from one of the tests that I had modified, and things look to be working correctly:
```javascript
[
'refresh',
'--yes',
'--skip-preview',
'--clear-pending-creates',
'--exec-agent',
'pulumi/pulumi/test',
'--exec-kind',
'auto.inline',
'--stack',
'organization/inline_node/int_test9848130f-6e00-4aa2-ad97-277bd5a916e7'
]
```

Support `--clear-pending-creates` for `refresh` command in NodeJS Automation API.

---

.mise.toml
changelog/pending/20250220--auto-python--add-clear-pending-creates-to-the-refresh-command-in-the-python-automation-api.yaml
sdk/python/lib/pulumi/automation/_stack.py

In #18653, we added `--clear-pending-crates` to the NodeJS Automation API. This PR does the equivalent work for the Python Automation API.
I also added the `uv` binary to `.mise.toml` as I needed it to run the Python Automation API tests.
Fixes #18102

Add `--clear-pending-creates` to `refresh` command in Python Automation API

---

changelog/pending/20250220--cli--fix-a-panic-in-help-new-when-local-templates-werent-present.yaml
pkg/cmd/pulumi/main_test.go
pkg/cmd/pulumi/newcmd/new.go

Fixes https://github.com/pulumi/pulumi/issues/18659
Comment in code pretty much covers it, but repeating here:
You'd think you could use cmd.Context() in the help function but cobra doesn't set context on the cmd even though the parent help command has it. I've raised https://github.com/spf13/cobra/issues/2240 to see about fixing it.

Fix panic in help new

---

changelog/pending/20250220--auto-nodejs--add-the-preview-only-flag-to-the-refresh-command-in-the-nodejs-automation-api.yaml
sdk/nodejs/automation/stack.ts

The `previewOnly` parameter now allows users to set the `--preview-only` flag in the NodeJS Automation API. This overrides [`--skip-preview` in the same way as Go](https://github.com/mcblair/pulumi/blob/edcecda3473ffe1733dd7e8e854addeadb893e04/sdk/go/auto/stack.go#L727-L729)*. As with #18653, it's difficult to test that flags are set at the moment, but I have manually tested that the flag shows up correctly:
```javascript
[
'refresh',
'--preview-only',
'--exec-agent',
'pulumi/pulumi/test',
'--exec-kind',
'auto.inline',
'--stack',
'organization/inline_node/int_test42ed92ec-177e-4156-8af2-223e0ebc91b7'
]
```
_* Note that, unlike Go, it doesn't unset the `--yes` flag when `--preview-only` is set. Given that Go doesn't seem to handle any prompts that may follow, it seems like this could be a …

Preview-only refresh in NodeJS

---

sdk/nodejs/provider/experimental/analyzer.ts
sdk/nodejs/tests/provider/experimental/analyzer.spec.ts
sdk/nodejs/tests/provider/experimental/testdata/asset-archive-types/index.ts

Handle assets and archives in the components analyzer.
Stacked on top of https://github.com/pulumi/pulumi/pull/18631

Experimental/Components]: Handle assets and archives

---

pkg/engine/lifecycletest/continue_on_error_test.go
pkg/engine/lifecycletest/delete_before_replace_test.go
pkg/engine/lifecycletest/parameterized_test.go
pkg/engine/lifecycletest/provider_test.go
pkg/engine/lifecycletest/pulumi_test.go
pkg/engine/lifecycletest/target_test.go
pkg/resource/deploy/import.go
pkg/resource/deploy/providers/reference.go

We were a little inconsistent in the tests if we bothered to check if ID was empty and setting it to UnknownID or if we just passed the ID directly. There was also a lot of duplicate code doing that empty check. This moves the empty check to "providers.NewReference" so we can just always pass ID directly.

Default to UnknownID in providers.NewReference

---

pkg/engine/plugins.go
pkg/importer/hcl2.go
pkg/resource/deploy/import.go
pkg/resource/deploy/providers/provider.go
pkg/resource/deploy/providers/registry.go
pkg/resource/deploy/source_eval.go

Happened to be looking in this area of the codebase and noticed that these were pretty much the same (bar some string / `tokens.Package` differences, but `tokens.Package` is just a string).
So this cleans up to just replace `ProviderParameterization` with `workspace.Parameterization` everywhere.

Repalce ProviderParameterization with workspace.Parameterization

---

changelog/pending/20250221--engine--dont-overwrite-schema-versions-if-they-exist.yaml
pkg/codegen/schema/loader.go

When loading a schema from a provider, we previously added logic that would overwrite the version in the returned schema with the plugin version if the schema had an older version. It's not clear why we did this, and is a bit odd when the plugin name and the package name match, but in the case of parameterized providers where plugin and package are different, it's outright wrong. This change thus adapts this behaviour to match its original intention -- adding a version only when one is missing (and moreover, only when parameterization is not involved).
Part of #18187

Don't overwrite schema versions if they exist

---

changelog/pending/20250221--cli-package--support-parameterizing-providers-when-calling-get-mapping.yaml
pkg/cmd/pulumi/packagecmd/package_extract_mapping.go

This change makes a small extension to `pulumi package get-mapping` so that, like its sibling `get-schema` command, it can accept and apply a parameterization before requesting a mapping from a provider.

Support parameterizing providers when calling `get-mapping`

---

changelog/pending/20250221--auto--fix-up-with-nested-secret-in-config-file.yaml
pkg/cmd/pulumi/stack/stack_history.go
pkg/cmd/pulumi/stack/stack_history_test.go
sdk/go/auto/stack_test.go

At the end of running an `up` operation from Automation API, the
`pulumi stack history` command is invoked to retrieve an update summary
of the operation.
We want the `stack history --json` command to succeed even if there are
problems decrypting secrets in the config, which can happen when the
`stack history` command doesn't have the encryption salt (because it is
stored in a separate config file). If there is an error decrypting a
config secret, the config's value is replaced with
`ERROR_UNABLE_TO_DECRYPT` rather than having the command fail.
Unfortunately, this does not work when there is a config value with a
nested secret. In that case, an obscure "unexpected end of JSON input"
error is returned and the command fails.
This happens because we attempt to unmarshal the nested value, …

[auto] Fix `up` with nested secret in config file

---

sdk/nodejs/provider/experimental/analyzer.ts
sdk/nodejs/tests/provider/experimental/analyzer.spec.ts
sdk/nodejs/tests/provider/experimental/testdata/map-types/index.ts
sdk/nodejs/tests/provider/experimental/testdata/optional-types/index.ts

We currently support optional types in typescript by adding `?` to the symbol name.  Also allow optional types by adding `| undefined` instead.

[Experimental/Component]: support optional types in unions

---

sdk/nodejs/provider/experimental/analyzer.ts
sdk/nodejs/provider/experimental/schema.ts
sdk/nodejs/tests/provider/experimental/analyzer.spec.ts
sdk/nodejs/tests/provider/experimental/testdata/component-description/index.ts

This is a little awkward because the jsDoc property is private in the compiler API, but I couldn't find a better way to access it.  It should be okay as a best effort to add doc descriptions.

[Experimental/Components]: Infer doc comments

---

changelog/pending/20250218--cli-package--correctly-deal-with-subdirs-in-package-add-when-no-version-number-is-specified.yaml
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_test.go
tests/integration/integration_nodejs_test.go

When we have plugins that are located in a subdir of a repository, we need to fix up the path to include that subdir, as we install the whole repository into `~/.pulumi/plugins`, and then use the plugin from a subdir.
Currently we only do that for "prerelease plugins", which means plugins whose version is referenced by a commit hash.  This is however not correct, as plugins from Git plugins don't necessarily have a version number, or they can be referenced by a regular semver version.
Fix up the path unconditionally if we have a subdir instead.
Fixes https://github.com/pulumi/pulumi/issues/18557

correctly run versionless plugins in subdirs

---

sdk/python/lib/pulumi/provider/experimental/analyzer.py
sdk/python/lib/test/provider/experimental/test_analyzer.py
sdk/python/lib/test/provider/experimental/testdata/excluded-files/.projectrc.py
sdk/python/lib/test/provider/experimental/testdata/excluded-files/component.py
sdk/python/lib/test/provider/experimental/testdata/excluded-files/tests/test_skipme.py

This PR changes our Python component analyzer to skip certain files and directories, in particular `tests` and and file starting with a dot. I think it's a reasonable default not to expect our users to define any components in those files.
Resolves https://github.com/pulumi/pulumi/issues/18646. While we could add a configuration nob for this and make users define the exclusion as the issue suggest, I believe we want to minimize the number of needed configuration values to achieve our goal of meeting users where they are.

[Experimental/components] Skip tests and .files while analyzing Python components

---

pkg/resource/deploy/step.go
pkg/resource/deploy/step_test.go

Same as https://github.com/pulumi/pulumi/pull/18611, we were missing a few more places where we should have been sending Name and Type. Again the grpc layer normally filled these in so this was only noticeable from tests.

Fill in some more Name and Type fields on requests

---

changelog/pending/20250224--cli-new--report-all-errors-from-git-clone-for-multiple-refs.yaml
sdk/go/common/workspace/templates.go

Currently when we try a git clone for a given url without a reference we try both master and main. If the clone for master _and_ main both fail we only report back the error that happened for main.
This changes it so we report both errors. I also added some more log lines.

Report all errors back from git clone

---

changelog/pending/20250129--sdk-python--fix-merge-method-typing.yaml
sdk/python/lib/pulumi/invoke.py
sdk/python/lib/pulumi/resource.py
sdk/python/lib/test/test_resource.py

As a consumer, using the class method of merge results in a Pylance/Pyright type error:
After making the proposed change locally, the type error is resolved.

Fix mypy errors around ResourceOptions and InvokeOptions merge

---

changelog/pending/20250225--cli--make-policy-rm-and-stack-rm-non-interactive-when-requested.yaml
pkg/cmd/pulumi/policy/policy_rm.go
pkg/cmd/pulumi/stack/stack_rm.go

When `--non-interactive` is specified on the command line, pulumi promises to disable interactive mode for all commands, which means it should never prompt.  This however currently does not work for `policy rm` and `stack rm`, both of which still prompt even when `--non-interactive` is specified.
Instead of that, error out when `--non-interactive` is specified, but `--yes` isn't.
Prompted by https://github.com/pulumi/pulumi/issues/4717#issuecomment-2680086602.

stack/policy rm: require yes flag in non-interactive mode

---

pkg/cmd/pulumi/packagecmd/project_sdk_link.go

In the `pulumi package *` command family, we try to load the provider based on some properties, and if it fails and a corresponding executable exists, we suggest disambiguating it using "./".
Nowadays we can also have source based plugins, so we should give the user the same disambiguation option if the name matches a local directory instead of an executable.  Do that here.
Small fix I noticed while reading code for https://github.com/pulumi/pulumi/pull/18709.

package: also suggest disambiguating for local directories

---

changelog/pending/20250221--auto-python--add-preview-only-to-the-refresh-command-in-the-python-automation-api.yaml
sdk/python/lib/pulumi/automation/_cmd.py
sdk/python/lib/pulumi/automation/_stack.py

Like #18662, this adds support for the `--preview-only` flag in the `refresh` command when using the Python Automation API. It implements the same `--yes` behaviour as the NodeJS version: whether we skip preview or only show the preview, we always set `--yes` to avoid problems with later prompts in future.
Fixes #17598

Add `--preview-only` to the `refresh` command in the Python Automation API

---

sdk/nodejs/Makefile

From local testing, when running `make unit_tests` in `sdk/nodejs`, and then subsequently running `yarn run nyc report`, I only see coverage associated with the `tests_with_mocks`. The coverage data for the previous `nyc` command, which contains the majority of unit tests, appears to be missing from the coverage report.
This change adds `--no-clean`, so that the coverage data is appended and not cleared out between runs.
Similar to the problem we fixed for the Python SDK: https://github.com/pulumi/pulumi/pull/18475

[sdk/nodejs] Append coverage data

---

changelog/pending/20250225--sdk-nodejs--fix-searching-for-pulumi-packages-past-junction-points-on-windows.yaml
sdk/nodejs/cmd/pulumi-language-nodejs/main.go
tests/smoke_test.go

Fixes https://github.com/pulumi/pulumi/issues/18414
Turns out the nodejs runtime wasn't picking up our parameterized package in GetRequiredPackages at all because it was behind a junction point that Go wasn't seeing as a directory.
I'm not sure how this ever passed but I think it might have been due to this change (https://go-review.googlesource.com/c/go/+/565136) in Go 1.23.

Fix TestDestroyUpgradeWarningParameterized on Windows

---

changelog/pending/20250225--sdk-nodejs--fix-incorrect-dependencies-due-to-missing-await.yaml
sdk/nodejs/runtime/dependsOn.ts
sdk/nodejs/tests/runtime/dependsOn.spec.ts
sdk/nodejs/tsconfig.json

An unawaited Promise in the `addTransitivelyReferencedChildResourcesOfComponentResources` function leads to an incomplete dependency graph, which in turn leads to resources being created in the incorrect order.

Fix incorrect dependencies due to missing await

---

sdk/go/common/util/errutil/format_exiterr.go
sdk/go/pulumi-language-go/main.go
sdk/python/toolchain/toolchain.go
sdk/python/toolchain/toolchain_test.go
sdk/python/toolchain/uv.go

In Go, `exec.ExitErr` contains the whole Stderr of a command.  However it's `Error()` function unfortunately only returns the exit status, which in most cases is not enough to debug the problem.  In most cases we want to format these errors including the stderr to make the problems more debuggable.
Factor out the helper function we already have for the python toolchain, and make it available to other places as well.  Start using it in the Go conformance tests, where I ran into this today.  We should spread the usage of this to wherever we deal with ExitErrors, but let's start here for now.

introduce helper function for exiterr, and use it in language tests

---

sdk/nodejs/provider/experimental/analyzer.ts
sdk/nodejs/tests/provider/experimental/analyzer.spec.ts
sdk/nodejs/tests/provider/experimental/testdata/resource-reference/index.ts

Currently resource references are wrongly parsed as types, which will then later not work.  Since we're not supporting them for now, give a nice error to the user instead of doing something broken.

[Experimental/Components]: return an error for resource references

---

pkg/resource/deploy/step_generator.go

Same as https://github.com/pulumi/pulumi/pull/18695, found another request we weren't filling in Name and Type.

Add another missing Name and Type

---

sdk/go/auto/cmd_test.go

There's many possiblilities of what the output is when pulumi up is canceled, depending on the exact moment the cancelation signal gets through to the process.  Trying to match against all of them seems like a bit of a fools errand, so let's only match against the exit code, which should still give us enough information to check whether the run was canceled successfully or not.
Fixes https://github.com/pulumi/pulumi/issues/18573

(hopefully) fix flaky TestRunCanceled

---

changelog/pending/20250227--programgen--fix-concurrent-map-write-panics-in-the-caching-mapper.yaml
pkg/codegen/convert/caching_mapper.go
pkg/codegen/convert/caching_mapper_test.go

The caching mapper is susceptible to concurrent map write panics when doing bulk conversions. This change avoids the panic by adding some locking around the map.
Fixes #18744

Fix concurrent map write panics in caching mapper

---

pkg/codegen/dotnet/gen_test.go

We already have a mutex around dotnet build, and dotnet test seems to require the same.  Also remove a dead link from the comment and link to an issue instead, which should not be deleted (GitHub action logs get deleted after some relatively short period of time).
Fixes https://github.com/pulumi/pulumi/issues/18738
Fixes https://github.com/pulumi/pulumi/issues/16528
(hopefully)

try to fix flake in TestGeneratedPackage

---

docs/architecture/providers/components.md

This came up when reading the docs for Components.
I hope this diagram can make the Construct decision flow a little more clear.

Add RegisterResource diagram for Construct

---

pkg/codegen/go/gen.go

If we don't have a better way to generate the module path for Go in codegen, we currently use the Publisher field to do so.  However the Publisher field in the schema is free-form text, and doesn't necessarily fit into a package name.  Use the namespace that was set up for this purpose instead.
Note that this is technically a breaking change, however it's expected that this is not used very much.  This is because most providers would also set the Repository field, which overrides the Publisher/Namespace.
Part of https://github.com/pulumi/pulumi/issues/18369

use namespace instead of publisher for Go package generation

---

changelog/pending/20250228--sdk-python--fix-get_organization-returning-none-from-older-sdks.yaml
sdk/python/cmd/pulumi-language-python-exec
tests/integration/integration_python_test.go
tests/integration/python/organization/.gitignore
tests/integration/python/organization/Pulumi.yaml
tests/integration/python/organization/__main__.py
tests/integration/python/organization/requirements.txt

When versions v3.152.0 and earlier of the `pulumi` python SDK are used with v3.153.0 of the CLI, the `pulumi.get_organization()` function returns `None` rather than the expected organization. This is a regression that was introduced by #18595.
This is what's happening: `pulumi-language-python-exec` ships with the CLI. In v3.153.0, it tries to create an instance of `pulumi.runtime.Settings`, passing a new parameter: `root_directory`. However, older versions of the `pulumi` python SDK do not support this parameter. An error is raised, which is caught and we fall back to default values, which doesn't have the `organization`, so it ends up being `None`.
This change fixes the problem in `pulumi-language-python-exec`. We first try to create `Settings` with all possible parameters. If it runs …

[sdk/python] Fix `get_organization` returning `None`

---

changelog/pending/20250226--cli-config-state--support-a-pulumi_stack-environment-variable-for-selecting-your-stack.yaml
pkg/backend/state/stacks.go

closes https://github.com/pulumi/pulumi/issues/13550
My team regularly utilizes [direnv](https://direnv.net/) to select between deployment environments using directories.
We would love to use this same approach to select our pulumi stack. We aren't willing to wrap `pulumi` to accomplish this, but it seems like adding an environment variable override is easy enough to upstream. 😀
1) As a NOP change, I created a `getCurrentStackName()` function that returns a **string**. This just sets up my second commit for an easier change.
2) If `PULUMI_STACK` is defined, return it as the string value
```
make build install
```
```bash
$ ~/.pulumi-dev/bin/pulumi up
Please choose a stack, or create a new one:  [Use arrows to move, type to filter]
bedrock
> cluster
network
<create a new stack>
```
```bash …
```

support `PULUMI_STACK` environment variable for selecting your stack

---

sdk/nodejs/tests/automation/localWorkspace.spec.ts

For automation tests we want to use the local backend if PULUMI_ACCESS_TOKEN is not set.  We attempted to do this in this test, however we didn't pass it to `LocalWorkspace.createStack`, but rather to the `map` function and failed to realize that.
Pass the test backend to the right function to make this work without having to set a pulumi access token in the environment.

fix test backend usage in automation test

---

pkg/backend/httpstate/client/client.go
pkg/backend/httpstate/client/client_test.go
pkg/cmd/pulumi/config/io_test.go
pkg/cmd/pulumi/stack/stack_history_test.go
pkg/engine/lifecycletest/pulumi_test.go
pkg/resource/deploy/source_eval_test.go
pkg/resource/stack/deployment.go
pkg/resource/stack/secrets.go
pkg/resource/stack/secrets_test.go
pkg/secrets/mock.go
pkg/secrets/passphrase/manager.go
pkg/secrets/service/manager.go
sdk/go/common/apitype/service.go
sdk/go/common/apitype/service_test.go
sdk/go/common/apitype/stacks.go
sdk/go/common/resource/config/crypt.go
sdk/go/common/resource/config/value_test.go

Make naming of types and methods consistent with the actual service API route (which we can't easily change).
1. Rename BulkDecrypt to BatchDecrypt
2. Rename "bulk" api types to "batch"
This will require some additional fixes on the service side on the next update.

Rename batch crypt types

---

sdk/python/lib/pulumi/provider/experimental/analyzer.py
sdk/python/lib/test/provider/experimental/test_analyzer.py

In python it's possible to write something like `pulumi.Input[dict]`, where `dict` has no type arguments.  This currently causes us to throw a confusing exception.  Detect that case, and provide a better error message to the user.

provide friendlier exception when dict has no type arguments

---

sdk/nodejs/Makefile
sdk/nodejs/package.json
sdk/nodejs/tests/automation/localWorkspace.spec.ts
sdk/nodejs/tsconfig.json
sdk/nodejs/yarn.lock

I've been doing a lot of automation API changes recently, and it's really helpful to be able to write a test, then run that test repeatedly as I make changes. This PR adds `make test_watch` to the `sdk/nodejs` makefile. There are a few advantages to this over `make test_auto`:
* This runs the Typescript directly using [`tsx`](https://tsx.is/) instead of compiling the SDK and its tests to JS _before_ running tests. This means the watch command's startup is much faster.
* It auto-configures a valid organization based on the account with which you've authenticated. This means you don't get errors when your account doesn't have the same organizations as the CI does.
* You can run specific tests using the `TEST_GREP` argument, which means you can run a handful of the tests you care about, …

Add `make test_watch`, a test-watching command for NodeJS

---

changelog/pending/20250303--cli--set-the-parallel-flag-with-pulumi_parallel-environment-variable.yaml
pkg/cmd/pulumi/operations/destroy.go
pkg/cmd/pulumi/operations/flags_test.go
pkg/cmd/pulumi/operations/import.go
pkg/cmd/pulumi/operations/preview.go
pkg/cmd/pulumi/operations/refresh.go
pkg/cmd/pulumi/operations/up.go
pkg/cmd/pulumi/operations/watch.go
sdk/go/common/env/env.go

Feat(cli): Set the --parallel flag with PULUMI_PARALLEL environment varariable, fixes #12037

Feat(cli): Set the --parallel flag with PULUMI_PARALLEL environment var

---

sdk/go/common/apitype/policy.go

Policy Groups can now contain accounts as well as stacks.  We need this field to be returned from the pulumi cloud API

add num accounts to policy group summary

---

pkg/codegen/pcl/functions.go
pkg/codegen/pcl/functions_test.go

This updates the PCL signature of `can` to only be an `output(bool)` when the input argument is either dynamic or an output itself. If the input argument is a plain value then the return value of `can` just be a plain `bool`.

Only lift can to output space if needed

---

sdk/python/Makefile
sdk/python/lib/test/automation/test_isolation.py
sdk/python/lib/test/automation/test_local_workspace.py
sdk/python/pyproject.toml
sdk/python/pytest.ini
sdk/python/uv.lock

Very similar PR to #18750: this allows us to run specific pytests every time a code or test file is updated. This also gets the tests to pass on my machine.

Add `make test_watch`, a test-watching command for Python

---

sdk/python/lib/pulumi/provider/experimental/metadata.py
sdk/python/lib/pulumi/provider/experimental/schema.py
sdk/python/lib/pulumi/provider/provider.py
sdk/python/lib/pulumi/provider/server.py

We don't want to force, in fact we want to discourage, authors from specifying the version of the plugin, particularly in Git plugins. Make it optional in the Metadata class, so it no longer needs to be passed in.
Note that this means `GetPluginInfo` will not return a version in some cases.  We could probably try to grab that version from the Git repo for each language, but doing that is a bit awkward.  Note that in many cases we don't use the version form `GetPluginInfo` anyway, e.g. in `pulumi plugin ls` we seem to use the version from the directory in `~/.pulumi/plugins`.

[Experimental/Components]: make provider version optional

---

docs/architecture/README.md
docs/architecture/converters.md
docs/architecture/plugins.md
proto/.checksum.txt
proto/pulumi/provider.proto
sdk/nodejs/proto/provider_grpc_pb.js
sdk/proto/go/provider.pb.go
sdk/proto/go/provider_grpc.pb.go
sdk/python/lib/pulumi/runtime/proto/provider_pb2.pyi
sdk/python/lib/pulumi/runtime/proto/provider_pb2_grpc.py
sdk/python/lib/pulumi/runtime/proto/provider_pb2_grpc.pyi

Following the recent work on `pulumi convert` and supporting more Terraform conversion than ever, this change bulks out the developer documentation on how conversion and converter plugins work under the hood, in order to capture some of the details discovered and introduced as part of this effort.

Flesh out documentation on converters

---

sdk/go/common/util/cmdutil/args.go

Following on from https://github.com/pulumi/pulumi/pull/18767 we no longer need to Exit in our args validation function. We can't totally get rid of our custom validator here because it prints help text for bad arguments, while cobra either prints help text for _all_ errors, or no help text if SuppressUsage is set (we set that).
This does unlock being able to unit test command parsing.

Don't Exit in ArgsFunc

---

pkg/codegen/pcl/functions.go
pkg/codegen/pcl/functions_test.go

Similar fix as for https://github.com/pulumi/pulumi/pull/18791, only return an output from try if we have a dynamic input that might lift it to an output. This also makes the return type more precise, returning a unification of the input types.

Bind the type for try more precisely

---

changelog/pending/20250305--cli--stack-selections-will-now-always-be-saved-as-if-stack-select-had-been-used.yaml
pkg/cmd/pulumi/stack/io.go

This change sets the stackLoadOption in chooseStack to true, whereas 
before it was set to false by default. 
This will cause the chooseStack functionality to set the backend state to remember the stack selected.
Fixes #14490

When calling chooseStack, always set `stackSetCurrent` to true

---

changelog/pending/20250304--cli-plugin--fix-plugin-exited-prematurely-false-positives.yaml
sdk/go/common/resource/plugin/plugin.go
sdk/go/common/resource/plugin/plugin_test.go

When closing a plugin, the plugin's connection state is used to determine whether the plugin had crashed, where a connection state other than `Ready` is presumed crashed. This can lead to false positives, as it's possible for the connection state to change from `Ready` to `Idle` after an idle timeout (e.g. 5 minutes) for plugins that have not crashed.
This leads to incorrect messages reported to users, such as:
```
Detected that /Users/user/.pulumi/plugins/resource-random-v4.18.0/pulumi-resource-random exited prematurely.
This is *always* a bug in the provider. Please report the issue to the provider author as appropriate.
```
This change avoids the false positives by making a request to a health check service on the plugin as a way of determining if the plugin is still alive. Most …

Fix plugin "exited prematurely" false positives

---

changelog/pending/20250225--auto-python--add-the-ability-to-rename-the-given-stack-to-the-python-automation-api.yaml
sdk/python/lib/pulumi/automation/_stack.py
sdk/python/lib/test/automation/test_local_workspace.py

As with the NodeJS Automation API, this PR adds the ability to rename the current stack using the automation API. It also adds a test that follows the same approach as with NodeJS.
* #18696
* #15357

Add `stack rename` to the Python Automation API

---

changelog/pending/20250224--auto-nodejs--add-stack-rename-to-the-nodejs-automation-api.yaml
sdk/nodejs/automation/stack.ts
sdk/nodejs/tests/automation/localWorkspace.spec.ts

The first of a series of PRs to add the ability to rename stacks to the automation API. I tried to follow the same pattern as the other commands in the API, but I'd appreciate someone with more experience here taking a look to make sure I've not missed something important! 
* https://github.com/pulumi/pulumi/issues/15357

Implement `stack rename` for the NodeJS automation API

---

.mise.toml
changelog/pending/20250226--auto-go--add-the-ability-to-rename-the-given-stack-to-the-go-automation-api.yaml
sdk/go/auto/optrename/optrename.go
sdk/go/auto/stack.go
sdk/go/auto/stack_test.go

To match both TypeScript and Python, this PR adds the `stack rename` command to the Automation API for Go.
* #15357
* #18696
* #18712
Fixes #15357.

Add the `stack rename` command to the Go Automation API.

---

Makefile

https://github.com/pulumi/pulumi/pull/18728 discussed the correct way to set this, but then typo'd out the "bin" at some point.

Fix make build to copy to go bin

---

developer-docs/providers/implementers-guide.md

Provider authors need to understand the interaction of Read() and Diff() during refresh. Here is my attempt to document this. It appears Check is not called during this flow. Appreciate any corrections.

developer-docs: Document pulumi refresh

---

pkg/backend/errors.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/backend_test.go
sdk/go/common/env/env.go

This PR was spun off of https://github.com/pulumi/pulumi/pull/18627. The new structured error is consumed there.

Refactor: Structured error for missing an env required when non-interactive use

---

sdk/go/common/workspace/templates.go
sdk/go/common/workspace/templates_test.go

This change was pulled out of https://github.com/pulumi/pulumi/pull/18627. This commit is a pure refactor & adds tests.

Refactor: Add structured errors when a template isn't found

---

cmd/pulumi-test-language/go.mod
cmd/pulumi-test-language/providers/component_property_deps_provider.go
cmd/pulumi-test-language/providers/component_provider.go
cmd/pulumi-test-language/providers/plain_provider.go
cmd/pulumi-test-language/providers/ref_ref_provider.go

These changes require Go 1.23 which should be fine to upgrade conformance tests to. We could make similar changes across pkg and sdk but might be a bit aggressive forcing them to 1.23 this soon (1.24 only just came out, so even though 1.22 technicaly isn't in our support list anymore we probably don't want to be too quick to force 1.23 on people).

Update from exp/maps to maps in the conformance tests

---

changelog/pending/20250306--engine--engine-will-respect-cgroup-limits-for-parallel.yaml
pkg/cmd/pulumi/main.go
pkg/cmd/pulumi/operations/flags_test.go
pkg/cmd/pulumi/operations/up.go
pkg/go.mod
pkg/go.sum
sdk/go/common/util/cmdutil/trace.go
tests/go.sum
tests/smoke_test.go

Fixes https://github.com/pulumi/pulumi/issues/18814
Nice small fix thanks to Uber's libraries. This will override GOMAXPROC, and then uses that to decide the value for --parallel.

Use go.uber.org/automaxprocs to respect cgroup cpu limits

---

pkg/cmd/pulumi/packagecmd/package_pack_sdk.go
pkg/cmd/pulumi/packagecmd/package_publish.go
pkg/cmd/pulumi/plugin/plugin_run.go

In the push to get rid of the "cmd" struct wrappers and just test directly against cobra, this gets rid of a couple of simple ones.

Fold a couple of simple commands into just cobra runs

---

pkg/cmd/pulumi/deployment/deployment_settings_utils_test.go
sdk/go/auto/cmd_test.go
sdk/go/common/util/gitutil/git_test.go

TempDir returns a temporary directory for the test to use.The directory is automatically removed when the test and
all its subtests complete. More info  https://pkg.go.dev/testing#B.TempDir

refactor: use t.TempDir() instead of os.MkdirTemp

---

pkg/cmd/pulumi/packagecmd/package_add.go

When getting the schema fails and returns a diagnostics error we currently only print the first error, and say "x more diagnostics". This happens e.g. when the schema fails to validate against the pulumi.json schema.  It's often helpful to see the entire list of errors instead, as that helps seeing the whole picture.  Print the whole list instead.

print all diagnostic errors when getting the schema failed

---

pkg/cmd/pulumi/pulumi.go
pkg/cmd/pulumi/whoami/whoami.go
pkg/cmd/pulumi/whoami/whoami_test.go

This removes the `whoAmICmd` to replace it with just the cobra wrapper. 
There's three things worth calling out here.
1. We can still mock out stdout by using `cmd.OutOrStdout()` in the run function, and setting it explicitly in the tests. Otherwise cobra defaults it to `os.Stdout`. This will be the general way of mocking stdout in commands going forward.
2. We inject the `workspace.Context` and `backend.LoginManager` to the new function so we can mock them in tests. They were hardcoded in the run function to the singleton instances.
3. Because we're injecting those two types we can just use the global `CurrentBackground` function. If we do this everywhere we should be able to remove the global `BackendInstance` variable from that function eventually.

Make `whoami` just a cobra command

---

changelog/pending/20250311--sdk-dotnet--upgrade-pulumi-dotnet-to-3-76-1.yaml
pkg/codegen/testing/test/helpers.go
scripts/get-language-providers.sh

This has been released and Awsx has started to rely on it, so our tests break without this being updated.

upgrade pulumi dotnet to 3.76.1

---

changelog/pending/20250311--engine--return-an-error-on-malformed-provider-references-rather-than-ignoring-them.yaml
pkg/engine/lifecycletest/provider_test.go
pkg/resource/deploy/source_eval.go

In https://github.com/pulumi/pulumi/pull/16241/ we originally added package references via the `provider` field. We would check to see if the field contained a "::" and if so treat it as an explicit provider reference, else we'd treat it as a package reference. If either of these failed to parse/lookup it would return an error.
In https://github.com/pulumi/pulumi/pull/16458/ we added a new explicit package ref field and stopped using the `provider` field to transmit the package reference. When we did this we removed the case from provider parsing for package refs, but we left in the check to see if the field contained a "::".
So before both these changes if you sent a malformed field like "hi" it would error, but after these two changes it would just ignore the provider field and use the …

Re-add provider error

---

cmd/pulumi-test-language/go.mod

When one does not have the correct Go version installed by default on the system, the version specified in the `go.mod` file needs to include the patch version for the Go tooling to automatically install the toolchain.  Make that so, so things don't break for people that have older Go versions still installed on the system.

use full Go version in pulumi-test-language/go.mod

---

pkg/resource/stack/secrets.go

- Reduce amount of memory allocated to the buffered channel from 3mb to 32kb.
- 1000 secrets is still more than 99% of stacks.

Reduce encryption batch size

---

changelog/pending/20250311--sdk-python--fix-mapping-input-names-in-construct-recursively-in-component-providers.yaml
sdk/python/lib/pulumi/provider/experimental/provider.py
sdk/python/lib/test/provider/experimental/test_provider.py
sdk/python/lib/test/provider/experimental/testdata/complex-args/__init__.py

Fix https://github.com/pulumi/pulumi/issues/18846
Python component host maps snake_case to camelCase while calculating the schema and seems to have good tests for that. At runtime during Construct invocation, we need to do the reverse camelCase to snake_case for actual component values. A basic version of this was in place, but it did not happen for types within lists/maps. This PR tries to fix this.
I'm surprised there are no tests around this tricky area. I added a test but I don't have high confidence I covered everything. I will also open a follow-up issue to do the same for outputs.
cc @julienp when you are back to check my PR too and chime in on adding test coverage.

[python/components] Map input names recursively

---

sdk/python/lib/pulumi/provider/experimental/analyzer.py

I audited the python analyzer and it looks like error messages are already decent (on the level of TypeScript). We can definitely do better but at least we give the context of type/property names most of the time.
I found just one exception - so here is a tiny change towards https://github.com/pulumi/pulumi/issues/18692

[python/components] Better error message for a missing type

---

pkg/engine/lifecycletest/framework/framework.go

Noticed this while working on parallel diff. Most of the lifecycle tests leave `Parallel` as zero, which eventually makes its way down to step executor setup which sets it to 1. So none of our lifecycle tests are really testing any parallelism in the system.
This sets `Parallel` to `runtime.NumCPU()` so that tests will start seeing operations happen in parallel, hopefully proving out more of the system.
N.B. This isn't the same as what we default `--parallel` to, we respect cgroup limits there but I figure for tests this is fine and saves moving that code to be shared by lifecycle tests.

Run lifecycle tests with parallelism

---

changelog/pending/20250311--sdk-go--fix-overriding-protect-in-child-resources.yaml
cmd/pulumi-test-language/tests/l2_resource_parent_inheritance.go
cmd/pulumi-test-language/tests/testdata/l2-resource-parent-inheritance/main.pp
sdk/go/pulumi-language-go/language_test.go
sdk/go/pulumi-language-go/testdata/projects/l2-resource-parent-inheritance/main.go
sdk/go/pulumi/context.go
sdk/go/pulumi/provider.go
sdk/go/pulumi/resource.go
sdk/go/pulumi/resource_test.go
sdk/go/pulumi/rpc_test.go
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsc/projects/l2-resource-parent-inheritance/index.ts
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsnode/projects/l2-resource-parent-inheritance/index.ts
sdk/python/cmd/pulumi-language-python/testdata/classes/projects/l2-resource-parent-inheritance/__main__.py
sdk/python/cmd/pulumi-language-python/testdata/setuppy/projects/l2-resource-parent-inheritance/__main__.py
sdk/python/cmd/pulumi-language-python/testdata/toml/projects/l2-resource-parent-inheritance/__main__.py

Also add an override test to l2-resource-parent-inheritance.
This fixes the issue described in https://github.com/pulumi/pulumi/issues/18833 but does not fully fix the optionality of protect in transforms and construct. That will require wire protocol changes, and public api changes to the Go SDK.

Fix protect inheritance in Go

---

pkg/backend/display/events.go
pkg/engine/events.go
pkg/engine/update.go

Fixes https://github.com/pulumi/pulumi/issues/18884
Steps in `OnResourceStepPost` could be read or incremented. If these happened at the same time you'd get a data race. That data race didn't actually matter but it could trigger the go race detector in tests. Worse was you could potentially race in the increment logic losing count by one. 
This changes the increment to an atomic add to avoid all races.

Update step counter atomicly

---

pkg/cmd/pulumi/org/org_search.go
pkg/cmd/pulumi/org/org_search_ai.go

Fix two locations where we made a `QueryOptions` struct just to set it's display field, and then only looked at the display field.
Replaced with just a display options variable.

Remove unused QueryOptions structs

---

docs/architecture/providers/parameterized.md
sdk/go/common/resource/plugin/provider.go

- Clarify key facts people need to know.
- Add the point of view of what a provider author needs to know.
- Add godocs for Parameterization types to help provider implementers.

Improve parameterize docs

---

pkg/engine/update.go

Turns out https://github.com/pulumi/pulumi/pull/18886 wasn't enough, we need to explicitly do an atomic load of this Steps variable as well.

Load Steps variable with atomic

---

sdk/go/common/testing/util.go
sdk/go/pulumi-language-go/language_test.go
sdk/nodejs/cmd/pulumi-language-nodejs/language_test.go
sdk/python/cmd/pulumi-language-python/language_test.go

Similar to what we did in yaml in
https://github.com/pulumi/pulumi-yaml/pull/741, only log a truncated version of stdout/stderr for each test.  These log lines can get quite long, so if that conformance test fails, it will overload the GitHub runner with too much output, making it hard debug.  Logging only the first 1024 characters sidesteps that.

implement log truncation in conformance tests

---

sdk/go/common/apitype/organizations.go

Part of https://github.com/pulumi/pulumi-service/issues/26419
Defines the API response type for the impending `GetDefaultOrganization` API.

Add GetDefaultOrganizationResponse type for backend/cli definition

---

changelog/pending/20250317--yaml--introduce-the-packages-section-in-pulumi-yaml.yaml
cmd/pulumi-test-language/interface.go
pkg/cmd/pulumi/packagecmd/project_sdk_link.go
pkg/cmd/pulumi/policy/policy_publish.go
pkg/engine/deployment.go
sdk/go/common/resource/plugin/context.go
sdk/go/common/resource/plugin/host.go
sdk/go/common/resource/plugin/host_test.go
sdk/go/common/workspace/project.go
sdk/go/common/workspace/project.json
sdk/go/common/workspace/project_test.go
tests/integration/run_plugin/go/main.go

This PR introduces a new optional section to Pulumi.yaml called `packages`. The section can give names to package dependencies and provide sources, versions, and arguments for those dependencies. Two forms are supported: short and explicit:
```yaml
packages:
planetscale:
source: terraform-provider
version: 0.3.0
parameters:
- planetscale/planetscale
mylocalprovider: ./local/path
agithubpackage: github.com/myorg/myrepo@v0.1.0
```
An internal type `packageValue` is defined so that we could support deserialization of both strings and structured specs.
I've tried to keep the local folder resolution logic consistent with what `pulumi package` does today. For that, I refactored a `IsLocalPluginPath` helper function that is able to tell whether a given source is a folder path or something else …

Introduce the packages section in Pulumi.yaml

---

pkg/cmd/pulumi/packagecmd/package.go
pkg/cmd/pulumi/packagecmd/package_pack_sdk.go
pkg/cmd/pulumi/packagecmd/package_publish_sdk.go

This renames the existing files/methods of the dev-only SDK publishing commands. It's in preparation of https://github.com/pulumi/pulumi/pull/18818 which actually concerns itself with publishing packages

Rename SDK publishing commands to reflect that they're operating on SDKs

---

changelog/pending/20250318--cli-package--fix-explicitly-named-package-names-in-nodejs.yaml
pkg/cmd/pulumi/packagecmd/project_sdk_link.go
pkg/cmd/pulumi/packagecmd/project_sdk_link_test.go

In `pulumi.json` PackageName is documented as `NPM package name (includes @namespace)`.  However in LinkPackage we're using it to specify the importname of the package, which is not correct.  Fix that, and fix up the test as well.

fix nodejs PackageName usage in LinkPackage

---

pkg/codegen/dotnet/gen_program.go

Discovered in https://github.com/pulumi/pulumi-dotnet/pull/545. Hopefully this will fix the conformance test.

fix usage of rootnamespace in dotnet programgen

---

pkg/codegen/dotnet/gen_program.go

https://github.com/pulumi/pulumi/pull/18932 fixed the right thing, but it wasn't complete.  We also need to bring the namespace into the right format.  Do so here.

dotnet: format namespace correctly in programgen

---

sdk/go/common/apitype/service.go

Fix https://github.com/pulumi/pulumi-service/issues/26811
Follow-up from [Slack conversation](https://pulumi.slack.com/archives/C02VCJEBT2N/p1741979075342809): Update the Capabilities API schema to include default orgs, to distinguish between backends that will support the new `GetDefaultOrg` API.
See https://github.com/pulumi/pulumi/pull/18908 for the `GetDefaultOrg` API response type.

Add default orgs as an API capability

---

cmd/pulumi-test-language/go.mod
cmd/pulumi-test-language/interface_test.go
cmd/pulumi-test-language/internal_test.go
cmd/pulumi-test-language/l1_empty_test.go
cmd/pulumi-test-language/l1_main_test.go
cmd/pulumi-test-language/l2_continue_on_error_test.go
cmd/pulumi-test-language/l2_destroy_test.go
cmd/pulumi-test-language/l2_large_test.go
cmd/pulumi-test-language/l2_resource_asset_test.go
cmd/pulumi-test-language/l2_resource_simple_test.go
cmd/pulumi-test-language/program_overrides_test.go
cmd/pulumi-test-language/runtime_options_test.go
sdk/go/pulumi-language-go/go.mod
sdk/go/pulumi-language-go/language_test.go
sdk/go/pulumi-language-go/main_test.go
sdk/nodejs/cmd/pulumi-language-nodejs/go.mod
sdk/nodejs/cmd/pulumi-language-nodejs/language_test.go
sdk/nodejs/cmd/pulumi-language-nodejs/main_test.go
sdk/python/cmd/pulumi-language-python/go.mod
sdk/python/cmd/pulumi-language-python/language_test.go
sdk/python/cmd/pulumi-language-python/main_test.go

This required updating these to go 1.24, but these aren't depended on as libraries so that should be fine.
One of the recommendations of https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize

Update languages and conformance tests to use `T.Context()`

---

changelog/pending/20250318--cli-install-package--install-package-sdks-on-pulumi-install.yaml
pkg/cmd/pulumi/install/install.go
pkg/cmd/pulumi/packagecmd/package_add.go
tests/integration/integration_nodejs_test.go
tests/integration/packages-install/Pulumi.dev.yaml
tests/integration/packages-install/Pulumi.yaml
tests/integration/packages-install/index.ts
tests/integration/packages-install/package.json
tests/integration/packages-install/tsconfig.json

This change adds a new step to `pulumi install`: it will list all packages from the `packages` section and install SDKs for each of them. This will happen on each run of `pulumi install`, there is no check if SDKs are already present or not, but this is supposed to be idempotent.
`package add` has no functional changes yet, it's just refactored to expose a helper function.
I added a test with the `packages` section that runs `pulumi install` and checks that the right thing was dowloaded. The `codecov` number sucks but it looks like we only have integration level tests for pulumi install and packages?
Also, a small cleanup - remove the existing folder before copying the generated SDKs, so there is no dirty files left. Fixes https://github.com/pulumi/pulumi-yaml/issues/755
Part of …

Install package SDKs on pulumi install

---

.golangci.yml
pkg/backend/display/display_test.go
pkg/secrets/passphrase/manager_test.go
pkg/testing/integration/program.go
sdk/go/auto/git_test.go
sdk/go/auto/stack_test.go
sdk/go/common/resource/asset_test.go
sdk/go/common/resource/plugin/host_test.go
sdk/go/common/testing/environment.go
sdk/go/common/workspace/plugins_install_test.go
sdk/go/common/workspace/project_test.go
tests/stack_test.go

The `tenv` linter is deprecated, and `usetesting` is the suggested replacement.  Switch out the linters to get rid of the warning and fix up the places where `usetesting` complains.

use usetesting linter instead of tenv

---

tests/integration/integration_test.go

These tests disable the paralleltest linter because they claim to use programtest.  However they are just using `ptesting.NewEnvironment`, which doesn't by itself make the tests parallel (it enables running them in parallel though because it sets up separate environments).
Remove the line disabling the linter and make the tests run in parallel.

run more integration tests in parallel

---

Makefile

`make dist` currently depends on `build`, even though it doens't use any of its artifacts.  At the same time `dist` is also used in `make build_local`, which is used for rebuilding binaries for integration tests. However since we're setting GOBIN to `$repo_root/bin`, `build` now tries to copy the pulumi binary to the same directory as the `dist` command does, and the same directory the binary is being built in.
We still want to use `make dist` for `build_local`, because it also builds the language plugins, which are used in the integration tests. Just remove the `build` target from the dependency list of `dist`. `go install` already does that job, and we don't need to build the wasm bits, as `dist` is expected to install binaries not just build them anyway.
(This was accidentally broken …

make dist target not depend on build and fix PULUMI_INTEGRATION_REBUILD_BINARIES

---

changelog/pending/20250318--sdkgen--aliases-in-provider-schemas-can-now-be-set-with-just-an-array-of-strings-for-the-aliased-types.yaml
pkg/codegen/dotnet/gen.go
pkg/codegen/go/gen.go
pkg/codegen/nodejs/gen.go
pkg/codegen/python/gen.go
pkg/codegen/schema/bind.go
pkg/codegen/schema/pulumi.json
pkg/codegen/schema/schema.go
pkg/codegen/schema/schema_test.go
pkg/codegen/testing/utils/host.go
tests/testdata/codegen/aliases-1.0.0.json
tests/testdata/codegen/aliases-1.0.0.yaml

When we added aliases to schemas we added them with the project and name aliases that programs can specify as well. 
Codegen was never hooked up to use these fields, and it doesn't really make sense for a schema to say "resources of this type always used to come from the X project".
Providers team asked about these the other day, and rather than re-explaining their dead code again this just gets rid of them. It also simplifies the "aliases" property to allow just strings. So rather than:
```
"aliases": [{"type": "pkg:index::OldType"}],
```
You can now just do:
```
"aliases": ["pkg:index::OldType"],
```
A mixture of forms also works. I've added tests to ensure that we roundtrip these in the same format we read them. Schemas built from PackageSpecs will continue to default to object form. …

Cleanup aliases in schema

---

.mise.toml
docs/contributing/development.md

Ensure that `$PULUMI_ROOT` is always set to `$REPO/.root`, even when running from a subfolder.

Use Mise config_root var instead of env.PWD

---

sdk/python/pyproject.toml

`pytest-watch` is a dev dependency, not a regular dependency, as pointed out here: https://github.com/pulumi/pulumi/commit/1c880e26ddcae0287b535a0ae6b5193059cd5ccd#r154029991

pytest-watch is a dev dependency

---

sdk/nodejs/provider/experimental/provider.ts
sdk/nodejs/provider/experimental/schema.ts
sdk/nodejs/provider/provider.ts
sdk/nodejs/tests/provider/experimental/schema.spec.ts
tests/integration/component_provider/nodejs/component-provider-host/provider/package.json
tests/integration/integration_nodejs_test.go

We decided to lead with git tags for source-based plugins and ignore anything language specific, like the version set in package.json. For a local package, we'll return an nil version. This PR removes our dependency on the package version. I also had to modify the base Provider class to make `version` nullable.
Resolve https://github.com/pulumi/pulumi/issues/18967

[nodejs] Stop returning a version from componentProviderHost

---

changelog/pending/20250320--cli-install-package--dont-add-duplicate-sdks-to-requirements-txt.yaml
pkg/cmd/pulumi/packagecmd/project_sdk_link.go
tests/integration/integration_python_test.go

Check if the package is already present in requirements.txt before adding it.
Fixes https://github.com/pulumi/pulumi/issues/18969
Fixes https://github.com/pulumi/pulumi-terraform-module/issues/207

Avoid duplicate packages in requirements.txt

---

.github/workflows/ci-run-test.yml
cmd/pulumi-test-language/test_host.go
pkg/cmd/pulumi/plugin/plugin.go
pkg/cmd/pulumi/plugin/plugin_run.go
pkg/codegen/schema/loader.go
pkg/codegen/schema/loader_test.go
pkg/engine/plugins.go
pkg/resource/deploy/deploytest/pluginhost.go
pkg/resource/deploy/providers/registry_test.go
sdk/go/common/resource/plugin/analyzer_plugin.go
sdk/go/common/resource/plugin/converter_plugin.go
sdk/go/common/resource/plugin/host.go
sdk/go/common/resource/plugin/langruntime_plugin.go
sdk/go/common/resource/plugin/langruntime_test.go
sdk/go/common/resource/plugin/mock.go
sdk/go/common/resource/plugin/provider_plugin.go
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_test.go
tests/integration/integration_test.go

When trying to find plugins we currently pass its kind, name and version through.  However that's not enough to fully specify a plugin, especially given the way git plugins work.  Also pass through the PluginDownloadURL, so we can fully identify a plugin, and find the right one.

pass through pluginspec for finding plugins

---

pkg/codegen/hcl2/model/expression.go

I special cased this lift for pulumiResourceType/Name the other day and wrote a comment saying we were skipping them. But found we actually already had an issue that described how this lift was over eager and if we fixed this generally it would cover pulumiResourceType/Name as well. Rewording the comment and adding the link to the issue in so that we don't have to re-discover this.

Add TODO to liftOperationType call

---

changelog/pending/20250324--sdk-python--remove-the-dev-dependency-on-pytest-watch.yaml
sdk/python/Makefile
sdk/python/pyproject.toml
sdk/python/uv.lock

While this seems totally fine for me locally, it seems to be fine only for my machine, which isn't ideal. This PR removes it from our dependencies entirely.

Remove `pytest-watch` entirely

---

changelog/pending/20250321--sdk-nodejs--check-for-typescript-errors-in-components-plugin.yaml
sdk/nodejs/biome.json
sdk/nodejs/provider/experimental/analyzer.ts
sdk/nodejs/tests/provider/experimental/analyzer.spec.ts
sdk/nodejs/tests/provider/experimental/testdata/syntax-error/index.ts

When analyzing a components plugin, check for TypeScript errors and report them to the user.
Part of https://github.com/pulumi/pulumi/issues/18692

Check for typescript errors in components plugin

---

tests/integration/integration_test.go

We pass in nil for the info/error writers in InstallDependencies, which means that if there is an actual error we panic and don't have any valid error output.  Fix that by passing in `os.Stdout` and `os.Stderr`, which go test will then print.
*Something* fails when trying to merge https://github.com/pulumi/pulumi/actions/runs/14039014408/job/39304652576, but it's impossible to see what because of the panic.

pass in valid info/error writers in test

---

pkg/cmd/pulumi/packagecmd/package_gen_sdk.go

A fix for a formatting issue with the `gen-sdk` command.  Given a make routine that generates SDK code before running some gotests, we see the phrase `SDK has been written to sdk/go` with improper formatting:
```plain
❯ make examples/random-login/test
go build -C examples/random-login -o ../../bin/examples/pulumi-resource-random-login github.com/pulumi/pulumi-go-provider/examples/random-login
pulumi package get-schema ./bin/examples/pulumi-resource-random-login > examples/random-login/schema.json
SDK has been written to sdk/gook        github.com/pulumi/pulumi-go-provider/examples/random-login      (cached)
?       github.com/pulumi/pulumi-go-provider/examples/random-login/sdk/go/randomlogin   [no test files]
?       github.com/pulumi/pulumi-go-provider/examples/random-login/sdk/go/randoml …
```

`pulumi package gen-sdk`: newline character

---

sdk/go/common/testing/environment.go

We're seeing failures in CI on Windows when Go tries to delete the temp dir. Revert back to the previous implementation that uses `os.MkdirTemp`. On Windows, if there's an error deleting the temp dir, it will be logged, but won't cause a failure. This also allows us to keep the environment if the test fails (via `DeleteIfNotFailed`).
Fixes #19010

Revert change to use `t.TempDir` in testing environment

---

changelog/pending/20250224--cli-new--allow-pulumi-new-to-use-templates-defined-in-the-pulumi-cloud.yaml
pkg/cmd/pulumi/newcmd/new.go
pkg/cmd/pulumi/newcmd/new_ai_test.go
pkg/cmd/pulumi/newcmd/new_test.go
pkg/cmd/pulumi/newcmd/template.go
pkg/cmd/pulumi/operations/up.go
pkg/cmd/pulumi/templates/org.go
pkg/cmd/pulumi/templates/templates.go
pkg/cmd/pulumi/templates/templates_test.go
pkg/cmd/pulumi/templates/workspace.go

This PR allows `pulumi new` to fetch org-wide templates from `app.pulumi.com` when they
are enabled. Part of https://github.com/pulumi/pulumi-service/issues/25732.
Conceptually, there are 2 parts to this PR:
- Wraps `workspace.RetrieveTemplates` in a new API specific for `cmd`:
```go
// Create a new [Template] [Source] associated with a given [Scope].
func New(
ctx context.Context, templateNamePathOrURL string, scope Scope,
templateKind workspace.TemplateKind, interactive bool,
) *Source { ... }
```
This is necessary because `workspace.RetrieveTemplates` is in `sdk`: `"github.com/pulumi/pulumi/sdk/v3/go/common/workspace"`. The new template download functionality needs to depend on various backend features such as `cmdBackend "github.com/pulumi/pulumi/pkg/v3/cmd/pulumi/backend"`, which are …

Fetch Org-wide Project Templates from `app.pulumi.com`

---

tests/config_test.go
tests/history_test.go
tests/login_test.go
tests/policy_new_test.go
tests/remote_test.go
tests/smoke_test.go
tests/stack_test.go

We had a duplicate copy of `deleteIfNotFailed` that can be replaced with the built-in `DeleteIfNotFailed` method.

Delete duplicate `deleteIfNotFailed` helper

---

sdk/go/common/testing/environment.go

This method was added when `DeleteEnvironment` used to assert it did not fail ([see](https://github.com/pulumi/pulumi/commit/59f88030b72b7c621b302b1890d2df34538daf1d)). `DeleteEnvironment` was later changed to allow failures, which can happen in CI, particularly on Windows.
`DeleteEnvironmentFallible` is no longer used anywhere ([see](https://github.com/search?q=DeleteEnvironmentFallible+NOT+is%3Afork&type=code); only shows up in old forks).
This change removes the dead code.
Follow-up from https://github.com/pulumi/pulumi/pull/19017#discussion_r2011970183

Delete unused `DeleteEnvironmentFallible` method

---

changelog/pending/20250325--cli-package--use-correct-local-path-for-git-based-components-with-a-version-tag.yaml
pkg/resource/deploy/deploytest/pluginhost.go
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_test.go
tests/integration/external_tagged_component/.gitignore
tests/integration/external_tagged_component/Pulumi.yaml
tests/integration/external_tagged_component/index.ts
tests/integration/external_tagged_component/package.json
tests/integration/external_tagged_component/tsconfig.json
tests/integration/integration_test.go

In https://github.com/pulumi/pulumi/pull/18951, we started passing through PluginSpec to get the plugin info, instead of relying on fixing up the name.  This works great, except that we missed the critical fact that those plugins can also have tagged versions, and the codepath to find those tagged plugins is different.
Make sure we also pick up the plugins using their local names for tagged plugins as well.
Part of https://github.com/pulumi/pulumi/issues/19022

use localname for plugin selection for tagged plugins as well

---

pkg/cmd/pulumi/packagecmd/package_publish.go
pkg/cmd/pulumi/packagecmd/package_publish_test.go

This change builds on top of https://github.com/pulumi/pulumi/pull/18818 to automatically slurp up `README.md` files from the package source (e.g. when publishing a component).
That way users do not manually have to specify their READMEs

Enable 'pulumi package publish' to detect README files

---

changelog/pending/20250321--sdk-nodejs--allow-namespace-for-components-to-be-set-in-pulumiplugin-yaml.yaml
sdk/nodejs/cmd/run-plugin/run.ts
sdk/nodejs/provider/experimental/provider.ts
sdk/nodejs/provider/experimental/schema.ts
sdk/nodejs/tests/provider/experimental/provider.spec.ts
sdk/nodejs/tests/provider/experimental/schema.spec.ts
sdk/nodejs/yarn.lock
tests/integration/integration_nodejs_test.go
tests/integration/namespaced_component/PulumiPlugin.yaml
tests/integration/namespaced_component/index.ts
tests/integration/namespaced_component/package.json

For components in NodeJS, we can try to infer the namespace from the package name in the `package.json` file, if it is in the format `@<namespace>/<name>`.
Not sure it's worth adding an integration test here? It would be nice to have, but it's a lot of work to set up for just this. A conformance test would be neat, but unfortunately we don't have those running `package add` yet.

nodejs: allow namespace implicitly inferred

---

changelog/pending/20250326--auto-python--add-preview-only-option-for-destroy-in-the-python-automation-api.yaml
sdk/python/lib/pulumi/automation/_stack.py
sdk/python/lib/test/automation/test_local_workspace.py

Part of #18725. This PR adds the ability to run `destroy --preview-only` via the Python automation API.

Add the `--preview-only` option for `destroy` in the Python API

---

changelog/pending/20250325--sdk-python--add-getrequiredpackages-to-the-python-automation-api.yaml
sdk/python/lib/pulumi/automation/_server.py

This command is used as part of `create_or_select_stack`, which has caused problems such as #18955. This PR adds the command to the API, which then fixes the error.
Fixes #18955.

Support `GetRequiredPackages` in the Python Automation API

---

changelog/pending/20250321--cli-package--support-github_token-and-gitlab_token-in-pulumi-package-add-for-git-packages.yaml
sdk/go/common/util/gitutil/git.go
sdk/go/common/util/gitutil/git_test.go

When cloning using our gitutil, we try to paste the URL and get access tokens.  However we currently don't support such URLs in `package add`, and it's often more convenient to set the authentication in the environment.  Allow setting the `GITHUB_TOKEN` and `GITLAB_TOKEN` environment variables for authentication.

gitutil: use access tokens from environment if possible

---

changelog/pending/20250326--auto-nodejs--add-the-preview-only-option-for-destroy-in-the-nodejs-automation-api.yaml
sdk/nodejs/automation/stack.ts
sdk/nodejs/tests/automation/localWorkspace.spec.ts

Part of #18725. This PR adds the ability to run destroy `--preview-only` via the NodeJS automation API.

Add the `--preview-only` option for `destroy` in the NodeJS API

---

changelog/pending/20250327--programgen--fix-plugin-resolution-in-convert.yaml
pkg/cmd/pulumi/convert/convert.go
pkg/codegen/convert/base_plugin_mapper.go
pkg/codegen/convert/base_plugin_mapper_test.go
pkg/codegen/convert/provider_factory.go
sdk/go/common/workspace/plugins.go

Change #18951  introduced more robust plugin resolution, but convert has
some quirks that didn't set the "kind" field so resolution was not
working.  This fixes that, adds some testing, and some helpers to help
avoid this.
In the long run it'd be nice if mappers and plugin resolution used the
same functions, but this at least fixes it for now.
fixes #19039

Fix plugin resolution in convert.

---

sdk/nodejs/provider/experimental/analyzer.ts
sdk/nodejs/tests/provider/experimental/analyzer.spec.ts
sdk/nodejs/tests/provider/experimental/testdata/re-exports/anotherComponent.ts
sdk/nodejs/tests/provider/experimental/testdata/re-exports/components.ts
sdk/nodejs/tests/provider/experimental/testdata/re-exports/index.ts
sdk/nodejs/tests/provider/experimental/testdata/re-exports/myComponent.ts

Found a case when Analyzer fails to find TypeScript classes. It's a re-export:
```ts
export { MyComponent } from "./myComponent"; 
```
This PR adds a case for re-exports in schema analyzer.

[components/nodejs] Discover component types through re-exports

---

changelog/pending/20250326--sdk-python--set-name-and-namespace-via-component_provider_host.yaml
pkg/cmd/pulumi/packagecmd/project_sdk_link.go
sdk/go/common/resource/plugin/provider_plugin.go
sdk/go/common/resource/plugin/provider_plugin_test.go
sdk/go/common/workspace/plugins.go
sdk/nodejs/provider/experimental/provider.ts
sdk/nodejs/provider/experimental/schema.ts
sdk/nodejs/tests/provider/experimental/schema.spec.ts
sdk/python/lib/pulumi/provider/experimental/ComponentProvider.md
sdk/python/lib/pulumi/provider/experimental/__init__.py
sdk/python/lib/pulumi/provider/experimental/analyzer.py
sdk/python/lib/pulumi/provider/experimental/host.py
sdk/python/lib/pulumi/provider/experimental/provider.py
sdk/python/lib/pulumi/provider/experimental/schema.py
sdk/python/lib/test/provider/experimental/test_analyzer.py
sdk/python/lib/test/provider/experimental/test_provider.py
sdk/python/lib/test/provider/experimental/test_schema.py
sdk/python/lib/test/provider/experimental/testdata/complex-args/PulumiPlugin.yaml
sdk/python/lib/test/provider/experimental/testdata/missing-input/PulumiPlugin.yaml
tests/integration/component_provider/python/component-provider-host/provider/__main__.py
tests/integration/component_provider/python/exception/provider/__main__.py
tests/integration/component_provider/python/recursive-types/provider/__main__.py
tests/integration/component_test/python-component/__main__.py
tests/integration/integration_nodejs_test.go
tests/integration/integration_python_test.go

Explicitly set the name (and optionally namespace) in `component_provider_host`, and remove `Metadata`.
A future boostrap-less mode will be able to infer the name from `pyproject.toml` (provided we support python packages).

python: set name and namespace via component_provider_host

---

changelog/pending/20250327--programgen-nodejs--fix-references-to-variables-that-were-renamed-due-to-keyword-overlap-etc-in-resource-attributes.yaml
pkg/codegen/nodejs/gen_program.go
pkg/codegen/nodejs/gen_program_expressions.go
pkg/codegen/testing/test/program_driver.go
tests/testdata/codegen/this-keyword-resource-attr-pp/nodejs/submodule.ts
tests/testdata/codegen/this-keyword-resource-attr-pp/nodejs/this-keyword-resource-attr.ts
tests/testdata/codegen/this-keyword-resource-attr-pp/submodule/main.pp
tests/testdata/codegen/this-keyword-resource-attr-pp/this-keyword-resource-attr.pp

When creating resources/variables when generating typescript from PCL,
the instantiation is renamed but references is when assigning attributes
specifically were overlooked.  Simply always renaming within lowering is
not acceptable since it will rewrite legitamate references to `this`.
Instead, specifically when referencing pcl attribute assigns (which
cannot reference `this` in the typescript sense, as these are only
doable when generating code as in the case of parent assign) rename
variables with valid names.
Fixes #18542

Fix this being incorrectly renamed in typescript when instantiating resources

---

Makefile
build/common.mk
sdk/go/Makefile

Previously, we installed the `pulumi` binary when `make build` was run. `make build` should only *build* the binary, `make install` should *install* it. This commit brings `make build` back to what most developers expect.

Stop installing `pulumi` on `make build`

---

Makefile

This makes the Makefile simpler *and* more performant. The only semantic change is marking `build_local` as `PHONY`.

Don't recursively call `make` as part of `make build_local`

---

scripts/get-job-matrix.py

dotnet 6 is no longer in support, we can move tests to just test against 8 and 9.
Also rewrote the version sets to not repeat the version numbers in each set.

Minimum dotnet version is now 8, not 6

---

changelog/pending/20250327--cli--add-run-program-support-to-pulumi-destroy.yaml
pkg/backend/diy/backend.go
pkg/backend/httpstate/backend.go
pkg/cmd/pulumi/deployment/remote.go
pkg/cmd/pulumi/operations/destroy.go
pkg/cmd/pulumi/operations/preview.go
pkg/cmd/pulumi/operations/refresh.go
pkg/cmd/pulumi/operations/up.go
pkg/engine/destroy.go

This adds `--run-program` to `pulumi destroy`.
When true this will cause the engine to run the users program as part of the destroy to update providers and component resources.

Add --run-program to destroy

---

sdk/go/Makefile

We try to avoid copying the pulumi-lanugage-go binary if it the file is the same.  However this uses bash-isms, which don't work in every shell.  Make sure we run it in `bash` to avoid issues with it.

make build_local with shells other than bash

---

pkg/cmd/pulumi/packagecmd/project_sdk_link.go
sdk/go/common/resource/plugin/host.go
sdk/go/common/workspace/plugins.go

We introduced this helper in https://github.com/pulumi/pulumi/pull/19043.  Use it everywhere instead of the string comparison as a cleanup.

use `spec.IsGitPlugin()` consistently

---

sdk/go/pulumi/context.go
sdk/go/pulumi/context_test.go
sdk/go/pulumi/mocks.go
sdk/go/pulumi/run_test.go

This PR builds on #19019 by adding additional unit tests and slight refactoring. This work ensures that `RegisterResourceOutputs` can be called multiple times for the same resource URN without triggering multiple RPC calls. Any subsequent calls become no-ops, preventing provider failures caused by redundant output registrations.  
While a broader fix at the engine level is desirable, this SDK-level change is necessary to support the components work in `pulumi-go-provider`. Previously, the `pulumi-go-provider``infer` framework handled output registration for components. However, a recent update allows converting existing Pulumi component programs into providers, where outputs may already be explicitly registered within the program code. This can result in duplicate calls to …

[sdk/go] Ensure RegisterResourceOutputs is Idempotent

---

cmd/pulumi-test-language/tests/l3_component_simple.go
cmd/pulumi-test-language/tests/testdata/l3-component-simple/main.pp
cmd/pulumi-test-language/tests/testdata/l3-component-simple/myComponent/main.pp
pkg/codegen/pcl/program.go
sdk/go/pulumi-language-go/language_test.go
sdk/go/pulumi-language-go/testdata/overrides/l3-component-simple/Pulumi.yaml
sdk/go/pulumi-language-go/testdata/overrides/l3-component-simple/go.mod
sdk/go/pulumi-language-go/testdata/overrides/l3-component-simple/main.go
sdk/go/pulumi-language-go/testdata/overrides/l3-component-simple/myComponent.go
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsc/projects/l3-component-simple/.gitignore
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsc/projects/l3-component-simple/Pulumi.yaml
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsc/projects/l3-component-simple/index.ts
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsc/projects/l3-component-simple/myComponent.ts
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsc/projects/l3-component-simple/package.json
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsc/projects/l3-component-simple/tsconfig.json
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsnode/projects/l3-component-simple/.gitignore
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsnode/projects/l3-component-simple/Pulumi.yaml
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsnode/projects/l3-component-simple/index.ts
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsnode/projects/l3-component-simple/myComponent.ts
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsnode/projects/l3-component-simple/package.json
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsnode/projects/l3-component-simple/tsconfig.json
sdk/python/cmd/pulumi-language-python/language_test.go

Adds a simple conformance test that component resources work. We added support for these for converting TF modules, but this is also good for testing that the runtimes treat component resources the same way.
Currently this only tests Typescript because I ran into programgen issues for both Go and Python. 
Go is missing a load of types to go from literals to Input types. 
Python is outputting TypedDicts with `total=false` that then don't type check when accessed.

l3-component-simple test

---

changelog/pending/20250328--sdk-nodejs--fix-names-in-type-references-in-components.yaml
sdk/nodejs/provider/experimental/analyzer.ts
sdk/nodejs/provider/experimental/provider.ts
sdk/nodejs/tests/provider/experimental/analyzer.spec.ts
tests/integration/integration_nodejs_test.go
tests/integration/namespaced_component/index.ts

When we introduced namespaces in TypeScript, we missed that the Analyzer was still using `packageJSON.name` to generate type references. This meant types would be generated with just the name, but references would be broken, because they would use the full name field from `package.json`, which can include the namespace.
Fix that by passing the name through correctly.
Fixes https://github.com/pulumi/pulumi/issues/19055

fix names in type references when namespaces are defined in package.json

---

changelog/pending/20250331--pkg--update-moby-moby-to-26-1-5.yaml
pkg/go.mod
pkg/go.sum
tests/go.sum

Dependabot doesn't seem to flag it (probably as the issue is in docker-engine and not the client), but we've received reports some other scanners are flagging CVE-2024-41110 for our current version of moby/moby.
This is fixed in https://github.com/moby/moby/releases/tag/v26.1.5

Upgrade moby/moby for CVEs

---

changelog/pending/20250401--sdk-nodejs--fix-sdk-generation-for-components-that-use-resource-references-and-are-namespaced.yaml
pkg/codegen/nodejs/gen.go

When introducing namespaces we (I) were a little overzealous in typescript SDK gen, and we end up importing even pulumi packages from the package namespace.  Fix that.
Fixes https://github.com/pulumi/pulumi/issues/19054

typescript: fix resource reference imports with namespaces

---

changelog/pending/20250401--sdk-python--serialize-component-description-to-the-json-schema.yaml
sdk/python/lib/pulumi/provider/experimental/schema.py
tests/integration/integration_python_test.go

We properly infer the component description in the analysis code, but forgot to add it to the schema JSON.
Descriptions for complex types or fields worked correctly.

Serialize component description to the JSON schema

---

.github/workflows/ci-run-test.yml

Having this action unpinned means we'll pick up any push to main. This action hasn't changed in two years, so just pin it to the latest commit, so it won't move under our feet.
Just noticed this while looking at some actions output.

pin jlumbroso/free-disk-space action

---

sdk/python/cmd/pulumi-language-python/main.go

In the python conformance tests we build wheels for the Python SDK, and the SDK for every provider.  We use `python build` for this. `python build` builds a sdist and then a wheel from that by default. However we don't need the source distribution at all in conformance tests and only care about the wheel. Instructing `python build` to only build the wheel cuts the build time roughly in half.  This brings the time to run a single python conformance test locally from 48 seconds to 27 seconds.

speed up python performance tests with this one simple trick

---

changelog/pending/20250401--cli-plugin--f-ix-slowness-of-workspace-detectprojectfrompath-affecting-pulumi-convert-timings.yaml
sdk/go/common/util/fsutil/walkup.go
sdk/go/common/util/fsutil/walkup_test.go
sdk/go/common/workspace/paths.go
sdk/go/common/workspace/paths_test.go

There is a utility function workspace.DetectProjectFromPath that attempts to scan the file system starting at a given path to find the deepest containing ancestor directory that appears to have a Pulumi.yaml or a similar project file present.
Before this change it did not scale well for situations where ancestor folders have a lot of entries. It would scan each ancestor directory and examine every entry to test it for being the Pulumi project file.
For example, in a `pulumi convert` scenario a Mac M3 Pro was taking 10-15 seconds to perform 300000 file system checks here in a situation where tempdirs had a lot of entries, dominating the cost of any other calls.
With this change the function no longer scans directories but instead probes for possible Pulumi.yaml file locations more …

Speed up workspace.DetectProjectFromPath

---

pkg/cmd/pulumi/packagecmd/project_sdk_link.go

We should be using the language host codegen in all cases now. This fixes the last hardlink we had to dotnet codegen in GenSDK.

Use dotnet language host based codegen

---

sdk/python/cmd/pulumi-language-python/main.go

In https://github.com/pulumi/pulumi/pull/19099 we made some progress speeding up python conformance tests.  If we have uv available we can go one step further, and use that to build the wheel.  This gets a single test to run in 20 seconds instead of 27 locally on my machine.
The benefit is even bigger when running more tests, as `pip` seems to have some internal locking against other instances, which `uv` doesn't suffer from.

further speed up python conformance tests when uv is available

---

sdk/python/cmd/pulumi-language-python/main.go
sdk/python/toolchain/pip.go
sdk/python/toolchain/poetry.go
sdk/python/toolchain/toolchain.go
sdk/python/toolchain/uv.go

Mypy doesn't exclude the virtualenv by default when typechecking. It does exclude only hidden files, starting with a `.`.  At the same time, `uv` installs a file into the virtualenv that doesn't typecheck correctly.
By default that's fine, as `uv` uses `.venv` as its virtualenv location, but it breaks when someone uses a custom venv location, and uses mypy.  For example in conformance tests, we use `venv` as the virtual env location, which in turn makes the tests fail because of `mypy`.  This could also happen to someone using a custom venv location with `uv`.

exclude virtualenv from being checked by mypy

---

changelog/pending/20250404--sdk-python--return-an-inputpropertyerror-for-invalid-enum-values.yaml
sdk/python/lib/pulumi/provider/experimental/provider.py
sdk/python/lib/test/provider/experimental/test_provider.py

Return a nicer error message when a user sets a bad value for an enum typed property. Using InputPropertyError ensures we display actionable error information, for example:
```
error: provider:index:MyComponent resource 'comp' has a problem:
- property enumInput with value '{7}' has a problem: Invalid value 7.0 of type <class 'float'> for enum 'Emu'
```

Return an InputPropertyError for invalid enum values

---

cmd/pulumi-test-language/interface.go
cmd/pulumi-test-language/interface_test.go
cmd/pulumi-test-language/internal_test.go
cmd/pulumi-test-language/l1_empty_test.go
cmd/pulumi-test-language/l1_main_test.go
cmd/pulumi-test-language/l2_continue_on_error_test.go
cmd/pulumi-test-language/l2_destroy_test.go
cmd/pulumi-test-language/l2_large_test.go
cmd/pulumi-test-language/l2_resource_asset_test.go
cmd/pulumi-test-language/l2_resource_simple_test.go
cmd/pulumi-test-language/program_overrides_test.go
cmd/pulumi-test-language/runtime_options_test.go
pkg/util/gsync/syncmap.go

In conformance tests we curently generate all the SDKs once, but we re-pack them for each test run.  This seems unnecessary, as the packed artifacts shouldn't change.  Only pack them once, to save time. Also `uv` seems to be non-deterministic when packing these artifacts, which seems to result in flakes in https://github.com/pulumi/pulumi/pull/19109.
Cache the artifacts instead, and re-use them for various tests.
Note that we currently simply overwrite artifacts in the same directory, so if the artifacts were any different, our tests would already be broken, since any test we're running would get a random artifact to use.
I expect this brings some performance improvements in all languages.  Let's see what CI says.
Fixes #16079

cache SDK artifacts in conformance tests

---

changelog/pending/20240925--sdk-go--add-property-path-and-associated-functions.yaml
changelog/pending/20241007--sdk-go--make-property-value-immutable.yaml
sdk/go/common/resource/property_compatibility.go
sdk/go/property/array.go
sdk/go/property/array_test.go
sdk/go/property/equal.go
sdk/go/property/map.go
sdk/go/property/map_test.go
sdk/go/property/path.go
sdk/go/property/path_test.go
sdk/go/property/type.go
sdk/go/property/values.go
sdk/go/property/values_test.go
sdk/go/property/visit.go

tldr: making all `property.Value`s immutable will make the API less idiomatic, but it will make API design and usage of `property.Value` clearer and less bug prone. We can do it without sacrificing too much performance.
This change is stacked on top of https://github.com/pulumi/pulumi/pull/17374.
There are two major concerns to address with this PR:
- The API is unidiomatic. ☝️ explains why I think the change is worth it from that perspective.
- The change is not performant.
Regardless of this PR, all APIs that manipulate `property.Value` *must* be of the shape:
```go
func alterValue(startingValue property.Value) (mutatedValue property.Value, _ error)
```
This is because you cannot reliably mutate `startingValue`. You can only mutate `startingValue` if it is a map or an array.[^1] APIs of …

Make `property.Value` immutable

---

pkg/backend/diy/backend.go
pkg/backend/httpstate/backend.go

This might be the result of a botched rebase or the like, but we're currently picking the wrong refresh method (and consequently iteration source) when passing `--run-program`, which causes a crash if the source gets touched (since the default is an error source). This change fixes that so that `--run-program` works in all cases for `refresh`.

Pick the right `refresh` when running programs

---

changelog/pending/20250407--sdk-python--properties-used-in-component-outputs-are-never-plain.yaml
sdk/python/lib/pulumi/provider/experimental/analyzer.py
sdk/python/lib/pulumi/provider/experimental/component.py
sdk/python/lib/test/provider/experimental/test_analyzer.py
sdk/python/lib/test/provider/experimental/testdata/docstrings/component.py
tests/integration/component_provider/python/component-provider-host/provider/component.py
tests/integration/integration_python_test.go

The plain attribute is only relevant for inputs. When generating the
schema for a component, we need to track wether we are currently looking
at a type used as an input or an output of the component. The properties
of types used as component inputs, including nested types, as well as
list items and dictionary values, can potentially be plain, unless they
are within an input. The properties of types used as component outputs
can never be plain.
There is some churn in the tests because we were previously sharing
complex types for both inputs and outputs, but that's not possible due
to the restriction on the plain property.
Fixes https://github.com/pulumi/pulumi/issues/18694

Properties used in component outputs are never plain

---

.github/workflows/sign.yml

The current version of `baptiste0928/cargo-install` we're using to install `b3sum` is failing for all merge attempts in the merge queue:
```
Attempt to load from cache ...
Error: Cache service responded with 422
at Object.<anonymous> (/home/runner/work/_actions/baptiste0928/cargo-install/bf6758885262d0e6f61089a9d8c8790d3ac3368f/dist/index.js:555:19)
at Generator.next (<anonymous>)
at fulfilled (/home/runner/work/_actions/baptiste0928/cargo-install/bf6758885262d0e6f61089a9d8c8790d3ac3368f/dist/index.js:482:58)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
https://github.com/baptiste0928/cargo-install mentions:
> **Versions prior to v3.2 will stop working on February 1st, 2025**, due to GitHub changing their cache service APIs. See the [@actions/cache …

ci: Use the latest version of baptiste0928/cargo-install

---

pkg/backend/apply.go
pkg/backend/display/progress.go
pkg/backend/display/progress_test.go
pkg/backend/diy/backend.go
pkg/backend/httpstate/backend.go

Follows https://github.com/pulumi/pulumi/pull/17956
Behaviour changes:
- We now show copilot summary if an error happens during a preview-of-an-update, as well as the update itself.
- If Copilot is disabled in the org we skip the code path (instead of showing message: "Copilot not enabled")
Code changes:
- Moves the Copilot summary code into `apply`, this allows it to respond to errors found in the preview-of-update.
- Reworks logic to capture events first, then go and render them, feels a bit cleaner, though memory implications etc?

Support Copilot summarizing errors discovered in the preview phase of an update

---

sdk/go/auto/cmd_test.go

This test continues to be flaky, however I’ve been unable to reproduce this locally. Presumably it flakes under heavy load/resource contention.
When I looked into this previously, I concluded (possibly wrongly) that we get `signal: interrupt` when we cancel the context before the operation has started. If we cancel after the operation has started we get the expected exit status.
The previous attempt in https://github.com/pulumi/pulumi/pull/18178/files to unflake this test used a sentinel file that we look for so that we know we’ve started the operation. This waited for up to 10 seconds for this file. This PR increases this to a full minute.
We can the flake rate and most recent occurence  here https://app.codecov.io/gh/pulumi/pulumi/tests/master?term=TestRunCanceled
We should hold off on …

Wait longer for sentinel file in TestRunCanceled

---

changelog/pending/20250408--cli-new--avoid-creating-a-main-py-file-when-chosing-the-uv-toolchain.yaml
sdk/python/toolchain/uv.go
sdk/python/toolchain/uv_test.go
tests/integration/integration_python_acceptance_test.go

We run `uv init` to create the `pyproject.toml` file when using the uv as the toolchain. Before version 0.6 this would always create a `hello.py` file, which we then delete. With version 0.6 this changed to `main.py`, but this also introduced a new `--bare` option to avoid creating such a file altogether.
Fixes https://github.com/pulumi/pulumi/issues/19153

Avoid creating a main.py file when chosing the uv toolchain

---

sdk/nodejs/queryable/index.ts

Add a comment so it's more obvious that `@pulumi/policy` has a dependency on `@pulumi/pulumi/queryable`.
Follow-up from https://github.com/pulumi/pulumi/pull/19172#discussion_r2035540821

[sdk/nodejs] Add comment about dependency

---

pkg/backend/httpstate/client/client.go
sdk/go/common/apitype/core.go

Extend Pulumi Cloud stack model with optional environment and secrets provider fields to allow stack configs to be persisted without a file on disk - only referencing a single ESC environment.
There is no configuration map included as stacks managed through the cloud will source all configuration keys from the ESC environment to leverage the existing ESC editing experience.
The fields added to the Stack in Pulumi Cloud are the minimum required to produce a stack config file equivilent to the following, though it's never actually written to disk:
```yaml
secretsProvider: {stack.SecretsProvider}
encryptionKey: {stack.EncryptionKey}
encryptionSalt: {stack.EncryptionSalt}
environment:
- {stack.Environment}
```
This also introduces a new API route, reflected in the client (`UpdateStackConfig`) …

API types & endpoint for managing cloud stack config

---

pkg/cmd/pulumi/packagecmd/package_add.go
tests/integration/integration_nodejs_test.go
tests/integration/packageadd-namespace/provider/schema.json

In https://github.com/pulumi/pulumi/pull/19157 we introduced saving details of the package added with `pulumi package add` into the Pulumi.yaml packages section.  For doing that we get the version from the installed package, which in turn gets it from the schema.
However the version is an optional field in the schema.  We set it automatically when using Git based plugins, but e.g. local plugins don't necessarily return a version at all.  This means `pkg.Version` can be `nil` and thus the CLI panics.  Add a check for that, and keep the version from what's passed in in the command line args if available.
No changelog necessary here since this wasn't released yet, so the bug was never customer facing.
Fixes https://github.com/pulumi/pulumi-yaml/issues/778

fix package_add panic when there's no version in the schema

---

sdk/go/auto/stack_test.go

Multiple tests are using this test project for their testing, and drop temporary config files there in some cases.  This leads to flaky tests, such as in https://github.com/pulumi/pulumi/issues/19194.
Fix that by copying the test project to a temporary directory for each of the tests, which makes sure they do not interfere with eachother.
Fixes https://github.com/pulumi/pulumi/issues/19194

stack_test: make each test copy testproj to its own temp dir

---

pkg/codegen/go/doc_test.go

`pkgs.Language` map must not be shared between parallel tests.

fix race in TestGetDocLinkForPulumiType test

---

changelog/pending/20250410--sdk-nodejs--target-es2020-instead-of-es2016.yaml
sdk/nodejs/tests/runtime/testdata/closure-tests/cases/116-Do-not-capture-2/snapshot.txt
sdk/nodejs/tsconfig.json

This change bumps TypeScript's target ECMAScript version from ES2016 to ES2020, which:
-  Reduces the amount of downlevel support code that TypeScript emits in the .js files we ship as part of the `@pulumi/pulumi` npm package
- Allows native JavaScript language features (such as async/await) to be used directly by Node/V8 rather than those features being emulated using older language features
We've indicated in our `package.json` that Node 18+ is required ([over a year ago](https://github.com/pulumi/pulumi/pull/15816)). Node 18 [supports ES2022](https://node.green/#ES2022). However, we're still building the SDK with TypeScript 3.8, which [supports targeting ES2020](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#es2020-for-target-and-module). So it should be …

[sdk/nodejs] Target ES2020

---

changelog/pending/20250410--engine--fix-replaceonchanges-being-respected-during-deletebeforereplace-checks.yaml
pkg/backend/display/json.go
pkg/engine/lifecycletest/delete_before_replace_test.go
pkg/resource/deploy/import.go
pkg/resource/deploy/source_eval_test.go
pkg/resource/deploy/step.go
pkg/resource/deploy/step_generator.go
pkg/resource/stack/checkpoint.go
pkg/resource/stack/deployment.go
pkg/resource/stack/deployment_test.go
sdk/go/common/apitype/core.go
sdk/go/common/resource/resource_state.go

Fixes #19056
This fixes two bugs with DBR logic. Firstly that ReplaceOnChanges would never trigger a replace as part of DBR even if the field was being changed, secondly that IgnoreChanges wouldn't prevent a replace if a field changed (but shouldn't have because of ignore changes).
Doing this requires that ReplaceOnChanges is saved to state with IgnoreChanges so that we have access to it at the point DBR is checking dependencies from state to see if they need replacing.

Fix ReplaceOnChanges and IgnoreChanges being respected during DBR diffs

---

sdk/go/property/values.go

I think these comments were from when Value was still a mutable type. There is no WithValue function for Values anymore.

Remove outdated comments about property.Values

---

changelog/pending/20250414--sdk-python--support-optional-types-using-3-10-union-syntax.yaml
sdk/python/lib/pulumi/provider/experimental/analyzer.py
sdk/python/lib/test/provider/experimental/test_analyzer.py
sdk/python/lib/test/provider/experimental/testdata/analyzer-errors/union-type-3-10-syntax/component.py

Starting with Python 3.10, unions can be written using `|`. This also means that optional types can be typed as `some_type | None` in addition to `Optional[some_type]`.
Fixes https://github.com/pulumi/home/issues/4049

Support optional types using union syntax

---

sdk/python/lib/test/provider/experimental/testdata/complex-args/PulumiPlugin.yaml
sdk/python/lib/test/provider/experimental/testdata/missing-input/PulumiPlugin.yaml

I think these were leftover from a rebase when the python analyzer was changed to take a list of components.

Remove unused testfiles

---

changelog/pending/20250415--auto-go-nodejs-python--add-run-program-to-automation-api-for-destroy-and-refresh.yaml
sdk/go/auto/optdestroy/optdestroy.go
sdk/go/auto/optrefresh/optrefresh.go
sdk/go/auto/stack.go
sdk/nodejs/automation/stack.ts
sdk/python/lib/pulumi/automation/_stack.py

Adds --run-program support to nodejs, python, and go.
I've added this explicitly (that is we explicitly pass `=true` or `=false`) so that if we change the default behaviour of the flag in the future anyone who explicitly set `false` will continue to get the same behaviour they expect.  As opposed to passing `--run-program` for true and nothing for false, where if we then changed the default behaviour anyone who had explicitly set false would suddenly be having their program run.

Add run-program to automation api

---

changelog/pending/20250417--programgen--fix-generation-of-importid-when-building-programs-from-state.yaml
pkg/importer/hcl2.go
pkg/importer/hcl2_test.go
pkg/importer/testdata/cases.json

Fixes https://github.com/pulumi/pulumi/issues/19235
`import` and `ignoreChanges` are both options of strings, but the old code for `makeResourceOptions` recorded these as `LiteralValueExpressions`. A quoted string has to be wrapped in a `TemplateExpression` first so that it writes out correctly as a quoted string.

Test and fix importID in GenerateHCL2Definition

---

pkg/go.mod
pkg/go.sum

We had this replace, because xanzy/ssh-agent was not lazy-loading DLLs, and had sporadic failures since then.  We have however since then upstreamed these changes in https://github.com/xanzy/ssh-agent/pull/10, which has been released in xanzy/ssh-agent v0.3.2.  We're pulling in v0.3.3 here, so we can just go back to rely on upstream, cleaning up an unnecessary replace.

remove no-longer-necessary replace

---

changelog/pending/20250417--components-nodejs--fix-component-construct-when-the-theres-a-namespace-in-the-name-field-in-package-json.yaml
sdk/nodejs/provider/experimental/provider.ts
tests/integration/integration_nodejs_test.go
tests/integration/namespaced_component/example/Pulumi.yaml
tests/integration/namespaced_component/index.ts

In https://github.com/pulumi/pulumi/pull/19066, we fixed component schema generation to work correctly when the `name` field in the `package.json` file includes the namespace.  However we missed that we also need to fix up construct, so we can correctly construct a component.  Fix that now.
Fixes https://github.com/pulumi/pulumi/issues/19055

fix component construct when package.json includes namespace

---

changelog/pending/20250411--sdk-python--add-bootstrap-less-mode-for-python-component-providers.yaml
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_install_python_test.go
sdk/python/cmd/pulumi-language-python/main.go
sdk/python/lib/pulumi/provider/experimental/host.py
sdk/python/lib/pulumi/run/plugin/__main__.py
sdk/python/toolchain/poetry.go
sdk/python/toolchain/pyproject.go
sdk/python/toolchain/pyproject_test.go
tests/integration/component_provider/python/bootstrap-less/provider/.gitignore
tests/integration/component_provider/python/bootstrap-less/provider/PulumiPlugin.yaml
tests/integration/component_provider/python/bootstrap-less/provider/pyproject.toml
tests/integration/component_provider/python/bootstrap-less/provider/src/provider/__init__.py
tests/integration/component_provider/python/bootstrap-less/provider/src/provider/component.py
tests/integration/component_provider/python/bootstrap-less/yaml/Pulumi.yaml
tests/integration/component_provider/python/package/provider/.gitignore
tests/integration/component_provider/python/package/provider/PulumiPlugin.yaml
tests/integration/component_provider/python/package/provider/pyproject.toml
tests/integration/component_provider/python/package/provider/src/provider/__init__.py
tests/integration/component_provider/python/package/provider/src/provider/__main__.py
tests/integration/component_provider/python/package/provider/src/provider/component.py
tests/integration/component_provider/python/package/yaml/Pulumi.yaml
tests/integration/integration_python_test.go

We now support two ways of running Python based plugins: bare
directories (the existing implementation) and now additionally as
buildable packages.
If the plugin directory is a bare directory (that is not a Python
package) with a `__main__.py`, we run the plugin's `__main__.py`
directly. Dependencies for these plugins are specified via
`requirements.txt`.
Otherwise, we check if the plugin directory is a buildable Python
package. In that case we run the plugin via `pulumu.run.plugin`.
Dependencies are installed from the `dependencies` section of the
`pyproject.toml`.
This enables bootstrap-less mode, where when running in package
mode, and the package exports ComponentResources, we
automatically host a provider for them.
Fixes https://github.com/pulumi/home/issues/4044
Fixes …

Add bootstrap-less mode for Python component providers

---

pkg/resource/deploy/import.go
pkg/resource/deploy/step.go
pkg/resource/deploy/step_generator.go
pkg/resource/deploy/step_test.go

Just trying to be a bit more consistent that import strings aren't IDs really. This uses the actual ImportID field for them instead, and sets ID once the import step has run.

Use ImportID not ID for import strings

---

tests/integration/component_provider/nodejs/component-provider-host/python/Pulumi.yaml
tests/integration/component_provider/nodejs/component-provider-host/yaml/Pulumi.yaml
tests/integration/integration_nodejs_test.go

Similar to https://github.com/pulumi/pulumi/pull/19210, use the `packages` section in `Pulumi.yaml` to hook up the local component provider.

Tidy up Node.js component provider tests

---

changelog/pending/20250418--cli-install--handle-local-plugin-paths-with-a-version-number.yaml
pkg/cmd/pulumi/install/install.go
tests/integration/integration_nodejs_test.go
tests/integration/packages-install-local/example/.gitignore
tests/integration/packages-install-local/example/Pulumi.yaml
tests/integration/packages-install-local/example/index.ts
tests/integration/packages-install-local/example/package.json
tests/integration/packages-install-local/example/tsconfig.json
tests/integration/packages-install-local/provider/PulumiPlugin.yaml
tests/integration/packages-install-local/provider/index.ts
tests/integration/packages-install-local/provider/package.json

In https://github.com/pulumi/pulumi/pull/18940 we extended `pulumi install` to generate the SDKs for packages referenced in `Pulumi.yaml`, however depending on how the provider is referenced in `Pulumi.yaml`, this does not work for local providers.
When a provider is added via `pulumi package add /some/path`, we create an entry in `Pulumi.yaml` with the version:
```
packages:
greeter: /some/path@0.0.0
```
This causes `pulumi install` to fail, as it does not properly detect the path due to the version number.
Fixes https://github.com/pulumi/pulumi/issues/19253

Handle local plugin paths with a version number

---

sdk/go/common/resource/property_compatibility.go
sdk/go/common/resource/property_compatibility_test.go

Stacked on top of #19256.
This PR changes the `resource.PropertyValue` representation of a computed `property.Value` so that it correctly roundtrips through gRPC.
Before this PR, `resource.ToResourcePropertyValue(property.New(property.Computed))` returns a `resource.PropertyValue{V: resource.Computed{}}`, which is semantically correct: a computed value with no additional information known. Unfortunately, this does not round trip through `plugin.(Un)Marshal` functions. Marshalling and unmarshaling turns `resource.PropertyValue{V: resource.Computed{}}` into `resource.PropertyValue{V: nil}`, which is not semantically equivalent. 
This PR solves the problem by changing the how `resource.ToResourcePropertyValue` translates computed values. …

Round trip computed property.Value's through gRPC

---

changelog/pending/20250418--sdk-nodejs-python--dont-install-python-nodejs-runtimes-during-make-build.yaml
sdk/nodejs/Makefile
sdk/python/Makefile

Similar to https://github.com/pulumi/pulumi/pull/19048 we should not install the binaries during `make build`.
This helps when using `mise`.  Previously `make build` would also install `pulumi-language-python` into `$GOBIN`, however not the `pulumi-language-python-exec` shim, causing problems when the shim is not found in the same directory as the runtime.

Don’t install python/nodejs runtimes during `make build`

---

pkg/codegen/docs.go
pkg/codegen/dotnet/doc.go
pkg/codegen/go/doc.go
pkg/codegen/nodejs/doc.go
pkg/codegen/python/doc.go

This function is never called in Pulumi code:
https://github.com/search?q=org%3Apulumi%20GetModuleDocLink&type=code.

Remove unused `GetModuleDocLink` from `DocLanguageHelper`

---

sdk/go/property/fmt.go
sdk/go/property/fmt_test.go

Stacked on #19258.
This PR implements `fmt.GoStringer` for `property` types. This enables programmers to paste the value from `fmt.Printf("Properties: %#v", myPropertyMap)` into a unit test and have it compile. This is a quality of life feature for Go programmers using the library. It should not effect the runtime behavior of `property`.

Implement `fmt.GoStringer` for `property.{Value,Map,Array}`

---

changelog/pending/20250411--programgen--support-provider-resources-in-generatehcl2definition.yaml
pkg/importer/hcl2.go
pkg/importer/hcl2_test.go

Adds the ability to generate HCL during import, but after attempting to
write a smoke test I saw that we don't actually support importing
providers in the internal registry provider:
See pkg/resource/deploy/providers/registry.go:
```
func (r *Registry) Read(context.Context, plugin.ReadRequest) (plugin.ReadResponse, error) {
return plugin.ReadResponse{}, errors.New("provider resources may not be read")
}
```
Although now we can generate HCL2, importing a provider will not work
until this is implemented.
Related #19036

Support named providers in GenerateHCL2Definition

---

pkg/engine/journal.go

Imports are like creates and should not mark the state (if any) as done. This worked because it happened to pass `New()` rather than `Old()` which was probably a typo, but meant that this value was never matched on in the list filtering later.

Fix typo in journal code

---

.github/workflows/ci-lint.yml
Makefile
build/common.mk
pkg/codegen/schema/pulumi.json

Use biome to format `pulumi.json` and https://github.com/santhosh-tekuri/jsonschema to validate it.
I picked  `github.com/santhosh-tekuri/jsonschema` because we are already using this in `developer-docs/utils/jsonschema2md.go`.
I picked `biome` because that's the formatter we use for the Node.js SDK and it supports formatting JSON files.

Format & lint pulumi.json

---

sdk/nodejs/Makefile
sdk/python/Makefile

In https://github.com/pulumi/pulumi/pull/19250 we stopped setting `GOBIN` for the `dist` target in the makefiles for `sdk/{nodejs,python}`.  This is fine for the `go install` part, but are also using the same env variable to drop more scripts into this directory.  Having it not set breaks this target.  Fix that by re-adding setting the `GOBIN` variable for the target.

sdk/{nodejs,python}/Makefile: export GOBIN before using it

---

tests/integration/component_provider/nodejs/component-provider-host/provider/package.json

We rely on this dependency being the exact version for the test to run, otherwise we infer the latest version that matches ^4.18.0, which currently is 4.18.1, breaking the test.
Noticed in https://github.com/pulumi/pulumi/actions/runs/14621588029/job/41023355115

pin @pulumi/random in test

---

changelog/pending/20250422--sdk-nodejs--add-exclude-and-exclude-dependents-to-the-nodejs-automation-api.yaml
sdk/nodejs/automation/stack.ts

The [Pulumi GitHub Action](https://github.com/pulumi/actions) uses the NodeJS Automation API to run Pulumi commands. Therefore, in order to do https://github.com/pulumi/actions/issues/1362, we need to add the `--exclude` and `--exclude-dependents` flags to the automation API. This PR does that. I also added `--target-dependents` in one place where it was forgotten.

Add `--exclude` and `--exclude-dependents` to the NodeJS automation

---

changelog/pending/20250423--pkg--update-dependencies-in-the-json-schema.yaml
pkg/codegen/schema/loader.go
pkg/codegen/schema/pulumi.json
tests/integration/integration_nodejs_test.go

We added the dependencies field to the Pulumi schema in https://github.com/pulumi/pulumi/pull/19071, but after some refactoring we ended up with the wrong definition in `pulumi.json`. Update this to match the reality.

Update Dependencies in the JSON schema

---

changelog/pending/20250424--cli-package--detect-readme-in-subdir-for-package-publishing.yaml
pkg/cmd/pulumi/packagecmd/package_publish.go
pkg/cmd/pulumi/packagecmd/package_publish_test.go

When publishing a VCS based component - via `pulumi package publish` - it picked the README in the root of the repository instead of the one located in the subdirectory where the component is located.
For example, running `GITHUB_TOKEN="$(gh auth token)" pulumi package publish https://github.com/pulumi/pulumiup-2025-keynote-demo/components/container-app --source private` should use this readme: https://github.com/pulumi/pulumiup-2025-keynote-demo/blob/main/components/container-app/README.md
But it ends up picking this one: https://github.com/pulumi/pulumiup-2025-keynote-demo/blob/main/README.md
The missing piece was taking the packages `LocalName` into account as well.
Fixes https://github.com/pulumi/pulumi-service/issues/27663

fix: detect readme in subdir for package publishing

---

changelog/pending/20250423--auto-nodejs--add-the-ability-to-configure-a-remote-executor-image.yaml
sdk/nodejs/automation/localWorkspace.ts
sdk/nodejs/automation/remoteWorkspace.ts
sdk/nodejs/tests/automation/remoteWorkspace.spec.ts

This PR is the NodeJS part of the automation API work to add `RemoteExecutorImage` configuration to all the various languages.
* https://github.com/pulumi/pulumi/issues/15693
* https://github.com/pulumi/pulumi/pull/15697

Add `RemoteExecutorImage` configuration to the NodeJS Automation API

---

.github/workflows/ci-run-test.yml

This shouldn't be needed anymore (I think we introduced this temporarily, to debug selectively upload test results to codecov). Somehow this failed in https://github.com/pulumi/pulumi/actions/runs/14643049132/job/41090458864?pr=19305.
It really doesn't make sense to me that it failed (Windows behaves weirdly sometimes I guess), but at the same time we don't need this step, so let's get rid of it.

remove "Debug branch name" step

---

pkg/codegen/docs.go
pkg/codegen/dotnet/doc.go
pkg/codegen/go/doc.go
pkg/codegen/go/doc_test.go
pkg/codegen/nodejs/doc.go
pkg/codegen/python/doc.go

```patch
-	GetFunctionName(modName string, f *schema.Function) string
+	GetFunctionName(f *schema.Function) string
```
The special bookkeeping that `modName` requires is used only within Go's `DocLanguageHelper`, and `go_gen.DocLanguageHelper` should manage the bookkeeping as necessary here. This complexity does not need to be exposed to callers of the function.
If this change is approved, I'll update the `GetFunctionName` method in pulumi-dotnet and pulumi-yaml.

Simplify `DocLanguageHelper.GetFunctionName`

---

changelog/pending/20250424--sdk-go--improve-output-when-plugin-crashes.yaml
sdk/go/common/resource/plugin/plugin.go
tests/integration/integration_go_test.go

We added this message recently, but at least to my eyes it always looked a little off, and almost like the output code was in some way buggy itself.  Instead of trying to make this message very fancy, report it like any other error message.
Before:
After:

clean up error message on premature provider exits

---

changelog/pending/20250424--sdk-python--add-pulumi_type-decorator.yaml
sdk/python/lib/pulumi/__init__.py
sdk/python/lib/pulumi/type_token.py
sdk/python/lib/test/test_type_token.py

Add a `pulumi_type` decorator to annotate Pulumi types such as resources and enums with their type token. This also provides a `get_pulumi_type` helper to retrieve the token.
Once this is released, we can update codegen to use this decorator to annotate resources and enums. We will also update the codegen change introduced in https://github.com/pulumi/pulumi/pull/19221 to use the decorator instead.
Ref https://github.com/pulumi/pulumi/issues/19297 & https://github.com/pulumi/pulumi/issues/18484

Add pulumi.type_token decorator

---

changelog/pending/20250424--engine--fix-importid-being-lost-from-state-during-update-operations.yaml
pkg/engine/lifecycletest/import_test.go
pkg/resource/deploy/step_generator.go

`ImportID` was only set when doing an import which meant it was lost from state if you did a normal update on the resource. This then broke the re-import logic on a later `up`.
This fixes it to always save it to state, and updates the test to check that actual import IDs and IDs are kept track of ok.

Ensure we always save ImportID

---

pkg/engine/lifecycletest/analyzer_test.go
pkg/engine/lifecycletest/pulumi_test.go
pkg/engine/update.go
pkg/resource/deploy/source_eval.go
pkg/resource/deploy/source_eval_test.go
sdk/go/common/resource/plugin/analyzer_plugin.go
sdk/go/common/resource/plugin/analyzer_plugin_test.go
sdk/go/common/resource/plugin/config.go
sdk/go/common/resource/plugin/host.go
sdk/go/common/resource/plugin/langruntime.go
sdk/go/common/resource/plugin/langruntime_plugin.go
sdk/go/common/resource/plugin/testdata/analyzer/main.go

This updates the language and analyser plugin interfaces to take `property.Map` from the engine layer, rather than `map[string]string`. 
We still have to translate to string maps internally for backwards compatibility, but we can push that lower and lower till we can eventually get rid of it.
There's a lot of follow ups that could be done after this to spread the new `property.Value/Map` system further, but that's not a rush. We can translate between the two at each boundary point for now.

Use the new property.Value system for plugin config

---

pkg/backend/snapshot.go
pkg/backend/snapshot_test.go
pkg/engine/journal.go
pkg/engine/lifecycletest/destroy_test.go
pkg/engine/lifecycletest/target_test.go
pkg/resource/deploy/step.go
pkg/resource/deploy/step_generator.go

Rather than tracking deletes as a special case we can just treat them the same as things being "done" generally. This is really useful when we start allowing multiple operations per-resource (e.g. import then update) as the done semantics just work.
There were comments about "If this is a delete-replace operation, we don't want to mark the resource as deleted because we want to keep the new resource." but I can't recall the reasoning for those comments and removing them hasn't broken any tests. If anyone can come up with a test case that depended on these things share, but otherwise I think this is safe.
The only other change needed was when we make `SameSteps` the two state pointers have to be different objects. This requires a copy in `getDependencySteps`. I've also added an assert to …

Remove the 'deletes' field, just use 'dones'

---

Makefile
build/common.mk

Running `make format` inside an sdk folder breaks, because we pull in the format target from `common.mk`, which tries to fromat `pulumi.json`. This was added in https://github.com/pulumi/pulumi/pull/19281
The formatting for `pulumi.json` should only happen as part of the top level makefile.

Fix make format

---

changelog/pending/20250424--auto-python--add-exclude-and-exclude-dependents-to-the-automation-api.yaml
sdk/python/lib/pulumi/automation/_stack.py

I added these to NodeJS as part of another ticket, but I'll add them to the other SDKs for completeness' sake.
* https://github.com/pulumi/pulumi/pull/19270

Add `--exclude` and `--exclude-dependents` to the Python automation API

---

changelog/pending/20250425--engine--fix-error-message-when-trying-to-load-plugins-in-private-repositories-with-no-authentication.yaml
sdk/go/common/resource/plugin/host.go
sdk/go/common/resource/plugin/host_test.go
sdk/go/common/workspace/plugins.go

In IsLocalPluginPath, we check if a plugin is a remote plugin. To do that, we parse the PluginSpec first, and then check based on that.
However, when the plugin is in a private Git repo, we get an error here, because we fail to fetch the latest tag of the Git repo. Instead, return a special error for that, and look for it specifically here, so we can correctly determine that it's a local plugin, or remote, and thus give a good error message to the user down the line.
Fixes https://github.com/pulumi/pulumi/issues/19325

treat private plugins as Git Plugins still

---

.mise.toml

The lock file format has some extra information now. Require this version so `uv sync` doesn’t churn the file.

Require uv  0.6.16

---

pkg/engine/lifecycletest/continue_on_error_test.go
pkg/engine/lifecycletest/import_test.go

In preparation for the new import system this changes a few tests such that they are still valid today, but have extra checks that we want to assert on for the new system as well.
`TestContinueOnErrorImport` is changed to explicitly fail the read, rather than relying on the diff failure that is being removed in the new system.
`TestImportOption` adds some checks that the outputs we see in the program are what we expect to see.

Update some import tests

---

changelog/pending/20250425--auto-go--add-exclude-and-exclude-dependents-to-the-automation-api.yaml
sdk/go/auto/optdestroy/optdestroy.go
sdk/go/auto/optpreview/optpreview.go
sdk/go/auto/optrefresh/optrefresh.go
sdk/go/auto/optup/optup.go
sdk/go/auto/stack.go

The next in a series. This PR adds `--exclude` and `--exclude-dependents` options for the stack commands in the Go Automation API.
- #19270 
- #19310

Add `--exclude` and `--exclude-dependents` to the Go Automation API

---

cmd/pulumi-test-language/go.sum
pkg/codegen/docs_integ_test.go
sdk/nodejs/cmd/pulumi-language-nodejs/go.sum
sdk/python/cmd/pulumi-language-python/go.sum
tests/go.sum

This is in preparation for https://github.com/pulumi/pulumi/pull/19306, which changes the signature and implementation of `GetLanguageTypeString`, but should generally preserve the result.

Add tests for `(DocLanguageHelper).GetLanguageTypeString`

---

changelog/pending/20250425--cli--always-save-fully-qualified-stack-names-to-the-settings-file.yaml
pkg/cmd/pulumi/newcmd/new.go
pkg/cmd/pulumi/newcmd/new_acceptance_test.go
pkg/cmd/pulumi/newcmd/new_test.go
pkg/cmd/pulumi/stack/io.go
pkg/cmd/pulumi/stack/stack_rename.go
pkg/cmd/pulumi/stack/stack_select.go

Noticed in https://github.com/pulumi/pulumi/pull/19324/files/aa1c465e08639c1578cc43e62fa7ea86879a8634#r2059990017
We need to save fully qualified stack names to the settings to prevent the following issue. 
Imagine the default org is currently "foo" and we create and save a stack "bar". Historically this would save the abbreviated name to the settings so just "bar".
If we then change the default org to "qux" and run `up` it will load the name from settings and reconstruct "bar" into "qux/bar" instead of "foo/bar" which is the stack that had actually been selected!
This fixes that to just always save the fully qualified name to stack settings.

Always save fully qualified stack names to settings

---

pkg/backend/backend.go
pkg/backend/diy/backend.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/client/client.go
sdk/go/common/apitype/stacks.go

Follow-up to #19086
When creating a new stack, allow the option to enable storing the stack config remotely in the cloud.
The backend is not yet implemented, so integration tests will be added as part of #19166

Implement stack creation with cloud config

---

changelog/pending/20250428--cli-package--mark-package-publish-command-as-non-experimental.yaml
pkg/cmd/pulumi/packagecmd/package_publish.go

We've started using this command for publishing public packages to the registry, as well as started dogfooding it for the private registry. Marking it as non-experimental now to make it easier to discover.

Mark package publish command as non-experimental

---

sdk/go/common/apitype/core.go

Introduced in https://github.com/pulumi/pulumi/pull/19086, these are not yet in use but should capitalize the second word to match all other API types.

Fix casing of stack config JSON properties

---

changelog/pending/20250423--cli-package--introduce-pulumi-package-info-to-show-information-about-a-package.yaml
pkg/cmd/pulumi/packagecmd/package.go
pkg/cmd/pulumi/packagecmd/package_info.go
pkg/cmd/pulumi/packagecmd/package_info_test.go

Introduce a new `pulumi package info` command that allows the user to get details of a package without having to read through the whole schema.  It filters out some details, and intentionally simplifies some of it to make it more accessible.
Examples:
```
$ pulumi package info aws
Provider: aws (6.75.0)
Description: A Pulumi package for creating and managing Amazon Web Services (AWS) cloud resources.
Total resources: 1502
Total modules: 214
Use 'pulumi package info --module <module> aws' to list resources in a module
Use 'pulumi package info --module <module> --resource <resource> aws' for detailed resource info
```
```
$ pulumi package info aws --module s3
Module: aws:s3
Resources: 27
- AccessPoint: Provides a resource to manage an S3 Access Point.
- AccountPublicAccessBlock: Manages S3 …
```

introduce `pulumi package info`

---

changelog/pending/20250424--auto-python--add-the-ability-to-configure-a-remote-executor-image.yaml
sdk/python/lib/pulumi/automation/_local_workspace.py
sdk/python/lib/pulumi/automation/_remote_workspace.py
sdk/python/lib/test/automation/test_remote_workspace.py

The Python portion of https://github.com/pulumi/pulumi/issues/15693.
* https://github.com/pulumi/pulumi/pull/19286
* https://github.com/pulumi/pulumi/pull/15697
There unfortunately aren't tests for checking command output in Python, but a manual dump of the arguments looks good:
```
... --remote-executor-image=test --remote-executor-image-username=foo --remote-executor-image-password=bar ...
```

Add Remote Executor Image configuration to the Python automation API.

---

pkg/backend/httpstate/backend.go
pkg/backend/httpstate/stack.go
pkg/backend/httpstate/stack_test.go
pkg/backend/mock.go
pkg/backend/organizations.go
pkg/backend/organizations_test.go
pkg/cmd/pulumi/newcmd/new.go
pkg/cmd/pulumi/newcmd/new_acceptance_test.go
pkg/cmd/pulumi/newcmd/new_test.go
pkg/cmd/pulumi/newcmd/stack.go
pkg/cmd/pulumi/org/org.go
pkg/cmd/pulumi/org/org_search.go
pkg/cmd/pulumi/org/org_search_ai.go
pkg/cmd/pulumi/org/org_search_test.go
pkg/cmd/pulumi/packagecmd/package_publish.go
pkg/cmd/pulumi/packagecmd/package_publish_test.go
pkg/cmd/pulumi/policy/policy_publish.go
pkg/cmd/pulumi/policy/policy_publish_test.go
tests/integration/integration_test.go
tests/stack/stack_test.go

Essentially a copy of https://github.com/pulumi/pulumi/pull/19249 but with commits re-organized for readability. 
This work is part of Project Hockeystick (https://github.com/orgs/pulumi/projects/274)
This PR updates the call sites for workspace.GetBackendConfigDefaultOrg to a wrapper `backend.GetDefaultOrg` that includes a fallback lookup to the backend for default org. If the backend does not support the GetDefaultOrg API, or if it has no opinion, `backend.GetDefaultOrg` will preserve existing behavior by returning an empty string for call sites to evaluate appropriately.
It additionally introduces a new call site: cloudBackend.ListStacks` -- This upfront call will reduce the number of API calls made in `cloudBackendReference.String()` to check the workspace against the default …

Add default org lookup against the backend if not locally configured by user

---

changelog/pending/20250425--pkg--allow-for-hyphens-in-function-names.yaml
pkg/codegen/schema/pulumi.json
pkg/codegen/schema/schema_test.go

This pull request introduces a new schema definition for function types.
Currently, function tokens may not have any hyphens in their final part. For most existing functions, this is fine, since we habitually do not create functions that have hyphens in them.
However, for provider-level Methods, which are of the token format `pulumi:providers/packageName/functionName`, sometimes the provider has a hyphen. Famous example: `terraform-provider` - the base name for our provider parameterization.
Rather than widening the regex scope for all tokens, this pull request adds a new `functionToken` to the metaschema with an additional allowed `-` in the regex pattern.
Adds tests to confirm this is permissible for all function tokens, as well as the special provider methods.
Fixes …

Allow for hyphens in function names

---

pkg/backend/organizations.go
pkg/backend/organizations_test.go
pkg/backend/state/stacks.go
pkg/backend/state/stacks_test.go

Follow up from conversation in https://github.com/pulumi/pulumi/pull/19324#discussion_r2059688744
1. The CLI tracks the current selected stack for a given project in ~/.pulumi/workspaces/
1. There was a pre-existing bug where if a user updates their default org, their current stack as tracked in the above file would not necessarily get updated; potentially resulting in the wrong stack getting updated in the wrong org. This bug was fixed in https://github.com/pulumi/pulumi/pull/19336, so changes to the default org would not affect the selected stack moving forward.
The concern is around existing users who will be upgrading from a version previous to the bug patch directly to one with https://github.com/pulumi/pulumi/pull/19324 landed. It is the same bug vector as described above, but with …

Add legacy default org logic for back compat during version upgrade

---

changelog/pending/20250430--auto-nodejs--add-onerror-callback-for-capturing-incremental-stderr-output.yaml
sdk/nodejs/automation/cmd.ts
sdk/nodejs/automation/stack.ts
sdk/nodejs/tests/automation/localWorkspace.spec.ts

This PR replicates the `onOutput` callback for stderr in the NodeJS Automation API so that error information can be collected incrementally. I also included a test (that was surprisingly difficult to come up with).
This is a part of #6511.

Add `onError` callbacks to the NodeJS Automation API operations

---

pkg/codegen/docs.go
pkg/codegen/docs_integration_test.go
pkg/codegen/dotnet/doc.go
pkg/codegen/dotnet/doc_test.go
pkg/codegen/go/doc.go
pkg/codegen/go/gen.go
pkg/codegen/nodejs/doc.go
pkg/codegen/python/doc.go
pkg/codegen/python/gen.go
pkg/codegen/python/python_test.go

```patch
type DocLanguageHelper interface {
-	GetLanguageTypeString(pkg *schema.Package, moduleName string, t schema.Type, input bool) string
+ 	// GetTypeName gets the name of a type in the language of the DocLanguageHelper.
+	//
+	// relativeToModule should always be a module returned from pkg.TokenToModule. It
+	// should not be language specialized.
+	GetTypeName(pkg *schema.Package, t schema.Type, input bool, relativeToModule string) string
...
}
```
This change (similar to https://github.com/pulumi/pulumi/pull/19268) reduces the book-keeping necessary to use `DocLanguageHelper`. The name change brings the method more inline with other `DocLanguageHelper` methods like `GetPropertyName`, `GetEnumName` and `GetFunctionName`. 
More important is the change in what is expected from the …

Replace `GetLanguageTypeString` with `GetTypeName`

---

pkg/codegen/dotnet/doc.go
pkg/codegen/dotnet/doc_test.go

This field is never written to, and so is always `nil`. We should remove it in favor of
the actual namespace value associated with the package we are operating on.

Remove `dotnet.DocLanguageHelper.Namespaces`

---

changelog/pending/20250501--cli-plugin--allow-creating-analyzer-plugins-without-config.yaml
sdk/go/common/resource/plugin/analyzer_plugin.go
sdk/go/common/resource/plugin/analyzer_plugin_test.go
sdk/go/common/resource/plugin/testdata/analyzer-no-config/main.go
sdk/go/common/resource/plugin/testdata/analyzer-no-config/pulumi-analyzer-policy-test
sdk/go/common/resource/plugin/testdata/analyzer-no-config/pulumi-analyzer-policy-test.cmd
tests/integration/integration_test.go

We broke this in https://github.com/pulumi/pulumi/pull/19328 and fixed it in https://github.com/pulumi/pulumi/issues/19383. The fix has a unit test. Go one step further and add an integration test that ensures we can publish (and remove) a policy from the live backend.

Add an integration test for policy publishing

---

changelog/pending/20250423--sdk-python--support-resource-references.yaml
sdk/python/lib/pulumi/provider/experimental/analyzer.py
sdk/python/lib/pulumi/provider/experimental/component.py
sdk/python/lib/pulumi/provider/experimental/schema.py
sdk/python/lib/test/provider/experimental/test_analyzer.py
sdk/python/lib/test/provider/experimental/testdata/resource-ref/component.py
sdk/python/lib/test/provider/experimental/testdata/resource-ref/mock_package/__init__.py
sdk/python/lib/test/provider/experimental/testdata/resource-ref/mock_package/mock_module.py
sdk/python/lib/test/provider/experimental/testdata/resource-ref/mock_package/pulumi-plugin.json
sdk/python/lib/test/provider/experimental/testdata/resource-ref/mock_package_para/__init__.py
sdk/python/lib/test/provider/experimental/testdata/resource-ref/mock_package_para/mock_module.py
sdk/python/lib/test/provider/experimental/testdata/resource-ref/mock_package_para/pulumi-plugin.json
tests/integration/component_provider/python/resource-ref/provider/PulumiPlugin.yaml
tests/integration/component_provider/python/resource-ref/provider/__main__.py
tests/integration/component_provider/python/resource-ref/provider/component.py
tests/integration/component_provider/python/resource-ref/provider/requirements.txt
tests/integration/component_provider/python/resource-ref/yaml/Pulumi.yaml
tests/integration/integration_python_test.go

Similar to the Node.js implementation in https://github.com/pulumi/pulumi/pull/18885
When we encounter an input or output that is a subclass of `Resource`, we look up its type token. This is available under the `pulumi_type` properties for SDKs built with https://github.com/pulumi/pulumi/pull/19221. To retrieve the version, download URL and parameterization for a Pulumi package, we load the `pulumi-plugin.json` file. These packages are tracked as dependencies and returned in the schema so that codegen can generate the correct language specific dependencies.

Support Resource References

---

pkg/codegen/docs.go
pkg/codegen/docs_integration_test.go
pkg/codegen/dotnet/doc.go
pkg/codegen/dotnet/doc_test.go
pkg/codegen/go/doc.go
pkg/codegen/go/doc_test.go
pkg/codegen/nodejs/doc.go
pkg/codegen/python/doc.go

Change the interface of `DocLanguageHelper.GetTypeName` and `GetMethodResultName` to accept `schema.PackageReference` instead of `*schema.Package`. Lazily bound schemas are much more efficient when producing docs for a single page (as we intend to do for a live registry).
The original logic for `schema.PackageReference` can be found here: https://github.com/pulumi/pulumi/pull/9620.

`DocLanguageHelper`: `*schema.Package` -> `schema.PackageReference`

---

changelog/pending/20250430--sdk-go--loosening-github-com-hostname-requirement-to-support-github-enterprise.yaml
sdk/go/common/util/gitutil/git.go
sdk/go/common/util/gitutil/git_test.go

feat: loosening github.com hostname requirement to support GitHub Ent)erprise
This pull request introduces changes to loosen the strict `github.com` hostname requirement, enabling support for GitHub Enterprise. The updates include modifications to the SDK and documentation to reflect this change.
* [`changelog/pending/20250430--sdk-go--loosening-github-com-hostname-requirement-to-support-github-enterprise.yaml`](diffhunk://#diff-4d6ebc748f8b968493b2e8bf8ae16fe7943d7f6402942897f94a6a145a28dbcdR1-R4): Added a changelog entry describing the new feature that loosens the `github.com` hostname requirement to support GitHub Enterprise.
* [`sdk/go/common/util/gitutil/git.go`](diffhunk://#diff-32b4aaf1466287dbb878a57a8a1368d8f7741468444e8ff92c4a41b7e9aab370L57-R58): Updated the `GitHubHostName` …

feat: loosening github.com hostname requirement to support GitHub Ent

---

changelog/pending/20250506--cli-display--fix-race-condition-when-rendering-progress-events.yaml
pkg/backend/display/progress.go

When we are installing plugins as part of a Pulumi operation (e.g. `pulumi up`), we'll render a series of progress bars to show the user what is going on. Under the hood, the CLI manages this by responding to progress events, tracking them in a map and rendering them as system messages. Concurrent access to this map is guarded by a mutex.
Recently, #17594 was re-opened due to users experiencing hangs/locking behaviour when installing plugins as part of an update. While we don't have a solid reproduction, we do have some data from occurrences which suggests that the system is idle, and thus most likely deadlocked. If so, given that we did not see these issues prior to the introduction of progress events, we can reason that the mutex guarding the progress events map is the cause of this …

Fix race condition when rendering progress events

---

changelog/pending/20250506--cli-package--make-sure-namespaces-from-git-plugins-are-always-lowercase.yaml
pkg/cmd/pulumi/packagecmd/project_sdk_link.go
tests/integration/integration_test.go

Namespaces are only allowed to be lowercase.  For git repos we take them from the URL, which is allowed to have uppercase characters and is usually not case sensitive.  Automatically lowercase the namespace, so this always works and doesn't confuse users that use components from Git repos that don't have an explicit namespace set.
E.g. someone might use `pulumi package add github.com/Pulumi/xyz-component`, which should just use the lowercase `pulumi` (as that's what the URL is pointing to because of case insensitivity), instead of `Pulumi`.

make namespaces we get from git repos always lowercase

---

changelog/pending/20250506--sdk--support-node-js-24.yaml
scripts/get-job-matrix.py
sdk/nodejs/cmd/pulumi-language-nodejs/language_test.go
sdk/nodejs/tests/runtime/closure-integration-tests.ts

Node.js 18 is no longer supported. We don’t have any changes that break compatibility with this version, but we are no longer running tests for it.

Support Node.js 24

---

pkg/codegen/go/gen_program_expressions.go
pkg/codegen/hcl2/model/type.go
pkg/codegen/hcl2/model/type_const.go
pkg/codegen/hcl2/model/type_enum.go
pkg/codegen/hcl2/model/type_list.go
pkg/codegen/hcl2/model/type_map.go
pkg/codegen/hcl2/model/type_none.go
pkg/codegen/hcl2/model/type_object.go
pkg/codegen/hcl2/model/type_opaque.go
pkg/codegen/hcl2/model/type_output.go
pkg/codegen/hcl2/model/type_promise.go
pkg/codegen/hcl2/model/type_set.go
pkg/codegen/hcl2/model/type_test.go
pkg/codegen/hcl2/model/type_tuple.go
pkg/codegen/hcl2/model/type_union.go
pkg/codegen/pcl/functions_test.go

Type conversions are mutually recursive and can exhibit bad runtime behaviour (probably O(2^n) if I'm guessing right) in some cases.  With large schemas this means we essentially never finish the conversion.
To fix this we can use dynamic programming techniques, and cache the intermediate results, which helps cut down the runtime for this significantly.  Locally this brings the resourcedocgen command from https://github.com/pulumi/pulumi-java/issues/1772, from never finishing (or at least not before my patience runs out after running it overnight) to completing in ~3 minutes, after including this change in the Java language runtime.

cache intermediate results for type conversions

---

sdk/nodejs/provider/server.ts

I _think_ this should be an absolute no-op, as these types don't seem to escape these functions.
We actually have types for the things we expect these to be, and if we're wrong, everything will still fail in exactly the same way as before this PR. This change should just mean that the LSP is a bit more useful.

Add some NodeJS request types

---

pkg/codegen/pcl/call.go
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsc/projects/l2-component-call-simple/index.ts
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsc/projects/l2-provider-call-explicit/index.ts
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsc/projects/l2-provider-call/index.ts
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsnode/projects/l2-component-call-simple/index.ts
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsnode/projects/l2-provider-call-explicit/index.ts
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsnode/projects/l2-provider-call/index.ts
sdk/python/cmd/pulumi-language-python/testdata/classes/projects/l2-component-call-simple/__main__.py
sdk/python/cmd/pulumi-language-python/testdata/classes/projects/l2-provider-call-explicit/__main__.py
sdk/python/cmd/pulumi-language-python/testdata/classes/projects/l2-provider-call/__main__.py
sdk/python/cmd/pulumi-language-python/testdata/setuppy/projects/l2-component-call-simple/__main__.py
sdk/python/cmd/pulumi-language-python/testdata/setuppy/projects/l2-provider-call-explicit/__main__.py
sdk/python/cmd/pulumi-language-python/testdata/setuppy/projects/l2-provider-call/__main__.py
sdk/python/cmd/pulumi-language-python/testdata/toml/projects/l2-component-call-simple/__main__.py
sdk/python/cmd/pulumi-language-python/testdata/toml/projects/l2-provider-call-explicit/__main__.py
sdk/python/cmd/pulumi-language-python/testdata/toml/projects/l2-provider-call/__main__.py

Method calls (represented by the `Call` gRPC call on the provider interface and the `call` intrinsic in PCL) always return outputs -- we don't support "plain" (e.g. `Promise` in NodeJS, `Task` in Python) calls as we do for invokes. When the `call` PCL intrinsic was introduced, we incorrectly gave it a plain type, which happened to work for the NodeJS and Python conformance tests we introduced due to those languages' support for automatic lifting of output properties. For instance, in NodeJS, the below is fine, even though `component1.identity()` returns an `Output`:
```typescript
export const from_identity = component1.identity().result;
```
Under the hood, "lifting" means that this is desugared to an `apply`:
```typescript
export const from_identity = component1.identity().apply(call => …
```

Fix the return type of the PCL `call` intrinsic

---

sdk/go/property/values.go
sdk/go/property/values_test.go

A `property.Value` can't depend on the same resource more then once, so it doesn't make sense to allow `property.Value` to represent duplicate resource dependencies.

Deduplicate dependencies for `property.Value`

---

changelog/pending/20250507--engine--fix-refresh-run-program-hanging-on-non-trivial-programs.yaml
pkg/engine/lifecycletest/refresh_test.go
pkg/resource/deploy/deployment_executor.go
pkg/resource/deploy/step_executor.go

Fixes https://github.com/pulumi/pulumi/issues/19406
We were hitting an issue where the step generator would return no steps after a refresh but we'd still pass these off to the step executor to execute. This then hit the logic in step workers to shutdown if they get a `nil` chain, so after N refreshes you'd have no step workers left.
This makes two changes.
Firstly we don't bother sending things to the step executor if there's no steps.
Secondly I've changed the worker exit check to look at the completion channel (which `ExecuteSerial` always sets) rather than the `Chain` (which is set by the API user) to prevent us hitting this footgun that `nil` doesn't behave the same as just an empty slice again.

Fix --run-program hanging on non-trivial programs

---

changelog/pending/20250506--programgen-nodejs--fix-generating-imports-for-functions-in-3-rd-party-packages-such-as-atpulumiverse-scaleway.yaml
pkg/codegen/nodejs/gen_program.go
pkg/codegen/nodejs/gen_program_expressions.go
pkg/codegen/nodejs/gen_program_test.go

Packages may override Node imports to be @pulumiverse/scaleway instead of @pulumi/scaleway. Before the change the code respected this for resources but not for invokes, and if invokes were used generated invalid Node programs. This is fixed by reusing the code that handled resources to cover invokes as well.
Fixes https://github.com/pulumi/pulumi/issues/19409

Respect customized Node package names in Node program generator

---

Makefile

V2 now infers the path prefix.

Remove `--path-prefix` from `golangci-lint`

---

.github/workflows/on-release-manual-dispatch.yml
.github/workflows/release-pr.yml
.github/workflows/release.yml

Two commits:
We changed `make tidy` to only check tidiness in #19421, and added a new `make tidy_fix` target to actually do the tidy. This fixes up the workflow to call the new `make tidy_fix` target.
This commit contains two changes:
1. Temporarily comment out jobs that have already successfully run in the `release.yml` workflow. See
https://github.com/pulumi/pulumi/actions/runs/14886609176/job/41807855803
2. Add a way to manually dispatch a release via `on-release-manual-dispatch.yml` workflow. The new file is a copy of `on-release.yml`, but setup to allow manual trigger with input variables, rather than being triggered by a release.
This change will be reverted after v3.168.0 is fully released.

Temporary changes to unblock v3.168.0 release

---

changelog/pending/20250507--cli--add-run-program-to-preview-for-use-with-refresh.yaml
pkg/cmd/pulumi/operations/preview.go
pkg/cmd/pulumi/operations/up.go
pkg/engine/lifecycletest/preview_test.go

This adds `--run-program` to `pulumi preview` and `pulumi up`. This only has an effect when `--refresh` is also used, but when set will use the new refresh system as part of step generation, rather than refreshing everything up-front based on state.
This has a _small_ difference that it _doesn't_ refresh resources that are being deleted. That should probably be deemed a bug, but might be we're ok shipping this as is first.

Add `--run-program` to `preview`/`up`

---

sdk/go/common/resource/plugin/provider.go
sdk/go/common/resource/plugin/provider_plugin.go
sdk/go/common/resource/plugin/provider_plugin_test.go
sdk/go/common/resource/plugin/provider_server.go

This change adopts the protobuf changes for views on `plugin.Provider`. This isn't functional yet. Just updating the interfaces.
Part of https://github.com/pulumi/pulumi/issues/19240

Views: Adopt on `plugin.Provider`

---

cmd/pulumi-test-language/tests/l2_invoke_scalar.go
cmd/pulumi-test-language/tests/l2_invoke_simple.go

Simple cleanup, just using RequireSingleResource instead of a loop like
other tests

Use require single resource in invoke conformance tests

---

sdk/python/lib/test/automation/test_config_file.py
sdk/python/lib/test/automation/test_utils.py

This failed (and was retried) in the merge queue when there were multiple PRs running at the same time.
Use a random stack name and a unique project name to avoid any issues.

Unflake test_config_file_option

---

sdk/go/common/workspace/plugins.go

In preparation for https://github.com/pulumi/home/issues/3990, this PR simplifies and disambiguates `workspace.NewPluginSpec` so it is easer to extend.
This is a refactor, and should not have user visible changes.

Simplify plugin spec definition

---

pkg/backend/display/progress.go
pkg/backend/display/progress_test.go
pkg/backend/httpstate/backend.go

Fixes https://github.com/pulumi/pulumi.ai/issues/1858
Two bugs here:
1. We were mis-identifying previews as updates. (and now correctly read `backend.UpdateOperation.isDryRun`), this is nice for completely accurate rendering of output. There are subtle differences between update and preview ("create" vs "created" and probably others).
2. We were using `isPreview` for some error condition checking (influenced by the above incorrect check). Additionally Auth errors are not ResourceOperationFailures so we weren't catching those in some cases at all. We simplify that logic to check both ResourceOperationFailed and then diagnostics too (auth errors) regardless of whether its a preview or update.
_Note: this affects the unreleased `--copilot` feature_

Fixes rendering `--copilot` error summary on auth errors

---

pkg/codegen/docs_integration_test.go
pkg/codegen/python/doc.go

This was detected when attempting to upgrade the registry to latest pu/pu. The zero value is fine here.

Python codegen shouldn't fail when we are missing `PackageInfo`

---

pkg/codegen/docs_integration_test.go
pkg/codegen/python/doc.go

In #19035 we started out writing the fully qualified types for python in codegen, e.g. `builtins.str` instead of just `str`.
However this is not desired for docs, as it might confuse people. Don't add the builtins prefix for docs generation.
This was partly fixed in https://github.com/pulumi/pulumi/pull/19359, but I missed a spot. Fix that now.
Fixes https://github.com/pulumi/pulumi/issues/19272

codegen/python: don't use builtins.* prefix for docs (part 2)

---

changelog/pending/20250509--engine--the-engine-now-defers-policy-pack-installation-to-the-language-hosts.yaml
pkg/backend/httpstate/policypack.go
pkg/engine/lifecycletest/analyzer_test.go
pkg/engine/update.go

This updates the engine to use the InstallDependencies method on language hosts to install policy pack dependencies.
Tested on the policy repo at https://github.com/pulumi/pulumi-policy/pull/377

Use language host to install policy pack dependencies

---

pkg/backend/display/ai.go
pkg/backend/display/ai_test.go

Part of https://github.com/pulumi/pulumi.ai/issues/1858
Decouple `SUPPRESS_COPILOT_LINK` and `--copilot`
Previous behavior: 
- `up --copilot` is the only command that showed the link after the copilot error summary.
- `up` was the only command that originally had the _old_ link and actually set `ShowCopilotLink = !SUPPRESS_COPILOT_LINK` in `up.go`
- `preview --copilot`, `refresh --copilot`, `destroy --copilot` did not show the link after the copilot error summary as we were respecting this older flag in the newer code.
New behaviour:
- `--copilot` shows the link after the copilot error summary on all 4 commands.
Notes:
- SUPPRESS_COPILOT_LINK is part of an older feature that is only honored by `pulumi up`.
- As `--copilot` is available on up, preview, destroy, refresh this make …

Fixes link in `--copilot` error summary appearing.

---

docs/architecture/testing/integration.md
sdk/go/common/lazy/lazy.go
sdk/go/common/testing/environment.go
tests/integration/main_test.go
tests/stack/main_test.go
tests/stack/stack_test.go
tests/testutil/test_main_util.go

Stop resolving the pulumi binary from the `$PATH` for integration tests because this has unexpected failures modes where other installations might be used accidentally if the local project hasn't been built correctly.
Follow-on to #19461
- If `PULUMI_INTEGRATION_BINARY_PATH`, then require that to be used for `pulumi ...` commands
- Use the existing TestMain functions in integration tests to set `PULUMI_INTEGRATION_BINARY_PATH`
- Fail the test if the pulumi binary does not exist in `$REPO/bin` - do not fall back to using the $PATH.
- An alternative binary can be explicitly set by the user by specifying the environment variable `PULUMI_INTEGRATION_BINARY_PATH`.
- Remove the unused UseLocalPulumiBuild option.

Integration test explicit pulumi binary

---

.goreleaser.yml

I noticed in CI that goreleaser was complaining about a few deprecated options we are using.  Let's move to the non-deprecated options, to clean up the warnings and future proof our config.
- https://goreleaser.com/deprecations/#snapshotname_template
- https://goreleaser.com/deprecations/#buildsgobinary
- https://goreleaser.com/deprecations/#archivesformat_overridesformat

rename deprecated goreleaser options

---

changelog/pending/20250509--sdk-nodejs--pass-ignorechanges-replaceonchanges-customtimeouts-retainondelete-and-deletedwith-to-the-provider-constructor.yaml
sdk/python/lib/pulumi/provider/server.py

This PR passes more resource options to the provider constructor. This is the equivalent code for the NodeJS and Go.
* https://github.com/pulumi/pulumi/pull/19494
* https://github.com/pulumi/pulumi/pull/12701

[Python] Propagate more ComponentResourceOptions to provider constructors

---

pkg/codegen/docs_integration_test.go
pkg/codegen/nodejs/gen_program.go
pkg/codegen/schema/package_reference.go

This PR brings nodejs's `moduleName` inline with the rest of nodejs's codegen and codegen at large. Language specific blocks are managed by specifying an importer at bind time, not by codegen injecting their own language importer.
This allows us to test docs generation in parallel.
Follow-up on https://github.com/pulumi/pulumi/pull/19488.

[codegen/nodejs] Do not import during docs generation

---

changelog/pending/20250513--sdk--add-cliversionresponsewithcache-apitype.yaml
sdk/go/common/apitype/cli.go

The upcoming work in pulumi-service to use OpenAPI codegen requires all returns to be defined in `apitype`. While this new field is transitional as we roll out changes to the version checking endpoint, we still need to add it to the struct to not block the OpenAPI work.
Ref https://github.com/pulumi/pulumi-service/pull/27857

Add optional cache duration to CLIVersionResponse apitype

---

changelog/pending/20250513--sdk-go--accept-context-context-wherever-new-plugin-context-s-are-created.yaml
cmd/pulumi-test-language/interface.go
pkg/cmd/pulumi/operations/import.go
pkg/cmd/pulumi/packagecmd/package_add.go
pkg/cmd/pulumi/packagecmd/package_extract_mapping.go
pkg/cmd/pulumi/packagecmd/package_extract_schema.go
pkg/cmd/pulumi/packagecmd/package_gen_sdk.go
pkg/cmd/pulumi/packagecmd/package_info.go
pkg/cmd/pulumi/packagecmd/package_publish.go
pkg/cmd/pulumi/packagecmd/project_sdk_link.go
pkg/cmd/pulumi/policy/policy_publish.go
pkg/codegen/pcl/binder.go
pkg/codegen/schema/bind.go
pkg/codegen/schema/loader_test.go
pkg/codegen/schema/schema_test.go
pkg/engine/deployment.go
pkg/resource/deploy/source_eval_test.go
pkg/resource/deploy/step_test.go
sdk/go/common/resource/plugin/analyzer_plugin_test.go
sdk/go/common/resource/plugin/context.go
sdk/go/common/resource/plugin/context_test.go
sdk/go/common/resource/plugin/host_test.go
sdk/go/common/resource/plugin/langruntime_test.go
sdk/go/common/resource/plugin/plugin_test.go
sdk/go/common/resource/plugin/provider_plugin_test.go
tests/integration/run_plugin/go/main.go

This commit alters the signature of `plugin.NewContext` and `plugin.NewContextWithRoot` to accept a `context.Context`, instead of grabbing a new one from `context.Background`. It removes `plugin.NewContextWithContext`, since it is now redundant.
[GitHub Search](https://github.com/search?q=plugin.NewContextWithContext+-is%3Afork&type=code) shows that `plugin.NewContextWithContext` is only used in `pulumi/pulumi`.
[GitHub Search](https://github.com/search?q=plugin.NewContextWithRoot+-is%3Afork&type=code) shows that `plugin.NewContextWithRoot` is used in `pulumi/pulumi` and once in `pulumi/pulumi-yaml`.
[GitHub Search](https://github.com/search?q=org%3Apulumi+plugin.NewContext&type=code) shows that `plugin.NewContext` is used in `pulumi/pulumi`, once in `pulumi/pulumi-terraform-bridge`, once …

`plugin.NewContext(WithRoot)?` accept `context.Context`

---

changelog/pending/20250513--sdk-go--accept-context-context-in-workspace-getplugininfo-and-workspace-getpluginpath.yaml
pkg/cmd/pulumi/plugin/plugin.go
pkg/cmd/pulumi/plugin/plugin_run.go
pkg/engine/plugins.go
sdk/go/common/resource/plugin/analyzer_plugin.go
sdk/go/common/resource/plugin/converter_plugin.go
sdk/go/common/resource/plugin/host.go
sdk/go/common/resource/plugin/langruntime_plugin.go
sdk/go/common/resource/plugin/provider_plugin.go
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_test.go

This commit changes `workspace.GetPluginPath` and `workspace.GetPluginInfo` to accept `context.Context` as their first argument.
[GitHub Search](https://github.com/search?q=workspace.GetPluginPath+-is%3Afork+language%3Ago&type=code&p=1) shows that `workspace.GetPluginPath` is only used in `pulumi/pulumi` and once in `pulumi/pulumi-terraform-bridge`.
[GitHub Search](https://github.com/search?q=workspace.GetPluginInfo+-is%3Afork+language%3Ago&type=code) shows that `workspace.GetPluginInfo` is only used in `pulumi/pulumi`.

`workspace.GetPlugin{Path,Info}` accepts `context.Context`

---

pkg/backend/backenderr/backenderr.go
pkg/backend/httpstate/client/client.go
pkg/backend/httpstate/client/client_test.go
pkg/backend/httpstate/package_registry.go
pkg/backend/mock.go
pkg/backend/package_registry.go
sdk/go/common/apitype/package.go

This PR exposes the registry's get and list APIs for resource plugins.
This is motivated by https://github.com/pulumi/home/issues/3990.
`apitype.PackageMetadata` and `apitype.ListPackageResponse` are copied from the service.

Registry search methods in `backend`

---

CONTRIBUTING.md

I always wonder which category it is and have to a look at previous releases. I think we occasionally post them into "Announcements", but I think mostly we use "Releases".

Specify discussion category for release

---

changelog/pending/20250512--cli--update-package-add-help-to-mention-pulumi-yaml.yaml
docs/architecture/providers/parameterized.md
pkg/cmd/pulumi/packagecmd/package_add.go

Update the docs for `pulumi package add` to indicate that the package is also added to `Pulumi.yaml`.

Update `package add` docs

---

changelog/pending/20250509--programgen--copy-assets-emitted-from-converter-plugins-to-target-directory-of-the-generated-projects.yaml
pkg/cmd/pulumi/convert/convert.go
pkg/util/afero/afero.go
pkg/util/afero/afero_test.go

When `pulumi convert` talks to converter plugins, it tells them where they should emit PCL files from which we bind a program and convert it. If the converters happen to emit non-PCL files such as assets of the program, we just ignore them. This PR addresses the issue by copying non-PCL files from the source program directory (where PCL files were emitted) into the target generated project directory so that the assets stay part of the project. 
This was implemented for conformance tests (specifically for the `l2-resource-asset-archive` test) but not for `pulumi convert` so here we implement it. 
This might be used to support using local TF modules via `pulumi-converter-terraform` where we could copy the contents of the modules into the target project directory. 
Extending `Copy` and …

[convert] Copy assets emitted from converter plugins to target directory of the generated project

---

sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_test.go

Unify the error message when a user submits an invalid semver version:
```patch
URL:  "VERSION must be valid semver or git commit hash: v1.0.0.0"
-Name: "VERSION must be valid semver: Invalid character(s) found in patch number \"0.0\""
+Name: "VERSION must be valid semver: v1.0.0.0"
```

Unify the error message for invalid semver

---

changelog/pending/20250502--auto-python--add-on_error-callback-for-capturing-incremental-stderr-output.yaml
sdk/python/lib/pulumi/automation/_cmd.py
sdk/python/lib/pulumi/automation/_local_workspace.py
sdk/python/lib/pulumi/automation/_stack.py
sdk/python/lib/test/automation/test_local_workspace.py

This PR replicates the `on_output` callback for stderr in the Python Automation API so that error information can be collected incrementally.
* #19372
* #6511
Fixes #6511.

Add `on_error` callbacks to the Python Automation API operations

---

changelog/pending/20250514--auto-python--fix-hang-in-automation-api-operations.yaml
sdk/python/lib/pulumi/automation/_stack.py
sdk/python/lib/test/automation/test_stack.py

Automation API starts a thread to watch the events log. If the automation API call throws an error before the actual Pulumi operation starts, we will never write a cancel event to the logs file, and the thread hangs forever. Use a threading.Event to stop the polling loop to ensure the thread always finishes.

Fix hang in automation API operations

---

pkg/backend/httpstate/client/client.go
pkg/backend/httpstate/client/client_test.go
pkg/cmd/pulumi/pulumi.go
pkg/cmd/pulumi/pulumi_test.go
sdk/go/common/apitype/cli.go

Use the server provided `cacheMS` to store the duration for which version information should be cached.

Improve diagnostic event capture for cloud backends

---

changelog/pending/20250514--cli-install--dont-overwrite-versions-embedded-in-the-plugin-spec.yaml
pkg/cmd/pulumi/plugin/plugin_install.go
pkg/cmd/pulumi/plugin/plugin_install_test.go

For a description of the problem being addressed, see #19546. This PR is best reviewed commit by commit: the first commit is a refactor to make this testable. It does not change behavior. The second commit applies the fix with a test to lock in the correct behavior.
Fixes #19546

Avoid overwriting version set with `pkg@version` for `pulumi plugin install`

---

pkg/cmd/pulumi/newcmd/new.go
pkg/cmd/pulumi/operations/up.go
pkg/cmd/pulumi/templates/org.go
pkg/cmd/pulumi/templates/templates.go
pkg/cmd/pulumi/templates/templates_test.go

This argument is never actually read, so we don't need to pass it down.

Remove unused argument

---

pkg/cmd/pulumi/backend/login_manager.go
pkg/cmd/pulumi/templates/org.go

This function is only called in 2 places, and they handle the situation correctly:
It's handled directly in `getOrgTemplates`:
https://github.com/pulumi/pulumi/blob/559d223ac7b2d1b63226f62ac4c3f057f414aa80/pkg/cmd/pulumi/templates/org.go#L65-L68
It's handled as the result of `NonInteractiveCurrentBackend` in `getSummaryAbout`:
https://github.com/pulumi/pulumi/blob/559d223ac7b2d1b63226f62ac4c3f057f414aa80/pkg/cmd/pulumi/backend/backend.go#L65-L66
https://github.com/pulumi/pulumi/blob/559d223ac7b2d1b63226f62ac4c3f057f414aa80/pkg/cmd/pulumi/about/about.go#L187-L190

Don't return a backend with no logged in user

---

sdk/go/common/apitype/service.go

This reverts commit 25150e7d40c02b073cfe5aaec0de86937be7bcff.
We ended up not using capabilities to determine whether the backend supports the GetDefaultOrg API, so removing the unused code.
Related issue: https://github.com/pulumi/pulumi-service/issues/27548

Revert "Add default orgs as an API capability (#18928)"

---

.github/workflows/ci-run-test.yml

In https://github.com/pulumi/pulumi/pull/18719, we started using a `$PULUMI_GOCOVERDIR` variable, which we would translate into `$GOCOVERDIR` before running the `pulumi` binary in integration tests. This is because `go test` overwrites the `$GOCOVERDIR` variable otherwise, which resulted in us not having coverage data in integration tests.
However what we missed there is that other tests, such as the automation API tests also run the pulumi binary, but we have nothing that translates from `$PULUMI_GOCOVERDIR` to `$GOCOVERDIR` there (and nothing would need to, since nothing overwrites the env variable).  To fix this also set the $GOCOVERDIR` env variable for those tests that don't run under `go test -cover`, so we get coverage data from those tests as well.
Noticed this because a flaky …

Set GOCOVERDIR in addition to PULUMI_GOCOVERDIR in tests

---

changelog/pending/20250516--cli-install--fix-installation-of-python-policies-to-default-to-virtualenv-rather-than-site-packages.yaml
pkg/backend/httpstate/policypack.go

Fixes https://github.com/pulumi/pulumi/issues/19568
In https://github.com/pulumi/pulumi/pull/19477 we change policy installation to use the language runtimes `InstallDependencies` function. Unfortunately this doesn't auto-set the virtualenv option for python, because for programs the logic has never been to auto-set it. But policy packs _did_ autoset it to "venv" if it wasn't set and moving to InstallDependencies lost that.
This adds a small special case to policy install to set the option, we have very similar code in policy new.

Add in venv backcompat for python when installing policy

---

pkg/codegen/docs.go
pkg/codegen/docs_integration_test.go
pkg/codegen/dotnet/doc.go
pkg/codegen/go/doc.go
pkg/codegen/nodejs/doc.go
pkg/codegen/python/doc.go

This PR includes the new method, and an implementation for every language in this repo.
Motivated by https://github.com/pulumi/pulumi-service/issues/27266: The API we want to support needs needs to provide an overview of whats in the package (resources and functions). Concretely, that means it needs to return a list of modules, where each module needs to itself have a list of the resources and functions it contains. Each element returned (module, resource, function) needs to have a language appropriate name for each language we support.
I already have PRs to implement this in Java and YAML:
- https://github.com/pulumi/pulumi-java/pull/1808
- https://github.com/pulumi/pulumi-yaml/pull/797

Add `DocLanguageHelper.GetModuleName`

---

pkg/backend/apply.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/client/ai.go
sdk/go/common/apitype/ai.go
sdk/go/common/apitype/service.go
sdk/go/common/apitype/service_test.go

Fixes https://github.com/pulumi/pulumi.ai/issues/1821
Provides a deprecation story for the APIs that power the two `--copilot` features:
1. `explain-preview` #19138 
2. `summarize-error` #17956 
We now check `/api/capabilities` to see if those features are supported on the backend before enabling either the above features.
Server side PR:
- https://github.com/pulumi/pulumi-service/pull/28203

Adds /api/capabilities checking for `--copilot`

---

changelog/pending/20250515--cli-display--release-explain-preview-and-summarize-error-copilot-features.yaml
pkg/cmd/pulumi/operations/destroy.go
pkg/cmd/pulumi/operations/preview.go
pkg/cmd/pulumi/operations/refresh.go
pkg/cmd/pulumi/operations/up.go

Fixes https://github.com/pulumi/pulumi.ai/issues/1711
- --copilot flag will now be visible in pulumi: up, preview, destroy, refresh
- Part of the release

Unhide the --copilot flag in pulumi commands

---

pkg/codegen/pcl/binder.go
pkg/codegen/pcl/binder_nodes.go
pkg/codegen/pcl/binder_resource.go
pkg/codegen/pcl/binder_schema.go
pkg/codegen/pcl/binder_schema_test.go
pkg/codegen/schema/loader.go

I noticed we were using these functions and not getting lint errors, so this marks the functions as actually deprecated, and then fixes up the call sites.

Mark `LoadPackageReference` as deprecated

---

scripts/get-job-matrix.py

The error message we print here suggests that go compliation may have failed and to try `make lint`, but `go test --list` can also fail due to errors in test main functions.
To help debug those cases, and also to make the compilation errors more clear lets just print stdout and stderr from the failing command as well as our summary error message.

Print stdout/err if go test --list fails

---

cmd/pulumi-test-language/test_host.go
pkg/cmd/pulumi/operations/preview.go
pkg/cmd/pulumi/operations/up.go
pkg/engine/debugging.go
pkg/engine/debugging_test.go
pkg/engine/update.go
pkg/resource/deploy/deploytest/pluginhost.go
pkg/resource/deploy/providers/registry_test.go
pkg/resource/deploy/source_eval.go
sdk/go/common/resource/plugin/analyzer_plugin.go
sdk/go/common/resource/plugin/converter_plugin.go
sdk/go/common/resource/plugin/debugging.go
sdk/go/common/resource/plugin/host.go
sdk/go/common/resource/plugin/langruntime_plugin.go
sdk/go/common/resource/plugin/mock.go
sdk/go/common/resource/plugin/provider_plugin.go

Currently `--attach-debugger` only allows debugging programs. However we are introducing functionality to allow debugging source based plugins as well. For that, we want users to be able to filter what they want to debug.
By default users will be debugging programs, which is probably the most common case for most users. However we also allow debugging either all plugins, or plugins filtered by name.  These can be specified using `--attach-debugger plugins` or
`--attach-debugger plugin=<name>`.

allow filtering the runnable types that can be debugged

---

pkg/backend/apply.go
pkg/backend/apply_test.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/client/client.go

Fixes https://github.com/pulumi/pulumi.ai/issues/1856
- Rather than erroring out pulumi.
- Errors maybe timeouts / network errors that can be retried
- Add tests
Looks like this:

Return Copilot explainPreview errors to the user

---

pkg/cmd/pulumi/operations/import.go

Fixes https://github.com/pulumi/pulumi/issues/19538
Reduce amount of detail included inline and link to [the import guide](https://www.pulumi.com/docs/iac/adopting-pulumi/import/#bulk-import-operations) for full schema & field explanation. This includes the name table and additional fields relating to the provider, components, parents and remote.
Explain use of `pulumi preview --import-file` with example and making it more prominent by putting the sample command on its own line.

Refine import docs

---

pkg/codegen/docs.go
pkg/codegen/docs_integration_test.go
pkg/codegen/dotnet/doc.go
pkg/codegen/go/doc.go
pkg/codegen/nodejs/doc.go
pkg/codegen/python/doc.go

This PR adds a new method to `DocLanguageHelper` (mirroring the existing `GetFunctionName`), and an implementation for every language in this repo.
Motivated by https://github.com/pulumi/pulumi-service/issues/27266: The API we want to support needs needs to provide an overview of whats in the package (resources and functions). Concretely, that means it needs to return a list of modules, where each module needs to itself have a list of the resources and functions it contains. Each element returned (module, resource, function) needs to have a language appropriate name for each language we support.
This PR is extremely similar to https://github.com/pulumi/pulumi/pull/19569.
There are already PRs for pulumi-java and pulumi-yaml:
- https://github.com/pulumi/pulumi-java/pull/1810
- …

Add `DocLanguageHelper.GetResourceName`

---

Makefile
sdk/go/Makefile
tests/testutil/test_main_util.go

Currently the `build` target only builds `bin/pulumi` and puts it in $REPO_ROOT/bin.  However that's confusing, as we want all binaries there usually.  Make `build_local` the default `build` target, which already does exactly that.

make the `build` target build the whole repo

---

changelog/pending/20250519--engine--the-engine-will-respect-errors-from-plugin-handshake-methods.yaml
sdk/go/common/resource/plugin/analyzer_plugin.go
sdk/go/common/resource/plugin/langruntime_plugin.go
sdk/go/common/resource/plugin/provider_plugin.go

The engine was incorrectly throwing away any errors from plugin Handshake. While we should correctly ignore "Not implemented" errors, any other error should be bubbled up as a failure condition.

Return errors if handshake fails

---

changelog/pending/20250519--engine--elide-stackreference-outputs-that-fail-to-decrypt.yaml
pkg/backend/backend.go
pkg/backend/httpstate/backend.go
pkg/backend/secrets.go
pkg/backend/secrets_test.go
pkg/engine/lifecycletest/pulumi_test.go
pkg/resource/deploy/builtins.go
pkg/resource/deploy/builtins_test.go
pkg/resource/deploy/deployment.go
pkg/resource/deploy/deploytest/backendclient.go

`StackReference` is a resource offered by all core Pulumi SDKs, backed internally by the built-in provider. `StackReference`s allow stacks to read and refer to the outputs of other stacks. For example, given two stacks A and B, here written in TypeScript:
```typescript
// a/index.ts
export = async () => {
return {
aString: "from-a",
}
}
// b/index.ts
export = async () => {
const aRef = new pulumi.StackReference("organization/a/dev");
const aString = aRef.getOutput("aString")
return {
bString: pulumi.interpolate`from-b-and-${aString}`,
}
}
```
Here, A produces a single output, `aString`, with the value `from-a`. B creates a `StackReference` to A and loads the `aString` output, before including it in its own output, yielding `bString: "from-b-and-from-a"`.
This all works well, and can in …

Elide `StackReference` outputs that fail to decrypt

---

changelog/pending/20250508--programgen-python--add-sdk-support-for-scalar-call-returns-from-providers.yaml
sdk/python/lib/pulumi/runtime/__init__.py
sdk/python/lib/pulumi/runtime/invoke.py
sdk/python/lib/test/runtime/test_invoke.py

Much like #19387, this enables python scalar return values from method calls,
but now in python.
In order to keep things consistent, this change adds the equivalent functions call_single, call_single_plain.
Since python has automatic apply lifting there is no need to differentiate
between sync/async in these functions.
Codegen changes are in #19464
Part of #7345

Add python sdk support for method calls that return scalars

---

changelog/pending/20250521--cli--add-pulumi-esc-as-an-alias-for-pulumi-env.yaml
pkg/cmd/pulumi/env/env.go

This feels like a net positive, especially for heavy users of both ESC and Pulumi IaC that may have muscle memory that `pulumi env` breaks.
Fixes #15682.

Alias `pulumi esc` to `pulumi env`

---

changelog/pending/20250516--programgen--ensure-package-parameterization-during-convert-uses-the-output-project-directory-as-the-working-directory.yaml
pkg/cmd/pulumi/convert/convert.go

Converter plugins emit PCL that contains package descriptors with a parameterization value. That parameterization sometimes include relative paths that parameterized providers use to resolve assets e.g. resolving paths to local TF modules. When resolving these relative paths, they should be relative to output directory where the final Pulumi project is generated, not the current working directory where `pulumi convert` is running from which is the current behaviour today.
The current working directory where a package becomes parameterized from is the working directory of the plugin context it was loaded from. This PR changes the plugin context for the entirety of `pulumi convert` such that it uses the output directory (where the pulumi generated project will live) as the working directory …

[convert] Ensure convert uses the output project directory as the working directory

---

pkg/backend/diy/backend_legacy_test.go
pkg/backend/diy/backend_test.go
pkg/backend/httpstate/backend_test.go
pkg/backend/snapshot_test.go
pkg/cmd/pulumi/metadata/metadata_test.go
pkg/cmd/pulumi/newcmd/new_test.go
pkg/codegen/schema/docs_test.go
pkg/codegen/schema/schema_test.go
pkg/secrets/cloud/aws_test.go
pkg/secrets/cloud/manager_test.go
pkg/secrets/passphrase/manager_test.go
sdk/go/auto/cmd_test.go
sdk/go/common/tokens/stack_name_test.go
sdk/go/common/util/gitutil/git_test.go
sdk/go/common/workspace/plugins_install_nodejs_test.go
sdk/go/common/workspace/plugins_test.go
sdk/nodejs/cmd/pulumi-language-nodejs/main_test.go
sdk/python/toolchain/pip_test.go
sdk/python/toolchain/toolchain_test.go
tests/integration/integration_go_test.go
tests/integration/integration_nodejs_test.go
tests/integration/integration_python_acceptance_test.go
tests/integration/policy/policy_test.go
tests/smoke/smoke_test.go
tests/stack/stack_test.go

Removing nolint comments because the linter can now see t.Setenv calls.
Prompted by https://github.com/pulumi/pulumi/pull/19593#discussion_r2096032691

Clean up a load of nolint comments

---

changelog/pending/20250520--sdkgen--fix-data-race-in-codegen-type-conversions.yaml
pkg/codegen/hcl2/model/type_const.go
pkg/codegen/hcl2/model/type_enum.go
pkg/codegen/hcl2/model/type_list.go
pkg/codegen/hcl2/model/type_map.go
pkg/codegen/hcl2/model/type_object.go
pkg/codegen/hcl2/model/type_output.go
pkg/codegen/hcl2/model/type_promise.go
pkg/codegen/hcl2/model/type_set.go
pkg/codegen/hcl2/model/type_tuple.go
pkg/codegen/hcl2/model/type_union.go

This cache is used to cache intermediate results for type conversions (see also https://github.com/pulumi/pulumi/pull/19422). However as these functions can be called in parallel, if the cache is not initialized, there is a possibility of a data race, checking for `t.cache == nil` from one goroutine, while another writes to the variable.
We could fix this using a mutex, but this code is somewhat performance critical, so it's better to just make sure to initialize this up front, so we don't have to have a lock at every conversion.

codegen: always initialize cache when initializing type

---

cmd/pulumi-test-language/test_host.go

Noticed while adding policy tests. The host context never cleaned up all the grpc connections that it created.

Close grpc connections on host close in conformance tests

---

changelog/pending/20250522--cli--improve-error-message-when-stack-select-is-run-in-non-interactive-mode.yaml
pkg/cmd/pulumi/stack/stack_select.go

When `pulumi stack select` is run in non-interactive mode, and no stack name is passed in as an argument to the command, we error out with:
```
error: no stack selected; please use `pulumi stack select` or `pulumi stack init` to choose one
```
This is confusing to the user, as they are already running `pulumi stack select`. Improve the error message here, to make this less confusing to the user, and get them to either run the command in interactive mode, or pass an argument to `pulumi stack select`.

stack select: better error in non-interactive mode

---

Makefile

Realpath returns "" on macos for non-existent files, which then causes all our binaries to build to ~/go/bin instead of ./bin. Fix it by just making sure the folder exists with a mkdir first.

Fix makefile for osx

---

changelog/pending/20250425--programgen-python--add-pulumi-as-reserved-keyword-in-binder-to-fix-python-codegen-issues.yaml
pkg/codegen/schema/bind.go
pkg/codegen/schema/reserved_keywords.go
pkg/codegen/schema/schema_test.go

Python codegen breaks due to the pulumi key name being reserved.  This change is a first pass at adding various checks to the schema to fail instead of generating the failing program.
Also added some diags that were not returned due to error.  Error should be checked but diags might be useful (as they are in these tests) so I moved some things around a bit to return them
Fixes #18994

schema check and reserve pulumi keyword

---

changelog/pending/20250527--auto-python--revert-add-on_error-callback-for-capturing-incremental-stderr-output.yaml
sdk/python/lib/pulumi/automation/_cmd.py
sdk/python/lib/pulumi/automation/_local_workspace.py
sdk/python/lib/pulumi/automation/_stack.py
sdk/python/lib/test/automation/test_local_workspace.py

Reverts pulumi/pulumi#19541.
`select` isn't Windows-friendly. We have a feeling that replacing `select` with `selectors` might be all that is required to fix this, but we're not certain. So, we're going to revert this change, fix CI to run the tests against Windows, and then we'll know for sure.

Revert "Add `on_error` callbacks to the Python Automation API operations"

---

changelog/pending/20250523--cli-display--fix-color-of-copilot-summarize-error-so-its-more-readable-on-light-terminals.yaml
pkg/backend/display/ai.go

Fixes #19641 
- BrightGreen + light background in terminal is not great
- The point of the color was to draw the eye to the short summary. Once that is "loaded" you can more quickly scan the diagnostics section if needed.
- Does the ✨ alone bring enough attention?
Below are 3 variations on the existing colors:
1. Soften the green to make it more readable on light terminals
2. Remove the color
3. Remove the color and shift the ✨ 
Here, after below discussion, we select variant 2.

Make color of Copilot summarize-error output more readable

---

Makefile
docs/Makefile
scripts/retry
sdk/nodejs/Makefile
sdk/python/Makefile

In CI, `make ensure` sometimes fails because upstream servers return a 5xx or other random network issues.  We already have `scripts/retry` to retry things in CI, and these targets should retry just in case we hit a temporary hiccup, e.g. such as in
https://github.com/pulumi/pulumi/actions/runs/15272119669/job/42950379398.
`scripts/retry` sets some extra environment variables that help with `go test`, but they won't interfere with this, and it's convnient to have a single script for retrying.

retry downloads form upstream in `make ensure`

---

pkg/engine/lifecycletest/framework/framework.go

Small improvement to the lifecycletest framework.  Currently if there's an error, we log it and call `t.FailNow()` (and then unnecessarily still assert that there's no error).  Refactor this, so it's all a single `require.NoError`, which in addition to being cleaner (and more importantly) also provides the full backtrace for the error, which makes it easier to debug.
Tiny thing I noticed while working with lifecycletests.

improve error handling in lifecycletest framework

---

.github/workflows/cron-direct-build.yml

Rather than relying on whatever already exists on the machine.
Fixes #19227.

Install the Pulumi dev release before running the direct cron build

---

pkg/cmd/pulumi/plugin/plugin_run.go
sdk/go/common/resource/plugin/analyzer_plugin.go
sdk/go/common/resource/plugin/converter_plugin.go
sdk/go/common/resource/plugin/langruntime_plugin.go
sdk/go/common/resource/plugin/plugin.go
sdk/go/common/resource/plugin/plugin_test.go
sdk/go/common/resource/plugin/provider_plugin.go

Rather than using `exec.Cmd` just re-use the execution logic we already have in the plugin system for `plugin run`.
This has a difference that we're `io.Copy`ing the standard io streams rather than assigning `os.Stdout/err` directly to the commands io streams. Should be fine for the simple uses of `plugin run` we have, but if we want to support rich tty style things here we'd need to be smarter about this.

Use plugin.ExecPlugin in plugin run

---

changelog/pending/20250530--engine--log-callbacks-requests.yaml
pkg/resource/deploy/source_eval.go

Use the plugin context’s GRPC dial options for callback clients so that requests are logged when using `PULUMI_DEBUG_GRPC`.

Log callback requests

---

changelog/pending/20250528--sdkgen-python--add-sdkgen-for-non-object-method-invoke-return-values.yaml
sdk/python/lib/pulumi/runtime/__init__.py
sdk/python/lib/pulumi/runtime/invoke.py

Much like #19387 which adds method call scalar returns, this change adds
sdk changes for scalar invoke returns in python (a feature already in nodejs)
This is the SDK changes only which must be relesed before the sdkgen
changes which are in #19661 
Part of #19388

Add sdk changes to python to enable non-object function call returns

---

changelog/pending/20250605--engine--fix-panic-when-importing-resources.yaml
pkg/engine/lifecycletest/framework/framework.go
pkg/engine/lifecycletest/import_test.go
pkg/resource/deploy/step_generator.go
pkg/resource/deploy/step_generator_events.go

Engine tests weren't running with plan generation turned on, but in the CLI we always enable this. That missed that we could hit a panic for imported resources because it hit an error that it's plan already unexpectedly existed.
It would be worth our time ensuring engine tests always test this flag.

Fix plan generation for imported resources

---

pkg/backend/backend.go
pkg/backend/backenderr/backenderr.go
pkg/backend/backenderr/backenderr_test.go
pkg/backend/diy/backend.go
pkg/backend/diy/unauthenticatedregistry/package_registry.go
pkg/backend/diy/unauthenticatedregistry/package_registry_test.go
pkg/backend/httpstate/backend.go
pkg/backend/mock.go
sdk/go/common/env/env.go
sdk/go/common/registry/registry.go
sdk/go/common/registry/registry_test.go

This PR adds an interface for reading the Pulumi registry in `sdk/go/common/registry`, and extends the definition of backend to include `GetReadOnlyPackageRegistry`. 
Both backends have been adjusted to supporting returning a conforming type:
- The HTTP backend returns the same object it already returned for `GetPackageRegistry`.
- The DIY backend now returns an unauthenticated registry. Unauthenticated registries hit the service without credentials, and thus can only see publicly available packages. 
The new code is not used in this PR. This has been factored out of https://github.com/pulumi/pulumi/pull/19499, and will be consumed in follow-up PRs.

Implement a shared registry read abstraction

---

pkg/cmd/pulumi/install/install.go
pkg/cmd/pulumi/packagecmd/project_sdk_link.go
sdk/go/common/resource/plugin/host.go
sdk/go/common/resource/plugin/host_test.go

Context propagation is nice. More propagation is better.
A GitHub search shows that only we use `plugin.IsLocalPluginPath`:
https://github.com/search?q=%22plugin.IsLocalPluginPath%22+-is%3Afork&type=code

Pass `context.Context` to `plugin.IsLocalPluginPath`

---

changelog/pending/20250609--cli--fix-package-add-always-reporting-providers-as-crashing.yaml
pkg/cmd/pulumi/packagecmd/project_sdk_link.go
tests/integration/integration_go_test.go

Fixes https://github.com/pulumi/pulumi/issues/19764
We were calling `Close` directly on the provider plugin client objects, which did correctly close the provider down cleanly. But it didn't remove it from the list of providers that the host object was tracking. When we then asked the host object to also close it tried to close each provider and would error that the provider had unexpectedly already shutdown.
Small fix to just use `host.CloseProvider` instead of closing the provider object directly.

Test and fix providers not being cleanly shutdown in package add

---

.github/workflows/ci.yml
cmd/pulumi-test-language/main_test.go
pkg/backend/apply_test.go
pkg/backend/display/progress_test.go
pkg/backend/diy/main_test.go
pkg/backend/httpstate/main_test.go
pkg/backend/httpstate/snapshot_test.go
pkg/engine/lifecycletest/pulumi_test.go
pkg/engine/progress_test.go
pkg/resource/deploy/deploytest/main_test.go
pkg/resource/deploy/main_test.go
pkg/secrets/passphrase/manager_test.go
sdk/go/common/resource/config/repr_test.go
sdk/go/common/resource/plugin/main_test.go
sdk/go/common/tail/tail_test.go
sdk/go/common/util/gitutil/git_test.go
sdk/go/common/workspace/main_test.go
sdk/go/common/workspace/plugins_test.go
sdk/go/internal/gen-pux-applyn/main_test.go
sdk/go/pulumi/generate/main_test.go
sdk/python/toolchain/pip_test.go
sdk/python/toolchain/pyproject_test.go
sdk/python/toolchain/toolchain_test.go

We currently run unit tests on linux only.  However we have enough compute capacity to run them on all platforms, and it's safer to do so.  Do so.
Note that a bunch of tests don't succeed on Windows (and some don't succeed on MacOS).  For the most part I just excluded them from being run on those platforms here, leaving the cleanup for follow up PRs.  This gets us to a place where *new* tests are going to be run on all platforms, so we don't have more regressions, and we can clean up the platform specific excludes as we go.  Some excludes are using a `TestMain` in the package, which is because most of the tests in that package do not run successfully, and it was too much work to go through test by test.

run unit tests on all platforms

---

changelog/pending/20250605--engine--close-sourceiterator.yaml
pkg/engine/lifecycletest/analyzer_test.go
pkg/engine/lifecycletest/delete_before_replace_test.go
pkg/engine/lifecycletest/import_test.go
pkg/engine/lifecycletest/pending_replace_test.go
pkg/engine/lifecycletest/provider_test.go
pkg/engine/lifecycletest/pulumi_test.go
pkg/engine/lifecycletest/step_generator_test.go
pkg/engine/lifecycletest/target_test.go
pkg/engine/lifecycletest/update_plan_test.go
pkg/engine/lifecycletest/views_test.go
pkg/resource/deploy/deployment_executor.go
pkg/resource/deploy/deployment_executor_test.go

We need to close the SourceIterator so it will cleanup the resource monitor. This will cancel any outstanding requests on the resource monitor, which ensures that the calls get written to the  `PULUMI_DEBUG_GRPC` log.
This required updated many of the lifecycle tests since now the `monitor.RegisterResource` calls always returns. Tests previously asserted `NoError` on these, but we never actually hit the assertion.

Close SourceIterator

---

changelog/pending/20250609--cli-install--resolve-plugin-download-urls-by-referencing-the-pulumi-registry.yaml
pkg/backend/backenderr/backenderr.go
pkg/backend/httpstate/client/api.go
pkg/cmd/pulumi/plugin/plugin_install.go
pkg/cmd/pulumi/plugin/plugin_install_test.go
sdk/go/common/env/env.go
sdk/go/common/registry/errors.go
sdk/go/common/registry/registry.go
sdk/go/common/registry/registry_test.go
sdk/go/common/registry/resolve.go
sdk/go/common/registry/resolve_test.go

This PR adds support for performing a registry based lookup when installing packages with `pulumi plugin install`.
Examples:
```console
$ pulumi plugin install resource aws-k8s # aws-k8s is a private package
[resource plugin aws-k8s-0.0.21] installing
Downloading plugin: 456.40 KiB / 456.40 KiB [=======================] 100.00% 0s
```
```console
$ pulumi plugin install resource azapi # azapi is in the public registry, but not published by Pulumi
error: 404 HTTP error fetching plugin from https://api.github.com/repos/pulumi/pulumi-azapi/releases/latest. If this is a private GitHub repository, try providing a token via the GITHUB_TOKEN environment variable. See: https://github.com/settings/tokens
```
```console
$ pulumi plugin install resource dirien/azapi # we need to reference the …
```

Use the Pulumi Registry when resolving `pluginDownloadURLs` for `pulumi plugin install`.

---

scripts/get-language-providers.sh

Updating ahead of the release.  Note that we don't update the dotnet version for now, since the release for the language plugin binary failed, and there are no new updates here, so we can defer this for next week.

update java and yaml to latest version

---

sdk/go/pulumi/policyx/policy_pack.go
sdk/go/pulumi/policyx/server.go

Trying to be consistent, we called this engine in dotnet. We should call it engine here as well, we'd already renamed the type here so just need to rename one field.

Rename host to engine in policyx

---

.github/workflows/cron-test-all.yml

Collecting coverage data on windows is quite flaky (see https://github.com/pulumi/pulumi/issues/16490). Since we're running the most extensive test suite in the daily test run, this unfortunately comes up quite often here.
We already get coverage data on each merge, which won't change during the daily run (maybe it's a tiny bit higher since we run more test jobs daily, but that's another reason to disable it here, so we get more consistent data).
Disable the coverage reporting here to reduce the flakyness hopefully.
Fixes https://github.com/pulumi/pulumi/issues/19639

disable coverage reporting in daily test runs

---

changelog/pending/20250611--programgen--fix-panic-in-programgen.yaml
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/pcl/binder_component.go
pkg/codegen/pcl/binder_schema_test.go

Since https://github.com/pulumi/pulumi/pull/19604, we're doing a bit more initialization in `model.New.*Type`, namely initializing the map for caching intermediate results for type reduction.  However there were a few places where we just directly initialized the struct, which makes the map not initialized, leading to panics.  Fix this by always initializing the types properly.
Fixes https://github.com/pulumi/pulumi/issues/19828

always initialize model types properly

---

Makefile

`sort` does not sort the same way for some characters on macOS compared to Linux, depending on the locale. By setting the locale to `C` we ensure we get the same order here.
This remove the need to manually re-order the protobuf `.checksum.txt` file when updating protobufs on macOS.

Fix proto checksum order on macOS

---

changelog/pending/20250612--auto-nodejs--fix-stack-name-in-object-after-rename-operations.yaml
sdk/nodejs/automation/stack.ts
sdk/nodejs/tests/automation/localWorkspace.spec.ts

Currently when using `stack.rename()` in the NodeJS automation API, we rename the stack, but internally keep using the old name.  This means any subsequent operations on that stack object will also use that old name.
For the cloud backend this *kinda* works, as I think the cloud just redirects from the old name to the new one, as long as there's no new stack that took over the old name.  However for the filestate backend this doesn't work at all, since the stack is no longer available.
Fix this by setting the name of the stack correctly internally as well.
Also fix the test so it works when `PULUMI_ACCESS_TOKEN` is not set. Note that there's a little oddity here, as for local backends we don't have a summary event for the rename here.  Not sure how to deal with that correctly.

auto/nodejs: rename stack internally when calling rename()

---

pkg/codegen/testing/test/helpers.go
scripts/get-language-providers.sh

This isn't going into this weeks release, but we should upgrade the version anyway, as once providers start depending on the newer SDK version our integration tests will start failing if we don't update now.

upgrade pulumi-dotnet to latest

---

changelog/pending/20250613--auto-python--respect-parallelism-settings.yaml
sdk/python/lib/pulumi/automation/_server.py

When running an inline python program using the automation API, deployments are limited to 16 concurrent actions.
We can notice the issue in this demo, which uses the automation API (with an inline program) : [https://asciinema.org/a/01HCUcmfWo27RUyuEJtnPoMHt](https://asciinema.org/a/01HCUcmfWo27RUyuEJtnPoMHt)
We can see that 16 resources are created (which takes 10 seconds), then the 14 last resources are created. This results in waiting 20 seconds, while it was expected to create all resources simultaneously.
This demo runs the exact same program but using the pulumi binary : [https://asciinema.org/a/olWRUsZGfrVNZ4FdBzLUDqUxF](https://asciinema.org/a/olWRUsZGfrVNZ4FdBzLUDqUxF)
I found out that unlike the `sdk/python/cmd/pulumi-language-python-exec` script, `the …

[AutomationAPI/Python] Fix Parallelism

---

cmd/pulumi-test-language/interface.go
pkg/backend/diy/stack.go
pkg/backend/httpstate/stack.go
pkg/backend/mock.go
pkg/backend/stack.go
pkg/cmd/pulumi/config/config.go
pkg/cmd/pulumi/logs/logs.go
pkg/cmd/pulumi/operations/destroy.go
pkg/cmd/pulumi/operations/import.go
pkg/cmd/pulumi/operations/preview.go
pkg/cmd/pulumi/operations/refresh.go
pkg/cmd/pulumi/operations/up.go
pkg/cmd/pulumi/operations/watch.go
pkg/cmd/pulumi/stack/io.go
pkg/cmd/pulumi/stack/stack_change_secrets_provider.go
pkg/cmd/pulumi/stack/stack_change_secrets_provider_test.go
pkg/cmd/pulumi/stack/stack_export.go
pkg/cmd/pulumi/stack/stack_rename.go
pkg/cmd/pulumi/stack/stack_rm.go
pkg/cmd/pulumi/state/io.go
pkg/cmd/pulumi/state/state_delete_test.go
pkg/cmd/pulumi/state/state_repair.go
pkg/cmd/pulumi/state/state_repair_test.go
tests/integration/backend/diy/backend_postgres_test.go

The `Stack` interface has a series of methods whose implementations always delegate to the underlying `Backend`. These serve only to widen the interface unnecessarily (making it harder to identify what code is _actually_ backend-specific) and can be replaced with a single set of stack-agnostic functions. These functions actually already exist; they are just not used consistently. This change removes the interface methods and rolls out the functions uniformly, removing a bunch of code and nicely shrinking the `Stack` interface to something more fundamental.

Remove dead code for stack operations

---

changelog/pending/20250616--cli-install--dont-consult-the-registry-when-file-is-specified.yaml
pkg/cmd/pulumi/plugin/plugin_install.go
pkg/cmd/pulumi/plugin/plugin_install_test.go

This addressed a bug that Pulumi's own insights team found when running:
```
pulumi plugin install resource some-provider ${VERSION} --file ${FILE}
```
The registry should not be consulted when `--file` has been passed, since the user has located the provider for us. This is the same reason why the registry shouldn't be consulted when `--server` (pluginDownloadURL) is passed.

Skip registry lookup when `--file` is passed

---

Makefile

The lint steps have recently started to require the `biome` dependency in sdk/nodejs.  This is not available unless one has run `make ensure` or a command with similar effect (installing the biome dependency) before.  Make the lint step depend on `ensure` to make sure it can always successfully run.

make lint steps depend on `ensure`

---

pkg/cmd/pulumi/newcmd/new_test.go

While writing up the post mortem for https://github.com/pulumi/home/issues/4062 I noticed that the test I included was redundant with `TestPulumiNewWithoutPulumiAccessToken` and my test actually had the exact same issue as the test from the original PR!
I had validated the test locally with no ambient Pulumi credentials, to ensure it failed without the fix, but we would have not caught this issue in CI if it cropped up again.

Fix TestPulumiNewWithoutPulumiAccessToken

---

pkg/cmd/pulumi/stack/io.go

Fixes #19749
Warnings are written to stderr so won't affect the JSON from the stdout.
This might break anywhere which asserts that the stderr is empty as a criteria for success.

Use diag.Sink for stack config warning

---

pkg/backend/backend.go
pkg/backend/cloud_registry.go
pkg/backend/diy/backend.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/backend_test.go
pkg/backend/httpstate/cloud_registry.go
pkg/backend/httpstate/mock.go
pkg/backend/mock.go
pkg/cmd/pulumi/packagecmd/package_publish.go
pkg/cmd/pulumi/packagecmd/package_publish_test.go
pkg/cmd/pulumi/plugin/plugin_install.go

The registry handles not just packages but also templates and other resources, so CloudRegistry is a more accurate name.

Rename PackageRegistry to CloudRegistry

---

changelog/pending/20250617--backend-diy--diy-backend-can-now-remove-stacks-that-are-empty-except-for-their-root-stack-resource-this-is-inline-with-the-behaviour-of-the-service.yaml
pkg/backend/diy/backend.go
tests/stack/stack_test.go

This was noticed in dotnet testing: https://github.com/pulumi/pulumi-dotnet/pull/650/commits/5547cc03dd70ecd500bab203739e86e99ba4fc33
Seems the service will allow the removal of a stack even if it still has it's root stack resource in it (i.e. not cleaned up completly via destroy). But the DIY backend would error that the stack still had resources.
This adds a test to show both behave the same now, and fixes the DIY backend to allow removal when there is only one resource which is the root stack.

Allow DIY backend to remove stacks with just a stack resource

---

pkg/cmd/pulumi/plugin/plugin_run.go
sdk/go/common/resource/plugin/plugin.go

Cleans up a `context.TODO`, waiting is an async action that can be cancelled if the context cancels.

Thread a context to plugin Wait

---

changelog/pending/20250618--engine--fix-views-with-refresh-run-program.yaml
pkg/backend/snapshot.go
pkg/engine/journal.go
pkg/engine/lifecycletest/views_test.go
pkg/resource/deploy/resource_status.go
pkg/resource/deploy/step.go
pkg/resource/deploy/step_generator.go

Originally reported in https://github.com/pulumi/pulumi/issues/19755, and worked around via https://github.com/pulumi/pulumi/pull/19821 which changed the tfmodule views to refresh before the program. This didn't fix tfmodules (or other views) when used with `--refresh --run-program`.
This fixes views to write to the snapshot correctly when being refreshed, this follows the same logic as normal refresh steps. That is they can either be pre-program-run non-persisted steps, or persisted steps being run during the program.
With this fix in place we should be able to move the RefreshBeforeUpdate back to how it was, but I haven't done that in this PR.

Fix refresh views with --run-program

---

pkg/engine/lifecycletest/delete_before_replace_test.go
pkg/engine/lifecycletest/pulumi_test.go

This test is flaky because occasionally the steps are not being generated in the same order.  In particular sometimes the Same step happens before the Replace step.  I'm assuming this is because of the recently introduced asynchronicity of the step generator.
Either way what we care about here is that all the steps are happening, not necessarily that they are always in the exact same order.  Steps do need a partial ordering, so snapshot integrity is still sustained, but we already check for snapshot integrity at every test step in the framework anyway.
Potentially we could just replace `AssertSameSteps` with the new function, but I'm not sure if ordering matters *somewhere*, so I went for the minimally necessary change for now.
Fixes https://github.com/pulumi/pulumi/issues/19063

fix flaky TestExplicitDeleteBeforeReplace

---

pkg/backend/diy/backend.go
pkg/backend/diy/state.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/state.go
pkg/engine/deployment.go
pkg/engine/deployment_test.go
pkg/engine/destroy.go
pkg/engine/engine.go
pkg/engine/events.go
pkg/engine/import.go
pkg/engine/lifecycletest/framework/framework.go
pkg/engine/refresh.go
pkg/engine/update.go
pkg/engine/update_test.go

The `engine.UpdateInfo` type captures information about a Pulumi update (where an update is a general term for a Pulumi operation, and not just e.g. a `pulumi up`). Until now, it has been an interface exposing information about the Pulumi project being operated on and the selected target (stack, configuration, etc.), with implementations for both DIY and Cloud (`httpstate`) backends.
It turns out that these implementations are in fact largely the same -- data structures carrying the relevant `Project` and `Target`, with some backend-specific bits tacked on. Hoisting out these backend-specific bits into the code that actually cares about them allows us to make `UpdateInfo` a dumb struct instead. This reduces the amount of update code that is actually backend-specific, and should make it …

Unify `UpdateInfo` implementations

---

changelog/pending/20250620--sdk-nodejs--fix-the-use-of-parameterised-packages-and-mocks.yaml
sdk/nodejs/log/index.ts
sdk/nodejs/runtime/mocks.ts
sdk/nodejs/runtime/resource.ts
tests/integration/go/parameterized/actual_program_test.txt
tests/integration/nodejs/parameterized/index.spec.ts
tests/integration/python/parameterized/test.py

This tests and fixes the use of parameterised packages in Node mocks.
Firstly there is the actual fix, we need to set `store.supportsParameterization` to true when using mocks.
Secondly, I've added tests to Node and Go and Python, to check that the resource registration _actually_ runs.
Thirdly, I've added some more debug logs to the node codebase that I found useful tracking down what was happening here.

Fix parameterised packages in node mocks

---

sdk/go/common/tail/tail_test.go

These tests are flaky, because of races in the underlying tail library.  I haven't been able to figure out those races so far, but these test flakes are quite annoying.
/xref https://github.com/pulumi/pulumi/issues/19888
Fixes https://github.com/pulumi/pulumi/issues/19919

skip flaky go/common/tail tests

---

changelog/pending/20250623--cli--do-not-assume-that-package-sources-without-file-path-prefixes-are-file-paths.yaml
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_test.go

In preparation for https://github.com/pulumi/pulumi/pull/19928.
This is a minor breaking change, since `packages:` blocks in `Pulumi.yaml` that specified path based packages with less then 4 slashes and no leading `./`, `../` or `/` will stop working. The problem can be addressed by appending a `./` to the package.

Allow plugin names to include up to 3 slashes

---

changelog/pending/20250618--cli--warn-more-aggressively-for-very-old-cli-versions.yaml
pkg/cmd/pulumi/pulumi.go
pkg/cmd/pulumi/pulumi_test.go

When the Pulumi CLI (and as a consequence, the Pulumi engine) falls _way_ behind, it is almost guaranteed that users will have a subpar experience due to the number of issues we fix (such as snapshot integrity bugs) and improvements we ship at a regular cadence. This change tweaks the update prompt in these cases to emphasize that the running version is really very old and that updating is more advisory than opportunistic. Presently, we consider "very old" to either be a major version (unlikely in the near future, but a safe bet) or 24 minor versions (which assuming ~1 release a week is 24 weeks = 6 months, which feels reasonable).
Part of #19105

Warn more aggressively for very old CLI versions

---

pkg/engine/lifecycletest/target_test.go

We always go down the `if err == nil` path here, or the `ErrorContains` would fail.
Leftover from https://github.com/pulumi/pulumi/pull/19740

Remove useless `if` in TestTargetUntargetedParent

---

pkg/backend/diy/unauthenticatedregistry/package_registry.go
pkg/backend/diy/unauthenticatedregistry/package_registry_test.go
pkg/backend/httpstate/client/client.go
pkg/backend/httpstate/client/client_test.go
pkg/backend/httpstate/cloud_registry.go
pkg/backend/mock.go
pkg/cmd/pulumi/plugin/plugin_install_test.go
sdk/go/common/registry/registry.go
sdk/go/common/registry/registry_test.go
sdk/go/common/registry/resolve.go

`SearchByName` calls into the `ListPackages` endpoint in the registry, and this name is more descriptive. This is in preparation for adding `ListTemplates` and `GetTemplates` to the registry here.

Rename `(registry.Registry).SearchByName` to `ListPackages`

---

changelog/pending/20250604--auto-pass-run-program-to-preview-and-up.yaml
sdk/go/auto/optpreview/optpreview.go
sdk/go/auto/optup/optup.go
sdk/go/auto/stack.go
sdk/nodejs/automation/stack.ts
sdk/python/lib/pulumi/automation/_stack.py

https://github.com/pulumi/pulumi/pull/19218 introduces runProgram to the automation api, but only for destroy/preview. https://github.com/pulumi/pulumi/pull/19667 introduces support to feed runProgram into pulumi up in the auto sdk. https://github.com/pulumi/pulumi/pull/19449/files already added support for preview/up.
The following change adds the similar support for preview/up in the sdk for go/nodejs/python.

Support runProgram for preview/up in auto sdk

---

changelog/pending/20250625--auto-python--add-preview_destroy-to-allow-dry-runs-of-destroy-commands.yaml
sdk/python/lib/pulumi/automation/_stack.py
sdk/python/lib/test/automation/test_local_workspace.py

Similarly to #19900, this PR adds the `preview_destroy` command and deprecates the `preview_only` flag for `destroy`. The aforementioned PR explains the problem, but in short, the change summary for `destroy(preview_only=True)` is inaccurate.

Add `preview_destroy` for the Python Automation API

---

changelog/pending/20250618--auto-python--add-preview_refresh-to-allow-dry-runs-of-refresh-commands.yaml
sdk/python/lib/pulumi/automation/_stack.py
sdk/python/lib/test/automation/test_local_workspace.py

In https://github.com/pulumi/pulumi/pull/19373, we added the `previewOnly` flag to the `refresh` command. However, this raised some issues, as commands in the automation API use the `pulumi stack history` to find the results of a given command. Because a preview command doesn't produce any new information in the `stack history`, we would instead return the results of whatever the previous command was (https://github.com/pulumi/pulumi/issues/19443).
Unfortunately, if we want the preview information, we have to make do with what we can find in the event summary, but this doesn't give us enough information to construct a full `RefreshResult`. For that reason, this PR introduces a new command, `preview_refresh` (to return everything we _can_ know, which is a `PreviewResult`), and deprecates …

Add `preview_refresh` for the Python Automation API

---

changelog/pending/20250624--engine--fix-a-panic-when-mixing-target-refresh-and-provider-upgrades.yaml
pkg/engine/lifecycletest/target_test.go
pkg/resource/deploy/step_generator.go

Fixes https://github.com/pulumi/pulumi/issues/19879
If we hit the case where the provider resource wasn't registered we should be able to look it up from the old state. This fixes the case where a resource would need to be sent to analysis but wasn't registered in the update pass and so its provider was also not registered.

Fix a panic with --target, --refresh and provider upgrades

---

scripts/get-language-providers.sh

`pulumi-java` is now on `v1.13.2`.

Bump `pulumi-java` for the next release

---

CONTRIBUTING.md

I got stung by this yesterday, so it's good to have a big, red reminder and a little more explanation.

Add a warning to the `CONTRIBUTING.md` release section

---

pkg/backend/diy/unauthenticatedregistry/package_registry.go
pkg/backend/httpstate/client/client.go
pkg/backend/httpstate/client/client_template_test.go
pkg/backend/httpstate/client/client_test.go
pkg/backend/httpstate/cloud_registry.go
pkg/backend/mock.go
pkg/cmd/pulumi/plugin/plugin_install_test.go
sdk/go/common/apitype/templates.go
sdk/go/common/registry/registry.go
sdk/go/common/registry/registry_test.go
sdk/go/common/registry/resolve_test.go

This PR adds two new functions to `(registry.Registry)`: `GetTemplate` and `ListTemplates`. These functions will be used to incorporate Private Registry backed templates into the Pulumi CLI.
Related to https://github.com/pulumi/pulumi-service/issues/29500
Stacked on https://github.com/pulumi/pulumi/pull/19936

Add `(registry.Registry).{Get,List}Template(s)`

---

changelog/pending/20250627--sdk-go-nodejs-python--add-pulumi_automation_api.yaml
pkg/cmd/pulumi/pulumi.go
pkg/cmd/pulumi/pulumi_test.go
sdk/go/auto/cmd.go
sdk/nodejs/automation/cmd.ts
sdk/python/lib/pulumi/automation/_cmd.py

Always set `PULUMI_AUTOMATION_API=true` in Automation API calls and pass it through to metadata.

Add PULUMI_AUTOMATION_API marker env variable and add to metadata

---

pkg/resource/deploy/step_generator.go

Rather than building all the delete steps then filtering them by --targets and --excludes, just run the filtering logic as we build the steps. This also saves old providers being started up by "EnsureProvider" just to go unused.

Filter delete steps while building

---

.github/workflows/cron-test-all.yml

I just added this in https://github.com/pulumi/pulumi/pull/19987, but when manually running a job, you can select the branch via the GitHub UI, there’s no need to make this a separate input.

Simplify cron-test-all branch selection

---

changelog/pending/20250314--sdk-python--log-safely-in-python-in-the-presence-of-pulumi_error_output_string.yaml
sdk/python/lib/pulumi/_output.py
sdk/python/lib/pulumi/output.py
sdk/python/lib/pulumi/runtime/resource.py
sdk/python/lib/test/test_output.py

Attempting to convert an `Output` to a string is a common pitfall Pulumi users face -- since an `Output` value may not be available yet (akin to a `Promise` in NodeJS, for instance), it's not in general possible or safe to serialize an `Output` to a string in all cases. To this end, the various language SDKs override string serialization for `Output` so that an informative message is printed, which hopefully helps the user achieve what they set out to (e.g. via `__str__` in Python, `toString` in Java, and so on).
For users that want their programs to throw a hard error when they mistakenly try to stringify an `Output`, Pulumi offers the `PULUMI_ERROR_OUTPUT_STRING` environment variable. If this is set, the relevant implementations (`__str__`, etc.) will crash if called. This is all well …

Log safely in Python in the presence of `PULUMI_ERROR_OUTPUT_STRING`

---

changelog/pending/20250702--cli-new--fix-the-ai-prompt-flow-of-pulumi-new-command.yaml
pkg/cmd/pulumi/newcmd/new.go
pkg/cmd/pulumi/newcmd/new_ai_test.go

Fix https://github.com/pulumi/pulumi/issues/19994 which is a regression from https://github.com/pulumi/pulumi/pull/18627
The change is essentially moving the block which assigns `args.templateNameOrURL` above the call to `cmdTemplates.New` which uses `args.templateNameOrURL`. With the existing order, `args.templateNameOrURL` set to the AI URL was ignored.
The rest of the change is refactoring the AI prompting to a separate function and a test that mocks that function to a hard-coded value.

Fix the AI prompt flow for pulumi new

---

changelog/pending/20250707--cli--fix-stack-select-when-local-default-org-differs-from-the-service-setting-for-default-org.yaml
pkg/backend/httpstate/backend.go

Fixes https://github.com/pulumi/pulumi/issues/19598
There was an inconsistency between GetStack and ListStacks on deciding what the default org was. This could result in stacks from GetStack thinking the default org was A, and stacks from ListStacks thinking the default org was B.
When rendering out the names this could result in the same stack being rendered different. GetStack for "A/proj/stk" would print "stk" because it thought A was the default org, while ListStack would render "A/proj/stk" because it thought B was the default org.
When used in stack select code this could result in an error from the survey library as we gave it a list of stacks (including "A/proj/stk") but told it the default was just "stk" (which wasn't in the list).

Fix ListStacks to use the same default-org logic as loading a single stack

---

sdk/python/lib/pulumi/resource_hooks.py

We're calling this callback in other SDKs. This is breaking, but we have not released this code yet.

Rename ResourceHook.func -> callback

---

.github/workflows/cron-direct-build.yml

The `cron-direct-build` GitHub Action tests that Pulumi can be built when all modules are downloaded from version-controlled source (using `GOPROXY=direct`, see https://go.dev/ref/mod) rather than through a module proxy. Recent changes mean that `make build` will now attempt to build all SDKs by default. In the direct build workflow, these builds fail due to missing toolchains. This change restores the behaviour of the workflow by opting out of these sub-builds.
Fixes #20003

Don't build all SDKs in the direct build job

---

sdk/python/Makefile

Other SDK Makefiles have a target for the plugin that corresponds with the binary name. This commit extends the Python Makefile with the same support.
For example, this mirrors Go here:
https://github.com/pulumi/pulumi/blob/ac738adfb8bbb0f5770e8560c8841c407f69c1d1/sdk/go/Makefile#L25-L29

Align the `sdk/python/Makefile` to other SDK Makefiles

---

changelog/pending/20250630--sdk-nodejs--automatic-esm-configuration.yaml
sdk/nodejs/cmd/run/hooks.ts
sdk/nodejs/cmd/run/run.ts
sdk/nodejs/tsconfig.json
tests/integration/integration_nodejs_test.go
tests/integration/nodejs/esm-ts-auto-typecheck/Pulumi.yaml
tests/integration/nodejs/esm-ts-auto-typecheck/index.ts
tests/integration/nodejs/esm-ts-auto-typecheck/package.json
tests/integration/nodejs/esm-ts-auto-typecheck/tsconfig.json
tests/integration/nodejs/esm-ts-auto/Pulumi.yaml
tests/integration/nodejs/esm-ts-auto/index.ts
tests/integration/nodejs/esm-ts-auto/other.ts
tests/integration/nodejs/esm-ts-auto/package.json
tests/integration/nodejs/esm-ts-auto/tsconfig.json

We support native ESM mode (meaning modules are not transpiled to CommonJS, among other things), but it requires some explicit configuration, see https://www.pulumi.com/docs/iac/languages-sdks/javascript/#native-esm-support
With this PR, we attempt to configure everything automatically.
If we detect manual configuration, we fallback to the old code path, to avoid messing with any custom configuration.

Automatic ESM configuration

---

tests/integration/integration_nodejs_test.go
tests/integration/nodejs/ts-type-stripping/Pulumi.yaml
tests/integration/nodejs/ts-type-stripping/main.ts
tests/integration/nodejs/ts-type-stripping/other.ts
tests/integration/nodejs/ts-type-stripping/package.json

Starting with Node.js v23.6.0, types are automatically stripped from .ts
files and we can run without ts-node.
This only adds a properly configured test case. We want to continue
using ts-node by default, as it does typechecking, which is the default
Pulumi behaviour.
Note that versions above v22.6.0 also support a
`--experimental-strip-types` flag to enable this behaviour and users can
opt into that via the `nodeargs` option.
https://nodejs.org/en/learn/typescript/run-natively

Add a test for Node.js's type stripping

---

changelog/pending/20250710--sdk-python--fix--automation-stack-rename.yaml
sdk/python/lib/pulumi/automation/_stack.py

Fix the stack renaming logic in the Python automation API by ensuring the object's name is updated after a rename operation. Also, support None as a valid value for the history attribute when the stack is empty.

[issue-20020] Fix stack rename in python automation api

---

sdk/nodejs/tests/automation/util.ts

This PR ensures that, if you set `PULUMI_TEST_ORG`, the organisation you set will take priority when choosing the organisation for creating stacks in integration tests. We could probably change `pulumi-test` to `moolumi` here to make it fully compatible with Python, but let's not tear down two fences at once.

Prioritise `PULUMI_TEST_ORG` in NodeJS automation tests

---

changelog/pending/20250706--auto-go-nodejs-python--support-run-program-for-inline-programs-in-refresh-and-destroy-operations.yaml
sdk/go/auto/stack.go
sdk/go/auto/stack_test.go
sdk/nodejs/automation/stack.ts
sdk/python/lib/pulumi/automation/_stack.py

Add support for inline programs with `--run-program` for refresh and destroy operations. This required an engine fix to support `--client` for these operations which was released in [3.181](https://github.com/pulumi/pulumi/releases/tag/v3.181.0).

Add inline program support to refresh/destroy

---

changelog/pending/20250714--cli--fix-a-panic-in-the-console-command-when-a-non-existant-stack-was-passed-as-a-stack-argument.yaml
pkg/cmd/pulumi/console/console.go
tests/smoke/smoke_test.go

`GetStack` can potentially return nil if the given stack name isn't found, as opposed to "not found" error.
This wasn't checked for in the console command and later code tried to dereference the stack object to get the string reference for it.
Fixes https://github.com/pulumi/pulumi/issues/20035

Fix panic in console command

---

pkg/engine/lifecycletest/pulumi_test.go

These seem to work, so I guess we can probably switch them on.

Re-enable lifecycle tests on MacOS

---

tests/integration/integration_python_acceptance_test.go

I was looking at this test while looking at https://github.com/pulumi/pulumi/issues/19834, and it looks like I committed some nonsense here when I introduced the test. Supposedly the intention was to call `skip` on non-Windows platforms.

Tidy up TestUvWindowsError

---

pkg/resource/deploy/deploytest/languageruntime.go

Since https://github.com/pulumi/pulumi/pull/19837/files#diff-984b3279d61b588030474831898bb76d093d863ca2d0015bb081d842602a9ab7R841, we're waiting for the program to finish running before shutting the engine down.
This is useful in regular operation, however it introduces a small issue in the lifecycletests.  Because programs can be canceled using by the `require.*` family of functions, we sometimes don't "finish" running the program correctly, if there are test failures.  In those cases, we currently just hang, which makes the tests much harder to debug.  Fix this.
The inline comment describes the issue a bit more carefully.

stop lifecycletests form deadlocking when a `require` fails in the program function

---

changelog/pending/20250716--sdk-nodejs--allow-setting-resource-hooks-in-transforms.yaml
sdk/nodejs/provider/server.ts
sdk/nodejs/runtime/callbacks.ts
sdk/nodejs/runtime/resource.ts
tests/integration/resource_hooks/nodejs_transform/Pulumi.yaml
tests/integration/resource_hooks/nodejs_transform/index.ts
tests/integration/resource_hooks/nodejs_transform/package.json
tests/integration/resource_hooks/nodejs_transform/random.ts
tests/integration/resource_hooks/resource_hooks_nodejs_test.go

With https://github.com/pulumi/pulumi/pull/20051 in place, we can get the hooks from the current resource options inside a transform, and then modify that option.

Allow setting resource hooks in transforms

---

changelog/pending/20250717--sdk-nodejs--fix-before-exit-handler.yaml
sdk/nodejs/cmd/run/index.ts
tests/integration/integration_nodejs_test.go
tests/integration/nodejs/before-exit/Pulumi.yaml
tests/integration/nodejs/before-exit/index.js
tests/integration/nodejs/before-exit/package.json

The aws provider has a handler that creates `BucketNotification` objects in a `beforeExit` handler, see https://github.com/pulumi/pulumi-aws/blob/df45f46766be1d304a5fcf7d6dc192846f7433a8/sdk/nodejs/s3/s3Mixins.ts#L187
`beforeExit` handlers are run in FIFO order, and since we register [ours](https://github.com/pulumi/pulumi/blob/dbfb8f2ccd8b11fb66ccbe5cced5abb324a554f5/sdk/nodejs/cmd/run/index.ts#L84) before the program is loaded, it runs before the AWS provided one. This is problematic, because we call `SignalAndWaitForShutdown` in the handler, but then a resource registration comes in afterwards, which will fail.
To fix this, we employ a bit of a hack to ensure our handler runs last, and in fact only runs after all the async work spawned by the first set of handlers has completed.
A user …

Fix before exit handler

---

changelog/pending/20250623--cli-install-package--allow-using-pulumi-package-add-with-registry-identifiers.yaml
pkg/cmd/pulumi/cmd/registry.go
pkg/cmd/pulumi/convert/convert.go
pkg/cmd/pulumi/install/install.go
pkg/cmd/pulumi/packagecmd/package_add.go
pkg/cmd/pulumi/packagecmd/package_extract_mapping.go
pkg/cmd/pulumi/packagecmd/package_extract_schema.go
pkg/cmd/pulumi/packagecmd/package_gen_sdk.go
pkg/cmd/pulumi/packagecmd/package_info.go
pkg/cmd/pulumi/packagecmd/package_publish.go
pkg/cmd/pulumi/packagecmd/package_publish_test.go
pkg/cmd/pulumi/packagecmd/project_sdk_link.go
pkg/cmd/pulumi/plugin/plugin_install.go
pkg/cmd/pulumi/templates/cloud.go
sdk/go/common/apitype/package.go
tests/smoke/smoke_test.go

> [!IMPORTANT]  
> This feature is experimental, and only enabled when `PULUMI_EXPERIMENTAL=1` is set.
This PR adds support for using `pulumi package add <registry ID>`. As an example:
```sh
pulumi package add opentofu/airbytehq/airbyte
```
```yaml
name: ian-test-python
runtime:
name: python
options:
virtualenv: venv
packages:
airbyte: opentofu/airbytehq/airbyte@0.13.0
random:
source: pulumi/pulumi/terraform-provider
version: 0.11.0
parameters:
- hashicorp/random
- 3.6.3
```
This is compatible with `pulumi install`, which correctly regenerates the SDK for the registry based provider.
Merging this PR will be a bit complicated, due to the inability to update all package loaders at once:
Before this PR, `plugin.IsLocalPluginPath(ctx, "opentofu/airbytehq/airbyte")` returned true. That means …

Support `pulumi package add <registry ID>`

---

changelog/pending/20250718--engine--fix-a-snapshot-integrity-issue-with-destroy-run-program-and-resource-reads.yaml
pkg/engine/lifecycletest/destroy_test.go
pkg/resource/deploy/step_generator.go

Fixes https://github.com/pulumi/pulumi/issues/19363
When running `destroy --run-program` we would do resource reads and add them to state, but then not remove them from state later even though we would have removed their provider.
This fixes GenerateReadSteps to tag these resources as to be deleted when running in destroy mode.

Fix snapshot error with destroy --run-program and resource reads

---

.github/workflows/ci-dev-release.yml
.github/workflows/ci-performance-gate.yml

We have to build the CLI before we can build the matrix because of https://github.com/pulumi/pulumi/pull/19580/files#diff-35f0237533998a7ed8096d74035a0dc62347b33535080d232c14ccfc4e8c270e
Cache the go deps to make this a little faster

Cache go deps when building CI matrix

---

changelog/pending/20250719--sdk-nodejs--dont-use-automatic-esm-mode-when-import-or-require-is-set.yaml
sdk/nodejs/cmd/run/run.ts
tests/integration/integration_nodejs_test.go
tests/integration/nodejs/esm-tsx/Pulumi.yaml
tests/integration/nodejs/esm-tsx/index.ts
tests/integration/nodejs/esm-tsx/other.ts
tests/integration/nodejs/esm-tsx/package.json
tests/integration/nodejs/esm-tsx/tsconfig.json

Similar to how we skip automatic ESM mode when there is a `--loader` flag, skip it in the presence of `--import` or `--require` flags. For example [tsx](https://tsx.is) is often used with `--import tsx`.
Usually we wouldn’t hit this case, because we require a recent version of `ts-node` to activate automatic ESM mode, and when using `tsx` there’s no reason to have `ts-node` explicitly installed. It might still be present though, either directly in `package.json` for some other use, or as an indirect dependency.
This could lead to a setup where code would first run though `tsx`, stripping the types, and then through `ts-node/esm`, which could then potentially fail with a type error since it was now dealing with a lot of `any` and `unknown` types.

Don’t use automatic ESM mode when `--import` or `--require` is set

---

changelog/pending/20250719--sdk-nodejs--avoid-cannot-convert-object-to-primitive-value-error-when-running-into-type-errors.yaml
sdk/nodejs/cmd/run/run.ts
tests/integration/integration_nodejs_test.go

We had a first fix for this in https://github.com/pulumi/pulumi/pull/18080, but I ran into another one of these errors while working on https://github.com/pulumi/pulumi/pull/20091

Avoid "Cannot convert object to primitive value" error when running into type errors

---

changelog/pending/20250707--cli-package--force-new-style-go-modules-to-be-written-out-when-using-package-add.yaml
pkg/cmd/pulumi/packagecmd/package_add.go
tests/integration/packageadd-namespace/provider/schema.json

Fixes https://github.com/pulumi/pulumi/issues/19519
When running `package add` we can always force `SupportPack` to true. This will result in the new style of go module files being written out, which the package add instructions are designed for.
Most uses of `package add` are probably already using schemas that set `SupportPack` (e.g any parameterised things, but also the new component library providers), so this is probably only really going to affect providers written with the Go provider framework, which as per #19519 don't really work currently anyway so risk of breaking anyone seems low.

Force SupportPack on for package add

---

sdk/go/common/apitype/policy.go

Add entity type to policy group summary.
Used for showing new split between account/stack policy groups

policy summary apitype entity type

---

changelog/pending/20250723--cli-engine--exclude-and-exclude-protected-flags-now-work-together-correctly-for-destroy-commands.yaml
pkg/cmd/pulumi/operations/destroy.go
tests/integration/integration_test.go

Previously, `--exclude-protected` was sugar over `--target`, which caused problems when used with `--exclude`. This PR makes `--exclude-protected` sugar over `--exclude`, and thus the two can be mixed together additively.
Fixes #19231.

Make `--exclude-protected` sugar over `--exclude`

---

tests/testdata/codegen/schema/provider-methods-1.json
tests/testdata/codegen/schema/provider-methods-2.json
tests/testdata/codegen/schema/provider-methods-3.json

Raised by a customer that some providers were using "#/resources/pulumi:providers:pkg" instead of just "#/provider". Which looks odd as a JSON ref because "resources/pulumi:providers:pkg" wouldn't have been a path to valid object in the json document.
We have these tests using that odd format, but they pass just fine using the "#/provider" style, so lets fix them up as a first step to sanitizing things here.

Use #/provider rather than #/resources/pulumi:providers:pkg

---

cmd/pulumi-test-language/interface.go
pkg/backend/diy/backend_legacy_test.go
pkg/backend/diy/backend_test.go
pkg/cmd/pulumi/stack/io.go
pkg/cmd/pulumi/stack/stack_change_secrets_provider.go
pkg/cmd/pulumi/stack/stack_change_secrets_provider_test.go
pkg/cmd/pulumi/stack/stack_export.go
pkg/cmd/pulumi/state/io.go
pkg/cmd/pulumi/state/state_move_test.go
pkg/cmd/pulumi/state/state_repair.go
pkg/resource/stack/deployment.go
tests/integration/backend/diy/backend_postgres_test.go
tests/stack/stack_test.go
tests/stack/testdata/html_escape/Pulumi.yaml
tests/stack/testdata/html_escape/index.ts
tests/stack/testdata/html_escape/package.json

This change adds a new helper function for serializing a snapshot to an untyped deployment. This reduces duplication in preparation for writing version 4 when certain features are used, which will come in a subsequent change.
Part of https://github.com/pulumi/pulumi/issues/19705

Add `SerializeUntypedDeployment` helper

---

changelog/pending/20250724--cli--stop-passing-accept-application-x-tar-to-registry-template-download-urls-to-avoid-signature-mismatch.yaml
pkg/backend/httpstate/client/client.go
pkg/backend/httpstate/client/client_template_test.go

Stop passing `Accept: application/x-tar` and other headers to registry template download URLs to avoid signature mismatch.
Example error this fixes:
```
~/Development/cli-deployment-test λ PULUMI_EXPERIMENTAL=1 ~/go/src/github.com/pulumi/pulumi/bin/pulumi new csharp-documented
error: failed to download from "https://blobs-fnune-review.review-stacks.pulumi-dev.io/private-registry/templates/d5c13739-d452-46d5-a978-1bd79b022439/archive.tar.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=reviewStacksSecretRootUser%2F20250721%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250721T152124Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&X-Amz-Signature=50cf2d9cf4e2a5164122c07b4bb7085a3314d58b59987c482a9fbde9a0ffd27d": [403] <?xml version="1.0" encoding="UTF-8"?> …
```

Fix registry template downloads by not passing custom headers

---

changelog/pending/20250725--sdk-nodejs--fix-delete-hooks-in-inline-automation-api-programs.yaml
sdk/nodejs/automation/server.ts
sdk/nodejs/cmd/run/index.ts
sdk/nodejs/runtime/settings.ts
sdk/nodejs/tests/automation/localWorkspace.spec.ts

The inline automation API language runtime needs to call `SignalAndWaitForShutdown` when the program completes.
Note that for inline programs the lifetime of the program is tied to the program function execution. When the program function returns, we wait for any queued work and then shutdown. Work that gets queued later will not be executed (or might if it manages to race the shutdown), see https://github.com/pulumi/pulumi/issues/20114. This is different from "normal" Pulumi programs, where the lifetime is that of the Node.js process. This is *not* a change in this PR, but we do rely on this existing behaviour for delete hooks.

Fix delete hooks in inline automation API programs

---

tests/integration/nodejs/promise-message/index.js

I saw this flake. I assume what’s happening is that it took too long to go through our exit handlers on an overloaded CI run.

Fix flake in TestNodejsPromiseMessage

---

changelog/pending/20250724--yaml--config-values-can-now-be-parsed-with-type-object.yaml
sdk/go/common/workspace/project.go
sdk/go/common/workspace/project_test.go

In #20129, we added `object` as a type that may be used for `config` in `Pulumi.yaml`. This PR ensures that we are able to parse objects into this new type.

Support parsing object types in `Pulumi.yaml`

---

changelog/pending/20250725--sdk-nodejs--bump-typescript-target-to-es2020-for-plugins-and-policy-packs.yaml
sdk/nodejs/cmd/run-plugin/run.ts
sdk/nodejs/cmd/run-policy-pack/run.ts

We updated this for the program entrypoint in https://github.com/pulumi/pulumi/pull/19980/files#diff-56150bcb0a988cc1b28983a197010bbca7a34e91910a23c5062aee074e8164b6R366
The minimum version of TypeScript we support (and ship a vendored version of) is 3.8, which supports ES 2020.

Bump TypeScript target to ES2020 for plugins and policy packs

---

pkg/backend/display/progress.go
pkg/backend/display/rows.go

This bool variable can be accessed from a different goroutine than the one it is written in, and reading it can thus be racy.  Fix this race by using an atomic bool instead, which is safe from races.
Fixes https://github.com/pulumi/pulumi/issues/20156
Fixes https://github.com/pulumi/pulumi/issues/20126

display: make done an atomic bool

---

pkg/go.mod
pkg/go.sum
tests/go.sum

This addresses a dependabot alert: https://github.com/advisories/GHSA-4vq8-7jfc-9cvp

Update moby/moby dependency to v28.3.3

---

changelog/pending/20250730--sdk-python--copy-get_root_directory-to-the-pulumi-module.yaml
pkg/codegen/python/gen_program_expressions.go
sdk/python/cmd/pulumi-language-python/testdata/classes/projects/l1-builtin-project-root/__main__.py
sdk/python/cmd/pulumi-language-python/testdata/setuppy/projects/l1-builtin-project-root/__main__.py
sdk/python/cmd/pulumi-language-python/testdata/toml/projects/l1-builtin-project-root/__main__.py
sdk/python/lib/pulumi/__init__.py
sdk/python/lib/pulumi/metadata.py

This got added back in https://github.com/pulumi/pulumi/pull/18595 but you had to use it via `pulumi.runtime.get_root_directory()`. There isn't really anything else that we expect users to look at in the runtime module, so this copies it to the root pulumi module so it's now just `pulumi.get_root_directory()`.

Add get_root_directory to root pulumi module

---

changelog/pending/20250716--cli--support-for-writing-v4-checkpoints-deployments.yaml
pkg/backend/diy/backend.go
pkg/backend/diy/state.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/backend_test.go
pkg/backend/httpstate/client/client.go
pkg/backend/httpstate/client/client_test.go
pkg/backend/httpstate/diffs.go
pkg/backend/httpstate/snapshot.go
pkg/backend/httpstate/snapshot_test.go
pkg/backend/httpstate/testdata/snapshot_test.json
pkg/resource/stack/checkpoint.go
pkg/resource/stack/checkpoint_test.go
pkg/resource/stack/deployment.go
pkg/resource/stack/deployment_test.go
sdk/go/common/apitype/service.go
sdk/go/common/apitype/service_test.go

This change adds support for writing checkpoints/deployments with a schema version of 4 when the following features are used: refreshBeforeUpdate, views, or hooks. Otherwise, version 3 will continue to be used.
If the service doesn't support v4 deployment schemas, v3 will continue to be used.
Fixes https://github.com/pulumi/pulumi/issues/19705

Support writing v4 checkpoints/deployments

---

pkg/engine/lifecycletest/framework/framework.go

I ran into this while working on https://github.com/pulumi/pulumi/pull/20174. Testify returns the whole stack trace rather than just showing the log, which is often useful to see what actually failed.  Use that framework here consistently, so we get better test output.
There's also a bug here, where we don't fail if we encounter an event we don't expect, so fix that as well.

use the testify framework more in lifecycletests

---

pkg/codegen/testing/test/helpers.go
scripts/get-language-providers.sh

In preparation for the 3.187.0 release.
(https://github.com/pulumi/pulumi-dotnet/pull/678 still needs to merge before we can do this)

update versions of language providers

---

changelog/pending/20250801--sdkgen--warn-about-refs-of-the-form-resources-pulumi-providers-pkg.yaml
pkg/codegen/schema/bind.go
pkg/codegen/schema/schema_test.go

Part of fixing https://github.com/pulumi/pulumi/issues/20029
This makes schema binding warn when finding references of the form "#/resources/pulumi:providers:<pkg>", instructing that the user should rewrite them to the form "#/provider".

Warn on refs of the form "#/resources/pulumi:providers:<pkg>"

---

changelog/pending/20250801--cli-env--bump-esc-to-v0-17-0.yaml
cmd/pulumi-test-language/go.mod
cmd/pulumi-test-language/go.sum
pkg/go.mod
pkg/go.sum
sdk/go.mod
sdk/go.sum
sdk/go/pulumi-language-go/go.mod
sdk/go/pulumi-language-go/go.sum
sdk/nodejs/cmd/pulumi-language-nodejs/go.mod
sdk/nodejs/cmd/pulumi-language-nodejs/go.sum
sdk/python/cmd/pulumi-language-python/go.mod
sdk/python/cmd/pulumi-language-python/go.sum
tests/go.mod
tests/go.sum
tests/integration/construct_component_configure_provider/testcomponent-go/go.mod
tests/integration/construct_component_configure_provider/testcomponent-go/go.sum
tests/integration/construct_component_provider_propagation/go/go.mod
tests/integration/construct_component_provider_propagation/go/go.sum
tests/integration/construct_component_resource_options/go/go.mod
tests/integration/construct_component_resource_options/go/go.sum
tests/integration/construct_nested_component/go/go.mod
tests/integration/construct_nested_component/go/go.sum

ESC Approvals ([--draft CLI option for various commands](https://github.com/pulumi/esc/releases/tag/v0.17.0)) moved out of preview today with public announcements coming Monday. 
It would be great to get this out in an upcoming release so that esc within the pulumi CLI stays fairly up to date.

Bump esc to v0.17.0

---

pkg/engine/update.go

This is not used elsewhere, let’s make it private.

Make shouldRecordReadStep private

---

pkg/engine/lifecycletest/continue_on_error_test.go
pkg/engine/lifecycletest/golang_sdk_test.go
pkg/engine/lifecycletest/provider_test.go
pkg/engine/lifecycletest/refresh_legacy_diff_test.go
pkg/engine/lifecycletest/refresh_test.go
pkg/engine/lifecycletest/resource_reference_test.go
pkg/engine/lifecycletest/target_test.go
pkg/resource/deploy/builtins.go
pkg/resource/deploy/deploytest/provider.go
pkg/resource/deploy/step.go
sdk/go/common/resource/plugin/provider_plugin.go

Prompted by https://github.com/pulumi/pulumi/issues/20186
The logic that `ID=""` should be treated as a delete was squeezed into the grpc layer by setting outputs to nil if ID was blank.
This PR moves that logic up to the refresh step, so it's consistent across all lifecycle tests. A number of tests and the builtin provider needed updating for this.

Move ID="" logic from grpc layer to refresh step

---

changelog/pending/20250805--engine--fix-panic-in-refreshes-due-to-concurrent-map-writes.yaml
pkg/resource/deploy/step_generator.go

Fixes https://github.com/pulumi/pulumi/issues/20194
This code is called in a goroutine, potentially in parallel with other calls. Lock around it to prevent `fatal error: concurrent map writes` errors from happening.

Add lock around depGraph.Alias

---

changelog/pending/20250806--cli--restore-terminal-mode-on-panic.yaml
pkg/backend/display/progress.go

Pulumi sets the terminal to raw mode, and on exit restores the terminal to its previous state. However when we crash due to a panic, we don’t restore the state.
By deferring the `Close` call, we’ll call the terminal’s `Close` method when we panic.
This only works if the panic comes from the same goroutine as the display code. If we panic in another goroutine, we won’t call the deferred method, and we still won't restore the state.

Restore terminal mode on panic

---

changelog/pending/20250806--sdk-python--fix-dependency-installation-in-uv-workspaces.yaml
sdk/python/toolchain/uv.go
tests/integration/integration_python_acceptance_test.go
tests/integration/python/uv-workspace/infra/projects/some-project/Pulumi.yaml
tests/integration/python/uv-workspace/infra/projects/some-project/__main__.py
tests/integration/python/uv-workspace/infra/projects/some-project/pyproject.toml
tests/integration/python/uv-workspace/infra/pyproject.toml
tests/integration/python/uv-workspace/packages/some-package/pyproject.toml
tests/integration/python/uv-workspace/packages/some-package/src/some_package/__init__.py

Since https://github.com/pulumi/pulumi/pull/20117 we run `uv sync` for any Python command to get closer to the behaviour of  `uv run python`. However `uv run` does an inexact sync by deafult, so we need to run with the `--inexact` flag.
This could lead to dependencies being removed from the virtualenv if they were assumed to be implicitly available via the workspace.
Fixes https://github.com/pulumi/pulumi/issues/20185

Fix dependency installation in uv workspaces

---

changelog/pending/20250810--sdk-nodejs--fix-swapped-stderr-stdout-callback-comments-in-previewoptions-interface.yaml
sdk/nodejs/automation/stack.ts

Fixes #20246
This PR corrects the swapped documentation comments for `onOutput` and `onError` callbacks in the `PreviewOptions` interface.

Fix swapped stderr/stdout comments in PreviewOptions interface

---

changelog/pending/20250808--engine--fix-race-when-reading-plugin-stdout.yaml
sdk/go/common/resource/plugin/plugin.go

When running a binary plugin we use `cmd.Stdout/StderrPipe` to get the output from the binary. These pipes have internal goroutines that copy the data around, and when the process exits, the pipes are closed. An important caveat when using these pipes is that you must read all the data from the pipe before `cmd.Wait()` is called, otherwise you will miss data.
From the documentation https://pkg.go.dev/os/exec#Cmd.StdoutPipe:
> It is thus incorrect to call Wait before all reads from the pipe have completed
However, ExecPlugin returns an already started plugin and runs a goroutine that waits for the plugin to exit:
```go
go func() {
err := cmd.Wait()
wait.Reject(err)
} else {
wait.Fulfill(struct{}{})
}
}()
```
If a plugin exits very quickly, this can lead to us trying to read …

Fix race when reading plugin stdout

---

changelog/pending/20250807--auto-python--add-json-option-to-preview-in-python-pulumi-automation-add-flag-to-obtain-json-output-when-running-preview-using-python-automation-bindings.yaml
sdk/python/lib/pulumi/automation/_stack.py
sdk/python/lib/test/automation/test_local_workspace.py

Add flag to obtain JSON output when running preview using Python automation bindings.

Add `json` option to preview in Python `pulumi.automation`.

---

pkg/resource/deploy/deploytest/sink.go
sdk/go/common/diag/sink.go
sdk/go/common/diag/sink_test.go

While the Stringify function is used, and both real implementations of Sink have a Stringify function, there wasn't anything that made use of the fact that it was on the interface. 
Remove it from the interface so we now have a simpler interface that will be easier to write a mock type around. As opposed to the old TestSink which had to embed the defaultSink in it just to get access to Stringify.

Remove Stringify from Sink interface

---

docs/architecture/deployment-execution/state.md

While I was looking into documenting journaling, I realized we don't seem to have any documentation of the current system either.  Add a little of that, which will maybe make journaling and its challenges a little easier to understand.

add a little documentation of the current snapshot system

---

sdk/go/pulumi-language-go/main.go

Noticed this error in CI somewhere today.  I suspect it's because of network errors, but hard to tell without more information.  Using `errutil.ErrorWithStderr` should help with making this easier to read in the future.

use ErrorWithStderr for `go mod tidy` errors

---

pkg/cmd/pulumi/operations/preview.go

Per https://github.com/pulumi/docs/pull/15698 and [the GA blog post](https://www.pulumi.com/blog/announcing-public-preview-update-plans/) `save-plan` is no longer experimental. The label can be removed and flag unhidden.

Remove experimental label & unhide save-plan

---

pkg/engine/lifecycletest/alias_test.go
pkg/engine/lifecycletest/delete_before_replace_test.go
pkg/engine/lifecycletest/import_test.go
pkg/engine/lifecycletest/pending_delete_test.go
pkg/engine/lifecycletest/provider_test.go
pkg/engine/lifecycletest/pulumi_test.go
pkg/engine/test_journal.go

In #20199 we refactored the test journal to be named like that, but we didn't rename the internal names of constants and structs and types. Do that now, to avoid conflicts in subsequent refactorings. (In particular for https://github.com/pulumi/pulumi/pull/19862#discussion_r2257736913)

rename JournalEntry to TestJournalEntry in test_journal.go

---

changelog/pending/20250815--cli--fix-pulumi-template-publish-failing-with-relative-paths-by-normalizing-to-absolute-paths-before-archive-creation.yaml
pkg/cmd/pulumi/templatecmd/template_publish.go
pkg/cmd/pulumi/templatecmd/template_publish_test.go

When using relative paths other than `.`, like `./template-dir`, the archive creation would nest files under the directory name (e.g., `template-dir/Pulumi.yaml`) instead of at the archive root. The backend expects `Pulumi.yaml` at the root level, causing publish to fail with "archive is missing Pulumi.yaml file".
Resolve this by converting the template directory path to an absolute path before creating the archive, ensuring consistent archive structure regardless of whether relative or absolute paths are used.
Example failure output:
```sh
~/Development λ pulumi template publish ./registry-backed-templates-demo --name registry-backed-templates-demo --version 0.0.0
Creating archive from directory: ./registry-backed-templates-demo
Publishing template …
```

Fix template publish with relative paths other than '.'

---

changelog/pending/20250811--cli-new--dont-prompt-for-ai-or-template-when-passing-yes.yaml
pkg/cmd/pulumi/newcmd/new_acceptance_test.go
pkg/cmd/pulumi/newcmd/new_ai.go
pkg/cmd/pulumi/newcmd/new_test.go
pkg/cmd/pulumi/newcmd/template.go

Picks up the work in https://github.com/pulumi/pulumi/pull/19414 
Default to picking a template over ai mode when running `pulumi new --yes`.
This also tweaks the error message when new template name or url is provided when running in non-interactive mode.
Fixes https://github.com/pulumi/pulumi/issues/19378

Don't prompt for ai or template when passing --yes

---

pkg/engine/deployment.go
pkg/engine/destroy.go
pkg/engine/engine.go
pkg/engine/import.go
pkg/engine/lifecycletest/framework/framework.go
pkg/engine/plugins.go
pkg/engine/refresh.go
pkg/engine/update.go

These changes add a PluginManager interface to `pkg/engine` that is used
to abstract interactions with installed plugins. This allows the
lifecycle test framework to supply an implementation of the plugin
manager that does no I/O and always treats all plugins as installed. This
could also be used to improve test coverage for `EnsurePluginsAreInstalled`.

engine: add a PluginManager interface

---

changelog/pending/20250820--cli--log-version-and-cli-metadata.yaml
pkg/cmd/pulumi/pulumi.go

When looking through logs, it is useful to know which version of the CLI was used, or which command was run. To help with this, when running with verbose logging, we now output the version of the CLI and metadata about the command being run, such as the command & flags, as well as any `PULUMI_` env variables. This does not include any potentially sensitive information like flag or env variable values, only their names.
Example output:
```
I0820 10:18:09.751839   99698 pulumi.go:290] Pulumi 3.191.0-dev.0
I0820 10:18:09.753023   99698 pulumi.go:293] CLI Metadata: map[Command:pulumi up Environment:PULUMI_TEST_ORG PULUMI_CONFIG_PASSPHRASE Flags:--diff --refresh --run-program --skip-preview --verbose
```

Log version and CLI metadata

---

changelog/pending/20250820--programgen--emit-warnings-instead-of-erros-in-non-strict-mode-when-binding-resource-blocks.yaml
pkg/codegen/pcl/binder_resource.go

Separate PR for https://github.com/pulumi/pulumi/pull/20345 specifically for turning errors into warnings in non-strict mode

Emit warnings instead of erros in non-strict mode when binding resource blocks

---

changelog/pending/20250820--programgen--simplify-range-value-types-when-it-is-derived-from-object-of-objects-and-warn-on-unknown-properties.yaml
pkg/codegen/hcl2/model/type_collection.go
pkg/codegen/pcl/binder_resource.go
pkg/codegen/pcl/binder_test.go

Fixes the type-checking issue of https://github.com/pulumi/pulumi-converter-terraform/issues/373 making CLI more resilient when encountering programs of that try to traverse an object of objects and then indexing a non-existent key 😓 
Part of the problem is that when traversing an object of objects shaped like this 
```
accounts = {
"us-east-1" = {
awsRegion = "us-east-1"
something = 10
}
"us-west-2" = {
awsRegion = "us-west-2"
something = 20
}
"eu-west-1" = {
awsRegion = "eu-west-1"
something = 30
}
}
```
When such object is used in a `range` expression of a resource, then we try to extract the `rangeKey` and `rangeValue` types of the collection being iterated. In the case of the above the `rangeValue` is computed to be a union of all the objects types in the map `union(object1, object2, …

[PCL] Simplify range value types when it is derived from object of objects and warn on unknown properties

---

pkg/backend/display/events.go
pkg/engine/events.go

We deepcopy engine events when creating them, but our deepcopy code doesn't support errors.  ErrorEvents would thus always end up empty. Fix this by making the payload a string instead.
Noticed this while testing the journaling code.

make ErrorEventPayload a string

---

pkg/resource/deploy/source_eval.go

Add the debug labels when marshalling or unmarshalling in callbacks.

Add labels to MarshalOptions for callbacks

---

changelog/pending/20250821--cli--log-stack-trace-when-interrupted-when-using-verbose-logging.yaml
pkg/backend/cancellation_scope.go

When logging at level 9 and above, grab a stack trace for all goroutines when we get interrupted. This can be helpful when debugging a hang.
For example this snippet is from a run that has a transform that's hanging:
```
I0821 20:19:32.155779   91857 cancellation_scope.go:79] github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*resmon).wrapTransformCallback.func1({0x10737e420, 0x140006b4d50}, {0x106bca008, 0x1}, {0x14001f00240, 0x15}, 0x1, {0x14001c5e8c0, 0x37}, 0x140006b4ea0, ...)
I0821 20:19:32.155782   91857 cancellation_scope.go:79] 	/Users/julien/Projects/pulumi/pulumi/pkg/resource/deploy/source_eval.go:1496 +0x3e4
I0821 20:19:32.155788   91857 cancellation_scope.go:79] github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*resmon).RegisterResource(0x140021021e0, {0x10737e420, …
```

Log stack trace when interrupted when using verbose logging

---

pkg/testing/integration/program_test.go

These changes fix TestGoModEdits to account for the fact that the
worktree for the `github.com/pulumi/pulumi` repository may not be
located at a path that terminates in `pulumi`. In that case,
`getEditStr` resolves the replacement path to different locations
depending on whether or not the module being replaced uses a relative
path.

[testing] Fix TestGoModEdits for alt worktrees

---

changelog/pending/20250821--cli--print-the-location-of-the-log-file-when-running-with-the-verbose-flag.yaml
pkg/cmd/pulumi/pulumi.go
sdk/go/common/util/logging/log.go
tests/smoke/smoke_test.go

Make it easier to find the log file when running with `-vN` by printing the path at the end of the command run.

Print the location of the log file when running with the verbose flag

---

pkg/engine/lifecycletest/provider_test.go
sdk/go/common/resource/plugin/provider_server.go

This was missing the propogation of the DeletedWith option on the server side.

Fix TestDeletedWithOptionInheritanceMLC to pass with grpc providers

---

changelog/pending/20250822--sdk-nodejs--add-previewdestroy-to-allow-dry-runs-of-destroy-commands.yaml
sdk/nodejs/automation/stack.ts
sdk/nodejs/tests/automation/localWorkspace.spec.ts

Continuing in the steps of #19900, #19948, and so on, this PR adds the `previewDestroy` command and deprecates the `--preview-only` flag in the `destroy` command. The reason is that `destroy` (like `refresh`) uses the event log to figure out what was affected by a change. However, preview commands don't generate event logs, so you instead get the results of whatever the _previous_ change was. This PR special-cases this preview behaviour to avoid the bug.

Add `previewDestroy` to the NodeJS SDK

---

sdk/python/lib/pulumi/runtime/invoke.py
sdk/python/lib/pulumi/runtime/resource.py
sdk/python/lib/pulumi/runtime/settings.py

This always raises an exception, so the correct return type is `NoReturn`.
Edit: `Never` was added in 3.11, use `NoReturn` instead, which is equivalent but more idiomatic for function returns https://typing.python.org/en/latest/spec/special-types.html#never

Improve types for handle_grpc_error

---

changelog/pending/20250821--sdk-go--fix-source-position-information.yaml
sdk/go/pulumi/context.go

- Per the docs, `Frame.File` is always `/`-separated. Split it
correctly.
- The `Uri` property of each reported source position should have the
`file` scheme, not the `project` scheme. The engine will perform the
`file`->`project` mapping.
- Pull the frame -> position mapping out into its own function

[sdk/go] Source position tweaks

---

pkg/engine/lifecycletest/import_test.go

Grpc doesn't send nil maps, just empties, so a couple of expected values needed fixing in this test when running on grpc.

Fix TestImportOption to work with grpc

---

pkg/codegen/hcl2/model/diagnostics.go

This test is sometimes flaky because the array of unknown properties is not sorted, and can appear in different orders.
The test fails with:
```
Error:      	"unknown property 'aws_region' among [something awsRegion]" does not contain "unknown property 'aws_region' among [awsRegion something]"
```
We go for the simple fix here, just sorting that array, as it should always be cheap enough to do so, and is the best way to fix the test.
noticed in https://github.com/pulumi/pulumi/actions/runs/17270052509/job/49012394297?pr=20403.
Fixes https://github.com/pulumi/pulumi/issues/20406

fix flaky TestRangeTraversalFromObjectOfObjectsDoesNotError

---

docs/contributing/development.md

The mise configuration uses Go package installation, this is still experimental and requires a flag to be enabled:
https://mise.jdx.dev/dev-tools/backends/go.html
I've updated the documentation to show how to enable it either with a setting or an environment variable. I'll keep an eye on if this changes and remove it later. 
Question: 
Happy with me not linking the reference here?

update mise guide to show enabling experimental mode

---

pkg/cmd/pulumi/config/config.go

In `pulumi config set`, `--` can be used to disambiguate values that look like flags, iow, they have the format `--<value>`.  Make this clear in the usage string.  Note that this means flags should be set before the `--`, so move the `[flags]` part earlier in the usage string as well.
Fixes https://github.com/pulumi/pulumi/issues/20434

improve usage string for pulumi config set

---

changelog/pending/20250903--cli-display--replace-ijc-gotty-terminfo-package-with-xo-terminfo.yaml
cmd/pulumi-test-language/go.mod
cmd/pulumi-test-language/go.sum
pkg/backend/display/diff_test.go
pkg/backend/display/internal/terminal/info.go
pkg/backend/display/internal/terminal/mock.go
pkg/backend/display/internal/terminal/simple.go
pkg/backend/display/progress_test.go
pkg/go.mod
pkg/go.sum
tests/go.mod
tests/go.sum

The `github.com/ijc/Gotty` package doesn't know how to load the terminfo file on macOS (or FreeBSD), so we were always using the fallback paths on these systems (and on Windows, because terminfo is not a thing there).
The tests run with `TERM=vt102`, and the escape codes for some operations are different from those in the fallback paths, so the golden files are inconsistent. Now that we can correctly load the terminfo file, we get consistent behaviour in the tests when running on Linux and macOS.
Ref https://github.com/pulumi/pulumi/issues/19675

Replace terminfo package

---

changelog/pending/20250903--cli-package--fix-not-using-already-installed-package-in-pulumi-package-add-when-pulumi_experimental-1.yaml
pkg/cmd/pulumi/packagecmd/project_sdk_link.go
pkg/cmd/pulumi/packageresolution/package_resolution.go
pkg/cmd/pulumi/packageresolution/package_resolution_test.go
pkg/cmd/pulumi/plugin/plugin.go
pkg/cmd/pulumi/plugin/plugin_install.go
tests/smoke/smoke_test.go

If a package is already installed, we should always default to using it instead of resolving to some other package. Otherwise, in this sequence:
```
e.RunCommand("pulumi", "plugin", "install", "resource", "terraform-provider", "0.3.1")
e.RunCommand("pulumi", "package", "add", "terraform-provider", "hashicorp/random", "3.6.3")
```
The second command will run the package resolver and try to install the latest-available version of `terraform-provider`, which may not be `0.3.1` (in the case of our tests, it was `0.13.0`).
:information_source: Using the already-installed version is in conformance with previous behavior of `pulumi package add`. See this issue for a wider exploration: https://github.com/pulumi/pulumi/issues/20450
Fixes https://github.com/pulumi/pulumi/issues/20441
Should …

Fix not using already-installed package when PULUMI_EXPERIMENTAL=1

---

changelog/pending/20250904--sdk-go--show-a-message-that-the-go-program-is-being-compiled.yaml
sdk/go/pulumi-language-go/main.go
sdk/go/pulumi-language-go/main_test.go

It can take a while to compile large Go programs, especially if the go tooling has to download dependencies. Show a message so that the user knows what’s happening and it doesn’t look like a stuck program.
Fixes https://github.com/pulumi/pulumi/issues/19672
https://github.com/user-attachments/assets/52477cb5-f096-489d-8911-7dba0e8fa112

Show a message that the Go program is being compiled

---

changelog/pending/20250905--cli-display--change-the-default-for-show-full-output-from-true-to-false.yaml
pkg/cmd/pulumi/operations/destroy.go
pkg/cmd/pulumi/operations/preview.go
pkg/cmd/pulumi/operations/up.go

The flag was fixed in https://github.com/pulumi/pulumi/pull/20464 to apply to resource & stack outputs, and to work for `preview` and `destroy`.
Flip the default to false. Long text lines will now be truncated to 150 characters or 3 lines. Use `--show-full-output=true` to get back the old behaviour.

Change the default for --show-full-output from true to false

---

sdk/go/auto/cmd.go
sdk/nodejs/automation/cmd.ts
sdk/python/lib/pulumi/automation/_cmd.py

When initializing the PulumiCommand object, we need to load the CLI version.
By default, this will also perform an update check and print a warning if out of date. In this context, the warning will not be displayed, but the addional network call will slow down construction of workspaces etc.
Therefore, this is a small optimization to disable the update check for this command.

Skip update check on command init

---

changelog/pending/20250917--components-python--fix-parenting-of-python-components.yaml
sdk/python/lib/pulumi/provider/experimental/server.py
sdk/python/lib/pulumi/provider/server.py
sdk/python/lib/pulumi/resource.py
tests/integration/component_provider/nodejs/component-provider-host/nodejs-npm/index.ts
tests/integration/component_provider/nodejs/component-provider-host/nodejs-pnpm/index.ts
tests/integration/component_provider/nodejs/component-provider-host/python/__main__.py
tests/integration/component_provider/python/component-provider-host/nodejs/index.ts
tests/integration/component_provider/python/component-provider-host/python/__main__.py
tests/integration/integration_nodejs_test.go
tests/integration/integration_python_test.go

The server code for python components had it's if condition flipped for applying parents. That is if the URN was non-empty it ignored it, and if it was empty it tired to construct a dependency resource with an empty URN.
This fixes the condition and changed the component tests to show parenting works.
Fixes https://github.com/pulumi/pulumi/issues/20507

Fix parents in python components

---

pkg/resource/stack/deployment.go
pkg/resource/stack/deployment_test.go

When serializing resources with secrets, we use the `SerializePropertyValue` function, which internally uses `apitype.SecretV1` to represent secrets.  However the corresponding `DeserializePropertyValue` function only supports
`map[string]any`. This works currently because we usually roundtrip these property values through the backend, and deserializing from JSON we get the `map` value back, even when we originally serialized a `SecretV1`.
In subsequent PRs we want to introduce serializing and deserializing of resources within the CLI, so deserializing a `SecretV1` needs to work. Make that so. The alternative would be to just return a map from `SerializePropertyValue`, but that seems worse than using the proper types where we can.
The serializing and deserializing within the CLI comes …

make roundtripping serialized resources with secrets work

---

sdk/go/common/resource/config/map.go
sdk/go/common/resource/config/object.go
sdk/go/common/resource/config/plaintext.go
sdk/go/common/resource/config/value.go

These changes rename adjustObjectValue to coerceObject and clarify its
documentation and logic. This refactoring is not a behavioral change.

[config] Clarify string coercion

---

changelog/pending/20250918--engine--expand-snapshot-integrity-check-for-resources.yaml
pkg/cmd/pulumi/state/state_rename_test.go
pkg/cmd/pulumi/state/state_repair_test.go
pkg/engine/lifecycletest/import_test.go
pkg/engine/lifecycletest/target_test.go
pkg/resource/deploy/snapshot.go
pkg/resource/deploy/snapshot_test.go

When [deserializing resources](https://github.com/pulumi/pulumi/blob/f5953999c151ea354a448c5f641c5cc37b33d2f3/pkg/resource/stack/deployment.go#L651-L661), we currently check some properties of resources, e.g. that it has a URN, a type, and that component resources have no ID.
However we currently don't check the same when verifying snapshot integrity.  This means we could pass a snapshot integrity check, and send the snapshot to the backend, but could then fail to derserialize the snapshot.  Fix this by expanding the snapshot integrity check, and fixing up the tests that violate these checks.
I'm a little scared of the `VerifyIntegrity` changes, since it could be that we get more snapshot integrity errors from this, although I *think* users should already be getting deserialization errors …

expand snapshot integrity check to check that resources are well formed

---

tests/integration/integration_test.go

The first message argument to Failf is an unformatted message.

Fix failure message in TestRunningViaCLIWrapper

---

changelog/pending/20250922--sdk--fix-plugin-killing-during-cancellation.yaml
sdk/go/common/resource/plugin/plugin.go
tests/integration/integration_test.go
tests/integration/interrupt/program/index.js
tests/integration/interrupt/provider/__main__.py

`TestRunningViaCLIWrapper` tests cancellation via `Ctrl-C/SIGINT`. The test was broken in two ways:
* `pulumi package add ...` runs the component provider and then shuts it down normally. This sends a `SIGINT` to the plugin, so it creates the `interrupted.txt` sentinel file.
* The program did not actually use the provider, so during the update operation we didn’t start the component provider.
Fixing the test by removing the `interrupted.txt` created during `pulumi package add`, and creating a component in the program revealed a bug in how we shutdown plugins.
Plugins are first sent a `SIGINT`. If the plugin does not terminate within 5 seconds, we send a SIGKILL. However if the operation is cancelled, the `context.Context` created for the 5 second timeout was parented to a cancelled …

Fix plugin killing during cancellation

---

pkg/backend/journal.go
pkg/backend/journaler_snapshot_test.go
pkg/engine/journal_snapshot.go
pkg/resource/deploy/snapshot.go

Currently in the journal implementation we only made copies of the old snapshot, but then added new resources without copying them.  This meant that the engine was still updating pointers, which is not what we want, as that doesn't translate to the service.
Make the journal make copies of new entries as well to avoid this.
This reveals a few places where we were still relying on the pointers
of resources for correct operation of the journal. This commit fixes
them. In particular:
- It's possible that new resources are later marked as
Delete/PendingReplacement, so we need to split those fields out into
DeleteNew/DeleteOld and PendingReplacementNew/PendingReplacementOld.
- RegisterResourceOutputs always piggybacks on a step that has already
happened, as there is no special step for it. This …

copy new resources as well as old ones

---

pkg/cmd/pulumi/config/config_env_init_test.go

This PR changes the config_env_init_test so that it uses a hardcoded config instead of roundtripping using Plaintext and Encrypt.
This reduces high coupling to Plaintext which is not relevant for the actual test and removes the Encrypt dependency.

Use hardcoded config in config_env_init_test

---

changelog/config.yaml
changelog/pending/20250919--cli-policy--send-vcs-metadata-when-publishing-policy-packs.yaml
pkg/backend/httpstate/client/client.go
pkg/backend/httpstate/client/client_publish_policy_pack_test.go
pkg/backend/httpstate/policypack.go
pkg/backend/policypack.go
pkg/cmd/pulumi/metadata/metadata.go
pkg/cmd/pulumi/policy/policy_publish.go
pkg/cmd/pulumi/policy/policy_publish_test.go
sdk/go/common/apitype/policy.go

When publishing a policy pack, include vcs metadata (i.e. git source location), so tools like Neo know where the source of a policy pack lives. The vcs metadata is the same metadata that's sent as part of Pulumi operations like `pulumi up`.
Fixes #20516

Send vcs metadata when publishing policy packs

---

changelog/pending/20250930--cli-about-new--add-environment-variables-to-pulumi-new-pulumi-about-env.yaml
sdk/go/common/env/env.go
sdk/go/common/workspace/templates.go
sdk/go/common/workspace/templates_test.go

Adding support for configuring the templates directory from env variables so that smoke tests can run from a separate git repository

feat: Adding support for configuring the templates directory from env vars

---

Makefile

When running `make lint`, I usually want to see all issues at once, and not have to see them piece by piece. Enable that behaviour by default.

show all lint issues by default

---

changelog/pending/20251001--cli-about--adding-pulumi-about-env-to-help.yaml
pkg/cmd/pulumi/about/about_env.go

Previously `pulumi about env` was not able to be found when a user ran `pulumi about --help` this is because we did not have enough environment variables documented. This has improved significantly, and while it may not be every environment variable, its enough, to help users find most things they need.

feat: enable `env` for `pulumi about env` in `pulumi about --help`

---

pkg/backend/httpstate/client/client.go
pkg/backend/httpstate/snapshot.go
pkg/backend/httpstate/snapshot_benchmark_test.go
pkg/backend/httpstate/snapshot_test.go
pkg/backend/journal.go
pkg/engine/lifecycletest/framework/framework.go
pkg/resource/deploy/deploytest/languageruntime.go
pkg/resource/deploy/deploytest/pluginhost.go
pkg/resource/deploy/deploytest/resourcemonitor.go
pkg/resource/deploy/source_eval.go
sdk/go/common/apitype/journal.go

Add a new set of benchmarks for measuring the performance of our various
snapshot managers (mainly the delta patcher and the in-progress journaler).
Each benchmark case is an instantation of a general case that runs an
update from an empty base snapshot. The update itself s captured by the
case. Each case is itself parameterizable by the snapshot manager used
for persistence.
There are two kinds of cases: one performs an update by issuing a
set of mutually-independent resources with state that contains random
data, and one replays the registrations and reads implied by the
resources in a state file.
For the former cases, the number of resources and the amount of random
data stored in state are parameterizable. A set list of instantiations
is used to drive the top-level benchmark.
For the …

[backend] Add benchmarks for snapshot managers

---

pkg/cmd/pulumi/metadata/metadata_test.go

Some minor test cleanup to the metadata tests:
- Avoid `e.RunCommand("mkdir", "subdirectory")` to make the tests more portable
- Use `assert.Equal` rather than `assert.EqualValues`
- Use `assert.[Not]Contains` rather than `assert.True/False`
- Use `require.True` rather than `t.Errorf`
- Pass the expected value to `assert.Equal` in the right param position
Based on feedback on #20528, with some additional cleanup while already cleaning up here.

Minor test cleanup

---

changelog/pending/20251003--cli-state--exclude-root-stack-correctly-when-moving-resources-and-when-include-parents-is-passed.yaml
pkg/cmd/pulumi/state/state_move.go
pkg/cmd/pulumi/state/state_move_test.go

We had a wrong condition when calculating the parents that need to be included in a move.  This caused us to always include the root stack when --include-parents was given, if the resource to be moved had a parent. Fix that condition, and update the test to also reflect that.

don't include rootstack when --include-parents is given

---

changelog/pending/20251003--backend-service--fix-the-insecure-flag-in-pulumi-login.yaml
pkg/cmd/pulumi/auth/login.go
pkg/cmd/pulumi/backend/backend.go
pkg/cmd/pulumi/backend/login_manager.go
pkg/cmd/pulumi/newcmd/new_test.go
pkg/cmd/pulumi/policy/policy_publish.go
pkg/cmd/pulumi/policy/policy_publish_test.go
pkg/cmd/pulumi/state/state_delete_test.go
pkg/cmd/pulumi/state/state_repair_test.go
pkg/cmd/pulumi/state/state_upgrade_test.go
pkg/cmd/pulumi/templates/templates_test.go
pkg/cmd/pulumi/whoami/whoami_test.go
tests/login/login_test.go

I think this should fix https://github.com/pulumi/pulumi/issues/20645. There were two issues, firstly at some point we just totally stopped looking at the `--insecure` flag during the `login` command. Secondly we didn't always re-lookup the insecure flag when loading the current logged in account.

Add a login test for --insecure

---

sdk/python/lib/test/test_mock_registered_resources.py

Because the MockMonitor subclass is named `Test...`, pytest assumes it is a test class and emits a warning. Turns out we don’t need this class at all.

Fix warnings in test_mock_registered_resources.py

---

changelog/pending/20250505--cli-config--add-json-input-support-to-pulumi-config-set-all.yaml
pkg/cmd/pulumi/config/config.go
pkg/cmd/pulumi/config/config_test.go
tests/integration/integration_test.go

This change brings the work done by @arthurgavazza (thanks, @arthurgavazza!) in #12558 up-to-date, rebasing it and addressing the comments left on the PR. In doing so, it adds the `--json` flag to the `pulumi config set-all` command, so that users can bulk set configuration using a JSON string in the same format as produced by `pulumi config --json`.
Note that the command takes a JSON _value_, not a JSON _file_.
Fixes #11872
Closes #12558

Add `--json` input support to `pulumi config set-all`

---

Makefile

This target is currently broken if `gotestsum` is installed, as it doesn't pass the `-rapid.checks` target correctly. Not sure why `gotestsum` acts like that, but we don't necessarily need it, and can just run directly through `go test` to fix this.

fix fuzzing target in Makefile

---

pkg/engine/lifecycletest/fuzzing/resource.go

Only custom resources can have an ID.  Since #20519, we also check that in the snapshot integrity code.  The fuzz tester doesn't generate resources correctly yet in this case, make it do so.

fuzzing: don't generate ID for non-custom resources

---

scripts/run-conformance.sh

The `-x` option in bash instructs bash to print out each command run before executing the command. I have set the flag for this script since it makes it easy to re-run a specific failing command, avoiding the wait for running tests that already pass.

Show the commands run by `scripts/run-conformance.sh`

---

changelog/pending/20251007--engine--fix-assert-when-a-resource-thats-not-targeted-on-a-destroy-is-marked-as-delete.yaml
pkg/engine/lifecycletest/pending_delete_test.go
pkg/resource/deploy/step.go

Since #20061 we generate same steps for untargeted resources during a destroy. When generating same steps, we assert that `Delete` of the resource is set to "false". However it is possible for `Delete` to be set on the resource, and it not being targeted in a destroy in this case, which triggers the assertion.
We can be a bit more lenient here, and allow same steps to be generated for resources that are marked for deletion to fix this.
(Found using fuzz testing, the fuzz tester crashed on this)
/cc @Frassle, you might have more context on whether it's okay to have a resource be marked as `Delete` during a same step. I think it's okay, but would appreciate a sanity check.

allow resources in same steps to be marked for deletion
