CHANGELOG.md
pkg/cmd/pulumi/plugin_rm.go

Fixes: #5376
```                                                                                                                                                                                          ⍉
pulumi plugin rm --all --yes
no plugins found to uninstall
echo $?
0
```

Improve user message when pulumi plugin rm --all has no plugins to remove

---

CHANGELOG.md
pkg/cmd/pulumi/plugin_install.go
sdk/go/common/workspace/plugins.go

Fixes: #4427
Fixes: #3609
By default, there is no indepth logging:
```
pulumi plugin install resource azure-nextgen v0.2.1
[resource plugin azure-nextgen-0.2.1] installing
Downloading plugin: 17.82 MiB / 17.82 MiB [=========================] 100.00% 2s
Moving plugin... done.
```
We can increase the logging verosity get more detailed logging:
```
pulumi plugin install resource azure-nextgen v0.2.1 -v=1 --logtostderr
[resource plugin azure-nextgen-0.2.1] installing
I1010 19:30:58.472772    7128 plugins.go:201] azure-nextgen downloading from https://get.pulumi.com/releases/plugins
Downloading plugin: 0 B / 17.82 MiB [----------------------------------]   0.00%I1010 19:30:58.704168    7128 plugin_install.go:136] [resource plugin azure-nextgen-0.2.1] installing tarball ...
Downloading plugin: …
```

Respect logging verbosity as part of pulumi plugin install

---

CHANGELOG.md
sdk/python/lib/pulumi/resource.py

Fixes https://github.com/pulumi/pulumi/issues/5534, and also fixed up some other doc comment errata I noticed while making changes here.

[sdk/python] Fix ResourceOptions annotations and doc strings

---

CHANGELOG.md
sdk/dotnet/Pulumi/Deployment/Deployment_Prepare.cs
sdk/dotnet/Pulumi/Resources/Resource.cs

Add a lock around child resource manipulation to prevent hashset concurrency issues. Fix #4821

[dotnet] Add a lock around child resource manipulation 

---

pkg/engine/journal.go
pkg/engine/lifeycletest/pulumi_test.go
pkg/engine/lifeycletest/test_plan.go
pkg/engine/plan.go
pkg/engine/query.go
pkg/engine/update.go

Move these tests to a new package, `lifecycletest`, that also exposes
APIs that allow consumers to implement their own lifecycle tests. This
is intended to ease the burden of testing plugin implementations and to
set the stage for cleaning up the lifecycle tests themselves.
This involves two changes to the public API, only one of which is
strictly necessary:
- The `host` field of `UpdateOptions` is now exported
- The `Journal` type has been moved from test-only code to the package
proper
The former change is necessary, as it is the mechanism by which package
consumers may inject their own plugin loaders. I was reluctant to expose
this field originally because I wanted to ensure that the behavior of
packages that embed Pulumi is consistent with that of the Pulumi CLI
with respect to plugin …

Refactor lifecycle tests.

---

CHANGELOG.md
pkg/backend/display/watch.go

Ensure CLI doesn't panic when pulumi watch is used with policies enabled

---

sdk/nodejs/tests/automation/localWorkspace.spec.ts
sdk/nodejs/tests/config.spec.ts
sdk/nodejs/tests/iterable.spec.ts
sdk/nodejs/tests/output.spec.ts
sdk/nodejs/tests/resource.spec.ts
sdk/nodejs/tests/runtime/asyncIterableUtil.spec.ts
sdk/nodejs/tests/runtime/langhost/cases/003.one_complex_resource/index.js
sdk/nodejs/tests/runtime/langhost/cases/004.ten_complex_resources/index.js
sdk/nodejs/tests/runtime/langhost/cases/005.resource_thens/index.js
sdk/nodejs/tests/runtime/langhost/cases/009.invoke/index.js
sdk/nodejs/tests/runtime/langhost/cases/010.runtime_settings/index.js
sdk/nodejs/tests/runtime/langhost/cases/014.read_resource/index.js
sdk/nodejs/tests/runtime/langhost/cases/015.runtime_sxs/index.js
sdk/nodejs/tests/runtime/langhost/cases/017.parent_defaults/index.js
sdk/nodejs/tests/runtime/langhost/cases/041.component_opt_single_provider/index.js
sdk/nodejs/tests/runtime/langhost/cases/042.component_opt_providers_array/index.js
sdk/nodejs/tests/runtime/langhost/cases/060.provider_invokes/index.js
sdk/nodejs/tests/runtime/langhost/cases/061.provider_in_parent_invokes/index.js
sdk/nodejs/tests/runtime/langhost/cases/062.providerref_invokes/index.js
sdk/nodejs/tests/runtime/langhost/cases/063.providerref_in_parent_invokes/index.js
sdk/nodejs/tests/runtime/langhost/cases/064.async_components/index.js
sdk/nodejs/tests/runtime/langhost/run.spec.ts
sdk/nodejs/tests/runtime/props.spec.ts
sdk/nodejs/tests/runtime/tsClosureCases.ts
sdk/nodejs/tests/testmode.spec.ts

assert.Equal and assert.deepEqual have been deprecated in favor of assert.strictEqual and assert.deepStrictEqual

Replace equal and deepEqual with strictEqual and deepStrictEqual

---

sdk/go/common/resource/plugin/provider_plugin.go

This parameter was not actually stamped into the `provider` value, thus
eliminating its effect.

Respect `disableProviderPreview` in providers.

---

.github/workflows/container-build.yml
.github/workflows/homebrew.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml

This PR fixes some of the outstanding issues with the build
- sends a repository dispatch directly to the docs repo
- fixes the versioning issues with the docker builds
- fixes the homebrew token
Only thing outstanding now is chocolatey builds. Those depends on the docs builds, which are in the docs repo, so we need to address that separately (and trigger it manually for now)

Fix outstanding issues with build

---

pkg/codegen/dotnet/templates.go
sdk/dotnet/cmd/pulumi-language-dotnet/main.go

The existing plugin discovery mechanism doesn't form for Azure NextGen: the NuGet name `Pulumi.AzureNextGen` is translated to the plugin name `azurenextgen` instead of `azure-nextgen`. See https://github.com/pulumi/pulumi-azure-nextgen/issues/70
Basically, there is simingly no way to recover the `dash` in the name without extra metadata. I see two options:
- Hard-code the knowledge about `-nextgen` in the plugin acquisition function
- Add the plugin name to the `version.txt` file next to plugin version
This PR implements the latter. `version.txt` may now be
```
azure-nextgen
0.2.3
```
One downside is that older language plugin versions may get confused about the new format in Azure NextGen `version.txt`. Seems ok-ish as it won't be worse than the current behavior.

Read .NET plugin name from version.txt

---

.github/workflows/windows-build.yml
.github/workflows/windows-pr.yml
.github/workflows/windows-release.yml
build.proj

Fixes: #5648
Recently, GHA windows image was updated with Python 3.9. We didn't specific a specific version of Python when creating a Pipenv so it was using the latest version installed - marking this as a specific version ignores the 3.9 installed as default

Trying to solve Python build on windows

---

CHANGELOG.md
pkg/operations/resources.go

Fixes: #3432
Fixes: #5625
@pgavlin and I had a short convo about this and decided this was the best course of action
When using the following code:
```
import * as pulumi from "@pulumi/pulumi";
class LandingZone extends pulumi.ComponentResource {
constructor(name: string, args: {}, opts?: pulumi.ComponentResourceOptions) {
super("custom:LandingZone", name, args, opts);
this.registerOutputs();
}
};
const lz = new LandingZone("main", {});
```
The previous behaviour was:
```
▶ pulumi watch
Watching (dev):
19:49:26.191[                    ] Updating...
19:49:27.797[     watch-panic-dev] create pulumi:pulumi:Stack
19:49:29.166[     watch-panic-dev] done create pulumi:pulumi:Stack
19:49:29.415[                main] create custom:LandingZone
19:49:29.866[                main] done create …
```

Ensure CLI doesn't panic when using pulumi watch and ComponentResources

---

.github/workflows/codegen-test.yml
.github/workflows/master.yml
.github/workflows/prerelease.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml
.github/workflows/res-docs-test.yml
.github/workflows/windows-build.yml
.github/workflows/windows-pr.yml
.github/workflows/windows-release.yml

Upgrade the build to target Node14 now that it is LTS

---

CHANGELOG.md
pkg/cmd/pulumi/stack_graph.go

Ensure the CLI doesn't panic when trying to build a graph for a stack with no snapshot

---

pkg/cmd/pulumi/stack_history.go

Related: #5679
This is just a quality of life improvement - this doesn't actually fix the bug but will fail the application gracefully

Ensure CLI doesn't panic when trying to decrypt a config value in stack history

---

sdk/dotnet/Pulumi/Deployment/Deployment_ResourceModules.cs
sdk/dotnet/Pulumi/PublicAPI.Shipped.txt
sdk/dotnet/Pulumi/Serialization/Deserializer.cs
sdk/dotnet/Pulumi/Serialization/ResourceModules.cs
sdk/dotnet/Pulumi/Serialization/ResourcePackages.cs
sdk/go/common/util/archive/archive.go
sdk/go/pulumi/rpc.go
sdk/nodejs/runtime/rpc.ts
sdk/python/lib/pulumi/runtime/rpc.py

This is necessary due to the way we've factored the libraries imported
by users into modules. The primary alternative is to ensure that each
child module imports the root module for a package and registers itself
with that package where necessary to prevent circular dependencies. This
simplifies the core SDKs slightly at the cost of greater complications
in the generated SDKs; the approach taken by these changes seems like a
more maintainable option.
The `ResourcePackage` types remain for the use of the root module for
a package, which will register itself in order to construct providers.
Contributes to #2430.

Add resource modules.

---

CHANGELOG.md
sdk/python/lib/pulumi/runtime/settings.py

The feature to check should not be hardcoded to "secrets".
Fixes #5697.

Fix feature support checks in the Python SDK.

---

CHANGELOG.md
pkg/cmd/pulumi/stack_history.go

This changes this:
```
▶ pulumi stack history --json --show-secrets
error: bad value
```
to this
```
▶ pulumi stack history --json --show-secrets
[
{
"kind": "update",
"startTime": "2020-11-06T00:20:16.000Z",
"message": "",
"environment": {
"exec.kind": "cli"
},
"config": {
"aws:region": {
"value": "us-east-1",
"secret": false
},
"history:MySecretPassword": {
"value": "Password1234!",
"secret": true
}
},
"result": "succeeded",
"endTime": "2020-11-06T00:20:29.000Z",
"resourceChanges": {
"same": 1,
"update": 1
}
},
{
"kind": "import",
"startTime": "2020-11-06T00:19:28.000Z",
"message": "",
"environment": {},
"config": {},
"result": "succeeded",
"endTime": "2020-11-06T00:19:29.000Z",
"resourceChanges": {
"create": 0,
"delete": 0,
"same": 2,
"update": 1
}
},
{
"kind": "update",
"startTime": …
```

Ensure pulumi history marks secrets that can't be un-encrypted as such

---

CHANGELOG.md
pkg/resource/deploy/source_eval.go

This feature isn't fully supported yet, so stop reporting it is.
I verified this allows the `aws-ts-eks` example to work, where it'd previously error during `pulumi up`.
Fixes https://github.com/pulumi/pulumi/issues/5705

Report feature "resourceReferences" is not supported

---

docker/actions/entrypoint.sh

Users can define the stack name to deploy multiple environments using multiple AWS accounts in the same branch.
```
- uses: docker://pulumi/actions
with:
args: up
env:
AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_01 }}
AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_01 }}
PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
PULUMI_CI: up
PULUMI_ROOT: infra
PULUMI_STACK_NAME: stack_a
- uses: docker://pulumi/actions
with:
args: up
env:
AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_02 }}
AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_02 }}
PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
PULUMI_CI: up
PULUMI_ROOT: infra
PULUMI_STACK_NAME: stack_b
```

chore(actions): support custom stack name from env

---

sdk/go/x/auto/stack.go

@elsesiy reported an issue with unmarshalling Automation API preview results. I've turned the error into an `AutoError` so that the resulting message provides more useful diagnostics. 
https://github.com/pulumi/pulumi/issues/5470#issuecomment-723374166

Turn Automation API unmarshaling error into AutoError for Go SDK preview ops

---

pkg/codegen/python/gen.go

Fixes: https://github.com/pulumi/pulumi-vsphere/issues/143

Ensure multi-line deprecation warnings are escaped correctly in Python

---

sdk/nodejs/provider/server.ts

The call to `read` wasn't passing the URN.
https://github.com/pulumi/pulumi/blob/e8880e21817edaf6decf7dd30ce84be132202d2f/sdk/nodejs/provider/provider.ts#L179
Also delete a comment that doesn't apply here (copy/paste error from the [dynamic provider](https://github.com/pulumi/pulumi/blob/e8880e21817edaf6decf7dd30ce84be132202d2f/sdk/nodejs/cmd/dynamic-provider/index.ts#L229-L230)).

Fix bug calling `Provider.read`

---

CHANGELOG.md
pkg/engine/lifeycletest/pulumi_test.go
pkg/engine/lifeycletest/test_plan.go
pkg/resource/deploy/import.go

`pulumi import` may otherwise fail if there are providers in the
statefile.

Create a builtin provider during import.

---

CHANGELOG.md
pkg/cmd/pulumi/new.go
sdk/go/common/util/goversion/version.go
sdk/go/common/util/goversion/version_test.go
sdk/go/pulumi-language-go/main.go
sdk/go/pulumi-language-go/main_test.go

Fixes #5724
This change enforces that the go version is at least 1.14.0 for go projects. 
Now the following error is seen when running `pulumi up` on an incompatible version:
```
Previewing update (dev)
View Live: https://app.pulumi.com/.../dev/previews/...
error: failed to discover plugin requirements: go version must be 1.14.0 or higher (1.13.8 detected)
```
and the following when `pulumi new` is invoked:
```
pulumi new gcp-go
Enter a value or leave blank to accept the (default), and press <ENTER>.
Press ^C at any time to quit.
project name: (new-project)
project description: (A minimal Google Cloud Go Pulumi program)
Created project 'new-project'
Please enter your desired stack name.
To create a stack in an organization, use the format <org-name>/<stack-name> (e.g. `acmecorp/dev`). …
```

Pulumi-language-go and pulumi new now checks go version is at least 1.14.0

---

CHANGELOG.md
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_install_test.go

When installing a plugin, previous versions of Pulumi extracted the plugin tarball to a temp directory and then renamed the temp directory to the final plugin directory. This was done to prevent concurrent installs: if a process fails to rename the temp dir because the final dir already exists, it means another process already installed the plugin. Unfortunately, on Windows the rename operation often fails due to aggressive virus scanners opening files in the temp dir.
In order to provide reliable plugin installs on Windows, we now extract the tarball directly into the final directory, and use file locks to prevent concurrent installs from toppling over one another.
During install, a lock file is created in the plugin cache directory with the same name as the plugin's final directory but …

Fix plugin install failures on Windows

---

CHANGELOG.md
pkg/engine/plan.go
pkg/engine/plugins.go
pkg/engine/query.go
pkg/engine/update.go

The way `pulumi new` installs dependencies for .NET projects is slightly different from other languages. For Node.js, Python, and Go, `pulumi new` runs the appropriate command to install project dependencies (e.g. `npm install`, `pip install`, or `go mod download`). For .NET, it calls the same routine used during `preview|up` to ensure required plugins are installed. For .NET, this ends up running `dotnet build` which implicitly installs Nuget packages, builds the project, and also attempts to determine and install the needed Pulumi plugins. When this operation runs during `preview|up`, and there are failures installing a plugin, the error is logged, but deliberately not returned, because an error will be shown for missing plugins later on during the `preview|up` operation. However, …

.NET: Report plugin install errors during `pulumi new`

---

CHANGELOG.md
pkg/backend/display/progress.go

Fixes: #5626
It used to be:
```
Policy Violations:
[advisory]  aws v0.1.20200912  allowed-image-owner (demo-aws-ts-webserver-server-0: aws:ec2/instance:Instance)
Check machine image is from an approved publisher.
Publisher [137112412989] is not one of [self,099720109477].
```
Notice that it was name: type
We would rather this was type: name
```
Policy Violations:
[advisory]  aws v0.1.20200912  allowed-image-owner (aws:ec2/instance:Instance: demo-aws-ts-webserver-server-0)
Check machine image is from an approved publisher.
Publisher [137112412989] is not one of [self,099720109477].
```

Small UX change to the output of policy violations

---

pkg/engine/deployment.go
pkg/engine/destroy.go
pkg/engine/events.go
pkg/engine/import.go
pkg/engine/refresh.go
pkg/engine/update.go

This name better suits the semantics of the type, and aligns with the
rename of deploy.Plan to deploy.Deployment. These changes also refactor
the `update` method s.t. previews and updates are more consistent in
their behavior (e.g. duration and resource changes are now reported for
both, incl. on error paths).

Rename engine.plan to engine.deployment.

---

CHANGELOG.md
sdk/python/dist/pulumi-analyzer-policy-python
sdk/python/dist/pulumi-analyzer-policy-python.cmd
sdk/python/dist/pulumi-resource-pulumi-python
sdk/python/dist/pulumi-resource-pulumi-python.cmd

If `PULUMI_PYTHON_CMD` is set, use it instead of running `python` directly.
Fixes https://github.com/pulumi/pulumi/issues/5518

Respect PULUMI_PYTHON_CMD in scripts

---

pkg/codegen/internal/test/testdata/external-resource-schema/schema.json
pkg/codegen/schema/schema.go
pkg/codegen/schema/schema_test.go

These changes extend the type reference parser in the schema package to
accept references of the form "(package/version/schema.json)?#/provider".
These references refer to the package's provider type, which is
otherwise not referenceable, as it is not present in the "resources"
array.

Allow schemas to reference to provider types.

---

pkg/resource/deploy/builtins.go
sdk/python/Pipfile.lock
sdk/python/lib/pulumi/resource.py
sdk/python/lib/pulumi/runtime/__init__.py
sdk/python/lib/pulumi/runtime/invoke.py
sdk/python/lib/pulumi/runtime/resource.py
sdk/python/lib/pulumi/runtime/rpc.py
tests/integration/get_resource/python/.gitignore
tests/integration/get_resource/python/Pulumi.yaml
tests/integration/get_resource/python/__main__.py
tests/integration/integration_python_test.go

Just what it says on the tin.
These changes take advantage of the fact that Python invokes are
synchronous to fetch the resource state inside of its constructor. The
SDK code generator will be updated to use the new `urn` parameter inside
of each module's implementation of `ResourceModule.construct`.
Part of #2430.

Add support for getResource to the Python SDK.

---

pkg/cmd/pulumi/plugin_install.go
sdk/go/common/workspace/plugins.go

Two improvements:
1. Don't display "[resource plugin <foo>] installing" if the plugin is already installed.
2. Close the plugin download progress bar before displaying any subsequent output, and only show output of `npm install` when there is an error.
Fixes https://github.com/pulumi/pulumi/issues/5807

Improve the output when installing plugins

---

CHANGELOG.md
sdk/go/common/testing/environment.go
sdk/go/common/workspace/creds.go
tests/stack_test.go

The `PULUMI_BACKEND_URL` env var allows specifying the backend to use instead of deferring to the project or the `~/.pulumi/credentials.json` file to decide on the "current" backend.  This allows for using Pulumi without a dependence on this piece of global filesystem state, so that each `pulumi` invocation can control the exact backend it want's to operate on, without having to do stateful `pulumi login`/`pulumi logout` operations.
This is especially useful for automation scenarios like Automation API generally (and effectively solves #5591), or pulumi/pulumi-kubernetes-operator#83 specifically.
This also makes things like https://github.com/pulumi/pulumi/blob/efe7a599e65637378b9ceeac125386b5effd0d68/dist/actions/entrypoint.sh#L10 less necessary, and possible to accomplish for any …

Add PULUMI_BACKEND_URL env var

---

pkg/codegen/python/gen.go

[`provider.py`](https://github.com/pulumi/pulumi-aws/blob/master/sdk/python/pulumi_aws/provider.py#L21-L22) is missing the `inputs` import. This corrects the issue.

[codegen/python] - Include inputs import in provider.py

---

pkg/engine/lifeycletest/pulumi_test.go
pkg/resource/stack/deployment.go
sdk/dotnet/Pulumi/Serialization/Constants.cs
sdk/dotnet/Pulumi/Serialization/Deserializer.cs
sdk/go/common/resource/plugin/provider_plugin.go
sdk/go/common/resource/plugin/rpc.go
sdk/go/common/resource/plugin/rpc_test.go
sdk/go/common/resource/properties.go
sdk/go/pulumi/rpc.go
sdk/nodejs/runtime/rpc.ts
sdk/python/Pipfile.lock
sdk/python/lib/pulumi/runtime/rpc.py

- Differentiate between resource references that have no ID (i.e. because
the referenced resource is not a CustomResource) and resource references
that have IDs that are not known. This is necessary for proper
backwards-compatible serialization of resource references.
- Fix the key that stores a resource reference's package version in the
.NET, NodeJS, and Python SDKs.
- Ensure that the resource monitor's marshalling/unmarshalling  of inputs
and outputs to/from calls to `Construct` retain resource references as
appropriate.
- Fix serialization behavior for resources -> resource references in the
Go SDK: if a resource's ID is unknown, it should still be serialized
as a resource reference, albeit a reference with an unknown ID.

Fix a few issues with resource references.

---

sdk/python/Pipfile
sdk/python/Pipfile.lock
sdk/python/lib/pulumi/runtime/rpc.py
sdk/python/lib/setup.py

There are two significant changes in this commit: one to the way
resource packages/modules are stored and retrieved, and one to resource
ref deserialization in the face of missing resource packages/modules.
Resource packages and modules no longer require an exact version match
during deserialization. Instead, the newest compatible version of the
package or module is selected. If no version was specified, the newest
version of the package or module will be chosen. As a special case, a
package or module that has no version will always be treated as the best
version for that package or module.
If a resource package or module is not found when attempting to
deserialize a resource reference, the SDK no longer emits an error, and
instead deserializes the reference as its URN or ID (if present). …

Update Python resource ref deserialization.

---

.github/workflows/container-build.yml

Our current image push is overwriting the wrong repository. I'll build the v2.14.0 images manually for now, this will fix things up for the next release

use correct repository for actions build

---

pkg/codegen/docs/gen.go
pkg/codegen/docs/gen_function.go

This fixes a panic during docs generation which occurs in the recent .NET codegen block which evaluates the package of an object type
https://github.com/pulumi/docs/runs/1443615556?check_suite_focus=true#step:15:83

Populate package for doc args types

---

pkg/codegen/python/gen.go
pkg/codegen/schema/schema.go

Generate ResourcePackage and ResourceModule implementations and
registrations. A ResourcePackage is generated for any module that
includes a provider resource (which should be the root module only), and
a ResourceModule is generated for any module that includes a resource.
Note that version information is currently omitted. We should fix this
up before enabling resource reference deserialization end-to-end.

[codegen/python/sdk]: package/module registration

---

pkg/resource/deploy/source_eval.go

Need to double check with @pgavlin to see if we're ready to enable this by default, but in the meantime, we can enable it behind a feature flag (set via environment variable) so we can use dev builds of the CLI rather than having to build the CLI locally to turn it on.

Turn on support for resourceReferences behind feature flag

---

CHANGELOG.md
pkg/resource/deploy/source_eval.go

Unless the PULUMI_DISABLE_RESOURCE_REFERENCES flag
is explicitly set to a truthy value, the resource reference feature is now
enabled by default.
Fix #5838

Enable resource reference feature by default

---

sdk/nodejs/provider/server.ts

Remove a `console.log` call that's adding unnecessary diagnostic messages to programs that use multi-lang components implemented in TS/JS.
Avoids output like the following during `pulumi preview|up`:
```
Diagnostics:
pulumi:pulumi:Stack (clusterex-dev):
instanceRoles: ["urn:pulumi:dev::clusterex::aws:iam/role:Role::example-role1","urn:pulumi:dev::clusterex::aws:iam/role:Role::example-role0","urn:pulumi:dev::clusterex::aws:iam/role:Role::example-role2"]
skipDefaultNodeGroup: []
```

Avoid unnecessary diagnostic messages for programs that use multi-lang components

---

CHANGELOG.md
pkg/resource/deploy/source_eval.go

To de-risk the Pulumi v2.15.0 release, temporarily revert 679d40950f54c3c22827bec9e9bad4edcd27dacb. Use of resource references will require `PULUMI_EXPERIMENTAL_RESOURCE_REFERENCES=1` to be set until the feature has been enabled by default.

Revert "Enable resource reference feature by default"

---

CHANGELOG.md
sdk/go/common/workspace/creds.go
sdk/go/common/workspace/creds_test.go

Running `pulumi` operations in parallel could occasionally result in truncating the `~/.pulumi/credentials.json` file and reading that truncated file from another process before the content could be written.
Instead, use `os.Rename` to atomically replace the file contents.
Concurrent `pulumi` operations could still compete for who gets to write the file first, and could lead to surprising results in some extreme cases.   But we should not see the corrupted file contents any longer.
Fixes #3877.

Make credentials.json file writes concurrency safe

---

CHANGELOG.md
pkg/cmd/pulumi/crypto.go
pkg/cmd/pulumi/crypto_local.go
pkg/cmd/pulumi/stack_change_secrets_provider.go
pkg/cmd/pulumi/util.go

Fixes: #5452
When the user is requesting to change the secrets provider to a
passphrase provider, we now calculate that has been requested.
This means, we will prompt for a new passphrase for use in encrypting
the stack.
```
pulumi stack change-secrets-provider passphrase
Enter your passphrase to unlock config/secrets
(set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):
Enter your new passphrase to protect config/secrets:
Re-enter your new passphrase to confirm:
Migrating old configuration and state to new secrets provider
Enter your passphrase to unlock config/secrets
(set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):
```
Thanks to @pierskarsenbarg for helping to drive through the workflow here!

Ensure we can rotate pulumi passphrase secrets providers

---

CHANGELOG.md
sdk/go/common/resource/properties_path.go
sdk/go/common/resource/properties_path_test.go

The current logic attempts to update the array but, because
append may need to allocate a new array with adequate space,
the code can currently leave dest referring to the old,
under-sized array. The solution is to use the set(dest)
logic that already exists and is used for the IsNull case.
Added a test case that would fail before this fix and now passes.
This fixes pulumi/pulumi#5871.

Properly resize arrays when adding

---

CHANGELOG.md
pkg/resource/deploy/deployment_executor.go

Without this, we can panic. 
Fixes: https://github.com/pulumi/pulumi/issues/5883
Fixes: https://github.com/pulumi/pulumi/issues/5860
Fixes: https://github.com/pulumi/pulumi/issues/5876
Fixes: https://github.com/pulumi/pulumi-aws/issues/1252
Previous behaviour:
```
Type                 Name                 Plan
+   pulumi:pulumi:Stack  import-post-dev      create.
=   └─ aws:iam:Policy    AdministratorAccess  import.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4a80f56]
goroutine 73 [running]:
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*deploymentExecutor).importResources(0xc000eefa60, 0x5c10020, 0xc00151c4e0, 0x869c2a8, 0xc0005b2dc0, 0x7fffffff, 0x0, 0x0, 0x0, 0x0, ...) …
```

Ensure we have an import error before using in import path

---

.github/workflows/run-docs-generation.yml

This action errors because the older version is using deprecated commands. https://github.com/pulumi/pulumi/pull/5894/checks?check_run_id=1520508242

Update run-docs-gen to use v3 of create-pull-request

---

CHANGELOG.md
sdk/go/common/workspace/creds.go
sdk/go/common/workspace/creds_test.go

This re-applies the fix in #5857 to make credentials.json writes concurrency safe.
The original fix used `path.Dir` instead of `filepath.Dir` - which led to not placing the temp file in the same folder (and drive) as the renamed file target on Windows.  This led to errors on Windows environments where the working directory was on a different drive than the `~/.pulumi` directory (https://github.com/pulumi/pulumi/issues/5879).  
The change to use `filepath.Dir` instead ensures that even on Windows, the true directory containing the credentials file is used for the temp file as well.
Fixes #3877.

Re-apply #5857

---

pkg/resource/deploy/builtins.go
pkg/resource/deploy/step_executor.go
pkg/resource/deploy/step_generator.go

Record new resources after their operations have been run rather than
before in order to ensure that all state is available and appropriately
marked as secret.
Fixes #5803.

Fix new resource recording.

---

pkg/codegen/docs/gen.go

We need to remove the `Optional` wrapper before we split the type string into parts, otherwise we end up with an extra `]` after the type. [Example](https://www.pulumi.com/docs/reference/pkg/aws/lambda/function/#runtime_python)
Note, the example above actually has 2 extra `]` at the end, only one of which is removed by this PR. The other is caused by `Union` types, I have a fix for that incoming.

Remove optional identifier before splitting type string.

---

.github/workflows/run-build-and-acceptance-tests.yml
.github/workflows/run-codegen-test.yml
pkg/codegen/docs/gen.go
pkg/codegen/docs/templates/properties.tmpl

Treat union types as separate `propertyType`s so we can have separate links. This corrects an issue where union types have an extra `]` at the end [in python](https://github.com/pulumi/docs/pull/4769/files#diff-38ea811bf02d4a3a4b1c104ff357002f2324c68b93a1055f380326592f769e09R3316) but more generally, it standardizes how union types are emitted in the docs.
This PR also changes the github workflow to only run docs-related tests when the path is `pkg/codegen/docs/**`.

Fix union types in resource docs

---

sdk/nodejs/provider/server.ts

`log.error` will call the engine's `log` gRPC endpoint (if the engine is available; otherwise it will write to `console.error`) with `LogSeverity.ERROR`, which tell the engine to stop processing further resource operations.
Without this, any uncaught errors (such as input validation errors done inside `apply`) would be written to stderr, but wouldn't actually result in an update error.
Fixes https://github.com/pulumi/pulumi-eks/issues/480

[sdk/nodejs] Use `log.error` to log uncaught errors

---

CHANGELOG.md
sdk/nodejs/Makefile
sdk/nodejs/runtime/mocks.ts
sdk/nodejs/tests_with_mocks/mocks.spec.ts
sdk/nodejs/tsconfig.json

Otherwise, unit tests for programs that reference resources that have been registered with `registerResourceModule` fail with unhandled exceptions.
We didn't have any existing tests for mocks for Node.js, so I added some based on the [ones we have for Python](https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/test_with_mocks/test_testing_with_mocks.py), and augmented it to cover this case. The new test fails before the change to the SDK, and passes afterwards.
Part of https://github.com/pulumi/pulumi/issues/5832

[sdk/nodejs] Implement getResource in the mock monitor

---

pkg/backend/display/diff.go
pkg/backend/display/options.go
pkg/backend/display/progress.go

This is intended to make it easier to write tests for components (e.g.
the backends) that consume these packages.

Allow display output to be explicitly redirected.

---

CHANGELOG.md
sdk/dotnet/Pulumi.Tests/Mocks/MocksTests.cs
sdk/dotnet/Pulumi.Tests/Mocks/TestStack.cs
sdk/dotnet/Pulumi/Serialization/Converter.cs
sdk/dotnet/Pulumi/Serialization/ResourcePackages.cs
sdk/dotnet/Pulumi/Testing/MockMonitor.cs

This change implements getResource in the mock monitor. This uncovered some issues deserializing resources, which this change also addresses.
Part of #5832
Related to https://github.com/pulumi/pulumi/pull/5914
Related to https://github.com/pulumi/pulumi/pull/5919

[sdk/dotnet] Fix deserializing resources

---

CHANGELOG.md
sdk/go/pulumi/rpc.go

Fixes https://github.com/pulumi/pulumi/issues/5928
There's a marshaling loop that can run multiple times for the purposes of unpacking pointer fields. The dependency array was mistakenly declared inside the loop, causing accumulated dependencies to be clobbered if the loop runs more than once. 
A similar issue was fixed for secrets via https://github.com/pulumi/pulumi/pull/4387, but this was missed. Reading through this method in full, it doesn't seem like there are any additional bugs of this category lurking in the loop...
Used the following program to verify the fix locally. The subnet dependency is missing from the state file before this patch, and present with the patch applied. 
```go
package main
import (
"github.com/pulumi/pulumi-azure/sdk/v3/go/azure/core" …
```

Fix bug that could cause Go SDK to drop dependencies

---

CHANGELOG.md
pkg/resource/deploy/source_eval.go

Disable resource ref support until https://github.com/pulumi/pulumi-kubernetes/issues/1405
is fixed. This bug currently affects Python users with recent versions of the pulumi SDK
who are using the pulumi-kubernetes provider.

Temporarily disable resource ref support

---

pkg/codegen/docs.go
pkg/codegen/docs/gen.go
pkg/codegen/dotnet/doc.go
pkg/codegen/go/doc.go
pkg/codegen/nodejs/doc.go
pkg/codegen/python/doc.go

The primitive type links go to external sites and aren't consistent or particularly helpful. This PR removes primitive type links from the resource docs.

[codegen/docs] - Remove primitive type links

---

pkg/codegen/dotnet/gen_test.go
pkg/codegen/dotnet/utilities.go
pkg/codegen/dotnet/utilities_test.go
pkg/codegen/go/gen_test.go
pkg/codegen/go/utilities.go
pkg/codegen/go/utilities_test.go
pkg/codegen/nodejs/gen_test.go
pkg/codegen/python/gen_test.go

Currently, in [python](https://github.com/pulumi/pulumi/blob/master/pkg/codegen/python/utilities.go#L45) and [nodejs](https://github.com/pulumi/pulumi/blob/master/pkg/codegen/nodejs/utilities.go#L87), `makeValidIdentifier` adds an underscore **before** the starting character (i.e., `8` -> `_8`), but in C# and Go it **replaces** the starting character (i.e., `8` -> `_`). This PR updates the latter to match the former.

[codegen/*] - Align makeValidIdentifier between languages

---

pkg/codegen/dotnet/gen.go

Fixes the enum typestring from `Pulumi.Kubernetes.Types..Core.V1.ServiceSpecType` to `Pulumi.Kubernetes.Core.V1.ServiceSpecType`

[codegen/dotnet] - Fix enum naming for k8s

---

CHANGELOG.md
pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/refresh.go
pkg/cmd/pulumi/up.go
pkg/cmd/pulumi/util.go
pkg/cmd/pulumi/watch.go
pkg/engine/deployment.go
pkg/engine/lifeycletest/pulumi_test.go
pkg/engine/lifeycletest/resource_reference_test.go
pkg/engine/update.go
pkg/resource/deploy/deployment.go
pkg/resource/deploy/deploytest/languageruntime.go
pkg/resource/deploy/deploytest/provider.go
pkg/resource/deploy/deploytest/resourcemonitor.go
pkg/resource/deploy/source_eval.go
sdk/go/common/resource/plugin/rpc.go

- Add component ref coverage to the existing test
- Add coverage for a downlevel SDK communicating with an engine that
supports resource refs
- Add coverage for a downlevel engine communicating with an SDK that
supports resource refs
As part of improving coverage, these changes add a knob to explicitly
disable resource refs in the engine without the use of the environment
variable. The environment variable is now only read by the CLI.
I believe that these changes also fix #5939, which I needed to
address in order for the tests to pass.

Improve resource ref unit tests.

---

sdk/nodejs/Makefile

Bumping timeout as we've seen some related test failures recently.

bump nodejs test timeout for automation api

---

pkg/codegen/docs/gen.go
pkg/codegen/docs/gen_test.go

@zchase I went with the suggestion you had in the issue but happy to adjust as needed. Note the difference between the Package level and Resource level tags... both for the title tag and the meta description. Let me know if we want to bring those in alignment.
Fixes: https://github.com/pulumi/docs/issues/4799

Improve meta tags on documentation

---

sdk/nodejs/runtime/mocks.ts
sdk/nodejs/runtime/settings.ts
sdk/nodejs/tests/runtime/props.spec.ts
sdk/nodejs/tests/testmode.spec.ts

These tests cover the same scenarios that are coverted in the engine's
unit tests, but exercise the Node SDK's marshalling paths.
These changes include a few enhancements to the Node SDK's test APIs
that make it easier to more precisely control its behavior, and extend
the `Mocks` interface to allow the registration of component resources
to work properly.

Add NodeJS resource ref unit tests.

---

CHANGELOG.md
pkg/engine/lifeycletest/import_test.go
pkg/resource/deploy/step.go

The step generator applies `ignoreChanges` pre-processing for all
resources by copying old input values to the new goal for any properties
mentioned in the `ignoreChanges` list. However, this pre-processing
depends on the existence of prior inputs, which by definition does not
exist for a resource being imported prior to the issuance of the
`ImportStep`. These changes add this processing to the implementation of
`ImportStep`, using the inputs read from the provider as the prior
inputs.

Add ignoreChanges preprocessing in `ImportStep`.

---

CHANGELOG.md
pkg/engine/lifeycletest/pulumi_test.go
pkg/resource/deploy/source_eval.go

Now that resources are serialized as refs, ComponentResources
may try to unmarshal local resource refs before they are
initialized during the RegisterResource step.
This change avoids that issue by skipping Output marshaling
for local ComponentResources during the RegisterResource step.
These Outputs will be handled instead during the
RegisterResourceOutputs step.
Fix https://github.com/pulumi/pulumi/issues/5940

Fix bug with ComponentResource resource refs

---

sdk/nodejs/runtime/rpc.ts
sdk/nodejs/runtime/settings.ts
sdk/nodejs/tests/runtime/props.spec.ts

Call `runtime._reset` prior to each test to ensure that the runtime is
in a consistent state.

Use `beforeEach` in NodeJS tests.

---

sdk/python/lib/pulumi/runtime/mocks.py
sdk/python/lib/pulumi/runtime/rpc.py
sdk/python/lib/test/test_next_serialize.py

- Improve the existing coverage to use real resources and mocks
- Add tests for deserialization as well as serialization
- Add tests that serialize custom resources during preview

Add Python resource ref unit tests.

---

CHANGELOG.md
pkg/backend/httpstate/client/client.go
pkg/backend/httpstate/policypack.go
sdk/go/common/util/archive/archive.go
sdk/go/common/workspace/plugins.go

This runs a serious risk of exhausting the memory on lower-end machines
(e.g. certain CI VMs), especially given the potential size of some
plugins.

Do not read TGZs into memory.

---

CHANGELOG.md
sdk/python/python.go

There was a [regression](https://github.com/pulumi/pulumi/pull/5787/files#diff-4a0aed9481c8b2728775fb1fd8bf00087e85c56b10002168c675e4c4c32f2325L147-L148) introduced in #5787 that causes the `venv` for the policy pack to not be created correctly. This PR fixes the regression.
Fixes: https://github.com/pulumi/pulumi-policy/issues/262

Fix virtual env path

---

CHANGELOG.md
pkg/engine/lifeycletest/pulumi_test.go
pkg/resource/deploy/deploytest/pluginhost.go
sdk/go/common/resource/plugin/provider.go
sdk/go/common/resource/plugin/provider_plugin.go
sdk/go/common/resource/plugin/provider_server.go
sdk/go/common/resource/plugin/rpc.go

These changes are a combination of three commits, each of which
contributes to the testing and/or fixing of a problem with marshaling
unknowns in `plugin.provider.Update` when `preview` is true.
These changes add support for communicating with providers using the
gRPC adapters to the deploytest pacakage. This makes it easier to test
the gRPC adapters across typical lifecycle patterns.
Supporting these changes are two additions to the `resource/plugin`
package:
1. A type that bridges between the `plugin.Provider` interface and the
`pulumirpc.ResourceProviderServer`
2. A function to create a `plugin.Provider` given a
`pulumirpc.ResourceProviderClient`
The deploytest package uses these to wrap an in-process
`plugin.Provider` in a gRPC interface and connect to it without using
the default …

gRPC bridge: fix unknowns in `Update` previews

---

build.proj

Noticed that the windows build is still using verbose logging and has a lower timeout compared to our other builds. This PR fixes it.

[build/windows] - Fix verbose test logging and increase timeout

---

pkg/codegen/dotnet/gen.go
pkg/codegen/internal/test/testdata/simple-enum-schema/dotnet/Inputs/ContainerArgs.cs
pkg/codegen/internal/test/testdata/simple-enum-schema/dotnet/Tree/V1/RubberTree.cs
pkg/codegen/internal/test/testdata/simple-enum-schema/go/plant/tree/v1/rubberTree.go
pkg/codegen/internal/test/testdata/simple-enum-schema/nodejs/tree/v1/rubberTree.ts
pkg/codegen/internal/test/testdata/simple-enum-schema/python/pulumi_plant_provider/_inputs.py
pkg/codegen/internal/test/testdata/simple-enum-schema/python/pulumi_plant_provider/outputs.py
pkg/codegen/internal/test/testdata/simple-enum-schema/python/pulumi_plant_provider/tree/v1/rubber_tree.py
pkg/codegen/internal/test/testdata/simple-enum-schema/schema.json
pkg/codegen/schema/schema.go

While trying to implement https://github.com/pulumi/pulumi-azure-nextgen/issues/183 I noticed that schema binding fails for enum properties if they have a default value.
This PR binds the default value to the underlying type of the enum, both strict and "relaxed" (union-based).
It also adjusts the .NET codegen to set the default value to a strict enum in constructors.

[codegen] Add support for default values in enum properties

---

sdk/dotnet/Makefile

Fixes: #3882
This will clean the old packages as well as only "installing" the
latest built package
This ensures old packages are not "installed"
This will only affect local builds / installs

Ensure only latest nuget packages are locally installed

---

CHANGELOG.md
pkg/cmd/pulumi/console.go

Fixes: #5854
If a stackname is not passed as an argument then it will use the
currently selected stack

[CLI] Allow pulumi console to accept a stack name

---

CHANGELOG.md
sdk/go/common/workspace/creds.go

[CLI] Provider better user error when Pulumi credentials file is corrupt

---

pkg/codegen/dotnet/gen.go

The current .NET codegen implementation generates nested union types for multi-case `oneOf` properties. The number of cases varies between 3 and 93 in the Azure NextGen provider. Nested union types in our C# SDK turn out to be highly problematic, see https://github.com/pulumi/pulumi-azure-nextgen/issues/19
This PR keeps `Union<T0, T1>` type for two-case unions but falls back to plain `object` for any multi-case property. While we lose some type "safety", the user experience actually becomes simpler.
I considered more advanced alternative but they seem non-trivial:
- Support inheritance in schema (including multi-level hierarchies). Possibly doable but is disruptive for all languages.
- Support `Union3<T0, T1, T2>`, `Union4...` types. The `OneOf` library that we rely on has types up to 9 …

[codegen/dotnet] Stop generating nested unions

---

CHANGELOG.md
pkg/engine/lifeycletest/provider_test.go
pkg/resource/deploy/source_eval.go

Although raw provider resources accept an input that allows a user to
specifiy a provider version to use, this input is not reflected in
current SDK code generation. Furthermore, we already have a method to
specify the provider version that should be used for a resource: the
"version" resource option. These changes update the code that handles
provider resource registrations to autmoatically populate the version
input from the "version" resource option if the option is present.
Fixes https://github.com/pulumi/pulumi-azure/issues/803.

Respect the version option for provider resources.

---

CHANGELOG.md
sdk/go/pulumi/context.go
sdk/go/pulumi/run_test.go

These are already supported by the implementation, but were prevented by overzealous input validation in Invoke and ReadResource.
Follow-up to #4522 and #4521.

[sdk/go] Support maps in Invoke outputs and Read inputs

---

CHANGELOG.md
sdk/python/lib/pulumi/log.py

[sdk/python] - Don't log if debug and no engine

---

CHANGELOG.md
sdk/dotnet/Pulumi/Testing/MockMonitor.cs

Fixes #6080
For more details check #6080 
The problem is that if the urn is not present in the given args, then the unit tests will fail.

[sdk/dotnet] Moved urn value retrieval into if statement

---

CHANGELOG.md
pkg/codegen/go/gen.go
pkg/codegen/go/gen_test.go
pkg/codegen/internal/test/testdata/simple-enum-schema/go/plant/pulumiTypes.go
pkg/codegen/internal/test/testdata/simple-enum-schema/go/plant/tree/v1/rubberTree.go
sdk/go/pulumi/rpc.go
sdk/go/pulumi/types.go

Fixes https://github.com/pulumi/pulumi/issues/6068

Allow optional strict enum types to be omitted

---

CHANGELOG.md
sdk/dotnet/Pulumi.Tests/Core/OutputTests.cs
sdk/dotnet/Pulumi/Core/Output.cs
sdk/dotnet/Pulumi/PublicAPI.Shipped.txt

Related: #5653
This will take an existing output and then unwrap the secret, and return a new output
```
var x = Output.CreateSecret("test");
var y = Output.Unsecret(x); // new output that has "test" but is not a secret
```
Also adds the ability to check if an output is a secret:
```
var x = Output.CreateSecret("test");
var isSecret = await Output.IsSecretAsync(x); // true
```

[dotnet] Unsecret and IsSecret implementation for .NET

---

CHANGELOG.md
sdk/dotnet/Pulumi.Tests/Serialization/ResourcePackagesTests.cs
sdk/dotnet/Pulumi/Serialization/ResourcePackages.cs

When a resource reference is deserialized, it may not have a version in which case `version` will be an empty string:
https://github.com/pulumi/pulumi/blob/9fbdc51fcd38cd6e805652928583eba4ce6a5b5b/sdk/dotnet/Pulumi/Serialization/Deserializer.cs#L227-L230
This change fixes `TryGetResourceType` to work correctly when an empty version is passed.
Fixes https://github.com/pulumi/pulumi/issues/6088

Fix looking up empty version in ResourcePackages.TryGetResourceType

---

sdk/go/pulumi/context.go
sdk/go/pulumi/resource_test.go
sdk/go/pulumi/rpc.go
sdk/go/pulumi/rpc_test.go

In order to support resource construction in the Go SDK, the
engine context needs to be available in the RPC unmarshaling
code. This change adds a context parameter to the Construct and
ConstructProvider functions, and plumbs the engine context through
to the relevant calls to these functions.
Related to #5801

Plumb context through RPC interface to support resource construction

---

pkg/cmd/pulumi/new_test.go
pkg/go.sum
sdk/go/common/workspace/creds.go
sdk/go/x/auto/stack.go

Couple of quick but necessary fixes for Kubernetes operator to support backends other than app.pulumi.com.

Fixes to support non-pulumi backends in kubernetes operator

---

CHANGELOG.md
sdk/dotnet/Pulumi.Tests/Mocks/MocksTests.cs
sdk/dotnet/Pulumi.Tests/Serialization/ConverterTests.cs
sdk/dotnet/Pulumi.Tests/Serialization/ResourceRefPropertyTests.cs
sdk/dotnet/Pulumi/Serialization/Constants.cs
sdk/dotnet/Pulumi/Serialization/Deserializer.cs
sdk/dotnet/Pulumi/Serialization/ResourcePackages.cs
sdk/dotnet/Pulumi/Serialization/Serializer.cs
sdk/dotnet/Pulumi/Testing/IMocks.cs
sdk/dotnet/Pulumi/Testing/MockMonitor.cs

- Add tests that serialize custom and component resources for targets
that support resource references
- Add tests that serialize custom and component resources for downlevel
targets
- Add tests that deserialize known custom and component resources
- Add tests that deserialize missing custom and component resources
These changes also fix a few bugs that were encountered during testing:
- Component resource construction was not supported
- Resources with missing packages could not be deserialized
In the latter case, a missing resource is deserialized as a generic
DependencyResource.
These changes also update the signature of IMocks.NewResourceAsync to
allow the returned ID to be null. This is technically a C# breaking change
with respect to nullability.

Add .NET resource ref unit tests.

---

.github/workflows/run-build-and-acceptance-tests.yml
CHANGELOG.md
sdk/python/lib/pulumi/x/automation/stack.py

This import is only in v3.7 of python and isn't used in our code.
Fixes: https://github.com/pulumi/pulumi/issues/6108

Remove annotations import

---

CHANGELOG.md
sdk/nodejs/output.ts
sdk/nodejs/tests/output.spec.ts

Related: #5653
This will take an existing output and then unwrap the secret, and
return a new output
```
import * as pulumi from "@pulumi/pulumi";
const x = pulumi.secret("test")
export const xVal = x;
const y = pulumi.unsecret(x);
export const yVal = y;
```
```
▶ pulumi stack output
Current stack outputs (3):
OUTPUT         VALUE
xVal           [secret]
yVal           test
```
Also adds the ability to check if an output is as secret:
```
import * as pulumi from "@pulumi/pulumi";
const x = pulumi.secret("test")
const isSecret = pulumi.isSecret(x);
export const isSecretDeets = isSecret;
```

Add the ability to pulumi.unsecret an existing output

---

pkg/codegen/go/gen.go

This function uses reflection to determine the current package
path and then extracts the version from that path string.
Part of #5801

[codegen/go] Add utility function to get current package version

---

pkg/cmd/pulumi/logs.go

Fixes: #6118
```
▶ pulumi logs --help
[PREVIEW] Show aggregated resource logs for a stack
This command aggregates log entries associated with the resources in a stack from the corresponding
provider. For example, for AWS resources, the `pulumi logs` command will query
CloudWatch Logs for log data relevant to resources in a stack.
```

Updating the description for the pulumi logs cli command

---

CHANGELOG.md
sdk/go/pulumi/types.go
sdk/go/pulumi/types_test.go

Related: #5653
There are situations where we need to ensure we understand if an
Output contains secrets and for the ability to take an Output that
contains a secret and creates the unsecret version
```
secretString := ToSecret(String("foo"))
unSecretString := Unsecret(secretString)
```

Adding `pulumi.IsSecret` and `pulumi.Unsecret` to the Go SDK

---

pkg/engine/events.go
pkg/engine/lifeycletest/pulumi_test.go
pkg/engine/lifeycletest/resource_reference_test.go
pkg/resource/stack/deployment.go
sdk/go/common/resource/plugin/rpc.go
sdk/go/common/resource/plugin/rpc_test.go
sdk/go/common/resource/properties.go
sdk/go/common/resource/properties_diff.go
sdk/go/pulumi/rpc.go

When marshaling a resource reference as its ID (i.e. when
opts.KeepResources is false, as it will be in the case of downlevel SDKs
and resource providers), we must take care to marshal/unmarshal an empty
ID as the unknown property value.
Fixes #5939.

Fix resource-ref-as-ID marshaling.

---

sdk/go/pulumi/resource.go
sdk/go/pulumi/resource_test.go
sdk/go/pulumi/rpc.go
sdk/go/pulumi/rpc_test.go

- Add tests that deserialize known custom and component resources
- Add tests that deserialize missing custom and component resources
These changes also add support for deserializing resources with missing
modules/packages. Such resources are deserialized as generic component,
custom, or provider resources as appropriate.

Add resource ref unit tests for the Go SDK.

---

pkg/codegen/go/gen_program.go

Needed for https://github.com/pulumi/pulumi-terraform-bridge/issues/320
Without this go programgen produces malformed input.

Fix base import path handling in go programgen

---

CHANGELOG.md
pkg/engine/events.go
pkg/engine/lifeycletest/pulumi_test.go
pkg/engine/lifeycletest/resource_reference_test.go
pkg/resource/stack/deployment.go
pkg/resource/stack/deployment_test.go
sdk/go/common/resource/plugin/rpc.go
sdk/go/common/resource/plugin/rpc_test.go
sdk/go/common/resource/properties.go
sdk/go/common/resource/properties_diff.go
sdk/go/pulumi/resource.go
sdk/go/pulumi/resource_test.go
sdk/go/pulumi/rpc.go
sdk/go/pulumi/rpc_test.go

PR #6125 introduced a bug by marshaling resource
ids as PropertyValues, but not handling that case on
the unmarshaling side. The previous code assumed
that the id was a simple string value. This bug prevents
any stack update operations (preview, update, destroy,
refresh). Since this change was already
released, we must now handle both cases in the
unmarshaling code.
Fix #6158

Fix malformed resource value bug

---

CHANGELOG.md
sdk/dotnet/Pulumi/Deployment/Deployment_RegisterResourceOutputs.cs

.NET's implementation of `RegisterResourceOutputs` was always serializing resources as resource references, regardless of the monitor's reported support. This change fixes .NET to check if the monitor supports resource references, which is consistent with all the other languages, and with serialization code elsewhere in the .NET SDK ([here](https://github.com/pulumi/pulumi/blob/45d81f4eb4bba3d7989c4ba072a21c5d9d36b355/sdk/dotnet/Pulumi/Deployment/Deployment_Prepare.cs#L37) and [here](https://github.com/pulumi/pulumi/blob/45d81f4eb4bba3d7989c4ba072a21c5d9d36b355/sdk/dotnet/Pulumi/Deployment/Deployment_Invoke.cs#L45)).
Fixes #6171

[sdk/dotnet] RegisterResourceOutputs: Check for resource ref support

---

CHANGELOG.md
pkg/backend/display/detailedDiff.go
pkg/backend/display/detailedDiff_test.go

Fixes https://github.com/pulumi/pulumi/issues/6135
The cause is probably the Azure NextGen provider that returns the diff in tags as if tags are a typed object rather than an untyped map with arbitrary keys. In the case of panic, there is a tag that contains `[Something]` which fails to parse as a valid path.
However, my point in this PR is that the diff comes from a semi-trusted source (an arbitrary provider, could be 3rd party, eventually), so it's not worth panicking. Rather, we can assume a reasonable default.  In this case, the diff shows as 
which isn't perfect but probably way better than panic.

Relax the diff path check to avoid panic

---

pkg/codegen/go/gen.go
pkg/codegen/internal/test/testdata/simple-enum-schema/dotnet/Tree/V1/Enums.cs
pkg/codegen/internal/test/testdata/simple-enum-schema/dotnet/Tree/V1/RubberTree.cs
pkg/codegen/internal/test/testdata/simple-enum-schema/go/plant/tree/v1/pulumiEnums.go
pkg/codegen/internal/test/testdata/simple-enum-schema/go/plant/tree/v1/rubberTree.go
pkg/codegen/internal/test/testdata/simple-enum-schema/nodejs/tree/v1/rubberTree.ts
pkg/codegen/internal/test/testdata/simple-enum-schema/nodejs/types/enums/tree/v1/index.ts
pkg/codegen/internal/test/testdata/simple-enum-schema/python/pulumi_plant/tree/v1/_enums.py
pkg/codegen/internal/test/testdata/simple-enum-schema/python/pulumi_plant/tree/v1/rubber_tree.py
pkg/codegen/internal/test/testdata/simple-enum-schema/schema.json

Fixes a couple of bugs in go codegen for enums - specifically around setting defaults correctly.
Updated tests with improved coverage for the above.
The PR is split in 2 commits, the first implements the core Go changes and adds the relevant go test data. The latter updates testdata for other languages due to the test schema update.

[codegen/go] Fix default value handling for enums

---

scripts/get-version

When building for alpine aports we download the pulumi source from a
github archive (e.g.
https://github.com/pulumi/pulumi/archive/v2.16.0.tar.gz) but this
doesn't include the .git information to allow scripts/get-version to
work.
This patch, which is currently applied on top of the base pulumi
code as part of the alpine build (see [1]), simply allows the alpine
build script to explicitly set the version used. In the alpine build
script this always matches the source code archive version to download.
[1] https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/16281

Allow VERSION to be set explicitly

---

sdk/nodejs/runtime/rpc.ts

Promise leak debugging was accidentally toStringing an Output, leading to a red herring for several users trying to understand what was causing promise leaks.
Related to #6153 and #5853.

Avoid toStringing Output in debuggablePromise

---

pkg/codegen/dotnet/gen.go
pkg/codegen/internal/test/testdata/external-resource-schema/dotnet/Component.cs

- Avoids problematic `using` statements.
- Fixes fully qualified names of external resources.
- Avoids emitting directories with README.md files for external modules.
This change will allow us to remove the [workarounds](https://github.com/pulumi/pulumi-eks/blob/e92395d0148d0ea3016a0212a2c9532561a3d5be/provider/cmd/pulumi-gen-eks/main.go#L1519-L1557) for .NET in EKS.

[codegen/dotnet]: Fix bugs referencing external resources/types

---

sdk/python/lib/pulumi/resource.py

This fixes the weird broken up rendering as seen in https://github.com/pulumi/docs/issues/4607

Fix the rendering of ResourceOptions.merge

---

pkg/codegen/go/gen.go
pkg/codegen/internal/test/testdata/simple-resource-schema/go/example/pulumiTypes.go
pkg/codegen/internal/test/testdata/simple-resource-schema/schema.json

Multiple fixes to compilation problems in various generated Go SDKs.
Fixes https://github.com/pulumi/pulumi-aws/issues/1321 among other issues.
This follows up from https://github.com/pulumi/pulumi/pull/6179 
Having run on some major SDKs, the last set of compilation issues are due to:
1. Lack of Array and Map input/output variants generated for enum types
2. Name collisions among input/output variants of types and other synonymous types.
These are being addressed in a separate PR.

Various fixes to go codegen to address SDK compilation problems

---

CHANGELOG.md
pkg/cmd/pulumi/crypto_local.go

Fixes: #6208
When changing from a cloudsecrets provider to a passphrase secrets provider
ensure that cloud specific details are removed from the local workspace
```
▶ pulumi stack init my-stack --secrets-provider hashivault://my-stack
Created stack 'my-stack'
~/code/vault-test
▶ pulumi config set my-secret --secret Password1234!
~/code/vault-test
▶ cat Pulumi.my-stack.yaml
secretsprovider: hashivault://my-stack
encryptedkey: dmF1bHQ6djE6c1k3cnRtbExrTmsvYVJvV3Z1KzRJUncvWW5NaVVHd2VTWnBReU16UzR2bnZxcVk4L2dndkJUUzdNSTdSWWxNNEk5TmR1dVJ1UHJMOGQydUc=
config:
vault-test:my-secret:
secure: v1:QZTzjMyCabRLb3qF:6i00N2lYsAO0R3jOODDW89qJa5CTlLs3x0YroBg=
~/code/vault-test
▶ pulumi stack change-secrets-provider passphrase
Enter your new passphrase to protect config/secrets:
Re-enter your new passphrase …
```

Ensure Old Secrets Provider Details Removed when Changing to Passphrase

---

.github/workflows/release.yml

This is a specific repository dispatch event that can be used for
updating and testing a CLI version

Migrating to smoke-test-cli repository_dispatch event in examples repo

---

pkg/codegen/go/gen.go
pkg/codegen/internal/test/testdata/external-resource-schema/go/example/component.go

Avoid serialization failures for inputs with arrays/maps of external references.
Without this the array and maps input types in `Args` structs don't match their corresponding `Input` variants' element type resulting in errors such as this:
`marshaling properties: awaiting input property instanceRoles: cannot marshal an input of type iam.RoleArray with element type []*iam.Role as a value of type []iam.Role`

[codegen/go]Handle arrays/maps of external refs as pointers

---

CHANGELOG.md
sdk/python/lib/pulumi/output.py
sdk/python/lib/test/test_next_serialize.py
sdk/python/lib/test/test_output.py

`Output.from_input` deeply unwraps nested output values in dicts and lists, but doesn't currently do that for the more recently added "input types" (i.e. args classes). This leads to errors when using args classes with output values with `Provider` resources, which uses `Output.from_input` on each input property and then serializes the value to JSON in an `apply`. This changes fixes `Output.from_input` to recurse into values within args classes to propertly unwrap any nested outputs.
The following program fails before the change, and succeeds after:
```python
import pulumi
import pulumi_aws as aws
key = pulumi.Output.from_input("key")
provider = aws.Provider("test",
ignore_tags=aws.ProviderIgnoreTagsArgs(keys=[key]))
```
Fixes #5780

[sdk/python] from_input: Unwrap nested outputs in input types

---

pkg/backend/httpstate/state.go

An external developer we've been working with was trying to troubleshoot some failures in a custom backend they were building, and wasn't sure if the logic in `httpstate.newTokenSource` was right. After taking a close look, everything is totally fine. But it takes a careful review of the code to see what's going on.
This PR just adds some comments to help clarify what's going on.
Fixes #5763

Add a couple comments

---

sdk/nodejs/tests/automation/localWorkspace.spec.ts
sdk/nodejs/x/automation/server.ts
sdk/nodejs/x/automation/stack.ts

This changeset adds several improvements to our error handling for nodejs inline programs run via Automation API. Along the way, I also cleaned up a bunch of unused functionality from `server.ts` (exposing a `result` promise, providing an unused CLI exit code, etc). Summary of fixes: 
1. Run user code in a try/finally to ensure the gRPC `LanguageServer` is always torn down cleanly (otherwise causes failed programs to hang)
2. Run the leaked promise detector after the CLI has exited, this is more consistent with the behavior of CLI programs (detector normally runs as late as possible when the process exits). This fixes the erroneous messages observed in https://github.com/pulumi/pulumi/issues/6153 https://github.com/pulumi/pulumi/issues/5853
2. Ensure that all kinds of `Error` are handled …

Improve nodejs automation api inline error handling

---

.github/workflows/trigger-container-build-event.yml
docker/README.md
docker/dotnet/Dockerfile.ubi

Fixes: #6185
This PR also addresses the fact that we create an image of
pulumi-nodejs:latest and then the ubi and debian builds override
that pulumi-nodejs:latest with their versions
this overwrite is actually last container wins. Therefore, we will
not be tagging the ubi and debian builds with latest to ensure that
latest is *actually* deterministic

Ensure ubi container installs correct dotnet sdk version

---

.github/workflows/download-pulumi-cron.yml

Fixes: #4132
This will test across all available download styles that are Pulumi
managed. I will not install anything like nixos etc

Adding a nightly cron job to ensure we are testing Pulumi install

---

CHANGELOG.md
sdk/python/lib/pulumi/runtime/invoke.py
sdk/python/lib/pulumi/runtime/resource.py
sdk/python/lib/pulumi/runtime/settings.py
sdk/python/lib/pulumi/runtime/stack.py
sdk/python/lib/pulumi/x/automation/_server.py
sdk/python/lib/pulumi/x/automation/stack.py
sdk/python/lib/pulumi/x/automation/workspace.py

The main goal of this PR is to fix all the areas where we were previously exiting the process when the monitor is unavailable and instead just absorb the grpc `UNAVAILABLE` message. There are more details on the exact behavior this was causing and the motivation behind the change in issue #6228. 
I've tested this manually against my initial program that was logging the asyncio warnings, but I'm  not really sure how to write automated tests for this - open to suggestions if there are any. The way to know that it works is that we don't see any asyncio warnings in the console when running a program that fails.
There are also a few misc. formatting corrections.
Fixes: #6228

[sdk/python] - Gracefully handle monitor shutdown

---

CHANGELOG.md
sdk/python/lib/pulumi/runtime/rpc.py
sdk/python/lib/test/test_next_serialize.py

Fixes: https://github.com/pulumi/pulumi/issues/6000
The test case errors before the change and succeeds after.

[python/sdk] - Correctly handle outputs with properties named "values"

---

CHANGELOG.md
pkg/backend/backend.go
pkg/backend/filestate/backend.go
pkg/backend/filestate/state.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/client/client.go
pkg/backend/mock.go
pkg/cmd/pulumi/history.go
pkg/cmd/pulumi/stack_history.go
sdk/go/x/auto/example_test.go
sdk/go/x/auto/stack.go
sdk/nodejs/x/automation/stack.ts
sdk/python/lib/pulumi/x/automation/stack.py

We had some reports of [perf issues](https://github.com/pulumi/pulumi/issues/5453#issuecomment-773442294) related to pulumi stack history. Specifically we use this command to fetch update summary after an update with automation API. As you perform more updates, performance degrades as we fetch more data and decrypt more secrets. This change does two things:
1. add a `--limit=N` flag to `pulumi history` and `pulumi stack history` to allow only fetching the most recent `N` records.
2. consume this flag in the appropriate places in the Automation API SDKs for node, go, and python. 
Note that this is technically a small breaking change for Go (other languages mark this as optional and previous SDK shape is still valid) but this is within the boundaries we've set for the alpha and is an …

Add `--limit` flag to `pulumi stack history` and consume from automation api

---

.github/workflows/pr.yml
.github/workflows/run-build-and-acceptance-tests.yml

This fixes not picking up linting issues when sending a PR as
the PR job uses `pull_request_target` which in turn only checks out
from master which is a security measure

Move linting check into command-dispatch job

---

CHANGELOG.md
pkg/backend/backend.go
pkg/backend/filestate/backend.go
pkg/backend/filestate/state.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/client/client.go
pkg/backend/mock.go
pkg/cmd/pulumi/history.go
pkg/cmd/pulumi/stack_history.go
sdk/go/x/auto/example_test.go
sdk/go/x/auto/stack.go
sdk/nodejs/x/automation/stack.ts
sdk/python/lib/pulumi/x/automation/stack.py
tests/history_test.go

Fixes https://github.com/pulumi/pulumi/issues/6168.
Replaces the `--limit` flag added in https://github.com/pulumi/pulumi/pull/6257.
Found that we have some integration tests that cover the history command, so I made some updates to add some coverage over the new parameters (In addition to the same set of manual testing I did on both the SaaS and filestate backends for #6257)

Add pagination to `pulumi stack history`

---

tests/integration/integration_python_test.go

The Python installation on the Windows GHA runner includes a `python3.exe` which is a symlink to `python.exe`.
Our integration tests look for the Python binary to use to initialize the test's virtual environment by first looking for `python3` on `PATH`, falling back to `python`. In this case, it finds `python3` and uses it to run `python3 -m venv venv`. However, this call ends up failing because `venv` will try to run `ensurepip` to ensure pip is available inside the virtual environment.
https://github.com/python/cpython/blob/ea46579067fd2d4e164d6605719ffec690c4d621/Lib/venv/__init__.py#L291-L298:
```python
def _setup_pip(self, context):
"""Installs or upgrades pip in a virtual environment"""
cmd = [context.env_exe, '-Im', 'ensurepip', '--upgrade',
'--default-pip'] …
```

Fix Python Windows test failures

---

build.proj
pkg/testing/integration/program.go

We install the version of Python we need in the CI environment (e.g. 3.9.x).

Do not specify a specific version of Python on Windows

---

CHANGELOG.md
pkg/testing/integration/program.go
sdk/python/python.go
tests/integration/integration_python_test.go

We previously looked for `python3` and fallback to `python` on all systems. However, our Windows CI images include a `python3.exe` symlink to `python.exe` which does not work with `venv`. So on Windows, just look for `python` first, falling back to `python3`. (The default python.org Windows installation only includes `python.exe`).

Look for `python` binary first on Windows

---

CHANGELOG.md
pkg/testing/integration/program.go
tests/integration/integration_python_test.go
tests/integration/types/types_test.go

This way, the tests use the built-in virtual environment support by default, which is what most customers will be using. A new `UsePipenv` option is available to go back to using pipenv for tests.

Default to UseAutomaticVirtualEnv in integration tests

---

pkg/codegen/internal/test/testdata/external-resource-schema/python/pulumi_example/_inputs.py
pkg/codegen/internal/test/testdata/external-resource-schema/python/pulumi_example/arg_function.py
pkg/codegen/internal/test/testdata/external-resource-schema/python/pulumi_example/cat.py
pkg/codegen/internal/test/testdata/external-resource-schema/python/pulumi_example/component.py
pkg/codegen/internal/test/testdata/external-resource-schema/python/pulumi_example/workload.py
pkg/codegen/internal/test/testdata/simple-resource-schema/python/pulumi_example/arg_function.py
pkg/codegen/internal/test/testdata/simple-resource-schema/python/pulumi_example/other_resource.py
pkg/codegen/python/gen.go

These changes will allow us to remove the remaining [workarounds](https://github.com/pulumi/pulumi-eks/blob/f7ef1c09cc34a2bc2914b49fab46eafa8135896f/provider/cmd/pulumi-gen-eks/main.go#L1576-L1638) for the Python codegen in EKS.
Fixes #5819
Fixes #6232

[codegen/python] Fix issues related to referencing external resources/types

---

pkg/codegen/docs/gen.go
pkg/codegen/docs/gen_function.go

The schema specifies supported environment variables
for Provider inputs, but these are not currently reflected
in the generated docs. This change adds any supported
environment variables to the input property comment
field on Provider resources.
Here's an example of the rendered docs with this change:

[codegen/docs] Add environment variable info to Provider inputs

---

.github/workflows/run-build-and-acceptance-tests.yml

@komalali tagging you for review here as you originally added this line - not sure if it was intended to be left there though
Basically, with that line in place, we never ran any linting / building or testing on a PR run when changes to codegen happened and that meant that #6336 to fix a broken build so hoping we can add this
P.

Ensure changes to pkg/codegen/docs run PR build

---

CHANGELOG.md
sdk/go/x/auto/local_workspace_test.go
sdk/go/x/auto/stack.go

TL;DR After running `stack.Up(...)` via the Automation API, I want access to the update `version` number for the stack.
A resource type integration in [Concourse](https://concourse-ci.org) expects that after an "update" (semantic specific to the resource type implementation) that an identifier for this new version is returned to Concourse. 
For the [Pulumi Concourse CI](https://github.com/ringods/pulumi-resource) integration, I am using the `version` field to model the series of Pulumi deployments. After running `stack.Up(...)` via the Automation API, I would like access to the `version` field from the result JSON so I can return it to Concourse:
https://github.com/ringods/pulumi-resource/blob/c122a20c802fc200f69c303d525c6f83e28ed83b/pkg/out/out.go#L45-L49
/cc @EvanBoyle

Exposing the version in the UpdateSummary struct.

---

CHANGELOG.md
sdk/go/x/auto/local_workspace_test.go
sdk/go/x/auto/test/nested_config/Pulumi.dev.yaml
sdk/go/x/auto/test/nested_config/Pulumi.yaml
sdk/nodejs/tests/automation/data/nested_config/Pulumi.dev.yaml
sdk/nodejs/tests/automation/data/nested_config/Pulumi.yaml
sdk/nodejs/tests/automation/localWorkspace.spec.ts
sdk/python/lib/pulumi/x/automation/_local_workspace.py
sdk/python/lib/test/automation/data/nested_config/Pulumi.dev.yaml
sdk/python/lib/test/automation/data/nested_config/Pulumi.yaml
sdk/python/lib/test/automation/test_local_workspace.py

Also adds a test that parses nested configuration in each language.
To be clear, automation API reads lists and maps as json strings. For now, it is up to the user to de/reserialize the json. This PR is merely fixing the python implementation to match what is already happening in nodejs and go.

[Automation] Fix python nested config parsing

---

CHANGELOG.md
sdk/python/lib/pulumi/output.py
sdk/python/lib/test/test_next_serialize.py

We added a check to `Output.all()` that raises an error if no inputs are provided. This is a breaking change as both internal and user code depends on `Output.all()` to handle empty inputs. 
This PR corrects the function to once again handle `Output.all()` with empty inputs.
Fixes: https://github.com/pulumi/pulumi/issues/6380

[sdk/python] - Allow Output.all with no inputs

---

CHANGELOG.md
sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs

By just not making assertions about the entire collection, as that will break if there are existing stacks.
Fix https://github.com/pulumi/pulumi/issues/6378

[Automation API] - resolve stack manipulation test assertions

---

pkg/codegen/python/gen.go

This [new](https://github.com/pulumi/pulumi/pull/5787) optional file can be used to include additional metadata about the provider plugin (such as version and custom server URL), which the [Python language host will use](https://github.com/pulumi/pulumi/blob/5ab051cd974a619ab4c31e423b5813df0df4b3a2/sdk/python/cmd/pulumi-language-python/main.go#L338-L343) when determining a program's required plugins.
This change fixes the codegen to emit the file in the correct location (inside the package dir). Note: Providers need to opt-in to emitting this file via a schema option (because it requires some Makefile changes to insert the version in the file) and we haven't done that with any of our providers yet.

[codegen/python] Emit pulumiplugin.json in the correct dir

---

CHANGELOG.md
sdk/nodejs/runtime/rpc.ts
sdk/nodejs/tests/runtime/registrations.spec.ts

It is possible for the same version of the same provider SDK to be loaded multiple times in Node.js.  In this case, we might legitimately get mutliple registrations of the same resource.  It should not matter which we use, so we can just skip re-registering.  De-serialized resources will always be instances of classes from the first registered package.
Example layout this addresses.  Registrations of resources in `package3` at the same verrsion.
* `node_modules`
*  `@pulumi/pulumi`
* `package1`
*  `node_modules`
*  `package3`
* `package2`
* `node_modules`
*  `package3`
Fixes #6258.

[sdk/nodejs] Skip re-registrations of same package+version

---

CHANGELOG.md
pkg/backend/filestate/backend.go
pkg/backend/filestate/gcpauth.go
pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/refresh.go
pkg/cmd/pulumi/up.go
pkg/cmd/pulumi/util.go

Fixes: #4029
Fixes: #3537
Should the user want to get permalinks when using a self-managed backend, they can pass a flag:
```
$ pulumi up --suppress-permalink false
```
Permalinks for these self-managed backends will be suppressed on `update`, `preview`, `destroy`,
`import` and `refresh` operations.
A view of the functionality:
```
$ pulumi whoami -v
User: stack72
Backend URL: file://~
$ PULUMI_CONFIG_PASSPHRASE=password pulumi up
Previewing update (pphrase-2):
Type                 Name                       Plan
pulumi:pulumi:Stack  testing-pphrase-2
Resources:
2 unchanged
$ PULUMI_CONFIG_PASSPHRASE=password pulumi up --suppress-permalink false
Previewing update (pphrase-2):
Type                 Name                       Plan
pulumi:pulumi:Stack  testing-pphrase-2
Resources:
2 unchanged …
```

[cli] Disable permalinks to the update details page when using self-managed backends (S3, Azure, GCS)

---

CHANGELOG.md
pkg/cmd/pulumi/config.go
pkg/cmd/pulumi/config_test.go
sdk/go/common/util/cmdutil/args.go
tests/config_test.go

Fixes: https://github.com/pulumi/pulumi/issues/6329

[CLI] - Add commands for config set-all and rm-all

---

CHANGELOG.md
sdk/dotnet/Pulumi.Automation/LocalWorkspace.cs
sdk/go/x/auto/local_workspace.go
sdk/go/x/auto/local_workspace_test.go
sdk/nodejs/x/automation/localWorkspace.ts
sdk/python/lib/pulumi/x/automation/__init__.py
sdk/python/lib/pulumi/x/automation/_local_workspace.py

**Before**
- Mixed (10 secret, 10 plain): 11.69s
- Mixed (20 secret, 20 plain): 24.85s
- Plain (20 plain): 11.25s
- Plain (40 plain): 26.39s
- Secret (20 secret): 12.29s
- Secret (40 secret): 25.36s
**After**
- Mixed (10 secret, 10 plain): 1.18s
- Mixed (20 secret, 20 plain): 1.55s
- Plain (20 plain): 1.05s
- Plain (40 plain): 1.20s
- Secret (20 secret): 1.51s
- Secret (40 secret): 2.54s
Related to: https://github.com/pulumi/pulumi/pull/6373

[automation] - Consume config set-all and rm-all commands

---

pkg/codegen/dotnet/templates.go

We currently include `version.txt` in the package via `<Content Include="version.txt">`. This places the file in the NuGet package in two locations: the `content` directory and `contentFiles`.
We want the file to be in `content` because this is where the Pulumi .NET Language host looks for the file when determining a program's required plugins.
However, having the file in `contentFiles` is problematic. For packages that reference other Pulumi resource packages (e.g. for multi-lang components), referenced `contentFiles` are included in the package by default. This means another package's `version.txt` will be included and used over the current project's `version.txt`. For example, if a multi-lang component package `Pulumi.Xyz` references `Pulumi.Aws`, the `version.txt` from `Pulumi.Aws` …

[codegen/dotnet] Fixes to version.txt handling

---

CHANGELOG.md
pkg/backend/snapshot.go
pkg/backend/snapshot_test.go

Switch from using `reflect.DeepEqual` to using PropertyMap's `DeepEquals` directly for Inputs and Outputs.
This avoids issues with `reflect.DeepEqual` treating `nil` and empty arrays as non-equal.  These appear to have been triggered recently by https://github.com/pulumi/pulumi/pull/6006/files#diff-1fd47e1ff18121659c96a8f47296a2c0c715eb2662c64c7297fa0c5c1ad25c19R290, which changed deserialization of arrays into PropertyMaps from returning `nil` to returning empty arrays.
Also adds additional logging in mustWrite.
Fixes #6197.

Fix mustWrite for Input/Output PropertyMaps

---

.github/workflows/master.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/run-build-and-acceptance-tests.yml
.goreleaser.yml
CHANGELOG.md
CHANGELOG_PENDING.md
CONTRIBUTING.md

As part of our continued effort to make our releases more useful,
we will be adding our CHANGELOG entries to the GitHub Release.
To make this process smooth, we are going to change things a little:
1. All new changelog entries when submitting a PR for an upcoming
release will now need to get added to CHANGELOG_PENDING.md
This is the source of information for what will be delivered in the
release.
2. When a release is being made, the entries from CHANGELOG_PENDING
will be copied to a new version and dated section in CHANGLOG to
mark the release
3. The GH tags will continue as normal and Goreleaser will copy
the changelog entries to the release section in GH

Changing the process for CHANGELOG entries

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi.Automation/PreviewResult.cs
sdk/dotnet/Pulumi.Automation/PublicAPI.Unshipped.txt
sdk/dotnet/Pulumi.Automation/WorkspaceStack.cs
sdk/nodejs/x/automation/stack.ts
sdk/python/lib/pulumi/x/automation/_stack.py

The current implementation in nodejs, python and dotnet attempts to get an action summary for `preview` by running `pulumi history --page-size 1`. However, `preview` summaries are not pushed to `history` because (you guessed it!) it's just a preview and not an actually executed command. As a result, the `summary` ends up being either nothing (before an `up` has ever been run) or the summary of the last executed command of `up/refresh/destroy`. In either case, it is an incorrect result.
This PR removes the `summary` property from `PreviewResult`. 
Notes:
* It might be preferable to wait until structured output is implemented and we can access the preview summary and use that here rather than removing the summary property.
* Go will be handled in a separate PR as it has a different …

[automation] - Remove summary from PreviewResult

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/x/automation/_cmd.py

This PR fixes the usage of `TemporaryFile` in python automation API. Particularly in Windows, `NamedTemporaryFile` [cannot be reopened](https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile:~:text=Whether%20the%20name%20can%20be%20used,cannot%20on%20Windows%20NT%20or%20later) while it is already open, which was leading to errors. We don't need a `NamedTemporaryFile` nor did we need to reopen it, we just needed `seek` to get back to the beginning of the file before we read it.
We don't run SDK unit tests in our Windows build which is why this wasn't caught, but I've opened an [issue](https://github.com/pulumi/pulumi/issues/6417) to track that work.
https://github.com/pulumi/pulumi/pull/6424 has an example of the …

[automation/python] - Use TemporaryFile and seek()

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
sdk/dotnet/Pulumi.Automation/Commands/LocalPulumiCmd.cs

Resolve issue with the `UpdateOptions.OnOutput` delegate not being called because we were reading from the Standard Output stream on the `Process` incorrectly in `LocalPulumiCmd`.

[sdk/dotnet] - automation api OnOutput not called fix

---

pkg/codegen/internal/test/testdata/external-resource-schema/python/pulumi_example/cat.py
pkg/codegen/internal/test/testdata/external-resource-schema/python/pulumi_example/component.py
pkg/codegen/internal/test/testdata/external-resource-schema/python/pulumi_example/workload.py
pkg/codegen/internal/test/testdata/simple-enum-schema/dotnet/Tree/V1/RubberTree.cs
pkg/codegen/internal/test/testdata/simple-enum-schema/nodejs/tree/v1/rubberTree.ts
pkg/codegen/internal/test/testdata/simple-enum-schema/python/pulumi_plant/tree/v1/rubber_tree.py
pkg/codegen/internal/test/testdata/simple-enum-schema/schema.json
pkg/codegen/internal/test/testdata/simple-resource-schema/python/pulumi_example/resource.py
pkg/codegen/python/gen.go

The python implementation of the `Resource.get()` function doesn't account for output properties that are not also represented in the `stateInputs`. This PR corrects this oversight.
From the codegen tests and how this error has manifested, this appears to only affect non-TF providers.
Fixes: https://github.com/pulumi/pulumi-kubernetes/issues/1479

[codegen/python] - Fix python .get() codegen

---

.gitignore

We removed the `Pipfile.lock` file from source control as part of #6424 because we require different dependencies based on platform. This PR adds `Pipfile.lock` to `.gitignore`.

Ignore Pipfile.lock

---

CHANGELOG.md
pkg/resource/deploy/step_generator.go

The engine-side fix for https://github.com/pulumi/pulumi-azure-native/issues/617
If an explicit provider is aliased, the difference must not require replacements for resources defined with this provider.
After the fix and aliasing the provider, I'm only seeing this diff in the scenario of https://github.com/pulumi/pulumi-azure-native/issues/617
```
Type                              Name                  Plan       Info
pulumi:pulumi:Stack               azure-nextgen-cs-dev             
~   └─ pulumi:providers:azure-native  p1                    update     [diff: ~version]
```

Respect provider aliases while diffing resources

---

CHANGELOG.md
CHANGELOG_PENDING.md
sdk/go/pulumi/generate.go
sdk/go/pulumi/templates/types_builtins.go.template
sdk/go/pulumi/templates/types_builtins_test.go.template
sdk/go/pulumi/types_builtins.go
sdk/go/pulumi/types_builtins_test.go

Adds two new methods for every Array and Map type:
```go
func ToStringArray(in []string) StringArray 
func ToStringArrayOutput(in []StringOutput) StringArrayOutput
```
These make it easier to take raw arrays of underlying values and project them into `*Array` instances of the lifted Pulumi type.
This addresses most of the cases in #3861, but does not handle cross-casting between things like `[]ID` and `[]string`.  Conversions like that always require writing a `for` loop in Go, and I believe it's reasonable to say that they require a for loop in an Apply in the Pulumi Go programming model.
It could be argued that we don't even need the helpers added here along similar grounds - but in this case, the Pulumi Go programming model itself is the one forcing a type projection that wouldn't have …

[sdk/go] Add To methods to convert array and map values to Inputs

---

.github/workflows/master.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/run-build-and-acceptance-tests.yml
pkg/testing/integration/program.go
tests/integration/get_resource/dotnet/GetResource.csproj
tests/integration/transformations/dotnet/simple/Transformations.csproj

When passing a package source as part of a `dotnet add package` in
our acceptance testing framework, dotnet was then trying to use that
package source for the restoration of other packages in the csproj
file.
We have removed passing the source to `dotnet add package` add
and replaced it with adding a machine level package source via
`dotnet nuget add source` command
this is the more correct way to work and will allow us to be able
to search multiple locations as part of the `dotnet restore` command

Ensuring dotnet package sources are correct for local packages

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/runtime/mocks.py
sdk/python/lib/pulumi/runtime/sync_await.py
sdk/python/lib/test_with_mocks/resources.py
sdk/python/lib/test_with_mocks/test_testing_with_mocks.py

This change avoids `RuntimeError: There is no current event loop in thread '<thread_name>'` errors when passing a resource as an input multiple times when using mocks.
The problem is that when using mocks, we deserialize the gRPC inputs before passing them to the user's mock methods. Deserializing inputs doesn't typically require an event loop, however, during deserialization of resource references, we end up creating some instances of `Future`, which does require an event loop to be present for the current thread. If this is done multiple times for a resource, it's possible that `deserialize_properties` will be called on an asyncio thread that doesn't yet have an event loop, resulting in the error being raised.
The error does not occur when only passing the resource reference once …

[sdk/python] Fix mocks issue when passing a resource more than once

---

pkg/codegen/internal/test/testdata/simple-enum-schema/nodejs/tree/v1/rubberTree.ts
pkg/codegen/nodejs/gen.go

Before this change, any changes to provider defaults were not picked up:
```
const prov = new aws.Provider("named-provider", {
region: "us-west-2",
skipMetadataApiCheck: false,
skipGetEc2Platforms: false,
});
```
the false values were overriding the defaults but they were not being picked up by the provider:
```
I0310 18:51:52.873680   49300 rpc.go:72] Marshaling property for RPC[ResourceMonitor.RegisterResource(pulumi:providers:aws,named-provider)]: skipCredentialsValidation={true}
I0310 18:51:52.873691   49300 rpc.go:72] Marshaling property for RPC[ResourceMonitor.RegisterResource(pulumi:providers:aws,named-provider)]: skipGetEc2Platforms={true}
I0310 18:51:52.873700   49300 rpc.go:72] Marshaling property for RPC[ResourceMonitor.RegisterResource(pulumi:providers:aws,named-provider)]: …
```

Change nodejs codegen to use coalescing operator when when default values are present

---

CHANGELOG_PENDING.md
pkg/backend/watch.go
pkg/backend/watch_darwin_arm64.go

The underlying library for pulumi watch uses CGO which stops
cross compilation. As as our CI vendor does't have the new mac
hardware, we cannot compile our binaries on darwin arm64 hardware
This means, that in order to release the arm64 binaries, we are
going to remove support for pulumi watch as that is the functionality
using the library in question
This functionality will be returning in a future release

Disabling the use of pulumi watch on darwin/arm64 architecture

---

.github/workflows/master.yml

temporary debugging - will be removed

Debugging why windows builds are being marked as dirty

---

CHANGELOG_PENDING.md
pkg/backend/display/events.go
pkg/go.sum
scripts/go.sum
sdk/go.mod
sdk/go.sum
sdk/go/common/apitype/events.go
sdk/go/common/apitype/history.go
sdk/go/x/auto/events/events.go
sdk/go/x/auto/local_workspace_test.go
sdk/go/x/auto/optdestroy/optdestroy.go
sdk/go/x/auto/optpreview/optpreview.go
sdk/go/x/auto/optrefresh/optrefresh.go
sdk/go/x/auto/optup/optup.go
sdk/go/x/auto/stack.go
sdk/go/x/auto/watcher.go
tests/go.sum

See also: https://github.com/pulumi/pulumi/pull/6454 for the nodejs implementation.
Adds the ability to pass in channels to receive raw events from the Pulumi event stream via an option passed to the `Preview`, `Up`, `Refresh` and `Destroy` commands.
This change is marked **breaking** because it changes the shape of the `PreviewResult` struct.
Before:
```go
type PreviewResult struct {
Steps         []PreviewStep  `json:"steps"`
ChangeSummary map[string]int `json:"changeSummary"`
}
```
After:
```go
type PreviewResult struct {
StdOut        string
StdErr        string
ChangeSummary map[apitype.OpType]int
}
```
Fixes: #6441, #6308

[automation/go] - Expose structured logging

---

.github/workflows/master.yml

This will allow us to start publishing dev channel builds as
3.0.0-alpha.<githash>
```
VERSION_PREFIX=3.0.0 pulumictl get version
3.0.0-alpha.1615565817+0c439b9e
pulumictl get version
2.23.0-alpha.1615565817+0c439b9e
```
This PR will have no bearing on any other branch by feature-3.0 - so it will need to go to master and then we need to rebase that branch!

Set VERSION_PREFIX to be 3.0.0 when using feature-3.0 branch

---

sdk/dotnet/Pulumi.Automation.Tests/Serialization/GeneralJsonConverterTests.cs

When running `make`:
```
X Pulumi.Automation.Tests.Serialization.GeneralJsonConverterTests.CanDeserializeConfigValue [1ms]
Error Message:
System.Text.Json.JsonException : The JSON object contains a trailing comma at the end which is not supported in this mode. Change the reader options. Path: $.secret | LineNumber: 3 | BytePositionInLine: 4.
---- System.Text.Json.JsonReaderException : The JSON object contains a trailing comma at the end which is not supported in this mode. Change the reader options. LineNumber: 3 | BytePositionInLine: 4.
Stack Trace:
at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, JsonReaderException ex)
at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
at …
```

JSON does not admit trailing commas

---

pkg/codegen/docs/templates/constructor_args.tmpl
pkg/codegen/docs/templates/enums.tmpl
pkg/codegen/docs/templates/examples.tmpl
pkg/codegen/docs/templates/package_details.tmpl
pkg/codegen/docs/templates/properties.tmpl

https://github.com/pulumi/docs/pull/5418 upgrades pulumi/docs to use Hugo 0.81, whose new(ish) Markdown renderer functions a little bit differently. This change updates our doc-gen templates accordingly.
⚠️ Don't merge this change until the PR above is merged into pulumi/docs.

Update resource-docs templates to adjust for Hugo upgrade

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/stack_export.go

Fixes: #6195
Before:
```
▶ pulumi stack export --show-secrets
error: could not deserialize deployment: decrypting secret value: failed to decrypt: incorrect passphrase, please set PULUMI_CONFIG_PASSPHRASE to the correct passphrase
```
Notice that it doesn't even ask for the passphrase
After adding a simple check to get the secrets manager we can now
ensure that the user has access to the correct credentials before
we even use the secrets manager
```
pulumi stack export --show-secrets
Enter your passphrase to unlock config/secrets
(set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):
{
"version": 3,
"deployment": {
"manifest": {
"time": "2021-01-27T14:21:23.197301Z",
"magic": "72fc43d05bda7c857308a563548faa323639f314a8d27c0ce550589753311fad",
"version": …
```

Ensure a user has access to the secret manager before trying to decrypt checkpoint

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
sdk/dotnet/Pulumi.Automation/Commands/IPulumiCmd.cs
sdk/dotnet/Pulumi.Automation/Commands/LocalPulumiCmd.cs
sdk/dotnet/Pulumi.Automation/DestroyOptions.cs
sdk/dotnet/Pulumi.Automation/PublicAPI.Unshipped.txt
sdk/dotnet/Pulumi.Automation/Pulumi.Automation.xml
sdk/dotnet/Pulumi.Automation/RefreshOptions.cs
sdk/dotnet/Pulumi.Automation/UpOptions.cs
sdk/dotnet/Pulumi.Automation/UpdateOptions.cs
sdk/dotnet/Pulumi.Automation/Workspace.cs
sdk/dotnet/Pulumi.Automation/WorkspaceStack.cs

Dotnet support for #6511 and also fixes #6483 
NOTE: I did move the `OnOutput` and added the new `OnStdErr` action to the options base class `UpdateOptions` instead of duplicating them for each option type.
I tried to figure out a way to test that the StdErr action would be called, but I did not seem to find a way to get data written to the standard error stream. Even logging with `Log.Warn` or `Log.Error` would end up being written to the standard output stream.

[automation/dotnet] Add ability to capture stderr

---

sdk/dotnet/Pulumi.Automation/WorkspaceStack.cs
sdk/nodejs/x/automation/stack.ts
sdk/python/lib/pulumi/x/automation/_stack.py

dotnet, nodejs and python automation APIs did not specify exec-kind for
refresh or destroy operations. This is now added following the same
logic from the go automation API.

[automation/dotnet,nodejs,python] Specify exec-kind for refresh & destroy

---

CHANGELOG_PENDING.md
sdk/go/pulumi/mocks.go
sdk/go/pulumi/run_test.go

Part of #5832
Related to https://github.com/pulumi/pulumi/pull/5914
Related to https://github.com/pulumi/pulumi/pull/5919
Related to https://github.com/pulumi/pulumi/pull/5921

[sdk/go] Implement getResource in the mock monitor

---

Makefile
scripts/get-version
sdk/dotnet/Makefile
sdk/go/Makefile
sdk/nodejs/Makefile
sdk/python/Makefile

Fixes: #6565
As part of #6460, the logic for determing the version of the build was
moved to be a dependency on pulumictl.
Unfortunately, the homebrew installs use the "make dist" command to
build + install Pulumi to the user maching and as that would have a
dependency on pulumictl and it not existing on the user machine, it
would pass an empty version to the ldflag
This then manifested to the user as:
```
▶ pulumi version
warning: A new version of Pulumi is available. To upgrade from version '0.0.0' to '2.22.0', run
$ brew upgrade pulumi
or visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
```
We are able to mitigate this behaviour by bringing back the get-version
script and using that script as part of the make brew installation
We can see that …

Ensure that make brew works as expected rather than passing empty version

---

sdk/go/common/workspace/templates.go

This commit changes the repository URLs and default branch names for both program and policy pack template repositories from constants to variables, in order that they are customizable by linker flags.
For example, compiling the Pulumi CLI with the following linker flags:
- `-X [module path]/workspace.pulumiTemplateGitRepository=https://github.com/jen20/pulumi-templates.git`
- `-X [module path]/workspace.pulumiTemplateBranch=main`
Would instruct the `pulumi new` command to pull the list of available templates from the `main` branch of the specified repository instead of the upstream default. The defaults are left unchanged.

Make template repository URL and ref modifiable

---

sdk/dotnet/Pulumi/Deployment/Deployment.Logger.cs
sdk/dotnet/Pulumi/Log.cs
sdk/go/pulumi/log.go
sdk/nodejs/log/index.ts
sdk/python/lib/pulumi/log.py

Resolves https://github.com/pulumi/pulumi/issues/6090 by updating docs to reflect current non-terminating behavior of log.error and equivalents.

Fix docstring on node log.error and other SDK equivalents

---

CHANGELOG_PENDING.md
pkg/backend/display/rows.go

Refresh diffs should be diffs of *outputs* not *inputs*.  The code was previously attempting to do this - but was not correct because OpRefresh transmogrifies itself into OpUpdate, OpSame or OpDelete as it is processed, and so those resulting operations (which were what shows the diff) would render their input diff as normal.
Instead, decide whether to render refresh-based output diffs based on whether the action being performed is a `pulumi refresh` instead of using the Op kind.
**Before:**
```
Type                                   Name                                   Plan       Info
pulumi:pulumi:Stack                    refresh-test-luke-dev                             
├─ aws:s3:Bucket                       b                                                 
│  ├─ …
```

Fix `pulumi refresh` diffs

---

CHANGELOG_PENDING.md
sdk/go/common/workspace/loaders.go
sdk/go/common/workspace/project.go

Previously, the CLI did not cache configuration files, which
required a read from disk + unmarshalling + validation each
time a consumer needed to read one of these configurations.
This change introduces global caches for each type of Pulumi
configuration file (Project, ProjectStack, PolicyPackProject, and
PluginProject). The configuration is cached after the first request
and the cached value will be used for any subsequent operations.
Important note: The global configurations are not thread safe,
but this same problem exists using the previous method of
reading/writing config files on disk. Synchronization
will be added in a follow up change to allow for thread safe config
operations.
Fix https://github.com/pulumi/pulumi/issues/6564
Here's an example `pulumi up` to show the new …

[sdk/go] Cache loaded configuration files

---

sdk/go/pulumi/context.go
sdk/go/pulumi/rpc.go
sdk/go/pulumi/rpc_test.go
sdk/go/pulumi/types.go
sdk/go/pulumi/types_test.go

These methods were getting promoted onto every struct that implemented
the Output interface, and are not necessary.
On a real world program, this saves 4% in binary size overall, and
15% of remaining binary size if `Apply<TypeName>` functions are
removed (https://github.com/pulumi/pulumi/issues/6592).

Reduce the number of methods on output

---

CHANGELOG_PENDING.md
sdk/nodejs/tests/automation/localWorkspace.spec.ts
sdk/nodejs/tsconfig.json
sdk/nodejs/x/automation/index.ts
sdk/nodejs/x/automation/localWorkspace.ts
sdk/nodejs/x/automation/minimumVersion.ts
sdk/nodejs/x/automation/workspace.ts

* Added a `LocalWorkspace.pulumiVersion` property that returns the underlying Pulumi CLI version.
* `LocalWorkspace` constructor checks that the `pulumiVersion` >= the minimum version set in `minimumVersion.ts` and returns an error to update the CLI if the check fails.
Nodejs part of #6348 and #6419
Also see: https://github.com/pulumi/pulumi/pull/6577 for Go

[automation/nodejs] - Implement min version checking

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/x/automation/__init__.py
sdk/python/lib/pulumi/x/automation/_local_workspace.py
sdk/python/lib/pulumi/x/automation/_minimum_version.py
sdk/python/lib/pulumi/x/automation/_workspace.py
sdk/python/lib/pulumi/x/automation/errors.py
sdk/python/lib/test/automation/test_local_workspace.py

* Added a `LocalWorkspace.pulumi_version` attribute that returns the underlying Pulumi CLI version.
* `LocalWorkspace` constructor checks that the `pulumi_version` >= the minimum version set in `_minimum_version.py` and raises an exception to update the CLI if the check fails.
Python part of #6348 and #6419
Also see: https://github.com/pulumi/pulumi/pull/6577 for Go and https://github.com/pulumi/pulumi/pull/6580 for nodejs

[automation/python] - Implement min version checking

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi/Core/Input.cs
sdk/dotnet/Pulumi/Core/Output.cs

Addresses https://github.com/pulumi/pulumi/issues/6295

Remove MaybeNull from Output/Input.Create to avoid spurious warnings

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/x/automation/_local_workspace.py

The Project and Stack save routines were erroneously
dumping the Python objects rather than the `__dict__`
property, which resulted in some extra annotations
in the resulting YAML files. Some parsers don't handle
these annotations correctly, and consider the resulting
YAML file to be invalid.
Here's an example of the previous `Pulumi.yaml` file:
```yaml
!!python/object:pulumi.x.automation._project_settings.ProjectSettings
author: null
backend: null
config: null
description: null
license: null
main: null
name: inline_runtime_error_python
runtime: python
template: null
website: null
```

[automation/python] Fix Settings file save

---

.gitignore
CHANGELOG_PENDING.md
sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
sdk/dotnet/Pulumi.Automation/LocalWorkspace.cs
sdk/dotnet/Pulumi.Automation/PublicAPI.Unshipped.txt
sdk/dotnet/Pulumi.Automation/Pulumi.Automation.xml
sdk/dotnet/Pulumi.Automation/Workspace.cs

* Added a `LocalWorkspace.PulumiVersion` field that returns the underlying Pulumi CLI version.
* `LocalWorkspace` constructor checks that the `PulumiVersion` >= `LocalWorkspace._minimumVersion` and raises an exception to update the CLI if the check fails.
Please let me know if there's a more idiomatic way to do this!
C# part of #6348 and #6419
Also see: https://github.com/pulumi/pulumi/pull/6577 for Go, https://github.com/pulumi/pulumi/pull/6580 for nodejs and https://github.com/pulumi/pulumi/pull/6589 for python

[automation/dotnet] - Implement min version checking

---

sdk/go/x/auto/local_workspace_test.go
sdk/nodejs/tests/automation/localWorkspace.spec.ts
sdk/python/lib/test/automation/test_local_workspace.py

Changes the tests to test various current versions against a min version rather than the other way around. Also adds a test case for prerelease.

[automation/*] - Add min version test for prerelease

---

sdk/nodejs/x/automation/events.ts

Go model seems to have these optional:
```
// StepEventMetadata describes a "step" within the Pulumi engine, which is any concrete action
// to migrate a set of cloud resources from one state to another.
type StepEventMetadata struct {
// Op is the operation being performed.
Op   OpType `json:"op"`
URN  string `json:"urn"`
Type string `json:"type"`
// Old is the state of the resource before performing the step.
Old *StepEventStateMetadata `json:"old"`
// New is the state of the resource after performing the step.
New *StepEventStateMetadata `json:"new"`
// Omitted from the type sent to the Pulumi Service is "Res", which may be either Old or New.
```
The emerging C# model treats them optional also. 
Should they be optional/nullable in TypeScript?

Make .old and .new nullable on StateEventMetadata

---

CHANGELOG_PENDING.md
sdk/go/common/workspace/loaders.go

Some YAML parsers don't correctly handle Byte-order Marks,
so automatically strip it off during load.
Related to #423

[cli] Strip Byte-order Mark (BOM) from YAML configs during load

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/x/automation/_cmd.py

The previous implementation did not correctly pass forward the environment variables and `env` ended up as `None`. 
This isn't entirely straightforward to test in isolation but it is used by https://github.com/pulumi/pulumi/pull/6527 and I was able to test that it works as expected because the `PULUMI_DEBUG_COMMANDS` env var is successfully passed through and the tests don't fail with `unknown flag --event-log`.

[automation/python] - Fix passing of extra environment variables

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/runtime/invoke.py
sdk/python/lib/pulumi/runtime/mocks.py
sdk/python/lib/pulumi/runtime/settings.py
sdk/python/lib/test_with_mocks/test_testing_with_mocks.py

The current logic lets unhandled errors in the RPC invocation
unahandled in the async loop, which crashes the process due to
the way we await completion of RPCs before exiting the process
in Python. Instead of doing that, we can just marshal them back
to the synchronous awaiter as part of the calling convention,
and have that awaiter (which is called by the invoke methods)
re-raise the exception. This should fix pulumi/pulumi#3611.

Make data sources catchable in Python

---

CHANGELOG_PENDING.md
sdk/nodejs/cmd/dynamic-provider/index.ts

Contributes to https://github.com/pulumi/pulumi/issues/6645
Closes https://github.com/pulumi/customer-support/issues/360
I went ahead and broke out the non-breaking portion of https://github.com/pulumi/pulumi/pull/6646 into a separate PR. 
This change caches deserialized dynamic providers, so we don't have to repeatedly call `requireFromString` for each diff, check, etc call when many of the same dynamic resource are created. That library ultimately bottoms out on `vm.createContext` https://nodejs.org/api/vm.html#vm_what_does_it_mean_to_contextify_an_object
There was a perf regression in node v12 on this method that exacerbates the issue for our users on that version: https://github.com/nodejs/node/issues/29842

Add provider side caching for dynamic provider deserialization

---

CHANGELOG_PENDING.md
sdk/nodejs/runtime/resource.ts
sdk/nodejs/runtime/rpc.ts
sdk/nodejs/tests/runtime/props.spec.ts

Fixes https://github.com/pulumi/pulumi/issues/6643
More detail in the issues above, but TLDR is that we were swallowing errors in registerResource. This change fixes `prepareResource` to set up reject handlers on ID and URN promises to appropriately propagate the errors.

fix nodejs resource functions (ie registerResource) to properly propagate errors

---

.github/workflows/trigger-container-build-event.yml
docker/nodejs/Dockerfile
docker/nodejs/Dockerfile.alpine

Right now, we test the container at the end of the build rather than
before publishing so while we decouple that work, we should not fail
the build step if a security advisory was found - it's too late, the
containers are released so we should instead catch the advisory and
that will allow our release pipeline to continue
FWIW, our CI doesn't pick up these image vulnerabilities and it should for sure! I will add some followup tasks

[docker] allow docker container builds to pass when security advistory

---

pkg/codegen/go/gen.go
pkg/codegen/internal/test/testdata/external-resource-schema/go/example/init.go
pkg/codegen/internal/test/testdata/simple-enum-schema/go/plant/init.go
pkg/codegen/internal/test/testdata/simple-enum-schema/go/plant/tree/v1/init.go
pkg/codegen/internal/test/testdata/simple-plain-schema/go/example/init.go
pkg/codegen/internal/test/testdata/simple-resource-schema/go/example/init.go

We've been emitting calls to `New<Resource>` for resource registrations in Go, passing `nil` for args. However, some of those `New<Resource>` functions actually check for `nil` args and return an error if the resource has required arguments.
At first, I was looking for a way to check inside `New<Resource>` if the `URN` option was specified and in that case not error on `nil` args (like we do in other languages), but we don't provide a way to access the resource option values outside the Go SDK), so I don't think there is a way to do it this way for Go.
So instead, this change updates the registration code to call `ctx.RegisterResource` directly instead of `New<Resource>`, where we can pass a `nil` args.
Fixes https://github.com/pulumi/pulumi-eks/issues/537

[codegen/go] Fix Go resource registrations

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
sdk/dotnet/Pulumi.Automation/Commands/IPulumiCmd.cs
sdk/dotnet/Pulumi.Automation/Commands/LocalPulumiCmd.cs
sdk/dotnet/Pulumi.Automation/LocalWorkspace.cs
sdk/dotnet/Pulumi.Automation/LocalWorkspaceOptions.cs
sdk/dotnet/Pulumi.Automation/Workspace.cs

Allow environment variables to have a null value

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
sdk/dotnet/Pulumi.Automation/Commands/IPulumiCmd.cs
sdk/dotnet/Pulumi.Automation/Commands/LocalPulumiCmd.cs
sdk/dotnet/Pulumi.Automation/LocalWorkspace.cs
sdk/dotnet/Pulumi.Automation/LocalWorkspaceOptions.cs
sdk/dotnet/Pulumi.Automation/Workspace.cs

This reverts commit 17d1ce509e5589ec7c6b495b7548e7ee1ad6671d.
This PR from a community memeber that I merged because it was approved is [breaking](https://github.com/pulumi/pulumi/runs/2242168751#step:17:47) master: https://github.com/pulumi/pulumi/pull/6520
Reverting until someone can take a closer look.

Revert "Allow environment variables to have a null value (#6520)"

---

sdk/nodejs/runtime/closure/parseFunction.ts

This fixes a similar issue with `__rest` as was documented for `__awaiter` in #2530 and fixed in #2599

Be resilient to 3rd party libraries placing a __rest function on the global object.

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi.Automation.Tests/Data/correct_project/Pulumi.yaml
sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
sdk/dotnet/Pulumi.Automation/Collections/DictionaryContentsComparer.cs
sdk/dotnet/Pulumi.Automation/DictionaryContentsComparer.cs
sdk/dotnet/Pulumi.Automation/Exceptions/ProjectSettingsConflictException.cs
sdk/dotnet/Pulumi.Automation/LocalWorkspace.cs
sdk/dotnet/Pulumi.Automation/ProjectBackend.cs
sdk/dotnet/Pulumi.Automation/ProjectRuntime.cs
sdk/dotnet/Pulumi.Automation/ProjectRuntimeOptions.cs
sdk/dotnet/Pulumi.Automation/ProjectSettings.cs
sdk/dotnet/Pulumi.Automation/ProjectTemplate.cs
sdk/dotnet/Pulumi.Automation/ProjectTemplateConfigValue.cs
sdk/dotnet/Pulumi.Automation/PublicAPI.Unshipped.txt
sdk/dotnet/Pulumi.Automation/Pulumi.Automation.xml
sdk/dotnet/README.md

It's been a while since I did .NET (mostly F# background) so appreciate comments on what's C#-idiomatic, is the IEqualityComparer thing over the top? IN F# we take for granted auto-gen value equality on maps etc.

Avoid overriding dotnet proj settings accidentally

---

sdk/dotnet/Pulumi.Automation/Commands/LocalPulumiCmd.cs

This change should not result in visible behavior difference but simplifies the code. It turns out CliWrap treats the envVar arg as modifications on top of existing system environment, which it propagates already. We do not need to do it therefore.

Simplify env var propagation

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi.Automation.Tests/LocalPulumiCmdTests.cs
sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
sdk/dotnet/Pulumi.Automation/Commands/IPulumiCmd.cs
sdk/dotnet/Pulumi.Automation/Commands/LocalPulumiCmd.cs
sdk/dotnet/Pulumi.Automation/LocalWorkspace.cs
sdk/dotnet/Pulumi.Automation/LocalWorkspaceOptions.cs
sdk/dotnet/Pulumi.Automation/Pulumi.Automation.csproj
sdk/dotnet/Pulumi.Automation/Workspace.cs

This fixes #6499 
Based on https://github.com/pulumi/pulumi/pull/6680, only addition really is just updating CliWrap.

[automation/dotnet] Allow null environment variables

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/runtime/stack.py

Fixes: https://github.com/pulumi/pulumi/issues/6697

[python/sdk] - Fix serialization bug if output contains 'items' property

---

CHANGELOG_PENDING.md
sdk/go/common/workspace/loaders.go

#6636 inadvertently changed the minimum Go version
requirement to 1.16 since ReadFile was moved in that
version. Switch back to ioutil.ReadFile to avoid forcing
an upgrade at this time.

[sdk/go] Use ioutil.ReadFile to avoid forcing 1.16 upgrade

---

CHANGELOG_PENDING.md
sdk/nodejs/dynamic/index.ts
sdk/nodejs/runtime/settings.ts
sdk/nodejs/tests/automation/localWorkspace.spec.ts
sdk/nodejs/tests/runtime/settings.spec.ts

The full description and motivation of this change is outlined here: https://github.com/pulumi/pulumi/pull/6673
TLDR; this change enables caching by default for dynamic providers serialized as a part of executing a program via nodejs. This decreases memory usage and increases runtime significantly for programs making heavy use of dynamic providers. 
This is technically a breaking change as we are now caching dynamic providers based on object equality. It is technically true (but unlikely in practice) that a dynamic provider could rely on some global state, or that in-between resource creation operations that individual methods of the provider (diff/check/create/etc) could be mutated. 
Due to this, users should treat dynamic resource providers as immutable and opt to create singleton …

Enable nodejs dynamic provider caching by default on program side

---

sdk/python/lib/pulumi/runtime/rpc.py
sdk/python/lib/test/test_next_serialize.py

Follow-up from #6701
Marked as no-changelog-required because I added the changelog entry in #6701
Fixes: #6697

Fix serializing bug if output contains 'items' property

---

.github/workflows/run-build-and-acceptance-tests.yml
CHANGELOG_PENDING.md
sdk/python/lib/pulumi/_types.py
sdk/python/lib/pulumi/resource.py
sdk/python/lib/pulumi/runtime/resource.py
sdk/python/lib/pulumi/runtime/rpc.py
sdk/python/lib/test/test_next_serialize.py
sdk/python/lib/test/test_types_input_type_types.py
tests/integration/integration_python_test.go
tests/integration/python/translation/.gitignore
tests/integration/python/translation/Pulumi.yaml
tests/integration/python/translation/__main__.py

This change addresses Python dictionary key translation issues. When the
type of `props` passed to the resource is decorated with `@input_type`,
the type's and resource's property name metadata will be used for dict
key translations instead of the resource's `translate_input_property`
and `translate_output_property` methods.
The generated provider SDKs will be updated to opt-in to this new
behavior:
- FIX: Keys in user-defined dicts will no longer be unintentionally
translated/modified.
- BREAKING: Dictionary keys in nested output classes are now
consistently snake_case. If accessing camelCase keys from such output
classes, move to accessing the values via the snake_case property
getters (or snake_case keys). Generated SDKs will log a warning
when accessing camelCase keys.
When …

[sdk/python] Improved dict key translation support

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
sdk/dotnet/Pulumi.Automation/LocalWorkspace.cs

Found this while working on something else. Basically `GetConfigValueAsync` was not working because the default JsonSerializer was unable to deserialize `ConfigValue` due to it not having a parameterless constructor.

[automation/dotnet] Fix GetConfigValueAsync failing to deserialize

---

CHANGELOG_PENDING.md
sdk/nodejs/log/index.ts

Fixes https://github.com/pulumi/pulumi/issues/6713
Logging-related errors in nodejs are currently getting swallowed and holding up the RPCKeepAlive chain ultimately causing promise leaks. 
Incidentally contributes towards https://github.com/pulumi/pulumi/issues/6712
For #6712, this approach bubbles up log messages impacted to stderr which seems like a good compromise here.

[sdk/nodejs] Improve handling of log related errors 

---

CHANGELOG_PENDING.md
docker/python/Dockerfile
docker/python/Dockerfile.alpine

Update Pulumi python docker image to python 3.9

---

pkg/codegen/internal/test/testdata/external-resource-schema/python/pulumi_example/_inputs.py
pkg/codegen/internal/test/testdata/external-resource-schema/python/pulumi_example/arg_function.py
pkg/codegen/internal/test/testdata/external-resource-schema/python/pulumi_example/cat.py
pkg/codegen/internal/test/testdata/external-resource-schema/python/pulumi_example/component.py
pkg/codegen/internal/test/testdata/external-resource-schema/python/pulumi_example/workload.py
pkg/codegen/internal/test/testdata/simple-enum-schema/python/pulumi_plant/_inputs.py
pkg/codegen/internal/test/testdata/simple-enum-schema/python/pulumi_plant/outputs.py
pkg/codegen/internal/test/testdata/simple-enum-schema/python/pulumi_plant/tree/v1/nursery.py
pkg/codegen/internal/test/testdata/simple-enum-schema/python/pulumi_plant/tree/v1/rubber_tree.py
pkg/codegen/internal/test/testdata/simple-plain-schema/python/pulumi_example/_inputs.py
pkg/codegen/internal/test/testdata/simple-plain-schema/python/pulumi_example/component.py
pkg/codegen/internal/test/testdata/simple-plain-schema/python/pulumi_example/outputs.py
pkg/codegen/internal/test/testdata/simple-resource-schema/python/pulumi_example/arg_function.py
pkg/codegen/internal/test/testdata/simple-resource-schema/python/pulumi_example/other_resource.py
pkg/codegen/internal/test/testdata/simple-resource-schema/python/pulumi_example/resource.py
pkg/codegen/python/gen.go

This change updates the Python SDK codegen to opt-in to the new casing
translation behavior, which will use the passed-in props type's property
name metadata for translations, rather than calling the resource's
`translate_input_property` and `translate_output_property` methods.
- FIX: Keys in user-defined dicts will no longer be unintentionally
translated/modified.
- BREAKING: Dictionary keys in nested output classes are now
consistently snake_case. If accessing camelCase keys from such output
classes, move to accessing the values via the snake_case property
getters (or snake_case keys). A warning will be logged when accessing
camelCase keys.
When serializing inputs:
- If a value is a dict and the associated type is an input type, the
dict's keys will be translated based on the input …

[codegen/python] Adopt improved key translation

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/stack_change_secrets_provider.go
pkg/cmd/pulumi/state.go
pkg/codegen/go/gen_test.go
pkg/codegen/nodejs/gen_program.go
sdk/dotnet/Pulumi.Tests/Mocks/MocksTests.cs
sdk/dotnet/Pulumi.Tests/Serialization/ResourceRefPropertyTests.cs
sdk/dotnet/Pulumi/PublicAPI.Shipped.txt
sdk/dotnet/Pulumi/Testing/IMocks.cs
sdk/dotnet/Pulumi/Testing/MockMonitor.cs
sdk/go/auto/test/errors/conflict_error/go.sum
sdk/go/pulumi/mocks.go
sdk/go/pulumi/run_test.go
sdk/go/pulumi/stack_reference_test.go
sdk/nodejs/runtime/index.ts
sdk/nodejs/runtime/mocks.ts
sdk/nodejs/tests/runtime/props.spec.ts
sdk/nodejs/tests_with_mocks/mocks.spec.ts
sdk/python/lib/pulumi/runtime/__init__.py
sdk/python/lib/pulumi/runtime/mocks.py
sdk/python/lib/test/test_next_serialize.py
sdk/python/lib/test_with_mocks/test_testing_with_mocks.py
tests/integration/python/resource_args/__main__.py
tests/integration/python/translation/__main__.py

Fixes: #6617
@justinvp / @komalali / @lukehoban tagging you fine folks on this PR - this is the follow up to the work of https://github.com/pulumi/pulumi/pull/6551 where we want to allow extensibility in the future without any need to break things

Refactor Mock newResource and call to accept property bag rather than individual args

---

CHANGELOG_PENDING.md
sdk/nodejs/x/automation/stack.ts

An attempt at fixing https://github.com/pulumi/actions/issues/163
The current implementation just creates a temp dir and waits for the CLI to start writing to that file. If that process is delayed by more than 10s we fail. This change tries to be resilient to that case.

explicitly create event log file for nodejs automation api

---

CHANGELOG_PENDING.md
pkg/engine/project.go
tests/integration/integration_nodejs_test.go
tests/integration/project_main_abs/.gitignore
tests/integration/project_main_abs/Pulumi.yaml
tests/integration/project_main_abs/index.ts
tests/integration/project_main_abs/package.json
tests/integration/project_main_parent/Pulumi.yaml
tests/integration/project_main_parent/foo/.gitignore
tests/integration/project_main_parent/foo/bar/Pulumi.yaml
tests/integration/project_main_parent/foo/index.ts
tests/integration/project_main_parent/foo/package.json

Required to fix https://github.com/pulumi/pulumi/issues/5578
See previous discussion in prototype PR here: https://github.com/pulumi/pulumi/pull/6247
TLDR; this change relaxes constraints on the `main` field in a pulumi project (pulumi.yaml) to accept absolute paths and relative paths that point to a parent directory. These are old constraints from PPC that are no longer relevant. Relaxing these constraints will allow us to fix bugs around file assets, closure serialization, and dynamic providers for automation API inline programs.

Enable absolute and relative parent paths for pulumi main

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/stack_history.go

fixes https://github.com/pulumi/pulumi/issues/6737
Set a default limit of 10 entries for `pulumi stack history`. It isn't uncommon for a stack to have hundreds of history entries, in which case accidentally running this command can cause hangs for several seconds.

Set defaults for `pulumi stack history`

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi.Automation/LocalWorkspace.cs
sdk/dotnet/Pulumi.Automation/ProjectSettings.cs
sdk/go/x/auto/local_workspace.go
sdk/go/x/auto/minimum_version.go
sdk/nodejs/x/automation/localWorkspace.ts
sdk/nodejs/x/automation/minimumVersion.ts
sdk/python/lib/pulumi/x/automation/_local_workspace.py
sdk/python/lib/pulumi/x/automation/_minimum_version.py

Fixes https://github.com/pulumi/pulumi/issues/5578
This sets the `main` property when create default projects for inline programs so that relative paths properly resolve. This allows many utilities to function as expected such as assets, archives, closure serialization, magic functions, and dynamic providers. 
Writing tests for this proved to be challenging. Assets were the first thing I thought to reach for, but they don't wail when pointing at an invalid path so that was effectively useless: https://github.com/pulumi/pulumi/issues/5577
I did try to write a dynamic provider test, and couldn't get it to pass inside of our existing test infrastructure (the defaults are designed for situations where you have /index.ts and /node_modules as siblings). 
I did manually verify this with an …

Set main for default projects in Automation API

---

CHANGELOG_PENDING.md
sdk/go/common/workspace/creds.go
tests/login_test.go

Currently, running `pulumi logout --all` will error out if the `credentials.json` file doesn't exist. With this change, the client won't complain if it fails to delete the creds file because it doesn't exist.

Don't return an error if DeleteAllAccounts failed because the creds file doesn't exist

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/history.go
pkg/cmd/pulumi/stack_history.go

Adds the flag `pulumi stack history --full-dates` will print the full dates of updates, instead of the relative `6 hours ago` (or whatever amount).
Ex, `Updated 2021-02-04 10:38:15 -0800 PST took 46s` instead of `Updated 2 months ago took 46s`
rdar://76424838 (pulumi stack history should show full dates instead of relative dates)

Add a flag to stack history to print full dates

---

CHANGELOG_PENDING.md
sdk/nodejs/runtime/closure/v8_v11andHigher.ts

This change inadvertently broke support for node 10. I am going to reapply this change to the 3.0 branch where we can add a node that this also drops support for node 10 (which conveniently arrives at EOL next month). 
Fixes https://github.com/pulumi/pulumi/issues/6755
FYI @DSoko2

Revert "[sdk/nodejs] Add multiple VM contexts support to closure serialization (#6648)"

---

CHANGELOG_PENDING.md
sdk/nodejs/runtime/closure/v8_v11andHigher.ts

…ure serialization (#6648)" (#6759)"
This reverts commit fd9f2710b6027d36990a6705fe41e10d9d820c3b.
This reapplies the VM context change that requires node v11+. I added a breaking entry in the changelog indicating that we are dropping support for node < v11.x. 
cc @DSoko2 this change will be available in the upcoming 3.0 release.

Revert "Revert "[sdk/nodejs] Add multiple VM contexts support to closure serialization"

---

pkg/resource/deploy/source_eval.go

Update the RegisterResource method in the ResourceMonitor
to unmarshal the providers field added in d297db3 and then resolve
any provider references so that they can be set on the Construct call.
Related to https://github.com/pulumi/pulumi-eks/issues/555

[CLI] Handle providers field for RegisterResourceRequest

---

pkg/codegen/internal/test/testdata/external-resource-schema/python/pulumi_example/cat.py
pkg/codegen/internal/test/testdata/external-resource-schema/python/pulumi_example/component.py
pkg/codegen/internal/test/testdata/external-resource-schema/python/pulumi_example/workload.py
pkg/codegen/internal/test/testdata/simple-enum-schema/python/pulumi_plant/tree/v1/nursery.py
pkg/codegen/internal/test/testdata/simple-enum-schema/python/pulumi_plant/tree/v1/rubber_tree.py
pkg/codegen/internal/test/testdata/simple-plain-schema/python/pulumi_example/component.py
pkg/codegen/internal/test/testdata/simple-resource-schema/python/pulumi_example/other_resource.py
pkg/codegen/internal/test/testdata/simple-resource-schema/python/pulumi_example/resource.py
pkg/codegen/python/gen.go

These have been deprecated for a very long time and it's a trivial change to remove them from the generated code. Let's clean this up for the 3.0-based providers.

[codegen/python] Remove deprecated __name__ and __opts__ args

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/resource.py
sdk/python/lib/pulumi/runtime/resource.py

Resolve providers references and include the resulting refs in the
providers field of RegisterResourceRequest that was added in
d297db3.
Related to https://github.com/pulumi/pulumi-eks/issues/555

[sdk/python] Handle providers for RegisterResourceRequest

---

CHANGELOG_PENDING.md
pkg/codegen/docs.go
pkg/codegen/docs/gen.go
pkg/codegen/docs/gen_function.go
pkg/codegen/docs/gen_test.go
pkg/codegen/dotnet/doc.go
pkg/codegen/dotnet/doc_test.go
pkg/codegen/dotnet/gen.go
pkg/codegen/go/doc.go
pkg/codegen/internal/test/testdata/external-resource-schema/nodejs/cat.ts
pkg/codegen/internal/test/testdata/external-resource-schema/nodejs/component.ts
pkg/codegen/internal/test/testdata/external-resource-schema/nodejs/types/input.ts
pkg/codegen/internal/test/testdata/external-resource-schema/python/pulumi_example/component.py
pkg/codegen/internal/test/testdata/simple-enum-schema/nodejs/tree/v1/rubberTree.ts
pkg/codegen/internal/test/testdata/simple-enum-schema/nodejs/types/input.ts
pkg/codegen/internal/test/testdata/simple-plain-schema/nodejs/component.ts
pkg/codegen/internal/test/testdata/simple-plain-schema/nodejs/types/input.ts
pkg/codegen/nodejs/doc.go
pkg/codegen/nodejs/gen.go
pkg/codegen/nodejs/importer.go
pkg/codegen/python/doc.go
pkg/codegen/python/gen.go
pkg/codegen/python/importer.go
sdk/python/lib/test/automation/errors/compilation_error/typescript/package-lock.json
sdk/python/lib/test/automation/errors/runtime_error/javascript/package-lock.json
sdk/python/lib/test/automation/errors/runtime_error/typescript/package-lock.json

See #6200 for a complete description of the issue. In short, we generate
inconsistent names for object types depending on whether or not they are
transitively reachable from resources or functions, which risks
unintentional breaking changes due to schema updates.
1. Name "input" types differently: `TArgs` for a type that is used in
resource inputs, having `Input<T>` properties, and `T` for a type
that is used in invoke inputs. The same schema type can produce both.
2. Always keep the name `T` for output types, avoid appending `Result` to
the name.
3. As needed, introduce a flag in the existing providers' schemas to avoid
breaking changes. Consider removing it on a major version bump.
Fixes #6200.

Fix inconsistent object type naming.

---

CHANGELOG_PENDING.md
sdk/go/pulumi/context.go

Resolve providers references and include the resulting refs in the
providers field of RegisterResourceRequest that was added in
d297db3.
Related to https://github.com/pulumi/pulumi-eks/issues/555

[sdk/go] Handle providers for RegisterResourceRequest

---

pkg/codegen/dotnet/gen.go
pkg/codegen/nodejs/gen.go
pkg/codegen/python/gen.go

This avoids unintentional breaking changes. Ideally we would use a
different knob, but we only have one compat field at the moment.

Generate old type names in k8s compat mode.

---

CHANGELOG_PENDING.md
Makefile
build.proj
pkg/resource/provider/component_provider.go
pkg/resource/provider/host.go
sdk/go/pulumi/context.go
sdk/go/pulumi/provider.go
sdk/go/pulumi/provider/empty.s
sdk/go/pulumi/provider/provider.go
sdk/go/pulumi/provider_linked.go
sdk/go/pulumi/run.go
tests/go.mod
tests/integration/construct_component/testcomponent-go/.gitignore
tests/integration/construct_component/testcomponent-go/main.go
tests/integration/integration_dotnet_test.go
tests/integration/integration_go_test.go
tests/integration/integration_nodejs_test.go
tests/integration/integration_python_test.go
tests/integration/integration_test.go

This makes it possible to create a resource provider with a `Construct` implementation in Go, similar to [what we have for Node](https://github.com/pulumi/pulumi/tree/master/sdk/nodejs/provider).
Fixes #5489

Support defining remote components in Go

---

CHANGELOG_PENDING.md
sdk/go/common/workspace/templates.go

If the remote of the `~/.pulumi/templates` repo is different than the remote provided through the `workspace.pulumiTemplateGitRepository`, remove that directory. Without this change, if the user has templates cached locally (extremely likely), the client will attempt to clone the directory in `~/.pulumi`; when that fails because the dir already exists, it will drop into the `templates` dir and do a pull. This results in the client continuing to use the previous templates source, instead of the new one set by `pulumiTemplateGitRepository`.
This change makes https://github.com/pulumi/pulumi/pull/6545 usable.

Clean the template dir if the remote has changed

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi/Deployment/Deployment_Prepare.cs
sdk/dotnet/Pulumi/Deployment/Deployment_ReadResource.cs
sdk/dotnet/Pulumi/Deployment/Deployment_RegisterResource.cs

Resolve providers references and include the resulting refs in the
providers field of RegisterResourceRequest that was added in
d297db3.
Related to https://github.com/pulumi/pulumi-eks/issues/555

[sdk/dotnet] Handle providers for RegisterResourceRequest

---

pkg/codegen/docs/gen.go
pkg/codegen/docs/gen_function.go
pkg/codegen/docs/templates/constructor_args.tmpl
pkg/codegen/docs/templates/constructor_params.tmpl
pkg/codegen/docs/templates/resource.tmpl
pkg/codegen/docs/templates/utils.tmpl

Add line breaks and whitespace to avoid long horizontal scrolls for Python constructor/function arguments. Also, include the new ResourceArgs constructor overload.
Fixes https://github.com/pulumi/docs/issues/5365

[docgen] Fix horizontal scroll in python resource docs

---

Makefile
build.proj
sdk/go/pulumi/provider.go
sdk/go/pulumi/provider/provider.go
sdk/go/pulumi/provider_linked.go
sdk/go/pulumi/provider_test.go
tests/integration/construct_component/testcomponent-go/main.go
tests/integration/construct_component_plain/testcomponent-go/.gitignore
tests/integration/construct_component_plain/testcomponent-go/main.go
tests/integration/integration_dotnet_test.go
tests/integration/integration_go_test.go
tests/integration/integration_nodejs_test.go
tests/integration/integration_python_test.go
tests/integration/integration_test.go

- Adds support for prompt values.
- Renames `ConstructInputs.SetArgs` => `ConstructInputs.CopyTo` (improved name, IMO)
Fixes #6425

[sdk/go] Support prompt values in `Construct`

---

CHANGELOG.md
sdk/dotnet/Pulumi.Automation.Tests/Data/testproj/go.mod
sdk/go/auto/test/errors/compilation_error/go/go.mod
sdk/go/auto/test/errors/conflict_error/go.mod
sdk/go/auto/test/errors/runtime_error/go/go.mod
sdk/go/auto/test/testproj/go.mod
sdk/nodejs/tests/automation/data/testproj/go.mod
sdk/python/lib/test/automation/data/testproj/go.mod
sdk/python/lib/test/automation/errors/conflict_error/go.mod
sdk/python/lib/test/automation/errors/runtime_error/go/go.mod

Fixes the problems that `gopls` language server reports regarding same module names being overused within the project.
Closes #6775

Fixes #6775: Duplicated Go modules

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi.Automation/Pulumi.Automation.csproj

[automation/dotnet] Use Grpc.AspNetCore.Server package - without Grpc.Tools dependency

---

CHANGELOG_PENDING.md
pkg/codegen/dotnet/gen.go
pkg/codegen/internal/test/testdata/external-resource-schema/docs/component.md
pkg/codegen/internal/test/testdata/external-resource-schema/python/pulumi_example/component.py
pkg/codegen/internal/test/testdata/simple-plain-schema/docs/component.md
pkg/codegen/internal/test/testdata/simple-plain-schema/dotnet/Component.cs
pkg/codegen/internal/test/testdata/simple-plain-schema/dotnet/Inputs/FooArgs.cs
pkg/codegen/internal/test/testdata/simple-plain-schema/go/example/component.go
pkg/codegen/internal/test/testdata/simple-plain-schema/go/example/pulumiTypes.go
pkg/codegen/internal/test/testdata/simple-plain-schema/nodejs/component.ts
pkg/codegen/internal/test/testdata/simple-plain-schema/nodejs/types/input.ts
pkg/codegen/internal/test/testdata/simple-plain-schema/python/pulumi_example/_inputs.py
pkg/codegen/internal/test/testdata/simple-plain-schema/python/pulumi_example/component.py
pkg/codegen/internal/test/testdata/simple-plain-schema/schema.json
pkg/codegen/nodejs/gen.go
pkg/codegen/python/gen.go
pkg/codegen/schema/schema.go
pkg/codegen/utilities_types.go

These changes fix a regression introduced by #6686 that caused the SDK
code generators for .NET, Python, and Typescript to omit definitions for
plain object types. This regression occurred because #6686 drew a
clearer line between types used as resource arguments and types used
as function arguments, but conflated "resource arguments" with "inputty
types". This caused the code generators to generate inputty types for
any types used as resource arguments, even those that are used for
plainly-typed properties.
Fixes #6796.

Distinguish between inputty and plain args types.

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/runtime/rpc.py
sdk/python/mypy.ini
sdk/python/stubs/semver/__init__.pyi

This bug actually prevents resources from hydrating that is:
```
get_resource_module('azure-native', 'authorization', '1.0.0')
```
Is broken..

Fix bug in semver usage by enabling typechecking

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/stack_history.go

Readding #6739 since it was lost during the 3.0 release
Also not sure what to say in the CHANGELOG

Re-add - Set pagination defaults for `pulumi stack history` to 10 entries (#6739)

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/automation/_stack.py

Deserialization of config values in UpdateSummary was erroring when the config value is a map or array. This fixes the issue.
Fixes: #6809

[automation/python] - Fix deserialization of UpdateSummary

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi.Automation/LocalWorkspace.cs
sdk/go/auto/minimum_version.go
sdk/nodejs/automation/minimumVersion.ts
sdk/nodejs/tests/automation/localWorkspace.spec.ts
sdk/python/lib/pulumi/automation/_minimum_version.py

We need to bump the minimum version because the stack select changes require CLI-SDK alignment.

[auto/*] - Bump min version

---

sdk/nodejs/runtime/debuggable.ts

Fixes https://github.com/pulumi/pulumi/issues/6815
It appears this rejection handler was left over was not meant to ship in the nodejs SDK. It seems to be interfering with error handling in some cases.

remove erroneous global promise rejection handler

---

sdk/python/lib/pulumi/automation/_cmd.py
sdk/python/lib/pulumi/automation/_local_workspace.py
sdk/python/lib/pulumi/automation/_stack.py
sdk/python/lib/setup.py

* Fixes a number of pylint errors for [consider-using-with](http://pylint.pycqa.org/en/latest/whatsnew/2.8.html?highlight=consider-using-with#new-checkers:~:text=New%20refactoring%20message%20consider%2Dusing%2Dwith.%20This%20message,are%20called%20without%20a%20with%20block.)
* Updates the grpcio requirement in `setup.py` to mirror the [Pipfile](https://github.com/pulumi/pulumi/blob/master/sdk/python/Pipfile#L9)

[sdk/python] - Fix python lint errors

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/runtime/mocks.py
sdk/python/lib/test_with_mocks/resources.py
sdk/python/lib/test_with_mocks/test_testing_with_mocks.py

The [refactor](https://github.com/pulumi/pulumi/pull/6672) to `MockResourceArgs` introduced a bug for `ReadResource` as the request does not include a `custom` attribute, leading to an error when mocking `StackReference`. 
This PR corrects the issue and adds a test for `StackReference`.
Fixes: #6861

Fix python mock args

---

CHANGELOG_PENDING.md
sdk/go/auto/stack.go
sdk/go/auto/stack_test.go

Adds missing receiver funcs for GetPermalink to PreviewResult,RefreshResult,DestroyResult
Add simple test case
Update Changelog
Fix #6778

[auto/go] - Provide GetPermalink for all results

---

pkg/codegen/go/gen_program.go

This commit adjusts the way that Go module versions are discovered from packages when generating Go programs, to account for those on module version 1. Previously, this function would panic when dereferencing a nil instance of `semver.Version`.

Permit Go program gen to work with modules at v1

---

README.md

For us who are using dark mode on Github, the Pulumi logo is not showing. I've taken the liberty to play around with a few options to fix it.
~~This option mimics the information boxes from the Pulumi website.~~
- ~~Dark mode: https://user-images.githubusercontent.com/3726815/115958917-ca2a7180-a509-11eb-8680-7ea2da401b3b.jpg~~
- ~~Light mode: https://user-images.githubusercontent.com/3726815/115958922-d0205280-a509-11eb-88e9-aea7dd346a58.jpg~~
This option is just a box with rounded corners in white with the logo on top.
**Screenshots of the README**:
- Dark mode: https://user-images.githubusercontent.com/3726815/115958887-ab2bdf80-a509-11eb-9b29-ecb469c6d1a8.jpg
- Light mode: https://user-images.githubusercontent.com/3726815/115958907-b717a180-a509-11eb-944c-e98d73966860.jpg
Requires …

docs: Update Github logo

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/stack_export.go
pkg/secrets/passphrase/manager.go
pkg/secrets/passphrase/manager_test.go
tests/stack_test.go

Fixes: #6286
When a user is using the passphrase provider and unsets the environment
variables that let them interact with the secrets provider, then would
get an error as follows:
```
▶ pulumi up -y -f
error: decrypting secret value: failed to decrypt: incorrect passphrase, please set PULUMI_CONFIG_PASSPHRASE to the correct passphrase
```
We are oging to change this error message to make it more obvious
to a user what the error is and how they need to fix it
```
▶ pulumi up -y -f
error: constructing secrets manager of type "passphrase": unable to find either `PULUMI_CONFIG_PASSPHRASE` nor `PULUMI_CONFIG_PASSPHRASE_FILE` when trying to access the Passphrase Secrets Manager. Please ensure one of these values are set to allow the operation to continue
```
Ideally, we would like to prompt …

[cli] Ensure the user has set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
sdk/dotnet/Pulumi.Automation/LocalWorkspace.cs
sdk/dotnet/Pulumi.Automation/Pulumi.Automation.xml
sdk/go/auto/local_workspace.go
sdk/go/auto/local_workspace_test.go
sdk/nodejs/automation/localWorkspace.ts
sdk/nodejs/tests/automation/localWorkspace.spec.ts
sdk/python/lib/pulumi/automation/_local_workspace.py
sdk/python/lib/test/automation/test_local_workspace.py

This PR adds an option to skip the minimal CLI version check for Automation API . If `PULUMI_AUTOMATION_API_SKIP_VERSION_CHECK` has a non-empty value, the check is skipped.
Docs PR: https://github.com/pulumi/pulumi-hugo/pull/154
Fixes: #6711

[automation/*] - Optionally skip Automation API version check

---

sdk/go/auto/local_workspace.go
sdk/go/auto/local_workspace_test.go

Helps with #5432 
Test demonstrates a panic without the fixes. Also - on case-sensitive filesystems the use of `pulumi.xxx.yaml` vs. `Pulumi.xxx.yaml` matters.

[auto/go] Fix stack settings save/load typo and add tests

---

pkg/secrets/passphrase/manager.go

This incorporates some post merge feedback from https://github.com/pulumi/pulumi/pull/6893
This doesn't change the functionality of any of the tests:
```
go test -v ./secrets/passphrase -count=1
=== RUN   TestPassphraseManagerIncorrectPassphraseReturnsErrorCrypter
--- PASS: TestPassphraseManagerIncorrectPassphraseReturnsErrorCrypter (0.89s)
=== RUN   TestPassphraseManagerIncorrectStateReturnsError
--- PASS: TestPassphraseManagerIncorrectStateReturnsError (0.00s)
=== RUN   TestPassphraseManagerCorrectPassphraseReturnsSecretsManager
--- PASS: TestPassphraseManagerCorrectPassphraseReturnsSecretsManager (1.08s)
=== RUN   TestPassphraseManagerNoEnvironmentVariablesReturnsError
--- PASS: TestPassphraseManagerNoEnvironmentVariablesReturnsError (0.00s)
PASS
ok …
```

[cleanup] Small stylistic changes to NewPassphaseSecretsManagerFromState

---

pkg/codegen/go/gen.go
pkg/codegen/internal/test/testdata/simple-plain-schema-with-root-package/go/pulumiUtilities.go

If `rootPackageName` is set, we can look for the version in the `baseImportPath` rather than at a location based on the package name - which currently fails if every component is not named `pulumi-*`. To err on the side of caution, this method is only used for packages where `rootPackageName` is set, meaning existing SDKs retain their current behavior.
The new behavior is confirmed via the test added in #6862.
_Note that this PR requires #6862 to apply cleanly - that commit is included here so it builds. Apparently stacked PRs don't work across forks - or I can't work out how to make it so to target #6862! The actual new work of this PR is in `a73dd60`._

Respect baseImportPath in codegen'd Go SDKs

---

CHANGELOG_PENDING.md
pkg/backend/updates.go
pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/refresh.go
pkg/cmd/pulumi/up.go
pkg/cmd/pulumi/util.go
pkg/cmd/pulumi/watch.go
sdk/go/auto/debug/debuglogging.go
sdk/go/auto/local_workspace_test.go
sdk/go/auto/minimum_version.go
sdk/go/auto/optdestroy/optdestroy.go
sdk/go/auto/optpreview/optpreview.go
sdk/go/auto/optrefresh/optrefresh.go
sdk/go/auto/optup/optup.go
sdk/go/auto/stack.go
sdk/nodejs/automation/minimumVersion.ts
sdk/nodejs/automation/stack.ts
sdk/nodejs/tests/automation/localWorkspace.spec.ts

Adds CLI support, and automation API support for the nodejs and Go SDKs for specifying a user agent at update time. 
This user agent is stored with the update and can be displayed in various backends so that users can distinguish between human driven activity, CLI activity, and activity driven by automation like the Kubernetes Operator or the Pulumi GHA. 
Leaving this as a hidden flag in the CLI for now. We can eventually open and up, and add documentation so users can use this via the CLI but I will leave that as a later exercise. For now the current implementation with a hidden flag suits the desired use case. 
Contributes to https://github.com/pulumi/pulumi/issues/6503 for CLI, Go, and Node. Required for https://github.com/pulumi/home/issues/1375

Add user agent to the CLI, Go and Nodejs Automation API SDKs

---

sdk/go/auto/local_workspace.go

When calling l.GetEnvVars() to evaluate whether version checking should be skipped because of variables passed into the workspace, they have not yet been set. This commit modifies the logic to look at the environment variables in the options instead of in the workspace.
Test coverage is at the level of the function called currently.
Labelling pull requests requires write access to the repository.
Since the original functionality  has not yet been released, I do not believe it warrants a CHANGELOG entry.

[kind/bug] [automation/go]: Look in workspace options for version optout

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/_types.py
sdk/python/lib/test/langhost/inheritance_translation/__init__.py
sdk/python/lib/test/langhost/inheritance_translation/__main__.py
sdk/python/lib/test/langhost/inheritance_translation/inheritance_translation.py
sdk/python/lib/test/langhost/inheritance_types/__init__.py
sdk/python/lib/test/langhost/inheritance_types/__main__.py
sdk/python/lib/test/langhost/inheritance_types/inheritance_types.py
sdk/python/lib/test/langhost/inheritance_types/pulumi_pkg/__init__.py
sdk/python/lib/test/langhost/inheritance_types/pulumi_pkg/mod/__init__.py
sdk/python/lib/test/langhost/inheritance_types/pulumi_pkg/mod/outputs.py
sdk/python/lib/test/langhost/inheritance_types/pulumi_pkg/mod/resource.py

We were only looking at the current resource class's type/name metadata for camelCase <=> snake_case property name translations which prevented it from working correctly when using a subclass of a resource. This change addresses this by looking at metadata of the current class and any base classes.
Additionally, to help resolve forward references when getting type hints, we'd pass along the current resource class's globals, which doesn't work correctly when using a subclass of a resource. This change also addresses this, by using the globals of the current class and any base classes.
Fixes #6850

[sdk/python] Address issues when using resource subclasses

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/runtime/rpc.py
sdk/python/lib/test/langhost/input_type_mismatch/__init__.py
sdk/python/lib/test/langhost/input_type_mismatch/__main__.py
sdk/python/lib/test/langhost/input_type_mismatch/test_input_type_mismatch.py

Pulumi 3.0 raises an error when a dict value is passed as an input but the type annotation does not accept a dict. Unfortunately, this prevents historical cases where a dict value is allowed but the type annotation doesn't match. We need to fix the type annotations, but in the meantime, we should not raise an error in the SDK for such cases as it breaks existing programs.
Fixes #6818
Fixes https://github.com/pulumi/pulumi-kubernetes/issues/1541

[sdk/python] Don't error when dict input value has a mismatched type

---

CHANGELOG_PENDING.md
sdk/go/common/workspace/plugins.go

This commit makes it possible to opt out of loading plugins from `PATH` by setting `PULUMI_IGNORE_AMBIENT_PLUGINS` to any non-empty value. This is useful when automatic IDE tooling may build remote component plugins into `GOBIN` unbeknownst to the user, and a resulting stale version of the plugin is loaded in place of newer versions - even those , explicitly installed.
No existing test coverage of plugin loading as far as I can tell.

[plugins] Allow opt out of loading plugins on PATH

---

sdk/nodejs/tests/automation/data/tcfg/Pulumi.yaml
sdk/nodejs/tests/automation/localWorkspace.spec.ts

Fixes a flakey test by using a local file backend to avoid interop in the service.
Fixes https://github.com/pulumi/pulumi/issues/6945

Use local backend for concurrency test

---

sdk/go/common/workspace/plugins.go

As a followup to #6944, we needed to invert the check for the
Env var that skips the ambient plugins on the PATH

Small change to the logic around ambient plugins on the PATH

---

CHANGELOG_PENDING.md
pkg/engine/diff.go

Fixes: #6934
With this snippet of code:
```
func main() {
pulumi.Run(func(ctx *pulumi.Context) error {
// Create an AWS resource (S3 Bucket)
vpc, err := ec2.NewVpc(ctx, "main", &ec2.VpcArgs{
CidrBlock: pulumi.String("10.0.0.0/16"),
})
return err
}
rt, err := ec2.NewRouteTable(ctx, "example", &ec2.RouteTableArgs{
VpcId: vpc.ID(),
})
// Export the name of the bucket
ctx.Export("rt", rt)
return nil
})
}
```
the CLI would panic on the diff as follows:
```
panic: fatal: An assertion has failed
goroutine 249 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
/private/tmp/pulumi-20210422-70582-1bpvlru/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assert(...) …
```

Ensure ResourceReference is included in printPropertyValue

---

pkg/codegen/docs/gen_test.go
pkg/codegen/docs/templates/constructor_args.tmpl
pkg/codegen/docs/templates/enums.tmpl
pkg/codegen/docs/templates/properties.tmpl
pkg/codegen/internal/test/testdata/external-resource-schema/docs/cat.md
pkg/codegen/internal/test/testdata/external-resource-schema/docs/component.md
pkg/codegen/internal/test/testdata/external-resource-schema/docs/provider.md
pkg/codegen/internal/test/testdata/external-resource-schema/docs/workload.md
pkg/codegen/internal/test/testdata/simple-enum-schema/docs/provider.md
pkg/codegen/internal/test/testdata/simple-enum-schema/docs/tree/v1/nursery.md
pkg/codegen/internal/test/testdata/simple-enum-schema/docs/tree/v1/rubbertree.md
pkg/codegen/internal/test/testdata/simple-plain-schema/docs/component.md
pkg/codegen/internal/test/testdata/simple-plain-schema/docs/provider.md
pkg/codegen/internal/test/testdata/simple-resource-schema/docs/otherresource.md
pkg/codegen/internal/test/testdata/simple-resource-schema/docs/provider.md
pkg/codegen/internal/test/testdata/simple-resource-schema/docs/resource.md

Resources with properties without `.Comment` values are rendered with empty lines, which breaks Markdown rendering, so this change just removes any leading and trailing whitespace.
Fixes https://github.com/pulumi/docs/issues/5904.

Remove leading and trailing whitespace in resource properties

---

pkg/codegen/go/gen_program_expressions.go
pkg/codegen/go/gen_program_inputs.go
pkg/codegen/go/gen_program_test.go
pkg/codegen/hcl2/binder_schema.go
pkg/codegen/hcl2/model/type_const.go
pkg/codegen/hcl2/model/type_eventuals.go
pkg/codegen/hcl2/model/type_opaque.go
pkg/codegen/hcl2/model/type_union.go
pkg/codegen/hcl2/rewrite_convert.go
pkg/codegen/internal/test/host.go
pkg/codegen/internal/test/providers.go
pkg/codegen/internal/test/testdata/azure-native.json
pkg/codegen/internal/test/testdata/azure-native.pp
pkg/codegen/internal/test/testdata/azure-native.pp.cs
pkg/codegen/internal/test/testdata/azure-native.pp.go
pkg/codegen/internal/test/testdata/azure-native.pp.py
pkg/codegen/internal/test/testdata/azure-native.pp.ts
pkg/codegen/schema/schema.go

Resolves #6392
Needed for https://github.com/pulumi/pulumi-azure-native/issues/549
The scenario that this PR tries to address is when a resource property is a union of several object types. Each object type has a discriminator: a property `Foo` with a const value. Each type has its own const value for that property. See the `azure-native.json` for real-life examples (it's a small subset of the full Azure Native spec).
Two large-ish changes here:
1. Adjust to `RewriteConversions` to exclude object types that don't match the discriminator value of particular input in this program. The program gen can then use the only remaining union case as the schema type for property initialization.
2. Introduce a new HCL type to hold a const value. This is needed to prevent collapsing multiple types …

[codegen] Discriminated unions in programgen

---

CHANGELOG_PENDING.md
pkg/secrets/passphrase/manager.go

Fixes: #6974
Passphrase Environment variables were set before loading the
secrets provider from state
Unfortunately, it seems that some users are using empty passphrases
and thus this newly introduced logic has broken their usecases
We now check that the environment variables are set - it doesn't
matter if they are set as empty, but the existance of an empty
environment variabe still suggests that it is an intentional
empty passphrase

[cli] Prevent regression in loading passphrase secrets provider from state

---

pkg/codegen/internal/test/testdata/external-resource-schema/nodejs/argFunction.ts
pkg/codegen/internal/test/testdata/external-resource-schema/nodejs/cat.ts
pkg/codegen/internal/test/testdata/external-resource-schema/nodejs/component.ts
pkg/codegen/internal/test/testdata/simple-enum-schema/nodejs/tree/v1/nursery.ts
pkg/codegen/internal/test/testdata/simple-enum-schema/nodejs/tree/v1/rubberTree.ts
pkg/codegen/internal/test/testdata/simple-plain-schema/nodejs/component.ts
pkg/codegen/internal/test/testdata/simple-resource-schema/nodejs/argFunction.ts
pkg/codegen/internal/test/testdata/simple-resource-schema/nodejs/otherResource.ts
pkg/codegen/internal/test/testdata/simple-resource-schema/nodejs/resource.ts
pkg/codegen/nodejs/gen.go

This change removes the `readonly` requirement for nodejs resource and function input args. The readonly requirement makes it unnecessarily difficult to do simple things like conditional argument construction:
```ts
let args: ResourceArgs = { someProp: "someValue" }
if (something) {
args.someOtherProp = "someOtherValue"
}
```
I can't think of any way that this would impact or break users. Just seems like we're being overly-conservative here.
Fixes https://github.com/pulumi/pulumi/issues/6106
(no changelog as this shouldn't impact users at all)

Relax readonly requirement for generated nodejs resource args

---

CHANGELOG_PENDING.md
sdk/go/common/resource/config/map_test.go
sdk/go/common/resource/config/value.go

Config values that are objects are represented in memory as JSON strings. When a config map is being saved to a file, object values are first unmarshaled from JSON to `interface{}` and then the entire config map is marshaled to YAML (or JSON) and saved to disk. When an object value is unmarshaled from JSON, any numbers in the JSON string were being implicitly unmarshaled as `float64`, which resulted in some numbers in the nested objects being emitted in YAML using exponent notation (e.g. a number `12321123131` in an object value was being saved in the YAML as `1.2321123131e+10`). To address this, when unmarshaling the JSON for an object value, first try to unmarshal any numbers as `int64`, falling back to `float64`.
Fixes #6787
Running `pulumi config set --path parent.nested 12321123131` …

Config: Avoid emitting integers in objects using exponent notation

---

sdk/python/lib/test/provider/test_server.py

The test changed since it was broken; after changes the async modifier is not even needed. We did not detect test breakage before since it was not running as it was missing the extra async pytest dependency.
Fixes skipped/broken python unit test.

Fix tests that used to be skipped on missing async lib

---

CHANGELOG_PENDING.md
pkg/codegen/python/gen.go
sdk/python/lib/pulumi/_utils.py
sdk/python/lib/test/data/lazy_import_test/__init__.py
sdk/python/lib/test/data/lazy_import_test/x.py
sdk/python/lib/test/test_utils.py

Fixes https://github.com/pulumi/pulumi/issues/7021

Fix issue with lazy_import affecting pulumi-eks

---

sdk/nodejs/tests/automation/localWorkspace.spec.ts

The test in question was running `Stack.createOrSelect` concurrently which modifies global state by setting each stack [as current](https://github.com/pulumi/pulumi/blob/73a66f48ead301bacf1d7d2833c016cf803b57c1/pkg/cmd/pulumi/stack_init.go#L120) which can cause issues. This PR moves the stack creation out of the promise and sets config via the `ws` to avoid the global state corruption cause by `createStack` and `selectStack`.
Fixes https://github.com/pulumi/pulumi/issues/7026
If the test stops being flakey this PR has been successful.

Create stacks serially before setting config concurrently

---

.github/workflows/run-build-and-acceptance-tests.yml

We should ensure that when a command dispatch event comes from a
user contribution, that we are running CI against their code

Checkout for command dispatch events was using master

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi.Automation/WorkspaceStack.cs

This is a nuclear option for the issue of the internal language server web host:
1. Reading `appsettings.json` and causing collision issues if referenced by an ASPNET API
2. Logging ASPNET logs
If we want to include some configuration of the internal web host, such as environment variables, or if we want to conditionally enable the logging or something, we can do that.
Fixes #7020 #6780

[auto/dotnet] - disable language server host logging and appsettings.json check

---

tests/integration/integration_nodejs_test.go

Adding acceptance tests for password less passphrase secret providers

---

CHANGELOG_PENDING.md
pkg/resource/deploy/step.go

Fixes: #4662
Before:
```
Diagnostics:
random:index:RandomPassword (test):
error: Preview failed: refusing to delete protected resource 'urn:pulumi:dev::test-protected-resource::random:index/randomPassword:RandomPassword::test'
pulumi:pulumi:Stack (test-protected-resource-dev):
error: preview failed
```
After:
```
Diagnostics:
pulumi:pulumi:Stack (test-protected-resource-dev):
error: preview failed
random:index:RandomPassword (test):
error: Preview failed: unable to delete resource "urn:pulumi:dev::test-protected-resource::random:index/randomPassword:RandomPassword::test"
as it is currently marked for protection. To unprotect the resource, either remove the protection bit from your Pulumi application or use the command:
`pulumi state unprotect …
```

[cli] Provide user feedback when protected resources can't be deleted

---

sdk/dotnet/Pulumi.Tests/Resources/DictionaryResourceArgsTests.cs
sdk/dotnet/Pulumi/Resources/DictionaryResourceArgs.cs

@lblackstone this should prevent the exception that you are getting from the Kubernetes secret wrapping. I haven't tested it end-to-end though because your original commit doesn't seem to exist anymore. There's a chance something would go wrong at a later stage. I'm happy to collaborate further on that one.

Allow outputs in dictionary resource args

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi.Automation/Serialization/CancelEventModel.cs
sdk/dotnet/Pulumi.Automation/Serialization/EngineEventModel.cs

Fixes #7047 
Unfortunately the problem only happens when using .NET 5 so writing a suitable test currently is not possible afaik. I verified the change locally by using a minimal .NET 5 program and then calling `PreviewAsync` with the provided `OnEvent`-callback. Without the change the same error occurs as described in #7047. With the change the deserialization works as expected.

[auto/dotnet] Fix deserialization of CancelEvent in .NET 5

---

CHANGELOG_PENDING.md
pkg/codegen/python/gen.go

This commit adds a fallback for the README definition in the generated setup.py files for Python SDKs, thus allowing editable installs of packages which not yet been built.
Codegen tests do not appear to test setup.py generation.

Allow editable installs of dev Python packages

---

.github/workflows/release.yml
.goreleaser.yml

The Windows binary didn't upload to S3 during the release. We had to
ask our ops team to do this - this fixes that issue

Fix 2 small release issues with regards to uploading binaries to S3

---

.github/workflows/command-dispatch.yml
.github/workflows/pr.yml
.github/workflows/run-codegen-test.yml
.github/workflows/run-docs-generation.yml

Fixes: #7099
PRs from maintainers will work as normal - PRs from the community
can now be triggered with command dispatch events

Add ability to test downstream codegen and docsgen from PRs

---

pkg/codegen/schema/schema.go

Following pulumi/pulumi-terraform-bridge#347, properties are generated for all provider config matching the inputs. Unfortunately this does not work for complex values generally (not only in bridged providers) since values are JSON serialized.
While a proper solution to this is designed, it's sufficient for now to stop generating non-primitive properties, which this commit does.
Following pulumi/pulumi-terraform-bridge#347, the following schema diff is produced for `pulumi-aws`:
```diff
diff --git a/provider/cmd/pulumi-resource-aws/schema.json b/provider/cmd/pulumi-resource-aws/schema.json
index 4b9553258..72bdfca93 100644
--- a/provider/cmd/pulumi-resource-aws/schema.json
+++ b/provider/cmd/pulumi-resource-aws/schema.json
@@ -148781,6 +148781,93 @@
},
"provider": {
"description": "The …
```

Omit non-primitive provider properties from code-gen

---

CHANGELOG_PENDING.md
sdk/nodejs/automation/stack.ts
sdk/nodejs/package.json

A few users have reported a failure when running `Stack.preview()` due to JSON failing to parse. Unfortunately, the error message wasn't really telling us what the actual issue was, but we were able to get some more details by adding debugging logging and getting some help from users.
I traced this issue back to the split2 library, where incomplete lines might be dropped. This could happen if the logfile is polled when a message is being written, resulting in a half-formed JSON line. I've replaced it using [Readline](https://nodejs.org/docs/latest-v14.x/api/readline.html#readline_readline). I've also added additional error logging in case we see these errors again.
Fixes: https://github.com/pulumi/pulumi/issues/6768
This error is difficult to test as it is intermittent, but the existing …

[auto/nodejs] - Reimplement JSON event parsing with Readline

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
sdk/dotnet/Pulumi/Config.cs
sdk/go/auto/local_workspace_test.go
sdk/go/pulumi/config/get.go
sdk/go/pulumi/templates/config-get.go.template
sdk/nodejs/config.ts
sdk/nodejs/tests/automation/localWorkspace.spec.ts
sdk/python/lib/pulumi/config.py
sdk/python/lib/test/automation/test_local_workspace.py
tests/integration/integration_dotnet_test.go
tests/integration/integration_go_test.go
tests/integration/integration_nodejs_test.go
tests/integration/integration_python_test.go

Temporarily disable the new config secret warning to avoid unactionable warnings from provider `config` modules. We'll re-enable the warning when we've addressed that issue.
Fixes #7126

Temporarily disable config secrets warning

---

CHANGELOG_PENDING.md
pkg/engine/plugins.go
sdk/go/common/workspace/plugins.go

We currently send plugin install output to stdout. This interferes
with --json (#5747), automation API scenarios, and in general is bad
CLI hygiene. This change sends plugin output to stdout instead.
Two questions:
1. Is there a reason this isn't the preferred fix? I can easily believe
so, since we were exploring alternative ideas in the linked issue.
2. How should I test this? Where are the current plugin installation
test cases? I clearly can't add a dependency on AWS here -- is
there a "simpler" plugin that I can install for test purposes?

Send plugin install output to stderr

---

pkg/codegen/python/gen_resource_mappings.go
pkg/codegen/python/gen_resource_mappings_test.go

Currently the JSON literals generated for Python codegen do not have consistent ordering of list elements. This is unfortunate for our CI as repeat builds generate code diffs. The fix sorts the data before splicing it into JSON.

Fix non-deterministic ordering of generated Python code

---

sdk/nodejs/runtime/rpc.ts

I was looking at some program traces and noticed hundreds of calls to `/pulumirpc.Engine/Log`. When I remove debug logs for duplicate resource registrations, this basic program cuts it's runtime from 10s down to 3s.
```ts
import * as aws from "@pulumi/aws";
import * as kubernetes from "@pulumi/kubernetes";
console.log(aws);
console.log(kubernetes);
export const foo = {};
```
Looking at the traces, there are ~800 logging calls for duplicate registrations, each of which is an RPC request to the engine. This change puts those specific logging calls behind the excessive debug flag. Perhaps in theory this shouldn't be a problem, and we should be able to handle these logging requests but it does appear to be creating perf problems for the most basic of programs. 
No tests or …

put nodejs resource registration logs behind excessiveDebugOutput flag

---

pkg/codegen/dotnet/gen_test.go
pkg/codegen/go/gen.go
pkg/codegen/go/gen_test.go
pkg/codegen/internal/test/testdata/external-resource-schema/docs/cat.md
pkg/codegen/internal/test/testdata/external-resource-schema/docs/component.md
pkg/codegen/internal/test/testdata/external-resource-schema/dotnet/Component.cs
pkg/codegen/internal/test/testdata/external-resource-schema/dotnet/Inputs/PetArgs.cs
pkg/codegen/internal/test/testdata/external-resource-schema/go/example/component.go
pkg/codegen/internal/test/testdata/external-resource-schema/go/example/pulumiTypes.go
pkg/codegen/internal/test/testdata/external-resource-schema/nodejs/component.ts
pkg/codegen/internal/test/testdata/external-resource-schema/nodejs/types/input.ts
pkg/codegen/internal/test/testdata/external-resource-schema/python/pulumi_example/_inputs.py
pkg/codegen/internal/test/testdata/external-resource-schema/python/pulumi_example/component.py
pkg/codegen/internal/test/testdata/external-resource-schema/schema.json
pkg/codegen/nodejs/gen_test.go

In Go, resource types are modeled as pointers, but there were cases where the type was not being emitted as a pointer, leading to marshaling errors in programs. Additionally, array and map values that are external references were being emitted as pointers, but only _resources_ should be pointers (not external types), regardless of whether the resource type is external or local.
This fixes the underlying Go marshaling issues with https://github.com/pulumi/pulumi-eks/issues/566 and @lblackstone's repro in https://github.com/pulumi/pulumi-eks/issues/577
Part of https://github.com/pulumi/pulumi-eks/issues/566
Part of https://github.com/pulumi/pulumi-eks/issues/577

[codegen/go] Fix emitted type of resources and types

---

pkg/backend/httpstate/client/client.go
sdk/go/common/apitype/policy.go

As you know Pulumi Service supports [self-hosted](https://www.pulumi.com/docs/guides/self-hosted/) options. This means a customer can self-host Pulumi Service on Azure. For policy pack publishing to work with Azure Storage, the signed URL retrieved from the service must have a header called `x-ms-blob-type` that is set to `BlockBlob`. This is an exception with Azure Storage only. Since the header is a custom header only used by Azure Storage service, it is safe to include it for all of them.
Fixes `N/A`
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~ I have not added a test to this repo but we do have a test in the service that exercises this for signed URLs.

Support using pre-signed URLs for Azure Storage issued by the Pulumi Service

---

CHANGELOG_PENDING.md
sdk/nodejs/automation/stack.ts

I had thought this issue was resolved, but alas it is not.
In the absence of a repro, I've decided to remove the error on this line and change it to a warning. In most cases all we need is the summary event from the preview (when a user hasn’t provided an onEvent callback), and it seems more reasonable to only error if we are unable to get the summary rather than if we are unable to read any random event. Hopefully this warning will allow us to gather more data on the issue if it continues to pop up, but at the very least folks who are not using `onEvent` will be able to let their programs complete without error.
Related to: https://github.com/pulumi/pulumi/issues/6768

[automation/nodejs] - Only log, don't error on unparsed events

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/output.py
sdk/python/lib/test/test_output.py

These mutually recursive functions unintentionally had exponential complexity in nesting depth of objects, arg types and most likely arrays.
Remove the exponential complexity by avoiding direct recursion of `from_input` on itself, and relying on mutual recursion with `all` alone to reduce nested substructure.
Also simplify the implementation to aid readability.
Fixes pulumi/pulumi-kubernetes#1597.
Fixes pulumi/pulumi-kubernetes#1425.
Fixes pulumi/pulumi-kubernetes#1372.
Fixes #3987.

[sdk/python] Avoid exponential complexity for `from_input`/`all`

---

pkg/backend/httpstate/policypack.go
pkg/cmd/pulumi/new.go
sdk/go/common/workspace/plugins.go
sdk/nodejs/npm/npm.go
sdk/nodejs/npm/npm_test.go

This change skips installation of `devDependencies` by running  `yarn install --production` or `npm install --production` when installing pulumi plugins that specify the `nodejs` runtime via `PulumiPlugin.yaml`. 
In my tests, this results in a 35% reduction in size (my plugins include typescript as a dev dep) from `230MB` -> `150MB`. 
Contributes to https://github.com/pulumi/pulumi/issues/7182
Not a user facing features, simply an optimization.

skip installing dev dependencies for nodejs plugin setup

---

.github/PULL_REQUEST_TEMPLATE.md
pkg/backend/httpstate/client/api.go

It ensures users are using a CLI version that supports publishing policy packs to Azure Storage.
Fixes # `N/A`
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~ Bumping the service API version.
~~- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change~~

Bump the Pulumi Service API version header to 7

---

CHANGELOG_PENDING.md
pkg/codegen/go/gen.go
pkg/codegen/internal/test/testdata/external-resource-schema/go/example/init.go
pkg/codegen/internal/test/testdata/simple-enum-schema/go/plant/init.go
pkg/codegen/internal/test/testdata/simple-enum-schema/go/plant/tree/v1/init.go
pkg/codegen/internal/test/testdata/simple-plain-schema-with-root-package/go/init.go
pkg/codegen/internal/test/testdata/simple-plain-schema/go/example/init.go
pkg/codegen/internal/test/testdata/simple-resource-schema/go/example/init.go

This commit fixes a govet warning and generated code that uses a formatting directive with
`fmt.Println`, when it should be `fmt.Printf` instead.

Fix Go init.go codegen to be govet compliant

---

CHANGELOG_PENDING.md
pkg/engine/deployment.go

Fixes: #6990
Previously:
```
pulumi import aws:ec2/instance/Instance id-12345 test-instance
Previewing import (dev)
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   3.4.0-alpha.1622658772+dbea8058.dirty
Go Version:       go1.16.4
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            fatal: An assertion has failed: Module member token 'aws:ec2/instance/Instance' missing module member delimiter
```
After:
```
pulumi import aws:ec2/instance/Instance …
```

[cli] Protect against panic when using incorrect token type in pulumi import

---

CHANGELOG_PENDING.md
pkg/codegen/dotnet/gen.go
pkg/codegen/internal/test/testdata/simple-plain-schema/docs/component.md
pkg/codegen/internal/test/testdata/simple-plain-schema/dotnet/Component.cs
pkg/codegen/internal/test/testdata/simple-plain-schema/dotnet/Inputs/FooArgs.cs
pkg/codegen/internal/test/testdata/simple-plain-schema/go/example/component.go
pkg/codegen/internal/test/testdata/simple-plain-schema/go/example/pulumiTypes.go
pkg/codegen/internal/test/testdata/simple-plain-schema/nodejs/component.ts
pkg/codegen/internal/test/testdata/simple-plain-schema/python/pulumi_example/component.py
pkg/codegen/internal/test/testdata/simple-plain-schema/schema.json

Fix the generated C# code for plain properties:
- Value types should not be initialized with `= null!`
- Arrays and maps should be `List<T>` and `Dictionary<string, TValue>`
Fixes #6813
Fixes #7092

[codegen/dotnet] Fix plain properties

---

.github/workflows/run-codegen-test.yml

Fixes: #7218
Changes that propagated from the pulumi codebase to the providers
conflicted with dep versions already in place - the provider tests
needed to have a `go mod tidy` command rather than a `go mod download`
This will clean the unused dependencies that were causing the conflict
and thus the build failure

[build] ensure downstream codegen tests run go mod tidy

---

CODE-OF-CONDUCT.md

This adds to the scope of the Code of Conduct to be inclusive of GitHub Discussions forum as well as the Community Slack 
Signed-off-by: Matt Stratton <matt.stratton@gmail.com>
This adds to the scope of the Code of Conduct to be inclusive of GitHub Discussions forum as well as the Community Slack
There are no required tests for this change.

Update CoC to include GH Discussions and Slack

---

sdk/go/common/resource/plugin/rpc.go
sdk/go/common/resource/plugin/rpc_test.go

Fixes #7132 
MarshalPropertyValue code says:
```
return nil, nil // return nil and the caller will ignore it.
```
But this particular call site does not ignore `nil`. This has caused panics far away from the source of the problem.
The fix ignores the nil inside the list context.
If this is against the spirit of removing unknowns, we should fail loudly instead.
I don't as of today have a valid Pulumi user program that hits this; the example I was going off is not valid.

Fix MarshalProperties handling of list-nested unknowns

---

pkg/backend/watch.go

We were trimming trailing newlines from log messages in `pulumi logs` but not in `pulumi watch`.  The latter was seeing many empty lines in logs as a result of this.  This change consistently trims trailing newlines in all log rendering.

Render logs consistently in watch and logs

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/output.py
sdk/python/lib/test/test_output.py

Fixes #7252.
Subtly, `Output.all(**{})` by design returns `Output([])`, because the `all` function itself cannot distinguish between this and `Output.all()`.  So we must special case empty dicts to avoid calling `all` on them.
We were missing tests for empty arrays and dicts, so these have been added.

Ensure `Output.from_input({})` returns `{}` instead of `[]`

---

pkg/codegen/internal/test/testdata/schema/bad-methods-1.json
pkg/codegen/internal/test/testdata/schema/bad-methods-2.json
pkg/codegen/internal/test/testdata/schema/bad-methods-3.json
pkg/codegen/internal/test/testdata/schema/bad-methods-4.json
pkg/codegen/internal/test/testdata/schema/bad-methods-5.json
pkg/codegen/internal/test/testdata/schema/bad-methods-6.json
pkg/codegen/internal/test/testdata/schema/good-methods-1.json
pkg/codegen/schema/schema.go
pkg/codegen/schema/schema_test.go

The implementation of this is based on what was outlined in the original design doc.
One question I had while implementing this: Why not add the method definitions directly in the resource's `"methods"` section instead of referencing functions defined in the top-level `"functions"` section?
Part of #7072

Add schema support for methods

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/import.go

This PR is to handle a panic that is caused by a failure during go codegen when using the `pulumi import` command. Unfortunately, `import` is impossible to write tests for since it is dependent on a resource existing in a provider. The [original PR](https://github.com/pulumi/pulumi/pull/4765) to add the import command included no tests.
I have also been unable to repro this particular failure manually since I do not have the correct access to use the `PushRestrictions` feature for `BranchProtection` in Github as I do not have an organization using the team or enterprise tiers.
I tested this change by manually adding a panic to the `generateImportedDefinitions` function and observing the resulting output. 
Related to: #7112

[cli/import] - Handle panic during import codegen

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
sdk/dotnet/Pulumi.Automation.Tests/Pulumi.Automation.Tests.csproj
sdk/dotnet/Pulumi.Automation.Tests/xunit.runner.json
sdk/dotnet/Pulumi.Automation/LocalWorkspace.cs
sdk/dotnet/Pulumi.Automation/LocalWorkspaceOptions.cs
sdk/dotnet/Pulumi.Automation/PreviewOptions.cs
sdk/dotnet/Pulumi.Automation/PublicAPI.Shipped.txt
sdk/dotnet/Pulumi.Automation/Pulumi.Automation.xml
sdk/dotnet/Pulumi.Automation/Runtime/LanguageRuntimeService.cs
sdk/dotnet/Pulumi.Automation/UpOptions.cs
sdk/dotnet/Pulumi.Automation/Workspace.cs
sdk/dotnet/Pulumi.Automation/WorkspaceStack.cs
sdk/dotnet/Pulumi.Tests/xunit.runner.json
sdk/dotnet/Pulumi/Core/Output.cs
sdk/dotnet/Pulumi/Deployment/Deployment.EnginerLogger.cs
sdk/dotnet/Pulumi/Deployment/Deployment.Runner.cs
sdk/dotnet/Pulumi/Deployment/Deployment.cs
sdk/dotnet/Pulumi/Deployment/Deployment_Inline.cs
sdk/dotnet/Pulumi/Deployment/Deployment_RegisterResourceOutputs.cs
sdk/dotnet/Pulumi/Deployment/IDeploymentInternal.cs
sdk/dotnet/Pulumi/Deployment/IEngineLogger.cs
sdk/dotnet/Pulumi/Deployment/InlineDeploymentSettings.cs
sdk/dotnet/Pulumi/Pulumi.csproj

[dotnet/sdk] Support microsoft logging extensions with inline programs

---

CHANGELOG_PENDING.md
pkg/codegen/python/gen.go

Every time a resource is created (without an explicit provider version specified), `_utilities.get_version()` is called to determine the package version. This call is expensive and can measurably impact performance, especially for programs with many resources. This change caches the value so it is only determined once.
This shaved off ~12 seconds from the following program:
```python
from pulumi_aws import s3
bucket = s3.Bucket("mybucket")
for x in range(5000):
s3.BucketObject(f"{x}", bucket=bucket.id, content="hello")
```
Fixes #7291

[codegen/python] Cache the package version

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/runtime/resource.py
sdk/python/lib/pulumi/runtime/rpc.py
sdk/python/lib/pulumi/runtime/settings.py

`log.debug` messages are part of an update and get sent to the service. Reducing the number of `log.debug` calls can significantly improve the performance of a program. This commit changes the debug logging in the Python SDK to be similar to the debug logging in the Node.js SDK.
- An `excessive_debug_output` variable has been added (that can be set to `True` during debugging), but otherwise will avoid a large number of `log.debug` calls.
- Some unhelpful/redundant `log.debug` calls have been deleted.
Fixes #7292
---
The following program run with `pulumi preview` (plus the fix from #7293):
```python
from pulumi_aws import s3
bucket = s3.Bucket("mybucket")
for x in range(5000):
s3.BucketObject(f"{x}", bucket=bucket.id, content="hello")
```
Duration Before: 35.8 seconds
Duration After: 6.35 …

[sdk/python] Reduce `log.debug` calls for improved performance

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/output.py
sdk/python/lib/test/test_output.py

Although `Output` objects can never correctly support iteration, Python will see the implementation of `__getitem__` and try to iterate the object, leading to an infinite loop.  To prevent this, we need to explicitly implement `__iter__` and make it return a `TypeError` to prevent iteration (and offer a useful error message).
Fixes #5028.

[sdk/python] Ensure Output objects are not iterable

---

pkg/codegen/hcl2/binder.go
pkg/codegen/hcl2/binder_schema.go

Add an option to allow missing object properties. This will prevent us
from losing examples once resource typechecking is fixed (it is
currently unintentionally disabled because the resource inputs object
type has an unexpected shape).

[codegen/pcl] Allow missing object properties.

---

pkg/codegen/hcl2/binder.go
pkg/codegen/hcl2/binder_resource.go

More testing has found further issues with incorrect attribute shapes
generated by tf2pulumi. This knob will allow us to continue to generate
examples until those bugs are fixed.

Add an option to skip resource typechecking.

---

pkg/testing/integration/program.go
sdk/go/common/util/cmdutil/trace.go
sdk/nodejs/runtime/rpc.ts

I'm finding I need a few more hooks to enable trace collections easily in the integration tests. Everything in this PR is opt-in. If you don't set the magic env vars nothing should be affected for our regular users.
- Allows to run ProgramTest with `Tracing: "file:./pulumi-{command}.trace` resulting in multiple files depending on which command is being traced.
- Allows to set PULUMI_TRCING_TAG_FOO env vars to add tags to the top-level trace span
- Allows to set PULUMI_TRACING_MEMSTATS_POLL_INTERVAL=100ms to poll runtime.ReadMemStats and record in the trace
- Records os, arch, num_cpu in the trace

Tracing enhancements for CLI perf metrics capture

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
sdk/dotnet/Pulumi.Automation/Commands/LocalPulumiCmd.cs
sdk/dotnet/Pulumi.Automation/Runtime/LanguageRuntimeService.cs
sdk/dotnet/Pulumi.Automation/WorkspaceStack.cs

This resolves the issue of resources being destroyed after an exception is thrown during an inline program. The gRPC portion of the Automation API implementation is now correctly returning in the error case and the `WorkspaceStack` instance is now conditionally throwing the relevant exception if an inline exception is present, that way the correct exception bubbles up to the Automation API consumer.
Fixes #7050

[sdk/dotnet] - bug fix resources destroyed after exception thrown during inline program

---

pkg/codegen/schema/schema.go

The `bad-methods-2.json` test ensures there is an error when trying to use a function as a method twice.
The schema looks like:
```json
"methods": {
"bar": "xyz:index:Foo/bar",
"baz": "xyz:index:Foo/bar"
}
```
And the expected error is:
> function xyz:index:Foo/bar for method baz is already a method
However, when the schema is unmarshalled into a map, the keys in the map are unordered (just as JSON keys in objects are unordered), so occaisonally we'd see an error mentioning method `bar` rather than `baz`:
> function xyz:index:Foo/bar for method bar is already a method
To address this, we'll fix the portion of the code that is generating the error to walk the map in a deterministic order, and we'll also return the list of methods in the same deterministic order as well.
Fixes #7298

[codegen/schema] Fix intermittent failing test

---

CHANGELOG_PENDING.md
pkg/backend/backend.go
pkg/backend/filestate/backend.go
pkg/backend/filestate/stack.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/stack.go
pkg/backend/mock.go
pkg/backend/stack.go
pkg/backend/watch.go
pkg/cmd/pulumi/watch.go

Closes https://github.com/pulumi/pulumi/issues/6620
As mentioned in the linked issue, currently, the `pulumi watch` command watches the entire Pulumi project directory (recursively). With this PR, developers will be able to specify the exact paths that need to be watched.
The main motivation for this came from the fact that in our project, the application code (so, not infrastructure code) folder is located within the Pulumi project folder. Now, this wouldn't be a problem if we didn't bundle our application code with Webpack.  
This means that, while writing application code, the re-deploy process gets triggered by the `watch` command twice:
1. once for the change that the developer made in the source application code
2. once after Webpack has actually built the change, and stored the new …

Watch Command - Added `--path` Argument

---

sdk/go/pulumi/types.go

This commit moves from simply asserting on the assignability of types to using Assertf to print the types in question. This provides more information to a user whose code is panicking because of non-assignability.
Ultimately it would likely be better to surface this via error messages instead of via panic, but this at least improves the debuggability in the meantime.

Print actionable information on assertion failure

---

pkg/backend/watch_darwin_arm64.go

https://github.com/pulumi/pulumi/pull/7247 added the ability to specify paths in `pulumi watch`, but this PR didn't update the alternative handling we have for `darwin/arm64` where `watch` isn't supported. This led to a [failure](https://github.com/pulumi/pulumi/runs/2878255663?check_suite_focus=true#step:8:77) in p/p master.
This PR corrects the issue by updating the darwin/arm64 function signature.

Fix watch command in macos arm64 builds

---

pkg/codegen/python/gen.go

Fixes: https://github.com/pulumi/pulumi-aws/issues/1519
There is a realistic change that a mapped property is called `resource_name` and
this would conflict with the internal property `resource_name`.
Mypy reports an sdk error here:
```
dk/python/pulumi_aws/servicecatalog/tag_option_resource_association.py:277: error: Duplicate argument 'resource_name' in function definition
Found 1 error in 1 file (errors prevented further checking)
```
It's better to move the python internal property to something that
won't conflict, `resource_name_` in this case

[codegen/python] Update Python codegen to use a non-conflicting property name

---

CHANGELOG_PENDING.md
sdk/nodejs/automation/server.ts
sdk/nodejs/runtime/settings.ts
sdk/nodejs/tests/automation/localWorkspace.spec.ts

This change detects when nodejs automation api inline programs load multiple instances of `@pulumi/pulumi` and triggers an early failure with a helpful error message:
```console
pulumi:pulumi:Stack (inlineNode-dev):
error: Unhandled exception: Error: Detected multiple versions of '@pulumi/pulumi' in use in an inline automation api program
Use the yarn 'resolutions' field to resolve this: https://github.com/pulumi/pulumi/issues/5449.
```
Using multiple versions of pulumi/pulumi in inline programs can cause collisions in global state. Until we address https://github.com/pulumi/pulumi/issues/5449, inline node automation users need to pin to a single version of pulumi/pulumi to avoid issues like those seen in https://github.com/pulumi/pulumi/issues/6998
This change set adds a module level …

detect nodejs side by side pulumi for inline automation programs and fail fast

---

sdk/go/common/resource/properties_path.go
sdk/go/common/resource/properties_path_test.go

Related to https://github.com/pulumi/pulumi/issues/6753

[sdk/go] Add Contains method to PropertyPath

---

.goreleaser.yml

This was temporarily disabled due to an issue where an incorrect error
message was received about a 404. This was actually due to not being
able to post to `announcement` style categories
The Releases category was changed to be `open ended discussion` so
we can enable this feature again
see https://github.com/goreleaser/goreleaser/issues/2304 for details

Ensure releases are announced to GitHub discussions

---

CHANGELOG_PENDING.md
Makefile
build.proj
sdk/nodejs/provider/server.ts
tests/integration/construct_component_error_apply/nodejs/.gitignore
tests/integration/construct_component_error_apply/nodejs/Pulumi.yaml
tests/integration/construct_component_error_apply/nodejs/component.ts
tests/integration/construct_component_error_apply/nodejs/index.ts
tests/integration/construct_component_error_apply/nodejs/package.json
tests/integration/construct_component_error_apply/testcomponent/index.ts
tests/integration/construct_component_error_apply/testcomponent/package.json
tests/integration/construct_component_error_apply/testcomponent/pulumi-resource-testcomponent
tests/integration/construct_component_error_apply/testcomponent/pulumi-resource-testcomponent.cmd
tests/integration/construct_component_error_apply/testcomponent/tsconfig.json
tests/integration/integration_nodejs_test.go

The uncaught handler wasn't terminating the outstanding gRPC request causing a hang. This change adds/removes an uncaught handler around constructImpl calls that bubbles the uncaught error back via the gRPC callback. 
Fixes # https://github.com/pulumi/pulumi/issues/6991

Fix a hang in nodejs remote components when an error is thrown within an apply

---

CHANGELOG_PENDING.md
sdk/go/pulumi/provider.go
sdk/go/pulumi/provider_test.go

These changes contain a preliminary fix for #7359 in the Go SDK. The fix
handles input values that are nested one level deep within maps and
arrays, but does not handle other cases of nested input types.

Preliminary fix for #7359.

---

.github/workflows/run-codegen-test.yml

Currently, all downstream codegen test jobs get canceled if just one fails. 
This PR changes the behavior so that some tests may run to completion even if others fail. 
While we strive to always have all of the downstream codegen jobs run to completion, there are occasions where certain providers cannot be updated due to extenuating circumstances. In those situations, it is better to see the result of **some** downstream provider codegen tests rather than none at all.

Turn off fail-fast for codegen tests

---

CHANGELOG_PENDING.md
sdk/nodejs/resource.ts
sdk/nodejs/runtime/invoke.ts
sdk/nodejs/runtime/rpc.ts
tests/integration/construct_component_methods/nodejs/.gitignore
tests/integration/construct_component_methods/nodejs/Pulumi.yaml
tests/integration/construct_component_methods/nodejs/component.ts
tests/integration/construct_component_methods/nodejs/index.ts
tests/integration/construct_component_methods/nodejs/package.json
tests/integration/integration_nodejs_test.go

Support for calling methods from Node.js.
Part of #7072

[sdk/nodejs] Support for calling methods

---

CHANGELOG_PENDING.md
pkg/codegen/go/doc.go
pkg/codegen/go/gen.go
pkg/codegen/go/gen_test.go
pkg/codegen/internal/test/testdata/simple-enum-schema/docs/tree/v1/nursery.md
pkg/codegen/internal/test/testdata/simple-enum-schema/docs/tree/v1/rubbertree.md
pkg/codegen/internal/test/testdata/simple-enum-schema/go/plant/pulumiEnums.go
pkg/codegen/internal/test/testdata/simple-enum-schema/go/plant/pulumiTypes.go
pkg/codegen/internal/test/testdata/simple-enum-schema/go/plant/tree/v1/nursery.go
pkg/codegen/internal/test/testdata/simple-enum-schema/go/plant/tree/v1/pulumiEnums.go
pkg/codegen/internal/test/testdata/simple-enum-schema/go/plant/tree/v1/rubberTree.go

[codegen/go] - Inputty Go enums

---

pkg/codegen/dotnet/gen.go
pkg/codegen/dotnet/gen_test.go

`Input{List,Map}` handle some of this themselves.

[codegen/dotnet] Deeply unwrap collection element types.

---

sdk/go/pulumi/context.go

Mechanical refactor to avoid a 16-element tuple. While fairly local, was a nuisance.

Add a helper record to name fields in a very long tuple

---

Makefile

A number of tests have likely not been running since tags were added to
each test file. This is because `go list` uses build flags when scanning
files, so any pacakges that did not include at least one file that did
not have any tags (read: about half of the integration tests) were not
picked up by the command used in the Makefile to detect tests.

Re-enable tests.

---

pkg/codegen/utilities_test.go
pkg/codegen/utilities_types.go

SimplifyInputUnion was dropping element types that were not inputs.
These changes fix that bug.
Fixes #7454.

[codegen] Fix SimplifyInputUnion.

---

pkg/resource/deploy/source_query.go

Query mode does not fill out the Target field of EvalRunInfo before
booting its resource monitor. These changes fix a recent update to query
mode that attempts to dereference the nil Target.
Note that the missing target is by design, and other portions of the
query infrastructure have identical code to compensate.

[query] Do not access config with a nil Target.

---

pkg/codegen/dotnet/gen_test.go
pkg/codegen/go/gen_test.go
pkg/codegen/internal/test/testdata/types.json
pkg/codegen/internal/test/type_driver.go
pkg/codegen/nodejs/gen_test.go
pkg/codegen/python/gen_test.go
pkg/codegen/schema/schema.go

The inputs and expected outputs for the tests are encoded using a
schema. Each property present in the schema forms a testcase; the
expected outputs for each language are stored in each property's
`Language` field with the language name "test". Expected outputs can be
regenerated using `PULUMI_ACCEPT`.

[codegen] Add type name generation tests.

---

sdk/go/pulumi/context.go
sdk/go/pulumi/rpc_test.go

Based on a conversation in https://github.com/pulumi/pulumi/pull/7437#discussion_r665748931 we might prefer to be strict and fail with an exception in the Go SDK when unknowns are being marshaled in a context that does not expect them. Currently the behavior instead is to filter them out of the data structure. There were issues around this such as https://github.com/pulumi/pulumi/pull/7214
There are many other places in the codebase that have the similar problem, but I only attempt to edit context.go here to keep the change small and see this passes CI checks.

Reject unknowns in context.go when not in preview

---

pkg/cmd/pulumi/policy_new_test.go

Relax errmsg check

---

tests/integration/aliases/aliases_go_test.go
tests/integration/aliases/aliases_nodejs_test.go
tests/integration/aliases/aliases_py_test.go

Let alias tests compile under tags=all

---

CHANGELOG.md
pkg/resource/deploy/step_generator.go
pkg/resource/deploy/step_generator_test.go

The diff rendering logic tests whether the `DetailedDiff` is `nil` to determine whether to use it for rendering or defer to older older supported approaches to computing diffs.
The new logic added in https://github.com/pulumi/pulumi/pull/7226 could lead to replacing a `nil` `DetailedDiff` with an empty `DetailedDiff`, which would make the rendering logic believe that a `DetailedDiff` was present but empty, instead of missing entirely.
This change ensures that we maintain nil-ness of the `DetailedDiff` when we transform it for handling of `replaceOnChanges`.
Also adds tests for this and other cases on `applyReplaceOnChanges`.
Fixes #7486.

Fix rendering of diffs for resource without DetailedDiffs

---

sdk/go/pulumi/rpc.go

This fixes #7504, and is the other half of the interim fix corresponding to #7359. The case listed in #7509 no longer reproduces after this fix is applied.
The change to imports is the result of running `goimports` and is not a functional change.
Fixes #7504.
No automated tests added, but repro case in #7504 no longer reproduces with this fix.
Not a user-facing change.
N/A.

Fix marshaling prompt slices/maps with input elems

---

sdk/go/pulumi/rpc.go

Just what it says on the tin. This code should be made more precise once
7434 is fixed.

Add a TODO.

---

CHANGELOG_PENDING.md
pkg/codegen/go/gen.go
pkg/codegen/go/gen_test.go
pkg/codegen/internal/test/testdata/simple-enum-schema/go/plant/pulumiEnums.go
pkg/codegen/internal/test/testdata/simple-enum-schema/go/plant/tree/v1/pulumiEnums.go

Emit To[ElementType]PtrOutput methods for go enum output types

---

sdk/go/common/apitype/stacks.go

This PR adds an optional `ContinuationToken *string` field to `apitype.ListStacksResponse`. This is the REST API type returned from the Pulumi Service (or any HTTP State backend), and will be used to enable paginating results when running `pulumi stack ls`.
Once checked in, the Pulumi Service will then support a newer variant of the ListStacks API endpoint that will support pagination using this new field. And a follow-up commit into the Pulumi CLI will emit a new `Accept` header value, flagging the Pulumi Service to return stacks in a paginated fashion. (So newer CLIs will take advantage of the newer API semantics, while older clients -- with the older `Accept` header value -- will receive the previous behavior.)
Being an optional field also means that any existing HTTPState backend …

Add ContinuationToken to ListStacksResponse

---

README.md

Adds a link to GitHub Discussions and a GH Discussions badge to the README
No tests required - README change only.
I do not think this needs a CHANGELOG entry

Add GitHub Discussions links to the README

---

pkg/codegen/internal/test/testdata/nested-module-thirdparty/nodejs/deeply/nested/index.ts
pkg/codegen/nodejs/gen.go

This commit fixes code generation for intermediate module paths to produce valid TypeScript identifiers.
Before this change, the following (non-compilable) import was produced in `./jetstack/certmanager/acme`:
```
import * as jetstack/certmanager/acme/v1alpha2 from "./jetstack/certmanager/acme/v1alpha2";
```
After this change, the following import is produced:
```
import * as v1alpha2 from "./v1alpha2";
```
This example is repeated at each level of the module tree. Test expectations are adjusted to reflect this change.
This is not a user-facing change.

Fix Node.js intermediate module import path generation

---

pkg/codegen/go/gen.go
pkg/codegen/internal/test/testdata/external-resource-schema/go/example/component.go

This commit modifies Go program generation to prevent producing array and slice object elements as pointers in args structures, which fails at runtime and does not make sense in any case. For example, in the case of a type defined like this in schema:
```json
"statements": {
"type": "array",
"items": {
"$ref": "/aws/v4.8.0/schema.json#/types/aws:iam/getPolicyDocumentStatement:getPolicyDocumentStatement"
}
},
```
The following (which fails at runtime) was produced before this change:
```go
Statements []*iam.GetPolicyDocumentStatement `pulumi:"statements"`
```
And the following is produced after after this change:
```go
Statements []iam.GetPolicyDocumentStatement `pulumi:"statements"`
```
Test expectations are updated accordingly.
This is not a user-facing change.

Stop producing pointers for map and slice elements

---

pkg/codegen/internal/test/testdata/external-resource-schema/python/setup.py
pkg/codegen/internal/test/testdata/nested-module-thirdparty/python/setup.py
pkg/codegen/internal/test/testdata/nested-module/python/setup.py
pkg/codegen/internal/test/testdata/plain-schema-gh6957/python/setup.py
pkg/codegen/internal/test/testdata/resource-args-python/python/setup.py
pkg/codegen/internal/test/testdata/simple-enum-schema/python/setup.py
pkg/codegen/internal/test/testdata/simple-methods-schema/python/setup.py
pkg/codegen/internal/test/testdata/simple-plain-schema-with-root-package/python/setup.py
pkg/codegen/internal/test/testdata/simple-plain-schema/python/setup.py
pkg/codegen/internal/test/testdata/simple-resource-schema-custom-pypackage-name/python/setup.py
pkg/codegen/internal/test/testdata/simple-resource-schema/python/setup.py
pkg/codegen/python/gen.go

This commit modifies the generation of `setup.py` to use Python variables as the source for the package version and plugin version instead of placeholder strings. This has the effect of making the packages installable via the `-e` flag directly from their source directory rather than requiring a build step, which is useful while developing a plugin and examples in tandem.
Not a user-facing change.

Use variable over placeholder for Python version

---

pkg/codegen/internal/test/testdata/simple-methods-schema/go/example/foo.go
pkg/codegen/internal/test/testdata/simple-methods-schema/nodejs/foo.ts
pkg/codegen/internal/test/testdata/simple-methods-schema/python/pulumi_example/foo.py
pkg/codegen/internal/test/testdata/simple-methods-schema/schema.json
pkg/codegen/nodejs/gen.go

This is the before/after:
```diff
-generateKubeconfig(): pulumi.Output<Foo.GenerateKubeconfigResult> {
+generateKubeconfig(args: Foo.GenerateKubeconfigArgs): pulumi.Output<Foo.GenerateKubeconfigResult> {
```
Fixes #7538

[codegen/nodejs] Fix missing args param

---

pkg/codegen/hcl2/binder.go
pkg/codegen/hcl2/binder_schema.go

When converting a `schema.InputType` to a `model.Type`, calculate the
resolved form of the type in the schema type system rather than the
model type system. The results are semantically identical, but the
number of type objects that are allocated is much smaller b/c
`model.NewOutputType` no longer allocates.
This deserves a little more explanation.
In order to prevent nested outputs and/or promises, `model.NewOutputType`
calculates the resolved form of its argument prior to allocating a new
`OutputType` value. Calculating the resolved form of the argument is a
no-op if the argument is already fully resolved. Therefore, passing in a
fully-resolved schema type prevents `model.NewOutputType` from
calulating the resolved form, and `model.NewOutputType` will only
allocate the `OutputType` …

[codegen/pcl] Allocate fewer type instances.

---

pkg/codegen/go/gen_program.go
pkg/codegen/schema/schema.go

- Track which languages have been imported for a package. If a language
has already been imported, do not re-run its importers.
- Track which package contexts have been loaded in the Go code
generator, and do not reload a context that already exists.
These changes shave a significant amount of time off of codegen in
azure-native.

[codegen/go] Improve codegen performance.

---

CHANGELOG_PENDING.md
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/backend_test.go

Fixes https://github.com/pulumi/pulumi/issues/5564
Now performing `$ ~/go/bin/pulumi login https://api.pulumi.com/` will create entries in `~/.pulumi/credentials.json` without the trailing slash.

Normalize cloud URL during login

---

pkg/codegen/internal/test/testdata/provider-config-schema/python/pulumi_configstation/config/__init__.pyi
pkg/codegen/internal/test/testdata/provider-config-schema/python/pulumi_configstation/config/vars.py
pkg/codegen/python/gen.go

Fixes the type annotations for config variables with default values. In doing this, I realized that some of the existing type annotations were really broken, for instance:
```python
@property
def is_member(self) -> str:
return __config__.get('isMember') or True
```
This will actually return a string or a bool... so the type hint is definitely wrong (and it's also just bizarre behavior). 
I decided to fix the type annotations and corresponding `config.get` functions for primitive types. This seems like a palatable breaking change, not quite going to the extents of the more complex objects which are still tracked in #7493 which would be a more obviously breaking change for users.
Not updating CHANGELOG-PENDING as this is a follow-on from #7447

[codegen/python] - Fix required vs default values in provider config

---

CHANGELOG_PENDING.md
pkg/codegen/internal/test/testdata/external-resource-schema/nodejs/package.json
pkg/codegen/internal/test/testdata/nested-module-thirdparty/nodejs/package.json
pkg/codegen/internal/test/testdata/nested-module/nodejs/package.json
pkg/codegen/internal/test/testdata/provider-config-schema/nodejs/config/vars.ts
pkg/codegen/internal/test/testdata/provider-config-schema/nodejs/package.json
pkg/codegen/internal/test/testdata/resource-args-python/nodejs/package.json
pkg/codegen/internal/test/testdata/simple-enum-schema/nodejs/package.json
pkg/codegen/internal/test/testdata/simple-methods-schema/nodejs/package.json
pkg/codegen/internal/test/testdata/simple-plain-schema-with-root-package/nodejs/package.json
pkg/codegen/internal/test/testdata/simple-plain-schema/nodejs/package.json
pkg/codegen/internal/test/testdata/simple-resource-schema-custom-pypackage-name/nodejs/package.json
pkg/codegen/internal/test/testdata/simple-resource-schema/nodejs/package.json
pkg/codegen/internal/test/testdata/simple-yaml-schema/nodejs/package.json
pkg/codegen/nodejs/gen.go

[codegen/nodejs] - Dynamic provider config getters

---

pkg/codegen/hcl2/model/diagnostics.go
pkg/codegen/hcl2/model/type.go
pkg/codegen/hcl2/model/type_const.go
pkg/codegen/hcl2/model/type_eventuals.go
pkg/codegen/hcl2/model/type_list.go
pkg/codegen/hcl2/model/type_map.go
pkg/codegen/hcl2/model/type_none.go
pkg/codegen/hcl2/model/type_object.go
pkg/codegen/hcl2/model/type_opaque.go
pkg/codegen/hcl2/model/type_output.go
pkg/codegen/hcl2/model/type_promise.go
pkg/codegen/hcl2/model/type_set.go
pkg/codegen/hcl2/model/type_tuple.go
pkg/codegen/hcl2/model/type_union.go

- Lazily produce conversion failure diagnostics. This lowers the
allocation volume and cuts down on execution time by avoiding the
conversion of source and dest types to strings.
- Add a fast path for union conversions that checks if the source type
is identical to any of the union's element types. Type equality
checks are generally much faster than type conversion checks.
These changes lead to a significant speedup in codegen time in
azure-native.

[codegen/hcl2] Improve ConversionFrom perf.

---

pkg/codegen/internal/test/testdata/external-resource-schema/docs/argfunction/_index.md
pkg/codegen/internal/test/testdata/external-resource-schema/docs/cat/_index.md
pkg/codegen/internal/test/testdata/external-resource-schema/docs/component/_index.md
pkg/codegen/internal/test/testdata/external-resource-schema/docs/workload/_index.md
pkg/codegen/internal/test/testdata/external-resource-schema/nodejs/argFunction.ts
pkg/codegen/internal/test/testdata/external-resource-schema/nodejs/cat.ts
pkg/codegen/internal/test/testdata/external-resource-schema/nodejs/component.ts
pkg/codegen/internal/test/testdata/external-resource-schema/nodejs/types/input.ts
pkg/codegen/internal/test/testdata/external-resource-schema/nodejs/types/output.ts
pkg/codegen/internal/test/testdata/external-resource-schema/nodejs/workload.ts
pkg/codegen/internal/test/testdata/plain-schema-gh6957/docs/staticpage/_index.md
pkg/codegen/internal/test/testdata/plain-schema-gh6957/nodejs/staticPage.ts
pkg/codegen/internal/test/testdata/simple-methods-schema/nodejs/foo.ts
pkg/codegen/nodejs/gen.go
pkg/codegen/nodejs/importer.go

This pull request includes two related changes - the second builds upon the first.
1. Allow non-pulumi imports for Node.js
Currently the code generator is assuming that Node.js dependencies are following a naming scheme that is prefixed with `@pulumi/`. If this is not the case the generated import statement is incorrect.
This commit adds a map `ProviderNameToModuleName` to the language definition that allows you to map the name of the extracted provider of a dependency to a module name that the generator now uses to create the import statement.
2.  Prepend "pulumi" to import names in Node.js SDK
It is common when writing multi-language components to have a module name which conflicts with a provider name. This can produce unusable code, since you cannot simultaneously import a package as …

Update package import handling for Node.js

---

pkg/codegen/internal/test/testdata/azure-native.pp.py
pkg/codegen/internal/test/testdata/kubernetes-operator.pp.py
pkg/codegen/internal/test/testdata/kubernetes-template.pp.py
pkg/codegen/python/gen_program.go
pkg/codegen/python/gen_program_test.go
pkg/codegen/python/python.go

- Only build casing tables once per package
- Right-size buffers in name generation
These changes lead to a significant speedup in example gen for
azure-native.

[codegen/python] Improve program gen perf.

---

CHANGELOG.md
sdk/dotnet/Pulumi/Deployment/Deployment_Prepare.cs
sdk/dotnet/Pulumi/Resources/ComponentResource.cs
sdk/nodejs/resource.ts
sdk/nodejs/runtime/resource.ts
tests/integration/integration_dotnet_test.go
tests/integration/integration_go_test.go
tests/integration/integration_nodejs_test.go
tests/integration/integration_python_test.go

When a resource `dependsOn` a remote component, we were not correctly waiting on it, because we were skipping over waiting on components, and only waiting on their custom resource children.  For remote components, we do not know the children, but waiting on the remote component will always wait on all children.
This fixes the Node.js and .NET SDKs which both contain this approach to collecting transitive dependencies.  The Go and Python SDKs use a different approach which did not have this bug. https://github.com/pulumi/pulumi/issues/7542 is tracking aligning the implementations as a follow-up.
Fixes #7540.

[sdk] Wait on remote component dependencies

---

build.proj
sdk/dotnet/Makefile

This should avoid occasional errors like:
```
attempting to find a local Pulumi NuGet package yielded [/opt/pulumi/nuget/Pulumi.3.8.0-alpha.1626397740.nupkg /opt/pulumi/nuget/Pulumi.3.8.0-alpha.1626408887.nupkg] results
```
When there are more then one versions leftover from prior builds.
@stack72, I noticed `dotnet clean` was already in the Makefile, but commented out. Any downside you're aware of to uncommenting?

[sdk/dotnet] Clean obj & bin dirs when building

---

pkg/codegen/dotnet/templates.go
pkg/codegen/internal/test/testdata/external-resource-schema/dotnet/Pulumi.Example.csproj
pkg/codegen/internal/test/testdata/nested-module-thirdparty/dotnet/Pulumi.Foo-bar.csproj
pkg/codegen/internal/test/testdata/nested-module/dotnet/Pulumi.Foo.csproj
pkg/codegen/internal/test/testdata/plain-schema-gh6957/dotnet/Pulumi.Xyz.csproj
pkg/codegen/internal/test/testdata/provider-config-schema/dotnet/Pulumi.Configstation.csproj
pkg/codegen/internal/test/testdata/resource-args-python/dotnet/Pulumi.Example.csproj
pkg/codegen/internal/test/testdata/simple-enum-schema/dotnet/Pulumi.Plant.csproj
pkg/codegen/internal/test/testdata/simple-plain-schema-with-root-package/dotnet/Pulumi.Example.csproj
pkg/codegen/internal/test/testdata/simple-plain-schema/dotnet/Pulumi.Example.csproj
pkg/codegen/internal/test/testdata/simple-resource-schema-custom-pypackage-name/dotnet/Pulumi.Example.csproj
pkg/codegen/internal/test/testdata/simple-resource-schema/dotnet/Pulumi.Example.csproj
pkg/codegen/internal/test/testdata/simple-yaml-schema/dotnet/Pulumi.Example.csproj

Fix https://github.com/pulumi/pulumi-azure-native/issues/985 (once it propagates to azure-native)
This is only needed in Azure Native but as we only compile a single project for each provider, there should be no downside to enabling it for all providers.

Set UseSharedCompilation to false

---

sdk/dotnet/Pulumi.Automation.Tests/CommandExceptionTests.cs
sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs

I have fixed the dotnet Automation.Tests that were failing because of missing PULUMI_CONFIG_PASSPHRASE environment variable.
The change is fixing tests and no impact on existing behaviour
There is no changes related to calling Pulumi Service API

Set PULUMI_CONFIG_PASSPHRASE for Automation Tests

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi.Automation/Pulumi.Automation.xml
sdk/dotnet/Pulumi/Core/Archive.cs
sdk/dotnet/Pulumi/Core/Asset.cs
sdk/dotnet/Pulumi/Serialization/Converter.cs
sdk/dotnet/Pulumi/Serialization/Serializer.cs
sdk/go/pulumi/asset.go
sdk/go/pulumi/rpc.go
sdk/go/pulumi/rpc_test.go

The two more strongly-typed Pulumi SDKs curently fail with an error
during unmarshaling when attempting to marshal a value that is not an
asset into an asset-typed location (e.g. an asset-typed resource
output property). While this behavior is reasonable on its face, it
gives rise to practical challenges when dealing with TF-provider-backed
resources that have asset-typed properties. When such a resource is
refreshed, the values of its asset-typed properties are replaced with
non-asset values, as the TF bridge can't currently create a resonable
stand-in asset value.
For example, consider an S3 bucket object:
```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
const bucket = new aws.s3.Bucket("my-bucket");
new aws.s3.BucketObject("my-object", {
source: new …
```

[sdk/{go,dotnet] Unmarshal invalid assets.

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/config.go
pkg/cmd/pulumi/stack_output_test.go
pkg/cmd/pulumi/util.go
pkg/cmd/pulumi/util_test.go

Fixes https://github.com/pulumi/pulumi/issues/5474

[cli] - Don't escape special characters when printing JSON

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
sdk/dotnet/Pulumi.Automation/Commands/LocalPulumiCmd.cs
sdk/dotnet/Pulumi.Automation/Events/EventLogWatcher.cs
sdk/dotnet/Pulumi.Automation/LocalWorkspace.cs
sdk/dotnet/Pulumi.Automation/Pulumi.Automation.xml
sdk/dotnet/Pulumi.Automation/Runtime/LanguageRuntimeService.cs
sdk/dotnet/Pulumi.Automation/WorkspaceStack.cs
sdk/dotnet/Pulumi/Deployment/Deployment.EnginerLogger.cs
sdk/dotnet/Pulumi/Deployment/Deployment_Invoke.cs
sdk/dotnet/Pulumi/Deployment/Deployment_Prepare.cs
sdk/dotnet/Pulumi/Deployment/Deployment_ReadOrRegisterResource.cs
sdk/dotnet/Pulumi/Deployment/Deployment_ReadResource.cs
sdk/dotnet/Pulumi/Deployment/Deployment_RegisterResource.cs
sdk/dotnet/Pulumi/Deployment/Deployment_RegisterResourceOutputs.cs
sdk/dotnet/Pulumi/Deployment/Deployment_RootResource.cs
sdk/dotnet/Pulumi/Deployment/Deployment_Run.cs
sdk/dotnet/Pulumi/Deployment/GrpcEngine.cs
sdk/dotnet/Pulumi/Deployment/InlineDeploymentResult.cs

Fixes async await warnings found while looking into #7422. (Does not fix #7422 itself.)

[sdk/dotnet] Fix async await warnings

---

CHANGELOG_PENDING.md
sdk/go/pulumi/context.go
tests/integration/construct_component_methods/go/main.go

Pass a valid `destType` to `marshalInput` to avoid panicing when the `self` resource implements `pulumi.Input`.
This issue would have been caught by testing the generated code, in addition to comparing it to what is expected.
Fixes #7603

[sdk/go] Fix methods panic when marshaling `self`

---

sdk/go/auto/errors_test.go
sdk/go/auto/test/errors/conflict_error/main.go

Just combing through the backlog and found this item. Tests pass consistently on my machine, but bumped up the from 1s to 5s (does not increase total runtime of test at all). 
Fixes https://github.com/pulumi/pulumi/issues/5378 fixes https://github.com/pulumi/pulumi/issues/5312

reenable concurrent update test

---

pkg/codegen/dotnet/gen.go
pkg/codegen/internal/test/testdata/types.json

Collection types nested inside of Input<Union<...>> types need to abide
by the usual rules for collection types nested inside of input types.
These changes replace the use of the generic SimplifyInputUnion with a
.NET-specific simplifyInputUnion that does not remove Input types
inside of a union if those Input types wrap collection types. Retaining
these Input types allows the usual logic for handling
Input<Collection<...> types in typeString to kick in.
Fixes #7569.

[sdk/dotnet] Fix collections in input unions.

---

sdk/dotnet/Pulumi.Tests/Deployment/DeploymentRunnerTests.cs

Saw TerminatesEarlyOnExceptionStack flaking up on Mac OS runner, giving it a larger timeout (note: the test if passing finishes quickly and does not wait for the timeout, so this should not slow down test suites).

Timeout of 1min for the slow task

---

.github/workflows/issue-management.yml

Adding some issue management automation, including:
- Automatically closing issues that have had the `awaiting-feedback` label for more than 14 days

Add issue management Actions

---

.github/workflows/issue-management.yml

We merged https://github.com/pulumi/pulumi/pull/7476 which is applying the [awaiting-feedback-stale](https://github.com/pulumi/pulumi/issues?q=is%3Aopen+is%3Aissue+label%3Aawaiting-feedback-stale) label appropriately, but the issues aren't actually set to close. 
Adding [days-before-close ](https://github.com/actions/stale#days-before-close)solves this

Actually close the issue after being marked as stale

---

pkg/codegen/go/gen.go
pkg/codegen/internal/test/helpers.go
pkg/codegen/internal/test/sdk_driver.go
pkg/codegen/internal/test/testdata/external-resource-schema/go/example/cat.go
pkg/codegen/internal/test/testdata/external-resource-schema/go/example/component.go
pkg/codegen/internal/test/testdata/external-resource-schema/go/example/workload.go
pkg/codegen/internal/test/testdata/plain-schema-gh6957/go/xyz/staticPage.go
pkg/codegen/internal/test/testdata/resource-args-python/go-program/go_test.go
pkg/codegen/internal/test/testdata/resource-args-python/go/example/person.go
pkg/codegen/internal/test/testdata/resource-args-python/go/example/pet.go

The code for input method generation was duplicated. These changes
remove the duplicated code.
This is prep for fixing #7595.

[codegen/go] Unify input method generation.

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi.Tests/Resources/DependencyProviderResourceTests.cs
sdk/dotnet/Pulumi/Resources/DependencyProviderResource.cs
sdk/nodejs/resource.ts
sdk/nodejs/tests/resource.spec.ts
sdk/python/lib/pulumi/resource.py
sdk/python/lib/test/test_resource.py

When initializing `DependencyProviderResource` (Node.js, Python, and .NET), pass the package to the base constructor instead of an empty string s.t. the provider is usable when its package is read.
Note that the Go SDK was already doing this (line 133):
https://github.com/pulumi/pulumi/blob/eaf78edfef11c7ab97dc90b2bafd3c9fcc7eedf7/sdk/go/pulumi/resource.go#L127-L135
... so this is making the other language SDKs consistent.
Also worth noting that the likelihood of this being a problem is much less now after #7624, but it's still worth fixing because it's still possible to fallback to `DependencyProviderResource` when we can't rehydrate a provider.
Fixes #6895

Set the package on DependencyProviderResource

---

pkg/codegen/docs/gen.go
pkg/codegen/docs/gen_test.go
pkg/codegen/python/doc.go
pkg/codegen/python/gen.go
pkg/codegen/python/gen_program.go
pkg/codegen/python/gen_program_expressions.go
pkg/codegen/python/gen_program_lower.go
pkg/codegen/python/gen_program_quotes.go

Coincident with the release of Pulumi 3.0, we updated the provider SDK codegen for Python to no longer use casing tables for translating Python snake_case names to Pulumi camelCase names (and vice versa). Instead, the mapping is encoded in decorators applied on class properties.
Some of the code that was used to generate and use the casing tables has persisted. This commits removes this code, as it's no longer necessary, and will improve the quality of our generated examples.
Follow-up from https://github.com/pulumi/pulumi/pull/7547#issuecomment-881659505

[codegen/python] Delete dead code around casing tables

---

pkg/codegen/nodejs/gen.go
pkg/codegen/nodejs/importer.go

This commit adds two new fields to the Node package info struct to permit setting the plugin name if it differs from the package name, and the version if it differs from the package version. This was already supported by the loader.
No test coverage of this area.
Not a user-facing change.
N/A.

Allow setting plugin name and version for Node.js

---

CHANGELOG_PENDING.md
pkg/backend/filestate/backend.go
pkg/backend/filestate/backend_test.go
pkg/backend/filestate/stack.go

The information exposed via `pulumi stack ls` does not require being able to decrypt state files, but the existing logic for `pulumi stack ls` with the filestate backend was to fully decrypt the state file anyway, silently skipping any stacks that could not be decrypted.  This led to surprising results from `pulumi stack ls`.
After these changes, `pulumi stack ls` with the filestate backend will list *all* stacks that are available.  Notably, because there is no notion of "project" scoping in the fielstate backend (yet), `pulumi stack ls` will list all stacks independent of the project name.
Fixes #4798.

[backend/filestate] Allow `pulumi stack ls` to see all stacks regardless of passphrase

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/up.go
pkg/engine/lifeycletest/delete_before_replace_test.go
pkg/engine/lifeycletest/target_test.go
pkg/resource/deploy/deployment_executor.go
pkg/resource/deploy/step_generator.go

Prior to this change, when a component was targeted without including all of its children in the list of targets, it would result in an error like below:
```
Diagnostics:
infrastructure:k8s-istio-operator (web-dev):
error: Cannot delete parent resource 'urn:pulumi:istio-operator::infrastructure::infrastructure:k8s-istio-operator::web-dev' without also deleting child 'urn:pulumi:istio-operator::infrastructure::infrastructure:k8s-istio-operator$kubernetes:yaml:ConfigGroup::web-dev'
```
However, when a component is targeted, it is logical that the user intended to also target the component's children, since the component itself is a wrapper for all of its children. This PR changes the behavior to include children when a component is targeted instead of erroring. 
**Note:** This changes the …

Include children when targeting components.

---

CHANGELOG_PENDING.md

Cleanup CHANGELOG_PENDING after a release

---

pkg/backend/httpstate/backend.go
pkg/codegen/docs/templates/resource.tmpl

Per the title, the programming model topic is being refactored, split up, and merged with existing content in pulumi/docs#4707.
This PR updates the boilerplate doc links from within our autogen'ed ref pages. The docs PR has redirects in place so the current link doesn't 404 after the PR merged and pushed live.
Once the docs PR is live, we can merge this in when it makes sense to do so.

Updating doc links to align with changes in docs #4707

---

pkg/codegen/dotnet/gen_program_expressions.go
pkg/codegen/go/gen_program.go
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/hcl2/functions.go
pkg/codegen/internal/test/program_driver.go
pkg/codegen/internal/test/testdata/functions.pp
pkg/codegen/internal/test/testdata/functions.pp.cs
pkg/codegen/internal/test/testdata/functions.pp.go
pkg/codegen/internal/test/testdata/functions.pp.py
pkg/codegen/internal/test/testdata/functions.pp.ts
pkg/codegen/nodejs/gen_program.go
pkg/codegen/nodejs/gen_program_expressions.go
pkg/codegen/python/gen_program_expressions.go

- `join` joins an array of strings using a specified separator
- `toBase64` converts a string to its Base64 representation
These changes also contain fixes for invokes with inputs that are absent
or optional.

[codegen/*] Add join and toBase64 functions.

---

CHANGELOG_PENDING.md
sdk/go/pulumi/context.go
sdk/go/pulumi/context_test.go
sdk/go/pulumi/log.go
sdk/go/pulumi/types.go
sdk/go/pulumi/types_test.go
sdk/go/pulumi/workgroup.go
sdk/go/pulumi/workgroup_test.go

Fixing WaitGroup related panics in the Go SDK

---

pkg/resource/provider/component_provider.go
tests/integration/component_provider_schema/testcomponent-go/main.go

This commit adds a new counterpart to `ComponentMain` which accepts functional options for specifying callback functions. Currently it supports `construct` (for components) and `call` (for methods), but is extensible in a non-breaking fashion in future to support all other provider methods as they become desirable to implement.
The original `ComponentMain` still exists, though it may be desirable to deprecate it in future in favor of `ProviderMain`.
Existing test uses new function.
Not a user facing change.
N/A.

Add ProviderMain function

---

tests/examples/examples_test.go
tests/integration/component_provider_schema/testcomponent-go/main.go
tests/integration/construct_component/testcomponent-go/main.go
tests/integration/construct_component_methods/testcomponent-go/main.go
tests/integration/construct_component_methods_unknown/testcomponent-go/main.go
tests/integration/construct_component_plain/testcomponent-go/main.go
tests/integration/construct_component_unknown/go/random.go
tests/integration/construct_component_unknown/testcomponent-go/main.go

We can use the new `provider.MainWithOptions` from #7598 to reduce boilerplate in some of our testcomponent providers.
Also, while cleaning up here, I took this as an opportunity to replace use of `github.com/pkg/errors` in the `tests` dir to use the built-in functionality of the Go standard library.

Use `provider.MainWithOptions` to reduce boilerplate in integration tests

---

sdk/python/lib/pulumi/runtime/rpc.py
sdk/python/lib/test/runtime/test_rpc.py

This makes the example from https://github.com/pulumi/pulumi/issues/7313 pass (examples/aws-py-ec2-provisioners).
Fixes #7313 
It did not hang this time but it did fail with a relatively obscure stack trace. It works with the fix.

Fix reflecting list type annotations

---

CHANGELOG_PENDING.md
pkg/codegen/internal/test/testdata/nested-module-thirdparty/python/foo_bar/__init__.py
pkg/codegen/internal/test/testdata/nested-module-thirdparty/python/foo_bar/deeply/__init__.py
pkg/codegen/internal/test/testdata/nested-module-thirdparty/python/foo_bar/deeply/nested/__init__.py
pkg/codegen/internal/test/testdata/nested-module/python/pulumi_foo/__init__.py
pkg/codegen/internal/test/testdata/nested-module/python/pulumi_foo/nested/__init__.py
pkg/codegen/internal/test/testdata/provider-config-schema/python/pulumi_configstation/__init__.py
pkg/codegen/internal/test/testdata/simple-enum-schema/python/pulumi_plant/__init__.py
pkg/codegen/internal/test/testdata/simple-enum-schema/python/pulumi_plant/tree/__init__.py
pkg/codegen/internal/test/testdata/simple-methods-schema/python/pulumi_example/__init__.py
pkg/codegen/python/gen.go

Fixes  module completion part of #7367
The issues with sub-package discovery are fixed for VSCode and PyCharm.

Fix IDE completion issues for lazy imports

---

sdk/dotnet/Makefile

Fixed small typo in build script. Previously, the -ldflags would be given an incorrect empty version.

Go install command is given proper DOTNET_VERSION

---

pkg/cmd/pulumi/config_test.go
sdk/go/common/resource/config/key.go

Turns out the assertion check would only fail if the namespace was ":" or "".

Assertion fix in config key generation

---

CHANGELOG_PENDING.md
sdk/go/auto/local_workspace.go
sdk/go/auto/local_workspace_test.go
sdk/go/auto/optremove/optremove.go
sdk/go/auto/workspace.go

I'm in the need for forcibly delete certain stacks from the state, even though they have resources in it.
This is relevant for us for kubeneretes stacks that we wish to delete because we are going to destroy the infra stack anyway.

Add force flag for RemoveStack

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/resource.py
sdk/python/lib/pulumi/runtime/resource.py

Similar to #5282, but for core SDK types. The tl;dr is that because
Sequence[T] is covariant, constructing resources becomes much more
ergonomic.
Fix #7693.

python: Use Sequence rather than List in Resource fields

---

CONTRIBUTING.md

CONTRIBUTING.md updated to require NodeJS v11.x rather than v10.x, as Pulumi 3.0 no longer supports the latter.

Update of CONTRIBUTING.md to reflect 3.0 changelog

---

CHANGELOG_PENDING.md
sdk/nodejs/automation/server.ts
sdk/nodejs/runtime/resource.ts

Fixes https://github.com/pulumi/pulumi/issues/6998
Turns out we weren't adding `prepareResource` work the the keep-alive queue. We were waiting until `runAsyncResourceOp` which happens in a `.then` chained off of `prepareResource`. The automation api shutdown routine, `runtime.disconnect`, was unaware of this outstanding work as a result.

[sdk/nodejs] Account for outstanding async work done in `prepareResource`

---

pkg/codegen/schema/schema.go

Fixes: https://github.com/pulumi/pulumi/issues/7717

[programgen] - Fix a panic in property binding

---

CHANGELOG_PENDING.md
sdk/go/pulumi/context.go
sdk/go/pulumi/resource.go
sdk/go/pulumi/resource_set.go
sdk/go/pulumi/rpc.go
sdk/go/pulumi/rpc_test.go

Implement Node/.NET-style dependency semantics for component resources.
Depending on a component implicitly depends on all of the component's
children. The exact set of children depends on exactly when the
component resource is observed.
Part of #7542.

[sdk/go] Transitive component dependencies.

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/resource.py
sdk/python/lib/pulumi/runtime/resource.py
sdk/python/lib/test/langhost/component_dependencies/__init__.py
sdk/python/lib/test/langhost/component_dependencies/__main__.py
sdk/python/lib/test/langhost/component_dependencies/test_component_dependencies.py
sdk/python/lib/test/langhost/property_dependencies/test_property_dependencies.py

Implement Node/.NET-style dependency semantics for component resources.
Depending on a component implicitly depends on all of the component's
children. The exact set of children depends on exactly when the
component resource is observed.
Part of #7542.

[sdk/python] Transitive component dependencies.

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/dynamic/dynamic.py
tests/integration/dynamic/python-non-main/.gitignore
tests/integration/dynamic/python-non-main/Pulumi.yaml
tests/integration/dynamic/python-non-main/__main__.py
tests/integration/dynamic/python-non-main/other.py
tests/integration/integration_python_test.go

The underlying library `dill` that we use for serializing dynamic providers into Pulumi state for Python dynamic providers serializes classes differently depending on whether they are in `__main__` or in another module.  We need the by-value serialization to be applied in all cases.
https://github.com/uqfoundation/dill/issues/424 is tracking adding the ability into `dill` to specify this by-value serialization explicitly, but until then, we will temporarily re-write the `__module__` of a provider class prior to serialization, so that `dill` behaves as we need for the dynamic provider use case.
Fixes #7453.

Allow Python dynamic provider resources to be constructed outside of `__main__`

---

pkg/backend/httpstate/state.go

- Add context to the lease renewal failure error
- Spew to the -v=3 logs when lease renewal fails
Fixes #3055.

[backend/http] Better lease renewal diagnosability

---

sdk/python/lib/test_with_mocks/resources.py
sdk/python/lib/test_with_mocks/test_testing_with_mocks.py

Fixes #6561
I could not reproduce 6561 locally except by replacing `sync_await._ensure_event_loop()` with `get_event_loop`. These refactored tests pass under plain `get_event_loop`. This is because all action now happens on the main thread, unlike on ThreadPoolExecutor as in the product. 
So it is unfortunate that the refactored tests are working in a context that's different from product context.
On the upside, I believe they will stop flaking up the PR verification. This is a big relief.
TO reduce blast radius, I refactored the test suite to use Pytest fixtures so that the modifications to the default executor are "local" to the test suite and do not bleed into other tests.

Remove threading from mock tests to fix AIO waits on diff event loop

---

CHANGELOG_PENDING.md
pkg/engine/lifeycletest/golang_sdk_test.go
sdk/go/pulumi/rpc.go

A few identically-typed variables got confused with the changes in #7737.
The confusion caused empty property values to be included in resources
that had any dependencies on other resources, which confused the
unmarshaling code for Go multi-language components. These changes fix
the typo and restore the original behavior, which is to omit empty
property values.

[sdk/go] Fix a typo in marshaling.

---

pkg/codegen/hcl2/binder.go

`BindExpressionText()` has the potential to return a nil `typeExpr`, which leads to the subsequent `typeExpr.Type()` call panicking. A guard condition is added to return with an error if `typeExpr` is found to be nil after calling `BindExpressionText()`.
Before, the error was identified by the coverage tracker in this way:
```
{
"Reason": "runtime error: invalid memory address or nil pointer dereference",
"Count": 1
},
```
Now, it is more specific:
```
{
"Reason": "cannot bind expression: \u003canonymous\u003e:0,61-62: Missing attribute separator; Expected a newline or comma to mark the beginning of the next attribute.",
"Count": 1
},
```

Fixed nil pointer error with BindExpressionText and typeExpr

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/dynamic/dynamic.py
tests/integration/dynamic/python-resource-type-name/Pulumi.yaml
tests/integration/dynamic/python-resource-type-name/__main__.py
tests/integration/integration_python_test.go

Now there is not possible to change a name of dynamic provider resource without copying a code of the `pulumi.sdk.python.lib.pulumi.dynamic.dynamic.Resource` and changing the hard-coded name `"pulumi-python:dynamic:Resource"`. I successfully uses this proposal to make it possible.
Usage:
```python
class CustomResource(
Resource, name="my-custom-provider:CustomResource"
):
...
```

Added support for custom naming of dynamic provider resource

---

pkg/codegen/go/gen.go

Fixes non-determinism introduced in https://github.com/pulumi/pulumi/pull/7779 by sorting. 
Tested this locally against azure native and it results in no diff (other than sorting a few declarations). 
Iterating over maps when generating code is a bag sad.

stabilize go codegen for nested collection types

---

pkg/testing/integration/program.go

Fixes issues similar to the one surfacing in:
https://github.com/pulumi/pulumi/pull/7781
Basically `go mod tidy` fetches transitive dependencies, if it's placed after edits that point to the local SDK, then any new dependencies from the local SDK propagate automatically into integration tests without having to explicitly declare them. 
Questions:
- do we want that? or we actually want to explicitly declare those in tests projects
- is it safe to remove `go mod download` - I think `go mod tidy` includes that work

Fix order of go mod tidy

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/new.go

Change `pulumi new` to use `go mod tidy` rather than `go mod download` when installing Go project dependencies, to ensure the project is fully prepared to be used by `pulumi up`, avoiding `missing go.sum entry for module` errors.
Fixes #7807

Avoid `missing go.sum entry for module` for new Go projects

---

sdk/python/lib/pulumi/automation/_local_workspace.py
sdk/python/lib/pulumi/automation/_representable.py
sdk/python/lib/pulumi/automation/_stack.py
sdk/python/lib/pulumi/automation/events.py
sdk/python/lib/pulumi/provider/server.py
sdk/python/lib/pulumi/resource.py
sdk/python/lib/pulumi/runtime/config.py
sdk/python/lib/pulumi/runtime/mocks.py
sdk/python/lib/pulumi/runtime/resource.py
sdk/python/lib/pulumi/runtime/rpc.py
sdk/python/lib/pulumi/runtime/stack.py
sdk/python/lib/pulumi/urn.py
sdk/python/lib/test/test_urn.py

Python LINT started flagging duplicate code in our codebase, including on master, so I'm starting to clean up. This PR just lifts URN parsing into a shared function.

Satisfy Python lint: factor out URN parsing in Python and other fixes

---

CHANGELOG_PENDING.md
pkg/codegen/schema/schema.go
pkg/codegen/schema/schema_test.go

Allow hyphens to be used in package names. 
Fixes #7775

Allow hyphen in schema path

---

pkg/codegen/go/gen_program_expressions.go

Fixed `invalid Go source code` error that would occur when converting example `#/resources/aws:directoryservice/logService:LogService`.
Before, the error was identified by the coverage tracker in this way:
```
{
"ProviderName": "aws",
"ProviderVersion": "4.15.0+dirty",
"ExampleName": "#/resources/aws:directoryservice/logService:LogService",
"IsDuplicated": false,
"FailedLanguages": [
{
"TargetLanguage": "go",
"FailureSeverity": 3,
"FailureInfo": "invalid Go source code:\n\n20:59: expected ')', found '-' (and 10 more errors)",
"MultipleTranslations": false
}
]
}
```
The error occurred because the input's `ad-log-policyPolicyDocument` wasn't formatted to use underscores, while the return's `ad_log_policyPolicyDocument` was. 
```
import (
"fmt"
"github.com/pulumi/pulumi/sdk/v3/go/pulumi" …
```

Fixed invalid go source code issue

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/pulumi.go
pkg/cmd/pulumi/schema.go
pkg/cmd/pulumi/schema_check.go
pkg/codegen/schema/loader.go
pkg/codegen/schema/schema.go
pkg/codegen/schema/schema_test.go

- Change the schema package to report semantic errors as diagnostics
rather than Go errors
- Add a `pulumi schema check` command to the CLI for static checking of
package schemas
The semantic checker can be extended in the future to add support for
target-specific checks.

[codegen/schema] Add a schema checker

---

CHANGELOG_PENDING.md
sdk/go/auto/local_workspace.go
sdk/go/auto/local_workspace_test.go

Fixes https://github.com/pulumi/pulumi-kubernetes-operator/issues/183

[auto/go] Fix stack config loading

---

CHANGELOG_PENDING.md

One of these is mine. Sorry
`addreses` is spelled `addresses` and `comand` is spelled `command`. 

Fix CHANGELOG_PENDING.md spelling

---

.github/workflows/run-build-and-acceptance-tests.yml

Github actions defaults to `fail-fast: true` for build matrices. However, we'd like to see the results of all the runs even if one fails. This PR fixes the issue. 
Similar to https://github.com/pulumi/pulumi/pull/7441

Don't fail if one subset fails

---

pkg/codegen/hcl2/model/type_object.go

No longer throws an error when encountering the [legacy HCL indexation operator](https://github.com/hashicorp/hcl/blob/main/hclsyntax/spec.md) ".0"
The following HCL example now successfully converts.
Original:
```hcl
...
access_policy {
tenant_id = azurerm_log_analytics_cluster.example.identity.0.tenant_id
object_id = azurerm_log_analytics_cluster.example.identity.0.principal_id
key_permissions = [
"get",
"unwrapkey",
"wrapkey",
]
}
}
...
```
Result:
```ts
...
{
tenantId: exampleCluster.identity.apply(identity => identity[0].tenantId),
objectId: exampleCluster.identity.apply(identity => identity[0].principalId),
keyPermissions: [
"get",
"unwrapkey",
"wrapkey",
],
},
],
...
```

Fixed "unknown property '0'" error

---

sdk/dotnet/Pulumi/Core/CodegenUtilities.cs
sdk/dotnet/Pulumi/PublicAPI.Shipped.txt

This is the part of https://github.com/pulumi/pulumi/pull/7899 that needs to ship first so that providers upgrade to this SDK. It has been tested as part of 7899.

Add CodegenUtilities to C# SDK in prep for 5758

---

pkg/codegen/hcl2/model/type_object.go

Reverts pulumi/pulumi#7912
Tests need to be updated to reflect ".0" being made valid.
```
// Test that traversing a map(T) with a type that is not convertible to string returns DynamicType and an error.
testTraverse(t, typ, hcl.TraverseIndex{Key: cty.ListVal([]cty.Value{cty.NumberIntVal(0)})}, typ.ElementType, true)
```

Revert "Fixed "unknown property '0'" error"

---

CHANGELOG_PENDING.md
sdk/go/common/resource/plugin/rpc.go
sdk/go/common/resource/plugin/rpc_test.go

Currently whenever an issue occurs in `UnmarshalProperties` and
`MarshalProperties` the offending property is hidden and very difficult
to track down.
This commit changes the behavior. For `Assets` and `Archives` the error
message now includes the URI and for other properties it includes the
key of the `PropertyMap`.
Existing tests use new functionality.

feat: Improve error messages for (un)marshalling

---

pkg/codegen/dotnet/gen_program_expressions.go
pkg/codegen/dotnet/utilities.go
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/go/gen_program_utils.go
pkg/codegen/hcl2/functions.go
pkg/codegen/nodejs/gen_program_expressions.go
pkg/codegen/python/gen_program_expressions.go

Implemented Terraform's filebase64() function for all 4 languages, solving a total of 48 code generation errors across the AWS, GCP, and Azure providers

Implemented filebase64() support for Code Generator

---

CHANGELOG_PENDING.md
pkg/go.sum
sdk/go.mod
sdk/go.sum
sdk/go/common/resource/plugin/rpc.go
sdk/go/common/resource/plugin/rpc_rapid_test.go
sdk/go/common/resource/plugin/rpc_test.go
sdk/go/common/resource/properties.go
sdk/go/common/resource/properties_test.go
tests/go.sum

This change expands the definition of `resource.Output` in the Go SDK with additional information about the output, i.e. dependencies and secretness, and adds support in the core Go RPC code for (un)marshaling output values.
Output values are marshaled as special objects ala archives, assets, and resource refs and are unmarshaled as `resource.Output` values.
Note: The current plan is to scope this to only be used when marshaling inputs to a multi-lang component and for method calls using `Call`.
Subsequent PRs will add:
- A monitor feature for output values, which will initially be disabled by default but available to turn on via an envvar
- A way for component providers to indicate support for accepting output values (for `Construct` and `Call`)
- Support for (un)marshaling output values …

Initial support for (un)marshaling output values

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/about.go

Use golang's native `json.Unmarshal` and tagged types instead of custom parsing with `interface{}`. 
Fixes #7942
Parsing json files is now handled by a library, and the library (go-std) does not need testing.

Use json.Unmarshal instead of custom parser

---

sdk/nodejs/runtime/invoke.ts
sdk/nodejs/runtime/resource.ts
sdk/nodejs/runtime/rpc.ts
sdk/nodejs/runtime/settings.ts
sdk/nodejs/tests/runtime/props.spec.ts

This change adds support for marshaling outputs as output values in the Node.js SDK.
Fixes #7850
Part of #7434

[sdk/nodejs] Marshal output values

---

sdk/python/lib/pulumi/runtime/invoke.py
sdk/python/lib/pulumi/runtime/resource.py
sdk/python/lib/pulumi/runtime/rpc.py
sdk/python/lib/pulumi/runtime/settings.py
sdk/python/lib/test/test_next_serialize.py

This change adds support for marshaling outputs as output values in the Python SDK.
Fixes #7851
Related to #7925
Part of #7434

[sdk/python] Marshal output values

---

scripts/test_subsets.py
sdk/dotnet/Makefile
sdk/go/Makefile
sdk/nodejs/Makefile
sdk/python/Makefile
sdk/python/Pipfile

The Automation API tests take long enough that thay don't really fit
into `test_fast`. These changes move those tests to `test_all`.

[automation-api] Exclude tests from test_fast.

---

pkg/resource/provider/component_provider.go
sdk/go/pulumi/provider.go
sdk/go/pulumi/provider_test.go
sdk/go/pulumi/rpc.go
sdk/go/pulumi/urnset.go

This adds support for unmarshaling output values in the `CopyTo` helper used when copying inputs to an args struct. More details here: https://github.com/pulumi/pulumi/pull/7928#issuecomment-916227805
Note: I'd like to add more test cases and clean up the implementation a bit, but I'll do that in a subsequent change.
Fixes #7848
Part of #7434

[sdk/go] Unmarshal output values in component provider

---

sdk/python/lib/pulumi/runtime/rpc.py
sdk/python/lib/test/test_next_serialize.py

Pass along the `keep_output_values` param when serializing values within dicts.

[sdk/python] Fix serializing output values within dicts

---

CHANGELOG_PENDING.md
developer-docs/Makefile
developer-docs/go.mod
developer-docs/go.sum
developer-docs/index.md
developer-docs/providers/implementers-guide.md
developer-docs/providers/metaschema.md
developer-docs/utils/jsonschema2md.go
pkg/codegen/internal/test/testdata/output-funcs/funcWithConstInput.json
pkg/codegen/internal/test/testdata/simple-enum-schema/schema.json
pkg/codegen/schema/pulumi.json
pkg/codegen/schema/schema.go
pkg/go.mod
pkg/go.sum
tests/go.sum

The Pulumi Package metaschema is a JSON schema definition that describes
the format of a Pulumi Package schema. The metaschema can be used to
validate certain basic properties of a Pulumi Package schema, including
(but not limited to):
- data types (e.g. is this property a string?)
- data formats (e.g. is this string property a valid regex?)
- object shapes (e.g. is this object missing required properties?)
The schema binder has been updated to use the metaschema as its first
validation pass.
In addition to its use in the binder, the metaschema has its own page in
the developer documentation. This page is generated using a small tool,
jsonschema2md.go.

[schema] Add the Pulumi Package metaschema.

---

.github/workflows/run-build-and-acceptance-tests.yml

The motivation is included in the comment.

Cancel checks on outdated PR commits

---

.github/workflows/master.yml
.github/workflows/release.yml
.github/workflows/run-build-and-acceptance-tests.yml
scripts/test_subsets.py

The goal of this change is to facilitate merging PRs faster.
In particular we have a shortage of Mac OS workers and therefore have PRs waiting to be verified until workers become available. With this change:
- the number of workers booked for a PR verification goes down from **4** to **1**
- by skipping integration and Automation API tests on the Mac OS worker, the Mac OS worker PR verification time is **36 min**
- after a PR is merged, the full set of tests will still run on 4 Mac OS workers on every commit in `master` branch
In addition to skipping tests on Mac OS, the PR changes the partitioning of the tests into test subsets. This is done so that the subset of checks that *do* run on every PR on Mac OS (this subset is called `etc`) conservatively includes all the important tests. This …

Faster CI PR verification on Mac OS: run fewer tests, use fewer workers

---

developer-docs/Makefile
developer-docs/architecture/deployment-schema.md
developer-docs/index.md
developer-docs/providers/metaschema.md
developer-docs/utils/jsonschema2md.go
pkg/resource/stack/deployment.go
pkg/resource/stack/deployment_test.go
sdk/go/common/apitype/core.go
sdk/go/common/apitype/deployments.json
sdk/go/common/apitype/property-values.json
sdk/go/common/apitype/resources.json

This schema can be used to validate the contents of a Pulumi deployment.
If a deployment validates against this schema, it should be considered
syntactically valid, though it may contain certain classes of semantic
errors (e.g. references to unknown resources in dependency lists,
dependency cycles, etc.).
This schema is not yet used for validation in practice and may not be
entirely accurate.
These changes also add this schema (and the schemas on which it depends)
to the developer documentation. jsonschema2md.go has been updated to
support multi-file schemas.

[apitype] Add a JSON schema for deployments.

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/automation/_local_workspace.py
sdk/python/lib/test/automation/test_local_workspace.py

This repro'd with `print(stack)` in a local program so I added that to the test.

[auto/python] - Fix a bug in printing stack.

---

CHANGELOG_PENDING.md
sdk/nodejs/runtime/mocks.ts
sdk/nodejs/tests_with_mocks/mocks.spec.ts
sdk/python/lib/pulumi/runtime/mocks.py
sdk/python/lib/test_with_mocks/resources.py
sdk/python/lib/test_with_mocks/test_testing_with_mocks.py

v3.13.0 introduces support for serializing outputs in inputs as special output value objects in the Node.js and Python SDKs when serializing inputs for remote components and method calls. This functionality is currently disabled by default in the engine (setting the `PULUMI_ENABLE_OUTPUT_VALUES` envvar to a truthy value enables it).
However, unit testing remote components with mocks results in errors being raised in v3.13.0, related to the new output value support. This is due to the mock monitor implementation saying it supports all features (which now includes output values), so the SDK serializers are serializing outputs as output values, which the mock monitor can't handle correctly.
This change addresses the issue by updating the mock monitor implementation in the Node.js and Python …

[sdk/{nodejs,python}] Fix errors when testing remote components with mocks

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/util.go
sdk/go/common/resource/plugin/provider_plugin.go
sdk/go/common/resource/plugin/rpc.go
sdk/go/common/resource/plugin/rpc_test.go
sdk/nodejs/runtime/rpc.ts
sdk/nodejs/tests/runtime/props.spec.ts
sdk/python/lib/pulumi/runtime/rpc.py
sdk/python/lib/test/test_next_serialize.py

Enable output values by default in the resource monitor and change the polarity of the envvar from `PULUMI_ENABLE_OUTPUT_VALUES` to `PULUMI_DISABLE_OUTPUT_VALUES`.
We've had a cron job running in the `pulumi/examples` repro with the feature both enabled and disabled, and everything is looking good on those runs (as expected), so we're comfortable enabling it by default.
Fixes #8007

Enable output values by default

---

pkg/codegen/internal/test/helpers.go

This change makes sure that we do get to see stdout/stderr of a failing command. I think the original code is a typo.

Do report stdout and stderr in case of failure

---

sdk/go/common/resource/plugin/provider_plugin.go
sdk/go/common/resource/plugin/rpc.go
sdk/go/common/resource/plugin/rpc_test.go
sdk/go/pulumi/context.go
sdk/go/pulumi/mocks.go
sdk/go/pulumi/provider_test.go
sdk/go/pulumi/rpc.go
sdk/go/pulumi/rpc_test.go
sdk/go/pulumi/run_test.go

This change adds support for marshaling outputs as output values in the Go SDK.
Fixes #7849
Part of #7434

[sdk/go] Marshal output values

---

.github/workflows/trigger-container-build-event.yml

Change Docker build to use Pulumi's fork of action-docker-build.

---

sdk/go/pulumi/provider_test.go
sdk/go/pulumi/rpc.go

`ConstructInputs.CopyTo` can error when falling back to the old marshaling behavior when it's lacking an input type registration for a _known_ output value. In such cases, it tries to unmarshal the known output value, but can't because of a missing switch case leading to very strange errors like ` unmarshaling value: expected a string, got a string`. This change adds the missing case.
Fixes #8081
Part of #7434

[sdk/go] Fix unmarshaling known output values in provider

---

CHANGELOG.md
CHANGELOG_PENDING.md

This is patterned off the similar note for v3.5.0/v3.5.1, but there are slight differences between what's in the CHANGELOG vs. GH release notes. I went with consistent text for both for in this change.
https://github.com/pulumi/pulumi/blob/472f14c992406f673ec905bdc65c0c8fb2fdeeb6/CHANGELOG.md#L424
vs
https://github.com/pulumi/pulumi/releases/tag/v3.5.1
> **Please Note:** Release v3.5.0 failed in our build pipeline so will be rebuilt with a new tag of v3.5.1

Prepare for v3.13.2 release

---

.github/workflows/release.yml

* Adds `lint` step as required before release.
* Adds a new job `check-clean-worktree` to ensure the git work tree is clean before releasing.
I elected to add a separate job for this step to avoid doing it 8 times as part of build-and-test.
I unfortunately don't know how to test this without a release. However, this is already a part of the `master` workflow: https://github.com/pulumi/pulumi-aws/blob/master/.github/workflows/master.yml#L68-L69
Fixes https://github.com/pulumi/pulumi/issues/8092

Check worktree is clean before releasing

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/up.go
pkg/cmd/pulumi/util.go
pkg/cmd/pulumi/util_test.go
sdk/go/common/workspace/project.go

Fixes: #8058
A user can now specify the following in their Pulumi.yaml
```
options:
refresh: always
```
This will cause the derivative stacks to refresh by default when running an update, preview
or destroy command. We can override this with `--refresh=false`
the specific CLI commands still override this argument. Therefore:
* If a user sets refresh: always, they can override this behaviour with `--refresh==false`
* if a user sets `--refresh` or `--refresh=true` then it will use that by default
* if no cli args are passed but `refresh: always` then we will perform a refresh
* the default behaviour still exists of no refresh
https://asciinema.org/a/2BQoAe9gx9E07gBiM9h9A1cra

[cli] Add the ability to control auto-refresh of stacks by Pulumi.yaml

---

developer-docs/architecture/type-system.md
developer-docs/index.md

Just what it says on the tin: add some initial documentation for the
abstract Pulumi type system. Over time, this documentation will be
fleshed out to describe the relationship between the abstract type
system and its wire representations, Pulumi package schemas, and
language SDK implementations.

[developer-docs] Add preliminary type system docs.

---

pkg/engine/lifeycletest/pulumi_test.go
pkg/engine/lifeycletest/test_plan.go
pkg/resource/deploy/deploytest/resourcemonitor.go
pkg/resource/deploy/source_eval.go

This test is derived from a user-reported issue rooted in dependencies
on remote components.
Closes #7786.

[engine/test] Add a repro for #7786.

---

pkg/codegen/go/gen.go
pkg/codegen/go/importer.go

Go codegen flag to disable fnOutput generation to save space

---

sdk/go/common/resource/testing/rapid.go

These changes add a context type to `resource/testing` that can be used to
generate property values that are valid with respect to certain rules. The
context represents a Pulumi stack, and contains a project name, stack name,
and a list of resources.
- URNs generated using a context will always use the context's project
and stack name
- Resource references generated using a context will always refer to
resources in the context's resource list
- Output values generated using a context will always pull dependencies
from the context's resource list

[testing] Stack context for value generation

---

.github/workflows/run-build-and-acceptance-tests.yml

This reverts commit a9c9853e85fb628979569701e8714f1694a6a719.
Per [docs](https://docs.github.com/en/actions/learn-github-actions/contexts) `github.head_ref` is only available via `pull_request` or `pull_request_target`.   
This breaks as `/run-acceptance-tests` is triggered via `repository_dispatch`, eg:
https://github.com/pulumi/pulumi/actions/runs/1295914761/workflow
To get unblocked, let's revert and figure out an alternative way to do concurrency later.
cc: @t0yv0

Revert "Cancel checks on outdated PR commits (#8016)"

---

CHANGELOG_PENDING.md
sdk/go/auto/stack.go

This MR fixes an issue in the Pulumi Go automation API where --target / --replace args are not correctly formated, causing the CLI to not recognize the flag :
Error: unknown flag: --target urn:pulumi:stack::project::pulumi:providers:kubernetes::k8s

Fix Go automation API --target / --replace args

---

sdk/python/lib/pulumi/output.py

fix for grammatical typo in docstring of Output method apply

Fix typo in Output.apply docstring

---

.github/workflows/run-build-and-acceptance-tests.yml
CHANGELOG_PENDING.md
sdk/python/cmd/pulumi-language-python-exec

[sdk/python] - Python 3.10 compatibility

---

pkg/resource/provider/host.go

Signed-off-by: Liam White <liam@tetrate.io>
As described in #7156. When I run Pulumi up I get:
```
pulumi:providers:tsb (tsb):
error: tsb (resource) plugin [/Users/liamwhite/go/bin/pulumi-resource-tsb] wrote a non-numeric port to stdout ('2021-05-27T13:44:04.073942Z	info	[core]parsed scheme: ""'): strconv.Atoi: parsing "2021-05-27T13:44:04.073942Z\tinfo\t[core]parsed scheme: \"\"": invalid syntax
```
This is due to grpc logging to stdout before the provider writes the port to stdout. This PR explicitly sets the GRPC defaults to prevent users from overriding them and breaking their providers.
Fixes #7156

Turn off grpc info log in Provider

---

.github/workflows/run-build-and-acceptance-tests.yml

Reworking the reverted PR    https://github.com/pulumi/pulumi/pull/8118
```
github.ref      = refs/pull/8145/merge
github.head_ref = t0yv0/cancel-checks-on-outdated-pr-commits-2
```
Using both data points now to compute the pre-emption ID. This does still work to cancel outdated checks on this PRs. I suspect this might fix the `/run-acceptance-tests` since `github.ref` should still be available, but I'm not sure that I can test it without merging to master first, as right now `/run-acceptance-tests` uses the workflow definition from master it seems, which makes sense for security...
Can I merge this and test it and quickly follow up with either revert or fixup/removal of debug statements? 

Bring back PR automatic outdated commit check pre-emption

---

.github/workflows/run-build-and-acceptance-tests.yml

Continuing to work out PR concurrency controls. Currently on master all `/run-acceptance-tests` get the same concurrency ID which makes the latest one cancel all in-progress runs. This is not desirable. Experimenting with computing a unique concurrency ID for `/run-acceptance-tests` dispatches.

Improve concurrent ID computation for /run-acceptance-tests

---

.gitignore
.vscode/settings.json

Currently this is just setting go.buildTags to "all" so the language
specific tests are included in build and test commands by default.
Missing this leads to the confusing (at least to new people) behavior
of clicking run test on a test method and vscode then saying there is no
test to run.

Check in default vscode settings

---

CHANGELOG_PENDING.md
sdk/nodejs/runtime/resource.ts
sdk/python/lib/pulumi/runtime/known_types.py
sdk/python/lib/pulumi/runtime/resource.py
sdk/python/lib/pulumi/runtime/rpc.py

Expand dependencies when marshaling output values #8301
Fixes #7977

Expand dependencies when marshaling output values

---

CHANGELOG_PENDING.md
README.md
sdk/python/cmd/pulumi-language-python-exec
sdk/python/lib/pulumi/_types.py
sdk/python/lib/pulumi/automation/_server.py
sdk/python/lib/pulumi/runtime/mocks.py
sdk/python/lib/pulumi/runtime/rpc_manager.py
sdk/python/lib/pulumi/runtime/stack.py
sdk/python/lib/pulumi/runtime/sync_await.py
sdk/python/lib/setup.py

This reverts commit 895ae970ac0b998fdf5dbef0299f70125cea0dac.
Python 3.6 is not EOL yet, and this will break for users who were unaware of this change. We should minimize user pain during updates, and propose we implement a version checker (#8325) to better display a warning to users that the version they're using will soon not be supported. 
Intent is to revert this revert by EOY, more closely aligned to the EOL date.

Revert "[python/sdk] - Remove python 3.6 support (#8161)"

---

pkg/codegen/go/gen.go

- Remove enumElementType, whose functionality duplicates work done in
argsTypeImpl
- Clarify the args- vs. Go-ness of the two element types
This is prep work for #7943. These changes should not produce codegen diffs.

[codegen/go] Slightly simplify enum type gen.

---

pkg/go.mod
pkg/go.sum
sdk/go.mod
sdk/go.sum
sdk/go/common/util/cmdutil/console.go
sdk/go/common/util/cmdutil/console_test.go
tests/go.mod
tests/go.sum

Fixes two bugs in how padding was calculated in PrintTable.
Firstly we remove all ANSI escape codes from the string before measuring
how wide it is. Secondly we measure glyph count (using rivo/uniseg) not
byte or rune count of the string.
Together these fix the padding/alignment issues I saw when using
PrintTable with plan output. They also slightly change the layout of
"pulumi stack", for example the below is printed with current master and
has 6 characters of space for padding between SecurityGroup and
web-secgrp:
```
Current stack resources (4):
TYPE                                        NAME
pulumi:pulumi:Stack                         aws-cs-webserver-test
├─ aws:ec2/securityGroup:SecurityGroup      web-secgrp
├─ aws:ec2/instance:Instance                web-server-www
└─ …
```

Fix cmdutil.PrintTable to handle ansi escapes and non-byte glyphs

---

CHANGELOG_PENDING.md
pkg/codegen/go/gen_program.go
pkg/codegen/internal/test/testdata/random-pet-pp/dotnet/random-pet.cs
pkg/codegen/internal/test/testdata/random-pet-pp/go/random-pet.go
pkg/codegen/internal/test/testdata/random-pet-pp/nodejs/random-pet.ts
pkg/codegen/internal/test/testdata/random-pet-pp/python/random-pet.py
pkg/codegen/internal/test/testdata/random-pet-pp/random-pet.pp

When importing a resource in Go, we change resource names with hyphens to snake_case. This happens because we [introduced a change](https://github.com/pulumi/pulumi/pull/4915/files#diff-d6817c1c54a334e663ae7a8ef2bcc697641fcddf412b0d2b97c884a9e297a5f3R247) that converts the resource name to a valid Go identifier so it can be used as a local variable. But we were also using this converted name as the string resource name, which causes problems with import: the imported resource in the state file has the original resource name, but the generated program uses the converted name, causing Pulumi to delete and recreate the resource when adopting the generated import code.
This change fixes the issue by maintaining the original resource name, and only using the converted name for variables.
Fixes …

[programgen/go] Don't change imported resource names

---

.devcontainer/Dockerfile

Something has changed in the base image such that the directory
/etc/sudoers.d doesn't exist. Simple fix, `mkdir -p` that directory
before we write to it.

Fix devcontainer Dockerfile build

---

.vscode/settings.json

Our makefiles always run `go test` with a 1h timeout. This updates the default vscode settings to the same.

Increase default go test timeout

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/automation/events.py

Fixes the deserialization for the `metadata` property on `ResourcePreEvent`, `ResOutputsEvent` and `ResOpFailedEvent`. There are no existing tests for the deserialization of engine events, so I haven't added any but this fixes my issue locally.

[auto/python] - Fix deserialization of event 

---

.devcontainer/devcontainer.json
.vscode/settings.json

These gopls settings should apply to any vscode instance, not just ones in devcontainers.

Move gopls settings to .vscode from .devcontainer

---

sdk/python/cmd/pulumi-language-python/main.go

Note: we do this at the language plugin level because extremely old
version of python (python2) have different syntax, and we don't want
parse errors to occlude our version message.
Fixes #8325

Validate python version

---

pkg/testing/integration/util.go

Moving over https://pkg.go.dev/github.com/pulumi/pulumi-eks/utils#AssertHTTPResultWithRetry to integration testing library since it is generally usable across different packages.

Move AssertHTTPResultWithRetry from pulumi-eks utils

---

.devcontainer/devcontainer.json
.github/workflows/master.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/run-build-and-acceptance-tests.yml
.vscode/settings.json
sdk/dotnet/Makefile

Improve support for dotnet (mostly) in vscode and the devcontainer.
This installs a test adapter for dotnet in the devcontainer so that our C# tests show in the vscode test explorer.
This also sets some default settings for onmisharp and the test-adapter to focus on the main sdk .sln.
Finally this changes the devcontainer startup to call "make ensure" rather than "dotnet restore" on every csproj. The main dotnet projects are now restored as part of "make ensure". The sum result of this is that once the devcontainer is started up there are working environments for all the languages (dotnet has projects restored, go has deps downloaded, python has a venv setup etc).

Improve vscode dotnet support

---

CHANGELOG_PENDING.md

Cleanup CHANGELOG_PENDING after 3.17.1

---

sdk/go/common/workspace/workspace.go

This improvement comes in two parts.
1. The error message for a corrupt workspace settings file now clearly
indicates both the file and the parsing error.
2. Writing the workspace settings is now atomic. This prevents
corruption from multiple concurrent calls.
Fixes #6287
This change also lessons the impact of #8186, though it is still something we need to address.

Improve corrupt workspace settings experience

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi/Core/Output.cs
sdk/dotnet/Pulumi/Resources/ComponentResourceOptions.cs
sdk/dotnet/Pulumi/Resources/CustomResourceOptions.cs

Docs in a few places weren't actually showing list items, see:
- https://www.pulumi.com/docs/reference/pkg/dotnet/Pulumi/Pulumi.ComponentResourceOptions.html#Pulumi_ComponentResourceOptions_Merge_Pulumi_ComponentResourceOptions_Pulumi_ComponentResourceOptions
- https://www.pulumi.com/docs/reference/pkg/dotnet/Pulumi/Pulumi.CustomResourceOptions.html
- https://www.pulumi.com/docs/reference/pkg/dotnet/Pulumi/Pulumi.Output-1.html
The dotnet [xmldocs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#list) suggest:
>for a table, bulleted list, or numbered list, you only need to supply an entry for description
btw we have an example of this in code already here: https://github.com/pulumi/pulumi/blob/master/sdk/dotnet/Pulumi/Resources/DictionaryResourceArg …

Fixing broken lists in dotnet docs

---

sdk/python/lib/pulumi/output.py

We have seen cases where a lot of errors like this are reported:
```
UnboundLocalError: local variable 'resources' referenced before assignment
```
This change prevents this failure mode, which might be a symptom of some other issue, but currently obscures it in the error path.

[sdk/python] Avoid 'referenced before assignment' error

---

.devcontainer/Dockerfile
.gitpod.yml
.gitpod/Dockerfile
CONTRIBUTING.md
build/common.mk
pkg/testing/integration/program.go
sdk/dotnet/Makefile
sdk/nodejs/README.md

`/opt/pulumi` is legacy of our build system we are trying to fix. We still need a place to put executables and artifacts. Luckily, `~/.pulumi` already exists. This moves our build artifacts from `/opt/pulumi.{bin,nuget,node_modules}` to `~/.pulumi/{bin,nuget,node_modules}`. This fixes the insane permissions problems of `/opt/pulumi`, as `~/.pulumi` is normal user accessible space. 

Move `/opt/pulumi` to `$HOME/.pulumi`

---

CHANGELOG_PENDING.md
pkg/codegen/dotnet/gen_program.go
pkg/codegen/dotnet/gen_program_expressions.go
pkg/codegen/internal/test/program_driver.go
pkg/codegen/internal/test/testdata/aws-fargate-pp/dotnet/aws-fargate.cs
pkg/codegen/internal/test/testdata/output-funcs-aws-pp/dotnet/output-funcs-aws.cs

Programgen support for F.Invoke forms in .NET (#7949)

---

pkg/codegen/docs/gen.go
pkg/codegen/internal/test/testdata/env-helper/docs/moduletest/_index.md

This is actually quite serious as it causes master build failure. This makes it deterministic. If there's a better sort than lexicographic that fits this code LMK.

Fix non-determinism in docsgen

---

CHANGELOG_PENDING.md
pkg/backend/filestate/backend.go
pkg/backend/filestate/backend_test.go
pkg/backend/filestate/state.go

Pulumi CLI fails with the following error when running `pulumi stack select dev2 -c` to select a stack but first creating it, if it does not exist already.
```
pulumi stack select dev2 -c --cwd C:\GitHub\temp-pulumi-stacks\pr-test\
error: failed to load checkpoint: blob (key ".pulumi/stacks/dev2.json") (code=NotFound): CreateFile C:\temp\.pulumi\stacks\dev2.json: The system cannot find the file specified.
```
Fixes #8461 (Related to #8406)

[backend/filestate] Don't unwrap go-cloud errors

---

pkg/resource/deploy/step.go

when I run `pulumi up` with a protected resource pulumi give an example , but that example is not working
```
error: Preview failed: unable to delete resource "urn:pulumi:XXXXXX::XXXX::gcp:component:all_resource$gcp:storage/bucket:Bucket::bucket_XXXXX"
as it is currently marked for protection. To unprotect the resource, either remove the `protect` flag from the resource in your Pulumiprogram and run `pulumi up` or use the command:
`pulumi state unprotect urn:pulumi:XXXX::XXXX::gcp:component:all_resource$gcp:storage/bucket:Bucket::bucket_XXXXXX`
```
If I run the example cmd , it throw : 
```log
error: No such resource "urn:pulumi:XXXX::XXX::gcp:component:all_resource:storage/bucket:Bucket::bucket_XXXXX" exists in the current state
```
If i put around the urn some **`**  it work  : 
``` …
```

[FIX] unprotect cmd example

---

CHANGELOG_PENDING.md
sdk/go/common/util/gitutil/git.go
sdk/go/common/util/gitutil/git_test.go
sdk/go/common/workspace/templates.go

If no branch is specified, probe `master`, then probe `main` before failing. 
Fixes #8428
I would be curious if anyone has a different idea on how to download branches from both master and main without breaking changes.

[cli] check main after master

---

CHANGELOG_PENDING.md
sdk/python/cmd/pulumi-language-python/main.go

[sdk/pthon] Version Check: Handle virtual env correctly

---

sdk/go/common/resource/testing/rapid.go

It turns out that `require` calls t.FailNow() which causes undesirable quiet failure sometimes. IN contrast, it would seem that `assert.NoError(t, err)` in a generator skips the example and reruns the generator until a better example is found. This fixes #8464.
Fixes #8464

Do not FailNow() in generators

---

pkg/codegen/internal/test/testdata/resource-property-overlap/go-extras/tests/go_test.go

This simply covers the ArrayOutput/Index code generation with a unit test.  This was broken until pgavlin/resourcePtr pointer but now is fixed. The test will help keep it fixed.

Add a unit test over generated Go code to verify ArrayOutput/Index

---

sdk/go/common/util/result/result.go

I got fed up of assert errors in tests that looked like:
```
Expected nil, but got: &result.simpleResult{err:(*errors.fundamental)(0xc0002fa5d0)}
```
It was very hard to work out at a glance what had gone wrong and I kept
having to hook a debugger just to look at what the error was.
With GoString these now print something like:
```
Expected nil, but got: &simpleResult{err: Unexpected diag message: <{%reset%}>resource violates plan: properties changed: -zed, -baz, -foo<{%reset%}>
}
```
Which is much more useful.

Add String and GoString to Result

---

pkg/engine/lifeycletest/pulumi_test.go
pkg/engine/lifeycletest/test_plan.go

Hit this while trying to add some validation checks to runs of Preview while using plans. Seems one test actually was assuming this was the case already and just hasn't been running it's expected validate function.

Run validate function even if dryRun=true

---

CHANGELOG_PENDING.md
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_test.go

A custom server URL can contain `${VERSION}`, `${OS}`, or `${ARCH}` (case sensitive) in the URL and these values will be interpolated when downloading the plugin.
Fixes #8263

Allow interpolating plugin custom server URLs

---

CHANGELOG_PENDING.md
pkg/codegen/go/gen.go
pkg/codegen/internal/test/testdata/dashed-import-schema/go/plant-provider/tree/v1/rubberTree.go
pkg/codegen/internal/test/testdata/plain-object-defaults/go/example/foo.go
pkg/codegen/internal/test/testdata/plain-object-defaults/go/example/moduleTest.go
pkg/codegen/internal/test/testdata/plain-object-defaults/go/example/provider.go
pkg/codegen/internal/test/testdata/simple-enum-schema/go/plant/tree/v1/rubberTree.go

The overall goal of this change is to avoid unnecessary conversions
between pointer and non-pointer output types. The use of these
conversions requires that we always generate the pointer variant of an
object type, which impedes #7943's ability to omit these types. Instead,
we can let the return type of the callback match the argument type and
return the dereferenced result of `foo.Defaults()` if necessary.
These changes also simplify the generated code somewhat in order to
avoid introducing additional variables.

[codegen/go] Simplify object default applies.

---

CHANGELOG_PENDING.md
pkg/codegen/go/gen.go
pkg/codegen/internal/test/testdata/output-funcs-edgeorder/go/myedgeorder/pulumiTypes.go
pkg/codegen/internal/test/testdata/simple-resource-schema-custom-pypackage-name/go/example/pulumiTypes.go
pkg/codegen/internal/test/testdata/simple-resource-schema/go/example/pulumiTypes.go
pkg/codegen/internal/test/testdata/simple-yaml-schema/go/example/pulumiTypes.go

The element types for nested collection types are currently incorrect.
For arrays, we generate an element type of `[]FooArgs`, where
`FooArgs` is an args type for `FooInput`. Instead, the element type
should be `[]Foo`, where `Foo` is the element type of `FooInput`.
For maps, we generate an element type of `FooArgs`. Instead, the element
type should be `map[string]Foo`, where `Foo` is the element type of
`FooInput`.
These changes correct the element types. This is prep for #7943.

[codegen/go] Fix ElementType for nested collection types.

---

Makefile
build/common.mk
sdk/python/Makefile

Python kept failing to build. It was because we were invoking `python` instead of `$(PYTHON)`. This fixes the problem, along with a few other small nits.

Use $(PYTHON) for makefile

---

pkg/engine/destroy.go
pkg/engine/lifeycletest/import_test.go
pkg/engine/lifeycletest/pulumi_test.go
pkg/engine/lifeycletest/refresh_test.go
pkg/engine/lifeycletest/test_plan.go
pkg/resource/deploy/source_null.go

Got to love mutability by default. Just found a whole load of tests that are checking that resource snapshots haven't changed by checking they're equal to the snapshot before, but the snapshot was mutated by the update so it's trivially equal because its the same object. Changing it so we clone the snapshot before passing it in triggers a load of failures because default provider urns have been filled in by update and the test didn't expect that. This PR adds the code to clone before testing and fixes up the tests to pass again.

Clone snapshot before testing with it

---

CHANGELOG_PENDING.md
pkg/backend/filestate/backend.go
pkg/backend/filestate/lock.go
tests/stack_test.go

Always lock in filestate backends, previously feature-flagged

---

pkg/backend/httpstate/client/api.go
sdk/go/common/util/httputil/http.go

The Pulumi CLI's `httpstate` backend retries HTTP requests if it sees a 5xx error. This presumably makes stack updates a little more reliable in the face of transient network errors and things.
However, in practice the default values for the delay/retry logic are much too aggressive to actually be useful.
https://github.com/pulumi/pulumi/blob/a952140b34c667d005116ee53be08077b5863948/sdk/go/common/util/retry/until.go#L34-L38
Here are some timestamps I'm seeing for repeated HTTP requests that arise from failures. The first value is the initial 5xx, and the next four are the additional attempts to the same URL. Notice how all 5 requests are attempted in less than 2 seconds. (In-line with the default retry values... though not accounting for the time it takes to actually send the request, and …

Set less agressive timeouts for HTTP retries

---

pkg/codegen/docs/gen_kubernetes.go

The change needed for https://github.com/pulumi/pulumi-kubernetes/issues/1799 (we'll need to propagate it to the resourcegen tool in docs).
I'm not sure at which point this got broken - have we changed the module names for Helm? Anyway - I fixed it and added a panic instead of silently returning a blank collection.

Fix the module name of Helm for Python doc generation

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi.Tests/Mocks/Issue7422.cs
sdk/dotnet/Pulumi.Tests/Mocks/MocksTests.cs
sdk/dotnet/Pulumi.Tests/StackTests.cs
sdk/dotnet/Pulumi.Tests/TestDeploymentLogger.cs
sdk/dotnet/Pulumi/Deployment/Deployment_ReadOrRegisterResource.cs
sdk/dotnet/Pulumi/Exceptions/RunException.cs
sdk/dotnet/Pulumi/Resources/Resource.cs
sdk/dotnet/Pulumi/Serialization/OutputCompletionSource.cs
sdk/dotnet/Pulumi/Stack.cs

Under certain conditions, C# SDK can race to observe nulls in Urn property of a resource. This is reproduced via a non-deterministic mock test, and fixed in this PR.
Fixes #7422 
On top of https://github.com/pulumi/pulumi/pull/8577 (requires merging that first).

Fix 7422 - NullPointerException race on Urn property in C# SDK

---

pkg/codegen/docs/.gitignore
pkg/codegen/docs/gen_test.go

Praneet removed the generation of the packaged.go file in https://github.com/pulumi/pulumi/pull/8389 but I still had it sitting around in my local repo because it was still .gitignored. Was very confusing why "make lint" kept throwing up lint error even on a fresh master checkout.
This removes the .gitignore in that folder and also an out of date comment for one test that used that old file.

Remove .gitignore for file we no longer generate

---

CHANGELOG_PENDING.md
sdk/go/common/workspace/plugins.go

Opt language hosts out of `PULUMI_IGNORE_AMBIENT_PLUGINS`. Currently, setting `PULUMI_IGNORE_AMBIENT_PLUGINS` breaks the Automation API because the Automation API does not have a language specific package manager to fall back to.

Opt language hosts out of `PULUMI_IGNORE_AMBIENT_PLUGINS`

---

sdk/go/pulumi/provider.go
sdk/go/pulumi/provider_test.go

Rather than setting the destination to a value of one of the `pulumi.`
primitive types, set the destination to a value of the appropriate args
type. For example, consider the following definitions:
```
type StringEnumInput interface {
Input
ToStringEnumOutput() StringEnumOutput
ToStringEnumOutputWithContext(context.Context) StringEnumOutput
}
...
type StringEnum string
...
type StringEnumInputArgs struct {
Value StringEnumInput `pulumi:"value"`
}
func init() {
RegisterInputType(reflect.TypeOf((*StringEnumInput)(nil)).Elem(), StringEnum(""))
}
```
The original code would have attempted to set
`StringEnumInputArgs.Value` to a value of type `pulumi.String`, but
`pulumi.String` does not implement `StringEnumInput`. The fixed code
creates a value of type `StringEnum`, sets its value to …

[sdk/go] Fix copyInputTo for enums.

---

.github/workflows/master.yml
.github/workflows/run-build-and-acceptance-tests.yml

We've been having issues with codecov where uploading results would fail to some token error (`Passed token was 0 characters long`) - @iwahbe has opened this as an issue upstream here https://github.com/codecov/codecov-action/issues/598
Open for discussion if we should make this blocking on the Main branch, but for now let's disable `fail_ci_if_error`

update codecov setting to not fail ci on error

---

CHANGELOG_PENDING.md
pkg/backend/httpstate/client/client.go
pkg/cmd/pulumi/config.go
pkg/cmd/pulumi/stack.go
pkg/cmd/pulumi/stack_export.go
pkg/cmd/pulumi/stack_history.go
pkg/cmd/pulumi/stack_output.go
pkg/cmd/pulumi/util.go

For users who use the Pulumi Service for their state BUT a 3rd party
secrets provider, we now log when that secret decryption has happened.
We have 2 forms of logs:
* single secret when a user uses `pulumi config get x --show-secrets`
* batch decryption for when a user runs a stack export or config list
The API logs to request are fire and forget. The API response is a 204
so we don't need to do anything with the response.

[cli] Log Secret Decryption events when using 3rd party secrets + service

---

CHANGELOG_PENDING.md
pkg/codegen/schema/loader.go
pkg/codegen/schema/schema.go

Allow consumers to load package specs without validating them against
the Pulumi package metaschema. This dramatically reduces the package
load time for scenarios in which packages can be assumed to be
well-formed (e.g. program codegen + packages that are referenced by a
root schema).
Fixes #8541.

[codegen/schema] Do not validate in ImportSchema.

---

sdk/python/lib/pulumi/_types.py

`make lint` stopped passing on master. I believe we may have an unpinned mypy dep that auto-upgraded and started complaining about type-checking this little call site.

Fix python lint (mypy checks)

---

pkg/codegen/docs/gen.go
pkg/codegen/docs/gen_kubernetes.go

Follow-up and further improvement to #8579:
- Excluded Release from override: [preview](http://pulumi-docs-origin-pr-6918-2bd7c18b.s3-website.us-west-2.amazonaws.com/registry/packages/kubernetes/api-docs/helm/v3/release/)
- Add descriptions to Chart args: [preview](http://pulumi-docs-origin-pr-6918-2bd7c18b.s3-website.us-west-2.amazonaws.com/registry/packages/kubernetes/api-docs/helm/v3/chart/)

Helm doc override: exclude Release and add description for Chart

---

pkg/cmd/pulumi/doc.go
pkg/cmd/pulumi/doc_object_type.tmpl
pkg/cmd/pulumi/doc_reader.go
pkg/go.mod
pkg/go.sum

I also added some special handling for TypeScript Union types, as they
display with an `|` operator. This previously broke our tables.

Enable object types

---

pkg/cmd/pulumi/doc_reader.go

We were having issues with selection after links were followed. This fixes that. 

Keep markdownReader.view up to date

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/resource.py
sdk/python/lib/test/test_stack_registers_outputs.py

Fixes #8273 
The behavior is modified not just for Stack but for any ComponentResource. I cannot find a reason for the original `if` statement but it does seem reasonable to expect RegisterResourceOutputs to always be called. Let us see if the test suite passes with these changes.

Always RegisterOutputs even if empty

---

.github/workflows/build.yml
.github/workflows/run-build-and-acceptance-tests.yml
.goreleaser.prerelease.yml
Makefile
scripts/go-wrapper.sh

Enable a dedicated GitHub Actions step to build the Go binaries:
- uses [Goreleaser](https://goreleaser.com/) similarly to our released binaries
- coverage support: with enable-coverage flag, builds produce a `pulumi` CLI compiled for coverage tracking
- tests download and test the exact same binaries
- builds run in a parallel matrix per platform to speed them up
- macos builds necessarily run on a macos-latest worker because of CGO
- windows builds run on an ubuntu-latest worker with cross-compilation
Remaining work will build upon this:
- Refactor Windows builds (not touched with this change) to use the same structure
- Apply the changes to non-PR workflows - release, prerelease, master
- Figure out release integration so during release it's obvious that exact same binaries are tested …

Factor out Go builds in CI into a dedicated x-platform step

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi/Serialization/OutputCompletionSource.cs

SetValue correctly annotates that the object held in data might be null.
But then ignores that annotation and tries to cast to `T`, if the object
is null this is fine for reference types which just stay null, but for
value types this throws a NullReferenceException. Simple fix to just use
`default(T)` for when `data.Value` is null, and only cast when non-null.
This has the same behaviour as before for reference types (where
`default(T)` is null) but means that value types take their default
value rather than throwing.
Fixes #8625

Don't crash on null inputs for value types in IOutputCompletionSource.SetValue(OutputData<object?> data)

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
sdk/dotnet/Pulumi.Automation/LocalWorkspace.cs
sdk/go/auto/cmd.go
sdk/go/auto/local_workspace.go
sdk/go/auto/local_workspace_test.go
sdk/nodejs/automation/cmd.ts
sdk/nodejs/automation/localWorkspace.ts
sdk/nodejs/tests/automation/localWorkspace.spec.ts
sdk/python/lib/pulumi/automation/_cmd.py
sdk/python/lib/pulumi/automation/_local_workspace.py
sdk/python/lib/test/automation/test_local_workspace.py

Fixes #8518  for all languages.

Fix for 8518 automation API issue with set_config "-value"

---

pkg/go.mod
pkg/go.sum
sdk/go.mod
sdk/go.sum
sdk/go/common/workspace/creds.go
sdk/go/common/workspace/creds_test.go
tests/go.mod
tests/go.sum

Investigating sporadic test failures on Windows has led me to this discovery. TestConcurrentCredentialsWrites had issues as it depended on the state of credentials file in the environment. Specifically in the lucky case the environment had no credentials therefore it was testing this no-op branch that does not demonstrate contention:
```
if len(creds.AccessTokens) == 0 {
err = os.Remove(credsFile)
if err != nil && !os.IsNotExist(err) {
return err
}
return nil
}
```
Fixing the test to demonstrate contention makes it fail on Windows with "access denied" when it tries to do os.Rename.
I shopped around again for a package to do reliable atomic file writes across platforms. I have tried using this package that we rely on elsewhere in the Pulumi codebase:
```
"github.com/gofrs/flock"
```
But it …

Fix creds file locking on Windows

---

sdk/python/lib/test/automation/test_errors.py

Locally I get a failure of `cd sdk/python && make test_auto` that is fixed with this little change.

Fix pip not found error

---

CHANGELOG_PENDING.md
pkg/backend/filestate/backend.go
tests/stack_test.go

The `httpstate` backend allows previews to proceed even while an update is in progress.  This is potentially problematic as the preview may be relative to a partial state of the stack, but ensures that previews will not be blocked on stacks that have long running updates (for example, to allow for concurrent PR jobs to preview changes).  This behaviour has been consistent ~forever for the `httpstate` backend.
In the `filestate `backend, we recently introduced locking, using a quite different (more coarse-grained) approach. As part of this implementation, preview was added to the list of operations that require an exclusive lock on the stack.
For consistency, we should loosen this so that preview behaves the same relative to state locking in the `filestate` and `httpstate` backends.
In the …

[backend/filestate] Allow preview on locked stack

---

CHANGELOG_PENDING.md
pkg/codegen/importer/hcl2.go
pkg/codegen/importer/testdata/cases.json

Map-typed values now always quote their keys, to ensure that non-identifier key names do not fail.
Fixes #7046.
Fixes #8454.
Fixes pulumi/pulumi-aws#1368.

[cli/import] Support import of values with map type keys with non-identifier names

---

pkg/go.mod
pkg/go.sum
sdk/go.mod
sdk/go.sum
sdk/go/common/util/fsutil/lock.go
tests/go.mod
tests/go.sum

For consistency with https://github.com/pulumi/pulumi/pull/8634

Replace gofrs/flock with rogpeppe/go-internal/lockedfile

---

sdk/dotnet/Pulumi.Tests/Mocks/MocksTests.cs

The assert fails for reasons outlined in #8637. The issue is test-only as in a non-mock context the URNs are allocated as expected. Commenting out the assert so that master builds stop failing.

Fix master build

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/automation/_server.py
sdk/python/lib/pulumi/runtime/rpc_manager.py
sdk/python/lib/test/automation/test_isolation.py

Clearing RPC_MANAGER prevents state contamination between several Automation API operations that intend to be distinct, such as exception poisoning from failed up 1 to otherwise successful up 2.
Fixes #8633 for Python
Separate PRs needed for:

Python Auto API fix to clear RPC_MANAGER

---

sdk/go.mod
sdk/go.sum

Update to a newer version to avoid CVE-2020-14040 in versions <=v0.3.2.
We depend on this indirectly via the tests in the gopkg.in/src-d/go-git.v4 library, which hasn't seen much active maintenance, so we'll just force to a newer version.

Bump golang.org/x/text dependency

---

.github/workflows/build.yml
.github/workflows/run-build-and-acceptance-tests.yml

This PR aggregates small tweaks to build.yml that will be needed by the new version of release.yml.
- parameter for default build platform so the caller can opt to building everything on macos-latest so checksums match
- upload checksums as an artifact
- move edited goreleaser config out of worktree to pass goreleaser dirty worktree tests ( /tmp/.goreleaser.current.yml )

Updates to build.yml

---

sdk/nodejs/package.json
sdk/nodejs/runtime/closure/createClosure.ts

Applying a workaround from https://github.com/grpc/grpc-node/issues/2002 discussion.
Fixes #8678

Work around node SDK tsc failure

---

CHANGELOG_PENDING.md
sdk/go.mod
sdk/go.sum
sdk/nodejs/cmd/pulumi-language-nodejs/main.go
sdk/nodejs/cmd/run/run.ts
tests/integration/integration_nodejs_test.go
tests/integration/nodejs/.gitignore
tests/integration/nodejs/compiler_options/.gitignore
tests/integration/nodejs/esm-js-main/Pulumi.yaml
tests/integration/nodejs/esm-js-main/package.json
tests/integration/nodejs/esm-js-main/src/main.js
tests/integration/nodejs/esm-js/Pulumi.yaml
tests/integration/nodejs/esm-js/index.js
tests/integration/nodejs/esm-js/package.json
tests/integration/nodejs/esm-ts-compiled/Pulumi.yaml
tests/integration/nodejs/esm-ts-compiled/index.ts
tests/integration/nodejs/esm-ts-compiled/other.ts
tests/integration/nodejs/esm-ts-compiled/package.json
tests/integration/nodejs/esm-ts-compiled/tsconfig.json
tests/integration/nodejs/esm-ts-specifier-resolution-node/Pulumi.yaml
tests/integration/nodejs/esm-ts-specifier-resolution-node/index.ts
tests/integration/nodejs/esm-ts-specifier-resolution-node/other.ts
tests/integration/nodejs/esm-ts-specifier-resolution-node/package.json
tests/integration/nodejs/esm-ts-specifier-resolution-node/tsconfig.json
tests/integration/nodejs/esm-ts/Pulumi.yaml
tests/integration/nodejs/esm-ts/index.ts
tests/integration/nodejs/esm-ts/other.ts
tests/integration/nodejs/esm-ts/package.json
tests/integration/nodejs/esm-ts/tsconfig.json

This follows up on the changes in https://github.com/pulumi/pulumi/pull/7764 with three additions:
* Support for passing args directly to `node` so that ESM loaders and other node process level configuration can be accessed via Pulumi
* Support the same default behaviour for loading a ESM module from Pulumi as for `node <program>`, including support for resolving main entrypoint from package folder.
* Add test cases for `.js`, pre-complied `.ts` and `ts-node`-based `.ts.
This includes test cases that show how to use top-level await in Node.js (which is only possible inside ESM), addressing https://github.com/pulumi/pulumi/issues/5161.  
Using ESM via the default `ts-node`-based TypeScript support is a little tricky, as it is dependent on experimental loader hook support in Node, upon …

[langhost/node] More ESM support: `nodeargs`, main entrypoints, and tests

---

.goreleaser.prerelease.yml
.goreleaser.yml
scripts/prep-for-goreleaser.sh

Unfortunately file mtimes affect archive checksums. Before this change, running `goreleaser` twice on the same machine and same file-set would produce a new checksum for the generated archives every single run, that is, checksum was not reproducible from the file-set. The changes fix that.
It is my hope that with the changes we can continue using goreleaser for post-release utility steps rather than recoding them, by running it twice but checking checksums from the second run against the ones in the first run.

Deterministic builds for goreleaser

---

codecov.yml

Until we've figured out why we seem to be seeing inaccurate code
coverage information (e.g. the status checks on #8627), make the code
coverage statuses informational.
Related to #8629.

[ci] Switch code coverage status to informational.

---

tests/integration/printf/go/go.mod

This was preventing the gopls server from working correctly in vscode.

Fix duplicate go module name

---

codecov.yml

These annotations are currently a bit noisy. Disable them for now (and
maybe forever).
See https://docs.codecov.com/docs/github-checks for details on Codecov
and GitHub checks/annotations.

[ci] Disable coverage annotations.

---

CHANGELOG_PENDING.md
sdk/nodejs/cmd/pulumi-language-nodejs/main.go
sdk/nodejs/cmd/pulumi-language-nodejs/main_test.go

The implementation of `GetRequiredPlugins` in the Node.js language host will return an empty set of plugins if it encounters errors reading `package.json` inside a subdirectory. The [intended behavior](https://github.com/pulumi/pulumi/blob/684d7aad3920042ce1982b5fedddea62a6e5bb61/sdk/nodejs/cmd/pulumi-language-nodejs/main.go#L244-L249) is to return any plugins that were found (even if there were some errors in the process) and to log any errors that occurred along the way. This change fixes the implementation to behave as intended.
Fixes #8697

[nodejs/sdk] GetRequiredPlugins: Return plugins even when there're errors

---

CHANGELOG.md

Prepare for v3.21.1 release

---

CHANGELOG_PENDING.md

Clean CHANGELOG_PENDING

---

pkg/resource/deploy/manifest.go
pkg/resource/deploy/snapshot.go
pkg/resource/stack/deployment.go

Given that update plans also use the Manifest type it makes sense to implement it's serialisation and deserialisation methods on it directly.
This commit also moves it into it's own file so that code is separate from snapshot.

Split Manifest type to it's own file

---

codecov.yml

Take advantage of [Codecov's support for subprojects](https://github.com/pulumi/pulumi/pull/8685) to split the results for this repo into results for the CLI/core packages and each SDK.
If this works, I'm hoping that it will help us better track down sources of non-determinism and confusing coverage results.

Split coverage results into projects

---

pkg/engine/lifeycletest/analyzer_test.go
pkg/engine/lifeycletest/import_test.go
pkg/engine/lifeycletest/pulumi_test.go
pkg/engine/lifeycletest/step_generator_test.go
pkg/resource/deploy/deploytest/analyzer.go
pkg/resource/deploy/deploytest/pluginhost.go

Improve coverage of analyers and import plans (the state import half of
`pulumi import`) as well as some failure cases in the step generator.
Analyzer coverage required extending the deploytest package to support
loading analyzers.

[core] Improve engine test coverage.

---

sdk/dotnet/Makefile

@pgavlin I dug into this, looks like the issue was that the `/p:` syntax was not parsing on Windows under Bash. The `-p:` syntax is working better for me, so I can restore the original forms. Also restoring the cov parameters that I lost accidentally in the refactor. PTAL, also curious how the CI goes.

Restore coverage collection for dotnet

---

CHANGELOG_PENDING.md
sdk/go/common/resource/properties_path.go
sdk/go/common/resource/properties_path_test.go

`PropertyPaths` are used as path descriptors with wildcards (`*`). Users
know they can use `root["*"]` to wildcard on any entry in a map. Because
strings and numbers can both be used to index (map vs array), our users
expect to be able to use `root[*]` as a wildcard for an array. We should
parse `[*]` so wildcards work as expected. Internally, this will be
syntactic sugar for `["*"]`, but with much less user confusion.
Fixes #8197
See also: https://github.com/pulumi/pulumi-hugo/issues/908

Accept `*` as an index in property paths

---

.github/workflows/test-fast.yml
.github/workflows/test.yml
build/utils/locked-go/go.mod
build/utils/locked-go/go.sum
build/utils/locked-go/main.go
scripts/locked-go-toolchain.sh

The hypothesis being tested here is that we have OOMs in CI due to more than one instance of the `go` toolchain running at the same time, and the linker being particularly hungry (~300MB RAM) on Windows. The workaround locks the `go` toolchain at OS level so only one instance of `go build` or `go run` can run at a time. 
I've tested it a bit and it seems to work as designed. It slows down Windows verification a bit, the integration tests go into 1h7min territory, but they seem to complete so far without OOM. That'd still be a win in my book if this truly works. I think this is still conceptually better than tuning down test parallelism param (currently -p 10), since tests that do not use Go actually continue to run in parallel.
What would be best is eventually modifying the tests to set …

Try a locked go toolchain

---

CHANGELOG_PENDING.md
sdk/go/common/resource/config/value.go
sdk/go/common/resource/config/value_test.go

Reverts pulumi/pulumi#8682
Fixes https://github.com/pulumi/pulumi/issues/8745
Fixes https://github.com/pulumi/pulumi/issues/8752

Revert "Unify Map and Value number exporting"

---

sdk/dotnet/Pulumi.Automation.Tests/LocalPulumiCmdTests.cs

This test failed and, to be honest, I struggled to find good xunit documentation.
It appears there were two issues in this test:
1. The Assert.Matches was failing on the string termination `$`.
2. The automation API output was trimmed in the test on line 42, but the accumulated lines were not. I didn't see an obvious commit including the word trim, but I'm guessing some behavior changed with automation output?
The line 42 test failed on matching the line beginning:
```
$ curl -sSL https://get.pulumi.com | sh
```
Which when trimmed would not equal itself.

[sdk/dotnet] Fix failing test

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi/Core/Output.cs
sdk/dotnet/Pulumi/PublicAPI.Shipped.txt

Fixes #4824
Changes `Output<T>.ToString()` to return an informative message similar to what we return for `toString` in the node sdk.

Change Output<T>.ToString() to return a message

---

sdk/dotnet/Pulumi.Automation.Tests/LocalPulumiCmdTests.cs

Regarding:
- #8751
This code appears to hit an issue on Windows where the expected & actual values in the assertion are trimmed differently. That PR fixed the issue by not trimming the left hand side on Linux, but on Windows, a trailing `\n` is found in the expected value:
```
Expected: String[] ["v3.23.0-alpha.1642436772\n"]
Actual:   List<String> ["v3.23.0-alpha.1642436772"]
```
The types are, I believe, not relevant for the assertion though the `\n` at the end is.
This test will ensure that both sides are an IEnumerable<String> and are trimmed before asserting on. There is some underlying behavior here, likely related to Windows using CRLF line termination, which isn't relevant to the test at hand.

[sdk/dotnet] Fix test by ensuring both sides of test strings trimmed

---

sdk/dotnet/Pulumi.Automation.Tests/LocalPulumiCmdTests.cs

Reverts pulumi/pulumi#8771
Per @t0yv0 who observed we're still getting inconsistency in test results & an acceptance test failure on Windows even with this change. Will debug from a Windows dotnet build soon.

Revert "[sdk/dotnet] Fix test by ensuring both sides of test strings trimmed"

---

sdk/dotnet/Pulumi.Automation.Tests/LocalPulumiCmdTests.cs

This reverts commit dc30b7e426d361fd68c2166787a37af3e5db7b22.
Fully reverts #8778 - the revert produced by GitHub returned the upstream branch to an intermediate commit.
This restores the file to the last version prior to me making any changes to the test file: 3530ba3205a97193f0a773635371d5ef4d548237.

Revert "[sdk/dotnet] Fix failing test (#8751)"

---

.github/workflows/test-fast.yml

Just as we do already for the Mac OS testing, this PR reduces the scope of PR testing to exclude most integration tests on Windows, leaving only the fall-through `etc` test subset. The reason to do this is that we are losing a lot of builds to Windows OOM issues that are making builds flaky and are not related to regressions. If there are Windows specific regressions introduced on PRs that are caught by these tests, they will be caught once master.yml workflow runs and breaks, and we will have to back out the PR. This is inconvenient but optimizes for the common case - PRs that do not break on windows will go in faster.

Reduce windows PR testing

---

.github/workflows/test-fast.yml
.github/workflows/test.yml
Makefile
sdk/dotnet/Makefile
sdk/go/Makefile
sdk/nodejs/Makefile
sdk/python/Makefile

Reduce probability of Windows test worker VM OOM issue by reducing test parallelism 10 to 1 on Windows. The impact is 60min --> 77min testing duration. I have not yet seen the CI OOM with these changes, but definitely need a larger sample to see if this works or not. I still would like to merge this and continue watching the builds.

Lower test parallelism for Windows testing

---

CHANGELOG_PENDING.md
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_test.go

Rather than downloading from get.pulumi.com, we now have changed to
specify that providers are downloaded from GitHub Releases for
all of the official plugins

[CLI] Allow downloading plugins from GitHub Releases

---

CHANGELOG_PENDING.md
pkg/resource/deploy/providers/provider_test.go
sdk/go/common/tokens/names.go
sdk/go/common/tokens/names_test.go

[sdk/common] allow names with hyphens

---

.github/workflows/test-fast.yml
.github/workflows/test.yml

Copying Go cache setup from build.yml to test.yml, since test.yml rebuilds the tests it seems like it will benefit.
Minor issue: matrix.platform != matrix.os so it won't be the same exact cache key as in build.yml.

Use Go build cache in tests

---

pkg/backend/filestate/backend.go

This makes Delete/Update/Import/Preview the same for filestate and
httpstate. They could just be plain functions now except that `apply` is
hidden.
This also catches that when Watch did an update it wouldn't take the
lock for the filestate backend because Watch called `apply` directly not
`Update`.

Lock inside filestate.apply instead of Update/Delete/Import

---

sdk/go/common/tokens/names.go
sdk/go/common/tokens/names_test.go
sdk/go/common/tokens/tokens.go
sdk/go/common/tokens/tokens_test.go

Since https://github.com/pulumi/pulumi/pull/8695 Name and thus QName has
allowed hyphens, making PackageName just the same as a QName now.

Make PackageName just a QName

---

.github/workflows/test-fast.yml
.github/workflows/test.yml
Makefile
sdk/dotnet/Makefile
sdk/go/Makefile
sdk/nodejs/Makefile
sdk/python/Makefile

Reverts pulumi/pulumi#8755
Backing this out as it did not help our core problem of lost builds.

Revert "Lower test parallelism for Windows testing"

---

CHANGELOG_PENDING.md
pkg/engine/lifeycletest/pulumi_test.go
pkg/resource/deploy/step_generator.go

If a resource is protected we will no longer try to create a replacement for it. Previously the engine would of tried to create the replacement then issued a delete for the protected resource and then error out, that to-be-deleted-but-protected resource would then be left in the stack state and cause every `up` afterwards to also error.
Related to https://github.com/pulumi/pulumi/issues/5749

Don't allow protected resources to be replaced

---

sdk/nodejs/README.md

Minor tweak that points users to the install page, since the homepage no longer has a download link.
Fixes https://github.com/pulumi/pulumi-hugo/issues/958.

Link to the install page from the Node.js README

---

CHANGELOG_PENDING.md
sdk/nodejs/cmd/run/run.ts
tests/integration/integration_nodejs_test.go
tests/integration/nodejs/esm-ts-default-export/Pulumi.yaml
tests/integration/nodejs/esm-ts-default-export/index.ts
tests/integration/nodejs/esm-ts-default-export/package.json
tests/integration/nodejs/esm-ts-default-export/tsconfig.json

In #7764 and #8655 we added support for ESM entrypoints.  However, ESM "default exports" were handled just as "normal" in Node.js dynamic import of ESM - as a `default` proeprty in the export object.
This is not a particularly useful behaviour for Pulumi program entry points, and doesn't quite match some of the special logic we apply to non-object exports in CommonJS modules (invoking exported functions, and then awaiting exports promises).
Instead, this change adds support for default exports, treating the default export (if present) as the full returned export value.
It is for now an error to have both a default export and named exports, since it is unclear what this should mean.  In the future, we could potentially relax this and define how these two sets of exports are merged.
This is …

[sdk/nodejs] Support top-level default exports in ESM

---

CHANGELOG_PENDING.md
pkg/backend/httpstate/client/client.go
pkg/engine/lifeycletest/pulumi_test.go
pkg/go.mod
pkg/go.sum
pkg/resource/stack/deployment.go
pkg/resource/stack/deployment_test.go
pkg/resource/stack/secrets.go
pkg/resource/stack/secrets_test.go
pkg/secrets/b64/manager.go
pkg/secrets/cloud/manager.go
pkg/secrets/passphrase/manager.go
pkg/secrets/service/manager.go
sdk/go.mod
sdk/go.sum
sdk/go/common/resource/config/crypt.go
sdk/go/common/resource/config/value_test.go

Fixes: #6445
Previously, when a deserialisation operation, e.g, `pulumi stack` command
was carried out, each service based secret in the stack was decrypted one at a time
causing n times the number of API requests to the Pulumi service
This meant the following to the user:
```
Calling [pulumi stack] with [1000] secrets took [210.04] seconds.
```
With this new code, we now scan all the inputs and outputs for secrets,
and make a bulk secret decryption dequest to the service and then use
the secrets as a lookup for the deserialization operation. This means
we have a single API request to the service and now means the following
to the user:
```
Calling [pulumi stack] with [1000] secrets took [16.30] seconds.
```

Using a decryptAll functionality when deserializing a deployment

---

.github/workflows/test-fast.yml
.github/workflows/test-windows-ci.yml
.github/workflows/test.yml

The `if` condition added in `test` and `test-fast`, along with the additional input, should enable Mac & Linux tests to proceed and Windows tests will be filtered out.
A scheduled job is added which runs _just_ the Windows tests, using the full test suite.
Related:
- #8820
Closes: #8824

ci: Run windows platform tests if and only if workflow run with windows-ci: true

---

pkg/cmd/pulumi/gen_completion.go
sdk/dotnet/cmd/pulumi-language-dotnet/main.go
sdk/go/auto/local_workspace.go
sdk/go/auto/stack.go

I encountered these when I upgraded `golangci-lint`. This fixes the newly active lints. 

Fix new lint errors

---

pkg/go.sum
sdk/go.mod
sdk/go.sum
tests/go.sum

Fixes: #8834
Post #8676, there was a corrupted go.sum file in tests due to not having
run go mod tidy in that folder

Ensure tests/go.sum has been updated

---

CHANGELOG_PENDING.md
sdk/nodejs/cmd/dynamic-provider/index.ts
sdk/nodejs/dynamic/index.ts
sdk/nodejs/provider/provider.ts
sdk/nodejs/provider/server.ts
sdk/python/lib/pulumi/dynamic/__main__.py
sdk/python/lib/pulumi/dynamic/dynamic.py

Remove sequence numbers from the dynamic provider interfaces. 
It was a source breaking change adding these to the interface declarations. We don't need sequence numbers yet so this can go in as a 4.0 change.
Fixes https://github.com/pulumi/pulumi/issues/8848

Remove sequence numbers from dynamic providers

---

sdk/nodejs/README.md

@cnunciato this is adjusting the link text since we are no longer sending them to pulumi.com; let me know if we don't want to do this for some reason

adjust link text in node sdk readme

---

.github/workflows/prerelease.yml
.github/workflows/release.yml
.goreleaser.prerelease.yml
.goreleaser.yml
scripts/go-wrapper.sh
scripts/unpack.sh

With these changes:
- release.yml no longer rebuilds Go binaries, but releases pre-built tested binaries; it only rebuilds the tar/zip archives
- checksum mismatch on the archives now blocks any side-effecting release actions, making sure we cannot enter "partially released" state again
- checksum mismatch is a hard failure again (used to be a warning) 
- the reproduced checksum mismatch seems to be fixed
Motivation: several master.yml builds and release.yml builds during last patch releases were lost to checksum mismatch, after which we made checkum mismatch check advisory.
A bit of background on what the check is about:
- originally we built Go binaries and put them in archives in build.yml and test them with test.yml
- due to peculiarities of Goreleaser, we rebuild the archives again …

Do not rebuild Go binaries in release.yml, use testsed builds

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/up.go
pkg/resource/deploy/snapshot.go
pkg/resource/deploy/snapshot_test.go

Add wildcard for --target and family

---

CHANGELOG_PENDING.md
sdk/nodejs/runtime/invoke.ts

Provider plugins that publish to a third party destination, and then used via NodeJS sdk don't respect the `pluginDownloadURL` destination for finding the package.
A bit of sleuthing and I found that the variable here was set & not used after assignment.

Aaron friel/issue8890

---

CHANGELOG_PENDING.md
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/go/gen_program_optionals.go
pkg/codegen/go/gen_program_test.go
pkg/codegen/internal/test/program_driver.go
pkg/codegen/internal/test/testdata/aws-fargate-pp/go/aws-fargate.go
pkg/codegen/internal/test/testdata/aws-optionals-pp/aws-optionals.pp
pkg/codegen/internal/test/testdata/aws-optionals-pp/go/aws-optionals.go
pkg/codegen/internal/test/testdata/aws-webserver-pp/go/aws-webserver.go
sdk/go/pulumi/type_conversions.go

As described in #8821, docs generated for helper functions can be incorrect because optional arguments to parameter objects are not correctly handled.
Previously, code would be generated like so:
```go
policyDocument, err := iam.GetPolicyDocument(ctx, &iam.GetPolicyDocumentArgs{
Statements: []iam.GetPolicyDocumentStatement{
iam.GetPolicyDocumentStatement{
Sid: "1",
//...
```
However "Sid" is of type `*string`.
This four helper conversion functions, to handle the primitive types we lower from, and modifies codegen to recursively apply these functions inside of an invoke call.
In the new code generation, the above is instead rendered as:
```go
policyDocument, err := iam.GetPolicyDocument(ctx, &iam.GetPolicyDocumentArgs{
Statements: []iam.GetPolicyDocumentStatement{ …
```

[codegen/go] Improve optional params in invoke

---

pkg/codegen/nodejs/gen_program_test.go

There was a mismatch between `@types/node` and `typescript` on their
default versions. This was fixed by listing both of them explicitly as a
`devDependency`.

Fix nodejs type mismatch

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/plugin_install.go
pkg/codegen/schema/loader.go
pkg/engine/plugins.go
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_install_test.go

Plugin installation has an early return path in the case that the plugin
was already installed. For normal plugin installation, this is okay and
saves some work. For reinstallation, however, this defeats the purpose
by causing installation to return before doing any actual work.
With these changes, we can better accommodate developer scenarios
without requiring that plugins are available on the PATH. For example,
the following script can be used to install a plugin under development:
tar -c [plugin files] | gzip > plugin.tgz
pulumi plugin install [kind] [name] [version] -f ./plugin.tgz --reinstall

[plugins] Fix plugin reinstallation.

---

CHANGELOG_PENDING.md
pkg/backend/httpstate/backend.go
pkg/cmd/pulumi/stack_init.go

Fixes: #8409
Anywhere we parse a stack name, we now take into account if a defaultOrg
is set for the stack. This means stack selection, stack up, stack delete
etc are all going to be able to take advantage of using defaultOrg

[cli] use defaultOrg anywhere where ParseStackReference is used

---

pkg/testing/integration/program.go

Motivating example is something like (pseudocode):
```go
programTest(t, firstStackOptions)
programTest(t, secondStackOptions)
```
Where "secondStackOptions" will refer to a very basic stack that uses a stack reference to the first. This is a much cleaner example to put at the top level of a repo or in an "examples" folder:
```
repo/
└── examples/
├── stackreference-consumer/
│   ├── Pulumi.yaml
│   └── ...
└── stackreference-producer/
├── Pulumi.yaml
└── ...
```
The goal being to ensure all stacks in the examples dir are concise representative of features users would use in projects, without clutter or subdirectories that only the test harness cares about, while still being fully tested.

Enable delaying programtest cleanup to test Cleanup

---

CHANGELOG_PENDING.md
sdk/nodejs/runtime/resource.ts
sdk/nodejs/tests/runtime/langhost/cases/068.remote_component_providers/index.js
sdk/nodejs/tests/runtime/langhost/cases/068.remote_component_providers/package.json
sdk/nodejs/tests/runtime/langhost/run.spec.ts

[sdk/nodejs] Pickup provider as part of providers

---

.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/test-fast.yml
.github/workflows/test.yml
scripts/test_subsets.py

This compromise is aimed at making release flow more stable, currently affected by Windows OOM and requires lots of restarts. First we move some integration work out of `etc` subset - I suspect this should mitigate the Windows OOM of the `etc` worker. Then we use test-fast.yml in releases (assuming master.yml did the full test.yml already by that time). This means that only the `etc` worker will run on Mac + Windows platforms on releases (similar to what's happening on PRs). 

Simpler x-plat testing in release.yml; lighten etc subset

---

sdk/go/common/workspace/plugins.go

The separator should be `,` not `&`.

Fix typo in comment

---

sdk/go/common/workspace/plugins.go

[cli] download plugins from github releases by default

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/util_test.go
sdk/go/common/util/gitutil/git_test.go

Pulumi tests that create and manipulate git repos make the assumptions that config value `init.defaultBranch` is set to `master`, and `user.name` and `user.email` are globally set. These assumption make the following tests fail in development environments where `init.defaultBranch` is not master and where `user.name` and `user.email` are not globally set.
Fixes #8924

Set init.defaultBranch and user info in git tests

---

codecov.yml

The data displayed in the coverage comment is not particularly useful
due to instability in our coverage results. That instability is inherent
in the way that our tests run. Most notably, tests take a different amount
of time from run-to-run (which causes changes in e.g. spinner coverage),
and some tests process different input data (this is primarily associated
with property-based tests). Because the coverage comment displays all
changes to coverage rather than only those that are associated with the
changed lines, the comment may make it appear that a PR affects the
coverage of certain files that it does not.

[codecov] Disable the coverage comment.

---

CHANGELOG_PENDING.md
sdk/nodejs/cmd/run/run.ts

Adds an env var `PULUMI_NODEJS_TRANSPILE_ONLY`, defaulting to `false`, that controls if Pulumi will typecheck should perform any typechecking on its own. As this default is what the only allowed value was before this change, this should not break any existing workflows.
In our case, we prefer to run Pulumi separately from `tsc` to compile our code.

Allow turning ts typechecking off

---

CHANGELOG_PENDING.md
pkg/backend/filestate/backend.go

This reverts commit 8b4da4eba73cb98fe4c06b44179183562f707247 (reverts #8806).

Revert "Lock inside filestate.apply instead of Update/Delete/Import (#8806)"

---

CHANGELOG_PENDING.md
pkg/backend/display/diff.go
pkg/backend/display/progress.go
pkg/backend/display/query.go
pkg/backend/httpstate/backend.go
sdk/go/common/util/cmdutil/spinner.go

The non-interactive dot spinner functionality was not being triggered due to Interactive == true checks in calling functions.
also added color to match the output style
Fixes #6574

re-enable and color dot spinner for non-interactive mode

---

CHANGELOG_PENDING.md
pkg/codegen/go/gen_program.go
pkg/go.mod
pkg/go.sum

Add an additional function to enable configurable codegen options.
Here's an example of the generated Go code with this change:
```go
package main
import (
"github.com/pulumi/pulumi-aws/sdk/v4/go/aws/rds"
"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)
func main() {
pulumi.Run(func(ctx *pulumi.Context) error {
dbCluster, err := rds.NewCluster(ctx, "db-Cluster", &rds.ClusterArgs{
MasterPassword: pulumi.ToSecret("foobar").(pulumi.StringOutput),
})
return err
}
return nil
})
}
```
Note that this code currently won't compile due to an unused variable. We could generate a block of code like this if we wanted to guarantee that it compiles:
```go
// The following assignments are used to ignore unused variable compiler errors for generated variables.
_ = dbCluster
```
Fixes # …

[codegen/go] Add GenerateProgramWithOpts function

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/crypto_local.go
pkg/resource/stack/secrets.go
pkg/secrets/passphrase/manager.go
pkg/secrets/passphrase/manager_test.go
sdk/go/common/testing/environment.go
tests/integration/integration_nodejs_test.go
tests/integration/integration_test.go

In #2736, caching was introduced inside the passphrase secrets provider to avoid prompting the user for a password multiple times in the same `pulumi` command. However, the cache is not used in all cases, which leads to double prompting and/or erroring if the passphrase is not set in the `PULUMI_CONFIG_PASSPHRASE` envvar. In some cases, the user is prompted for their passphrase and then the command fails because the passphrase wasn't set via the envvar.
This change addresses these issues. The net effect is that when using the passphrase secrets provider, you'll be prompted for your passphrase up-front once (if interactive and the envvar isn't set), and subsequent uses will use the cached value and won't prompt or error if the envvar isn't set.
Implementation note: This moves the prompting …

Fix passphrase secrets provider prompting

---

pkg/testing/integration/program.go

While testing another feature, I needed to create a stack to exercise _only_ outputs. That stack emitted no engine events and therefore failed in programtest.

Allow trivial stack with no engine events

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/gen_completion.go

Adding alias of `completion` to follow the defacto cli options in other cobra cli tools. This is just a "nice to have" as I didn't think `pulumi` had shell completion 
Fixes #9005 
- [x ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

Adding completion alias

---

.github/workflows/build.yml
.github/workflows/master.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/run-build-and-acceptance-tests.yml
.github/workflows/run-codegen-test.yml
.github/workflows/run-docs-generation.yml
.github/workflows/test-fast.yml
.github/workflows/test.yml
tests/about_test.go

See: #9014 
* Ensures our builders & runners check that the version of go in the runner cache is the latest that matches the version requested (currently 1.17.x).
* Makes the failing test more resilient and more likely to pass on developer machines by making the test only check the major and minor version, which matches our CI system which expects go 1.17.x
Detailed build logs:
Builder (macos or ubuntu) builds Pulumi with go 1.17.7: https://github.com/pulumi/pulumi/runs/5271142183?check_suite_focus=true#step:7:14
Test harness (Windows) installs go 1.17.6 from cache: https://github.com/pulumi/pulumi/runs/5271213861?check_suite_focus=true#step:7:17
Test harness then fails on checking if the built binary's "pulumi about" result contains "go1.17.6", which it does not because it was built with …

CI: resolve build/test failures on Windows

---

CHANGELOG_PENDING.md
sdk/nodejs/automation/stack.ts

Take 2 of https://github.com/pulumi/pulumi/pull/7872
Fix following deprecation warning
```txt
(node:49420) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
```

Fix DeprecationWarning  fs.rmdir (take 2)

---

pkg/engine/lifeycletest/pulumi_test.go
pkg/resource/stack/checkpoint_test.go
pkg/resource/stack/deployment.go
pkg/resource/stack/secrets.go
pkg/resource/stack/secrets_test.go
pkg/resource/stack/testdata/checkpoint-secrets.json
pkg/resource/stack/testdata/checkpoint-v3.json
pkg/secrets/b64/manager.go
pkg/secrets/passphrase/manager.go
pkg/secrets/service/manager.go
sdk/go/common/resource/config/crypt.go
sdk/go/common/resource/config/value_test.go

The bulk decryption logic in deployment deserialization did not recur
into slices or maps. This prevented the bulk decryption of nested secret
values. These changes fix that bug, improve test coverage, and refactor
the bulk decryption code for simplicity, clarity, and separation of
concerns.
Related to https://github.com/pulumi/home/issues/1842.

[secrets] Fix + refactor bulk decryption.

---

CHANGELOG_PENDING.md
pkg/codegen/go/gen.go
pkg/codegen/testing/test/sdk_driver.go
pkg/codegen/testing/test/testdata/replace-on-change/go/example/cat.go
pkg/codegen/testing/test/testdata/simple-methods-schema/go/example/foo.go
pkg/codegen/testing/test/testdata/simple-methods-schema/schema.json
pkg/codegen/testing/test/testdata/simple-resource-schema/docs/resource/_index.md
pkg/codegen/testing/test/testdata/simple-resource-schema/dotnet/Resource.cs
pkg/codegen/testing/test/testdata/simple-resource-schema/go/example/resource.go
pkg/codegen/testing/test/testdata/simple-resource-schema/nodejs/resource.ts
pkg/codegen/testing/test/testdata/simple-resource-schema/python/pulumi_example/resource.py
pkg/codegen/testing/test/testdata/simple-resource-schema/schema.json

#7128 added code to mark properties as secret based on a schema flag, but did not correctly handle the case where output properties do not have a corresponding input property. In this case, code was generated for nonexistent input properties, and would lead to a panic.
Fixes #8967

[codegen/go] Fix secret codegen for input properties

---

CHANGELOG_PENDING.md
sdk/nodejs/cmd/run/run.ts

Fix https://github.com/pulumi/pulumi/discussions/9053

Pass project path to tsnode

---

CHANGELOG_PENDING.md
pkg/resource/deploy/source_eval.go
pkg/resource/deploy/source_eval_test.go
pkg/resource/deploy/source_query.go

When denying default providers was added, we had no special handling for
Reads and Invokes. This lead to confusing error messages. The fix (#8853)
involved checking on invokes. This check didn't apply to several types
of calls (Read) as well as blocking invokes with providers applied.
This PR fixes the logic to only deny providers when they are default
providers.
It also pushes the change into `getProviderFromSource`, which ensures
that this behavior is handled the same way (and correctly) for both
Invokes and Reads.
Fixes #9055
Fixes #9060

Fix (Read,Invoke) denied default provider handling

---

.github/workflows/test.yml

ci, workaround: temporarily disable win tests to bypass OOM

---

sdk/nodejs/Makefile

Fixed nodejs make install script by dropping `devDependencies` in `.pulumi-dev/node_modules` as it does not use them. Yarn attempts to resolve devDependencies on prod builds. Linked a discussion in #9019. Opening an issue #9027 to add CI tests for dev scripts.
Fixes #9019
Filing #9027 #9042

[sdk/nodejs] Fix make install

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/plugin_install.go
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_test.go

Fixes https://github.com/pulumi/pulumi/issues/9001

Support looking up plugin version from GitHub

---

pkg/backend/httpstate/backend.go
pkg/cmd/pulumi/login.go
pkg/cmd/pulumi/org.go

We've already tested if the current backend supports Organizations.
There's no need to type test for the httpstate.Backend as well.
Also remove `httpstate.SetDefaultOrg` which was just a straight call to `workspace.SetBackendConfigDefaultOrg`.

Remove type test in `org set-default`

---

CHANGELOG_PENDING.md
pkg/backend/backend.go
pkg/backend/filestate/backend.go
pkg/backend/filestate/backend_test.go
pkg/backend/httpstate/backend.go
pkg/backend/mock.go
pkg/cmd/pulumi/cancel.go

Does what it says on the tin, supports `pulumi cancel` for the filestate backend.
Part of https://github.com/pulumi/pulumi/issues/4605

Support `pulumi cancel` for filestate backend

---

.github/workflows/test.yml

Reverts pulumi/pulumi#9084
This was a temporary work around to allow the release process to succeed.

Revert "ci, workaround: temporarily disable win tests to bypass OOM"

---

sdk/go/common/workspace/paths.go

if someone uses `pulumi stack init` but is not in a pulumi project we display an error and suggest that they may be using `--stack` incorrectly. but we believe that may be less common, and it may be more common that folks are in the wrong directory, or haven't yet created a pulumi project. this updates the error message to include that info. super open to feedback!! also if anyone feels strongly we should not lose the stack flag message, id be happy to keep it in there, just let me know.

improve no project found error message

---

pkg/resource/deploy/step.go

OpDeleteReplaced was rendering as "delete-replacedd". Now just renders as "deleted" (same as how OpDiscardReplaced just renders as "discarded")

Fix PastTense for ops ending in 'd'

---

pkg/backend/backend.go
pkg/backend/display/display.go
pkg/backend/display/progress.go
pkg/backend/display/rows.go
pkg/backend/filestate/backend.go
pkg/backend/filestate/lock.go
pkg/backend/filestate/snapshot.go
pkg/backend/filestate/state.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/stack.go
pkg/cmd/pulumi/config.go
pkg/cmd/pulumi/crypto_cloud.go
pkg/cmd/pulumi/crypto_http.go
pkg/cmd/pulumi/crypto_local.go
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/stack_import.go
pkg/cmd/pulumi/stack_ls_test.go
pkg/cmd/pulumi/stack_rename.go
pkg/cmd/pulumi/stack_rm.go
pkg/engine/lifeycletest/test_plan.go
pkg/resource/deploy/deployment.go
pkg/resource/deploy/import.go
pkg/resource/deploy/source_eval.go
pkg/resource/deploy/source_eval_test.go
pkg/resource/deploy/step_generator.go
pkg/resource/deploy/target.go
pkg/resource/edit/operations.go
pkg/resource/edit/operations_test.go
pkg/resource/stack/checkpoint.go
sdk/go/common/util/fsutil/qname.go

Stack names don't allow "/" delimiters and as such are `tokens.Name`s not `tokens.QNames`. This goes through the "pkg" side of the codebase to change uses of stack names into `tokens.Name`, mostly this is around the `StackReference` and backend types.
As part of 4.0 we ought to follow these changes through to the "sdk" side of the codebase as well.

Make StackReference.Name a tokens.Name

---

CHANGELOG_PENDING.md
sdk/python/lib/setup.py
sdk/python/requirements.txt

Pin the version of `grpcio` that python uses to `<1.44.0`. This is a temporary measure, waiting on either a deeper fix or https://github.com/grpc/grpc/issues/29044. 
Fixes #9011

Restrict grpcio version to below 1.44.0

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/import.go

Adds a flag `--generate-code` to pulumi import. By default this is true, but users can pass `--generate-code=false` to skip the code generation step of import.
Fixes https://github.com/pulumi/pulumi/issues/9134

Add a --generate-code flag to import

---

CHANGELOG_PENDING.md
sdk/go/pulumi/context.go

This MR fixes a bug in the Go SDK where the RetainOnDelete configuration is not stored in the state file and therefore, not applied.

Fix RetainOnDelete for Go SDK

---

CHANGELOG_PENDING.md
pkg/engine/lifeycletest/pulumi_test.go
pkg/resource/deploy/step_generator.go
sdk/go/common/diag/errors.go

Validate that resource names are valid names in the step generator before trying to make URNs or anything else with them.
Fixes https://github.com/pulumi/pulumi/issues/8949

Check resource names are valid

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/new.go

When running with --yes and letting pulumi select the default project name if it was invalid you got an error message like:
`Sorry, '' is not a valid project name.`
This fixes that case to instead return the actual project name that caused the issue.
Fixes https://github.com/pulumi/pulumi/issues/8747

Fix error message in `pulumi new`

---

Makefile
scripts/get-version
sdk/dotnet/Makefile
sdk/go/Makefile
sdk/nodejs/Makefile
sdk/python/Makefile

Reverts pulumi/pulumi#9132
~When installing for homebrew, we don't have `pulumictl` available.~

Revert "Remove last few uses of get-version script"

---

sdk/go/pulumi/mocks.go
sdk/go/pulumi/run_test.go

For use in other provider / plugin projects, allows unit testing that resource options such as parent, provider, etc. are passed through correctly.

testing: allow mock contexts to get resource options

---

.github/workflows/master.yml

Verified that this checks out with https://rhysd.github.io/actionlint/, which reports some other miscellaneous issues that existed prior to #9083

ci: remove duplicate step in master branch workflow

---

CHANGELOG_PENDING.md
sdk/nodejs/automation/stack.ts

Fixes #9065: uncaught error "ENOENT: no such file or directory" when an error occurs during the stack up
_Suggestion of where to write it ?_

Fixes #9065: uncaught error "ENOENT: no such file or directory" 

---

sdk/go/common/tokens/names.go
sdk/go/common/tokens/names_test.go

I download all the stack names currently in metabase and checked this new regex against them with:
```
func TestStackNames(t *testing.T) {
f, err := os.Open("/home/fraser/query_result_2022-03-09T14_21_20.792902-08_00.csv")
log.Fatal("Unable to read input file", err)
}
defer f.Close()
r := csv.NewReader(f)
for {
rec, err := r.Read()
if err == io.EOF {
break
}
assert.NoError(t, err)
name := rec[0]
assert.True(t, IsName(name), "'%s' isn't a name", name)
}
}
```
Before the changes in this PR that flagged up a number of problematic stack names like `--diff`, `0`, `.dev`

Update tokens.Name to match what's actually in the service

---

.github/workflows/master.yml

Fix #9188 (or rather work around it)

Roll back to setup-python-v1 to avoid build failure

---

CHANGELOG_PENDING.md
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_test.go

This makes a few changes to our github authentication flow.
1) We only look at the GITHUB_TOKEN environment variable now. GITHUB_ACTOR and GITHUB_PERSONAL_ACCESS_TOKEN are no longer used. 
2) The token is sent via the Authorization header instead of Authentication, as documented at https://docs.github.com/en/rest/overview/resources-in-the-rest-api#authentication
3) We try to use this env var even when accessing the pulumi repos.
This allows us to develop plugins in private repos but continue to use our standard plugin flow.

Support plugins from private Pulumi repos

---

.github/workflows/release.yml

This PR adds a new workflow which triggers a `winget-deploy` dispatch event from pulumictl. This triggers the [pulumi-winget](https://github.com/pulumi/pulumi-winget) repository to generate a manifest of the latest pulumi release and submits it to [winget-pkgs](https://github.com/microsoft/winget-pkgs) using [winget-create](https://github.com/microsoft/winget-create)
This is an attempt at fixing #4676 though it requires more testing

Dispatch winget-deploy event on new releases

---

build/common.mk
scripts/go-test.py

Uses `--rerun-fails` with `gotestsum` to improve reliability of flakey tests.
I noticed a build error creating `/node_modules` and saw locally that if PULUMI_HOME isn't set, in the makefile the expression `$(realpath $$HOME/.pulumi-dev` doesn't do what I would expect:
makefile:
```
test_foo:
echo $(realpath $$HOME/.pulumi-dev/)
echo $(realpath $$HOME/.pulumi-dev)
```
output:
```
$ make test_foo
echo 
echo 
```
Fortunately, $HOME is very rarely not an absolute path, so I don't know what we're guarding against with realpath. If we do need to use realpath, we can change that line in common.mk to `$(realpath $(shell echo "$$HOME/.pulumi-dev"))` or even `$(shell mkdir -p $$HOME/.pulumi-dev && readlink -f $$HOME/.pulumi-dev)`, but that actually introduces another oddity: MacOS doesn't bundle …

ci: tolerate and retry fluke test failures

---

pkg/codegen/dotnet/gen_program_expressions.go
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/nodejs/gen_program_expressions.go
pkg/codegen/pcl/functions.go
pkg/codegen/python/gen_program_expressions.go

Adds the `stack`, `project` and `cwd` functions to the list of PCL built in functions. These get the stack name, project name, and current working directory respectively.

Expand pcl intrinsic functions

---

.github/workflows/master.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/run-build-and-acceptance-tests.yml
.github/workflows/test-fast.yml
.github/workflows/test.yml

n/t
CI errors on the PR may be disregarded as tests use workflow defined on @master by default, and this won't change those until it's merged. (A catch-22 we need to resolve, but separately.)

ci: disable dotnet telemetry, emit version

---

CHANGELOG_PENDING.md
sdk/go/pulumi/types.go
sdk/go/pulumi/types_test.go

In awaitInputs we didn't correctly handle the case of the input value being a pointer and the resolved destination being `interface{}`. We now handle this by allocating a new pointer of the same type of the input, and assiging that to the resolved location if resolved.Type is `any`.
Else we expect resolved.Type() to be some pointer type that the exisiting logic can handle.
Fixes https://github.com/pulumi/pulumi/issues/9192

Support pointers in pulumi.All

---

pkg/resource/deploy/deploytest/pluginhost.go

This causes invalid tests to crash instead of error.

Handle `nil` version for deploytest/pluginhost

---

pkg/backend/backend.go
pkg/backend/display/display.go
pkg/backend/display/progress.go
pkg/backend/display/rows.go
pkg/backend/filestate/backend.go
pkg/backend/filestate/lock.go
pkg/backend/filestate/snapshot.go
pkg/backend/filestate/state.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/stack.go
pkg/cmd/pulumi/config.go
pkg/cmd/pulumi/crypto_cloud.go
pkg/cmd/pulumi/crypto_http.go
pkg/cmd/pulumi/crypto_local.go
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/stack_import.go
pkg/cmd/pulumi/stack_ls_test.go
pkg/cmd/pulumi/stack_rename.go
pkg/cmd/pulumi/stack_rm.go
pkg/engine/lifeycletest/test_plan.go
pkg/resource/deploy/deployment.go
pkg/resource/deploy/import.go
pkg/resource/deploy/source_eval.go
pkg/resource/deploy/source_eval_test.go
pkg/resource/deploy/step_generator.go
pkg/resource/deploy/target.go
pkg/resource/edit/operations.go
pkg/resource/edit/operations_test.go
pkg/resource/stack/checkpoint.go
sdk/go/common/util/fsutil/qname.go

This reverts commit f0aa4df149b6d0afa9169ed59d91c92fb12e208d.
This also removes the AsName asserting casts for stack names. We do want to add them in at some point to be sure that bad names don't slip in somehow but they don't need adding with this.

Readd "Make StackReference.Name a tokens.Name (#9088)"

---

pkg/backend/httpstate/backend.go

Before:
`If you're using the --stack flag,pass the fully qualified name (org/project/stack):`
After:
`If you're using the --stack flag, pass the fully qualified name (org/project/stack):`

Add missing whitespace in error string

---

CHANGELOG_PENDING.md
pkg/backend/snapshot_test.go
pkg/engine/lifeycletest/pulumi_test.go
pkg/resource/deploy/builtins.go
pkg/resource/deploy/deploytest/provider.go
pkg/resource/deploy/step.go
pkg/resource/deploy/step_generator.go
sdk/go/common/resource/plugin/provider_plugin.go

```
I'm getting an internal assertion thrown here: https://github.com/pulumi/pulumi/blob/8b516bb05434ca8c6dac94b76a5583e855ffd0b6/sdk/go/common/resource/plugin/provider_plugin.go#L808
(Actually, it's line 807 in the stack trace, but presumably either the URN or ID is empty..)
This is in a brand new project/stack. Never been deployed. Any ideas on what I should be looking for? (edited) 
```
This was due to accidentally passing `""` as the ID in a get call. This PR fixes it so we now report an error like `Expected an ID for urn:pulumi:test::test::pkgA:m:typA::resA` rather than a panic due to an assert.

Read needs a non-empty ID

---

sdk/go/pulumi/resource_test.go

Addresses linter issues I'm hitting in a PR:
```
go/pulumi/resource_test.go:379:20: var-declaration: should omit type ResourceInput from declaration of var resourceInput; it will be inferred from the right-hand side (revive)
var resourceInput ResourceInput = NewResourceInput(resource)
^
go/pulumi/resource_test.go:381:21: var-declaration: should omit type ResourceOutput from declaration of var resourceOutput; it will be inferred from the right-hand side (revive)
var resourceOutput ResourceOutput = resourceInput.ToResourceOutput()
^
```

Fix lint issues

---

sdk/nodejs/runtime/closure/createClosure.ts
sdk/nodejs/runtime/closure/package.ts
sdk/nodejs/runtime/closure/parseFunction.ts

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with functions which work similarily but aren't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

Replace deprecated String.prototype.substr()

---

CHANGELOG_PENDING.md
pkg/engine/lifeycletest/pulumi_test.go
pkg/resource/deploy/step_generator.go

If `Check` returns failures it won't return any new inputs that we can check plans against. The resource will failed anyway because of the check failure so we can just skip checking against the update plan.
Fixes https://github.com/pulumi/pulumi/issues/9247

Don't check update plans against invalid resources

---

sdk/dotnet/Pulumi/Pulumi.csproj

Upgraded `Serilog.Sinks.Console` to version 4.
Fixes #8994

 fix: #8994

---

CHANGELOG_PENDING.md
sdk/nodejs/cmd/run/run.ts
sdk/nodejs/package.json

[area/nodejs] Take engines property into account when engine-strict appear in .npmrc file

---

CHANGELOG_PENDING.md
sdk/nodejs/automation/stack.ts

Same fix as in https://github.com/pulumi/pulumi/pull/9097 but for the preview command.

Fix #9065 for previews

---

CHANGELOG_PENDING.md
pkg/codegen/go/gen.go
pkg/codegen/testing/test/testdata/external-resource-schema/go/example/argFunction.go
pkg/codegen/testing/test/testdata/output-funcs-edgeorder/go/myedgeorder/listConfigurations.go
pkg/codegen/testing/test/testdata/output-funcs-edgeorder/go/myedgeorder/listProductFamilies.go
pkg/codegen/testing/test/testdata/output-funcs-tfbridge20/go/mypkg/getAmiIds.go
pkg/codegen/testing/test/testdata/output-funcs-tfbridge20/go/mypkg/listStorageAccountKeys.go
pkg/codegen/testing/test/testdata/output-funcs/go/mypkg/funcWithAllOptionalInputs.go
pkg/codegen/testing/test/testdata/output-funcs/go/mypkg/funcWithDefaultValue.go
pkg/codegen/testing/test/testdata/output-funcs/go/mypkg/funcWithDictParam.go
pkg/codegen/testing/test/testdata/output-funcs/go/mypkg/funcWithListParam.go
pkg/codegen/testing/test/testdata/output-funcs/go/mypkg/getBastionShareableLink.go
pkg/codegen/testing/test/testdata/output-funcs/go/mypkg/getIntegrationRuntimeObjectMetadatum.go
pkg/codegen/testing/test/testdata/output-funcs/go/mypkg/listStorageAccountKeys.go
pkg/codegen/testing/test/testdata/plain-object-defaults/go/example/funcWithAllOptionalInputs.go
pkg/codegen/testing/test/testdata/plain-object-disable-defaults/go/example/funcWithAllOptionalInputs.go
pkg/codegen/testing/test/testdata/simple-resource-schema-custom-pypackage-name/go/example/argFunction.go
pkg/codegen/testing/test/testdata/simple-resource-schema/go/example/argFunction.go

@guineveresaenger how about this version? The `fmt.Errorf()` ran into some issues with having to import `fmt` which unfortunately are still really pesky in our go codegen, we need to work out automatic `import()` section fixup. The alternate version simply coerces `nil` to empty struct. I don't think it's much of a problem as this should not arise really in practice - the underlying code should `err` or else return non-nil. The original error is fixed in this version by guarding `*r` by a nil check.
I've then auto-updated the test cases to match:
```
cd pkg/codegen/go
PULUMI_ACCEPT=1 go test -test.v
```

Fix generated code panic on *nil

---

CHANGELOG_PENDING.md
pkg/backend/display/json.go
pkg/engine/lifeycletest/golang_sdk_test.go
pkg/engine/lifeycletest/pulumi_test.go
pkg/resource/deploy/import.go
pkg/resource/deploy/plan.go
pkg/resource/deploy/snapshot.go
pkg/resource/deploy/source_eval_test.go
pkg/resource/deploy/step.go
pkg/resource/deploy/step_generator.go
pkg/resource/stack/deployment.go
pkg/resource/stack/deployment_test.go
sdk/go/common/apitype/core.go
sdk/go/common/resource/resource_state.go

This reverts commit 17068e9b4907cc22acc65c3f80aca2f6aa8caa9f.
Turns out NormalizeURNReferences needs this in the state to fix up URNs while the deployment is running. It feels like we should be able to either thread this information through to the snapshot manager another way but it's not obvious how. It's also tricky to test because snapshot code differs massively in unit tests compared to proper runs.

Revert "Strip Aliases from state (#9275)"

---

CHANGELOG_PENDING.md
pkg/codegen/go/gen.go
pkg/codegen/testing/test/testdata/external-resource-schema/go/example/argFunction.go
pkg/codegen/testing/test/testdata/output-funcs-edgeorder/go/myedgeorder/listConfigurations.go
pkg/codegen/testing/test/testdata/output-funcs-edgeorder/go/myedgeorder/listProductFamilies.go
pkg/codegen/testing/test/testdata/output-funcs-tfbridge20/go/mypkg/getAmiIds.go
pkg/codegen/testing/test/testdata/output-funcs-tfbridge20/go/mypkg/listStorageAccountKeys.go
pkg/codegen/testing/test/testdata/output-funcs/go/mypkg/funcWithAllOptionalInputs.go
pkg/codegen/testing/test/testdata/output-funcs/go/mypkg/funcWithDefaultValue.go
pkg/codegen/testing/test/testdata/output-funcs/go/mypkg/funcWithDictParam.go
pkg/codegen/testing/test/testdata/output-funcs/go/mypkg/funcWithListParam.go
pkg/codegen/testing/test/testdata/output-funcs/go/mypkg/getBastionShareableLink.go
pkg/codegen/testing/test/testdata/output-funcs/go/mypkg/getIntegrationRuntimeObjectMetadatum.go
pkg/codegen/testing/test/testdata/output-funcs/go/mypkg/listStorageAccountKeys.go
pkg/codegen/testing/test/testdata/plain-object-defaults/go/example/funcWithAllOptionalInputs.go
pkg/codegen/testing/test/testdata/plain-object-disable-defaults/go/example/funcWithAllOptionalInputs.go
pkg/codegen/testing/test/testdata/simple-resource-schema-custom-pypackage-name/go/example/argFunction.go
pkg/codegen/testing/test/testdata/simple-resource-schema/go/example/argFunction.go

Fixes https://github.com/pulumi/pulumi-aws/issues/1872.
This should result in the following sample output in the Go SDK:
```
func GetPolicyDocumentOutput(ctx *pulumi.Context, args GetPolicyDocumentOutputArgs, opts ...pulumi.InvokeOption) GetPolicyDocumentResultOutput {
return pulumi.ToOutputWithContext(context.Background(), args).
ApplyT(func(v interface{}) (GetPolicyDocumentResult, error) {
args := v.(GetPolicyDocumentArgs)
r, err := GetPolicyDocument(ctx, &args, opts...)
return nil, err
}
if r == nil {
return nil, fmt.Errorf("expected either result or error to be nil, not both")
}
return *r, err
}).(GetPolicyDocumentResultOutput)
}
```

[codegen/go] Update Go SDK function output to check for errors

---

pkg/backend/display/progress.go
pkg/cmd/pulumi/logs.go
pkg/cmd/pulumi/pulumi.go
pkg/go.mod
pkg/go.sum
tests/go.mod
tests/go.sum

We depend on a fairly old version of the Docker dependency, which was flagged with a a CVE on another repo that depends on pulumi/pulumi.
https://github.com/advisories/GHSA-g7v2-2qxx-wjrw
This updates Docker related dependencies to supported versions, and follows the deprecation warning on the term package that it was refactored to a separate repo.

sec: address dependabot issue in docker dep

---

build/common.mk
sdk/dotnet/Makefile
sdk/go/Makefile
sdk/nodejs/Makefile
sdk/python/Makefile

I want to package the pulumi python sdk for my linux distribution www.nixos.org. 
One difficulty is that the shell is not in /bin/bash on that system (there is only /bin/sh, bash is at /nix/store/3pa0xk3mgmx7hqskg63gxviyw7f217i6-bash-interactive-5.1-p12/bin/bash for instance)
When running the tests I would like to be able to override the SHELL value without having to patch all the Makefiles, hence the change.
I also added a way to bypass the `pulumictl get version`. I dont know how it works but it seems like it needed a git repo ? I already know the version from the nix package so I wanted to skip that altogether.

allow to override makefile variables

---

pkg/backend/snapshot.go

Adds a defensive nil check matching the one shortly before in the same function.

Fix panic in snapshot.go

---

CHANGELOG_PENDING.md
pkg/resource/deploy/plan.go

I had assumed that we would never get a nil input map, but we don't actually constraint `Check` to return non-nil. It can return nil instead of empty.
Fixes https://github.com/pulumi/pulumi/issues/9247

Input map may be nil

---

CHANGELOG_PENDING.md
pkg/engine/journal.go
pkg/engine/lifeycletest/golang_sdk_test.go
pkg/engine/lifeycletest/provider_test.go
pkg/engine/lifeycletest/pulumi_test.go
pkg/engine/lifeycletest/test_plan.go
pkg/resource/deploy/step_generator.go

As we discovered when removing aliases from the state entirely, the
snapshotter needs to be alias-aware so that it can fix up references to
resources that were aliased. After a resource operation finishes, the
snapshotter needs to write out a new copy of the snapshot. However, at
the time we write the snapshot, there may be resources that have not yet
been registered that refer to the just-registered resources by a
different URN due to aliasing. Those references need to be fixed up
prior to writing the snapshot in order to preserve the snapshot's
integrity (in particular, the property that all URNs refer to resources
that exist in the snapshot).
For example, consider the following simple dependency graph: A <-- B.
When that graph is serialized, B will contain a reference to A in its …

[engine] Only record a resource's chosen alias.

---

pkg/backend/httpstate/client/api.go
pkg/backend/httpstate/client/client.go
pkg/backend/httpstate/client/client_test.go

This change introduces internal `httpClient` and `restClient` abstractions in the `httpstate` backend, along with a `newClient` function variable that can be used to customize the `*Client` returned from `NewClient`.

Add internal abstractions in backend/httpstate/client

---

pkg/testing/integration/program.go

There was a small hiccup with trying to run a ProgramTest without an actual update, that is:
```go
integration.ProgramTestOptions{
Config: map[string]string{
"aws:region": "us-west-1",
},
SkipRefresh:            true,
SkipEmptyPreviewUpdate: true,
SkipExportImport:       true,
SkipUpdate:             true,
}
```
Event log is being asked only from `pulumi up` commands, consequently it's empty when there's no such commands. Then the parsing logic proceeds to ignore non-existent file, but tries to parse json events out of the resulting empty stream, and fails.
With these changes:
- eventLog field renamed to updateEventLog to highlight what it is
- parsing logic does not error out when the file does not exist but instead returns an empty log slice
And I can now run tests with these options …

Fix issue with parsing empty engine logs

---

.vscode/settings.json
pkg/secrets/service/manager.go
pkg/util/testutil/testdiagsink.go
sdk/go/common/diag/sink.go

defaultSink calls `Color.Colorize` which will panic if Color isn't one of the expected options. We just trying to catch the most egregious failings here where Color has been left blank because of a default initialized `FormatOptions` struct.

Ensure that FormatOptions.Color is set before use in diag.defaultSink

---

pkg/cmd/pulumi/about.go

Fix typo in `pulumi about` ([pkg/cmd/pulumi/about.go](https://github.com/pulumi/pulumi/compare/master...aetheryx:patch-1#diff-0e269f8c30430af0c9555b9bf13c3940d3befb38488a55dd36e330e990dd6b0e)): `Puluimi` -> `Pulumi`
Reason: shouldn't need a test
Reason: I don't think typo fixes make it into the changelog, but can update the pending changelog if they should

Fix typo in `pulumi about`

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/errors.go
pkg/engine/lifeycletest/pulumi_test.go
pkg/resource/deploy/deployment.go
pkg/resource/deploy/deployment_executor.go

Fixes #4265
This PR changes the deployment execution such that it no longer errors out when there are pending operations. Instead, it only warns the users and explains that they can use `pulumi refresh` to clear the operations and they will no longer see the warning (unless there are pending `create` operations)

Warn users when there are pending operations but proceed with deployment

---

CHANGELOG_PENDING.md
pkg/engine/diff.go
pkg/engine/events.go
pkg/engine/lifeycletest/pulumi_test.go

Instead of replacing `Secret` values with the text `[secret]`, retain
the `Secret` value and replace its element with the text `[secret]`.
This allows downstream consumers (e.g. the CLI's diff renderer) to
understand that the contents of the value is secret if necessary.
Concretely, this fixes an issue in which differences in nested
properties of secret object values would not render correctly.

[events] Retain `Secret` values.

---

CHANGELOG_PENDING.md
pkg/resource/deploy/step_generator.go

Warn when `additionalSecretOutputs` includes `id`

---

pkg/backend/apply.go
pkg/backend/display/diff.go
pkg/backend/display/display.go
pkg/backend/display/events.go
pkg/backend/display/progress.go
pkg/backend/display/watch.go
pkg/backend/httpstate/state.go
pkg/cmd/pulumi/pulumi.go
pkg/cmd/pulumi/replay_events.go

This command renders a recorded stream of engine events using either the
progress or diff renderer. This is useful for debugging problems with
these renderers.

[cli] Add a replay-events debug command.

---

pkg/backend/display/diff.go
pkg/backend/display/object_diff.go
pkg/backend/display/progress.go
pkg/backend/display/rows.go
pkg/engine/detailedDiff.go
pkg/engine/detailedDiff_test.go

- Move the code that deals in translating detailed diffs into object
diffs out of package `backend/display` and into package `engine`
- Move the code that deals in displaying diffs out of package `engine`
and into package `backend/display`

[display] Refactor diff translation and display.

---

CHANGELOG_PENDING.md
pkg/codegen/nodejs/gen.go
pkg/codegen/nodejs/gen_test.go
pkg/codegen/nodejs/utilities.go
pkg/codegen/nodejs/utilities_test.go

Fixes https://github.com/pulumi/pulumi/issues/9342

Escape deprecation messages before interpolating into source text

---

CHANGELOG_PENDING.md
pkg/engine/lifeycletest/pulumi_test.go
pkg/resource/stack/deployment.go
pkg/resource/stack/secrets.go
pkg/resource/stack/secrets_test.go
pkg/secrets/b64/manager.go
pkg/secrets/passphrase/manager.go
pkg/secrets/service/manager.go
sdk/go/common/resource/config/crypt.go
sdk/go/common/resource/config/value_test.go

`BulkDecrypt` only made use of the bulk decryption if the `Decrypter` passed in was itself a `BulkDecrypter`. Only the `serviceCrypter` implemented this interface but most of the time it's wrapped with a `cachingCrypter`.
Rather than just adding BulkDecrypt to `cachingCrypter` I've just moved it to the `Decrypter` interface and ensured that every  implementation either does something efficient if it can, or calls `DefaultBulkDecrypt` to just loop over 1-by-1. 
Fixes https://github.com/pulumi/pulumi/issues/9350

Change BulkDecrypt to not rely on type tests

---

sdk/go/auto/stack.go

Background
---
Automation API Color flag should pass unquoted string:
```
error: unsupported color option: '\"auto\"'
```
Since we're using ["os/exec"](https://pkg.go.dev/os/exec) there is no shell, I think we should not quote arguments?
> Unlike the "system" library call from C and other languages, the os/exec package intentionally does not invoke the system shell

fix: Automation API Color flag should pass unquoted string

---

pkg/testing/integration/command.go

I had wanted this to ensure that dynamic providers were working correctly, but we also have test providers that we don't install as proper plugins.

Don't disable ambient providers during tests

---

.github/workflows/run-docs-generation.yml

the body text on the prs that get auto-opened over in docs
don't mention that they need to be manually closed
this adds a note about it
preview of the msg can be seen here: https://github.com/pulumi/docs/pull/7360#issue-1206176566

updating body text of downstream resource docs prs

---

CHANGELOG_PENDING.md
pkg/backend/display/object_diff.go
pkg/backend/display/testdata/up-4.json.stdout.txt

When rendering an array diff, do not render an unchanged element if we
do not have a value for the element.
Fixes #9365.

[cli] Do not render missing sames in arrays.

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/destroy.go

Previously, "down" was a suggestion for "destroy". This commit makes it an alias instead, to give symmetry of "up" => "down".
No test coverage of command aliases, assumed to work by virtue of Cobra upstream testing.
No changes.

cli: Make "down" an alias of "destroy"
