pulumi/pulumi

.github/workflows/test-fast.yml
.github/workflows/test.yml

Use python not python3 in test.yml

---

.github/workflows/test-fast.yml
.github/workflows/test.yml

PR #8617 inadvertently broke coverage collection and reporting for
NodeJS and .NET.

[ci] Restore code coverage data for Node/.NET

---

CHANGELOG_PENDING.md

Clean CHANGELOG_PENDING.md

---

sdk/dotnet/Pulumi.Automation.Tests/LocalPulumiCmdTests.cs

This test was flakey for me when building on Windows & *nix using different versions of the dotnet framework or depending on whether I had an up to date Pulumi version installed. The regex match is to blame.
On old versions during CI when we do build a version locally, we expect a message on stdout advising that a new version is available. If the user hasn't built the language provider locally or has the current version built, we expect an empty string.
Rather than use regex, which had inconsistent matching behavior and as usual, caused two problems, we just test if the string is nonempty first.
Once and for all, this resolves this test passing the matrix consisting of:
Pulumi version   |    OS   | .NET SDK
---------------- | ------- | --------
3.21.1 (old)     | Windows | 3.1
3.21.1 …

[sdk/dotnet] Fix inconsistent automation test

---

pkg/codegen/dotnet/gen_program_expressions.go
pkg/codegen/dotnet/utilities.go
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/go/gen_program_utils.go
pkg/codegen/nodejs/gen_program.go
pkg/codegen/nodejs/gen_program_expressions.go
pkg/codegen/nodejs/gen_program_utils.go
pkg/codegen/pcl/functions.go
pkg/codegen/python/gen_program.go
pkg/codegen/python/gen_program_expressions.go
pkg/codegen/python/gen_program_utils.go

Implemented filebase64sha256 support for code generator, and fileArchive support for Go.
Pairs with: https://github.com/pulumi/pulumi-terraform-bridge/pull/391

Implemented filebase64sha256 & fileArchive support for codegen

---

.github/workflows/test-fast.yml
.github/workflows/test.yml

Small fix to the Go Cache stanzas in test.yml/test-fast.yml - we need code checked out before hashing go.sum takes effect.

Checkout repo before hashing go.sum for cache keys

---

sdk/python/lib/pulumi/resource.py

Improve Python SDK types

---

CHANGELOG.md

Prepare for v3.23.0 release

---

pkg/go.mod
tests/go.mod

Update pkg -> sdk dependency

---

.github/workflows/test-fast.yml
.github/workflows/test.yml

Cleaned up version of https://github.com/pulumi/pulumi/pull/8832

Windows test failures don't affect check result

---

.github/workflows/release.yml

Ignore checksum mismatch temporarily

---

CHANGELOG.md

Prepare for v3.23.2 release

---

pkg/testing/integration/program.go

This change allows to opt-out of the "unrecognized project runtime" error that assumes that no other languages are supported. This helps to write Pascal tests for example.

Abstract PrepareProject in programtest to allow more PLs

---

pkg/cmd/pulumi/util.go

Workaround for https://github.com/AlecAivazis/survey/issues/342
Fixes https://github.com/pulumi/pulumi/issues/8887

Workaround for surveycore bug with empty defaults

---

pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/up.go

Fixes https://github.com/pulumi/pulumi/issues/8889

Enable planning if a plan file path is given

---

CONTRIBUTING.md

Part of https://github.com/pulumi/home/issues/1779
Brushes up language, refreshes information (we no longer use Travis) and links to community resources and CoC.

Update contributor guide

---

CHANGELOG_PENDING.md
pkg/backend/apply.go
pkg/backend/display/display.go
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/policy_new.go
pkg/cmd/pulumi/state.go
pkg/cmd/pulumi/util.go
pkg/go.mod
pkg/go.sum
tests/go.mod
tests/go.sum

Reverts #8858 #8888 
Fixes #8912 [slack thread](https://pulumi.slack.com/archives/CBUP505U7/p1643713912052759)

reverted 8ffac5c (#8858) (#8888) CLI issues

---

CHANGELOG.md

Update changelog for 3.24.0

---

.gitignore

Ignore build artifacts for clean git state

---

CHANGELOG.md

Prepare for v3.24.1 release

---

pkg/codegen/go/gen_program_expressions.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/invalid-go-sprintf-pp/go/invalid-go-sprintf.go
pkg/codegen/testing/test/testdata/invalid-go-sprintf-pp/invalid-go-sprintf.pp

Fix 8940 invalid go code generated

---

pkg/resource/deploy/source_eval.go

Explicitly catch invokes with denied default providers and give a
helpful error message.
Improves https://github.com/pulumi/pulumi/issues/8853

Improve error handling for denied Invokes

---

CHANGELOG_PENDING.md
pkg/backend/snapshot.go

Fixes https://github.com/pulumi/pulumi/issues/9002

Fix snapshot assert for replacement deletes

---

pkg/testing/integration/program.go

Revert "Allow trivial stack with no engine events"

---

CHANGELOG.md

Prepare for v3.25.1 release

---

CHANGELOG_PENDING.md

Cleanup changelog pending

---

pkg/backend/backend.go
pkg/backend/display/display.go
pkg/backend/display/progress.go
pkg/backend/display/rows.go
pkg/backend/filestate/backend.go
pkg/backend/filestate/lock.go
pkg/backend/filestate/snapshot.go
pkg/backend/filestate/state.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/stack.go
pkg/cmd/pulumi/config.go
pkg/cmd/pulumi/crypto_cloud.go
pkg/cmd/pulumi/crypto_http.go
pkg/cmd/pulumi/crypto_local.go
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/stack_import.go
pkg/cmd/pulumi/stack_ls_test.go
pkg/cmd/pulumi/stack_rename.go
pkg/cmd/pulumi/stack_rm.go
pkg/engine/lifeycletest/test_plan.go
pkg/resource/deploy/deployment.go
pkg/resource/deploy/import.go
pkg/resource/deploy/source_eval.go
pkg/resource/deploy/source_eval_test.go
pkg/resource/deploy/step_generator.go
pkg/resource/deploy/target.go
pkg/resource/edit/operations.go
pkg/resource/edit/operations_test.go
pkg/resource/stack/checkpoint.go
sdk/go/common/util/fsutil/qname.go

Revert "Make StackReference.Name a tokens.Name"

---

CHANGELOG.md

Prepare for v3.26.1 release

---

sdk/go/common/workspace/plugins.go

Opt new language plugins out of the some of the special cases we currently have for bundled language plugins.

Only special case the bundled language plugins

---

pkg/backend/httpstate/backend.go

Suggest to use fully qualified stack name with --stack

---

sdk/go/common/workspace/plugins.go

A bit more guidance to users working with projects with providers distributed via private repos.
```
$ pulumi up --yes
error: failed to load language plugin pascal: no language plugin 'pascal' found in the workspace or on your $PATH
$ pulumi plugin install language pascal
error: 404 HTTP error fetching plugin from https://api.github.com/repos/pulumi/pulumi-pascal/releases/latest
$ export GITHUB_TOKEN=$(pass github.com/pa-token-pascal)
$ pulumi plugin install language pascal
$ pulumi up --yes
```

Improve errmsgs arising from using plugins in private GitHub repos

---

.github/workflows/test.yml

Try and fix the memory limits we seem to be hitting

Lower windows test parallelism

---

sdk/nodejs/package.json

Upgrade minimist package to 1.2.6

---

CHANGELOG_PENDING.md
pkg/backend/display/json.go
pkg/engine/lifeycletest/golang_sdk_test.go
pkg/engine/lifeycletest/pulumi_test.go
pkg/resource/deploy/import.go
pkg/resource/deploy/plan.go
pkg/resource/deploy/snapshot.go
pkg/resource/deploy/source_eval_test.go
pkg/resource/deploy/step.go
pkg/resource/deploy/step_generator.go
pkg/resource/stack/deployment.go
pkg/resource/stack/deployment_test.go
sdk/go/common/apitype/core.go
sdk/go/common/resource/resource_state.go

Strip Aliases from state

---

CHANGELOG.md

Prepare for v3.27.0 release

---

pkg/go.mod
tests/go.mod

Update go.mod and run tidy

---

pkg/backend/httpstate/backend.go
pkg/backend/httpstate/client/api.go
pkg/backend/httpstate/client/client.go
pkg/backend/httpstate/policypack.go
pkg/cmd/pulumi/policy_group_ls.go
pkg/cmd/pulumi/stack_rename.go
sdk/go/auto/local_workspace.go
sdk/go/auto/local_workspace_test.go

Small set of changes with some minor code improvements:
- Wrap some errors for improved debugging
- Improve import ordering
- Add some useful comments

Minor code improvements

---

CHANGELOG_PENDING.md

To be merged post v3.28.0 release.

Cleanup CHANGELOG_PENDING.md post release

---

sdk/python/.pylintrc
sdk/python/lib/pulumi/_utils.py
sdk/python/lib/setup.py
sdk/python/mypy.ini
sdk/python/requirements.txt

Follow on from https://github.com/pulumi/pulumi/pull/9336

Unpin protobuf, teach pylint about generated members

---

sdk/go/common/resource/plugin/plugin.go

While today all plugins are processes we have plans to also run plugins via other methods. The only thing the process object was used for on the plugin struct was to kill it, so I've weakened the interface to just require a `Kill` method. We'll be able to implement that for our other plugin runners as well.

Replace plugin.Proc with Kill

---

sdk/go.mod
sdk/go.sum

Fix sdk/go.{mod,sum}

---

README.md

the resources listed in the readme were a little bit outdated, this updates them. super open to any feedback on the resources i selected and the words used to describe them.

updating the resources in the readme

---

pkg/codegen/pcl/rewrite_convert.go

Change pcl.LowerConversion to allow invalid conversions

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/plugin.go
pkg/cmd/pulumi/up.go

Fixes https://github.com/pulumi/pulumi/issues/9437

Fix a missing context close

---

pkg/cmd/pulumi/convert.go
pkg/cmd/pulumi/pulumi.go

First pass at a pulumi convert command to go from one "language" to another. Currently for internal experimentation.

pulumi convert command

---

CHANGELOG_PENDING.md
pkg/codegen/dotnet/gen_program_expressions.go
pkg/codegen/go/gen_program.go
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/nodejs/gen_program_expressions.go
pkg/codegen/pcl/functions.go
pkg/codegen/pcl/rewrite_apply.go
pkg/codegen/pcl/type.go
pkg/codegen/python/gen_program_expressions.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/assets-archives-pp/assets-archives.pp
pkg/codegen/testing/test/testdata/assets-archives-pp/dotnet/assets-archives.cs
pkg/codegen/testing/test/testdata/assets-archives-pp/go/assets-archives.go
pkg/codegen/testing/test/testdata/assets-archives-pp/nodejs/assets-archives.ts
pkg/codegen/testing/test/testdata/assets-archives-pp/python/assets-archives.py

Implements `RemoteAsset`, `RemoteArchive`, `StringAsset`, and `AssetArchive` in our intermediate representation and code generation for each language.

codegen for all assets and archives types

---

CHANGELOG.md

Prepare for v3.31.0 release

---

CHANGELOG_PENDING.md
pkg/codegen/go/gen.go
pkg/codegen/testing/test/testdata/dashed-import-schema/go/plant-provider/pulumiTypes.go
pkg/codegen/testing/test/testdata/different-enum/go/plant/pulumiTypes.go
pkg/codegen/testing/test/testdata/go-plain-ref-repro/go/repro/ecs/fargateTaskDefinition.go
pkg/codegen/testing/test/testdata/go-plain-ref-repro/go/repro/ecs/pulumiTypes.go
pkg/codegen/testing/test/testdata/plain-object-defaults/go/example/mod1/pulumiTypes.go
pkg/codegen/testing/test/testdata/plain-object-defaults/go/example/mod2/pulumiTypes.go
pkg/codegen/testing/test/testdata/plain-object-defaults/go/example/pulumiTypes.go
pkg/codegen/testing/test/testdata/plain-schema-gh6957/go/xyz/staticPage.go
pkg/codegen/testing/test/testdata/simple-enum-schema/go/plant/pulumiTypes.go
pkg/codegen/testing/test/testdata/simple-plain-schema-with-root-package/go/component.go
pkg/codegen/testing/test/testdata/simple-plain-schema/go/example/component.go
pkg/codegen/utilities_types.go

Shallow Plain Types

---

sdk/python/cmd/pulumi-language-python/main.go

Raised from https://github.com/pulumi/pulumi/issues/9128

Wrap pip error with text showing command called

---

sdk/go/pulumi/context.go

Required to fix:
- https://github.com/pulumi/pulumi-yaml/issues/193

[sdk/go] ensure that raw output API tracks dependencies

---

.github/workflows/master.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml

One more fix folks, apologies, almost there. Last master run had valid checksums but failed to upload to S3.

Fix secret name typo

---

CHANGELOG.md

Prepare for v3.5.0 release

---

CHANGELOG_PENDING.md

cleaned up CHANGELOG_PENDING.md

---

.github/workflows/release.yml

Will uncomment tests after release.

disabled tests to workaround protobuf issues

---

pkg/codegen/schema/loader.go
pkg/codegen/schema/loader_schema_test.go

Found another place we copy the schema.

[engine] Remove a copy of schema bytes, use regexp over string.

---

pkg/codegen/schema/loader_schema_test.go

Fix the master build with t.Parallel()

Fix the master build with t.Parallel()

---

CHANGELOG_PENDING.md
pkg/engine/plugins.go
pkg/engine/plugins_test.go
sdk/go/common/workspace/plugins.go

Apply a lexiographic sort on equal plugins

---

tests/integration/delete_before_create/step1/package.json
tests/integration/delete_before_create/step1/resource.ts

Fix build: Import uuid/v4 differently

---

CHANGELOG_PENDING.md
pkg/backend/filestate/state.go

improved filestateBackend search prefix

---

CHANGELOG_PENDING.md
pkg/backend/filestate/state.go

Fixes #9795
Area is already covered by integration test (hence master is red).

Fix master: test local state gzip

---

pkg/go.mod
pkg/go.sum
scripts/get-language-providers.sh

Point to pulumi-yaml 0.5.1

---

pkg/testing/integration/util.go
sdk/go/common/resource/asset.go
sdk/go/common/resource/asset_test.go
sdk/go/common/util/archive/archive.go

More error checks for https://github.com/pulumi/pulumi/issues/9789

Add some more checks that io.Copy copies as much as expected

---

CHANGELOG.md

Prepare for v3.35.0 release

---

CHANGELOG.md

Prepare for v3.35.1 release

---

pkg/cmd/pulumi/destroy.go

Refine the description of destroy command to be more accurate

---

CHANGELOG_PENDING.md
pkg/resource/deploy/step_generator.go

Fixes https://github.com/pulumi/pulumi/issues/9985

Use set logic to mininize the number of aliases

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/plugin_ls.go

Fix a panic in pulumi plugin ls --project --json

---

pkg/codegen/dotnet/gen_program_expressions.go
pkg/codegen/testing/test/testdata/functions-pp/dotnet/functions.cs

Use a correct class name for UTF8 in C# programgen

---

CHANGELOG_PENDING.md
pkg/engine/lifecycletest/target_test.go
pkg/resource/deploy/step_generator.go

This reverts commit 7ebba683d905e7cc50ac210e0d7cb6d6c523d184.

Revert "Filter non-targeted resource out much earlier (#9960)"

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/convert.go

Update `pulumi convert`  help text

---

pkg/go.mod
pkg/go.sum
scripts/get-language-providers.sh
tests/go.sum

Use released java 0.4.1

---

CHANGELOG_PENDING.md
pkg/resource/deploy/deployment_executor.go
pkg/resource/deploy/deployment_executor_test.go
sdk/proto/.checksum.txt

Unparent deleted resources when rebuilding state

---

pkg/codegen/dotnet/gen_program_expressions.go
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/nodejs/gen_program_expressions.go
pkg/codegen/python/gen_program_expressions.go

This enables azure-native to generate examples.

Remove programgen conversion assertions

---

CHANGELOG.md

Update Changelog for 3.36.0

---

pkg/cmd/pulumi/plugin.go
pkg/engine/plugins.go
sdk/go/common/resource/plugin/analyzer_plugin.go
sdk/go/common/resource/plugin/langruntime_plugin.go
sdk/go/common/resource/plugin/provider_plugin.go
sdk/go/common/workspace/plugins.go

Just a couple of sanity changes based on a comment from Harry on https://github.com/pulumi/pulumi/pull/10146

Change GetPluginPath to assert the paths are as expected and use the paths calculated 

---

pkg/cmd/pulumi/convert.go
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/plugin.go
pkg/cmd/pulumi/policy_publish.go
pkg/cmd/pulumi/up.go
pkg/engine/deployment.go
pkg/engine/query.go
sdk/go/common/resource/plugin/context.go
sdk/go/common/resource/plugin/host.go

Simple change, this stuff just simply wasn't used so rip it all out.

Remove config from host, was unused

---

pkg/testing/integration/program.go
tests/integration/integration_dotnet_test.go
tests/integration/integration_go_test.go
tests/integration/integration_nodejs_test.go
tests/integration/integration_python_test.go
tests/integration/integration_test.go

Little experiment to use plugin links rather than PATH manipulation.

Use plugin link instead of PATH manipulation in programtest

---

tests/integration/get_resource/dotnet/Program.cs
tests/integration/get_resource/go/main.go
tests/integration/get_resource/nodejs/index.ts
tests/integration/get_resource/python/__main__.py
tests/integration/integration_dotnet_test.go
tests/integration/integration_go_test.go
tests/integration/integration_nodejs_test.go

Check that secrets remain encrypted

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi.Tests/Serialization/ListOutputCompletionSourceTests.cs
sdk/dotnet/Pulumi/Serialization/Serializer.cs

Fixes https://github.com/pulumi/pulumi/issues/10275

Fix InitializedByDefault for non-generic types

---

CHANGELOG.md
CHANGELOG_PENDING.md
pkg/backend/httpstate/state.go

Reverts pulumi/pulumi#10168 to fix #10293

Revert "Remove api/renewLease from startup crit path"

---

README.md

pls let me know what i got wrong, thank you!

add java+yaml to readme

---

sdk/dotnet/Pulumi.FSharp/Pulumi.FSharp.fsproj

Pin FSharp.Core explicitly to >= 4.7.2

---

sdk/go/pulumi/provider.go

Allow tags in construct decoder

---

pkg/go.mod
pkg/go.sum
scripts/get-language-providers.sh

bump java v0.5.3

---

CHANGELOG_PENDING.md
pkg/codegen/go/doc.go
pkg/codegen/go/gen.go
pkg/codegen/go/gen_crd2pulumi.go
pkg/codegen/go/gen_program.go
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/go/gen_program_test.go
pkg/codegen/go/gen_test.go

Revert "Expose external package cache"

---

pkg/go.mod
pkg/go.sum

chore: Move aaronfriel/ssh-agent fork to pulumi/ssh-agent

---

tests/about_test.go

Fix json formatted pattern match on "about" test

---

sdk/python/lib/pulumi/output.py
sdk/python/lib/test/test_output.py

Fix Python SDK apply causing program hangs

---

CHANGELOG_PENDING.md
pkg/codegen/go/gen_program.go

Part of pulumi/pulumi-yaml#306.

[codegen/go] Use correct method name for loading float config values

---

CONTRIBUTING.md

Added s to fix typo

---

CONTRIBUTING.md

Brief note about a required environment variable when running integration tests.

chore: Adds note about integration test environment config

---

pkg/codegen/schema/schema.go

Add `omitempty` for some fields missing it.

Omit more empty fields in PackageSpec

---

pkg/codegen/nodejs/gen_test.go

Fix concurrent map write panic in node codegen test

---

sdk/python/lib/pulumi/automation/_stack.py
sdk/python/lib/pulumi/dynamic/__main__.py
sdk/python/lib/pulumi/provider/server.py
sdk/python/lib/test/langhost/util.py

[sdk/python] Use loopback addresses for providers & automation API

---

CHANGELOG_PENDING.md
sdk/go/common/util/archive/archive.go
sdk/go/common/util/archive/archive_test.go

For https://github.com/pulumi/pulumi/issues/10488

Look at .gitignore files above dir

---

pkg/cmd/pulumi/about.go
pkg/cmd/pulumi/plugin.go
pkg/cmd/pulumi/plugin_install.go
pkg/cmd/pulumi/plugin_ls.go
pkg/codegen/schema/loader.go
pkg/engine/lifecycletest/provider_test.go
pkg/engine/lifecycletest/pulumi_test.go
pkg/engine/plugins.go
pkg/engine/plugins_test.go
pkg/engine/update.go
pkg/resource/deploy/deployment.go
pkg/resource/deploy/deploytest/languageruntime.go
pkg/resource/deploy/deploytest/pluginhost.go
pkg/resource/deploy/providers/registry_test.go
pkg/resource/deploy/source_eval.go
pkg/resource/deploy/source_query.go
sdk/go/common/resource/plugin/host.go
sdk/go/common/resource/plugin/langruntime.go
sdk/go/common/resource/plugin/langruntime_plugin.go
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_install_test.go
sdk/go/common/workspace/plugins_test.go

Retry of https://github.com/pulumi/pulumi/pull/10492.
This time with a fixed and improved testDeletePlugin function.
This reverts commit 603d8591267ce81d57a336563411faac90981bfd.

Split PluginInfo in Info and Spec

---

sdk/python/requirements.txt

pinned pylint==2.14.5

---

README.md

I added the link to the LICENSE File in the readme for easy access.

Added link to the LICENSE file in the README

---

pkg/backend/httpstate/token_source_test.go

Disable token_source_test on windows

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/state.go

Don't panic when snap is nil

---

sdk/go/pulumi/run.go

Suggestion to reorg code to keep RunErr as-before

---

sdk/nodejs/tests/automation/cmd.spec.ts

Relax assert about num of onOutput calls

---

developer-docs/providers/implementers-guide.md

Correct type grammar in dev docs

---

pkg/codegen/schema/docs_test.go

The loops in this file create millions of subtests, the majority of which do very little work. This reduces the time to execute these tests to a couple seconds.

ci: Reduce test duration by avoiding costly subtests in loop

---

.github/PULL_REQUEST_TEMPLATE.md

Update PULL_REQUEST_TEMPLATE.md referencing the new changelog tool

---

.github/workflows/ci-run-test.yml

Do not fail on test summary steps

---

CONTRIBUTING.md

This PR updates the contributor guide to describe the new changelog process.

Update contributor.md to describe new changelog process.

---

changelog/pending/20220916--programgen-go--codegen-apply-fn-fix.yaml
pkg/codegen/dotnet/gen_program_expressions.go
pkg/codegen/go/gen_program.go
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/nodejs/gen_program_expressions.go
pkg/codegen/pcl/functions.go
pkg/codegen/python/gen_program_expressions.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/aws-s3-folder-pp/go/aws-s3-folder.go
pkg/codegen/testing/test/testdata/functions-pp/dotnet/functions.cs
pkg/codegen/testing/test/testdata/functions-pp/functions.pp
pkg/codegen/testing/test/testdata/functions-pp/go/functions.go
pkg/codegen/testing/test/testdata/functions-pp/nodejs/functions.ts
pkg/codegen/testing/test/testdata/functions-pp/python/functions.py

Fixes `pulumi/yaml` [337](https://github.com/pulumi/pulumi-yaml/issues/337)
minor: Fixes https://github.com/pulumi/pulumi/issues/8077

Fix codegen for `__apply` functions

---

changelog/pending/20221003--sdk-python--python-update-summary-fix.yaml
sdk/python/lib/pulumi/automation/_stack.py

Fixes https://github.com/pulumi/pulumi/issues/10905

Handle end_time missing from UpdateSummary

---

.github/workflows/ci-lint.yml

We run make tidy as part of release so we really want to make sure it's correct before anything hits master.

Run make tidy as part of linting

---

changelog/pending/20220916--programgen-go--codegen-apply-fn-fix.yaml
changelog/pending/20220927--sdk-go--install-deps-1-18.yaml
changelog/pending/20220927--sdkgen-nodejs--fix-null-node-lazy-loading-issue.yaml
changelog/pending/20220928--sdk-go--unsafe-await.yaml
changelog/pending/20220929--sdk-go--fix-sdk-bug-in-mergedependencies.yaml
changelog/pending/20220930--cli--eject-dont-panic.yaml
changelog/pending/20221001--cli-about-plugin--rm-github-experimental.yaml
changelog/pending/20221003--backend--issue-7251.yaml
changelog/pending/20221003--sdk-python--python-invoke.yaml
changelog/pending/20221003--sdk-python--python-update-summary-fix.yaml
changelog/pending/20221004--sdk-python--python-format.yaml

Revert "Clear out changelog for next release"

---

changelog/pending/20221009--programgen-go--fix-go-range-constant-int-10853.yaml
pkg/codegen/go/gen_program.go
pkg/codegen/nodejs/gen_program.go
pkg/codegen/pcl/binder_test.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/aws-eks-pp/nodejs/aws-eks.ts
pkg/codegen/testing/test/testdata/aws-s3-folder-pp/nodejs/aws-s3-folder.ts
pkg/codegen/testing/test/testdata/simple-range-pp/dotnet/simple-range.cs
pkg/codegen/testing/test/testdata/simple-range-pp/go/simple-range.go
pkg/codegen/testing/test/testdata/simple-range-pp/nodejs/simple-range.ts
pkg/codegen/testing/test/testdata/simple-range-pp/python/simple-range.py
pkg/codegen/testing/test/testdata/simple-range-pp/simple-range.pp

[go/program-gen] Fixes int constant range expressions for go

---

changelog/config.yaml
changelog/pending/20221013--yaml--bump-yaml.yaml
pkg/go.mod
pkg/go.sum
tests/go.mod

Upgrade yaml to v0.5.10

---

pkg/cmd/pulumi/convert.go

Every time I need to debug `pulumi convert` I have to hack YAML program-gen and make it output the intermediate PCL program text to stdout and work from there. Here, I've added PCL as a proper target language for `pulumi convert` (without needing to parse the program text and generate `pcl.Program` from it) 
I tried a simpler approach:
```go
projectGenerator = func(directory string, project workspace.Project, p *pcl.Program) error {
programText := fmt.Sprintf("%v", p)
outputFile := path.Join(directory, "main.pp")
err := ioutil.WriteFile(outputFile, []byte(programText), 0600)
return fmt.Errorf("could not write output program: %w", err)
}
return nil
}
```
but the default formatter for `pcl.Program` writes out invalid PCL (including non-formatted type metadata) so I went with …

Add PCL as a target language for pulumi convert

---

CONTRIBUTING.md

Added links to go, node, and python downloads in the contributing document.

added links to contributing.md for go, node, and python downloads

---

.github/scripts/get-changelog
Makefile
changelog/pending/20221018--ci--fix-pull-request-urls-in-pulumi-changelogs.yaml

Updates the changelog generator with fixes:
- https://github.com/AaronFriel/go-change/pull/13
- https://github.com/AaronFriel/go-change/pull/17

fix(ci): Fix pull request URLs in changelogs

---

.github/workflows/rebase.yml

Add `/rebase` command

---

pkg/backend/updates.go
pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/refresh.go
pkg/cmd/pulumi/up.go
pkg/cmd/pulumi/util.go
pkg/cmd/pulumi/watch.go
sdk/go/common/constant/exec_kind.go

Send update metadata to the service about if we're using update plans.

Send update metadata about update plans

---

pkg/backend/httpstate/backend.go

Retrieving engine events programmatically through automation api would result in the operation seemingly hanging for remote operations. This was particularly noticeable during remote previews, because preview in automation API programmatically inspects engine events to look for the summary event (which it doesn't do for up/refresh/destroy).
The problem is due to the lack of a terminating `CancelEvent`. Normally, for local operations, the event stream is always terminated by a `CancelEvent` which is the sentinel value used to indicate the operation is complete. However, when sending events to the service, the `CancelEvent` is not sent. So when we're retrieving events from the service for a remote operation, we weren't getting back a `CancelEvent`.
The fix is to send a synthesized …

[auto] Fix hangs for remote previews

---

.github/workflows/download-pulumi-cron.yml

Attempt to fix this failing build https://github.com/pulumi/pulumi/actions/runs/3350653319/jobs/5551595514

[download-cron] Fix powershell script to install winget 

---

pkg/codegen/dotnet/gen_program_test/batchyaml/gen_program_test.go
pkg/codegen/go/gen_program_test/batchyaml/gen_program_test.go
pkg/codegen/nodejs/gen_program_test/batchyaml/gen_program_test.go
pkg/codegen/python/gen_program_test/batchyaml/gen_program_test.go
pkg/codegen/testing/test/testdata/transpiled_examples/cue-random-pp/dotnet/dotnet.csproj
pkg/codegen/testing/test/testdata/transpiled_examples/cue-static-web-app-pp/dotnet/dotnet.csproj
pkg/codegen/testing/test/testdata/transpiled_examples/getting-started-pp/dotnet/dotnet.csproj
pkg/codegen/testing/test/testdata/transpiled_examples/random-pp/dotnet/dotnet.csproj

Cover all languages for examples synced from pulumi/yaml

Test transpiled examples for all languages

---

sdk/go/common/resource/asset.go
sdk/go/common/resource/asset_test.go
sdk/go/common/resource/config/crypt.go
sdk/go/common/resource/config/key.go
sdk/go/common/resource/properties_path.go
sdk/go/common/resource/resource_id.go

Not all of them, but replacing a batch of pkg/errors with just errors or fmt.

Cleaning up a few pkg/errors uses

---

pkg/codegen/docs/templates/function.tmpl
pkg/codegen/testing/test/testdata/external-resource-schema/docs/argfunction/_index.md
pkg/codegen/testing/test/testdata/functions-secrets/docs/funcwithsecrets/_index.md
pkg/codegen/testing/test/testdata/other-owned/docs/argfunction/_index.md
pkg/codegen/testing/test/testdata/other-owned/docs/overlayfunction/_index.md
pkg/codegen/testing/test/testdata/output-funcs-edgeorder/docs/listconfigurations/_index.md
pkg/codegen/testing/test/testdata/output-funcs-edgeorder/docs/listproductfamilies/_index.md
pkg/codegen/testing/test/testdata/output-funcs-tfbridge20/docs/getamiids/_index.md
pkg/codegen/testing/test/testdata/output-funcs-tfbridge20/docs/liststorageaccountkeys/_index.md
pkg/codegen/testing/test/testdata/output-funcs/docs/funcwithalloptionalinputs/_index.md
pkg/codegen/testing/test/testdata/output-funcs/docs/funcwithconstinput/_index.md
pkg/codegen/testing/test/testdata/output-funcs/docs/funcwithdefaultvalue/_index.md
pkg/codegen/testing/test/testdata/output-funcs/docs/funcwithdictparam/_index.md
pkg/codegen/testing/test/testdata/output-funcs/docs/funcwithemptyoutputs/_index.md
pkg/codegen/testing/test/testdata/output-funcs/docs/funcwithlistparam/_index.md
pkg/codegen/testing/test/testdata/output-funcs/docs/getbastionshareablelink/_index.md
pkg/codegen/testing/test/testdata/output-funcs/docs/getclientconfig/_index.md
pkg/codegen/testing/test/testdata/output-funcs/docs/getintegrationruntimeobjectmetadatum/_index.md
pkg/codegen/testing/test/testdata/output-funcs/docs/liststorageaccountkeys/_index.md
pkg/codegen/testing/test/testdata/plain-object-defaults/docs/funcwithalloptionalinputs/_index.md
pkg/codegen/testing/test/testdata/plain-object-disable-defaults/docs/funcwithalloptionalinputs/_index.md
pkg/codegen/testing/test/testdata/provider-config-schema/docs/funcwithalloptionalinputs/_index.md
pkg/codegen/testing/test/testdata/regress-8403/docs/getcustomdbroles/_index.md
pkg/codegen/testing/test/testdata/regress-node-8110/docs/examplefunc/_index.md
pkg/codegen/testing/test/testdata/simple-plain-schema/docs/dofoo/_index.md
pkg/codegen/testing/test/testdata/simple-resource-schema-custom-pypackage-name/docs/argfunction/_index.md
pkg/codegen/testing/test/testdata/simple-resource-schema/docs/argfunction/_index.md
pkg/codegen/testing/test/testdata/simple-resource-schema/docs/overlayfunction/_index.md
pkg/codegen/testing/test/testdata/simple-yaml-schema/docs/argfunction/_index.md

Fixes pulumi-yaml https://github.com/pulumi/pulumi-yaml/issues/399

Update YAML invoke syntax for docs

---

pkg/cmd/pulumi/util_remote.go
tests/remote_test.go
tests/stack_test.go

Also some changes to validate flags earlier (before getting the backend).
Related:
- https://github.com/pulumi/pulumi/pull/11291
- https://github.com/pulumi/pulumi/pull/11292
- https://github.com/pulumi/pulumi/pull/11293
- https://github.com/pulumi/pulumi/pull/11294

[cli] Test remote operations

---

sdk/python/lib/pulumi/automation/_remote_workspace.py
sdk/python/lib/pulumi/automation/_stack.py
sdk/python/lib/test/automation/test_local_workspace.py
sdk/python/lib/test/automation/test_remote_workspace.py
sdk/python/lib/test/automation/test_utils.py

Also cleans up some error messages to be consistent with the CLI and other languages.
Related:
- https://github.com/pulumi/pulumi/pull/11290
- https://github.com/pulumi/pulumi/pull/11291
- https://github.com/pulumi/pulumi/pull/11292
- https://github.com/pulumi/pulumi/pull/11294

[auto/python] Test remote operations

---

pkg/codegen/dotnet/gen.go
pkg/codegen/testing/test/testdata/azure-native-nested-types/dotnet/Pulumi.AzureNative.csproj
pkg/codegen/testing/test/testdata/cyclic-types/dotnet/Pulumi.Example.csproj
pkg/codegen/testing/test/testdata/dash-named-schema/dotnet/Pulumi.FooBar.csproj
pkg/codegen/testing/test/testdata/dashed-import-schema/dotnet/Pulumi.Plant.csproj
pkg/codegen/testing/test/testdata/functions-secrets/dotnet/Pulumi.Mypkg.csproj
pkg/codegen/testing/test/testdata/hyphen-url/dotnet/Pulumi.Registrygeoreplication.csproj
pkg/codegen/testing/test/testdata/naming-collisions/dotnet/Pulumi.Example.csproj
pkg/codegen/testing/test/testdata/nested-module-thirdparty/dotnet/Pulumi.FooBar.csproj
pkg/codegen/testing/test/testdata/output-funcs-edgeorder/dotnet/Pulumi.Myedgeorder.csproj
pkg/codegen/testing/test/testdata/output-funcs-tfbridge20/dotnet/Pulumi.Mypkg.csproj
pkg/codegen/testing/test/testdata/output-funcs/dotnet/Pulumi.Mypkg.csproj
pkg/codegen/testing/test/testdata/plain-and-default/dotnet/Pulumi.FooBar.csproj
pkg/codegen/testing/test/testdata/plain-object-defaults/dotnet/Pulumi.Example.csproj
pkg/codegen/testing/test/testdata/plain-object-disable-defaults/dotnet/Pulumi.Example.csproj
pkg/codegen/testing/test/testdata/plain-schema-gh6957/dotnet/Pulumi.Xyz.csproj
pkg/codegen/testing/test/testdata/regress-8403/dotnet/Pulumi.Mongodbatlas.csproj
pkg/codegen/testing/test/testdata/regress-node-8110/dotnet/Pulumi.My8110.csproj
pkg/codegen/testing/test/testdata/replace-on-change/dotnet/Pulumi.Example.csproj
pkg/codegen/testing/test/testdata/resource-args-python-case-insensitive/dotnet/Pulumi.Example.csproj
pkg/codegen/testing/test/testdata/resource-args-python/dotnet/Pulumi.Example.csproj
pkg/codegen/testing/test/testdata/resource-property-overlap/dotnet/Pulumi.Example.csproj
pkg/codegen/testing/test/testdata/secrets/dotnet/Pulumi.Mypkg.csproj
pkg/codegen/testing/test/testdata/simple-enum-schema/dotnet/Pulumi.Plant.csproj
pkg/codegen/testing/test/testdata/simple-methods-schema-single-value-returns/dotnet/Pulumi.Example.csproj
pkg/codegen/testing/test/testdata/simple-methods-schema/dotnet/Pulumi.Example.csproj
pkg/codegen/testing/test/testdata/simple-plain-schema-with-root-package/dotnet/Pulumi.Example.csproj
pkg/codegen/testing/test/testdata/simple-plain-schema/dotnet/Pulumi.Example.csproj
pkg/codegen/testing/test/testdata/simple-resource-schema/dotnet/Pulumi.Example.csproj

Followup on https://github.com/pulumi/pulumi/pull/11315#discussion_r1018893409.

Set minimum .NET build version to 3.23.0

---

changelog/pending/20221110--sdk-python--copy-resourceoptions-correctly-during-a-merge.yaml
sdk/python/lib/pulumi/resource.py
sdk/python/lib/test/test_resource.py

Correctly copy ResourceOptions during a merge

---

pkg/codegen/nodejs/gen.go
pkg/codegen/testing/test/testdata/external-resource-schema/nodejs/argFunction.ts
pkg/codegen/testing/test/testdata/functions-secrets/nodejs/funcWithSecrets.ts
pkg/codegen/testing/test/testdata/output-funcs-edgeorder/nodejs/listConfigurations.ts
pkg/codegen/testing/test/testdata/output-funcs-edgeorder/nodejs/listProductFamilies.ts
pkg/codegen/testing/test/testdata/output-funcs-tfbridge20/nodejs/getAmiIds.ts
pkg/codegen/testing/test/testdata/output-funcs-tfbridge20/nodejs/listStorageAccountKeys.ts
pkg/codegen/testing/test/testdata/output-funcs/nodejs/funcWithAllOptionalInputs.ts
pkg/codegen/testing/test/testdata/output-funcs/nodejs/funcWithConstInput.ts
pkg/codegen/testing/test/testdata/output-funcs/nodejs/funcWithDefaultValue.ts
pkg/codegen/testing/test/testdata/output-funcs/nodejs/funcWithDictParam.ts
pkg/codegen/testing/test/testdata/output-funcs/nodejs/funcWithEmptyOutputs.ts
pkg/codegen/testing/test/testdata/output-funcs/nodejs/funcWithListParam.ts
pkg/codegen/testing/test/testdata/output-funcs/nodejs/getBastionShareableLink.ts
pkg/codegen/testing/test/testdata/output-funcs/nodejs/getClientConfig.ts
pkg/codegen/testing/test/testdata/output-funcs/nodejs/getIntegrationRuntimeObjectMetadatum.ts
pkg/codegen/testing/test/testdata/output-funcs/nodejs/listStorageAccountKeys.ts
pkg/codegen/testing/test/testdata/plain-object-defaults/nodejs/funcWithAllOptionalInputs.ts
pkg/codegen/testing/test/testdata/plain-object-disable-defaults/nodejs/funcWithAllOptionalInputs.ts
pkg/codegen/testing/test/testdata/provider-config-schema/nodejs/funcWithAllOptionalInputs.ts
pkg/codegen/testing/test/testdata/regress-8403/nodejs/getCustomDbRoles.ts
pkg/codegen/testing/test/testdata/regress-node-8110/nodejs/exampleFunc.ts
pkg/codegen/testing/test/testdata/simple-plain-schema/nodejs/doFoo.ts
pkg/codegen/testing/test/testdata/simple-resource-schema-custom-pypackage-name/nodejs/argFunction.ts
pkg/codegen/testing/test/testdata/simple-resource-schema/nodejs/argFunction.ts
pkg/codegen/testing/test/testdata/simple-yaml-schema/nodejs/argFunction.ts

This came up as part of the my work on simplified functions (multi args / single output) so here is a PR for this specific change

[nodejs/sdk-gen] Simplify default options for function invokes

---

pkg/codegen/schema/loader.go
sdk/go/common/workspace/plugins.go

This is necessary to unblock https://github.com/pulumi/docs/pull/8230

Account for version when caching schemas

---

tests/integration/nodejs/esm-ts-compiled/package.json

Bump nodejs integration test version

---

scripts/get-job-matrix.py

Workaround for https://github.com/pulumi/pulumi/issues/11488

Limit NodeJS to 19.1

---

pkg/go.mod
pkg/go.sum
pkg/secrets/cloud/manager_test.go
tests/go.mod
tests/go.sum

Start of tests as part of looking into https://github.com/pulumi/pulumi/issues/11482.
I need to add another test to check that assumed roles work, but I haven't yet worked out how to get aws to let me do an assume role from the sdk. But these are a start and worth adding in while still looking into adding more.

Add tests for awskms secret manager

---

sdk/python/lib/pulumi/runtime/rpc.py

Fix python lint errors

---

pkg/cmd/pulumi/convert.go
pkg/go.mod
pkg/go.sum
tests/go.mod

Last part of the new convert mapper work, update terraform-bridge to bring in the new code with support for convert mappers and use it in convert.

Convert mapper phase 5

---

pkg/codegen/hcl2/model/expression.go
pkg/codegen/hcl2/model/print_test.go
pkg/codegen/importer/hcl2_test.go
pkg/codegen/importer/language.go
pkg/codegen/importer/testdata/cases.json

Escape `${` in string literals

---

developer-docs/providers/metaschema.md

Add `willReplaceOnChanges` to metaschema

---

pkg/codegen/schema/pulumi.json

Add `willReplaceOnChanges` to schema

---

sdk/python/README.md

Added README.md file for python sdk which was missing earlier . I reffered documentation given in pulumi website to create this file.
Fixes #10080

Added README.md file in pulumi/sdk/python

---

pkg/codegen/python/gen_program_expressions.go
pkg/codegen/testing/test/testdata/aws-secret-pp/python/aws-secret.py
pkg/codegen/testing/test/testdata/transpiled_examples/azure-app-service-pp/python/azure-app-service.py

Fix Python codegen for secret() intrinsic

---

pkg/codegen/go/gen.go

Minor cleanup in go codegen

---

pkg/codegen/go/gen_program.go
pkg/codegen/testing/test/testdata/functions-pp/dotnet/functions.cs
pkg/codegen/testing/test/testdata/functions-pp/functions.pp
pkg/codegen/testing/test/testdata/functions-pp/go/functions.go
pkg/codegen/testing/test/testdata/functions-pp/nodejs/functions.ts
pkg/codegen/testing/test/testdata/functions-pp/python/functions.py

Adds test for https://github.com/pulumi/pulumi/pull/11643

Add test for codegen error initialization 

---

sdk/python/cmd/pulumi-language-python/main.go
sdk/python/python.go

What it says on the tin. We want to replace all usages of "github.com/pkg/errors" with just "errors", this handles everything in sdk/python.

Clean up use of pkg/errors in sdk/python

---

sdk/README.md

Cleanup sdk/README.md

---

changelog/pending/20230105--auto-python--fix-issue-specifying-log_verbosity.yaml
sdk/python/lib/pulumi/automation/_stack.py

[auto/python] Fix issue specifying log_verbosity

---

sdk/go/pulumi/types.go

Moves accessing all of the fields to be guarded by the lock.

sdk/go: Simplify await(), prevent data races

---

pkg/engine/lifecycletest/pulumi_test.go

Also tweaked the error from delete to make it a bit more clear if we hit something here again.
Fixes https://github.com/pulumi/pulumi/issues/11792

Add missing dependency set to TestPendingDeleteOrder

---

sdk/go/auto/git.go
sdk/go/auto/local_workspace.go
sdk/go/auto/remote_workspace.go
sdk/go/auto/stack.go

Next little bit of removing pkg/errors, remove the few uses in sdk/go/auto.

Clean up use of pkg/errors in sdk/go/auto

---

sdk/go/common/resource/plugin/host.go

Just adding context to an error message.

Improve err message on an invalid plugin override

---

sdk/go/common/workspace/creds.go
sdk/go/common/workspace/paths.go
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/project.go
sdk/go/common/workspace/templates.go
sdk/go/common/workspace/workspace.go

The continued sage of killing pkg/errors, small bites at a time.

Replace pkg/errors in sdk/go/common/workspace

---

pkg/cmd/pulumi/stack_output.go

Pull core logic of `pulumi stack output`
into a separate `stackOutputCmd` struct
rather than having it all inside an anonymous function.
That also turns state captured in the closure
into normal fields on the struct.
This contains no logic changes.
This is a step towards making this logic more testable
in service to #2632.

cmd/stack output: Pull out core logic

---

pkg/secrets/cloud/manager_test.go

Tidy up prompted by https://github.com/pulumi/pulumi/pull/11880

Replace assertNoError with require.NoError in aws kms tests

---

pkg/cmd/pulumi/stack_output.go

There's a bit of branching and duplication
between the JSON and the default case.
(with --json + without) x (with an argument + without)
That branching will only get worse with the upcoming `--shell` flag
(#2632).
This change defines an stackOutputWriter interface
that handles the actual printing,
with two implementations: one for JSON, one for user-readable output.
Note that all writers currently write directly to stdout.
In a future change, these may begin using `io.Writer`s.
In service to #2632

cmd/stack output: Introduce a Writer abstraction

---

sdk/go/common/resource/plugin/provider_plugin.go
sdk/go/common/resource/plugin/provider_plugin_test.go

This is a follow-up to #11975 with a more permanent fix.
The cause of the original data race was that
some of the invocations accessed the configuration
before the Configure RPC succeeded.
Notably, there was a case where we had:
doStuff(cfg)
waitForConfiguration()
doMoreStuff(cfg)
The issue was fixed by simple re-ordering.
waitForConfiguration()
doStuff(cfg)
doMoreStuff(cfg)
However, it remains very easy to read the configuration
before it's actually configured.
It's only a matter of time before the same bug arises again.
To fix this, we pull out the configuration into its own struct,
and make it accessible only by calling a specific function.
This separation is enforced by a promise-like object
with a consumer (Await) and a producer (Fulfill) end.
Any method that needs the configuration …

sdk/plugin/provider: Prevent use-before-configure races

---

sdk/go/common/tokens/tokens.go

Continuing tiny pkg/errors clean ups

Clean up pkg/errors in go/common/tokens

---

sdk/python/lib/pulumi/asset.py
sdk/python/lib/pulumi/automation/_remote_workspace.py
sdk/python/lib/pulumi/resource.py
sdk/python/lib/pulumi/runtime/resource.py
sdk/python/lib/pulumi/runtime/rpc.py
sdk/python/lib/pulumi/runtime/stack.py
sdk/python/lib/pulumi/stack_reference.py

It would appear the formatting rules have changed.

Reformat python

---

sdk/go/common/resource/config/map.go
sdk/go/common/resource/config/value.go

Continuing pkg/errors cleanup.

pkg/errors cleanup for sdk/go/common/resource/config

---

sdk/python/requirements.txt

Pin mypy to 0.991 to make lints pass for release 3.54.0

---

pkg/go.mod
pkg/go.sum

Upgrades to latest moby release.
Resolves GHSA-vp35-85q5-9f25

pkg: Upgrade moby

---

sdk/python/lib/pulumi/runtime/sync_await.py

Tiny little tidy up to _sync_awaits type annotation.

Make the _sync_await type more precise

---

sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_test.go

Just a little tidy up some things I noticed while working on the gitlab source.
1. Rename pluginURLSource to httpSource. A plugin URL is _anything_ that is given as a pluginDownloadURL. This type only handles the downloads from http/https locations.
2. Make GetSource error for unrecognized source schemes. If we add new schemes in the future (fairly likely) if someone tries to use one of the new schemes on an old CLI they'll get a fairly comprehensible error that the scheme wasn't recognized rather than some cryptic error from however the http library fails trying to parse the strange (to it) url.

Rename http source

---

pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/import_test.go

Follow up to #12182
If an input file has several issues,
rather than stopping after the first,
list them all.
Example:
```
% pulumi import -f tmp.json
error: 2 errors occurred:
1) resource 'foo' has no type
2) resource 'foo' has no ID
```
This currently uses hashicorp/go-multierror for this.
Once Go 1.20 is the minimum supported version,
we can change this to the standard library's `errors.Join` function.
Refs #12103

pulumi import: Print all errors in the file

---

pkg/backend/httpstate/backend.go
pkg/backend/httpstate/stack.go
pkg/cmd/pulumi/console.go
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/new_acceptance_test.go
pkg/cmd/pulumi/org.go
pkg/cmd/pulumi/policy_group_ls.go
pkg/cmd/pulumi/policy_ls.go
pkg/cmd/pulumi/query.go
pkg/cmd/pulumi/stack_init.go
pkg/cmd/pulumi/stack_ls.go
pkg/cmd/pulumi/stack_select.go
pkg/cmd/pulumi/up.go
pkg/cmd/pulumi/util.go
pkg/cmd/pulumi/util_remote.go
pkg/cmd/pulumi/whoami.go

More little steps for https://github.com/pulumi/pulumi/issues/12152. Pass the `*Project` to `currentBackground` so it doesn't have to load the project anymore.

Pass *Project to currentBackend

---

sdk/go/common/resource/properties_diff.go

I was digging into something else, and got confused by a misleading comment, so I figured I'd update it :+1:
^ The change does not affect the executable program.
^ I don't think this warrants a changelog entry – let me know if I should add one!
^ The change does not affect the executable program.

chore(sdk/go): fix a somewhat misleading comment

---

pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/stack_init.go
pkg/cmd/pulumi/stack_select.go
pkg/cmd/pulumi/up.go
pkg/cmd/pulumi/util.go

Yup another small change for https://github.com/pulumi/pulumi/issues/12152.
This just moves the project loading up from createStack to the root cmd level.

Pass root and project to createStack

---

sdk/go/pulumi/resource_test.go

Adds a test case to verify that a ComponentResource
propagates its Provider and Providers values
to children constructed with that type.
Refs #12161

sdk/go: Test case for Provider propagation

---

pkg/cmd/pulumi/gen_markdown.go
pkg/cmd/pulumi/import.go
pkg/codegen/dotnet/gen_program.go
pkg/codegen/go/gen_program.go
pkg/codegen/nodejs/gen_program.go
pkg/codegen/python/gen_program.go
pkg/engine/eventsink.go
pkg/graph/dotconv/print.go
sdk/go/common/diag/sink.go

Replace `buffer.WriteString(fmt.Sprintf(..))` calls,
where buffer is one of `bytes.Buffer`, `strings.Builder`, or `bufio.Writer`,
with equivalent `fmt.Fprintf` calls -- all those types are io.Writers.

chore: WriteString(Sprintf(..)) => Fprintf(..)

---

sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_test.go

As a quick alternative to https://github.com/pulumi/pulumi/pull/12307, make the rate limit error more explicit that it's because of rate limits.

Nicer github rate limit error

---

pkg/codegen/testing/test/testdata/docker-4.0.0-alpha.0.json

Our Makefile defines this schema as one of the ones downloaded.
The schema was added in #11570 but not checked into the repository.

testdata: add missing docker-4.0.0-alpha.0 schema

---

pkg/cmd/pulumi/package_gen_sdk.go

This is hidden because we don't really want people using overlays, the current plan is try and remove them all. But we currently have some in use in existing providers and we need to support that to migrate those providers over to using gen-sdk rather than calling into the codegen libraries themselves.

Add hidden --overlays option to gen-sdk

---

pkg/cmd/pulumi/package_gen_sdk.go

I don't like this behaviour but looks like command and boilerplate is already using this.
Bit grim because it means the --overlay paths behave slightly different to the --out paths.

Revert gen-sdk --out behaviour change

---

sdk/go/common/workspace/project_test.go

Add some tests for roundtripping Pulumi.yaml files.
One checks that if we create, save and load a file we both get back the same value we saved.
The other checks that if we load a file then edit it and save it we get the expected YAML result.

Test project roundtrips

---

changelog/pending/20230310--programgen-dotnet-go-nodejs-python--implement-not-implement-function-intrinsic-in-pcl.yaml
pkg/codegen/dotnet/gen_program.go
pkg/codegen/dotnet/gen_program_expressions.go
pkg/codegen/dotnet/utilities.go
pkg/codegen/go/gen_program.go
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/go/gen_program_utils.go
pkg/codegen/nodejs/gen_program.go
pkg/codegen/nodejs/gen_program_expressions.go
pkg/codegen/nodejs/gen_program_utils.go
pkg/codegen/pcl/functions.go
pkg/codegen/python/gen_program.go
pkg/codegen/python/gen_program_expressions.go
pkg/codegen/python/gen_program_utils.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/throw-not-implemented-pp/dotnet/throw-not-implemented.cs
pkg/codegen/testing/test/testdata/throw-not-implemented-pp/go/throw-not-implemented.go
pkg/codegen/testing/test/testdata/throw-not-implemented-pp/nodejs/throw-not-implemented.ts
pkg/codegen/testing/test/testdata/throw-not-implemented-pp/python/throw-not-implemented.py
pkg/codegen/testing/test/testdata/throw-not-implemented-pp/throw-not-implemented.pp

[pcl/program-gen] Add "Not Implemented" PCL function intrinsic

---

pkg/cmd/pulumi/convert.go
pkg/cmd/pulumi/import.go

Also print the warning to the Diag stream so it _always_ shows in the terminal.

Close converter plugins after use

---

sdk/go/auto/remote_workspace_test.go

Previously, we were only testing setting the branch of the remote repo. Now we have a test that specifies a commitHash instead.
Follow-up from #11716

[auto/go] Add test for remote commitHash

---

pkg/backend/filestate/backend.go

The currentProject is stored as a plain field on the local backend.
This is fine right now because SetCurrentProject
is not expected to be called concurrently with anything else.
However, in #12437 (project-scoped stacks),
we need to be able to access the current project in a context
where there are no guarantees about SetCurrentProject being called
concurrently with other operations.
This switches the currentProject into an atomic.Pointer
that we can Load and Swap in a thread-safe manner.
Note that this does not protect us from data races caused by
concurrent mutations to the workspace.Project struct's fields,
but that doesn't appear to be a concern;
the code treats that object as a blob of constant values.
Extracted from #12437

filestate: Make currentProject an atomic.Pointer

---

pkg/codegen/convert/mapper.go

Currently bridge provider plugins return a mapping for "tf" but not "terraform", the bridge has been updated to reply for both but given it takes time for providers to be updated and published we're adding this compat shim to just try both names.
Also closes off the provider plugins after calling GetMapping to stop a resource leak.

Temporary compatability shim for tf mappings

---

pkg/backend/filestate/store.go

ListReferences for project layout is currently inefficient.
It roughly does the equivalent of:
for proj in bucket.List(stacksDir)
for ref in bucket.List(stacksDir + "/" + proj):
This is fine for local, file-based storage,
but super inefficient for S3 or Azure.
The reason this was written as above is because we treat the bucket
as a directory tree in listBucket.
This changes projectStore.ListReferences to use the underlying
bucket.List method directly--without setting the Delimiter.
This treats the bucket as a flat file list instead of a hierarchy,
and we can extract project and stack names from it in one go.

filestate/projectStore: Optimize ListReferences

---

pkg/go.mod
pkg/go.sum
tests/go.mod
tests/go.sum

Upgrade to the latest release of pulumi-java.
Refs pulumi/pulumi-java#1042

pulumi-java: Upgrade to v0.9.0

---

developer-docs/README.md

Add README.md for the developer documentation site for more visibility as it's super helpful.

Create README.md for developer docs

---

README.md

Proposed edits to update for new messaging and refreshing some of the content.
Also propose updating the text in the **About** section to: 
> Pulumi - Infrastructure as Code in any programming language. Build infrastructure intuitively on any cloud using familiar languages 🚀

Update Pulumi readme

---

pkg/testing/integration/program.go

RelativeWorkDir is a `ProgramTestOption` that defines where the `pulumi` command should be executed relative
to the test directory. This PR repairs a bug in the application of `ProgramTestOptions` that prevents `Pulumi.yaml`
from loading when RelativeWorkDir is provided.
This change repairs a bug in the integration testing suite. Currently, RelativeWorkDir
is not used (nor is it usable). With this fix, RelativeWorkDir can now be used in integration tests.
If this PR passes tests, then the change to the test harness is safe, and thus we don't need to add
another test to prove the correctness of the test harness itself.
N/A. See above for explanation.

Fix failure to load Pulumi.yaml when RelativeWorkDir provided.

---

pkg/cmd/pulumi/convert.go

Missing newline in printed message.

Fix missing \n in message

---

pkg/cmd/pulumi/convert.go

Fix up https://github.com/pulumi/pulumi/pull/12808 to cover parse errors

Fix parse diagnostics returning as diagnostics not error

---

sdk/go/common/resource/plugin/langruntime_plugin.go

Remove unsed Runtime method from langhost

---

pkg/cmd/pulumi/convert.go
pkg/resource/deploy/providers/registry.go
pkg/resource/deploy/providers/registry_test.go
pkg/workspace/plugin.go
pkg/workspace/plugin_test.go

Shares much of the same logic as auto-install of provider plugins during updates.

Auto download converter plugins

---

.github/PULL_REQUEST_TEMPLATE.md

This is a followup to #12860. Adds routine pre-commit tasks to the pull request checklist.
n/a

Add routine checks to pull request template

---

pkg/backend/filestate/backend.go
pkg/backend/filestate/stack.go
pkg/backend/filestate/state.go
pkg/backend/httpstate/stack.go

Fixes a TODO in pkg/backend/filestate/stack.go, adds a new one in pkg/backend/filestate/backend.go. That TODO could be fixed but means rewriting all the RenameStack tests to work in terms of checkpoints not snapshots so figured better to split out to a separate PR later.

Make filestate.Snapshot lazy like httpstate

---

pkg/engine/lifecycletest/pulumi_test.go

These tests didn't have any checks for how arrays behave, this adds some coverage for that.

Add a few more tests for IgnoreChanges with arrays

---

Makefile
build/common.mk
sdk/go/Makefile
sdk/nodejs/Makefile
sdk/python/Makefile

Fix the makefiles to run build/test/brew on the Go and NodeJS language plugins correctly.

Fix makefiles

---

pkg/cmd/pulumi/convert.go

Add a couple of messages to convert to see the stages of converting "from" and converting "to".
Part of https://github.com/pulumi/pulumi/issues/13096

Add stage messages to convert

---

changelog/pending/20230523--engine--fix-wildcards-in-ignorechanges.yaml
changelog/pending/20230526--engine--fix-ignorechanges-setting-ignore-array-indexs-to-zero.yaml
pkg/engine/lifecycletest/pulumi_test.go
pkg/resource/deploy/step_generator.go
sdk/go/common/resource/properties_path.go
sdk/go/common/resource/properties_path_test.go

Fixes https://github.com/pulumi/pulumi/issues/12581

Fix wildcards in IgnoreChanges

---

sdk/go/auto/test/errors/compilation_error/typescript/package-lock.json
sdk/go/auto/test/errors/compilation_error/typescript/package.json
sdk/go/auto/test/errors/runtime_error/javascript/package-lock.json
sdk/go/auto/test/errors/runtime_error/javascript/package.json
sdk/go/auto/test/errors/runtime_error/typescript/package-lock.json
sdk/go/auto/test/errors/runtime_error/typescript/package.json
sdk/nodejs/tests/automation/data/tcfg/package-lock.json
sdk/nodejs/tests/automation/data/tcfg/package.json
sdk/python/lib/test/automation/errors/compilation_error/typescript/package-lock.json
sdk/python/lib/test/automation/errors/compilation_error/typescript/package.json
sdk/python/lib/test/automation/errors/runtime_error/javascript/package-lock.json
sdk/python/lib/test/automation/errors/runtime_error/javascript/package.json
sdk/python/lib/test/automation/errors/runtime_error/typescript/package-lock.json
sdk/python/lib/test/automation/errors/runtime_error/typescript/package.json

Combines the following dependabot changes into a single PR:
- #13266
- #13267
- #13268
- #13269
- #13270
- #13271
- #13272

Bump semver and @pulumi/pulumi

---

CHANGELOG.md
changelog/pending/20230601--cli-state--the-upgrade-command-now-prompts-the-user.yaml
changelog/pending/20230609--engine--old-inputs-are-sent-to-provider-diff-functions-as-well-as-the-old-outputs.yaml
changelog/pending/20230620--programgen-go--fix-aliasing-package-names-using-dashes-when-schema-doesnt-include-go-package-info-override.yaml
changelog/pending/20230622--cli--stack-output-on-the-console-no-longer-escapes-html-characters-inside-json-strings.yaml
changelog/pending/20230622--cli-state--disallow-renaming-resources-to-invalid-names-that-will-corrupt-the-state.yaml
changelog/pending/20230622--programgen-go--use-raw-string-literals-for-long-multi-line-strings.yaml
changelog/pending/20230622--programgen-nodejs-python--prefer-output-versioned-invokes-in-generated-programs-for-nodejs-and-python.yaml
changelog/pending/20230622--sdk-go-nodejs-python--missing-config-error-text-includes-secret-if-requiresecret-was-used.yaml
changelog/pending/20230622--sdk-nodejs--update-atgrpc-grpc-js-to-1-8-16.yaml
changelog/pending/20230623--cli-display--print-the-summary-event-for-previews-that-contain-non-error-level-diagnostic-messages.yaml
changelog/pending/20230623--engine--engine-marks-outputs-secret-if-an-output-of-the-same-name-is-marked-secret.yaml
changelog/pending/20230624--auto-nodejs--adds-a-better-error-message-for-invalid-nodejs-autoapi-workdir.yaml
changelog/pending/20230624--sdk-nodejs--support-loading-package-json-from-parent-directory.yaml
changelog/pending/20230624--sdkgen-nodejs--fix-isinstance-methods-for-generated-provider-types.yaml
changelog/pending/20230626--cli--improve-the-cli-stack-validation-error-message.yaml
changelog/pending/20230626--cli-package--fixes-resolving-plugins-when-they-are-not-yet-installed-in-plugin-cache.yaml
changelog/pending/20230628--cli-display--fix-diffs-sometimes-not-showing-even-in-details-view.yaml
changelog/pending/20230628--cli-state--add-interactive-urn-selection-to-pulumi-state-rename-unprotect-delete.yaml
changelog/pending/20230628--pkg-testing--programtest-dropped-the-coverprofile-option-as-its-no-longer-necessary.yaml
changelog/pending/20230628--sdkgen--fix-loading-schemas-from-providers-on-path.yaml
pkg/go.mod
sdk/go/pulumi-language-go/go.mod
sdk/nodejs/cmd/pulumi-language-nodejs/go.mod
tests/go.mod

Changelog and go.mod updates for v3.74.0

---

pkg/engine/lifecycletest/pulumi_test.go

Fixes https://github.com/pulumi/pulumi/issues/10117
These are based on names that users currently have used in the pulumi service.

Add tests for various resource names

---

pkg/engine/journal.go

This class is only used for tests, but when writing up a new test and trying to get it to fail I was seeing skipped creates in the snapshots. Simple fix to here to skip those.

Fix engine.Journal to not write out skipped creates

---

pkg/util/plugin.go

See https://github.com/Zaid-Ajaj/pulumi-converter-bicep and @Zaid-Ajaj's latest TGIF demo.

Add Zaid's bicep converter to the known plugin list

---

changelog/pending/20230804--cli--revert-warning-about-ambient-plugins-loaded-from-path-13607.yaml
pkg/cmd/pulumi/plugin.go
pkg/engine/destroy.go
pkg/engine/plugins.go
pkg/engine/refresh.go
pkg/engine/update.go
sdk/go/common/resource/plugin/analyzer_plugin.go
sdk/go/common/resource/plugin/converter_plugin.go
sdk/go/common/resource/plugin/host.go
sdk/go/common/resource/plugin/langruntime_plugin.go
sdk/go/common/resource/plugin/provider_plugin.go
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_test.go

Reverts pulumi/pulumi#13607
Fixes #13656

Revert "Warn about ambient plugins loaded from $PATH"

---

pkg/codegen/nodejs/gen_program.go

As usual for these changes, nothings yet using this but it will be tested by matrix testing and is a direct copy from that branch.

Support localDependencies in the NodeJS codegen

---

pkg/util/plugin.go

Requested by @ringods. The pulumiverse repo for this exists but nothings currently published.

Remove ibm from pulumiverse list

---

.github/workflows/on-merge.yml

I'm not sure why `success()` and `failure()` don't work as expected here, but the [needs context](https://docs.github.com/en/actions/learn-github-actions/contexts#needs-context) does do what we want.
Previously, if the CI job failed the job `ci-ok` job would still pass:
```
❯ act --detect-event
WARN  ⚠ You are using Apple M-series chip and you have not specified container architecture, you might encounter issues while running act. If so, try running it with '--container-architecture linux/amd64'. ⚠
[Merge/info] 🚀  Start image=ghcr.io/catthehacker/ubuntu:act-latest
[Merge/info]   🐳  docker pull image=ghcr.io/catthehacker/ubuntu:act-latest platform= username= forcePull=true
[Merge/info]   🐳  docker create image=ghcr.io/catthehacker/ubuntu:act-latest platform= entrypoint=["tail" "-f" …
```

ci: Fix ci-ok check on merge

---

pkg/cmd/pulumi/stack_change_secrets_provider.go

Was looking at adding a new flag to this command, and wanted to write some tests for that (it's currently totally untested) and the first step for that is splitting it into the new "cmd struct" style.

Split newStackChangeSecretsProviderCmd into command struct

---

.github/workflows/on-pr-default.yml

This needs to be its own job. Refs #13785.

ci: Report ci-ok on version bumps, take two

---

sdk/go/common/workspace/config.go

- Unexport a function that has no callers outside the workspace package
- Rather than using validation callbacks, use a flag + conditionally call the single validator

[workspace] Minor simplification for config merge

---

README.md

docs: make variable declaration more consistency

---

changelog/pending/20230906--sdk-go--rename-join-in-pulumix-to-flatten.yaml
sdk/go/pulumix/combinators.go
sdk/go/pulumix/combinators_test.go

Fixes https://github.com/pulumi/pulumi/issues/13864

Rename Output.Join to Flatten

---

CHANGELOG.md
changelog/pending/20230910--cli--adds-basic-search-and-ai-assisted-search-functionality.yaml
changelog/pending/20230910--cli--adds-pulumi-ai-and-pulumi-ai-web-commands.yaml

This is purely a changelog-related PR. We want to align our blogposts with the changelog on p/p, and since these features should come bundled with the functionality/design feedback, it makes sense for the changelog to reflect that.

Revises changelog history to align with AI CLI release planning

---

pkg/backend/snapshot.go

This field was always true, just remove it.

Remove boolean var that was always true

---

changelog/pending/20230918--cli-new--fix-selector-wrapping-on-narrow-terminals.yaml
cmd/pulumi-test-language/go.mod
cmd/pulumi-test-language/go.sum
pkg/go.mod
pkg/go.sum
sdk/go/pulumi-language-go/go.mod
sdk/go/pulumi-language-go/go.sum
sdk/nodejs/cmd/pulumi-language-nodejs/go.mod
sdk/nodejs/cmd/pulumi-language-nodejs/go.sum
sdk/python/cmd/pulumi-language-python/go.mod
sdk/python/cmd/pulumi-language-python/go.sum
tests/go.mod
tests/go.sum

Fixes https://github.com/pulumi/pulumi/issues/8169
Fixes https://github.com/pulumi/pulumi/issues/11812
Bump survey to v2.3.7 which contains a fix for
https://github.com/go-survey/survey/issues/101
Old: https://asciinema.org/a/jhHadL382jrzrLiU9vAsV7YR9
New: https://asciinema.org/a/lEVkdm1UdMXwUWdpipMxLGOga

[`pulumi new` wrapping] Fix pulumi new selector wrapping on narrow terminals.

---

changelog/pending/20230710--cli-about--pulumi-about-and-pulumi-whoami-will-now-return-information-about-the-access-token-used-to-login-to-the-service.yaml
pkg/backend/backend.go
pkg/backend/filestate/backend.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/client/client.go
pkg/backend/httpstate/stack.go
pkg/backend/mock.go
pkg/cmd/pulumi/about.go
pkg/cmd/pulumi/login.go
pkg/cmd/pulumi/new_acceptance_test.go
pkg/cmd/pulumi/org_search.go
pkg/cmd/pulumi/org_search_ai.go
pkg/cmd/pulumi/org_search_ai_test.go
pkg/cmd/pulumi/org_search_test.go
pkg/cmd/pulumi/policy_group_ls.go
pkg/cmd/pulumi/policy_ls.go
pkg/cmd/pulumi/whoami.go
pkg/cmd/pulumi/whoami_test.go
sdk/go/common/workspace/creds.go

Fixes https://github.com/pulumi/pulumi-cloud-requests/issues/236

Add token info to whoami

---

pkg/resource/deploy/deployment_executor.go
pkg/resource/deploy/import.go

Continued cleanup of the result type.

Clean up result.Result in import.go

---

sdk/python/lib/pulumi/resource.py

Fix a typo in new error message that was just introduced.

[sdk/python] Fix typo in error message

---

.github/workflows/on-release-manual-dispatch.yml
.github/workflows/release.yml
scripts/publish_npm.sh

See individual commit descriptions for details.

Temporary changes to unblock v3.88.1 release

---

pkg/testing/integration/program.go
sdk/go/common/workspace/project.go
tests/integration/environments_basic/Pulumi.yaml
tests/integration/environments_basic/index.ts
tests/integration/environments_basic/package.json
tests/integration/environments_merge/Pulumi.yaml
tests/integration/environments_merge/index.ts
tests/integration/environments_merge/package.json
tests/integration/integration_nodejs_test.go

- Add support for environments to the integration test framework
- Add integration tests for simple + merged environments

[environments] Add integration tests

---

developer-docs/providers/implementers-guide.md

Multiple typos fixed in developer-docs/providers/implementers-guide.md file.

Typos fixed in implementers-guide.md file

---

.github/workflows/ci-prepare-release.yml

Update to https://github.com/sigstore/cosign-installer/releases/tag/v3.1.2

Update cosign-installer action

---

pkg/resource/deploy/step_executor.go

This was getting annoying when debugging tests because a step would fail it wouldn't propagate up in the wrapped error and we don't show the diagnostic logs in tests.

Wrap StepApplyFailed so we can see errors in tests

---

changelog/pending/20231115--sdk-python--use-typing-dict-in-type-annotation-instead-of-dict.yaml
sdk/python/lib/pulumi/dynamic/__main__.py

Fixes https://github.com/pulumi/pulumi/issues/14580.

Replace dict with typing.Dict in type annotation

---

cmd/pulumi-test-language/go.mod
cmd/pulumi-test-language/go.sum
pkg/go.mod
pkg/go.sum
sdk/go/pulumi-language-go/go.mod
sdk/go/pulumi-language-go/go.sum
sdk/nodejs/cmd/pulumi-language-nodejs/go.mod
sdk/nodejs/cmd/pulumi-language-nodejs/go.sum
sdk/python/cmd/pulumi-language-python/go.mod
sdk/python/cmd/pulumi-language-python/go.sum
tests/go.mod
tests/go.sum

Should help with the `cli.PrepareEnvironment` build issues some people have been seeing.

Update esc to v0.6.0

---

pkg/engine/lifecycletest/pulumi_test.go

Extend the unknowns in config for a provider test to cover Invokes and Calls.

Extend unknown providers test to cover Call and Invoke

---

tests/integration/double_pending_delete/double_pending_delete_test.go
tests/integration/integration_go_acceptance_test.go
tests/integration/integration_go_test.go
tests/integration/integration_nodejs_acceptance_test.go
tests/integration/integration_nodejs_test.go
tests/integration/integration_python_acceptance_test.go
tests/integration/integration_python_test.go
tests/integration/integration_test.go
tests/integration/partial_state/partial_state_test.go
tests/integration/protect_resources/protect_test.go
tests/integration/steps/steps_test.go

Again same as https://github.com/pulumi/pulumi/pull/14644, just fixing some issues that make lint sees once you enable build tags.

Fix some more lint issues

---

changelog/pending/20231129--yaml--upgrade-yaml-to-1-4-3.yaml
pkg/go.mod
pkg/go.sum
tests/go.sum

Upgrade `pulumi-yaml` to the latest version, including https://github.com/pulumi/pulumi-yaml/pull/529.

Upgrade pulumi-yaml to 1.4.3

---

.golangci.yml
tests/integration/aliases/aliases_go_test.go
tests/integration/aliases/aliases_nodejs_test.go
tests/integration/aliases/aliases_py_test.go
tests/integration/delete_before_create/delete_before_create_test.go
tests/integration/dependency_steps/dependency_steps_test.go
tests/integration/double_pending_delete/double_pending_delete_test.go
tests/integration/duplicate_urns/duplicate_urns_test.go
tests/integration/integration_go_acceptance_test.go
tests/integration/integration_go_test.go
tests/integration/integration_nodejs_acceptance_test.go
tests/integration/integration_nodejs_test.go
tests/integration/integration_python_acceptance_test.go
tests/integration/integration_python_test.go
tests/integration/integration_util_test.go
tests/integration/partial_state/partial_state_test.go
tests/integration/protect_resources/protect_test.go
tests/integration/query/query_test.go
tests/integration/read/import_acquire/import_acquire_test.go
tests/integration/read/read_dbr/read_dbr_test.go
tests/integration/read/read_relinquish/read_relinquish_test.go
tests/integration/read/read_replace/read_dbr_test.go
tests/integration/recreate_resource_check/resource_recreate_check_test.go
tests/integration/steps/steps_test.go
tests/integration/transformations/transformations_nodejs_test.go
tests/integration/transformations/transformations_py_test.go
tests/integration/types/types_test.go

All paralleltest issues, also turns on the linter for these files now they lint ok.

Fix remaining lint issues

---

pkg/codegen/convert/plugin_mapper.go

Quick fix for https://github.com/pulumi/pulumi/issues/14718.
This could probably be smarter but this will unblock the use of the new converter for providers.

Lock in the plugin mapper

---

changelog/pending/20231207--auto-nodejs--add-config-env-functions.yaml
sdk/nodejs/automation/localWorkspace.ts
sdk/nodejs/automation/stack.ts
sdk/nodejs/automation/workspace.ts
sdk/nodejs/tests/automation/data/nested_config/Pulumi.dev.yaml
sdk/nodejs/tests/automation/localWorkspace.spec.ts

Add nodejs automation API support for adding and removing environments for stack configuration.
Fixes https://github.com/pulumi/pulumi/issues/14795

[Automation API / Nodejs] - Environment functions

---

changelog/pending/20231207--auto-go--add-config-env-functions.yaml
sdk/go/auto/local_workspace.go
sdk/go/auto/local_workspace_test.go
sdk/go/auto/stack.go
sdk/go/auto/test/nested_config/Pulumi.dev.yaml
sdk/go/auto/workspace.go

Add go automation API support for adding and removing environments for stack configuration.
Fixes https://github.com/pulumi/pulumi/issues/14794

[Automation API / Go] - Environment functions

---

.github/workflows/cron-direct-build.yml

Add a test that we can run a user Go program with GOPROXY=direct.

Add simple Go test with GOPROXY=direct

---

.github/workflows/ci.yml
tests/integration/integration_go_acceptance_test.go

See if this helps with windows job timeouts.

Split up acceptance tests

---

pkg/resource/deploy/builtins_test.go
pkg/resource/deploy/deploytest/languageruntime_test.go
pkg/resource/deploy/deploytest/pluginhost_test.go
pkg/resource/deploy/deploytest/provider.go
pkg/resource/deploy/deploytest/sink.go
pkg/resource/deploy/manifest_test.go
pkg/resource/deploy/plan_test.go
pkg/resource/deploy/providers/registry_test.go
pkg/resource/deploy/source_eval.go
pkg/resource/deploy/source_eval_test.go
pkg/resource/deploy/source_query_test.go
pkg/resource/deploy/step_test.go

code coverage `pkg/resource/deploy` from 76% -> 83%
Will remove CI changes and squash commits prior to merging PR.

[ci] `pkg/resource/deploy` coverage

---

changelog/pending/20231219--cli--update-esc-to-v0-6-2.yaml
cmd/pulumi-test-language/go.mod
cmd/pulumi-test-language/go.sum
pkg/go.mod
pkg/go.sum
sdk/go.mod
sdk/go.sum
sdk/go/pulumi-language-go/go.mod
sdk/go/pulumi-language-go/go.sum
sdk/nodejs/cmd/pulumi-language-nodejs/go.mod
sdk/nodejs/cmd/pulumi-language-nodejs/go.sum
sdk/python/cmd/pulumi-language-python/go.mod
sdk/python/cmd/pulumi-language-python/go.sum
tests/go.mod
tests/go.sum
tests/integration/construct_component_configure_provider/testcomponent-go/go.mod
tests/integration/construct_component_configure_provider/testcomponent-go/go.sum
tests/integration/construct_component_provider_propagation/go/go.mod
tests/integration/construct_component_provider_propagation/go/go.sum
tests/integration/construct_component_resource_options/go/go.mod
tests/integration/construct_component_resource_options/go/go.sum
tests/integration/construct_nested_component/go/go.mod
tests/integration/construct_nested_component/go/go.sum

Update to the latest version of esc.

Update esc to v0.6.2

---

pkg/backend/filestate/backend.go
pkg/resource/edit/operations.go
pkg/resource/edit/operations_test.go

The RenameStack function in filestate was one of the few places outside of "cmd" still using `stack.DefaultSecretsProvider`, which it was only using because the stack rename function was written in terms of deserialised snapshots instead of serialised deployments.
This change rewrites the RenameStack function to work on the raw deployment data rather than deserialised snapshot. This allows us to remove the use of `stack.DefaultSecretsProvider` from filestate.
This would also allow the service to update their use of RenameStack to work on the raw deployment as well, saving them the use of their NoopSecretsProvider.

Rewrite filestate.RenameStack logic in terms of checkpoints

---

pkg/resource/deploy/source_query_test.go

Adds `pkg/resource/deploy/source_query_test.go` which adds missing coverage to `pkg/resource/deploy/source_query.go`
Note: disregard CI changes. will revert prior to merge.

[ci] `pkg/resource/deploy/source_query.go` coverage

---

pkg/testing/integration/program_test.go
scripts/get-job-matrix.py

In the past we've run into consistent timeouts running on smaller Windows runners, but let's see how we currently fare.

Attempt to run Windows tests on small runners

---

changelog/pending/20240115--sdk-go--add-withvalue-to-pulumi-context.yaml
sdk/go/pulumi/context.go
sdk/go/pulumi/context_test.go
sdk/go/pulumi/provider.go
sdk/go/pulumi/resource_test.go
sdk/go/pulumi/run.go

Add WithValue to pulumi.Context
Fixes https://github.com/pulumi/pulumi/issues/11825.

[11825] Add WithValue to pulumi.Context

---

pkg/asset/massage.go
pkg/backend/display/object_diff.go
pkg/engine/events.go
sdk/go/common/resource/asset.go

Prompted by https://github.com/pulumi/pulumi/pull/15157.
Trying to move as much of the code in assets and archives to pkg.

Move some asset code to pkg

---

changelog/pending/20240118--cli-display--fix-json-yaml-value-diff-displays.yaml
pkg/backend/display/diff_test.go
pkg/backend/display/object_diff.go
pkg/backend/display/testdata/json-yaml/json-text-change.json
pkg/backend/display/testdata/json-yaml/json-text-change.json.stdout.txt
pkg/backend/display/testdata/json-yaml/json.json
pkg/backend/display/testdata/json-yaml/json.json.stdout.txt
pkg/backend/display/testdata/json-yaml/yaml-text-change.json
pkg/backend/display/testdata/json-yaml/yaml-text-change.json.stdout.txt
pkg/backend/display/testdata/json-yaml/yaml.json
pkg/backend/display/testdata/json-yaml/yaml.json.stdout.txt

Fixes https://github.com/pulumi/pulumi/issues/13981.
This regressed in https://github.com/pulumi/pulumi/pull/11803. I've added tests to this PR to show both the value diffing and text diffing for when the JSON/YAML string is different but the values are the same.

Fix JSON/YAML diffs

---

pkg/resource/deploy/source_eval.go
pkg/resource/deploy/source_eval_test.go

Precursor to moving transformations to run for remote components. We need to re-send alias options to the transform function but we'll want to do the NodeJS fixup before sending them onwards.

Fix NodeJS alias objects at the protocol level.

---

sdk/go/common/workspace/project.go

I had a question about how to configure the Go Automation SDK to use Pulumi Cloud as a backend. This adds documentation to make things easier for the next person with the same question by clarifying what values to use in different situations.
Doc change only.

Improve Go Automation SDK ProjectBackend documentation

---

tests/go.mod
tests/integration/backend/filestate/backend_aws_test.go
tests/integration/backend/filestate/backend_azure_test.go
tests/integration/backend/filestate/backend_gcp_test.go
tests/integration/backend/filestate/helpers.go

Fixes https://github.com/pulumi/pulumi/issues/3760

add tests for aws and gcp

---

changelog/pending/20230406--cli-plugin--add-plugin-run-command-for-running-plugin-binaries-directly.yaml
pkg/cmd/pulumi/plugin.go
pkg/cmd/pulumi/plugin_run.go
pkg/resource/deploy/deploytest/pluginhost.go
sdk/go/common/resource/plugin/host.go
sdk/go/common/workspace/plugins.go

Mostly for providers to experiment with, currently hidden behind "PULUMI_DEV".

Add `plugin run` command

---

sdk/go/common/resource/plugin/rpc.go
sdk/go/common/resource/plugin/rpc_test.go

Fix an issue with UpgradeToOutputValues that tripped an assert in ResourceReferences. 
Also shouldn't matter much but made UpgradeToOutputValues require KeepOutputValues set as well.

Fix upgrade with ResourceReference

---

pkg/resource/deploy/deploytest/resourcemonitor.go

While working on some new tests I noticed that ResourceMonitor in the tests didn't set KeepOutputValues for remote resources like it should. This fixes that.

Set KeepOutputValues in deploytest.ResourceMonitor

---

.github/workflows/ci-run-test.yml
.github/workflows/ci-test-docs-generation.yml
.github/workflows/pr-test-codegen-downstream.yml

ci: Use the latest version of setup-dotnet

---

.github/workflows/ci-dev-release.yml
.github/workflows/on-merge.yml

Fixes https://github.com/pulumi/pulumi/issues/15471.

Fix dev release versions

---

pkg/resource/deploy/step_generator.go

We have generics and the slices package now, use it to save having to think if a reversing for loop is correct or not.

Use slices.Reverse

---

pkg/cmd/pulumi/convert-trace.go

If a span doesn't have a TimespanEvent then determine the start and end times from the sub spans (if any). This fixes an occational issue where one of the root spans doesn't have the TimespanEvent set which causes the entire OTEL trace conversion to fail
Also ensure that InstrumentationLibrary and InstrumentationScope return the same object.

`convert-trace` handles root spans with no TimespanEvent

---

.golangci.yml
changelog/pending/20240228--sdk-nodejs--regenerate-yarn-lock-to-fix-lru-cache-hoisting.yaml
pkg/backend/httpstate/backend_test.go
pkg/cmd/pulumi/util_test.go
pkg/codegen/nodejs/test.go
pkg/testing/integration/program.go
sdk/go/auto/errors_test.go
sdk/go/auto/local_workspace_test.go
sdk/go/auto/remote_workspace_test.go
sdk/go/auto/stack_test.go
sdk/go/common/testing/util.go
sdk/nodejs/npm/manager_test.go
sdk/nodejs/package.json
sdk/nodejs/yarn.lock
tests/config_test.go
tests/integration/backend/diy/helpers.go
tests/preview_only_test.go

Fixes https://github.com/pulumi/pulumi/issues/15528
See https://github.com/pulumi/pulumi/pull/15540 & https://github.com/pulumi/pulumi/pull/15531
Re-creating this as a PR with `ci/test` label so we can get it merged.

Fix merge failures #2

---

pkg/cmd/pulumi/import.go

Adds a brief note about where to find these items.
Part of https://github.com/pulumi/pulumi-hugo/issues/1265.

Add a note about where to find the type token and lookup id

---

sdk/nodejs/provider/server.ts
sdk/nodejs/runtime/invoke.ts
sdk/nodejs/runtime/resource.ts
sdk/nodejs/runtime/rpc.ts

Just fixing up some `any` uses to their actual types. One instance of a missing undefined check.

Cleanup so uses of `any` in the nodejs sdk

---

CONTRIBUTING.md

As we discussed in ideation yesterday, this is the way we want to go, and try to be consistent with it.  I've also opened https://github.com/pulumi/go-change/pull/25 to update the go-change tool to suggest that mood.

document active imperative mood for changelog messages

---

pkg/codegen/nodejs/gen_test.go
pkg/codegen/nodejs/test.go
pkg/codegen/testing/test/testdata/embedded-crd-types/nodejs/package.json
pkg/codegen/testing/test/testdata/embedded-crd-types/schema.json
sdk/nodejs/cmd/pulumi-language-nodejs/language_test.go
tests/integration/integration_nodejs_acceptance_test.go
tests/integration/integration_nodejs_test.go
tests/integration/nodejs/codepaths-nested/nested/index.ts
tests/integration/nodejs/codepaths-workspaces/infra/index.ts
tests/integration/nodejs/codepaths/index.ts

Fixes #15557 
Ref #15555
Ref #15556

Unskip tests skipped in #15555, #15556, #15557

---

changelog/pending/20240205--sdk-python--add-support-for-remote-transforms.yaml
sdk/python/.pylintrc
sdk/python/lib/pulumi/__init__.py
sdk/python/lib/pulumi/resource.py
sdk/python/lib/pulumi/runtime/__init__.py
sdk/python/lib/pulumi/runtime/_callbacks.py
sdk/python/lib/pulumi/runtime/resource.py
sdk/python/lib/pulumi/runtime/settings.py
sdk/python/lib/pulumi/runtime/stack.py
tests/integration/transforms/python/simple/Pulumi.yaml
tests/integration/transforms/python/simple/__main__.py
tests/integration/transforms/python/simple/random_.py
tests/integration/transforms/transforms_py_test.go

This PR adds support for remote transforms to the Python SDK.
Part of #12996

[sdk/python] Add support for remote transforms

---

CONTRIBUTING.md
pkg/backend/display/progress.go

chore: remove repetitive words

---

pkg/cmd/pulumi/import.go

Pointed out at https://github.com/pulumi/pulumi/issues/15633#issuecomment-1995610172

Fix some grammer in import docs

---

scripts/go-test.py

Add some more debug output to maybe help us identify what's happening in https://github.com/pulumi/pulumi/issues/15274.
I don't get why the output in https://github.com/pulumi/pulumi/actions/runs/7672650761/job/20913866181#step:38:1 suddenly just stops, so adding some debug output here to see if that helps track/narrow things down.

add some more debug output to CI script

---

pkg/cmd/pulumi/config.go
pkg/cmd/pulumi/config_test.go

- Add a test to cover literal environments
- Add another test for config merging

[cli] Additional tests for environments + config

---

sdk/nodejs/package.json

Make package.engines reflect the reality of what we support.

Update node version in package.json

---

changelog/pending/20240402--sdk-nodejs--set-package-json-engines-to-node-18.yaml

Somehow https://github.com/pulumi/pulumi/pull/15816 got merged without changelog.

Add missing changelog for #15816

---

pkg/backend/display/rows.go
pkg/backend/httpstate/client/client.go

chore: fix function name in comment

---

pkg/codegen/pcl/binder_component.go
pkg/codegen/schema/schema.go
sdk/go/pulumi/generate/templates/types_builtins.go.template
sdk/go/pulumi/types_builtins.go

This commit exists to enable the Java SDK to update and use it, which then unblocks the next commit passing tests.
Part of #6346

feat: declare a new type for 'any resource'

---

changelog/pending/20240324--sdkgen-dotnet-go--fixes-sdk-generation-when-referencing-shared-types-in-config-variables.yaml
changelog/pending/20240326--sdk-python--adds-typechecker-runtime-option-to-the-python-language-host.yaml
changelog/pending/20240404--auto--tolerate-missing-stack-and-bookkeeping-files-in-programtest.yaml
changelog/pending/20240409--programgen-dotnet--removes-trailing-whitespace-from-emitted-dependson-resource-option-expressions.yaml

Fix a few changelog entries that aren't consistent with our style guide.
I noticed these in https://github.com/pulumi/pulumi/pull/15920.  If we want to fix these up we should merge this before that PR.

changelog consistency fixes

---

pkg/codegen/schema/schema.go
sdk/go/auto/remote_workspace.go

Fix some names in comments to match the attached code names.

chore: fix some comments

---

pkg/codegen/dotnet/gen.go
pkg/codegen/dotnet/templates.go

Last few changes needed to get the dotnet repo passing conformance tests.

Finish supporting dotnet conformance

---

sdk/go/pulumi/context.go
tests/integration/transforms/go/simple/main.go
tests/integration/transforms/go/simple/random.go
tests/integration/transforms/nodejs/simple/index.ts
tests/integration/transforms/nodejs/simple/random.ts
tests/integration/transforms/python/simple/__main__.py
tests/integration/transforms/python/simple/random_.py
tests/integration/transforms/transforms_test.go

Adding some more transform tests. Trying to repro https://github.com/pulumi/pulumi/issues/15984 although it oddly seems to be component resource specific. These tests are still worth having and found some other issues.

Add tests for providers with transforms

---

pkg/cmd/pulumi/convert_test.go
pkg/cmd/pulumi/gen_completion.go
pkg/cmd/pulumi/package.go
pkg/cmd/pulumi/util_test.go

Fix function names in comments.

chore: fix function names in comment

---

pkg/codegen/testing/test/helpers.go

Fixes https://github.com/pulumi/pulumi/issues/16047.

Update version of dotnet we run tests against

---

changelog/pending/20240524--cli-state--fix-state-renames-involving-deletedwith.yaml
pkg/cmd/pulumi/state_rename.go

Fix state renames involving `DeletedWith`

---

Makefile

We missed this in https://github.com/pulumi/pulumi/pull/16246.
Fixes https://github.com/pulumi/pulumi/issues/16268

fix name of Makefile target

---

changelog/pending/20240610--components-dotnet--upgrade-dotnet-to-3-64-0.yaml
pkg/codegen/testing/test/helpers.go
scripts/get-language-providers.sh

Upgrade to the latest dotnet release.

upgrade dotnet dependency to latest

---

sdk/go/common/apitype/deployments.go

Add support for deployment settings YAML marshalling. This work is part of the effort to manage deployment settings through the CLI and source control. 
Fixes https://github.com/pulumi/pulumi-service/issues/20275

Update pu/pu apitype to support Deployment Settings yaml marshalling

---

pkg/backend/backend.go
pkg/backend/diy/backend.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/client/client.go
pkg/backend/mock.go

Add DS endpoints to the backend and client
Fixes https://github.com/pulumi/pulumi-service/issues/20276

Update pu/pu to support new Deployment Settings endpoints

---

changelog/pending/20240610--sdk-python--automatically-converts-requirements-txt-to-pyproject-toml-when-using-poetry.yaml
cmd/pulumi-test-language/go.mod
cmd/pulumi-test-language/go.sum
sdk/go.mod
sdk/go.sum
sdk/go/pulumi-language-go/go.mod
sdk/go/pulumi-language-go/go.sum
sdk/nodejs/cmd/pulumi-language-nodejs/go.mod
sdk/nodejs/cmd/pulumi-language-nodejs/go.sum
sdk/python/toolchain/poetry.go
sdk/python/toolchain/poetry_test.go
tests/integration/construct_component_configure_provider/testcomponent-go/go.mod
tests/integration/construct_component_configure_provider/testcomponent-go/go.sum
tests/integration/construct_component_provider_propagation/go/go.mod
tests/integration/construct_component_provider_propagation/go/go.sum
tests/integration/construct_component_resource_options/go/go.mod
tests/integration/construct_component_resource_options/go/go.sum
tests/integration/construct_nested_component/go/go.mod
tests/integration/construct_nested_component/go/go.sum
tests/integration/integration_python_acceptance_test.go

When using a template that uses requirements.txt with the poetry toolchain, we convert this to a pyproject.toml automatically.
Fixes https://github.com/pulumi/pulumi/issues/16355
Ref https://github.com/pulumi/pulumi/issues/15937
Stacked on top of https://github.com/pulumi/pulumi/pull/16347

Convert requirements.txt to pyproject.toml

---

pkg/cmd/pulumi/config_env_add_test.go

Apply the flake fix from https://github.com/pulumi/pulumi/pull/16468 to the rest of the test cases.
Fixes https://github.com/pulumi/pulumi/issues/16474

Fix TestConfigEnvAddCmd flake

---

pkg/cmd/pulumi/config_env_add_test.go
pkg/cmd/pulumi/config_env_init_test.go
pkg/cmd/pulumi/config_env_ls_test.go
pkg/cmd/pulumi/config_env_rm_test.go
pkg/cmd/pulumi/config_env_test.go

Fixes https://github.com/pulumi/pulumi/issues/16474
Continue the fixes from https://github.com/pulumi/pulumi/pull/16482 and https://github.com/pulumi/pulumi/pull/16477

Fix TestConfigEnvXXX flakes

---

pkg/go.mod
pkg/go.sum
tests/go.mod
tests/go.sum

This version has been released a couple of days ago, let's pull it in here.

update pulumi-yaml to 1.9.0

---

pkg/cmd/pulumi/state_move.go
pkg/cmd/pulumi/state_move_test.go

Once we moved the resources, we also want to save the snapshot.  Do so here.
We try to save the destination snapshot first, so resources don't get orphaned, as it's probably slightly easier for users to delete resources form the source snapshot than it is for them to import them again in the destination. Ideally this would be an atomic operation, but I don't think we have the means to do that right now.

save snapshots after we moved the resources

---

changelog/pending/20240711--yaml--fixes-using-stackreference-outputs-of-types-other-than-string-in-pulumi-yaml.yaml
cmd/pulumi-test-language/go.mod
pkg/go.mod
pkg/go.sum
sdk/go/pulumi-language-go/go.mod
sdk/nodejs/cmd/pulumi-language-nodejs/go.mod
sdk/python/cmd/pulumi-language-python/go.mod
tests/go.mod
tests/go.sum
tests/integration/construct_component_configure_provider/testcomponent-go/go.mod

Fixes pulumi/pulumi-yaml#599
See:
- https://github.com/pulumi/pulumi/pull/16625
- https://github.com/pulumi/pulumi-yaml/pull/600

Update Pulumi YAML to 1.9.1

---

sdk/go/common/resource/plugin/provider_plugin_test.go

This commit adds a test to ensure that provider `Delete`s are passed with the correct set of parameters. This is a regression test for #16440, as part of the follow-up to #16441 in #16484. Assuming we are happy with this level/style of test, we should consider adding tests for the other provider methods also.
Fixes #16484

Test provider `Delete` parameter marshalling

---

pkg/cmd/pulumi/deployment_settings_config.go
pkg/cmd/pulumi/deployment_settings_ops.go
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/util.go

This PR unifies and standardizes user prompting
Also applies feedback from https://github.com/pulumi/pulumi/pull/16564

Unify user prompts + cleanups + previous feedback

---

changelog/pending/20240717--sdk-nodejs--add-support-for-invoke-stack-transforms.yaml
sdk/nodejs/invoke.ts
sdk/nodejs/resource.ts
sdk/nodejs/runtime/callbacks.ts
sdk/nodejs/runtime/invoke.ts
sdk/nodejs/runtime/settings.ts
sdk/nodejs/runtime/stack.ts
sdk/nodejs/runtime/state.ts
tests/integration/transforms/nodejs/simple/index.ts
tests/integration/transforms/nodejs/simple/random.ts

Similar to what we recently did for Go in https://github.com/pulumi/pulumi/pull/16617, also implement invoke transforms for NodeJS

implement invoke transforms for NodeJS

---

changelog/pending/20240715--auto-python--implement-stack-import_resources-for-batch-importing-resources-into-a-stack.yaml
sdk/python/lib/pulumi/automation/_stack.py
sdk/python/lib/test/automation/data/import/Pulumi.yaml
sdk/python/lib/test/automation/data/import/expected_generated_code.yaml
sdk/python/lib/test/automation/test_local_workspace.py

Addressing https://github.com/pulumi/pulumi/issues/8237 for Python. 
Since `import` is a reserved keyword in python, I went with `import_resources` as the function name. It's a bit unfortunate that it is not the same name as other SDKs but I wasn't sure which name to use here.  Suggestions are welcome 🙏

[python/automation] Implement Stack.import_resources() for batch importing resources into a stack

---

pkg/engine/lifecycletest/parameterized_test.go

Parameterization refers to the ability for a provider to vary its schema based on a parameter that is passed to a new `Parameterize` call on the provider interface. The package reference that is returned may then be used to interact with the bespoke schema/packages within. Paramterization is key to e.g. dynamically bridging providers. In this instance we can manage and release a single "bridge" provider that accepts a parameter defining the upstream provider to bridge, and returns a reference to a dynamically constructed package whose schema reflects the upstream as needed.
In this commit, we add test cases for `Construct`, the call which powers multi-language components (MLCs). The nature of `Construct` means that it already works by virtue of the changes made to `RegisterResource` …

Test parameterized `Construct` support in the engine

---

cmd/pulumi-test-language/providers/config_provider.go
cmd/pulumi-test-language/tests.go

Small test bug missed in https://github.com/pulumi/pulumi/pull/16837.

Fix l2-resource-config to test name and pluginDownloadURL correctly

---

sdk/nodejs/runtime/resource.ts

I noticed this while testing something.  It's been there for a long time, but might as well fix it.

fix typo in an error message

---

developer-docs/providers/implementers-guide.md

Following up on a [recent PR](https://github.com/pulumi/pulumi/pull/16725) to document the interaction of ignoreChanges and Check, adding this documentation to dev docs.

devdocs: Document ignore changes interaction with Check

---

changelog/pending/20240729--auto-go--add-support-for-pulumi-destroy-preview-only.yaml
sdk/go/auto/local_workspace_test.go
sdk/go/auto/stack.go

[auto/go] Add support for `destroy --preview-only`

---

changelog/pending/20240808--sdk-python--add-parameterization-support-for-call-and-read-in-python.yaml
pkg/codegen/python/gen.go
sdk/python/lib/pulumi/resource.py
sdk/python/lib/pulumi/runtime/invoke.py
sdk/python/lib/pulumi/runtime/resource.py
tests/integration/integration_python_test.go
tests/integration/python/parameterized/__main__.py
tests/integration/python/parameterized/sdk/python/pulumi_pkg/echo.py

Thread through package_ref for call and read_resource.
Stacked on https://github.com/pulumi/pulumi/pull/16901 to get the testprovider updates.

Add parameterization support for call & read in python

---

pkg/cmd/pulumi/package_add.go

Currently, `gen-sdk` does not include the name of the plugin or package in the directory it generates code into. Moreover, it _does_ include the name of the language for which code is being generated. Neither of these is a great experience when producing SDKs that must be manually linked, so we work around this in `package add`, moving generated code into an `sdks/<package-name>` subdirectory.

Use better names for `package add`-generated SDKs

---

pkg/cmd/pulumi/state_edit.go

Typo in https://github.com/pulumi/pulumi/pull/16992

fix help text for --stack in state edit

---

pkg/codegen/testing/test/program_driver.go

The issue no longer repros so we can unskip these compile tests.
Fixes #8075

[programgen/nodejs] Unskip some tests

---

pkg/codegen/nodejs/gen.go
tests/testdata/codegen/simplified-invokes/nodejs/absMultiArgs.ts
tests/testdata/codegen/simplified-invokes/nodejs/absMultiArgsReducedOutput.ts
tests/testdata/codegen/simplified-invokes/nodejs/absMultiArgsReducedOutputSwapped.ts
tests/testdata/codegen/simplified-invokes/nodejs/getArchive.ts
tests/testdata/codegen/simplified-invokes/nodejs/getArrayCustomResult.ts
tests/testdata/codegen/simplified-invokes/nodejs/getAsset.ts
tests/testdata/codegen/simplified-invokes/nodejs/getCustomResult.ts
tests/testdata/codegen/simplified-invokes/nodejs/getDictionary.ts

Fixes https://github.com/pulumi/pulumi/issues/16908

Add semicolon output functions

---

changelog/pending/20240814--backend-service--prefer-pulumi_access_token-set-in-the-environment-over-the-one-stored-in-the-config-when-they-dont-match.yaml
changelog/pending/20240815--docs--show-envvars-for-provider-nested-types.yaml
changelog/pending/20240816--cli--show-a-better-message-when-logging-out-with-all.yaml

Just a couple of changelog fixes to get them into a consistent style for 3.130.0.

Changelog fixes

---

changelog/pending/20240828--auto-python--add-localworkspace-install-method.yaml
sdk/python/lib/pulumi/automation/_local_workspace.py
sdk/python/lib/test/automation/test_local_workspace.py

Add the LocalWorkspace.install method to the Python Automation API
Ref https://github.com/pulumi/pulumi/issues/16781

Add LocalWorkspace.install method for Python

---

pkg/backend/display/options.go
pkg/backend/display/progress.go
pkg/backend/display/progress_test.go
pkg/engine/lifecycletest/test_plan.go

Add a deep link to Pulumi Console from CLI.
Details: https://docs.google.com/document/d/1QJucNEnO4hcnhqwADyMYXEHMuyhrB6tyulpoxbYX7Xg/edit?usp=sharing

Add link to Copilot in CLI printDiagnostics

---

pkg/codegen/schema/loader_client.go

A `LoaderClient` is a `ReferenceLoader` over grpc. As such it can be `Close`ed, but this wasn't being exposed on the public API because we were just returning a `ReferenceLoader` directly.
This makes the LoaderClient type public so it's clear it can be closed.

Make LoaderClient public

---

changelog/pending/20240902--auto-nodejs--add-localworkspace-install-method-for-nodejs.yaml
sdk/nodejs/automation/localWorkspace.ts
sdk/nodejs/tests/automation/localWorkspace.spec.ts

Add the LocalWorkspace.install method to the Nodejs Automation API
Ref https://github.com/pulumi/pulumi/issues/16781

Add LocalWorkspace.install method for Nodejs

---

tests/integration/resource_refs_get_resource/go/main.go

In https://github.com/pulumi/pulumi/pull/16897 we made sure we wait for the child to be registered in the container before we continue to avoid racyness.  We however also need to do the same for the message registered on the child, otherwise that can still race.  Do so here.
Fixes https://github.com/pulumi/pulumi/issues/17095

ResourceRefsGetResourceGo: also wait for the childs message to be registered

---

sdk/nodejs/cmd/pulumi-language-nodejs/main.go

Add debugging support for the Go language. The scaffolding for this was put in place previously in #17072 and then #17087.
To start the debugging, we're passing the `--inspect-brk` option to node, which enables debug mode, and pauses the program until the debugger is attached.
Again writing tests for this seems a bit tricky, since we need to attach to a process (unless someone knows the trick on how to do that?)
Fixes #17171

add debugging support to Nodejs language host

---

.github/workflows/ci-build-binaries.yml
CONTRIBUTING.md

As suggested by @tgummerer at https://github.com/pulumi/pulumi/pull/17015/files#r1722817544.

Document get.pulumi.com to download PRs

---

pkg/cmd/pulumi/new_test.go
pkg/go.mod
sdk/go/common/resource/plugin/analyzer_plugin.go
sdk/go/common/resource/plugin/host.go
sdk/go/common/resource/plugin/host_server.go
sdk/go/common/resource/plugin/langruntime_plugin.go
sdk/go/common/resource/plugin/rpc.go
sdk/go/common/util/cmdutil/args.go
sdk/go/common/util/cmdutil/diag.go
sdk/go/common/util/cmdutil/profile.go
sdk/go/common/util/rpcutil/serve.go

Also replace a couple of cases of `errors.Cause` with `errors.Is`.

Replace pkg/errors.Wrap with fmt.Errorf

---

cmd/pulumi-test-language/go.mod
cmd/pulumi-test-language/go.sum
pkg/backend/httpstate/environments.go
pkg/go.mod
pkg/go.sum
sdk/go/pulumi-language-go/go.mod
sdk/go/pulumi-language-go/go.sum
sdk/nodejs/cmd/pulumi-language-nodejs/go.mod
sdk/nodejs/cmd/pulumi-language-nodejs/go.sum
sdk/python/cmd/pulumi-language-python/go.mod
sdk/python/cmd/pulumi-language-python/go.sum
tests/go.mod
tests/go.sum
tests/integration/construct_component_configure_provider/testcomponent-go/go.mod
tests/integration/construct_component_configure_provider/testcomponent-go/go.sum

Use the new `GetAnonymousOpenEnvironment` method from ESC for anonymous environments
(will merge into the esc projects feature branch)
Tested with `pulumi config --open`

Use anonymous open env route for ESC

---

cmd/pulumi-test-language/interface.go
cmd/pulumi-test-language/l1empty_test.go

YAML doesn't have a core SDK so we need to be able to run conformance testing skipping the parts related to having a core SDK.

Allow conformance test to run without a core SDK

---

changelog/pending/20240913--sdk-dotnet--update-dotnet-to-3-67-1.yaml
pkg/codegen/testing/test/helpers.go
scripts/get-language-providers.sh

This includes a fix for debugging in the dotnet language host

Upgrade pulumi-dotnet to 3.67.1

---

changelog/pending/20240913--pkg--update-pulumi-java-to-0-16-1.yaml
pkg/go.mod
pkg/go.sum
tests/go.mod
tests/go.sum

Upgrade pulumi-java to 0.16.1

---

cmd/pulumi-test-language/test_host.go

This is needed for yaml conformance tests. The schema loading code tries to call ResolvePlugin to see if it can get the path before calling Provider to load the plugin.

Support ResolvePlugin for schema loading

---

tests/integration/integration_go_test.go
tests/integration/integration_python_test.go
tests/integration/python/venv/requirements.txt

The debugging support has been merged in https://github.com/pulumi/pulumi/pull/17179, without adding tests to facilitate early testing.  We should however really have a test for it to make sure this works.  Add that here.

python: add test showing that attaching a debugger works

---

changelog/pending/20240917--yaml--update-pulumi-yaml-to-1-10-1.yaml
pkg/go.mod
pkg/go.sum
tests/go.sum

Upgrade pulumi-yaml to the latest patch release.

Update pulumi-yaml to 1.10.1

---

changelog/pending/20240919--sdkgen-python--fix-sdk-gen-for-parameterized-providers.yaml
pkg/codegen/python/gen.go
tests/integration/python/parameterized/sdk/python/pulumi_pkg/_utilities.py
tests/integration/python/parameterized/sdk/python/setup.py

And fix the support feature flag looked at in get_package.

Update python codegen to use 3.134.1 for param providers

---

pkg/cmd/pulumi/state_delete_test.go

Couple more state delete tests checking some basic scenarios.

Add more state delete tests

---

pkg/cmd/pulumi/install.go
pkg/engine/destroy.go
pkg/engine/plugins.go
pkg/engine/plugins_test.go
pkg/engine/refresh.go
pkg/engine/update.go

Get latest version if one not specified in pulumi manifest
Refactor code from
https://github.com/pulumi/pulumi/pull/16981 to share code.
Related to https://github.com/pulumi/pulumi/issues/16920
Original version: #16982

plugin versions code reuse

---

sdk/nodejs/cmd/pulumi-language-nodejs/language_test.go

Add another `t.Run` layer to the node conformance tests so the tsc and tsnode runs in parallel.

Run nodejs conformance tests with more parallelism

---

docs/architecture/types/property-path.md

Write some initial documentation for property paths.
Not super happy with this, but I'm also not quite sure what else to document here.  Suggestions very welcome!

document property paths

---

changelog/pending/20240926--sdk-python--search-upwards-for-pyproject-toml-when-using-poetry.yaml
sdk/python/cmd/pulumi-language-python/main.go
sdk/python/toolchain/poetry.go
sdk/python/toolchain/toolchain.go
sdk/python/toolchain/toolchain_test.go
tests/integration/integration_python_acceptance_test.go
tests/integration/python/poetry-main-and-parent/Pulumi.yaml
tests/integration/python/poetry-main-and-parent/__pyproject.toml
tests/integration/python/poetry-main-and-parent/src/__main__.py
tests/integration/python/poetry-main-and-parent/src/poetry.toml
tests/integration/python/poetry-main-and-parent/src/pyproject.toml
tests/integration/python/poetry-main/Pulumi.yaml
tests/integration/python/poetry-main/poetry.toml
tests/integration/python/poetry-main/pyproject.toml
tests/integration/python/poetry-main/src/__main__.py
tests/integration/python/poetry-parent/poetry.toml
tests/integration/python/poetry-parent/pyproject.toml
tests/integration/python/poetry-parent/subfolder/Pulumi.yaml
tests/integration/python/poetry-parent/subfolder/__main__.py

Start searching in the program directory and walk upwards to find
pyproject.toml.
Fixes https://github.com/pulumi/pulumi/issues/17359

Search upwards for pyproject.toml when using Poetry

---

pkg/resource/deploy/snapshot.go
pkg/resource/deploy/snapshot_test.go

The `Snapshot.Prune` method was introduced in #17408 in order to remove dangling references from faulty state snapshots. In this commit we extend its capabilities, returning a list of the results that were pruned and/or rewritten. In doing so we enable callers (such as the futuer `state repair` command) to print out a summary of the changes affected by pruning if they wish.

Return pruned resources from `Snapshot.Prune`

---

README.md

Update README.md to add links to ESC

Update README.md to add links to ESC

---

pkg/resource/deploy/snapshot_test.go

We attempted to fix this flake with assert.ElementsMatch, however there is a nested list of `RemovedDependencies` that doesn’t have a stable order either.
Fixes https://github.com/pulumi/pulumi/issues/17476

Fix flake in TestSnapshotPrune_FixesDanglingReferences

---

changelog/pending/20241010--yaml--update-yaml-to-1-11-1.yaml
pkg/go.mod
pkg/go.sum
tests/go.mod
tests/go.sum

Update yaml to 1.11.1

---

docs/writing.md

So that when browsing the website folks can find where to send corrections.

Explain how to contribute to dev docs

---

changelog/pending/20241023--cli-display--colorize-selected-stack-when-listing.yaml
pkg/cmd/pulumi/stack_ls.go

colorize selected stack when listing

---

changelog/pending/20241029--yaml--update-yaml-to-1-11-2.yaml
pkg/go.mod
pkg/go.sum
tests/go.sum

Update yaml to 1.11.2

---

changelog/pending/20241018--sdk-python--fixes-13516-fix-valueerror-and-assertionerror-to-provide-better-debugging-information.yaml
sdk/python/lib/pulumi/runtime/resource.py
sdk/python/lib/pulumi/runtime/rpc.py

fix ValueError and AssertionError to provide better debugging information

Fixes #13516 - fix ValueError and AssertionError to provide better debugging information

---

README.md

1. Added UTM parameters to all links pointing to a pulumi.com page
2. Changed linked reference under "Welcome" section from "Pulumi ESC" to "Secrets Management"

Update README.md to add UTMs to links

---

pkg/backend/httpstate/token_source_test.go

A data race was detected in token_source_test.go. This fixes the issue by adding locking around the `response` variable.
Fixes #17903

Fix data race in token source test

---

cmd/pulumi-test-language/interface.go

This updates the conformance tests to use the list of packages used by the PCL program for the expected dependencies, rather than the list of provider plugins assigned for the test.
This fixes the TODO that we weren't correctly dealing with parameterized packages because the program wouldn't depend on the provider plugin package, but the parameterized package instead.

Use PCL packages to decide the expected program dependencies

---

pkg/codegen/schema/pulumi.json

Fixed a few glitches while working on https://github.com/pulumi/pulumi/pull/17955

Tiny fixes in pulumi.json descriptions

---

pkg/cmd/pulumi/deployment_settings_utils.go
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/new_acceptance_test.go
pkg/cmd/pulumi/new_test.go
pkg/cmd/pulumi/stack_init.go
pkg/cmd/pulumi/ui/survey.go
pkg/cmd/pulumi/up.go

This is another helper function that is used by a few commands. This commit moves it into the `ui` subpackage.

Break `promptForValue` out of `pulumi new`

---

tests/smoke_test.go

This adds an integration test for https://github.com/pulumi/pulumi/pull/12196 to ensure the right warning gets printed in a real world scenario.
This test is _go_ specific but the only language specific code it relies on is GetRequiredPlugins/Packages which is fully tested for all languages in conformance testing.

Add an integration test for the provider refresh warning

---

pkg/resource/autonaming/config.go
pkg/resource/autonaming/config_test.go

Founds the first bug in autonaming configuration... 
Here is my sample program for Azure Native:
```yaml
name: autonaming
description: Autonaming configuration example
runtime: yaml
config:
pulumi:autonaming:
value:
pattern: ${project}-${stack}-${name}
providers:
azure-native:
resources:
azure-native:storage:StorageAccount:
pattern: ${project}${stack}${name}${alphanum(6)}
resources:
rg:
type: azure-native:resources:ResourceGroup
sa:
type: azure-native:storage:StorageAccount
properties:
resourceGroupName: ${rg.name}
sku:
name: Standard_LRS
kind: StorageV2
```
Expected result: both resource group and storage account are named as specified by custom configuration.
Actual result: resource group is named according to our default policy, not user's configuration.
It starts working correctly if …

Refine autonaming config calculation on provider/resource level

---

tests/integration/integration_test.go

In preparation for removing the `ConfigFile` global from these commands, this change adds some integration test coverage for them.

Add tests for `config rm` and `config rm-all`

---

changelog/pending/20241212--engine--change-loader-server-to-use-package-load-v2-so-it-can-include-paramaterization.yaml

I missed this during review.  Adjust the changelog so it conforms with https://github.com/pulumi/pulumi/blob/master/CONTRIBUTING.md#changelog-messages.

fixup changelog style

---

sdk/nodejs/cmd/pulumi-language-nodejs/main_test.go

Fixes #17578 
(hopefully, eventually)

Added new contents of package.json to see how our tests react

---

.github/workflows/ci-run-test.yml
changelog/pending/20241227--sdk-python--fix-listpackages-when-using-uv.yaml
sdk/python/toolchain/toolchain_test.go
sdk/python/toolchain/uv.go

ListPackages was not respecting the `transitive=false` flag when using the `uv` toolchain.

Fix ListPackages when using uv

---

sdk/go/internal/types.go
sdk/go/pulumi/types.go
sdk/go/pulumi/types_test.go

Fix for https://github.com/pulumi/pulumi/pull/17885

DeferredOutput

---

pkg/codegen/hcl2/README.md

Minor updates after reading the docs

Update hcl2 Readme

---

sdk/python/cmd/pulumi-language-python/main.go

When a `command.Run()` fails, it can return an `ExitError` containing information about the failed process execution. By default, the string representation of an `ExitError` only prints the exit code. The `ExitError` type, however, captures a subset of the failed process' standard error, which can be very useful when debugging why things went wrong. This commit modifies the Python language host so that two places where it runs subcommands (spawning type checkers such as `pyright`, and booting shimless plugins) now include standard error when an `ExitError` is detected. This should help us fix e.g. failures in conformance tests or the like.

Include standard error for failed Python commands

---

pkg/codegen/schema/loader.go
pkg/codegen/schema/loader_test.go
pkg/importer/hcl2.go
pkg/importer/hcl2_test.go

In #18039 we added the ability to generate code for imports involving parameterized providers. In doing so, we cleaned up a long-standing TODO around checking the versions of loaded providers against those in the state being imported to. While this stricter check brought with it a higher degree of correctness, it broke a number of workflows, such as attaching an existing provider instance (which may have a different version) to an import operation. This happens in some provider CI workflows and tests, where we want to test an older state file's compatibility with the new (to-be-released) provider version. In such cases, the state reports vN and the load returns vN+0.0.1 or the like. This change restores the old behaviour by introducing explicit errors to identify when mismatches occur and …

Allow provider version mismatches when `import`ing resources

---

.github/workflows/ci-build-sdks.yml
.github/workflows/ci-dev-release.yml
.github/workflows/ci-lint.yml
.github/workflows/ci-run-test.yml
.github/workflows/release.yml

Upgrade to the latest version of astral-sh/setup-uv.

Upgrade astral-sh/setup-uv to v5

---

tests/smoke_test.go

We had TestDestroyUpgradeWarningParameterized to test this warning for parameterized local packages, but nothing to test against normal packages.

Add non-parameterised smoke test for the destroy upgrade warning

---

CONTRIBUTING.md

I stumbled over this when trying to fix something in Go codegen.

Add language host binary Make instructions to CONTRIBUTING.md

---

changelog/pending/20250131--sdk-python--add-infrastructure-to-bootstrap-providers-from-component-resources.yaml
changelog/pending/20250131--sdk-python--experimental-analyze-componentresource-properties.yaml
sdk/python/lib/pulumi/provider/experimental/analyzer.py
sdk/python/lib/test/provider/experimental/test_analyzer.py

Analyze the type annotations of ComponentResources to derive a schema.
Ref https://github.com/pulumi/pulumi/issues/18366

[Experimental] Analyze ComponentResource properties

---

proto/.checksum.txt
proto/pulumi/resource.proto
sdk/nodejs/proto/resource_grpc_pb.js
sdk/proto/go/resource.pb.go
sdk/proto/go/resource_grpc.pb.go
sdk/python/lib/pulumi/runtime/proto/resource_pb2.pyi
sdk/python/lib/pulumi/runtime/proto/resource_pb2_grpc.py
sdk/python/lib/pulumi/runtime/proto/resource_pb2_grpc.pyi

Connect the dots on packageRef.

chore: clarifying packageRef use in proto docs

---

changelog/pending/20250206--sdk-python--experimental-components-support-array-types-in-component-schema-inference.yaml
sdk/python/lib/pulumi/provider/experimental/analyzer.py
sdk/python/lib/pulumi/provider/experimental/component.py
sdk/python/lib/pulumi/provider/experimental/schema.py
sdk/python/lib/test/provider/experimental/test_analyzer.py
tests/integration/component_provider/python/component-provider-host/Pulumi.yaml
tests/integration/component_provider/python/component-provider-host/provider/component.py
tests/integration/integration_python_test.go

Fixes https://github.com/pulumi/pulumi/issues/18421

[Experimental/Components] Support array types in component schema inference

---

changelog/pending/20250206--sdk-python--experimental-components-support-dict-types-in-component-schema-inference.yaml
sdk/python/lib/pulumi/provider/experimental/analyzer.py
sdk/python/lib/pulumi/provider/experimental/component.py
sdk/python/lib/pulumi/provider/experimental/schema.py
sdk/python/lib/test/provider/experimental/test_analyzer.py
tests/integration/component_provider/python/component-provider-host/Pulumi.yaml
tests/integration/component_provider/python/component-provider-host/provider/component.py
tests/integration/integration_python_test.go

Fixes https://github.com/pulumi/pulumi/issues/18422

[Experimental/Components] Support dict types in component schema inference

---

.github/workflows/ci-run-test.yml
scripts/go-test.py

Report test results to codecov.
For example this PR's results can be seen here https://app.codecov.io/gh/pulumi/pulumi/tests/julienp%2Fcodecov-test-results

Upload test results to codecov

---

changelog/pending/20250207--sdk-python--experimental-components-throw-an-error-when-encountring-resource-references.yaml
sdk/python/lib/pulumi/provider/experimental/analyzer.py
sdk/python/lib/test/provider/experimental/test_analyzer.py

https://github.com/pulumi/pulumi/issues/18484 tracks the work to properly handle these.

[Experimental/Components] Throw an error when encountring resource references

---

sdk/go/common/resource/properties.go

Fix IsAsset and IsArchive doc comment

---

README.md

updated links to not redirect (redirect is stripping UTMs), standardized UTMs

Readme updates to use links that don't redirect and standardize UTMs

---

sdk/python/lib/pulumi/provider/experimental/ComponentProvider.md

Closes https://github.com/pulumi/pulumi/issues/18467

[Experimental/Components] Add a tutorial on writing a component provider

---

changelog/pending/20250210--sdk-python--experimental-components-handle-assets-and-archives.yaml
sdk/python/lib/pulumi/provider/experimental/analyzer.py
sdk/python/lib/pulumi/provider/experimental/provider.py
sdk/python/lib/test/provider/experimental/test_analyzer.py
tests/integration/component_provider/python/component-provider-host/.gitignore
tests/integration/component_provider/python/component-provider-host/nodejs/Pulumi.yaml
tests/integration/component_provider/python/component-provider-host/nodejs/index.ts
tests/integration/component_provider/python/component-provider-host/nodejs/package.json
tests/integration/component_provider/python/component-provider-host/provider/component.py
tests/integration/component_provider/python/component-provider-host/python/Pulumi.yaml
tests/integration/component_provider/python/component-provider-host/python/__main__.py
tests/integration/component_provider/python/component-provider-host/yaml/Pulumi.yaml
tests/integration/component_provider/python/recursive-types/.gitignore
tests/integration/component_provider/python/recursive-types/yaml/Pulumi.yaml
tests/integration/integration_python_test.go

Fixes https://github.com/pulumi/pulumi/issues/18508
Ref https://github.com/pulumi/pulumi/issues/18458

[Experimental/Components] Handle Assets and Archives

---

changelog/pending/20250211--sdk-python--experimental-components-detect-more-map-and-list-types.yaml
sdk/python/lib/pulumi/provider/experimental/analyzer.py
sdk/python/lib/test/provider/experimental/test_analyzer.py

Support a wider range of array and map types.
Fixes https://github.com/pulumi/pulumi/issues/18530

[Experimental/Components] Detect more map and array types

---

sdk/python/lib/pulumi/provider/experimental/ComponentProvider.md

3.150.0 ships with enough of the implementation for us to use here

update python component tutorial

---

tests/integration/main_test.go
tests/main_test.go
tests/testutil/test_main_util.go

Factor this method out since it's used in two places.  Also document it while we're at it.
Thanks @Frassle for this suggestion!

factor out function for setting up binary rebuilding

---

changelog/pending/20250213--sdk-nodejs--experimental-components-infer-simple-inputs-and-optionality.yaml
sdk/nodejs/.eslintrc.js
sdk/nodejs/Makefile
sdk/nodejs/provider/experimental/analyzer.ts
sdk/nodejs/provider/experimental/schema.ts
sdk/nodejs/tests/provider/experimental/analyzer.spec.ts
sdk/nodejs/tests/provider/experimental/testdata/bad-args/index.ts
sdk/nodejs/tests/provider/experimental/testdata/optional-types/index.ts
sdk/nodejs/tests/provider/experimental/testdata/package.json
sdk/nodejs/tests/provider/experimental/testdata/simple-types/index.ts
sdk/nodejs/tsconfig.json
tests/integration/component_provider/nodejs/component-provider-host/provider/component.ts
tests/integration/component_provider/nodejs/component-provider-host/python/__main__.py
tests/integration/component_provider/nodejs/component-provider-host/yaml/Pulumi.yaml
tests/integration/integration_nodejs_test.go

Analyze the Component inputs and outputs and infer simple types like string, number
and boolean. Also infers if the types are optional.

[Experimental/Components] Infer simple inputs/outputs and optionality

---

changelog/pending/20250214--sdk-nodejs--experimental-components-infer-input-types.yaml
sdk/nodejs/provider/experimental/analyzer.ts
sdk/nodejs/tests/provider/experimental/analyzer.spec.ts
sdk/nodejs/tests/provider/experimental/testdata/input-types/index.ts
tests/integration/component_provider/nodejs/component-provider-host/python/__main__.py
tests/integration/component_provider/nodejs/component-provider-host/yaml/Pulumi.yaml
tests/integration/integration_nodejs_test.go

[Experimental/Components] Infer input types

---

pkg/resource/deploy/deployment_executor.go
pkg/resource/deploy/step.go

Simple little improvement to remove an unused channel.

Remove unused done channel from RefreshStep

---

changelog/pending/20250214--sdk-nodejs--experimental-components-handle-complextype.yaml
sdk/nodejs/provider/experimental/analyzer.ts
sdk/nodejs/provider/experimental/provider.ts
sdk/nodejs/provider/experimental/schema.ts
sdk/nodejs/tests/provider/experimental/analyzer.spec.ts
sdk/nodejs/tests/provider/experimental/testdata/complex-types/index.ts
sdk/nodejs/tests/provider/experimental/testdata/mutually-recursive-types/index.ts
sdk/nodejs/tests/provider/experimental/testdata/recursive-complex-types/index.ts
tests/integration/component_provider/nodejs/component-provider-host/provider/component.ts
tests/integration/component_provider/nodejs/component-provider-host/python/__main__.py
tests/integration/component_provider/nodejs/component-provider-host/yaml/Pulumi.yaml
tests/integration/integration_nodejs_test.go

Parse complex types, including nested complex types and recursive types.

[Experimental/Components]: Handle ComplexType

---

docs/contributing/development.md

Just one extra note that I had to run `mise trust` to make everything happy.

Update `mise` quickstart instructions

---

sdk/nodejs/provider/experimental/analyzer.ts
sdk/nodejs/tests/provider/experimental/analyzer.spec.ts
sdk/nodejs/tests/provider/experimental/testdata/map-types/index.ts

Handle maps and records in typescript.

[Experimental/Components]: Handle maps

---

sdk/nodejs/provider/experimental/analyzer.ts

These quotes are unbalanced, leading to a slightly ugly error message. Fix that.

[Experimental/Components]: Fix up unbalanced quotes

---

pkg/resource/deploy/source.go
pkg/resource/deploy/source_error.go
pkg/resource/deploy/source_error_test.go
pkg/resource/deploy/source_eval.go
pkg/resource/deploy/source_eval_test.go
pkg/resource/deploy/source_null.go

Remove Info from Source

---

sdk/nodejs/provider/experimental/analyzer.ts

Removing a couple of unused variables the LSP warned me about, and fix the spelling of analyze to be consistent throughout.

[Experimental/Components]: minor typescript cleanups

---

sdk/nodejs/provider/experimental/ComponentProvider.md

Add a guide for authoring typescript components.  Based on the python guide.

[Experimental/Components]: add typescript guide

---

changelog/pending/20250227--sdkgen-dotnet--update-pulumi-dotnet-to-v3-75-2.yaml
pkg/codegen/testing/test/helpers.go
scripts/get-language-providers.sh
tests/testdata/codegen/transpiled_examples/cue-random-pp/dotnet/dotnet.csproj
tests/testdata/codegen/transpiled_examples/getting-started-pp/dotnet/dotnet.csproj
tests/testdata/codegen/transpiled_examples/kubernetes-pp/dotnet/dotnet.csproj
tests/testdata/codegen/transpiled_examples/random-pp/dotnet/dotnet.csproj

This updates dotnet codegen to 3.75.2 to revert the net8 updates.

Update to dotnet v3.75.2

---

.github/workflows/ci-build-sdks.yml
.github/workflows/ci-run-test.yml
.github/workflows/release.yml
pkg/codegen/testing/test/dotnet.go
sdk/nodejs/tests/automation/data/testproj_dotnet/TestProj.csproj
tests/testdata/codegen/transpiled_examples/cue-random-pp/dotnet/dotnet.csproj
tests/testdata/codegen/transpiled_examples/getting-started-pp/dotnet/dotnet.csproj
tests/testdata/codegen/transpiled_examples/kubernetes-pp/dotnet/dotnet.csproj
tests/testdata/codegen/transpiled_examples/random-pp/dotnet/dotnet.csproj

The latest dotnet SDK only builds with net8.0 so we need to update to that here.

Update to net8

---

pkg/codegen/dotnet/templates.go

Leave a comment here so that we don't over eagerly bump this again.

Add comment about TargetFramework

---

Makefile

Both `make build` and `make install` install the `pulumi` binary to a global location (using `go install` under the hood). This PR adds a `bin/pulumi` target that will build a local copy of Pulumi. It also changes the implementation of `make build` and `make install` to use the copy generated with `make bin/pulumi`.
Since I often run `make build install`, this cuts build time for me in half.

De-duplicate the build for `make build` and `make test`

---

pkg/backend/backend.go
pkg/backend/diy/backend.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/client/api.go
pkg/backend/httpstate/client/api_endpoints.go
pkg/backend/httpstate/client/client.go
pkg/backend/httpstate/client/client_test.go
pkg/backend/mock.go
sdk/go/common/apitype/templates.go
sdk/go/common/workspace/project.go

Part of https://github.com/pulumi/pulumi/pull/18627
In service of https://github.com/pulumi/pulumi-service/issues/25732.

Add the ability to list org templates in via the service backend

---

pkg/codegen/pcl/rewrite_apply_test.go

Just to be sure that conditionals do re-write to apply calls, add a unit test for it.

Test conditionals in TestApplyRewriter

---

pkg/resource/deploy/import.go

This code got duplicated in https://github.com/pulumi/pulumi/pull/14467. The lines above are exactly the same as the deleted lines.

Delete duplicate code

---

cmd/pulumi-test-language/l2_resource_asset_test.go
cmd/pulumi-test-language/tests/l2_resource_asset_archive.go
cmd/pulumi-test-language/tests/testdata/l2-resource-asset-archive/subdir/main.pp
sdk/go/pulumi-language-go/testdata/projects/l2-resource-asset-archive/subdir/main.go
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsc/projects/l2-resource-asset-archive/subdir/index.ts
sdk/nodejs/cmd/pulumi-language-nodejs/testdata/tsnode/projects/l2-resource-asset-archive/subdir/index.ts
sdk/python/cmd/pulumi-language-python/testdata/classes/projects/l2-resource-asset-archive/subdir/__main__.py
sdk/python/cmd/pulumi-language-python/testdata/setuppy/projects/l2-resource-asset-archive/subdir/__main__.py
sdk/python/cmd/pulumi-language-python/testdata/toml/projects/l2-resource-asset-archive/subdir/__main__.py

Fix master after https://github.com/pulumi/pulumi/pull/18820 removed the test file the tests depended on.

Fix conformance test to pin raw data content

---

pkg/backend/display/progress.go
pkg/backend/httpstate/backend.go

make function comment match function name

chore: make function comment match function name

---

changelog/pending/20250321--cli-package--allow-overriding-name-and-namespace-of-plugins-in-pulumiplugin-yaml.yaml
pkg/cmd/pulumi/packagecmd/project_sdk_link.go
sdk/go/common/workspace/project.go
tests/integration/component_test/python-component/PulumiPlugin.yaml
tests/integration/component_test/python-component/__main__.py
tests/integration/component_test/python-component/component.py
tests/integration/component_test/python-component/requirements.txt
tests/integration/component_test/ts-consumer/.gitignore
tests/integration/component_test/ts-consumer/Pulumi.yaml
tests/integration/component_test/ts-consumer/index.ts
tests/integration/component_test/ts-consumer/package-lock.json
tests/integration/component_test/ts-consumer/package.json
tests/integration/component_test/ts-consumer/tsconfig.json
tests/integration/integration_test.go

If there is a name or namespace set in the PulumiPlugin.yaml, we always want to override it from there. Do so during `package add`.

package add: override name and namespace from PulumiPlugin.yaml

---

changelog/pending/20250324--cli-package--update-package-add-command-format-string.yaml
pkg/cmd/pulumi/packagecmd/package_add.go
sdk/nodejs/provider/experimental/ComponentProvider.md

Nothing too exciting here - I recently tried to go through the process of [creating a component](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/provider/experimental/ComponentProvider.md) and ran into a couple little issues, mostly through misunderstanding. This PR updates the docs to add notes that would've helped.

Documentation updates for custom components

---

sdk/python/lib/test/provider/experimental/test_analyzer.py

[load_module](https://docs.python.org/3/library/importlib.html#importlib.abc.Loader.load_module) is deprecated and will be removed in 3.15.
Note this is only used for test setup.

Remove usage of deprecated SourceFileLoader.load_module

---

docs/requirements.txt

Address https://github.com/pulumi/pulumi/security/dependabot/1707
This is used for building the developer docs only.

Update Jinja in docs

---

changelog/pending/20250408--yaml--upgrade-yaml-to-1-15-2.yaml
scripts/get-language-providers.sh

To pull in https://github.com/pulumi/pulumi-yaml/pull/771.

upgrade to latest yaml release

---

sdk/python/lib/test/provider/experimental/test_provider.py

We already do this, and it is partially covered by an integration test. This PR adds a unittest that ensures we properly map from snake_case to camelCase, even in nested complex types.
Closes https://github.com/pulumi/pulumi/issues/18882

Test that component outputs are mapped from snake_case to camelCase

---

sdk/python/.gitignore
sdk/python/cmd/pulumi-language-python-exec
sdk/python/pyproject.toml

This file is gitignored at the top level (apparently for goreleaser?),
but changes are tracked in git because the file was intentionally added
to git at some point. However tools like ruff don't understand that
distinction and ignore the file (because of the .gitignore). Un-ignore
the file at the sdk/python level, add it to the ruff includes and format
it.

Format cmd/pulumi-language-python-exec

---

pkg/backend/display/progress_test.go

Fixes: https://github.com/pulumi/pulumi/issues/19164
- Avoid running the test data ingestion in Parallel by creating a buffered chan instead

Fixes a DATA RACE flake in the TestCaptureProgressEvents tests

---

sdk/nodejs/provider/experimental/analyzer.ts

No functional changes, just moving code around to reduce the duplication.

[components/typescript] Refactor and simplify analyzeType method

---

changelog/pending/20250411--cli-new--dont-require-to-be-logged-in-to-retrieve-templates.yaml
pkg/backend/backend.go
pkg/backend/backenderr/backenderr.go
pkg/backend/diy/backend.go
pkg/backend/errors/errors.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/backend_test.go
pkg/backend/httpstate/client/api.go
pkg/cmd/pulumi/newcmd/config.go
pkg/cmd/pulumi/newcmd/new_ai_test.go
pkg/cmd/pulumi/newcmd/new_test.go
pkg/cmd/pulumi/stack/io.go
pkg/cmd/pulumi/templates/org.go
pkg/cmd/pulumi/templates/templates_test.go
pkg/util/testutil/mockbackend.go

Don't attempt to retrieve organization level templates when we are not
logged in.
Fixes https://github.com/pulumi/pulumi/issues/19073
Fixes https://github.com/pulumi/pulumi/issues/19180

Don't require to be logged in to retrieve templates

---

pkg/cmd/pulumi/packagecmd/package_publish_test.go
pkg/cmd/pulumi/stack/stack_change_secrets_provider_test.go
pkg/cmd/pulumi/stack/stack_ls_test.go
pkg/cmd/pulumi/stack/stack_test.go

Follow up to https://github.com/pulumi/pulumi/pull/19196, where the helper was added to testutils.

Use shared MockBackendInstance test helper

---

pkg/engine/lifecycletest/analyzer_test.go

I couldn't see this tested anywhere in pu/pu so adding a little bit to the lifecycle test to assert what config is sent to analyzer plugins.

Test analyzer config

---

sdk/go/common/resource/property_compatibility.go

Stacked on top of #19257.
This PR exposes two new functions from the `resources` package to make converting to and from `property.Map`s easier: `resource.ToResourcePropertyMap` and `resource.FromResourcePropertyMap`. These are convenience functions to obviate the need for casts and value conversions:
```go
ToResourcePropertyValue(property.New(m)).ObjectValue()
```
```go
FromResourcePropertyValue(resource.NewProperty(m)).AsMap()
```

Expose `resource.{To,From}ResourcePropertyMap`

---

pkg/codegen/dotnet/gen.go
pkg/codegen/dotnet/gen_program.go
pkg/codegen/go/gen_program.go
pkg/codegen/pcl/binder_resource.go
pkg/codegen/pcl/utilities.go
pkg/codegen/python/gen_program.go
pkg/codegen/utilities.go
sdk/go/common/util/maputil/sorted.go

This function is used in a couple of places already, and as part of https://github.com/pulumi/pulumi/issues/19097 I'm planning to introduce another. Factor that one copy out, and only keep that one.

factor out SortedKeys function into maputil

---

changelog/pending/20250424--cli--add-pulumi_run_program-environment-variable-to-globally-set-run-program.yaml
pkg/cmd/pulumi/operations/destroy.go
pkg/cmd/pulumi/operations/refresh.go
sdk/go/common/env/env.go

Fixes https://github.com/pulumi/pulumi/issues/19292

Add RUN_PROGRAM envvar to set --run-program

---

pkg/codegen/schema/loader_test.go
pkg/codegen/schema/package_reference.go

Stacking on top of <https://github.com/pulumi/pulumi/pull/19317>, this allows partially loaded packages to access language definitions.

Lazily import language blocks from `schema.PackageReference`s

---

changelog/pending/20250430--sdk-yaml--update-pulumi-yaml-to-v1-18-0.yaml
scripts/get-language-providers.sh

Hot of the press: https://github.com/pulumi/pulumi-yaml/releases/tag/v1.18.0

upgrade pulumi-yaml to 1.18.0

---

sdk/go/common/testing/environment.go

1. This did not resolve the binary path correctly when using mise as the root directory is changed.
2. Move to the `SetupCommandIn` method so it's used for all command methods (e.g. when expecting failure too)
3. Only override the command if the current command is for `pulumi`. Resolve all other commands with the system default approach.

Fix UseLocalPulumiBuild

---

sdk/go/property/README.md
sdk/go/property/values.go

Add documentation for the `property` package

---

tests/integration/resource_refs_get_resource/python/__main__.py

This test is racy, the same way the Node and Go versions were.  We fixed Node and Go in https://github.com/pulumi/pulumi/pull/16903 and https://github.com/pulumi/pulumi/pull/16897 respectively.  Apply the same fix to Python to unflake the test.
Fixes https://github.com/pulumi/pulumi/issues/19485

fix flaky TestResourceRefsGetResourcePython test

---

developer-docs/go.sum
sdk/go/common/slice/slice.go
sdk/go/common/slice/slice_test.go

And add explicit tests for the package.

Remove unnecessary line from `slice.MapError`

---

sdk/python/lib/pulumi/provider/experimental/analyzer.py

No functional changes other than a slight tweak to some error messages. This extracts the function to retrieve dependency information from the resource handling so that we can re-use it for external enums.

Refactor dependency information retrieval

---

pkg/codegen/docs_integration_test.go

Following up on https://github.com/pulumi/pulumi/pull/19396#issue-3034061809
Add a benchmark for https://github.com/pulumi/pulumi/pull/19313

Add a benchmark for `GetPropertyNames`

---

docs/architecture/testing/integration.md

Assuming we land https://github.com/pulumi/pulumi/pull/19573

Update integration test docs

---

pkg/codegen/testing/test/helpers.go
scripts/get-language-providers.sh

https://github.com/pulumi/pulumi-dotnet/pull/617

Update the .NET SDK to v3.82.1

---

pkg/engine/lifecycletest/fuzzing/plan.go

Given that we've seen issues like https://github.com/pulumi/pulumi/issues/19879 that depend on --refresh being set, add that to the fuzzing dimensions.

Add refresh to fuzzing

---

pkg/engine/lifecycletest/fuzzing/program.go

This change fixes the fuzzing tests following some recent fixes elsewhere in the engine (e.g. #19837). It also fixes a bug in scenario generation where provider references weren't being rewritten following a parenting change (e.g. reparenting an explicit provider). Hopefully this means they are in a position where we can look at running them in CI.

Fix up fuzz tests

---

pkg/engine/lifecycletest/pulumi_test.go

Fixes https://github.com/pulumi/pulumi/issues/19983

Fix race in TestConstructHangsAfterRegisterResourceFailure

---

pkg/engine/lifecycletest/delete_before_replace_test.go

Fixes https://github.com/pulumi/pulumi/issues/20042
Rather than relying on bool flags being set in the right order we now actually wait on `WaitGroups`. This does mean if we break this test it will probably manifest as a timeout, but currently these wait groups are guarnteed to be triggered in the right order, because that's what they're testing for.

Fix flaky TestDBRParallel

---

sdk/nodejs/yarn.lock

Fixes https://github.com/pulumi/pulumi/security/dependabot/2054

Upgrade indirect brace-expansion@2.0.2 dep

---

pkg/engine/lifecycletest/delete_before_replace_test.go

Race detector can't see the synchronisation between diffs in this test so thinks this is a write/write race to set `diffCalled`.

Fix race in test

---

docs/requirements.txt

Fixes https://github.com/pulumi/pulumi/security/dependabot/2064

Update docs deps

---

sdk/nodejs/Makefile
sdk/python/Makefile

Copy the shims `pulumi-resource-pulumi-{nodejs,python}` and `pulumi-analyzer-policy{,-python}` to `$REPO/bin` so we have a complete installation in that folder.

Copy shims to bin

---

pkg/cmd/pulumi/newcmd/io.go

Thanks @danielrbradley for pairing with me :)

Update error message on non-empty directories.

---

pkg/engine/lifecycletest/refresh_test.go

This test was pretty useless because it looped over and asserted properties of the resources, but didn't assert that the resources _were_ in the list to assert against. 
This fixes the test to return ID so refresh doesn't just delete the resources. I'm pretty sure there's more issues here if we turn on `WithGrpc` but this is a start.

Fix TestRefreshInitFailure to not just delete all the resources

---

tests/integration/integration_test.go
tests/stack/stack_test.go

See https://github.com/pulumi/pulumi-service/issues/31668

Run the tests for stacks using the service sequentially

---

pkg/cmd/pulumi/newcmd/new_acceptance_test.go
pkg/cmd/pulumi/newcmd/new_test.go
tests/integration/integration_test.go
tests/stack/stack_test.go

Ref https://github.com/pulumi/pulumi/issues/20410
Ref https://github.com/pulumi/pulumi-service/issues/31668

Skip stack init/rename tests

---

pkg/backend/display/object_diff_test.go

Add some tests before changing the behaviour for https://github.com/pulumi/pulumi/issues/2909 and fixing https://github.com/pulumi/pulumi/issues/20416

Add some tests for the stack output display during `pulumi up`

---

changelog/pending/20250828--cli-new--fail-when-running-wiht-language-without-ai-in-non-interactive-mode.yaml
pkg/cmd/pulumi/newcmd/new.go
pkg/cmd/pulumi/newcmd/new_acceptance_test.go
pkg/cmd/pulumi/newcmd/new_ai.go

Fixes https://github.com/pulumi/pulumi/issues/20320

Fail when running with --language without --ai in non-interactive mode

---

sdk/go/common/resource/plugin/analyzer_plugin.go

We had to have our own marshaling code to convert protobuf Structs to/from Go maps because there wasn't anything built-in to do this when this code was originally written. But since then, built-in helpers were added to google.golang.org/protobuf with https://go-review.googlesource.com/c/protobuf/+/225298. This change switches over to use the built-in functionality.

Use built-in protobuf Struct / Go map marshaling code

---

docs/debugging/README.md
docs/debugging/performance.md

Add some docs on debugging performance issues.

Add developer docs on using `--tracing` and `--profiling`

---

changelog/pending/20250926--sdk-yaml--bump-pulumi-yaml-to-1-23-2.yaml
scripts/get-language-providers.sh

https://github.com/pulumi/pulumi-yaml/releases/tag/v1.23.2

Bump pulumi-yaml to 1.23.2
