pulumi/pulumi

CHANGELOG_PENDING.md
sdk/go/pulumi/resource.go
sdk/go/pulumi/resource_test.go

Allows encapsulation of multiple options to appear as a single option. Providing some useful flexibility for callers of the code.
resolves #9455

feat(resource): ✨  Add Composite ResourceOption

---

sdk/go/pulumi/context.go
sdk/go/pulumi/resource.go
sdk/go/pulumi/run_test.go
sdk/go/pulumi/types.go

This enables a Pulumi program in Go that directly constructs resources by type tokens to get access to the full property map, including querying the known-ness and secret-ness of properties without needing to marshal them into an appropriately tagged data structure.
For example, in a Go program where we wish to dynamically access properties of a resource, we might perform this step while evaluating keys at each level:
```go
rawOutputs := x.GetRawOutputs(ctx.ctx)
return evaluateAccessF(rawOutputs, accessors)
```
Is there a better way to plumb this API, and are we satisfied with the naming?

gosdk: add API to retrieve raw property map of outputs

---

pkg/cmd/pulumi/convert.go

Ensures that if a user types `--language csharp` we get the intended behavior. We may want to refine this to only permit `csharp`, to be determined.

convert: add language aliases for --language arg

---

pkg/codegen/dotnet/gen_program.go
pkg/codegen/go/gen_program.go
pkg/codegen/nodejs/gen_program.go
pkg/codegen/pcl/binder.go
pkg/codegen/pcl/binder_nodes.go
pkg/codegen/pcl/binder_resource.go
pkg/codegen/pcl/diagnostics.go
pkg/codegen/pcl/local.go
pkg/codegen/pcl/output.go
pkg/codegen/pcl/program.go
pkg/codegen/pcl/resource.go
pkg/codegen/python/gen_program.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/logical-name-pp/dotnet/logical-name.cs
pkg/codegen/testing/test/testdata/logical-name-pp/go/logical-name.go
pkg/codegen/testing/test/testdata/logical-name-pp/logical-name.pp
pkg/codegen/testing/test/testdata/logical-name-pp/nodejs/logical-name.ts
pkg/codegen/testing/test/testdata/logical-name-pp/python/logical-name.py

Lexical names, or variable/declaration names, are invisible to the Pulumi API at runtime. They exist for the programmer to give useful names to objects to reason about their program. Modifying lexical names to fit the target language does not change the [denotational semantics](https://en.wikibooks.org/wiki/Haskell/Denotational_semantics) of the program, e.g.: renaming the _variable name_ `myBucket` to `my_bucket` in the example below results in the same behavior on `pulumi up`. 
```ts
const myBucket = new aws.s3.Bucket("my-bucket", {website: {
//    ~~~~~~~~ lexical name        ~~~~~~~~~~~ unique name
indexDocument: "index.html",
}});
```
By contrast, the first argument to a resource constructor and the argument to name a stack output is meaningful to the Pulumi API and can affect the …

codegen: preserve externally visible names of a resources and outputs

---

sdk/go/pulumi/types.go

This resolves an issue where running `pulumi destroy` lost information on sequencing the deletes when using this API.

Add deps to unsafe unknown outputs API

---

CHANGELOG_PENDING.md
pkg/backend/filestate/backend_test.go
pkg/backend/filestate/state.go

src and dst arguments to bucket.Copy were the wrong way round.

Fix backupTarget

---

CHANGELOG_PENDING.md
pkg/backend/display/diff.go
pkg/backend/display/object_diff.go
pkg/backend/display/progress.go
pkg/backend/display/testdata/template-body.json.stdout.txt
pkg/backend/display/testdata/up-2.json.stdout.txt
pkg/backend/display/testdata/up-3.json.stdout.txt
pkg/backend/display/testdata/up-4.json.stdout.txt
pkg/backend/display/testdata/up.json.stdout.txt

Reuse the support for decoding JSON/YAML strings into objects to display
such values as objects during create, same, and delete operations (we
already do this for updates).
These changes also unexport a number of methods that should be internal
to the display package.

[cli] Render JSON/YAML encoded values as objects.

---

pkg/codegen/nodejs/gen_program.go
pkg/codegen/nodejs/gen_program_expressions.go

Generate module names correctly (same way as `resourceTypeName`). 
I was unable to create an independent test for this (copying the offending PCL from `azure-native` does not reproduce the bug), but have verified that the fix works by running the failing `azure-native` test with a `replace` statement pointing to my local `pulumi/pulumi`. I propose we merge this now to unblock `azure-native` and add a repro test as followup. 
Fixes #9485

Use exising module name infrastrucure

---

CHANGELOG_PENDING.md

Clear CHANGELOG_PENDING.md post v3.31.0 release

---

CHANGELOG_PENDING.md
pkg/backend/display/object_diff.go
sdk/go/common/resource/properties.go

YAML supports mappings with arbitrarily-typed keys (unlike JSON, which
only supports string keys). These mappings decode into
`map[interface{}]interface{}` values, which are not supported by
`resource.NewPropertyValue`. These changes add a function to the display
logic that translates `map[interface{}]interface{}` values decoded from
YAML to `map[string]interface{}` values iff the keys are strings or
numeric values.
Fixes https://github.com/pulumi/pulumi/issues/9502.

[diff] Handle YAML maps with numeric keys.

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/util.go

Fixes an issue in pulumi new where if you tried to give a stack name of "org/stack" and had a default org set it would result in a stack name of "defaultOrg/org/stack" and then complain your org didn't match your project.

Fix when we add default org to stack name

---

tests/integration/integration_nodejs_test.go

This test was checking that we could get a secret provider when setting PULUMI_CONFIG_PASSPHRASE, but it set it to the empty string! That's now treated the same as not setting the variable so the test started failing.

Fix works-when-passphrase-set test

---

CHANGELOG_PENDING.md
pkg/engine/lifeycletest/pulumi_test.go
pkg/engine/plugins.go

Fixes https://github.com/pulumi/pulumi-yaml/issues/188

Try to get latest version for plugins when installing

---

CHANGELOG_PENDING.md
pkg/secrets/passphrase/manager.go
pkg/secrets/passphrase/manager_test.go

Fixes https://github.com/pulumi/pulumi/issues/9539

Fix handling of PULUMI_CONFIG_PASSPHRASE_FILE

---

CHANGELOG_PENDING.md
pkg/backend/display/progress.go

[Couple of community members](https://pulumi-community.slack.com/archives/C84L4E3N1/p1651678078066689) have seen an assert panic around here:
```
panic: fatal: An assertion has failed: action must be non empty
goroutine 2009 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
/private/tmp/pulumi-20220504-79959-1budjvw/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0x0?, {0x1053aa67e?, 0x140010182d0?}, {0x0?, 0x10537c4e7?, 0x3?})
/private/tmp/pulumi-20220504-79959-1budjvw/sdk/go/common/util/contract/assert.go:33 +0xe4
github.com/pulumi/pulumi/pkg/v3/backend/display.makeActionProgress({0x106864480, 0x1}, {0x0, 0x0})
/private/tmp/pulumi-20220504-79959-1budjvw/pkg/backend/display/progress.go:59 +0xa8 …
```

Don't try to display empty rows

---

Makefile
scripts/brew.sh
scripts/get-language-providers.sh

Fixes #9538
How I tested this:
https://github.com/t0yv0/pulumi has essentially the same change
https://github.com/t0yv0/homebrew-tap has a Formula that's derived from https://github.com/Homebrew/homebrew-core/blob/master/Formula/pulumi.rb which we're trying to make work, but disables checksums and redirects source to t0yv0/pulumi
Then one can test with:
`anton@Antons-MacBook-Pro> brew install t0yv0/tap/pulumi2`
This executes the modified Formula against this change, and you get 
```
which pulumi-language-java
which pulumi-language-yaml
```
Note that I removed the reliance on `gh` CLI on concerns that the environments where the official Brew formula runs do not have it installed. Assume curl instead. Note that computing github release paths in curl is not pretty, and if `gh release …

Modify make brew to include Java and YAML

---

pkg/codegen/docs/templates/function.tmpl
pkg/codegen/testing/test/testdata/external-resource-schema/docs/argfunction/_index.md
pkg/codegen/testing/test/testdata/other-owned/docs/argfunction/_index.md
pkg/codegen/testing/test/testdata/other-owned/docs/overlayfunction/_index.md
pkg/codegen/testing/test/testdata/output-funcs-edgeorder/docs/listconfigurations/_index.md
pkg/codegen/testing/test/testdata/output-funcs-edgeorder/docs/listproductfamilies/_index.md
pkg/codegen/testing/test/testdata/output-funcs-tfbridge20/docs/getamiids/_index.md
pkg/codegen/testing/test/testdata/output-funcs-tfbridge20/docs/liststorageaccountkeys/_index.md
pkg/codegen/testing/test/testdata/output-funcs/docs/funcwithalloptionalinputs/_index.md
pkg/codegen/testing/test/testdata/output-funcs/docs/funcwithconstinput/_index.md
pkg/codegen/testing/test/testdata/output-funcs/docs/funcwithdefaultvalue/_index.md
pkg/codegen/testing/test/testdata/output-funcs/docs/funcwithdictparam/_index.md
pkg/codegen/testing/test/testdata/output-funcs/docs/funcwithlistparam/_index.md
pkg/codegen/testing/test/testdata/output-funcs/docs/getbastionshareablelink/_index.md
pkg/codegen/testing/test/testdata/output-funcs/docs/getclientconfig/_index.md
pkg/codegen/testing/test/testdata/output-funcs/docs/getintegrationruntimeobjectmetadatum/_index.md
pkg/codegen/testing/test/testdata/output-funcs/docs/liststorageaccountkeys/_index.md
pkg/codegen/testing/test/testdata/plain-object-defaults/docs/funcwithalloptionalinputs/_index.md
pkg/codegen/testing/test/testdata/plain-object-disable-defaults/docs/funcwithalloptionalinputs/_index.md
pkg/codegen/testing/test/testdata/regress-8403/docs/getcustomdbroles/_index.md
pkg/codegen/testing/test/testdata/regress-node-8110/docs/examplefunc/_index.md
pkg/codegen/testing/test/testdata/simple-plain-schema/docs/dofoo/_index.md
pkg/codegen/testing/test/testdata/simple-resource-schema-custom-pypackage-name/docs/argfunction/_index.md
pkg/codegen/testing/test/testdata/simple-resource-schema/docs/argfunction/_index.md
pkg/codegen/testing/test/testdata/simple-resource-schema/docs/overlayfunction/_index.md
pkg/codegen/testing/test/testdata/simple-yaml-schema/docs/argfunction/_index.md

Right now, YAML examples are being shown under the Java tab:
Th change fixes that.

Fix the function template to show YAML under the YAML tab

---

CHANGELOG_PENDING.md
pkg/secrets/passphrase/manager.go
pkg/secrets/passphrase/manager_test.go

This partially reverts 273fa3343dbbef8a7551b3d8cf87af19bd356e89
I've left the behaviour that PULUMI_CONFIG_PASSPHRASE_FILE being empty is the same as unset because an empty file path isn't valid anyway.
Fixes https://github.com/pulumi/pulumi/issues/9541

Allow PULUMI_CONFIG_PASSPHRASE to be empty

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
sdk/dotnet/Pulumi.Automation/LocalWorkspace.cs
sdk/dotnet/Pulumi/Pulumi.csproj
sdk/dotnet/Pulumi/Serialization/ResourcePackages.cs

Both OneOf (https://github.com/mcintyre321/OneOf/pull/102) and semver (https://github.com/maxhauser/semver/pull/66) has recently added a `netstandard2.0` target to their packages, which means they no longer drag along the NETStandard.Library dependency when targeting non-.NET Framework platforms:
This PR bumps those packages to their latest versions to get rid of the NETStandard.Library dependency and subsequently some vulnerability warnings in Snyk (and other analyzers):

Bump versions of semver and OneOf

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/console.go

Fix panic in 'pulumi console' when no stack is selected.

---

.github/workflows/master.yml
.github/workflows/prerelease.yml
.github/workflows/publish-binaries.yml
.github/workflows/release.yml
.github/workflows/run-build-and-acceptance-tests.yml
scripts/go-wrapper.sh

Fixes #9602
It seems that we do not pin goreleaser and upgrades to 1.8.3 changed the binary naming, which defeated the `go-wrapper.sh` prebuilt logic. As a result we stopped reusing prebuilt binaries and sometimes would rebuild binaries in the publish step. This also slowed down the publish step significantly. Due to differences in go cache this would result in mismatch.
These kinds of changes are difficult to test but I've tested up to matching checksums by invoking the master.yml-like configuration from the `run-build-and-acceptance-tests.yml` script.
As a bonus I tried factoring out the publishing into a reusable workflow. This way there is a bit more hope that whatever we fix there goes out to all of master.yml, prerelease.yml, release.yml.

Fixes checksum validation issues and factors out publish-binaries.yml

---

.github/workflows/release.yml

reenable commented tests from 3.33.1 release

---

.github/workflows/build.yml
.github/workflows/master.yml
.github/workflows/prerelease.yml
.github/workflows/publish-binaries.yml
.github/workflows/release.yml
.github/workflows/run-build-and-acceptance-tests.yml
.github/workflows/run-codegen-test.yml
.github/workflows/run-docs-generation.yml
.github/workflows/test-fast.yml
.github/workflows/test.yml

Uses the new facility in jaxxstorm/action-install-gh-release to cache the tools (has to pin them to cache). Aimed at avoiding ratelimit issues.

Pin and enable caching installed tools

---

pkg/codegen/go/gen_program_expressions.go
pkg/codegen/pcl/binder_schema.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/synthetic-resource-properties-pp/dotnet/synthetic-resource-properties.cs
pkg/codegen/testing/test/testdata/synthetic-resource-properties-pp/go/synthetic-resource-properties.go
pkg/codegen/testing/test/testdata/synthetic-resource-properties-pp/nodejs/synthetic-resource-properties.ts
pkg/codegen/testing/test/testdata/synthetic-resource-properties-pp/python/synthetic-resource-properties.py
pkg/codegen/testing/test/testdata/synthetic-resource-properties-pp/synthetic-resource-properties.pp
pkg/codegen/testing/test/testdata/synthetic.json
pkg/codegen/testing/utils/host.go
pkg/codegen/testing/utils/providers.go

Code generation fails to bind types on scope traversals through outputs when the output is a resource type and not an object/map/etc.
Needed to fix: https://github.com/pulumi/pulumi-yaml/issues/185
The code generation is currently subpar as we aren't using lifted/proxied property access in each language, and I'm happy to take feedback if it's a small fix. As an example, the Go example should be:
```go
// This:
ctx.Export("simple", rt.Res1.Obj1())
// Not this:
ctx.Export("simple", rt.Res1.ApplyT(func(res1 *resourceproperties.Res1) (resourceproperties.Obj1, -error) {
return res1.Obj1, nil
}).(resourceproperties.Obj1Output))
```
But I think that fixing this requires a new rewriting pass, akin to the one implemented in Node.

[codegen] Improve handling of resources with outputs that are resources.

---

pkg/codegen/nodejs/gen_program.go
pkg/codegen/testing/test/testdata/aws-s3-folder-pp/nodejs/aws-s3-folder.ts

The `import * from ...` path wasn't exercised except in one test where it was invalid. TC-39 has not specified a meaning for that syntax: [Import forms mappings](https://tc39.es/ecma262/#_ref_488)
Rather than add an additional special case for the `fs` module, I've removed the conditional and regenerated our local codegen. This fixes a bug encountered while implementing `pulumi convert` for YAML feature pulumi/pulumi-yaml#200.

[codegen/nodejs] fix invalid 'import * from' branch in codegen

---

.github/workflows/test.yml

Missed one more cache opportunity.

Enable cache on gotestsum

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/logout.go

Adds a confirmation string to `pulumi logout` to add more clarity/confidence in the state after the command exits.
Fixes #9450

added confirmation string to `pulumi logout`

---

tests/integration/enums/python/__main__.py

Fixes #9652 
Having bisected our repo and then diffed CI logs, I found that the culprit of the test failures was a change in behavior in the `dill` library used to serialize dynamic providers in Python. I believe the issue is that a change in `dill` enabled capturing of closures, and this results in non-reproducible serialization of the provider.
I looked at three options for this:
1. Set an upper bound on `dill`. This did cause tests to pass locally, but it also meant opting out of ongoing security and bug fixes from the library until we could solve the non-determinism.
2. Fix the test so that it does not rely on capturing a global variable. This narrows the coverage of the test case, but it also more closely aligns with our docs on dynamic providers.
3. Update provider serialization (we …

Fix Python Dynamic provider test failures: simplify test, remove capture of global variable

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/dynamic/dynamic.py
tests/integration/enums/python/__main__.py

See:
- #9652
- #9653
Where this PR differs from #9653 is thanks to a suggestion on the upstream report to the `dill` package:
https://github.com/uqfoundation/dill/issues/481#issuecomment-1133789848
> I think a solution that will not require me rushing to get this to work but will not break compatibility with other versions of dill or your library, is to overwrite `pickle.Pickler. _batch_setitems` to sort the items.
> 
> ```python
>     unsorted_batch_setitems = pickle.Pickler._batch_setitems
> 
>     def _batch_setitems(self, items):
>         unsorted_batch_setitems(sorted(items))
> 
>     pickle.Pickler._batch_setitems = _batch_setitems
> ```
> 
> I hope this is able to fix the problem in pulumi's case while I work on the more general `deterministic` flag.
Thank you to @anivegesana, as …

Fix non-determinism in Python dynamic provider serialization

---

CHANGELOG_PENDING.md
sdk/nodejs/runtime/closure/v8_v11andHigher.ts

Remove secondary source of eager caching on module load to fix provider warnings about accessing the inspector object. Load and cache on first use instead.
Fixes #9375 
Follow up to #9614

Fix eager loading of inflight context

---

pkg/codegen/dotnet/test.go
pkg/codegen/go/test.go
pkg/codegen/nodejs/gen_program.go
pkg/codegen/nodejs/test.go
pkg/codegen/python/gen_program.go

* [codegen] Fix ImportLanguages map usage in python, nodejs
* [codegen] Add typescript dependency to packages during convert
* [testing] Add non-destructive TypeCheck operations for pulumi convert testing
These are used in:
- pulumi/pulumi-yaml#195

[codegen] Potpourri of codegen improvements for `pulumi convert`

---

pkg/codegen/schema/schema.go
pkg/codegen/schema/schema_test.go

Makes the stringified form of `schema.UnionType` slightly nicer.

Fix default handling for schema.UnionType.String

---

pkg/codegen/schema/loader.go
pkg/codegen/schema/package_reference.go
pkg/codegen/schema/schema.go
pkg/codegen/schema/schema_test.go

This change is composed of two pieces: one to guard access to the binding
operations and their results using a mutex, and one to make the result of
PartialPackage.Snapshot safe to use concurrently.
The former set of changes is pretty straighforward, and just involves
adding a mutex and appropriate locking/unlocking around binding operations
and reads/writes from/to PartialPackage.def.
The latter change is a bit riskier. The result of PartialPackage.Snapshot
is a *Package. Prior to these changes, multiple calls to Snapshot would
return a pointer to the same Package value after updating its fields.
Becuase the *Package API is field-based instead of method-based, there is
no way to make the update itself concurrency-safe, as there's nowhere to
add locking, and it is not possible to …

[schema] Make PartialPackage concurrency-safe

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/runtime/resource.py
sdk/python/lib/test/langhost/remote_component_dependencies/__init__.py
sdk/python/lib/test/langhost/remote_component_dependencies/__main__.py
sdk/python/lib/test/langhost/remote_component_dependencies/test_remote_component_dependencies.py

Don't add children of remote componet resources

---

sdk/go/common/workspace/plugins.go

In CI environments that capture all terminal output, the `Downloading plugin` output can end up concatenated over and over, like so:
```
Downloading plugin: 90.43 MiB / 105 MiB  85.35% 00m13sDownloading plugin: 90.43 MiB / 105 MiB  85.35% 00m13sDownloading plugin: 90.43 MiB / 105 MiB  85.35% 00m13s...
```
If we're in a non-interactive environment, disable the progress bar.

[cli] Disable plugin install progress bar in CI, non-interactive shells

---

sdk/nodejs/proto/provider_grpc_pb.js
sdk/proto/go/provider.pb.go
sdk/proto/provider.proto
sdk/python/lib/pulumi/runtime/proto/provider_pb2_grpc.py

Add a more comprehensive description about the semantics of the provider Cancel operation. This description was copied from the pulumi-kubernetes provider where this feature was originally implemented.

Update docstring for Cancel gRPC method

---

CHANGELOG_PENDING.md
sdk/python/lib/setup.py
sdk/python/requirements.txt

Fixes https://github.com/pulumi/pulumi/issues/9694
We should look at updating protoc such that we can generate new style python protobuf code. However that is _involved_ due to us being on an old version and both Go and Node generators have also changed substantially over time.
As quick fix for the p0 this just pins us to not use version 4 of the library.

Pin python protobuf to <4

---

pkg/testing/integration/program.go

Add diffs in order to make debugging acceptance tests failures in CI easier. Sample output:
```
pulumi:pulumi:Stack: (same)
[urn=urn:pulumi:dev::test-bucket::pulumi:pulumi:Stack::test-bucket-dev]
+ aws:s3/bucket:Bucket: (create)
[urn=urn:pulumi:dev::test-bucket::aws:s3/bucket:Bucket::my-bucket]
[provider=urn:pulumi:dev::test-bucket::pulumi:providers:aws::default_5_4_0::978387a2-eabb-4b06-b63d-0cd0f7a5225d]
acl          : "private"
bucket       : "my-bucket-0e20e92"
forceDestroy : false
websiteDomain: "stack72.dev"
--outputs:--
~ bucketName: "my-new-bucket-9d8e54f" => output<string>
- aws:s3/bucket:Bucket: (delete)
[id=my-new-bucket-9d8e54f]
[urn=urn:pulumi:dev::test-bucket::aws:s3/bucket:Bucket::my-new-bucket]
[provider=urn:pulumi:dev::test-bucket::pulumi:providers:aws::default_5_4_0::9783 …
```

Add --diff to preview in acceptance test flow.

---

pkg/codegen/docs/gen.go

This change fixes unsafe html emitted for Java properties for template types which results in mangling API docs for multiple resources, see https://www.pulumi.com/registry/packages/command/api-docs/local/command/ and https://www.pulumi.com/registry/packages/kubernetes/api-docs/helm/v3/chart/ for instance.
The general expectation based on [this template]( https://github.com/pulumi/pulumi/blob/master/pkg/codegen/docs/templates/constructor_args.tmpl) is that the type name is already safe (`htmlSafe` marks literal strings to be safe) but this was not true before the change for template types (`e.g. List<T>`), resulting in unescaped html. 
I can certainly make the escaping parameterized on the language but I suspect this should be safe across all languages. Happy to make this more targeted if …

Fix unsafe html emitted for Java properties

---

sdk/python/lib/setup.py
sdk/python/requirements.txt

After the _fun_ of protobuf releasing version 4 with breaking changes we want to try and reduce the chance of that happening across any of our dependencies again. 
`~=N.M` is the same as `==N.*,>=N.M`. That is no higher than the current major version, but higher or equal for the minor version.

Update python requirments to pin to major version

---

sdk/go/common/util/ciutil/detect.go
sdk/go/common/util/ciutil/systems.go

Detect an additional CI provider, relying on the default implementation of [DetectVars](https://github.com/pulumi/pulumi/blob/29eb7bd3300f974e42791ad049a7c821ecf69c8b/sdk/go/common/util/ciutil/systems.go#L109) that just populates the provider name.

add additional CI provider detection

---

.github/workflows/test-windows-cron.yml

Add versions.txt production to test-windows-cron

---

pkg/cmd/pulumi/stack_history.go

`pulumi stack history` has been labeled as in preview for 2+ years (as `pulumi history` back then) - there's no reason to keep this label any longer.

Remove preview label from pulumi stack history

---

scripts/versions.sh

The places where GENERIC_VERSION is used in the CI scripts previously expected a version like "a.b.c", not "***v***a.b.c".
Or to be precise, they expected the verbatim output of `$(pulumictl get version --language generic -o)`, and the GENERIC_VERSION env var added a `v` prefix.
Intended to fix build errors on pulumi-docker-containers like the following:
https://github.com/pulumi/pulumi-docker-containers/runs/6660404954?check_suite_focus=true

[ci] use unprefixed (no-v) version for generic version, fix docker container builds

---

sdk/go/pulumi/types.go
sdk/go/pulumi/types_test.go

An Output and its ApplyT method has behavior akin to NodeJS' Promise and then method, in that nested outputs are unwrapped. A previous PR, to fix #9506, lacked rigorous tests of the desired behavior of the unwrapping.
This adds those tests and solves some bugs caused by mutation in the `await` function. Instead, a fresh Output is created and we properly implement a Monadic "join" like behavior where we accumulate known-ness/errors, secret-ness, and dependencies. If not for known-ness, these would be a commutative monoid and order-independent. Two states however are non-commutative: when not known or the error field is set. This behaves similar to throwing an exception in NodeJS, we early exit and additional Then methods don't have their arguments called.
Without this PR, the added tests …

Fix `join` equivalent operation when nesting ApplyT

---

pkg/codegen/schema/loader.go

This is part of fixing https://github.com/pulumi/pulumi-yaml/issues/135.

Add typed error when an empty schema is returned

---

pkg/cmd/pulumi/login.go

Fixes #9410
I think we should just respond with an error message here. If you type `https://api.pulumi.com` then everything works as expected. We shouldn't perform the automatic conversion of `app` to `api`.

Special case the error specifing app.pulumi.com

---

.github/workflows/test-windows-cron.yml

Fix 9763 test-windows-cron

---

pkg/codegen/nodejs/test.go
pkg/codegen/python/gen_test.go

Two codegen optimizations on the longest running languages:
- Python: Don't run pyTestCheck unless there were mixins that add tests. On my machine this changes the python test time from ~340s to ~55s.
- TypeScript: Add the `tsc` flags '--skipLibCheck true` and `--skipDefaultLibCheck true'. This cuts ~50s off of the
total time needed in github.com/pulumi/pulumi/pkg/v3/codegen/nodejs. This is valid if we assume that packages which we depend on are valid.

[python,nodejs] Speed up codegen tests

---

tests/integration/delete_before_create/step1/package.json

Working in the blind to fix
https://github.com/pulumi/pulumi/runs/6721365268?check_suite_focus=true
as I can't repro it locally - but maybe updating to the latest helps?

Update uuid version

---

pkg/testing/integration/program.go

The integration test framework was silently ignoring the `OrderedConfig` option if it was set using the `With` method.

fix: Add missing OrderedConfig to integration test With method

---

.gitignore

The release.yml workflow [failed](https://github.com/pulumi/pulumi/runs/6794002150?check_suite_focus=true) to publish v3.34 because go releaser doesn't like to see the build artifacts tracked in git so here we ignore them

Do not track go-releaser build directories: fixes release workflow

---

.goreleaser.build.yml
CHANGELOG_PENDING.md
scripts/go-wrapper.sh

Fixes #9816
Example testing locally:
```
goreleaser -f .goreleaser.build.yml --skip-validate --rm-dist
```

Prefer static linking except on darwin where CGO is required

---

CHANGELOG_PENDING.md
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/stack.go
pkg/backend/stack.go
pkg/cmd/pulumi/config.go
pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/util.go
sdk/go/common/workspace/paths.go
tests/integration/integration_test.go

This reverts commit 150aba462e248875d1ce3474e813868836f56d93.
Fixes https://github.com/pulumi/pulumi/issues/9815

Revert "allow `pulumi destroy -s <stack>` if not in a pulumi project dir (#9613)"

---

sdk/go/common/workspace/templates.go

Right now, when we are raising a PR in pulumi/templates, it uses [workspace.RetrieveTemplates](https://github.com/pulumi/templates/blob/master/tests/template_test.go#L70) which in turn calls [retrievePulumiTemplates](https://github.com/pulumi/pulumi/blob/master/sdk/go/common/workspace/templates.go#L311) in pulumi/pulumi that clones and tests the templates from `master` branch of pulumi/templates instead of cloning and testing the template changes from the raised PR 
> see [pulumi/templates#294](https://github.com/pulumi/templates/pull/294) where the problem comes to light: github actions building outdated templates from master branch and not the new ones
This PR makes sure that if we are running the tests of pulumi/templates that we are also cloning the right branch, not always defaulting …

Clone and test pulumi/templates from the current working branch

---

CHANGELOG.md

Retroactively update release notes to include blurb and link to YAML release.
After this is merged, I'll edit the GitHub release for 3.34 to match.

YAML v0.5.1 release note update

---

pkg/cmd/pulumi/main_1.17_test.go
pkg/cmd/pulumi/main_1.18_test.go
pkg/cmd/pulumi/main_test.go

This file previously compiled only on go 1.17 as the signature for `MainStart` changed. This adds the necessary methods and via conditional compilation, targets pre-1.18 and 1.18 methods.

[pkg] Enable main_test to compile on go 1.17 and go 1.18

---

sdk/go/common/workspace/templates.go

Reverts pulumi/pulumi#9804 because the better way to fix pulumi/templates is to make them use local templates without downloading them again from their repo

Revert "Clone and test pulumi/templates from the current working branch"

---

CHANGELOG_PENDING.md
sdk/go/common/util/gitutil/git.go
sdk/go/common/util/gitutil/git_test.go

The `ParseGitRepoURLs()` function makes a few of assumptions about the number of paths in a given git URI. This PR sidesteps those assumptions in the general case where the URI contains `.git` using a more general approach.  As a result, we can parse nested git projects.
Fixes https://github.com/pulumi/pulumi/issues/9354

[sdk/go] Support nested git project paths

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/output.py
sdk/python/lib/test/test_output.py

Our other SDKs return a warning message when trying to stringify outputs. This updates the Python SDK to also return a warning message.

Change str(output) to return a warning message

---

CHANGELOG_PENDING.md
sdk/go/pulumi/stack_reference.go
sdk/go/pulumi/stack_reference_test.go

When a valid stack reference is asked to retrieve an absent key as a string, the default value is returned. This results in previews displaying `""` as the value of the stack reference key. See the [linked issue](https://github.com/pulumi/pulumi/issues/9365) for an example. 
This PR makes the following changes:
1. When the value is absent during a preview, return an unknown output. This fixes the linked issue.
2. When the value is absent during a `pulumi up`, error when a string is requested. This brings the behavior of `string` inline with `Int` and `Float64`.
Fixes #9365

[sdk/go] Improve unknown stack references preview

---

CHANGELOG_PENDING.md
sdk/go/pulumi/stack_reference.go
sdk/go/pulumi/stack_reference_test.go

[sdk/go] Ensure stackref getters localize secret-ness to the key retrieved

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/import.go
pkg/codegen/importer/hcl2_test.go
pkg/codegen/importer/language_test.go
pkg/codegen/schema/loader.go
pkg/codegen/schema/loader_schema_test.go
pkg/codegen/schema/loader_test.go
pkg/codegen/testing/test/sdk_driver.go
pkg/codegen/testing/test/testdata/eks.json
pkg/codegen/testing/test/testdata/external-go-import-aliases/schema.json
pkg/codegen/testing/test/testdata/external-node-compatibility/schema.json
pkg/codegen/testing/test/testdata/external-resource-schema/schema.json
pkg/codegen/testing/test/testdata/plain-schema-gh6957/schema.json
pkg/codegen/testing/utils/host.go
pkg/codegen/testing/utils/providers.go
pkg/go.mod
pkg/go.sum
pkg/resource/deploy/deploytest/pluginhost.go
pkg/resource/deploy/providers/registry_test.go
sdk/go/common/resource/plugin/host.go
sdk/go/common/workspace/plugins.go
tests/go.mod
tests/go.sum

Implements caching of schemas in package loader. Package loader searches for plugins & before calling GetSchema, attempts to read a `schema-${pkg}.json` file. On cache miss or when the plugin is newer than the cache, the file is updated via GetSchema call.
Tested against locally installed packages as well as plugin cache located packages, e.g.: when `pulumi-resource-azure-native` is in $GOBIN, this caches the schema to `$GOBIN/schema-azure-native.json`.
A micro benchmark shows substantial improvements in wall time and bytes of memory allocated/copied, and a combined benchmark of this PR along with PRs to Azure Native & YAML reduced the time for a `pulumi preview` on an Azure Native stack down to 2.5 seconds from 12, and down to 340MiB peak memory usage from ~2GiB.
A microbenchmark shows …

[schema] Faster schema loading via caching alongside plugins

---

sdk/dotnet/Pulumi/Core/Output.cs
sdk/dotnet/Pulumi/Extensions.cs

Noticed this while looking around the Output code checking for async bugs. I don't think this is a bug, the current logic looks like it handles cancellations and exceptions ok but there's no need for it. We can just use the compilers await logic to do the mapping from a task with a value to an OutputData structure. Also saves the extra TaskCompletionSource object.

Use await not Task.Assign

---

pkg/codegen/python/gen.go

Fixes the [linter](https://github.com/pulumi/pulumi/runs/6890736442) after an unfortunate merge in https://github.com/pulumi/pulumi/pull/9856

Rename optionalUrl to fix linter

---

pkg/codegen/python/python.go
pkg/codegen/python/python_test.go

Github search shows no usage of `PyNameLegacy` in our repos. Bumped into it while looking at #5175.

Remove the deprecated PyNameLegacy function

---

CHANGELOG_PENDING.md
pkg/go.mod
pkg/go.sum
sdk/go.mod
sdk/go.sum
sdk/go/common/resource/resource_id.go
sdk/go/common/resource/resource_id_test.go
tests/go.mod
tests/go.sum

NewUniqueHexV2 tried to generate deterministic names via sequence numbers, but this was insufficent to generate names that worked for many scenarios. We're going to try to generate names based on more sources of data, but there's no need to keep updating providers and provider code each time we change the data set. Instead we're going to pass the byte
slice to Check and use that as a random source, the engine will then be free to change how those random bytes get generated (including possibly just generating them completly randomly)
This adds a new function for generating unique names that will work with that idea. It takes a byte slice and uses that to generate a random number sequence to fill in the random part of the name. This new method also takes a "charset" option as currently …

Add NewUniqueName

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi.Automation/PublicAPI.Shipped.txt
sdk/dotnet/Pulumi.Automation/UpdateOptions.cs
sdk/dotnet/Pulumi.Automation/WorkspaceStack.cs
sdk/go/auto/optpreview/optpreview.go
sdk/go/auto/optup/optup.go
sdk/go/auto/stack.go
sdk/nodejs/automation/stack.ts
sdk/python/lib/pulumi/automation/_stack.py

Adds support for policy packs in automation API so we can address https://github.com/pulumi/actions/issues/212
Fixes #6757

add support for local policy packs in auto api

---

CHANGELOG_PENDING.md
pkg/resource/deploy/source_eval.go

This PR adds a warning when component resources have the `ignoreChanges` option applied, since that option has no effect and is ignored by the engine.
**Reviewers:** Looking for guidance on how to test Diagnostic messages. If this change warrants a test, I'm happy to add one. Could you point me to an example of how I could inspect diagnostics and confirm my change works?
@Frassle [in the original issue](https://github.com/pulumi/pulumi/issues/9704#issuecomment-1139460514), you mentioned there could be other options that are ignored by components. If that's true, could you help me determine what those options are?
Fixes https://github.com/pulumi/pulumi/issues/9704

Add warning when using ignoreChange on Component.

---

.github/workflows/run-codegen-test.yml

Downstream tests will fail as they update their provider binaries to use go 1.18: https://github.com/pulumi/pulumi/runs/6872372597?check_suite_focus=true#step:8:49
This tactically only updates the Go version for these tests, as we don't want to inadvertently depend on any 1.18 behavior in the Go SDK yet.
Fixes: #9862

Fix downstream codegen test failures

---

sdk/dotnet/Pulumi/Deployment/Deployment_Prepare.cs

Protobuf string fields can't be set to null. As we're building the Spec object all the fields are optional and we were indicating that with nullness which then tripped the null check in the property setter. This changes the code to just check nullness first and only set the spec property if it's non-null.

Fix dotnet alias spec

---

scripts/get-language-providers.sh

This would release pulumi-language-java v0.4.0 together with the new Pulumi CLI, see what's new in https://github.com/pulumi/pulumi-java/blob/main/CHANGELOG.md#040-2022-06-22

Update pulumi-java ref to v0.4.0

---

CHANGELOG_PENDING.md
pkg/engine/lifeycletest/pulumi_test.go
pkg/engine/lifeycletest/test_plan.go
pkg/resource/deploy/source_eval.go

This PR is a follow-on to https://github.com/pulumi/pulumi/pull/9863. There are some resource options that have no effect when applied to component resources. This PR will produce a warning each time those options are applied to components.
The initial PR was scoped to emit a warning for the `ignoreChanges` option, while this PR addresses resource options `customTimeouts`, `additinoalSecretOutputs`, `replaceOnChanges`, and `retainOnDelete` as well.
Fixes https://github.com/pulumi/pulumi/issues/9877

Add Warnings when Resource Options are applied to Components with no effect

---

CHANGELOG_PENDING.md
sdk/go/auto/stack.go

This PR fixes an issue which passes quoted string to color flag in golang auto sdk
```bash
error: unsupported color option: '\"auto\"'
```

[auto/go] - pass unquoted string to color flag

---

Makefile
sdk/dotnet/Makefile
sdk/go/Makefile
sdk/nodejs/Makefile
sdk/python/Makefile

Avoid realpath Makefile func that seems flaky on Win

---

CHANGELOG_PENDING.md
pkg/resource/deploy/step_generator.go

We really need to sort out what are actually valid names and validate them correctly, but that's part of https://github.com/pulumi/pulumi/issues/8949. For now assume it's fine to throw any string in here because it's been working so far.
Fixes https://github.com/pulumi/pulumi/issues/9947

Don't check QName is valid in alias logic

---

pkg/codegen/schema/bind.go
pkg/codegen/schema/schema.go
pkg/codegen/schema/schema_test.go

We include a `PackageReference` which is guaranteed to be correct with schema types.
Helps with #9932

Include pkg reference in bound schema types

---

sdk/dotnet/Pulumi/Pulumi.csproj

As requested in https://github.com/pulumi/pulumi/issues/7911#issuecomment-1065732155
cc @gitfool

Update C# protobuf reference to 3.20.1

---

Makefile
build/common.mk
sdk/dotnet/Makefile
sdk/go/Makefile
sdk/nodejs/Makefile
sdk/python/Makefile

Following up on the earlier comment by @iwahbe that PROJECT_ROOT is confusing, and not really root. This PR removes the PROJECT_ROOT variable. It was needed because common Go flags were defined in `common.mk` but the paths to the wrapper script were different depending on which target was run. In the updated code, `GO_TEST` and `GO_TEST_FAST` are simply redefined in every Makefile with the appropriate relative path to the wrapper.

Remove PROJECT_ROOT Make var

---

CHANGELOG_PENDING.md

Cleanup CHANGELOG_PENDING after v3.35.1 release

---

scripts/release.sh

This extends `scripts/release.sh` to partially automate our entire release sequence. I am always a little nervous messing things up doing it manually. And perhaps most importantly, taking 3 PRs to do the release is a lot.
The manual sequence is documented in https://github.com/pulumi/home/wiki/Producing-the-Pulumi-CLI-and-SDKs
With this helper script, the idea is to reorder merging and tagging so that only 1 PR is needed. I believe this should work. Three commits are created, and should me merged without squashing on top of master. Only after that all the tags are added. Once the tags are added, release.yml automation kicks off from the tags.
I have test-driven it on a t0yv0/pulumi fork.
As an alternative we could also tag the commits before they land on master. This is a bit dangerous if …

Automate release chores

---

sdk/python/lib/pulumi/output.py
sdk/python/lib/test/test_output.py

Not sure why I was using square braces here. This changes the error message to more match python syntax and names.

Fix typo in __str__ error message

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/refresh.go
pkg/cmd/pulumi/up.go

`--skip-preview` means there's nothing to confirm for up/destroy/refresh/import, so we shouldn't be asking for `--yes` in non-interactive mode.
Fixes #4569

[cli] Do not require --yes if --skip-preview is set

---

sdk/nodejs/package.json

Update the explicit reference to `source-map-support` from `^0.4.16` to `^0.5.6`. It's the same one that we reference transitively via `ts-node@7.0.1`, which, I believe, is the reason why `yank.lock` hasn't changed.
I validated manually that `0.5.x` has no `Buffer()` in its source code.
It's a partial fix to https://github.com/pulumi/pulumi/issues/8790 - after this change gets released, I'll have to go through all tests that reference Pulumi (like Automation API) and update them to the latest version, including bumping their `package.json.lock` files.

Reference a later version of source-map-support

---

CONTRIBUTING.md

Updates CONTRIBUTING.md so that we don't require installing .NET Core 3.1 but the latest (.NET 6.0.301). 
Fixes #9811

Update Contributing.md to point to the latest .NET

---

sdk/nodejs/tsconfig.json

Addresses https://github.com/pulumi/docs/issues/2782.
All functions in Pulumi SDKs take an InvokeOptions-typed argument, and all the generated documentation for those functions has a broken link because it's not part of the NodeJS SDK documentation generated for pulumi/pulumi.
The version of TypeDoc used by pulumi/docs is quite old, and I suspect it consults `tsconfig.json` to find the source files (evidence: someone complaining that it does not do this well enough: https://github.com/TypeStrong/typedoc/issues/1515). I have conservatively just added the file in question to `files`, since:
- I'm not sure if .files _should_ list all the files*
- Upgrading TypeDoc would surely have many unintended consequences
(*If it should, it would not be that tricky to add a linting task which checks …

Include invoke.ts (and its type `InvokeOptions`) in generated documentation

---

CHANGELOG_PENDING.md
pkg/codegen/dotnet/gen_program.go
pkg/codegen/go/gen_program.go
pkg/codegen/python/gen_program.go

Fixes pulumi/pulumi-command#85

Fix the panic on pulumi convert for package without a version

---

pkg/cmd/pulumi/stack_rm.go

Fixes #9166, please make sure the wording makes sense to you
Example of an output:
```
This will permanently remove the 'dev' stack!
Please confirm that this is what you'd like to do by typing ("dev"): dev
error: 'dev' still has resources; removal rejected. Possible actions:
- Make sure that 'dev' is the stack that you want to destroy
- Run `pulumi destroy` to delete the resources, then run `pulumi stack rm`
- Run `pulumi stack rm --force` to override this error
```

Improve wording for the stack removal error when stack still has resources

---

sdk/go/common/resource/plugin/langruntime_plugin.go
sdk/go/common/resource/plugin/plugin.go
sdk/go/common/util/cmdutil/trace.go

Not including the test case yet - but my informal test case is a program obtained from `pulumi new aws-go` invoked as: 
```
pulumi preview --tracing=file:./preview.tace
```
If one looks at how providers are invoked in that example it's like this:
```
EXEC /home/pulumit0yv0/bin/pulumi-language-go [-root=/home/pulumit0yv0/tmp/tracing-example -tracing=tcp://127.0.0.1:41793 127.0.0.1:39649]
EXEC /home/pulumit0yv0/.pulumi/plugins/resource-aws-v5.7.2/pulumi-resource-aws [127.0.0.1:39649]
```
`tcp://127.0.0.1:41793` is the proxy server that appends to `./preview.trace` started by `pulumi` process.
I think the right fix is to ignore TracingToFile var. Once I did that I started having `-tracing` arg populated twice for the pulumi-language-go command so I cleaned up the place where that happens …

Fix --tracing flag propagation to resource plugins

---

CHANGELOG_PENDING.md
pkg/codegen/dotnet/gen_program.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/aws-iam-policy-pp/aws-iam-policy.pp
pkg/codegen/testing/test/testdata/aws-iam-policy-pp/dotnet/aws-iam-policy.cs
pkg/codegen/testing/test/testdata/aws-iam-policy-pp/go/aws-iam-policy.go
pkg/codegen/testing/test/testdata/aws-iam-policy-pp/nodejs/aws-iam-policy.ts
pkg/codegen/testing/test/testdata/aws-iam-policy-pp/python/aws-iam-policy.py

Fixes [#10042  (issue)](https://github.com/pulumi/pulumi/issues/10042)

fix: Adds support for C#-specific InputProperty names

---

pkg/codegen/go/gen_program.go

Mark error is assigned when generating temporary variables that return errors

---

pkg/codegen/python/gen.go
pkg/codegen/python/gen_test.go

I feel like this is simpler, more universal, and more correct than what we have? Let me know if you see counter-cases. It's the last test case that trips our current escaping and the AzureDevOps provider.
Fixes #9441

Simplify and harden escaping in Python doc strings SDK gen

---

pkg/codegen/go/importer.go

First part of #10077
This is a no-op right now, we need to introduce this flag, wait for Azure Native to depend on this version and set it to "true", then we will change the behavior.

Enable polarity flip on GenerateExtraInputTypes

---

CHANGELOG_PENDING.md
sdk/go/pulumi/types.go
sdk/go/pulumi/types_test.go

Although `pulumi.String` and other type primitive type aliases are not output types (do not implement `Output`), they all implement `ElementType` which gives us enough information to resolve them, via the element type, to their corresponding output types.
This adds a new interface we can use to deduce that and a fallback path.
Fixes #6505

Use ElementType to deduce resultType

---

sdk/go/pulumi/types.go
sdk/go/pulumi/types_test.go

As identified by a build failure on master here: https://github.com/pulumi/pulumi/runs/7313397089?check_suite_focus=true#step:35:100
The previous PR, #10103 failed to handle `IntInput`, and in creating a new zero value (nil) value for the interface failed.
This adds a check to see if the return type is an input type, then it attempts to look up the associated concrete type to operate on that instead. This handles BoolInput, IntInput, et al. And otherwise attempting to look up the element type in the concrete type to output type map.
Manually re-running the failing test succeeds. The test is a bit idiosyncratic, using `GetResource` in an Apply to sequence it after creating a RandomPet, but it makes a good test case: we should expect unusual Go programs in the wild and handle them well. …

Handle input types in return position of ApplyT

---

scripts/tidy.sh

Use -compat 1.17 in tidy

---

CHANGELOG_PENDING.md
sdk/go/common/workspace/plugins.go

Log a warning that using GITHUB_REPOSITORY_OWNER is deprecated.

Add deprecation warning about GITHUB_REPOSITORY_OWNER

---

pkg/cmd/pulumi/convert.go

Don't hide the convert command

---

CHANGELOG_PENDING.md
pkg/codegen/go/gen_program.go
pkg/codegen/pcl/binder_resource.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/aws-resource-options-pp/go/aws-resource-options.go

Fixes up import and constructor calling, input argument type naming and field typing for provider resources.
The issues were:
* Providers were imported from a `/providers` module path because we read it from the middle part of the type token, we weren't handling the `pulumi:providers:$packageName` special case token. Updates Go program generation to handle that, and to also handle the type name (e.g.: `NewProvider` not `Newaws`).
* Providers inputs and shape are populated from `schema.Config()`, but providers are resources in the schema, they just live in a special location. Updates the binder to special case providers and treat it as a resource.
Fixes https://github.com/pulumi/pulumi-yaml/issues/283
Fixes #8076
Fixes #6510

[codegen/go] Support provider resources

---

pkg/codegen/go/gen_program.go

This was causing panics in downstream codegen tests
Fixes https://github.com/pulumi/pulumi/issues/10151

Revert change to panic in codegen

---

CHANGELOG_PENDING.md
pkg/resource/deploy/source_eval.go
sdk/go/common/tokens/names.go
sdk/go/common/tokens/names_test.go

Doesn't look like these are used by anything, so preferring to just remove them rather than documenting them as dangerous.
Fixes https://github.com/pulumi/pulumi/issues/10052

Remove As[Q]Name functions

---

CHANGELOG_PENDING.md
sdk/python/cmd/pulumi-language-python/main.go

When not using a virtual environment we look at the PULUMI_PYTHON_CMD to control what python binary to run (defaulting to looking for "python" or "python3" if it's not set).
This adds a check for this variable when using a virtual environment allowing a user to change from "python", if for example they want to force something like "python39".

Support PULUMI_PYTHON_CMD with venvs

---

CHANGELOG_PENDING.md
pkg/backend/filestate/backend.go
pkg/backend/filestate/state.go
pkg/backend/httpstate/state.go
pkg/cmd/pulumi/config.go
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/new_test.go
pkg/cmd/pulumi/stack_change_secrets_provider.go
pkg/cmd/pulumi/stack_export.go
pkg/cmd/pulumi/stack_import.go
pkg/cmd/pulumi/up.go
pkg/engine/lifecycletest/pulumi_test.go
pkg/operations/resources_test.go
pkg/resource/stack/checkpoint.go
pkg/resource/stack/deployment.go
pkg/resource/stack/deployment_test.go
pkg/resource/stack/secrets.go
pkg/resource/stack/secrets_test.go
pkg/secrets/b64/manager.go
pkg/secrets/passphrase/manager.go
pkg/secrets/service/manager.go
pkg/testing/integration/program.go
sdk/go/common/resource/config/crypt.go
sdk/go/common/resource/config/value.go
sdk/go/common/resource/config/value_test.go
tests/stack_test.go

Currently opentracing spans generated by the HTTP client when calling BulkDecrypt endpoint are not parented correctly. This seems to be an issue with not propagating `context.Context` through the code correctly. I took a stab at propagating it and I can see the spans snapping back into place.
Since we're changing interfaces under `sdk/` this is a breaking change. It can be fixed by injecting `context.Background()` at the call sites. 
Example project:
```
package main
import (
"github.com/pulumi/pulumi-aws/sdk/v5/go/aws/s3"
"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)
func main() {
pulumi.Run(func(ctx *pulumi.Context) error {
// Create an AWS resource (S3 Bucket)
bucket, err := s3.NewBucket(ctx, "my-bucket", nil)
return err
}
// Export the name of the bucket …
```

Fix orphan bulk decrypt traces

---

sdk/nodejs/cmd/pulumi-language-nodejs/main.go

pulumi-language-nodejs starts node sub-processes to manage Pulumi projects. With these changes the subprocesses are now visible as spans in the [Pulumi trace](https://www.pulumi.com/docs/support/troubleshooting/#performance). The tagging convention is taken from pulumi-language-go. The change is small enough we might not need to highlight it in changelog.

Add tracing around os.Exec in node provider

---

CHANGELOG_PENDING.md
pkg/codegen/schema/loader.go
pkg/codegen/schema/mock_pulumi_schema.go

Return a mocked pulumi package so in pulumi-yaml, resources such as `StackReference` can be instantiated, rather than relying on `Fn::StackReference`
Addresses `pulumi-yaml`[#198](https://github.com/pulumi/pulumi-yaml/issues/198)

Add mock pulumi package

---

CHANGELOG_PENDING.md
sdk/go/auto/cmd.go
sdk/go/auto/local_workspace.go
sdk/go/auto/local_workspace_test.go
sdk/go/auto/optdestroy/optdestroy.go
sdk/go/auto/optpreview/optpreview.go
sdk/go/auto/optrefresh/optrefresh.go
sdk/go/auto/optup/optup.go
sdk/go/auto/stack.go

Exposes a new `Option` `ErrorProgressStreams` in the Automation API
that allows `stderr` to be redirected to one or more `io.Writers`.
The option is available for `refresh`, `destroy`, `preview` and `update`
operations. This will allow an enduser to tap into the ongoing stream
for `stderr`. Until now only concatenated `string` of outputs containing
all events was available in the returned result of an operation.

feat: Ability to capture incremental stderr

---

README.md

As a step towards https://github.com/pulumi/pulumi/issues/9743, this PR adds a note to the README that `v1` and `v2` of the CLI are EOL.

Update README to show EOL CLI versions.

---

.github/workflows/build.yml
.github/workflows/publish-binaries.yml
.github/workflows/run-build-and-acceptance-tests.yml
.github/workflows/test-fast.yml
.github/workflows/test-macos-cron.yml
.github/workflows/test-minimal.yml
.github/workflows/test-windows-cron.yml
.github/workflows/test.yml
.goreleaser.build.yml
.goreleaser.prerelease.yml
.goreleaser.yml
pkg/backend/filestate/state.go
scripts/get-language-providers.sh
scripts/prep-for-goreleaser.sh

Run a sampling of integration tests on MacOS and Windows only, and adds that same set of tests to Linux.
This changes the number of test jobs:
* MacOS from 7 to 1
* Windows from 7 to 1
* Linux from 7 to 8
The build jobs which run on MacOS are not changed.
Each commit should be descriptive of its content. The change to the goreleaser configs aims to reduce duplication and aid brevity. The biggest change to goreleaser configuration is the removal of the separate "build IDs" and archives for nix-like and Windows. Instead, the `prepare-for-goreleaser` script prepares `./bin/${GOOS}` directories for the final assembly of extra files into the archives. This simplifies the archive config to the following:
```yaml
archives:
- wrap_in_directory: pulumi
format_overrides:
- goos: windows
format: zip …
```

[ci] Reduce PR cycle time, MacOS runner demand

---

.goreleaser.build.yml
.goreleaser.prerelease.yml
.goreleaser.yml

The `{{ .Name }}` template string in GoReleaser includes the extension, which must be stripped to use it in a `prebuilt.path`. 
Verified locally by running all three goreleaser configs with `--debug` for verbose output. The command to run the `.goreleaser.build.yml` against Windows x86-64 is:
```bash
#!/bin/bash
GOWORK=off GORELEASER_CURRENT_TAG=v3.35.0-alpha.1 GOOS=windows GOARCH=amd64 \
goreleaser build -f .goreleaser.build.yml \
-p 1 --skip-validate --rm-dist --snapshot --single-target
mv goreleaser goreleaser-windows
GOWORK=off GORELEASER_CURRENT_TAG=v3.35.0-alpha.1 GOOS=windows GOARCH=amd64 \
goreleaser build -f .goreleaser.prerelease.yml \
-p 1 --skip-validate --rm-dist --snapshot --single-target
```

[ci] Fix extra extension in goreleaser templates

---

CHANGELOG_PENDING.md
sdk/go/pulumi/context.go

Expose context.Context from pulumi.Context via getter method
Addresses #10162

Expose context.Context from pulumi.Context

---

sdk/nodejs/automation/server.ts
sdk/nodejs/cmd/dynamic-provider/index.ts
sdk/nodejs/cmd/run-policy-pack/run.ts
sdk/nodejs/cmd/run/run.ts
sdk/nodejs/config.ts
sdk/nodejs/dynamic/index.ts
sdk/nodejs/metadata.ts
sdk/nodejs/output.ts
sdk/nodejs/provider/server.ts
sdk/nodejs/resource.ts
sdk/nodejs/tsutils.ts

The key motivation for this change is speeding up startup of small JavaScript programs. That is:
```
pulumi new javascript
time pulumi preview
```
This 300ms is simply is the cost of adding ts-node and typescript dependency to the imports.
Importing `"runtime"` directly considered harmful because it imports "typescript" indirectly via "closure" support.

Avoid importing typescript unless necessary

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/convert.go

Add `install-dependencies` flag to allow user to opt out of installing dependencies on `pulumi convert` if they only want the generated files. Defaults to `true.
Addresses #10196

Add flag to specify whether to install dependencies on `pulumi convert`

---

pkg/codegen/go/gen_program.go

Since https://github.com/pulumi/pulumi-terraform-bridge/commit/4df3c4a150da485c714a44dbc189072b72b74469, it is safe to return errors when invalid code is generated. We don't need to wait for providers to pull in an updated version of the bridge since they will depend on this new code only through the bridge. We should stop panicking.

[go] Don't panic on invalid program code

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/convert.go

Updates [this merged PR](https://github.com/pulumi/pulumi/pull/10198)

Add flag to specify whether to install dependencies on pulumi convert

---

pkg/backend/httpstate/state.go

Before the changes, the trace of `pulumi preview` on new AWS project shows `api/renewLease` call on the critical path-to-first-resource, something we are trying to optimize. After the changes the call either never happens on short programs. This seems like a small win. For me this is about 120ms.
Relevant context on where tokens come from and how it flows through the code:
```go
func (b *cloudBackend) apply(...) {
// createAndStartUpdate makes the initial token
// it is Seen as "api/startUpdate" operation in the trace
// example:
//
// POST /api/stacks/t0yv0/perf-js-test/dev/update/6c834f3e-2fba-4286-b317-1ec66cb8e697
..., token, ... := b.createAndStartUpdate(...) // POST /update/..
b.runEngineAction(... token ...)
}
func (b *cloudBackend) runEngineAction(... token ...) {
.. := …
```

Remove api/renewLease from startup crit path

---

pkg/engine/deployment.go

Stumbled on this while mucking around with plugins.
If ProjectInfoContext failed and returned a nil context and error, we would first try to call `WithCancelChannel` on that nil context before checking the error, which clearly went bang.
Simple flip to check the error value first.
Wouldn't discriminate result types be nice...

Fix error check in newDeployment

---

sdk/nodejs/runtime/closure/createClosure.ts
sdk/nodejs/runtime/closure/rewriteSuper.ts
sdk/nodejs/runtime/closure/utils.ts

Continues the earlier work of trying not to pay for importing typescript when unused. Unfortunately further changes are needed. This statement, common in our JavaScript templates and many programs:
```
require("@pulumi/pulumi");
```
Pulls in "./runtime" which in turn pulls in "./closure/serializeClosure" which pulls in "typescript". 
This is only done so "./runtime" can re-export these two functions:
```
export {
serializeFunctionAsync,
serializeFunction,
SerializedFunction,
SerializeFunctionArgs,
}  from "./closure/serializeClosure";
```
I thought about making a lazy re-export here but I'm a bit rusty with my node to figure out how to safely do that. So instead I just mechanically switched "./closure" code to lazy-import either "typescript" or parts of itself until the problem went away. …

Make sure import pulumi/pulumi does not necessarily import typescript

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/gen_completion.go

This PR exposes `gen-completion` when running `pulumi --help`.
This feature is already documented in our official [documentation](https://www.pulumi.com/docs/reference/cli/#command-line-completion).
Fixes #10215

Expose `gen-completion` command when running `pulumi --help`

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/stack_ls.go

Reverts [PR #10059](https://github.com/pulumi/pulumi/pull/10059); performance was significantly impacted due to calling `GetStatus` on every list status

Revert "Add last status to `pulumi stack ls` output"

---

pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/refresh.go
pkg/cmd/pulumi/up.go

- the help for `pulumi import --yes` and `... --skip-preview` mentioned "refresh" as the operation, rather than "import"; I think this was probably leftover copypasta, so I've changed it to "import"; and,
- the help text for `pulumi {destroy,up,import,refresh} --skip-preview` has "perform ... performing"; I've changed the first "perform" to "calculate" so it flows better.

Tidy up some help text

---

pkg/backend/filestate/backend_test.go
pkg/backend/httpstate/backend_test.go
pkg/backend/httpstate/console_test.go
pkg/cmd/pulumi/new_test.go
pkg/cmd/pulumi/util_test.go
pkg/codegen/testing/test/testdata/plain-object-defaults/go-extras/tests/codegen_test.go
sdk/go/common/util/ciutil/vars_test.go
sdk/go/common/workspace/plugins_install_nodejs_test.go
sdk/go/common/workspace/plugins_test.go
sdk/nodejs/npm/npm_test.go
tests/integration/integration_nodejs_test.go
tests/integration/policy/policy_test.go
tests/stack_test.go

This PR replaces `os.Setenv` with `t.Setenv`. Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
This saves us at least 2 lines (error check, and unsetting the env var) on every instance.
Reference: https://pkg.go.dev/testing#T.Setenv

test: use `T.Setenv` to set env vars in tests

---

CHANGELOG_PENDING.md
sdk/python/python.go
sdk/python/python_test.go

Fixes https://github.com/pulumi/pulumi/issues/10102

Fix python overriding PATH on Windows

---

sdk/python/lib/pulumi/provider/server.py

When running Component Providers, command line flags are passed. When debugging using `--logflow` `--logtostderr` `-v=5`, `-v=5` is passed to argparse. argparse doesn't expect this and crashes as it is not in the list of parameters the program expects. 
This change makes the program more fault tolerant around unexpected parameters being passed in by callers.
Fixes #10208

make provider more tolerant of unexpected command line args

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi.Tests/Serialization/ListOutputCompletionSourceTests.cs
sdk/dotnet/Pulumi/Serialization/Serializer.cs

[dotnet/sdk] Serialize immutable arrays initialized by default

---

CHANGELOG_PENDING.md
pkg/resource/deploy/source_eval.go
tests/integration/get_resource/dotnet/Program.cs
tests/integration/get_resource/go/main.go
tests/integration/get_resource/nodejs/index.ts
tests/integration/get_resource/python/__main__.py
tests/integration/integration_dotnet_test.go
tests/integration/integration_go_test.go
tests/integration/integration_nodejs_test.go

During Invoke, secrets are stripped and returned back in cleartext. This PR keeps them encrypted when returning them.
I've added tests and checked `nodejs` `python` sdk's v3.0.0, but was having difficulty checking the go sdk and dotnet SDK at versions v3.0.0
Fixes #10172

fix unmarshalling secrets raw

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/plugin_install.go
pkg/codegen/schema/loader.go
pkg/engine/plugins.go
sdk/go/common/workspace/plugins.go

We occasionally see network issues (most notably "tls: bad record MAC")
during plugin downloads. When grabbing plugins for codegen we already
had some retry logic. This shares that retry logic to the `pulumi plugin
install` command and the engine.
Fixes https://github.com/pulumi/pulumi/issues/9824
Note, plumbing in the progress bar and support for printing about
retries is a little bit odd but we're going to have to totally rethink
this interface at some point when the engine gets put behind a gRPC
interface and all the display logic has to be ripped out. So it works
good enough for now.

Retry plugin downloads

---

sdk/go/common/testing/environment.go
sdk/go/common/testing/environment_test.go
tests/integration/integration_test.go

Refactor the `testing.Environment` `SetEnvVars` method to append to the slice of env vars, rather than overwriting it with a new slice. As per the behavior of `Cmd.Env`, later env vars will take precedence over newer env vars, and the `Env` field is public anyway so if you really wanted to clear the slice you still can. This enables the possibility of setting env vars in `NewEnvironment` without needing to worry that subsequent calls to `SetEnvVars` will erase those env vars.

refactor: append to env var list instead of overwriting.

---

pkg/cmd/pulumi/plugin_install.go

Just a small error improvement. Previously we would take the given name and kind and try and look it up on github, but that probably doesn't exist if we're installing from a file.

Error that version is needed if using --file

---

sdk/python/lib/setup.py
sdk/python/requirements.txt

pinned grpcio to 1.47 which was used in the last successful version to run.
Fixes #10301

pinned grpcio

---

pkg/codegen/schema/loader.go
pkg/codegen/schema/mock_pulumi_schema.go

This ensures the schema is fully validated by the spec parser, the old
schema wasn't even codegen-able because of various fields not being
linked up correctly.

Change pulumi schema to use PackageSpec

---

sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
sdk/dotnet/Pulumi.Tests/Serialization/MarshalOutputTests.cs

Fix C# warnings in test projects

---

CONTRIBUTING.md

Update the build instructions a little based on recent findings during my onboarding, namely, that jq is required.
Also bump the Go version a bit from 1.17 whose end of life is on 8/16.
(documentation only)

Add jq to required build tools and update Go version

---

CHANGELOG_PENDING.md
sdk/go/common/workspace/plugins.go

No point retrying errors due to writing the plugin to a temporary file. This splits the error tracking up so we only retry read errors.
Fixes https://github.com/pulumi/pulumi/issues/10310

Don't retry plugin write errors

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/config.py
sdk/python/lib/test/automation/test_local_workspace.py
sdk/python/lib/test/conftest.py

Fixes [#10342 ](https://github.com/pulumi/pulumi/issues/10342)
This adds optional arguments to each `pulumi.Config.get<_object|_int|_float|_bool>` method in the python SDK to handle fallback default values.  This interface is a bit more "pythonic" in that most `get` methods provide a default argument (see `dict.get` for a canonical example), and will allow us to generate both more simple and more idiomatic python code in the future (see https://github.com/pulumi/pulumi/issues/10268)

feat: Supports optional arguments for pulumi.Config getters

---

CHANGELOG_PENDING.md
sdk/go/common/diag/colors/colors.go
sdk/go/common/diag/colors/colors_test.go

Partial fix for https://github.com/pulumi/pulumi/issues/10351, it should at least stop the panic. I suspect we're getting mangled or unescaped input from somewhere though and that needs tracking down and fixing as well.

Fix and add test for stray %}> sequences in colorizer

---

CHANGELOG_PENDING.md
pkg/codegen/go/doc.go
pkg/codegen/go/gen.go
pkg/codegen/go/gen_crd2pulumi.go
pkg/codegen/go/gen_program.go
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/go/gen_program_test.go
pkg/codegen/go/gen_test.go

As of #9933 we maintain a cache of globally analyzed external packages necessary for name resolution. To avoid unacceptable performance degradations, we cache that set of packages. 
This worked fine for SDK generation, but the cache didn't persist between ProgramGen calls (used to generate examples), which make up the vast majority of time spent.
This PR exposes that cache as a option to allow keeping the cache between invocations of ProgramGen. 
I'm including the new performance graph below for comparison. It doesn't render well here but can be downloaded to view.
Fixes #10308 
The performance improvement does require this patch to TF-bridge:
```patch
pkg/tf2pulumi/convert/convert.go | 6 +++++-
pkg/tfgen/docs.go                | 1 +
pkg/tfgen/generate.go            | 2 ++
3 files …
```

Expose external package cache

---

.github/workflows/build.yml
pkg/go.mod
pkg/go.sum
tests/go.mod
tests/go.sum

Go module dependencies:
* CVE-2020-29652 for Go module golang.org/x/crypto:v0.0.0-20200622213623-75b288015ac9
Compiler/toolchain dependencies:
* CVE-2022-28327 for Go 1.17.8
* CVE-2022-24675 for Go 1.17.8

Security rollup: build CLI binaries using go1.19, update dependencies

---

tests/about_test.go

Following #10357, which updated the build toolchain to use `go1.19`, an integration test failed on master from failing to match the test toolchain's version.
This test too tightly couples our build & release process with tests, so I've relaxed it do a regexp match that `pulumi about` emits *a* Go version.

chore: Relax integration test and only check for a valid go version

---

CHANGELOG_PENDING.md
pkg/codegen/go/doc.go
pkg/codegen/go/gen.go
pkg/codegen/go/gen_crd2pulumi.go
pkg/codegen/go/gen_program.go
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/go/gen_program_test.go
pkg/codegen/go/gen_test.go

Fixes https://github.com/pulumi/pulumi/issues/10308
This a restored version of https://github.com/pulumi/pulumi/pull/10340.

Expose external package cache + global default (Take 2)

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/about.go
pkg/cmd/pulumi/about_test.go
pkg/cmd/pulumi/convert.go
pkg/resource/deploy/deploytest/languageruntime.go
pkg/testing/integration/program.go
sdk/dotnet/cmd/pulumi-language-dotnet/main.go
sdk/go/common/resource/plugin/langruntime.go
sdk/go/common/resource/plugin/langruntime_plugin.go
sdk/go/pulumi-language-go/main.go
sdk/nodejs/cmd/pulumi-language-nodejs/main.go
sdk/python/cmd/pulumi-language-python/main.go

This moves all the language specific "about" information into the language plugins. This is part of the continued chipping away of having the engine have to know anything about specific languages.

Move about information to language plugins

---

sdk/nodejs/cmd/run-policy-pack/run.ts
sdk/nodejs/cmd/run/run.ts

Currently, when Node encounters an error we haven't anticipated, our error messaging could potentially cause more frustration than necessary.  We should be sure to offer helpful error messaging when possible, and when not possible, we should strive to reduce frustration as much as possible.
I have not added tests, as this is purely a text-copy change.

fix: Replaces current fallback nodejs error messaging

---

sdk/python/lib/pulumi/output.py
sdk/python/lib/test/test_output.py

Replace arrow with colon, as is correct for Python
Fixes a personal user encounter I had today 😄

Correct Python syntax in help text

---

sdk/go/common/workspace/project.go
sdk/go/common/workspace/project_test.go

Without some changes to `pulumi new` behavior, this has the surprising and incorrect behavior of causing the `resources` block to be duplicated in templates.
Reverts pulumi/pulumi#10269

Revert "[cli] Allow Pulumi.yaml files to contain additional, preserved keys"

---

pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/sdk_driver.go

Some of our Codegen tests import azure-native, which is a known massive project. AZ Native has finally exceeded the max size permitted by `go mod` for import and has started failing builds as a result. **This issue is blocking release**.
This PR skips the failing tests that use AZ-Native. I tried to leave as much enabled as possible -- I didn't disable tests in other languages that use AZ Native. Unfortunately, I wasn't able to use `SkipCompile` instead of `Skip`, because `go mod tidy` is producing the error, and that happens at generation-time, which is before compile-time.
Also, I didn't disable all tests that use AZ Native -- only the ones that were failing on master.
Marking this PR as "draft" for now because a better solution would be to pin an earlier version of AZ Native, which I …

Skip codegen tests that import az-nature. 

---

.github/workflows/build.yml
.github/workflows/publish-binaries.yml
.github/workflows/run-build-and-acceptance-tests.yml
.github/workflows/test-macos-cron.yml
.github/workflows/test-minimal.yml
.github/workflows/test-windows-cron.yml
.github/workflows/test.yml
.goreleaser.build.yml
.goreleaser.prerelease.yml
.goreleaser.yml
pkg/backend/filestate/state.go
scripts/get-language-providers.sh
scripts/prep-for-goreleaser.sh

Reimplement #10149 to reduce CI workloads again. Includes fixes from PRs #10187 and #10206.
Unblocks PR #10213, as the above PRs are the foundation for including an additional binary reliably in builds.
Fixes the regression #10262 by placing Windows files in a `pulumi/bin` folder in the archive, matching what install scripts expect on Windows.

Reduce macOS jobs on PRs, replace with partial integration tests

---

CHANGELOG_PENDING.md
pkg/backend/filestate/backend.go
pkg/backend/filestate/backend_test.go

This PR fixes a bug where the File state backend failed to apply validation logic to stack names (validation logic was dead code!) This PR introduces a tiny test to guard against this error, and a fix.
Fixes https://github.com/pulumi/pulumi/issues/10405

File state backend must apply validation logic when parsing stack refs

---

scripts/release.sh

The error message in the release script is mislabeled. This PR corrects the label and reorders the error messages to make tracing feel more linear.

Fix mislabeling in error message of release script

---

pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/util.go
pkg/util/yamlutil/node_tools.go
pkg/util/yamlutil/node_tools_test.go

Expands on #10269 with utility functions to preserve existing YAML document structure, including comments, while mutating key fields.
And coincidentally simplifying our templates, changes to how we install dependencies has removed the need to check for the "python" runtime and set a venv field.
With these changes, with or without a `Pulumi.yaml.append` file, `pulumi new aws-yaml` creates a file like so:
```yaml
name: tmp-941fe618-e0bf-4149-ab8b-54ca557202ed
description: A minimal AWS Pulumi YAML program
runtime: yaml
resources:
my-bucket:
type: aws:s3:Bucket
outputs:
bucketName: ${my-bucket.id}
```
The new implementation only removes the `.append` file, it does not concatenate it with `Pulumi.yaml`.
Fixes pulumi/pulumi-yaml#303

[cli] Enable single-file Pulumi YAML templates

---

.goreleaser.build.yml
.goreleaser.prerelease.yml
.goreleaser.yml
CHANGELOG_PENDING.md
pkg/backend/watch.go
pkg/go.mod
pkg/go.sum
scripts/get-pulumi-watch.sh
scripts/prep-for-goreleaser.sh
tests/go.mod
tests/go.sum

Replaces library used to implement recursive file watching with https://github.com/pulumi/pulumi-watch, which is itself a shim around https://github.com/watchexec/watchexec.
This solves our cross-platform build issues, and allows us to build our CLIs on any platform and cross-compile to macOS.
Fixes #9326

 Fix x-plat issues with watch, use watchexec-derived binary

---

pkg/backend/filestate/lock.go

No need to manually delete lock files anymore, `pulumi cancel` will do this.

Improve lock error for filestate

---

pkg/engine/plugins.go
pkg/resource/deploy/deploytest/pluginhost.go
pkg/resource/deploy/providers/registry_test.go
sdk/go/common/resource/plugin/host.go
sdk/go/common/workspace/plugins.go

Rather than partially filling in a PluginInfo object, this now uses a type that carries exactly what is needed for a project plugin specification.

Use explict ProjectPlugins rather than partially filling PluginInfo

---

pkg/backend/filestate/crypto.go
pkg/backend/filestate/stack.go
pkg/backend/httpstate/crypto.go
pkg/backend/httpstate/crypto_test.go
pkg/backend/httpstate/stack.go
pkg/backend/mock.go
pkg/backend/stack.go
pkg/cmd/pulumi/crypto.go
pkg/cmd/pulumi/util.go

This removes a type test for stack type, allowing us to use MockStacks in this area of code.

Move default secret manager to stack

---

CHANGELOG_PENDING.md
sdk/python/lib/setup.py
sdk/python/requirements.txt

This PR upgrades the version of PyYAML from v5.3 to v6.0.
Fixes https://github.com/pulumi/pulumi/issues/10396

Update PyYAML to v6.0

---

pkg/cmd/pulumi/util.go

`parsed.Query().Set("algorithm", "RSA-OAEP-256")` is a no-op because `Query()` returns a copy of the query values, not a reference. So this was really just `secretsProvider = url.Parse(secretsProvider).String()`.
Given it's been like this for three years and no-ones complained about azure vault secrets I think it's safe to just remove rather than fix.

Remove some dead secret manager code

---

pkg/cmd/pulumi/stack_change_secrets_provider.go
pkg/cmd/pulumi/util.go

Saves a type check by backend.
We don't have to worry about rotatePassphraseSecretsProvider for this because the default secret provider would have never triggered a rotate anyway.

Use Stack.DefaultSecretManager in createSecretsManager

---

CHANGELOG_PENDING.md
pkg/codegen/schema/loader.go
pkg/codegen/schema/loader_schema_test.go

Experimentally, this can reduce time taken in calls to load a schema by 1-3 seconds, which for a Pulumi YAML program execution or call to `pulumi convert` (on the order of 5-10s) is a significant performance improvement.
The benchmark showed that prior to this change, the benchmark took 1.1 to 2.5 seconds on a relatively recent Intel laptop processor:
Before:
```
goos: linux
goarch: amd64
pkg: github.com/pulumi/pulumi/pkg/v3/codegen/schema
cpu: 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
BenchmarkSchemaEmptyCheck
BenchmarkSchemaEmptyCheck/large-schema-empty-check-time
BenchmarkSchemaEmptyCheck/large-schema-empty-check-time-8
1	1734625270 ns/op	    6768 B/op	      22 allocs/op
PASS
```
(That's 1.7 seconds/operation, sample size of 1.)
After:
``` …
```

perf: Use a faster check for empty schemas

---

pkg/cmd/pulumi/convert.go

Make the fact that `convert` must take YAML as a source more obvious.

Update help for convert command

---

CHANGELOG_PENDING.md
pkg/codegen/go/gen.go
pkg/codegen/testing/test/testdata/dash-named-schema/go/foo/doc.go
pkg/codegen/testing/test/testdata/dashed-import-schema/go/plant-provider/doc.go
pkg/codegen/testing/test/testdata/nested-module-thirdparty/go/foo/doc.go
pkg/codegen/testing/test/testdata/plain-and-default/go/foo/doc.go
pkg/codegen/testing/test/testdata/simple-plain-schema-with-root-package/go/doc.go

codegen/go: Ensure docs information matches package name

---

CHANGELOG_PENDING.md
sdk/go/auto/git.go
sdk/go/auto/git_test.go

This makes `GitRepo.Branch` work for any of the following kinds of value (assuming a default branch of "main" at the upstream repo):
- `main`
- `not-main`
- `refs/heads/main`
- `refs/heads/not-main`
- `refs/remotes/origin/main`
- `refs/remotes/origin/not-main`
- `refs/tags/v1.0.0`
Fixes #10278.

Work with all kinds of branch names

---

.github/workflows/build.yml
.github/workflows/run-build-and-acceptance-tests.yml
.github/workflows/run-build-and-integration-tests.yml
.github/workflows/test-windows-cron.yml
scripts/go-wrapper.sh

Updated based on team discussion, we will use Linux runners for PR tests and continue building release binaries on macOS.
------
Blocked on #10213, this switches our CI system to build all binaries using cross-compilation from Ubuntu Linux runners, reducing macOS contention.
There is one prominent downside to this that is relevant:
Building on macOS with CGO_ENABLED=1 is required for the CLI to use split-tunnel VPNs on macOS that use per-DNS-name tunneling. This could impact enterprise clients with self-hosted Pulumi services. See:
- https://github.com/golang/go/issues/12524
For that reason, we may want to discuss running builds on Linux in pre-merge checks, and when implementing merge queues in #10091, ensure that merge checks & release builds use macOS builders.

ci: Build CLI in test using Linux runners, production using macOS

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/policy_new.go
pkg/cmd/pulumi/state.go
pkg/cmd/pulumi/terminal.go
pkg/cmd/pulumi/terminal_test.go

https://github.com/pulumi/pulumi/pull/10130 introduced a Terminal UI fix to optimize the pageSize parameter when displaying large selectors via the `survey` library. Unfortunately under certain conditions the logic results in a negative pageSize which causes `survey` library to panic. The fix here centralizes the logic introduced in 10130 into a helper function and makes sure that its return values are non-negative.
Fixes [#10540](https://github.com/pulumi/pulumi/issues/10450)

Fix negative page size panic

---

CHANGELOG_PENDING.md
sdk/python/lib/pulumi/runtime/config.py
sdk/python/lib/pulumi/runtime/settings.py
sdk/python/lib/test/automation/test_isolation.py

This PR makes our global values that are not more complicated classes (like SETTINGS) ContextVars, and updates their interfaces where appropriate.
Fixes #6052

 fix: Ports Python CONFIG, ROOT, and _SECRET_KEYS to ContextVars 

---

CHANGELOG_PENDING.md
sdk/nodejs/cmd/run-policy-pack/run.ts
sdk/nodejs/cmd/run/run.ts
tests/integration/integration_nodejs_test.go
tests/integration/nodejs/omit-stacktrace/syntax-error/Pulumi.yaml
tests/integration/nodejs/omit-stacktrace/syntax-error/index.js
tests/integration/nodejs/omit-stacktrace/syntax-error/package.json
tests/integration/nodejs/omit-stacktrace/syntax-error/tsconfig.json
tests/integration/nodejs/omit-stacktrace/ts-error/Pulumi.yaml
tests/integration/nodejs/omit-stacktrace/ts-error/index.ts
tests/integration/nodejs/omit-stacktrace/ts-error/package.json
tests/integration/nodejs/omit-stacktrace/ts-error/tsconfig.json

This PR catches and displays SyntaxErrors without stack traces. It also makes the error message more similar to other user errors by outputting in the same format as user errors.
Fixes #10373 
**New**
[![asciicast](https://asciinema.org/a/EZbFlwgOQriC00G729Sf3AB1c.svg)](https://asciinema.org/a/EZbFlwgOQriC00G729Sf3AB1c)
[![asciicast](https://asciinema.org/a/UdBX4jeoLOKp1vaqy32Fz8Gnz.svg)](https://asciinema.org/a/UdBX4jeoLOKp1vaqy32Fz8Gnz)
**Current**
[![asciicast](https://asciinema.org/a/y36oS26PRgzYyJwZHY0CZ4vHd.svg)](https://asciinema.org/a/y36oS26PRgzYyJwZHY0CZ4vHd)
[![asciicast](https://asciinema.org/a/mx2HYqzm2BQnvQe6kaZU45T4K.svg)](https://asciinema.org/a/mx2HYqzm2BQnvQe6kaZU45T4K)

updated error message to catch syntax errors

---

sdk/go/common/apitype/project.json

Can be added to vscode for validation while writing project files.
Not using to validate loaded project files yet, but we may want to do that in the future. I expect this to be _much_ more useful when users start writing config entries in project files.

Schema for project files

---

pkg/cmd/pulumi/about.go
pkg/cmd/pulumi/plugin.go
pkg/cmd/pulumi/plugin_install.go
pkg/cmd/pulumi/plugin_ls.go
pkg/codegen/schema/loader.go
pkg/engine/lifecycletest/provider_test.go
pkg/engine/lifecycletest/pulumi_test.go
pkg/engine/plugins.go
pkg/engine/plugins_test.go
pkg/engine/update.go
pkg/resource/deploy/deployment.go
pkg/resource/deploy/deploytest/languageruntime.go
pkg/resource/deploy/deploytest/pluginhost.go
pkg/resource/deploy/providers/registry_test.go
pkg/resource/deploy/source_eval.go
pkg/resource/deploy/source_query.go
sdk/go/common/resource/plugin/host.go
sdk/go/common/resource/plugin/langruntime.go
sdk/go/common/resource/plugin/langruntime_plugin.go
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_install_test.go
sdk/go/common/workspace/plugins_test.go

PluginSpec is used to specifiy a plugin, and is what is passed to things like "Install". PluginInfo is used to refer to an installed plugin, and so has extra data like file sizes, and time stamps, but does not include things like plugin download url.

Split PluginInfo in Info and Spec

---

pkg/testing/integration/program.go
sdk/go/common/workspace/project.go

Determined by bisecting on this repo, the change here https://github.com/pulumi/pulumi/commit/bb84532fe6077979566101a3ebce89e18f99a87b#diff-58bdc2879a0109885b20b1ac1c52e30423b544b4a0b3e4326c1b79a063c7ce14R1694-R1731 breaks most YAML ProgramTest tests by turning them into no-ops, as reading and then writing the project file removes the `resources`, `variables`, `config`, and `outputs` keys that YAML adds to the project file.
ProgramTests with a validation step that check for `outputs` would fail, because there would be no outputs.
Adding a fallback map for all additional keys to the project type and using yaml.v3 enables us to load, mutate, and write back the project file in programtest, albeit in a manner that clobbers comments. 
I had an alternative patch that used `yamlutil` methods to …

fix: PluginLink program tests clobber YAML keys in Project.yaml files

---

pkg/cmd/pulumi/about.go
pkg/cmd/pulumi/plugin.go
pkg/cmd/pulumi/plugin_install.go
pkg/cmd/pulumi/plugin_ls.go
pkg/codegen/schema/loader.go
pkg/engine/lifecycletest/provider_test.go
pkg/engine/lifecycletest/pulumi_test.go
pkg/engine/plugins.go
pkg/engine/plugins_test.go
pkg/engine/update.go
pkg/resource/deploy/deployment.go
pkg/resource/deploy/deploytest/languageruntime.go
pkg/resource/deploy/deploytest/pluginhost.go
pkg/resource/deploy/providers/registry_test.go
pkg/resource/deploy/source_eval.go
pkg/resource/deploy/source_query.go
sdk/go/common/resource/plugin/host.go
sdk/go/common/resource/plugin/langruntime.go
sdk/go/common/resource/plugin/langruntime_plugin.go
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_install_test.go
sdk/go/common/workspace/plugins_test.go

Reverts pulumi/pulumi#10492
This change seems to be causing TestInstallCleansOldFiles test failure on Windows, which is only qualifying master builds. Reverting temporarily.

Revert "Split PluginInfo in Info and Spec"

---

sdk/go/common/apitype/updates.go

The new fields will enable servers to decide on and indicate token expiration intervals, which in the future will allow the clients to make fewer assumptions about the token lifetime and optimize renewing tokens based on the server-provided expiration.

Add token expiration fields

---

sdk/nodejs/automation/stack.ts
sdk/nodejs/cmd/dynamic-provider/index.ts
sdk/nodejs/provider/server.ts
sdk/nodejs/tests/runtime/langhost/run.spec.ts

Improves security and should avoid tripping Windows & macOS firewall to allow `pulumi-resource-*` to accept network connections.

[sdk/nodejs] Use loopback addresses for providers & automation API

---

CHANGELOG_PENDING.md
sdk/dotnet/Pulumi.Automation/WorkspaceStack.cs

Like #10498, for dotnet. Dotnet uses the same class to provide a language host for Automation API inline & local programs, and lacks a dynamic provider, hence fewer lines changed.

[sdk/dotnet] Use loopback addresses for automation API

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/console.go

This PR fixes the `pulumi console` command to redirect the user to the stack's page in the pulumi service UI as documented.
Fixes #10508

[cli] fix `pulumi console` command

---

tests/about_test.go

The issue that https://github.com/pulumi/pulumi/pull/10378 was addressing was not fixed by that change. The regex still does not match the expected output, causing the `TestAboutCommands/json` test to fail. This PR updates that regex, so that it's correctly checking that the Go version output is a valid core semver.

test: fix regex used to test Go version output in about command.

---

CHANGELOG_PENDING.md
sdk/nodejs/automation/cmd.ts
sdk/nodejs/package.json
sdk/nodejs/tests/automation/localWorkspace.spec.ts

Fixes #10523 
Currently, there is an issue when spawning multiple child_processes at once - it's not entirely clear what's causing the issues but whatever it is, subprocesses being spawned are closing with successful exit codes and our runner / those processes' parent receives no data back from the pipes attached to them.  This replaces the `child_process` implementation with [execa](https://www.npmjs.com/package/execa) which appears to be very well supported.  It simplifies how these commands are processed and eliminates the null-stdout errors.

fix(sdk/nodejs): resolves issue with multiple parallel shell processes

---

CHANGELOG_PENDING.md
pkg/cmd/pulumi/plugin_install.go
sdk/go/common/workspace/plugins.go

With non-hex string:
```
$ pulumi plugin install resource gcp 6.35.0 --checksum boom
error: --checksum was not a valid hex string: encoding/hex: invalid byte: U+006F 'o'
```
With the wrong checksum:
```
$ pulumi plugin install resource gcp 6.35.0 --checksum c58ade076e5b84aaeef154950e6b9b907341f0747163e3f299d3fc21594baa9d
[resource plugin gcp-6.35.0] installing
Downloading plugin: 44.08 MiB / 44.08 MiB [=========================] 100.00% 7s
error: [resource plugin gcp-6.35.0] downloading from : failed to download plugin: gcp-6.35.0: invalid checksum, expected c58ade076e5b84aaeef154950e6b9b907341f0747163e3f299d3fc21594baa9d, actual c58ade076e5b84aaeef154950e6b9b907341f0747163e3f299d3fc21594baa9c
```
Made the retry logic a bit smarter to not retry checksum failures (yes it _could_ be a …

Add --checksum to `pulumi plugin install`

---

pkg/codegen/testing/test/testdata/output-funcs-tfbridge20/dotnet/Pulumi.Mypkg.csproj
pkg/codegen/testing/test/testdata/output-funcs-tfbridge20/schema.json
pkg/codegen/testing/test/testdata/output-funcs/dotnet/Pulumi.Mypkg.csproj
pkg/codegen/testing/test/testdata/output-funcs/schema.json

Update NUnit3TestAdapter used in tests to be able to test with latest SDK (M1) cc @RobbieMcKinstry to confirm the fix

[dotnet/tests] Update unit test adapter for mypkg schema

---

pkg/cmd/pulumi/up.go
pkg/cmd/pulumi/watch.go

Adds a missing space to the --secrets-provider description (Onlyused -> Only used)
Reason: not applicable
Reason: not applicable

Fix typo in --secrets-provider help message

---

scripts/get-pulumi-watch.sh

I looked at the release artifacts of a recent master build and saw these were missing.
Goreleaser expects files in `bin/darwin-x64` and so on, not `bin/darwin-amd64`.

ci: fix pulumi-watch binaries absent from release binaries

---

pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/util.go
sdk/go/common/workspace/paths.go

Simplifies some error handling by bubbling up a named & wrapped error which `pulumi destroy` can handle as a special case. Removes the need for handling a return value with an empty project and no error in commands that cannot handle that case.

refactor: simplify error handling in readProject API

---

pkg/cmd/pulumi/destroy.go

Fix lint on master with line too long

---

.github/workflows/run-codegen-test.yml

Currently downstream checks are broken because terraform-bridge used in providers has not caught up with sdk/ changes from this repo. But terraform-bridge master has caught up. This change links against terraform-bridge master and does the checks.

Fix downstream checks by using master terraform-bridge

---

CHANGELOG_PENDING.md
pkg/backend/httpstate/client/client.go
pkg/backend/httpstate/client/client_test.go

The Pulumi REST API supports GZIP compressed payloads, and we use this for `PATCH /checkpoints` and `POST /events/batch`.
We were not using it for `POST /import` or `POST /batch-decrypt`, even though both can in common cases need to upload multi-MB payloads.
We now GZIP these two payloads.
Fixes #9266.

Compress `/import` API calls to the Pulumi REST API

---

pkg/backend/httpstate/backend.go
pkg/cmd/pulumi/about.go
pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/util.go

Don't try to log into a backend for 'about', pointed out in  https://github.com/pulumi/pulumi/issues/10439#issuecomment-1219933307
Also fix about to not try and get project plugins unless we have a project. Reduces two errors to one.
Before (with 3.34.1):
```
warning: Failed to get information about the plugin: no Pulumi.yaml project file found (searching upwards from /home/fraser/projects). If you have not created a project yet, use `pulumi new` to do so
warning: Failed to read project: no Pulumi.yaml project file found (searching upwards from /home/fraser/projects). If you have not created a project yet, use `pulumi new` to do so
warning: Failed to get information about the current stack: no Pulumi.yaml project file found (searching upwards from /home/fraser/projects). If you have not …
```

Couple of 'about' improvments

---

CHANGELOG.md

I think this is what we meant to add to the changelog instead for the latest Pulumi Java release. 
Fixes #  N/A

update Pulumi Java latest release changelog item

---

CHANGELOG_PENDING.md
sdk/go/common/workspace/paths.go

The double use of the "path" variable here meant this error message looked like:
```
no Pulumi.yaml project file found (searching upwards from ). If you have not created a project yet, use `pulumi new` to do so: no project file found
```
But we want it to look like:
```
no Pulumi.yaml project file found (searching upwards from /home/fraser/projects). If you have not created a project yet, use `pulumi new` to do so: no project file found
```

Fix "no Pulumi.yaml" error message

---

pkg/cmd/pulumi/refresh.go

We should add this check two. It is exposed to the same problem.

Add additional `nil` check for `Snapshot`.

---

CHANGELOG_PENDING.md
sdk/nodejs/package.json

This PR bumps the version of TypeScript used by the NodeJS runtime (and the NodeJS SDK (`@pulumi/pulumi`)) to v3.8.3 from v3.73. 
v3.8 introduces the `import type` and `export type` syntax, which is required to use OpenTelemetry.

Bump TSC version to 3.8.3

---

CHANGELOG_PENDING.md
sdk/nodejs/automation/cmd.ts
sdk/nodejs/package.json
sdk/nodejs/tests/automation/cmd.spec.ts
sdk/nodejs/tsconfig.json

Fixes #10611
When modifying `runPulumiCmd`, we failed to continue calling `onOutput` on the new API's stdout return.  This resolves that issue.

fix(automation): runPulumiCommand failed to call onOutput when provided

---

sdk/go/common/util/rpcutil/interceptor.go

This is a little fix to the reparenting functionality. 
Before the fix, if I do `pulumi new aws-go` and `pulumi up --yes --tracing file:./up.trace` and view the trace, there is a `pulumi` trace that has most of information, and then there's many orphan traces that did not get parented to spans under `pulumi`, including 4 RegisterResource spans (2x preview/update and 2 resources: Stack and s3.Bucket).
After the fix, the RegisterResource spans are parented to preview or update spans as expected. All the others are too. So for the selected Go example there are therefore no remaining orphan spans.
I'm not sure why the previous impl stopped working as intended, but the new one is more high-level and easier to foolproof.

Fix orphan register-resource traces

---

CHANGELOG_PENDING.md
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_test.go

Debugging into the engine showed that execution appeared to query for the resource plugin `checkly/pulumi`, which is close to the NPM package name (`@checkly/pulumi`), however the resource plugin is named `checkly`. This caused Pulumi to attempt to acquire and download the plugin and fail.
This bug is specific to the nodejs language host - other languages are unaffected, as verified by converting an example program to YAML and converting to each and running a `pulumi preview`.
```yaml
name: tmp.k4AiLfczOQ
runtime: go
description: A minimal AWS Pulumi YAML program
resources:
my-bucket:
properties:
activated: true
frequency: 10
request:
method: GET
url: https://checklyhq.com
type: API
type: checkly:Check
```
Fixes #10648.

Revert "Install missing plugins when encountering them (#10530)"

---

sdk/dotnet/cmd/pulumi-language-dotnet/main.go

It seems that `dotnet run --no-build` is a bit faster if the binaries have been built already.
```
time dotnet run .                                                                                                  ~/tmp/how-does-dotnet-do-it-2
Unhandled exception. System.InvalidOperationException: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
at Pulumi.Deployment..ctor(RunnerOptions runnerOptions)
at Pulumi.Deployment.<>c.<RunAsync>b__104_0()
at Pulumi.Deployment.CreateRunnerAndRunAsync(Func`1 deploymentFactory, Func`2 runAsync)
at Program.<Main>$(String[] args) in /Users/anton/tmp/how-does-dotnet-do-it-2/Program.cs:line 5
at Program.<Main>(String[] args)
dotnet run .  1.44s user 0.36s system 139% cpu 1.290 total
[134] anton@Antons-MacBook-Pro> time dotnet …
```

Use `dotnet run --no-build`

---

pkg/cmd/pulumi/convert.go

Remove incorrect help text

---

CHANGELOG_PENDING.md
pkg/codegen/go/gen_program.go
pkg/codegen/go/gen_program_expressions.go

Fix invalid resource type on `pulumi convert` to Go

---

pkg/backend/filestate/backend.go
tests/integration/integration_test.go

Hello pulumers. I spent some hours trying to discover why my stack name was invalid, because the error message didn't mention the 100 characters limit imposed by the CLI. I had no problem in shortening the stack name, but what do you think about improving the error message?
Thanks 🙏

Improve error message about stack name validation

---

CHANGELOG_PENDING.md
pkg/codegen/go/gen.go

Fixes #10656
This PR prevents more then 500 types + associated types from residing in the same file. This should keep files less then 40,000 LOC. By comparison, the problematic file (`sdk/go/aws/wafv2/pulumiTypes.go`) has 679,162 LOC at 70M.

Chunk pulumiTypes.go

---

CHANGELOG_PENDING.md
sdk/nodejs/automation/cmd.ts
sdk/nodejs/tests/automation/cmd.spec.ts

Fixes #10611 
Originally the issue was introduced in https://github.com/pulumi/pulumi/commit/26549ab52d9ce02b7461d87dc7789524a4e8f8c4 that switched from child_process to execa library.  This accidentally dropped onOutput support. 
The fix in 10631 reintroduced onOutput support as one-shot call at the end of the process.
https://github.com/pulumi/pulumi/pull/10631/files#diff-b35ce5a8458abde54622e6fcc6d9b47f30c1cbb88c12d0e22986ca7b97e20a84R64
This PR is trying to go back to the behavior where onOutput is called with data chunks from the pulumi output stream as they arrive.

[nodejs/auto] Fix incremental behavior of onStdout

---

pkg/cmd/pulumi/new.go
pkg/engine/plugin_host.go
pkg/resource/deploy/deploytest/pluginhost.go
pkg/resource/provider/host.go
sdk/go/common/resource/plugin/plugin.go
sdk/go/common/util/rpcutil/health.go
sdk/go/common/util/rpcutil/interceptor.go
sdk/go/common/util/rpcutil/serve.go
sdk/nodejs/cmd/pulumi-language-nodejs/main.go

This PR adds an `npm-install` span to the trace as created by `pulumi new typescript --tracing file:./new.trace`, and makes sure this trace has no orphan spans.
The no-orphan-traces part includes fixes to some of our infrastructure that are riding in the same PR.
1. In the case of streaming gRPC calls like ```    rpc  InstallDependencies(InstallDependenciesRequest) returns (stream  InstallDependenciesResponse) {}```, add missing interceptors so that tracing "sees" those calls just as normal calls
2. In the case of pulumi new command, a plugin.Context was created that "forgot" about tracing setup in InitTracing, and therefore client calls to the language plugin were forgetting the parent
We're finding that `npm i` takes a long time (40s locally, 5-20 min in CI) in some cases such as …

Add tracing to `npm install` and fix orphan tracing

---

developer-docs/providers/implementers-guide.md

Reverts pulumi/pulumi#10685
Actually I might have been too hasty with the change @aq17  - reading more tests, it seems that in the URN grammar indeed module needs to be omitted, otherwise the grammar gets ambiguous with '::'. So this was correct as -written. There's something peculiar though that codegen generates type tokens that look like `example::Component` but the engine must be translating these into URN parts that read as `example:Component`.

Revert "Correct type grammar in dev docs"

---

.github/workflows/on-release.yml
.goreleaser.yml

The "on-release.yml" workflow for the v3.39.4 job failed due to a typo. Workflow here: https://github.com/pulumi/pulumi/actions/runs/3049276939
Error:
> The workflow is not valid. .github/workflows/on-release.yml (Line: 39, Col: 11): Input next-version is required, but not provided while calling. .github/workflows/on-release.yml (Line: 43, Col: 21): Invalid input, next_version is not defined in the referenced workflow.
The input parameter for `release.yml` is `next-version`, with a hyphen, not `next_version`.

ci: fix on-release script typo, clean up goreleaser.yml

---

.github/scripts/get-next-version
.github/workflows/on-release.yml

This turns the "safeties off" after validating the bors workflow and ensuring everything up to the dispatch commands succeeds.
It also fixes an error in `get-next-version` that resulted in the "vNext" PR #10701 to calculate the wrong "next version", which was corrected by hand. (The branch name and commit history is evidence of the error.)

Prep for real 3.40.0 release

---

sdk/python/lib/test/runtime/test_resource_dep_cycle.py
sdk/python/lib/test/test_broken_dynamic_provider.py
sdk/python/lib/test/test_monitor_termination.py

This fixes Windows tests failing like this due to very short (1 second) timeouts.
https://github.com/pulumi/pulumi/actions/runs/3054396239/jobs/4926314390

ci: Fix Windows flake with longer timeout

---

tests/integration/integration_go_test.go

These tests performed unnecessary refresh steps. Happened to catch these while optimizing build times. The impact on execution times was negligible.

ci: Skip refresh on tests that should fail fast

---

sdk/go/common/workspace/plugins_install_nodejs_test.go
tests/history_test.go
tests/integration/targets/targets_test.go
tests/stack_test.go

These cut execution time on myriad node tests by 5 to 30 seconds each. Linking `@pulumi/pulumi` first, before `yarn install`, enables yarn to skip downloading and extracting the node SDK before replacing it with a symlink.

ci: Use yarn link before install, ensure Pulumi latest is used

---

bors.toml

The default timeout is one hour, which our CI runs can exceed. This should give us a buffer while work is done to reduce execution time to a reasonable threshold.

ci: Increase bors timeout

---

tests/integration/integration_test.go

These tests no longer mutate environment variables, instead using `e.SetEnvVars` to only set env vars on child processes since #10263.

ci: Improve test parallelism, enabled by #10263

---

pkg/engine/lifecycletest/target_test.go

This change parallelizes subtests. Although there are only ~200 combinations tested, they are fully parallelizable and this reduces execution time for these tests from 80-100s to 10-15s each, reducing execution time for the package by about a minute or a little more. Each parent test is compute bound and already run in parallel, so the reduction isn't additive.

ci: Reduce test duration with parallel subtests

---

.github/workflows/ci-integration-test.yml
.github/workflows/ci-run-test.yml
Makefile
build/common.mk
scripts/go-test.py
scripts/retry
sdk/dotnet/Makefile
sdk/go/Makefile
sdk/nodejs/Makefile
sdk/python/Makefile

This adds a retry script to `./scripts/retry` which takes any shell command and retries it up to `PULUMI_TEST_RETRIES` times. On each iteration of the script, parallelism and variation is reduced.

ci: Enable robust retries on tests

---

.github/workflows/ci-prepare-release.yml

In the absence of key distribution or attestation of a "proper" signing key for now, this enables the "sign" job which adds checksum artifacts, sans signatures.
This leaves open the possibility of using sigstore.dev & tooling, or some other tooling to sign artifacts.
Fixes #10707.

ci: Re-enable checksums

---

.github/workflows/ci-run-test.yml
changelog/pending/20220914--ci--local-programtest.yaml
pkg/testing/integration/program.go
tests/examples/examples_test.go
tests/integration/integration_dotnet_test.go
tests/integration/integration_go_test.go
tests/integration/integration_nodejs_test.go
tests/integration/integration_python_test.go
tests/integration/query/query_test.go

These changes make integration tests run much more quickly on a local dev loop, for easily parallelized program tests like in the `integration_go_test.go` file the improvement was on the order of minutes across all tests.
The changes rely on setting `PULUMI_BACKEND_URL` to override the backend during particular tests. The backend is set to a temporary directory which is cleaned up on exit. 
A helper function `NewBackendUrl(t *testing.T)` is added to enable
When `PULUMI_TEST_USE_SERVICE=true`, the `RequireService` option is set to true.
When `RequireService == true`, the test is skipped if an access token is not present, improving local dev experience by skipping tests which would error very loudly.
When `RequireService == false and CloudURL == ""`, then we use the helper function to …

ci: Enable programtests against local backend, improve isolation

---

sdk/python/lib/test/automation/test_errors.py
sdk/python/lib/test/automation/test_isolation.py
sdk/python/lib/test/automation/test_local_workspace.py

These tests fail loudly and hard when `PULUMI_ACCESS_TOKEN` is not set, making local dev experience more brittle. Along with changes made in a future PR to enable easier local dev testing without a Pulumi service account, this will improve developer experience when running `make` in the repo.

ci: Skip Python service tests when access token is absent

---

pkg/testing/integration/program.go

These options were previously added without also adding the override handling in `With`.

Add missing `ProgramTestOptions` overrides in `With`

---

.github/workflows/ci-run-test.yml

Hopefully this will improve our merge queue success rates on Windows

Change GO_TEST_PARALLELISM to improve Windows CI

---

pkg/testing/integration/program.go

Similar to what Automation API does. It does not look like Automation API does any escaping so perhaps this is OK. The change saves lots of precious seconds on CI when a lot of examples and config values are involved, like in pulumi/templates.

Use set-all

---

changelog/pending/20220915--sdk-go--serde-for-nil-resource-refs.yaml
sdk/go/pulumi/provider.go
sdk/go/pulumi/provider_test.go
sdk/go/pulumi/rpc.go

This fixes the `pulumi-go-provider/examples/random-login` example. Previously, it panicked on the RPC layer.

Serde `<Resource><nil>` pointers correctly

---

Makefile
scripts/brew.sh
scripts/get-language-providers.sh
scripts/get-pulumi-watch.sh
scripts/prep-for-goreleaser.sh

This enables `make brew` to run as before, accounting for directory changes. The prep-for-goreleaser script places artifacts in `./bin/` now.
`make brew` now succeeds.
Fixes #10735

ci: Fix make brew

---

README.md

Update the python and go versions to match the currently supported minimum versions.
@AaronFriel pointed out to me the other day that Golangs supported version text is a bit hard to parse but it means only the latest two releases are supported (i.e. 1.18 and 1.19).

Update supported versions in README.md

---

pkg/cmd/pulumi/up.go
tests/integration/integration_go_test.go

Looking at detailed performance traces I noticed we call exportStack twice on every update. This can get expensive if stacks are large, and creates extra service traffic. This quick fix makes it only happen if --target like options are specified.

Do not call exportStack twice on every update

---

sdk/nodejs/tests/runtime/langhost/cases/070.unusual_alias_names/index.js
sdk/nodejs/tests/runtime/langhost/cases/071.large_alias_counts/index.js
sdk/nodejs/tests/runtime/langhost/cases/072.large_alias_lineage_chains/index.js
sdk/nodejs/tests/runtime/langhost/run.spec.ts

Fixes #10053 
Adds a few tests (one skipped) to replicate some issues we've been seeing in aliasing.  The skipped test (and the slow unskipped test) should be resolved by #9734

chore(sdk/nodejs): Adds tests for resource alias combinations

---

sdk/nodejs/automation/minimumVersion.ts
sdk/nodejs/cmd/run/tracing.ts
sdk/nodejs/provider/internals.ts
sdk/nodejs/runtime/debuggable.ts
sdk/nodejs/runtime/index.ts
sdk/nodejs/runtime/settings.ts
sdk/nodejs/tsutils.ts

These exported APIs aren't intended for public use. Marking them as `@internal` makes TypeScript remove them from the `.d.ts` files and removes them from our SDK docs.

[sdk/nodejs] Mark internal APIs `@internal` to filter from SDK docs

---

sdk/dotnet/Pulumi.Automation/LocalWorkspaceOptions.cs
sdk/dotnet/Pulumi.Automation/Pulumi.Automation.xml
sdk/dotnet/Pulumi.Automation/Workspace.cs
sdk/nodejs/automation/localWorkspace.ts
sdk/nodejs/automation/workspace.ts
sdk/python/lib/pulumi/automation/_workspace.py

Updates an outdated docstring link I stumbled across while using Pulumi Automation API. 
There is no existing issue.
This is a non-code change and I believe it could be labeled `impact/no-changelog-required`; as such I have not made Changelog updates as per the [updated guidelines](https://github.com/pulumi/pulumi/commit/385d08218a5806c3389dd0a4b565a28b3fecf2a6). If I am mistaken please let me know!

Update automation api secrets provider docstring link

---

changelog/pending/20220920--cli-plugin--dont-retry-plugin-downloads.yaml
sdk/go/common/workspace/plugins.go

Don't retry downloads on 403 and 404s responses

---

.github/workflows/ci-prepare-release.yml

Re-enables creating a `pulumi-${version}-checksum.txt` on release.
The s3 blob upload will upload this to S3 as it's configured to upload any artifact in the release prefixed with `pulumi-`:
https://github.com/pulumi/pulumi/blob/bce637624e00b610c213f4f60fe1dd17aa8513b2/.github/workflows/release.yml#L130-L137
Resolves #10807

Re-enable prior release process's checksums

---

changelog/pending/20220921--engine--analyzer-bundled.yaml
sdk/go/common/workspace/plugins.go

Fixes discovering these plugins if the directory "pulumi[.exe]" is in is not on PATH.

Add pulumi-analyzer-policy and pulumi-analyzer-policy-python to the list of bundled plugins

---

scripts/get-job-matrix.py
sdk/go/common/workspace/plugins_install_test.go

These tests pass on my Windows device, perhaps due to some more systemic fix with path handling.
Resume running these tests.
Resolves #8649

ci: Re-enable Windows tests with temp dir

---

.github/workflows/ci-info.yml

When I wrote this check there were no draft releases or my GITHUB_TOKEN token was unauthenticated and so didn't see the draft releases.
Now that we're using merge queues for release processes, and the GITHUB_TOKEN is valid, we need to check if it's published or it's still a draft. This will clear this misleading error on staging workflows:

ci: Remove a misleading error message on merge queue workflows

---

scripts/get-job-matrix.py

`go test -list` and `go list` both require the underlying code to compile, this improves the error message when the "matrix" job fails by providing a helpful direction.

ci: Improve feedback when matrix failure is due to Go compilation failure

---

.github/workflows/ci.yml
.github/workflows/on-community-pr.yml
.github/workflows/on-pr-changelog.yml
.github/workflows/pr-test-acceptance-on-dispatch.yml

Fixes a couple issues with our community contribution workflows:
* The ref for calculating changelogs should be the merge ref, the `github.ref` variable is the wrong value, given that it evaluated to `refs/head/master`: https://github.com/pulumi/pulumi/actions/runs/3071146998/jobs/4961576379#step:1:31
* The changelog comment on the dispatch job was redundant
* The CI job needs a GitHub token and Pulumi access token, so those are made explicit. Existing workflow calls to `ci.yml` use `secrets: inherit` to pass these down transparently. For contributor workflows, we prefer to be explicit. This ensures the workflow doesn't have access to, e.g., AWS tokens.

ci: fix community contributor workflow

---

changelog/pending/20220922--cli--fix-tracing-http-resp-parse.yaml
pkg/backend/httpstate/client/api.go
pkg/backend/httpstate/client/client.go

Pulumi preview seemed to hang for 26s+ on a large stack and a slow network connection, while --tracing was not showing anything to account for these 26s. As it turns out there was a bug that excluded the time it took to transfer the response body over the network and parse it, specifically affecting ExportStack operation in the program. 
This now fixed for all HTTP-related operation spans.

Ensure response parsing is included in HTTP client trace spans

---

changelog/pending/20220921--sdk-nodejs-python--get-org.yaml
sdk/dotnet/Pulumi/Deployment/Deployment.cs
sdk/dotnet/Pulumi/Deployment/DeploymentInstance.cs
sdk/dotnet/Pulumi/Deployment/Deployment_Inline.cs
sdk/dotnet/Pulumi/Deployment/IDeployment.cs
sdk/dotnet/Pulumi/Testing/TestOptions.cs
sdk/nodejs/metadata.ts
sdk/nodejs/runtime/settings.ts
sdk/python/lib/pulumi/automation/_server.py
sdk/python/lib/pulumi/metadata.py
sdk/python/lib/pulumi/policy/__main__.py
sdk/python/lib/pulumi/provider/server.py
sdk/python/lib/pulumi/runtime/proto/provider_pb2.pyi
sdk/python/lib/pulumi/runtime/settings.py
tests/integration/stack_reference/dotnet/Program.cs
tests/integration/stack_reference/dotnet/step1/Program.cs
tests/integration/stack_reference/dotnet/step2/Program.cs
tests/integration/stack_reference_secrets/dotnet/step2/Program.cs

Changes `getOrganization` to return "organization" by default. This will apply when using filestate, or by default in unit tests (unless explicitly set as part of test setup).

Make getOrganization total, default to 'organization'

---

pkg/codegen/pcl/rewrite_convert.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/discriminated-union-pp/discriminated-union.pp
pkg/codegen/testing/test/testdata/discriminated-union-pp/dotnet/discriminated-union.cs
pkg/codegen/testing/test/testdata/discriminated-union-pp/nodejs/discriminated-union.ts
pkg/codegen/testing/test/testdata/discriminated-union-pp/python/discriminated-union.py

Examples in our docs that use discriminated unions to determine `...Input` types are broken, e.g., pulumi/pulumi-azure-native#1960.
Debugging this, I found that the discriminator is expected to be a string, but it is (in this case) a *string wrapped in a __convert call. This patch simply tries both cases.
Submitting this as a speculative draft PR because I'm new to this area and don't know if this is the best approach to fix the issue. Maybe the `__convert(*string)` should be resolved to a plain string before the lookup?
Apologies for the whitespace changes, gofmt 1.19 will do that.

Resolve discriminated unions when the discriminator is a string pointer

---

changelog/pending/20220922--engine--fix-cmd.yaml
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_install_test.go

Always return a PluginInfo with a path.
Merge SetSchemaMetadata into SetFileMetadata.
Specifically check for .exe in windows test.
Try to find an existing file for the reported plugin path. Fallback to plugin.exe if we can't find one.
Should allow https://github.com/pulumi/pulumi/pull/10805 to merge without test failures.

Support .cmd executables for plugins on Windows

---

changelog/pending/20220921--programgen--options-dot-version.yaml
pkg/codegen/dotnet/gen_program.go
pkg/codegen/dotnet/gen_program_test.go
pkg/codegen/go/gen_program_test.go
pkg/codegen/importer/hcl2_test.go
pkg/codegen/importer/language_test.go
pkg/codegen/nodejs/gen_program.go
pkg/codegen/nodejs/gen_program_test.go
pkg/codegen/pcl/binder.go
pkg/codegen/pcl/binder_resource.go
pkg/codegen/pcl/binder_schema.go
pkg/codegen/pcl/binder_schema_test.go
pkg/codegen/pcl/binder_test.go
pkg/codegen/pcl/invoke.go
pkg/codegen/python/gen_program.go
pkg/codegen/python/gen_program_test.go
pkg/codegen/python/utilities_test.go
pkg/codegen/schema/loader.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/aws-resource-options-pp/aws-resource-options.pp
pkg/codegen/testing/utils/host.go

Running pulumi convert when a resource has options.version specified does not generate corresponding code that sets the version on the resource
Fixes #10195 
Fixes #10358

Support options.version on pulumi convert

---

changelog/pending/20220921--sdk-go--org-name.yaml
sdk/go/pulumi-language-go/main.go
sdk/go/pulumi/context.go
sdk/go/pulumi/mocks.go
sdk/go/pulumi/run.go
tests/integration/integration_go_smoke_test.go
tests/integration/stack_reference/go/main.go
tests/integration/stack_reference/go/step1/main.go
tests/integration/stack_reference/go/step2/main.go

Adds organization name to the gosdk.
Part of https://github.com/pulumi/pulumi/issues/2800.

Add Organization to go sdk

---

pkg/cmd/pulumi/new.go
pkg/codegen/go/gen_program.go
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/pcl/binder_test.go
pkg/codegen/schema/docs_test.go
pkg/codegen/testing/test/testdata/aws-s3-folder-pp/go/aws-s3-folder.go
pkg/codegen/utilities.go
pkg/testing/integration/util.go
sdk/go/common/util/fsutil/copy.go
sdk/go/common/util/fsutil/walkup.go
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/templates.go
sdk/nodejs/cmd/pulumi-language-nodejs/main.go
tests/stack_test.go

This PR replaces all `ioutil.ReadDir` to `os.ReadDir`. `ioutil.ReadDir` has been deprecated in Go 1.16. The new `os.ReadDir` is a more efficient implementation than `ioutil.ReadDir`. 
The full proposal can be read here: https://github.com/golang/go/issues/41467
Reference: https://pkg.go.dev/io/ioutil#ReadDir

refactor: use `os.ReadDir` for lightweight directory reading

---

pkg/go.mod
pkg/secrets/cloud/manager.go

We'd [previously removed](https://github.com/pulumi/pulumi/pull/6379) the direct dependency on `github.com/pkg/errors` in the `pkg` module, but a [community PR brought it back](https://github.com/pulumi/pulumi/pull/6379). This change removes it once again, as it's not needed for wrapping the errors in these cases.

Remove dependency on `github.com/pkg/errors` in `pkg` module

---

README.md

This PR fixes dotnet logo URL in README.md.
Current URL is showing a 404 error.

Fix dotnet logo URL in README.md

---

pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/aws-lambda-pp/aws-lambda.pp
pkg/codegen/testing/test/testdata/aws-lambda-pp/python/aws-lambda.py
pkg/codegen/testing/test/testdata/azure-native-pp/azure-native.pp
pkg/codegen/testing/test/testdata/azure-native-pp/dotnet/azure-native.cs
pkg/codegen/testing/test/testdata/azure-native-pp/nodejs/azure-native.ts
pkg/codegen/testing/test/testdata/azure-native-pp/python/azure-native.py

These were discovered when the typechecking was improved in Pulumi YAML.
We discovered we were missing some required fields in our examples when https://github.com/pulumi/pulumi-yaml/pull/350 was merged. This PR updates the pu/pu copy of the tests.

Add missing fields to PCL tests

---

.github/workflows/trigger-homebrew-event.yml

GitHub removed `brew` from the path:
- https://github.com/actions/runner-images/issues/6283
This change should be reviewed and after it merges, we should be able to run the following command with an appropriate access token to trigger the workflow and publish 3.40.2:
```shell
pulumictl create homebrew-bump "3.40.2" "$(git rev-parse v3.40.2)"
```
Resolves #10860

ci: Reenable Brew publishing after GH runners removed brew from path

---

.github/workflows/release-homebrew-tap.yml

In #10861, the homebrew tap update failed due to PULUMI_VERSION being undefined. The env var was not declared on all of the steps needed.
Moves the env var declaration up, and makes a few tweaks and removes a `git push` that should not have been run when dry-run is false.
After this is merged, we should be able to trigger it manually [via the GitHub Workflow page]( https://github.com/pulumi/pulumi/actions/workflows/release-homebrew-tap.yml) to verify that the changes work.
Resolves #10861.

ci: Fix env, script cleanup on homebrew tap release action

---

sdk/python/lib/pulumi/runtime/resource.py

Fixes #10885.
I'm not sure how to construct a test that would truly validate this - it would require timing a Child resource construction that occurred in the middle of the dependency resolution, due to the interleaving of async work.

[sdk/python] Prevent set change during iteration errrors

---

changelog/pending/20220930--cli--eject-dont-panic.yaml
pkg/cmd/pulumi/convert.go

Pass an owned loader to yamlgen.Eject for convert

---

sdk/python/.gitignore
sdk/python/Makefile
sdk/python/lib/setup.py

This commit modifies `setup.py` to use a Python variable as the source of the package version instead of a placeholder string and adds a fallback for the README definition. This makes the package installable via the `-e` flag directly from its source directory (`sdk/python/lib`), rather than having a build step and having to `-e` install the built directory (`sdk/python/env/src`).
This is equivalent to some changes we've made in our generated Python provider SDKs (#7097 and #7479), making the core SDK consistent with those.

[sdk/python] Allow editable installs without build step

---

pkg/cmd/pulumi/pulumi.go

suggests setting PULUMI_SKIP_UPDATE_CHECK in the log statement.
Fixes #10292

suggest setting PULUMI_SKIP_UPDATE_CHECK when error fetching latest version #10292

---

sdk/go/common/apitype/updates.go

Add API shape for PatchUpdateCheckpointDeltaRequest for the service to ingest. Pulled from prototyped branch https://github.com/pulumi/pulumi/compare/t0yv0/efficient-patch-protocol
Parent story: https://github.com/pulumi/home/issues/1768

Add api type for PatchUpdateCheckpointDeltaRequest

---

changelog/pending/20220927--sdk-go--install-deps-1-18.yaml
sdk/go/pulumi-language-go/main.go

As go 1.17 is out of support, it falls outside our support window. However, we may still want to remove the `-compat=1.18` flag passed to `go mod tidy` to allow best effort support for whichever the current Go version is.

fix: Best effort support for Go versions below 1.18

---

changelog/pending/20220928--sdk-go--unsafe-await.yaml
sdk/go/pulumi/types.go
sdk/go/pulumi/types_test.go

Barring implementation of #4834 or this PR, conditionally creating resources in a component provider requires creating resources inside of an Apply, which we strongly recommend against. While both provide workarounds, this new API may be more ergonomic to use - when used correctly - to conditionally create child resources.
A struct return type is used to avoid confusion of the adjacent boolean return values `known` and `secret`.

sdk/go: Enable unsafe await of Output values in Go SDK

---

changelog/pending/20221001--cli-about-plugin--rm-github-experimental.yaml
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_test.go

Remove experimental support of github releases for plugin sources. We now have support for this via `github:` download urls.

Remove experimental github support

---

pkg/testing/integration/program.go

Expands the scope of `integration.ProgramOptions.ExpectFailures` to enable https://github.com/pulumi/pulumi-yaml/pull/360.

Add expectFailure to another case

---

pkg/backend/filestate/crypto.go
pkg/backend/httpstate/crypto.go
pkg/cmd/pulumi/crypto.go
pkg/cmd/pulumi/crypto_cloud.go
pkg/cmd/pulumi/util.go

Don't do config path resolution deep in the secret managers, expect paths to be resolved higher up.

Require a config path to be passed to NewSecret methods

---

changelog/pending/20221004--sdk-python--python-format.yaml
sdk/python/lib/pulumi/output.py
sdk/python/lib/test/test_output.py

Add Output.format to python SDK

Add Output.format to python SDK

---

.github/workflows/release-homebrew-tap.yml

Fixes the issue where the `gh` CLI reported that no token was present: https://github.com/pulumi/pulumi/actions/runs/3145787399/jobs/5113494314

ci: Enable gh cli in every step of job

---

.vscode/settings.json
pkg/cmd/pulumi/convert.go
pkg/cmd/pulumi/convert_test.go
pkg/cmd/pulumi/convert_testdata/.gitignore

This moves the bulk of the convert logic into a function that can be run in a unit test, along with a trivial unit test entry point.
This codifies the approach I've used (writing micro programs after modifying `convert.go`) to debug panics in Pulumi YAML.

Refactor convert command to add entrypoint for pulumi convert debugging

---

sdk/go/pulumi/internals.go
sdk/go/pulumi/internals/outputs.go
sdk/go/pulumi/internals/outputs_test.go
sdk/go/pulumi/types.go
sdk/go/pulumi/types_test.go

Following internal discussion, expose this function on a separate package: `sdk/v3/go/pulumi/internals`.

sdk/go: Move unsafe API to internals package

---

sdk/go/common/apitype/updates.go

Expose a new API that accepts an UntypedDeployment not as a struct but as a json.RawMessage, as a part of delta checkpoint work:
If the CLI is able to pass to the service the entire UntypedDeployment in a json.RawMessage that the service can dump directly into S3, then we gain two things:
1. The service doesn’t need to marshal anything before writing to S3 (saving time and also renders the concern about encoding/json compacting input obsolete)
2. We can better guarantee that the UntypedDeployment written in S3 service-side is exactly as the CLI expects it to be formatted, rather than implicitly trust that the service team is marshalling and formatting the checkpoint file into S3 correctly
For full background context: https://github.com/pulumi/pulumi-service/issues/10292
Relevant slack …

Add PatchUpdateUntypedCheckpointRequest API shape

---

.github/scripts/generate-homebrew-tap

To prevent bad commits like https://github.com/pulumi/homebrew-tap/commit/cf74ca655dfa00411779c16862633e65ba0e3672 when running locally.

Fix .github/scripts/generate-homebrew-tap to export PULUMI_VERSION

---

changelog/pending/20221004--docs--more-flexible-doc-parsing.yaml
pkg/codegen/docs/examples.go
pkg/codegen/docs/gen_test.go

Allow more flexible parsing when extracting examples from descriptions

---

.github/workflows/download-pulumi-cron.yml

Add winget and msi install checks in download cron job

---

changelog/pending/20221006--cli-new--fix-ado-repos.yaml
sdk/go/common/util/gitutil/git.go
sdk/go/common/workspace/templates.go

Small path bug, "git clone" by default clones to a new folder based on the last part of the repo name. So running something like `pulumi new https://fraser0275@dev.azure.com/fraser0275/fraser/_git/fraser` resulted in us making a folder like /tmp/pulumi-templates-1234/fraser with all the templates in it. That last part of the path was unexpected, because when we use gogit it clones directly into the target directory we give it.
Simple fix to just add `.` to the git clone command. I also added some logging while I was about here, given it helped me work out this issue.
Fixes https://github.com/pulumi/pulumi/issues/10886

Fix cloning from ADO repos

---

changelog/pending/20221006--cli-new--issue-10484.yaml
pkg/cmd/pulumi/destroy.go

Addresses issue https://github.com/pulumi/pulumi/issues/10484
- _There does not appear to be a `./pkg/cmd/pulumi/destroy_test_.go` file, and so I did not create one. I sanity-tested that existing commands are not affected, and that the requested use-case(s) work: example `pulumi destroy --remove` and `pulumi destroy --yes --remove`_

feat(cli): add --remove flag to pulumi destroy

---

pkg/backend/httpstate/backend.go
pkg/cmd/pulumi/login.go
pkg/cmd/pulumi/policy_publish.go
pkg/cmd/pulumi/util.go

Do for the login functions (`Login` and `Current`) what https://github.com/pulumi/pulumi/pull/9310 did for the backend client. This provides a way to customize the login behavior. This adds a `LoginManager` interface, with `Login` and `Current` methods. The `NewLoginManager` function returns a `defaultLoginManager` instance, and to modify which `LoginManager` implementation is returned, the `newLoginManager` function can be reassigned in an init function within the `httpstate` package. 

refactor: create a LoginManager interface for encapsulating backend logins

---

pkg/codegen/pcl/binder_resource.go

Direct access to entries is both not threadsafe and failes without version support.
This allows Pulumi YAML to depend on 3.41.1. Without this change tests fail.

Use loadPackageSchema instead of accessing entries

---

pkg/backend/apply.go

This check isn't needed so we can simplify to just an else block. `plan` will be nil if ExperimentalPlans is turned off.

Remove an unneeded check for ExperimentalPlans

---

sdk/go/common/workspace/project.go
sdk/go/common/workspace/project_test.go

"expected an object" isn't very informative, "expected project to be an object, was 'string'" is much better.

Improve the error message for Pulumi.yaml with wrong type of data

---

changelog/pending/20221009--cli--project-path-error.yaml
sdk/go/common/workspace/loaders.go
sdk/go/common/workspace/project_test.go
sdk/go/common/workspace/templates.go
tests/integration/integration_test.go

It's not always clear _which_ project we're loading (especially when iterating template directories), so this adds the project path to the error message and also clarifies which part of project loading failed (e.g. no marshaller, failed validation, etc).

Wrap project load errors with the path that failed

---

pkg/backend/backend.go
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/up.go
pkg/engine/deployment.go
pkg/engine/lifecycletest/pulumi_test.go
pkg/engine/update.go
pkg/resource/deploy/deployment.go
pkg/resource/deploy/step_executor.go
pkg/resource/deploy/step_generator.go

This option is just used to control if a plan is generated or not, we'll continue to use it even after plans are no longer experimental. No need to generate a plan if it's not being used at all (e.g. during `up`).

Rename ExperimentalPlans to GeneratePlan

---

changelog/pending/20221006--sdkgen-go--module-path.yaml
pkg/codegen/go/gen_program.go
pkg/codegen/go/gen_program_test.go
pkg/codegen/go/importer.go
pkg/codegen/pcl/binder_resource.go
pkg/codegen/pcl/binder_test.go
pkg/codegen/schema/loader.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/modpath-pp/go/modpath.go
pkg/codegen/testing/test/testdata/modpath-pp/modpath.pp
pkg/codegen/testing/test/testdata/other.json
pkg/codegen/testing/test/testdata/third-party-package-pp/go/third-party-package.go

Add `modulePath` to the schema

---

changelog/pending/20221006--cli-display--update-time-elapsed.yaml
pkg/backend/display/progress.go

Fixes #10534 
This PR modifies the display to show the time that a resource takes to update.
[![asciicast](https://asciinema.org/a/XHYWenULkugoY57kStsadcBH8.svg)](https://asciinema.org/a/XHYWenULkugoY57kStsadcBH8)

show time elapsed per resource in update

---

.github/workflows/download-pulumi-cron.yml

Not exactly sure if this will work but only one way to find out.

Add install winget cli step to download cron job before using winget to download pulumi

---

pkg/testing/integration/program.go

The first commit removes a redundant check to skip the test in `prepareProgram`, given the check in `newProgramTester`:
https://github.com/pulumi/pulumi/blob/2b1b4fb0b4d6d2c32cd1303957babc2942703eb4/pkg/testing/integration/program.go#L761-L769
The second refactors the two functions, given that both are private to the test package and `prepareProgram` is called if and only if it's immediately followed by `newProgramTest`. The former is now a side-effecting function that mutates its options, the latter is a pure constructor.

ci: Unblock local ProgramTest usage

---

.github/workflows/ci-build-sdks.yml
.github/workflows/ci-lint.yml
.github/workflows/ci-run-test.yml
.github/workflows/ci-test-docs-generation.yml
.github/workflows/release.yml

Resolves #10997 
Disables this step and leaves a pointer to #11000 to implement in November when .NET 7 is released.

fix(ci): Disable setup-dotnet action, rely on globally installed dotnet

---

changelog/pending/20221011--backend-service--httpstate-backend-patch-protocol.yaml
pkg/backend/httpstate/client/api.go
pkg/backend/httpstate/client/api_endpoints.go
pkg/backend/httpstate/client/client.go
pkg/backend/httpstate/client/client_test.go
pkg/backend/httpstate/client/marshal.go
pkg/backend/httpstate/diffs.go
pkg/backend/httpstate/marshal.go
pkg/backend/httpstate/snapshot.go
pkg/backend/httpstate/snapshot_test.go
pkg/backend/httpstate/token_source.go
pkg/go.mod
pkg/go.sum
sdk/go/common/apitype/updates.go

Fixes #3930 (the client side updates)
Introduces a protocol for saving state that uses text diffs over slightly-indented JSON. The client changes are currently behind a feature flag PULUMI_OPTIMIZED_CHECKPOINT_PATCH=true. When Pulumi service deploys the corresponding endpoints, this functionality will start to be available for the users opting into the flag.
Besides tests added in the PR we have ran some end-to-end tests manually against an experimental service deployment with @caseyyh to make sure the client and the server are aligned on the protocol.

Introduce an efficient text-diff based patch protocol

---

changelog/pending/20221012--cli-display--fix-gocloud-stderr.yaml
pkg/cmd/pulumi/pulumi.go

This is all very sad and makes me miss [ILogger](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.ilogger) from the dotnet world 😞 
Fixes https://github.com/pulumi/pulumi/issues/10996
Ignore the fact that this blob doesn't work, but note how it doesn't print "azureblob" at the start anymore.
```
fraser@IBASA-PC:~/projects/example$ ~/.pulumi/bin/pulumi login azblob://badblob?storage_account=fraser
2022/10/12 18:06:42 azureblob: constructed service URL: https://fraser.blob.core.windows.net
2022/10/12 18:06:42 azureblob.URLOpener: using NewDefaultAzureCredential
error: problem logging in: unable to check if bucket azblob://badblob?storage_account=fraser is accessible: blob (code=Unknown): GET https://fraser.blob.core.windows.net/badblob …
```

Redirect 'log' output to 'logging'

---

changelog/pending/20221009--programgen-dotnet--pcl-annotate-resource-inputs-apply-property-overrides.yaml
pkg/codegen/dotnet/gen_program.go
pkg/codegen/dotnet/gen_program_expressions.go
pkg/codegen/hcl2/model/expression.go
pkg/codegen/pcl/binder_resource.go
pkg/codegen/testing/test/testdata/kubernetes-pod-pp/dotnet/kubernetes-pod.cs
pkg/codegen/testing/test/testdata/kubernetes-pod-pp/go/kubernetes-pod.go
pkg/codegen/testing/test/testdata/kubernetes-pod-pp/kubernetes-pod.pp
pkg/codegen/testing/test/testdata/kubernetes-pod-pp/nodejs/kubernetes-pod.ts
pkg/codegen/testing/test/testdata/kubernetes-pod-pp/python/kubernetes-pod.py

For `pcl.GetSchemaForType` to work on `model.ObjectConsExpression`, the type of the expression need to be annotated with its associated schema type. So I've implemented `pcl.AnnotateResourceInputs` which annotates resource inputs but also their deeply nested object properties, making the schema type information available for expressions of type `model.ObjectConsExpression`, then using this information to apply property name overrides in dotnet programgen
> I believe I will use this in java program-gen as well, it will simplify a lot of code 
Fixes #10671 
TODO: requires #10958 to be merged first because I need the `annotateObjectProperties` function implemented there :)

[codegen] Implement pcl.AnnotateResourceInputs and apply property overrides for deeply nested objects

---

pkg/cmd/pulumi/stack.go

Rather than display some potentially confusing output, only show the update time and Pulumi version used to deploy it when those values are present.
Improves code readability by following current variable styling.
On an empty stack, the display now appears as:
```
$ pulumi stack
Current stack is dev:
Owner: friel
Current stack resources (0):
No resources currently in this stack
```
Instead of:
```
$ pulumi stack
Current stack is dev:
Last update time unknown
Pulumi version: ?
Owner: friel
Current stack resources (0):
No resources currently in this stack
```

cli: Clean up `pulumi stack` output for non-deployed stacks

---

changelog/pending/20221013--cli-package--get-schema-handle-dirs.yaml
pkg/cmd/pulumi/package.go

This allows us to distinguish between ./myProvider (execute the binary at path) and myProvider (execute the installed plugin called myProvider).
Fixes #11014

Require a path separator for path based binaries.

---

changelog/pending/20221011--cli-import--import-union-types-pcl-10934.yaml
pkg/codegen/importer/hcl2.go
pkg/codegen/importer/hcl2_test.go

[import] Handle importing resource properties of type Union

---

changelog/pending/20221014--sdk-go--avoid-backfilling-property-deps-go.yaml
pkg/resource/deploy/source_eval.go
sdk/go/pulumi/rpc.go
sdk/go/pulumi/rpc_test.go

Two changes:
Change the Go SDK to always send a filled-in property dependencies map, which is consistent with all of the other language SDKs. This prevents the engine from backfilling an empty map with explicit dependencies specified in the `pulumi.DependsOn` `ResourceOption`.
**Node.js:**
https://github.com/pulumi/pulumi/blob/a4dbd1da4fb0b5df716aeda56f9caf7d2d5175e4/sdk/nodejs/runtime/rpc.ts#L140-L143
**Python:**
https://github.com/pulumi/pulumi/blob/a4dbd1da4fb0b5df716aeda56f9caf7d2d5175e4/sdk/python/lib/pulumi/runtime/rpc.py#L211-L223
**.NET:**
https://github.com/pulumi/pulumi/blob/a4dbd1da4fb0b5df716aeda56f9caf7d2d5175e4/sdk/dotnet/Pulumi/Deployment/Deployment_Serialization.cs#L79-L83
**Java:**
https://github.com/pulumi/pulumi-java/blob/33e2d98ad96890937f5374e7b6699fc518edfc19/sdk/java …

Avoid backfilling property deps for Go

---

pkg/testing/integration/program.go

Unblocks Azure Native usage of ProgramTests in Go, resolves #11050's example by permitting usage such as:
```go
func genReplace(t *testing.T, subPkg string) string {
moduleDir, err := filepath.Abs(fmt.Sprintf("../pulumi-azure-native-sdk/%s", subPkg))
require.NoError(t, err)
return fmt.Sprintf("github.com/pulumi/pulumi-azure-native-sdk/%s=%s", subPkg, moduleDir)
}
func getGoBaseOptions(t *testing.T) integration.ProgramTestOptions {
base := getBaseOptions(t)
baseGo := base.With(integration.ProgramTestOptions{
Dependencies: map[string]string{
genReplace("aad"),
},
})
return baseGo
}
```
Resolves #11050

feat(programtest): Enable ProgramTest for Azure-Native split modules

---

CHANGELOG.md

This PR changes occurrences of `pulls` in the CHANGELOG to `pull`, fixing broken links generated before [this bug fix](https://github.com/AaronFriel/go-change/pull/17).

Change occurances of pulls to pull, fix broken URL

---

changelog/pending/20221017--sdk-nodejs--fix-ts-all-types.yaml
sdk/nodejs/output.ts

Using `all` currently looses type safety around the handling of input values which are possibly undefined. By adding the explicit undefined option to each argument, the undefined case outside the inputty type does not get captured.
By removing the explicit `undefined` cases, the undefined is captured by the generic parameter and correctly carried through to the output type.
For example, if an input to `all` is possibly undefined, the value after `all` won't be labeled as possibly undefined.
```typescript
// pulumi.Input<string> | undefined
let input = possiblyUndefinedInput();
// pulumi.Output<string>
let original = pulumi.all([input])[0];
// pulumi.Output<string | undefined>
let newBehaviour = pulumi.all([input])[0];
function possiblyUndefinedInput(): pulumi.Input<string> | undefined { …
```

Remove undefined cases from inputs to `all` function

---

changelog/pending/20221017--sdk-go--decode-ptr-asset-and-ptr-archive-values.yaml
sdk/go/common/resource/mapper_test.go
sdk/go/common/util/mapper/mapper_decode.go

We handle ptr sources in deserialization. This is necessary since `pulumi.New*Asset` and `pulumi.New*Archive` return `*resource.Asset` and `*resource.Archive` respectively.
This will fix https://github.com/pulumi/pulumi-command/issues/143 when it is picked up.

Allow decoding *asset and *archive values

---

changelog/pending/20221014--programgen--gen-errs.yaml
pkg/codegen/report/report.go
pkg/codegen/report/report_test.go
pkg/codegen/schema/loader.go

This PR introduces a shared format for reporting codegen problems.
Fixes #10988

Add standardized program-gen reporting helpers

---

sdk/nodejs/.eslintrc.js

I often open VS Code in the root `pulumi/pulumi` directory, and when I do that and edit any `sdk/nodejs` files, eslint complains with:
> Parsing error: File '/users/user/go/src/github.com/pulumi/pulumi/tsconfig.json' not found.
This is because it looks for `tsconfig.json` in the current working directory by default. To fix this, `tsconfigRootDir` can be set in `.eslintrc.js`.

[sdk/nodejs] Avoid eslint error in VS Code

---

pkg/resource/deploy/source_eval.go
sdk/nodejs/runtime/resource.ts

This improves the error message for https://github.com/pulumi/pulumi-awsx/issues/930.

Improve the error for a denied component provider

---

changelog/pending/20221020--cli-import--only-trigger-an-import-when-necessary-during-refresh.yaml
pkg/cmd/pulumi/refresh.go

Only trigger an import when needed during refresh

---

pkg/cmd/pulumi/new_smoke_test.go
pkg/cmd/pulumi/new_test.go
pkg/cmd/pulumi/policy_new_smoke_test.go
pkg/cmd/pulumi/policy_new_test.go
tests/examples/examples_smoke_test.go
tests/examples/examples_test.go

Mitigate test timeouts on Windows ([recent job that timed out](https://github.com/pulumi/pulumi/actions/runs/3276024063)) and long test delays due to non-parallelizable tests on macOS. For context: integration tests run on Linux and run all tests, the smoke tests are a subset of tests that run on macOS & Windows which set the build tag "smoke", causing some test files to be skipped. These tests tend to come in pairs of files, `_test.go` and `_smoke_test.go`.
This PR fixes the `examples_test.go` which had the build flags reversed, and moves one test which checks stdout behavior to the smoke tests.
This PR also adds smoke test files for `pkg/cmd` to move some tests onto the Linux runners only, which we run with greater parallelism. This removes some of the slower and non-parallelizable …

ci: Implement smoke tests for pkg/cmd, fix examples smoke tests

---

scripts/get-job-matrix.py

Node 19 is released: https://nodejs.org/en/blog/announcements/v19-release-announce/

ci: Begin testing against node 19.x

---

pkg/resource/deploy/source_eval.go

This is invoked on getResource requests for stack templates.

Don't block the pulumi package

---

changelog/pending/20221022--sdk-python--python-runtime-now-respects-parallel-flag.yaml
sdk/python/cmd/pulumi-language-python-exec
sdk/python/lib/pulumi/runtime/settings.py

This PR sets the default futures executor to use the `--parallel` flag to determine thread count.
Fixes #1116

[SDK/Python] Respect --parallel flag

---

changelog/pending/20221019--engine--fix-type-validation-of-stack-config-with-secure-values.yaml
pkg/cmd/pulumi/config.go
pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/logs.go
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/refresh.go
pkg/cmd/pulumi/up.go
pkg/cmd/pulumi/watch.go
pkg/secrets/b64/manager.go
sdk/go/common/resource/config/crypt.go
sdk/go/common/resource/config/value.go
sdk/go/common/workspace/config.go
sdk/go/common/workspace/project.go
sdk/go/common/workspace/project.json
sdk/go/common/workspace/project_test.go

Fixes project level config correctly type checking secret values. 
Also adds a "secret: true" flag to the config schema to require that the config value is secret (this doesn't currently enforce that the default must be secret because we have no way of setting a secure value in Pulumi.yaml).
This removes the support for `pulumi config list/get` to show project level defaults, they now purely look at stack config. Ideally we'll add this back in but it needs to be done in such a way that we can correctly validate secure config values, but only initializing the decrypter (and thus asking for passphrases etc) if it's needed for the values that list/get is showing.
By default list doesn't do any decryption just transforming any secure value to the string "[secure]". That clearly won't …

Add 'secret' to config

---

tests/integration/construct_nested_component/go/go.mod

This was a duplicate module name with tests/integration/construct_component/go/go.mod.

Fix module name for tests/integration/construct_nested_component/go/go.mod

---

sdk/go/common/util/gitutil/git.go

To help with https://github.com/pulumi/pulumi/issues/11121

Report unstaged changes from GitCloneOrPull

---

changelog/pending/20221025--engine--fix-an-invalid-cast-in-analyzer-plugins.yaml
sdk/go/common/resource/plugin/analyzer_plugin.go

Fixes https://github.com/pulumi/pulumi/issues/11140

Fix invalid cast in analyzer_plugin.go

---

changelog/pending/20221025--auto-dotnet--add-json-option-to-updateoptions.yaml
sdk/dotnet/Pulumi.Automation/UpdateOptions.cs
sdk/dotnet/Pulumi.Automation/WorkspaceStack.cs

Add Json option to dotnet automation api

---

changelog/pending/20221025--engine--prevent-concurrent-read-writes-to-the-component-providers-map.yaml
pkg/resource/deploy/source_eval.go

Prevent concurrent writes to the component providers map

---

changelog/pending/20221025--cli--allow-globbing-for-resources-that-do-not-yet-exist.yaml
pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/refresh.go
pkg/cmd/pulumi/up.go
pkg/engine/lifecycletest/refresh_test.go
pkg/engine/lifecycletest/target_test.go
pkg/engine/update.go
pkg/resource/deploy/deployment.go
pkg/resource/deploy/deployment_executor.go
pkg/resource/deploy/deployment_test.go
pkg/resource/deploy/snapshot.go
pkg/resource/deploy/snapshot_test.go
pkg/resource/deploy/step_generator.go

Fixes #8956
This changes how the various `--target` globs work. Instead of expanding the glob on the current snapshot, we now push the glob into the engine itself. This allows us to glob on resources not yet created.
In exchange for this feature, we give up the ability to reject globs that expand to nothing ahead of running a pulumi up. We gain a much more intuitive interface: globs work as expected, _without caveats_.

Support future glob patterns

---

.github/workflows/ci.yml
.github/workflows/download-pulumi-cron.yml
.github/workflows/on-pr.yml
changelog/pending/20221026--build--fix-release-build-to-continue-to-use-macos-11.yaml
scripts/get-job-matrix.py

GitHub are rolling out macos 12 for the -latest image (https://github.com/actions/runner-images/issues/6384), but we need to continue to support and build for macos 11.
Fixes https://github.com/pulumi/pulumi/issues/11152

Replace macos-latest with macos-11

---

changelog/pending/20221025--auto-dotnet-go-nodejs-python--detect-concurrent-update-error-from-local-backend.yaml
sdk/dotnet/Pulumi.Automation/Commands/Exceptions/CommandException.cs
sdk/go/auto/errors.go
sdk/nodejs/automation/errors.ts
sdk/python/lib/pulumi/automation/errors.py

[auto] detect concurrent update error from local backend

---

sdk/dotnet/Pulumi/Core/Output.cs

Fixes #11120 because docfx cannot properly render ordered lists

[dotnet] Simplify the format of docs comment of Output<T>

---

changelog/pending/20221025--auto-dotnet--allow-deserializing-complex-stack-config-values.yaml
sdk/dotnet/Pulumi.Automation.Tests/Serialization/StackSettingsConfigValueJsonConverterTests.cs
sdk/dotnet/Pulumi.Automation.Tests/Serialization/StackSettingsConfigValueYamlConverterTests.cs
sdk/dotnet/Pulumi.Automation/Serialization/Json/StackSettingsConfigValueJsonConverter.cs
sdk/dotnet/Pulumi.Automation/Serialization/Yaml/StackSettingsConfigValueYamlConverter.cs

Fixes #11107 now instead of failing, we JSON-ify the complex stack config value

[dotnet/auto] allow deserializing complex stack config values

---

changelog/config.yaml
changelog/pending/20221026--cli-state--add-the-target-dependents-flag-to-pulumi-state-delete.yaml
pkg/cmd/pulumi/state_delete.go
pkg/resource/edit/operations.go
pkg/resource/edit/operations_test.go
pkg/resource/graph/dependency_graph.go
pkg/resource/graph/dependency_graph_rapid_test.go

Add `pulumi state delete --target-dependents`

---

changelog/pending/20221027--cli--hard-reset-the-templates-checkout-to-work-around-a-go-git-issue-with-ignored-files.yaml
sdk/go/common/util/gitutil/git.go

Fixes https://github.com/pulumi/pulumi/issues/11121

cli: Fix issue with pulumi new and unstaged files

---

pkg/backend/display/options.go
pkg/backend/display/progress.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/client/client.go
pkg/cmd/pulumi/crypto.go
pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/refresh.go
pkg/cmd/pulumi/stack_change_secrets_provider.go
pkg/cmd/pulumi/stack_init.go
pkg/cmd/pulumi/up.go
pkg/cmd/pulumi/util.go
pkg/cmd/pulumi/util_remote.go
pkg/cmd/pulumi/util_remote_test.go
sdk/go.mod
sdk/go/common/apitype/deployments.go
sdk/go/common/apitype/events.go
tests/integration/construct_nested_component/go/go.mod

This change adds experimental CLI support for remote operations. For the new CLI flags to show up `PULUMI_EXPERIMENTAL` envvar must best to a truthy value. Automation API (separate PRs for each language forthcoming), leverage these commands and flags under the covers.
Here's an example:
```
PULUMI_EXPERIMENTAL=true pulumi up --remote https://github.com/pulumi/examples.git \
--stack="justinvp/aws-ts-s3-folder/dev" \
--remote-git-branch="refs/heads/master" \
--remote-git-repo-dir="aws-ts-s3-folder" \
--remote-env="AWS_REGION=us-west-2" \
--remote-env="AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" \
--remote-env-secret="AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" \
--remote-env-secret="AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN"
```
And similar for `preview`, `refresh`, and `destroy` commands.
Note: …

[cli] Experimental support for remote operations

---

changelog/pending/20221027--auto-go--support-for-remote-operations.yaml
sdk/go/auto/local_workspace.go
sdk/go/auto/optremotedestroy/optremotedestroy.go
sdk/go/auto/optremotepreview/optremotepreview.go
sdk/go/auto/optremoterefresh/optremoterefresh.go
sdk/go/auto/optremoteup/optremoteup.go
sdk/go/auto/remote_stack.go
sdk/go/auto/remote_workspace.go
sdk/go/auto/remote_workspace_test.go
sdk/go/auto/stack.go

This change adds preview support for remote operations in Go's Automation API.
Here's an example of using it:
```go
package main
import (
"context"
"fmt"
"os"
"github.com/pulumi/pulumi/sdk/v3/go/auto"
"github.com/pulumi/pulumi/sdk/v3/go/auto/optremotedestroy"
"github.com/pulumi/pulumi/sdk/v3/go/auto/optremoteup"
)
func main() {
// to destroy our program, we can run `go run main.go destroy`
var preview, destroy, refresh bool
argsWithoutProg := os.Args[1:]
destroy := len(argsWithoutProg) > 0 && argsWithoutProg[0] == "destroy"
ctx := context.Background()
org := "justinvp"
projectName := "aws-ts-s3-folder"
stackName := auto.FullyQualifiedStackName(org, projectName, "devgo")
repo := auto.GitRepo{
URL:         "https://github.com/pulumi/examples.git",
Branch:      "refs/heads/master", …
```

[auto/go] Support for remote operations

---

changelog/pending/20221027--auto-nodejs--support-for-remote-operations.yaml
sdk/nodejs/automation/index.ts
sdk/nodejs/automation/localWorkspace.ts
sdk/nodejs/automation/remoteStack.ts
sdk/nodejs/automation/remoteWorkspace.ts
sdk/nodejs/automation/stack.ts
sdk/nodejs/tests/automation/remoteWorkspace.spec.ts
sdk/nodejs/tsconfig.json

This change adds preview support for remote operations in Node.js's Automation API.
Here's an example of using it:
```ts
import * as process from "process";
import { RemoteWorkspace, fullyQualifiedStackName } from "@pulumi/pulumi/automation";
const args = process.argv.slice(2);
const destroy = args.length > 0 && args[0] === "destroy";
const org = "justinvp";
const projectName = "aws-ts-s3-folder";
const stackName = fullyQualifiedStackName(org, projectName, "devnode");
(async function() {
const stack = await RemoteWorkspace.createOrSelectStack({
stackName,
url: "https://github.com/pulumi/examples.git",
branch: "refs/heads/master",
projectPath: projectName,
}, {
envVars: {
AWS_REGION:            "us-west-2",
AWS_ACCESS_KEY_ID:     process.env.AWS_ACCESS_KEY_ID ?? "",
AWS_SECRET_ACCESS_KEY: …
```

[auto/nodejs] Support for remote operations

---

changelog/pending/20221027--auto-python--support-for-remote-operations.yaml
sdk/python/lib/pulumi/automation/__init__.py
sdk/python/lib/pulumi/automation/_local_workspace.py
sdk/python/lib/pulumi/automation/_remote_stack.py
sdk/python/lib/pulumi/automation/_remote_workspace.py
sdk/python/lib/pulumi/automation/_stack.py
sdk/python/lib/test/automation/test_remote_workspace.py

This change adds preview support for remote operations in Python's Automation API.
Here's an example of using it:
```python
import sys
import os
import pulumi.automation as auto
args = sys.argv[1:]
destroy = args and args[0] == "destroy"
org = "justinvp"
project_name = "aws-ts-s3-folder"
stack_name = auto.fully_qualified_stack_name(org, project_name, "devpy")
stack = auto.create_or_select_remote_stack_git_source(
stack_name=stack_name,
url="https://github.com/pulumi/examples.git",
branch="refs/heads/master",
project_path=project_name,
opts=auto.RemoteWorkspaceOptions(
env_vars={
"AWS_REGION":            "us-west-2",
"AWS_ACCESS_KEY_ID":     os.environ["AWS_ACCESS_KEY_ID"],
"AWS_SECRET_ACCESS_KEY": auto.Secret(os.environ["AWS_SECRET_ACCESS_KEY"]),
"AWS_SESSION_TOKEN": …
```

[auto/python] Support for remote operations

---

changelog/pending/20221028--sdk-go-yaml--prevent-race-on-resource-output.yaml
sdk/go/pulumi/context.go

I encountered a problem trying to flush non-determinism out of pulumi-yaml. Running our tests with high `--count=N` values resulted in panics from concurrent accesses to `Ouptput` values. These changes allow running `go test -count=500 -race  ./...` without errors (caused by pulumi/pulumi).

Prevent race when resolving a property map

---

changelog/pending/20221028--sdk-go-yaml--block-issecret-until-secretness-is-known.yaml
sdk/go/pulumi/types.go
sdk/go/pulumi/types_test.go

This PR ensures that `pulumi.IsSecret` works as expected. 
`IsSecret` presented 3 problems.
1. It wasn't thread safe, which triggered go's `-race` flag. (brought up by https://github.com/pulumi/pulumi/pull/11186)
2. It returned the currently known status of secret, meaning that `[]bool{IsSecret(a), IsSecret(a)}` could evaluate to `[]bool{false, true}` if the underlying value resolved between calls.
3. `IsSecret` may return the wrong value for unknown or erred `Output`s.
This PR fixes (1) and (2) by awaiting the underlying value during the `IsSecret` call. (3) is unfixable, and I explain why in a comment.
Blocking on calls to `IsSecret` is necessary for correctness in the general case. We can add optimizations later if necessary. The two I have in mind are
1. Adding a concept of "known …

Make IsSecret threadsafe

---

changelog/pending/20221029--cli-config--optional-typing-and-extended-short-syntax.yaml
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/logs.go
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/refresh.go
pkg/cmd/pulumi/up.go
pkg/cmd/pulumi/watch.go
sdk/go/common/workspace/config.go
sdk/go/common/workspace/project.go
sdk/go/common/workspace/project.json
sdk/go/common/workspace/project_test.go

This PR extends the specs of the hierarchical configuration rules in the following manner:
- The `type` property/attribute is made _optional_ for project configuration which means stack values overriding this config block will not be validated against the type (integer stack value will override string project value)
- Stacks can now use non-project config values that don't have to be defined at the project level (because they are not namespaced by the project, i.e. `aws:region`)
- Non-project config values (i.e. `aws:region`) defined at the project level _cannot_ have a `type` nor `default` properties, only `value`
- Project config block using short-hand syntax now accept arrays: `pulumi:disable-default-providers: ["*"]`
- Project config block when defined using `value` can be anything …

Hierarchical config: optional typing extended short-hand syntax

---

changelog/pending/20221031--auto-dotnet--support-for-remote-operations.yaml
sdk/dotnet/Pulumi.Automation.Tests/RemoteWorkspaceTests.cs
sdk/dotnet/Pulumi.Automation/EnvironmentVariableValue.cs
sdk/dotnet/Pulumi.Automation/LocalWorkspace.cs
sdk/dotnet/Pulumi.Automation/LocalWorkspaceOptions.cs
sdk/dotnet/Pulumi.Automation/PublicAPI.Shipped.txt
sdk/dotnet/Pulumi.Automation/Pulumi.Automation.xml
sdk/dotnet/Pulumi.Automation/RemoteDestroyOptions.cs
sdk/dotnet/Pulumi.Automation/RemoteGitAuthArgs.cs
sdk/dotnet/Pulumi.Automation/RemoteGitProgramArgs.cs
sdk/dotnet/Pulumi.Automation/RemotePreviewOptions.cs
sdk/dotnet/Pulumi.Automation/RemoteRefreshOptions.cs
sdk/dotnet/Pulumi.Automation/RemoteUpOptions.cs
sdk/dotnet/Pulumi.Automation/RemoteUpdateOptions.cs
sdk/dotnet/Pulumi.Automation/RemoteWorkspace.cs
sdk/dotnet/Pulumi.Automation/RemoteWorkspaceOptions.cs
sdk/dotnet/Pulumi.Automation/RemoteWorkspaceStack.cs
sdk/dotnet/Pulumi.Automation/Workspace.cs
sdk/dotnet/Pulumi.Automation/WorkspaceStack.cs

This change adds preview support for remote operations in .NET's Automation API.
**Note:** ~~I've tried _many_ incantations of `dotnet format dotnet.sln analyzers --diagnostics=RS0016`, but have not been able to get the code fix applied to update `sdk/dotnet/Pulumi.Automation/PublicAPI.Shipped.txt`. Perhaps a .NET 6 bug (I'm running on an M1 Mac)? https://github.com/dotnet/format/issues/1416 might be relevant. I'll try again a bit later, but I might have to manually update the file, unless someone else's tools are working and can pull down the branch and run it.~~
Update: I didn't see any failures in the PR related to not having updated `sdk/dotnet/Pulumi.Automation/PublicAPI.Shipped.txt`, so maybe we're no longer checking this or something is broken? In any case, I still wasn't able to …

[auto/dotnet] Support for remote operations

---

changelog/pending/20221031--sdk-dotnet--make-the-localserializer-class-public.yaml
sdk/dotnet/Pulumi.Automation/Serialization/LocalSerializer.cs

**Use case:** I want to be able to deserialize a `Pulumi.stack.yml` file without using a `LocalWorkspace`, as that requires too much configuration and isn't very well-documented.

Expose LocalSerializer

---

pkg/backend/display/jsonmessage.go
pkg/backend/display/progress.go
pkg/backend/display/tableutil.go
pkg/cmd/pulumi/replay_events.go

The progress display is logically composed of two pieces:
- An event listener that transforms raw engine events into renderable data
- A renderer that renders that data on to the screen
The interface for the latter is relatively simple. It only really needs to know the following:
- When an idle interval has elapsed
- When a row has changed
- When a system message (e.g. a line printed to stdout) has arrived
- When the update is done
- When the display is closed
- When to print a raw line
This interface is general enough to accommodate multiple renderers.

[display] Factor out the low-level progress renderer.

---

changelog/pending/20221013--engine--update-plan-dbr.yaml
pkg/engine/lifecycletest/update_plan_test.go
pkg/resource/deploy/deployment.go
pkg/resource/deploy/step_generator.go

We weren't correctly handling the case where a resource was marked for deletion due to one of it's dependencies being deleted. We would add an entry to it's "Ops" list, but then overwrite that "Ops" list when we came to generate the recreation step.
Fixes https://github.com/pulumi/pulumi/issues/10924

Fix update plans with dependent replacements

---

changelog/pending/20221014--engine--pending-deletes.yaml
pkg/engine/lifecycletest/pulumi_test.go
pkg/resource/deploy/deployment_executor.go
pkg/resource/deploy/step_generator.go
tests/integration/double_pending_delete/double_pending_delete_test.go
tests/integration/double_pending_delete/step3/index.ts
tests/integration/double_pending_delete/step4/index.ts

This removes all the handling of pending deletes from the start of deployments. Instead we allow resources to just be deleted as they usually would at the end of the deployment.
There's a big comment in TestPendingDeleteOrder that explains the order of operations in a succesful run and how that order differs if we try and do pending deletes up-front.
Fixes https://github.com/pulumi/pulumi/issues/2948

Do not execute pending deletes at the start of deployment

---

changelog/pending/20221101--engine--expand-duplicate-urn-checks-across-direct-urns-and-aliases.yaml
pkg/engine/lifecycletest/pulumi_test.go
pkg/resource/deploy/step_generator.go
sdk/go/common/diag/errors.go

We need to check that for example that if a resource X is created that we don't allow another resource Y to be alias against X. Likewise if our old state has X and we then create Y aliased against X we should not then allow X to be created later in the deployment.
Fixes https://github.com/pulumi/pulumi/issues/11173

Check for duplicate aliases and plain URNs

---

changelog/pending/20221102--programgen-dotnet-go-java-nodejs-python--support-a-logical-name-for-config-vars.yaml
pkg/codegen/dotnet/gen_program.go
pkg/codegen/go/gen_program.go
pkg/codegen/nodejs/gen_program.go
pkg/codegen/pcl/binder_nodes.go
pkg/codegen/pcl/config.go
pkg/codegen/python/gen_program.go
pkg/codegen/python/python_test.go

Support a logical name for config vars

---

.github/workflows/download-pulumi-cron.yml

I think the problem was the missing `|` when using multi-line scripts 😅 now I simplified this into a one-liner (attempt nr. 3)
Tested using a Windows machine

Fix winget install in download cron

---

pkg/go.mod
pkg/go.sum

Pull in Pulumi YAML 1.0.1 to allow ejecting from YAML programs with `config` based nodes.

Include YAML 1.0.1

---

changelog/pending/20221102--sdk-python--handle-none-being-passed-to-register_resource_outputs.yaml
sdk/python/lib/pulumi/runtime/resource.py

Fixes https://github.com/pulumi/pulumi/issues/11227.

Handle None being passed to register_resource_outputs

---

pkg/backend/apply.go
pkg/backend/backend.go
pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/query.go
pkg/cmd/pulumi/refresh.go
pkg/cmd/pulumi/up.go
pkg/cmd/pulumi/watch.go
pkg/engine/lifecycletest/update_plan_test.go
pkg/engine/update.go

This threads a new option "Experimental" through to the engine which is used to decided if plans should be used or not. This also generates plans for any preview with --save-plan, but also now generates plans during the preview phase of up.

Decouple the generation of plans from the automatic use of plans

---

sdk/go/pulumi/types.go

This is the last step necessary to allow pulumi-yaml to run a subset of its tests with `-race=true`. 
The race is is between `ApplyT` and `fulfillValue` on copying a slice. 
Both me (@iwahbe) and @t0yv0 have independently confirmed that the race is not hiding a deeper issue. Further discussion of the issue is at https://github.com/pulumi/pulumi/pull/11186.
A stack trace from the `-race` flag that this issue fixes:
```
Write at 0x00c000422ec0 by goroutine 463:
github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*OutputState).fulfillValue()
/Users/ianwahbe/go/src/github.com/pulumi/pulumi/sdk/go/pulumi/types.go:198 +0x590
github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*OutputState).ApplyTWithContext.func1()
/Users/ianwahbe/go/src/github.com/pulumi/pulumi/sdk/go/pulumi/types.go:516 …
```

Make OutputState pass the `-race` detector

---

Makefile
pkg/codegen/schema/docs_test.go
pkg/codegen/testing/utils/host.go

Fixes #11252
I've been unable to repro locally, but the underlying issue is encountered while binding packages, (not the functionality under test). I've changed the loading mechanism to use our standard `utils.NewHost` framework. Hopefully this will eliminate the flaky behavior.
Fully binding ecs correctly requires `aws@4.15.0`.
I've also limited the test to only run once on each named schemas. I don't think we need to produce and check docs for every version of every schema.

Standardize pkg loading for TestReferenceRenderer

---

changelog/pending/20221102--cli--pulumi-debug-grpc.yaml
pkg/engine/deployment.go
pkg/engine/plugin_host.go
pkg/resource/deploy/deploytest/pluginhost.go
pkg/resource/deploy/source_eval.go
pkg/resource/deploy/source_query.go
pkg/resource/provider/main.go
pkg/util/rpcdebug/interceptors.go
pkg/util/rpcdebug/logformat.go
sdk/dotnet/cmd/pulumi-language-dotnet/main.go
sdk/go/auto/remote_workspace_test.go
sdk/go/auto/stack.go
sdk/go/common/resource/plugin/analyzer_plugin.go
sdk/go/common/resource/plugin/context.go
sdk/go/common/resource/plugin/host_server.go
sdk/go/common/resource/plugin/langruntime_plugin.go
sdk/go/common/resource/plugin/plugin.go
sdk/go/common/resource/plugin/provider_plugin.go
sdk/go/common/util/rpcutil/interceptor.go
sdk/go/common/util/rpcutil/serve.go
sdk/go/pulumi-language-go/main.go
sdk/nodejs/cmd/pulumi-language-nodejs/main.go
sdk/python/cmd/pulumi-language-python/main.go

Fixes #10232
`PULUMI_DEBUG_GRPC=./debug.json pulumi preview` now works.
The debug APIs are probably unstable so I moved them out to their own repo rather than hosting under sdk/.
Debug interceptors are no-op unless the process initializes them in main. Currently only `pulumi` process initializes them if the env var is set. This way we observe conversations only once, as a server for ResourceMonitor etc, and as a client for plugin conversations (language and resource).
I can now see provider conversations logged which was of interest to me.

Add debug GRPC interceptors that print conversations in JSON

---

.github/workflows/ci-lint.yml
bors.toml
scripts/git-linear-history-check.sh

This ensures commit history is linear, enabling customer-owned forks of the pulumi CLI to more easily maintain their fork. Reverse merges into PR branches result in a more complex process for them and for us.
To test this PR, I based my PR branch off an older commit from the target branch and added a merge commit. That resulted in the check failing:
https://github.com/pulumi/pulumi/actions/runs/3416559764/jobs/5686840393
> Checking merge commit efb7be0747f8d19ae77033ba9f2a94865ac15153  for non-linear history
> Main branch parent is: 83c9dfcb9 Merge #11262
> PR branch parents are d9460b9047658ca574d99f0e436190f4d044cbe5
> Checking: d9460b904 Merge remote-tracking branch 'origin/master' into friel/block-reverse-merge
> Error: Non-linear history, PR contains a merge …

ci: block non-linear merges

---

changelog/pending/20221101--cli-display--improve-the-usability-of-the-interactive-dipslay-by-making-the-treetable-scrollable.yaml
pkg/backend/display/jsonmessage.go
pkg/backend/display/options.go
pkg/backend/display/progress.go
pkg/backend/display/sigint_unix.go
pkg/backend/display/sigint_windows.go
pkg/backend/display/tree.go
pkg/go.mod
pkg/go.sum
tests/go.mod
tests/go.sum

The display pipleline looks like this:
```
╭──────╮
│Engine│
╰──────╯
⬇ engine events
╭────────────────╮
│Progress Display│
╰────────────────╯
⬇ display events: ticks, resource updates, system messages
╭─────────────────╮
│Progress Renderer│
╰─────────────────╯
⬇ text
╭────────╮
│Terminal│
╰────────╯
```
The existing implementation of the interactive Progress Renderer is broken
into two parts, the display renderer and the message renderer. The display
renderer converts display events into progress messages, each of which
generally represents a single line of text at a particular position in
the output. The message renderer converts progress messages into screen
updates by identifying whether or not the contents of a particular
message have changed and if so, re-rendering its output line. …

[cli] Reimplement the interactive renderer

---

.github/workflows/ci-run-test.yml

Increases likelihood of CI passing on Windows due to longstanding CPU exhaustion bug on runners. (GitHub support ticket 1791026 on my account.)

ci: Reduce Windows test parallelism

---

pkg/cmd/pulumi/convert.go
pkg/codegen/pcl/program.go

We're going to use convert for more data sources than just YAML (e.g. hcl, arm, etc). So we don't want the PCL output option to be YAML specific given it should be usable for any input source.

Make convert's pcl output yaml agnostic

---

pkg/backend/apply.go
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/policy_new.go
pkg/cmd/pulumi/refresh.go
pkg/cmd/pulumi/state.go
pkg/cmd/pulumi/util.go
pkg/go.mod
pkg/go.sum
tests/go.mod
tests/go.sum

Pick up the bugfix to https://github.com/AlecAivazis/survey/issues/228.
This also provides a cleaner API for setting survey icons.

[cli] Update the survey module

---

pkg/backend/apply.go

The lack of a newline causes the prompt to wrap in terminals that are fewer than 120 or so columns wide. The wrapping confuses the survey package's redraw, which causes the repeated prompts each time the survey is redrawn (i.e. on every keypress). Removing the wrapping by adding a newline avoids this issue.

[cli] Add a newline in the refresh confirmation prompt

---

.vscode/settings.json
changelog/pending/20221107--engine--disable-auto-parenting-to-see-if-that-fixes-10950.yaml
pkg/engine/lifecycletest/pulumi_test.go
pkg/resource/deploy/step_generator.go
tests/integration/integration_nodejs_test.go

Might fix https://github.com/pulumi/pulumi/issues/10950, but I've not been able to reproduce that bug so this is just a best guess.

Disable auto stack parenting

---

tests/integration/gather_plugin/dotnet/MyStack.cs
tests/integration/gather_plugin/go/main.go
tests/integration/gather_plugin/nodejs/index.ts
tests/integration/gather_plugin/python/__main__.py
tests/integration/integration_dotnet_smoke_test.go
tests/integration/integration_dotnet_test.go
tests/integration/integration_go_smoke_test.go
tests/integration/integration_go_test.go
tests/integration/integration_nodejs_smoke_test.go
tests/integration/integration_nodejs_test.go
tests/integration/integration_python_smoke_test.go
tests/integration/integration_python_test.go
tests/integration/integration_smoke_test.go
tests/integration/integration_test.go
tests/integration/integration_util_test.go

Reduces the set of smoke tests run on Windows & macOS, balances the reduced parallelism #11249 by moving tests which don't seem to obviously entail cross-platform behavior changes. The tests moved to only run on Linux environments are listed below and except for the first, all were split from `integration_test.go`.
* `TestRefreshGo` checks that the Pulumi.yaml `options.refresh` option is obeyed (moved to integration_go_test from integration_go_smoke_test)
* `TestStackTagValidation` which tests Pulumi.yaml validation
* `TestStackInitValidation` which tests an error on running `pulumi stack init`
* `TestConfigPaths` which tests `pulumi config set` under a wide variety of inputs
* `TestDestroyStackRef` which tests running `pulumi destroy` on a stack with a large stack reference
* …

ci: Move more tests to linux-only integration tests

---

sdk/nodejs/Makefile
sdk/nodejs/automation/remoteWorkspace.ts
sdk/nodejs/tests/automation/localWorkspace.spec.ts
sdk/nodejs/tests/automation/remoteWorkspace.spec.ts
sdk/nodejs/tests/automation/util.ts
sdk/nodejs/tsconfig.json

Also cleans up some error messages to be consistent with the CLI and other languages.
Related:
- https://github.com/pulumi/pulumi/pull/11290
- https://github.com/pulumi/pulumi/pull/11291
- https://github.com/pulumi/pulumi/pull/11293
- https://github.com/pulumi/pulumi/pull/11294

[auto/nodejs] Test remote operations

---

pkg/codegen/docs/gen.go
pkg/codegen/dotnet/gen.go
pkg/codegen/go/gen.go
pkg/codegen/nodejs/gen.go
pkg/codegen/python/gen.go
pkg/codegen/utilities.go

We duplicate the `fs` type in nodejs, dotnet and python. We reimplement it in go: `setFile`. This PR defines a shared `Fs` in codegen and changes all implementations to use it.

Standardize the FS abstraction for codegen

---

README.md

The `securityGroups` property on `aws.ec2.Instance` has been deprecated for some time, and does not support updates.  Use `vpcSecurityGroupIds` instead.

Avoid use of deprecated API in README code example

---

Makefile
sdk/python/lib/pulumi/runtime/proto/resource_pb2.pyi

Regenerate the .pyi files as left from https://github.com/pulumi/pulumi/pull/11095. 
It's unclear to me why this didn't happen in the initial PR. The only thing I can think of is that .checksum.txt was manually edited.

Regenerate .pyi files, sort diffs on proto cksum

---

changelog/pending/20221109--cli-display--fix-text-cutting-off-prior-to-the-edge-of-the-terminal.yaml
pkg/backend/display/jsonmessage.go
pkg/backend/display/progress.go
pkg/backend/display/tableutil.go
pkg/backend/display/testdata/not-truncated/template-body.json.interactive-100x80-cooked.stdout.txt
pkg/backend/display/testdata/not-truncated/template-body.json.interactive-100x80.stdout.txt
pkg/backend/display/testdata/not-truncated/template-body.json.interactive-80x24-cooked.stdout.txt
pkg/backend/display/testdata/not-truncated/template-body.json.interactive-80x24.stdout.txt
pkg/backend/display/testdata/not-truncated/up-4.json.interactive-80x24-cooked.stdout.txt
pkg/backend/display/testdata/not-truncated/up-4.json.interactive-80x24.stdout.txt
pkg/backend/display/testdata/not-truncated/up-5.json.interactive-100x80-cooked.stdout.txt
pkg/backend/display/testdata/not-truncated/up-5.json.interactive-100x80.stdout.txt
pkg/backend/display/testdata/not-truncated/up-5.json.interactive-80x24-cooked.stdout.txt
pkg/backend/display/testdata/not-truncated/up-5.json.interactive-80x24.stdout.txt
pkg/backend/display/testdata/not-truncated/up.json.interactive-100x80-cooked.stdout.txt
pkg/backend/display/testdata/not-truncated/up.json.interactive-100x80.stdout.txt
pkg/backend/display/testdata/not-truncated/up.json.interactive-80x24-cooked.stdout.txt
pkg/backend/display/testdata/not-truncated/up.json.interactive-80x24.stdout.txt
pkg/backend/display/testdata/not-truncated/webserver-userdata.json.interactive-80x24-cooked.stdout.txt
pkg/backend/display/testdata/not-truncated/webserver-userdata.json.interactive-80x24.stdout.txt
pkg/backend/display/tree.go
sdk/go/common/diag/colors/colors.go
sdk/go/common/diag/colors/colors_test.go
sdk/go/common/diag/colors/diag.go

The number of Unicode code points in a string is not the same as the
number of user-visible characters (graphemes). When measuring colorized
strings, we want the latter rather than the former. Notably, these
changes fix some issues where the interactive display cut off before the
right edge of the terminal.

[color] Use graphemes to measure strings.

---

sdk/go/common/apitype/service.go

Add request shapes for Capabilities API, which will moving forward help cement service/client contract in dynamically indicating which features are available in a given backend for the CLI to use.
Related: https://github.com/pulumi/pulumi-service/issues/10510

Add prelim interface contract for Capabilities API

---

pkg/cmd/pulumi/convert.go
pkg/cmd/pulumi/convert_test.go
pkg/cmd/pulumi/pcl_convert_testdata/main.pp

Little step towards making convert support multiple inputs as well as outputs. Firstly just allowing us to convert from PCL. Figure this could be quite useful for debugging codegen issues as well if you've got a source PCL program.

Support PCL as a convert input (and output)

---

.github/workflows/ci-build-sdks.yml
.github/workflows/ci-lint.yml
.github/workflows/ci-run-test.yml
.github/workflows/ci-test-docs-generation.yml
.github/workflows/release.yml
scripts/get-job-matrix.py

The `actions/setup-dotnet` action published v3.0.3 two weeks ago addressing the ECONNRESET issues discovered in #10997.
Reverts #11001
Resolves #11000

ci: Re-enable version sets for .NET, test GA version of 6 and 7

---

changelog/pending/20221111--sdk-dotnet--add-dictionaryinvokeargs-for-dynamically-constructing-invoke-input-bag-of-properties.yaml
sdk/dotnet/Pulumi.Tests/Resources/DictionaryInvokeArgsTests.cs
sdk/dotnet/Pulumi/PublicAPI.Shipped.txt
sdk/dotnet/Pulumi/Resources/DictionaryInvokeArgs.cs

[sdk/dotnet] Add DictionaryInvokeArgs for dynamically constructing invoke inputs

---

pkg/codegen/dotnet/gen.go
pkg/codegen/testing/test/testdata/azure-native-nested-types/dotnet/Pulumi.AzureNative.csproj
pkg/codegen/testing/test/testdata/cyclic-types/dotnet/Pulumi.Example.csproj
pkg/codegen/testing/test/testdata/dash-named-schema/dotnet/Pulumi.FooBar.csproj
pkg/codegen/testing/test/testdata/dashed-import-schema/dotnet/Pulumi.Plant.csproj
pkg/codegen/testing/test/testdata/functions-secrets/dotnet/Pulumi.Mypkg.csproj
pkg/codegen/testing/test/testdata/hyphen-url/dotnet/Pulumi.Registrygeoreplication.csproj
pkg/codegen/testing/test/testdata/naming-collisions/dotnet/Pulumi.Example.csproj
pkg/codegen/testing/test/testdata/nested-module-thirdparty/dotnet/Pulumi.FooBar.csproj
pkg/codegen/testing/test/testdata/output-funcs-edgeorder/dotnet/Pulumi.Myedgeorder.csproj
pkg/codegen/testing/test/testdata/output-funcs-tfbridge20/dotnet/Pulumi.Mypkg.csproj
pkg/codegen/testing/test/testdata/output-funcs/dotnet/Pulumi.Mypkg.csproj
pkg/codegen/testing/test/testdata/plain-and-default/dotnet/Pulumi.FooBar.csproj
pkg/codegen/testing/test/testdata/plain-object-defaults/dotnet/Pulumi.Example.csproj
pkg/codegen/testing/test/testdata/plain-object-disable-defaults/dotnet/Pulumi.Example.csproj
pkg/codegen/testing/test/testdata/plain-schema-gh6957/dotnet/Pulumi.Xyz.csproj
pkg/codegen/testing/test/testdata/regress-8403/dotnet/Pulumi.Mongodbatlas.csproj
pkg/codegen/testing/test/testdata/regress-node-8110/dotnet/Pulumi.My8110.csproj
pkg/codegen/testing/test/testdata/replace-on-change/dotnet/Pulumi.Example.csproj
pkg/codegen/testing/test/testdata/resource-args-python-case-insensitive/dotnet/Pulumi.Example.csproj
pkg/codegen/testing/test/testdata/resource-args-python/dotnet/Pulumi.Example.csproj
pkg/codegen/testing/test/testdata/resource-property-overlap/dotnet/Pulumi.Example.csproj
pkg/codegen/testing/test/testdata/secrets/dotnet/Pulumi.Mypkg.csproj
pkg/codegen/testing/test/testdata/simple-enum-schema/dotnet/Pulumi.Plant.csproj
pkg/codegen/testing/test/testdata/simple-methods-schema-single-value-returns/dotnet/Pulumi.Example.csproj
pkg/codegen/testing/test/testdata/simple-methods-schema/dotnet/Pulumi.Example.csproj
pkg/codegen/testing/test/testdata/simple-plain-schema-with-root-package/dotnet/Pulumi.Example.csproj
pkg/codegen/testing/test/testdata/simple-plain-schema/dotnet/Pulumi.Example.csproj
pkg/codegen/testing/test/testdata/simple-resource-schema/dotnet/Pulumi.Example.csproj

When generating dotnet SDKs, if a schema doesn't specify a package reference to Pulumi nuget, we add it automatically by default. However, when generating test dotnet sdks, we also use project references that refer to the local Pulumi SDK and it is not correct to have either (although usually it compiles if you don't use latest SDK changes) 
This PR makes it so that if we are already referencing a local Pulumi SDK via a project reference, then we don't add a package reference to Pulumi

Do not reference Pulumi nuget if a project reference to Pulumi.csproj already exists

---

changelog/pending/20221114--sdk-go--allow-sane-conversions-for-as-map-and-as-array-conversions.yaml
sdk/go/pulumi/generate/main.go
sdk/go/pulumi/generate/templates/types_builtins.go.template
sdk/go/pulumi/types.go
sdk/go/pulumi/types_builtins.go
sdk/go/pulumi/types_test.go

Fixes #11348
Fixes #11347
This PR implements deep type conversion for the `As*Map` and `As*Array` methods on `AnyOutput`.
For example, you can now call `AsIntArrayMapOutput` on an `AnyOutput` with underlying value `map[string]interface{}{"zero": []int{0}, "one": []int{1}}`.
I choose to implement this with reflection (as opposed to in the templating system) because I didn't want to handle the combinatorial explosion of outer and inner types. This solution works for arbitrary nesting of arbitrary types.

Allow sane conversions for `As*Map*` and `As*Array*` conversions

---

changelog/pending/20221109--pkg--panic-in-codegen-obj-expressions.yaml
pkg/codegen/pcl/invoke.go

@dirien raised an issue where tfgen would panic converting PCL under an edge case where an `ObjectExpression` had `nil` arguments. By introducing this guard, we skip annotating the the Object with the type provided by the schema the function in the schema has no args.
S/o to @Zaid-Ajaj for explaining this code to me and confirming the kill. I was lost without his aid! 
Fixes https://github.com/pulumi/pulumi/issues/11305

Guard against empty inputs for objs expressions.

---

changelog/pending/20221115--cli--fix-stack-selection-prompt.yaml
pkg/cmd/pulumi/util.go

Fixes https://github.com/pulumi/pulumi/issues/11334

Fix default answer for AskOne prompt

---

.github/workflows/on-pr.yml

These jobs can result in some misleading information in PRs from community members. 
GitHub Actions `pull_request` workflows triggered from forks lack access to secrets and write permissions on the base repository. Our CI actions depend on secrets to retrieve metadata via GitHub API and some secrets for integration tests.
This disables those jobs for fork workflows. The `on-community-pr.yml` workflow will provide commands for maintainers to run CI, or `bors merge` can run a full suite of tests once the PR is reviewed.
This was tested by creating PR #11367 from a fork.

ci: Skip CI workflows on forks where permissions would cause workflow to fail

---

changelog/pending/20221116--programgen--enable-type-checking-for-resource-attributes.yaml
pkg/codegen/pcl/binder.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/assets-archives-pp/assets-archives.pp
pkg/codegen/testing/test/testdata/assets-archives-pp/dotnet/assets-archives.cs
pkg/codegen/testing/test/testdata/assets-archives-pp/go/assets-archives.go
pkg/codegen/testing/test/testdata/assets-archives-pp/nodejs/assets-archives.ts
pkg/codegen/testing/test/testdata/assets-archives-pp/python/assets-archives.py

Type check resource attributes unless instructed otherwise.
This makes debugging programgen errors so much easier!

Type check resource attributes

---

changelog/pending/20221116--engine--always-keep-resources-when-pulumi-pulumi-getresource-is-invoked.yaml
changelog/pending/20221116--sdk-go-nodejs-python--set-acceptresources-when-invoking-pulumi-pulumi-getresource.yaml
pkg/resource/deploy/source_eval.go
sdk/go/pulumi/context.go
sdk/nodejs/runtime/resource.ts
sdk/python/lib/pulumi/runtime/resource.py

We used to always keep resource references when marshaling the results of `pulumi:pulumi:getResource`, but this regressed in #9323 to only keep resource if the invoke request's `acceptResources` flag was set. Unfortunately, that flag is not being set when calling `pulumi:pulumi:getResource` in the Go, Node.js, and Python SDKs (although, it is being set for .NET and Java).
Two fixes:
1. Update the monitor to go back to always keeping resources when `pulumi:pulumi:getResource` is being invoked. This way, older SDKs that are not setting `acceptResources` will go back to the original behavior.
2. Update the SDKs to always set `acceptResources`, so that these newer versions of the SDKs will work with older engines that are checking `acceptResources`.
(2) will help us with EKS 1.0. We'll be …

Keep resource refs when invoking `pulumi:pulumi:getResource`

---

changelog/pending/20221116--programgen-dotnet-go-nodejs-python--dont-generate-traverse-error-when-typecheck-is-disabled.yaml
pkg/codegen/hcl2/model/binder_expression.go
pkg/codegen/hcl2/model/diagnostics.go
pkg/codegen/hcl2/model/scope.go
pkg/codegen/hcl2/model/traversable.go
pkg/codegen/hcl2/model/type_union.go
pkg/codegen/pcl/binder_resource.go
pkg/codegen/pcl/binder_schema.go
pkg/codegen/pcl/binder_test.go
pkg/codegen/pcl/rewrite_convert.go
pkg/codegen/report/report_test.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/traverse-union-repro-pp/dotnet/traverse-union-repro.cs
pkg/codegen/testing/test/testdata/traverse-union-repro-pp/go/traverse-union-repro.go
pkg/codegen/testing/test/testdata/traverse-union-repro-pp/nodejs/traverse-union-repro.ts
pkg/codegen/testing/test/testdata/traverse-union-repro-pp/python/traverse-union-repro.py
pkg/codegen/testing/test/testdata/traverse-union-repro-pp/traverse-union-repro.pp
sdk/go/common/workspace/plugins.go

Fixes #11346
In every case I examined, the original error came from mis-typed PCL. The fix here allows us to continue without error, but it won't generate correctly typed code.
This PR fixes a couple of different problems. 
1. It improves the diagognostics, both within the binder and within the test framework.
2. It moves omitted errors to warnings (instead of dropping them).
3. It prevents rewrites on dynamic types, fixing the original error.

Address the `cannot traverse union(...)` error when converting examples

---

README.md

Because `master` is always green by tautologically, this PR removes the CI badges from the repo. The Linux badge was broken, and there's no way to reconstitute it with our new setup. Further, it wouldn't provide any meaningful information since `master` is always green.
Fixes #11280

Remove CI badges, move EOL below langs

---

changelog/pending/20221117--sdk-nodejs--attempt-to-select-stack-then-create-as-fallback-on-createorselect.yaml
sdk/dotnet/Pulumi.Automation/WorkspaceStack.cs
sdk/go/auto/stack.go
sdk/nodejs/automation/stack.ts

Fixes #11392
If a user does not have write permission (i.e. read-only), attempting to create the stack first will fail before the stack select fallback is triggered. Flip the logic to select first, then create.
https://github.com/pulumi/pulumi/commit/7695311d799f47a3cf13e6019d135eec4bb886bd changed it for python auto API already, this PR does the same for TS, Go, C#

Attempt to select stack then create as fallback

---

pkg/cmd/pulumi/util.go

Fixes #11407 
Follow on to PR [11354](https://github.com/pulumi/pulumi/pull/11354). When we don't prompt to `create a new stack`, we should default to an existing stack so the empty string isn't populated.

Fix stack selection behavior

---

pkg/codegen/dotnet/gen.go
pkg/codegen/dotnet/gen_program_expressions.go
pkg/codegen/hcl2/model/binder_expression.go
pkg/codegen/hcl2/model/functions.go
pkg/codegen/nodejs/gen.go
pkg/codegen/nodejs/gen_program_expressions.go
pkg/codegen/pcl/invoke.go
pkg/codegen/schema/bind.go
pkg/codegen/schema/schema.go

This PR moves validation logic for `multiArgumentInputs` from language generators to the schema binder.
If `multiArgumentInputs` matches input properties, we order the input properties to match. `schema.Function.MultiArgumentInputs` is a boolean, not a list of properties. This simplifies the check needed in downstream codegen. We reverse this process when we marshal out of `schema.Function` back to `schema.FunctionSpec`.

Simplified invoke gen improve bind

---

bors.toml

This is a separate PR due to `pull_request_target` workflows running in the context of the base repository's main branch. The change in this PR is not mergeable until #11364 is merged. At which time, this will need to be rebased to trigger workflows to run, and the new workflow will run.
Fixes #11360.

Adjust bors.toml after #11364

---

changelog/pending/20221121--sdk-python--dont-error-on-type-mismatches-when-using-input-values-for-outputs.yaml
sdk/python/lib/pulumi/runtime/rpc.py
sdk/python/lib/test/langhost/input_values_for_outputs/__init__.py
sdk/python/lib/test/langhost/input_values_for_outputs/__main__.py
sdk/python/lib/test/langhost/input_values_for_outputs/test_input_values_for_outputs.py

When resolving a resource's outputs, if an output value is missing (and it's not a preview), the SDK will see if there was an input prop of the same name as the output prop and use that input value as the value for the output. We do this across our SDKs. It can be problematic when the input prop's type isn't the same as the output prop's type. In the Python SDK, if the input value is a `dict` and the type of the output cannot be converted from a `dict`, then the SDK currently raises an `AssertionError`, which causes `pulumi up` to fail. This is inconsistent with the other language SDKs, which don't error during `pulumi up` in such cases.
This change changes the behavior of the Python SDK to not error when attempting to use an input value for the output value when there is a type mismatch. …

[sdk/python] Don't error on type mismatches when using input values for outputs

---

changelog/pending/20221115--cli--add-prompt-to-up-to-use-experimental-update-plans.yaml
pkg/backend/apply.go
pkg/backend/httpstate/backend.go

Adds an option to use plans in the update prompt:
```
Do you want to perform this update?  [Use arrows to move, type to filter]
> [experimental] yes, using Update Plans (https://pulumi.com/updateplans)
yes
no
details
```
Needs at least https://github.com/pulumi/pulumi-hugo/pull/2230 merged and published first.
Fixes https://github.com/pulumi/pulumi/issues/9687

Add experimental use plan option to up

---

pkg/cmd/pulumi/new.go
sdk/go/common/workspace/templates.go

Instead of doing nothing if a broken template is selected, display the reason why its broken:
Example:
```
X pulumi new --offline
Please choose a template (88/203 shown):
go                                 (This template is currently broken)
error: template 'go' is currently broken: could not validate '~/.pulumi/templates/go/Pulumi.yaml': project is missing a 'runtime' attribute
```
I'm not sure if failing to select a broken template was the intended behavior, but it is really confusing. Here the selection works, but errors with the reason whey the template is broken.

Improve the experience of selecting a broken template

---

pkg/cmd/pulumi/new.go
sdk/go/common/workspace/templates.go

Fixes #11434 
If one or more templates are invalid in a repo, we should omit showing those to users instead of failing completely.

Do not fail pulumi new on invalid template(s)

---

pkg/codegen/go/gen.go
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/aws-webserver-pp/go/aws-webserver.go

Fixes #8070
Progress on https://github.com/pulumi/pulumi/issues/11427

Mark external modules as forign

---

changelog/pending/20221123--cli--up-yes-should-not-use-update-plans.yaml
pkg/backend/apply.go

Fixes https://github.com/pulumi/pulumi/issues/11444

Only use preview plans for --yes in experimental mode

---

pkg/codegen/hcl2/model/type_const.go
pkg/codegen/pcl/binder_resource.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/kubernetes-pod-pp/dotnet/kubernetes-pod.cs
pkg/codegen/testing/test/testdata/kubernetes-pod-pp/go/kubernetes-pod.go
pkg/codegen/testing/test/testdata/kubernetes-pod-pp/kubernetes-pod.pp
pkg/codegen/testing/test/testdata/kubernetes-pod-pp/nodejs/kubernetes-pod.ts
pkg/codegen/testing/test/testdata/kubernetes-pod-pp/python/kubernetes-pod.py

Don't emit missing var errors for const vars

---

changelog/pending/20221123--cli--dont-print-update-plan-message-with-json.yaml
pkg/cmd/pulumi/preview.go

Fixes https://github.com/pulumi/pulumi/issues/11453

Don't print the update plan message if using --json

---

pkg/codegen/go/gen_program.go

Cleanup the `getPulumiImport` function.
In doing so, remove an edge causing extraneous `/index` in https://github.com/pulumi/pulumi/issues/11427. 
For reviewers, looking at the diff for this PR is painful. It's much easier to review the old and new code separately.
Part of https://github.com/pulumi/pulumi/issues/11427.

Cleanup import generation

---

pkg/codegen/go/gen_program.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/assets-archives-pp/go/assets-archives.go

Don't import types if the type is only referenced in a scoped traversal (`foo.bar`), not named directly.
Part of https://github.com/pulumi/pulumi/issues/11427
Relates to https://github.com/pulumi/pulumi/issues/8324

Don't import types referenced from local variables

---

sdk/go/auto/remote_workspace.go
sdk/go/auto/remote_workspace_test.go

Also cleans up some error messages to be consistent with the CLI and other languages.
Related:
- https://github.com/pulumi/pulumi/pull/11290
- https://github.com/pulumi/pulumi/pull/11292
- https://github.com/pulumi/pulumi/pull/11293
- https://github.com/pulumi/pulumi/pull/11294

[auto/go] Test remote operations

---

sdk/dotnet/Pulumi.Automation.Tests/DeploymentsApiFactAttribute.cs
sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs
sdk/dotnet/Pulumi.Automation.Tests/RemoteWorkspaceTests.cs
sdk/dotnet/Pulumi.Automation.Tests/Utility.cs
sdk/dotnet/Pulumi.Automation/RemoteWorkspace.cs

Also cleans up some error messages to be consistent with the CLI and other languages.
Related:
- https://github.com/pulumi/pulumi/pull/11290
- https://github.com/pulumi/pulumi/pull/11291
- https://github.com/pulumi/pulumi/pull/11292
- https://github.com/pulumi/pulumi/pull/11293

[auto/dotnet] Test remote operations

---

pkg/codegen/nodejs/gen_program_expressions.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/aws-eks-pp/nodejs/aws-eks.ts
pkg/codegen/testing/test/testdata/aws-s3-folder-pp/nodejs/aws-s3-folder.ts

Fix TS list iteration. This involves fixing `lambda` generation when exporting an object, as well as fixing the argument order when mapping over arrays.
Fixes #8067

Fix the aws-eks programgen example

---

changelog/pending/20221125--docs--exclude-id-output-property-for-component-resources.yaml
pkg/codegen/docs/gen.go
pkg/codegen/testing/test/testdata/enum-reference/docs/myModule/iamresource/_index.md
pkg/codegen/testing/test/testdata/hyphen-url/docs/registrygeoreplication/_index.md
pkg/codegen/testing/test/testdata/other-owned/docs/barresource/_index.md
pkg/codegen/testing/test/testdata/other-owned/docs/fooresource/_index.md
pkg/codegen/testing/test/testdata/other-owned/docs/otherresource/_index.md
pkg/codegen/testing/test/testdata/plain-schema-gh6957/docs/staticpage/_index.md
pkg/codegen/testing/test/testdata/simple-methods-schema-single-value-returns/docs/foo/_index.md
pkg/codegen/testing/test/testdata/simple-methods-schema/docs/foo/_index.md
pkg/codegen/testing/test/testdata/simple-plain-schema-with-root-package/docs/component/_index.md
pkg/codegen/testing/test/testdata/simple-plain-schema/docs/component/_index.md
pkg/codegen/testing/test/testdata/simple-resource-schema-custom-pypackage-name/docs/otherresource/_index.md
pkg/codegen/testing/test/testdata/simple-resource-schema/docs/barresource/_index.md
pkg/codegen/testing/test/testdata/simple-resource-schema/docs/fooresource/_index.md
pkg/codegen/testing/test/testdata/simple-resource-schema/docs/otherresource/_index.md
pkg/codegen/testing/test/testdata/simple-yaml-schema/docs/otherresource/_index.md

An `id` output property was being emitted for all resources, but component resources do not have an `id`.
Fixes #11462

[docs] Exclude id output property for component resources

---

.github/workflows/download-pulumi-cron.yml

Partially addresses #11342 because there is no sane way to install winget-cli unless already installed and it keeps failing our CI checks. For the time being, disabling the check so that we don't get failures and look into the issue again

Disable failing windows-winget-install wokflow from download cron job

---

changelog/pending/20221121--backend-service--allows-the-service-to-opt-into-bandwidth-optimized-diff-protocol.yaml
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/client/api_endpoints.go
pkg/backend/httpstate/client/client.go
pkg/backend/httpstate/client/client_test.go
pkg/backend/httpstate/diffs.go
pkg/backend/httpstate/snapshot.go
pkg/backend/httpstate/snapshot_test.go

Starts using diff-based PATCH protocol for saving checkpoints for backends that indicate that they support it via `GET /api/capabilities`. Removes flags that opted into the feature. Specifically:
- call GET /api/capabilities in parallel with GetStack call so as not to add to critical path latency
- interpret 404 Not Found as "no capabilities" for backwards compatibility and not forcing a simultaneous backend update
- let the response from /api/capabilities configure a minimal stack size cutoff for opting into the diff-based protocol
- opens the possibility to tune the optimal cutoff with service experimentation
Fixes https://github.com/pulumi/home/issues/2425
I've tested the change against the mainline backend that does not support capabilities yet (404 path) and the experimental backend …

Feature detect diff-based bandwidth-optimized PATCH protocol for saving checkpoints

---

pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/policy_new.go
sdk/go/common/workspace/templates.go

Extension of https://github.com/pulumi/pulumi/pull/11435, but for `pulumi policy new`. 
Part of #11434

Do not fail pulumi policy new on invalid template(s)

---

changelog/pending/20221128--programgen-nodejs--add-between-and.yaml
pkg/codegen/nodejs/gen_program_expressions.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/aws-s3-logging-pp/nodejs/aws-s3-logging.ts

Add `.` between `?` and `]`

---

changelog/pending/20221128--programgen-nodejs--fix-capitalization-when-generating-fs-readdirsync.yaml
pkg/codegen/nodejs/gen_program_expressions.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/aws-s3-folder-pp/nodejs/aws-s3-folder.ts

This lets us reenable the `"aws-s3-folder"` programgen test for nodejs.

Fix capitalization for generated `fs.readdirSync`

---

changelog/pending/20221129--programgen-go--convert-the-result-of-immediate-invokes-to-ouputs-when-necessary.yaml
pkg/codegen/go/gen_program.go
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/aws-fargate-pp/go/aws-fargate.go

Convert plain array values to input values when passing them into an array. 
Fixes #8440

Convert invoke results to ouputs when needed

---

changelog/pending/20221118--cli-about--add-fully-qualified-stack-name-to-current-stack.yaml
pkg/backend/backend.go
pkg/backend/filestate/backend.go
pkg/backend/httpstate/stack.go
pkg/cmd/pulumi/about.go
pkg/cmd/pulumi/stack_ls_test.go

Resolves #11386
```shell
$ pulumi about 
Current Stack: dev
Fully qualified stack name: Fully qualified stack name: friel/tmp.knCczy5IiO/dev
Found no resources associated with dev
Found no pending operations associated with dev
```
```shell
$ pulumi about --json | jq '.currentStack.fullyQualifiedName'
"friel/tmp.knCczy5IiO/dev"
```
When there is no valid stack, the `currentStack` value is `null`. 
Due to an existing bug, when the backend is filestate the `currentStack` value is `null`. It appears on filestate backends we do not render the current stack.

`pulumi about` outputs the fully qualified stack reference

---

changelog/pending/20221201--programgen--improve-error-message-for-invalid-enum-values-on-pulumi-convert.yaml
pkg/codegen/dotnet/gen_program_expressions.go
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/nodejs/gen_program_expressions.go
pkg/codegen/pcl/binder_schema.go
pkg/codegen/pcl/binder_schema_test.go
pkg/codegen/python/gen_program_expressions.go

Fixes #10814 
Currently if an invalid enum value is provided, `(nil, true)` is returned [here](https://github.com/pulumi/pulumi/blob/master/pkg/codegen/pcl/binder_schema.go#L498). On `pulumi convert`, we still try to translate the PCL to the resulting language [here](https://github.com/pulumi/pulumi/blob/master/pkg/codegen/pcl/binder_schema.go#L569), causing an unhelpful error message `(PANIC=Format method: runtime error: invalid memory address or nil pointer dereference)` to be injected into the invalid program text (example in #10814).
This change improves it a bit so that the valid enum values are provided in the error message, i.e. `(PANIC=Format method: fatal: A failure has occurred: Invalid enum provided: valid values are [Block Append])`

Improve error message for invalid enum values on `pulumi convert`

---

changelog/pending/20221201--sdk-nodejs--fix-regression-when-passing-a-provider-to-a-mlc.yaml
sdk/nodejs/runtime/resource.ts
sdk/nodejs/tests/runtime/langhost/run.spec.ts

#11093 changed the Node.js SDK to pass a provider specified in a MLC's `ResourceOptions.provider` to the engine.
Unfortunately, this regresses behavior that existing programs rely on. For example:
```ts
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";
const myRegion = new aws.Provider("us-east-1", {
region: "us-east-1",
});
const vpc = new awsx.ec2.Vpc("awsx-nodejs-default-args", {}, { provider: myRegion });
```
In the above program, an explicit _aws_ provider is being passed to the _aws**x**_ `VPC` component, with the intention that the _aws_ provider will be used as the provider for all of `Vpc`'s children.
With the change in #11093, the engine would try to call `Construct` for the `Vpc` using the specified `aws` provider, which does not work (it fails with …

[sdk/nodejs] Fix regression when passing a provider to a MLC

---

changelog/pending/20221202--sdkgen-nodejs--generate-js-doc-comments-for-output-versioned-invokes-and-use-explicit-any-type.yaml
pkg/codegen/nodejs/gen.go
pkg/codegen/testing/test/testdata/external-resource-schema/nodejs/argFunction.ts
pkg/codegen/testing/test/testdata/functions-secrets/nodejs/funcWithSecrets.ts
pkg/codegen/testing/test/testdata/output-funcs-edgeorder/nodejs/listConfigurations.ts
pkg/codegen/testing/test/testdata/output-funcs-edgeorder/nodejs/listProductFamilies.ts
pkg/codegen/testing/test/testdata/output-funcs-tfbridge20/nodejs/getAmiIds.ts
pkg/codegen/testing/test/testdata/output-funcs-tfbridge20/nodejs/listStorageAccountKeys.ts
pkg/codegen/testing/test/testdata/output-funcs/nodejs/funcWithAllOptionalInputs.ts
pkg/codegen/testing/test/testdata/output-funcs/nodejs/funcWithDefaultValue.ts
pkg/codegen/testing/test/testdata/output-funcs/nodejs/funcWithDictParam.ts
pkg/codegen/testing/test/testdata/output-funcs/nodejs/funcWithEmptyOutputs.ts
pkg/codegen/testing/test/testdata/output-funcs/nodejs/funcWithListParam.ts
pkg/codegen/testing/test/testdata/output-funcs/nodejs/getBastionShareableLink.ts
pkg/codegen/testing/test/testdata/output-funcs/nodejs/getIntegrationRuntimeObjectMetadatum.ts
pkg/codegen/testing/test/testdata/output-funcs/nodejs/listStorageAccountKeys.ts
pkg/codegen/testing/test/testdata/plain-object-defaults/nodejs/funcWithAllOptionalInputs.ts
pkg/codegen/testing/test/testdata/plain-object-disable-defaults/nodejs/funcWithAllOptionalInputs.ts
pkg/codegen/testing/test/testdata/provider-config-schema/nodejs/funcWithAllOptionalInputs.ts
pkg/codegen/testing/test/testdata/simple-resource-schema-custom-pypackage-name/nodejs/argFunction.ts
pkg/codegen/testing/test/testdata/simple-resource-schema/nodejs/argFunction.ts
pkg/codegen/testing/test/testdata/simple-yaml-schema/nodejs/argFunction.ts

- Generate JS doc comments for output-versioned invokes
- Use explicit `any` type within apply lambda
This is part of #11418 but irrelevant to that (big) PR so this will help make the changes smaller and more clear

[typescript/sdk-gen] Generate JS doc comments for output-versioned invokes

---

pkg/backend/httpstate/backend.go

Allow users to opt out of deltaCheckpointUpdates even if the backend indicates it should be used. This remains necessary while PULUMI_OPTIMIZED_CHECKPOINT_PATCH has higher memory requirements on the client and may cause out-of-memory issues in constrained environments.
Part of https://github.com/pulumi/home/issues/2426

Allow opting out of PULUMI_OPTIMIZED_CHECKPOINT_PATCH

---

sdk/go/common/util/mapper/mapper_decode.go
sdk/go/common/util/mapper/mapper_test.go

`map[string]*string` does not turn around through mapper, causing a panic.
```go
go test -run TestReproduceMapStringPointerTurnaroundIssue                                                                                                  ~/code/pulumi/sdk/go/common/util/mapper
--- FAIL: TestReproduceMapStringPointerTurnaroundIssue (0.00s)
mapper_test.go:608: encodedMap: map[args:map[key:value]]
panic: reflect: Elem of invalid type string [recovered]
panic: reflect: Elem of invalid type string
goroutine 20 [running]:
testing.tRunner.func1.2({0x11cb480, 0xc0000992b0})
/nix/store/0c30lcag5r6ahw3qj0x7lkshpry4yqwl-go-1.19/share/go/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
/nix/store/0c30lcag5r6ahw3qj0x7lkshpry4yqwl-go-1.19/share/go/src/testing/testing.go:1399 +0x39f …
```

Fix panic in mapper support for map[string]*string

---

changelog/pending/20221205--sdk--add-methods-to-cast-pointer-types-to-corresponding-pulumi-ptr-types.yaml
sdk/go/pulumi/generate/templates/types_builtins.go.template
sdk/go/pulumi/types_builtins.go

Fixes #11536
Adds methods to convert pointer types to corresponding pulumi Ptr types

Add `*[TYPE]` to `[TYPE]Ptr` methods

---

.github/workflows/ci-run-test.yml

The step to [configure the pagefile on Windows](https://github.com/pulumi/pulumi/actions/runs/3624853251/jobs/6112393713) began failing due to an update to the underlying runner image. Given that this is blocking CI, we'll remove the step for now.
Either #11532 or #11471 should address performance of integration tests and reliability and obviate the need for this step.

ci: Remove page file tweak for Windows

---

.github/workflows/ci-run-test.yml
.vscode/settings.json
changelog/pending/20221205--pkg-testing--optionally-caches-python-venvs-for-testing.yaml
pkg/testing/integration/program.go
tests/integration/integration_python_smoke_test.go

The cache key is based on hashing the contents of "requirements.txt" for each python test.  This should result in unchanged test results among tests sharing venvs, and maintains environment isolation across requirement sets
Fixes #11485

fix(testing): Adds cached python venvs for integration tests

---

Makefile
pkg/codegen/testing/utils/host.go

Updating Pulumi YAML to address pulumi/pulumi-yaml#421 and pulumi/pulumi-yaml#422, requires testing against the Docker v4.0.0-alpha.0 schema. That required updating this repo, and using Go workspaces/module replacement to allow the deploytest plugin loader to find the prerelease schema.
This change allows Pulumi YAML to define its own set of required plugins, decoupling the two repos and preventing the catch-22 here.
Because this repo will need to support the new example being authored which will serve as a test of #421 and #422, this also adds Docker v4.0.0-alpha.0 as a schema.

testing: Allow plugin testing users to define their own plugin sets

---

pkg/codegen/dotnet/gen_program.go
pkg/codegen/pcl/binder_schema.go

Instead of indirecting through .NET function names, just use the schema token to lookup the function.

Simplify `findFunctionSchema`

---

pkg/codegen/pcl/binder_resource.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/simple-range-pp/dotnet/simple-range.cs
pkg/codegen/testing/test/testdata/simple-range-pp/go/simple-range.go
pkg/codegen/testing/test/testdata/simple-range-pp/nodejs/simple-range.ts
pkg/codegen/testing/test/testdata/simple-range-pp/python/simple-range.py
pkg/codegen/testing/test/testdata/simple-range-pp/simple-range.pp

Fixes the binding issue with `options { range = number }`.

Fix PCL binding of options.range = number

---

changelog/pending/20221206--sdk-dotnet-nodejs--add-inokesingle-variants-to-dotnet-and-nodejs-sdks.yaml
sdk/dotnet/Pulumi/Deployment/DeploymentInstance.cs
sdk/dotnet/Pulumi/Deployment/Deployment_Invoke.cs
sdk/dotnet/Pulumi/Deployment/IDeployment.cs
sdk/dotnet/Pulumi/PublicAPI.Shipped.txt
sdk/nodejs/runtime/invoke.ts

Needed for #11418 where we have invoke calls that return a simple type (such as `number`) but the runtime and engine _require_ the outputs to be a struct (as per the RPC definition) so here we are adding variants of `invoke` that unwraps the returned object and gets the first value from that object.
For example, a provider with a schema `outputs: { type: "number" }` will have an invoke implementation that returns `{ __result: 42.0 }`, in these case (non-object return types) we use `InvokeSingle` instead of `Invoke`
> It doesn't matter what the name of the key is, we always get the first value by first key.

[sdk/dotnet/nodejs] Add InvokeSingle variants to dotnet and nodejs SDKs

---

pkg/codegen/python/doc.go
pkg/codegen/python/gen.go
pkg/codegen/python/gen_program.go
pkg/codegen/python/gen_program_expressions.go
pkg/codegen/python/gen_resource_mappings.go
pkg/codegen/schema/bind.go
pkg/codegen/schema/schema.go
pkg/codegen/utilities.go

Part of https://github.com/pulumi/pulumi/issues/9932
tldr: `Package` is not reliable when its used for an external package. We are transferring over to `PackageReference`, and will remove the `Package` field once all references to it have been removed.

Don't use *schema.Package in python codegen

---

.github/workflows/on-pr.yml

The [PR workflow to update Pulumi YAML to 1.0.4](https://github.com/pulumi/pulumi/actions/runs/3642973677) shows that it created a draft release, and this has been the case for all contributors' PRs.
This fixes the extra alpha releases created as a result of pull requests. The job "prepare-release" shouldn't run unless the ci/test label is set, indicating an intent to evaluate the full CI pipeline.

ci: Fix extraneous alpha draft releases

---

.github/workflows/ci-run-test.yml
.github/workflows/ci.yml
scripts/get-job-matrix.py

The `continue-on-error` flag is set to true whenever the matrix platform contains "windows" for smoke tests. This does mean these jobs will allow failures and proceed, however this should substantially reduce the false negatives due to the behavior of the CI platform. Per the response from GitHub support ticket on my account:
> I've confirmed that our engineering team has an open backlog item focused around "protecting" the provisioning service in cases of resource starvation. I believe this will address your exact concerns so that high resource consumption does not result in an abandoned job.
> 
> In the meantime, there unfortunately is not much capability exposed for affecting priority on the VM. Until improvements are implemented, our team still recommends trying to reduce load on the …

Improve `bors` merge reliability: Windows smoke tests are advisory and run with reduced parallelism

---

changelog/pending/20221206--sdk-python--allows-for-duplicate-output-values-in-python.yaml
sdk/python/.gitignore
sdk/python/lib/pulumi/runtime/stack.py
sdk/python/lib/test/langhost/stack_output/__main__.py
sdk/python/lib/test/langhost/stack_output/test_stack_output.py

I used the node SDK as inspiration for this change - there were a few things we were doing differently in python (specifically handling all cases in the outer layer of `massage` rather than allowing for more fine-grained control in a `massage_complex` function like in node.  We also take the stack concept from the node SDK to resolve the immediate issue of duplicate outputs.
Fixes #11133

fix(sdk/python): Allow for duplicate output values in python programs

---

changelog/pending/20221208--sdkgen-dotnet-go-nodejs-python--do-not-generate-result-types-for-functions-with-empty-outputs.yaml
pkg/codegen/dotnet/gen.go
pkg/codegen/go/gen.go
pkg/codegen/nodejs/gen.go
pkg/codegen/python/gen.go
pkg/codegen/schema/schema.go
pkg/codegen/testing/test/testdata/output-funcs/docs/funcwithemptyoutputs/_index.md
pkg/codegen/testing/test/testdata/output-funcs/dotnet/FuncWithEmptyOutputs.cs
pkg/codegen/testing/test/testdata/output-funcs/go/mypkg/funcWithEmptyOutputs.go
pkg/codegen/testing/test/testdata/output-funcs/nodejs/funcWithEmptyOutputs.ts
pkg/codegen/testing/test/testdata/output-funcs/nodejs/index.ts
pkg/codegen/testing/test/testdata/output-funcs/python/pulumi_mypkg/func_with_const_input.py
pkg/codegen/testing/test/testdata/output-funcs/python/pulumi_mypkg/func_with_empty_outputs.py
pkg/codegen/testing/test/testdata/regress-node-8110/python/pulumi_my8110/example_func.py
pkg/codegen/testing/test/testdata/simple-plain-schema/python/pulumi_example/do_foo.py

Part of #11418 where we shouldn't generate result types for function invokes that have no properties. 
This is a separate PR to showcase the exact changes required to improve the situation and reduce the diff from #11418

[sdk/gen] Avoid generating Result types for functions with empty outputs

---

pkg/cmd/pulumi/convert.go

Had the setting of this flag to false on the "read pcl", but it actually needs to be set on the "write pcl" side. That is if we write out a PCL project, don't try to install dependencies on it.

Fix generate flag for pcl convert

---

pkg/cmd/pulumi/new.go

Document that `pulumi new` can use a local path for templates

---

changelog/pending/20221209--sdk-go--add-jsonmarshal-to-go-sdk.yaml
sdk/go/pulumi/generate/templates/types_builtins.go.template
sdk/go/pulumi/types.go
sdk/go/pulumi/types_builtins.go
sdk/go/pulumi/types_test.go

This is not as useful for Go as it is for other languages, but it's consistent and it saves an Apply call.
Ideally we would handle nested Output types during marshalling, but to do that correctly we need some way to get access to per-call-to-JSONMarshal flags to note if we see any unknowns, or secrets.
Go just doesn't (AFAIK) have any way to support doing that.
So we do the next best thing which is we at least error that nested Outputs can't be marshalled. Note that the `Output` interface doesn't embed the `Marshal` interface because there _may_ be users who have wrote their own `Output` types and that would be a breaking change.

Add JSONMarshal to go sdk

---

changelog/pending/20221208--sdk-python--fix-a-deadlock-on-provider-side-error-with-automation-api.yaml
sdk/python/lib/pulumi/automation/_server.py

The rationale behind this change is explained in the linked issue. I haven't worked on the Checklist below, as I'd like to get an eye with more pulumi knownledge on the issue beforehand.
Also, reproducing deadlocks in unit tests is always quite tricky, so I'd rather not do it until I'm sure this is the proper approach
Fixes #11594

fix: Prevent a deadlock on provider error in py automation api

---

sdk/dotnet/Pulumi.Tests/Core/OutputTests.cs

Couple of tests for Output.Format, prompted by looking into https://github.com/pulumi/pulumi/issues/11623 and seeing that we seem to have zero tests for this method right now.

Add some basic tests for Output.Format

---

changelog/pending/20221212--programgen-go--Check-for-optional-Ptr-types-within-Union-types.yaml
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/testing/test/testdata/aws-s3-logging-pp/go/aws-s3-logging.go
pkg/codegen/testing/test/testdata/synthetic-resource-properties-pp/go/synthetic-resource-properties.go

Fixes #11496 
This fixes a bug in Go programgen where optional outputs are not returned as pointers (example in ticket)

Check for optional/ Ptr types within Unions [go/programgen]

---

changelog/pending/20221116--cli--adds-a-flag-that-allows-user-to-set-the-node-label-as-the-resource-name-instead-of-the-full-urn-in-the-stack-graph.yaml
pkg/cmd/pulumi/stack_graph.go

This feature allows the user to opt for short node labels, i.e, only the resource name part of the URN instead of the full URN that is returned as the node label in the stack graph while using ```pulumi stack graph``` command. A flag named ```short-node-name``` is added to the ```pulumi stack graph``` command that enables this feature.
Existing command : ```pulumi stack graph [file-name]```
Example : ```pulumi stack graph dev```
Output for dev :
strict digraph {
Resource0 [label="urn:pulumi:dev::Test-Simple-Stack::pulumi:pulumi:Stack::Test-Simple-Stack-dev"];
Resource1 [label="urn:pulumi:dev::Test-Simple-Stack::pulumi:providers:aws-native::default_0_40_2"];
Resource2 [label="urn:pulumi:dev::Test-Simple-Stack::aws-native:s3:Bucket::my-bucket2"];
Resource2 -> Resource0 [color = "#AA6639"]; …

Feature - Short Node Label for Stack Graph

---

changelog/pending/20221117--cli--delete-stack-config-file-on-pulumi-remove.yaml
pkg/cmd/pulumi/destroy.go

`pulumi destroy --remove` command now will delete also the stack config file. This will be consistent with `pulumi stack rm`
Fixes #11198

Pulumi destroy --remove command deletes stack config file

---

tests/integration/nodejs/esm-srcdir-ts/Pulumi.yaml
tests/integration/nodejs/esm-srcdir-ts/package-lock.json
tests/integration/nodejs/esm-srcdir-ts/package.json
tests/integration/nodejs/esm-srcdir-ts/src/index.ts
tests/integration/nodejs/esm-srcdir-ts/src/other.ts
tests/integration/nodejs/esm-srcdir-ts/tsconfig.json

Trying to use `ts-node` with the loader for top level async-await seems to fail if the Pulumi code is inside a `src` directory, a rather common pattern for Pulumi users.
I don't know why, but adding this test-case to hopefully help get some fixes
Fixes #9153

chore: add new test case for esm-loading with a srcdir

---

sdk/dotnet/Pulumi/Exceptions/LogException.cs

I'd like to expose `LogException`. In general I think it's good that Exceptions are exposed, so they can be caught.
In this particular case, I'd love to be able to diagnose #9582 more effectively, and perhaps even retry if that's the type of error that happens.

Expose LogException

---

pkg/cmd/pulumi/import.go
pkg/codegen/importer/hcl2.go

Allow passing raw URN instead of `name=URN` for parent and provider, defaulting name to `parent` and `provider` respectively.
Report an error if the names of the parent and provider are the same (instead of silently overwriting the parent with the provider).
Provide better error messages if the provided URN is not a URN - specifically if it is a provider reference.
Fix up an error message that included a parent instead of provider URN.
Also update the help text with some additional examples.
Fixes #5958.
Contributes to #10288.

[import] Parent and Provider improvements

---

changelog/pending/20221212--cli-display--fixes-negative-durations-on-update-display.yaml
pkg/backend/display/progress.go
tests/integration/integration_nodejs_test.go

Fixes #11188 
This PR fixes negative times showing up on the update display. This was caused by operations that did not emit a resource output event using the end time for the previous operation if it existed. This change clears the old end time if it exists.
~TODO~

fix negative stopwatch times

---

pkg/go.mod
pkg/testing/integration/program.go
pkg/testing/integration/program_test.go
tests/go.mod
tests/go.sum
tests/integration/aliases/aliases_go_test.go

This improves and expands on ProgramTest behavior for initializing Go programs, enabling better relative path handling and adding some safeguards. These are documented in `TestGoModEdits`.

Improve ProgramTest errors and path handling for Go programs

---

pkg/codegen/go/gen_program.go

Fixes #11584 .
This fixes a codegen bug where `=` was always being used when generating a local variable with no assignment (assigning to `_`), which is incorrect if an error is also being assigned to for the first time (`_, err := ...`).

Fix undeclared err codegen bug

---

changelog/pending/20221209--sdk-python--add-jsondumps-to-python-sdk.yaml
sdk/python/lib/pulumi/output.py
sdk/python/lib/test/test_output.py

Following on with adding to json functions to each SDK, this one is for Python.
It even handles nested Outputs via our _sync_await helper.

Add json_dumps to python sdk

---

pkg/codegen/schema/pulumi.json

Signed-off-by: Ringo De Smet <ringo@de-smet.name>
The `language` section in the JSON Schema for our Pulumi schema is defined as `object` without any further details:
https://github.com/pulumi/pulumi/blob/6f21c0dacafdcd5f7a45147ed9e192281932e9c3/pkg/codegen/schema/pulumi.json#L127-L130
This PR extends the JSON schema to cover for all the properties defined in the structs of the language specific importers:
* [pkg/codegen/dotnet/importer.go](https://github.com/pulumi/pulumi/blob/6f21c0dacafdcd5f7a45147ed9e192281932e9c3/pkg/codegen/dotnet/importer.go#L29-L43)
* [pkg/codegen/go/importer.go](https://github.com/pulumi/pulumi/blob/6f21c0dacafdcd5f7a45147ed9e192281932e9c3/pkg/codegen/go/importer.go#L24-L90)
* [pkg/codegen/nodejs/importer.go](https://github.com/pulumi/pulumi/blob/6f21c0dacafdcd5f7a …

Expanding the JSON Schema definition for `language` of the Pulumi Schema

---

sdk/go/common/workspace/plugins.go

Just happened to notice this, so figured I'd fix it quick:

Add a space in plugin error message

---

pkg/testing/integration/program_test.go

PR #11611 assumed a unix-y error message in one of the failure cases of the test `TestGoModEdits`. This case did not match on Windows:
```
=== FAIL: testing/integration TestGoModEdits/invalid-path-non-existent (0.00s)
program_test.go:170: 
Error Trace:	C:\a\pulumi\pulumi\pkg\testing\integration\program_test.go:170
Error:      	Error "error reading go.mod at ../../../.tmp.non-existent-dir: open ..\\..\\..\\.tmp.non-existent-dir\\go.mod: The system cannot find the path specified." does not contain "open ../../../.tmp.non-existent-dir/go.mod: no such file or directory"
Test:       	TestGoModEdits/invalid-path-non-existent
--- FAIL: TestGoModEdits/invalid-path-non-existent (0.00s)
```

Fix test failure on Windows

---

changelog/pending/20221213--cli--improve-performance-of-convert-to-not-try-and-load-so-many-provider-plugins.yaml
pkg/codegen/convert/mapper.go
sdk/go/common/resource/plugin/provider_server.go

What it says on the tin. Makes the PluginMapper lazy so for yaml we don't have to load every plugin in ~/.pulumi/plugins.
We don't load any provider plugins until we need to load an conversion mapping that we don't yet have.
Once we find the first provider that supplies a conversion mapping we stop looking for any more.
The only other improvement to make here that I think is possible is to shut down the providers after asking for their conversion mapping data. But that needs a rejig of how plugin.Host works, which is hard to do right now as it's a public api.

Make the PluginMapper lazy

---

pkg/cmd/pulumi/convert.go
pkg/cmd/pulumi/convert_test.go
pkg/cmd/pulumi/env.go
pkg/cmd/pulumi/pulumi.go
pkg/codegen/report/report.go
sdk/go/common/env/env.go
sdk/go/common/resource/plugin/host.go
sdk/go/common/util/env/env.go
sdk/go/common/util/env/env_test.go
sdk/go/common/workspace/plugins.go

Add a library to encapsulate environmental variable declaration, lookup and parsing. 
Variables strongly typed and declared in the module scope like so:
```go
// Automatically prefixed with PULUMI_ by default
var Experimental = env.Bool("EXPERIMENTAL", "Enable experimental options and commands")
```
Values are accessed by calling `.Value()` on the module level variable:
```go
if Experimental.Value() { // .Value() returns a bool here
// do the new exiting thing
} else {
// do the well tested thing
}
```
Environmental variables can be predicated on other boolean type variables:
```go
var NewThingParam = env.String("NEW_THING", "pass this to the new thing", 
env.Needs(Expiremental))
```
Predicated variables will only show up as set if there predicate is `true`:
```go
if v := …
```

Library for environmental variable access

---

changelog/pending/20221215--programgen--dont-panic-on-some-empty-objects.yaml
pkg/codegen/pcl/invoke.go

Fixes #11658
I have been unable to repro the bug, but since `annotateObjectProperties` is advisory, I'm adding some defensive `nil` checks.

Don't panic when annotating with missing objects

---

changelog/pending/20221206--cli--allow-rotating-the-encrpytion-key-for-cloud-secrets.yaml
pkg/backend/filestate/crypto.go
pkg/cmd/pulumi/crypto.go
pkg/cmd/pulumi/crypto_cloud.go
pkg/cmd/pulumi/crypto_cloud_test.go
pkg/cmd/pulumi/stack_change_secrets_provider.go
pkg/cmd/pulumi/util.go

Little thing I noticed while looking at secrets. We support the idea of rotating the passphrase secret provider (that is changing the key and assigning a new passphrase). Turns out this makes sense for the cloud secret provider as well where we generate a new symmetric key.

Rotate cloud secrets provider

---

changelog/pending/20221031--sdk-nodejs--delegates-alias-computation-to-engine-for-node-sdk.yaml
pkg/resource/deploy/step_generator.go
sdk/go/common/util/env/env.go
sdk/nodejs/resource.ts
sdk/nodejs/runtime/resource.ts
sdk/nodejs/runtime/settings.ts
sdk/nodejs/tests/runtime/langhost/cases/072.large_alias_lineage_chains/index.js
sdk/nodejs/tests/runtime/langhost/run.spec.ts
tests/go.mod
tests/integration/aliases/nodejs/adopt_into_component/step2/index.ts

This moves the alias computation from the node SDK to the engine (which now does these computations for us as of #10819 ).  This dramatically improves performance when resources with many aliases are parented to one another.
Fixes #11062

feat(sdk/nodejs): delegates alias computation to the engine

---

pkg/codegen/hcl2/model/expression.go
pkg/codegen/pcl/rewrite_convert.go

Passing a typed `nil` through a interface conversion, such as a `*hclsyntax.UnaryOpExpr` through a `hclsyntax.Node` interface will result in a half-nil fat pointer with the value part `nil`. Since most of programgen assumes that `(model.Expression).SyntaxNode().Range()` is valid, a `syntax.None` is passed instead of a `nil`.

Don't return half-nil fat ptrs from `SyntaxNode()`

---

.github/workflows/ci-build-binaries.yml
.github/workflows/ci-prepare-release.yml
.github/workflows/ci.yml
.github/workflows/on-merge.yml
.github/workflows/on-pr.yml
.github/workflows/pr-test-acceptance-on-dispatch.yml
changelog/pending/20221109--ci--sign-pulumi-binaries-with-cosign.yaml

This PR adds cosign to the build process of the Pulumi binaries. I changed the pipeline so cosign can sign without keys by authenticating with OIDC. GitHub supports this.

feat: sign pulumi binaries with cosign

---

changelog/pending/20221218--auto-dotnet-go-nodejs-python--adds-skipinstalldependencies-option-for-remote-workspaces.yaml
pkg/cmd/pulumi/util_remote.go
sdk/go/auto/local_workspace.go
sdk/go/auto/remote_workspace.go
sdk/go/auto/remote_workspace_test.go
sdk/go/auto/stack.go
sdk/go/common/apitype/deployments.go
sdk/nodejs/automation/localWorkspace.ts
sdk/nodejs/automation/remoteWorkspace.ts
sdk/nodejs/tests/automation/remoteWorkspace.spec.ts
sdk/python/lib/pulumi/automation/_local_workspace.py
sdk/python/lib/pulumi/automation/_remote_workspace.py
sdk/python/lib/test/automation/test_remote_workspace.py

Automation API support for the `skipInstallDependencies` Deployments API option.
Fixes #11357

[auto] RemoteWorkspaces: Add `skipInstallDependencies` option

---

changelog/pending/20221217--sdkgen-go--illegal-cast-in-resource-constructors-when-secret-wrapping-input-arguments.yaml
pkg/codegen/go/gen.go
pkg/codegen/testing/test/testdata/nested-module-thirdparty/go/foo/deeply/nested/module/resource.go
pkg/codegen/testing/test/testdata/nested-module/go/foo/nested/module/resource.go
pkg/codegen/testing/test/testdata/provider-config-schema/go/configstation/provider.go
pkg/codegen/testing/test/testdata/secrets/go/mypkg/resource.go
pkg/codegen/testing/test/testdata/simple-resource-schema/go/example/resource.go
pkg/codegen/testing/test/testdata/simple-yaml-schema/go/example/resource.go

Fixes #11664 after new SDK gen. Will require an update to pulumi-aws using this branch or a new release.
Codegen for wrapping input properties as secrets performed an incorrect cast, as seen in Pulumi's AWS classic SDK.
Using the sample program and the resource constructor described in #11664 as our test case, from `pulumi-aws/sdk/v5/go/aws/secretmanager/secretVersion.go`:
```go
func NewSecretVersion(ctx *pulumi.Context,
name string, args *SecretVersionArgs, opts ...pulumi.ResourceOption) (*SecretVersion, error)
if args == nil {
return nil, errors.New("missing one or more required arguments")
}
if args.SecretId == nil {
return nil, errors.New("invalid value for required argument 'SecretId'")
}
if args.SecretBinary != nil {
82:        args.SecretBinary = …
```

Fix illegal cast in resource constructors when secret-wrapping input arguments.

---

pkg/codegen/hcl2/model/diagnostics.go
pkg/codegen/hcl2/model/pretty/display.go
pkg/codegen/hcl2/model/pretty/display_test.go
pkg/codegen/hcl2/model/type.go
pkg/codegen/hcl2/model/type_const.go
pkg/codegen/hcl2/model/type_enum.go
pkg/codegen/hcl2/model/type_list.go
pkg/codegen/hcl2/model/type_map.go
pkg/codegen/hcl2/model/type_none.go
pkg/codegen/hcl2/model/type_object.go
pkg/codegen/hcl2/model/type_opaque.go
pkg/codegen/hcl2/model/type_output.go
pkg/codegen/hcl2/model/type_promise.go
pkg/codegen/hcl2/model/type_set.go
pkg/codegen/hcl2/model/type_tuple.go
pkg/codegen/hcl2/model/type_union.go

This PR changes how type errors are printed, adding multi-line pretty printing to types. It is part of an effort to make PCL type error messages better (https://github.com/pulumi/pulumi/issues/11573).
For comparison, here is the same error message with and without this PR:
Before:
```
--- FAIL: TestGenerateExamples (0.00s)
--- FAIL: TestGenerateExamples/aws-static-website (0.19s)
example_transpile_test.go:124: 
Error Trace:    /Users/ianwahbe/go/src/github.com/pulumi/pulumi-yaml/pkg/tests/example_transpile_test.go:124
Error:          Should be false
Test:           TestGenerateExamples/aws-static-website
Messages:       aws-static-website.pp:9,11-21: cannot assign expression of type object({accelerateConfiguration = output(union(none, object({accelerationStatus = …
```

Pretty print PCL types in error messages

---

pkg/codegen/go/gen_program.go
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/testing/test/testdata/aws-optionals-pp/go/aws-optionals.go
pkg/codegen/testing/test/testdata/aws-webserver-pp/go/aws-webserver.go
pkg/codegen/testing/test/testdata/kubernetes-pod-pp/dotnet/kubernetes-pod.cs
pkg/codegen/testing/test/testdata/kubernetes-pod-pp/go/kubernetes-pod.go
pkg/codegen/testing/test/testdata/kubernetes-pod-pp/kubernetes-pod.pp
pkg/codegen/testing/test/testdata/kubernetes-pod-pp/nodejs/kubernetes-pod.ts
pkg/codegen/testing/test/testdata/kubernetes-pod-pp/python/kubernetes-pod.py

Fixes #11663
Fix incorrect pointer argument codegen when objects are nested inside an array whose type is not a pointer.
Example:
`&s3.BucketLoggingArgs` is valid here
```
bucket, err := s3.NewBucket(ctx, "bucket", &s3.BucketArgs{
Loggings: s3.BucketLoggingArray{
&s3.BucketLoggingArgs{
TargetBucket: logs.Bucket,
},
},
})
```
but `&ec2.SubnetSpecArgs{}` is invalid here:
```
SubnetSpecs: []ec2.SubnetSpecArgs{
&ec2.SubnetSpecArgs{
Type:     ec2.SubnetTypePublic,
CidrMask: 22,
},
&ec2.SubnetSpecArgs{
Type:     ec2.SubnetTypePrivate,
CidrMask: 20,
},
},
```
Instead, it should be: 
```
SubnetSpecs: []ec2.SubnetSpecArgs{
{
Type:     ec2.SubnetTypePublic,
CidrMask: 22,
},
{
Type:     ec2.SubnetTypePrivate,
CidrMask: 20,
},
},
```

Fix incorrect pointers for array of objects [go/codegen]

---

changelog/pending/20221220--cli-plugin--fix-check-of-executable-bits-on-windows.yaml
pkg/cmd/pulumi/package.go
pkg/cmd/pulumi/plugin_install.go

Fixes the checking of executable bits for plugins in Windows (which doesn't have executable bits).
Obligatory https://fasterthanli.me/articles/i-want-off-mr-golangs-wild-ride#simple-is-a-lie given I literally re-read this yesterday and then hit _this_ today.

Fix executable checks for windows

---

.github/workflows/release.yml

Now that dotnet has been exfiltrated to https://github.com/pulumi/pulumi-dotnet we do not release it as part of the release workflow. The release step errors since the dotnet artifacts are no longer uploaded to GitHub as part of the release bundle.
Is there an easy way to test this change?

Remove Dotnet from release step of GH workflow

---

pkg/backend/snapshot.go
pkg/backend/snapshot_test.go
pkg/cmd/pulumi/util.go
pkg/engine/deployment.go
pkg/resource/deploy/source_eval.go
sdk/go/common/env/env.go
sdk/go/common/util/cmdutil/console.go

This is one of many PRs to port our environmental variable usage over to the new library.
I modified `cmdutil.Table` to allow printing multi-line rows to allow vars to have multi-line documentation.

Move over some env vars to the new lib

---

pkg/codegen/hcl2/model/diagnostics.go
sdk/go/common/env/env.go

Fixes https://github.com/pulumi/pulumi/issues/11722
The aim is to remove this flag after the `pretty` library can provably handle recursive types.
Related to #11676

Make pretty-printing conditional

---

changelog/pending/20221226--sdk-nodejs--add-jsonparse.yaml
sdk/nodejs/output.ts
sdk/nodejs/tests/output.spec.ts

Partner method to jsonStringify.

Add jsonParse to nodejs sdk

---

pkg/testing/integration/program_test.go

TestGoModEdits requires that one of the following conditions
be true for the test to pass:
- pulumi/pulumi is checked out at $GOPATH/src/github.com/pulumi/pulumi
- PULUMI_GO_DEP_ROOT is set to the directory where it's checked out
With wide usage of Go modules,
we're less likely to have folks working under GOPATH.
As for PULUMI_GO_DEP_ROOT, it makes sense for the generic utility:
Being able to specify where the dependency is checked out
is useful on a per-project basis,
but it makes less sense for this test.
This test is specifically checking the values inside the sdk/go.mod
and the path for that is always fixed.
This change modifies TestGoModEdits to pass
no matter where the repository is checked out
-- as long as it's called "pulumi".
It does so by hard-coding the position of the …

testing/integration: Fix failure without GOPATH

---

pkg/backend/httpstate/backend.go
sdk/go/common/apitype/service.go

Revv capability API to V2

---

pkg/codegen/testing/test/testdata/logical-name-pp/dotnet/logical-name.cs
pkg/codegen/testing/test/testdata/logical-name-pp/go/logical-name.go
pkg/codegen/testing/test/testdata/logical-name-pp/logical-name.pp
pkg/codegen/testing/test/testdata/logical-name-pp/nodejs/logical-name.ts
pkg/codegen/testing/test/testdata/logical-name-pp/python/logical-name.py

PCL config can also have a logical name but that wasn't covered in the logical name test. Small test addition to cover that.

Add config to logical-name-pp test

---

sdk/go/pulumi/mocks.go
sdk/go/pulumi/run_test.go

Continuing to replace "github.com/pkg/errors" with "errors", this handles everything in sdk/go/pulumi.

Clean up use of pkg/errors in sdk/go/pulumi

---

sdk/go/pulumi/types.go

Related to https://github.com/pulumi/pulumi/issues/11727 though that might have possibly been fixed on master already, as the last known failing version is  3.43.1

Make sure output state deps is only accessed under a lock

---

pkg/backend/apply.go

For the options presented in the 'Do you want to perform this update?'
dialog, move the experimental option to the bottom.
Before:
```
Do you want to perform this update?  [Use arrows to move, type to filter]
[experimental] yes, using Update Plans (https://pulumi.com/updateplans)
yes
> no
details
```
Now:
```
Do you want to perform this update?  [Use arrows to move, type to filter]
yes
> no
details
[experimental] yes, using Update Plans (https://pulumi.com/updateplans)
```
Fixes #11800

cli/update: Move experimental option to bottom

---

.golangci.yml
pkg/backend/httpstate/backend.go
pkg/cmd/pulumi/view-trace.go
pkg/codegen/docs/gen.go
sdk/go/auto/example_test.go

This opts the project into [nolintlint],
which finds incorrect usages of the `//nolint` directive.
If used incorrectly, these can show up the project's API Reference,
which looks a bit shoddy.
[nolintlint]: https://github.com/golangci/golangci-lint/blob/master/pkg/golinters/nolintlint/README.md
Note that this configures the linter to ignore unused directives.
We have a bunch of those across the project,
and some of them are in generated or templated files.
In addition to enabling the linter,
this fixes a couple other nolint directives
that were missed in #11791.
Depends on #11791
Relates to #11785

golangci-lint: Opt into nolintlint

---

pkg/codegen/docs/gen_test.go
pkg/codegen/docs/package_tree_test.go

Tests in pkg/codegen/docs all run in parallel,
but many of them call initTestPackageSpec,
which modifies the global testPackageSpec variable.
So these tests end up stomping on each other.
`go test -race` fails in this directory.
To address the data race,
this change deletes the global variable entirely,
and replaces initTestPackageSpec with newTestPackageSpec.
newTestPackageSpec returns a new copy of the package spec
which the tests can use individually.
Resolves #11790

pkg/codegen/docs: Fix data race in tests

---

changelog/pending/20221228--sdk-python--add-output-json_loads-using-json-loads.yaml
sdk/python/lib/pulumi/output.py
sdk/python/lib/test/test_output.py

Add json_loads to python sdk

---

changelog/pending/20221229--sdk-go--add-output-jsonunmarshal-using-encoding-json.yaml
sdk/go/pulumi/types.go
sdk/go/pulumi/types_test.go

Partner method to JSONMarshal.

Add JSONUnmarshal to go sdk

---

changelog/pending/20230107--cli-new--allow-running-inside-new-git-repositories.yaml
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/new_test.go

The following set of operations currently fail with the CLI.
git init
pulumi new
This is because `pulumi new` refuses to run inside
non-empty directories.
This changes `pulumi new` to ignore .git, .hg, and .bzr
files/directories when considering whether a directory is empty.
Resolves #11789

cli/new: Ignore VCS directories

---

sdk/go/auto/example_test.go

example_test is opted out of all linters for some reason.
Instead, opt-out only of the ones that it wants to ignore:
errcheck and goconst.
Enabling other linters also found a typo in the comments:
verison instead of version.

auto/example_test: Opt-out specific linters, fix typos

---

pkg/backend/display/diff_test.go
pkg/backend/display/progress_test.go

`bytes.Buffer` has a `String()` method
that is equivalent to `string(b.Bytes())`.

backend/display/test: string(buffer.Bytes()) => buffer.String()

---

pkg/codegen/dotnet/gen_program_test/batch1/gen_program_test.go
pkg/codegen/dotnet/gen_program_test/batch2/gen_program_test.go
pkg/codegen/dotnet/gen_program_test/batch3/gen_program_test.go
pkg/codegen/dotnet/gen_program_test/batch4/gen_program_test.go
pkg/codegen/dotnet/gen_program_test/batch5/gen_program_test.go
pkg/codegen/dotnet/gen_program_test/batch6/gen_program_test.go
pkg/codegen/go/gen_program_test/batch1/gen_program_test.go
pkg/codegen/go/gen_program_test/batch2/gen_program_test.go
pkg/codegen/go/gen_program_test/batch3/gen_program_test.go
pkg/codegen/go/gen_program_test/batch4/gen_program_test.go
pkg/codegen/go/gen_program_test/batch5/gen_program_test.go
pkg/codegen/go/gen_program_test/batch6/gen_program_test.go
pkg/codegen/nodejs/gen_program_test/batch1/gen_program_test.go
pkg/codegen/nodejs/gen_program_test/batch2/gen_program_test.go
pkg/codegen/nodejs/gen_program_test/batch3/gen_program_test.go
pkg/codegen/nodejs/gen_program_test/batch4/gen_program_test.go
pkg/codegen/nodejs/gen_program_test/batch5/gen_program_test.go
pkg/codegen/nodejs/gen_program_test/batch6/gen_program_test.go
pkg/codegen/python/gen_program_test/batch1/gen_program_test.go
pkg/codegen/python/gen_program_test/batch2/gen_program_test.go
pkg/codegen/python/gen_program_test/batch3/gen_program_test.go
pkg/codegen/python/gen_program_test/batch4/gen_program_test.go
pkg/codegen/python/gen_program_test/batch5/gen_program_test.go
pkg/codegen/python/gen_program_test/batch6/gen_program_test.go

Runs `gofmt -w -s` on all files.
Command used to make this change:
gofmt -w -s $(rg --files -g '*.go' | rg -v compilation_error)
Depends on #11821
Refs #10327

all: gofmt -w -s

---

.github/workflows/ci-lint.yml

Now that all code is gofmt compliant (#11822),
we can upgrade to the latest golangci-lint.
We should be able to re-enable staticcheck
some time after this lands.
Refs #10327
Refs #9280

ci/lint: Use latest golangci-lint

---

.golangci.yml

golangci-lint constantly prints this message:
```
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
```
Drop these linters and enable the 'unused' linter.
Depends on #11823

golangci-lint: Drop deprecated linters

---

pkg/engine/lifecycletest/pulumi_test.go
pkg/engine/plugin_host.go
pkg/resource/deploy/deploytest/pluginhost.go
pkg/resource/deploy/deploytest/resourcemonitor.go
pkg/resource/provider/host.go
sdk/go/common/resource/plugin/analyzer_plugin.go
sdk/go/common/resource/plugin/langruntime_plugin.go
sdk/go/common/resource/plugin/provider_plugin.go
sdk/go/common/util/rpcutil/health.go
sdk/go/pulumi/context.go
sdk/nodejs/cmd/pulumi-language-nodejs/main.go
sdk/python/cmd/pulumi-language-python/main.go
tests/integration/integration_util_test.go

[grpc.WithInsecure](https://pkg.go.dev/google.golang.org/grpc#WithInsecure) is deprecated.
Instead, we're expected to use:
grpc.WithTransportCredentials(insecure.NewCredentials())
This updates all instances across pkg/, sdk/ and tests/.
In service to #11808

grpc: WithInsecure is deprecated

---

pkg/backend/filestate/state.go
pkg/operations/resources_test.go
pkg/resource/stack/checkpoint.go

SerializeCheckpoint takes the `secrets.Manager` to use as a parameter.
DeserializeCheckpoint was hardcoded to always use the `DefaultSecretsProvider`, this changes it to take it to also take it as a parameter, and lifts the setting of `DefaultSecretsProvider` up to filestate.
Later changes will work out how to lift `DefaultSecretsProvider` out of filestate and httpstate.

Lift DefaultSecretsProvider out of DeserializeCheckpoint

---

pkg/engine/lifecycletest/pulumi_test.go
pkg/resource/deploy/step.go

Change the error message for deleting protected resources so it sounds less like we tried and failed to delete the resource, and more like we chose not to. 
Fixes #11816

Cleanup diag error for protected resources

---

pkg/resource/stack/checkpoint.go
pkg/resource/stack/deployment.go
pkg/resource/stack/secrets.go
pkg/secrets/provider.go

Trying to push DefaultSecretsProvider up past the backends resulted in a module loop between pkg/resource/stack and pkg/resource/deploy. This places SecretProvider in the secrets module to avoid that.

Move SecretsProvider to pkg/secrets

---

pkg/go.mod
pkg/resource/deploy/deploytest/resourcemonitor.go
pkg/resource/deploy/deploytest/resourcemonitor_test.go

Another step towards #11808.
ResourceMonitor.Call calls ResourceMonitorClient.Call
and converts the output into a few different results.
During the conversion, it builds a `map[PropertyKey][]URN`,
but it never fills that map with values,
and instead always returns the empty map.
This was caught by staticcheck:
```
resource/deploy/deploytest/resourcemonitor.go:390:11: SA4010: this result of append is never used, except maybe in other appends (staticcheck)
```

deploytest/ResourceMonitor: Don't drop deps

---

sdk/go/common/resource/plugin/rpc_test.go

TestAssetSerialize prints to stdout from the test.
This seems like a leftover from debugging.
Drop that in favor of a t.Logf so that if the test fails,
the print is still available in the output.

sdk/resource/plugin: Don't print from test

---

sdk/go/common/resource/plugin/provider_server.go
sdk/go/common/resource/plugin/provider_server_test.go

If `GetArgs()` is empty, the inputs map isn't initialized
before the loop starts filling it.
Adding entries to a nil map will cause a panic.
Fix the potential panic and add a failing test.
Issue caught by staticcheck.
```
go/common/resource/plugin/provider_server.go:245:4: SA5000: assignment to nil map (staticcheck)
```
Refs #11808

sdk/resource/ProviderServer: Fix potential panic at Configure

---

pkg/codegen/hcl2/model/diagnostics.go
pkg/codegen/hcl2/model/pretty/display.go
pkg/codegen/hcl2/model/pretty/display_test.go
pkg/codegen/hcl2/model/type_enum.go
pkg/codegen/hcl2/model/type_list.go
pkg/codegen/hcl2/model/type_map.go
pkg/codegen/hcl2/model/type_object.go
pkg/codegen/hcl2/model/type_output.go
pkg/codegen/hcl2/model/type_promise.go
pkg/codegen/hcl2/model/type_set.go
pkg/codegen/hcl2/model/type_tuple.go
pkg/codegen/hcl2/model/type_union.go
sdk/go/common/env/env.go

Re-enable pretty printing of types in the default case. 
Pretty printing by default was disabled as a quick solution for https://github.com/pulumi/pulumi-gcp/pull/963. This PR has been manually tested against `pulumi-gcp`.
This PR adds 3 behaviors to the `pretty.Formatter` type.
1. A inner string method that accommodates state.
2. A visit function that allows pre-processing to discover recursive
types and apply tags to them.
3. A hash function that allows structural hashing on recursive types. This hash function is memoized by the `tagGenerator` during traversal.
Together, this allows pretty-printing recursive types, regardless of
the pointers are. This allows `(0x1)Object{ key: *0x1 }` to be the same
as `(0x1)Object{ key: (0x2)Object{ key: *0x1 }}`.

Pretty recursive types

---

changelog/pending/20230113--sdk-python--fix-a-typeerror-in-output-from_input.yaml
sdk/python/lib/pulumi/output.py
sdk/python/lib/test/test_output.py

Fixes a TypeError in Output.from_input when passing in an empty input type.

Fix a TypeError in Output.from_input

---

tests/integration/appdash_test.go

The pattern,
f, err := os.Open(..)
defer f.Close()
if err != nil { return }
Isn't quite right because the contract
for functions that return err, unless otherwise specified,
is that if `err != nil`, then the other results are invalid.
So if `os.Open` fails, the `f` should be considered invalid,
and we should not defer close on it because that could panic.
[`os.File.Close` guards against this][1],
but it's still preferable to defer the close after the error check.
f, err := os.Open(..)
if err != nil { return }
defer f.Close()
[1]: https://cs.opensource.google/go/go/+/refs/tags/go1.19.5:src/os/file_posix.go;l=21
```
integration/appdash_test.go:17:2: SA5001: should check returned error before deferring traceFile.Close() (staticcheck)
```
Refs #11808

test/integration: defer close after successful open

---

pkg/codegen/testing/tstypes/tstypes.go

string constants don't behave like iota.
With,
type something string
const (
foo something = "foo"
bar           = "bar"
)
Only `foo` will have the type `something`.
`bar` will be an untyped string literal.
The type is copied over only when there's no rhs, e.g.
type something int
const (
foo something = iota
bar
)
This adds types for constants
that were intended to have the type `typeTokenKind`.
Issue found by staticcheck:
```
codegen/testing/tstypes/tstypes.go:157:2: SA9004: only the first constant in this group has an explicit type (staticcheck)
```
Refs #11808

pkg/codegen: Add types for typeTokenKind values

---

pkg/codegen/go/gen_test.go

`sort.StringSlice` is a type wrapper, not a function.
type StringSlice []string
So `ordering = sort.StringSlice(ordering)` has no effect.
This replaces that with use of `sort.Strings`,
whic has the desired effect of sorting the slice in place.
Also drops the unnecesary index tracking to append into the slice
in favor of appends.
```
codegen/go/gen_test.go:220:4: SA4029: sort.StringSlice is a type, not a function, and sort.StringSlice(ordering) doesn't sort your values; consider using sort.Strings instead (staticcheck)
```
Refs #11808

codgen/go/test: Replace ineffective sort

---

sdk/go/pulumi/generate/main.go
sdk/go/pulumi/generate/main_test.go

Code in go/pulumi/generate that determines the destination file path
based on the name of the template
incorrectly used TrimRight instead of TrimSuffix.
TrimRight removes all instances
of *any* of the provided characters (referred to as the cutset)
from the provided string
instead of removing just a fixed suffix.
So if we tried to generate say, a .tmpl file,
it would have stripped that from the destination file path too.
This switches to TrimSuffix, which is what was intended here,
and adds a test to verify the desired behavior.
```
go/pulumi/generate/main.go:343:54: SA1024: cutset contains duplicate characters (staticcheck)
```
Refs #11808

sdk/go/generate: Replace incorrect TrimRight with TrimSuffix

---

pkg/backend/httpstate/backend.go
pkg/codegen/go/gen.go
pkg/codegen/nodejs/gen.go
pkg/codegen/python/gen.go

A couple places in pkg/ use Printf without any arguments.
These cases can use the input strings as-is instead.
This changes switches them to the Print variant.
Issues found by staticcheck:
backend/httpstate/backend.go:1627:2: SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
backend/httpstate/backend.go:1644:5: SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
codegen/go/gen.go:2260:2: SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
codegen/nodejs/gen.go:1088:3: SA1006: printf-style function with dynamic format string and no further …

pkg: Drop unnecessary printfs

---

pkg/codegen/pcl/utilities.go
pkg/testing/integration/program.go

Removes unnecessary appends in pkg.
There were two instances:
- append into a slice that's never used again
- append with nothing to append (`append([]{foo}) == []{foo}`)
Issue found by staticcheck:
```
testing/integration/program.go:2190:15: SA4021: x = append(y) is equivalent to x = y (staticcheck)
testing/integration/program.go:2192:15: SA4021: x = append(y) is equivalent to x = y (staticcheck)
codegen/pcl/utilities.go:158:11: SA4010: this result of append is never used, except maybe in other appends (staticcheck)
```
Refs #11808

pkg: Fix unnecessary appends

---

sdk/go/common/resource/plugin/plugin.go

The unused tracingToFile on pluginArgumentOptions
caused a reference to cmdutil.TracingToFile
which has been deprecated.
```
go/common/resource/plugin/plugin.go:301:20: SA1019: cmdutil.TracingToFile is deprecated: Even in this case TracingEndpoint will now have the tcp:// scheme and will point to a proxy server that will append traces to the user-specified file. Plugins should respect TracingEndpoint and ignore TracingToFile. (staticcheck)
```
Refs #11808

sdk/plugin: Delete unused tracingToFile field

---

sdk/go/pulumi/internals/outputs_test.go

pulumi.NewOutput has been deprecated in favor of Context.NewOutput.
```
go/pulumi/internals/outputs_test.go:37:22: SA1019: pulumi.NewOutput is deprecated: use Context.NewOutput instead. (staticcheck)
go/pulumi/internals/outputs_test.go:50:21: SA1019: pulumi.NewOutput is deprecated: use Context.NewOutput instead. (staticcheck)
```
Refs #11808

sdk/internal: pulumi.NewOutput => ctx.NewOutput

---

sdk/go/pulumi/context_test.go

`time.Sleep(10)` is perceived as a bug because there's no unit.
If the author was coming from another programming language
they could have meant milliseconds or seconds (unlikely).
Make the nanosecond unit explicit.
```
go/pulumi/context_test.go:93:14: SA1004: sleeping for 10 nanoseconds is probably a bug; be explicit if it isn't (staticcheck)
```
Refs #7661
Refs #11808
---
I'm not sure if this was actually intended to be nanoseconds.
The test still passes with milliseconds and microseconds,
although with milliseconds
it takes a lot longer because of the many iterations.
CC @t0yv0, in case you remember the unit you wanted here.

sdk/context/test: Explicitly sleep for 10 nanoseconds

---

sdk/go/pulumi-language-go/main.go

Continuing the pkg/errors clean up. This removes uses of it from the go language host main code.

Clean up pkg/errors in go language host

---

sdk/go/pulumi/types.go
sdk/go/pulumi/types_test.go

ApplyT duplicates the applier validation logic used by ApplyTWithContext
with the exception that it expects one parameter instead of two.
It then wraps the applier in a wrapper function which ignores the context,
and passes it on to ApplyTWithContext,
which validates the function *again*.
This change de-dupes the validation logic
by introducing an internal "applier" object.
This object represents validated and normalized versions
of user-supplied appliers.
Given an applier object, ApplyTWithContext can use applier.Call
and always pass in a context, and always expect an error return.
o, err := ap.Call(ctx, i)
This change is made in service to #11783 and #11784

ApplyT, ApplyTWithContext: De-dupe validation

---

changelog/pending/20230105--sdk-go--allows-users-to-discover-if-their-program-is-being-run-with-a-mock-monitor.yaml
sdk/go/pulumi/context.go
sdk/go/pulumi/context_test.go

It is often desirable to detect running Pulumi programs under mocks in the same situations where it would be interesting to know if they were executing as a dry run. This commit adds a mechanism to find out (in Go).

feat: Add ctx.RunningWithMocks()

---

changelog/pending/20230114--sdk-nodejs--add-support-for-custom-naming-of-dynamic-provider-resource.yaml
sdk/nodejs/dynamic/index.ts
tests/integration/dynamic/nodejs-resource-type-name/Pulumi.yaml
tests/integration/dynamic/nodejs-resource-type-name/index.ts
tests/integration/dynamic/nodejs-resource-type-name/package.json
tests/integration/integration_nodejs_test.go

Fixes #11856 
Added two new optional constructor parameters to `pulumi.dynamic.Resource`, `module`, and `type`, which enables custom type naming of dynamic provider resources.
Based on the Python implementation from [here](https://github.com/pulumi/pulumi/pull/7633).
All dynamic provider resources would have the type `pulumi-nodejs:dynamic:Resource`
Usage:
```ts
class CustomResource extends pulumi.dynamic.Resource {
constructor (name: string, opts?: pulumi.ResourceOptions) {
super(new DummyResourceProvider(), name, {}, opts, "custom-provider", "CustomResource")
}
}
```
Output: `pulumi-nodejs:dynamic/custom-provider:CustomResource`

[sdk/nodejs] - Add support for custom naming of dynamic provider resource

---

sdk/go/pulumi/types.go
sdk/go/pulumi/types_test.go

ApplyT or ApplyTWithContext panic if the Output.Type
does not match the parameter of the function.
For example,
```
panic: applier's first input parameter must be assignable from int, got string
```
It can take some effort to get to the root cause
if a file has several appliers.
This change augments the message reported in the panic
to include the definition location of the applier that was invalid.
```
panic: applier's first input parameter must be assignable from int, got string
applier defined at [..]/src/pulumi/sdk/go/pulumi/types_test.go:1160
```
Note that this is the location of the applier,
not the ApplyT/ApplyTWithContext call.
That information is currently present in the stack trace.
If desirable, we can also bubble that to the top in the panic.
Resolves #11783

ApplyT: Include applier location for mismatch panics

---

changelog/pending/20230117--cli-display--fixes-11864-pulumi-panics-when-pulumi-yaml-provider-plugin-does-not-have-a-path-provided.yaml
sdk/go/common/workspace/project.json
tests/integration/integration_test.go

Fixes #11864 
This PR introduces a change such that Pulumi no longer panics before main when the Pulumi.yaml contains a provider plugin that has an empty/unspecified `path` key.
This PR removes the `contract.AssertNoError()` call and modifies the function to return the error. Instead of panicking, the error is now contained in the `DefaultPulumiPackageError` variable.
In terms of usage, it appears that [pulumi-lsp](https://github.com/pulumi/pulumi-lsp/blob/d5e1d1ef3750479a17e351675b0dfee654de61c0/sdk/yaml/completion.go#L353) uses this variable.

fix panic when Pulumi.yaml has a provider with an empty/unspecified path key

---

sdk/go/pulumi/types.go

`pulumi.Unsecret` currently has an unconditional data race:
```
Write at 0x00c0000f80a9 by goroutine 132:
github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*OutputState).fulfillValue()
[..]/pulumi/sdk/go/pulumi/types.go:197 +0x3c4
github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*OutputState).resolveValue()
[..]/pulumi/sdk/go/pulumi/types.go:235 +0x2b0
github.com/pulumi/pulumi/sdk/v3/go/pulumi.toOutputTWithContext.func3()
[..]/pulumi/sdk/go/pulumi/types.go:1060 +0x278
Previous write at 0x00c0000f80a9 by goroutine 130:
github.com/pulumi/pulumi/sdk/v3/go/pulumi.UnsecretWithContext()
[..]/pulumi/sdk/go/pulumi/types.go:636 +0xd8
github.com/pulumi/pulumi/sdk/v3/go/pulumi.Unsecret()
[..]/pulumi/sdk/go/pulumi/types.go:628 +0xa4
github.com/pulumi/pulumi/sdk/v3/go/pulumi.TestUnsecret() …
```

sdk/Unsecret: Fix data race

---

sdk/go/pulumi/context.go
sdk/go/pulumi/resource_test.go
sdk/go/pulumi/run.go
sdk/go/pulumi/run_test.go

TestDependsOnInputs modified the `monitor` attached to the context
while the context was still using it.
This caused a data race:
```
Read at 0x00c00041d8d8 by goroutine 4280:
github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*interceptingResourceMonitor).RegisterResource()
[..]/pulumi/sdk/go/pulumi/resource_test.go:708 +0x44
github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*Context).registerResource.func1()
[..]/pulumi/sdk/go/pulumi/context.go:854 +0xd28
Previous write at 0x00c00041d8d8 by goroutine 2880:
github.com/pulumi/pulumi/sdk/v3/go/pulumi.newInterceptingResourceMonitor()
[..]/pulumi/sdk/go/pulumi/resource_test.go:671 +0xac
```
Replacing the ResourceMonitorClient appears to be the only way
to get the information that the dependency tracker needs,
but replacing the client …

sdk/go: Fix TestDependsOnInputs data race

---

sdk/python/lib/pulumi/runtime/stack.py
sdk/python/lib/test/runtime/test_stack.py

When the `await RPC_MANAGER.rpcs.pop()` explodes,
the traceback is for `RPC_MANAGER.rpcs.pop()`, e.g.
```
error: Program failed with an unhandled exception:
Traceback (most recent call last):
File "/opt/hostedtoolcache/pulumi/3.43.1/x64/pulumi-language-python-exec", line 179, in <module>
loop.run_until_complete(coro)
File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
return future.result()
File "[..]/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
await run_pulumi_func(lambda: Stack(func))
File "[..]/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
await wait_for_rpcs()
File "[..]/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 73, …
```

sdk/py/stack: Original traceback in wait_for_rpcs

---

pkg/testing/integration/program.go
tests/integration/construct_component/go/Pulumi.yaml
tests/integration/construct_component/nodejs/Pulumi.yaml
tests/integration/construct_component/python/Pulumi.yaml
tests/integration/construct_component_methods_resources/go/Pulumi.yaml
tests/integration/construct_component_methods_resources/nodejs/Pulumi.yaml
tests/integration/construct_component_methods_resources/python/Pulumi.yaml
tests/integration/construct_component_methods_unknown/go/Pulumi.yaml
tests/integration/construct_component_methods_unknown/nodejs/Pulumi.yaml
tests/integration/construct_component_methods_unknown/python/Pulumi.yaml
tests/integration/construct_component_plain/go/Pulumi.yaml
tests/integration/construct_component_plain/nodejs/Pulumi.yaml
tests/integration/construct_component_plain/python/Pulumi.yaml
tests/integration/construct_component_unknown/go/Pulumi.yaml
tests/integration/construct_component_unknown/nodejs/Pulumi.yaml
tests/integration/construct_component_unknown/python/Pulumi.yaml
tests/integration/construct_nested_component/go/Pulumi.yaml
tests/integration/gather_plugin/go/Pulumi.yaml
tests/integration/gather_plugin/nodejs/Pulumi.yaml
tests/integration/gather_plugin/python/Pulumi.yaml
tests/integration/integration_go_smoke_test.go
tests/integration/integration_go_test.go
tests/integration/integration_nodejs_smoke_test.go
tests/integration/integration_nodejs_test.go
tests/integration/integration_python_smoke_test.go
tests/integration/integration_python_test.go
tests/integration/integration_test.go
tests/integration/integration_util_test.go

Instead of setting testprovider via the ProgramTest.LocalProviders option use the plugin link capabilities in Pulumi.yaml instead.
This gives test coverage of both the plugin yaml option, and also the use of that option with ProgramTest (with and without LocalProviders being set as well, because we still use that for the component provider tests).

Use plugin link and shimless for testprovider

---

changelog/pending/20230118--sdk--add-support-for-a-teams-array-in-the-createstackrequest-which-allows-specifying-teams-when-a-stack-is-created.yaml
sdk/go/common/apitype/stacks.go

Add support for a Teams array in the CreateStackRequest which allows specifying Teams when a Stack is created.
Updates #10784
Signed-off-by: Steve Sloka <steve@pulumi.com>

Add support for a Teams array in the CreateStackRequest

---

pkg/codegen/hcl2/model/type_enum.go
pkg/codegen/hcl2/model/type_object.go
pkg/codegen/hcl2/model/type_tuple.go
pkg/codegen/hcl2/model/type_union.go

ObjectType.String and a few other types
do a fair bit of computation to build a string representation.
They memoize the result in an internal `s` field.
This causes a data race if two goroutines call `String()`
on the same object at the same time.
Tests in pkg/codegen/pcl ran into the following
from ObjectType.String.
```
Write at 0x00c00055c030 by goroutine 36:
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.(*ObjectType).string()
[..]/pulumi/pkg/codegen/hcl2/model/type_object.go:300 +0x418
[.. snip ..]
github.com/pulumi/pulumi/pkg/v3/codegen/pcl.TestApplyRewriter.func1()
[..]/pulumi/pkg/codegen/pcl/rewrite_apply_test.go:176 +0x68
testing.tRunner()
/opt/homebrew/Cellar/go/1.19.5/libexec/src/testing/testing.go:1446 +0x188
testing.(*T).Run.func1() …
```

pkg/hcl2/model: Make String methods thread-safe

---

pkg/codegen/go/gen_program_expressions.go

generator.argumentTypeName increments a typeNameID global variable.
This causes a data race when tests run in parallel:
```
Read at 0x000005d9dd28 by goroutine 20:
github.com/pulumi/pulumi/pkg/v3/codegen/go.(*generator).argumentTypeName()
/home/runner/work/pulumi/pulumi/pkg/codegen/go/gen_program_expressions.go:775 +0x84
github.com/pulumi/pulumi/pkg/v3/codegen/go.(*generator).genObjectConsExpression()
...
Previous write at 0x000005d9dd28 by goroutine 19:
github.com/pulumi/pulumi/pkg/v3/codegen/go.(*generator).argumentTypeName()
/home/runner/work/pulumi/pulumi/pkg/codegen/go/gen_program_expressions.go:775 +0xa4
github.com/pulumi/pulumi/pkg/v3/codegen/go.(*generator).genTemplateExpression()
/home/runner/work/pulumi/pulumi/pkg/codegen/go/gen_program_expressions.go:672 …
```

pcl/codegen: Fix typeNameID data race

---

changelog/pending/20230118--sdk-go--coerces-outputs-to-applyt-functions-if-the-types-are-convertible.yaml
sdk/go/pulumi/types.go
sdk/go/pulumi/types_test.go

Adds support to ApplyT to automatically coerce new type wrappers
when calling the provided functions.
With this change, the following is valid:
var idout pu.IDOutput = ...
idout.ApplyT(func(id string) string {
// ...
})
Note that this does not use `To{Type}Output` methods at this time.
We will likely want to add that in the future given #11750.
We can do that in a backwards compatible way.
This coerces only those values that are defined
with language-level type wrappers in the following form:
type ID string
This *does not* coerce types with different undedrlying representations.
Specifically, the following conversons are not supported
even though they're supported by Go using the `T(v)` syntax.
string => int
string => []byte
[]byte => string
The choice to convert between these types …

ApplyT: Coerce new type wrappers

---

changelog/pending/20230119--auto-nodejs--enable-programmatic-tagging-of-stacks-nodejs-only.yaml
sdk/nodejs/automation/localWorkspace.ts
sdk/nodejs/automation/stack.ts
sdk/nodejs/automation/tag.ts
sdk/nodejs/automation/workspace.ts
sdk/nodejs/tests/automation/localWorkspace.spec.ts

Adds stack tag management support to the **nodejs** automation api sdk (https://github.com/pulumi/pulumi/issues/5681).
Before I move on to other language/runtime SDKs, I'd like to get a quick sanity check on this nodejs implementation, since they will follow a similar pattern 👍 . There is no changelog for now; this won't be merged as-is. Thank you! 🙏😄 
Fixes: https://github.com/pulumi/pulumi/issues/5681
- ~~[ ] I have run `make changelog` and committed the `changelog/pending/<file>` documenting my change~~

Add stack tag support for nodejs automation api sdk

---

scripts/get-job-matrix.py

Fixes #11488. 
Upstream PR to Node was merged and included in 19.4: https://github.com/nodejs/node/releases/tag/v19.4.0

ci: Resume testing on Node current with 19.4 release

---

pkg/codegen/testing/test/program_driver.go

Landable version of #11928
We seem to be hitting OOMs in CI quite often
whlie running code generation integration tests.
This drops parallelism from these tests because
experimentation revealed that running these tests serially
mitigates this issue somewhat.
Resolves #11925

test/codegen: Don't run in parallel

---

pkg/codegen/docs/gen.go
pkg/codegen/docs/utils.go

fixes: https://github.com/pulumi/registry/issues/951
This PR fixes an issue where a resource named "index" has trouble resolving the url likely because "index" is some sort of reserved keyword. This change prepends a double underscore to the resource name in the URL that gets generated and also updates the links that reference this on both the module page and the package tree in the left nav. Visually everything looks the same, it is just the directory name and underlying links that get updated. It will still display as "Index" when rendered on the page.
As an example this route `/registry/packages/gcp/api-docs/firestore/index/` ends up resulting in a 404. With this change we add a double underscore which results in the following route `registry/packages/gcp/api-docs/firestore/__index/` …

Fix broken links related to resources named "index"

---

bors.toml

Fixes #11923 
Lints failing has caused bors to fail very often. This PR makes passing lint required for bors merge.

make passing lint required to bors merge a PR

---

pkg/cmd/pulumi/cancel.go
pkg/cmd/pulumi/config.go
pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/logs.go
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/refresh.go
pkg/cmd/pulumi/stack.go
pkg/cmd/pulumi/stack_change_secrets_provider.go
pkg/cmd/pulumi/stack_export.go
pkg/cmd/pulumi/stack_graph.go
pkg/cmd/pulumi/stack_history.go
pkg/cmd/pulumi/stack_import.go
pkg/cmd/pulumi/stack_init.go
pkg/cmd/pulumi/stack_output.go
pkg/cmd/pulumi/stack_rename.go
pkg/cmd/pulumi/stack_rm.go
pkg/cmd/pulumi/stack_select.go
pkg/cmd/pulumi/stack_tag.go
pkg/cmd/pulumi/state.go
pkg/cmd/pulumi/up.go
pkg/cmd/pulumi/util.go
pkg/cmd/pulumi/util_test.go
pkg/cmd/pulumi/watch.go

There are a few helper functions in util.go
that accept two booleans: offerNew and setCurrent.
These functions are called *quite* often
and callers always have to pass these two naked booleans:
requireStack(ctx, stack, false, opts, true)
To reduce confusion, these booleans have to be annotated with a comment.
requireStack(ctx, stack, false, opts, true /* setCurrent */)
Given how pervasive these two are,
this change turns them into a set of bit flags:
stackLoadOnly
stackOfferNew
stackSetCurrent
Callers pass in a bitwise OR of these as needed:
Before                   Now
offerNew  setCurrent       stackLoadOption
------------------------------------------
false     false           stackLoadOnly
true      false           stackOfferNew
false     true            stackSetCurrent
true      true …

cmd/stack: Reduce noise from offerNew, setCurrent bool

---

changelog/pending/20230123--auto-nodejs--fix-nodejs-automation-api-always-setting-the-pulumi_config-environment-variable.yaml
sdk/nodejs/automation/cmd.ts
sdk/nodejs/automation/localWorkspace.ts
sdk/nodejs/automation/server.ts
sdk/nodejs/tests/automation/data/testproj_dotnet/.gitignore
sdk/nodejs/tests/automation/data/testproj_dotnet/Program.cs
sdk/nodejs/tests/automation/data/testproj_dotnet/Pulumi.yaml
sdk/nodejs/tests/automation/data/testproj_dotnet/TestProj.csproj
sdk/nodejs/tests/automation/localWorkspace.spec.ts

nodejs automation api was setting the envvar PULUMI_CONFIG for every pulumi command it called, this tripped up the dotnet sdk which only expects PULUMI_CONFIG to be set to a valid JSON string (not the empty string).
Looks like this was just a slightly confused bit of code to try and deal with parallel programs, I've moved it out of the workspace part of automation api and fixed up the inline server to deal with parallel programs correctly instead.
Fixes #11945

Test and fix for nodejs automation api

---

pkg/resource/deploy/source_eval.go

Add note about not adding more features to SupportsFeature to switch to an enum model for the next one. Prompted by https://github.com/pulumi/pulumi-dotnet/pull/88.

Add note about SupportsFeature

---

sdk/go/common/apitype/history.go

Part of: https://github.com/pulumi/service-requests/issues/155
This adds the resource count to the update info struct. We want to surface this through the stack updates endpoint in the service. We import this type in the pulumi-service from here so I need to get the struct updated. See: https://github.com/pulumi/pulumi-service/pull/11990.

Add resource count to update info struct

---

changelog/pending/20230125--sdk-go--fixes-data-race-in-provider-plugin-resulting-in-weakly-typed-secrets.yaml
sdk/go/common/resource/plugin/provider_plugin.go
sdk/go/common/resource/plugin/provider_plugin_test.go

The data race results from Delete accessing configuration
before Configure has been called.
The immediate fix for this is to fix the call ordering.
Resolves #11971
---
A better fix is to make it impossible
to access configuration before Configure is called.
That will address any other similar cases (if any).
Doing that requires a little more information,
so I'd appreciate some guidance in that direction
before I can fix this.
Specficially:
- Is Configure *required* to be called?
- Are those fields all invalid until Configure is called?
- If Configure fails, what happens to all these calls
that depend on that informaton?

sdk/go/plugin: Fix data race between Configure and Delete

---

pkg/cmd/pulumi/stack_output.go
pkg/cmd/pulumi/stack_output_test.go

`pulumi stack output`'s core behavior stems from
acquiring the current stack and inspecting its outputs.
To test this logic sufficiently,
we need to be able to inject an alternative stack value.
This change adds a `requireStack` field to stackOutputCmd.
This, if set, specifies an alternative to the requireStack function
that we use to acquire the current stack.
As a demonstration of what this unlocks,
this change also includes tests for
the core functionality of `pulumi stack outputs`:
print plain and secret outputs
together or separately
with and without --json
with and without --show-secrets
Note that to test the output of the command,
we have to temporarily replace `os.Stdout`.
This is indicative of debt -- there are too many functions
that print to stdout directly intsead of an …

cmd/stack output: Inject requireStack and test output

---

changelog/pending/20230120--sdk-go--delegate-alias-computation-to-the-engine.yaml
sdk/go/pulumi/alias.go
sdk/go/pulumi/context.go
sdk/go/pulumi/context_test.go
sdk/go/pulumi/rpc_test.go

This PR removes the use of `collapseAliases` from the go SDK which used to calculate aliases of resources from `ResourceOptions` and their inherited child aliases (a.k.a. alias explosion) and starts using the new alias specification `pulumirpc.Alias` that is handled by the engine in a language-agnostic manner. 
This PR removes `aliases: []URNOutput` from `resourceState` because we no longer have to keep track of them in `makeResourceState` but instead calculate them in `prepareResourceInputs`. 
Fixes #11066
Potentially addresses #11697

[go/sdk] Delegate alias computation to the engine

---

changelog/pending/20230120--sdk-go--delegate-alias-computation-to-the-engine.yaml
sdk/go/pulumi/alias.go
sdk/go/pulumi/context.go
sdk/go/pulumi/context_test.go
sdk/go/pulumi/rpc_test.go

Reverts pulumi/pulumi#11935 because we removed the correct fallback behaviour of `collapseAliases`

Revert "[go/sdk] Delegate alias computation to the engine"

---

changelog/pending/20230124--sdk-python--fix-handling-of-output-keys-in-dicts-passed-to-output-from_input.yaml
sdk/python/lib/pulumi/output.py
sdk/python/lib/test/test_output.py

Turned out if you passed a dict with an Output type key to `Output.from_input` you'd get a type error:
```
TypeError: keywords must be strings
```
This adds a test and fixes the dict handling in from_input to also support keys that are Outputs.

Handle Outputs in dict keys passed to from_input

---

pkg/backend/filestate/backend.go
pkg/backend/filestate/backend_test.go
pkg/backend/filestate/state.go
pkg/resource/stack/checkpoint.go

ImportDeployment and ExportDeployment for the filestate backend would try to fully serialize/deserialize both the current deployment data for the stack, and for import also the new deployment data. This would require the creating of secret managers and possibly the prompting for passphrases.
It was all unnecessary, Import/Export is defined in terms of untyped deployments. We can just do a simple marshal to/from the checkpoint structure rather than doing a full deployment serialization/deserialization.

Don't marshal/unmarshal deployments for import/export

---

changelog/pending/20230123--cli--adds-a-shell-flag-to-pulumi-stack-output-to-print-outputs-as-a-shell-script.yaml
pkg/cmd/pulumi/stack_output.go
pkg/cmd/pulumi/stack_output_fuzz_test.go
pkg/cmd/pulumi/stack_output_test.go
pkg/cmd/pulumi/testdata/fuzz/FuzzPowershellStackOutputWriter/5838cdfae7b16cde2707c04599b62223e7bade8dafdd8a1c53b8f881e8f79d99
pkg/cmd/pulumi/testdata/fuzz/FuzzPowershellStackOutputWriter/b5bbc3d0d660602a096a3956016c5a0f57eddd321f15e9c6276d05290424365a
pkg/cmd/pulumi/testdata/fuzz/FuzzPowershellStackOutputWriter/d0b1335002dd171e1b89df7e6ea2ccbf017be0459542a11ec676c3bf280dc292
pkg/cmd/pulumi/testdata/fuzz/FuzzPowershellStackOutputWriter/ddca139cc2f39efdaed4ae893f402e930890e37ef70be194dfe16dbfec241877
pkg/go.mod

Adds a `--shell` option to `pulumi stack output`
that writes the outputs for a stack as a shell script.
% pulumi stack output --shell
bucketName=mybucket-1234
websiteURL="http://mybucket-1234.example.com"
On Windows, it will produce a Powershell script:
% pulumi stack output --shell
$bucketName = 'mybucket-1234'
$websiteURL = 'http://mybucket-1234.example.com'
The idea is that given:
% pulumi stack output
[..]
bucketName   mybucket-1234
websiteURL   http://mybucket-1234.example.com
A user will be able to do the following
in a shell script:
eval "$(pulumi stack output --shell)"
echo "Created bucket $bucketName"
echo "Visit at $websiteURL"
If a user specifies a single property name,
only that will be written in the shell script.
eval "$(pulumi stack output --shell bucketName)"
echo …

cmd/stack output: Add --shell option

---

pkg/cmd/pulumi/stack.go
pkg/cmd/pulumi/stack_output.go
pkg/cmd/pulumi/stack_output_test.go
pkg/cmd/pulumi/util.go
sdk/go/common/util/cmdutil/console.go

The implementation of `pulumi stack output` prints everything
to a global `io.Writer`.
This makes testing its output a bit hacky and unparalellizable
because we have to hijack `os.Stdout` to capture the output.
This changes it the command implementation
and all the functions it relies on
to accept an `io.Writer` as an argument.
This allows us to delete the os.Stdout hijacking hack
that was introduced in #11952,
and have those tests run in parallel, writing to an in-memory buffer.

cmd/stack output: Print to an io.Writer

---

pkg/testing/integration/program.go
pkg/testing/integration/program_test.go

This change to ProgramTest allows Go module replacements to omit the major version number, simplifying the process to release a provider with a new major version.
When the major version is incremented in a PR, the examples fail to compile if they reference the incorrect SDK version.
This enables the examples to be written to target a versionless `/sdk`, and have a Dependencies line such as:
```go
integration.ProgramTestOptions{
Dependencies: []string{
"github.com/pulumi/pulumi-keycloak/sdk=../sdk",
},
}
```
This versionless import mapping means that examples run regardless of the major version of the provider, and updates to major versions in PRs will require only one PR.
A provider PR proving out the implementation was created against this commit here:
- …

feat: enable simpler Go programtest replacements

---

pkg/backend/backend.go
pkg/backend/backend_test.go
pkg/backend/filestate/backend.go
pkg/backend/filestate/stack.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/stack.go
pkg/backend/httpstate/state.go
pkg/backend/mock.go
pkg/backend/query.go
pkg/backend/stack.go
pkg/backend/watch.go
pkg/cmd/pulumi/about.go
pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/logs.go
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/query.go
pkg/cmd/pulumi/refresh.go
pkg/cmd/pulumi/stack.go
pkg/cmd/pulumi/stack_graph.go
pkg/cmd/pulumi/stack_output.go
pkg/cmd/pulumi/stack_output_test.go
pkg/cmd/pulumi/state.go
pkg/cmd/pulumi/up.go
pkg/cmd/pulumi/watch.go
pkg/engine/deployment.go
pkg/engine/query.go

All uses of stack.DefaultSecretsProvider are now in pkg/cmd, every other use has been changed to take a secrets.Provider as a parameter in someway.
I renamed a load of variables from "stack" to "stackName" as part of this because it clashed with the "stack" module that DefaultSecretsProvider is currently defined in, but I think this is probably a good change anyway given these were `string`s not `Stack`s.

Push DefaultSecretsProvider up to pkg/cmd

---

changelog/pending/20230128--backend-filestate--the-filestate-backend-now-supports-project-scoped-stacks.yaml
pkg/backend/backend.go
pkg/backend/filestate/backend.go
pkg/backend/filestate/backend_test.go
pkg/backend/filestate/bucket.go
pkg/backend/filestate/lock.go
pkg/backend/filestate/snapshot.go
pkg/backend/filestate/state.go
pkg/resource/stack/checkpoint.go
sdk/go/common/tokens/names.go

This is a first pass at supporting projects for the file state backend.
Projects must be given explictly, that is unlike the service backend where the stack reference "teststack" would implictly parse as the stack "teststack" in the current project in the current organisation.
"teststack" with the filestate backend will continue to parse as the stack "teststack" not associated with a project, but you can now give the stack reference now as "testproj/teststack" to get a project scoped stack.
This makes no effort to try automatically moving stack files to be associated with projects. Users can use `pulumi stack rename` to do that if they so wish.
Fixes the project part of https://github.com/pulumi/pulumi/issues/2522.

Support projects in the file state backend

---

.github/workflows/ci.yml
pkg/cmd/pulumi/stack_output_fuzz_test.go
pkg/cmd/pulumi/testdata/fuzz/FuzzPowershellStackOutputWriter/b5bbc3d0d660602a096a3956016c5a0f57eddd321f15e9c6276d05290424365a

We were ignoring smoke test failures on Windows.
This is not desirable.

ci: Don't ignore smoke test failures on Windows

---

changelog/pending/20230130--sdk-python--delegate-alias-computation-to-the-engine.yaml
sdk/python/lib/pulumi/resource.py
sdk/python/lib/pulumi/runtime/resource.py
sdk/python/lib/pulumi/runtime/settings.py
sdk/python/lib/test/langhost/aliases/__main__.py
sdk/python/lib/test/runtime/test_create_alias_specs.py

Supersedes #11983 lazily apply the fallback logic for older engines using `all_aliases` and do cleanup work
Fixes #11064 (issue)

[sdks/python] Delegate alias computation to the engine

---

.github/workflows/ci-lint.yml
Makefile

Instead of rolling our own caching logic,
use the official golangci-lint-action
and run `go mod tidy` concurrently.
This has a few advantages over the current setup:
- Non-container builds are faster to run
(we take ~20 seconds to set up the container)
- golangci-lint-action's caching logic is better:
it periodically invalidates itself automatically
- `go mod tidy` takes over am inute to run;
this can be done in parallel
Caveats:
- golangci-lint-action does not support multiple modules in one call,
so we have to run the action separately for each submodule.
- We have to duplicate some of what `make lint` specifies.
If we ever add more checks to `make lint`,
we'll need to also update this job.
Refs #12019
Supersedes #12029

ci/lint: Use golangci-lint-action

---

.github/workflows/ci.yml
.github/workflows/on-pr.yml
scripts/get-job-matrix.py

In #11155, we pinned CI to macos-11
because we want to continue to support macOS 11.
This, however hsa created a new issue:
grpcio does not publish wheels for macos-11 anymore
and building it from source takes long enough to kill our CI
(see #12054 #12050).
To fix the issue while continuing to support older macOS,
run CI on macos-latest, but leave build jobs and friends on macos-11.
Resolves #12054, #12050

ci: Use macos-latest

---

changelog/pending/20230128--backend-filestate--the-filestate-backend-now-supports-project-scoped-stacks.yaml
pkg/backend/backend.go
pkg/backend/filestate/backend.go
pkg/backend/filestate/backend_test.go
pkg/backend/filestate/bucket.go
pkg/backend/filestate/lock.go
pkg/backend/filestate/snapshot.go
pkg/backend/filestate/stack.go
pkg/backend/filestate/state.go
pkg/resource/stack/checkpoint.go
sdk/go/common/tokens/names.go

Temporarily reverting this to keep master in a releasable state while we finalize the design.
As it was, the syntax `pulumi stack select foo/bar` could mean fundamentally different things based on what backend you're logged into. In the Service backend, the `foo` is the org. In the Self-Managed backend, the `foo` would be the project name. Moreover, in the Service backend, there is one "fully-qualified" name, and all the others are just shorthands. But this wouldn't be true in the Self-Managed backend where `bar` represents a fundamentally different stack than `foo/bar`. This makes it hard to explain what stack identities are. Self-Managed has been a pure subset of what Service supported in terms of stack identities. If we went with this design, it would be a partially overlapping, but …

Temporarily revert support for projects in the Self-Managed backend

---

.github/workflows/ci-lint.yml
.github/workflows/ci-test-docs-generation.yml
scripts/get-job-matrix.py

Go 1.20 was just released.
Switch to testing with Go 1.19 and 1.20.
Resolves #12040

ci: Test with Go 1.19, 1.20

---

changelog/pending/20230202--sdkgen-go--go-sdks-now-use-errors-new-instead-of-github-com-pkg-errors-new.yaml
pkg/codegen/go/gen.go
pkg/codegen/testing/test/testdata/dashed-import-schema/go/plant-provider/tree/v1/nursery.go
pkg/codegen/testing/test/testdata/dashed-import-schema/go/plant-provider/tree/v1/rubberTree.go
pkg/codegen/testing/test/testdata/different-enum/go/plant/tree/v1/nursery.go
pkg/codegen/testing/test/testdata/different-enum/go/plant/tree/v1/rubberTree.go
pkg/codegen/testing/test/testdata/external-go-import-aliases/go/example/component.go
pkg/codegen/testing/test/testdata/external-resource-schema/go/example/component.go
pkg/codegen/testing/test/testdata/plain-and-default/go/foo/moduleResource.go
pkg/codegen/testing/test/testdata/plain-object-defaults/go/example/foo.go
pkg/codegen/testing/test/testdata/plain-object-disable-defaults/go/example/foo.go
pkg/codegen/testing/test/testdata/plain-schema-gh6957/go/xyz/staticPage.go
pkg/codegen/testing/test/testdata/regress-go-8664/go/my8664/conditionalAccessPolicy.go
pkg/codegen/testing/test/testdata/secrets/go/mypkg/resource.go
pkg/codegen/testing/test/testdata/simple-enum-schema/go/plant/tree/v1/nursery.go
pkg/codegen/testing/test/testdata/simple-enum-schema/go/plant/tree/v1/rubberTree.go
pkg/codegen/testing/test/testdata/simple-plain-schema-with-root-package/go/component.go
pkg/codegen/testing/test/testdata/simple-plain-schema/go/example/component.go

Continue clean up of our use of pkg/errors. This changes our Go code generator to stop using it, there's still a few places in the sdk using it so go.mods will still reference it.
Looks like the only thing the code generator used "pkg/errors" for was `New` which is also on "errors".

Use 'errors' not 'pkg/errors' in go codegen

---

tests/integration/integration_util_test.go

integration_util_test contains a helper function synchronouslyDo
which attempts to run an operation with a file lock with a timeout,
in a blocking manner.
This implementation has a couple issues.
First, there's a data race between Lock() and Unlock() of the mutex:
the function defers an unlock regardless of whether a lock was acquired,
and if the timing is right, it causes a data race in FileMutex
on reading and writing the fsunlock field.
```
Read at 0x00c000388040 by goroutine 16:
github.com/pulumi/pulumi/sdk/v3/go/common/util/fsutil.(*FileMutex).Unlock()
/Users/runner/work/pulumi/pulumi/sdk/go/common/util/fsutil/lock.go:64 +0x3e
github.com/pulumi/pulumi/tests/integration.synchronouslyDo.func1()
/Users/runner/work/pulumi/pulumi/tests/integration/integration_util_test.g …
```

test/integration: Avoid data race from FileMutex

---

tests/integration/integration_util_test.go

Currently, component setup panics if there's an error.
This isn't great because when it panics,
it fails to notify the outer goroutine that's waiting for setup,
which leaves that goroutine waiting for 10 minutes gefore giving up.
The net effect of this is that when setup fails for a test,
it takes 10 minutes to kill the test
even if setup failed within seconds.
Fix this by using testify and logging errors right away.

test/integration: Don't panic during setup

---

.github/workflows/ci.yml
bors.toml

**Update:** With https://github.com/pulumi/pulumi/pull/12031 linting runs in about a minute.
Linting should be an extremely low-watermark requirement for evaluating build health. Blocking on it allows use to reduce the number of concurrent runners who are canceled early.
**Trade-offs:**
* This should delay CI time by the amount of time it takes to lint: _e.g._ CI will be ~5 minutes slower on the happy path.
* When a job is queued that fails a lint check, fewer runners will be soaked up just to fail lint checks. This will decrease the overall queue time across all builds.
* Ultimately, we're trading slower happy-path builds for smarter build scheduling. 
* We can mitigate the linting bottleneck by speeding up the linting process (https://github.com/pulumi/pulumi/pull/12023).
This PR …

Require linting before running unit, integ, and smoke tests.

---

sdk/go/pulumi/context.go
sdk/go/pulumi/provider.go
sdk/go/pulumi/resource.go
sdk/go/pulumi/resource_test.go

The `DependsOn` and `DependsOnInputs` resource options
store their captured information on the `resourceOptions` struct
in a lossy format: they store function references.
This makes it impossible to go back to the original lists of resources
or resource array inputs for use cases like #11698.
As a step towards making this possible,
replace the stored closures with interfaces.
The implementations in the first commit
are a drop-in replacement for the prior behavior
with no logic changes whatsoever.
The second commit makes a minor optimization:
it adds URNs to the same set instead
of constantly allocating new sets and combining them afterwards.
Refs #11698

sdk/go: Don't store DependsOn in a lossy form

---

.github/workflows/ci.yml

With Go 1.20, we no longer need to use macOS runners for these builds
because it includes a CGo-free DNS resolver.
Depends on #12039
Refs #9224

ci/build-targets: Use ubuntu runners for macOS

---

tests/integration/integration_util_test.go

Issue #12050 would have been a lot easier to debug
if we had been capturing the output of the commands.
This changes runComponentSetup to execute bash with `-x`
so that every command in the shell script is logged before it's run.
This feeds that output into an `io.Writer` that logs to the testing.TB.
This way, if the test fails or times out,
we'll have a bunch of meaningful log output
associated with the tests that ran them.
Capturing the command output in a reliable way
required introduction of something slightly more complicated
than `strings.Split(\n)` because there's a good chance
that we'll have partial lines written to the writer.
The approach taken by the Writer here is:
it will log the input one line at a time usually,
but when it sees a partial line, it will buffer it in-memory …

test/integration: Capture component setup output

---

.github/workflows/ci-test-docs-generation.yml
.github/workflows/ci.yml

Addresses the TODO and uses version-set generated by get-job-matrix
to decide which version of our various platforms should be used.

ci/test-docs-generation: Attempt to use version-sets

---

changelog/pending/20230204--cli--add-insecure-flag-to-pulumi-login-which-disables-https-certificate-checks.yaml
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/client/client.go
pkg/backend/httpstate/client/client_test.go
pkg/backend/httpstate/snapshot_test.go
pkg/cmd/pulumi/login.go
pkg/cmd/pulumi/logout.go
pkg/cmd/pulumi/policy_publish.go
pkg/cmd/pulumi/pulumi.go
pkg/cmd/pulumi/util.go
pkg/secrets/service/manager.go
sdk/go/common/workspace/creds.go

Add --insecure option to `pulumi login` which disables https certificate checks.
Fixes https://github.com/pulumi/pulumi/issues/9120

Add --insecure option to `pulumi login`

---

changelog/pending/20230131--sdk-go--delegate-alias-computation-to-the-engine.yaml
sdk/go/pulumi/context.go
sdk/go/pulumi/context_test.go

Fixes #11066
Addresses #11697 
Credit to @abhinav for making aliases unit-testable by intercepting `RegisterResource` calls. 
> I did change the test slightly so that it either checks for `AliasURNs: []string` or `Aliases: []*pulumirpc.Alias` because I've made it such that one of them is `nil` depending on `supportsAliasSpecs`

[sdks/go] Delegate alias computation to the engine

---

pkg/codegen/docs/templates/resource.tmpl

There are a few resources with a *very* large number of nested types.  We have seen this lead to generating docs pages that cannot be loaded in a browser.
Instead, only emit the first 200 nested types, and emit a note to users if we have done this.
In the AWS provider, this only triggers for `wafv2.WebAcl` and `wafv2.RuleGroup`.
This reduces the size of http://localhost:1313/registry/packages/aws/api-docs/wafv2/webacl/ from 64MB to 2.5MB (still huge - but manageable).
Fixes https://github.com/pulumi/registry/issues/1481 (once this is incorporate into `registrygen`).

[codegen/docs] Only emit first 200 nested types

---

sdk/python/lib/pulumi/runtime/invoke.py
sdk/python/lib/pulumi/runtime/resource.py
sdk/python/lib/pulumi/runtime/rpc_manager.py

A couple of the inner functions (`do_call`, `do_register`) weren't being type checked (mypy doesn't type check unannotated functions: https://mypy.readthedocs.io/en/stable/common_issues.html#no-errors-reported-for-obviously-wrong-code).
This adds annotations for those functions and then fixes up _all_ the type errors that fell out from that.

Enable type checking in some inner functions

---

changelog/pending/20230206--cli--fix-verbose-logging-to-filter-secrets.yaml
sdk/go/common/util/logging/log.go

We use a small logging wrapper around glog for most of our logging. The global Errorf/Warningf/Infof methods in that module format the string and args passed in then filter out any secrets before calling into glog with the final string.
The wrapper also exposed a `V` method to only log if verbosity was set, but that directly returned a glog.Verbose which mean the Infof calls to that didn't run our secret filtering code.
This changes the logging wrapper to return a `VerboseShim` (Not a great name, but `Verbose` was already taken in this module) which is simply a new type over `glog.Verbose` with the same methods but it calls `FilterString` on the inputs.
Technically a breaking change, but I think the uses of this will be source compatible.

Fix V logging to also filter out secrets

---

README.md

Follow up to #12097 and pulumi/pulumi-hugo#2476
Updates the README to say that for Go, we require supported Go versions
instead of just "1.18+" as that doesn't quite match our support policy.

README: Reference supported Go versions

---

changelog/pending/20230107--pkg--pkg-raise-go-directive-to-1-18.yaml
changelog/pending/20230107--sdk-go--sdk-raise-go-directive-to-1-18.yaml
developer-docs/go.mod
pkg/go.mod
sdk/go.mod
tests/go.mod

Raise the 'go' directive for top-level Go modules to 1.18.
This is the minimum version of Go required by Pulumi.
Raising this directive allows us to use language features like generics
in the codbase.
Resolves #11798
Note that this includes two changelog entries: one for sdk, one for pkg

go.mod: Raise to 'go 1.18'

---

pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/policy_new.go
pkg/cmd/pulumi/preview.go
pkg/cmd/pulumi/pulumi.go
pkg/cmd/pulumi/stack_select.go
pkg/cmd/pulumi/state_unprotect.go
pkg/cmd/pulumi/up.go
pkg/cmd/pulumi/util.go

Migrates uses of contract.{Assert, AssertNoError} in pkg/cmd
to use Assertf and AssertNoErrorf so that
we write more meaningful messages when these contracts are violated.
Incremental step towards deprecating the non-f variants.
Refs #12103

pkg/cmd: Prefer contract.Assertf over contract.Assert

---

pkg/cmd/pulumi/pulumi.go

The `gen-completion` command was unhidden in https://github.com/pulumi/pulumi/pull/10218 but the command wasn't actually moved away from the hidden command group.
When running `pulumi --help`, the `gen-completion` command appears under a `Hidden Commands` section.
```
Hidden Commands:
gen-completion 
```
This PR moves the command to the `Other Commands` section.

Move gen-completion away from Hidden Command block

---

changelog/pending/20230208--backend-filestate--pulumi-login-to-support-google-oauth-access-tokens-via-environment-variable.yaml
pkg/authhelpers/gcpauth.go

`pulumi login gs://....` now supports the use of google access tokens. If the environment variable `GOOGLE_OAUTH_ACCESS_TOKEN` is set during a `pulumi login gs://...` pulumi will utilize the provided token to login to the bucket, assuming this has not been pre-empted by another auth type.
Fixes  [#12067](https://github.com/pulumi/pulumi/issues/12067)

`pulumi login` to support google oauth access tokens for GCS buckets

---

changelog/pending/20230203--sdk-go--stackreference-getoutputdetails-go.yaml
sdk/go/pulumi/stack_reference.go
sdk/go/pulumi/stack_reference_test.go

Outputs received from StackReferences are currently
unnecessarily wrapped in `Output<T>`.
If the name is known (`string`, not `Input<string>`),
these values are largely fixed and "known" at runtime.
This change introduces a
StackReference.GetOutputDetails method to Go
and a StackReference.get_output_details method to Python.
This method returns a plain OutputDetails object.
This object has two fields: value and secretValue.
At most one of these fields is set,
depending on whether the stack reference output is a secret.
Refs #10839, #5035
---
**Related**

sdk/go/StackReference: Add GetOutputDetails

---

changelog/pending/20230203--sdk-python--sdk-py-stackreference-getoutputdetails-py-yaml.yaml
sdk/python/lib/pulumi/__init__.py
sdk/python/lib/pulumi/stack_reference.py
sdk/python/lib/test/test_stack_reference.py

This is the Python equivalent to the StackReference.GetOutputDetails
method and accompanying type added to the Go SDK in #12034.
This will allow users of the Python SDK to fetch outputs from stack
references directly--without going through an Output type.
Refs #10839, #5035

sdk/py/StackReference: Add get_output_details

---

changelog/pending/20230204--sdk-nodejs--stackreference-getoutputdetails-node.yaml
sdk/nodejs/runtime/mocks.ts
sdk/nodejs/stackReference.ts
sdk/nodejs/tests/stackReference.spec.ts
sdk/nodejs/tsconfig.json

NodeJS equivalent of the StackReference.GetOutputDetails
method and accompanying type added to the Go SDK in #12034.
This will allow users of the TypeScript and JavaScript SDKs
to fetch outputs from stack references directly--without going through
an Output type.
Couple notes about testing:
- `MockMonitor.readResource` kept exploding because the getCustom method
was missing on the provided object.
I didn't find any examples in the Node SDK
of using mocks to test StackReferences,
so I'm guessing this was an unexercised code path.
I've fixed that.
- It seems that the JavaScript SDK promotes an entire map to secret
if an item inside it is a secret.
So I had to isolate the two test cases into separate outputs
to get the plain text case to be written as a "value".
If there's a more correct way …

sdk/node/StackReference: Add getOutputDetails

---

changelog/pending/20230208--engine--fixes-an-issue-where-pulumi-state-delete-would-delete-all-matching-urns-in-interactive-mode.yaml
pkg/resource/edit/operations.go
pkg/resource/edit/operations_test.go

This PR fixes an issue where 'pulumi state delete <urn>' would prompt the user to disambiguate between multiple resources in state with the same URN and proceed to delete all of them. With this change, dependency checks are performed only if the deletion will lead to no resources possessing the URN. The targetDependents flag will only target dependents if the deleted resource will orphan the dependents.
Fixes #12077 
Fixes #12110

edit.DeleteResource now deletes by reference rather than by URN

---

pkg/resource/deploy/deploytest/pluginhost.go

Probably fixes https://github.com/pulumi/pulumi-terraform-bridge/issues/801

Fix SchemaPath in deployhost

---

changelog/pending/20230210--cli--remove-the-experimental-yes-using-update-plans-prompt.yaml
pkg/backend/apply.go

Fixes https://github.com/pulumi/pulumi/issues/11894

Remove the "yes, using Update Plans" prompt

---

changelog/pending/20230210--engine--fixed-issue-where-pulumi-displays-multiline-secrets-when-the-newlines-n-are-escaped.yaml
sdk/go/common/util/logging/log.go
sdk/go/common/util/logging/log_test.go

This PR fixes an issue where pulumi fails to mask multiline secrets that are JSONified. String matching did not work when newlines were replaced with `\n`.
Fixes #12016

Fixes multiline secrets not being masked when escaped.

---

sdk/go/pulumi/resource.go

CustomTimeouts is missing any documentation on what it's for,
and what the individual fields mean.
Add minimal godoc explaining use of the struct.

sdk/go: Document CustomTimeouts

---

pkg/codegen/utilities.go

Small change to remove a reflect check and just use Go generics instead.
I think this is our first use of generics in /pkg, which may affect providers but they should be on 1.18 by now.
I had a look at cleaning up the StringSet/Set stuff in this file as well but looks like that's best left till we require 1.20 so we can use the `comparable` constraint with interfaces https://stackoverflow.com/questions/71505556/go-generics-type-constraint-for-map-keys

Make SortedKeys type safe with generics

---

scripts/get-language-providers.sh

Tagged pulumi-dotnet to v3.54.0 while waiting for a new release, updating it here before kicking off a release

Update pulumi-dotnet to v3.54.0

---

changelog/pending/20230211--cli-plugin--remove-temporary-files-from-plugin-downloads.yaml
pkg/cmd/pulumi/plugin_install.go
pkg/engine/plugins.go
sdk/go/common/resource/plugin/host.go

Fixes https://github.com/pulumi/pulumi/issues/12144
There's only three places in the codebase that we call `workspace.DownloadToFile`. Before this change only one of them tried to run `os.Remove` to cleanup afterwards.
This unifies all to use `os.Remove` and to also explictly ignore the error returned by that (if it does fail it will log to `V(3)`).

Try to delete temporary files from plugin downloads

---

pkg/codegen/go/doc.go
pkg/codegen/go/gen.go
pkg/codegen/go/gen_program.go
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/go/utilities.go

Migrates uses of contract.{Assert, AssertNoError} in pkg/codegen/go
to use Assertf and AssertNoErrorf so that
we write more meaningful messages when these contracts are violated.
Incremental step towards deprecating the non-f variants.
Refs #12132

pkg/codegen/go: Prefer contract.Assertf over contract.Assert

---

changelog/pending/20230215--cli-import--fixes-panic-on-incomplete-resources-in-json-file.yaml
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/import_test.go

`pulumi import -f` panics if the JSON file provided as input
is missing information like ID or name.
This adds validation for the required fields of deploy.Import
when we're building it from the parsed file.
To provide maximum context in the error messages,
it attempts to extract any information it can glean
about the provided importSpec.
Example run:
```
% cat tmp.json
{
"resources": [
{
"type": "someTokenType",
"name": "someName"
}
]
}
% pulumi import -f tmp.json
error: resource 'someName' of type 'someTokenType' has no ID
```
Resolves #12103

cli/pulumi import: Don't panic on invalid file

---

changelog/pending/20230211--cli-plugin--plugin-download-urls-now-support-gitlab-as-a-first-class-url-schema-for-example-gitlab-gitlab-com-43429536.yaml
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_test.go

Plugin download urls now support GitLab as a first class url schema. For example "gitlab://gitlab.com/43429536".
The scheme is `gitlab://<host>/<project_id>`.
This assumes the apis are at `https://<host>//api/v4` e.g. fetching the latest version for the above url would fetch from `https://gitlab.com/api/v4/projects/43429536/releases/permalink/latest`.
It assumes that the GitLab release will have asset links in the same style as our GitHub releases. e.g.
`pulumi-resource-<package>-v<version>-<os>-<arch>.tar.gz` these names must be set for the `direct_asset_path` of the asset link in the GitLab release (see https://docs.gitlab.com/ee/api/releases/links.html#create-a-release-link).
It also assumes release names will be of the form `v<version>` like we do for GitHub, e.g. `v4.3.0`.
Whether …

Add gitlab source

---

sdk/go/auto/local_workspace_test.go
sdk/go/common/diag/sink.go
sdk/go/common/resource/asset.go
sdk/go/common/resource/config/crypt.go
sdk/go/common/resource/plugin/analyzer_plugin.go
sdk/go/common/resource/plugin/host.go
sdk/go/common/resource/plugin/langruntime_plugin.go
sdk/go/common/resource/plugin/plugin.go
sdk/go/common/resource/plugin/provider_plugin.go
sdk/go/common/resource/plugin/rpc.go
sdk/go/common/resource/plugin/rpc_test.go
sdk/go/common/resource/resource_id.go
sdk/go/common/tokens/names.go
sdk/go/common/util/buildutil/semver.go
sdk/go/common/util/mapper/mapper_decode.go
sdk/go/common/util/mapper/mapper_encode.go
sdk/go/common/util/rpcutil/rpcerror/rpcerror.go
sdk/go/common/util/rpcutil/writer.go
sdk/go/common/workspace/loaders.go
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/project.go
sdk/go/common/workspace/templates.go
sdk/go/common/workspace/workspace.go
sdk/go/pulumi/context.go
sdk/go/pulumi/provider.go
sdk/go/pulumi/rpc.go
sdk/go/pulumi/run.go
sdk/go/pulumi/types.go
sdk/python/python.go

Migrates all uses of contract.{Assert, AssertNoError, Require} in sdk/
to the `*f` variants that are required to provide more error context.
Step towards deprecating non-f variants entirely.
For context, `contract.Require` is similar to `contract.Assert`,
except it has a required parameter name as an argument:
func Require(cond bool, param string)
func Requiref(cond bool, param string, msg string, args ...any)
It includes the parameter name in the error message by default,
so the `msg` and `args` should only describe the constraint
without naming the parameter.
Refs #12132

sdk/go: Prefer contract.Assertf over Assert

---

pkg/engine/deployment.go
pkg/engine/destroy.go
pkg/engine/detailedDiff.go
pkg/engine/events.go
pkg/engine/import.go
pkg/engine/query.go
pkg/engine/refresh.go
pkg/engine/update.go

Migrates uses of contract.{Assert, AssertNoError, Require} in pkg/engine
to `*f` variants so that we're required to provide more error context.
Refs #12132

pkg/engine: Prefer contract.Assertf over Assert

---

sdk/go/pulumi/resource_test.go

This test has a bunch of independent blocks,
all in the form:
// <short explanation>
thing := ...
assertStuff(thing)
These are good candidates for subtests:
t.Run("short explanation", func(t *testing.T) {
thing := ...
assertStuff(thing)
})
This helps isolate them better and lets them run in parallel.
This commit contains no logic changes.

chore(sdk/go): Use subtests in TestResourceOptionMergingProvider

---

pkg/cmd/pulumi/login.go
pkg/cmd/pulumi/logout.go
pkg/cmd/pulumi/org.go
pkg/cmd/pulumi/policy_publish.go
pkg/cmd/pulumi/util.go
sdk/go/common/workspace/creds.go

Chipping away at https://github.com/pulumi/pulumi/issues/12152. This makes GetCurrentCloudURL take a `*Project` rather than loading the project itself. All call sites have been fixed up, most now need to the project loading there instead but over time we'll bump all these loads to the very top of the call stack in pkg/cmd.

Pass *Project to GetCurrentCloudURL

---

pkg/cmd/pulumi/about.go
pkg/cmd/pulumi/util.go

More little steps for https://github.com/pulumi/pulumi/issues/12152. Pass the *Project to nonInteractiveCurrentBackend so it doesn't have to load the project anymore.

Pass *Project to nonInteractiveCurrentBackend

---

changelog/pending/20230216--cli-display--display-now-shows-default-colorized-stacktraces-in-nodejs.yaml
pkg/backend/display/events.go
pkg/backend/display/events_test.go
sdk/nodejs/cmd/run-policy-pack/run.ts
sdk/nodejs/cmd/run/run.ts

This PR changes pulumi nodejs error logging to emit colorized stack traces to match nodejs's default behavior.
Fixes #10379 
New:
[![asciicast](https://asciinema.org/a/wh2tFUZXqm8cXqVo5WcHEexii.svg)](https://asciinema.org/a/wh2tFUZXqm8cXqVo5WcHEexii)
Current:
[![asciicast](https://asciinema.org/a/IvTzhNHfsAj82FT115bXT4XSN.svg)](https://asciinema.org/a/IvTzhNHfsAj82FT115bXT4XSN)

[sdk/nodejs] emit colorized stack traces

---

pkg/backend/backend.go
pkg/backend/filestate/backend.go
pkg/backend/filestate/backend_test.go
pkg/backend/httpstate/backend.go
pkg/backend/mock.go
pkg/cmd/pulumi/util.go

Next little bit for https://github.com/pulumi/pulumi/issues/12152. We pass the `*Project` to `currentProjectContradictsWorkspace` instead of loading the current project. One of the calls here was easy because we already had the project from the update operation struct. For the other I've had to thread a `*Project` through the `CreateStack` function. But we need that for some other stack creation bits anyway (Tags depend on the current project).

Pass *Project to currentProjectContradictsWorkspace

---

pkg/backend/backend.go
pkg/backend/filestate/backend.go
pkg/backend/filestate/backend_test.go
pkg/backend/httpstate/backend.go
pkg/backend/mock.go
pkg/backend/stack.go
pkg/cmd/pulumi/util.go

Next little bit for https://github.com/pulumi/pulumi/issues/12152. We now pass the root directory and project (if we have them, they can be "" and nil) to `GetEnvironmentTagsForCurrentStack`. Plumbing this up the call chain required adding "root" to the CreateStack call as well.

Pass root and project to GetTags methods

---

pkg/backend/display/display.go

This _might_ help with the issues we've been seeing with [automation api reading malformed JSON lines](https://github.com/pulumi/pulumi/issues/6768).

Set O_APPEND on the engine event log file

---

pkg/backend/httpstate/backend.go

we have said "tip of the day" since pulumi's birth
adjusting it to say "tip" since it never changes

remove "of the day" from login tip

---

bors.toml

Temporarily dropping lint requirement from bors
to unblock merging community PRs.
(Lint will still run as part of the merge workflow. This only drops it as a requirement for attempting the merge.)
Refs #12248

bors: Drop lint requirement

---

.github/scripts/set-output
.github/workflows/ci-run-test.yml
.github/workflows/ci-test-docs-generation.yml
.github/workflows/download-pulumi-cron.yml
.github/workflows/pr-test-codegen-test-on-dispatch.yml
.github/workflows/pr-test-docs-generation-on-dispatch.yml

Fixes #12244 
Update workflows to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```

Replace deprecated command with environment file

---

pkg/backend/apply.go
pkg/backend/display/object_diff.go
pkg/backend/filestate/backend.go
pkg/backend/filestate/lock.go
pkg/backend/filestate/state.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/client/client.go
pkg/backend/httpstate/stack.go
pkg/backend/httpstate/state.go
pkg/backend/snapshot.go

Migrates uses of contract.{Assert, AssertNoError, Require} in pkg/engine
to `*f` variants so that we're required to provide more error context.
Refs #12132

pkg/backend: Prefer contract.Assertf over Assert

---

pkg/resource/deploy/deploytest/provider.go
pkg/resource/deploy/providers/provider.go
pkg/resource/deploy/providers/reference.go
pkg/resource/deploy/providers/registry.go
pkg/resource/edit/operations.go
pkg/resource/graph/dependency_graph.go
pkg/resource/stack/checkpoint.go
pkg/resource/stack/deployment.go

Migrates some uses of contract.{Assert, AssertNoError, Require} in
pkg/resource to `*f` variants so that we're required to provide more
error context.
Refs #12132

pkg/resource: Prefer Assertf in some subpackages

---

pkg/resource/deploy/builtins.go
pkg/resource/deploy/deployment.go
pkg/resource/deploy/deployment_executor.go
pkg/resource/deploy/import.go
pkg/resource/deploy/plan.go
pkg/resource/deploy/snapshot.go
pkg/resource/deploy/source_eval.go
pkg/resource/deploy/step.go
pkg/resource/deploy/step_generator.go

pkg/resource/deploy has a bunch of Assert usages
without messages.
This migrates all of them to `*f` variants,
preferring `Requiref` for paramters.
Refs #12132

pkg/resource/deploy: Prefer Assertf

---

.github/workflows/rebase.yml

The `/rebase` command only runs for collaborators right now, but not for repository members or owners.
This updates the job to support the command from owners and members.
(See https://docs.github.com/en/graphql/reference/enums#commentauthorassociation.)
The `fromJSON` business is necessary to be able to represent the array in the GitHub expression.
(See https://docs.github.com/en/actions/learn-github-actions/expressio˚ns#example-matching-an-array-of-strings.)
Refs #12251

ci/rebase: Run for members and owners

---

sdk/python/lib/test/test_resource.py

The MergeResourceOptions test was incorrectly invoking
the static method ResourceOptions.merge as an instance method.
This issue was reported by the type-checker.

sdk/py/test: Fix MergeResourceOptions test

---

changelog/pending/20230227--sdk-nodejs--cleanup-temporary-pulumi-node-pipes-folders-after-running.yaml
sdk/nodejs/cmd/pulumi-language-nodejs/main.go
sdk/nodejs/cmd/pulumi-language-nodejs/proxy_unix.go

Fixes https://github.com/pulumi/pulumi/issues/12263
This calls shutdown on the pipes created in `Run` to ensure they always get cleaned up. Changed the multiple `Remove` calls to just a single `RemoveAll`, oddly the multiple `Remove` calls didn't seem to delete everything.

Cleanup node-pipes folder after Run

---

changelog/pending/20230301--sdk-python--grpc-1-51.3-python-sdk-contains-native-arm64-binaries.yaml
sdk/python/lib/setup.py
sdk/python/requirements.txt

[grpc 1.51.3](https://github.com/grpc/grpc/releases/tag/v1.51.3) contains a wheel with native arm64 binaries (universal2), easing the installation of the Pulumi Python SDK on Apple M1/M2 machines.grp

Python grpc 1.51.3 contains universal2 binaries (x86_64 & arm64)

---

LICENSE

Fixes https://github.com/pulumi/pulumi/issues/12316
As per https://opensource.stackexchange.com/questions/4149/include-appendix-of-apache-2-0-in-license-file the appendix of the Apache 2.0 license does not need to be included in the LICENSE file. We keep getting people commenting that we haven't filled in the name and data in the appendix so to reduce confusion lets just remove it.

Remove appendix from LICENSE

---

.github/workflows/ci-run-test.yml
.github/workflows/release.yml

We have a few places in CI where we use action-install-gh-release
to download and install specific or latest binary releases of a
dependency.
Nearly all these steps, besides the one in ci-test-codegen,
were unauthenticated.
This caused us to run into rate limits with the GitHub API
when trying to get the latest release and resulted in delays like:
```
Run jaxxstorm/action-install-gh-release@v1.7.1
==> System reported platform: linux
==> Using platform: linux
==> System reported arch: x64
==> Using arch: x64
Warning: RateLimit detected for request GET /repos/{owner}/{repo}/releases/tags/{tag}.
Retrying after 3300 seconds.
Error: The operation was canceled.
```
This sets GITHUB_TOKEN for all instances of this step
so that we're less likely to get rate limited by GitHub on this.

ci: Run action-install-gh-release with auth

---

changelog/pending/20230301--backend-service--reduce-retrieval-validation-latency-for-update-tokens.yaml
pkg/backend/httpstate/client/api.go
pkg/backend/httpstate/client/client.go
pkg/backend/httpstate/client/client_test.go
pkg/backend/httpstate/snapshot.go
pkg/backend/httpstate/snapshot_test.go
pkg/backend/httpstate/state.go
pkg/backend/httpstate/token_source.go
pkg/backend/httpstate/token_source_test.go

Rather than fetching update tokens in consumers of the API client, fetch them in the API client itself. This minimizes the latency between the retrieval of the token and the validation of the token by the Pulumi Service. This is intended to help prevent the use of expired tokens.
Part of #7094.

[cli] Fetch update tokens in the API client

---

scripts/retry

The set-output command has been deprecated by GitHub.
Replace it with the GITHUB_OUTPUT based variant.
This was the only remaining instance of `::set-output`
in the repository after e4e96c96d.

scripts/retry: set-output is deprecated

---

changelog/pending/20230228--sdk-go--fix-panic-from-attempting-to-create-a-resource-with-an-uninitialized-parent-resource.yaml
sdk/go/pulumi/context.go
sdk/go/pulumi/resource_test.go

The Go SDK panics if RegisterResource is called with a parent resource
that is uninitialized
(hasn't had its RegisterResource or RegisterComponentResource call yet).
The panic is during alias collapsing:
the system fails to read the unintialized parent resource's URN
from a zero-valued URNOutput.
Guard against this panic by verifying that the value passed to `Parent`
has been initialized.
We do this by checking the name of the resource--names are not allowed
to be empty when a resource is registered.
Resolves #12138

sdk/go: Fix panic from uninitialized parent resources

---

sdk/nodejs/package.json
sdk/nodejs/yarn.lock

A user mentioned having an issue with building due to a bug in an older version of the library.
- https://github.com/pulumi/pulumi/pull/8214#issuecomment-1448889221
Fixes #12312

unpin grpc-js

---

pkg/codegen/python/gen.go
pkg/codegen/python/gen_program.go
pkg/codegen/python/gen_program_expressions.go
pkg/codegen/python/gen_program_lower.go
pkg/codegen/python/gen_program_quotes.go

Migrates uses of contract.{Assert, AssertNoError, Require}
to `*f` variants so that we're required to provide more error context.
Refs #12132

pkg/codegen/python: Prefer contract.Assertf over Assert

---

pkg/codegen/nodejs/gen.go
pkg/codegen/nodejs/gen_lazyloads.go
pkg/codegen/nodejs/gen_program.go
pkg/codegen/nodejs/gen_program_expressions.go
pkg/codegen/nodejs/gen_program_lower.go
pkg/codegen/nodejs/utilities.go

Migrates uses of contract.{Assert, AssertNoError, Require}
to `*f` variants so that we're required to provide more error context.
Refs #12132

pkg/codegen/nodejs: Prefer contract.Assertf over Assert

---

pkg/backend/backend.go
pkg/backend/httpstate/policypack.go
pkg/cmd/pulumi/convert_test.go
pkg/cmd/pulumi/gen_markdown.go
pkg/cmd/pulumi/policy_ls.go
pkg/codegen/dotnet/gen.go
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/hcl2/syntax/comments_test.go
pkg/codegen/nodejs/gen.go
pkg/codegen/nodejs/gen_program_expressions.go
pkg/codegen/python/gen.go
pkg/codegen/python/gen_program_expressions.go
pkg/codegen/schema/docs_test.go
pkg/testing/integration/program.go
pkg/testing/integration/util.go
sdk/go/common/diag/colors/colors.go
sdk/go/common/resource/asset.go
sdk/go/common/resource/plugin/analyzer_plugin.go
sdk/go/common/resource/plugin/langruntime_plugin.go
sdk/go/common/resource/plugin/provider_plugin.go
sdk/go/common/util/cmdutil/exit.go
sdk/go/common/util/fsutil/qname.go
sdk/go/common/util/rpcutil/writer_test.go
sdk/go/common/workspace/templates.go
sdk/go/common/workspace/workspace.go

Replaces all instances of `strings.Replace(s, old, new, -1)`
with the equivalent `strings.ReplaceAll(s, old, new)`.
This function has been available since Go 1.12.

chore(all): strings.Replace(..., -1) => strings.Replace(...)

---

Makefile
pkg/codegen/testing/test/helpers.go
pkg/codegen/testing/test/testdata/random-4.11.2.json
pkg/codegen/testing/utils/host.go

Adds the most recent relese of pulumi-random to included schemas.
We need something newer than 4.2.0 or 4.3.1 (both from 2021)
to test options added since then, like retainOnDelete.
Refs https://github.com/pulumi/pulumi/pull/12306#issuecomment-1450923083

testdata/schema: Add random 4.11.2

---

sdk/nodejs/tests/resource.spec.ts

Adds a test case to verify that a ComponentResource
propagates its Provider and Providers values
to children constructed with that type.
Refs #12161

sdk/node: Test case for Provider propagation

---

changelog/pending/20230227--sdk-python--component-resource-provider-propagation.yaml
sdk/python/lib/pulumi/resource.py
sdk/python/lib/test/test_resource.py

It's currently possible in Pulumi to pass a ProviderResource
as a Provider option to a ComponentResource.
The ComponentResource will record the Provider for later,
and propagate it to its child resources.
This is currently the behavior in [all SDKs except Python][1].
[1]: https://github.com/pulumi/pulumi/issues/12161#issuecomment-1446864847
The reason this didn't work was because in Python's
providers merging logic, we use the incorrect package name
when saving the provider.
Instead of using the package name reported by the provider,
we were using the package name of the current resource
(the ComponentResource in this case).
To fix this, verify that the package name of the provider
matches the package name of the resource we're building.
If it doesn't, we will still save the provider
for …

sdk/py/ComponentResource: Propagate provider to children

---

.vscode/settings.json

We enabled gofumpt on the repository in #12347.
This updates the workspace-local VSCode configuration
to use gofumpt to format Go code.

vscode/settings: Enable gofumpt

---

changelog/pending/20230224--auto-dotnet-go-nodejs-python--fix-support-for-specifying-a-git-commit-for-remote-workspaces.yaml
pkg/cmd/pulumi/util_remote.go

This was being parsed from CLI flags, but seemingly not passed into the Deployment.
Not 100% sure how/where to add test coverage for this.

Pass `--remote-git-commit` to remote deployment

---

changelog/pending/20230224--auto-nodejs--fixes-issue-with-specifying-a-git-username-for-remote-workspaces.yaml
sdk/nodejs/automation/localWorkspace.ts
sdk/nodejs/tests/automation/remoteWorkspace.spec.ts

When a git username is specified for remote workspaces, we were using the wrong CLI flag. It should be `--remote-git-auth-username` not `--remote-git-username`. This change fixes this and adds tests to confirm we're using the right flag names for all the various remote workspace options.
Fixes #12264

[auto/nodejs] Fixes username for remote workspaces

---

changelog/pending/20230227--auto-go--enable-programmatic-tagging-of-stacks-go-only.yaml
sdk/go/auto/local_workspace.go
sdk/go/auto/local_workspace_test.go
sdk/go/auto/stack.go
sdk/go/auto/workspace.go

Adds support for tagging stacks with the Go automation API.
* https://github.com/pulumi/pulumi/issues/11936 (Go support)

Add stack tag support for go automation api sdk

---

changelog/pending/20230302--auto-go--fetch-commits-before-checkout.yaml
sdk/go/auto/git.go

If a commit hash is specified for a Git repo, explicitly fetch it before attempting to check it out. This allows using commits that are not fetched by default (e.g. GitHub test merge commits).

[go/auto/git] Fetch a commit if one is specified

---

changelog/pending/20230228--sdk-go--fixes-overwrite-of-the-provider-option-by-the-providers-option-due-to-ordering.yaml
sdk/go/pulumi/context.go
sdk/go/pulumi/resource.go
sdk/go/pulumi/resource_test.go

This change fixes a discrepancy in the Provider and Providers options
versus other SDKs:
Provider option doesn't always take precedence in the Go SDK.
Suppose we have providers 'ambient' and 'local' for the same package.
We want to use 'local' directly for the resource,
and 'ambient' for its child resources.
So we pass the options,
`Providers(ambient)` to put ambient into the bag of providers,
and `Provider(local)` to use it for the resource.
NewResource(ctx, Providers(ambient), Provider(local))
This works as expected, but if we flip the order of the options,
it doesn't:
NewResource(ctx, Provider(local), Providers(ambient))
This is because of how the two options are merged in the Go SDK.
`Provider(..)` unconditionally turns into `Providers(..)`,
losing the information about it being …

sdk/go/ResourceOption: Provider option takes precedence

---

changelog/pending/20230224--auto-python--enable-programmatic-tagging-of-stacks-python-only.yaml
sdk/python/lib/pulumi/automation/_local_workspace.py
sdk/python/lib/pulumi/automation/_stack.py
sdk/python/lib/pulumi/automation/_tag.py
sdk/python/lib/pulumi/automation/_workspace.py
sdk/python/lib/test/automation/test_local_workspace.py

Adds support for tagging stacks with the Python automation API.
* https://github.com/pulumi/pulumi/issues/11936 (Python support)

Add stack tag support for python automation api sdk

---

pkg/backend/backend.go
pkg/backend/filestate/backend.go
pkg/backend/filestate/backend_test.go
pkg/backend/filestate/bucket_test.go
pkg/backend/httpstate/backend.go
pkg/backend/httpstate/snapshot_test.go
pkg/backend/mock.go
pkg/cmd/pulumi/login.go
pkg/cmd/pulumi/logout.go
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/policy_publish.go
pkg/cmd/pulumi/stack_init.go
pkg/cmd/pulumi/stack_select.go
pkg/cmd/pulumi/up.go
pkg/cmd/pulumi/util.go

Rather than passing a `*workspace.Project` to most backend methods, just say that backends have a "current project" property. We set this on creation (because we normally have a project before creating a backend) but we also add a `SetCurrentProject` method for `pulumi new` to use because it's the (currently) one place where we need a backend before we have the project to go with it.

Set the current project as ambient context on backends.

---

changelog/pending/20230209--sdk-go--adds-newresourceoptions-to-preview-the-effect-of-a-list-of-resourceoption-values.yaml
sdk/go/pulumi/resource.go
sdk/go/pulumi/resource_test.go

Adds a new ResourceOptions type
and a constructor for it
func NewResourceOptions(...ResourceOption) ResourceOptions
Together, these provide a means for users
to look inside a `...ResourceOption` argument
from mocks and component resource implementations.
ResourceOptions is intended to *mostly* mirror
the internal resourceOptions struct
that the ResourceOption interface operates on.
However, it diverges from the internal representation
in a few places for a better user-facing API.
For example,
- instead of `map[string]Provider`, expose `[]Provider`
sorted by the `string`
- instead of dependency URN information,
expose fields analogous to the original options
More importantly, note that ResourceOptions currently
**does not** have a Provider field.
This is because of a bug that caused …

sdk/go: Support looking inside []ResourceOption

---

changelog/pending/20230228--programgen-dotnet-go-nodejs-python--adds-support-for-generating-retainondelete-options.yaml
pkg/codegen/dotnet/gen_program.go
pkg/codegen/go/gen_program.go
pkg/codegen/nodejs/gen_program.go
pkg/codegen/python/gen_program.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/retain-on-delete-pp/dotnet/retain-on-delete.cs
pkg/codegen/testing/test/testdata/retain-on-delete-pp/go/retain-on-delete.go
pkg/codegen/testing/test/testdata/retain-on-delete-pp/nodejs/retain-on-delete.ts
pkg/codegen/testing/test/testdata/retain-on-delete-pp/python/retain-on-delete.py
pkg/codegen/testing/test/testdata/retain-on-delete-pp/retain-on-delete.pp
pkg/codegen/testing/test/testdata/transpiled_examples/azure-app-service-pp/nodejs/package.json
pkg/codegen/testing/test/testdata/transpiled_examples/cue-random-pp/dotnet/dotnet.csproj
pkg/codegen/testing/test/testdata/transpiled_examples/cue-random-pp/nodejs/package.json
pkg/codegen/testing/test/testdata/transpiled_examples/random-pp/dotnet/dotnet.csproj

Uses the newly added `options.retainOnDelete` in PCL
to generate the RetainOnDelete resource option
for Go, NodeJS, .NET, and Python.
Java support cannot be added without a release of pulumi/pulumi
because the new field in pcl.ResourceOptions is not yet visible
to Java.
The change has been staged at https://github.com/pulumi/pulumi-java/pull/1005
pending merge and release of #12305.
Resolves #12304

codegen/{go,js,.net,py}: Generate retainOnDelete

---

pkg/backend/httpstate/backend.go
pkg/backend/httpstate/stack.go
pkg/cmd/pulumi/new_acceptance_test.go
pkg/cmd/pulumi/new_test.go
pkg/cmd/pulumi/org.go
pkg/cmd/pulumi/util.go
sdk/go/common/workspace/creds.go

Next step towards project cache cleanup. This passes the project explicitly to GetBackendConfigDefaultOrg rather than that doing a lookup for the project. It also fixes up the http stack references to use the `backend.currentProject` rather than looking up the current project on the file system.

Pass *workspace.Project to GetBackendConfigDefaultOrg

---

changelog/pending/20230307--cli-display--reorder-options-to-handle-pending-creates-users-can-now-hold-enter-to-select-the-clear-option-which-should-be-more-ergonomic.yaml
pkg/cmd/pulumi/refresh.go

When deleting a large number of resources from pending_creates, it is tedious to hit down and enter for each resource. 
Reordered pending create options to make it more ergonomic for users to hold Enter to resolve it.
Part of #12335 (I don't want to close the issue since there are some other ideas we could do to make it nicer, but this fix is very simple in the meantime.)

pulumi refresh `pending create` ordering

---

changelog/pending/20230307--cli-display--autoscroll-the-interactive-display-and-support-pgup-pgdown.yaml
pkg/backend/display/internal/terminal/term.go
pkg/backend/display/internal/terminal/term_test.go
pkg/backend/display/testdata/not-truncated/template-body.json.interactive-80x24-cooked.stdout.txt
pkg/backend/display/testdata/not-truncated/template-body.json.interactive-80x24.stdout.txt
pkg/backend/display/tree.go

These changes make two improvements to scrolling in the interactive display:
1. The interactive display can now be scrolled using the page-down and
page-up keys. These keys scroll the display N lines at a time, where N is
the height of the terminal.
2. If the display is scrolled to the bottom, it will now autoscroll it as new lines
are added to the output.
Fixes #12320 
Fixes #12295

[cli] Improve interactive scrolling

---

changelog/pending/20230307--auto-go--the-various-workspace-load-routines-e-g-loadproject-are-no-longer-singularly-cached.yaml
sdk/go/auto/local_workspace_test.go
sdk/go/common/workspace/loaders.go

Fixes https://github.com/pulumi/pulumi/issues/12152
This caching was originally added in https://github.com/pulumi/pulumi/pull/6576 two years ago. It saved a lot of file access because the system was repeatedly calling into the workspace module to load and re-load project files. We've cleaned up the system code to instead load the project files once, and pass the loaded `workspace.Project` object down the callchain to other sites that need it, rather than each site searching and loading the project. As such removing these caches shouldn't regress performance.

Remove the global caches for project files

---

sdk/go/common/util/cmdutil/console_test.go

Add a unit test for IsTruthy
because it appears to be lacking one.

go/cmdutil: Test for IsTruthy

---

sdk/go/pulumi/context.go
sdk/nodejs/runtime/resource.ts
sdk/python/lib/pulumi/resource.py

We added a warning here with the intention of turning it into an error
in July 2022, but we never did.
While we're discussing whether we still want this to become an error,
drop the specific date and just refer to "a future version."
Refs #8799

sdk: Drop date from provider conflict warning

---

sdk/nodejs/tests/automation/localWorkspace.spec.ts

Fix the test to use a random suffix in the stack name (like the other tests) to prevent failures during concurrent runs.
Fixes #12385

[sdk/nodejs/tests] Fix bug in test that prevents concurrent runs

---

changelog/pending/20230309--cli-plugin--fix-sending-empty-tokens-to-github-api.yaml
sdk/go/common/workspace/plugins.go
sdk/go/common/workspace/plugins_test.go

Fixes https://github.com/pulumi/pulumi/issues/12391
This looks to be the cause of the 401 responses from GitHub. When we refactored some code to add GitLab authorization headers we started sending half-filled headers when the envvars weren't set (e.g. Authorization = "token "). Looks like this was triggering GitHub to just blanket fail these requests to the /releases endpoint even though authorization wasn't even needed.

Don't send empty token/Bearer headers

---

changelog/pending/20230306--programgen-dotnet--pcl-components-and-dotnet-program-gen-implementation.yaml
pkg/cmd/pulumi/convert.go
pkg/codegen/dotnet/gen_program.go
pkg/codegen/dotnet/gen_program_expressions.go
pkg/codegen/dotnet/utilities.go
pkg/codegen/pcl/binder.go
pkg/codegen/pcl/binder_component.go
pkg/codegen/pcl/binder_nodes.go
pkg/codegen/pcl/binder_resource.go
pkg/codegen/pcl/binder_test.go
pkg/codegen/pcl/component.go
pkg/codegen/pcl/program.go
pkg/codegen/python/gen_program_quotes_test.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/components-pp/components.pp
pkg/codegen/testing/test/testdata/components-pp/dotnet/ExampleComponent.cs
pkg/codegen/testing/test/testdata/components-pp/dotnet/SimpleComponent.cs
pkg/codegen/testing/test/testdata/components-pp/dotnet/components.cs
pkg/codegen/testing/test/testdata/components-pp/exampleComponent/main.pp
pkg/codegen/testing/test/testdata/components-pp/simpleComponent/main.pp

This PR implements resource components as a construct at the PCL level to be consumed by program-gen and emit components for every language. As a starting point, I've implemented the program-gen implementation for dotnet and it works great! 
for PCL binding, added the new type of node called `Component` which now part of a PCL program along with config, resource, local variables and output variables. 
The binder for the _root_ PCL program now requires `DirPath` option when encountering a component declaration because we need to resolve the source files of the component, relative to the component that declares it. When binding a component, we create a new binder for the child program of that component and providing `Join(dirPath, componentSource)` as the new `DirPath` of that component. …

[pcl/programgen] PCL component block, binding and dotnet program-gen implementation

---

changelog/pending/20230304--cli--add-json-flag-to-pulumi-whoami-to-emit-output-as-json.yaml
changelog/pending/20230305--auto-nodejs--add-url-and-organizations-to-whoamiresult-for-nodejs-automation-api.yaml
changelog/pending/20230305--auto-python--add-url-and-organizations-to-whoamiresult-for-python-automation-api.yaml
changelog/pending/20230306--auto-go--add-whoamidetailed-which-includes-user-url-and-organizations-to-go-automation-api.yaml
pkg/cmd/pulumi/whoami.go
sdk/go/auto/local_workspace.go
sdk/go/auto/local_workspace_test.go
sdk/go/auto/workspace.go
sdk/nodejs/automation/localWorkspace.ts
sdk/nodejs/automation/workspace.ts
sdk/nodejs/tests/automation/localWorkspace.spec.ts
sdk/python/lib/pulumi/automation/_local_workspace.py
sdk/python/lib/pulumi/automation/_workspace.py
sdk/python/lib/test/automation/test_local_workspace.py

* Adds `--json` flag to `pulumi whoami` (CLI)
* Adds `url` and `organizations` to WhoAmIResult in NodeJS, Go and Python (automation API)
I sanity tested the auto api in the 3 runtimes and the cli output looks like:
```bash
$ pulumi whoami -j
{
"user": "me",
"organizations": [
"me",
"company"
],
"url": "https://app.pulumi.com/me"
}
```
Fixes # https://github.com/pulumi/pulumi/issues/10356

whoami: Add --json flag, expose everything in Auto API

---

pkg/cmd/pulumi/whoami.go
pkg/cmd/pulumi/whoami_test.go

This is a follow up to #12374.
Refactors the implementation of the whoami command
to use a whoAmICmd struct with less reliance on global state.
This is the same pattern as #11951.
With the refactor in place,
this adds tests for the core funtionality of the whoami command,
including the changes made in #12374.
This PR consists of two individually reviewable commits.

cmd/whoami: Refactor and test

---

.golangci.yml
pkg/backend/display/diff_test.go
pkg/backend/display/progress.go
pkg/backend/display/tree.go
pkg/cmd/pulumi/convert.go
pkg/cmd/pulumi/crypto.go
pkg/cmd/pulumi/destroy.go
pkg/cmd/pulumi/import.go
pkg/cmd/pulumi/new.go
pkg/cmd/pulumi/package_gen_sdk.go
pkg/codegen/dotnet/doc.go
pkg/codegen/go/gen_program_expressions.go
pkg/codegen/pcl/binder_component.go
pkg/codegen/pcl/binder_resource.go
pkg/codegen/python/gen_program_expressions.go
pkg/codegen/schema/bind.go
pkg/codegen/schema/schema.go
pkg/engine/lifecycletest/delete_before_replace_test.go
pkg/engine/lifecycletest/golang_sdk_test.go
pkg/engine/lifecycletest/provider_test.go
pkg/engine/lifecycletest/pulumi_test.go
pkg/engine/lifecycletest/resource_reference_test.go
pkg/engine/lifecycletest/test_plan.go
pkg/engine/lifecycletest/update_plan_test.go
sdk/go/common/resource/config/crypt.go
sdk/go/common/resource/resource_id_test.go
sdk/go/pulumi/run_test.go

golangci-lint: Drop goconst
Per team discussion, drop goconst.
The number of false positives with this linter is too high.
Whether or not something should be a constant
is the author and the reviewer's decision.
Also drops the nolint:goconst directives.

golangci: Drop goconst

---

.vscode/settings.json

This has always been experimental, and is due for removal now that go workspaces are a thing. Turning it on is probably detrimental to gopls performance as well due to the number of go.mod files in this repo, most of which aren't interesting for day-to-day work.

Remove experimentalWorkspaceModule from vscode settings

---

changelog/pending/20230310--cli-display--do-not-treat-single-line-strings-as-yaml-values.yaml
pkg/backend/display/object_diff.go
pkg/backend/display/object_diff_test.go

Only attempt to decode _multi-line_ strings as YAML values. This avoids decoding simple strings like "foo: bar" or "-" as YAML.
Fixes #12405.

[cli/diff] Tighten the YAML value heuristic

---

changelog/pending/20230310--sdk-go--fixes-an-id-handling-bug-in-provider_server-read-implementation.yaml
sdk/go/common/resource/plugin/provider_server.go
sdk/go/common/resource/plugin/provider_server_test.go

There seems to be an issue with provider_server ignoring the inner ID. In the case of importing random passwords, this leaks the secret password in plaintext into the state. 
See also: https://github.com/pulumi/pulumi-terraform-bridge/pull/882

Fix provider_server ID handling in Read

---

pkg/backend/display/tree.go
pkg/backend/httpstate/backend.go
pkg/cmd/pulumi/console.go
pkg/go.mod
pkg/go.sum
tests/go.mod
tests/go.sum

We currently have two different "open in browser" libraries
imported into our system:
github.com/pkg/browser
github.com/skratchdot/open-golang/open
pkg/browser has slightly more activity than open-golang
so switch to pkg/browser and delete the unused dependency.

pkg: Dedupe "open in browser" library

---

pkg/codegen/python/gen_test.go
pkg/testing/integration/program_test.go
sdk/go/common/resource/plugin/provider_plugin_test.go
sdk/go/common/testing/iotest/log_writer.go
sdk/go/common/testing/iotest/log_writer_test.go
tests/integration/integration_util_test.go

Adds a new iotest subpackage to the common/testing package
and moves the testLogWriter used in a prior integration test
into this directory.
The new API is:
package iotest
func LogWriter(testing.TB) io.Writer
This is a generally useful utility in any test that needs an io.Writer,
where we want them to not pollute actual stdout or stderr.
There are a few direct uses of os.Stderr and os.Stdout in our tests.
The second commit switches these to use iotest.LogWriter where appropriate,
Uses of os.Stdout/Stderr that were omitted:
- Example tests: These don't have a testing.TB to log to.
- pulumi/main_test: Replaces the global os.Stdout/Stderr in TestMain.
LogWriter isn't relevant there.

sdk/go: Add common/testing/iotest package

---

changelog/pending/20230209--sdk-go--adds-newinvokeoptions-to-preview-the-effect-of-a-list-of-invokeoption-values.yaml
sdk/go/pulumi/context.go
sdk/go/pulumi/resource.go
sdk/go/pulumi/resource_test.go

This is the InvokeOption analog for NewResourceOptions added in #12124.
However, in contrast to ResourceOptions, this just exports the existing
invokeOptions struct.
The reason for this is that right now, the public API for InvokeOptions
is the same as the internal representation,
so we don't need the separation-- for now.
To keep future edits aware of this distinction,
I've included a loud comment about what to do
when they do inevitably diverge.
Refs #11698

sdk/go: Support looking inside []InvokeOption

---

pkg/backend/filestate/backend.go
pkg/backend/filestate/backend_test.go
pkg/codegen/schema/loader_test.go
pkg/resource/deploy/source_eval_test.go
sdk/go/common/testing/diagtest/sink.go
sdk/go/common/testing/diagtest/sink_test.go
sdk/go/common/testing/iotest/log_writer.go
sdk/go/common/testing/iotest/log_writer_test.go

Adds a testing/diagtest package similar to
the previously added iotest package (#12377)
which writes log messages to a testing.TB's log stream.
This makes tests less noisy and helps associate error messages
with the exact test cases they came from.
diagtest, unlike iotest, prefixes each message with stdout or stderr.
To reuse iotest.LogWriter for this, we add support to iotest.LogWriter
to specify an optional prefix string.
This also updates all tests that use cmdutil.Diag directly
(because these write to the test process' stdout/stderr)
and instead use diagtest.Sink to have them write
to the test's logger.

sdk/common: Add testing/diagtest package

---

pkg/backend/filestate/backend.go
pkg/backend/filestate/backend_test.go
pkg/backend/filestate/bucket_test.go
pkg/cmd/pulumi/login.go
pkg/cmd/pulumi/util.go

Instead of using context.TODO everywhere,
plumb context.Context into filestate.New and filestate.Login,
and through that into other operations.
Change extracted from #12134

filestate: Plumb context through constructor

---

scripts/get-job-matrix.py

Node 19.8.0 was released ~5 hours ago and we're hitting an internal assert. Pin to 19.7.x to unblock CI until we understand what's going on with 19.8.0.
Part of #12434

Pin CI to Node 19.7.x to avoid hitting assert in 19.8.0

---

changelog/pending/20230314--sdk-go--fixes-use-of-provider-option-from-parent-resources-with-mismatched-packages.yaml
sdk/go/pulumi/context.go
sdk/go/pulumi/resource_test.go

In #12296, we started correctly interpreting the Provider argument
per other SDKs. but this introduced a regression:
the Provider field is now set for resources with mismatched types.
This results in a scenario where a provider foo for package X
is passed to a resource bar with package Y,
with the intent of plumbing it to bar's descendants,
but bar attempts to incorrectly use the provider directly.
foo := NewXProvider()
bar := NewYThing("bar", Provider(foo))
// ...
baz := NewXThing("baz", Parent(bar)) // should use foo
This worked previously, but with #12296, this fails
because NewYThing attempts to use Provider foo directly.
To fix this, we need to prevent NewYThing from using a provider
that does not match the package that it belongs to.
We had to make a similar change to the Python SDK …

sdk/go: Don't use Provider for type if package doesn't match

---

.gitignore
changelog/pending/20230309--programgen-dotnet-nodejs--component-resources-implementation-including-nested-components.yaml
pkg/codegen/dotnet/gen_program.go
pkg/codegen/nodejs/gen_program.go
pkg/codegen/nodejs/gen_program_expressions.go
pkg/codegen/pcl/binder_component.go
pkg/codegen/pcl/program.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/components-pp/dotnet/ExampleComponent.cs
pkg/codegen/testing/test/testdata/components-pp/exampleComponent/main.pp
pkg/codegen/testing/test/testdata/components-pp/nodejs/components.ts
pkg/codegen/testing/test/testdata/components-pp/nodejs/exampleComponent.ts
pkg/codegen/testing/test/testdata/components-pp/nodejs/simpleComponent.ts

- NodeJS program-gen implementation for component resources: generating components in seperate files and referencing them from where they are used. 
- PCL binder extended to allow for nested components
- Dotnet program-gen implements nested components 
Fixes #12416

[nodejs/program-gen] Component resource implementation 

---

scripts/get-job-matrix.py

Node v19.8.1 was just released with the upstream fix for the internal assert we were hitting. This change unpins us back to 19.x.
Fixes #12434

Unpin Node back to 19.x

---

changelog/pending/20230314--programgen--pcl-program-sourcefiles-returns-the-full-directory-tree-of-files.yaml
pkg/cmd/pulumi/convert.go
pkg/codegen/pcl/binder_component.go
pkg/codegen/pcl/binder_test.go
pkg/codegen/pcl/program.go
pkg/go.mod
pkg/go.sum
tests/go.mod
tests/go.sum

Implements `Program.WriteSource(fileSystem)` which is a function that writes out not just the root program files but also the files of sub programs defined by PCL components. 
Fixes #12427

PCL program.WriteSource(afero.Fs) implementation and usage in pulumi convert

---

changelog/pending/20230316--programgen-python--fix-handling-of-reserved-words-in-imports.yaml
pkg/codegen/python/gen_program.go
pkg/codegen/testing/test/program_driver.go
pkg/codegen/testing/test/testdata/lambda-0.1.0.json
pkg/codegen/testing/test/testdata/python-reserved-pp/python-reserved.pp
pkg/codegen/testing/test/testdata/python-reserved-pp/python/python-reserved.py
pkg/codegen/testing/utils/host.go

Part of https://github.com/pulumi/pulumi-terraform-bridge/issues/896
Adds a test that reserved words in schemas and PCL are handled correctly by python codegen.

Escape import names for python

---

pkg/backend/filestate/backend.go
pkg/backend/filestate/backend_test.go
pkg/backend/filestate/lock.go
pkg/backend/filestate/snapshot.go
pkg/backend/filestate/stack.go
pkg/backend/filestate/state.go
pkg/resource/stack/checkpoint.go

filestate backend currently operates exclusively with stack names.
All its internal pass around just the stack name, and nothing else.
This makes it a bit difficult to add project support to the backend.
This is a refactor in advance of adding project support,
changing the internals of filestate to pass a stack reference around.
It inspects the reference directly for all its operations.
Note: This contains no behavioral changes.
Name and FullyQualifiedName currently both return just the stack name.
In a future change, once project name is incorporated into the object,
FullyQualifiedName will be able to return `organization/$project/$name`.
Change extracted from #12134

filestate/internal: Use stack reference, not name

---

pkg/codegen/pcl/binder.go
pkg/codegen/pcl/binder_component.go

Fields of `ComponentProgramBinderArgs` were internal to the `pcl` package and could not use them in the bridge, this fixes it.

[pcl/binder] Export fields from component binder args

---

pkg/backend/filestate/backend.go
pkg/backend/filestate/backend_test.go
pkg/backend/filestate/state.go
pkg/backend/filestate/store.go
pkg/backend/filestate/store_test.go

Adds a referenceStore abstraction to control the layout of the storage,
and a legacyReferenceStore implementation based on the current layout
(that does not support projects).
This allows us to move code to determine file paths of stacks, their
histories, and their backups, all into a single component that we can
swap out for project support.
localBackendReferences keep track of the referenceStore that built them.
The primary reason for this is that when we add support for migrating a
stack state from legacy to project mode, `backend.store` will become
mutable.
For references created before the store for a backend was changed, we
still need to be able to access their original file paths, so we need to
hold onto the original referenceStore.
However, as a side-effect of this,
it's more …

filestate: Introduce referenceStore to control layout
